// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import CoreGraphics
import Foundation
import ImageIO

/// What one poll saw on the pasteboard: counts and type names only, so the
/// decision to touch an image is made before any image data is read. Size
/// limits are enforced once the data is in hand (file size before a file is
/// read, bytes and pixels before a bitmap is decoded).
struct PasteboardImageSnapshot: Equatable {
    let changeCount: Int
    let itemCount: Int
    let types: [String]
    let fileURLs: [URL]
}

/// The rules of the clipboard image optimizer, kept apart from the service so
/// the harness pins them without a pasteboard.
enum ClipboardImageOptimizerSupport {
    static let maxBytes = 20 * 1024 * 1024
    static let maxPixels = 100_000_000
    static let minimumSaving = 0.05
    static let maxDimensionChoices = [0, 1600, 2560, 3840]
    static let defaultQuality = 0.8

    enum Source: Equatable {
        case bitmap(type: String)
        /// A PNG, JPEG or TIFF file, written back as image data.
        case file(URL, uti: String)
        /// A HEIC, WebP, AVIF or BMP file, turned into a JPEG or PNG file.
        case convertedImage(URL, uti: String)
        case video(URL)
        case pdf(URL)

        var usesOutputFile: Bool {
            switch self {
            case .bitmap, .file: return false
            case .convertedImage, .video, .pdf: return true
            }
        }
    }

    enum SkipReason: Equatable {
        case ownWrite, sensitive, multipleItems, notImage, otherRepresentations, filesDisabled, tooLarge,
             kindDisabled
    }

    /// Which kinds of copy the optimizer may touch.
    struct Scope: Equatable {
        var images: Bool
        var imageFiles: Bool
        var convertImages: Bool
        var videos: Bool
        var pdfs: Bool
        /// Where optimized files live; a copy of one of them is never redone.
        var outputRoot: URL?

        static func fromDefaults(_ defaults: UserDefaults = .standard, outputRoot: URL?) -> Scope {
            Scope(images: defaults.bool(forKey: DefaultsKey.clipboardOptimizerImages),
                  imageFiles: defaults.bool(forKey: DefaultsKey.clipboardImageOptimizerIncludeFiles),
                  convertImages: defaults.bool(forKey: DefaultsKey.clipboardOptimizerConvertImages),
                  videos: defaults.bool(forKey: DefaultsKey.clipboardOptimizerVideos),
                  pdfs: defaults.bool(forKey: DefaultsKey.clipboardOptimizerPDFs),
                  outputRoot: outputRoot)
        }

        /// Whether the poll needs the file URLs at all.
        var readsFiles: Bool { (images && imageFiles) || videos || pdfs }

        func allows(_ source: Source) -> Bool {
            switch source {
            case .bitmap, .file: return images
            case .convertedImage: return images && convertImages
            case .video: return videos
            case .pdf: return pdfs
            }
        }
    }

    enum Eligibility: Equatable {
        case eligible(Source)
        case skip(SkipReason)
    }

    /// Marks an app puts on content that must be left exactly as it is: a
    /// secret, something about to be put back, or something generated.
    static let untouchableTypes: Set<String> = [
        ClipboardHistorySensitiveText.concealedPasteboardType,
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    /// Every name a lone bitmap can travel under. Anything else next to the
    /// image (HTML, a link, rich text) would be lost by a rewrite, so its
    /// presence leaves the copy alone.
    static let pngTypes: Set<String> = ["public.png", "Apple PNG pasteboard type"]
    static let tiffTypes: Set<String> = [
        "public.tiff", "NSTIFFPboardType", "NeXT TIFF v4.0 pasteboard type",
    ]
    static var bitmapTypes: Set<String> { pngTypes.union(tiffTypes) }

    static let fileURLType = "public.file-url"

    static func fileUTI(for url: URL) -> String? {
        switch url.pathExtension.lowercased() {
        case "png": return "public.png"
        case "jpg", "jpeg": return "public.jpeg"
        case "tif", "tiff": return "public.tiff"
        default: return nil
        }
    }

    static func isTooLarge(bytes: Int?, pixels: Int?) -> Bool {
        (bytes ?? 0) > maxBytes || (pixels ?? 0) > maxPixels
    }

    /// The image-only entry point from before videos and PDFs.
    static func eligibility(_ snapshot: PasteboardImageSnapshot,
                            lastOwnWrite: Int?,
                            includeFiles: Bool) -> Eligibility {
        eligibility(snapshot, lastOwnWrite: lastOwnWrite,
                    scope: Scope(images: true, imageFiles: includeFiles, convertImages: false,
                                 videos: false, pdfs: false, outputRoot: nil))
    }

    static func eligibility(_ snapshot: PasteboardImageSnapshot,
                            lastOwnWrite: Int?,
                            scope: Scope) -> Eligibility {
        if let lastOwnWrite, lastOwnWrite == snapshot.changeCount { return .skip(.ownWrite) }
        if snapshot.types.contains(where: untouchableTypes.contains) { return .skip(.sensitive) }
        if snapshot.itemCount > 1 || snapshot.fileURLs.count > 1 { return .skip(.multipleItems) }
        guard snapshot.itemCount == 1, !snapshot.types.isEmpty else { return .skip(.notImage) }

        if let url = snapshot.fileURLs.first {
            if let root = scope.outputRoot, ClipboardOptimizerFileSupport.isOwnOutput(url, root: root) {
                return .skip(.ownWrite)
            }
            let source: Source
            if let uti = fileUTI(for: url) {
                source = .file(url, uti: uti)
            } else if let uti = ClipboardOptimizerFileSupport.convertibleImageUTI(for: url) {
                source = .convertedImage(url, uti: uti)
            } else if ClipboardOptimizerFileSupport.isVideo(url) {
                source = .video(url)
            } else if ClipboardOptimizerFileSupport.isPDF(url) {
                source = .pdf(url)
            } else {
                return .skip(.notImage)
            }
            switch source {
            case .file, .convertedImage:
                guard scope.images else { return .skip(.kindDisabled) }
                guard scope.imageFiles else { return .skip(.filesDisabled) }
            default:
                break
            }
            return scope.allows(source) ? .eligible(source) : .skip(.kindDisabled)
        }

        guard scope.images else {
            return Set(snapshot.types).isDisjoint(with: bitmapTypes) ? .skip(.notImage) : .skip(.kindDisabled)
        }
        let types = Set(snapshot.types)
        guard !types.isDisjoint(with: bitmapTypes) else { return .skip(.notImage) }
        guard types.isSubset(of: bitmapTypes) else { return .skip(.otherRepresentations) }
        if let png = snapshot.types.first(where: pngTypes.contains) { return .eligible(.bitmap(type: png)) }
        return .eligible(.bitmap(type: snapshot.types.first(where: tiffTypes.contains)!))
    }

    /// A rewrite has to be worth it: at least `minSaving` of the original.
    static func shouldReplace(originalBytes: Int, encodedBytes: Int, minSaving: Double = minimumSaving) -> Bool {
        guard originalBytes > 0, encodedBytes > 0, encodedBytes < originalBytes else { return false }
        return Double(originalBytes - encodedBytes) / Double(originalBytes) >= minSaving
    }

    enum FormatPolicy: String, CaseIterable {
        case keep, jpeg
    }

    struct Options: Equatable {
        var format: FormatPolicy
        var quality: Double
        var maxDimension: Int
        var halveRetina: Bool
        var includeFiles: Bool

        static func sanitized(format: String?, quality: Double?, maxDimension: Int?,
                              halveRetina: Bool, includeFiles: Bool) -> Options {
            Options(format: format.flatMap(FormatPolicy.init(rawValue:)) ?? .keep,
                    quality: min(1, max(0.1, quality ?? ClipboardImageOptimizerSupport.defaultQuality)),
                    maxDimension: ClipboardImageOptimizerSupport.maxDimensionChoices
                        .contains(maxDimension ?? 0) ? (maxDimension ?? 0) : 0,
                    halveRetina: halveRetina,
                    includeFiles: includeFiles)
        }

        static func fromDefaults(_ defaults: UserDefaults = .standard) -> Options {
            sanitized(format: defaults.string(forKey: DefaultsKey.clipboardImageOptimizerFormat),
                      quality: defaults.object(forKey: DefaultsKey.clipboardImageOptimizerQuality) as? Double,
                      maxDimension: defaults.object(forKey: DefaultsKey.clipboardImageOptimizerMaxDimension) as? Int,
                      halveRetina: defaults.bool(forKey: DefaultsKey.clipboardImageOptimizerHalveRetina),
                      includeFiles: defaults.bool(forKey: DefaultsKey.clipboardImageOptimizerIncludeFiles))
        }
    }

    struct Plan: Equatable {
        let outputType: String
        /// Lossy quality, nil for lossless output.
        let quality: Double?
        /// The long edge to decode at, nil to keep the full size.
        let maxPixel: Int?
    }

    static func plan(_ options: Options, sourceType: String, hasAlpha: Bool, width: Int, height: Int) -> Plan {
        let wantsJPEG = sourceType == "public.jpeg" || (options.format == .jpeg && !hasAlpha)
        let longEdge = max(width, height)
        var target = longEdge
        if options.halveRetina { target = max(1, target / 2) }
        if options.maxDimension > 0 { target = min(target, options.maxDimension) }
        return Plan(outputType: wantsJPEG ? "public.jpeg" : "public.png",
                    quality: wantsJPEG ? options.quality : nil,
                    maxPixel: target < longEdge ? target : nil)
    }
}

/// The last gate before a result is written back: the feature is still on,
/// nothing reconfigured it meanwhile, and nobody copied something newer.
enum OptimizationCommit {
    static func accepts(generation: Int, current: Int, enabled: Bool, kindEnabled: Bool = true,
                        pasteboardChangeCount: Int, snapshotChangeCount: Int) -> Bool {
        generation == current && enabled && kindEnabled && pasteboardChangeCount == snapshotChangeCount
    }
}

/// Decode, plan and encode, with no pasteboard involved.
enum ClipboardImageOptimizerEncoding {
    struct Output: Equatable {
        let data: Data
        let type: String
    }

    static func optimize(data: Data,
                         sourceType: String,
                         options: ClipboardImageOptimizerSupport.Options,
                         isCancelled: () -> Bool) -> Output? {
        guard !isCancelled(), let info = MediaImageEncoder.imageInfo(data),
              !ClipboardImageOptimizerSupport.isTooLarge(bytes: data.count, pixels: info.width * info.height),
              !leavesAlone(data)
        else { return nil }
        let plan = ClipboardImageOptimizerSupport.plan(options, sourceType: sourceType, hasAlpha: info.hasAlpha,
                                                       width: info.width, height: info.height)
        return autoreleasepool { () -> Output? in
            guard !isCancelled(), let image = MediaImageEncoder.decode(
                      data, maxPixel: plan.maxPixel ?? max(info.width, info.height)),
                  !isCancelled(),
                  let encoded = MediaImageEncoder.encode(
                      image, type: plan.outputType, quality: plan.quality,
                      properties: resolution(info.dpi, scale: Double(max(image.width, image.height))
                                                 / Double(max(info.width, info.height, 1)))),
                  !isCancelled(),
                  ClipboardImageOptimizerSupport.shouldReplace(originalBytes: data.count,
                                                               encodedBytes: encoded.count)
            else { return nil }
            return Output(data: encoded, type: plan.outputType)
        }
    }

    /// Animations, HDR, deep color and gain or depth maps would not survive
    /// an 8-bit PNG or JPEG.
    static func leavesAlone(_ data: Data) -> Bool {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let traits = ClipboardOptimizerFileSupport.ImageTraits.read(source) else { return true }
        return traits.leavesAlone
    }

    struct Converted: Equatable {
        let data: Data
        let type: String
        let longEdge: Int
    }

    /// Turns a still HEIC, WebP, AVIF or BMP into a JPEG, or a PNG when it
    /// has transparency. Unlike `optimize` it always yields a file when it
    /// can, since the point is a format every app opens.
    static func convert(data: Data,
                        options: ClipboardImageOptimizerSupport.Options,
                        isCancelled: () -> Bool) -> Converted? {
        guard !isCancelled(), let info = MediaImageEncoder.imageInfo(data),
              !ClipboardImageOptimizerSupport.isTooLarge(bytes: data.count, pixels: info.width * info.height),
              !leavesAlone(data)
        else { return nil }
        var jpegOptions = options
        jpegOptions.format = .jpeg
        let plan = ClipboardImageOptimizerSupport.plan(jpegOptions, sourceType: "public.image",
                                                       hasAlpha: info.hasAlpha, width: info.width,
                                                       height: info.height)
        return autoreleasepool { () -> Converted? in
            guard !isCancelled(), let image = MediaImageEncoder.decode(
                      data, maxPixel: plan.maxPixel ?? max(info.width, info.height)),
                  !isCancelled(),
                  let encoded = MediaImageEncoder.encode(
                      image, type: plan.outputType, quality: plan.quality,
                      properties: resolution(info.dpi, scale: Double(max(image.width, image.height))
                                                 / Double(max(info.width, info.height, 1)))),
                  !isCancelled()
            else { return nil }
            return Converted(data: encoded, type: plan.outputType, longEdge: max(image.width, image.height))
        }
    }

    /// Only the resolution survives the metadata strip: without it a 144 dpi
    /// Retina capture pastes at twice its size. A downscale lowers it by the
    /// same ratio, so the image keeps its size on paste.
    static func resolution(_ dpi: Double?, scale: Double) -> [CFString: Any] {
        guard let dpi, dpi > 0 else { return [:] }
        let scaled = (dpi * scale).rounded()
        return [kCGImagePropertyDPIWidth: scaled, kCGImagePropertyDPIHeight: scaled]
    }
}
