// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import CoreGraphics
import Foundation
import ImageIO
import UniformTypeIdentifiers

enum ClipboardImageOptimizerTests {
    typealias Support = ClipboardImageOptimizerSupport

    static func snapshot(changeCount: Int = 7,
                         itemCount: Int = 1,
                         types: [String] = ["public.png"],
                         fileURLs: [URL] = []) -> PasteboardImageSnapshot {
        PasteboardImageSnapshot(changeCount: changeCount, itemCount: itemCount, types: types,
                                fileURLs: fileURLs)
    }

    static func run(_ suite: TestSuite) {
        eligibility(suite)
        savings(suite)
        options(suite)
        commitGate(suite)
        autoClear(suite)
        catalog(suite)
        encoder(suite)
    }

    static func eligibility(_ suite: TestSuite) {
        func check(_ snap: PasteboardImageSnapshot, lastOwnWrite: Int? = nil, includeFiles: Bool = false,
                   _ expected: Support.Eligibility, _ label: String) {
            let actual = Support.eligibility(snap, lastOwnWrite: lastOwnWrite, includeFiles: includeFiles)
            suite.expect(actual == expected, "\(label): got \(actual)")
        }
        check(snapshot(), .eligible(.bitmap(type: "public.png")), "a lone PNG is optimized")
        check(snapshot(types: ["public.tiff"]), .eligible(.bitmap(type: "public.tiff")), "a lone TIFF is optimized")
        check(snapshot(types: ["public.tiff", "NSTIFFPboardType", "public.png", "Apple PNG pasteboard type"]),
              .eligible(.bitmap(type: "public.png")), "PNG is preferred and legacy aliases are allowed")
        check(snapshot(), lastOwnWrite: 7, .skip(.ownWrite), "our own rewrite is never optimized again")
        check(snapshot(types: ["public.png", "org.nspasteboard.ConcealedType"]), .skip(.sensitive),
              "a concealed image is left alone")
        check(snapshot(types: ["public.png", "org.nspasteboard.TransientType"]), .skip(.sensitive),
              "a transient image is left alone")
        check(snapshot(types: ["public.png", "org.nspasteboard.AutoGeneratedType"]), .skip(.sensitive),
              "an auto generated image is left alone")
        check(snapshot(itemCount: 2), .skip(.multipleItems), "several items are left alone")
        check(snapshot(itemCount: 0, types: []), .skip(.notImage), "an empty pasteboard is left alone")
        check(snapshot(types: ["public.png", "public.html"]), .skip(.otherRepresentations),
              "a browser copy carrying HTML is never stripped of it")
        check(snapshot(types: ["public.tiff", "public.rtf"]), .skip(.otherRepresentations),
              "rich text next to an image is kept")
        check(snapshot(types: ["public.utf8-plain-text"]), .skip(.notImage), "text is not an image")
        check(snapshot(types: ["com.compuserve.gif"]), .skip(.notImage), "GIF is unsupported")
        check(snapshot(types: ["public.heic"]), .skip(.notImage), "HEIC is unsupported")
        check(snapshot(types: ["com.adobe.pdf"]), .skip(.notImage), "PDF is unsupported")
        suite.expect(Support.isTooLarge(bytes: Support.maxBytes + 1, pixels: nil), "more than 20 MB is too large")
        suite.expect(Support.isTooLarge(bytes: nil, pixels: Support.maxPixels + 1), "more than 100 MP is too large")
        suite.expect(!Support.isTooLarge(bytes: Support.maxBytes, pixels: Support.maxPixels),
                     "the limits themselves are allowed")
        check(snapshot(types: ["public.png", "Apple PNG pasteboard type", "public.tiff",
                               "NeXT TIFF v4.0 pasteboard type"]),
              .eligible(.bitmap(type: "public.png")), "a PNG written by setData(.png) is optimized")
        check(snapshot(types: ["public.png", "Apple PNG pasteboard type"]),
              .eligible(.bitmap(type: "public.png")), "a screenshot-style PNG copy is optimized")
        check(snapshot(types: ["public.tiff", "NeXT TIFF v4.0 pasteboard type"]),
              .eligible(.bitmap(type: "public.tiff")), "a TIFF with its legacy alias is optimized")

        let png = URL(fileURLWithPath: "/tmp/Shot.PNG")
        let fileTypes = ["public.file-url", "public.utf8-plain-text", "com.apple.icns", "public.tiff"]
        check(snapshot(types: fileTypes, fileURLs: [png]), .skip(.filesDisabled),
              "copied files stay alone by default")
        check(snapshot(types: fileTypes, fileURLs: [png]), includeFiles: true,
              .eligible(.file(png, uti: "public.png")), "a copied PNG file is optimized when files are on")
        let jpeg = URL(fileURLWithPath: "/tmp/photo.jpeg")
        check(snapshot(types: fileTypes, fileURLs: [jpeg]), includeFiles: true,
              .eligible(.file(jpeg, uti: "public.jpeg")), "a copied JPEG file is optimized when files are on")
        check(snapshot(types: fileTypes, fileURLs: [URL(fileURLWithPath: "/tmp/a.gif")]), includeFiles: true,
              .skip(.notImage), "a copied GIF file is unsupported")
        check(snapshot(types: fileTypes, fileURLs: [URL(fileURLWithPath: "/tmp/a.heic")]), includeFiles: true,
              .skip(.kindDisabled), "a copied HEIC file waits for conversion to be turned on")
        check(snapshot(itemCount: 2, types: fileTypes, fileURLs: [png, jpeg]), includeFiles: true,
              .skip(.multipleItems), "several copied files are left alone")
    }

    static func savings(_ suite: TestSuite) {
        suite.expect(!Support.shouldReplace(originalBytes: 0, encodedBytes: 0), "nothing to save from nothing")
        suite.expect(!Support.shouldReplace(originalBytes: 100, encodedBytes: 100), "same size is not replaced")
        suite.expect(!Support.shouldReplace(originalBytes: 100, encodedBytes: 120), "bigger output is not replaced")
        suite.expect(!Support.shouldReplace(originalBytes: 100, encodedBytes: 96), "4% saving is below the threshold")
        suite.expect(Support.shouldReplace(originalBytes: 100, encodedBytes: 95), "5% saving is replaced")
        suite.expect(!Support.shouldReplace(originalBytes: 100, encodedBytes: 0), "an empty encode is never used")
        suite.expect(Support.shouldReplace(originalBytes: 1_000, encodedBytes: 500, minSaving: 0.5),
                     "the threshold is configurable")
    }

    static func options(_ suite: TestSuite) {
        let defaults = Support.Options.sanitized(format: nil, quality: nil, maxDimension: nil,
                                                 halveRetina: false, includeFiles: false)
        suite.expect(defaults.format == .keep && defaults.quality == 0.8 && defaults.maxDimension == 0,
                     "defaults keep the format, lossless, full size")
        let odd = Support.Options.sanitized(format: "webp", quality: 9, maxDimension: 1234,
                                            halveRetina: true, includeFiles: true)
        suite.expect(odd.format == .keep && odd.quality == 1 && odd.maxDimension == 0
                        && odd.halveRetina && odd.includeFiles,
                     "unknown values fall back to safe choices")
        suite.expect(Support.Options.sanitized(format: "jpeg", quality: 0, maxDimension: 2560,
                                               halveRetina: false, includeFiles: false)
                        == Support.Options(format: .jpeg, quality: 0.1, maxDimension: 2560,
                                           halveRetina: false, includeFiles: false),
                     "quality is clamped and a listed dimension is kept")

        let keep = defaults
        suite.expect(Support.plan(keep, sourceType: "public.png", hasAlpha: true, width: 1600, height: 1000)
                        == Support.Plan(outputType: "public.png", quality: nil, maxPixel: nil),
                     "PNG stays PNG at full size")
        suite.expect(Support.plan(keep, sourceType: "public.tiff", hasAlpha: false, width: 10, height: 10).outputType
                        == "public.png", "TIFF becomes PNG")
        suite.expect(Support.plan(keep, sourceType: "public.jpeg", hasAlpha: false, width: 10, height: 10)
                        == Support.Plan(outputType: "public.jpeg", quality: 0.8, maxPixel: nil),
                     "a JPEG file stays JPEG")
        var jpeg = keep
        jpeg.format = .jpeg
        suite.expect(Support.plan(jpeg, sourceType: "public.png", hasAlpha: false, width: 10, height: 10)
                        == Support.Plan(outputType: "public.jpeg", quality: 0.8, maxPixel: nil),
                     "an opaque image becomes JPEG when asked")
        suite.expect(Support.plan(jpeg, sourceType: "public.png", hasAlpha: true, width: 10, height: 10).outputType
                        == "public.png", "an image with alpha keeps PNG instead of losing transparency")
        var halve = keep
        halve.halveRetina = true
        suite.expect(Support.plan(halve, sourceType: "public.png", hasAlpha: true, width: 1600, height: 1000).maxPixel
                        == 800, "halving Retina halves the long edge")
        var capped = halve
        capped.maxDimension = 1600
        suite.expect(Support.plan(capped, sourceType: "public.png", hasAlpha: true, width: 5000, height: 1000).maxPixel
                        == 1600, "the maximum dimension caps the halved size")
        capped.halveRetina = false
        suite.expect(Support.plan(capped, sourceType: "public.png", hasAlpha: true, width: 1000, height: 800).maxPixel
                        == nil, "a small image is never enlarged")
    }

    static func commitGate(_ suite: TestSuite) {
        suite.expect(OptimizationCommit.accepts(generation: 3, current: 3, enabled: true,
                                                pasteboardChangeCount: 9, snapshotChangeCount: 9),
                     "a current result on an unchanged pasteboard is written")
        suite.expect(!OptimizationCommit.accepts(generation: 3, current: 3, enabled: false,
                                                 pasteboardChangeCount: 9, snapshotChangeCount: 9),
                     "turning the feature off drops the result")
        suite.expect(!OptimizationCommit.accepts(generation: 2, current: 3, enabled: true,
                                                 pasteboardChangeCount: 9, snapshotChangeCount: 9),
                     "a stale generation drops the result")
        suite.expect(!OptimizationCommit.accepts(generation: 3, current: 3, enabled: true,
                                                 pasteboardChangeCount: 10, snapshotChangeCount: 9),
                     "a newer copy is never overwritten")
    }

    static func autoClear(_ suite: TestSuite) {
        suite.expect(ClipboardAutoClearSupport.changeCountAfterOwnRewrite(lastChangeCount: 5, from: 5, to: 6) == 6,
                     "our rewrite of the content auto clear is timing keeps its countdown")
        suite.expect(ClipboardAutoClearSupport.changeCountAfterOwnRewrite(lastChangeCount: 4, from: 5, to: 6) == 4,
                     "a rewrite of content auto clear has not seen yet is left to the normal poll")
        suite.expect(ClipboardAutoClearSupport.decide(changeCount: 6, lastChangeCount: 6, lastClearedChangeCount: -1,
                                                      lastChangeDate: Date(timeIntervalSince1970: 0),
                                                      now: Date(timeIntervalSince1970: 30), delay: 20) == .clear,
                     "after the rewrite the original copy time still decides the clear")
    }

    static func catalog(_ suite: TestSuite) {
        let feature = AppFeature.clipboardImageOptimizer
        suite.expect(feature.group == .clipboardFiles && feature.permissions.isEmpty
                        && feature.enabledKeys == [DefaultsKey.clipboardImageOptimizerEnabled]
                        && !feature.installedByDefault,
                     "the image optimizer is an opt-in clipboard feature with no permissions")
        let registered = Defaults.registeredDefaults
        suite.expect(registered[DefaultsKey.clipboardImageOptimizerEnabled] as? Bool == false
                        && registered[DefaultsKey.clipboardImageOptimizerFormat] as? String == "keep"
                        && registered[DefaultsKey.clipboardImageOptimizerQuality] as? Double == 0.8
                        && registered[DefaultsKey.clipboardImageOptimizerMaxDimension] as? Int == 0
                        && registered[DefaultsKey.clipboardImageOptimizerHalveRetina] as? Bool == false
                        && registered[DefaultsKey.clipboardImageOptimizerIncludeFiles] as? Bool == false,
                     "image optimizer defaults are lossless and off")
        let keys = [DefaultsKey.clipboardImageOptimizerEnabled, DefaultsKey.clipboardImageOptimizerFormat,
                    DefaultsKey.clipboardImageOptimizerQuality, DefaultsKey.clipboardImageOptimizerMaxDimension,
                    DefaultsKey.clipboardImageOptimizerHalveRetina, DefaultsKey.clipboardImageOptimizerIncludeFiles]
        suite.expect(keys.allSatisfy(SettingsBackupSupport.exportKeys().contains),
                     "image optimizer preferences travel in Settings backups")
        suite.expect(feature.settingsDestination
                        == FeatureSettingsDestination(.clipboard, sectionAnchor: .clipboardImageOptimizer),
                     "the image optimizer opens at its section of the clipboard page")
        suite.expect(ClipboardImageOptimizerStrings.enUS.caption.contains("Keep"),
                     "the lossless promise is scoped to the Keep format")
        for language in AppLanguage.allCases where language != .enUS {
            let strings = ClipboardImageOptimizerStrings.localized(language)
            suite.expect(strings.title != ClipboardImageOptimizerStrings.enUS.title,
                         "image optimizer title is translated in \(language.rawValue)")
        }
    }

    static func encoder(_ suite: TestSuite) {
        // A flat synthetic picture stored as uncompressed TIFF, the way a
        // screenshot often sits on the pasteboard.
        let width = 400, height = 300
        guard let context = CGContext(data: nil, width: width, height: height, bitsPerComponent: 8,
                                      bytesPerRow: 0, space: CGColorSpaceCreateDeviceRGB(),
                                      bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue) else {
            suite.expect(false, "test context")
            return
        }
        context.setFillColor(CGColor(red: 0.2, green: 0.4, blue: 0.8, alpha: 1))
        context.fill(CGRect(x: 0, y: 0, width: width, height: height))
        context.setFillColor(CGColor(red: 1, green: 1, blue: 1, alpha: 1))
        context.fill(CGRect(x: 40, y: 40, width: 120, height: 60))
        guard let image = context.makeImage(),
              let tiff = MediaImageEncoder.encode(image, type: UTType.tiff.identifier, quality: nil) else {
            suite.expect(false, "synthetic TIFF encodes")
            return
        }
        let info = MediaImageEncoder.imageInfo(tiff)
        suite.expect(info?.width == width && info?.height == height, "image info reads the pixel size")
        let result = ClipboardImageOptimizerEncoding.optimize(data: tiff, sourceType: "public.tiff",
                                                              options: .sanitized(format: nil, quality: nil,
                                                                                  maxDimension: nil,
                                                                                  halveRetina: false,
                                                                                  includeFiles: false),
                                                              isCancelled: { false })
        suite.expect(result?.type == "public.png" && (result?.data.count ?? .max) < tiff.count,
                     "a TIFF is re-encoded as a smaller PNG")
        let halved = ClipboardImageOptimizerEncoding.optimize(data: tiff, sourceType: "public.tiff",
                                                              options: .sanitized(format: nil, quality: nil,
                                                                                  maxDimension: nil,
                                                                                  halveRetina: true,
                                                                                  includeFiles: false),
                                                              isCancelled: { false })
        let halvedInfo = halved.flatMap { MediaImageEncoder.imageInfo($0.data) }
        suite.expect(halvedInfo?.width == 200 && halvedInfo?.height == 150, "halving Retina halves the pixels")
        // A Retina screenshot says 144 dpi; losing that pastes it at twice the size.
        let retina = MediaImageEncoder.encode(image, type: UTType.tiff.identifier, quality: nil,
                                              properties: [kCGImagePropertyDPIWidth: 144,
                                                           kCGImagePropertyDPIHeight: 144])!
        suite.expect(MediaImageEncoder.imageInfo(retina)?.dpi == 144, "image info reads the resolution")
        let keptDPI = ClipboardImageOptimizerEncoding.optimize(
            data: retina, sourceType: "public.tiff",
            options: .sanitized(format: nil, quality: nil, maxDimension: nil, halveRetina: false, includeFiles: false),
            isCancelled: { false }).flatMap { MediaImageEncoder.imageInfo($0.data) }
        suite.expect(keptDPI?.dpi == 144, "a lossless rewrite keeps the resolution, got \(String(describing: keptDPI?.dpi))")
        let halvedDPI = ClipboardImageOptimizerEncoding.optimize(
            data: retina, sourceType: "public.tiff",
            options: .sanitized(format: nil, quality: nil, maxDimension: nil, halveRetina: true, includeFiles: false),
            isCancelled: { false }).flatMap { MediaImageEncoder.imageInfo($0.data) }
        suite.expect(halvedDPI?.dpi == 72 && halvedDPI?.width == 200,
                     "halving scales the resolution so the paste keeps its size, got \(String(describing: halvedDPI?.dpi))")
        suite.expect(ClipboardImageOptimizerEncoding.optimize(data: tiff, sourceType: "public.tiff",
                                                              options: .sanitized(format: nil, quality: nil,
                                                                                  maxDimension: nil,
                                                                                  halveRetina: false,
                                                                                  includeFiles: false),
                                                              isCancelled: { true }) == nil,
                     "a cancelled encode produces nothing")
    }
}
