// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct BreakReminderStrings {
    let featureTitle: String
    let featureCaption: String
    let eyesSection: String
    let movementSection: String
    let scheduleSection: String
    let enabled: String
    let interval: String          // e.g. "Every"
    let breakLength: String
    let deliveryStyle: String
    let styleNotch: String
    let styleNotification: String
    let styleEscalating: String
    let styleOverlay: String
    let escalateAfter: String
    let workingHours: String
    let workingHoursCaption: String
    let activities: String
    let addActivity: String
    let done: String
    let snooze: String
    let skip: String
    let pauseMenu: String
    let pauseHour: String
    let pauseTomorrow: String
    let resume: String
    let preview: String
    let holdOffSection: String
    let holdForMic: String
    let holdForCamera: String
    let holdForFullscreen: String
    let resetWhenAway: String
    let breathingGuide: String
    let inhale: String
    let exhale: String
    let startSound: String
    let endSound: String
    let soundNone: String
    let eyesGeneric: String
    let movementGeneric: String
    let notchToggle: String
    let defaultEyes: [String]       // texts for the seeded eyes list, in order
    let defaultMovement: [String]   // texts for the seeded movement list, in order
}

extension FeatureStrings {
    static func breakReminders(_ language: AppLanguage) -> BreakReminderStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension BreakReminderStrings {
    static let enUS = BreakReminderStrings(
        featureTitle: "Break Reminders",
        featureCaption: "Reminds you to rest your eyes and move, and waits while you’re in a call.",
        eyesSection: "Eye breaks",
        movementSection: "Movement breaks",
        scheduleSection: "Schedule",
        enabled: "Enabled",
        interval: "Every",
        breakLength: "Break length",
        deliveryStyle: "Remind with",
        styleNotch: "Notch",
        styleNotification: "Notification",
        styleEscalating: "Notch, then full screen",
        styleOverlay: "Full screen",
        escalateAfter: "Go full screen after",
        workingHours: "Only during working hours",
        workingHoursCaption: "Reminders pause outside these days and hours.",
        activities: "Activities",
        addActivity: "Add activity",
        done: "Done",
        snooze: "Snooze 5 min",
        skip: "Skip",
        pauseMenu: "Pause breaks",
        pauseHour: "For 1 hour",
        pauseTomorrow: "Until tomorrow",
        resume: "Resume breaks",
        preview: "Preview",
        holdOffSection: "Hold off",
        holdForMic: "While the microphone is in use",
        holdForCamera: "While the camera is on",
        holdForFullscreen: "While a fullscreen app is in front",
        resetWhenAway: "Restart the countdown after I step away",
        breathingGuide: "Show a breathing guide on full screen",
        inhale: "Breathe in",
        exhale: "Breathe out",
        startSound: "Sound when a break starts",
        endSound: "Sound when a break ends",
        soundNone: "None",
        eyesGeneric: "Look away from the screen",
        movementGeneric: "Get up and move",
        notchToggle: "Break reminders",
        defaultEyes: ["Look at something 20 feet away", "Close your eyes", "Blink slowly ten times"],
        defaultMovement: ["Stand up and stretch", "10 pushups", "Walk around for two minutes", "Shoulder rolls"])

    static let ptBR = BreakReminderStrings(
        featureTitle: "Lembretes de pausa",
        featureCaption: "Lembra você de descansar os olhos e se mexer, e espera enquanto você está em uma chamada.",
        eyesSection: "Pausas para os olhos",
        movementSection: "Pausas para se mexer",
        scheduleSection: "Agenda",
        enabled: "Ativado",
        interval: "A cada",
        breakLength: "Duração da pausa",
        deliveryStyle: "Lembrar com",
        styleNotch: "Notch",
        styleNotification: "Notificação",
        styleEscalating: "Notch, depois tela cheia",
        styleOverlay: "Tela cheia",
        escalateAfter: "Ir para tela cheia após",
        workingHours: "Somente em horário de trabalho",
        workingHoursCaption: "Os lembretes pausam fora destes dias e horários.",
        activities: "Atividades",
        addActivity: "Adicionar atividade",
        done: "Concluído",
        snooze: "Adiar 5 min",
        skip: "Pular",
        pauseMenu: "Pausar lembretes",
        pauseHour: "Por 1 hora",
        pauseTomorrow: "Até amanhã",
        resume: "Retomar lembretes",
        preview: "Pré-visualizar",
        holdOffSection: "Adiar",
        holdForMic: "Enquanto o microfone estiver em uso",
        holdForCamera: "Enquanto a câmera estiver ligada",
        holdForFullscreen: "Enquanto um app em tela cheia estiver na frente",
        resetWhenAway: "Reiniciar a contagem depois que eu me ausentar",
        breathingGuide: "Mostrar um guia de respiração em tela cheia",
        inhale: "Inspire",
        exhale: "Expire",
        startSound: "Som ao iniciar uma pausa",
        endSound: "Som ao terminar uma pausa",
        soundNone: "Nenhum",
        eyesGeneric: "Desvie o olhar da tela",
        movementGeneric: "Levante-se e se mexa",
        notchToggle: "Lembretes de pausa",
        defaultEyes: ["Olhe para algo a 6 metros de distância", "Feche os olhos", "Pisque devagar dez vezes"],
        defaultMovement: ["Levante-se e se alongue", "10 flexões", "Caminhe por dois minutos", "Rotação dos ombros"])

    static let tr = BreakReminderStrings(
        featureTitle: "Mola Hatırlatıcıları",
        featureCaption: "Gözlerinizi dinlendirmenizi ve hareket etmenizi hatırlatır, bir görüşmedeyken bekler.",
        eyesSection: "Göz molaları",
        movementSection: "Hareket molaları",
        scheduleSection: "Zamanlama",
        enabled: "Etkin",
        interval: "Her",
        breakLength: "Mola süresi",
        deliveryStyle: "Hatırlatma şekli",
        styleNotch: "Çentik",
        styleNotification: "Bildirim",
        styleEscalating: "Çentik, sonra tam ekran",
        styleOverlay: "Tam ekran",
        escalateAfter: "Şu süre sonra tam ekrana geç",
        workingHours: "Yalnızca çalışma saatlerinde",
        workingHoursCaption: "Hatırlatıcılar bu gün ve saatlerin dışında duraklar.",
        activities: "Etkinlikler",
        addActivity: "Etkinlik ekle",
        done: "Tamam",
        snooze: "5 dk ertele",
        skip: "Atla",
        pauseMenu: "Molaları duraklat",
        pauseHour: "1 saat boyunca",
        pauseTomorrow: "Yarına kadar",
        resume: "Molalara devam et",
        preview: "Önizle",
        holdOffSection: "Ertele",
        holdForMic: "Mikrofon kullanılırken",
        holdForCamera: "Kamera açıkken",
        holdForFullscreen: "Tam ekran bir uygulama öndeyken",
        resetWhenAway: "Uzaklaştığımda geri sayımı yeniden başlat",
        breathingGuide: "Tam ekranda nefes rehberi göster",
        inhale: "Nefes al",
        exhale: "Nefes ver",
        startSound: "Mola başlarken ses",
        endSound: "Mola biterken ses",
        soundNone: "Yok",
        eyesGeneric: "Ekrandan uzağa bakın",
        movementGeneric: "Kalkın ve hareket edin",
        notchToggle: "Mola hatırlatıcıları",
        defaultEyes: ["6 metre uzaktaki bir şeye bakın", "Gözlerinizi kapatın", "On kez yavaşça göz kırpın"],
        defaultMovement: ["Ayağa kalkıp gerinin", "10 şınav", "İki dakika yürüyün", "Omuz çevirme"])

    static let ru = BreakReminderStrings(
        featureTitle: "Напоминания о перерывах",
        featureCaption: "Напоминает отдохнуть глазам и подвигаться, а во время звонка ждёт.",
        eyesSection: "Перерывы для глаз",
        movementSection: "Перерывы на движение",
        scheduleSection: "Расписание",
        enabled: "Включено",
        interval: "Каждые",
        breakLength: "Длительность перерыва",
        deliveryStyle: "Напоминать через",
        styleNotch: "Нотч",
        styleNotification: "Уведомление",
        styleEscalating: "Нотч, затем полный экран",
        styleOverlay: "Полный экран",
        escalateAfter: "Переходить на полный экран через",
        workingHours: "Только в рабочие часы",
        workingHoursCaption: "Напоминания приостанавливаются вне этих дней и часов.",
        activities: "Занятия",
        addActivity: "Добавить занятие",
        done: "Готово",
        snooze: "Отложить на 5 мин",
        skip: "Пропустить",
        pauseMenu: "Приостановить перерывы",
        pauseHour: "На 1 час",
        pauseTomorrow: "До завтра",
        resume: "Возобновить перерывы",
        preview: "Предпросмотр",
        holdOffSection: "Откладывать",
        holdForMic: "Пока используется микрофон",
        holdForCamera: "Пока включена камера",
        holdForFullscreen: "Пока впереди полноэкранное приложение",
        resetWhenAway: "Перезапускать отсчёт, когда я отхожу",
        breathingGuide: "Показывать дыхательную подсказку на весь экран",
        inhale: "Вдох",
        exhale: "Выдох",
        startSound: "Звук в начале перерыва",
        endSound: "Звук в конце перерыва",
        soundNone: "Нет",
        eyesGeneric: "Отведите взгляд от экрана",
        movementGeneric: "Встаньте и подвигайтесь",
        notchToggle: "Напоминания о перерывах",
        defaultEyes: ["Посмотрите на предмет в шести метрах", "Закройте глаза", "Медленно моргните десять раз"],
        defaultMovement: ["Встаньте и потянитесь", "10 отжиманий", "Походите две минуты", "Вращения плечами"])

    static let es = BreakReminderStrings(
        featureTitle: "Recordatorios de descanso",
        featureCaption: "Te recuerda descansar la vista y moverte, y espera mientras estás en una llamada.",
        eyesSection: "Descansos para la vista",
        movementSection: "Descansos de movimiento",
        scheduleSection: "Horario",
        enabled: "Activado",
        interval: "Cada",
        breakLength: "Duración del descanso",
        deliveryStyle: "Recordar con",
        styleNotch: "Notch",
        styleNotification: "Notificación",
        styleEscalating: "Notch, luego pantalla completa",
        styleOverlay: "Pantalla completa",
        escalateAfter: "Pasar a pantalla completa tras",
        workingHours: "Solo en horario laboral",
        workingHoursCaption: "Los recordatorios se pausan fuera de estos días y horas.",
        activities: "Actividades",
        addActivity: "Añadir actividad",
        done: "Hecho",
        snooze: "Posponer 5 min",
        skip: "Omitir",
        pauseMenu: "Pausar descansos",
        pauseHour: "Durante 1 hora",
        pauseTomorrow: "Hasta mañana",
        resume: "Reanudar descansos",
        preview: "Vista previa",
        holdOffSection: "Posponer",
        holdForMic: "Mientras el micrófono esté en uso",
        holdForCamera: "Mientras la cámara esté encendida",
        holdForFullscreen: "Mientras haya una app a pantalla completa delante",
        resetWhenAway: "Reiniciar la cuenta atrás cuando me ausente",
        breathingGuide: "Mostrar una guía de respiración a pantalla completa",
        inhale: "Inhala",
        exhale: "Exhala",
        startSound: "Sonido al empezar un descanso",
        endSound: "Sonido al terminar un descanso",
        soundNone: "Ninguno",
        eyesGeneric: "Aparta la vista de la pantalla",
        movementGeneric: "Levántate y muévete",
        notchToggle: "Recordatorios de descanso",
        defaultEyes: ["Mira algo a seis metros de distancia", "Cierra los ojos", "Parpadea lentamente diez veces"],
        defaultMovement: ["Levántate y estírate", "10 flexiones", "Camina durante dos minutos", "Giros de hombros"])

    static let sk = BreakReminderStrings(
        featureTitle: "Pripomienky prestávok",
        featureCaption: "Pripomenie vám oddýchnuť si oči a pohnúť sa a počká, kým ste v hovore.",
        eyesSection: "Prestávky pre oči",
        movementSection: "Pohybové prestávky",
        scheduleSection: "Plán",
        enabled: "Zapnuté",
        interval: "Každých",
        breakLength: "Dĺžka prestávky",
        deliveryStyle: "Pripomínať cez",
        styleNotch: "Výrez",
        styleNotification: "Oznámenie",
        styleEscalating: "Výrez, potom celá obrazovka",
        styleOverlay: "Celá obrazovka",
        escalateAfter: "Prejsť na celú obrazovku po",
        workingHours: "Iba v pracovnom čase",
        workingHoursCaption: "Pripomienky sa mimo týchto dní a hodín pozastavia.",
        activities: "Aktivity",
        addActivity: "Pridať aktivitu",
        done: "Hotovo",
        snooze: "Odložiť o 5 min",
        skip: "Preskočiť",
        pauseMenu: "Pozastaviť prestávky",
        pauseHour: "Na 1 hodinu",
        pauseTomorrow: "Do zajtra",
        resume: "Obnoviť prestávky",
        preview: "Ukážka",
        holdOffSection: "Odložiť",
        holdForMic: "Kým sa používa mikrofón",
        holdForCamera: "Kým je zapnutá kamera",
        holdForFullscreen: "Kým je vpredu aplikácia na celej obrazovke",
        resetWhenAway: "Po mojom odchode spustiť odpočet odznova",
        breathingGuide: "Zobraziť dychového sprievodcu na celej obrazovke",
        inhale: "Nádych",
        exhale: "Výdych",
        startSound: "Zvuk pri začiatku prestávky",
        endSound: "Zvuk pri konci prestávky",
        soundNone: "Žiadny",
        eyesGeneric: "Odvráťte pohľad od obrazovky",
        movementGeneric: "Vstaňte a pohnite sa",
        notchToggle: "Pripomienky prestávok",
        defaultEyes: ["Pozrite sa na niečo vzdialené šesť metrov", "Zavrite oči", "Desaťkrát pomaly žmurknite"],
        defaultMovement: ["Postavte sa a natiahnite sa", "10 klikov", "Dve minúty sa prejdite", "Krúženie ramenami"])

    static let de = BreakReminderStrings(
        featureTitle: "Pausenerinnerungen",
        featureCaption: "Erinnert dich daran, die Augen auszuruhen und dich zu bewegen, und wartet, solange du in einem Gespräch bist.",
        eyesSection: "Augenpausen",
        movementSection: "Bewegungspausen",
        scheduleSection: "Zeitplan",
        enabled: "Aktiviert",
        interval: "Alle",
        breakLength: "Pausendauer",
        deliveryStyle: "Erinnern per",
        styleNotch: "Notch",
        styleNotification: "Mitteilung",
        styleEscalating: "Notch, dann Vollbild",
        styleOverlay: "Vollbild",
        escalateAfter: "Vollbild nach",
        workingHours: "Nur während der Arbeitszeit",
        workingHoursCaption: "Außerhalb dieser Tage und Zeiten pausieren die Erinnerungen.",
        activities: "Aktivitäten",
        addActivity: "Aktivität hinzufügen",
        done: "Fertig",
        snooze: "5 Min. später",
        skip: "Überspringen",
        pauseMenu: "Pausen anhalten",
        pauseHour: "Für 1 Stunde",
        pauseTomorrow: "Bis morgen",
        resume: "Pausen fortsetzen",
        preview: "Vorschau",
        holdOffSection: "Aufschieben",
        holdForMic: "Während das Mikrofon verwendet wird",
        holdForCamera: "Während die Kamera an ist",
        holdForFullscreen: "Während eine Vollbild-App vorne ist",
        resetWhenAway: "Countdown neu starten, wenn ich weg war",
        breathingGuide: "Atemhilfe im Vollbild zeigen",
        inhale: "Einatmen",
        exhale: "Ausatmen",
        startSound: "Ton zu Beginn einer Pause",
        endSound: "Ton am Ende einer Pause",
        soundNone: "Keiner",
        eyesGeneric: "Schau vom Bildschirm weg",
        movementGeneric: "Steh auf und beweg dich",
        notchToggle: "Pausenerinnerungen",
        defaultEyes: ["Schau auf etwas, das sechs Meter entfernt ist", "Schließe die Augen", "Blinzle zehnmal langsam"],
        defaultMovement: ["Steh auf und strecke dich", "10 Liegestütze", "Geh zwei Minuten umher", "Schulterkreisen"])

    static let fr = BreakReminderStrings(
        featureTitle: "Rappels de pause",
        featureCaption: "Vous rappelle de reposer vos yeux et de bouger, et patiente pendant un appel.",
        eyesSection: "Pauses pour les yeux",
        movementSection: "Pauses mouvement",
        scheduleSection: "Planning",
        enabled: "Activé",
        interval: "Toutes les",
        breakLength: "Durée de la pause",
        deliveryStyle: "Rappeler via",
        styleNotch: "Encoche",
        styleNotification: "Notification",
        styleEscalating: "Encoche, puis plein écran",
        styleOverlay: "Plein écran",
        escalateAfter: "Passer en plein écran après",
        workingHours: "Uniquement pendant les heures de travail",
        workingHoursCaption: "Les rappels sont suspendus en dehors de ces jours et heures.",
        activities: "Activités",
        addActivity: "Ajouter une activité",
        done: "Terminé",
        snooze: "Reporter de 5 min",
        skip: "Passer",
        pauseMenu: "Suspendre les pauses",
        pauseHour: "Pendant 1 heure",
        pauseTomorrow: "Jusqu’à demain",
        resume: "Reprendre les pauses",
        preview: "Aperçu",
        holdOffSection: "Différer",
        holdForMic: "Pendant que le micro est utilisé",
        holdForCamera: "Pendant que la caméra est allumée",
        holdForFullscreen: "Pendant qu’une app en plein écran est au premier plan",
        resetWhenAway: "Relancer le compte à rebours après une absence",
        breathingGuide: "Afficher un guide de respiration en plein écran",
        inhale: "Inspirez",
        exhale: "Expirez",
        startSound: "Son au début d’une pause",
        endSound: "Son à la fin d’une pause",
        soundNone: "Aucun",
        eyesGeneric: "Détournez le regard de l’écran",
        movementGeneric: "Levez-vous et bougez",
        notchToggle: "Rappels de pause",
        defaultEyes: ["Regardez quelque chose à six mètres", "Fermez les yeux", "Clignez lentement des yeux dix fois"],
        defaultMovement: ["Levez-vous et étirez-vous", "10 pompes", "Marchez pendant deux minutes", "Rotations des épaules"])

    static let it = BreakReminderStrings(
        featureTitle: "Promemoria pause",
        featureCaption: "Ti ricorda di riposare gli occhi e di muoverti, e aspetta mentre sei in una chiamata.",
        eyesSection: "Pause per gli occhi",
        movementSection: "Pause di movimento",
        scheduleSection: "Pianificazione",
        enabled: "Attivo",
        interval: "Ogni",
        breakLength: "Durata della pausa",
        deliveryStyle: "Ricorda con",
        styleNotch: "Notch",
        styleNotification: "Notifica",
        styleEscalating: "Notch, poi schermo intero",
        styleOverlay: "Schermo intero",
        escalateAfter: "Passa a schermo intero dopo",
        workingHours: "Solo in orario di lavoro",
        workingHoursCaption: "I promemoria si sospendono fuori da questi giorni e orari.",
        activities: "Attività",
        addActivity: "Aggiungi attività",
        done: "Fatto",
        snooze: "Posticipa di 5 min",
        skip: "Salta",
        pauseMenu: "Sospendi le pause",
        pauseHour: "Per 1 ora",
        pauseTomorrow: "Fino a domani",
        resume: "Riprendi le pause",
        preview: "Anteprima",
        holdOffSection: "Rimanda",
        holdForMic: "Mentre il microfono è in uso",
        holdForCamera: "Mentre la fotocamera è accesa",
        holdForFullscreen: "Mentre un’app a schermo intero è in primo piano",
        resetWhenAway: "Riavvia il conto alla rovescia dopo che mi allontano",
        breathingGuide: "Mostra una guida al respiro a schermo intero",
        inhale: "Inspira",
        exhale: "Espira",
        startSound: "Suono all’inizio di una pausa",
        endSound: "Suono alla fine di una pausa",
        soundNone: "Nessuno",
        eyesGeneric: "Distogli lo sguardo dallo schermo",
        movementGeneric: "Alzati e muoviti",
        notchToggle: "Promemoria pause",
        defaultEyes: ["Guarda qualcosa a sei metri di distanza", "Chiudi gli occhi", "Batti le palpebre lentamente dieci volte"],
        defaultMovement: ["Alzati e stiracchiati", "10 flessioni", "Cammina per due minuti", "Rotazioni delle spalle"])

    static let ja = BreakReminderStrings(
        featureTitle: "休憩リマインダー",
        featureCaption: "目を休めて体を動かすよう知らせ、通話中は待機します。",
        eyesSection: "目の休憩",
        movementSection: "体を動かす休憩",
        scheduleSection: "スケジュール",
        enabled: "有効",
        interval: "間隔",
        breakLength: "休憩の長さ",
        deliveryStyle: "通知方法",
        styleNotch: "ノッチ",
        styleNotification: "通知",
        styleEscalating: "ノッチ、その後フルスクリーン",
        styleOverlay: "フルスクリーン",
        escalateAfter: "フルスクリーンに切り替えるまで",
        workingHours: "勤務時間中のみ",
        workingHoursCaption: "これらの曜日と時間以外ではリマインダーを停止します。",
        activities: "アクティビティ",
        addActivity: "アクティビティを追加",
        done: "完了",
        snooze: "5分後に再通知",
        skip: "スキップ",
        pauseMenu: "休憩を一時停止",
        pauseHour: "1時間",
        pauseTomorrow: "明日まで",
        resume: "休憩を再開",
        preview: "プレビュー",
        holdOffSection: "保留する条件",
        holdForMic: "マイクの使用中",
        holdForCamera: "カメラのオン中",
        holdForFullscreen: "フルスクリーンのアプリが前面にある間",
        resetWhenAway: "離席したらカウントダウンをやり直す",
        breathingGuide: "フルスクリーンで呼吸ガイドを表示",
        inhale: "吸って",
        exhale: "吐いて",
        startSound: "休憩開始時のサウンド",
        endSound: "休憩終了時のサウンド",
        soundNone: "なし",
        eyesGeneric: "画面から目を離しましょう",
        movementGeneric: "立ち上がって体を動かしましょう",
        notchToggle: "休憩リマインダー",
        defaultEyes: ["6メートル先のものを見る", "目を閉じる", "ゆっくり10回まばたきする"],
        defaultMovement: ["立ち上がってストレッチする", "腕立て伏せを10回", "2分間歩き回る", "肩を回す"])

    static let ko = BreakReminderStrings(
        featureTitle: "휴식 알림",
        featureCaption: "눈을 쉬게 하고 몸을 움직이도록 알려 주며, 통화 중에는 기다립니다.",
        eyesSection: "눈 휴식",
        movementSection: "움직임 휴식",
        scheduleSection: "일정",
        enabled: "사용",
        interval: "간격",
        breakLength: "휴식 시간",
        deliveryStyle: "알림 방식",
        styleNotch: "노치",
        styleNotification: "알림",
        styleEscalating: "노치 후 전체 화면",
        styleOverlay: "전체 화면",
        escalateAfter: "전체 화면으로 전환까지",
        workingHours: "근무 시간에만",
        workingHoursCaption: "이 요일과 시간 외에는 알림이 일시 중지됩니다.",
        activities: "활동",
        addActivity: "활동 추가",
        done: "완료",
        snooze: "5분 뒤 다시 알림",
        skip: "건너뛰기",
        pauseMenu: "휴식 일시 중지",
        pauseHour: "1시간 동안",
        pauseTomorrow: "내일까지",
        resume: "휴식 다시 시작",
        preview: "미리 보기",
        holdOffSection: "미루기",
        holdForMic: "마이크 사용 중",
        holdForCamera: "카메라가 켜져 있는 동안",
        holdForFullscreen: "전체 화면 앱이 앞에 있는 동안",
        resetWhenAway: "자리를 비우면 카운트다운 다시 시작",
        breathingGuide: "전체 화면에 호흡 가이드 표시",
        inhale: "들이쉬세요",
        exhale: "내쉬세요",
        startSound: "휴식 시작 소리",
        endSound: "휴식 종료 소리",
        soundNone: "없음",
        eyesGeneric: "화면에서 눈을 떼세요",
        movementGeneric: "일어나서 몸을 움직이세요",
        notchToggle: "휴식 알림",
        defaultEyes: ["6미터 떨어진 곳을 바라보기", "눈 감기", "천천히 열 번 눈 깜빡이기"],
        defaultMovement: ["일어나서 스트레칭하기", "팔굽혀펴기 10회", "2분 동안 걸어 다니기", "어깨 돌리기"])

    static let zhHans = BreakReminderStrings(
        featureTitle: "休息提醒",
        featureCaption: "提醒你让眼睛休息、活动身体，并在你通话时等待。",
        eyesSection: "眼睛休息",
        movementSection: "活动休息",
        scheduleSection: "日程",
        enabled: "启用",
        interval: "每隔",
        breakLength: "休息时长",
        deliveryStyle: "提醒方式",
        styleNotch: "刘海",
        styleNotification: "通知",
        styleEscalating: "刘海，然后全屏",
        styleOverlay: "全屏",
        escalateAfter: "多久后切换到全屏",
        workingHours: "仅在工作时间",
        workingHoursCaption: "在这些日期和时间之外，提醒会暂停。",
        activities: "活动",
        addActivity: "添加活动",
        done: "完成",
        snooze: "推迟 5 分钟",
        skip: "跳过",
        pauseMenu: "暂停休息",
        pauseHour: "1 小时",
        pauseTomorrow: "直到明天",
        resume: "恢复休息",
        preview: "预览",
        holdOffSection: "暂缓提醒",
        holdForMic: "麦克风使用期间",
        holdForCamera: "摄像头开启期间",
        holdForFullscreen: "全屏应用在前台期间",
        resetWhenAway: "离开后重新开始倒计时",
        breathingGuide: "全屏时显示呼吸引导",
        inhale: "吸气",
        exhale: "呼气",
        startSound: "休息开始时的声音",
        endSound: "休息结束时的声音",
        soundNone: "无",
        eyesGeneric: "把视线从屏幕移开",
        movementGeneric: "站起来活动一下",
        notchToggle: "休息提醒",
        defaultEyes: ["看向六米外的东西", "闭上眼睛", "缓慢眨眼十次"],
        defaultMovement: ["站起来伸展身体", "做 10 个俯卧撑", "走动两分钟", "转动肩膀"])

    static let zhTW = BreakReminderStrings(
        featureTitle: "休息提醒",
        featureCaption: "提醒你讓眼睛休息、活動身體，並在你通話時等待。",
        eyesSection: "眼睛休息",
        movementSection: "活動休息",
        scheduleSection: "排程",
        enabled: "啟用",
        interval: "每隔",
        breakLength: "休息時間",
        deliveryStyle: "提醒方式",
        styleNotch: "瀏海",
        styleNotification: "通知",
        styleEscalating: "瀏海，然後全螢幕",
        styleOverlay: "全螢幕",
        escalateAfter: "多久後切換到全螢幕",
        workingHours: "僅在工作時間",
        workingHoursCaption: "在這些日期和時間之外，提醒會暫停。",
        activities: "活動",
        addActivity: "新增活動",
        done: "完成",
        snooze: "延後 5 分鐘",
        skip: "略過",
        pauseMenu: "暫停休息",
        pauseHour: "1 小時",
        pauseTomorrow: "直到明天",
        resume: "恢復休息",
        preview: "預覽",
        holdOffSection: "暫緩提醒",
        holdForMic: "麥克風使用期間",
        holdForCamera: "相機開啟期間",
        holdForFullscreen: "全螢幕 App 在前景期間",
        resetWhenAway: "離開後重新開始倒數",
        breathingGuide: "全螢幕時顯示呼吸引導",
        inhale: "吸氣",
        exhale: "吐氣",
        startSound: "休息開始時的聲音",
        endSound: "休息結束時的聲音",
        soundNone: "無",
        eyesGeneric: "把視線從螢幕移開",
        movementGeneric: "站起來活動一下",
        notchToggle: "休息提醒",
        defaultEyes: ["看向六公尺外的東西", "閉上眼睛", "緩慢眨眼十次"],
        defaultMovement: ["站起來伸展身體", "做 10 個伏地挺身", "走動兩分鐘", "轉動肩膀"])

    static let zhHK = BreakReminderStrings(
        featureTitle: "休息提醒",
        featureCaption: "提醒你讓眼睛休息、活動身體，並在你通話時等待。",
        eyesSection: "眼睛休息",
        movementSection: "活動休息",
        scheduleSection: "時間表",
        enabled: "啟用",
        interval: "每隔",
        breakLength: "休息時間",
        deliveryStyle: "提醒方式",
        styleNotch: "瀏海",
        styleNotification: "通知",
        styleEscalating: "瀏海，然後全螢幕",
        styleOverlay: "全螢幕",
        escalateAfter: "多久後切換到全螢幕",
        workingHours: "只在工作時間",
        workingHoursCaption: "在這些日子和時間之外，提醒會暫停。",
        activities: "活動",
        addActivity: "新增活動",
        done: "完成",
        snooze: "延後 5 分鐘",
        skip: "略過",
        pauseMenu: "暫停休息",
        pauseHour: "1 小時",
        pauseTomorrow: "直至明天",
        resume: "恢復休息",
        preview: "預覽",
        holdOffSection: "暫緩提醒",
        holdForMic: "麥克風使用期間",
        holdForCamera: "相機開啟期間",
        holdForFullscreen: "全螢幕 App 在前景期間",
        resetWhenAway: "離開後重新開始倒數",
        breathingGuide: "全螢幕時顯示呼吸引導",
        inhale: "吸氣",
        exhale: "吐氣",
        startSound: "休息開始時的聲音",
        endSound: "休息結束時的聲音",
        soundNone: "無",
        eyesGeneric: "將視線從螢幕移開",
        movementGeneric: "站起來活動一下",
        notchToggle: "休息提醒",
        defaultEyes: ["望向六米外的東西", "閉上眼睛", "慢慢眨眼十次"],
        defaultMovement: ["站起來伸展身體", "做 10 下掌上壓", "走動兩分鐘", "轉動肩膀"])

    static let uk = BreakReminderStrings(
        featureTitle: "Нагадування про перерви",
        featureCaption: "Нагадує відпочити очам і порухатися, а під час дзвінка чекає.",
        eyesSection: "Перерви для очей",
        movementSection: "Перерви на рух",
        scheduleSection: "Розклад",
        enabled: "Увімкнено",
        interval: "Кожні",
        breakLength: "Тривалість перерви",
        deliveryStyle: "Нагадувати через",
        styleNotch: "Виріз",
        styleNotification: "Сповіщення",
        styleEscalating: "Виріз, потім повний екран",
        styleOverlay: "Повний екран",
        escalateAfter: "Перейти на повний екран через",
        workingHours: "Лише в робочі години",
        workingHoursCaption: "Поза цими днями й годинами нагадування призупиняються.",
        activities: "Заняття",
        addActivity: "Додати заняття",
        done: "Готово",
        snooze: "Відкласти на 5 хв",
        skip: "Пропустити",
        pauseMenu: "Призупинити перерви",
        pauseHour: "На 1 годину",
        pauseTomorrow: "До завтра",
        resume: "Відновити перерви",
        preview: "Попередній перегляд",
        holdOffSection: "Відкладати",
        holdForMic: "Поки використовується мікрофон",
        holdForCamera: "Поки увімкнена камера",
        holdForFullscreen: "Поки попереду повноекранна програма",
        resetWhenAway: "Перезапускати відлік, коли я відходжу",
        breathingGuide: "Показувати дихальну підказку на весь екран",
        inhale: "Вдих",
        exhale: "Видих",
        startSound: "Звук на початку перерви",
        endSound: "Звук наприкінці перерви",
        soundNone: "Немає",
        eyesGeneric: "Відведіть погляд від екрана",
        movementGeneric: "Встаньте й порухайтеся",
        notchToggle: "Нагадування про перерви",
        defaultEyes: ["Подивіться на предмет за шість метрів", "Заплющте очі", "Повільно кліпніть десять разів"],
        defaultMovement: ["Встаньте й потягніться", "10 віджимань", "Походіть дві хвилини", "Обертання плечима"])
}
