// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct BrowserPickerStrings {
    let featureName: String
    let featureDescription: String
    let searchKeywords: [String]
    let statusOn: String
    let statusOff: String
    let makeDefault: String
    let restoreFormat: String
    let defaultBrowserCaption: String
    let rulesTitle: String
    let rulesCaption: String
    let noRules: String
    let addRule: String
    let editRule: String
    let deleteRule: String
    let moveUp: String
    let moveDown: String
    let ruleEnabled: String
    let ruleActions: String
    let unavailableTargetFormat: String
    let newRuleTitle: String
    let siteLabel: String
    let pathLabel: String
    let pathPlaceholder: String
    let openInLabel: String
    let chooseBrowser: String
    let siteHint: String
    let invalidSite: String
    let coversSiteFormat: String
    let coversPathFormat: String
    let linkMatches: String
    let linkDoesNotMatch: String
    let cancel: String
    let save: String
    let saveAndOpen: String
    let noBrowsers: String
    let moreLinksFormat: String
    let addRuleFromLink: String
    let copyLink: String
    let rememberHint: String
    let targetMissingFormat: String
    let openFailedFormat: String
    let profilesWithheldFormat: String
}

extension FeatureStrings {
    static func browserPicker(_ language: AppLanguage) -> BrowserPickerStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension BrowserPickerStrings {
    static let enUS = BrowserPickerStrings(
        featureName: "Browser picker",
        featureDescription: "Choose the browser or profile for each link you click, or send sites to one automatically",
        searchKeywords: ["browser", "default browser", "links", "profile", "Chrome", "rules"],
        statusOn: "Links from other apps open through Vorssaint",
        statusOff: "Vorssaint is not the default browser yet",
        makeDefault: "Set as default browser…",
        restoreFormat: "Give links back to %@",
        defaultBrowserCaption: "To see the links you click, Vorssaint becomes the default browser and passes each link to the browser you choose. macOS asks you to confirm. Giving links back, or removing this feature, makes the previous browser the default again.",
        rulesTitle: "Rules",
        rulesCaption: "A link that matches a rule opens right away, without the picker. The first matching rule wins; drag rules to change their order.",
        noRules: "No rules yet, so every link shows the picker.",
        addRule: "Add rule…",
        editRule: "Edit…",
        deleteRule: "Delete",
        moveUp: "Move up",
        moveDown: "Move down",
        ruleEnabled: "Rule on",
        ruleActions: "Rule actions",
        unavailableTargetFormat: "%@ (not available)",
        newRuleTitle: "New rule",
        siteLabel: "Site",
        pathLabel: "Only under path",
        pathPlaceholder: "Optional, such as /team",
        openInLabel: "Open in",
        chooseBrowser: "Choose…",
        siteHint: "Enter a site such as example.com. Its subdomains are included.",
        invalidSite: "This is not a site address. Enter one such as example.com.",
        coversSiteFormat: "Covers every page of %@ and its subdomains.",
        coversPathFormat: "Covers pages of %1$@ under %2$@.",
        linkMatches: "This link matches.",
        linkDoesNotMatch: "This link does not match.",
        cancel: "Cancel",
        save: "Save",
        saveAndOpen: "Save and open",
        noBrowsers: "No browsers found",
        moreLinksFormat: "%d more",
        addRuleFromLink: "Rule for this site…",
        copyLink: "Copy link",
        rememberHint: "Hold ⌥ to always open this site here",
        targetMissingFormat: "%@ is not available. Choose where to open this link.",
        openFailedFormat: "%@ could not open this link.",
        profilesWithheldFormat: "macOS did not let Vorssaint read the profiles of %@, so each appears as one browser. Allow access when macOS asks, or turn on Full Disk Access."
    )

    static let ptBR = BrowserPickerStrings(
        featureName: "Seletor de navegador",
        featureDescription: "Escolha o navegador ou perfil de cada link em que você clica, ou envie sites para um deles automaticamente",
        searchKeywords: ["navegador", "navegador padrão", "links", "perfil", "Chrome", "regras"],
        statusOn: "Links de outros apps abrem pelo Vorssaint",
        statusOff: "O Vorssaint ainda não é o navegador padrão",
        makeDefault: "Definir como navegador padrão…",
        restoreFormat: "Devolver os links ao %@",
        defaultBrowserCaption: "Para ver os links em que você clica, o Vorssaint vira o navegador padrão e passa cada link ao navegador que você escolher. O macOS pede confirmação. Ao devolver os links, ou remover este recurso, o navegador anterior volta a ser o padrão.",
        rulesTitle: "Regras",
        rulesCaption: "Um link que corresponde a uma regra abre na hora, sem o seletor. Vale a primeira regra que corresponder; arraste as regras para mudar a ordem.",
        noRules: "Ainda não há regras, então todo link mostra o seletor.",
        addRule: "Adicionar regra…",
        editRule: "Editar…",
        deleteRule: "Remover",
        moveUp: "Mover para cima",
        moveDown: "Mover para baixo",
        ruleEnabled: "Regra ativada",
        ruleActions: "Ações da regra",
        unavailableTargetFormat: "%@ (indisponível)",
        newRuleTitle: "Nova regra",
        siteLabel: "Site",
        pathLabel: "Só no caminho",
        pathPlaceholder: "Opcional, como /equipe",
        openInLabel: "Abrir em",
        chooseBrowser: "Escolher…",
        siteHint: "Digite um site como example.com. Os subdomínios dele também entram.",
        invalidSite: "Isto não é um endereço de site. Digite um como example.com.",
        coversSiteFormat: "Vale para todas as páginas de %@ e seus subdomínios.",
        coversPathFormat: "Vale para as páginas de %1$@ em %2$@.",
        linkMatches: "Este link corresponde.",
        linkDoesNotMatch: "Este link não corresponde.",
        cancel: "Cancelar",
        save: "Salvar",
        saveAndOpen: "Salvar e abrir",
        noBrowsers: "Nenhum navegador encontrado",
        moreLinksFormat: "mais %d",
        addRuleFromLink: "Regra para este site…",
        copyLink: "Copiar link",
        rememberHint: "Segure ⌥ para sempre abrir este site aqui",
        targetMissingFormat: "%@ não está disponível. Escolha onde abrir este link.",
        openFailedFormat: "%@ não conseguiu abrir este link.",
        profilesWithheldFormat: "O macOS não deixou o Vorssaint ler os perfis de %@, então cada um aparece como um só navegador. Permita o acesso quando o macOS perguntar ou ative o Acesso Total ao Disco."
    )

    static let tr = BrowserPickerStrings(
        featureName: "Tarayıcı seçici",
        featureDescription: "Tıkladığınız her bağlantı için tarayıcıyı veya profili seçin ya da siteleri otomatik olarak birine gönderin",
        searchKeywords: ["tarayıcı", "varsayılan tarayıcı", "bağlantılar", "profil", "Chrome", "kurallar"],
        statusOn: "Diğer uygulamalardaki bağlantılar Vorssaint üzerinden açılır",
        statusOff: "Vorssaint henüz varsayılan tarayıcı değil",
        makeDefault: "Varsayılan tarayıcı yap…",
        restoreFormat: "Bağlantıları %@ uygulamasına geri ver",
        defaultBrowserCaption: "Tıkladığınız bağlantıları görebilmek için Vorssaint varsayılan tarayıcı olur ve her bağlantıyı seçtiğiniz tarayıcıya aktarır. macOS onay ister. Bağlantıları geri verdiğinizde veya bu özelliği kaldırdığınızda önceki tarayıcı yeniden varsayılan olur.",
        rulesTitle: "Kurallar",
        rulesCaption: "Bir kurala uyan bağlantı seçici gösterilmeden hemen açılır. İlk uyan kural geçerlidir; sırayı değiştirmek için kuralları sürükleyin.",
        noRules: "Henüz kural yok, bu yüzden her bağlantıda seçici gösterilir.",
        addRule: "Kural ekle…",
        editRule: "Düzenle…",
        deleteRule: "Kaldır",
        moveUp: "Yukarı taşı",
        moveDown: "Aşağı taşı",
        ruleEnabled: "Kural açık",
        ruleActions: "Kural eylemleri",
        unavailableTargetFormat: "%@ (kullanılamıyor)",
        newRuleTitle: "Yeni kural",
        siteLabel: "Site",
        pathLabel: "Yalnızca bu yolda",
        pathPlaceholder: "İsteğe bağlı, örneğin /ekip",
        openInLabel: "Şurada aç",
        chooseBrowser: "Seç…",
        siteHint: "example.com gibi bir site girin. Alt alan adları da dahildir.",
        invalidSite: "Bu bir site adresi değil. example.com gibi bir adres girin.",
        coversSiteFormat: "%@ ve alt alan adlarının tüm sayfalarını kapsar.",
        coversPathFormat: "%1$@ sitesinde %2$@ altındaki sayfaları kapsar.",
        linkMatches: "Bu bağlantı uyuyor.",
        linkDoesNotMatch: "Bu bağlantı uymuyor.",
        cancel: "Vazgeç",
        save: "Kaydet",
        saveAndOpen: "Kaydet ve aç",
        noBrowsers: "Tarayıcı bulunamadı",
        moreLinksFormat: "%d tane daha",
        addRuleFromLink: "Bu site için kural…",
        copyLink: "Bağlantıyı kopyala",
        rememberHint: "Bu siteyi her zaman burada açmak için ⌥ tuşunu basılı tutun",
        targetMissingFormat: "%@ kullanılamıyor. Bu bağlantının nerede açılacağını seçin.",
        openFailedFormat: "%@ bu bağlantıyı açamadı.",
        profilesWithheldFormat: "macOS, Vorssaint’in %@ profillerini okumasına izin vermedi; bu yüzden her biri tek tarayıcı olarak görünür. macOS sorduğunda izin verin veya Tam Disk Erişimi’ni açın."
    )

    static let ru = BrowserPickerStrings(
        featureName: "Выбор браузера",
        featureDescription: "Выбирайте браузер или профиль для каждой ссылки или отправляйте сайты в нужный автоматически",
        searchKeywords: ["браузер", "браузер по умолчанию", "ссылки", "профиль", "Chrome", "правила"],
        statusOn: "Ссылки из других приложений открываются через Vorssaint",
        statusOff: "Vorssaint пока не браузер по умолчанию",
        makeDefault: "Сделать браузером по умолчанию…",
        restoreFormat: "Вернуть ссылки в %@",
        defaultBrowserCaption: "Чтобы видеть ссылки, которые вы открываете, Vorssaint становится браузером по умолчанию и передаёт каждую ссылку выбранному браузеру. macOS попросит подтвердить. Если вернуть ссылки или удалить эту функцию, основным снова станет прежний браузер.",
        rulesTitle: "Правила",
        rulesCaption: "Ссылка, подходящая под правило, открывается сразу, без выбора. Срабатывает первое подходящее правило; порядок меняется перетаскиванием.",
        noRules: "Правил пока нет, поэтому для каждой ссылки показывается выбор.",
        addRule: "Добавить правило…",
        editRule: "Изменить…",
        deleteRule: "Удалить",
        moveUp: "Выше",
        moveDown: "Ниже",
        ruleEnabled: "Правило включено",
        ruleActions: "Действия с правилом",
        unavailableTargetFormat: "%@ (недоступен)",
        newRuleTitle: "Новое правило",
        siteLabel: "Сайт",
        pathLabel: "Только раздел",
        pathPlaceholder: "Необязательно, например /team",
        openInLabel: "Открывать в",
        chooseBrowser: "Выберите…",
        siteHint: "Введите сайт, например example.com. Его поддомены тоже учитываются.",
        invalidSite: "Это не адрес сайта. Введите, например, example.com.",
        coversSiteFormat: "Все страницы %@ и его поддоменов.",
        coversPathFormat: "Страницы %1$@ в разделе %2$@.",
        linkMatches: "Эта ссылка подходит.",
        linkDoesNotMatch: "Эта ссылка не подходит.",
        cancel: "Отменить",
        save: "Сохранить",
        saveAndOpen: "Сохранить и открыть",
        noBrowsers: "Браузеры не найдены",
        moreLinksFormat: "ещё %d",
        addRuleFromLink: "Правило для сайта…",
        copyLink: "Скопировать ссылку",
        rememberHint: "С ⌥ этот сайт всегда будет открываться здесь",
        targetMissingFormat: "%@ недоступен. Выберите, где открыть ссылку.",
        openFailedFormat: "%@ не смог открыть ссылку.",
        profilesWithheldFormat: "macOS не дала Vorssaint прочитать профили %@, поэтому каждый показан одним браузером. Разрешите доступ, когда macOS спросит, или включите «Полный доступ к диску»."
    )

    static let es = BrowserPickerStrings(
        featureName: "Selector de navegador",
        featureDescription: "Elige el navegador o perfil de cada enlace que pulses, o envía sitios a uno automáticamente",
        searchKeywords: ["navegador", "navegador predeterminado", "enlaces", "perfil", "Chrome", "reglas"],
        statusOn: "Los enlaces de otras apps se abren a través de Vorssaint",
        statusOff: "Vorssaint aún no es el navegador predeterminado",
        makeDefault: "Usar como navegador predeterminado…",
        restoreFormat: "Devolver los enlaces a %@",
        defaultBrowserCaption: "Para ver los enlaces que pulsas, Vorssaint pasa a ser el navegador predeterminado y entrega cada enlace al navegador que elijas. macOS te pide confirmación. Al devolver los enlaces, o al quitar esta función, el navegador anterior vuelve a ser el predeterminado.",
        rulesTitle: "Reglas",
        rulesCaption: "Un enlace que coincide con una regla se abre al momento, sin el selector. Gana la primera regla que coincida; arrastra las reglas para cambiar su orden.",
        noRules: "Aún no hay reglas, así que cada enlace muestra el selector.",
        addRule: "Añadir regla…",
        editRule: "Editar…",
        deleteRule: "Eliminar",
        moveUp: "Subir",
        moveDown: "Bajar",
        ruleEnabled: "Regla activada",
        ruleActions: "Acciones de la regla",
        unavailableTargetFormat: "%@ (no disponible)",
        newRuleTitle: "Nueva regla",
        siteLabel: "Sitio",
        pathLabel: "Solo en la ruta",
        pathPlaceholder: "Opcional, como /equipo",
        openInLabel: "Abrir en",
        chooseBrowser: "Elegir…",
        siteHint: "Escribe un sitio como example.com. Incluye sus subdominios.",
        invalidSite: "Esto no es la dirección de un sitio. Escribe una como example.com.",
        coversSiteFormat: "Abarca todas las páginas de %@ y sus subdominios.",
        coversPathFormat: "Abarca las páginas de %1$@ bajo %2$@.",
        linkMatches: "Este enlace coincide.",
        linkDoesNotMatch: "Este enlace no coincide.",
        cancel: "Cancelar",
        save: "Guardar",
        saveAndOpen: "Guardar y abrir",
        noBrowsers: "No se encontraron navegadores",
        moreLinksFormat: "%d más",
        addRuleFromLink: "Regla para este sitio…",
        copyLink: "Copiar enlace",
        rememberHint: "Mantén pulsada ⌥ para abrir siempre este sitio aquí",
        targetMissingFormat: "%@ no está disponible. Elige dónde abrir este enlace.",
        openFailedFormat: "%@ no pudo abrir este enlace.",
        profilesWithheldFormat: "macOS no permitió a Vorssaint leer los perfiles de %@, así que cada uno aparece como un solo navegador. Permite el acceso cuando macOS lo pregunte o activa Acceso total al disco."
    )

    static let sk = BrowserPickerStrings(
        featureName: "Výber prehliadača",
        featureDescription: "Vyberte prehliadač alebo profil pre každý odkaz, na ktorý kliknete, alebo posielajte weby automaticky do jedného",
        searchKeywords: ["prehliadač", "predvolený prehliadač", "odkazy", "profil", "Chrome", "pravidlá"],
        statusOn: "Odkazy z iných aplikácií sa otvárajú cez Vorssaint",
        statusOff: "Vorssaint zatiaľ nie je predvolený prehliadač",
        makeDefault: "Nastaviť ako predvolený prehliadač…",
        restoreFormat: "Vrátiť odkazy do aplikácie %@",
        defaultBrowserCaption: "Aby Vorssaint videl odkazy, na ktoré kliknete, stane sa predvoleným prehliadačom a každý odkaz odovzdá prehliadaču, ktorý vyberiete. macOS vás požiada o potvrdenie. Keď odkazy vrátite alebo túto funkciu odstránite, predvoleným bude znova predchádzajúci prehliadač.",
        rulesTitle: "Pravidlá",
        rulesCaption: "Odkaz, ktorý zodpovedá pravidlu, sa otvorí hneď, bez výberu. Platí prvé zodpovedajúce pravidlo; poradie zmeníte potiahnutím.",
        noRules: "Zatiaľ nie sú žiadne pravidlá, preto sa pri každom odkaze zobrazí výber.",
        addRule: "Pridať pravidlo…",
        editRule: "Upraviť…",
        deleteRule: "Odstrániť",
        moveUp: "Posunúť vyššie",
        moveDown: "Posunúť nižšie",
        ruleEnabled: "Pravidlo zapnuté",
        ruleActions: "Akcie pravidla",
        unavailableTargetFormat: "%@ (nedostupné)",
        newRuleTitle: "Nové pravidlo",
        siteLabel: "Web",
        pathLabel: "Len v ceste",
        pathPlaceholder: "Voliteľné, napríklad /tim",
        openInLabel: "Otvoriť v",
        chooseBrowser: "Vybrať…",
        siteHint: "Zadajte web, napríklad example.com. Zahŕňa aj jeho subdomény.",
        invalidSite: "Toto nie je adresa webu. Zadajte napríklad example.com.",
        coversSiteFormat: "Platí pre všetky stránky %@ a jeho subdomén.",
        coversPathFormat: "Platí pre stránky %1$@ v ceste %2$@.",
        linkMatches: "Tento odkaz zodpovedá.",
        linkDoesNotMatch: "Tento odkaz nezodpovedá.",
        cancel: "Zrušiť",
        save: "Uložiť",
        saveAndOpen: "Uložiť a otvoriť",
        noBrowsers: "Nenašli sa žiadne prehliadače",
        moreLinksFormat: "ďalšie: %d",
        addRuleFromLink: "Pravidlo pre tento web…",
        copyLink: "Kopírovať odkaz",
        rememberHint: "Podržte ⌥, aby sa tento web vždy otváral tu",
        targetMissingFormat: "%@ nie je dostupné. Vyberte, kde otvoriť tento odkaz.",
        openFailedFormat: "%@ nedokázal otvoriť tento odkaz.",
        profilesWithheldFormat: "macOS nedovolil aplikácii Vorssaint prečítať profily z %@, preto sa každý zobrazuje ako jeden prehliadač. Povoľte prístup, keď sa macOS opýta, alebo zapnite Úplný prístup k disku."
    )

    static let de = BrowserPickerStrings(
        featureName: "Browserauswahl",
        featureDescription: "Wähle für jeden angeklickten Link den Browser oder das Profil, oder sende Websites automatisch an einen",
        searchKeywords: ["Browser", "Standardbrowser", "Links", "Profil", "Chrome", "Regeln"],
        statusOn: "Links aus anderen Apps öffnen über Vorssaint",
        statusOff: "Vorssaint ist noch nicht der Standardbrowser",
        makeDefault: "Als Standardbrowser festlegen…",
        restoreFormat: "Links an %@ zurückgeben",
        defaultBrowserCaption: "Damit Vorssaint die angeklickten Links sieht, wird es zum Standardbrowser und gibt jeden Link an den gewählten Browser weiter. macOS bittet dich um Bestätigung. Gibst du die Links zurück oder entfernst diese Funktion, wird der vorherige Browser wieder zum Standard.",
        rulesTitle: "Regeln",
        rulesCaption: "Ein Link, der zu einer Regel passt, öffnet sofort ohne Auswahl. Die erste passende Regel gilt; ziehe Regeln, um ihre Reihenfolge zu ändern.",
        noRules: "Noch keine Regeln, daher zeigt jeder Link die Auswahl.",
        addRule: "Regel hinzufügen…",
        editRule: "Bearbeiten…",
        deleteRule: "Entfernen",
        moveUp: "Nach oben",
        moveDown: "Nach unten",
        ruleEnabled: "Regel aktiv",
        ruleActions: "Regelaktionen",
        unavailableTargetFormat: "%@ (nicht verfügbar)",
        newRuleTitle: "Neue Regel",
        siteLabel: "Website",
        pathLabel: "Nur unter Pfad",
        pathPlaceholder: "Optional, z.\u{00A0}B. /team",
        openInLabel: "Öffnen in",
        chooseBrowser: "Auswählen…",
        siteHint: "Gib eine Website wie example.com ein. Ihre Subdomains sind eingeschlossen.",
        invalidSite: "Das ist keine Websiteadresse. Gib eine wie example.com ein.",
        coversSiteFormat: "Gilt für alle Seiten von %@ und den Subdomains.",
        coversPathFormat: "Gilt für Seiten von %1$@ unter %2$@.",
        linkMatches: "Dieser Link passt.",
        linkDoesNotMatch: "Dieser Link passt nicht.",
        cancel: "Abbrechen",
        save: "Sichern",
        saveAndOpen: "Sichern und öffnen",
        noBrowsers: "Keine Browser gefunden",
        moreLinksFormat: "%d weitere",
        addRuleFromLink: "Regel für diese Website…",
        copyLink: "Link kopieren",
        rememberHint: "Halte ⌥ gedrückt, um diese Website immer hier zu öffnen",
        targetMissingFormat: "%@ ist nicht verfügbar. Wähle, wo dieser Link geöffnet wird.",
        openFailedFormat: "%@ konnte diesen Link nicht öffnen.",
        profilesWithheldFormat: "macOS hat Vorssaint die Profile von %@ nicht lesen lassen, daher erscheint jeder als ein Browser. Erlaube den Zugriff, wenn macOS fragt, oder aktiviere „Festplattenvollzugriff“."
    )

    static let fr = BrowserPickerStrings(
        featureName: "Sélecteur de navigateur",
        featureDescription: "Choisissez le navigateur ou le profil de chaque lien cliqué, ou envoyez des sites vers l’un d’eux automatiquement",
        searchKeywords: ["navigateur", "navigateur par défaut", "liens", "profil", "Chrome", "règles"],
        statusOn: "Les liens des autres apps s’ouvrent via Vorssaint",
        statusOff: "Vorssaint n’est pas encore le navigateur par défaut",
        makeDefault: "Définir comme navigateur par défaut…",
        restoreFormat: "Rendre les liens à %@",
        defaultBrowserCaption: "Pour voir les liens sur lesquels vous cliquez, Vorssaint devient le navigateur par défaut et transmet chaque lien au navigateur choisi. macOS vous demande de confirmer. Si vous rendez les liens ou supprimez cette fonctionnalité, le navigateur précédent redevient celui par défaut.",
        rulesTitle: "Règles",
        rulesCaption: "Un lien qui correspond à une règle s’ouvre aussitôt, sans le sélecteur. La première règle qui correspond l’emporte\u{00A0}; faites glisser les règles pour changer leur ordre.",
        noRules: "Aucune règle pour l’instant, chaque lien affiche donc le sélecteur.",
        addRule: "Ajouter une règle…",
        editRule: "Modifier…",
        deleteRule: "Supprimer",
        moveUp: "Monter",
        moveDown: "Descendre",
        ruleEnabled: "Règle activée",
        ruleActions: "Actions de la règle",
        unavailableTargetFormat: "%@ (indisponible)",
        newRuleTitle: "Nouvelle règle",
        siteLabel: "Site",
        pathLabel: "Seulement sous le chemin",
        pathPlaceholder: "Facultatif, par exemple /equipe",
        openInLabel: "Ouvrir dans",
        chooseBrowser: "Choisir…",
        siteHint: "Saisissez un site comme example.com. Ses sous-domaines sont inclus.",
        invalidSite: "Ce n’est pas une adresse de site. Saisissez-en une comme example.com.",
        coversSiteFormat: "Couvre toutes les pages de %@ et de ses sous-domaines.",
        coversPathFormat: "Couvre les pages de %1$@ sous %2$@.",
        linkMatches: "Ce lien correspond.",
        linkDoesNotMatch: "Ce lien ne correspond pas.",
        cancel: "Annuler",
        save: "Enregistrer",
        saveAndOpen: "Enregistrer et ouvrir",
        noBrowsers: "Aucun navigateur trouvé",
        moreLinksFormat: "%d de plus",
        addRuleFromLink: "Règle pour ce site…",
        copyLink: "Copier le lien",
        rememberHint: "Maintenez ⌥ pour toujours ouvrir ce site ici",
        targetMissingFormat: "%@ n’est pas disponible. Choisissez où ouvrir ce lien.",
        openFailedFormat: "%@ n’a pas pu ouvrir ce lien.",
        profilesWithheldFormat: "macOS n’a pas laissé Vorssaint lire les profils de %@\u{00A0}: chacun apparaît donc comme un seul navigateur. Autorisez l’accès quand macOS le demande ou activez l’accès complet au disque."
    )

    static let it = BrowserPickerStrings(
        featureName: "Selettore del browser",
        featureDescription: "Scegli il browser o il profilo per ogni link su cui fai clic, o invia i siti a uno in automatico",
        searchKeywords: ["browser", "browser predefinito", "link", "profilo", "Chrome", "regole"],
        statusOn: "I link delle altre app si aprono tramite Vorssaint",
        statusOff: "Vorssaint non è ancora il browser predefinito",
        makeDefault: "Imposta come browser predefinito…",
        restoreFormat: "Restituisci i link a %@",
        defaultBrowserCaption: "Per vedere i link su cui fai clic, Vorssaint diventa il browser predefinito e passa ogni link al browser che scegli. macOS chiede conferma. Se restituisci i link o rimuovi questa funzione, il browser precedente torna predefinito.",
        rulesTitle: "Regole",
        rulesCaption: "Un link che corrisponde a una regola si apre subito, senza il selettore. Vale la prima regola che corrisponde; trascina le regole per cambiarne l’ordine.",
        noRules: "Ancora nessuna regola, quindi ogni link mostra il selettore.",
        addRule: "Aggiungi regola…",
        editRule: "Modifica…",
        deleteRule: "Rimuovi",
        moveUp: "Sposta su",
        moveDown: "Sposta giù",
        ruleEnabled: "Regola attiva",
        ruleActions: "Azioni della regola",
        unavailableTargetFormat: "%@ (non disponibile)",
        newRuleTitle: "Nuova regola",
        siteLabel: "Sito",
        pathLabel: "Solo sotto il percorso",
        pathPlaceholder: "Facoltativo, ad esempio /team",
        openInLabel: "Apri in",
        chooseBrowser: "Scegli…",
        siteHint: "Inserisci un sito come example.com. Sono inclusi i suoi sottodomini.",
        invalidSite: "Questo non è un indirizzo di sito. Inseriscine uno come example.com.",
        coversSiteFormat: "Vale per tutte le pagine di %@ e dei suoi sottodomini.",
        coversPathFormat: "Vale per le pagine di %1$@ sotto %2$@.",
        linkMatches: "Questo link corrisponde.",
        linkDoesNotMatch: "Questo link non corrisponde.",
        cancel: "Annulla",
        save: "Salva",
        saveAndOpen: "Salva e apri",
        noBrowsers: "Nessun browser trovato",
        moreLinksFormat: "altri %d",
        addRuleFromLink: "Regola per questo sito…",
        copyLink: "Copia link",
        rememberHint: "Tieni premuto ⌥ per aprire sempre questo sito qui",
        targetMissingFormat: "%@ non è disponibile. Scegli dove aprire questo link.",
        openFailedFormat: "%@ non è riuscito ad aprire questo link.",
        profilesWithheldFormat: "macOS non ha permesso a Vorssaint di leggere i profili di %@, quindi ognuno appare come un solo browser. Consenti l’accesso quando macOS lo chiede o attiva Accesso completo al disco."
    )

    static let ja = BrowserPickerStrings(
        featureName: "ブラウザピッカー",
        featureDescription: "クリックしたリンクごとにブラウザやプロファイルを選ぶか、サイトを自動的に特定のブラウザで開きます",
        searchKeywords: ["ブラウザ", "デフォルトのブラウザ", "リンク", "プロファイル", "Chrome", "ルール"],
        statusOn: "ほかのアプリのリンクはVorssaint経由で開きます",
        statusOff: "Vorssaintはまだデフォルトのブラウザではありません",
        makeDefault: "デフォルトのブラウザに設定…",
        restoreFormat: "リンクを%@に戻す",
        defaultBrowserCaption: "クリックしたリンクを受け取るため、Vorssaintがデフォルトのブラウザになり、各リンクを選んだブラウザに渡します。macOSが確認を求めます。リンクを戻すか、この機能を削除すると、以前のブラウザが再びデフォルトになります。",
        rulesTitle: "ルール",
        rulesCaption: "ルールに一致したリンクはピッカーを出さずにすぐ開きます。最初に一致したルールが優先され、ドラッグで順番を変更できます。",
        noRules: "ルールがまだないため、すべてのリンクでピッカーが表示されます。",
        addRule: "ルールを追加…",
        editRule: "編集…",
        deleteRule: "削除",
        moveUp: "上へ移動",
        moveDown: "下へ移動",
        ruleEnabled: "ルールを有効にする",
        ruleActions: "ルールの操作",
        unavailableTargetFormat: "%@（使用できません）",
        newRuleTitle: "新規ルール",
        siteLabel: "サイト",
        pathLabel: "このパス以下のみ",
        pathPlaceholder: "任意（例：/team）",
        openInLabel: "開くアプリ",
        chooseBrowser: "選択…",
        siteHint: "example.comのようにサイトを入力します。サブドメインも含まれます。",
        invalidSite: "サイトのアドレスではありません。example.comのように入力してください。",
        coversSiteFormat: "%@とそのサブドメインのすべてのページが対象です。",
        coversPathFormat: "%1$@の%2$@以下のページが対象です。",
        linkMatches: "このリンクは一致します。",
        linkDoesNotMatch: "このリンクは一致しません。",
        cancel: "キャンセル",
        save: "保存",
        saveAndOpen: "保存して開く",
        noBrowsers: "ブラウザが見つかりません",
        moreLinksFormat: "ほか%d件",
        addRuleFromLink: "このサイトのルール…",
        copyLink: "リンクをコピー",
        rememberHint: "⌥を押したまま選ぶと、このサイトを常にここで開きます",
        targetMissingFormat: "%@は使用できません。このリンクを開く場所を選んでください。",
        openFailedFormat: "%@でこのリンクを開けませんでした。",
        profilesWithheldFormat: "macOSの制限で%@のプロファイルを読み取れないため、それぞれ1つのブラウザとして表示されます。macOSに尋ねられたら許可するか、フルディスクアクセスをオンにしてください。"
    )

    static let ko = BrowserPickerStrings(
        featureName: "브라우저 선택기",
        featureDescription: "클릭한 링크마다 브라우저나 프로필을 고르거나 사이트를 자동으로 한 브라우저에서 엽니다",
        searchKeywords: ["브라우저", "기본 브라우저", "링크", "프로필", "Chrome", "규칙"],
        statusOn: "다른 앱의 링크가 Vorssaint를 통해 열립니다",
        statusOff: "Vorssaint가 아직 기본 브라우저가 아닙니다",
        makeDefault: "기본 브라우저로 설정…",
        restoreFormat: "링크를 %@에 되돌려주기",
        defaultBrowserCaption: "클릭한 링크를 받기 위해 Vorssaint가 기본 브라우저가 되어 각 링크를 선택한 브라우저로 넘깁니다. macOS가 확인을 요청합니다. 링크를 되돌려주거나 이 기능을 제거하면 이전 브라우저가 다시 기본 브라우저가 됩니다.",
        rulesTitle: "규칙",
        rulesCaption: "규칙과 일치하는 링크는 선택기 없이 바로 열립니다. 처음 일치하는 규칙이 적용되며, 규칙을 드래그해 순서를 바꿀 수 있습니다.",
        noRules: "아직 규칙이 없어 모든 링크에 선택기가 표시됩니다.",
        addRule: "규칙 추가…",
        editRule: "편집…",
        deleteRule: "제거",
        moveUp: "위로 이동",
        moveDown: "아래로 이동",
        ruleEnabled: "규칙 켬",
        ruleActions: "규칙 동작",
        unavailableTargetFormat: "%@ (사용할 수 없음)",
        newRuleTitle: "새로운 규칙",
        siteLabel: "사이트",
        pathLabel: "이 경로만",
        pathPlaceholder: "선택 사항, 예: /team",
        openInLabel: "열 위치",
        chooseBrowser: "선택…",
        siteHint: "example.com과 같은 사이트를 입력하세요. 하위 도메인도 포함됩니다.",
        invalidSite: "사이트 주소가 아닙니다. example.com과 같이 입력하세요.",
        coversSiteFormat: "%@ 및 하위 도메인의 모든 페이지에 적용됩니다.",
        coversPathFormat: "%1$@에서 %2$@ 아래 페이지에 적용됩니다.",
        linkMatches: "이 링크가 일치합니다.",
        linkDoesNotMatch: "이 링크는 일치하지 않습니다.",
        cancel: "취소",
        save: "저장",
        saveAndOpen: "저장하고 열기",
        noBrowsers: "브라우저를 찾을 수 없음",
        moreLinksFormat: "%d개 더",
        addRuleFromLink: "이 사이트 규칙…",
        copyLink: "링크 복사",
        rememberHint: "⌥ 키를 누른 채 선택하면 이 사이트를 항상 여기에서 엽니다",
        targetMissingFormat: "%@을(를) 사용할 수 없습니다. 이 링크를 열 위치를 선택하세요.",
        openFailedFormat: "%@에서 이 링크를 열 수 없습니다.",
        profilesWithheldFormat: "macOS가 Vorssaint의 %@ 프로필 읽기를 허용하지 않아 각각 하나의 브라우저로 표시됩니다. macOS가 물어볼 때 허용하거나 전체 디스크 접근 권한을 켜세요."
    )

    static let zhHans = BrowserPickerStrings(
        featureName: "浏览器选择器",
        featureDescription: "为点按的每个链接选择浏览器或个人资料，或自动用某个浏览器打开网站",
        searchKeywords: ["浏览器", "默认浏览器", "链接", "个人资料", "Chrome", "规则"],
        statusOn: "其他 App 中的链接通过 Vorssaint 打开",
        statusOff: "Vorssaint 还不是默认浏览器",
        makeDefault: "设为默认浏览器…",
        restoreFormat: "将链接交还给 %@",
        defaultBrowserCaption: "为了看到你点按的链接，Vorssaint 会成为默认浏览器，并把每个链接交给你选择的浏览器。macOS 会请你确认。交还链接或移除此功能后，之前的浏览器会重新成为默认浏览器。",
        rulesTitle: "规则",
        rulesCaption: "与规则匹配的链接会直接打开，不显示选择器。第一条匹配的规则生效；拖移规则可更改顺序。",
        noRules: "还没有规则，因此每个链接都会显示选择器。",
        addRule: "添加规则…",
        editRule: "编辑…",
        deleteRule: "移除",
        moveUp: "上移",
        moveDown: "下移",
        ruleEnabled: "规则已开启",
        ruleActions: "规则操作",
        unavailableTargetFormat: "%@（不可用）",
        newRuleTitle: "新规则",
        siteLabel: "网站",
        pathLabel: "仅限路径",
        pathPlaceholder: "可选，例如 /team",
        openInLabel: "打开方式",
        chooseBrowser: "选择…",
        siteHint: "输入网站，例如 example.com。其子域名也包括在内。",
        invalidSite: "这不是网站地址。请输入例如 example.com。",
        coversSiteFormat: "适用于 %@ 及其子域名的所有页面。",
        coversPathFormat: "适用于 %1$@ 中 %2$@ 下的页面。",
        linkMatches: "此链接匹配。",
        linkDoesNotMatch: "此链接不匹配。",
        cancel: "取消",
        save: "保存",
        saveAndOpen: "保存并打开",
        noBrowsers: "未找到浏览器",
        moreLinksFormat: "还有 %d 个",
        addRuleFromLink: "为此网站添加规则…",
        copyLink: "拷贝链接",
        rememberHint: "按住 ⌥ 键选择，以后总在此处打开此网站",
        targetMissingFormat: "%@ 不可用。请选择打开此链接的位置。",
        openFailedFormat: "%@ 无法打开此链接。",
        profilesWithheldFormat: "macOS 未允许 Vorssaint 读取 %@ 的个人资料，因此每个浏览器只显示为一项。请在 macOS 询问时允许，或打开“完全磁盘访问权限”。"
    )

    static let zhTW = BrowserPickerStrings(
        featureName: "瀏覽器選擇器",
        featureDescription: "為點按的每個連結選擇瀏覽器或個人資料，或自動用某個瀏覽器打開網站",
        searchKeywords: ["瀏覽器", "預設瀏覽器", "連結", "個人資料", "Chrome", "規則"],
        statusOn: "其他 App 的連結會透過 Vorssaint 打開",
        statusOff: "Vorssaint 尚未成為預設瀏覽器",
        makeDefault: "設為預設瀏覽器…",
        restoreFormat: "將連結交還給 %@",
        defaultBrowserCaption: "為了看到你點按的連結，Vorssaint 會成為預設瀏覽器，並把每個連結交給你選擇的瀏覽器。macOS 會請你確認。交還連結或移除此功能後，先前的瀏覽器會再次成為預設瀏覽器。",
        rulesTitle: "規則",
        rulesCaption: "符合規則的連結會直接打開，不顯示選擇器。第一條符合的規則優先；拖移規則可更改順序。",
        noRules: "尚無規則，因此每個連結都會顯示選擇器。",
        addRule: "加入規則…",
        editRule: "編輯…",
        deleteRule: "移除",
        moveUp: "上移",
        moveDown: "下移",
        ruleEnabled: "規則已開啟",
        ruleActions: "規則動作",
        unavailableTargetFormat: "%@（無法使用）",
        newRuleTitle: "新規則",
        siteLabel: "網站",
        pathLabel: "僅限路徑",
        pathPlaceholder: "選填，例如 /team",
        openInLabel: "打開方式",
        chooseBrowser: "選擇…",
        siteHint: "輸入網站，例如 example.com。也包括其子網域。",
        invalidSite: "這不是網站位址。請輸入例如 example.com。",
        coversSiteFormat: "適用於 %@ 及其子網域的所有頁面。",
        coversPathFormat: "適用於 %1$@ 中 %2$@ 下的頁面。",
        linkMatches: "此連結符合。",
        linkDoesNotMatch: "此連結不符合。",
        cancel: "取消",
        save: "儲存",
        saveAndOpen: "儲存並打開",
        noBrowsers: "找不到瀏覽器",
        moreLinksFormat: "還有 %d 個",
        addRuleFromLink: "為此網站加入規則…",
        copyLink: "拷貝連結",
        rememberHint: "按住 ⌥ 鍵選擇，之後一律在這裡打開此網站",
        targetMissingFormat: "%@ 無法使用。請選擇要在哪裡打開此連結。",
        openFailedFormat: "%@ 無法打開此連結。",
        profilesWithheldFormat: "macOS 未允許 Vorssaint 讀取 %@ 的個人資料，因此每個瀏覽器只顯示為一項。請在 macOS 詢問時允許，或開啟「完整磁碟取用權限」。"
    )

    static let zhHK = BrowserPickerStrings(
        featureName: "瀏覽器選擇器",
        featureDescription: "為點按的每個連結選擇瀏覽器或個人資料，或自動用某個瀏覽器打開網站",
        searchKeywords: ["瀏覽器", "預設瀏覽器", "連結", "個人資料", "Chrome", "規則"],
        statusOn: "其他 App 的連結會透過 Vorssaint 打開",
        statusOff: "Vorssaint 尚未成為預設瀏覽器",
        makeDefault: "設為預設瀏覽器…",
        restoreFormat: "將連結交還給 %@",
        defaultBrowserCaption: "為了看到你點按的連結，Vorssaint 會成為預設瀏覽器，並把每個連結交給你選擇的瀏覽器。macOS 會請你確認。交還連結或移除此功能後，先前的瀏覽器會再次成為預設瀏覽器。",
        rulesTitle: "規則",
        rulesCaption: "符合規則的連結會直接打開，不顯示選擇器。第一條符合的規則優先；拖移規則可更改順序。",
        noRules: "未有規則，因此每個連結都會顯示選擇器。",
        addRule: "加入規則…",
        editRule: "編輯…",
        deleteRule: "移除",
        moveUp: "上移",
        moveDown: "下移",
        ruleEnabled: "規則已開啟",
        ruleActions: "規則動作",
        unavailableTargetFormat: "%@（無法使用）",
        newRuleTitle: "新規則",
        siteLabel: "網站",
        pathLabel: "僅限路徑",
        pathPlaceholder: "可選，例如 /team",
        openInLabel: "打開方式",
        chooseBrowser: "選擇…",
        siteHint: "輸入網站，例如 example.com。亦包括其子網域。",
        invalidSite: "這不是網站位址。請輸入例如 example.com。",
        coversSiteFormat: "適用於 %@ 及其子網域的所有頁面。",
        coversPathFormat: "適用於 %1$@ 中 %2$@ 下的頁面。",
        linkMatches: "此連結符合。",
        linkDoesNotMatch: "此連結不符合。",
        cancel: "取消",
        save: "儲存",
        saveAndOpen: "儲存並打開",
        noBrowsers: "找不到瀏覽器",
        moreLinksFormat: "還有 %d 個",
        addRuleFromLink: "為此網站加入規則…",
        copyLink: "拷貝連結",
        rememberHint: "按住 ⌥ 鍵選擇，之後一律在這裡打開此網站",
        targetMissingFormat: "%@ 無法使用。請選擇要在哪裡打開此連結。",
        openFailedFormat: "%@ 無法打開此連結。",
        profilesWithheldFormat: "macOS 未允許 Vorssaint 讀取 %@ 的個人資料，因此每個瀏覽器只顯示為一項。請在 macOS 詢問時允許，或開啟「完整磁碟取用權限」。"
    )

    static let uk = BrowserPickerStrings(
        featureName: "Вибір браузера",
        featureDescription: "Обирайте браузер або профіль для кожного посилання чи автоматично надсилайте сайти в потрібний",
        searchKeywords: ["браузер", "браузер за замовчуванням", "посилання", "профіль", "Chrome", "правила"],
        statusOn: "Посилання з інших програм відкриваються через Vorssaint",
        statusOff: "Vorssaint ще не браузер за замовчуванням",
        makeDefault: "Зробити браузером за замовчуванням…",
        restoreFormat: "Повернути посилання в %@",
        defaultBrowserCaption: "Щоб бачити посилання, які ви відкриваєте, Vorssaint стає браузером за замовчуванням і передає кожне посилання вибраному браузеру. macOS попросить підтвердити. Якщо повернути посилання або видалити цю функцію, основним знову стане попередній браузер.",
        rulesTitle: "Правила",
        rulesCaption: "Посилання, що відповідає правилу, відкривається одразу, без вибору. Спрацьовує перше відповідне правило; порядок змінюється перетягуванням.",
        noRules: "Правил поки немає, тому для кожного посилання показується вибір.",
        addRule: "Додати правило…",
        editRule: "Змінити…",
        deleteRule: "Видалити",
        moveUp: "Вище",
        moveDown: "Нижче",
        ruleEnabled: "Правило ввімкнено",
        ruleActions: "Дії з правилом",
        unavailableTargetFormat: "%@ (недоступний)",
        newRuleTitle: "Нове правило",
        siteLabel: "Сайт",
        pathLabel: "Лише розділ",
        pathPlaceholder: "Необов’язково, наприклад /team",
        openInLabel: "Відкривати в",
        chooseBrowser: "Виберіть…",
        siteHint: "Введіть сайт, наприклад example.com. Його піддомени теж враховуються.",
        invalidSite: "Це не адреса сайту. Введіть, наприклад, example.com.",
        coversSiteFormat: "Усі сторінки %@ та його піддоменів.",
        coversPathFormat: "Сторінки %1$@ у розділі %2$@.",
        linkMatches: "Це посилання підходить.",
        linkDoesNotMatch: "Це посилання не підходить.",
        cancel: "Скасувати",
        save: "Зберегти",
        saveAndOpen: "Зберегти й відкрити",
        noBrowsers: "Браузерів не знайдено",
        moreLinksFormat: "ще %d",
        addRuleFromLink: "Правило для сайту…",
        copyLink: "Скопіювати посилання",
        rememberHint: "З ⌥ цей сайт завжди відкриватиметься тут",
        targetMissingFormat: "%@ недоступний. Виберіть, де відкрити посилання.",
        openFailedFormat: "%@ не зміг відкрити посилання.",
        profilesWithheldFormat: "macOS не дозволила Vorssaint прочитати профілі %@, тому кожен показано одним браузером. Дозвольте доступ, коли macOS запитає, або ввімкніть «Повний доступ до диска»."
    )
}
