// SPDX-License-Identifier: GPL-3.0-or-later

import Foundation

struct CalendarStrings {
    let title: String; let description: String; let showInMenuBar: String; let accessRequired: String
    let openPreferences: String; let appearance: String; let menuBarStyle: String; let textScale: String
    let meetingAlerts: String; let alerts: String; let notifyBefore: String; let calendars: String
    let noEvents: String; let join: String; let openInCalendar: String; let allDay: String
    let agenda: String; let showMonthOutline: String; let showDeclinedEvents: String; let eventDots: String
    let eventDotsNone: String; let eventDotsSingleNeutral: String; let eventDotsSingleHighlighted: String
    let eventDotsMultiple: String; let menuBarComponents: String; let showAdjacentDays: String
    let componentIcon: String; let componentDate: String; let componentNextEvent: String
    let menuBarDateFormat: String; let customDatePattern: String
    let moveUp: String; let moveDown: String
    let newEvent: String; let start: String; let end: String; let cancel: String; let save: String
    let calendarLabel: String; let quickAddPlaceholder: String
    let durationZero: String; let durationMinute: String; let durationMinutes: String
    let durationHour: String; let durationHours: String; let durationDay: String; let durationDays: String

    func duration(from interval: TimeInterval) -> String {
        let minutes = max(0, Int(interval / 60))
        if minutes == 0 { return durationZero }
        let days = minutes / 1_440
        let hours = (minutes % 1_440) / 60
        let remaining = minutes % 60
        var parts: [String] = []
        if days > 0 { parts.append("\(days) \(days == 1 ? durationDay : durationDays)") }
        if hours > 0 { parts.append("\(hours) \(hours == 1 ? durationHour : durationHours)") }
        if remaining > 0 { parts.append("\(remaining) \(remaining == 1 ? durationMinute : durationMinutes)") }
        return parts.joined(separator: " ")
    }

    static func current(_ language: AppLanguage) -> Self {
        switch language {
        case .ptBR: return .init(title: "Calendário", description: "Sua agenda local e links de reunião na barra de menus.", showInMenuBar: "Mostrar Calendário na barra de menus", accessRequired: "O acesso ao Calendário é necessário.", openPreferences: "Abrir Preferências", appearance: "Aparência", menuBarStyle: "Estilo da barra de menus", textScale: "Escala do texto", meetingAlerts: "Alertas de reunião", alerts: "Alertas de reunião", notifyBefore: "Avisar antes", calendars: "Calendários", noEvents: "Nenhum evento", join: "Entrar", openInCalendar: "Abrir no Calendário", allDay: "Dia todo", agenda: "Agenda", showMonthOutline: "Mostrar contorno do mês", showDeclinedEvents: "Mostrar eventos recusados", eventDots: "Indicadores de eventos", eventDotsNone: "Sem indicadores", eventDotsSingleNeutral: "Um ponto discreto", eventDotsSingleHighlighted: "Um ponto destacado", eventDotsMultiple: "Vários pontos", menuBarComponents: "Componentes da barra de menus", showAdjacentDays: "Mostrar dias adjacentes", componentIcon: "Ícone", componentDate: "Data", componentNextEvent: "Próximo evento", menuBarDateFormat: "Formato da data", customDatePattern: "Padrão Unicode (ex.: dd/MM)", moveUp: "Mover para cima", moveDown: "Mover para baixo", newEvent: "Novo evento", start: "Início", end: "Fim", cancel: "Cancelar", save: "Salvar", calendarLabel: "Calendário", quickAddPlaceholder: "Ex.: Reunião amanhã às 15:00 por 1 hora /Trabalho", durationZero: "0 minutos", durationMinute: "minuto", durationMinutes: "minutos", durationHour: "hora", durationHours: "horas", durationDay: "dia", durationDays: "dias")
        case .es: return .init(title: "Calendario", description: "Tu agenda local y enlaces de reuniones en la barra de menús.", showInMenuBar: "Mostrar Calendario en la barra de menús", accessRequired: "Se requiere acceso al Calendario.", openPreferences: "Abrir Preferencias", appearance: "Apariencia", menuBarStyle: "Estilo de la barra de menús", textScale: "Escala del texto", meetingAlerts: "Alertas de reuniones", alerts: "Alertas de reuniones", notifyBefore: "Avisar antes", calendars: "Calendarios", noEvents: "Sin eventos", join: "Unirse", openInCalendar: "Abrir en Calendario", allDay: "Todo el día", agenda: "Agenda", showMonthOutline: "Mostrar contorno del mes", showDeclinedEvents: "Mostrar eventos rechazados", eventDots: "Indicadores de eventos", eventDotsNone: "Sin indicadores", eventDotsSingleNeutral: "Un punto discreto", eventDotsSingleHighlighted: "Un punto destacado", eventDotsMultiple: "Varios puntos", menuBarComponents: "Componentes de la barra de menús", showAdjacentDays: "Mostrar días adyacentes", componentIcon: "Ícono", componentDate: "Fecha", componentNextEvent: "Próximo evento", menuBarDateFormat: "Formato de la fecha", customDatePattern: "Patrón Unicode (p. ej. dd/MM)", moveUp: "Mover arriba", moveDown: "Mover abajo", newEvent: "Nuevo evento", start: "Inicio", end: "Fin", cancel: "Cancelar", save: "Guardar", calendarLabel: "Calendario", quickAddPlaceholder: "Ej.: Reunión mañana a las 15:00 por 1 hora /Trabajo", durationZero: "0 minutos", durationMinute: "minuto", durationMinutes: "minutos", durationHour: "hora", durationHours: "horas", durationDay: "día", durationDays: "días")
        case .fr: return .init(title: "Calendrier", description: "Votre agenda local et vos liens de réunion dans la barre des menus.", showInMenuBar: "Afficher le calendrier dans la barre des menus", accessRequired: "L’accès au calendrier est requis.", openPreferences: "Ouvrir les réglages", appearance: "Apparence", menuBarStyle: "Style de la barre des menus", textScale: "Échelle du texte", meetingAlerts: "Alertes de réunion", alerts: "Alertes de réunion", notifyBefore: "Prévenir avant", calendars: "Calendriers", noEvents: "Aucun événement", join: "Rejoindre", openInCalendar: "Ouvrir dans Calendrier", allDay: "Toute la journée", agenda: "Agenda", showMonthOutline: "Afficher le contour du mois", showDeclinedEvents: "Afficher les événements refusés", eventDots: "Indicateurs d’événements", eventDotsNone: "Aucun indicateur", eventDotsSingleNeutral: "Un point discret", eventDotsSingleHighlighted: "Un point mis en avant", eventDotsMultiple: "Plusieurs points", menuBarComponents: "Composants de la barre des menus", showAdjacentDays: "Afficher les jours adjacents", componentIcon: "Icône", componentDate: "Date", componentNextEvent: "Prochain événement", menuBarDateFormat: "Format de la date", customDatePattern: "Modèle Unicode (ex. dd/MM)", moveUp: "Monter", moveDown: "Descendre", newEvent: "Nouvel événement", start: "Début", end: "Fin", cancel: "Annuler", save: "Enregistrer", calendarLabel: "Calendrier", quickAddPlaceholder: "Ex. Réunion demain à 15 h pendant 1 heure /Travail", durationZero: "0 minute", durationMinute: "minute", durationMinutes: "minutes", durationHour: "heure", durationHours: "heures", durationDay: "jour", durationDays: "jours")
        case .enUS: return .init(title: "Calendar", description: "Your local agenda and meeting links in the menu bar.", showInMenuBar: "Show Calendar in menu bar", accessRequired: "Calendar access is required.", openPreferences: "Open Preferences", appearance: "Appearance", menuBarStyle: "Menu bar style", textScale: "Text scale", meetingAlerts: "Meeting alerts", alerts: "Meeting alerts", notifyBefore: "Notify before", calendars: "Calendars", noEvents: "No events", join: "Join", openInCalendar: "Open in Calendar", allDay: "All day", agenda: "Agenda", showMonthOutline: "Show month outline", showDeclinedEvents: "Show declined events", eventDots: "Event dots", eventDotsNone: "No dots", eventDotsSingleNeutral: "Single neutral dot", eventDotsSingleHighlighted: "Single highlighted dot", eventDotsMultiple: "Multiple dots", menuBarComponents: "Menu bar components", showAdjacentDays: "Show adjacent days", componentIcon: "Icon", componentDate: "Date", componentNextEvent: "Next event", menuBarDateFormat: "Date format", customDatePattern: "Unicode pattern (e.g. dd/MM)", moveUp: "Move up", moveDown: "Move down", newEvent: "New event", start: "Start", end: "End", cancel: "Cancel", save: "Save", calendarLabel: "Calendar", quickAddPlaceholder: "e.g. Team meeting tomorrow at 3 PM for 1 hour /Work", durationZero: "0 minutes", durationMinute: "minute", durationMinutes: "minutes", durationHour: "hour", durationHours: "hours", durationDay: "day", durationDays: "days")
        case .de: return .init(title: "Kalender", description: "Ihr lokaler Kalender und Besprechungslinks in der Menüleiste.", showInMenuBar: "Kalender in der Menüleiste anzeigen", accessRequired: "Kalenderzugriff ist erforderlich.", openPreferences: "Einstellungen öffnen", appearance: "Darstellung", menuBarStyle: "Menüleistenstil", textScale: "Textgröße", meetingAlerts: "Besprechungserinnerungen", alerts: "Erinnerungen", notifyBefore: "Vorher benachrichtigen", calendars: "Kalender", noEvents: "Keine Ereignisse", join: "Beitreten", openInCalendar: "In Kalender öffnen", allDay: "Ganztägig", agenda: "Tagesordnung", showMonthOutline: "Monatsumriss anzeigen", showDeclinedEvents: "Abgelehnte Ereignisse anzeigen", eventDots: "Ereignispunkte", eventDotsNone: "Keine Punkte", eventDotsSingleNeutral: "Ein dezenter Punkt", eventDotsSingleHighlighted: "Ein hervorgehobener Punkt", eventDotsMultiple: "Mehrere Punkte", menuBarComponents: "Menüleistenkomponenten", showAdjacentDays: "Angrenzende Tage anzeigen", componentIcon: "Symbol", componentDate: "Datum", componentNextEvent: "Nächstes Ereignis", menuBarDateFormat: "Datumsformat", customDatePattern: "Unicode-Muster (z. B. dd/MM)", moveUp: "Nach oben", moveDown: "Nach unten", newEvent: "Neues Ereignis", start: "Beginn", end: "Ende", cancel: "Abbrechen", save: "Sichern", calendarLabel: "Kalender", quickAddPlaceholder: "z. B. Besprechung morgen um 15:00 für 1 Stunde /Arbeit", durationZero: "0 Minuten", durationMinute: "Minute", durationMinutes: "Minuten", durationHour: "Stunde", durationHours: "Stunden", durationDay: "Tag", durationDays: "Tage")
        case .it: return .init(title: "Calendario", description: "La tua agenda locale e i link alle riunioni nella barra dei menu.", showInMenuBar: "Mostra Calendario nella barra dei menu", accessRequired: "È necessario l’accesso al Calendario.", openPreferences: "Apri Impostazioni", appearance: "Aspetto", menuBarStyle: "Stile della barra dei menu", textScale: "Scala del testo", meetingAlerts: "Avvisi delle riunioni", alerts: "Avvisi", notifyBefore: "Avvisa prima", calendars: "Calendari", noEvents: "Nessun evento", join: "Partecipa", openInCalendar: "Apri in Calendario", allDay: "Tutto il giorno", agenda: "Agenda", showMonthOutline: "Mostra contorno del mese", showDeclinedEvents: "Mostra eventi rifiutati", eventDots: "Indicatori eventi", eventDotsNone: "Nessun indicatore", eventDotsSingleNeutral: "Un punto discreto", eventDotsSingleHighlighted: "Un punto evidenziato", eventDotsMultiple: "Più punti", menuBarComponents: "Componenti della barra dei menu", showAdjacentDays: "Mostra giorni adiacenti", componentIcon: "Icona", componentDate: "Data", componentNextEvent: "Prossimo evento", menuBarDateFormat: "Formato data", customDatePattern: "Modello Unicode (es. dd/MM)", moveUp: "Sposta su", moveDown: "Sposta giù", newEvent: "Nuovo evento", start: "Inizio", end: "Fine", cancel: "Annulla", save: "Salva", calendarLabel: "Calendario", quickAddPlaceholder: "Es.: Riunione domani alle 15:00 per 1 ora /Lavoro", durationZero: "0 minuti", durationMinute: "minuto", durationMinutes: "minuti", durationHour: "ora", durationHours: "ore", durationDay: "giorno", durationDays: "giorni")
        case .ja: return .init(title: "カレンダー", description: "メニューバーにローカルの予定表と会議リンクを表示します。", showInMenuBar: "メニューバーにカレンダーを表示", accessRequired: "カレンダーへのアクセスが必要です。", openPreferences: "設定を開く", appearance: "外観", menuBarStyle: "メニューバーのスタイル", textScale: "テキストの大きさ", meetingAlerts: "会議の通知", alerts: "通知", notifyBefore: "事前に通知", calendars: "カレンダー", noEvents: "予定はありません", join: "参加", openInCalendar: "カレンダーで開く", allDay: "終日", agenda: "予定", showMonthOutline: "月の枠線を表示", showDeclinedEvents: "辞退した予定を表示", eventDots: "予定のマーカー", eventDotsNone: "マーカーなし", eventDotsSingleNeutral: "控えめな点", eventDotsSingleHighlighted: "強調した点", eventDotsMultiple: "複数の点", menuBarComponents: "メニューバーの項目", showAdjacentDays: "前後の日を表示", componentIcon: "アイコン", componentDate: "日付", componentNextEvent: "次の予定", menuBarDateFormat: "日付形式", customDatePattern: "Unicode パターン（例: dd/MM）", moveUp: "上へ移動", moveDown: "下へ移動", newEvent: "新規予定", start: "開始", end: "終了", cancel: "キャンセル", save: "保存", calendarLabel: "カレンダー", quickAddPlaceholder: "例: 明日15:00から1時間の会議 /仕事", durationZero: "0分", durationMinute: "分", durationMinutes: "分", durationHour: "時間", durationHours: "時間", durationDay: "日", durationDays: "日")
        case .ko: return .init(title: "캘린더", description: "메뉴 막대에서 로컬 일정과 회의 링크를 확인합니다.", showInMenuBar: "메뉴 막대에 캘린더 표시", accessRequired: "캘린더 접근 권한이 필요합니다.", openPreferences: "설정 열기", appearance: "모양", menuBarStyle: "메뉴 막대 스타일", textScale: "텍스트 크기", meetingAlerts: "회의 알림", alerts: "알림", notifyBefore: "미리 알림", calendars: "캘린더", noEvents: "일정 없음", join: "참가", openInCalendar: "캘린더에서 열기", allDay: "하루 종일", agenda: "일정", showMonthOutline: "월 윤곽선 표시", showDeclinedEvents: "거절한 일정 표시", eventDots: "일정 점", eventDotsNone: "점 없음", eventDotsSingleNeutral: "은은한 점 하나", eventDotsSingleHighlighted: "강조된 점 하나", eventDotsMultiple: "여러 점", menuBarComponents: "메뉴 막대 구성 요소", showAdjacentDays: "인접한 날짜 표시", componentIcon: "아이콘", componentDate: "날짜", componentNextEvent: "다음 일정", menuBarDateFormat: "날짜 형식", customDatePattern: "Unicode 패턴(예: dd/MM)", moveUp: "위로 이동", moveDown: "아래로 이동", newEvent: "새 일정", start: "시작", end: "종료", cancel: "취소", save: "저장", calendarLabel: "캘린더", quickAddPlaceholder: "예: 내일 오후 3시 1시간 회의 /업무", durationZero: "0분", durationMinute: "분", durationMinutes: "분", durationHour: "시간", durationHours: "시간", durationDay: "일", durationDays: "일")
        case .ru: return .init(title: "Календарь", description: "Ваш локальный календарь и ссылки на встречи в строке меню.", showInMenuBar: "Показывать календарь в строке меню", accessRequired: "Требуется доступ к Календарю.", openPreferences: "Открыть настройки", appearance: "Внешний вид", menuBarStyle: "Стиль строки меню", textScale: "Масштаб текста", meetingAlerts: "Напоминания о встречах", alerts: "Напоминания", notifyBefore: "Напомнить заранее", calendars: "Календари", noEvents: "Нет событий", join: "Присоединиться", openInCalendar: "Открыть в Календаре", allDay: "Весь день", agenda: "Повестка", showMonthOutline: "Показывать контур месяца", showDeclinedEvents: "Показывать отклонённые события", eventDots: "Индикаторы событий", eventDotsNone: "Без индикаторов", eventDotsSingleNeutral: "Одна ненавязчивая точка", eventDotsSingleHighlighted: "Одна выделенная точка", eventDotsMultiple: "Несколько точек", menuBarComponents: "Компоненты строки меню", showAdjacentDays: "Показывать соседние дни", componentIcon: "Значок", componentDate: "Дата", componentNextEvent: "Следующее событие", menuBarDateFormat: "Формат даты", customDatePattern: "Шаблон Unicode (например, dd/MM)", moveUp: "Переместить вверх", moveDown: "Переместить вниз", newEvent: "Новое событие", start: "Начало", end: "Окончание", cancel: "Отмена", save: "Сохранить", calendarLabel: "Календарь", quickAddPlaceholder: "Например: встреча завтра в 15:00 на 1 час /Работа", durationZero: "0 минут", durationMinute: "мин.", durationMinutes: "мин.", durationHour: "ч.", durationHours: "ч.", durationDay: "день", durationDays: "дней")
        case .tr: return .init(title: "Takvim", description: "Menü çubuğundaki yerel ajandanız ve toplantı bağlantılarınız.", showInMenuBar: "Menü çubuğunda Takvimi göster", accessRequired: "Takvim erişimi gerekli.", openPreferences: "Sistem Ayarlarını Aç", appearance: "Görünüm", menuBarStyle: "Menü çubuğu stili", textScale: "Metin ölçeği", meetingAlerts: "Toplantı uyarıları", alerts: "Uyarılar", notifyBefore: "Önceden bildir", calendars: "Takvimler", noEvents: "Etkinlik yok", join: "Katıl", openInCalendar: "Takvimde aç", allDay: "Tüm gün", agenda: "Ajanda", showMonthOutline: "Ay ana hattını göster", showDeclinedEvents: "Reddedilen etkinlikleri göster", eventDots: "Etkinlik noktaları", eventDotsNone: "Nokta yok", eventDotsSingleNeutral: "Tek nötr nokta", eventDotsSingleHighlighted: "Tek vurgulu nokta", eventDotsMultiple: "Birden çok nokta", menuBarComponents: "Menü çubuğu bileşenleri", showAdjacentDays: "Bitişik günleri göster", componentIcon: "Simge", componentDate: "Tarih", componentNextEvent: "Sonraki etkinlik", menuBarDateFormat: "Tarih biçimi", customDatePattern: "Unicode deseni (ör. dd/MM)", moveUp: "Yukarı taşı", moveDown: "Aşağı taşı", newEvent: "Yeni etkinlik", start: "Başlangıç", end: "Bitiş", cancel: "İptal", save: "Kaydet", calendarLabel: "Takvim", quickAddPlaceholder: "Örn. yarın 15:00’te 1 saatlik toplantı /İş", durationZero: "0 dakika", durationMinute: "dakika", durationMinutes: "dakika", durationHour: "saat", durationHours: "saat", durationDay: "gün", durationDays: "gün")
        case .zhHans: return .init(title: "日历", description: "在菜单栏中查看本地日程和会议链接。", showInMenuBar: "在菜单栏中显示日历", accessRequired: "需要访问日历。", openPreferences: "打开设置", appearance: "外观", menuBarStyle: "菜单栏样式", textScale: "文字缩放", meetingAlerts: "会议提醒", alerts: "提醒", notifyBefore: "提前提醒", calendars: "日历", noEvents: "没有事件", join: "加入", openInCalendar: "在日历中打开", allDay: "全天", agenda: "日程", showMonthOutline: "显示月份轮廓", showDeclinedEvents: "显示已拒绝的事件", eventDots: "事件圆点", eventDotsNone: "无圆点", eventDotsSingleNeutral: "单个低调圆点", eventDotsSingleHighlighted: "单个突出圆点", eventDotsMultiple: "多个圆点", menuBarComponents: "菜单栏组件", showAdjacentDays: "显示相邻日期", componentIcon: "图标", componentDate: "日期", componentNextEvent: "下一个事件", menuBarDateFormat: "日期格式", customDatePattern: "Unicode 模式（例如 dd/MM）", moveUp: "上移", moveDown: "下移", newEvent: "新建事件", start: "开始", end: "结束", cancel: "取消", save: "保存", calendarLabel: "日历", quickAddPlaceholder: "例如：明天 15:00 开会 1 小时 /工作", durationZero: "0 分钟", durationMinute: "分钟", durationMinutes: "分钟", durationHour: "小时", durationHours: "小时", durationDay: "天", durationDays: "天")
        case .zhTW: return .init(title: "行事曆", description: "在選單列中查看本機行程與會議連結。", showInMenuBar: "在選單列顯示行事曆", accessRequired: "需要行事曆存取權。", openPreferences: "打開設定", appearance: "外觀", menuBarStyle: "選單列樣式", textScale: "文字縮放", meetingAlerts: "會議提醒", alerts: "提醒", notifyBefore: "提前提醒", calendars: "行事曆", noEvents: "沒有行程", join: "加入", openInCalendar: "在行事曆中打開", allDay: "全天", agenda: "行程", showMonthOutline: "顯示月份外框", showDeclinedEvents: "顯示已拒絕的行程", eventDots: "行程圓點", eventDotsNone: "無圓點", eventDotsSingleNeutral: "單一低調圓點", eventDotsSingleHighlighted: "單一醒目圓點", eventDotsMultiple: "多個圓點", menuBarComponents: "選單列元件", showAdjacentDays: "顯示相鄰日期", componentIcon: "圖示", componentDate: "日期", componentNextEvent: "下一個行程", menuBarDateFormat: "日期格式", customDatePattern: "Unicode 模式（例如 dd/MM）", moveUp: "向上移動", moveDown: "向下移動", newEvent: "新增行程", start: "開始", end: "結束", cancel: "取消", save: "儲存", calendarLabel: "行事曆", quickAddPlaceholder: "例如：明天 15:00 開會 1 小時 /工作", durationZero: "0 分鐘", durationMinute: "分鐘", durationMinutes: "分鐘", durationHour: "小時", durationHours: "小時", durationDay: "天", durationDays: "天")
        case .zhHK: return .init(title: "日曆", description: "在選單列中查看本機日程和會議連結。", showInMenuBar: "在選單列顯示日曆", accessRequired: "需要日曆存取權。", openPreferences: "打開設定", appearance: "外觀", menuBarStyle: "選單列樣式", textScale: "文字縮放", meetingAlerts: "會議提醒", alerts: "提醒", notifyBefore: "提前提醒", calendars: "日曆", noEvents: "沒有日程", join: "加入", openInCalendar: "在日曆中打開", allDay: "全日", agenda: "日程", showMonthOutline: "顯示月份外框", showDeclinedEvents: "顯示已拒絕的日程", eventDots: "日程圓點", eventDotsNone: "無圓點", eventDotsSingleNeutral: "單一低調圓點", eventDotsSingleHighlighted: "單一醒目圓點", eventDotsMultiple: "多個圓點", menuBarComponents: "選單列元件", showAdjacentDays: "顯示相鄰日期", componentIcon: "圖示", componentDate: "日期", componentNextEvent: "下一個日程", menuBarDateFormat: "日期格式", customDatePattern: "Unicode 模式（例如 dd/MM）", moveUp: "向上移動", moveDown: "向下移動", newEvent: "新增日程", start: "開始", end: "結束", cancel: "取消", save: "儲存", calendarLabel: "日曆", quickAddPlaceholder: "例如：明天 15:00 開會 1 小時 /工作", durationZero: "0 分鐘", durationMinute: "分鐘", durationMinutes: "分鐘", durationHour: "小時", durationHours: "小時", durationDay: "天", durationDays: "天")
        }
    }
}
