// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct ChargeControlFeatureStrings {
    let title: String
    let hubDescription: String
    let showInPanel: String
    let settingsCaption: String
    let enableToggle: String
    let enableCaption: String
    let limitLabel: String
    let sailingMode: String
    let sailingRangeLabel: String
    let sailingCaption: String
    let charging: String
    let holding: String
    let onBattery: String
    let discharging: String
    let notCharging: String
    let allowControl: String
    let approvalCaption: String
    let openSettings: String
    let unsupported: String
    let noBattery: String
    let failed: String
    let safetyCaption: String
    let dischargeToLimit: String
    let stopDischarge: String
    let discharge: String
    let topUp: String
    let stopTopUp: String
    let toppingUp: String
    let calibrationTitle: String
    let calibrationCaption: String
    let startCalibration: String
    let cancelCalibration: String
    let calPhaseCharge: String
    let calPhaseDischarge: String
    let calPhaseChargeAgain: String
    let calPhaseHold: String
    let calPhaseRestore: String
    let calHoldRemainingFormat: String
    let calComplete: String
    let calNeedsPower: String
    let calUnsupportedDischarge: String
}

extension FeatureStrings {
    static func chargeControl(_ language: AppLanguage) -> ChargeControlFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension ChargeControlFeatureStrings {
    static let enUS = ChargeControlFeatureStrings(
        title: "Charge Limit",
        hubDescription: "Stops charging at a level you choose, and can run a full calibration cycle",
        showInPanel: "Show Charge Limit in the panel",
        settingsCaption: "Adds a charge limit dial to the menu bar panel.",
        enableToggle: "Limit charging",
        enableCaption: "The Mac keeps running from the adapter. Charging stops at the limit.",
        limitLabel: "Charge limit",
        sailingMode: "Sailing mode",
        sailingRangeLabel: "Sailing range",
        sailingCaption: "Charging resumes only after the battery falls this far below the limit.",
        charging: "Charging",
        holding: "Holding",
        onBattery: "On battery",
        discharging: "Discharging",
        notCharging: "Not charging",
        allowControl: "Allow charging control",
        approvalCaption: "Allow Vorssaint in Login Items to use the protected charging controller.",
        openSettings: "Open System Settings",
        unsupported: "Charge control is not available on this Mac.",
        noBattery: "This Mac has no internal battery.",
        failed: "Charging could not be changed.",
        safetyCaption: "The limit is enforced while Vorssaint is running. Charging returns to normal if the connection stops, you turn the limit off, or you quit.",
        dischargeToLimit: "Discharge to limit",
        stopDischarge: "Stop discharging",
        discharge: "Discharge",
        topUp: "Top up",
        stopTopUp: "Stop topping up",
        toppingUp: "Topping up",
        calibrationTitle: "Calibration",
        calibrationCaption: "Charges to 100%, discharges to 10%, charges to 100% again, holds for an hour, then returns to your limit. Leave the Mac plugged in. If charging pauses around 80%, turn off Optimized Battery Charging in System Settings.",
        startCalibration: "Start calibration",
        cancelCalibration: "Cancel calibration",
        calPhaseCharge: "Charging to 100%",
        calPhaseDischarge: "Discharging to 10%",
        calPhaseChargeAgain: "Charging to 100% again",
        calPhaseHold: "Holding at 100%",
        calPhaseRestore: "Returning to the charge limit",
        calHoldRemainingFormat: "%d min left",
        calComplete: "Calibration finished.",
        calNeedsPower: "Plug in the adapter to start calibration.",
        calUnsupportedDischarge: "This Mac cannot discharge while plugged in, so calibration is unavailable."
    )

    static let ptBR = ChargeControlFeatureStrings(
        title: "Limite de carga",
        hubDescription: "Interrompe a carga no nível que você escolher e pode rodar um ciclo completo de calibração",
        showInPanel: "Mostrar limite de carga no painel",
        settingsCaption: "Adiciona um seletor de limite de carga ao painel da barra de menus.",
        enableToggle: "Limitar a carga",
        enableCaption: "O Mac continua usando o adaptador. A carga para no limite.",
        limitLabel: "Limite de carga",
        sailingMode: "Modo Sailing",
        sailingRangeLabel: "Faixa do modo Sailing",
        sailingCaption: "A carga só é retomada depois que a bateria cai esta porcentagem abaixo do limite.",
        charging: "Carregando",
        holding: "Mantendo",
        onBattery: "Na bateria",
        discharging: "Descarregando",
        notCharging: "Sem carregar",
        allowControl: "Permitir controle da carga",
        approvalCaption: "Permita o Vorssaint nos Itens de Início para usar o controlador protegido da carga.",
        openSettings: "Abrir Ajustes do Sistema",
        unsupported: "O controle da carga não está disponível neste Mac.",
        noBattery: "Este Mac não tem bateria interna.",
        failed: "Não foi possível alterar a carga.",
        safetyCaption: "O limite vale enquanto o Vorssaint estiver aberto. A carga volta ao normal se a conexão parar, você desligar o limite ou sair.",
        dischargeToLimit: "Descarregar até o limite",
        stopDischarge: "Parar de descarregar",
        discharge: "Descarregar",
        topUp: "Completar",
        stopTopUp: "Parar de completar",
        toppingUp: "Completando",
        calibrationTitle: "Calibração",
        calibrationCaption: "Carrega até 100%, descarrega até 10%, carrega até 100% de novo, espera uma hora e volta ao seu limite. Deixe o Mac ligado na tomada. Se a carga parar perto de 80%, desative a Carga otimizada da bateria em Ajustes do Sistema.",
        startCalibration: "Iniciar calibração",
        cancelCalibration: "Cancelar calibração",
        calPhaseCharge: "Carregando até 100%",
        calPhaseDischarge: "Descarregando até 10%",
        calPhaseChargeAgain: "Carregando até 100% de novo",
        calPhaseHold: "Mantendo em 100%",
        calPhaseRestore: "Voltando ao limite de carga",
        calHoldRemainingFormat: "%d min restantes",
        calComplete: "Calibração concluída.",
        calNeedsPower: "Ligue o adaptador para iniciar a calibração.",
        calUnsupportedDischarge: "Este Mac não consegue descarregar na tomada, então a calibração não está disponível."
    )

    static let tr = ChargeControlFeatureStrings(
        title: "Şarj sınırı",
        hubDescription: "Şarjı seçtiğiniz düzeyde durdurur ve tam bir kalibrasyon döngüsü çalıştırabilir",
        showInPanel: "Şarj sınırını panelde göster",
        settingsCaption: "Menü çubuğu paneline bir şarj sınırı kadranı ekler.",
        enableToggle: "Şarjı sınırla",
        enableCaption: "Mac adaptörden çalışmaya devam eder. Şarj sınırda durur.",
        limitLabel: "Şarj sınırı",
        sailingMode: "Yelken modu",
        sailingRangeLabel: "Yelken aralığı",
        sailingCaption: "Pil, sınırın bu yüzde kadar altına düşmeden şarj yeniden başlamaz.",
        charging: "Şarj oluyor",
        holding: "Korunuyor",
        onBattery: "Pilde",
        discharging: "Deşarj oluyor",
        notCharging: "Şarj olmuyor",
        allowControl: "Şarj denetimine izin ver",
        approvalCaption: "Korumalı şarj denetimini kullanmak için Giriş Öğeleri’nde Vorssaint’e izin verin.",
        openSettings: "Sistem Ayarları’nı aç",
        unsupported: "Şarj denetimi bu Mac’te kullanılamıyor.",
        noBattery: "Bu Mac’te dahili pil yok.",
        failed: "Şarj değiştirilemedi.",
        safetyCaption: "Sınır, Vorssaint açıkken uygulanır. Bağlantı kesilirse, sınırı kapatırsanız veya çıkarsanız şarj normale döner.",
        dischargeToLimit: "Sınıra kadar deşarj et",
        stopDischarge: "Deşarjı durdur",
        discharge: "Deşarj et",
        topUp: "Tam doldur",
        stopTopUp: "Tam doldurmayı durdur",
        toppingUp: "Tam dolduruluyor",
        calibrationTitle: "Kalibrasyon",
        calibrationCaption: "%100’e şarj eder, %10’a deşarj eder, yeniden %100’e şarj eder, bir saat bekler ve sınırınıza döner. Mac’i prize takılı bırakın. Şarj %80 civarında durursa Sistem Ayarları’nda Optimize Edilmiş Pil Şarjı’nı kapatın.",
        startCalibration: "Kalibrasyonu başlat",
        cancelCalibration: "Kalibrasyonu iptal et",
        calPhaseCharge: "%100’e şarj ediliyor",
        calPhaseDischarge: "%10’a deşarj ediliyor",
        calPhaseChargeAgain: "Yeniden %100’e şarj ediliyor",
        calPhaseHold: "%100’de tutuluyor",
        calPhaseRestore: "Şarj sınırına dönülüyor",
        calHoldRemainingFormat: "%d dk kaldı",
        calComplete: "Kalibrasyon bitti.",
        calNeedsPower: "Kalibrasyonu başlatmak için adaptörü takın.",
        calUnsupportedDischarge: "Bu Mac prize takılıyken deşarj olamıyor, bu yüzden kalibrasyon kullanılamıyor."
    )

    static let ru = ChargeControlFeatureStrings(
        title: "Лимит зарядки",
        hubDescription: "Останавливает зарядку на выбранном уровне и может провести полный цикл калибровки",
        showInPanel: "Показывать лимит зарядки в панели",
        settingsCaption: "Добавляет в панель строки меню диск выбора лимита зарядки.",
        enableToggle: "Ограничить зарядку",
        enableCaption: "Mac продолжает работать от адаптера. Зарядка останавливается на лимите.",
        limitLabel: "Лимит зарядки",
        sailingMode: "Режим плавания",
        sailingRangeLabel: "Диапазон плавания",
        sailingCaption: "Зарядка возобновится только после падения заряда на этот процент ниже лимита.",
        charging: "Зарядка",
        holding: "Удержание",
        onBattery: "От батареи",
        discharging: "Разрядка",
        notCharging: "Не заряжается",
        allowControl: "Разрешить управление зарядкой",
        approvalCaption: "Разрешите Vorssaint в объектах входа, чтобы использовать защищённый контроллер зарядки.",
        openSettings: "Открыть Системные настройки",
        unsupported: "Управление зарядкой недоступно на этом Mac.",
        noBattery: "У этого Mac нет встроенной батареи.",
        failed: "Не удалось изменить зарядку.",
        safetyCaption: "Лимит действует, пока запущен Vorssaint. Зарядка возвращается к обычной, если соединение прервётся, вы выключите лимит или выйдете.",
        dischargeToLimit: "Разрядить до лимита",
        stopDischarge: "Остановить разрядку",
        discharge: "Разрядить",
        topUp: "Дозарядить",
        stopTopUp: "Остановить дозарядку",
        toppingUp: "Дозарядка",
        calibrationTitle: "Калибровка",
        calibrationCaption: "Заряжает до 100%, разряжает до 10%, снова заряжает до 100%, держит час и возвращается к вашему лимиту. Оставьте Mac подключённым. Если зарядка останавливается около 80%, отключите оптимизированную зарядку в Системных настройках.",
        startCalibration: "Начать калибровку",
        cancelCalibration: "Отменить калибровку",
        calPhaseCharge: "Зарядка до 100%",
        calPhaseDischarge: "Разрядка до 10%",
        calPhaseChargeAgain: "Повторная зарядка до 100%",
        calPhaseHold: "Удержание на 100%",
        calPhaseRestore: "Возврат к лимиту зарядки",
        calHoldRemainingFormat: "осталось %d мин",
        calComplete: "Калибровка завершена.",
        calNeedsPower: "Подключите адаптер, чтобы начать калибровку.",
        calUnsupportedDischarge: "Этот Mac не может разряжаться от сети, поэтому калибровка недоступна."
    )

    static let es = ChargeControlFeatureStrings(
        title: "Límite de carga",
        hubDescription: "Detiene la carga en el nivel que elijas y puede ejecutar un ciclo completo de calibración",
        showInPanel: "Mostrar el límite de carga en el panel",
        settingsCaption: "Añade un selector de límite de carga al panel de la barra de menús.",
        enableToggle: "Limitar la carga",
        enableCaption: "El Mac sigue usando el adaptador. La carga se detiene en el límite.",
        limitLabel: "Límite de carga",
        sailingMode: "Modo de navegación",
        sailingRangeLabel: "Margen de navegación",
        sailingCaption: "La carga solo se reanuda cuando la batería cae este porcentaje por debajo del límite.",
        charging: "Cargando",
        holding: "Manteniendo",
        onBattery: "Con batería",
        discharging: "Descargando",
        notCharging: "Sin cargar",
        allowControl: "Permitir el control de carga",
        approvalCaption: "Permite Vorssaint en Elementos de inicio para usar el controlador protegido de carga.",
        openSettings: "Abrir Ajustes del Sistema",
        unsupported: "El control de carga no está disponible en este Mac.",
        noBattery: "Este Mac no tiene batería interna.",
        failed: "No se pudo cambiar la carga.",
        safetyCaption: "El límite se aplica mientras Vorssaint está abierto. La carga vuelve a la normalidad si se corta la conexión, desactivas el límite o sales.",
        dischargeToLimit: "Descargar hasta el límite",
        stopDischarge: "Dejar de descargar",
        discharge: "Descargar",
        topUp: "Completar",
        stopTopUp: "Dejar de completar",
        toppingUp: "Completando",
        calibrationTitle: "Calibración",
        calibrationCaption: "Carga al 100%, descarga al 10%, vuelve a cargar al 100%, espera una hora y regresa a tu límite. Deja el Mac enchufado. Si la carga se detiene cerca del 80%, desactiva la Carga optimizada de la batería en Ajustes del Sistema.",
        startCalibration: "Iniciar calibración",
        cancelCalibration: "Cancelar calibración",
        calPhaseCharge: "Cargando al 100%",
        calPhaseDischarge: "Descargando al 10%",
        calPhaseChargeAgain: "Cargando de nuevo al 100%",
        calPhaseHold: "Manteniendo al 100%",
        calPhaseRestore: "Volviendo al límite de carga",
        calHoldRemainingFormat: "%d min restantes",
        calComplete: "Calibración terminada.",
        calNeedsPower: "Enchufa el adaptador para iniciar la calibración.",
        calUnsupportedDischarge: "Este Mac no puede descargarse enchufado, así que la calibración no está disponible."
    )

    static let de = ChargeControlFeatureStrings(
        title: "Ladelimit",
        hubDescription: "Stoppt das Laden auf einem von dir gewählten Stand und kann einen vollen Kalibrierzyklus ausführen",
        showInPanel: "Ladelimit im Panel zeigen",
        settingsCaption: "Fügt dem Menüleisten-Panel eine Ladelimit-Anzeige hinzu.",
        enableToggle: "Laden begrenzen",
        enableCaption: "Der Mac läuft weiter über das Netzteil. Das Laden stoppt am Limit.",
        limitLabel: "Ladelimit",
        sailingMode: "Sailing-Modus",
        sailingRangeLabel: "Sailing-Bereich",
        sailingCaption: "Das Laden wird erst fortgesetzt, wenn die Batterie um diesen Prozentsatz unter das Limit fällt.",
        charging: "Laden",
        holding: "Halten",
        onBattery: "Auf Akku",
        discharging: "Entladen",
        notCharging: "Lädt nicht",
        allowControl: "Ladesteuerung erlauben",
        approvalCaption: "Erlaube Vorssaint unter Anmeldeobjekte, um die geschützte Ladesteuerung zu nutzen.",
        openSettings: "Systemeinstellungen öffnen",
        unsupported: "Die Ladesteuerung ist auf diesem Mac nicht verfügbar.",
        noBattery: "Dieser Mac hat keinen internen Akku.",
        failed: "Das Laden konnte nicht geändert werden.",
        safetyCaption: "Das Limit gilt, solange Vorssaint läuft. Das Laden wird wieder normal, wenn die Verbindung abbricht, du das Limit ausschaltest oder beendest.",
        dischargeToLimit: "Bis zum Limit entladen",
        stopDischarge: "Entladen beenden",
        discharge: "Entladen",
        topUp: "Vollladen",
        stopTopUp: "Vollladen beenden",
        toppingUp: "Vollladen",
        calibrationTitle: "Kalibrierung",
        calibrationCaption: "Lädt auf 100 %, entlädt auf 10 %, lädt erneut auf 100 %, hält eine Stunde und kehrt zu deinem Limit zurück. Lass den Mac am Netz. Wenn das Laden bei etwa 80 % stockt, schalte die optimierte Batterieladung in den Systemeinstellungen aus.",
        startCalibration: "Kalibrierung starten",
        cancelCalibration: "Kalibrierung abbrechen",
        calPhaseCharge: "Laden auf 100 %",
        calPhaseDischarge: "Entladen auf 10 %",
        calPhaseChargeAgain: "Erneut auf 100 % laden",
        calPhaseHold: "Bei 100 % halten",
        calPhaseRestore: "Zurück zum Ladelimit",
        calHoldRemainingFormat: "noch %d Min.",
        calComplete: "Kalibrierung abgeschlossen.",
        calNeedsPower: "Schließe das Netzteil an, um die Kalibrierung zu starten.",
        calUnsupportedDischarge: "Dieser Mac kann am Netz nicht entladen, daher ist die Kalibrierung nicht verfügbar."
    )

    static let fr = ChargeControlFeatureStrings(
        title: "Limite de charge",
        hubDescription: "Arrête la charge au niveau que vous choisissez et peut lancer un cycle complet de calibration",
        showInPanel: "Afficher la limite de charge dans le panneau",
        settingsCaption: "Ajoute un cadran de limite de charge au panneau de la barre des menus.",
        enableToggle: "Limiter la charge",
        enableCaption: "Le Mac continue de fonctionner sur l’adaptateur. La charge s’arrête à la limite.",
        limitLabel: "Limite de charge",
        sailingMode: "Mode navigation",
        sailingRangeLabel: "Plage de navigation",
        sailingCaption: "La charge ne reprend qu’après une baisse de ce pourcentage sous la limite.",
        charging: "En charge",
        holding: "Maintien",
        onBattery: "Sur batterie",
        discharging: "Décharge",
        notCharging: "Pas en charge",
        allowControl: "Autoriser le contrôle de la charge",
        approvalCaption: "Autorisez Vorssaint dans les éléments d’ouverture pour utiliser le contrôleur de charge protégé.",
        openSettings: "Ouvrir Réglages Système",
        unsupported: "Le contrôle de la charge n’est pas disponible sur ce Mac.",
        noBattery: "Ce Mac n’a pas de batterie interne.",
        failed: "Impossible de modifier la charge.",
        safetyCaption: "La limite s’applique tant que Vorssaint est ouvert. La charge redevient normale si la connexion s’arrête, si vous désactivez la limite ou si vous quittez.",
        dischargeToLimit: "Décharger jusqu’à la limite",
        stopDischarge: "Arrêter la décharge",
        discharge: "Décharger",
        topUp: "Compléter",
        stopTopUp: "Arrêter de compléter",
        toppingUp: "Complément",
        calibrationTitle: "Calibration",
        calibrationCaption: "Charge à 100 %, décharge à 10 %, recharge à 100 %, attend une heure, puis revient à votre limite. Laissez le Mac branché. Si la charge s’arrête vers 80 %, désactivez la charge optimisée de la batterie dans Réglages Système.",
        startCalibration: "Démarrer la calibration",
        cancelCalibration: "Annuler la calibration",
        calPhaseCharge: "Charge vers 100 %",
        calPhaseDischarge: "Décharge vers 10 %",
        calPhaseChargeAgain: "Nouvelle charge vers 100 %",
        calPhaseHold: "Maintien à 100 %",
        calPhaseRestore: "Retour à la limite de charge",
        calHoldRemainingFormat: "%d min restantes",
        calComplete: "Calibration terminée.",
        calNeedsPower: "Branchez l’adaptateur pour démarrer la calibration.",
        calUnsupportedDischarge: "Ce Mac ne peut pas se décharger branché, la calibration est donc indisponible."
    )

    static let it = ChargeControlFeatureStrings(
        title: "Limite di carica",
        hubDescription: "Ferma la carica al livello che scegli e può eseguire un ciclo completo di calibrazione",
        showInPanel: "Mostra il limite di carica nel pannello",
        settingsCaption: "Aggiunge un selettore del limite di carica al pannello della barra dei menu.",
        enableToggle: "Limita la carica",
        enableCaption: "Il Mac continua a usare l’adattatore. La carica si ferma al limite.",
        limitLabel: "Limite di carica",
        sailingMode: "Modalità Sailing",
        sailingRangeLabel: "Intervallo Sailing",
        sailingCaption: "La ricarica riprende solo quando la batteria scende di questa percentuale sotto il limite.",
        charging: "In carica",
        holding: "Mantenimento",
        onBattery: "A batteria",
        discharging: "In scarica",
        notCharging: "Non in carica",
        allowControl: "Consenti il controllo della carica",
        approvalCaption: "Consenti Vorssaint in Elementi di login per usare il controller di carica protetto.",
        openSettings: "Apri Impostazioni di Sistema",
        unsupported: "Il controllo della carica non è disponibile su questo Mac.",
        noBattery: "Questo Mac non ha una batteria interna.",
        failed: "Impossibile modificare la carica.",
        safetyCaption: "Il limite vale mentre Vorssaint è aperto. La carica torna normale se la connessione si interrompe, disattivi il limite o esci.",
        dischargeToLimit: "Scarica fino al limite",
        stopDischarge: "Interrompi la scarica",
        discharge: "Scarica",
        topUp: "Completa",
        stopTopUp: "Interrompi il completamento",
        toppingUp: "Completamento",
        calibrationTitle: "Calibrazione",
        calibrationCaption: "Carica al 100%, scarica al 10%, ricarica al 100%, attende un’ora e torna al tuo limite. Lascia il Mac collegato. Se la carica si ferma intorno all’80%, disattiva la ricarica ottimizzata della batteria in Impostazioni di Sistema.",
        startCalibration: "Avvia calibrazione",
        cancelCalibration: "Annulla calibrazione",
        calPhaseCharge: "Carica al 100%",
        calPhaseDischarge: "Scarica al 10%",
        calPhaseChargeAgain: "Di nuovo in carica al 100%",
        calPhaseHold: "Mantenimento al 100%",
        calPhaseRestore: "Ritorno al limite di carica",
        calHoldRemainingFormat: "%d min rimasti",
        calComplete: "Calibrazione completata.",
        calNeedsPower: "Collega l’adattatore per avviare la calibrazione.",
        calUnsupportedDischarge: "Questo Mac non può scaricarsi da collegato, quindi la calibrazione non è disponibile."
    )

    static let ja = ChargeControlFeatureStrings(
        title: "充電上限",
        hubDescription: "選んだ残量で充電を止め、フル校正サイクルも実行できます",
        showInPanel: "パネルに充電上限を表示",
        settingsCaption: "メニューバーのパネルに充電上限のダイヤルを追加します。",
        enableToggle: "充電を制限",
        enableCaption: "Macはアダプタから動作し続けます。充電は上限で止まります。",
        limitLabel: "充電上限",
        sailingMode: "セーリングモード",
        sailingRangeLabel: "セーリング幅",
        sailingCaption: "バッテリー残量が上限からこの割合だけ下がるまで充電を再開しません。",
        charging: "充電中",
        holding: "維持中",
        onBattery: "バッテリ駆動",
        discharging: "放電中",
        notCharging: "充電していません",
        allowControl: "充電制御を許可",
        approvalCaption: "保護された充電コントローラを使うには、ログイン項目でVorssaintを許可してください。",
        openSettings: "システム設定を開く",
        unsupported: "このMacでは充電制御を使えません。",
        noBattery: "このMacには内蔵バッテリがありません。",
        failed: "充電を変更できませんでした。",
        safetyCaption: "上限はVorssaintの起動中に適用されます。接続が切れる、上限をオフにする、終了すると充電は通常に戻ります。",
        dischargeToLimit: "上限まで放電",
        stopDischarge: "放電を停止",
        discharge: "放電",
        topUp: "満充電",
        stopTopUp: "満充電をやめる",
        toppingUp: "満充電中",
        calibrationTitle: "校正",
        calibrationCaption: "100%まで充電し、10%まで放電し、再び100%まで充電して1時間保持したあと、設定した上限に戻します。Macを接続したままにしてください。80%付近で充電が止まると、システム設定で最適化されたバッテリー充電をオフにしてください。",
        startCalibration: "校正を開始",
        cancelCalibration: "校正をキャンセル",
        calPhaseCharge: "100%まで充電中",
        calPhaseDischarge: "10%まで放電中",
        calPhaseChargeAgain: "再び100%まで充電中",
        calPhaseHold: "100%で保持中",
        calPhaseRestore: "充電上限に戻しています",
        calHoldRemainingFormat: "残り%d分",
        calComplete: "校正が終わりました。",
        calNeedsPower: "校正を始めるにはアダプタを接続してください。",
        calUnsupportedDischarge: "このMacは接続したまま放電できないため、校正は使えません。"
    )

    static let ko = ChargeControlFeatureStrings(
        title: "충전 한도",
        hubDescription: "선택한 수준에서 충전을 멈추고 전체 보정 주기도 실행할 수 있습니다",
        showInPanel: "패널에 충전 한도 표시",
        settingsCaption: "메뉴 막대 패널에 충전 한도 다이얼을 추가합니다.",
        enableToggle: "충전 제한",
        enableCaption: "Mac은 어댑터로 계속 동작합니다. 충전은 한도에서 멈춥니다.",
        limitLabel: "충전 한도",
        sailingMode: "세일링 모드",
        sailingRangeLabel: "세일링 범위",
        sailingCaption: "배터리가 충전 한도보다 이 비율만큼 낮아진 후에만 충전을 재개합니다.",
        charging: "충전 중",
        holding: "유지 중",
        onBattery: "배터리 사용",
        discharging: "방전 중",
        notCharging: "충전하지 않음",
        allowControl: "충전 제어 허용",
        approvalCaption: "보호된 충전 컨트롤러를 쓰려면 로그인 항목에서 Vorssaint를 허용하세요.",
        openSettings: "시스템 설정 열기",
        unsupported: "이 Mac에서는 충전 제어를 사용할 수 없습니다.",
        noBattery: "이 Mac에는 내장 배터리가 없습니다.",
        failed: "충전을 바꾸지 못했습니다.",
        safetyCaption: "한도는 Vorssaint가 실행 중일 때 적용됩니다. 연결이 끊기거나 한도를 끄거나 종료하면 충전이 원래대로 돌아갑니다.",
        dischargeToLimit: "한도까지 방전",
        stopDischarge: "방전 중지",
        discharge: "방전",
        topUp: "완충",
        stopTopUp: "완충 중지",
        toppingUp: "완충 중",
        calibrationTitle: "보정",
        calibrationCaption: "100%까지 충전하고 10%까지 방전한 뒤 다시 100%까지 충전하고 한 시간 유지한 다음 설정한 한도로 돌아갑니다. Mac을 연결해 두세요. 충전이 80% 근처에서 멈추면 시스템 설정에서 배터리 충전 최적화를 끄세요.",
        startCalibration: "보정 시작",
        cancelCalibration: "보정 취소",
        calPhaseCharge: "100%까지 충전 중",
        calPhaseDischarge: "10%까지 방전 중",
        calPhaseChargeAgain: "다시 100%까지 충전 중",
        calPhaseHold: "100% 유지 중",
        calPhaseRestore: "충전 한도로 돌아가는 중",
        calHoldRemainingFormat: "%d분 남음",
        calComplete: "보정이 끝났습니다.",
        calNeedsPower: "보정을 시작하려면 어댑터를 연결하세요.",
        calUnsupportedDischarge: "이 Mac은 연결한 채로 방전할 수 없어 보정을 사용할 수 없습니다."
    )

    static let zhHans = ChargeControlFeatureStrings(
        title: "充电上限",
        hubDescription: "在你选择的电量停止充电，也可以跑完整的校准循环",
        showInPanel: "在面板中显示充电上限",
        settingsCaption: "在菜单栏面板中加入充电上限转盘。",
        enableToggle: "限制充电",
        enableCaption: "Mac 继续用电源适配器供电。充电会在上限处停止。",
        limitLabel: "充电上限",
        sailingMode: "巡航模式",
        sailingRangeLabel: "巡航区间",
        sailingCaption: "电量降至比充电上限低此百分比后才会恢复充电。",
        charging: "正在充电",
        holding: "保持中",
        onBattery: "使用电池",
        discharging: "正在放电",
        notCharging: "未在充电",
        allowControl: "允许充电控制",
        approvalCaption: "请在登录项中允许 Vorssaint，以便使用受保护的充电控制器。",
        openSettings: "打开系统设置",
        unsupported: "这台 Mac 不支持充电控制。",
        noBattery: "这台 Mac 没有内置电池。",
        failed: "无法更改充电。",
        safetyCaption: "上限仅在 Vorssaint 运行时生效。连接中断、关闭上限或退出后，充电会恢复正常。",
        dischargeToLimit: "放电到上限",
        stopDischarge: "停止放电",
        discharge: "放电",
        topUp: "充满",
        stopTopUp: "停止充满",
        toppingUp: "正在充满",
        calibrationTitle: "校准",
        calibrationCaption: "充到 100%，放到 10%，再充到 100%，保持一小时，然后回到你的上限。请保持 Mac 接电。如果充电在 80% 左右停下，请在系统设置中关闭优化电池充电。",
        startCalibration: "开始校准",
        cancelCalibration: "取消校准",
        calPhaseCharge: "正在充到 100%",
        calPhaseDischarge: "正在放到 10%",
        calPhaseChargeAgain: "再次充到 100%",
        calPhaseHold: "保持在 100%",
        calPhaseRestore: "正在回到充电上限",
        calHoldRemainingFormat: "还剩 %d 分钟",
        calComplete: "校准已完成。",
        calNeedsPower: "请接上适配器以开始校准。",
        calUnsupportedDischarge: "这台 Mac 无法在接电时放电，因此无法校准。"
    )

    static let zhTW = ChargeControlFeatureStrings(
        title: "充電上限",
        hubDescription: "在你選擇的電量停止充電，也可以執行完整校正循環",
        showInPanel: "在面板中顯示充電上限",
        settingsCaption: "在選單列面板加入充電上限轉盤。",
        enableToggle: "限制充電",
        enableCaption: "Mac 會繼續使用電源轉接器。充電會在上限停止。",
        limitLabel: "充電上限",
        sailingMode: "巡航模式",
        sailingRangeLabel: "巡航區間",
        sailingCaption: "電量降至比充電上限低此百分比後才會恢復充電。",
        charging: "充電中",
        holding: "維持中",
        onBattery: "使用電池",
        discharging: "放電中",
        notCharging: "未在充電",
        allowControl: "允許充電控制",
        approvalCaption: "請在登入項目中允許 Vorssaint，才能使用受保護的充電控制器。",
        openSettings: "打開系統設定",
        unsupported: "這台 Mac 無法使用充電控制。",
        noBattery: "這台 Mac 沒有內建電池。",
        failed: "無法變更充電。",
        safetyCaption: "上限只在 Vorssaint 執行時生效。連線中斷、關閉上限或結束後，充電會恢復正常。",
        dischargeToLimit: "放電到上限",
        stopDischarge: "停止放電",
        discharge: "放電",
        topUp: "充滿",
        stopTopUp: "停止充滿",
        toppingUp: "正在充滿",
        calibrationTitle: "校正",
        calibrationCaption: "充到 100%、放到 10%、再充到 100%，維持一小時後回到你的上限。請讓 Mac 保持接電。若充電在 80% 左右停下，請在系統設定關閉最佳化電池充電。",
        startCalibration: "開始校正",
        cancelCalibration: "取消校正",
        calPhaseCharge: "正在充到 100%",
        calPhaseDischarge: "正在放到 10%",
        calPhaseChargeAgain: "再次充到 100%",
        calPhaseHold: "維持在 100%",
        calPhaseRestore: "正在回到充電上限",
        calHoldRemainingFormat: "還剩 %d 分鐘",
        calComplete: "校正已完成。",
        calNeedsPower: "請接上轉接器以開始校正。",
        calUnsupportedDischarge: "這台 Mac 無法在接電時放電，因此無法校正。"
    )

    static let zhHK = ChargeControlFeatureStrings(
        title: "充電上限",
        hubDescription: "喺你揀嘅電量停充電，亦可以跑完整校正循環",
        showInPanel: "喺面板顯示充電上限",
        settingsCaption: "喺選單列面板加入充電上限轉盤。",
        enableToggle: "限制充電",
        enableCaption: "Mac 會繼續用電源轉換器。充電會喺上限停。",
        limitLabel: "充電上限",
        sailingMode: "巡航模式",
        sailingRangeLabel: "巡航區間",
        sailingCaption: "電量降至比充電上限低此百分比後才會恢復充電。",
        charging: "充電中",
        holding: "維持中",
        onBattery: "用電池",
        discharging: "放電中",
        notCharging: "未有充電",
        allowControl: "允許充電控制",
        approvalCaption: "請喺登入項目允許 Vorssaint，先至用到受保護嘅充電控制器。",
        openSettings: "打開系統設定",
        unsupported: "呢部 Mac 用唔到充電控制。",
        noBattery: "呢部 Mac 冇內置電池。",
        failed: "無法更改充電。",
        safetyCaption: "上限只喺 Vorssaint 開緊嗰陣生效。連線中斷、關閉上限或者退出之後，充電會回復正常。",
        dischargeToLimit: "放電到上限",
        stopDischarge: "停止放電",
        discharge: "放電",
        topUp: "充滿",
        stopTopUp: "停止充滿",
        toppingUp: "正充滿",
        calibrationTitle: "校正",
        calibrationCaption: "充到 100%、放到 10%、再充到 100%，維持一個鐘之後返到你嘅上限。請讓 Mac 保持接電。如果充電喺 80% 左右停下，請喺系統設定關閉優化電池充電。",
        startCalibration: "開始校正",
        cancelCalibration: "取消校正",
        calPhaseCharge: "正充到 100%",
        calPhaseDischarge: "正放到 10%",
        calPhaseChargeAgain: "再次充到 100%",
        calPhaseHold: "維持喺 100%",
        calPhaseRestore: "正返回充電上限",
        calHoldRemainingFormat: "仲有 %d 分鐘",
        calComplete: "校正完成。",
        calNeedsPower: "請接上轉換器先開始校正。",
        calUnsupportedDischarge: "呢部 Mac 接住電都放唔到電，所以校正用唔到。"
    )

}
