// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct ClaudeApprovalStrings {
    let title: String
    let hubDescription: String
    let toggle: String
    let explanation: String
    let newSessionsOnly: String
    let statusNotInstalledFormat: String
    let statusInstalledFormat: String
    let statusOtherCopy: String
    let statusUnreadableFormat: String
    let install: String
    let update: String
    let remove: String
    let reviewTitleFormat: String
    let reviewNote: String
    let confirmInstall: String
    let confirmRemove: String
    let cancel: String
    let foreignHooksFormat: String
    let socketTooLong: String
    let writeFailedFormat: String
    let deny: String
    let always: String
    let allow: String
    let alwaysHelp: String
    let requestLabelFormat: String
    let questionLabelFormat: String
    let planLabelFormat: String
    let other: String
    let otherPlaceholder: String
    let answer: String
    let approve: String
    let approveAcceptEdits: String
    let approveAcceptEditsHelp: String
    let keepPlanning: String
    let planFallbackTitle: String
    let codexUntested: String
}

extension FeatureStrings {
    static func claudeApprovals(_ language: AppLanguage) -> ClaudeApprovalStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .uk: return .uk
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension ClaudeApprovalStrings {
    static let enUS = ClaudeApprovalStrings(
        title: "Agent Approvals",
        hubDescription: "Answer Claude Code and Codex permission requests, questions and plans from the Dynamic Island",
        toggle: "Ask in the Dynamic Island",
        explanation: "When Claude Code or Codex asks for permission, the island opens with the project, the tool and the command. Claude Code questions and plans open there too. The terminal prompt stays available, and a request nobody answers goes back to it.",
        newSessionsOnly: "Claude Code and Codex read hooks when a session starts, so only sessions started after a change use them.",
        statusNotInstalledFormat: "Not installed in %@",
        statusInstalledFormat: "Installed in %@",
        statusOtherCopy: "Installed for another copy of Vorssaint",
        statusUnreadableFormat: "%@ is not valid JSON, so it is left untouched.",
        install: "Install…",
        update: "Update…",
        remove: "Remove…",
        reviewTitleFormat: "Changes to %@",
        reviewNote: "The current file is copied next to it first. Key order and spacing are normalized.",
        confirmInstall: "Install",
        confirmRemove: "Remove",
        cancel: "Cancel",
        foreignHooksFormat: "Another tool also answers permission requests: %@. Two answers at once are unpredictable, so turn one of them off.",
        socketTooLong: "The app’s support folder path is too long for a local socket, so approvals cannot run.",
        writeFailedFormat: "%@ could not be written.",
        deny: "Deny",
        always: "Always",
        allow: "Allow",
        alwaysHelp: "Allow, and add a rule so Claude Code stops asking for this",
        requestLabelFormat: "%@ asks for permission",
        questionLabelFormat: "%@ asks a question",
        planLabelFormat: "%@ proposes a plan",
        other: "Other",
        otherPlaceholder: "Your answer",
        answer: "Answer",
        approve: "Approve",
        approveAcceptEdits: "Approve, auto-accept edits",
        approveAcceptEditsHelp: "Approve and let this session edit files without asking",
        keepPlanning: "Keep planning",
        planFallbackTitle: "Plan",
        codexUntested: "Codex support follows its documentation and has not been checked against a real session yet.")

    static let ptBR = ClaudeApprovalStrings(
        title: "Aprovações de agentes",
        hubDescription: "Responda aos pedidos de permissão, perguntas e planos do Claude Code e do Codex na Dynamic Island",
        toggle: "Perguntar na Dynamic Island",
        explanation: "Quando o Claude Code ou o Codex pede permissão, a ilha abre com o projeto, a ferramenta e o comando. As perguntas e os planos do Claude Code também abrem ali. O aviso do terminal continua disponível, e um pedido sem resposta volta para ele.",
        newSessionsOnly: "O Claude Code e o Codex leem os hooks quando uma sessão começa, então só as sessões iniciadas depois de uma alteração os usam.",
        statusNotInstalledFormat: "Não instalado no %@",
        statusInstalledFormat: "Instalado no %@",
        statusOtherCopy: "Instalado para outra cópia do Vorssaint",
        statusUnreadableFormat: "%@ não é um JSON válido, então não é alterado.",
        install: "Instalar…",
        update: "Atualizar…",
        remove: "Remover…",
        reviewTitleFormat: "Alterações em %@",
        reviewNote: "O arquivo atual é copiado ao lado dele antes. A ordem das chaves e os espaços são normalizados.",
        confirmInstall: "Instalar",
        confirmRemove: "Remover",
        cancel: "Cancelar",
        foreignHooksFormat: "Outra ferramenta também responde aos pedidos de permissão: %@. Duas respostas ao mesmo tempo são imprevisíveis, então desative uma delas.",
        socketTooLong: "O caminho da pasta de suporte do app é longo demais para um socket local, então as aprovações não podem funcionar.",
        writeFailedFormat: "Não foi possível gravar %@.",
        deny: "Negar",
        always: "Sempre",
        allow: "Permitir",
        alwaysHelp: "Permitir e adicionar uma regra para o Claude Code não perguntar mais sobre isso",
        requestLabelFormat: "O %@ pede permissão",
        questionLabelFormat: "O %@ faz uma pergunta",
        planLabelFormat: "O %@ propõe um plano",
        other: "Outro",
        otherPlaceholder: "Sua resposta",
        answer: "Responder",
        approve: "Aprovar",
        approveAcceptEdits: "Aprovar e aceitar edições",
        approveAcceptEditsHelp: "Aprovar e deixar esta sessão editar arquivos sem perguntar",
        keepPlanning: "Continuar planejando",
        planFallbackTitle: "Plano",
        codexUntested: "O suporte ao Codex segue a documentação dele e ainda não foi verificado com uma sessão real.")

    static let tr = ClaudeApprovalStrings(
        title: "Ajan Onayları",
        hubDescription: "Claude Code ve Codex izin isteklerini, sorularını ve planlarını Dynamic Island’dan yanıtlayın",
        toggle: "Dynamic Island’da sor",
        explanation: "Claude Code veya Codex izin istediğinde ada; proje, araç ve komutla açılır. Claude Code soruları ve planları da orada açılır. Terminaldeki istem kullanılabilir kalır ve yanıtlanmayan bir istek ona geri döner.",
        newSessionsOnly: "Claude Code ve Codex kancaları oturum başlarken okur, bu yüzden yalnızca değişiklikten sonra başlayan oturumlar bunları kullanır.",
        statusNotInstalledFormat: "%@: kurulu değil",
        statusInstalledFormat: "%@: kurulu",
        statusOtherCopy: "Vorssaint’in başka bir kopyası için kurulu",
        statusUnreadableFormat: "%@ geçerli bir JSON değil, bu yüzden değiştirilmez.",
        install: "Kur…",
        update: "Güncelle…",
        remove: "Kaldır…",
        reviewTitleFormat: "%@ dosyasındaki değişiklikler",
        reviewNote: "Mevcut dosya önce yanına kopyalanır. Anahtar sırası ve boşluklar düzenlenir.",
        confirmInstall: "Kur",
        confirmRemove: "Kaldır",
        cancel: "Vazgeç",
        foreignHooksFormat: "Başka bir araç da izin isteklerini yanıtlıyor: %@. Aynı anda iki yanıt öngörülemez, bu yüzden birini kapatın.",
        socketTooLong: "Uygulamanın destek klasörü yolu yerel bir soket için çok uzun, bu yüzden onaylar çalışamaz.",
        writeFailedFormat: "%@ yazılamadı.",
        deny: "Reddet",
        always: "Her Zaman",
        allow: "İzin Ver",
        alwaysHelp: "İzin ver ve Claude Code’un bunu bir daha sormaması için bir kural ekle",
        requestLabelFormat: "%@ izin istiyor",
        questionLabelFormat: "%@ bir soru soruyor",
        planLabelFormat: "%@ bir plan öneriyor",
        other: "Diğer",
        otherPlaceholder: "Yanıtınız",
        answer: "Yanıtla",
        approve: "Onayla",
        approveAcceptEdits: "Onayla, düzenlemeleri otomatik kabul et",
        approveAcceptEditsHelp: "Onayla ve bu oturumun dosyaları sormadan düzenlemesine izin ver",
        keepPlanning: "Planlamaya devam et",
        planFallbackTitle: "Plan",
        codexUntested: "Codex desteği belgelerine dayanır ve henüz gerçek bir oturumla denenmedi.")

    static let ru = ClaudeApprovalStrings(
        title: "Разрешения агентов",
        hubDescription: "Отвечайте на запросы разрешений, вопросы и планы Claude Code и Codex в Dynamic Island",
        toggle: "Спрашивать в Dynamic Island",
        explanation: "Когда Claude Code или Codex запрашивает разрешение, остров открывается с проектом, инструментом и командой. Вопросы и планы Claude Code тоже открываются там. Запрос в терминале остаётся доступен, а запрос без ответа возвращается туда.",
        newSessionsOnly: "Claude Code и Codex читают хуки при запуске сеанса, поэтому изменение действует только в сеансах, начатых после него.",
        statusNotInstalledFormat: "Не установлено в %@",
        statusInstalledFormat: "Установлено в %@",
        statusOtherCopy: "Установлено для другой копии Vorssaint",
        statusUnreadableFormat: "%@ не является корректным JSON, поэтому файл не изменяется.",
        install: "Установить…",
        update: "Обновить…",
        remove: "Удалить…",
        reviewTitleFormat: "Изменения в %@",
        reviewNote: "Сначала текущий файл копируется рядом. Порядок ключей и отступы нормализуются.",
        confirmInstall: "Установить",
        confirmRemove: "Удалить",
        cancel: "Отменить",
        foreignHooksFormat: "Другой инструмент тоже отвечает на запросы разрешений: %@. Два ответа одновременно непредсказуемы, поэтому отключите один из них.",
        socketTooLong: "Путь к папке поддержки приложения слишком длинный для локального сокета, поэтому разрешения не работают.",
        writeFailedFormat: "Не удалось записать %@.",
        deny: "Запретить",
        always: "Всегда",
        allow: "Разрешить",
        alwaysHelp: "Разрешить и добавить правило, чтобы Claude Code больше не спрашивал об этом",
        requestLabelFormat: "%@ запрашивает разрешение",
        questionLabelFormat: "%@ задаёт вопрос",
        planLabelFormat: "%@ предлагает план",
        other: "Другое",
        otherPlaceholder: "Ваш ответ",
        answer: "Ответить",
        approve: "Одобрить",
        approveAcceptEdits: "Одобрить и принимать правки",
        approveAcceptEditsHelp: "Одобрить и разрешить этому сеансу менять файлы без вопросов",
        keepPlanning: "Продолжить планирование",
        planFallbackTitle: "План",
        codexUntested: "Поддержка Codex основана на его документации и ещё не проверена на реальном сеансе.")

    static let es = ClaudeApprovalStrings(
        title: "Aprobaciones de agentes",
        hubDescription: "Responde a las solicitudes de permiso, preguntas y planes de Claude Code y Codex desde la Dynamic Island",
        toggle: "Preguntar en la Dynamic Island",
        explanation: "Cuando Claude Code o Codex pide permiso, la isla se abre con el proyecto, la herramienta y el comando. Las preguntas y los planes de Claude Code también se abren ahí. El aviso del terminal sigue disponible, y una solicitud sin respuesta vuelve a él.",
        newSessionsOnly: "Claude Code y Codex leen los hooks al empezar una sesión, así que solo las sesiones iniciadas después de un cambio los usan.",
        statusNotInstalledFormat: "No instalado en %@",
        statusInstalledFormat: "Instalado en %@",
        statusOtherCopy: "Instalado para otra copia de Vorssaint",
        statusUnreadableFormat: "%@ no es un JSON válido, así que no se modifica.",
        install: "Instalar…",
        update: "Actualizar…",
        remove: "Quitar…",
        reviewTitleFormat: "Cambios en %@",
        reviewNote: "Primero se copia el archivo actual a su lado. El orden de las claves y los espacios se normalizan.",
        confirmInstall: "Instalar",
        confirmRemove: "Quitar",
        cancel: "Cancelar",
        foreignHooksFormat: "Otra herramienta también responde a las solicitudes de permiso: %@. Dos respuestas a la vez son impredecibles, así que desactiva una de ellas.",
        socketTooLong: "La ruta de la carpeta de soporte de la app es demasiado larga para un socket local, así que las aprobaciones no pueden funcionar.",
        writeFailedFormat: "No se pudo escribir %@.",
        deny: "Denegar",
        always: "Siempre",
        allow: "Permitir",
        alwaysHelp: "Permitir y añadir una regla para que Claude Code deje de preguntar por esto",
        requestLabelFormat: "%@ pide permiso",
        questionLabelFormat: "%@ hace una pregunta",
        planLabelFormat: "%@ propone un plan",
        other: "Otro",
        otherPlaceholder: "Tu respuesta",
        answer: "Responder",
        approve: "Aprobar",
        approveAcceptEdits: "Aprobar y aceptar ediciones",
        approveAcceptEditsHelp: "Aprobar y dejar que esta sesión edite archivos sin preguntar",
        keepPlanning: "Seguir planificando",
        planFallbackTitle: "Plan",
        codexUntested: "La compatibilidad con Codex sigue su documentación y aún no se ha comprobado con una sesión real.")

    static let sk = ClaudeApprovalStrings(
        title: "Schválenia agentov",
        hubDescription: "Odpovedajte na žiadosti o povolenie, otázky a plány Claude Code a Codex v Dynamic Island",
        toggle: "Pýtať sa v Dynamic Island",
        explanation: "Keď Claude Code alebo Codex žiada o povolenie, ostrov sa otvorí s projektom, nástrojom a príkazom. Otvoria sa tam aj otázky a plány Claude Code. Výzva v termináli zostáva dostupná a nezodpovedaná žiadosť sa vráti do nej.",
        newSessionsOnly: "Claude Code a Codex načítavajú hooky pri spustení relácie, takže zmenu použijú len relácie spustené po nej.",
        statusNotInstalledFormat: "Nie je nainštalované v %@",
        statusInstalledFormat: "Nainštalované v %@",
        statusOtherCopy: "Nainštalované pre inú kópiu Vorssaint",
        statusUnreadableFormat: "%@ nie je platný JSON, preto sa nemení.",
        install: "Nainštalovať…",
        update: "Aktualizovať…",
        remove: "Odstrániť…",
        reviewTitleFormat: "Zmeny v %@",
        reviewNote: "Aktuálny súbor sa najprv skopíruje vedľa neho. Poradie kľúčov a medzery sa normalizujú.",
        confirmInstall: "Nainštalovať",
        confirmRemove: "Odstrániť",
        cancel: "Zrušiť",
        foreignHooksFormat: "Na žiadosti o povolenie odpovedá aj iný nástroj: %@. Dve odpovede naraz sú nepredvídateľné, preto jeden z nich vypnite.",
        socketTooLong: "Cesta k podpornému priečinku aplikácie je pre lokálny socket príliš dlhá, preto schválenia nemôžu fungovať.",
        writeFailedFormat: "Súbor %@ sa nepodarilo zapísať.",
        deny: "Zamietnuť",
        always: "Vždy",
        allow: "Povoliť",
        alwaysHelp: "Povoliť a pridať pravidlo, aby sa Claude Code na toto už nepýtal",
        requestLabelFormat: "%@ žiada o povolenie",
        questionLabelFormat: "%@ kladie otázku",
        planLabelFormat: "%@ navrhuje plán",
        other: "Iné",
        otherPlaceholder: "Vaša odpoveď",
        answer: "Odpovedať",
        approve: "Schváliť",
        approveAcceptEdits: "Schváliť a prijímať úpravy",
        approveAcceptEditsHelp: "Schváliť a nechať túto reláciu upravovať súbory bez pýtania",
        keepPlanning: "Plánovať ďalej",
        planFallbackTitle: "Plán",
        codexUntested: "Podpora Codex vychádza z jeho dokumentácie a zatiaľ nebola overená na skutočnej relácii.")

    static let de = ClaudeApprovalStrings(
        title: "Agent-Freigaben",
        hubDescription: "Berechtigungsanfragen, Fragen und Pläne von Claude Code und Codex in der Dynamic Island beantworten",
        toggle: "In der Dynamic Island fragen",
        explanation: "Wenn Claude Code oder Codex um Erlaubnis fragt, öffnet sich die Insel mit Projekt, Werkzeug und Befehl. Fragen und Pläne von Claude Code öffnen sich dort ebenfalls. Die Abfrage im Terminal bleibt verfügbar, und eine unbeantwortete Anfrage geht dorthin zurück.",
        newSessionsOnly: "Claude Code und Codex lesen Hooks beim Start einer Sitzung, daher nutzen nur Sitzungen, die nach einer Änderung starten, sie.",
        statusNotInstalledFormat: "Nicht in %@ installiert",
        statusInstalledFormat: "In %@ installiert",
        statusOtherCopy: "Für eine andere Kopie von Vorssaint installiert",
        statusUnreadableFormat: "%@ ist kein gültiges JSON und bleibt daher unverändert.",
        install: "Installieren…",
        update: "Aktualisieren…",
        remove: "Entfernen…",
        reviewTitleFormat: "Änderungen an %@",
        reviewNote: "Die aktuelle Datei wird zuerst daneben kopiert. Schlüsselreihenfolge und Abstände werden vereinheitlicht.",
        confirmInstall: "Installieren",
        confirmRemove: "Entfernen",
        cancel: "Abbrechen",
        foreignHooksFormat: "Ein anderes Werkzeug beantwortet ebenfalls Berechtigungsanfragen: %@. Zwei Antworten gleichzeitig sind unvorhersehbar, schalte daher eines davon aus.",
        socketTooLong: "Der Pfad zum Support-Ordner der App ist für einen lokalen Socket zu lang, daher können Freigaben nicht laufen.",
        writeFailedFormat: "%@ konnte nicht geschrieben werden.",
        deny: "Ablehnen",
        always: "Immer",
        allow: "Erlauben",
        alwaysHelp: "Erlauben und eine Regel hinzufügen, damit Claude Code hierfür nicht mehr fragt",
        requestLabelFormat: "%@ fragt um Erlaubnis",
        questionLabelFormat: "%@ stellt eine Frage",
        planLabelFormat: "%@ schlägt einen Plan vor",
        other: "Sonstiges",
        otherPlaceholder: "Eigene Antwort",
        answer: "Antworten",
        approve: "Freigeben",
        approveAcceptEdits: "Freigeben, Änderungen automatisch annehmen",
        approveAcceptEditsHelp: "Freigeben und diese Sitzung Dateien ohne Rückfrage bearbeiten lassen",
        keepPlanning: "Weiter planen",
        planFallbackTitle: "Plan",
        codexUntested: "Die Codex-Unterstützung folgt der Codex-Dokumentation und wurde noch nicht mit einer echten Sitzung geprüft.")

    static let fr = ClaudeApprovalStrings(
        title: "Autorisations des agents",
        hubDescription: "Répondez aux demandes d’autorisation, questions et plans de Claude Code et Codex depuis la Dynamic Island",
        toggle: "Demander dans la Dynamic Island",
        explanation: "Quand Claude Code ou Codex demande une autorisation, l’île s’ouvre avec le projet, l’outil et la commande. Les questions et les plans de Claude Code s’y ouvrent aussi. La demande du terminal reste disponible, et une demande sans réponse lui revient.",
        newSessionsOnly: "Claude Code et Codex lisent les hooks au démarrage d’une session, donc seules les sessions lancées après un changement les utilisent.",
        statusNotInstalledFormat: "Non installé dans %@",
        statusInstalledFormat: "Installé dans %@",
        statusOtherCopy: "Installé pour une autre copie de Vorssaint",
        statusUnreadableFormat: "%@ n’est pas un JSON valide, il n’est donc pas modifié.",
        install: "Installer…",
        update: "Mettre à jour…",
        remove: "Retirer…",
        reviewTitleFormat: "Modifications de %@",
        reviewNote: "Le fichier actuel est d’abord copié à côté. L’ordre des clés et les espaces sont normalisés.",
        confirmInstall: "Installer",
        confirmRemove: "Retirer",
        cancel: "Annuler",
        foreignHooksFormat: "Un autre outil répond aussi aux demandes d’autorisation : %@. Deux réponses à la fois sont imprévisibles, désactivez donc l’un des deux.",
        socketTooLong: "Le chemin du dossier de support de l’app est trop long pour un socket local, les autorisations ne peuvent donc pas fonctionner.",
        writeFailedFormat: "Impossible d’écrire %@.",
        deny: "Refuser",
        always: "Toujours",
        allow: "Autoriser",
        alwaysHelp: "Autoriser et ajouter une règle pour que Claude Code ne le demande plus",
        requestLabelFormat: "%@ demande une autorisation",
        questionLabelFormat: "%@ pose une question",
        planLabelFormat: "%@ propose un plan",
        other: "Autre",
        otherPlaceholder: "Votre réponse",
        answer: "Répondre",
        approve: "Approuver",
        approveAcceptEdits: "Approuver, accepter les modifications",
        approveAcceptEditsHelp: "Approuver et laisser cette session modifier les fichiers sans demander",
        keepPlanning: "Continuer à planifier",
        planFallbackTitle: "Plan",
        codexUntested: "La prise en charge de Codex suit sa documentation et n’a pas encore été vérifiée sur une vraie session.")

    static let it = ClaudeApprovalStrings(
        title: "Approvazioni degli agenti",
        hubDescription: "Rispondi alle richieste di autorizzazione, alle domande e ai piani di Claude Code e Codex dalla Dynamic Island",
        toggle: "Chiedi nella Dynamic Island",
        explanation: "Quando Claude Code o Codex chiede un’autorizzazione, l’isola si apre con il progetto, lo strumento e il comando. Anche le domande e i piani di Claude Code si aprono lì. La richiesta nel terminale resta disponibile, e una richiesta senza risposta torna lì.",
        newSessionsOnly: "Claude Code e Codex leggono gli hook all’avvio di una sessione, quindi li usano solo le sessioni avviate dopo una modifica.",
        statusNotInstalledFormat: "Non installato in %@",
        statusInstalledFormat: "Installato in %@",
        statusOtherCopy: "Installato per un’altra copia di Vorssaint",
        statusUnreadableFormat: "%@ non è un JSON valido, quindi non viene modificato.",
        install: "Installa…",
        update: "Aggiorna…",
        remove: "Rimuovi…",
        reviewTitleFormat: "Modifiche a %@",
        reviewNote: "Il file attuale viene prima copiato accanto. L’ordine delle chiavi e gli spazi vengono normalizzati.",
        confirmInstall: "Installa",
        confirmRemove: "Rimuovi",
        cancel: "Annulla",
        foreignHooksFormat: "Anche un altro strumento risponde alle richieste di autorizzazione: %@. Due risposte insieme sono imprevedibili, quindi disattivane uno.",
        socketTooLong: "Il percorso della cartella di supporto dell’app è troppo lungo per un socket locale, quindi le approvazioni non possono funzionare.",
        writeFailedFormat: "Impossibile scrivere %@.",
        deny: "Nega",
        always: "Sempre",
        allow: "Consenti",
        alwaysHelp: "Consenti e aggiungi una regola perché Claude Code non lo chieda più",
        requestLabelFormat: "%@ chiede un’autorizzazione",
        questionLabelFormat: "%@ fa una domanda",
        planLabelFormat: "%@ propone un piano",
        other: "Altro",
        otherPlaceholder: "La tua risposta",
        answer: "Rispondi",
        approve: "Approva",
        approveAcceptEdits: "Approva e accetta le modifiche",
        approveAcceptEditsHelp: "Approva e lascia che questa sessione modifichi i file senza chiedere",
        keepPlanning: "Continua a pianificare",
        planFallbackTitle: "Piano",
        codexUntested: "Il supporto di Codex segue la sua documentazione e non è ancora stato verificato con una sessione reale.")

    static let ja = ClaudeApprovalStrings(
        title: "エージェントの承認",
        hubDescription: "Claude Code と Codex の許可リクエスト、質問、プランに Dynamic Island から応答します",
        toggle: "Dynamic Island で確認",
        explanation: "Claude Code または Codex が許可を求めると、プロジェクト、ツール、コマンドを表示してアイランドが開きます。Claude Code の質問とプランもそこに表示されます。ターミナルの確認もそのまま使え、応答のないリクエストはターミナルに戻ります。",
        newSessionsOnly: "Claude Code と Codex はセッション開始時にフックを読み込むため、変更後に開始したセッションでのみ使われます。",
        statusNotInstalledFormat: "%@ にインストールされていません",
        statusInstalledFormat: "%@ にインストール済み",
        statusOtherCopy: "別の Vorssaint 用にインストール済み",
        statusUnreadableFormat: "%@ が有効な JSON ではないため、変更しません。",
        install: "インストール…",
        update: "更新…",
        remove: "削除…",
        reviewTitleFormat: "%@ の変更内容",
        reviewNote: "先に現在のファイルを同じ場所にコピーします。キーの順序と空白は整えられます。",
        confirmInstall: "インストール",
        confirmRemove: "削除",
        cancel: "キャンセル",
        foreignHooksFormat: "別のツールも許可リクエストに応答しています: %@。同時に 2 つの応答があると結果が予測できないため、どちらかをオフにしてください。",
        socketTooLong: "アプリのサポートフォルダのパスがローカルソケットには長すぎるため、承認を使用できません。",
        writeFailedFormat: "%@ に書き込めませんでした。",
        deny: "拒否",
        always: "常に許可",
        allow: "許可",
        alwaysHelp: "許可し、Claude Code が今後これを確認しないようにルールを追加します",
        requestLabelFormat: "%@ が許可を求めています",
        questionLabelFormat: "%@ が質問しています",
        planLabelFormat: "%@ がプランを提案しています",
        other: "その他",
        otherPlaceholder: "回答を入力",
        answer: "回答",
        approve: "承認",
        approveAcceptEdits: "承認して編集を自動許可",
        approveAcceptEditsHelp: "承認し、このセッションが確認なしでファイルを編集できるようにします",
        keepPlanning: "計画を続ける",
        planFallbackTitle: "プラン",
        codexUntested: "Codex への対応はドキュメントに基づくもので、実際のセッションではまだ確認していません。")

    static let ko = ClaudeApprovalStrings(
        title: "에이전트 승인",
        hubDescription: "Dynamic Island에서 Claude Code와 Codex의 권한 요청, 질문, 계획에 응답합니다",
        toggle: "Dynamic Island에서 묻기",
        explanation: "Claude Code나 Codex가 권한을 요청하면 프로젝트, 도구, 명령과 함께 아일랜드가 열립니다. Claude Code의 질문과 계획도 여기에 열립니다. 터미널의 확인 창도 그대로 사용할 수 있으며, 응답하지 않은 요청은 터미널로 돌아갑니다.",
        newSessionsOnly: "Claude Code와 Codex는 세션을 시작할 때 훅을 읽으므로, 변경 후 시작한 세션에서만 사용됩니다.",
        statusNotInstalledFormat: "%@에 설치되지 않음",
        statusInstalledFormat: "%@에 설치됨",
        statusOtherCopy: "다른 Vorssaint 사본용으로 설치됨",
        statusUnreadableFormat: "%@ 파일이 올바른 JSON이 아니므로 변경하지 않습니다.",
        install: "설치…",
        update: "업데이트…",
        remove: "제거…",
        reviewTitleFormat: "%@ 변경 사항",
        reviewNote: "먼저 현재 파일을 같은 위치에 복사합니다. 키 순서와 공백은 정리됩니다.",
        confirmInstall: "설치",
        confirmRemove: "제거",
        cancel: "취소",
        foreignHooksFormat: "다른 도구도 권한 요청에 응답하고 있습니다: %@. 두 응답이 동시에 오면 결과를 예측할 수 없으므로 하나를 끄세요.",
        socketTooLong: "앱 지원 폴더 경로가 로컬 소켓에 너무 길어 승인을 사용할 수 없습니다.",
        writeFailedFormat: "%@에 쓸 수 없습니다.",
        deny: "거부",
        always: "항상",
        allow: "허용",
        alwaysHelp: "허용하고 Claude Code가 이 항목을 더 묻지 않도록 규칙을 추가합니다",
        requestLabelFormat: "%@에서 권한을 요청합니다",
        questionLabelFormat: "%@에서 질문합니다",
        planLabelFormat: "%@에서 계획을 제안합니다",
        other: "기타",
        otherPlaceholder: "답변 입력",
        answer: "답변",
        approve: "승인",
        approveAcceptEdits: "승인 후 편집 자동 수락",
        approveAcceptEditsHelp: "승인하고 이 세션이 묻지 않고 파일을 편집하도록 허용합니다",
        keepPlanning: "계속 계획",
        planFallbackTitle: "계획",
        codexUntested: "Codex 지원은 문서를 따르며 아직 실제 세션에서 확인하지 않았습니다.")

    static let uk = ClaudeApprovalStrings(
        title: "Дозволи агентів",
        hubDescription: "Відповідайте на запити дозволів, запитання й плани Claude Code і Codex у Dynamic Island",
        toggle: "Питати в Dynamic Island",
        explanation: "Коли Claude Code або Codex просить дозвіл, острів відкривається з проєктом, інструментом і командою. Запитання й плани Claude Code теж відкриваються там. Запит у терміналі залишається доступним, а запит без відповіді повертається туди.",
        newSessionsOnly: "Claude Code і Codex читають хуки під час запуску сеансу, тому зміна діє лише в сеансах, розпочатих після неї.",
        statusNotInstalledFormat: "Не встановлено в %@",
        statusInstalledFormat: "Встановлено в %@",
        statusOtherCopy: "Встановлено для іншої копії Vorssaint",
        statusUnreadableFormat: "%@ не є коректним JSON, тому файл не змінюється.",
        install: "Встановити…",
        update: "Оновити…",
        remove: "Вилучити…",
        reviewTitleFormat: "Зміни в %@",
        reviewNote: "Спершу поточний файл копіюється поруч. Порядок ключів і відступи впорядковуються.",
        confirmInstall: "Встановити",
        confirmRemove: "Вилучити",
        cancel: "Скасувати",
        foreignHooksFormat: "Інший інструмент теж відповідає на запити дозволів: %@. Дві відповіді одночасно непередбачувані, тому вимкніть один із них.",
        socketTooLong: "Шлях до теки підтримки застосунку задовгий для локального сокета, тому дозволи не працюють.",
        writeFailedFormat: "Не вдалося записати %@.",
        deny: "Заборонити",
        always: "Завжди",
        allow: "Дозволити",
        alwaysHelp: "Дозволити й додати правило, щоб Claude Code більше не питав про це",
        requestLabelFormat: "%@ просить дозвіл",
        questionLabelFormat: "%@ ставить запитання",
        planLabelFormat: "%@ пропонує план",
        other: "Інше",
        otherPlaceholder: "Ваша відповідь",
        answer: "Відповісти",
        approve: "Схвалити",
        approveAcceptEdits: "Схвалити й приймати зміни",
        approveAcceptEditsHelp: "Схвалити й дозволити цьому сеансу змінювати файли без запитань",
        keepPlanning: "Планувати далі",
        planFallbackTitle: "План",
        codexUntested: "Підтримка Codex спирається на його документацію і ще не перевірена на справжньому сеансі.")

    static let zhHans = ClaudeApprovalStrings(
        title: "智能体授权",
        hubDescription: "在灵动岛中回应 Claude Code 和 Codex 的权限请求、问题和计划",
        toggle: "在灵动岛中询问",
        explanation: "Claude Code 或 Codex 请求权限时，灵动岛会打开并显示项目、工具和命令。Claude Code 的问题和计划也会在这里打开。终端中的提示仍然可用，无人回应的请求会交还给终端。",
        newSessionsOnly: "Claude Code 和 Codex 在会话开始时读取钩子，因此只有更改后开始的会话才会使用。",
        statusNotInstalledFormat: "未安装到 %@",
        statusInstalledFormat: "已安装到 %@",
        statusOtherCopy: "已为另一份 Vorssaint 安装",
        statusUnreadableFormat: "%@ 不是有效的 JSON，因此不会修改。",
        install: "安装…",
        update: "更新…",
        remove: "移除…",
        reviewTitleFormat: "对 %@ 的更改",
        reviewNote: "会先将当前文件复制到同一位置。键的顺序和空白会被规范化。",
        confirmInstall: "安装",
        confirmRemove: "移除",
        cancel: "取消",
        foreignHooksFormat: "另一个工具也在回应权限请求：%@。同时出现两个回应会导致结果不可预测，请关闭其中一个。",
        socketTooLong: "App 支持文件夹的路径对本地套接字来说太长，因此无法使用授权。",
        writeFailedFormat: "无法写入 %@。",
        deny: "拒绝",
        always: "始终允许",
        allow: "允许",
        alwaysHelp: "允许并添加规则，让 Claude Code 不再询问此项",
        requestLabelFormat: "%@ 请求权限",
        questionLabelFormat: "%@ 提出了一个问题",
        planLabelFormat: "%@ 提出了一个计划",
        other: "其他",
        otherPlaceholder: "你的回答",
        answer: "回答",
        approve: "批准",
        approveAcceptEdits: "批准并自动接受编辑",
        approveAcceptEditsHelp: "批准，并让此会话无需询问即可编辑文件",
        keepPlanning: "继续规划",
        planFallbackTitle: "计划",
        codexUntested: "Codex 支持依据其文档实现，尚未在真实会话中验证。")

    static let zhTW = ClaudeApprovalStrings(
        title: "代理程式授權",
        hubDescription: "在動態島中回應 Claude Code 和 Codex 的權限要求、問題和計畫",
        toggle: "在動態島中詢問",
        explanation: "Claude Code 或 Codex 要求權限時，動態島會打開並顯示專案、工具和指令。Claude Code 的問題和計畫也會在這裡打開。終端機中的提示仍可使用，沒有回應的要求會交回終端機。",
        newSessionsOnly: "Claude Code 和 Codex 會在工作階段開始時讀取掛鉤，因此只有變更後開始的工作階段才會使用。",
        statusNotInstalledFormat: "未安裝到 %@",
        statusInstalledFormat: "已安裝到 %@",
        statusOtherCopy: "已為另一份 Vorssaint 安裝",
        statusUnreadableFormat: "%@ 不是有效的 JSON，因此不會修改。",
        install: "安裝…",
        update: "更新…",
        remove: "移除…",
        reviewTitleFormat: "對 %@ 的變更",
        reviewNote: "會先將目前的檔案複製到同一位置。鍵的順序和空白會被標準化。",
        confirmInstall: "安裝",
        confirmRemove: "移除",
        cancel: "取消",
        foreignHooksFormat: "另一個工具也在回應權限要求：%@。同時出現兩個回應會讓結果無法預測，請關閉其中一個。",
        socketTooLong: "App 支援檔案夾的路徑對本機通訊端來說太長，因此無法使用授權。",
        writeFailedFormat: "無法寫入 %@。",
        deny: "拒絕",
        always: "永遠允許",
        allow: "允許",
        alwaysHelp: "允許並新增規則，讓 Claude Code 不再詢問此項",
        requestLabelFormat: "%@ 要求權限",
        questionLabelFormat: "%@ 提出了一個問題",
        planLabelFormat: "%@ 提出了一個計畫",
        other: "其他",
        otherPlaceholder: "你的回答",
        answer: "回答",
        approve: "核准",
        approveAcceptEdits: "核准並自動接受編輯",
        approveAcceptEditsHelp: "核准，並讓此工作階段無需詢問即可編輯檔案",
        keepPlanning: "繼續規劃",
        planFallbackTitle: "計畫",
        codexUntested: "Codex 支援依據其文件實作，尚未在真實工作階段中驗證。")

    static let zhHK = ClaudeApprovalStrings(
        title: "代理程式授權",
        hubDescription: "在動態島中回應 Claude Code 和 Codex 的權限要求、問題和計劃",
        toggle: "在動態島中詢問",
        explanation: "Claude Code 或 Codex 要求權限時，動態島會打開並顯示項目、工具和指令。Claude Code 的問題和計劃也會在這裡打開。終端機中的提示仍可使用，沒有回應的要求會交回終端機。",
        newSessionsOnly: "Claude Code 和 Codex 會在工作階段開始時讀取掛鈎，因此只有變更後開始的工作階段才會使用。",
        statusNotInstalledFormat: "未安裝到 %@",
        statusInstalledFormat: "已安裝到 %@",
        statusOtherCopy: "已為另一份 Vorssaint 安裝",
        statusUnreadableFormat: "%@ 不是有效的 JSON，因此不會修改。",
        install: "安裝…",
        update: "更新…",
        remove: "移除…",
        reviewTitleFormat: "對 %@ 的變更",
        reviewNote: "會先將目前的檔案複製到同一位置。鍵的次序和空白會被標準化。",
        confirmInstall: "安裝",
        confirmRemove: "移除",
        cancel: "取消",
        foreignHooksFormat: "另一個工具也在回應權限要求：%@。同時出現兩個回應會令結果無法預測，請關閉其中一個。",
        socketTooLong: "App 支援資料夾的路徑對本機通訊端來說太長，因此無法使用授權。",
        writeFailedFormat: "無法寫入 %@。",
        deny: "拒絕",
        always: "永遠允許",
        allow: "允許",
        alwaysHelp: "允許並新增規則，令 Claude Code 不再詢問此項",
        requestLabelFormat: "%@ 要求權限",
        questionLabelFormat: "%@ 提出了一個問題",
        planLabelFormat: "%@ 提出了一個計劃",
        other: "其他",
        otherPlaceholder: "你的回答",
        answer: "回答",
        approve: "核准",
        approveAcceptEdits: "核准並自動接受編輯",
        approveAcceptEditsHelp: "核准，並讓此工作階段無需詢問即可編輯檔案",
        keepPlanning: "繼續規劃",
        planFallbackTitle: "計劃",
        codexUntested: "Codex 支援依據其文件實作，尚未在真實工作階段中驗證。")
}
