// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct ClipboardImageOptimizerStrings {
    let title: String
    let hubDescription: String
    let enable: String
    let caption: String
    let formatLabel: String
    let formatKeep: String
    let formatJPEG: String
    let formatCaption: String
    let quality: String
    let maxDimension: String
    let maxDimensionOff: String
    let halveRetina: String
    let halveRetinaCaption: String
    let includeFiles: String
    let includeFilesCaption: String
    let imagesToggle: String
    let convertImages: String
    let convertImagesCaption: String
    let videos: String
    let videosCaption: String
    let videoCodec: String
    let codecH264: String
    let codecHEVC: String
    let videoQuality: String
    let videoMaxDimension: String
    let videoMaxDimensionKeep: String
    let removeAudio: String
    let videoMaxSize: String
    let videoMaxDuration: String
    let minutesFormat: String
    let pdfs: String
    let pdfsCaption: String
    let pdfDPI: String
    let dpiFormat: String
    let pdfQuality: String
    let pdfMaxSize: String
    let storageCaption: String
    let clearCopies: String
    let keptBytes: String

    static func localized(_ language: AppLanguage) -> ClipboardImageOptimizerStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension FeatureStrings {
    static func clipboardImageOptimizer(_ language: AppLanguage) -> ClipboardImageOptimizerStrings {
        ClipboardImageOptimizerStrings.localized(language)
    }
}

extension ClipboardImageOptimizerStrings {
    static let enUS = ClipboardImageOptimizerStrings(
        title: "Clipboard optimizer",
        hubDescription: "Copied images, videos and PDFs get smaller",
        enable: "Shrink copied files",
        caption: "With Keep, copied PNG and TIFF images are re-encoded without quality loss when that saves space. JPEG and resizing are lossy. Images copied with text, links or formatting are left alone.",
        formatLabel: "Format",
        formatKeep: "Keep (lossless)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG is much smaller but blurs text. Images with transparency stay PNG.",
        quality: "JPEG quality",
        maxDimension: "Maximum size",
        maxDimensionOff: "Off",
        halveRetina: "Scale Retina images to 1x",
        halveRetinaCaption: "Halves the width and height, like a screenshot taken on a standard display.",
        includeFiles: "Also optimize copied image files",
        includeFilesCaption: "A copied PNG, JPEG or TIFF file is replaced by its optimized image, so pasting in Finder no longer copies the file.",
        imagesToggle: "Images",
        convertImages: "Convert HEIC, WebP, AVIF and BMP files",
        convertImagesCaption: "A copied file becomes a JPEG, or a PNG when it has transparency. Animated, HDR and 10-bit photos, including most iPhone HEIC photos, are left alone. Needs copied image files on.",
        videos: "Videos",
        videosCaption: "A copied MOV, MP4 or M4V file is re-encoded into a smaller copy and the clipboard points at it, so pasting gives the smaller copy. The original file is never changed. Reading a file in Desktop, Documents or Downloads may ask for access once.",
        videoCodec: "Codec",
        codecH264: "H.264 (most compatible)",
        codecHEVC: "HEVC (smaller)",
        videoQuality: "Video quality",
        videoMaxDimension: "Maximum resolution",
        videoMaxDimensionKeep: "Keep",
        removeAudio: "Remove audio",
        videoMaxSize: "Skip videos larger than",
        videoMaxDuration: "Skip videos longer than",
        minutesFormat: "%d min",
        pdfs: "PDFs",
        pdfsCaption: "Images inside a copied PDF are resampled into a smaller copy; text, links and form fields stay as they are. Signed, encrypted, tagged or scripted PDFs are left alone. The original file is never changed.",
        pdfDPI: "Image resolution",
        dpiFormat: "%d dpi",
        pdfQuality: "Image quality",
        pdfMaxSize: "Skip PDFs larger than",
        storageCaption: "Smaller copies of videos, PDFs and converted images are kept in Vorssaint’s Application Support folder, up to 2 GB, and removed after a day unless the clipboard or history still uses them.",
        clearCopies: "Clear optimized copies (%@)",
        keptBytes: "%@ kept for the clipboard and pinned history"
    )

    static let ptBR = ClipboardImageOptimizerStrings(
        title: "Otimizador da área de transferência",
        hubDescription: "Imagens, vídeos e PDFs copiados ficam menores",
        enable: "Reduzir arquivos copiados",
        caption: "Com Manter, imagens PNG e TIFF copiadas são recodificadas sem perda de qualidade quando isso economiza espaço. JPEG e redimensionamento perdem qualidade. Imagens copiadas com texto, links ou formatação não são alteradas.",
        formatLabel: "Formato",
        formatKeep: "Manter (sem perdas)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG fica bem menor, mas borra textos. Imagens com transparência continuam em PNG.",
        quality: "Qualidade do JPEG",
        maxDimension: "Tamanho máximo",
        maxDimensionOff: "Desativado",
        halveRetina: "Reduzir imagens Retina para 1x",
        halveRetinaCaption: "Divide a largura e a altura pela metade, como uma captura feita em uma tela comum.",
        includeFiles: "Otimizar também arquivos de imagem copiados",
        includeFilesCaption: "Um arquivo PNG, JPEG ou TIFF copiado é substituído pela imagem otimizada, então colar no Finder não copia mais o arquivo.",
        imagesToggle: "Imagens",
        convertImages: "Converter arquivos HEIC, WebP, AVIF e BMP",
        convertImagesCaption: "Um arquivo copiado vira JPEG, ou PNG quando tem transparência. Fotos animadas, HDR e de 10 bits, incluindo a maioria das fotos HEIC do iPhone, não são alteradas. Requer a otimização de arquivos de imagem copiados.",
        videos: "Vídeos",
        videosCaption: "Um arquivo MOV, MP4 ou M4V copiado é recodificado em uma cópia menor e a área de transferência passa a apontar para ela, então colar entrega a cópia menor. O arquivo original nunca é alterado. Ler um arquivo em Mesa, Documentos ou Downloads pode pedir acesso uma vez.",
        videoCodec: "Codec",
        codecH264: "H.264 (mais compatível)",
        codecHEVC: "HEVC (menor)",
        videoQuality: "Qualidade do vídeo",
        videoMaxDimension: "Resolução máxima",
        videoMaxDimensionKeep: "Manter",
        removeAudio: "Remover áudio",
        videoMaxSize: "Ignorar vídeos maiores que",
        videoMaxDuration: "Ignorar vídeos mais longos que",
        minutesFormat: "%d min",
        pdfs: "PDFs",
        pdfsCaption: "As imagens dentro de um PDF copiado são reamostradas em uma cópia menor; texto, links e campos de formulário ficam como estão. PDFs assinados, criptografados, com tags ou com scripts não são alterados. O arquivo original nunca é alterado.",
        pdfDPI: "Resolução das imagens",
        dpiFormat: "%d dpi",
        pdfQuality: "Qualidade das imagens",
        pdfMaxSize: "Ignorar PDFs maiores que",
        storageCaption: "As cópias menores de vídeos, PDFs e imagens convertidas ficam na pasta Application Support do Vorssaint, até 2 GB, e são removidas após um dia, a menos que a área de transferência ou o histórico ainda as use.",
        clearCopies: "Apagar cópias otimizadas (%@)",
        keptBytes: "%@ mantidos para a área de transferência e o histórico fixado"
    )

    static let tr = ClipboardImageOptimizerStrings(
        title: "Pano iyileştirici",
        hubDescription: "Kopyalanan resimler, videolar ve PDF’ler küçülür",
        enable: "Kopyalanan dosyaları küçült",
        caption: "Koru seçiliyken kopyalanan PNG ve TIFF resimler, yer kazandırdığında kalite kaybı olmadan yeniden kodlanır. JPEG ve yeniden boyutlandırma kalite kaybettirir. Metin, bağlantı veya biçimlendirmeyle kopyalanan resimlere dokunulmaz.",
        formatLabel: "Biçim",
        formatKeep: "Koru (kayıpsız)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG çok daha küçüktür ama metni bulanıklaştırır. Saydamlığı olan resimler PNG olarak kalır.",
        quality: "JPEG kalitesi",
        maxDimension: "En büyük boyut",
        maxDimensionOff: "Kapalı",
        halveRetina: "Retina resimlerini 1x boyutuna indir",
        halveRetinaCaption: "Genişliği ve yüksekliği yarıya indirir, standart bir ekranda alınmış bir ekran görüntüsü gibi.",
        includeFiles: "Kopyalanan resim dosyalarını da iyileştir",
        includeFilesCaption: "Kopyalanan bir PNG, JPEG veya TIFF dosyası iyileştirilmiş resmiyle değiştirilir; Finder’da yapıştırmak artık dosyayı kopyalamaz.",
        imagesToggle: "Resimler",
        convertImages: "HEIC, WebP, AVIF ve BMP dosyalarını dönüştür",
        convertImagesCaption: "Kopyalanan dosya JPEG’e, saydamlığı varsa PNG’ye dönüşür. Hareketli, HDR ve 10 bit fotoğraflara, iPhone’un çoğu HEIC fotoğrafı dahil, dokunulmaz. Kopyalanan resim dosyalarının açık olmasını gerektirir.",
        videos: "Videolar",
        videosCaption: "Kopyalanan bir MOV, MP4 veya M4V dosyası daha küçük bir kopyaya yeniden kodlanır ve pano bu kopyayı gösterir; yapıştırınca küçük kopya gelir. Özgün dosya hiçbir zaman değiştirilmez. Masaüstü, Belgeler veya İndirilenler’deki bir dosyayı okumak bir kez erişim izni isteyebilir.",
        videoCodec: "Kodek",
        codecH264: "H.264 (en uyumlu)",
        codecHEVC: "HEVC (daha küçük)",
        videoQuality: "Video kalitesi",
        videoMaxDimension: "En yüksek çözünürlük",
        videoMaxDimensionKeep: "Koru",
        removeAudio: "Sesi kaldır",
        videoMaxSize: "Şundan büyük videoları atla",
        videoMaxDuration: "Şundan uzun videoları atla",
        minutesFormat: "%d dk",
        pdfs: "PDF’ler",
        pdfsCaption: "Kopyalanan bir PDF’teki resimler daha küçük bir kopyada yeniden örneklenir; metin, bağlantılar ve form alanları olduğu gibi kalır. İmzalı, şifreli, etiketli veya betik içeren PDF’lere dokunulmaz. Özgün dosya hiçbir zaman değiştirilmez.",
        pdfDPI: "Resim çözünürlüğü",
        dpiFormat: "%d dpi",
        pdfQuality: "Resim kalitesi",
        pdfMaxSize: "Şundan büyük PDF’leri atla",
        storageCaption: "Videoların, PDF’lerin ve dönüştürülen resimlerin küçük kopyaları Vorssaint’in Application Support klasöründe 2 GB’a kadar tutulur ve pano ya da geçmiş hâlâ kullanmıyorsa bir gün sonra silinir.",
        clearCopies: "İyileştirilmiş kopyaları temizle (%@)",
        keptBytes: "%@ pano ve sabitlenmiş geçmiş için tutuluyor"
    )

    static let ru = ClipboardImageOptimizerStrings(
        title: "Оптимизатор буфера обмена",
        hubDescription: "Скопированные изображения, видео и PDF становятся меньше",
        enable: "Сжимать скопированные файлы",
        caption: "В режиме «Сохранять» скопированные изображения PNG и TIFF перекодируются без потери качества, если это экономит место. JPEG и уменьшение размера снижают качество. Изображения, скопированные вместе с текстом, ссылками или форматированием, не изменяются.",
        formatLabel: "Формат",
        formatKeep: "Сохранять (без потерь)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG намного меньше, но размывает текст. Изображения с прозрачностью остаются в PNG.",
        quality: "Качество JPEG",
        maxDimension: "Максимальный размер",
        maxDimensionOff: "Выкл.",
        halveRetina: "Уменьшать изображения Retina до 1x",
        halveRetinaCaption: "Уменьшает ширину и высоту вдвое, как у снимка экрана на обычном дисплее.",
        includeFiles: "Оптимизировать и скопированные файлы изображений",
        includeFilesCaption: "Скопированный файл PNG, JPEG или TIFF заменяется оптимизированным изображением, поэтому вставка в Finder больше не копирует сам файл.",
        imagesToggle: "Изображения",
        convertImages: "Конвертировать файлы HEIC, WebP, AVIF и BMP",
        convertImagesCaption: "Скопированный файл становится JPEG или PNG, если в нём есть прозрачность. Анимированные, HDR и 10-битные фото, включая большинство фото HEIC с iPhone, не изменяются. Требуется включить оптимизацию скопированных файлов изображений.",
        videos: "Видео",
        videosCaption: "Скопированный файл MOV, MP4 или M4V перекодируется в уменьшенную копию, и буфер обмена указывает на неё, поэтому при вставке получается уменьшенная копия. Исходный файл никогда не изменяется. Чтение файла на Рабочем столе, в Документах или Загрузках может один раз запросить доступ.",
        videoCodec: "Кодек",
        codecH264: "H.264 (наиболее совместимый)",
        codecHEVC: "HEVC (меньше)",
        videoQuality: "Качество видео",
        videoMaxDimension: "Максимальное разрешение",
        videoMaxDimensionKeep: "Сохранять",
        removeAudio: "Удалять звук",
        videoMaxSize: "Пропускать видео больше",
        videoMaxDuration: "Пропускать видео длиннее",
        minutesFormat: "%d мин",
        pdfs: "PDF",
        pdfsCaption: "Изображения внутри скопированного PDF пересчитываются в уменьшенную копию; текст, ссылки и поля форм остаются как есть. Подписанные, зашифрованные, размеченные PDF и PDF со скриптами не изменяются. Исходный файл никогда не изменяется.",
        pdfDPI: "Разрешение изображений",
        dpiFormat: "%d dpi",
        pdfQuality: "Качество изображений",
        pdfMaxSize: "Пропускать PDF больше",
        storageCaption: "Уменьшенные копии видео, PDF и конвертированных изображений хранятся в папке Application Support приложения Vorssaint, до 2 ГБ, и удаляются через день, если буфер обмена или история их больше не используют.",
        clearCopies: "Очистить оптимизированные копии (%@)",
        keptBytes: "%@ хранится для буфера обмена и закреплённой истории"
    )

    static let es = ClipboardImageOptimizerStrings(
        title: "Optimizador del portapapeles",
        hubDescription: "Las imágenes, vídeos y PDF copiados ocupan menos",
        enable: "Reducir los archivos copiados",
        caption: "Con Mantener, las imágenes PNG y TIFF copiadas se recodifican sin pérdida de calidad cuando así ocupan menos. JPEG y el cambio de tamaño pierden calidad. Las imágenes copiadas junto con texto, enlaces o formato no se tocan.",
        formatLabel: "Formato",
        formatKeep: "Mantener (sin pérdida)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG ocupa mucho menos, pero difumina el texto. Las imágenes con transparencia siguen en PNG.",
        quality: "Calidad JPEG",
        maxDimension: "Tamaño máximo",
        maxDimensionOff: "No",
        halveRetina: "Reducir las imágenes Retina a 1x",
        halveRetinaCaption: "Reduce a la mitad el ancho y el alto, como una captura hecha en una pantalla estándar.",
        includeFiles: "Optimizar también los archivos de imagen copiados",
        includeFilesCaption: "Un archivo PNG, JPEG o TIFF copiado se sustituye por su imagen optimizada, así que al pegar en el Finder ya no se copia el archivo.",
        imagesToggle: "Imágenes",
        convertImages: "Convertir archivos HEIC, WebP, AVIF y BMP",
        convertImagesCaption: "Un archivo copiado se convierte en JPEG, o en PNG si tiene transparencia. Las fotos animadas, HDR y de 10 bits, incluida la mayoría de las fotos HEIC del iPhone, no se tocan. Requiere activar los archivos de imagen copiados.",
        videos: "Vídeos",
        videosCaption: "Un archivo MOV, MP4 o M4V copiado se recodifica en una copia más pequeña y el portapapeles apunta a ella, así que al pegar se obtiene la copia pequeña. El archivo original nunca se modifica. Leer un archivo de Escritorio, Documentos o Descargas puede pedir acceso una vez.",
        videoCodec: "Códec",
        codecH264: "H.264 (más compatible)",
        codecHEVC: "HEVC (más pequeño)",
        videoQuality: "Calidad de vídeo",
        videoMaxDimension: "Resolución máxima",
        videoMaxDimensionKeep: "Mantener",
        removeAudio: "Quitar el audio",
        videoMaxSize: "Omitir vídeos de más de",
        videoMaxDuration: "Omitir vídeos que duren más de",
        minutesFormat: "%d min",
        pdfs: "PDF",
        pdfsCaption: "Las imágenes de un PDF copiado se remuestrean en una copia más pequeña; el texto, los enlaces y los campos de formulario se quedan como están. Los PDF firmados, cifrados, etiquetados o con scripts no se tocan. El archivo original nunca se modifica.",
        pdfDPI: "Resolución de imagen",
        dpiFormat: "%d ppp",
        pdfQuality: "Calidad de imagen",
        pdfMaxSize: "Omitir PDF de más de",
        storageCaption: "Las copias pequeñas de vídeos, PDF e imágenes convertidas se guardan en la carpeta Application Support de Vorssaint, hasta 2 GB, y se eliminan pasado un día salvo que el portapapeles o el historial aún las usen.",
        clearCopies: "Borrar copias optimizadas (%@)",
        keptBytes: "%@ guardados para el portapapeles y el historial fijado"
    )

    static let sk = ClipboardImageOptimizerStrings(
        title: "Optimalizátor schránky",
        hubDescription: "Skopírované obrázky, videá a PDF budú menšie",
        enable: "Zmenšovať skopírované súbory",
        caption: "Pri voľbe Zachovať sa skopírované obrázky PNG a TIFF znova zakódujú bez straty kvality, ak to ušetrí miesto. JPEG a zmena veľkosti kvalitu znižujú. Obrázky skopírované spolu s textom, odkazmi alebo formátovaním zostanú nezmenené.",
        formatLabel: "Formát",
        formatKeep: "Zachovať (bezstratovo)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG je oveľa menší, ale rozmazáva text. Obrázky s priehľadnosťou zostanú v PNG.",
        quality: "Kvalita JPEG",
        maxDimension: "Maximálna veľkosť",
        maxDimensionOff: "Vypnuté",
        halveRetina: "Zmenšiť obrázky Retina na 1x",
        halveRetinaCaption: "Zmenší šírku aj výšku na polovicu, ako pri snímke z bežného displeja.",
        includeFiles: "Optimalizovať aj skopírované obrázkové súbory",
        includeFilesCaption: "Skopírovaný súbor PNG, JPEG alebo TIFF sa nahradí optimalizovaným obrázkom, takže vloženie vo Finderi už súbor neskopíruje.",
        imagesToggle: "Obrázky",
        convertImages: "Konvertovať súbory HEIC, WebP, AVIF a BMP",
        convertImagesCaption: "Skopírovaný súbor sa zmení na JPEG, alebo na PNG, ak má priehľadnosť. Animované, HDR a 10-bitové fotky vrátane väčšiny fotiek HEIC z iPhonu zostanú nezmenené. Vyžaduje zapnuté skopírované obrázkové súbory.",
        videos: "Videá",
        videosCaption: "Skopírovaný súbor MOV, MP4 alebo M4V sa znova zakóduje do menšej kópie a schránka ukazuje na ňu, takže vložením dostanete menšiu kópiu. Pôvodný súbor sa nikdy nemení. Čítanie súboru na Ploche, v Dokumentoch alebo Stiahnutých môže raz požiadať o prístup.",
        videoCodec: "Kodek",
        codecH264: "H.264 (najkompatibilnejší)",
        codecHEVC: "HEVC (menší)",
        videoQuality: "Kvalita videa",
        videoMaxDimension: "Maximálne rozlíšenie",
        videoMaxDimensionKeep: "Zachovať",
        removeAudio: "Odstrániť zvuk",
        videoMaxSize: "Preskočiť videá väčšie ako",
        videoMaxDuration: "Preskočiť videá dlhšie ako",
        minutesFormat: "%d min",
        pdfs: "PDF",
        pdfsCaption: "Obrázky v skopírovanom PDF sa prevzorkujú do menšej kópie; text, odkazy a polia formulárov zostanú bez zmeny. Podpísané, šifrované, označené PDF alebo PDF so skriptami zostanú nezmenené. Pôvodný súbor sa nikdy nemení.",
        pdfDPI: "Rozlíšenie obrázkov",
        dpiFormat: "%d dpi",
        pdfQuality: "Kvalita obrázkov",
        pdfMaxSize: "Preskočiť PDF väčšie ako",
        storageCaption: "Menšie kópie videí, PDF a konvertovaných obrázkov sa uchovávajú v priečinku Application Support aplikácie Vorssaint, najviac 2 GB, a po dni sa odstránia, ak ich schránka alebo história už nepoužíva.",
        clearCopies: "Vymazať optimalizované kópie (%@)",
        keptBytes: "%@ uchovaných pre schránku a pripnutú históriu"
    )

    static let de = ClipboardImageOptimizerStrings(
        title: "Optimierung für die Zwischenablage",
        hubDescription: "Kopierte Bilder, Videos und PDFs werden kleiner",
        enable: "Kopierte Dateien verkleinern",
        caption: "Mit „Beibehalten“ werden kopierte PNG- und TIFF-Bilder verlustfrei neu kodiert, wenn das Platz spart. JPEG und Verkleinern sind verlustbehaftet. Bilder, die zusammen mit Text, Links oder Formatierung kopiert wurden, bleiben unverändert.",
        formatLabel: "Format",
        formatKeep: "Beibehalten (verlustfrei)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG ist viel kleiner, macht Text aber unscharf. Bilder mit Transparenz bleiben PNG.",
        quality: "JPEG-Qualität",
        maxDimension: "Maximale Größe",
        maxDimensionOff: "Aus",
        halveRetina: "Retina-Bilder auf 1x verkleinern",
        halveRetinaCaption: "Halbiert Breite und Höhe, wie bei einem Bildschirmfoto auf einem normalen Display.",
        includeFiles: "Auch kopierte Bilddateien optimieren",
        includeFilesCaption: "Eine kopierte PNG-, JPEG- oder TIFF-Datei wird durch ihr optimiertes Bild ersetzt, daher kopiert das Einsetzen im Finder die Datei nicht mehr.",
        imagesToggle: "Bilder",
        convertImages: "HEIC-, WebP-, AVIF- und BMP-Dateien umwandeln",
        convertImagesCaption: "Eine kopierte Datei wird zu JPEG, oder zu PNG, wenn sie Transparenz hat. Animierte, HDR- und 10-Bit-Fotos, einschließlich der meisten HEIC-Fotos vom iPhone, bleiben unverändert. Erfordert, dass kopierte Bilddateien aktiviert sind.",
        videos: "Videos",
        videosCaption: "Eine kopierte MOV-, MP4- oder M4V-Datei wird in eine kleinere Kopie neu kodiert, und die Zwischenablage verweist darauf, sodass beim Einsetzen die kleinere Kopie eingefügt wird. Die Originaldatei wird nie verändert. Beim Lesen einer Datei in Schreibtisch, Dokumente oder Downloads wird eventuell einmal nach Zugriff gefragt.",
        videoCodec: "Codec",
        codecH264: "H.264 (am kompatibelsten)",
        codecHEVC: "HEVC (kleiner)",
        videoQuality: "Videoqualität",
        videoMaxDimension: "Maximale Auflösung",
        videoMaxDimensionKeep: "Beibehalten",
        removeAudio: "Ton entfernen",
        videoMaxSize: "Videos überspringen, die größer sind als",
        videoMaxDuration: "Videos überspringen, die länger sind als",
        minutesFormat: "%d Min.",
        pdfs: "PDFs",
        pdfsCaption: "Bilder in einem kopierten PDF werden in eine kleinere Kopie neu abgetastet; Text, Links und Formularfelder bleiben erhalten. Signierte, verschlüsselte, getaggte oder skriptgesteuerte PDFs bleiben unverändert. Die Originaldatei wird nie verändert.",
        pdfDPI: "Bildauflösung",
        dpiFormat: "%d dpi",
        pdfQuality: "Bildqualität",
        pdfMaxSize: "PDFs überspringen, die größer sind als",
        storageCaption: "Kleinere Kopien von Videos, PDFs und umgewandelten Bildern werden im Ordner Application Support von Vorssaint gespeichert, bis zu 2 GB, und nach einem Tag entfernt, sofern Zwischenablage oder Verlauf sie nicht mehr verwenden.",
        clearCopies: "Optimierte Kopien löschen (%@)",
        keptBytes: "%@ für Zwischenablage und angehefteten Verlauf gespeichert"
    )

    static let fr = ClipboardImageOptimizerStrings(
        title: "Optimiseur du presse-papiers",
        hubDescription: "Les images, vidéos et PDF copiés deviennent plus légers",
        enable: "Alléger les fichiers copiés",
        caption: "Avec Conserver, les images PNG et TIFF copiées sont réencodées sans perte de qualité quand cela réduit leur taille. Le JPEG et le redimensionnement réduisent la qualité. Les images copiées avec du texte, des liens ou une mise en forme ne sont pas modifiées.",
        formatLabel: "Format",
        formatKeep: "Conserver (sans perte)",
        formatJPEG: "JPEG",
        formatCaption: "Le JPEG est bien plus léger mais rend le texte flou. Les images avec transparence restent en PNG.",
        quality: "Qualité JPEG",
        maxDimension: "Taille maximale",
        maxDimensionOff: "Désactivée",
        halveRetina: "Réduire les images Retina en 1x",
        halveRetinaCaption: "Divise la largeur et la hauteur par deux, comme une capture faite sur un écran standard.",
        includeFiles: "Optimiser aussi les fichiers image copiés",
        includeFilesCaption: "Un fichier PNG, JPEG ou TIFF copié est remplacé par son image optimisée. Coller dans le Finder ne copie donc plus le fichier.",
        imagesToggle: "Images",
        convertImages: "Convertir les fichiers HEIC, WebP, AVIF et BMP",
        convertImagesCaption: "Un fichier copié devient un JPEG, ou un PNG s’il contient de la transparence. Les photos animées, HDR et 10 bits, y compris la plupart des photos HEIC de l’iPhone, ne sont pas modifiées. Nécessite l’option des fichiers image copiés.",
        videos: "Vidéos",
        videosCaption: "Un fichier MOV, MP4 ou M4V copié est réencodé en une copie plus légère vers laquelle pointe le presse-papiers : coller donne la copie allégée. Le fichier d’origine n’est jamais modifié. Lire un fichier du Bureau, de Documents ou de Téléchargements peut demander l’accès une fois.",
        videoCodec: "Codec",
        codecH264: "H.264 (le plus compatible)",
        codecHEVC: "HEVC (plus léger)",
        videoQuality: "Qualité vidéo",
        videoMaxDimension: "Résolution maximale",
        videoMaxDimensionKeep: "Conserver",
        removeAudio: "Supprimer le son",
        videoMaxSize: "Ignorer les vidéos de plus de",
        videoMaxDuration: "Ignorer les vidéos durant plus de",
        minutesFormat: "%d min",
        pdfs: "PDF",
        pdfsCaption: "Les images d’un PDF copié sont rééchantillonnées dans une copie plus légère ; le texte, les liens et les champs de formulaire restent intacts. Les PDF signés, chiffrés, balisés ou contenant des scripts ne sont pas modifiés. Le fichier d’origine n’est jamais modifié.",
        pdfDPI: "Résolution des images",
        dpiFormat: "%d ppp",
        pdfQuality: "Qualité des images",
        pdfMaxSize: "Ignorer les PDF de plus de",
        storageCaption: "Les copies allégées des vidéos, PDF et images converties sont conservées dans le dossier Application Support de Vorssaint, jusqu’à 2 Go, et supprimées au bout d’un jour sauf si le presse-papiers ou l’historique les utilise encore.",
        clearCopies: "Effacer les copies optimisées (%@)",
        keptBytes: "%@ conservés pour le presse-papiers et l’historique épinglé"
    )

    static let it = ClipboardImageOptimizerStrings(
        title: "Ottimizzatore degli appunti",
        hubDescription: "Immagini, video e PDF copiati diventano più leggeri",
        enable: "Riduci i file copiati",
        caption: "Con Mantieni, le immagini PNG e TIFF copiate vengono ricodificate senza perdita di qualità quando si risparmia spazio. JPEG e ridimensionamento riducono la qualità. Le immagini copiate insieme a testo, link o formattazione restano intatte.",
        formatLabel: "Formato",
        formatKeep: "Mantieni (senza perdita)",
        formatJPEG: "JPEG",
        formatCaption: "Il JPEG è molto più leggero ma sfoca il testo. Le immagini con trasparenza restano PNG.",
        quality: "Qualità JPEG",
        maxDimension: "Dimensione massima",
        maxDimensionOff: "No",
        halveRetina: "Riduci le immagini Retina a 1x",
        halveRetinaCaption: "Dimezza larghezza e altezza, come uno screenshot fatto su un monitor standard.",
        includeFiles: "Ottimizza anche i file immagine copiati",
        includeFilesCaption: "Un file PNG, JPEG o TIFF copiato viene sostituito dalla sua immagine ottimizzata, quindi incollando nel Finder il file non viene più copiato.",
        imagesToggle: "Immagini",
        convertImages: "Converti file HEIC, WebP, AVIF e BMP",
        convertImagesCaption: "Un file copiato diventa JPEG, o PNG se ha trasparenza. Le foto animate, HDR e a 10 bit, compresa la maggior parte delle foto HEIC di iPhone, restano intatte. Richiede l’ottimizzazione dei file immagine copiati.",
        videos: "Video",
        videosCaption: "Un file MOV, MP4 o M4V copiato viene ricodificato in una copia più leggera a cui puntano gli appunti, quindi incollando si ottiene la copia leggera. Il file originale non viene mai modificato. La lettura di un file in Scrivania, Documenti o Download può chiedere l’accesso una volta.",
        videoCodec: "Codec",
        codecH264: "H.264 (più compatibile)",
        codecHEVC: "HEVC (più leggero)",
        videoQuality: "Qualità video",
        videoMaxDimension: "Risoluzione massima",
        videoMaxDimensionKeep: "Mantieni",
        removeAudio: "Rimuovi l’audio",
        videoMaxSize: "Salta i video più grandi di",
        videoMaxDuration: "Salta i video più lunghi di",
        minutesFormat: "%d min",
        pdfs: "PDF",
        pdfsCaption: "Le immagini in un PDF copiato vengono ricampionate in una copia più leggera; testo, link e campi dei moduli restano come sono. I PDF firmati, cifrati, con tag o con script restano intatti. Il file originale non viene mai modificato.",
        pdfDPI: "Risoluzione immagini",
        dpiFormat: "%d dpi",
        pdfQuality: "Qualità immagini",
        pdfMaxSize: "Salta i PDF più grandi di",
        storageCaption: "Le copie leggere di video, PDF e immagini convertite sono conservate nella cartella Application Support di Vorssaint, fino a 2 GB, e rimosse dopo un giorno a meno che gli appunti o la cronologia le usino ancora.",
        clearCopies: "Elimina copie ottimizzate (%@)",
        keptBytes: "%@ conservati per gli appunti e la cronologia fissata"
    )

    static let ja = ClipboardImageOptimizerStrings(
        title: "クリップボードの最適化",
        hubDescription: "コピーした画像、ビデオ、PDF を小さく",
        enable: "コピーしたファイルを縮小",
        caption: "「維持」では、コピーした PNG と TIFF の画像は、容量が減る場合に画質を落とさずに再エンコードされます。JPEG とサイズ変更では画質が落ちます。テキスト、リンク、書式と一緒にコピーした画像は変更しません。",
        formatLabel: "フォーマット",
        formatKeep: "維持（可逆）",
        formatJPEG: "JPEG",
        formatCaption: "JPEG はかなり小さくなりますが、文字がぼやけます。透明部分のある画像は PNG のままです。",
        quality: "JPEG の画質",
        maxDimension: "最大サイズ",
        maxDimensionOff: "オフ",
        halveRetina: "Retina 画像を 1x に縮小",
        halveRetinaCaption: "標準ディスプレイで撮ったスクリーンショットのように、幅と高さを半分にします。",
        includeFiles: "コピーした画像ファイルも最適化",
        includeFilesCaption: "コピーした PNG、JPEG、TIFF ファイルは最適化した画像に置き換わるため、Finder でペーストしてもファイルはコピーされなくなります。",
        imagesToggle: "画像",
        convertImages: "HEIC、WebP、AVIF、BMP ファイルを変換",
        convertImagesCaption: "コピーしたファイルは JPEG に、透明部分がある場合は PNG に変換されます。アニメーション、HDR、10 ビットの写真（iPhone の HEIC 写真のほとんどを含む）は変更しません。「コピーした画像ファイルも最適化」をオンにする必要があります。",
        videos: "ビデオ",
        videosCaption: "コピーした MOV、MP4、M4V ファイルは小さなコピーに再エンコードされ、クリップボードはそのコピーを指すため、ペーストすると小さなコピーが使われます。元のファイルは変更されません。デスクトップ、書類、ダウンロードのファイルを読み込むときに、一度だけアクセス許可を求められることがあります。",
        videoCodec: "コーデック",
        codecH264: "H.264（互換性重視）",
        codecHEVC: "HEVC（より小さい）",
        videoQuality: "ビデオの画質",
        videoMaxDimension: "最大解像度",
        videoMaxDimensionKeep: "維持",
        removeAudio: "オーディオを削除",
        videoMaxSize: "次より大きいビデオはスキップ",
        videoMaxDuration: "次より長いビデオはスキップ",
        minutesFormat: "%d 分",
        pdfs: "PDF",
        pdfsCaption: "コピーした PDF 内の画像は小さなコピーにリサンプリングされます。テキスト、リンク、フォームフィールドはそのままです。署名、暗号化、タグ付け、スクリプトを含む PDF は変更しません。元のファイルは変更されません。",
        pdfDPI: "画像の解像度",
        dpiFormat: "%d dpi",
        pdfQuality: "画像の画質",
        pdfMaxSize: "次より大きい PDF はスキップ",
        storageCaption: "ビデオ、PDF、変換した画像の小さなコピーは Vorssaint の Application Support フォルダに最大 2 GB まで保存され、クリップボードや履歴で使われていなければ 1 日後に削除されます。",
        clearCopies: "最適化したコピーを消去（%@）",
        keptBytes: "クリップボードとピン留めした履歴用に %@ を保持中"
    )

    static let ko = ClipboardImageOptimizerStrings(
        title: "클립보드 최적화",
        hubDescription: "복사한 이미지, 비디오, PDF를 더 작게",
        enable: "복사한 파일 줄이기",
        caption: "유지를 선택하면 복사한 PNG 및 TIFF 이미지는 용량이 줄어드는 경우 화질 손실 없이 다시 인코딩됩니다. JPEG와 크기 조절은 화질이 떨어집니다. 텍스트, 링크 또는 서식과 함께 복사한 이미지는 그대로 둡니다.",
        formatLabel: "포맷",
        formatKeep: "유지(무손실)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG는 훨씬 작지만 글자가 흐려집니다. 투명한 부분이 있는 이미지는 PNG로 유지됩니다.",
        quality: "JPEG 품질",
        maxDimension: "최대 크기",
        maxDimensionOff: "끔",
        halveRetina: "Retina 이미지를 1x로 줄이기",
        halveRetinaCaption: "일반 디스플레이에서 찍은 스크린샷처럼 너비와 높이를 절반으로 줄입니다.",
        includeFiles: "복사한 이미지 파일도 최적화",
        includeFilesCaption: "복사한 PNG, JPEG 또는 TIFF 파일이 최적화된 이미지로 바뀌므로 Finder에서 붙여넣어도 파일이 더 이상 복사되지 않습니다.",
        imagesToggle: "이미지",
        convertImages: "HEIC, WebP, AVIF 및 BMP 파일 변환",
        convertImagesCaption: "복사한 파일은 JPEG로, 투명한 부분이 있으면 PNG로 변환됩니다. 움직이는 사진, HDR 및 10비트 사진은 대부분의 iPhone HEIC 사진을 포함해 그대로 둡니다. 복사한 이미지 파일 최적화를 켜야 합니다.",
        videos: "비디오",
        videosCaption: "복사한 MOV, MP4 또는 M4V 파일은 더 작은 사본으로 다시 인코딩되고 클립보드가 그 사본을 가리키므로 붙여넣으면 작은 사본이 들어갑니다. 원본 파일은 절대 변경되지 않습니다. 데스크탑, 문서 또는 다운로드의 파일을 읽을 때 한 번 접근 권한을 요청할 수 있습니다.",
        videoCodec: "코덱",
        codecH264: "H.264(호환성 최고)",
        codecHEVC: "HEVC(더 작음)",
        videoQuality: "비디오 품질",
        videoMaxDimension: "최대 해상도",
        videoMaxDimensionKeep: "유지",
        removeAudio: "오디오 제거",
        videoMaxSize: "다음보다 큰 비디오 건너뛰기",
        videoMaxDuration: "다음보다 긴 비디오 건너뛰기",
        minutesFormat: "%d분",
        pdfs: "PDF",
        pdfsCaption: "복사한 PDF 안의 이미지는 더 작은 사본으로 리샘플링되며 텍스트, 링크, 양식 필드는 그대로 유지됩니다. 서명, 암호화, 태그 또는 스크립트가 있는 PDF는 그대로 둡니다. 원본 파일은 절대 변경되지 않습니다.",
        pdfDPI: "이미지 해상도",
        dpiFormat: "%d dpi",
        pdfQuality: "이미지 품질",
        pdfMaxSize: "다음보다 큰 PDF 건너뛰기",
        storageCaption: "비디오, PDF 및 변환된 이미지의 작은 사본은 Vorssaint의 Application Support 폴더에 최대 2GB까지 보관되며, 클립보드나 기록에서 더 이상 사용하지 않으면 하루 뒤 삭제됩니다.",
        clearCopies: "최적화된 사본 지우기(%@)",
        keptBytes: "클립보드와 고정된 기록용으로 %@ 보관 중"
    )

    static let zhHans = ClipboardImageOptimizerStrings(
        title: "剪贴板优化",
        hubDescription: "拷贝的图像、视频和 PDF 变得更小",
        enable: "缩小拷贝的文件",
        caption: "选择“保持”时，拷贝的 PNG 和 TIFF 图像在能节省空间时会无损重新编码。JPEG 和缩放会损失画质。与文本、链接或格式一起拷贝的图像保持不变。",
        formatLabel: "格式",
        formatKeep: "保持（无损）",
        formatJPEG: "JPEG",
        formatCaption: "JPEG 小得多，但会让文字变模糊。带透明度的图像仍为 PNG。",
        quality: "JPEG 质量",
        maxDimension: "最大尺寸",
        maxDimensionOff: "关闭",
        halveRetina: "将 Retina 图像缩小为 1x",
        halveRetinaCaption: "将宽度和高度减半，就像在标准显示器上截取的屏幕快照。",
        includeFiles: "同时优化拷贝的图像文件",
        includeFilesCaption: "拷贝的 PNG、JPEG 或 TIFF 文件会替换为优化后的图像，因此在访达中粘贴将不再拷贝该文件。",
        imagesToggle: "图像",
        convertImages: "转换 HEIC、WebP、AVIF 和 BMP 文件",
        convertImagesCaption: "拷贝的文件会转换为 JPEG，带透明度时转换为 PNG。动态、HDR 和 10 位照片（包括大多数 iPhone HEIC 照片）保持不变。需要开启“同时优化拷贝的图像文件”。",
        videos: "视频",
        videosCaption: "拷贝的 MOV、MP4 或 M4V 文件会重新编码为更小的副本，剪贴板指向该副本，因此粘贴得到的是较小的副本。原始文件永远不会被更改。读取桌面、文稿或下载中的文件时可能会请求一次访问权限。",
        videoCodec: "编解码器",
        codecH264: "H.264（兼容性最好）",
        codecHEVC: "HEVC（更小）",
        videoQuality: "视频质量",
        videoMaxDimension: "最大分辨率",
        videoMaxDimensionKeep: "保持",
        removeAudio: "移除音频",
        videoMaxSize: "跳过大于此大小的视频",
        videoMaxDuration: "跳过长于此时长的视频",
        minutesFormat: "%d 分钟",
        pdfs: "PDF",
        pdfsCaption: "拷贝的 PDF 中的图像会重新采样为更小的副本；文本、链接和表单栏位保持原样。已签名、加密、带标签或含脚本的 PDF 保持不变。原始文件永远不会被更改。",
        pdfDPI: "图像分辨率",
        dpiFormat: "%d dpi",
        pdfQuality: "图像质量",
        pdfMaxSize: "跳过大于此大小的 PDF",
        storageCaption: "视频、PDF 和转换后图像的较小副本保存在 Vorssaint 的 Application Support 文件夹中，最多 2 GB，一天后删除，除非剪贴板或历史记录仍在使用。",
        clearCopies: "清除优化后的副本（%@）",
        keptBytes: "为剪贴板和固定的历史记录保留了 %@"
    )

    static let zhTW = ClipboardImageOptimizerStrings(
        title: "剪貼板最佳化",
        hubDescription: "拷貝的影像、影片和 PDF 會變得更小",
        enable: "縮小拷貝的檔案",
        caption: "選擇「保持」時，拷貝的 PNG 和 TIFF 影像在能節省空間時會無損重新編碼。JPEG 和縮放會損失畫質。與文字、連結或格式一起拷貝的影像保持不變。",
        formatLabel: "格式",
        formatKeep: "保持（無損）",
        formatJPEG: "JPEG",
        formatCaption: "JPEG 小得多，但會讓文字變模糊。含透明度的影像仍為 PNG。",
        quality: "JPEG 品質",
        maxDimension: "最大尺寸",
        maxDimensionOff: "關閉",
        halveRetina: "將 Retina 影像縮小為 1x",
        halveRetinaCaption: "將寬度和高度減半，就像在標準顯示器上擷取的截圖。",
        includeFiles: "同時最佳化拷貝的影像檔案",
        includeFilesCaption: "拷貝的 PNG、JPEG 或 TIFF 檔案會替換為最佳化後的影像，因此在 Finder 中貼上將不再拷貝該檔案。",
        imagesToggle: "影像",
        convertImages: "轉換 HEIC、WebP、AVIF 和 BMP 檔案",
        convertImagesCaption: "拷貝的檔案會轉換為 JPEG，含透明度時轉換為 PNG。動態、HDR 和 10 位元照片（包括大多數 iPhone HEIC 照片）保持不變。需要開啟「同時最佳化拷貝的影像檔案」。",
        videos: "影片",
        videosCaption: "拷貝的 MOV、MP4 或 M4V 檔案會重新編碼為更小的副本，剪貼板會指向該副本，因此貼上時會得到較小的副本。原始檔案永遠不會被更改。讀取桌面、文件或下載項目中的檔案時可能會要求一次取用權限。",
        videoCodec: "編解碼器",
        codecH264: "H.264（相容性最佳）",
        codecHEVC: "HEVC（更小）",
        videoQuality: "影片品質",
        videoMaxDimension: "最大解析度",
        videoMaxDimensionKeep: "保持",
        removeAudio: "移除音訊",
        videoMaxSize: "略過大於此大小的影片",
        videoMaxDuration: "略過長於此時長的影片",
        minutesFormat: "%d 分鐘",
        pdfs: "PDF",
        pdfsCaption: "拷貝的 PDF 中的影像會重新取樣為更小的副本；文字、連結和表單欄位保持原樣。已簽署、加密、加上標記或含指令碼的 PDF 保持不變。原始檔案永遠不會被更改。",
        pdfDPI: "影像解析度",
        dpiFormat: "%d dpi",
        pdfQuality: "影像品質",
        pdfMaxSize: "略過大於此大小的 PDF",
        storageCaption: "影片、PDF 和轉換後影像的較小副本會儲存在 Vorssaint 的 Application Support 檔案夾中，最多 2 GB，並於一天後移除，除非剪貼板或歷史記錄仍在使用。",
        clearCopies: "清除最佳化後的副本（%@）",
        keptBytes: "為剪貼板和已釘選的歷史記錄保留了 %@"
    )

    static let zhHK = ClipboardImageOptimizerStrings(
        title: "剪貼板優化",
        hubDescription: "拷貝的影像、影片和 PDF 會變得更細",
        enable: "縮細拷貝的檔案",
        caption: "揀「保持」時，複製嘅 PNG 同 TIFF 圖像喺可以慳位時會無損重新編碼。JPEG 同縮放會損失質素。同文字、連結或格式一齊複製嘅圖像會保持不變。",
        formatLabel: "格式",
        formatKeep: "保持（無損）",
        formatJPEG: "JPEG",
        formatCaption: "JPEG 細得多，但會令文字變模糊。含透明度的影像仍為 PNG。",
        quality: "JPEG 質素",
        maxDimension: "最大尺寸",
        maxDimensionOff: "關閉",
        halveRetina: "將 Retina 影像縮細為 1x",
        halveRetinaCaption: "將闊度和高度減半，就好似喺標準顯示器上擷取的截圖。",
        includeFiles: "同時優化拷貝的影像檔案",
        includeFilesCaption: "拷貝的 PNG、JPEG 或 TIFF 檔案會換成優化後的影像，因此喺 Finder 貼上將不再拷貝該檔案。",
        imagesToggle: "影像",
        convertImages: "轉換 HEIC、WebP、AVIF 和 BMP 檔案",
        convertImagesCaption: "拷貝的檔案會轉換為 JPEG，含透明度時轉換為 PNG。動態、HDR 和 10 位元相片（包括大部分 iPhone HEIC 相片）保持不變。需要開啟「同時優化拷貝的影像檔案」。",
        videos: "影片",
        videosCaption: "拷貝的 MOV、MP4 或 M4V 檔案會重新編碼成更細的副本，剪貼板會指向該副本，因此貼上時會得到較細的副本。原始檔案永遠不會被更改。讀取桌面、文件或下載項目中的檔案時可能會要求一次存取權限。",
        videoCodec: "編解碼器",
        codecH264: "H.264（兼容性最好）",
        codecHEVC: "HEVC（更細）",
        videoQuality: "影片質素",
        videoMaxDimension: "最高解像度",
        videoMaxDimensionKeep: "保持",
        removeAudio: "移除音訊",
        videoMaxSize: "略過大過此大小的影片",
        videoMaxDuration: "略過長過此時長的影片",
        minutesFormat: "%d 分鐘",
        pdfs: "PDF",
        pdfsCaption: "拷貝的 PDF 內的影像會重新取樣成更細的副本；文字、連結和表格欄位保持原樣。已簽署、加密、加上標記或含程式碼的 PDF 保持不變。原始檔案永遠不會被更改。",
        pdfDPI: "影像解像度",
        dpiFormat: "%d dpi",
        pdfQuality: "影像質素",
        pdfMaxSize: "略過大過此大小的 PDF",
        storageCaption: "影片、PDF 和轉換後影像的較細副本會儲存在 Vorssaint 的 Application Support 資料夾中，最多 2 GB，並於一日後移除，除非剪貼板或歷史記錄仍在使用。",
        clearCopies: "清除優化後的副本（%@）",
        keptBytes: "為剪貼板和已釘選的歷史記錄保留了 %@"
    )

    static let uk = ClipboardImageOptimizerStrings(
        title: "Оптимізатор буфера обміну",
        hubDescription: "Скопійовані зображення, відео й PDF стають меншими",
        enable: "Стискати скопійовані файли",
        caption: "У режимі «Зберігати» скопійовані зображення PNG і TIFF перекодовуються без втрати якості, якщо це заощаджує місце. JPEG і зменшення розміру знижують якість. Зображення, скопійовані разом із текстом, посиланнями чи форматуванням, не змінюються.",
        formatLabel: "Формат",
        formatKeep: "Зберігати (без втрат)",
        formatJPEG: "JPEG",
        formatCaption: "JPEG значно менший, але розмиває текст. Зображення з прозорістю залишаються в PNG.",
        quality: "Якість JPEG",
        maxDimension: "Максимальний розмір",
        maxDimensionOff: "Вимк.",
        halveRetina: "Зменшувати зображення Retina до 1x",
        halveRetinaCaption: "Зменшує ширину й висоту вдвічі, як у знімка екрана на звичайному дисплеї.",
        includeFiles: "Оптимізувати й скопійовані файли зображень",
        includeFilesCaption: "Скопійований файл PNG, JPEG або TIFF замінюється оптимізованим зображенням, тому вставлення у Finder більше не копіює сам файл.",
        imagesToggle: "Зображення",
        convertImages: "Конвертувати файли HEIC, WebP, AVIF і BMP",
        convertImagesCaption: "Скопійований файл стає JPEG або PNG, якщо має прозорість. Анімовані, HDR і 10-бітні фото, зокрема більшість фото HEIC з iPhone, не змінюються. Потрібно ввімкнути оптимізацію скопійованих файлів зображень.",
        videos: "Відео",
        videosCaption: "Скопійований файл MOV, MP4 або M4V перекодовується в меншу копію, і буфер обміну вказує на неї, тому під час вставлення ви отримуєте меншу копію. Оригінальний файл ніколи не змінюється. Читання файлу на Робочому столі, у Документах чи Завантаженнях може один раз запитати доступ.",
        videoCodec: "Кодек",
        codecH264: "H.264 (найсумісніший)",
        codecHEVC: "HEVC (менший)",
        videoQuality: "Якість відео",
        videoMaxDimension: "Максимальна роздільність",
        videoMaxDimensionKeep: "Зберігати",
        removeAudio: "Вилучати звук",
        videoMaxSize: "Пропускати відео, більші за",
        videoMaxDuration: "Пропускати відео, довші за",
        minutesFormat: "%d хв",
        pdfs: "PDF",
        pdfsCaption: "Зображення всередині скопійованого PDF перераховуються в меншу копію; текст, посилання й поля форм залишаються без змін. Підписані, зашифровані, розмічені PDF і PDF зі скриптами не змінюються. Оригінальний файл ніколи не змінюється.",
        pdfDPI: "Роздільність зображень",
        dpiFormat: "%d dpi",
        pdfQuality: "Якість зображень",
        pdfMaxSize: "Пропускати PDF, більші за",
        storageCaption: "Менші копії відео, PDF і конвертованих зображень зберігаються в папці Application Support застосунку Vorssaint, до 2 ГБ, і вилучаються через день, якщо буфер обміну чи історія їх більше не використовують.",
        clearCopies: "Очистити оптимізовані копії (%@)",
        keptBytes: "%@ зберігається для буфера обміну й закріпленої історії"
    )
}
