// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Localized strings for the command bar, the type-and-run field that finds
/// everything the app can do. Action rows reuse each feature's own strings;
/// only the bar's chrome lives here.
struct CommandBarFeatureStrings {
    let pageTitle: String
    let hubDescription: String
    let panelCaption: String
    let settingsCaption: String
    let openButton: String
    let searchPlaceholder: String
    let suggestionsLabel: String
    let noResultsTitle: String
    let noResultsAction: String
    let argumentRangeFormat: String
    let argumentHint: String
    let confirmHint: String
    let kindApp: String
    let kindClipboard: String
    let kindSnippet: String
    let soundOutputSubtitle: String
    let soundOutputCurrent: String
    let volumeTitle: String
    let brightnessTitle: String
    let keepAwakeForFormat: String
    let needsSetupFormat: String
    let needsPermissionHint: String
    let actionCheckAppUpdates: String
    let actionCleanURL: String
    let actionOpenSettings: String
    let answerBatteryLabel: String
    let answerBatteryCharging: String
    let answerBatteryPlugged: String
    let answerMemoryLabel: String
    let answerMemoryFormat: String
    let answerStorageLabel: String
    let answerStorageFormat: String
    let copyHint: String
    let kindWindow: String
    let quitFormat: String
    let quitConfirmFormat: String
    let kindMenu: String
    let actionsTitle: String
    let actionsHint: String
    let actionPin: String
    let actionUnpin: String
    let actionName: String
    let actionRename: String
    let actionHide: String
    let actionForget: String
    let aliasPlaceholder: String
    let aliasTakenFormat: String
    let sourcesTitle: String
    let sourcesCaption: String
    let sourceActions: String
    let sourceApps: String
    let sourceMenus: String
    let sourceWindows: String
    let sourceQuitApps: String
    let sourceSettingsPages: String
    let sourceSnippets: String
    let sourceClipboard: String
    let sourceEmoji: String
    let sourceFolders: String
    let sourceAnswers: String
    let sourceCalculator: String
    let namedTitle: String
    let namedEmpty: String
    let pinnedTitle: String
    let pinnedEmpty: String
    let hiddenTitle: String
    let hiddenEmpty: String
    let forgetAllButton: String
    let tryTheseLabel: String
    let stillLooking: String
    let removeButton: String
    let confirmButton: String
    let soundMute: String
    let soundUnmute: String
    let stateOn: String
    let powerSleep: String
    let powerRestart: String
    let powerRestartConfirm: String
    let powerShutDown: String
    let powerShutDownConfirm: String
    let powerLogOut: String
    let powerLogOutConfirm: String
    let wifiOn: String
    let wifiOff: String
    let kindEmoji: String
    let kindFolder: String
    let answerDateLabel: String
    let answerTimeLabel: String
    let kindAnswer: String
    let kindSelection: String
    let selectedTitle: String
    let selectionCopy: String
    let selectionSearch: String
    let selectionUpper: String
    let selectionLower: String
    let selectionTitleCase: String
    let selectionShelf: String
    let selectionCount: String
    let selectionCountFormat: String
    let sourceSelection: String
    let kindLink: String
    let linkSearchHint: String
    let linksTitle: String
    let linksEmpty: String
    let linkDestinationLabel: String
    let linkKindLink: String
    let linkKindPlace: String
    let linkPlaceholdersHint: String
    let placeholderQuery: String
    let placeholderClipboard: String
    let placeholderSelection: String
    let placeholderDate: String
    let privacyNote: String
    let actionShortcut: String
    let actionShortcutChange: String
    let actionShortcutRemove: String
    let shortcutCaptureHint: String
    let rowShortcutsTitle: String
    let rowShortcutsEmpty: String
    let turnOnFormat: String
    let turnOffFormat: String
    let everythingTitle: String
    let categoryAll: String
    let restartAppFormat: String
    let forceQuitAppFormat: String
    let forceQuitAppConfirmFormat: String
    let uninstallAppFormat: String
}

extension FeatureStrings {
    static func commandBar(_ language: AppLanguage) -> CommandBarFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension CommandBarFeatureStrings {
    static let enUS = CommandBarFeatureStrings(
        pageTitle: "Command Bar",
        hubDescription: "One field that finds and runs everything the app does",
        panelCaption: "Type to find and run anything",
        settingsCaption: "One shortcut opens a field over whatever you are doing. Type a few letters, press Return and it happens. Nothing you type is saved.",
        openButton: "Open the bar now",
        searchPlaceholder: "Type what you want to do",
        suggestionsLabel: "Suggestions",
        noResultsTitle: "Nothing here by that name.",
        noResultsAction: "See suggestions",
        argumentRangeFormat: "%d to %d",
        argumentHint: "Return applies · Esc goes back",
        confirmHint: "Return confirms · Esc cancels",
        kindApp: "App",
        kindClipboard: "Paste from history",
        kindSnippet: "Insert snippet",
        soundOutputSubtitle: "Switch sound output",
        soundOutputCurrent: "Current output",
        volumeTitle: "Volume",
        brightnessTitle: "Screen brightness",
        keepAwakeForFormat: "Keep awake for %@",
        needsSetupFormat: "Turn on %@ in Settings",
        needsPermissionHint: "Needs permission · Return asks",
        actionCheckAppUpdates: "Check for app updates",
        actionCleanURL: "Clean the copied link",
        actionOpenSettings: "Open Settings",
        answerBatteryLabel: "Battery",
        answerBatteryCharging: "charging",
        answerBatteryPlugged: "on power",
        answerMemoryLabel: "Memory",
        answerMemoryFormat: "%@ of %@ in use",
        answerStorageLabel: "Storage",
        answerStorageFormat: "%@ free of %@",
        copyHint: "Return copies",
        kindWindow: "Window",
        quitFormat: "Quit %@",
        quitConfirmFormat: "Quit %@?",
        kindMenu: "Menu command",
        actionsTitle: "Actions",
        actionsHint: "Actions",
        actionPin: "Pin to the top",
        actionUnpin: "Unpin",
        actionName: "Give it your own name",
        actionRename: "Change the name it answers to",
        actionHide: "Never show this",
        actionForget: "Forget how often I use this",
        aliasPlaceholder: "The name you call it",
        aliasTakenFormat: "%@ already answers to that",
        sourcesTitle: "What the bar searches",
        sourcesCaption: "Turn off what you never want to see. Your own actions always stay.",
        sourceActions: "Vorssaint actions",
        sourceApps: "Apps",
        sourceMenus: "Menu commands of the app in front",
        sourceWindows: "Open windows",
        sourceQuitApps: "Quit an app",
        sourceSettingsPages: "Settings pages",
        sourceSnippets: "Snippets",
        sourceClipboard: "Clipboard history",
        sourceEmoji: "Emoji",
        sourceFolders: "Folders",
        sourceAnswers: "Answers about this Mac",
        sourceCalculator: "Sums and conversions",
        namedTitle: "Names you gave",
        namedEmpty: "Nothing named yet. Open the bar, pick a row and press the actions key.",
        pinnedTitle: "Pinned",
        pinnedEmpty: "Nothing pinned yet.",
        hiddenTitle: "Never shown",
        hiddenEmpty: "Nothing hidden.",
        forgetAllButton: "Forget what I use most",
        tryTheseLabel: "Try",
        stillLooking: "Still looking",
        removeButton: "Remove",
        confirmButton: "Confirm",
        soundMute: "Mute the sound",
        soundUnmute: "Turn the sound back on",
        stateOn: "on",
        powerSleep: "Sleep",
        powerRestart: "Restart",
        powerRestartConfirm: "Restart the Mac?",
        powerShutDown: "Shut down",
        powerShutDownConfirm: "Shut down the Mac?",
        powerLogOut: "Log out",
        powerLogOutConfirm: "Log out?",
        wifiOn: "Turn Wi-Fi on",
        wifiOff: "Turn Wi-Fi off",
        kindEmoji: "Emoji",
        kindFolder: "Folder",
        answerDateLabel: "Today",
        answerTimeLabel: "Time now",
        kindAnswer: "Answer",
        kindSelection: "Selection",
        selectedTitle: "Selected",
        selectionCopy: "Copy it",
        selectionSearch: "Use it in the search",
        selectionUpper: "UPPERCASE",
        selectionLower: "lowercase",
        selectionTitleCase: "Title Case",
        selectionShelf: "Keep it on the shelf",
        selectionCount: "Count it",
        selectionCountFormat: "%d words, %d characters",
        sourceSelection: "What is selected",
        kindLink: "Your shortcut",
        linkSearchHint: "Type what to look for after the name",
        linksTitle: "Your shortcuts",
        linksEmpty: "Nothing saved yet. Add a site, a folder or a search you open every day.",
        linkDestinationLabel: "Where it goes",
        linkKindLink: "Site or link",
        linkKindPlace: "Folder or file",
        linkPlaceholdersHint: "Drop one of these in and it gets filled in when it opens",
        placeholderQuery: "what you type",
        placeholderClipboard: "what you copied",
        placeholderSelection: "what is selected",
        placeholderDate: "today",
        privacyNote: "Everything happens on this Mac: no account, no cloud, nothing sent anywhere.",
        actionShortcut: "Give it a shortcut",
        actionShortcutChange: "Change the shortcut",
        actionShortcutRemove: "Take the shortcut off",
        shortcutCaptureHint: "Press the keys you want · Delete clears it · Esc goes back",
        rowShortcutsTitle: "Rows with their own shortcut",
        rowShortcutsEmpty: "No row has its own shortcut yet. Open the actions on any row to give it one.",
        turnOnFormat: "Turn on %@",
        turnOffFormat: "Turn off %@",
        everythingTitle: "Everything it can do",
        categoryAll: "All",
        restartAppFormat: "Restart %@",
        forceQuitAppFormat: "Force Quit %@…",
        forceQuitAppConfirmFormat: "Force quit %@? Unsaved changes will be lost.",
        uninstallAppFormat: "Uninstall %@…")

    static let ptBR = CommandBarFeatureStrings(
        pageTitle: "Barra de comando",
        hubDescription: "Um campo que acha e executa tudo que o app faz",
        panelCaption: "Digite para achar e executar qualquer coisa",
        settingsCaption: "Um atalho abre um campo por cima do que você estiver fazendo. Digite umas letras, aperte Return e pronto. Nada do que você digita fica salvo.",
        openButton: "Abrir a barra agora",
        searchPlaceholder: "Digite o que você quer fazer",
        suggestionsLabel: "Sugestões",
        noResultsTitle: "Nada com esse nome por aqui.",
        noResultsAction: "Ver sugestões",
        argumentRangeFormat: "%d a %d",
        argumentHint: "Return aplica · Esc volta",
        confirmHint: "Return confirma · Esc cancela",
        kindApp: "App",
        kindClipboard: "Colar do histórico",
        kindSnippet: "Inserir snippet",
        soundOutputSubtitle: "Trocar a saída de som",
        soundOutputCurrent: "Saída atual",
        volumeTitle: "Volume",
        brightnessTitle: "Brilho da tela",
        keepAwakeForFormat: "Manter acordado por %@",
        needsSetupFormat: "Ligue %@ nos Ajustes",
        needsPermissionHint: "Precisa de uma permissão · Return pede",
        actionCheckAppUpdates: "Verificar atualizações de apps",
        actionCleanURL: "Limpar o link copiado",
        actionOpenSettings: "Abrir os Ajustes",
        answerBatteryLabel: "Bateria",
        answerBatteryCharging: "carregando",
        answerBatteryPlugged: "na tomada",
        answerMemoryLabel: "Memória",
        answerMemoryFormat: "%@ de %@ em uso",
        answerStorageLabel: "Armazenamento",
        answerStorageFormat: "%@ livres de %@",
        copyHint: "Return copia",
        kindWindow: "Janela",
        quitFormat: "Encerrar %@",
        quitConfirmFormat: "Encerrar %@?",
        kindMenu: "Comando de menu",
        actionsTitle: "Ações",
        actionsHint: "Ações",
        actionPin: "Fixar no topo",
        actionUnpin: "Desafixar",
        actionName: "Dar um nome seu",
        actionRename: "Trocar o nome que ele atende",
        actionHide: "Nunca mostrar isto",
        actionForget: "Esquecer o quanto eu uso isto",
        aliasPlaceholder: "O nome que você usa",
        aliasTakenFormat: "%@ já atende por esse nome",
        sourcesTitle: "O que a barra procura",
        sourcesCaption: "Desligue o que você nunca quer ver. Suas ações continuam sempre.",
        sourceActions: "Ações do Vorssaint",
        sourceApps: "Apps",
        sourceMenus: "Comandos de menu do app da frente",
        sourceWindows: "Janelas abertas",
        sourceQuitApps: "Encerrar um app",
        sourceSettingsPages: "Páginas dos Ajustes",
        sourceSnippets: "Snippets",
        sourceClipboard: "Histórico da área de transferência",
        sourceEmoji: "Emoji",
        sourceFolders: "Pastas",
        sourceAnswers: "Respostas sobre este Mac",
        sourceCalculator: "Contas e conversões",
        namedTitle: "Nomes que você deu",
        namedEmpty: "Nada com nome ainda. Abra a barra, escolha uma linha e aperte a tecla de ações.",
        pinnedTitle: "Fixados",
        pinnedEmpty: "Nada fixado ainda.",
        hiddenTitle: "Nunca mostrar",
        hiddenEmpty: "Nada escondido.",
        forgetAllButton: "Esquecer o que eu mais uso",
        tryTheseLabel: "Tente",
        stillLooking: "Ainda procurando",
        removeButton: "Remover",
        confirmButton: "Confirmar",
        soundMute: "Silenciar o som",
        soundUnmute: "Voltar o som",
        stateOn: "ativo",
        powerSleep: "Dormir",
        powerRestart: "Reiniciar",
        powerRestartConfirm: "Reiniciar o Mac?",
        powerShutDown: "Desligar",
        powerShutDownConfirm: "Desligar o Mac?",
        powerLogOut: "Encerrar sessão",
        powerLogOutConfirm: "Encerrar a sessão?",
        wifiOn: "Ligar o Wi-Fi",
        wifiOff: "Desligar o Wi-Fi",
        kindEmoji: "Emoji",
        kindFolder: "Pasta",
        answerDateLabel: "Hoje",
        answerTimeLabel: "Hora agora",
        kindAnswer: "Resposta",
        kindSelection: "Seleção",
        selectedTitle: "Selecionado",
        selectionCopy: "Copiar",
        selectionSearch: "Usar na busca",
        selectionUpper: "MAIÚSCULAS",
        selectionLower: "minúsculas",
        selectionTitleCase: "Iniciais Maiúsculas",
        selectionShelf: "Guardar na prateleira",
        selectionCount: "Contar",
        selectionCountFormat: "%d palavras, %d caracteres",
        sourceSelection: "O que está selecionado",
        kindLink: "Seu atalho",
        linkSearchHint: "Digite o que procurar depois do nome",
        linksTitle: "Seus atalhos",
        linksEmpty: "Nada salvo ainda. Adicione um site, uma pasta ou uma busca que você abre todo dia.",
        linkDestinationLabel: "Para onde vai",
        linkKindLink: "Site ou link",
        linkKindPlace: "Pasta ou arquivo",
        linkPlaceholdersHint: "Coloque um destes e ele é preenchido na hora de abrir",
        placeholderQuery: "o que você digitar",
        placeholderClipboard: "o que você copiou",
        placeholderSelection: "o que está selecionado",
        placeholderDate: "hoje",
        privacyNote: "Tudo acontece neste Mac: sem conta, sem nuvem, nada sai daqui.",
        actionShortcut: "Dar um atalho",
        actionShortcutChange: "Trocar o atalho",
        actionShortcutRemove: "Tirar o atalho",
        shortcutCaptureHint: "Aperte as teclas que quiser · Delete limpa · Esc volta",
        rowShortcutsTitle: "Linhas com atalho próprio",
        rowShortcutsEmpty: "Nenhuma linha tem atalho ainda. Abra as ações de qualquer linha para dar um.",
        turnOnFormat: "Ligar %@",
        turnOffFormat: "Desligar %@",
        everythingTitle: "Tudo o que ela faz",
        categoryAll: "Tudo",
        restartAppFormat: "Reiniciar %@",
        forceQuitAppFormat: "Forçar encerramento de %@…",
        forceQuitAppConfirmFormat: "Forçar o encerramento de %@? Alterações não salvas serão perdidas.",
        uninstallAppFormat: "Desinstalar %@…")

    static let tr = CommandBarFeatureStrings(
        pageTitle: "Komut çubuğu",
        hubDescription: "Uygulamanın yaptığı her şeyi bulup çalıştıran tek alan",
        panelCaption: "Yazın, bulun ve çalıştırın",
        settingsCaption: "Tek bir kısayol, yaptığınız işin üstünde bir alan açar. Birkaç harf yazın, Return'e basın ve iş biter. Yazdıklarınız kaydedilmez.",
        openButton: "Çubuğu şimdi aç",
        searchPlaceholder: "Ne yapmak istediğinizi yazın",
        suggestionsLabel: "Öneriler",
        noResultsTitle: "Bu adda bir şey yok.",
        noResultsAction: "Önerileri gör",
        argumentRangeFormat: "%d ile %d arası",
        argumentHint: "Return uygular · Esc geri döner",
        confirmHint: "Return onaylar · Esc iptal eder",
        kindApp: "Uygulama",
        kindClipboard: "Geçmişten yapıştır",
        kindSnippet: "Parçacığı yaz",
        soundOutputSubtitle: "Ses çıkışını değiştir",
        soundOutputCurrent: "Şu anki çıkış",
        volumeTitle: "Ses düzeyi",
        brightnessTitle: "Ekran parlaklığı",
        keepAwakeForFormat: "%@ boyunca uyanık tut",
        needsSetupFormat: "Ayarlar'dan %@ özelliğini açın",
        needsPermissionHint: "İzin gerekiyor · Return ister",
        actionCheckAppUpdates: "Uygulama güncellemelerini denetle",
        actionCleanURL: "Kopyalanan bağlantıyı temizle",
        actionOpenSettings: "Ayarlar'ı aç",
        answerBatteryLabel: "Pil",
        answerBatteryCharging: "şarj oluyor",
        answerBatteryPlugged: "prizde",
        answerMemoryLabel: "Bellek",
        answerMemoryFormat: "%@ / %@ kullanımda",
        answerStorageLabel: "Depolama",
        answerStorageFormat: "%@ boş / %@",
        copyHint: "Return kopyalar",
        kindWindow: "Pencere",
        quitFormat: "%@ uygulamasını kapat",
        quitConfirmFormat: "%@ kapatılsın mı?",
        kindMenu: "Menü komutu",
        actionsTitle: "Eylemler",
        actionsHint: "Eylemler",
        actionPin: "En üste sabitle",
        actionUnpin: "Sabitlemeyi kaldır",
        actionName: "Kendi adını ver",
        actionRename: "Yanıt verdiği adı değiştir",
        actionHide: "Bunu hiç gösterme",
        actionForget: "Bunu ne sıklıkla kullandığımı unut",
        aliasPlaceholder: "Ona verdiğin ad",
        aliasTakenFormat: "%@ zaten bu ada yanıt veriyor",
        sourcesTitle: "Çubuğun aradıkları",
        sourcesCaption: "Hiç görmek istemediklerinizi kapatın. Kendi eylemleriniz hep kalır.",
        sourceActions: "Vorssaint eylemleri",
        sourceApps: "Uygulamalar",
        sourceMenus: "Öndeki uygulamanın menü komutları",
        sourceWindows: "Açık pencereler",
        sourceQuitApps: "Bir uygulamayı kapat",
        sourceSettingsPages: "Ayarlar sayfaları",
        sourceSnippets: "Parçacıklar",
        sourceClipboard: "Pano geçmişi",
        sourceEmoji: "Emoji",
        sourceFolders: "Klasörler",
        sourceAnswers: "Bu Mac hakkında yanıtlar",
        sourceCalculator: "Hesaplar ve dönüşümler",
        namedTitle: "Verdiğiniz adlar",
        namedEmpty: "Henüz ad verilmedi. Çubuğu açın, bir satır seçin ve eylemler tuşuna basın.",
        pinnedTitle: "Sabitlenenler",
        pinnedEmpty: "Henüz sabitlenmiş bir şey yok.",
        hiddenTitle: "Hiç gösterilmeyenler",
        hiddenEmpty: "Gizlenmiş bir şey yok.",
        forgetAllButton: "En çok kullandıklarımı unut",
        tryTheseLabel: "Deneyin",
        stillLooking: "Hâlâ aranıyor",
        removeButton: "Kaldır",
        confirmButton: "Onayla",
        soundMute: "Sesi kapat",
        soundUnmute: "Sesi geri aç",
        stateOn: "açık",
        powerSleep: "Uyku",
        powerRestart: "Yeniden başlat",
        powerRestartConfirm: "Mac yeniden başlatılsın mı?",
        powerShutDown: "Kapat",
        powerShutDownConfirm: "Mac kapatılsın mı?",
        powerLogOut: "Oturumu kapat",
        powerLogOutConfirm: "Oturum kapatılsın mı?",
        wifiOn: "Wi-Fi'yi aç",
        wifiOff: "Wi-Fi'yi kapat",
        kindEmoji: "Emoji",
        kindFolder: "Klasör",
        answerDateLabel: "Bugün",
        answerTimeLabel: "Şu anki saat",
        kindAnswer: "Yanıt",
        kindSelection: "Seçim",
        selectedTitle: "Seçili",
        selectionCopy: "Kopyala",
        selectionSearch: "Aramada kullan",
        selectionUpper: "BÜYÜK HARF",
        selectionLower: "küçük harf",
        selectionTitleCase: "Baş Harfler Büyük",
        selectionShelf: "Rafta sakla",
        selectionCount: "Say",
        selectionCountFormat: "%d sözcük, %d karakter",
        sourceSelection: "Seçili olan",
        kindLink: "Kısayolunuz",
        linkSearchHint: "Adın ardına aranacak şeyi yazın",
        linksTitle: "Kısayollarınız",
        linksEmpty: "Henüz bir şey yok. Her gün açtığınız bir siteyi, klasörü ya da aramayı ekleyin.",
        linkDestinationLabel: "Nereye gider",
        linkKindLink: "Site veya bağlantı",
        linkKindPlace: "Klasör veya dosya",
        linkPlaceholdersHint: "Bunlardan birini koyun, açılırken doldurulur",
        placeholderQuery: "yazdığınız şey",
        placeholderClipboard: "kopyaladığınız şey",
        placeholderSelection: "seçili olan",
        placeholderDate: "bugün",
        privacyNote: "Her şey bu Mac’te olur: hesap yok, bulut yok, hiçbir şey dışarı gitmez.",
        actionShortcut: "Kısayol ver",
        actionShortcutChange: "Kısayolu değiştir",
        actionShortcutRemove: "Kısayolu kaldır",
        shortcutCaptureHint: "İstediğiniz tuşlara basın · Delete siler · Esc geri döner",
        rowShortcutsTitle: "Kendi kısayolu olan satırlar",
        rowShortcutsEmpty: "Henüz kısayolu olan satır yok. Herhangi bir satırın eylemlerini açıp bir tane verin.",
        turnOnFormat: "%@ aç",
        turnOffFormat: "%@ kapat",
        everythingTitle: "Yapabildiği her şey",
        categoryAll: "Tümü",
        restartAppFormat: "%@ uygulamasını yeniden başlat",
        forceQuitAppFormat: "%@ uygulamasını zorla kapat…",
        forceQuitAppConfirmFormat: "%@ uygulaması zorla kapatılsın mı? Kaydedilmemiş değişiklikler kaybolacak.",
        uninstallAppFormat: "%@ uygulamasını kaldır…")

    static let ru = CommandBarFeatureStrings(
        pageTitle: "Командная панель",
        hubDescription: "Одно поле, которое находит и запускает всё в приложении",
        panelCaption: "Введите, чтобы найти и запустить что угодно",
        settingsCaption: "Одно сочетание клавиш открывает поле поверх того, чем вы заняты. Наберите пару букв, нажмите Return, и готово. Введённое нигде не сохраняется.",
        openButton: "Открыть панель сейчас",
        searchPlaceholder: "Наберите, что нужно сделать",
        suggestionsLabel: "Предложения",
        noResultsTitle: "Ничего с таким названием не нашлось.",
        noResultsAction: "Показать предложения",
        argumentRangeFormat: "от %d до %d",
        argumentHint: "Return применяет · Esc назад",
        confirmHint: "Return подтверждает · Esc отменяет",
        kindApp: "Приложение",
        kindClipboard: "Вставить из истории",
        kindSnippet: "Вставить сниппет",
        soundOutputSubtitle: "Переключить вывод звука",
        soundOutputCurrent: "Текущий вывод",
        volumeTitle: "Громкость",
        brightnessTitle: "Яркость экрана",
        keepAwakeForFormat: "Не давать Mac уснуть %@",
        needsSetupFormat: "Включите «%@» в Настройках",
        needsPermissionHint: "Нужно разрешение · Return запросит",
        actionCheckAppUpdates: "Проверить обновления приложений",
        actionCleanURL: "Очистить скопированную ссылку",
        actionOpenSettings: "Открыть Настройки",
        answerBatteryLabel: "Батарея",
        answerBatteryCharging: "заряжается",
        answerBatteryPlugged: "от сети",
        answerMemoryLabel: "Память",
        answerMemoryFormat: "%@ из %@ занято",
        answerStorageLabel: "Хранилище",
        answerStorageFormat: "%@ свободно из %@",
        copyHint: "Return копирует",
        kindWindow: "Окно",
        quitFormat: "Завершить %@",
        quitConfirmFormat: "Завершить %@?",
        kindMenu: "Команда меню",
        actionsTitle: "Действия",
        actionsHint: "Действия",
        actionPin: "Закрепить сверху",
        actionUnpin: "Открепить",
        actionName: "Дать своё имя",
        actionRename: "Изменить имя, на которое откликается",
        actionHide: "Никогда не показывать",
        actionForget: "Забыть, как часто я это использую",
        aliasPlaceholder: "Имя, которым вы это зовёте",
        aliasTakenFormat: "На это имя уже откликается %@",
        sourcesTitle: "Что ищет панель",
        sourcesCaption: "Выключите то, что не хотите видеть. Ваши действия остаются всегда.",
        sourceActions: "Действия Vorssaint",
        sourceApps: "Приложения",
        sourceMenus: "Команды меню активного приложения",
        sourceWindows: "Открытые окна",
        sourceQuitApps: "Завершить приложение",
        sourceSettingsPages: "Страницы настроек",
        sourceSnippets: "Сниппеты",
        sourceClipboard: "История буфера обмена",
        sourceEmoji: "Эмодзи",
        sourceFolders: "Папки",
        sourceAnswers: "Ответы об этом Mac",
        sourceCalculator: "Расчёты и конвертации",
        namedTitle: "Данные вами имена",
        namedEmpty: "Пока ничего не названо. Откройте панель, выберите строку и нажмите клавишу действий.",
        pinnedTitle: "Закреплённые",
        pinnedEmpty: "Пока ничего не закреплено.",
        hiddenTitle: "Никогда не показывать",
        hiddenEmpty: "Ничего не скрыто.",
        forgetAllButton: "Забыть, чем я пользуюсь чаще всего",
        tryTheseLabel: "Попробуйте",
        stillLooking: "Ещё ищем",
        removeButton: "Удалить",
        confirmButton: "Подтвердить",
        soundMute: "Выключить звук",
        soundUnmute: "Включить звук",
        stateOn: "включено",
        powerSleep: "Сон",
        powerRestart: "Перезагрузить",
        powerRestartConfirm: "Перезагрузить Mac?",
        powerShutDown: "Выключить",
        powerShutDownConfirm: "Выключить Mac?",
        powerLogOut: "Завершить сеанс",
        powerLogOutConfirm: "Завершить сеанс?",
        wifiOn: "Включить Wi-Fi",
        wifiOff: "Выключить Wi-Fi",
        kindEmoji: "Эмодзи",
        kindFolder: "Папка",
        answerDateLabel: "Сегодня",
        answerTimeLabel: "Текущее время",
        kindAnswer: "Ответ",
        kindSelection: "Выделение",
        selectedTitle: "Выделено",
        selectionCopy: "Скопировать",
        selectionSearch: "Использовать в поиске",
        selectionUpper: "ПРОПИСНЫЕ",
        selectionLower: "строчные",
        selectionTitleCase: "Каждое Слово С Заглавной",
        selectionShelf: "Положить на полку",
        selectionCount: "Посчитать",
        selectionCountFormat: "%d слов, %d символов",
        sourceSelection: "Выделенный текст",
        kindLink: "Ваш ярлык",
        linkSearchHint: "Введите после имени то, что нужно найти",
        linksTitle: "Ваши ярлыки",
        linksEmpty: "Пока пусто. Добавьте сайт, папку или поиск, которые открываете каждый день.",
        linkDestinationLabel: "Куда ведёт",
        linkKindLink: "Сайт или ссылка",
        linkKindPlace: "Папка или файл",
        linkPlaceholdersHint: "Вставьте одно из этих, и оно подставится при открытии",
        placeholderQuery: "то, что вы введёте",
        placeholderClipboard: "то, что вы скопировали",
        placeholderSelection: "то, что выделено",
        placeholderDate: "сегодня",
        privacyNote: "Всё происходит на этом Mac: без аккаунта, без облака, ничего не уходит наружу.",
        actionShortcut: "Назначить сочетание",
        actionShortcutChange: "Изменить сочетание",
        actionShortcutRemove: "Убрать сочетание",
        shortcutCaptureHint: "Нажмите нужные клавиши · Delete очищает · Esc возвращает",
        rowShortcutsTitle: "Строки со своим сочетанием",
        rowShortcutsEmpty: "Пока ни у одной строки нет своего сочетания. Откройте действия любой строки и назначьте его.",
        turnOnFormat: "Включить: %@",
        turnOffFormat: "Выключить: %@",
        everythingTitle: "Всё, что она умеет",
        categoryAll: "Все",
        restartAppFormat: "Перезапустить %@",
        forceQuitAppFormat: "Завершить %@ принудительно…",
        forceQuitAppConfirmFormat: "Завершить %@ принудительно? Несохранённые изменения будут потеряны.",
        uninstallAppFormat: "Удалить %@…")

    static let es = CommandBarFeatureStrings(
        pageTitle: "Barra de comandos",
        hubDescription: "Un campo que encuentra y ejecuta todo lo que hace la app",
        panelCaption: "Escribe para encontrar y ejecutar lo que sea",
        settingsCaption: "Un atajo abre un campo sobre lo que estés haciendo. Escribe unas letras, pulsa Retorno y listo. Nada de lo que escribes se guarda.",
        openButton: "Abrir la barra ahora",
        searchPlaceholder: "Escribe lo que quieres hacer",
        suggestionsLabel: "Sugerencias",
        noResultsTitle: "No hay nada con ese nombre.",
        noResultsAction: "Ver sugerencias",
        argumentRangeFormat: "%d a %d",
        argumentHint: "Retorno aplica · Esc vuelve",
        confirmHint: "Retorno confirma · Esc cancela",
        kindApp: "App",
        kindClipboard: "Pegar del historial",
        kindSnippet: "Insertar fragmento",
        soundOutputSubtitle: "Cambiar la salida de sonido",
        soundOutputCurrent: "Salida actual",
        volumeTitle: "Volumen",
        brightnessTitle: "Brillo de la pantalla",
        keepAwakeForFormat: "Mantener activo durante %@",
        needsSetupFormat: "Activa %@ en Ajustes",
        needsPermissionHint: "Necesita un permiso · Retorno lo pide",
        actionCheckAppUpdates: "Buscar actualizaciones de apps",
        actionCleanURL: "Limpiar el enlace copiado",
        actionOpenSettings: "Abrir Ajustes",
        answerBatteryLabel: "Batería",
        answerBatteryCharging: "cargando",
        answerBatteryPlugged: "enchufado",
        answerMemoryLabel: "Memoria",
        answerMemoryFormat: "%@ de %@ en uso",
        answerStorageLabel: "Almacenamiento",
        answerStorageFormat: "%@ libres de %@",
        copyHint: "Retorno copia",
        kindWindow: "Ventana",
        quitFormat: "Salir de %@",
        quitConfirmFormat: "¿Salir de %@?",
        kindMenu: "Comando de menú",
        actionsTitle: "Acciones",
        actionsHint: "Acciones",
        actionPin: "Fijar arriba",
        actionUnpin: "Dejar de fijar",
        actionName: "Ponerle tu propio nombre",
        actionRename: "Cambiar el nombre al que responde",
        actionHide: "No mostrar nunca esto",
        actionForget: "Olvidar cuánto uso esto",
        aliasPlaceholder: "El nombre con el que lo llamas",
        aliasTakenFormat: "%@ ya responde a ese nombre",
        sourcesTitle: "Lo que busca la barra",
        sourcesCaption: "Desactiva lo que nunca quieras ver. Tus acciones se quedan siempre.",
        sourceActions: "Acciones de Vorssaint",
        sourceApps: "Apps",
        sourceMenus: "Comandos de menú de la app al frente",
        sourceWindows: "Ventanas abiertas",
        sourceQuitApps: "Salir de una app",
        sourceSettingsPages: "Páginas de Ajustes",
        sourceSnippets: "Fragmentos",
        sourceClipboard: "Historial del portapapeles",
        sourceEmoji: "Emoji",
        sourceFolders: "Carpetas",
        sourceAnswers: "Respuestas sobre este Mac",
        sourceCalculator: "Cuentas y conversiones",
        namedTitle: "Nombres que pusiste",
        namedEmpty: "Aún no hay nombres. Abre la barra, elige una fila y pulsa la tecla de acciones.",
        pinnedTitle: "Fijados",
        pinnedEmpty: "Aún no hay nada fijado.",
        hiddenTitle: "No mostrar nunca",
        hiddenEmpty: "No hay nada oculto.",
        forgetAllButton: "Olvidar lo que más uso",
        tryTheseLabel: "Prueba",
        stillLooking: "Aún buscando",
        removeButton: "Quitar",
        confirmButton: "Confirmar",
        soundMute: "Silenciar el sonido",
        soundUnmute: "Volver a activar el sonido",
        stateOn: "activo",
        powerSleep: "Reposo",
        powerRestart: "Reiniciar",
        powerRestartConfirm: "¿Reiniciar el Mac?",
        powerShutDown: "Apagar",
        powerShutDownConfirm: "¿Apagar el Mac?",
        powerLogOut: "Cerrar sesión",
        powerLogOutConfirm: "¿Cerrar la sesión?",
        wifiOn: "Activar el Wi-Fi",
        wifiOff: "Desactivar el Wi-Fi",
        kindEmoji: "Emoji",
        kindFolder: "Carpeta",
        answerDateLabel: "Hoy",
        answerTimeLabel: "Hora actual",
        kindAnswer: "Respuesta",
        kindSelection: "Selección",
        selectedTitle: "Seleccionado",
        selectionCopy: "Copiar",
        selectionSearch: "Usar en la búsqueda",
        selectionUpper: "MAYÚSCULAS",
        selectionLower: "minúsculas",
        selectionTitleCase: "Iniciales Mayúsculas",
        selectionShelf: "Guardar en la bandeja",
        selectionCount: "Contar",
        selectionCountFormat: "%d palabras, %d caracteres",
        sourceSelection: "Lo que está seleccionado",
        kindLink: "Tu atajo",
        linkSearchHint: "Escribe qué buscar después del nombre",
        linksTitle: "Tus atajos",
        linksEmpty: "Nada guardado aún. Añade un sitio, una carpeta o una búsqueda que abras a diario.",
        linkDestinationLabel: "Adónde va",
        linkKindLink: "Sitio o enlace",
        linkKindPlace: "Carpeta o archivo",
        linkPlaceholdersHint: "Pon uno de estos y se rellena al abrir",
        placeholderQuery: "lo que escribas",
        placeholderClipboard: "lo que copiaste",
        placeholderSelection: "lo que está seleccionado",
        placeholderDate: "hoy",
        privacyNote: "Todo ocurre en este Mac: sin cuenta, sin nube, nada sale de aquí.",
        actionShortcut: "Darle un atajo",
        actionShortcutChange: "Cambiar el atajo",
        actionShortcutRemove: "Quitar el atajo",
        shortcutCaptureHint: "Pulsa las teclas que quieras · Suprimir lo borra · Esc vuelve",
        rowShortcutsTitle: "Filas con atajo propio",
        rowShortcutsEmpty: "Ninguna fila tiene atajo aún. Abre las acciones de cualquier fila para darle uno.",
        turnOnFormat: "Activar %@",
        turnOffFormat: "Desactivar %@",
        everythingTitle: "Todo lo que puede hacer",
        categoryAll: "Todo",
        restartAppFormat: "Reiniciar %@",
        forceQuitAppFormat: "Forzar salida de %@…",
        forceQuitAppConfirmFormat: "¿Forzar la salida de %@? Se perderán los cambios no guardados.",
        uninstallAppFormat: "Desinstalar %@…")

    static let de = CommandBarFeatureStrings(
        pageTitle: "Befehlsleiste",
        hubDescription: "Ein Feld, das alles findet und ausführt, was die App kann",
        panelCaption: "Tippen, finden, ausführen",
        settingsCaption: "Ein Kurzbefehl öffnet ein Feld über dem, was du gerade tust. Ein paar Buchstaben tippen, Return drücken, fertig. Nichts von dem, was du tippst, wird gespeichert.",
        openButton: "Leiste jetzt öffnen",
        searchPlaceholder: "Tippe, was du tun möchtest",
        suggestionsLabel: "Vorschläge",
        noResultsTitle: "Nichts mit diesem Namen gefunden.",
        noResultsAction: "Vorschläge ansehen",
        argumentRangeFormat: "%d bis %d",
        argumentHint: "Return übernimmt · Esc geht zurück",
        confirmHint: "Return bestätigt · Esc bricht ab",
        kindApp: "App",
        kindClipboard: "Aus dem Verlauf einsetzen",
        kindSnippet: "Textbaustein einfügen",
        soundOutputSubtitle: "Tonausgabe wechseln",
        soundOutputCurrent: "Aktuelle Ausgabe",
        volumeTitle: "Lautstärke",
        brightnessTitle: "Bildschirmhelligkeit",
        keepAwakeForFormat: "%@ wachhalten",
        needsSetupFormat: "Aktiviere %@ in den Einstellungen",
        needsPermissionHint: "Braucht eine Berechtigung · Return fragt nach",
        actionCheckAppUpdates: "App-Updates prüfen",
        actionCleanURL: "Kopierten Link bereinigen",
        actionOpenSettings: "Einstellungen öffnen",
        answerBatteryLabel: "Batterie",
        answerBatteryCharging: "lädt",
        answerBatteryPlugged: "am Netzteil",
        answerMemoryLabel: "Arbeitsspeicher",
        answerMemoryFormat: "%@ von %@ belegt",
        answerStorageLabel: "Speicherplatz",
        answerStorageFormat: "%@ frei von %@",
        copyHint: "Return kopiert",
        kindWindow: "Fenster",
        quitFormat: "%@ beenden",
        quitConfirmFormat: "%@ beenden?",
        kindMenu: "Menübefehl",
        actionsTitle: "Aktionen",
        actionsHint: "Aktionen",
        actionPin: "Oben anheften",
        actionUnpin: "Loslösen",
        actionName: "Eigenen Namen geben",
        actionRename: "Namen ändern, auf den es hört",
        actionHide: "Nie anzeigen",
        actionForget: "Vergessen, wie oft ich das nutze",
        aliasPlaceholder: "Der Name, den du benutzt",
        aliasTakenFormat: "%@ hört bereits auf diesen Namen",
        sourcesTitle: "Was die Leiste durchsucht",
        sourcesCaption: "Schalte aus, was du nie sehen willst. Deine Aktionen bleiben immer.",
        sourceActions: "Vorssaint-Aktionen",
        sourceApps: "Apps",
        sourceMenus: "Menübefehle der App im Vordergrund",
        sourceWindows: "Offene Fenster",
        sourceQuitApps: "Eine App beenden",
        sourceSettingsPages: "Einstellungsseiten",
        sourceSnippets: "Textbausteine",
        sourceClipboard: "Zwischenablage-Verlauf",
        sourceEmoji: "Emoji",
        sourceFolders: "Ordner",
        sourceAnswers: "Antworten über diesen Mac",
        sourceCalculator: "Rechnen und Umrechnen",
        namedTitle: "Vergebene Namen",
        namedEmpty: "Noch nichts benannt. Leiste öffnen, Zeile wählen, Aktionstaste drücken.",
        pinnedTitle: "Angeheftet",
        pinnedEmpty: "Noch nichts angeheftet.",
        hiddenTitle: "Nie anzeigen",
        hiddenEmpty: "Nichts ausgeblendet.",
        forgetAllButton: "Vergessen, was ich am meisten nutze",
        tryTheseLabel: "Probier",
        stillLooking: "Suche noch",
        removeButton: "Entfernen",
        confirmButton: "Bestätigen",
        soundMute: "Ton stummschalten",
        soundUnmute: "Ton wieder einschalten",
        stateOn: "an",
        powerSleep: "Ruhezustand",
        powerRestart: "Neustart",
        powerRestartConfirm: "Mac neu starten?",
        powerShutDown: "Ausschalten",
        powerShutDownConfirm: "Mac ausschalten?",
        powerLogOut: "Abmelden",
        powerLogOutConfirm: "Abmelden?",
        wifiOn: "WLAN aktivieren",
        wifiOff: "WLAN deaktivieren",
        kindEmoji: "Emoji",
        kindFolder: "Ordner",
        answerDateLabel: "Heute",
        answerTimeLabel: "Uhrzeit",
        kindAnswer: "Antwort",
        kindSelection: "Auswahl",
        selectedTitle: "Ausgewählt",
        selectionCopy: "Kopieren",
        selectionSearch: "In der Suche verwenden",
        selectionUpper: "GROSSBUCHSTABEN",
        selectionLower: "kleinbuchstaben",
        selectionTitleCase: "Erste Buchstaben Groß",
        selectionShelf: "Im Ablagefach behalten",
        selectionCount: "Zählen",
        selectionCountFormat: "%d Wörter, %d Zeichen",
        sourceSelection: "Was ausgewählt ist",
        kindLink: "Ihr Kurzbefehl",
        linkSearchHint: "Nach dem Namen eingeben, wonach gesucht wird",
        linksTitle: "Ihre Kurzbefehle",
        linksEmpty: "Noch nichts gespeichert. Fügen Sie eine Seite, einen Ordner oder eine Suche hinzu, die Sie täglich öffnen.",
        linkDestinationLabel: "Wohin es führt",
        linkKindLink: "Seite oder Link",
        linkKindPlace: "Ordner oder Datei",
        linkPlaceholdersHint: "Eines davon einsetzen, es wird beim Öffnen ausgefüllt",
        placeholderQuery: "was Sie eingeben",
        placeholderClipboard: "was Sie kopiert haben",
        placeholderSelection: "was ausgewählt ist",
        placeholderDate: "heute",
        privacyNote: "Alles passiert auf diesem Mac: kein Konto, keine Cloud, nichts verlässt ihn.",
        actionShortcut: "Kurzbefehl geben",
        actionShortcutChange: "Kurzbefehl ändern",
        actionShortcutRemove: "Kurzbefehl entfernen",
        shortcutCaptureHint: "Gewünschte Tasten drücken · Entf löscht · Esc geht zurück",
        rowShortcutsTitle: "Zeilen mit eigenem Kurzbefehl",
        rowShortcutsEmpty: "Noch hat keine Zeile einen eigenen Kurzbefehl. Öffnen Sie die Aktionen einer Zeile, um einen zu vergeben.",
        turnOnFormat: "%@ einschalten",
        turnOffFormat: "%@ ausschalten",
        everythingTitle: "Alles, was sie kann",
        categoryAll: "Alle",
        restartAppFormat: "%@ neu starten",
        forceQuitAppFormat: "%@ sofort beenden…",
        forceQuitAppConfirmFormat: "%@ sofort beenden? Nicht gesicherte Änderungen gehen verloren.",
        uninstallAppFormat: "%@ deinstallieren…")

    static let fr = CommandBarFeatureStrings(
        pageTitle: "Barre de commande",
        hubDescription: "Un champ qui trouve et lance tout ce que fait l'app",
        panelCaption: "Tapez pour trouver et lancer ce que vous voulez",
        settingsCaption: "Un raccourci ouvre un champ par-dessus ce que vous faites. Tapez quelques lettres, appuyez sur Retour, c'est fait. Rien de ce que vous tapez n'est enregistré.",
        openButton: "Ouvrir la barre maintenant",
        searchPlaceholder: "Tapez ce que vous voulez faire",
        suggestionsLabel: "Suggestions",
        noResultsTitle: "Rien à ce nom par ici.",
        noResultsAction: "Voir les suggestions",
        argumentRangeFormat: "%d à %d",
        argumentHint: "Retour applique · Échap revient",
        confirmHint: "Retour confirme · Échap annule",
        kindApp: "App",
        kindClipboard: "Coller depuis l'historique",
        kindSnippet: "Insérer un extrait",
        soundOutputSubtitle: "Changer la sortie audio",
        soundOutputCurrent: "Sortie actuelle",
        volumeTitle: "Volume",
        brightnessTitle: "Luminosité de l'écran",
        keepAwakeForFormat: "Garder éveillé pendant %@",
        needsSetupFormat: "Activez %@ dans les Réglages",
        needsPermissionHint: "Autorisation nécessaire · Retour la demande",
        actionCheckAppUpdates: "Rechercher les mises à jour des apps",
        actionCleanURL: "Nettoyer le lien copié",
        actionOpenSettings: "Ouvrir les Réglages",
        answerBatteryLabel: "Batterie",
        answerBatteryCharging: "en charge",
        answerBatteryPlugged: "sur secteur",
        answerMemoryLabel: "Mémoire",
        answerMemoryFormat: "%@ sur %@ utilisés",
        answerStorageLabel: "Stockage",
        answerStorageFormat: "%@ libres sur %@",
        copyHint: "Retour copie",
        kindWindow: "Fenêtre",
        quitFormat: "Quitter %@",
        quitConfirmFormat: "Quitter %@ ?",
        kindMenu: "Commande de menu",
        actionsTitle: "Actions",
        actionsHint: "Actions",
        actionPin: "Épingler en haut",
        actionUnpin: "Détacher",
        actionName: "Lui donner votre nom",
        actionRename: "Changer le nom auquel il répond",
        actionHide: "Ne jamais montrer ceci",
        actionForget: "Oublier à quel point je l'utilise",
        aliasPlaceholder: "Le nom que vous employez",
        aliasTakenFormat: "%@ répond déjà à ce nom",
        sourcesTitle: "Ce que la barre cherche",
        sourcesCaption: "Désactivez ce que vous ne voulez jamais voir. Vos actions restent toujours.",
        sourceActions: "Actions Vorssaint",
        sourceApps: "Apps",
        sourceMenus: "Commandes de menu de l'app au premier plan",
        sourceWindows: "Fenêtres ouvertes",
        sourceQuitApps: "Quitter une app",
        sourceSettingsPages: "Pages des Réglages",
        sourceSnippets: "Extraits",
        sourceClipboard: "Historique du presse-papiers",
        sourceEmoji: "Émoji",
        sourceFolders: "Dossiers",
        sourceAnswers: "Réponses sur ce Mac",
        sourceCalculator: "Calculs et conversions",
        namedTitle: "Noms que vous avez donnés",
        namedEmpty: "Rien de nommé pour l'instant. Ouvrez la barre, choisissez une ligne, appuyez sur la touche d'actions.",
        pinnedTitle: "Épinglés",
        pinnedEmpty: "Rien d'épinglé pour l'instant.",
        hiddenTitle: "Ne jamais montrer",
        hiddenEmpty: "Rien de masqué.",
        forgetAllButton: "Oublier ce que j'utilise le plus",
        tryTheseLabel: "Essayez",
        stillLooking: "Recherche en cours",
        removeButton: "Retirer",
        confirmButton: "Confirmer",
        soundMute: "Couper le son",
        soundUnmute: "Réactiver le son",
        stateOn: "activé",
        powerSleep: "Suspendre l'activité",
        powerRestart: "Redémarrer",
        powerRestartConfirm: "Redémarrer le Mac ?",
        powerShutDown: "Éteindre",
        powerShutDownConfirm: "Éteindre le Mac ?",
        powerLogOut: "Fermer la session",
        powerLogOutConfirm: "Fermer la session ?",
        wifiOn: "Activer le Wi-Fi",
        wifiOff: "Désactiver le Wi-Fi",
        kindEmoji: "Émoji",
        kindFolder: "Dossier",
        answerDateLabel: "Aujourd'hui",
        answerTimeLabel: "Heure actuelle",
        kindAnswer: "Réponse",
        kindSelection: "Sélection",
        selectedTitle: "Sélectionné",
        selectionCopy: "Copier",
        selectionSearch: "Utiliser dans la recherche",
        selectionUpper: "MAJUSCULES",
        selectionLower: "minuscules",
        selectionTitleCase: "Initiales En Majuscules",
        selectionShelf: "Garder sur l’étagère",
        selectionCount: "Compter",
        selectionCountFormat: "%d mots, %d caractères",
        sourceSelection: "Ce qui est sélectionné",
        kindLink: "Votre raccourci",
        linkSearchHint: "Tapez quoi chercher après le nom",
        linksTitle: "Vos raccourcis",
        linksEmpty: "Rien d’enregistré. Ajoutez un site, un dossier ou une recherche que vous ouvrez tous les jours.",
        linkDestinationLabel: "Où il mène",
        linkKindLink: "Site ou lien",
        linkKindPlace: "Dossier ou fichier",
        linkPlaceholdersHint: "Mettez-en un et il se remplit à l’ouverture",
        placeholderQuery: "ce que vous tapez",
        placeholderClipboard: "ce que vous avez copié",
        placeholderSelection: "ce qui est sélectionné",
        placeholderDate: "aujourd’hui",
        privacyNote: "Tout se passe sur ce Mac : pas de compte, pas de cloud, rien ne sort.",
        actionShortcut: "Lui donner un raccourci",
        actionShortcutChange: "Changer le raccourci",
        actionShortcutRemove: "Retirer le raccourci",
        shortcutCaptureHint: "Appuyez sur les touches voulues · Suppr efface · Échap revient",
        rowShortcutsTitle: "Lignes avec leur raccourci",
        rowShortcutsEmpty: "Aucune ligne n’a encore de raccourci. Ouvrez les actions d’une ligne pour lui en donner un.",
        turnOnFormat: "Activer %@",
        turnOffFormat: "Désactiver %@",
        everythingTitle: "Tout ce qu’elle sait faire",
        categoryAll: "Tout",
        restartAppFormat: "Relancer %@",
        forceQuitAppFormat: "Forcer %@ à quitter…",
        forceQuitAppConfirmFormat: "Forcer %@ à quitter ? Les modifications non enregistrées seront perdues.",
        uninstallAppFormat: "Désinstaller %@…")

    static let it = CommandBarFeatureStrings(
        pageTitle: "Barra dei comandi",
        hubDescription: "Un campo che trova ed esegue tutto ciò che fa l'app",
        panelCaption: "Scrivi per trovare ed eseguire qualsiasi cosa",
        settingsCaption: "Una scorciatoia apre un campo sopra quello che stai facendo. Scrivi qualche lettera, premi Invio e via. Niente di ciò che scrivi viene salvato.",
        openButton: "Apri la barra adesso",
        searchPlaceholder: "Scrivi cosa vuoi fare",
        suggestionsLabel: "Suggerimenti",
        noResultsTitle: "Qui non c'è niente con questo nome.",
        noResultsAction: "Vedi i suggerimenti",
        argumentRangeFormat: "da %d a %d",
        argumentHint: "Invio applica · Esc torna indietro",
        confirmHint: "Invio conferma · Esc annulla",
        kindApp: "App",
        kindClipboard: "Incolla dalla cronologia",
        kindSnippet: "Inserisci snippet",
        soundOutputSubtitle: "Cambia uscita audio",
        soundOutputCurrent: "Uscita attuale",
        volumeTitle: "Volume",
        brightnessTitle: "Luminosità dello schermo",
        keepAwakeForFormat: "Mantieni attivo per %@",
        needsSetupFormat: "Attiva %@ nelle Impostazioni",
        needsPermissionHint: "Serve un'autorizzazione · Invio la chiede",
        actionCheckAppUpdates: "Controlla gli aggiornamenti delle app",
        actionCleanURL: "Pulisci il link copiato",
        actionOpenSettings: "Apri le Impostazioni",
        answerBatteryLabel: "Batteria",
        answerBatteryCharging: "in carica",
        answerBatteryPlugged: "alimentazione",
        answerMemoryLabel: "Memoria",
        answerMemoryFormat: "%@ di %@ in uso",
        answerStorageLabel: "Archiviazione",
        answerStorageFormat: "%@ liberi di %@",
        copyHint: "Invio copia",
        kindWindow: "Finestra",
        quitFormat: "Esci da %@",
        quitConfirmFormat: "Uscire da %@?",
        kindMenu: "Comando di menu",
        actionsTitle: "Azioni",
        actionsHint: "Azioni",
        actionPin: "Fissa in alto",
        actionUnpin: "Togli dai fissati",
        actionName: "Dagli un nome tuo",
        actionRename: "Cambia il nome a cui risponde",
        actionHide: "Non mostrare mai questo",
        actionForget: "Dimentica quanto lo uso",
        aliasPlaceholder: "Il nome con cui lo chiami",
        aliasTakenFormat: "%@ risponde già a questo nome",
        sourcesTitle: "Cosa cerca la barra",
        sourcesCaption: "Disattiva ciò che non vuoi mai vedere. Le tue azioni restano sempre.",
        sourceActions: "Azioni di Vorssaint",
        sourceApps: "App",
        sourceMenus: "Comandi di menu dell'app in primo piano",
        sourceWindows: "Finestre aperte",
        sourceQuitApps: "Esci da un'app",
        sourceSettingsPages: "Pagine delle Impostazioni",
        sourceSnippets: "Snippet",
        sourceClipboard: "Cronologia degli appunti",
        sourceEmoji: "Emoji",
        sourceFolders: "Cartelle",
        sourceAnswers: "Risposte su questo Mac",
        sourceCalculator: "Calcoli e conversioni",
        namedTitle: "Nomi che hai dato",
        namedEmpty: "Ancora nessun nome. Apri la barra, scegli una riga e premi il tasto azioni.",
        pinnedTitle: "Fissati",
        pinnedEmpty: "Ancora niente di fissato.",
        hiddenTitle: "Non mostrare mai",
        hiddenEmpty: "Niente di nascosto.",
        forgetAllButton: "Dimentica cosa uso di più",
        tryTheseLabel: "Prova",
        stillLooking: "Sto ancora cercando",
        removeButton: "Rimuovi",
        confirmButton: "Conferma",
        soundMute: "Silenzia l'audio",
        soundUnmute: "Riattiva l'audio",
        stateOn: "attivo",
        powerSleep: "Stop",
        powerRestart: "Riavvia",
        powerRestartConfirm: "Riavviare il Mac?",
        powerShutDown: "Spegni",
        powerShutDownConfirm: "Spegnere il Mac?",
        powerLogOut: "Esci",
        powerLogOutConfirm: "Uscire dalla sessione?",
        wifiOn: "Attiva il Wi-Fi",
        wifiOff: "Disattiva il Wi-Fi",
        kindEmoji: "Emoji",
        kindFolder: "Cartella",
        answerDateLabel: "Oggi",
        answerTimeLabel: "Ora attuale",
        kindAnswer: "Risposta",
        kindSelection: "Selezione",
        selectedTitle: "Selezionato",
        selectionCopy: "Copia",
        selectionSearch: "Usa nella ricerca",
        selectionUpper: "MAIUSCOLE",
        selectionLower: "minuscole",
        selectionTitleCase: "Iniziali Maiuscole",
        selectionShelf: "Tieni nel ripiano",
        selectionCount: "Conta",
        selectionCountFormat: "%d parole, %d caratteri",
        sourceSelection: "Ciò che è selezionato",
        kindLink: "La tua scorciatoia",
        linkSearchHint: "Scrivi cosa cercare dopo il nome",
        linksTitle: "Le tue scorciatoie",
        linksEmpty: "Niente salvato. Aggiungi un sito, una cartella o una ricerca che apri ogni giorno.",
        linkDestinationLabel: "Dove porta",
        linkKindLink: "Sito o link",
        linkKindPlace: "Cartella o file",
        linkPlaceholdersHint: "Metti uno di questi e viene riempito all’apertura",
        placeholderQuery: "quello che scrivi",
        placeholderClipboard: "quello che hai copiato",
        placeholderSelection: "quello che è selezionato",
        placeholderDate: "oggi",
        privacyNote: "Tutto avviene su questo Mac: nessun account, nessun cloud, niente esce di qui.",
        actionShortcut: "Dagli una scorciatoia",
        actionShortcutChange: "Cambia la scorciatoia",
        actionShortcutRemove: "Togli la scorciatoia",
        shortcutCaptureHint: "Premi i tasti che vuoi · Canc cancella · Esc torna indietro",
        rowShortcutsTitle: "Righe con scorciatoia propria",
        rowShortcutsEmpty: "Nessuna riga ha ancora una scorciatoia. Apri le azioni di una riga per dargliene una.",
        turnOnFormat: "Attiva %@",
        turnOffFormat: "Disattiva %@",
        everythingTitle: "Tutto quello che sa fare",
        categoryAll: "Tutto",
        restartAppFormat: "Riavvia %@",
        forceQuitAppFormat: "Forza l’uscita da %@…",
        forceQuitAppConfirmFormat: "Forzare l’uscita da %@? Le modifiche non salvate andranno perse.",
        uninstallAppFormat: "Disinstalla %@…")

    static let ja = CommandBarFeatureStrings(
        pageTitle: "コマンドバー",
        hubDescription: "アプリのすべての機能を見つけて実行できる入力欄",
        panelCaption: "入力するだけで見つけて実行",
        settingsCaption: "ショートカットひとつで、作業中の画面の上に入力欄が開きます。数文字入力して Return を押すだけ。入力した内容は保存されません。",
        openButton: "今すぐバーを開く",
        searchPlaceholder: "やりたいことを入力",
        suggestionsLabel: "候補",
        noResultsTitle: "その名前では見つかりませんでした。",
        noResultsAction: "候補を見る",
        argumentRangeFormat: "%d〜%d",
        argumentHint: "Return で適用 · Esc で戻る",
        confirmHint: "Return で実行 · Esc でキャンセル",
        kindApp: "アプリ",
        kindClipboard: "履歴からペースト",
        kindSnippet: "スニペットを挿入",
        soundOutputSubtitle: "サウンド出力を切り替え",
        soundOutputCurrent: "現在の出力",
        volumeTitle: "音量",
        brightnessTitle: "画面の明るさ",
        keepAwakeForFormat: "%@スリープ防止",
        needsSetupFormat: "設定で「%@」をオンにしてください",
        needsPermissionHint: "許可が必要です · Return で要求",
        actionCheckAppUpdates: "アプリのアップデートを確認",
        actionCleanURL: "コピーした URL をクリーン",
        actionOpenSettings: "設定を開く",
        answerBatteryLabel: "バッテリー",
        answerBatteryCharging: "充電中",
        answerBatteryPlugged: "電源に接続",
        answerMemoryLabel: "メモリ",
        answerMemoryFormat: "%@ / %@ を使用中",
        answerStorageLabel: "ストレージ",
        answerStorageFormat: "空き %@ / %@",
        copyHint: "Return でコピー",
        kindWindow: "ウインドウ",
        quitFormat: "%@を終了",
        quitConfirmFormat: "%@を終了しますか？",
        kindMenu: "メニュー項目",
        actionsTitle: "アクション",
        actionsHint: "アクション",
        actionPin: "上部に固定",
        actionUnpin: "固定を解除",
        actionName: "自分の名前を付ける",
        actionRename: "反応する名前を変更",
        actionHide: "これは表示しない",
        actionForget: "使用頻度を忘れる",
        aliasPlaceholder: "あなたが呼んでいる名前",
        aliasTakenFormat: "%@ がすでにその名前です",
        sourcesTitle: "バーが探すもの",
        sourcesCaption: "見たくないものはオフに。自分のアクションは常に残ります。",
        sourceActions: "Vorssaint のアクション",
        sourceApps: "アプリ",
        sourceMenus: "最前面のアプリのメニュー項目",
        sourceWindows: "開いているウインドウ",
        sourceQuitApps: "アプリを終了",
        sourceSettingsPages: "設定ページ",
        sourceSnippets: "スニペット",
        sourceClipboard: "クリップボードの履歴",
        sourceEmoji: "絵文字",
        sourceFolders: "フォルダ",
        sourceAnswers: "この Mac についての答え",
        sourceCalculator: "計算と変換",
        namedTitle: "付けた名前",
        namedEmpty: "まだ名前はありません。バーを開いて行を選び、アクションキーを押してください。",
        pinnedTitle: "固定済み",
        pinnedEmpty: "まだ何も固定していません。",
        hiddenTitle: "表示しない",
        hiddenEmpty: "非表示のものはありません。",
        forgetAllButton: "よく使うものを忘れる",
        tryTheseLabel: "お試し",
        stillLooking: "検索中",
        removeButton: "削除",
        confirmButton: "確認",
        soundMute: "サウンドを消音",
        soundUnmute: "サウンドを元に戻す",
        stateOn: "オン",
        powerSleep: "スリープ",
        powerRestart: "再起動",
        powerRestartConfirm: "Mac を再起動しますか？",
        powerShutDown: "システム終了",
        powerShutDownConfirm: "Mac を終了しますか？",
        powerLogOut: "ログアウト",
        powerLogOutConfirm: "ログアウトしますか？",
        wifiOn: "Wi-Fi をオンにする",
        wifiOff: "Wi-Fi をオフにする",
        kindEmoji: "絵文字",
        kindFolder: "フォルダ",
        answerDateLabel: "今日",
        answerTimeLabel: "現在の時刻",
        kindAnswer: "答え",
        kindSelection: "選択範囲",
        selectedTitle: "選択中",
        selectionCopy: "コピー",
        selectionSearch: "検索に使う",
        selectionUpper: "大文字",
        selectionLower: "小文字",
        selectionTitleCase: "先頭を大文字",
        selectionShelf: "シェルフに置く",
        selectionCount: "数える",
        selectionCountFormat: "%d 語、%d 文字",
        sourceSelection: "選択されているもの",
        kindLink: "自分のショートカット",
        linkSearchHint: "名前の後に探すものを入力します",
        linksTitle: "自分のショートカット",
        linksEmpty: "まだ何もありません。毎日開くサイトやフォルダ、検索を追加してください。",
        linkDestinationLabel: "開く先",
        linkKindLink: "サイトまたはリンク",
        linkKindPlace: "フォルダまたはファイル",
        linkPlaceholdersHint: "これを入れておくと、開くときに埋まります",
        placeholderQuery: "入力した内容",
        placeholderClipboard: "コピーした内容",
        placeholderSelection: "選択されているもの",
        placeholderDate: "今日",
        privacyNote: "すべてこの Mac の中で完結します。アカウントもクラウドもなく、外には何も送りません。",
        actionShortcut: "ショートカットを設定",
        actionShortcutChange: "ショートカットを変更",
        actionShortcutRemove: "ショートカットを外す",
        shortcutCaptureHint: "使いたいキーを押します · Delete で消去 · Esc で戻る",
        rowShortcutsTitle: "独自のショートカットがある行",
        rowShortcutsEmpty: "まだどの行にもショートカットがありません。行のアクションを開いて設定してください。",
        turnOnFormat: "%@ をオン",
        turnOffFormat: "%@ をオフ",
        everythingTitle: "できること全部",
        categoryAll: "すべて",
        restartAppFormat: "%@を再起動",
        forceQuitAppFormat: "%@を強制終了…",
        forceQuitAppConfirmFormat: "%@を強制終了しますか？保存していない変更内容は失われます。",
        uninstallAppFormat: "%@をアンインストール…")

    static let ko = CommandBarFeatureStrings(
        pageTitle: "명령 막대",
        hubDescription: "앱의 모든 기능을 찾아서 실행하는 하나의 입력란",
        panelCaption: "입력해서 찾고 바로 실행",
        settingsCaption: "단축키 하나로 지금 하던 작업 위에 입력란이 열립니다. 몇 글자 입력하고 Return을 누르면 끝. 입력한 내용은 저장되지 않습니다.",
        openButton: "지금 막대 열기",
        searchPlaceholder: "하고 싶은 일을 입력",
        suggestionsLabel: "제안",
        noResultsTitle: "그 이름으로는 아무것도 없습니다.",
        noResultsAction: "제안 보기",
        argumentRangeFormat: "%d~%d",
        argumentHint: "Return 적용 · Esc 뒤로",
        confirmHint: "Return 확인 · Esc 취소",
        kindApp: "앱",
        kindClipboard: "기록에서 붙여넣기",
        kindSnippet: "스니펫 삽입",
        soundOutputSubtitle: "사운드 출력 전환",
        soundOutputCurrent: "현재 출력",
        volumeTitle: "음량",
        brightnessTitle: "화면 밝기",
        keepAwakeForFormat: "%@ 동안 절전 방지",
        needsSetupFormat: "설정에서 %@ 기능을 켜세요",
        needsPermissionHint: "권한이 필요합니다 · Return으로 요청",
        actionCheckAppUpdates: "앱 업데이트 확인",
        actionCleanURL: "복사한 링크 정리",
        actionOpenSettings: "설정 열기",
        answerBatteryLabel: "배터리",
        answerBatteryCharging: "충전 중",
        answerBatteryPlugged: "전원 연결됨",
        answerMemoryLabel: "메모리",
        answerMemoryFormat: "%@ / %@ 사용 중",
        answerStorageLabel: "저장 공간",
        answerStorageFormat: "%@ 사용 가능 / %@",
        copyHint: "Return으로 복사",
        kindWindow: "윈도우",
        quitFormat: "%@ 종료",
        quitConfirmFormat: "%@을(를) 종료할까요?",
        kindMenu: "메뉴 명령",
        actionsTitle: "동작",
        actionsHint: "동작",
        actionPin: "맨 위에 고정",
        actionUnpin: "고정 해제",
        actionName: "내 이름 지정",
        actionRename: "반응할 이름 변경",
        actionHide: "이것은 표시하지 않기",
        actionForget: "얼마나 자주 쓰는지 잊기",
        aliasPlaceholder: "당신이 부르는 이름",
        aliasTakenFormat: "%@이(가) 이미 그 이름을 씁니다",
        sourcesTitle: "막대가 찾는 것",
        sourcesCaption: "보고 싶지 않은 것은 끄세요. 내 동작은 항상 남습니다.",
        sourceActions: "Vorssaint 동작",
        sourceApps: "앱",
        sourceMenus: "맨 앞 앱의 메뉴 명령",
        sourceWindows: "열린 윈도우",
        sourceQuitApps: "앱 종료",
        sourceSettingsPages: "설정 페이지",
        sourceSnippets: "스니펫",
        sourceClipboard: "클립보드 기록",
        sourceEmoji: "이모티콘",
        sourceFolders: "폴더",
        sourceAnswers: "이 Mac에 대한 답",
        sourceCalculator: "계산과 변환",
        namedTitle: "지정한 이름",
        namedEmpty: "아직 이름이 없습니다. 막대를 열고 행을 선택한 뒤 동작 키를 누르세요.",
        pinnedTitle: "고정됨",
        pinnedEmpty: "아직 고정한 것이 없습니다.",
        hiddenTitle: "표시하지 않기",
        hiddenEmpty: "숨긴 것이 없습니다.",
        forgetAllButton: "자주 쓰는 것 잊기",
        tryTheseLabel: "해보기",
        stillLooking: "아직 찾는 중",
        removeButton: "제거",
        confirmButton: "확인",
        soundMute: "소리 끄기",
        soundUnmute: "소리 다시 켜기",
        stateOn: "켜짐",
        powerSleep: "잠자기",
        powerRestart: "재시동",
        powerRestartConfirm: "Mac을 재시동할까요?",
        powerShutDown: "시스템 종료",
        powerShutDownConfirm: "Mac을 종료할까요?",
        powerLogOut: "로그아웃",
        powerLogOutConfirm: "로그아웃할까요?",
        wifiOn: "Wi-Fi 켜기",
        wifiOff: "Wi-Fi 끄기",
        kindEmoji: "이모티콘",
        kindFolder: "폴더",
        answerDateLabel: "오늘",
        answerTimeLabel: "현재 시각",
        kindAnswer: "답",
        kindSelection: "선택 항목",
        selectedTitle: "선택함",
        selectionCopy: "복사",
        selectionSearch: "검색에 사용",
        selectionUpper: "대문자",
        selectionLower: "소문자",
        selectionTitleCase: "첫 글자만 대문자",
        selectionShelf: "선반에 보관",
        selectionCount: "세기",
        selectionCountFormat: "%d단어, %d자",
        sourceSelection: "선택한 내용",
        kindLink: "내 단축키",
        linkSearchHint: "이름 뒤에 찾을 내용을 입력합니다",
        linksTitle: "내 단축키",
        linksEmpty: "아직 없습니다. 매일 여는 사이트나 폴더, 검색을 추가하십시오.",
        linkDestinationLabel: "가는 곳",
        linkKindLink: "사이트 또는 링크",
        linkKindPlace: "폴더 또는 파일",
        linkPlaceholdersHint: "이 중 하나를 넣으면 열 때 채워집니다",
        placeholderQuery: "입력한 내용",
        placeholderClipboard: "복사한 내용",
        placeholderSelection: "선택한 내용",
        placeholderDate: "오늘",
        privacyNote: "모두 이 Mac 안에서 처리됩니다. 계정도 클라우드도 없고 밖으로 나가는 것도 없습니다.",
        actionShortcut: "단축키 지정",
        actionShortcutChange: "단축키 변경",
        actionShortcutRemove: "단축키 해제",
        shortcutCaptureHint: "원하는 키를 누르십시오 · Delete는 지웁니다 · Esc는 돌아갑니다",
        rowShortcutsTitle: "자체 단축키가 있는 항목",
        rowShortcutsEmpty: "아직 단축키가 있는 항목이 없습니다. 항목의 동작을 열어 지정하십시오.",
        turnOnFormat: "%@ 켜기",
        turnOffFormat: "%@ 끄기",
        everythingTitle: "할 수 있는 모든 것",
        categoryAll: "전체",
        restartAppFormat: "%@ 재시작",
        forceQuitAppFormat: "%@ 강제 종료…",
        forceQuitAppConfirmFormat: "%@ 앱을 강제로 종료할까요? 저장하지 않은 변경 사항은 사라집니다.",
        uninstallAppFormat: "%@ 제거…")

    static let zhHans = CommandBarFeatureStrings(
        pageTitle: "命令栏",
        hubDescription: "一个输入框，找到并执行 App 的所有功能",
        panelCaption: "输入即可找到并执行任何功能",
        settingsCaption: "一个快捷键就能在当前屏幕上打开输入框。输入几个字母，按下 Return 即可完成。输入的内容不会保存。",
        openButton: "立即打开命令栏",
        searchPlaceholder: "输入你想做的事",
        suggestionsLabel: "建议",
        noResultsTitle: "没有找到这个名称。",
        noResultsAction: "查看建议",
        argumentRangeFormat: "%d 到 %d",
        argumentHint: "Return 应用 · Esc 返回",
        confirmHint: "Return 确认 · Esc 取消",
        kindApp: "App",
        kindClipboard: "从历史记录粘贴",
        kindSnippet: "插入片段",
        soundOutputSubtitle: "切换声音输出",
        soundOutputCurrent: "当前输出",
        volumeTitle: "音量",
        brightnessTitle: "屏幕亮度",
        keepAwakeForFormat: "保持唤醒 %@",
        needsSetupFormat: "请在设置中开启%@",
        needsPermissionHint: "需要权限 · 按 Return 请求",
        actionCheckAppUpdates: "检查 App 更新",
        actionCleanURL: "清理拷贝的链接",
        actionOpenSettings: "打开设置",
        answerBatteryLabel: "电池",
        answerBatteryCharging: "充电中",
        answerBatteryPlugged: "已接电源",
        answerMemoryLabel: "内存",
        answerMemoryFormat: "已用 %@ / %@",
        answerStorageLabel: "存储空间",
        answerStorageFormat: "可用 %@ / %@",
        copyHint: "Return 拷贝",
        kindWindow: "窗口",
        quitFormat: "退出%@",
        quitConfirmFormat: "要退出%@吗？",
        kindMenu: "菜单命令",
        actionsTitle: "操作",
        actionsHint: "操作",
        actionPin: "固定到顶部",
        actionUnpin: "取消固定",
        actionName: "起个自己的名字",
        actionRename: "更改它响应的名字",
        actionHide: "从不显示这个",
        actionForget: "忘记我用它的频率",
        aliasPlaceholder: "你称呼它的名字",
        aliasTakenFormat: "%@ 已经使用这个名字",
        sourcesTitle: "命令栏搜索的内容",
        sourcesCaption: "关掉你不想看到的。你自己的操作始终保留。",
        sourceActions: "Vorssaint 操作",
        sourceApps: "App",
        sourceMenus: "最前面 App 的菜单命令",
        sourceWindows: "打开的窗口",
        sourceQuitApps: "退出 App",
        sourceSettingsPages: "设置页面",
        sourceSnippets: "片段",
        sourceClipboard: "剪贴板历史",
        sourceEmoji: "表情符号",
        sourceFolders: "文件夹",
        sourceAnswers: "关于这台 Mac 的答案",
        sourceCalculator: "计算与换算",
        namedTitle: "你起的名字",
        namedEmpty: "还没有名字。打开命令栏，选中一行，按下操作键。",
        pinnedTitle: "已固定",
        pinnedEmpty: "还没有固定任何内容。",
        hiddenTitle: "从不显示",
        hiddenEmpty: "没有隐藏任何内容。",
        forgetAllButton: "忘记我最常用的",
        tryTheseLabel: "试试",
        stillLooking: "仍在查找",
        removeButton: "移除",
        confirmButton: "确认",
        soundMute: "静音",
        soundUnmute: "恢复声音",
        stateOn: "已开启",
        powerSleep: "睡眠",
        powerRestart: "重新启动",
        powerRestartConfirm: "要重新启动 Mac 吗？",
        powerShutDown: "关机",
        powerShutDownConfirm: "要关闭 Mac 吗？",
        powerLogOut: "退出登录",
        powerLogOutConfirm: "要退出登录吗？",
        wifiOn: "打开无线局域网",
        wifiOff: "关闭无线局域网",
        kindEmoji: "表情符号",
        kindFolder: "文件夹",
        answerDateLabel: "今天",
        answerTimeLabel: "当前时间",
        kindAnswer: "答案",
        kindSelection: "选中内容",
        selectedTitle: "已选中",
        selectionCopy: "复制",
        selectionSearch: "用于搜索",
        selectionUpper: "全部大写",
        selectionLower: "全部小写",
        selectionTitleCase: "首字母大写",
        selectionShelf: "放到暂存架",
        selectionCount: "统计",
        selectionCountFormat: "%d 个词，%d 个字符",
        sourceSelection: "选中的内容",
        kindLink: "你的快捷方式",
        linkSearchHint: "在名称后输入要查找的内容",
        linksTitle: "你的快捷方式",
        linksEmpty: "还没有内容。添加一个每天都会打开的网站、文件夹或搜索。",
        linkDestinationLabel: "去往哪里",
        linkKindLink: "网站或链接",
        linkKindPlace: "文件夹或文件",
        linkPlaceholdersHint: "放入其中一个，打开时会自动填入",
        placeholderQuery: "你输入的内容",
        placeholderClipboard: "你复制的内容",
        placeholderSelection: "选中的内容",
        placeholderDate: "今天",
        privacyNote: "一切都在这台 Mac 上完成：不需要账户，不上云，什么都不外传。",
        actionShortcut: "设置快捷键",
        actionShortcutChange: "更改快捷键",
        actionShortcutRemove: "取消快捷键",
        shortcutCaptureHint: "按下想要的按键 · Delete 清除 · Esc 返回",
        rowShortcutsTitle: "有自己快捷键的条目",
        rowShortcutsEmpty: "还没有条目设置快捷键。打开任意条目的操作即可设置。",
        turnOnFormat: "打开%@",
        turnOffFormat: "关闭%@",
        everythingTitle: "它能做的一切",
        categoryAll: "全部",
        restartAppFormat: "重新启动%@",
        forceQuitAppFormat: "强制退出%@…",
        forceQuitAppConfirmFormat: "要强制退出%@吗？未保存的更改将会丢失。",
        uninstallAppFormat: "卸载%@…")

    static let zhTW = CommandBarFeatureStrings(
        pageTitle: "指令列",
        hubDescription: "一個輸入欄位，找到並執行 App 的所有功能",
        panelCaption: "輸入即可找到並執行任何功能",
        settingsCaption: "一個快速鍵就能在目前畫面上打開輸入欄位。輸入幾個字母，按下 Return 就完成。輸入的內容不會儲存。",
        openButton: "立即打開指令列",
        searchPlaceholder: "輸入你想做的事",
        suggestionsLabel: "建議",
        noResultsTitle: "沒有找到這個名稱。",
        noResultsAction: "查看建議",
        argumentRangeFormat: "%d 到 %d",
        argumentHint: "Return 套用 · Esc 返回",
        confirmHint: "Return 確認 · Esc 取消",
        kindApp: "App",
        kindClipboard: "從歷史記錄貼上",
        kindSnippet: "插入片段",
        soundOutputSubtitle: "切換聲音輸出",
        soundOutputCurrent: "目前輸出",
        volumeTitle: "音量",
        brightnessTitle: "螢幕亮度",
        keepAwakeForFormat: "保持喚醒 %@",
        needsSetupFormat: "請在設定中開啟%@",
        needsPermissionHint: "需要權限 · 按 Return 要求",
        actionCheckAppUpdates: "檢查 App 更新",
        actionCleanURL: "清理拷貝的連結",
        actionOpenSettings: "打開設定",
        answerBatteryLabel: "電池",
        answerBatteryCharging: "充電中",
        answerBatteryPlugged: "已接電源",
        answerMemoryLabel: "記憶體",
        answerMemoryFormat: "已用 %@ / %@",
        answerStorageLabel: "儲存空間",
        answerStorageFormat: "可用 %@ / %@",
        copyHint: "Return 拷貝",
        kindWindow: "視窗",
        quitFormat: "結束%@",
        quitConfirmFormat: "要結束%@嗎？",
        kindMenu: "選單指令",
        actionsTitle: "動作",
        actionsHint: "動作",
        actionPin: "固定到最上方",
        actionUnpin: "取消固定",
        actionName: "取個自己的名字",
        actionRename: "更改它回應的名稱",
        actionHide: "永不顯示這個",
        actionForget: "忘記我使用它的頻率",
        aliasPlaceholder: "你稱呼它的名字",
        aliasTakenFormat: "%@ 已經使用這個名稱",
        sourcesTitle: "指令列搜尋的內容",
        sourcesCaption: "關掉你不想看到的。你自己的動作永遠保留。",
        sourceActions: "Vorssaint 動作",
        sourceApps: "App",
        sourceMenus: "最前面 App 的選單指令",
        sourceWindows: "打開的視窗",
        sourceQuitApps: "結束 App",
        sourceSettingsPages: "設定頁面",
        sourceSnippets: "片段",
        sourceClipboard: "剪貼板歷史記錄",
        sourceEmoji: "表情符號",
        sourceFolders: "檔案夾",
        sourceAnswers: "關於這台 Mac 的答案",
        sourceCalculator: "計算與換算",
        namedTitle: "你取的名稱",
        namedEmpty: "還沒有名稱。打開指令列，選一行，按下動作鍵。",
        pinnedTitle: "已固定",
        pinnedEmpty: "還沒有固定任何項目。",
        hiddenTitle: "永不顯示",
        hiddenEmpty: "沒有隱藏任何項目。",
        forgetAllButton: "忘記我最常用的",
        tryTheseLabel: "試試",
        stillLooking: "仍在尋找",
        removeButton: "移除",
        confirmButton: "確認",
        soundMute: "靜音",
        soundUnmute: "恢復聲音",
        stateOn: "已開啟",
        powerSleep: "睡眠",
        powerRestart: "重新開機",
        powerRestartConfirm: "要重新開機嗎？",
        powerShutDown: "關機",
        powerShutDownConfirm: "要關閉 Mac 嗎？",
        powerLogOut: "登出",
        powerLogOutConfirm: "要登出嗎？",
        wifiOn: "打開 Wi-Fi",
        wifiOff: "關閉 Wi-Fi",
        kindEmoji: "表情符號",
        kindFolder: "檔案夾",
        answerDateLabel: "今天",
        answerTimeLabel: "目前時間",
        kindAnswer: "答案",
        kindSelection: "選取內容",
        selectedTitle: "已選取",
        selectionCopy: "複製",
        selectionSearch: "用於搜尋",
        selectionUpper: "全部大寫",
        selectionLower: "全部小寫",
        selectionTitleCase: "首字母大寫",
        selectionShelf: "放到暫存架",
        selectionCount: "統計",
        selectionCountFormat: "%d 個詞、%d 個字元",
        sourceSelection: "選取的內容",
        kindLink: "你的捷徑",
        linkSearchHint: "在名稱後輸入要尋找的內容",
        linksTitle: "你的捷徑",
        linksEmpty: "還沒有內容。加入一個每天都會開啟的網站、資料夾或搜尋。",
        linkDestinationLabel: "前往哪裡",
        linkKindLink: "網站或連結",
        linkKindPlace: "資料夾或檔案",
        linkPlaceholdersHint: "放入其中一個，開啟時會自動填入",
        placeholderQuery: "你輸入的內容",
        placeholderClipboard: "你複製的內容",
        placeholderSelection: "選取的內容",
        placeholderDate: "今天",
        privacyNote: "一切都在這台 Mac 上完成：不需要帳號，不上雲，什麼都不外傳。",
        actionShortcut: "設定快速鍵",
        actionShortcutChange: "更改快速鍵",
        actionShortcutRemove: "取消快速鍵",
        shortcutCaptureHint: "按下想要的按鍵 · Delete 清除 · Esc 返回",
        rowShortcutsTitle: "有自己快速鍵的項目",
        rowShortcutsEmpty: "還沒有項目設定快速鍵。開啟任一項目的操作即可設定。",
        turnOnFormat: "開啟%@",
        turnOffFormat: "關閉%@",
        everythingTitle: "它能做的一切",
        categoryAll: "全部",
        restartAppFormat: "重新啟動%@",
        forceQuitAppFormat: "強制結束%@…",
        forceQuitAppConfirmFormat: "要強制結束%@嗎？未儲存的更改將會遺失。",
        uninstallAppFormat: "解除安裝%@…")

    static let zhHK = CommandBarFeatureStrings(
        pageTitle: "指令列",
        hubDescription: "一個輸入欄位，找到並執行 App 的所有功能",
        panelCaption: "輸入即可找到並執行任何功能",
        settingsCaption: "一個快捷鍵就能在目前螢幕上打開輸入欄位。輸入幾個字母，按下 Return 就完成。輸入的內容不會儲存。",
        openButton: "立即打開指令列",
        searchPlaceholder: "輸入你想做的事",
        suggestionsLabel: "建議",
        noResultsTitle: "沒有找到這個名稱。",
        noResultsAction: "查看建議",
        argumentRangeFormat: "%d 到 %d",
        argumentHint: "Return 套用 · Esc 返回",
        confirmHint: "Return 確認 · Esc 取消",
        kindApp: "App",
        kindClipboard: "從歷史記錄貼上",
        kindSnippet: "插入片段",
        soundOutputSubtitle: "切換聲音輸出",
        soundOutputCurrent: "目前輸出",
        volumeTitle: "音量",
        brightnessTitle: "螢幕亮度",
        keepAwakeForFormat: "保持喚醒 %@",
        needsSetupFormat: "請在設定中開啟 %@",
        needsPermissionHint: "需要權限 · 按 Return 要求",
        actionCheckAppUpdates: "檢查 App 更新",
        actionCleanURL: "清理拷貝的連結",
        actionOpenSettings: "打開設定",
        answerBatteryLabel: "電池",
        answerBatteryCharging: "充電中",
        answerBatteryPlugged: "已接電源",
        answerMemoryLabel: "記憶體",
        answerMemoryFormat: "已用 %@ / %@",
        answerStorageLabel: "儲存空間",
        answerStorageFormat: "可用 %@ / %@",
        copyHint: "Return 拷貝",
        kindWindow: "視窗",
        quitFormat: "結束%@",
        quitConfirmFormat: "要結束%@嗎？",
        kindMenu: "選單指令",
        actionsTitle: "動作",
        actionsHint: "動作",
        actionPin: "固定到最上方",
        actionUnpin: "取消固定",
        actionName: "取個自己的名字",
        actionRename: "更改它回應的名稱",
        actionHide: "永不顯示這個",
        actionForget: "忘記我使用它的頻率",
        aliasPlaceholder: "你稱呼它的名字",
        aliasTakenFormat: "%@ 已經使用這個名稱",
        sourcesTitle: "指令列搜尋的內容",
        sourcesCaption: "關掉你不想看到的。你自己的動作永遠保留。",
        sourceActions: "Vorssaint 動作",
        sourceApps: "App",
        sourceMenus: "最前面 App 的選單指令",
        sourceWindows: "打開的視窗",
        sourceQuitApps: "結束 App",
        sourceSettingsPages: "設定頁面",
        sourceSnippets: "片段",
        sourceClipboard: "剪貼板歷史記錄",
        sourceEmoji: "表情符號",
        sourceFolders: "檔案夾",
        sourceAnswers: "關於這台 Mac 的答案",
        sourceCalculator: "計算與換算",
        namedTitle: "你取的名稱",
        namedEmpty: "還沒有名稱。打開指令列，選一行，按下動作鍵。",
        pinnedTitle: "已固定",
        pinnedEmpty: "還沒有固定任何項目。",
        hiddenTitle: "永不顯示",
        hiddenEmpty: "沒有隱藏任何項目。",
        forgetAllButton: "忘記我最常用的",
        tryTheseLabel: "試試",
        stillLooking: "仍在尋找",
        removeButton: "移除",
        confirmButton: "確認",
        soundMute: "靜音",
        soundUnmute: "恢復聲音",
        stateOn: "已開啟",
        powerSleep: "睡眠",
        powerRestart: "重新開機",
        powerRestartConfirm: "要重新開機嗎？",
        powerShutDown: "關機",
        powerShutDownConfirm: "要關閉 Mac 嗎？",
        powerLogOut: "登出",
        powerLogOutConfirm: "要登出嗎？",
        wifiOn: "打開 Wi-Fi",
        wifiOff: "關閉 Wi-Fi",
        kindEmoji: "表情符號",
        kindFolder: "檔案夾",
        answerDateLabel: "今天",
        answerTimeLabel: "目前時間",
        kindAnswer: "答案",
        kindSelection: "選取內容",
        selectedTitle: "已選取",
        selectionCopy: "複製",
        selectionSearch: "用於搜尋",
        selectionUpper: "全部大寫",
        selectionLower: "全部小寫",
        selectionTitleCase: "首字母大寫",
        selectionShelf: "放到暫存架",
        selectionCount: "統計",
        selectionCountFormat: "%d 個詞、%d 個字元",
        sourceSelection: "選取的內容",
        kindLink: "你的捷徑",
        linkSearchHint: "在名稱後輸入要尋找的內容",
        linksTitle: "你的捷徑",
        linksEmpty: "還沒有內容。加入一個每天都會開啟的網站、資料夾或搜尋。",
        linkDestinationLabel: "前往哪裡",
        linkKindLink: "網站或連結",
        linkKindPlace: "資料夾或檔案",
        linkPlaceholdersHint: "放入其中一個，開啟時會自動填入",
        placeholderQuery: "你輸入的內容",
        placeholderClipboard: "你複製的內容",
        placeholderSelection: "選取的內容",
        placeholderDate: "今天",
        privacyNote: "一切都在這台 Mac 上完成：不需要帳號，不上雲，什麼都不外傳。",
        actionShortcut: "設定快速鍵",
        actionShortcutChange: "更改快速鍵",
        actionShortcutRemove: "取消快速鍵",
        shortcutCaptureHint: "按下想要的按鍵 · Delete 清除 · Esc 返回",
        rowShortcutsTitle: "有自己快速鍵的項目",
        rowShortcutsEmpty: "還沒有項目設定快速鍵。開啟任一項目的操作即可設定。",
        turnOnFormat: "開啟%@",
        turnOffFormat: "關閉%@",
        everythingTitle: "它能做的一切",
        categoryAll: "全部",
        restartAppFormat: "重新啟動%@",
        forceQuitAppFormat: "強制結束%@…",
        forceQuitAppConfirmFormat: "要強制結束%@嗎？未儲存的更改將會遺失。",
        uninstallAppFormat: "解除安裝%@…")
}
