// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct EnvironmentFeatureStrings {
    let title: String
    let hubDescription: String
    let pathTitle: String
    let pathNote: String
    let terminal: String
    let apps: String
    let terminalOnly: String
    let noDifference: String
    let shellUnavailable: String
    let commandsTitle: String
    let commandsNote: String
    let runsFormat: String
    let shadowed: String
    let notFound: String
    let copyReport: String
}

extension FeatureStrings {
    static func environment(_ language: AppLanguage) -> EnvironmentFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .uk: return .uk
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension EnvironmentFeatureStrings {
    static let enUS = EnvironmentFeatureStrings(title: "Command Environment", hubDescription: "See why a command works in Terminal but not from an app: compare both PATHs and see which node, python or npx runs. Read-only", pathTitle: "Terminal PATH vs app PATH", pathNote: "Apps opened from Finder or the Dock do not see the highlighted folders. Use the full path in their settings.", terminal: "Terminal", apps: "Apps", terminalOnly: "Terminal only", noDifference: "Apps see every folder the terminal sees.", shellUnavailable: "Your login shell did not answer, so this shows only the system folders.", commandsTitle: "Commands", commandsNote: "The first match in the terminal PATH wins. Later copies never run.", runsFormat: "Runs %@", shadowed: "Shadowed", notFound: "Not found", copyReport: "Copy Report")
    static let ptBR = EnvironmentFeatureStrings(title: "Ambiente de comandos", hubDescription: "Descubra por que um comando funciona no Terminal mas não em um app: compare os dois PATHs e veja qual node, python ou npx é executado. Somente leitura", pathTitle: "PATH do Terminal x PATH dos apps", pathNote: "Apps abertos pelo Finder ou pelo Dock não veem as pastas destacadas. Use o caminho completo nos ajustes deles.", terminal: "Terminal", apps: "Apps", terminalOnly: "Só no Terminal", noDifference: "Os apps veem todas as pastas que o Terminal vê.", shellUnavailable: "O shell de login não respondeu, então só aparecem as pastas do sistema.", commandsTitle: "Comandos", commandsNote: "A primeira ocorrência no PATH do Terminal vence. As cópias seguintes nunca são executadas.", runsFormat: "Executa %@", shadowed: "Encoberto", notFound: "Não encontrado", copyReport: "Copiar relatório")
    static let tr = EnvironmentFeatureStrings(title: "Komut Ortamı", hubDescription: "Bir komutun Terminal’de çalışıp bir uygulamadan neden çalışmadığını görün: iki PATH’i karşılaştırın ve hangi node, python veya npx’in çalıştığını görün. Salt okunur", pathTitle: "Terminal PATH’i ve uygulama PATH’i", pathNote: "Finder veya Dock’tan açılan uygulamalar vurgulanan klasörleri görmez. Ayarlarında tam yolu kullanın.", terminal: "Terminal", apps: "Uygulamalar", terminalOnly: "Yalnızca Terminal", noDifference: "Uygulamalar Terminal’in gördüğü her klasörü görüyor.", shellUnavailable: "Oturum açma kabuğu yanıt vermedi, bu yüzden yalnızca sistem klasörleri gösteriliyor.", commandsTitle: "Komutlar", commandsNote: "Terminal PATH’indeki ilk eşleşme kazanır. Sonraki kopyalar hiç çalışmaz.", runsFormat: "%@ çalıştırır", shadowed: "Gölgelenmiş", notFound: "Bulunamadı", copyReport: "Raporu kopyala")
    static let ru = EnvironmentFeatureStrings(title: "Окружение команд", hubDescription: "Узнайте, почему команда работает в Терминале, но не из приложения: сравните оба PATH и посмотрите, какой node, python или npx запускается. Только чтение", pathTitle: "PATH Терминала и PATH приложений", pathNote: "Приложения, открытые из Finder или Dock, не видят выделенные папки. Указывайте в их настройках полный путь.", terminal: "Терминал", apps: "Приложения", terminalOnly: "Только в Терминале", noDifference: "Приложения видят все папки, которые видит Терминал.", shellUnavailable: "Оболочка входа не ответила, поэтому показаны только системные папки.", commandsTitle: "Команды", commandsNote: "Побеждает первое совпадение в PATH Терминала. Следующие копии никогда не запускаются.", runsFormat: "Запускает %@", shadowed: "Перекрыта", notFound: "Не найдено", copyReport: "Скопировать отчёт")
    static let es = EnvironmentFeatureStrings(title: "Entorno de comandos", hubDescription: "Descubre por qué un comando funciona en Terminal pero no desde una app: compara ambos PATH y mira qué node, python o npx se ejecuta. Solo lectura", pathTitle: "PATH de Terminal frente al de las apps", pathNote: "Las apps abiertas desde el Finder o el Dock no ven las carpetas resaltadas. Usa la ruta completa en sus ajustes.", terminal: "Terminal", apps: "Apps", terminalOnly: "Solo en Terminal", noDifference: "Las apps ven todas las carpetas que ve Terminal.", shellUnavailable: "El shell de inicio de sesión no respondió, así que solo se muestran las carpetas del sistema.", commandsTitle: "Comandos", commandsNote: "Gana la primera coincidencia del PATH de Terminal. Las copias siguientes nunca se ejecutan.", runsFormat: "Ejecuta %@", shadowed: "Tapado", notFound: "No encontrado", copyReport: "Copiar informe")
    static let sk = EnvironmentFeatureStrings(title: "Prostredie príkazov", hubDescription: "Zistite, prečo príkaz funguje v Termináli, ale nie z aplikácie: porovnajte obe PATH a pozrite sa, ktorý node, python alebo npx sa spustí. Iba na čítanie", pathTitle: "PATH Terminálu a PATH aplikácií", pathNote: "Aplikácie otvorené z Findera alebo Docku nevidia zvýraznené priečinky. V ich nastaveniach použite úplnú cestu.", terminal: "Terminál", apps: "Aplikácie", terminalOnly: "Iba v Termináli", noDifference: "Aplikácie vidia všetky priečinky, ktoré vidí Terminál.", shellUnavailable: "Prihlasovací shell neodpovedal, preto sa zobrazujú iba systémové priečinky.", commandsTitle: "Príkazy", commandsNote: "Vyhráva prvá zhoda v PATH Terminálu. Neskoršie kópie sa nikdy nespustia.", runsFormat: "Spúšťa %@", shadowed: "Zakrytý", notFound: "Nenašiel sa", copyReport: "Kopírovať správu")
    static let de = EnvironmentFeatureStrings(title: "Befehlsumgebung", hubDescription: "Finde heraus, warum ein Befehl im Terminal läuft, aber nicht aus einer App: Vergleiche beide PATH und sieh, welches node, python oder npx ausgeführt wird. Nur lesend", pathTitle: "Terminal-PATH und App-PATH", pathNote: "Apps, die über den Finder oder das Dock geöffnet werden, sehen die markierten Ordner nicht. Verwende in ihren Einstellungen den vollständigen Pfad.", terminal: "Terminal", apps: "Apps", terminalOnly: "Nur im Terminal", noDifference: "Apps sehen jeden Ordner, den das Terminal sieht.", shellUnavailable: "Die Login-Shell hat nicht geantwortet, daher sind nur die Systemordner zu sehen.", commandsTitle: "Befehle", commandsNote: "Der erste Treffer im Terminal-PATH gewinnt. Spätere Kopien laufen nie.", runsFormat: "Führt %@ aus", shadowed: "Verdeckt", notFound: "Nicht gefunden", copyReport: "Bericht kopieren")
    static let fr = EnvironmentFeatureStrings(title: "Environnement des commandes", hubDescription: "Comprenez pourquoi une commande fonctionne dans Terminal mais pas depuis une app\u{00A0}: comparez les deux PATH et voyez quel node, python ou npx s’exécute. Lecture seule", pathTitle: "PATH de Terminal et PATH des apps", pathNote: "Les apps ouvertes depuis le Finder ou le Dock ne voient pas les dossiers mis en évidence. Utilisez le chemin complet dans leurs réglages.", terminal: "Terminal", apps: "Apps", terminalOnly: "Terminal uniquement", noDifference: "Les apps voient tous les dossiers que voit Terminal.", shellUnavailable: "Le shell de connexion n’a pas répondu, seuls les dossiers système sont affichés.", commandsTitle: "Commandes", commandsNote: "La première correspondance du PATH de Terminal l’emporte. Les copies suivantes ne s’exécutent jamais.", runsFormat: "Exécute %@", shadowed: "Masqué", notFound: "Introuvable", copyReport: "Copier le rapport")
    static let it = EnvironmentFeatureStrings(title: "Ambiente dei comandi", hubDescription: "Scopri perché un comando funziona nel Terminale ma non da un’app: confronta i due PATH e vedi quale node, python o npx viene eseguito. Sola lettura", pathTitle: "PATH del Terminale e PATH delle app", pathNote: "Le app aperte dal Finder o dal Dock non vedono le cartelle evidenziate. Usa il percorso completo nelle loro impostazioni.", terminal: "Terminale", apps: "App", terminalOnly: "Solo nel Terminale", noDifference: "Le app vedono tutte le cartelle che vede il Terminale.", shellUnavailable: "La shell di login non ha risposto, quindi sono mostrate solo le cartelle di sistema.", commandsTitle: "Comandi", commandsNote: "Vince la prima corrispondenza nel PATH del Terminale. Le copie successive non vengono mai eseguite.", runsFormat: "Esegue %@", shadowed: "Oscurato", notFound: "Non trovato", copyReport: "Copia rapporto")
    static let ja = EnvironmentFeatureStrings(title: "コマンド環境", hubDescription: "ターミナルでは動くコマンドがアプリからは動かない理由を確認します。2つのPATHを比較し、どのnode、python、npxが実行されるかを表示します。読み取り専用", pathTitle: "ターミナルのPATHとアプリのPATH", pathNote: "FinderやDockから開いたアプリは、強調表示されたフォルダを参照できません。アプリの設定ではフルパスを指定してください。", terminal: "ターミナル", apps: "アプリ", terminalOnly: "ターミナルのみ", noDifference: "アプリはターミナルと同じフォルダをすべて参照できます。", shellUnavailable: "ログインシェルが応答しなかったため、システムのフォルダのみを表示しています。", commandsTitle: "コマンド", commandsNote: "ターミナルのPATHで最初に見つかったものが実行されます。後に見つかったコピーは実行されません。", runsFormat: "%@を実行", shadowed: "隠れています", notFound: "見つかりません", copyReport: "レポートをコピー")
    static let ko = EnvironmentFeatureStrings(title: "명령 환경", hubDescription: "명령이 터미널에서는 되는데 앱에서는 안 되는 이유를 확인합니다. 두 PATH를 비교하고 어떤 node, python, npx가 실행되는지 보여 줍니다. 읽기 전용", pathTitle: "터미널 PATH와 앱 PATH", pathNote: "Finder나 Dock에서 연 앱은 강조 표시된 폴더를 보지 못합니다. 앱 설정에는 전체 경로를 사용하세요.", terminal: "터미널", apps: "앱", terminalOnly: "터미널에만 있음", noDifference: "앱이 터미널과 같은 폴더를 모두 봅니다.", shellUnavailable: "로그인 셸이 응답하지 않아 시스템 폴더만 표시합니다.", commandsTitle: "명령", commandsNote: "터미널 PATH에서 처음 찾은 항목이 실행됩니다. 뒤의 사본은 실행되지 않습니다.", runsFormat: "%@ 실행", shadowed: "가려짐", notFound: "찾을 수 없음", copyReport: "보고서 복사")
    static let uk = EnvironmentFeatureStrings(title: "Середовище команд", hubDescription: "Дізнайтеся, чому команда працює в Терміналі, але не з програми: порівняйте обидва PATH і подивіться, який node, python чи npx запускається. Лише читання", pathTitle: "PATH Термінала і PATH програм", pathNote: "Програми, відкриті з Finder або Dock, не бачать виділених папок. Указуйте в їхніх налаштуваннях повний шлях.", terminal: "Термінал", apps: "Програми", terminalOnly: "Лише в Терміналі", noDifference: "Програми бачать усі папки, які бачить Термінал.", shellUnavailable: "Оболонка входу не відповіла, тому показано лише системні папки.", commandsTitle: "Команди", commandsNote: "Перемагає перший збіг у PATH Термінала. Наступні копії ніколи не запускаються.", runsFormat: "Запускає %@", shadowed: "Перекрито", notFound: "Не знайдено", copyReport: "Скопіювати звіт")
    static let zhHans = EnvironmentFeatureStrings(title: "命令环境", hubDescription: "查明命令为何在终端里能用、从 App 里却不能用：对比两边的 PATH，查看实际运行的是哪个 node、python 或 npx。只读", pathTitle: "终端 PATH 与 App PATH", pathNote: "从访达或程序坞打开的 App 看不到高亮的文件夹。请在它们的设置里填写完整路径。", terminal: "终端", apps: "App", terminalOnly: "仅终端", noDifference: "App 能看到终端能看到的所有文件夹。", shellUnavailable: "登录 shell 没有响应，因此只显示系统文件夹。", commandsTitle: "命令", commandsNote: "终端 PATH 中第一个匹配项生效，后面的副本永远不会运行。", runsFormat: "实际运行 %@", shadowed: "被遮蔽", notFound: "未找到", copyReport: "拷贝报告")
    static let zhTW = EnvironmentFeatureStrings(title: "指令環境", hubDescription: "查明指令為何在終端機能用、從 App 卻不能用：比較兩邊的 PATH，查看實際執行的是哪個 node、python 或 npx。唯讀", pathTitle: "終端機 PATH 與 App PATH", pathNote: "從 Finder 或 Dock 開啟的 App 看不到醒目標示的檔案夾。請在它們的設定中填寫完整路徑。", terminal: "終端機", apps: "App", terminalOnly: "僅終端機", noDifference: "App 能看到終端機看得到的所有檔案夾。", shellUnavailable: "登入 shell 沒有回應，因此只顯示系統檔案夾。", commandsTitle: "指令", commandsNote: "終端機 PATH 中第一個相符項目生效，之後的副本永遠不會執行。", runsFormat: "實際執行 %@", shadowed: "被遮蔽", notFound: "找不到", copyReport: "拷貝報告")
    static let zhHK = EnvironmentFeatureStrings(title: "指令環境", hubDescription: "查明指令為何在終端機能用、從 App 卻不能用：比較兩邊的 PATH，查看實際執行的是哪個 node、python 或 npx。唯讀", pathTitle: "終端機 PATH 與 App PATH", pathNote: "從 Finder 或 Dock 開啟的 App 看不到醒目顯示的資料夾。請在它們的設定中填寫完整路徑。", terminal: "終端機", apps: "App", terminalOnly: "僅終端機", noDifference: "App 能看到終端機看得到的所有資料夾。", shellUnavailable: "登入 shell 沒有回應，因此只顯示系統資料夾。", commandsTitle: "指令", commandsNote: "終端機 PATH 中第一個相符項目生效，之後的副本永遠不會執行。", runsFormat: "實際執行 %@", shadowed: "被遮蔽", notFound: "找不到", copyReport: "複製報告")
}
