// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct FanControlFeatureStrings {
    let title: String
    let hubDescription: String
    let showInPanel: String
    let settingsCaption: String
    let fanNameFormat: String
    let rpmFormat: String
    let allowControl: String
    let approvalCaption: String
    let openSettings: String
    let noFans: String
    let unsupported: String
    let alreadyControlled: String
    let failed: String
    let safetyCaption: String
    let safetyStopped: String
    let menuBarTitle: String
    let systemControl: String
    let manualControl: String
    let customCurve: String
    let adaptiveControl: String
    let mode: String
    let coolingIntensity: String
    let currentRPMFormat: String
    let targetRPMFormat: String
    let applyManual: String
    let applyCurve: String
    let applyAdaptive: String
    let returnToSystem: String
    let temperatureUnavailable: String
    let curveUnavailable: String
    let sensor: String
    let temperature: String
    let fanSpeed: String
    let addPoint: String
    let addSensor: String
    let removePoint: String
    let removeSensor: String
    let curveGraph: String
    let averageSoC: String
    let hottestSoC: String
    let averageCPU: String
    let hottestCPU: String
    let hottestGPU: String
    let helperUnavailable: String
    let resumeAfterRestart: String
    let adaptiveRampStartTemperature: String
    let adaptiveMaximumTemperature: String
    let adaptiveSweetSpotLevel: String
    let adaptiveMaximumLevel: String
    let adaptiveProfile: String
    let adaptiveProfileQuiet: String
    let adaptiveProfileBalanced: String
    let adaptiveProfilePerformance: String
    let adaptiveProfileCustom: String
    let adaptiveAdvanced: String
    let adaptiveHotspot: String
    let adaptiveActive: String
    let applyChanges: String
    let adaptiveSensitivity: String
    let adaptiveSensitivityRelaxed: String
    let adaptiveSensitivityStandard: String
    let adaptiveSensitivityResponsive: String
    let helpMode: String
    let helpManual: String
    let helpCurve: String
    let helpChart: String
    let helpProfile: String
    let helpSensitivity: String
    let helpSweetSpot: String
    let helpMaximum: String
    let helpRampStart: String
    let helpMaximumTemperature: String
    let helpApply: String
    let helpReturn: String
    let helpActive: String
    let helpResume: String
    let helpAllow: String
}

extension FeatureStrings {
    static func fanControl(_ language: AppLanguage) -> FanControlFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension FanControlFeatureStrings {
    static let enUS = FanControlFeatureStrings(
        title: "Fan Control",
        hubDescription: "Control fans manually or with temperature curves while seeing live and target RPM",
        showInPanel: "Show Fan Control in the panel",
        settingsCaption: "Adds manual fan speeds and temperature curves to the menu bar panel.",
        fanNameFormat: "Fan %d",
        rpmFormat: "%d RPM",
        allowControl: "Allow fan control",
        approvalCaption: "Allow Vorssaint in Login Items to use the protected fan controller.",
        openSettings: "Open System Settings",
        noFans: "This Mac has no controllable fan.",
        unsupported: "Fan control is not available on this Mac.",
        alreadyControlled: "Another process is controlling the fans. Return it to system control first.",
        failed: "The fans returned to system control because the requested control could not be verified.",
        safetyCaption: "Control stays active until you return to System. It returns automatically if the app disconnects, the Mac sleeps, sensor readings fail or thermal pressure rises.",
        safetyStopped: "Returned to system control because fan control was interrupted.",
        menuBarTitle: "Fan speed",
        systemControl: "System",
        manualControl: "Manual",
        customCurve: "Curve",
        adaptiveControl: "Adaptive",
        mode: "Control mode",
        coolingIntensity: "Fan speed",
        currentRPMFormat: "Current %d RPM",
        targetRPMFormat: "Target %d RPM",
        applyManual: "Apply manual control",
        applyCurve: "Apply fan curve",
        applyAdaptive: "Apply adaptive control",
        returnToSystem: "Use system control",
        temperatureUnavailable: "The selected temperature sensor stopped responding. Fan control returned to System.",
        curveUnavailable: "A selected temperature sensor is not available on this Mac.",
        sensor: "Temperature sensor",
        temperature: "Temperature",
        fanSpeed: "Fan speed",
        addPoint: "Add point",
        addSensor: "Add sensor",
        removePoint: "Remove point",
        removeSensor: "Remove sensor",
        curveGraph: "Temperature and fan speed curve",
        averageSoC: "Average SoC",
        hottestSoC: "Hottest SoC",
        averageCPU: "Average CPU",
        hottestCPU: "Hottest CPU",
        hottestGPU: "Hottest GPU",
        helperUnavailable: "The protected fan controller is unavailable. Allow Vorssaint in Login Items, then try again.",
        resumeAfterRestart: "Resume after restart or sleep",
        adaptiveRampStartTemperature: "Start temperature",
        adaptiveMaximumTemperature: "Full-speed temperature",
        adaptiveSweetSpotLevel: "Start speed",
        adaptiveMaximumLevel: "Maximum speed",
        adaptiveProfile: "Profile",
        adaptiveProfileQuiet: "Quiet",
        adaptiveProfileBalanced: "Balanced",
        adaptiveProfilePerformance: "Performance",
        adaptiveProfileCustom: "Custom",
        adaptiveAdvanced: "Advanced",
        adaptiveHotspot: "Hotspot",
        adaptiveActive: "Adaptive control running",
        applyChanges: "Apply changes",
        adaptiveSensitivity: "Sensitivity",
        adaptiveSensitivityRelaxed: "Relaxed",
        adaptiveSensitivityStandard: "Standard",
        adaptiveSensitivityResponsive: "Quick",
        helpMode: "System: the Mac’s own fan logic. Manual: one fixed speed. Curve: the speed follows temperature points you edit. Adaptive: the speed follows the temperature automatically, shaped by a profile.",
        helpManual: "A fixed fan speed as a share of each fan’s range, from its minimum to its maximum. It stays until you change it or return to System.",
        helpCurve: "The fan speed follows the temperature points you set for each sensor. With several sensors, the highest requested speed wins.",
        helpChart: "Orange: temperature. Cyan: current fan speed. Gray: target fan speed. Dashed lines mark the start and maximum temperatures. Covers this adaptive session only.",
        helpProfile: "Preset tunings. Quiet stays close to the system’s relaxed behavior, Balanced cools earlier, Performance cools earliest and hardest. Changing any value in Advanced switches this to Custom.",
        helpSensitivity: "How quickly the fans follow the temperature. Relaxed ignores short spikes and eases off slowly, Standard is the default, Quick speeds up and slows down sooner. A temperature already at the maximum threshold always goes straight to the maximum speed.",
        helpSweetSpot: "The fan speed, as a share of each fan’s range, used when the temperature reaches the start temperature. Cooler than that, the fans fall toward their minimum.",
        helpMaximum: "The highest speed adaptive control will use, as a share of each fan’s range. A lower value is quieter but leaves less cooling in reserve under heavy load.",
        helpRampStart: "The temperature at which the fans reach the start speed and begin to speed up. A higher value keeps the fans quiet longer but lets the Mac run hotter.",
        helpMaximumTemperature: "The temperature at which the fans reach the maximum speed. A lower value cools harder. It must stay a minimum gap above the start temperature.",
        helpApply: "Starts this control with the settings shown and replaces any control already running.",
        helpReturn: "Stops the current control and gives the fans back to the system.",
        helpActive: "Adaptive control is running with exactly these settings.",
        helpResume: "Applies this control again after a restart, wake or app relaunch. Choosing System turns it off.",
        helpAllow: "Fan control needs a small protected helper. macOS asks you to allow it in Login Items."
    )

    static let ptBR = FanControlFeatureStrings(
        title: "Controle das ventoinhas",
        hubDescription: "Controle manual ou por curvas de temperatura, com RPM atual e RPM-alvo",
        showInPanel: "Mostrar controle das ventoinhas no painel",
        settingsCaption: "Adiciona velocidades manuais e curvas de temperatura ao painel.",
        fanNameFormat: "Ventoinha %d",
        rpmFormat: "%d RPM",
        allowControl: "Permitir controle",
        approvalCaption: "Permita o Vorssaint nos Itens de Início para usar o controle protegido das ventoinhas.",
        openSettings: "Abrir Ajustes do Sistema",
        noFans: "Este Mac não tem ventoinha controlável.",
        unsupported: "O controle das ventoinhas não está disponível neste Mac.",
        alreadyControlled: "Outro processo está controlando as ventoinhas. Volte ao controle do sistema nele primeiro.",
        failed: "As ventoinhas voltaram ao sistema porque não foi possível confirmar o controle solicitado.",
        safetyCaption: "O controle fica ativo até você voltar ao Sistema. Ele é devolvido automaticamente se o app desconectar, o Mac repousar, os sensores falharem ou a pressão térmica subir.",
        safetyStopped: "Voltou ao controle do sistema porque o controle das ventoinhas foi interrompido.",
        menuBarTitle: "Velocidade das ventoinhas",
        systemControl: "Sistema",
        manualControl: "Manual",
        customCurve: "Curva",
        adaptiveControl: "Adaptativo",
        mode: "Modo de controle",
        coolingIntensity: "Velocidade das ventoinhas",
        currentRPMFormat: "Atual: %d RPM",
        targetRPMFormat: "Alvo: %d RPM",
        applyManual: "Aplicar controle manual",
        applyCurve: "Aplicar curva",
        applyAdaptive: "Aplicar controle adaptativo",
        returnToSystem: "Usar controle do sistema",
        temperatureUnavailable: "O sensor de temperatura selecionado parou de responder. O controle voltou ao Sistema.",
        curveUnavailable: "Um sensor de temperatura selecionado não está disponível neste Mac.",
        sensor: "Sensor de temperatura",
        temperature: "Temperatura",
        fanSpeed: "Velocidade",
        addPoint: "Adicionar ponto",
        addSensor: "Adicionar sensor",
        removePoint: "Remover ponto",
        removeSensor: "Remover sensor",
        curveGraph: "Curva de temperatura e velocidade",
        averageSoC: "Média do SoC",
        hottestSoC: "SoC mais quente",
        averageCPU: "Média da CPU",
        hottestCPU: "CPU mais quente",
        hottestGPU: "GPU mais quente",
        helperUnavailable: "O controlador protegido das ventoinhas não está disponível. Permita o Vorssaint nos Itens de Início e tente novamente.",
        resumeAfterRestart: "Retomar depois de reiniciar ou repousar",
        adaptiveRampStartTemperature: "Temperatura inicial",
        adaptiveMaximumTemperature: "Temperatura de velocidade máxima",
        adaptiveSweetSpotLevel: "Velocidade inicial",
        adaptiveMaximumLevel: "Velocidade máxima",
        adaptiveProfile: "Perfil",
        adaptiveProfileQuiet: "Silencioso",
        adaptiveProfileBalanced: "Equilibrado",
        adaptiveProfilePerformance: "Desempenho",
        adaptiveProfileCustom: "Personalizado",
        adaptiveAdvanced: "Avançado",
        adaptiveHotspot: "Ponto quente",
        adaptiveActive: "Controle adaptativo ativo",
        applyChanges: "Aplicar alterações",
        adaptiveSensitivity: "Sensibilidade",
        adaptiveSensitivityRelaxed: "Suave",
        adaptiveSensitivityStandard: "Padrão",
        adaptiveSensitivityResponsive: "Rápida",
        helpMode: "Sistema: a lógica de ventoinhas do próprio Mac. Manual: uma velocidade fixa. Curva: a velocidade segue os pontos de temperatura que você edita. Adaptativo: a velocidade acompanha a temperatura automaticamente, conforme um perfil.",
        helpManual: "Uma velocidade fixa, como porcentagem da faixa de cada ventoinha, do mínimo ao máximo. Permanece até você alterá-la ou voltar ao Sistema.",
        helpCurve: "A velocidade segue os pontos de temperatura definidos para cada sensor. Com vários sensores, vale a maior velocidade pedida.",
        helpChart: "Laranja: temperatura. Ciano: velocidade atual. Cinza: velocidade alvo. As linhas tracejadas marcam as temperaturas inicial e máxima. Mostra apenas esta sessão adaptativa.",
        helpProfile: "Ajustes predefinidos. Silencioso fica próximo do comportamento tranquilo do sistema, Equilibrado resfria mais cedo e Desempenho resfria primeiro e com mais força. Alterar qualquer valor em Avançado muda para Personalizado.",
        helpSensitivity: "A rapidez com que as ventoinhas acompanham a temperatura. Suave ignora picos curtos e reduz devagar, Padrão é o predefinido e Rápida acelera e desacelera mais cedo. Uma temperatura que já atingiu o limite máximo vai direto para a velocidade máxima.",
        helpSweetSpot: "A velocidade, em porcentagem da faixa de cada ventoinha, usada quando a temperatura chega à temperatura inicial. Abaixo disso, as ventoinhas descem rumo ao mínimo.",
        helpMaximum: "A maior velocidade que o controle adaptativo usará, em porcentagem da faixa de cada ventoinha. Um valor menor é mais silencioso, mas deixa menos reserva de resfriamento sob carga alta.",
        helpRampStart: "A temperatura em que as ventoinhas chegam à velocidade inicial e começam a acelerar. Um valor maior mantém o silêncio por mais tempo, mas deixa o Mac mais quente.",
        helpMaximumTemperature: "A temperatura em que as ventoinhas chegam à velocidade máxima. Um valor menor resfria com mais força. Deve ficar acima da temperatura inicial por um intervalo mínimo.",
        helpApply: "Inicia este controle com os ajustes exibidos e substitui qualquer controle em execução.",
        helpReturn: "Interrompe o controle atual e devolve as ventoinhas ao sistema.",
        helpActive: "O controle adaptativo está em execução exatamente com estes ajustes.",
        helpResume: "Aplica este controle novamente após reiniciar, despertar ou reabrir o app. Escolher Sistema o desativa.",
        helpAllow: "O controle das ventoinhas precisa de um pequeno auxiliar protegido. O macOS pede que você o permita em Itens de Início."
    )

    static let tr = FanControlFeatureStrings(
        title: "Fan denetimi",
        hubDescription: "Canlı ve hedef RPM ile fanları elle veya sıcaklık eğrileriyle denetleyin",
        showInPanel: "Fan denetimini panelde göster",
        settingsCaption: "Menü çubuğu paneline elle fan hızı ve sıcaklık eğrileri ekler.",
        fanNameFormat: "Fan %d",
        rpmFormat: "%d RPM",
        allowControl: "Fan denetimine izin ver",
        approvalCaption: "Korumalı fan denetimini kullanmak için Giriş Öğeleri’nde Vorssaint’e izin verin.",
        openSettings: "Sistem Ayarları’nı Aç",
        noFans: "Bu Mac’te denetlenebilir fan yok.",
        unsupported: "Bu Mac’te fan denetimi kullanılamıyor.",
        alreadyControlled: "Fanları başka bir işlem denetliyor. Önce oradan sistem denetimine dönün.",
        failed: "İstenen denetim doğrulanamadığı için fanlar sistem denetimine döndü.",
        safetyCaption: "Sistem’e dönene kadar denetim etkin kalır. Uygulama bağlantısı kesilirse, Mac uyursa, sensör okumaları başarısız olursa veya termal basınç yükselirse otomatik olarak geri verilir.",
        safetyStopped: "Fan denetimi kesildiği için sistem denetimine dönüldü.",
        menuBarTitle: "Fan hızı",
        systemControl: "Sistem",
        manualControl: "Elle",
        customCurve: "Eğri",
        adaptiveControl: "Uyarlamalı",
        mode: "Denetim modu",
        coolingIntensity: "Fan hızı",
        currentRPMFormat: "Anlık %d RPM",
        targetRPMFormat: "Hedef %d RPM",
        applyManual: "Elle denetimi uygula",
        applyCurve: "Fan eğrisini uygula",
        applyAdaptive: "Uyarlamalı denetimi uygula",
        returnToSystem: "Sistem denetimini kullan",
        temperatureUnavailable: "Seçilen sıcaklık sensörü yanıt vermeyi bıraktı. Fan denetimi Sistem’e döndü.",
        curveUnavailable: "Seçilen bir sıcaklık sensörü bu Mac’te kullanılamıyor.",
        sensor: "Sıcaklık sensörü",
        temperature: "Sıcaklık",
        fanSpeed: "Fan hızı",
        addPoint: "Nokta ekle",
        addSensor: "Sensör ekle",
        removePoint: "Noktayı kaldır",
        removeSensor: "Sensörü kaldır",
        curveGraph: "Sıcaklık ve fan hızı eğrisi",
        averageSoC: "Ortalama SoC",
        hottestSoC: "En sıcak SoC",
        averageCPU: "Ortalama CPU",
        hottestCPU: "En sıcak CPU",
        hottestGPU: "En sıcak GPU",
        helperUnavailable: "Korumalı fan denetleyicisi kullanılamıyor. Giriş Öğeleri’nde Vorssaint’e izin verip yeniden deneyin.",
        resumeAfterRestart: "Yeniden başlatma veya uykudan sonra sürdür",
        adaptiveRampStartTemperature: "Başlangıç sıcaklığı",
        adaptiveMaximumTemperature: "Tam hız sıcaklığı",
        adaptiveSweetSpotLevel: "Başlangıç hızı",
        adaptiveMaximumLevel: "En yüksek hız",
        adaptiveProfile: "Profil",
        adaptiveProfileQuiet: "Sessiz",
        adaptiveProfileBalanced: "Dengeli",
        adaptiveProfilePerformance: "Performans",
        adaptiveProfileCustom: "Özel",
        adaptiveAdvanced: "Gelişmiş",
        adaptiveHotspot: "Sıcak nokta",
        adaptiveActive: "Uyarlamalı denetim çalışıyor",
        applyChanges: "Değişiklikleri uygula",
        adaptiveSensitivity: "Duyarlılık",
        adaptiveSensitivityRelaxed: "Rahat",
        adaptiveSensitivityStandard: "Standart",
        adaptiveSensitivityResponsive: "Hızlı",
        helpMode: "Sistem: Mac’in kendi fan mantığı. El ile: sabit hız. Eğri: hız, düzenlediğiniz sıcaklık noktalarını izler. Uyarlamalı: hız, bir profile göre sıcaklığı otomatik izler.",
        helpManual: "Her fanın aralığına (en düşükten en yükseğe) göre yüzde olarak sabit bir hız. Siz değiştirene veya Sistem’e dönene kadar sürer.",
        helpCurve: "Hız, her sensör için belirlediğiniz sıcaklık noktalarını izler. Birden fazla sensör varsa istenen en yüksek hız geçerli olur.",
        helpChart: "Turuncu: sıcaklık. Camgöbeği: mevcut fan hızı. Gri: hedef hız. Kesikli çizgiler başlangıç ve en yüksek sıcaklığı gösterir. Yalnızca bu uyarlamalı oturumu kapsar.",
        helpProfile: "Hazır ayarlar. Sessiz, sistemin rahat davranışına yakın kalır; Dengeli daha erken, Performans en erken ve en güçlü şekilde soğutur. Gelişmiş’teki herhangi bir değeri değiştirmek Özel’e geçirir.",
        helpSensitivity: "Fanların sıcaklığı ne kadar hızlı izlediği. Rahat kısa ani artışları yok sayar ve yavaş düşer, Standart varsayılandır, Hızlı daha erken hızlanır ve yavaşlar. Sıcaklık en yüksek eşiğe ulaştıysa doğrudan en yüksek hıza çıkılır.",
        helpSweetSpot: "Sıcaklık başlangıç sıcaklığına ulaştığında kullanılan hız; her fanın aralığının yüzdesi olarak. Bunun altında fanlar en düşük hıza doğru iner.",
        helpMaximum: "Uyarlamalı denetimin kullanacağı en yüksek hız; her fanın aralığının yüzdesi olarak. Düşük değer daha sessizdir ama yüksek yükte soğutma payı azalır.",
        helpRampStart: "Fanların başlangıç hızına ulaşıp hızlanmaya başladığı sıcaklık. Yüksek değer fanları daha uzun süre sessiz tutar ama Mac daha çok ısınır.",
        helpMaximumTemperature: "Fanların en yüksek hıza ulaştığı sıcaklık. Düşük değer daha güçlü soğutur. Başlangıç sıcaklığının en az belirli bir aralık üzerinde olmalıdır.",
        helpApply: "Bu denetimi gösterilen ayarlarla başlatır ve çalışan denetimin yerini alır.",
        helpReturn: "Geçerli denetimi durdurur ve fanları sisteme geri verir.",
        helpActive: "Uyarlamalı denetim tam olarak bu ayarlarla çalışıyor.",
        helpResume: "Yeniden başlatma, uyandırma veya uygulamayı yeniden açma sonrasında bu denetimi tekrar uygular. Sistem’i seçmek kapatır.",
        helpAllow: "Fan denetimi küçük, korumalı bir yardımcı gerektirir. macOS, Giriş Öğeleri’nde izin vermenizi ister."
    )

    static let ru = FanControlFeatureStrings(
        title: "Управление вентиляторами",
        hubDescription: "Ручное управление и температурные кривые с текущими и целевыми оборотами",
        showInPanel: "Показывать управление вентиляторами на панели",
        settingsCaption: "Добавляет на панель ручную скорость и температурные кривые.",
        fanNameFormat: "Вентилятор %d",
        rpmFormat: "%d об/мин",
        allowControl: "Разрешить управление",
        approvalCaption: "Разрешите Vorssaint в Объектах входа для защищённого управления вентиляторами.",
        openSettings: "Открыть Системные настройки",
        noFans: "На этом Mac нет управляемого вентилятора.",
        unsupported: "Управление вентиляторами недоступно на этом Mac.",
        alreadyControlled: "Вентиляторами управляет другой процесс. Сначала верните там управление системе.",
        failed: "Вентиляторы вернулись под управление системы, потому что запрос не удалось проверить.",
        safetyCaption: "Управление действует до возврата в режим «Система». Оно возвращается автоматически при отключении приложения, сне Mac, сбое датчиков или росте тепловой нагрузки.",
        safetyStopped: "Управление возвращено системе из-за прерывания управления вентиляторами.",
        menuBarTitle: "Скорость вентилятора",
        systemControl: "Система",
        manualControl: "Вручную",
        customCurve: "Кривая",
        adaptiveControl: "Адаптивный",
        mode: "Режим управления",
        coolingIntensity: "Скорость вентиляторов",
        currentRPMFormat: "Сейчас %d об/мин",
        targetRPMFormat: "Цель %d об/мин",
        applyManual: "Применить ручной режим",
        applyCurve: "Применить кривую",
        applyAdaptive: "Применить адаптивное управление",
        returnToSystem: "Использовать управление системы",
        temperatureUnavailable: "Выбранный датчик температуры перестал отвечать. Управление возвращено системе.",
        curveUnavailable: "Один из выбранных датчиков температуры недоступен на этом Mac.",
        sensor: "Датчик температуры",
        temperature: "Температура",
        fanSpeed: "Скорость",
        addPoint: "Добавить точку",
        addSensor: "Добавить датчик",
        removePoint: "Удалить точку",
        removeSensor: "Удалить датчик",
        curveGraph: "Кривая температуры и скорости вентилятора",
        averageSoC: "Средняя SoC",
        hottestSoC: "Самая горячая SoC",
        averageCPU: "Средняя CPU",
        hottestCPU: "Самая горячая CPU",
        hottestGPU: "Самая горячая GPU",
        helperUnavailable: "Защищённый контроллер вентиляторов недоступен. Разрешите Vorssaint в Объектах входа и повторите попытку.",
        resumeAfterRestart: "Возобновлять после перезагрузки или сна",
        adaptiveRampStartTemperature: "Температура начала",
        adaptiveMaximumTemperature: "Температура максимума",
        adaptiveSweetSpotLevel: "Начальная скорость",
        adaptiveMaximumLevel: "Максимальная скорость",
        adaptiveProfile: "Профиль",
        adaptiveProfileQuiet: "Тихий",
        adaptiveProfileBalanced: "Сбалансированный",
        adaptiveProfilePerformance: "Производительность",
        adaptiveProfileCustom: "Свой",
        adaptiveAdvanced: "Дополнительно",
        adaptiveHotspot: "Горячая точка",
        adaptiveActive: "Адаптивное управление работает",
        applyChanges: "Применить изменения",
        adaptiveSensitivity: "Чувствительность",
        adaptiveSensitivityRelaxed: "Плавная",
        adaptiveSensitivityStandard: "Стандартная",
        adaptiveSensitivityResponsive: "Быстрая",
        helpMode: "Система: собственная логика вентиляторов Mac. Вручную: фиксированная скорость. Кривая: скорость следует заданным вами температурным точкам. Адаптивный: скорость автоматически следует температуре по выбранному профилю.",
        helpManual: "Фиксированная скорость в процентах от диапазона каждого вентилятора, от минимума до максимума. Сохраняется, пока вы её не измените или не вернётесь к системе.",
        helpCurve: "Скорость следует температурным точкам, заданным для каждого датчика. При нескольких датчиках применяется наибольшая запрошенная скорость.",
        helpChart: "Оранжевый: температура. Голубой: текущая скорость. Серый: целевая скорость. Пунктир показывает начальную и максимальную температуры. Только текущий адаптивный сеанс.",
        helpProfile: "Готовые настройки. «Тихий» близок к спокойному поведению системы, «Сбалансированный» охлаждает раньше, «Производительность» охлаждает раньше и сильнее всего. Изменение любого значения в «Дополнительно» переключает на «Свой».",
        helpSensitivity: "Как быстро вентиляторы следуют за температурой. «Плавная» игнорирует короткие всплески и снижает скорость медленно, «Стандартная» используется по умолчанию, «Быстрая» раньше разгоняется и замедляется. Если температура уже достигла максимального порога, сразу включается максимальная скорость.",
        helpSweetSpot: "Скорость в процентах от диапазона каждого вентилятора, которая используется при достижении начальной температуры. Ниже неё вентиляторы снижают скорость к минимуму.",
        helpMaximum: "Наибольшая скорость, которую использует адаптивное управление, в процентах от диапазона каждого вентилятора. Меньшее значение тише, но при высокой нагрузке остаётся меньше запаса охлаждения.",
        helpRampStart: "Температура, при которой вентиляторы выходят на начальную скорость и начинают разгоняться. Чем она выше, тем дольше вентиляторы тихие, но тем сильнее нагревается Mac.",
        helpMaximumTemperature: "Температура, при которой вентиляторы достигают максимальной скорости. Чем она ниже, тем сильнее охлаждение. Должна быть выше начальной температуры не меньше чем на минимальный интервал.",
        helpApply: "Запускает это управление с показанными настройками и заменяет уже работающее.",
        helpReturn: "Останавливает текущее управление и возвращает вентиляторы системе.",
        helpActive: "Адаптивное управление работает именно с этими настройками.",
        helpResume: "Снова применяет это управление после перезагрузки, пробуждения или перезапуска приложения. Выбор «Система» отключает его.",
        helpAllow: "Для управления вентиляторами нужен небольшой защищённый помощник. macOS попросит разрешить его в «Объектах входа»."
    )

    static let es = FanControlFeatureStrings(
        title: "Control de ventiladores",
        hubDescription: "Control manual o por curvas de temperatura con RPM actuales y objetivo",
        showInPanel: "Mostrar el control de ventiladores en el panel",
        settingsCaption: "Añade velocidades manuales y curvas de temperatura al panel.",
        fanNameFormat: "Ventilador %d",
        rpmFormat: "%d RPM",
        allowControl: "Permitir control",
        approvalCaption: "Permite Vorssaint en Ítems de inicio para usar el control protegido de los ventiladores.",
        openSettings: "Abrir Ajustes del Sistema",
        noFans: "Este Mac no tiene ningún ventilador controlable.",
        unsupported: "El control de ventiladores no está disponible en este Mac.",
        alreadyControlled: "Otro proceso controla los ventiladores. Devuélvelos primero al control del sistema.",
        failed: "Los ventiladores volvieron al sistema porque no se pudo verificar el control solicitado.",
        safetyCaption: "El control sigue activo hasta que vuelvas a Sistema. Se devuelve automáticamente si la app se desconecta, el Mac entra en reposo, fallan los sensores o aumenta la presión térmica.",
        safetyStopped: "Se devolvió el control al sistema porque se interrumpió el control de los ventiladores.",
        menuBarTitle: "Velocidad de ventiladores",
        systemControl: "Sistema",
        manualControl: "Manual",
        customCurve: "Curva",
        adaptiveControl: "Adaptativo",
        mode: "Modo de control",
        coolingIntensity: "Velocidad de los ventiladores",
        currentRPMFormat: "Actual: %d RPM",
        targetRPMFormat: "Objetivo: %d RPM",
        applyManual: "Aplicar control manual",
        applyCurve: "Aplicar curva",
        applyAdaptive: "Aplicar control adaptativo",
        returnToSystem: "Usar control del sistema",
        temperatureUnavailable: "El sensor de temperatura seleccionado dejó de responder. El control volvió al Sistema.",
        curveUnavailable: "Uno de los sensores de temperatura seleccionados no está disponible en este Mac.",
        sensor: "Sensor de temperatura",
        temperature: "Temperatura",
        fanSpeed: "Velocidad",
        addPoint: "Añadir punto",
        addSensor: "Añadir sensor",
        removePoint: "Eliminar punto",
        removeSensor: "Eliminar sensor",
        curveGraph: "Curva de temperatura y velocidad",
        averageSoC: "Promedio del SoC",
        hottestSoC: "SoC más caliente",
        averageCPU: "Promedio de CPU",
        hottestCPU: "CPU más caliente",
        hottestGPU: "GPU más caliente",
        helperUnavailable: "El controlador protegido de los ventiladores no está disponible. Permite Vorssaint en Ítems de inicio e inténtalo de nuevo.",
        resumeAfterRestart: "Reanudar tras reiniciar o salir del reposo",
        adaptiveRampStartTemperature: "Temperatura de inicio",
        adaptiveMaximumTemperature: "Temperatura de velocidad máxima",
        adaptiveSweetSpotLevel: "Velocidad inicial",
        adaptiveMaximumLevel: "Velocidad máxima",
        adaptiveProfile: "Perfil",
        adaptiveProfileQuiet: "Silencioso",
        adaptiveProfileBalanced: "Equilibrado",
        adaptiveProfilePerformance: "Rendimiento",
        adaptiveProfileCustom: "Personalizado",
        adaptiveAdvanced: "Avanzado",
        adaptiveHotspot: "Punto caliente",
        adaptiveActive: "Control adaptativo activo",
        applyChanges: "Aplicar cambios",
        adaptiveSensitivity: "Sensibilidad",
        adaptiveSensitivityRelaxed: "Suave",
        adaptiveSensitivityStandard: "Estándar",
        adaptiveSensitivityResponsive: "Rápida",
        helpMode: "Sistema: la lógica de ventiladores del propio Mac. Manual: una velocidad fija. Curva: la velocidad sigue los puntos de temperatura que editas. Adaptativo: la velocidad sigue la temperatura automáticamente según un perfil.",
        helpManual: "Una velocidad fija, como porcentaje del rango de cada ventilador, de su mínimo a su máximo. Se mantiene hasta que la cambies o vuelvas a Sistema.",
        helpCurve: "La velocidad sigue los puntos de temperatura que defines para cada sensor. Con varios sensores, se aplica la velocidad más alta solicitada.",
        helpChart: "Naranja: temperatura. Cian: velocidad actual. Gris: velocidad objetivo. Las líneas discontinuas marcan las temperaturas de inicio y máxima. Solo muestra esta sesión adaptativa.",
        helpProfile: "Ajustes predefinidos. Silencioso se mantiene cerca del comportamiento relajado del sistema, Equilibrado enfría antes y Rendimiento enfría lo antes y lo más fuerte posible. Cambiar cualquier valor en Avanzado pasa a Personalizado.",
        helpSensitivity: "Con qué rapidez siguen los ventiladores la temperatura. Suave ignora picos breves y baja despacio, Estándar es el valor predeterminado y Rápida acelera y frena antes. Si la temperatura ya alcanzó el umbral máximo, va directa a la velocidad máxima.",
        helpSweetSpot: "La velocidad, como porcentaje del rango de cada ventilador, que se usa al llegar a la temperatura de inicio. Por debajo, los ventiladores bajan hacia su mínimo.",
        helpMaximum: "La velocidad más alta que usará el control adaptativo, como porcentaje del rango de cada ventilador. Un valor menor es más silencioso, pero deja menos reserva de refrigeración con carga alta.",
        helpRampStart: "La temperatura a la que los ventiladores alcanzan la velocidad inicial y empiezan a acelerar. Un valor mayor mantiene el silencio más tiempo, pero el Mac se calienta más.",
        helpMaximumTemperature: "La temperatura a la que los ventiladores alcanzan la velocidad máxima. Un valor menor enfría con más fuerza. Debe quedar por encima de la temperatura de inicio por un margen mínimo.",
        helpApply: "Inicia este control con los ajustes mostrados y sustituye cualquier control en marcha.",
        helpReturn: "Detiene el control actual y devuelve los ventiladores al sistema.",
        helpActive: "El control adaptativo está en marcha exactamente con estos ajustes.",
        helpResume: "Vuelve a aplicar este control tras reiniciar, reactivar o reabrir la app. Elegir Sistema lo desactiva.",
        helpAllow: "El control de ventiladores necesita un pequeño ayudante protegido. macOS te pide permitirlo en Ítems de inicio."
    )

    static let sk = FanControlFeatureStrings(
        title: "Ovládanie ventilátorov",
        hubDescription: "Ovládajte ventilátory ručne alebo pomocou teplotných kriviek a sledujte aktuálne a cieľové otáčky",
        showInPanel: "Zobraziť ovládanie ventilátorov v paneli",
        settingsCaption: "Pridá do panela v lište ručné otáčky ventilátorov a teplotné krivky.",
        fanNameFormat: "Ventilátor %d",
        rpmFormat: "%d ot./min",
        allowControl: "Povoliť ovládanie ventilátorov",
        approvalCaption: "Povoľte Vorssaint v časti Položky a rozšírenia spúšťané pri prihlásení, aby mohol používať chránené ovládanie ventilátorov.",
        openSettings: "Otvoriť Systémové nastavenia",
        noFans: "Tento Mac nemá ovládateľný ventilátor.",
        unsupported: "Ovládanie ventilátorov nie je na tomto Macu dostupné.",
        alreadyControlled: "Ventilátory ovláda iný proces. Najprv ho vráťte na systémové ovládanie.",
        failed: "Ventilátory sa vrátili na systémové ovládanie, pretože požadované ovládanie sa nepodarilo overiť.",
        safetyCaption: "Ovládanie zostáva aktívne, kým sa nevrátite na Systém. Automaticky sa vráti, ak sa aplikácia odpojí, Mac uspí, zlyhajú snímače alebo stúpne tepelný tlak.",
        safetyStopped: "Ovládanie sa vrátilo systému, pretože bolo ovládanie ventilátorov prerušené.",
        menuBarTitle: "Otáčky ventilátora",
        systemControl: "Systém",
        manualControl: "Ručne",
        customCurve: "Krivka",
        adaptiveControl: "Adaptívny",
        mode: "Režim ovládania",
        coolingIntensity: "Otáčky ventilátora",
        currentRPMFormat: "Aktuálne %d ot./min",
        targetRPMFormat: "Cieľ %d ot./min",
        applyManual: "Použiť ručné ovládanie",
        applyCurve: "Použiť krivku ventilátora",
        applyAdaptive: "Použiť adaptívne ovládanie",
        returnToSystem: "Použiť systémové ovládanie",
        temperatureUnavailable: "Vybraný teplotný snímač prestal reagovať. Ovládanie sa vrátilo na Systém.",
        curveUnavailable: "Vybraný teplotný snímač nie je na tomto Macu dostupný.",
        sensor: "Teplotný snímač",
        temperature: "Teplota",
        fanSpeed: "Otáčky ventilátora",
        addPoint: "Pridať bod",
        addSensor: "Pridať snímač",
        removePoint: "Odstrániť bod",
        removeSensor: "Odstrániť snímač",
        curveGraph: "Krivka teploty a otáčok ventilátora",
        averageSoC: "Priemer SoC",
        hottestSoC: "Najteplejší SoC",
        averageCPU: "Priemer CPU",
        hottestCPU: "Najteplejší CPU",
        hottestGPU: "Najteplejší GPU",
        helperUnavailable: "Chránený ovládač ventilátorov nie je dostupný. Povoľte Vorssaint v časti Položky a rozšírenia spúšťané pri prihlásení a skúste to znova.",
        resumeAfterRestart: "Pokračovať po reštarte alebo spánku",
        adaptiveRampStartTemperature: "Počiatočná teplota",
        adaptiveMaximumTemperature: "Teplota maximálnej rýchlosti",
        adaptiveSweetSpotLevel: "Počiatočná rýchlosť",
        adaptiveMaximumLevel: "Maximálna rýchlosť",
        adaptiveProfile: "Profil",
        adaptiveProfileQuiet: "Tichý",
        adaptiveProfileBalanced: "Vyvážený",
        adaptiveProfilePerformance: "Výkon",
        adaptiveProfileCustom: "Vlastný",
        adaptiveAdvanced: "Rozšírené",
        adaptiveHotspot: "Horúci bod",
        adaptiveActive: "Adaptívne ovládanie beží",
        applyChanges: "Použiť zmeny",
        adaptiveSensitivity: "Citlivosť",
        adaptiveSensitivityRelaxed: "Pomalá",
        adaptiveSensitivityStandard: "Štandardná",
        adaptiveSensitivityResponsive: "Rýchla",
        helpMode: "Systém: vlastná logika ventilátorov Macu. Ručne: pevná rýchlosť. Krivka: rýchlosť sleduje body teploty, ktoré upravíte. Adaptívne: rýchlosť automaticky sleduje teplotu podľa profilu.",
        helpManual: "Pevná rýchlosť ako percento rozsahu každého ventilátora, od minima po maximum. Zostane, kým ju nezmeníte alebo sa nevrátite k systému.",
        helpCurve: "Rýchlosť sleduje body teploty, ktoré nastavíte pre každý senzor. Pri viacerých senzoroch platí najvyššia požadovaná rýchlosť.",
        helpChart: "Oranžová: teplota. Azúrová: aktuálna rýchlosť. Sivá: cieľová rýchlosť. Prerušované čiary označujú počiatočnú a maximálnu teplotu. Zobrazuje iba túto adaptívnu reláciu.",
        helpProfile: "Predvolené nastavenia. Tichý zostáva blízko pokojného správania systému, Vyvážený chladí skôr a Výkon chladí najskôr a najsilnejšie. Zmena ktorejkoľvek hodnoty v časti Rozšírené prepne na Vlastný.",
        helpSensitivity: "Ako rýchlo ventilátory sledujú teplotu. Pomalá ignoruje krátke špičky a spomaľuje pomaly, Štandardná je predvolená a Rýchla zrýchľuje a spomaľuje skôr. Ak teplota už dosiahla maximálny prah, ide rovno na maximálnu rýchlosť.",
        helpSweetSpot: "Rýchlosť ako percento rozsahu každého ventilátora, ktorá sa použije pri dosiahnutí počiatočnej teploty. Pod ňou ventilátory klesajú k minimu.",
        helpMaximum: "Najvyššia rýchlosť, ktorú adaptívne ovládanie použije, ako percento rozsahu každého ventilátora. Nižšia hodnota je tichšia, ale pri vysokej záťaži necháva menšiu rezervu chladenia.",
        helpRampStart: "Teplota, pri ktorej ventilátory dosiahnu počiatočnú rýchlosť a začnú zrýchľovať. Vyššia hodnota drží ventilátory dlhšie tiché, ale Mac sa viac zahrieva.",
        helpMaximumTemperature: "Teplota, pri ktorej ventilátory dosiahnu maximálnu rýchlosť. Nižšia hodnota chladí silnejšie. Musí byť vyššia ako počiatočná teplota aspoň o minimálny odstup.",
        helpApply: "Spustí toto ovládanie so zobrazeným nastavením a nahradí už bežiace ovládanie.",
        helpReturn: "Zastaví aktuálne ovládanie a vráti ventilátory systému.",
        helpActive: "Adaptívne ovládanie beží presne s týmto nastavením.",
        helpResume: "Po reštarte, prebudení alebo opätovnom otvorení aplikácie toto ovládanie znova použije. Voľba Systém ho vypne.",
        helpAllow: "Ovládanie ventilátorov potrebuje malého chráneného pomocníka. macOS vás požiada, aby ste ho povolili v položkách spúšťaných pri prihlásení."
    )

    static let de = FanControlFeatureStrings(
        title: "Lüftersteuerung",
        hubDescription: "Lüfter manuell oder per Temperaturkurve mit Ist- und Ziel-Drehzahl steuern",
        showInPanel: "Lüftersteuerung im Panel anzeigen",
        settingsCaption: "Fügt dem Panel manuelle Drehzahlen und Temperaturkurven hinzu.",
        fanNameFormat: "Lüfter %d",
        rpmFormat: "%d U/min",
        allowControl: "Lüftersteuerung erlauben",
        approvalCaption: "Erlaube Vorssaint unter Anmeldeobjekte, um die geschützte Lüftersteuerung zu verwenden.",
        openSettings: "Systemeinstellungen öffnen",
        noFans: "Dieser Mac hat keinen steuerbaren Lüfter.",
        unsupported: "Die Lüftersteuerung ist auf diesem Mac nicht verfügbar.",
        alreadyControlled: "Ein anderer Prozess steuert die Lüfter. Gib sie dort zuerst an das System zurück.",
        failed: "Die Lüfter wurden an das System zurückgegeben, weil die gewünschte Steuerung nicht bestätigt werden konnte.",
        safetyCaption: "Die Steuerung bleibt bis zur Rückkehr zu System aktiv. Sie wird bei getrennter App, Ruhezustand, Sensorausfall oder steigendem thermischem Druck automatisch zurückgegeben.",
        safetyStopped: "Wegen einer Unterbrechung wurde die Lüftersteuerung an das System zurückgegeben.",
        menuBarTitle: "Lüftergeschwindigkeit",
        systemControl: "System",
        manualControl: "Manuell",
        customCurve: "Kurve",
        adaptiveControl: "Adaptiv",
        mode: "Steuerungsmodus",
        coolingIntensity: "Lüftergeschwindigkeit",
        currentRPMFormat: "Aktuell %d U/min",
        targetRPMFormat: "Ziel %d U/min",
        applyManual: "Manuelle Steuerung anwenden",
        applyCurve: "Lüfterkurve anwenden",
        applyAdaptive: "Adaptive Steuerung anwenden",
        returnToSystem: "Systemsteuerung verwenden",
        temperatureUnavailable: "Der gewählte Temperatursensor antwortet nicht mehr. Die Steuerung wurde an das System zurückgegeben.",
        curveUnavailable: "Ein ausgewählter Temperatursensor ist auf diesem Mac nicht verfügbar.",
        sensor: "Temperatursensor",
        temperature: "Temperatur",
        fanSpeed: "Lüftergeschwindigkeit",
        addPoint: "Punkt hinzufügen",
        addSensor: "Sensor hinzufügen",
        removePoint: "Punkt entfernen",
        removeSensor: "Sensor entfernen",
        curveGraph: "Temperatur- und Lüfterkurve",
        averageSoC: "SoC-Durchschnitt",
        hottestSoC: "Heißester SoC",
        averageCPU: "CPU-Durchschnitt",
        hottestCPU: "Heißeste CPU",
        hottestGPU: "Heißeste GPU",
        helperUnavailable: "Die geschützte Lüftersteuerung ist nicht verfügbar. Erlaube Vorssaint unter Anmeldeobjekte und versuche es erneut.",
        resumeAfterRestart: "Nach Neustart oder Ruhezustand fortsetzen",
        adaptiveRampStartTemperature: "Starttemperatur",
        adaptiveMaximumTemperature: "Temperatur für Höchstdrehzahl",
        adaptiveSweetSpotLevel: "Startdrehzahl",
        adaptiveMaximumLevel: "Maximale Drehzahl",
        adaptiveProfile: "Profil",
        adaptiveProfileQuiet: "Leise",
        adaptiveProfileBalanced: "Ausgewogen",
        adaptiveProfilePerformance: "Leistung",
        adaptiveProfileCustom: "Eigenes",
        adaptiveAdvanced: "Erweitert",
        adaptiveHotspot: "Hotspot",
        adaptiveActive: "Adaptive Steuerung aktiv",
        applyChanges: "Änderungen anwenden",
        adaptiveSensitivity: "Empfindlichkeit",
        adaptiveSensitivityRelaxed: "Gelassen",
        adaptiveSensitivityStandard: "Standard",
        adaptiveSensitivityResponsive: "Schnell",
        helpMode: "System: die eigene Lüfterlogik des Mac. Manuell: eine feste Drehzahl. Kurve: die Drehzahl folgt den Temperaturpunkten, die du bearbeitest. Adaptiv: die Drehzahl folgt der Temperatur automatisch nach einem Profil.",
        helpManual: "Eine feste Drehzahl als Prozentsatz des Bereichs jedes Lüfters, vom Minimum bis zum Maximum. Sie bleibt, bis du sie änderst oder zu System zurückkehrst.",
        helpCurve: "Die Drehzahl folgt den Temperaturpunkten, die du für jeden Sensor festlegst. Bei mehreren Sensoren gilt die höchste angeforderte Drehzahl.",
        helpChart: "Orange: Temperatur. Cyan: aktuelle Drehzahl. Grau: Zieldrehzahl. Gestrichelte Linien markieren Start- und Höchsttemperatur. Zeigt nur diese adaptive Sitzung.",
        helpProfile: "Voreingestellte Abstimmungen. Leise bleibt nah am gelassenen Verhalten des Systems, Ausgewogen kühlt früher, Leistung kühlt am frühesten und am stärksten. Wenn du einen Wert unter Erweitert änderst, wechselt die Auswahl zu Eigenes.",
        helpSensitivity: "Wie schnell die Lüfter der Temperatur folgen. Gelassen ignoriert kurze Spitzen und regelt langsam zurück, Standard ist die Voreinstellung, Schnell dreht früher auf und ab. Erreicht die Temperatur bereits die Höchstschwelle, springt die Drehzahl direkt auf das Maximum.",
        helpSweetSpot: "Die Drehzahl als Prozentsatz des Bereichs jedes Lüfters, die bei Erreichen der Starttemperatur gilt. Darunter fallen die Lüfter Richtung Minimum.",
        helpMaximum: "Die höchste Drehzahl, die die adaptive Steuerung verwendet, als Prozentsatz des Bereichs jedes Lüfters. Ein niedrigerer Wert ist leiser, lässt aber unter hoher Last weniger Kühlreserve.",
        helpRampStart: "Die Temperatur, bei der die Lüfter die Startdrehzahl erreichen und hochzudrehen beginnen. Ein höherer Wert hält die Lüfter länger leise, der Mac wird aber wärmer.",
        helpMaximumTemperature: "Die Temperatur, bei der die Lüfter die maximale Drehzahl erreichen. Ein niedrigerer Wert kühlt stärker. Sie muss um einen Mindestabstand über der Starttemperatur liegen.",
        helpApply: "Startet diese Steuerung mit den angezeigten Einstellungen und ersetzt eine bereits laufende Steuerung.",
        helpReturn: "Beendet die aktuelle Steuerung und gibt die Lüfter an das System zurück.",
        helpActive: "Die adaptive Steuerung läuft genau mit diesen Einstellungen.",
        helpResume: "Wendet diese Steuerung nach Neustart, Aufwachen oder erneutem Öffnen der App wieder an. Die Auswahl von System schaltet sie aus.",
        helpAllow: "Die Lüftersteuerung braucht einen kleinen geschützten Helfer. macOS bittet dich, ihn unter Anmeldeobjekte zu erlauben."
    )

    static let fr = FanControlFeatureStrings(
        title: "Contrôle des ventilateurs",
        hubDescription: "Contrôle manuel ou par courbes de température avec vitesses réelle et cible",
        showInPanel: "Afficher le contrôle des ventilateurs dans le panneau",
        settingsCaption: "Ajoute les vitesses manuelles et les courbes de température au panneau.",
        fanNameFormat: "Ventilateur %d",
        rpmFormat: "%d tr/min",
        allowControl: "Autoriser le contrôle",
        approvalCaption: "Autorisez Vorssaint dans Ouverture pour utiliser le contrôle protégé des ventilateurs.",
        openSettings: "Ouvrir Réglages Système",
        noFans: "Ce Mac ne possède aucun ventilateur contrôlable.",
        unsupported: "Le contrôle des ventilateurs n’est pas disponible sur ce Mac.",
        alreadyControlled: "Un autre processus contrôle les ventilateurs. Rendez-les d’abord au système.",
        failed: "Les ventilateurs ont été rendus au système car le contrôle demandé n’a pas pu être vérifié.",
        safetyCaption: "Le contrôle reste actif jusqu’au retour à Système. Il est rendu automatiquement si l’app se déconnecte, si le Mac veille, si les capteurs échouent ou si la pression thermique augmente.",
        safetyStopped: "Le contrôle a été rendu au système car le contrôle des ventilateurs a été interrompu.",
        menuBarTitle: "Vitesse des ventilateurs",
        systemControl: "Système",
        manualControl: "Manuel",
        customCurve: "Courbe",
        adaptiveControl: "Adaptatif",
        mode: "Mode de contrôle",
        coolingIntensity: "Vitesse des ventilateurs",
        currentRPMFormat: "Actuelle %d tr/min",
        targetRPMFormat: "Cible %d tr/min",
        applyManual: "Appliquer le contrôle manuel",
        applyCurve: "Appliquer la courbe",
        applyAdaptive: "Appliquer le contrôle adaptatif",
        returnToSystem: "Utiliser le contrôle du système",
        temperatureUnavailable: "Le capteur de température choisi ne répond plus. Le contrôle a été rendu au Système.",
        curveUnavailable: "Un capteur de température sélectionné n’est pas disponible sur ce Mac.",
        sensor: "Capteur de température",
        temperature: "Température",
        fanSpeed: "Vitesse",
        addPoint: "Ajouter un point",
        addSensor: "Ajouter un capteur",
        removePoint: "Supprimer le point",
        removeSensor: "Supprimer le capteur",
        curveGraph: "Courbe de température et de vitesse",
        averageSoC: "Moyenne du SoC",
        hottestSoC: "SoC le plus chaud",
        averageCPU: "Moyenne du CPU",
        hottestCPU: "CPU le plus chaud",
        hottestGPU: "GPU le plus chaud",
        helperUnavailable: "Le contrôleur protégé des ventilateurs est indisponible. Autorisez Vorssaint dans Ouverture, puis réessayez.",
        resumeAfterRestart: "Reprendre après un redémarrage ou la veille",
        adaptiveRampStartTemperature: "Température de départ",
        adaptiveMaximumTemperature: "Température de vitesse maximale",
        adaptiveSweetSpotLevel: "Vitesse de départ",
        adaptiveMaximumLevel: "Vitesse maximale",
        adaptiveProfile: "Profil",
        adaptiveProfileQuiet: "Silencieux",
        adaptiveProfileBalanced: "Équilibré",
        adaptiveProfilePerformance: "Performance",
        adaptiveProfileCustom: "Personnalisé",
        adaptiveAdvanced: "Avancé",
        adaptiveHotspot: "Point chaud",
        adaptiveActive: "Contrôle adaptatif actif",
        applyChanges: "Appliquer les modifications",
        adaptiveSensitivity: "Sensibilité",
        adaptiveSensitivityRelaxed: "Souple",
        adaptiveSensitivityStandard: "Standard",
        adaptiveSensitivityResponsive: "Réactive",
        helpMode: "Système : la logique de ventilation propre au Mac. Manuel : une vitesse fixe. Courbe : la vitesse suit les points de température que vous modifiez. Adaptatif : la vitesse suit automatiquement la température selon un profil.",
        helpManual: "Une vitesse fixe, en pourcentage de la plage de chaque ventilateur, du minimum au maximum. Elle reste jusqu’à ce que vous la changiez ou reveniez à Système.",
        helpCurve: "La vitesse suit les points de température définis pour chaque capteur. Avec plusieurs capteurs, la vitesse demandée la plus élevée l’emporte.",
        helpChart: "Orange : température. Cyan : vitesse actuelle. Gris : vitesse cible. Les lignes en pointillés marquent les températures de départ et maximale. Ne couvre que cette session adaptative.",
        helpProfile: "Réglages prédéfinis. Silencieux reste proche du comportement tranquille du système, Équilibré refroidit plus tôt et Performance refroidit le plus tôt et le plus fort. Modifier une valeur dans Avancé passe en Personnalisé.",
        helpSensitivity: "La rapidité avec laquelle les ventilateurs suivent la température. Souple ignore les pics brefs et ralentit lentement, Standard est la valeur par défaut, Réactive accélère et ralentit plus tôt. Si la température a déjà atteint le seuil maximal, la vitesse passe directement au maximum.",
        helpSweetSpot: "La vitesse, en pourcentage de la plage de chaque ventilateur, utilisée quand la température atteint la température de départ. En dessous, les ventilateurs redescendent vers leur minimum.",
        helpMaximum: "La vitesse la plus élevée que le contrôle adaptatif utilisera, en pourcentage de la plage de chaque ventilateur. Une valeur plus basse est plus silencieuse, mais laisse moins de réserve de refroidissement en forte charge.",
        helpRampStart: "La température à laquelle les ventilateurs atteignent la vitesse de départ et commencent à accélérer. Une valeur plus haute garde les ventilateurs silencieux plus longtemps, mais le Mac chauffe davantage.",
        helpMaximumTemperature: "La température à laquelle les ventilateurs atteignent la vitesse maximale. Une valeur plus basse refroidit plus fort. Elle doit dépasser la température de départ d’un écart minimal.",
        helpApply: "Démarre ce contrôle avec les réglages affichés et remplace tout contrôle en cours.",
        helpReturn: "Arrête le contrôle actuel et rend les ventilateurs au système.",
        helpActive: "Le contrôle adaptatif fonctionne exactement avec ces réglages.",
        helpResume: "Réapplique ce contrôle après un redémarrage, une sortie de veille ou la réouverture de l’app. Choisir Système le désactive.",
        helpAllow: "Le contrôle des ventilateurs nécessite un petit assistant protégé. macOS vous demande de l’autoriser dans Ouverture."
    )

    static let it = FanControlFeatureStrings(
        title: "Controllo ventole",
        hubDescription: "Controllo manuale o con curve termiche e RPM attuali e obiettivo",
        showInPanel: "Mostra il controllo ventole nel pannello",
        settingsCaption: "Aggiunge velocità manuali e curve di temperatura al pannello.",
        fanNameFormat: "Ventola %d",
        rpmFormat: "%d RPM",
        allowControl: "Consenti controllo",
        approvalCaption: "Consenti Vorssaint in Elementi login per usare il controllo protetto delle ventole.",
        openSettings: "Apri Impostazioni di Sistema",
        noFans: "Questo Mac non ha ventole controllabili.",
        unsupported: "Il controllo ventole non è disponibile su questo Mac.",
        alreadyControlled: "Un altro processo controlla le ventole. Riportale prima al controllo di sistema.",
        failed: "Le ventole sono tornate al sistema perché non è stato possibile verificare il controllo richiesto.",
        safetyCaption: "Il controllo resta attivo finché non torni a Sistema. Viene restituito automaticamente se l’app si disconnette, il Mac va in stop, i sensori falliscono o aumenta la pressione termica.",
        safetyStopped: "Il controllo è tornato al sistema perché il controllo delle ventole è stato interrotto.",
        menuBarTitle: "Velocità ventole",
        systemControl: "Sistema",
        manualControl: "Manuale",
        customCurve: "Curva",
        adaptiveControl: "Adattivo",
        mode: "Modalità di controllo",
        coolingIntensity: "Velocità delle ventole",
        currentRPMFormat: "Attuale %d RPM",
        targetRPMFormat: "Obiettivo %d RPM",
        applyManual: "Applica controllo manuale",
        applyCurve: "Applica curva",
        applyAdaptive: "Applica controllo adattivo",
        returnToSystem: "Usa controllo di sistema",
        temperatureUnavailable: "Il sensore di temperatura selezionato non risponde più. Il controllo è tornato al Sistema.",
        curveUnavailable: "Un sensore di temperatura selezionato non è disponibile su questo Mac.",
        sensor: "Sensore di temperatura",
        temperature: "Temperatura",
        fanSpeed: "Velocità",
        addPoint: "Aggiungi punto",
        addSensor: "Aggiungi sensore",
        removePoint: "Rimuovi punto",
        removeSensor: "Rimuovi sensore",
        curveGraph: "Curva di temperatura e velocità",
        averageSoC: "Media SoC",
        hottestSoC: "SoC più caldo",
        averageCPU: "Media CPU",
        hottestCPU: "CPU più calda",
        hottestGPU: "GPU più calda",
        helperUnavailable: "Il controller protetto delle ventole non è disponibile. Consenti Vorssaint negli elementi di login e riprova.",
        resumeAfterRestart: "Riprendi dopo il riavvio o lo stop",
        adaptiveRampStartTemperature: "Temperatura di avvio",
        adaptiveMaximumTemperature: "Temperatura di velocità massima",
        adaptiveSweetSpotLevel: "Velocità iniziale",
        adaptiveMaximumLevel: "Velocità massima",
        adaptiveProfile: "Profilo",
        adaptiveProfileQuiet: "Silenzioso",
        adaptiveProfileBalanced: "Bilanciato",
        adaptiveProfilePerformance: "Prestazioni",
        adaptiveProfileCustom: "Personalizzato",
        adaptiveAdvanced: "Avanzate",
        adaptiveHotspot: "Punto caldo",
        adaptiveActive: "Controllo adattivo attivo",
        applyChanges: "Applica modifiche",
        adaptiveSensitivity: "Sensibilità",
        adaptiveSensitivityRelaxed: "Rilassata",
        adaptiveSensitivityStandard: "Standard",
        adaptiveSensitivityResponsive: "Reattiva",
        helpMode: "Sistema: la logica delle ventole del Mac stesso. Manuale: una velocità fissa. Curva: la velocità segue i punti di temperatura che modifichi. Adattivo: la velocità segue automaticamente la temperatura in base a un profilo.",
        helpManual: "Una velocità fissa, come percentuale dell’intervallo di ogni ventola, dal minimo al massimo. Resta finché non la modifichi o torni a Sistema.",
        helpCurve: "La velocità segue i punti di temperatura impostati per ogni sensore. Con più sensori vale la velocità richiesta più alta.",
        helpChart: "Arancione: temperatura. Ciano: velocità attuale. Grigio: velocità target. Le linee tratteggiate indicano le temperature di avvio e massima. Mostra solo questa sessione adattiva.",
        helpProfile: "Impostazioni predefinite. Silenzioso resta vicino al comportamento rilassato del sistema, Bilanciato raffredda prima e Prestazioni raffredda per primo e con più forza. Modificare un valore in Avanzate passa a Personalizzato.",
        helpSensitivity: "Quanto rapidamente le ventole seguono la temperatura. Rilassata ignora i picchi brevi e scende lentamente, Standard è il valore predefinito, Reattiva accelera e rallenta prima. Se la temperatura ha già raggiunto la soglia massima, si passa subito alla velocità massima.",
        helpSweetSpot: "La velocità, come percentuale dell’intervallo di ogni ventola, usata quando la temperatura raggiunge quella di avvio. Al di sotto, le ventole scendono verso il minimo.",
        helpMaximum: "La velocità più alta che il controllo adattivo userà, come percentuale dell’intervallo di ogni ventola. Un valore più basso è più silenzioso, ma lascia meno riserva di raffreddamento sotto carico elevato.",
        helpRampStart: "La temperatura a cui le ventole raggiungono la velocità iniziale e iniziano ad accelerare. Un valore più alto mantiene le ventole silenziose più a lungo, ma il Mac si scalda di più.",
        helpMaximumTemperature: "La temperatura a cui le ventole raggiungono la velocità massima. Un valore più basso raffredda con più forza. Deve superare la temperatura di avvio di un intervallo minimo.",
        helpApply: "Avvia questo controllo con le impostazioni mostrate e sostituisce qualsiasi controllo in corso.",
        helpReturn: "Interrompe il controllo attuale e restituisce le ventole al sistema.",
        helpActive: "Il controllo adattivo è in esecuzione esattamente con queste impostazioni.",
        helpResume: "Riapplica questo controllo dopo un riavvio, la riattivazione o la riapertura dell’app. Scegliere Sistema lo disattiva.",
        helpAllow: "Il controllo delle ventole richiede un piccolo helper protetto. macOS ti chiede di consentirlo in Elementi login."
    )

    static let ja = FanControlFeatureStrings(
        title: "ファン制御",
        hubDescription: "現在と目標の回転数を確認しながら手動または温度曲線でファンを制御",
        showInPanel: "ファン制御をパネルに表示",
        settingsCaption: "手動の回転数と温度曲線をメニューバーパネルに追加します。",
        fanNameFormat: "ファン%d",
        rpmFormat: "%d RPM",
        allowControl: "ファン制御を許可",
        approvalCaption: "保護されたファン制御を使うには、ログイン項目でVorssaintを許可してください。",
        openSettings: "システム設定を開く",
        noFans: "このMacには制御可能なファンがありません。",
        unsupported: "このMacではファン制御を利用できません。",
        alreadyControlled: "別のプロセスがファンを制御しています。先にシステム制御へ戻してください。",
        failed: "要求した制御を確認できなかったため、ファンはシステム制御へ戻りました。",
        safetyCaption: "システムへ戻すまで制御は有効です。アプリの切断、Macのスリープ、センサー障害、熱圧力の上昇時には自動でシステムへ戻ります。",
        safetyStopped: "ファン制御が中断されたため、システム制御へ戻りました。",
        menuBarTitle: "ファン速度",
        systemControl: "システム",
        manualControl: "手動",
        customCurve: "曲線",
        adaptiveControl: "適応",
        mode: "制御モード",
        coolingIntensity: "ファン速度",
        currentRPMFormat: "現在 %d RPM",
        targetRPMFormat: "目標 %d RPM",
        applyManual: "手動制御を適用",
        applyCurve: "ファン曲線を適用",
        applyAdaptive: "適応制御を適用",
        returnToSystem: "システム制御を使用",
        temperatureUnavailable: "選択した温度センサーが応答しなくなりました。システム制御へ戻りました。",
        curveUnavailable: "選択した温度センサーのいずれかをこのMacで利用できません。",
        sensor: "温度センサー",
        temperature: "温度",
        fanSpeed: "ファン速度",
        addPoint: "ポイントを追加",
        addSensor: "センサーを追加",
        removePoint: "ポイントを削除",
        removeSensor: "センサーを削除",
        curveGraph: "温度とファン速度の曲線",
        averageSoC: "SoC平均",
        hottestSoC: "最高SoC",
        averageCPU: "CPU平均",
        hottestCPU: "最高CPU",
        hottestGPU: "最高GPU",
        helperUnavailable: "保護されたファンコントローラを利用できません。ログイン項目でVorssaintを許可してから、もう一度お試しください。",
        resumeAfterRestart: "再起動やスリープのあとに再開",
        adaptiveRampStartTemperature: "開始温度",
        adaptiveMaximumTemperature: "最高回転数の温度",
        adaptiveSweetSpotLevel: "開始回転数",
        adaptiveMaximumLevel: "最高回転数",
        adaptiveProfile: "プロファイル",
        adaptiveProfileQuiet: "静音",
        adaptiveProfileBalanced: "バランス",
        adaptiveProfilePerformance: "パフォーマンス",
        adaptiveProfileCustom: "カスタム",
        adaptiveAdvanced: "詳細",
        adaptiveHotspot: "ホットスポット",
        adaptiveActive: "適応制御を実行中",
        applyChanges: "変更を適用",
        adaptiveSensitivity: "感度",
        adaptiveSensitivityRelaxed: "ゆるやか",
        adaptiveSensitivityStandard: "標準",
        adaptiveSensitivityResponsive: "素早い",
        helpMode: "システム：Mac 標準のファン制御。手動：固定回転数。カーブ：編集した温度ポイントに従う。適応：プロファイルに沿って温度に自動で追従します。",
        helpManual: "各ファンの範囲（最小〜最大）に対する割合で固定する回転数です。変更するかシステムに戻すまで維持されます。",
        helpCurve: "センサーごとに設定した温度ポイントに従って回転数が決まります。複数のセンサーがある場合は、最も高い要求値が使われます。",
        helpChart: "オレンジ：温度。シアン：現在の回転数。グレー：目標回転数。点線は開始温度と最高温度です。今回の適応制御中のみ表示します。",
        helpProfile: "あらかじめ用意した設定です。静音はシステムのゆるやかな挙動に近く、バランスは早めに冷却し、パフォーマンスは最も早く強く冷却します。「詳細」の値を変更すると「カスタム」になります。",
        helpSensitivity: "ファンが温度変化に追従する速さです。ゆるやかは短いスパイクを無視してゆっくり下げ、標準は既定値、素早いはより早く上げ下げします。温度が上限温度に達すると、すぐに最高回転数になります。",
        helpSweetSpot: "温度が開始温度に達したときの回転数で、各ファンの範囲に対する割合です。それより低いと、ファンは最小回転数へ下がります。",
        helpMaximum: "適応制御が使う最高回転数で、各ファンの範囲に対する割合です。低いほど静かですが、高負荷時の冷却の余裕は減ります。",
        helpRampStart: "ファンが開始回転数に達し、加速を始める温度です。高いほど静かな時間が長くなりますが、Mac は熱くなります。",
        helpMaximumTemperature: "ファンが最高回転数に達する温度です。低いほど強く冷却します。開始温度より最小間隔以上高く設定する必要があります。",
        helpApply: "表示中の設定でこの制御を開始し、実行中の制御を置き換えます。",
        helpReturn: "現在の制御を停止し、ファンをシステムに戻します。",
        helpActive: "適応制御はこの設定で実行中です。",
        helpResume: "再起動、スリープ解除、App の再起動後にこの制御を自動で再適用します。「システム」を選ぶとオフになります。",
        helpAllow: "ファン制御には、保護された小さなヘルパーが必要です。macOS が「ログイン項目」での許可を求めます。"
    )

    static let ko = FanControlFeatureStrings(
        title: "팬 제어",
        hubDescription: "현재 및 목표 RPM을 보며 수동 또는 온도 곡선으로 팬 제어",
        showInPanel: "패널에 팬 제어 표시",
        settingsCaption: "메뉴 막대 패널에 수동 속도와 온도 곡선을 추가합니다.",
        fanNameFormat: "팬 %d",
        rpmFormat: "%d RPM",
        allowControl: "팬 제어 허용",
        approvalCaption: "보호된 팬 제어를 사용하려면 로그인 항목에서 Vorssaint를 허용하세요.",
        openSettings: "시스템 설정 열기",
        noFans: "이 Mac에는 제어 가능한 팬이 없습니다.",
        unsupported: "이 Mac에서는 팬 제어를 사용할 수 없습니다.",
        alreadyControlled: "다른 프로세스가 팬을 제어하고 있습니다. 먼저 시스템 제어로 돌려놓으세요.",
        failed: "요청한 제어를 확인할 수 없어 팬이 시스템 제어로 돌아갔습니다.",
        safetyCaption: "시스템으로 돌아갈 때까지 제어가 유지됩니다. 앱 연결 해제, Mac 잠자기, 센서 오류 또는 열 압력 상승 시 자동으로 시스템에 반환됩니다.",
        safetyStopped: "팬 제어가 중단되어 시스템 제어로 돌아갔습니다.",
        menuBarTitle: "팬 속도",
        systemControl: "시스템",
        manualControl: "수동",
        customCurve: "곡선",
        adaptiveControl: "적응형",
        mode: "제어 모드",
        coolingIntensity: "팬 속도",
        currentRPMFormat: "현재 %d RPM",
        targetRPMFormat: "목표 %d RPM",
        applyManual: "수동 제어 적용",
        applyCurve: "팬 곡선 적용",
        applyAdaptive: "적응형 제어 적용",
        returnToSystem: "시스템 제어 사용",
        temperatureUnavailable: "선택한 온도 센서가 응답하지 않습니다. 팬 제어가 시스템으로 돌아갔습니다.",
        curveUnavailable: "선택한 온도 센서 중 하나를 이 Mac에서 사용할 수 없습니다.",
        sensor: "온도 센서",
        temperature: "온도",
        fanSpeed: "팬 속도",
        addPoint: "지점 추가",
        addSensor: "센서 추가",
        removePoint: "지점 제거",
        removeSensor: "센서 제거",
        curveGraph: "온도 및 팬 속도 곡선",
        averageSoC: "평균 SoC",
        hottestSoC: "가장 뜨거운 SoC",
        averageCPU: "평균 CPU",
        hottestCPU: "가장 뜨거운 CPU",
        hottestGPU: "가장 뜨거운 GPU",
        helperUnavailable: "보호된 팬 컨트롤러를 사용할 수 없습니다. 로그인 항목에서 Vorssaint를 허용한 다음 다시 시도하세요.",
        resumeAfterRestart: "재시작 또는 잠자기 후 다시 적용",
        adaptiveRampStartTemperature: "시작 온도",
        adaptiveMaximumTemperature: "최대 속도 온도",
        adaptiveSweetSpotLevel: "시작 속도",
        adaptiveMaximumLevel: "최대 속도",
        adaptiveProfile: "프로필",
        adaptiveProfileQuiet: "저소음",
        adaptiveProfileBalanced: "균형",
        adaptiveProfilePerformance: "성능",
        adaptiveProfileCustom: "사용자 설정",
        adaptiveAdvanced: "고급",
        adaptiveHotspot: "핫스팟",
        adaptiveActive: "적응형 제어 실행 중",
        applyChanges: "변경 사항 적용",
        adaptiveSensitivity: "민감도",
        adaptiveSensitivityRelaxed: "느긋함",
        adaptiveSensitivityStandard: "표준",
        adaptiveSensitivityResponsive: "빠름",
        helpMode: "시스템: Mac 기본 팬 제어. 수동: 고정 속도. 곡선: 직접 편집한 온도 지점에 따라 속도 조절. 적응형: 프로필에 따라 온도에 맞춰 자동 조절.",
        helpManual: "각 팬의 범위(최소~최대)에 대한 비율로 정하는 고정 속도입니다. 변경하거나 시스템으로 돌아갈 때까지 유지됩니다.",
        helpCurve: "센서마다 설정한 온도 지점에 따라 속도가 정해집니다. 센서가 여러 개면 가장 높은 요구 속도가 적용됩니다.",
        helpChart: "주황: 온도. 청록: 현재 팬 속도. 회색: 목표 속도. 점선은 시작 온도와 최대 온도입니다. 이번 적응형 제어 동안의 기록만 표시합니다.",
        helpProfile: "미리 정해진 설정입니다. 저소음은 시스템의 느긋한 동작에 가깝고, 균형은 더 일찍 냉각하며, 성능은 가장 일찍 강하게 냉각합니다. 고급의 값을 바꾸면 사용자 설정으로 바뀝니다.",
        helpSensitivity: "팬이 온도 변화를 따라가는 속도입니다. 느긋함은 짧은 급등을 무시하고 천천히 줄이며, 표준은 기본값, 빠름은 더 빨리 올리고 내립니다. 온도가 이미 최대 온도에 도달하면 곧바로 최대 속도가 됩니다.",
        helpSweetSpot: "온도가 시작 온도에 도달했을 때의 속도로, 각 팬 범위에 대한 비율입니다. 그보다 낮으면 팬은 최소 속도로 내려갑니다.",
        helpMaximum: "적응형 제어가 사용하는 최고 속도로, 각 팬 범위에 대한 비율입니다. 낮을수록 조용하지만 고부하에서 냉각 여유가 줄어듭니다.",
        helpRampStart: "팬이 시작 속도에 도달하고 빨라지기 시작하는 온도입니다. 높을수록 팬이 오래 조용하지만 Mac이 더 뜨거워집니다.",
        helpMaximumTemperature: "팬이 최대 속도에 도달하는 온도입니다. 낮을수록 강하게 냉각합니다. 시작 온도보다 최소 간격 이상 높아야 합니다.",
        helpApply: "표시된 설정으로 이 제어를 시작하고, 실행 중인 제어를 대체합니다.",
        helpReturn: "현재 제어를 중지하고 팬을 시스템에 돌려줍니다.",
        helpActive: "적응형 제어가 이 설정 그대로 실행 중입니다.",
        helpResume: "재시작, 잠자기 해제, 앱 재실행 후 이 제어를 자동으로 다시 적용합니다. 시스템을 선택하면 꺼집니다.",
        helpAllow: "팬 제어에는 보호된 작은 도우미가 필요합니다. macOS가 로그인 항목에서 허용하도록 요청합니다."
    )

    static let zhHans = FanControlFeatureStrings(
        title: "风扇控制",
        hubDescription: "查看当前和目标转速，并手动或按温度曲线控制风扇",
        showInPanel: "在面板中显示风扇控制",
        settingsCaption: "在菜单栏面板中添加手动转速和温度曲线。",
        fanNameFormat: "风扇%d",
        rpmFormat: "%d RPM",
        allowControl: "允许风扇控制",
        approvalCaption: "请在登录项中允许Vorssaint使用受保护的风扇控制。",
        openSettings: "打开系统设置",
        noFans: "这台Mac没有可控风扇。",
        unsupported: "这台Mac不支持风扇控制。",
        alreadyControlled: "另一个进程正在控制风扇。请先在那里恢复系统控制。",
        failed: "无法验证请求的控制，风扇已恢复系统控制。",
        safetyCaption: "控制会保持到你恢复系统模式。App 断开、Mac睡眠、传感器失效或热压力升高时会自动交还系统。",
        safetyStopped: "风扇控制中断，已恢复系统控制。",
        menuBarTitle: "风扇转速",
        systemControl: "系统",
        manualControl: "手动",
        customCurve: "曲线",
        adaptiveControl: "智能",
        mode: "控制模式",
        coolingIntensity: "风扇速度",
        currentRPMFormat: "当前 %d RPM",
        targetRPMFormat: "目标 %d RPM",
        applyManual: "启用手动控制",
        applyCurve: "启用风扇曲线",
        applyAdaptive: "启用智能控制",
        returnToSystem: "使用系统控制",
        temperatureUnavailable: "所选温度传感器停止响应。风扇控制已恢复系统模式。",
        curveUnavailable: "这台Mac不支持某个所选温度传感器。",
        sensor: "温度传感器",
        temperature: "温度",
        fanSpeed: "风扇速度",
        addPoint: "添加节点",
        addSensor: "添加传感器",
        removePoint: "移除节点",
        removeSensor: "移除传感器",
        curveGraph: "温度与风扇速度曲线",
        averageSoC: "SoC平均温度",
        hottestSoC: "SoC最高温度",
        averageCPU: "CPU平均温度",
        hottestCPU: "CPU最高温度",
        hottestGPU: "GPU最高温度",
        helperUnavailable: "受保护的风扇控制器不可用。请在登录项中允许 Vorssaint，然后重试。",
        resumeAfterRestart: "重新启动或睡眠后恢复",
        adaptiveRampStartTemperature: "起始温度",
        adaptiveMaximumTemperature: "满速温度",
        adaptiveSweetSpotLevel: "起始转速",
        adaptiveMaximumLevel: "最高转速",
        adaptiveProfile: "预设",
        adaptiveProfileQuiet: "安静",
        adaptiveProfileBalanced: "均衡",
        adaptiveProfilePerformance: "性能",
        adaptiveProfileCustom: "自定义",
        adaptiveAdvanced: "高级",
        adaptiveHotspot: "热点",
        adaptiveActive: "智能控制运行中",
        applyChanges: "应用更改",
        adaptiveSensitivity: "灵敏度",
        adaptiveSensitivityRelaxed: "平缓",
        adaptiveSensitivityStandard: "标准",
        adaptiveSensitivityResponsive: "迅速",
        helpMode: "系统：由 Mac 自带的风扇逻辑控制。手动：固定转速。曲线：转速跟随你编辑的温度点。智能：转速按预设自动跟随温度。",
        helpManual: "固定转速，按每个风扇量程（最低到最高）的百分比设置。会一直保持，直到你修改或回到系统控制。",
        helpCurve: "转速跟随你为每个传感器设置的温度点。有多个传感器时，取要求最高的转速。",
        helpChart: "橙色：温度。青色：当前转速。灰色：目标转速。虚线标出起始温度和最高温度。仅显示本次智能控制期间的数据。",
        helpProfile: "预设参数。安静接近系统的宽松行为，均衡更早开始散热，性能最早、最强力地散热。修改“高级”中的任一项会变为“自定义”。",
        helpSensitivity: "风扇跟随温度变化的快慢。平缓会忽略短暂尖峰并缓慢回落，标准为默认，迅速则更快升速和降速。温度一旦达到上限温度，会直接升到最高转速。",
        helpSweetSpot: "温度达到起始温度时使用的转速，按每个风扇量程的百分比。低于该温度时，风扇会向最低转速回落。",
        helpMaximum: "智能控制会使用的最高转速，按每个风扇量程的百分比。数值越低越安静，但高负载时留给散热的余量也越少。",
        helpRampStart: "风扇达到起始转速并开始加速的温度。数值越高，风扇安静的时间越长，但 Mac 会运行得更热。",
        helpMaximumTemperature: "风扇达到最高转速的温度。数值越低散热越强。必须比起始温度高出最小间隔。",
        helpApply: "按当前显示的设置启动此控制，并替换正在运行的控制。",
        helpReturn: "停止当前控制，把风扇交还给系统。",
        helpActive: "智能控制正按这组设置运行。",
        helpResume: "重启、唤醒或重新打开 App 后自动再次应用此控制。选择“系统”会关闭它。",
        helpAllow: "风扇控制需要一个受保护的小型辅助程序。macOS 会请你在“登录项”中允许它。"
    )

    static let zhTW = FanControlFeatureStrings(
        title: "風扇控制",
        hubDescription: "查看目前與目標轉速，並手動或依溫度曲線控制風扇",
        showInPanel: "在面板中顯示風扇控制",
        settingsCaption: "在選單列面板中加入手動轉速與溫度曲線。",
        fanNameFormat: "風扇%d",
        rpmFormat: "%d RPM",
        allowControl: "允許風扇控制",
        approvalCaption: "請在登入項目中允許Vorssaint使用受保護的風扇控制。",
        openSettings: "打開系統設定",
        noFans: "這台Mac沒有可控制的風扇。",
        unsupported: "這台Mac不支援風扇控制。",
        alreadyControlled: "另一個程序正在控制風扇。請先在那裡恢復系統控制。",
        failed: "無法驗證要求的控制，風扇已恢復系統控制。",
        safetyCaption: "控制會持續到你恢復系統模式。App中斷、Mac睡眠、感測器失效或熱壓力升高時會自動交還系統。",
        safetyStopped: "風扇控制中斷，已恢復系統控制。",
        menuBarTitle: "風扇轉速",
        systemControl: "系統",
        manualControl: "手動",
        customCurve: "曲線",
        adaptiveControl: "智慧",
        mode: "控制模式",
        coolingIntensity: "風扇速度",
        currentRPMFormat: "目前 %d RPM",
        targetRPMFormat: "目標 %d RPM",
        applyManual: "套用手動控制",
        applyCurve: "套用風扇曲線",
        applyAdaptive: "啟用智慧控制",
        returnToSystem: "使用系統控制",
        temperatureUnavailable: "所選溫度感測器停止回應。風扇控制已恢復系統模式。",
        curveUnavailable: "這台Mac不支援某個所選溫度感測器。",
        sensor: "溫度感測器",
        temperature: "溫度",
        fanSpeed: "風扇速度",
        addPoint: "加入節點",
        addSensor: "加入感測器",
        removePoint: "移除節點",
        removeSensor: "移除感測器",
        curveGraph: "溫度與風扇速度曲線",
        averageSoC: "SoC平均溫度",
        hottestSoC: "SoC最高溫度",
        averageCPU: "CPU平均溫度",
        hottestCPU: "CPU最高溫度",
        hottestGPU: "GPU最高溫度",
        helperUnavailable: "受保護的風扇控制器無法使用。請在登入項目中允許 Vorssaint，然後再試一次。",
        resumeAfterRestart: "重新開機或睡眠後恢復",
        adaptiveRampStartTemperature: "起始溫度",
        adaptiveMaximumTemperature: "滿速溫度",
        adaptiveSweetSpotLevel: "起始轉速",
        adaptiveMaximumLevel: "最高轉速",
        adaptiveProfile: "預設組合",
        adaptiveProfileQuiet: "安靜",
        adaptiveProfileBalanced: "平衡",
        adaptiveProfilePerformance: "效能",
        adaptiveProfileCustom: "自訂",
        adaptiveAdvanced: "進階",
        adaptiveHotspot: "熱點",
        adaptiveActive: "智慧控制執行中",
        applyChanges: "套用變更",
        adaptiveSensitivity: "靈敏度",
        adaptiveSensitivityRelaxed: "平緩",
        adaptiveSensitivityStandard: "標準",
        adaptiveSensitivityResponsive: "迅速",
        helpMode: "系統：由 Mac 內建的風扇邏輯控制。手動：固定轉速。曲線：轉速跟隨你編輯的溫度點。智慧：轉速依預設組合自動跟隨溫度。",
        helpManual: "固定轉速，以每個風扇範圍（最低到最高）的百分比設定。會一直維持，直到你修改或回到系統控制。",
        helpCurve: "轉速跟隨你為每個感測器設定的溫度點。有多個感測器時，取要求最高的轉速。",
        helpChart: "橘色：溫度。青色：目前轉速。灰色：目標轉速。虛線標示起始溫度與最高溫度。僅顯示本次智慧控制期間的資料。",
        helpProfile: "預設組合。安靜接近系統的寬鬆行為，平衡較早開始散熱，效能最早、最強力地散熱。修改「進階」中的任一項會變成「自訂」。",
        helpSensitivity: "風扇跟隨溫度變化的快慢。平緩會忽略短暫尖峰並緩慢回落，標準為預設，迅速則更快升速與降速。溫度一旦達到上限溫度，會直接升到最高轉速。",
        helpSweetSpot: "溫度達到起始溫度時使用的轉速，以每個風扇範圍的百分比表示。低於該溫度時，風扇會向最低轉速回落。",
        helpMaximum: "智慧控制會使用的最高轉速，以每個風扇範圍的百分比表示。數值越低越安靜，但高負載時保留的散熱餘量也越少。",
        helpRampStart: "風扇達到起始轉速並開始加速的溫度。數值越高，風扇安靜的時間越長，但 Mac 會運行得更熱。",
        helpMaximumTemperature: "風扇達到最高轉速的溫度。數值越低散熱越強。必須比起始溫度高出最小間隔。",
        helpApply: "依目前顯示的設定啟動此控制，並取代正在執行的控制。",
        helpReturn: "停止目前的控制，將風扇交還給系統。",
        helpActive: "智慧控制正依這組設定執行。",
        helpResume: "重新啟動、喚醒或重新開啟 App 後自動再次套用此控制。選擇「系統」會關閉它。",
        helpAllow: "風扇控制需要一個受保護的小型輔助程式。macOS 會請你在「登入項目」中允許它。"
    )

    static let zhHK = FanControlFeatureStrings(
        title: "風扇控制",
        hubDescription: "查看目前與目標轉速，並手動或依溫度曲線控制風扇",
        showInPanel: "在面板中顯示風扇控制",
        settingsCaption: "在選單列面板中加入手動轉速與溫度曲線。",
        fanNameFormat: "風扇%d",
        rpmFormat: "%d RPM",
        allowControl: "允許風扇控制",
        approvalCaption: "請在登入項目中允許Vorssaint使用受保護的風扇控制。",
        openSettings: "開啟系統設定",
        noFans: "這部Mac沒有可控制的風扇。",
        unsupported: "這部Mac不支援風扇控制。",
        alreadyControlled: "另一個程序正在控制風扇。請先在那裡恢復系統控制。",
        failed: "無法驗證要求的控制，風扇已恢復系統控制。",
        safetyCaption: "控制會持續到你恢復系統模式。App中斷、Mac睡眠、感測器失效或熱壓力升高時會自動交還系統。",
        safetyStopped: "風扇控制中斷，已恢復系統控制。",
        menuBarTitle: "風扇轉速",
        systemControl: "系統",
        manualControl: "手動",
        customCurve: "曲線",
        adaptiveControl: "智能",
        mode: "控制模式",
        coolingIntensity: "風扇速度",
        currentRPMFormat: "目前 %d RPM",
        targetRPMFormat: "目標 %d RPM",
        applyManual: "套用手動控制",
        applyCurve: "套用風扇曲線",
        applyAdaptive: "啟用智能控制",
        returnToSystem: "使用系統控制",
        temperatureUnavailable: "所選溫度感測器停止回應。風扇控制已恢復系統模式。",
        curveUnavailable: "這部Mac不支援某個所選溫度感測器。",
        sensor: "溫度感測器",
        temperature: "溫度",
        fanSpeed: "風扇速度",
        addPoint: "加入節點",
        addSensor: "加入感測器",
        removePoint: "移除節點",
        removeSensor: "移除感測器",
        curveGraph: "溫度與風扇速度曲線",
        averageSoC: "SoC平均溫度",
        hottestSoC: "SoC最高溫度",
        averageCPU: "CPU平均溫度",
        hottestCPU: "CPU最高溫度",
        hottestGPU: "GPU最高溫度",
        helperUnavailable: "受保護的風扇控制器無法使用。請在登入項目允許 Vorssaint，然後再試一次。",
        resumeAfterRestart: "重新啟動或睡眠後恢復",
        adaptiveRampStartTemperature: "起始溫度",
        adaptiveMaximumTemperature: "滿速溫度",
        adaptiveSweetSpotLevel: "起始轉速",
        adaptiveMaximumLevel: "最高轉速",
        adaptiveProfile: "預設組合",
        adaptiveProfileQuiet: "寧靜",
        adaptiveProfileBalanced: "平衡",
        adaptiveProfilePerformance: "效能",
        adaptiveProfileCustom: "自訂",
        adaptiveAdvanced: "進階",
        adaptiveHotspot: "熱點",
        adaptiveActive: "智能控制運行中",
        applyChanges: "套用變更",
        adaptiveSensitivity: "靈敏度",
        adaptiveSensitivityRelaxed: "平緩",
        adaptiveSensitivityStandard: "標準",
        adaptiveSensitivityResponsive: "迅速",
        helpMode: "系統：由 Mac 內建的風扇邏輯控制。手動：固定轉速。曲線：轉速跟隨你編輯的溫度點。智能：轉速依預設組合自動跟隨溫度。",
        helpManual: "固定轉速，以每個風扇範圍（最低到最高）的百分比設定。會一直維持，直到你修改或回到系統控制。",
        helpCurve: "轉速跟隨你為每個感測器設定的溫度點。有多個感測器時，取要求最高的轉速。",
        helpChart: "橘色：溫度。青色：目前轉速。灰色：目標轉速。虛線標示起始溫度與最高溫度。僅顯示本次智能控制期間的資料。",
        helpProfile: "預設組合。寧靜接近系統的寬鬆行為，平衡較早開始散熱，效能最早、最強力地散熱。修改「進階」中的任一項會變成「自訂」。",
        helpSensitivity: "風扇跟隨溫度變化的快慢。平緩會忽略短暫尖峰並緩慢回落，標準為預設，迅速則更快升速與降速。溫度一旦達到上限溫度，會直接升到最高轉速。",
        helpSweetSpot: "溫度達到起始溫度時使用的轉速，以每個風扇範圍的百分比表示。低於該溫度時，風扇會向最低轉速回落。",
        helpMaximum: "智能控制會使用的最高轉速，以每個風扇範圍的百分比表示。數值越低越寧靜，但高負載時保留的散熱餘量也越少。",
        helpRampStart: "風扇達到起始轉速並開始加速的溫度。數值越高，風扇安靜的時間越長，但 Mac 會運行得更熱。",
        helpMaximumTemperature: "風扇達到最高轉速的溫度。數值越低散熱越強。必須比起始溫度高出最小間隔。",
        helpApply: "依目前顯示的設定啟動此控制，並取代正在執行的控制。",
        helpReturn: "停止目前的控制，將風扇交還給系統。",
        helpActive: "智能控制正依這組設定執行。",
        helpResume: "重新啟動、喚醒或重新開啟 App 後自動再次套用此控制。選擇「系統」會關閉它。",
        helpAllow: "風扇控制需要一個受保護的小型輔助程式。macOS 會請你在「登入項目」中允許它。"
    )
    static let uk = FanControlFeatureStrings(
        title: "Керування вентиляторами",
        hubDescription: "Керуйте вентиляторами вручну або за температурними кривими, бачачи поточні та цільові об/хв",
        showInPanel: "Показувати керування вентиляторами в панелі",
        settingsCaption: "Додає ручні швидкості вентиляторів та температурні криві до панелі на смузі меню.",
        fanNameFormat: "Вентилятор %d",
        rpmFormat: "%d об/хв",
        allowControl: "Дозволити керування вентиляторами",
        approvalCaption: "Дозвольте Vorssaint у розділі «Автозапуск», щоб використовувати захищений контролер вентиляторів.",
        openSettings: "Відкрити Системні параметри",
        noFans: "На цьому Mac немає вентилятора, яким можна керувати.",
        unsupported: "Керування вентиляторами недоступне на цьому Mac.",
        alreadyControlled: "Інший процес керує вентиляторами. Спочатку поверніть його під системне керування.",
        failed: "Вентилятори повернулися під системне керування, оскільки запитане керування не вдалося перевірити.",
        safetyCaption: "Керування залишається активним, поки ви не повернетесь до «Система». Воно повертається автоматично, якщо програма відключається, Mac засинає, датчики дають збій або зростає термічний тиск.",
        safetyStopped: "Повернуто під системне керування, оскільки керування вентиляторами було перервано.",
        menuBarTitle: "Швидкість вентилятора",
        systemControl: "Система",
        manualControl: "Вручну",
        customCurve: "Крива",
        adaptiveControl: "Адаптивний",
        mode: "Режим керування",
        coolingIntensity: "Швидкість вентилятора",
        currentRPMFormat: "Поточні %d об/хв",
        targetRPMFormat: "Цільові %d об/хв",
        applyManual: "Застосувати ручне керування",
        applyCurve: "Застосувати криву вентилятора",
        applyAdaptive: "Застосувати адаптивне керування",
        returnToSystem: "Системне керування",
        temperatureUnavailable: "Обраний датчик температури припинив відповідати. Керування вентиляторами повернуто до «Система».",
        curveUnavailable: "Обраний датчик температури недоступний на цьому Mac.",
        sensor: "Датчик температури",
        temperature: "Температура",
        fanSpeed: "Швидкість вентилятора",
        addPoint: "Додати точку",
        addSensor: "Додати датчик",
        removePoint: "Видалити точку",
        removeSensor: "Видалити датчик",
        curveGraph: "Крива температури та швидкості вентилятора",
        averageSoC: "Середній SoC",
        hottestSoC: "Найгарячіший SoC",
        averageCPU: "Середній CPU",
        hottestCPU: "Найгарячіший CPU",
        hottestGPU: "Найгарячіший GPU",
        helperUnavailable: "Захищений контролер вентиляторів недоступний. Дозвольте Vorssaint у розділі «Автозапуск» і спробуйте знову.",
        resumeAfterRestart: "Відновлювати після перезавантаження або сну",
        adaptiveRampStartTemperature: "Початкова температура",
        adaptiveMaximumTemperature: "Температура максимуму",
        adaptiveSweetSpotLevel: "Початкова швидкість",
        adaptiveMaximumLevel: "Максимальна швидкість",
        adaptiveProfile: "Профіль",
        adaptiveProfileQuiet: "Тихий",
        adaptiveProfileBalanced: "Збалансований",
        adaptiveProfilePerformance: "Продуктивність",
        adaptiveProfileCustom: "Власний",
        adaptiveAdvanced: "Додатково",
        adaptiveHotspot: "Гаряча точка",
        adaptiveActive: "Адаптивне керування працює",
        applyChanges: "Застосувати зміни",
        adaptiveSensitivity: "Чутливість",
        adaptiveSensitivityRelaxed: "Плавна",
        adaptiveSensitivityStandard: "Стандартна",
        adaptiveSensitivityResponsive: "Швидка",
        helpMode: "Система: власна логіка вентиляторів Mac. Вручну: фіксована швидкість. Крива: швидкість слідує за температурними точками, які ви редагуєте. Адаптивний: швидкість автоматично слідує за температурою за профілем.",
        helpManual: "Фіксована швидкість у відсотках від діапазону кожного вентилятора, від мінімуму до максимуму. Зберігається, доки ви її не зміните або не повернетеся до системи.",
        helpCurve: "Швидкість слідує за температурними точками, заданими для кожного датчика. За кількох датчиків застосовується найвища запитана швидкість.",
        helpChart: "Помаранчевий: температура. Блакитний: поточна швидкість. Сірий: цільова швидкість. Пунктир позначає початкову та максимальну температури. Лише поточний адаптивний сеанс.",
        helpProfile: "Готові налаштування. «Тихий» близький до спокійної поведінки системи, «Збалансований» охолоджує раніше, «Продуктивність» охолоджує найраніше й найсильніше. Зміна будь-якого значення в «Додатково» перемикає на «Власний».",
        helpSensitivity: "Як швидко вентилятори слідують за температурою. «Плавна» ігнорує короткі стрибки й повільно знижує швидкість, «Стандартна» є типовою, «Швидка» раніше розганяється й сповільнюється. Якщо температура вже досягла максимального порогу, одразу вмикається максимальна швидкість.",
        helpSweetSpot: "Швидкість у відсотках від діапазону кожного вентилятора, що застосовується, коли температура досягає початкової. Нижче неї вентилятори знижують швидкість до мінімуму.",
        helpMaximum: "Найвища швидкість, яку використовує адаптивне керування, у відсотках від діапазону кожного вентилятора. Менше значення тихіше, але за високого навантаження лишається менший запас охолодження.",
        helpRampStart: "Температура, за якої вентилятори виходять на початкову швидкість і починають розганятися. Чим вона вища, тим довше вентилятори тихі, але Mac сильніше нагрівається.",
        helpMaximumTemperature: "Температура, за якої вентилятори досягають максимальної швидкості. Чим вона нижча, тим сильніше охолодження. Має бути вищою за початкову принаймні на мінімальний інтервал.",
        helpApply: "Запускає це керування з показаними налаштуваннями та замінює вже активне.",
        helpReturn: "Зупиняє поточне керування й повертає вентилятори системі.",
        helpActive: "Адаптивне керування працює саме з цими налаштуваннями.",
        helpResume: "Знову застосовує це керування після перезавантаження, пробудження або повторного відкриття застосунку. Вибір «Система» вимикає його.",
        helpAllow: "Для керування вентиляторами потрібен невеликий захищений помічник. macOS попросить дозволити його в розділі «Автозапуск»."
    )
}
