// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

enum HomeAssistantText: Int, CaseIterable {
    case home, description, tokenHint, url, token, connect, forget, search, visibleEntities, empty, setup
    case connecting, connected, offline, invalidURL, credentials, network, rejected, timeout, keychain, unsupported
    case dashboard, on, off, run, brightness, position, open, close, stop, mode, temperature, low, high, up, down
    case heat, cool, heatCool, auto, dry, fanOnly, unknown, unavailable
    case entitiesPerRow, customName, details, compactOn, compactOff, compactRun
    case extraInfo, firstSensor, secondSensor, none, liveHint
    case rename, originalName
    case connectionSettings, addEntities, entitiesHint
    case pages, createPage, page, pageTitle, deletePage, previousPage, nextPage, pagesHint
    case moveEntity, duplicateEntity, entityOptions
    case defaultColumns, customColumns, fillLastRow, fillLastRowHint
    case selectColor, hue, saturation, applyColor, cancelColor, colorHint
}

struct HomeAssistantStrings {
    let values: [String]
    private init(_ text: String) { values = text.components(separatedBy: "|") }
    subscript(_ key: HomeAssistantText) -> String { values[key.rawValue] }
    func state(_ state: String) -> String {
        switch state {
        case "on": return self[.on]
        case "off": return self[.off]
        case "heat": return self[.heat]
        case "cool": return self[.cool]
        case "heat_cool": return self[.heatCool]
        case "auto": return self[.auto]
        case "dry": return self[.dry]
        case "fan_only": return self[.fanOnly]
        case "unknown": return self[.unknown]
        case "unavailable": return self[.unavailable]
        default: return state
        }
    }
    func error(_ failure: HomeAssistantFailure) -> String {
        switch failure {
        case .invalidURL: return self[.invalidURL]
        case .credentials: return self[.credentials]
        case .network, .protocolError: return self[.network]
        case .rejected: return self[.rejected]
        case .timeout: return self[.timeout]
        case .keychain: return self[.keychain]
        case .unsupported: return self[.unsupported]
        }
    }
    func status(_ connection: HomeAssistantConnection) -> String {
        switch connection {
        case .unconfigured: return self[.setup]
        case .connecting: return self[.connecting]
        case .connected: return self[.connected]
        case .offline: return self[.offline]
        }
    }
    static func localized(_ language: AppLanguage) -> Self {
        switch language {
        case .enUS: return Self("Home Assistant|Control your Home Assistant entities from the Dynamic Island.|Create a long-lived access token in your Home Assistant profile. It is stored in this Mac’s Keychain. Leave blank to keep the saved token.|Server URL|Access token|Connect / Test|Forget connection|Search entities|Visible entities|Choose entities to display in Home Assistant settings.|Configure Home Assistant|Connecting…|Connected|Offline · states may be outdated|Enter the server’s HTTP or HTTPS address without a dashboard path.|Check your Home Assistant access token.|Cannot connect. Check the server and your network or VPN.|Home Assistant rejected the action.|The result is uncertain. States will be refreshed; the action will not be repeated.|Cannot access the token in Keychain.|This entity or action is unavailable.|Open dashboard|On|Off|Run|Brightness|Position|Open|Close|Stop|Mode|Temperature|Minimum|Maximum|Move up|Move down|Heat|Cool|Heat / Cool|Automatic|Dry|Fan only|Unknown|Unavailable|Entities per row|Custom name|Details|On|Off|Run|Additional readings|First sensor|Second sensor|None|Readings update live as Home Assistant reports changes. Choose the sensors to show on each card; device reporting frequency is managed by Home Assistant.|Rename sensor|Use original name|Connection|Add entities|Choose and arrange the cards shown in the island. Customize their names and additional readings below.|Pages|Create page|Page|Page title|Delete page|Previous page|Next page|Create named pages and assign entities to each. Swipe sideways in the island to change pages; scroll to step rows like Explore.|Move|Duplicate|Entity options|Default columns|Custom column count|Fill the last row|Widen cards in an incomplete last row to fill the available width. Applies only to this page.|Choose light color|Hue|Saturation|Apply color|Cancel|Apply sends one color change. If the light is off, it turns on.")
        case .es: return Self("Home Assistant|Controla tus entidades de Home Assistant desde la Dynamic Island.|Crea un token de larga duración en tu perfil de Home Assistant. Se guarda en el llavero de esta Mac. Déjalo vacío para conservar el token guardado.|URL del servidor|Token de acceso|Conectar / Probar|Olvidar conexión|Buscar entidades|Entidades visibles|Elige qué entidades mostrar en los ajustes de Home Assistant.|Configurar Home Assistant|Conectando…|Conectado|Sin conexión · los estados pueden estar desactualizados|Introduce la dirección HTTP o HTTPS del servidor sin la ruta del dashboard.|Revisa tu token de acceso de Home Assistant.|No se puede conectar. Revisa el servidor y tu red o VPN.|Home Assistant rechazó la acción.|El resultado es incierto. Se actualizarán los estados sin repetir la acción.|No se puede acceder al token en el llavero.|Esta entidad o acción no está disponible.|Abrir dashboard|Encendido|Apagado|Ejecutar|Brillo|Posición|Abrir|Cerrar|Detener|Modo|Temperatura|Mínimo|Máximo|Subir|Bajar|Calefacción|Refrigeración|Calefacción / Refrigeración|Automático|Deshumidificación|Solo ventilador|Desconocido|No disponible|Entidades por fila|Nombre personalizado|Detalles|On|Off|Activar|Información adicional|Primer sensor|Segundo sensor|Ninguno|Las lecturas se actualizan en vivo cuando Home Assistant informa cambios. Elige los sensores de cada tarjeta; la frecuencia de medición del dispositivo depende de Home Assistant.|Renombrar sensor|Usar nombre original|Conexión|Agregar entidades|Elige y ordena las tarjetas de la Island. Personaliza sus nombres y la información adicional debajo.|Páginas|Crear página|Página|Título de la página|Eliminar página|Página anterior|Página siguiente|Crea páginas con título y asigna entidades a cada una. Desliza hacia los costados en la Island para cambiar de página; el scroll desplaza filas como en Explorar.|Mover|Duplicar|Opciones de la entidad|Cantidad de columnas por defecto|Cantidad de columnas personalizada|Expandir la última fila|Si la última fila está incompleta, sus tarjetas se ensanchan para ocupar todo el ancho. Solo se aplica a esta página.|Elegir color de la luz|Tono|Saturación|Aplicar color|Cancelar|Aplicar envía un solo cambio de color. Si la luz está apagada, se enciende.")
        case .ptBR: return Self("Home Assistant|Controle suas entidades do Home Assistant pela Dynamic Island.|Crie um token de longa duração no seu perfil do Home Assistant. Ele fica nas Chaves deste Mac. Deixe vazio para manter o token salvo.|URL do servidor|Token de acesso|Conectar / Testar|Esquecer conexão|Buscar entidades|Entidades visíveis|Escolha as entidades para exibir nos ajustes do Home Assistant.|Configurar Home Assistant|Conectando…|Conectado|Offline · estados podem estar desatualizados|Insira o endereço HTTP ou HTTPS do servidor sem o caminho do painel.|Verifique seu token de acesso do Home Assistant.|Não foi possível conectar. Verifique o servidor e sua rede ou VPN.|O Home Assistant rejeitou a ação.|O resultado é incerto. Os estados serão atualizados sem repetir a ação.|Não foi possível acessar o token nas Chaves.|Esta entidade ou ação está indisponível.|Abrir painel|Ligado|Desligado|Executar|Brilho|Posição|Abrir|Fechar|Parar|Modo|Temperatura|Mínimo|Máximo|Mover para cima|Mover para baixo|Aquecer|Resfriar|Aquecer / Resfriar|Automático|Desumidificar|Só ventilador|Desconhecido|Indisponível|Entidades por linha|Nome personalizado|Detalhes|On|Off|Ativar|Informações adicionais|Primeiro sensor|Segundo sensor|Nenhum|As leituras são atualizadas ao vivo quando o Home Assistant informa mudanças. Escolha os sensores de cada cartão; a frequência de leitura do dispositivo é gerenciada pelo Home Assistant.|Renomear sensor|Usar nome original|Conexão|Adicionar entidades|Escolha e organize os cartões da ilha. Personalize os nomes e as leituras adicionais abaixo.|Páginas|Criar página|Página|Título da página|Excluir página|Página anterior|Próxima página|Crie páginas com título e atribua entidades a cada uma. Deslize lateralmente na ilha para trocar páginas; a rolagem move linhas como em Explorar.|Mover|Duplicar|Opções da entidade|Colunas padrão|Quantidade de colunas personalizada|Preencher a última linha|Amplia os cartões de uma última linha incompleta para ocupar toda a largura. Aplica-se apenas a esta página.|Escolher cor da luz|Matiz|Saturação|Aplicar cor|Cancelar|Aplicar envia uma única mudança de cor. Se a luz estiver apagada, ela acende.")
        case .tr: return Self("Home Assistant|Home Assistant varlıklarınızı Dynamic Island’dan yönetin.|Home Assistant profilinizde uzun ömürlü erişim belirteci oluşturun. Bu Mac’in Anahtar Zinciri’nde saklanır. Kayıtlı belirteci korumak için boş bırakın.|Sunucu URL’si|Erişim belirteci|Bağlan / Test et|Bağlantıyı unut|Varlık ara|Görünür varlıklar|Home Assistant ayarlarında gösterilecek varlıkları seçin.|Home Assistant’ı yapılandır|Bağlanıyor…|Bağlandı|Çevrimdışı · durumlar eski olabilir|Pano yolu olmadan sunucunun HTTP veya HTTPS adresini girin.|Home Assistant erişim belirtecinizi kontrol edin.|Bağlanılamıyor. Sunucuyu ve ağınızı veya VPN’i kontrol edin.|Home Assistant işlemi reddetti.|Sonuç belirsiz. Durumlar yenilenecek; işlem tekrarlanmayacak.|Anahtar Zinciri’ndeki belirtece erişilemiyor.|Bu varlık veya işlem kullanılamıyor.|Panoyu aç|Açık|Kapalı|Çalıştır|Parlaklık|Konum|Aç|Kapat|Durdur|Mod|Sıcaklık|En düşük|En yüksek|Yukarı taşı|Aşağı taşı|Isıtma|Soğutma|Isıtma / Soğutma|Otomatik|Nem alma|Yalnızca fan|Bilinmiyor|Kullanılamıyor|Satır başına varlık|Özel ad|Ayrıntılar|Açık|Kapalı|Çalıştır|Ek okumalar|İlk sensör|İkinci sensör|Yok|Home Assistant değişiklik bildirdikçe okumalar canlı güncellenir. Her kartın sensörlerini seçin; cihazların bildirim sıklığını Home Assistant yönetir.|Sensörü yeniden adlandır|Özgün adı kullan|Bağlantı|Varlık ekle|Adada gösterilen kartları seçip sıralayın. Aşağıdan adlarını ve ek okumalarını özelleştirin.|Sayfalar|Sayfa oluştur|Sayfa|Sayfa başlığı|Sayfayı sil|Önceki sayfa|Sonraki sayfa|Adlandırılmış sayfalar oluşturup varlıkları atayın. Sayfa değiştirmek için yana kaydırın; dikey kaydırma Keşfet gibi satırları taşır.|Taşı|Çoğalt|Varlık seçenekleri|Varsayılan sütunlar|Özel sütun sayısı|Son satırı doldur|Eksik son satırdaki kartları mevcut genişliği dolduracak şekilde genişletir. Yalnızca bu sayfaya uygulanır.|Işık rengini seç|Ton|Doygunluk|Rengi uygula|İptal|Uygula tek bir renk değişikliği gönderir. Işık kapalıysa açılır.")
        case .ru: return Self("Home Assistant|Управляйте сущностями Home Assistant из Dynamic Island.|Создайте долгосрочный токен в профиле Home Assistant. Он хранится в Связке ключей этого Mac. Оставьте поле пустым, чтобы сохранить текущий токен.|URL сервера|Токен доступа|Подключить / Проверить|Забыть подключение|Поиск сущностей|Видимые сущности|Выберите отображаемые сущности в настройках Home Assistant.|Настроить Home Assistant|Подключение…|Подключено|Нет связи · состояния могут устареть|Введите HTTP- или HTTPS-адрес сервера без пути к панели.|Проверьте токен доступа Home Assistant.|Не удалось подключиться. Проверьте сервер и сеть или VPN.|Home Assistant отклонил действие.|Результат неизвестен. Состояния обновятся без повторения действия.|Нет доступа к токену в Связке ключей.|Сущность или действие недоступны.|Открыть панель|Включено|Выключено|Запустить|Яркость|Положение|Открыть|Закрыть|Остановить|Режим|Температура|Минимум|Максимум|Выше|Ниже|Обогрев|Охлаждение|Обогрев / Охлаждение|Автоматически|Осушение|Только вентилятор|Неизвестно|Недоступно|Сущностей в строке|Своё название|Подробнее|Вкл.|Выкл.|Пуск|Дополнительные показания|Первый датчик|Второй датчик|Нет|Показания обновляются при получении изменений от Home Assistant. Выберите датчики для каждой карточки; частотой измерений устройств управляет Home Assistant.|Переименовать датчик|Использовать исходное имя|Подключение|Добавить сущности|Выберите и упорядочьте карточки островка. Настройте их названия и дополнительные показания ниже.|Страницы|Создать страницу|Страница|Название страницы|Удалить страницу|Предыдущая страница|Следующая страница|Создайте именованные страницы и назначьте им сущности. Смахивайте вбок для смены страниц; прокрутка перемещает строки как в обзоре.|Переместить|Дублировать|Параметры сущности|Столбцы по умолчанию|Настроить число столбцов|Заполнить последнюю строку|Расширяет карточки неполной последней строки на всю доступную ширину. Только для этой страницы.|Выбрать цвет света|Тон|Насыщенность|Применить цвет|Отмена|Применение отправляет одно изменение цвета. Выключенная лампа включится.")
        case .sk: return Self("Home Assistant|Ovládajte entity Home Assistant z Dynamic Island.|V profile Home Assistant vytvorte dlhodobý prístupový token. Uloží sa do Kľúčenky tohto Macu. Prázdne pole ponechá uložený token.|URL servera|Prístupový token|Pripojiť / Otestovať|Zabudnúť pripojenie|Hľadať entity|Viditeľné entity|Vyberte zobrazované entity v nastaveniach Home Assistant.|Nastaviť Home Assistant|Pripájanie…|Pripojené|Offline · stavy môžu byť zastarané|Zadajte HTTP alebo HTTPS adresu servera bez cesty k panelu.|Skontrolujte prístupový token Home Assistant.|Pripojenie zlyhalo. Skontrolujte server a sieť alebo VPN.|Home Assistant odmietol akciu.|Výsledok je neistý. Stavy sa obnovia bez opakovania akcie.|Token v Kľúčenke nie je dostupný.|Táto entita alebo akcia nie je dostupná.|Otvoriť panel|Zapnuté|Vypnuté|Spustiť|Jas|Poloha|Otvoriť|Zavrieť|Zastaviť|Režim|Teplota|Minimum|Maximum|Posunúť hore|Posunúť dole|Kúrenie|Chladenie|Kúrenie / Chladenie|Automaticky|Odvlhčovanie|Len ventilátor|Neznáme|Nedostupné|Entity na riadok|Vlastný názov|Podrobnosti|Zap.|Vyp.|Spustiť|Ďalšie údaje|Prvý senzor|Druhý senzor|Žiadny|Údaje sa aktualizujú naživo pri zmenách hlásených Home Assistant. Vyberte senzory pre každú kartu; frekvenciu meraní zariadenia spravuje Home Assistant.|Premenovať senzor|Použiť pôvodný názov|Pripojenie|Pridať entity|Vyberte a usporiadajte karty ostrova. Nižšie upravte ich názvy a ďalšie údaje.|Stránky|Vytvoriť stránku|Stránka|Názov stránky|Odstrániť stránku|Predošlá stránka|Ďalšia stránka|Vytvorte pomenované stránky a priraďte im entity. Potiahnutím nabok prepnete stránku; rolovanie posúva riadky ako v prehľade.|Presunúť|Duplikovať|Možnosti entity|Predvolený počet stĺpcov|Vlastný počet stĺpcov|Vyplniť posledný riadok|Rozšíri karty v neúplnom poslednom riadku na celú dostupnú šírku. Platí len pre túto stránku.|Vybrať farbu svetla|Odtieň|Sýtosť|Použiť farbu|Zrušiť|Použitie odošle jednu zmenu farby. Ak je svetlo vypnuté, zapne sa.")
        case .de: return Self("Home Assistant|Steuere deine Home-Assistant-Entitäten über die Dynamic Island.|Erstelle ein langlebiges Zugriffstoken in deinem Home-Assistant-Profil. Es wird im Schlüsselbund dieses Macs gespeichert. Leer lassen, um das gespeicherte Token zu behalten.|Server-URL|Zugriffstoken|Verbinden / Testen|Verbindung vergessen|Entitäten suchen|Sichtbare Entitäten|Wähle anzuzeigende Entitäten in den Home-Assistant-Einstellungen.|Home Assistant einrichten|Verbindung wird hergestellt…|Verbunden|Offline · Zustände können veraltet sein|Gib die HTTP- oder HTTPS-Adresse des Servers ohne Dashboard-Pfad ein.|Prüfe dein Home-Assistant-Zugriffstoken.|Keine Verbindung. Prüfe den Server und dein Netzwerk oder VPN.|Home Assistant hat die Aktion abgelehnt.|Das Ergebnis ist unklar. Zustände werden aktualisiert, die Aktion wird nicht wiederholt.|Kein Zugriff auf das Token im Schlüsselbund.|Diese Entität oder Aktion ist nicht verfügbar.|Dashboard öffnen|Ein|Aus|Ausführen|Helligkeit|Position|Öffnen|Schließen|Stoppen|Modus|Temperatur|Minimum|Maximum|Nach oben|Nach unten|Heizen|Kühlen|Heizen / Kühlen|Automatisch|Entfeuchten|Nur Lüfter|Unbekannt|Nicht verfügbar|Entitäten pro Zeile|Eigener Name|Details|An|Aus|Start|Zusätzliche Messwerte|Erster Sensor|Zweiter Sensor|Keiner|Messwerte werden bei Änderungen durch Home Assistant live aktualisiert. Wähle Sensoren für jede Karte; Home Assistant verwaltet die Meldefrequenz der Geräte.|Sensor umbenennen|Originalnamen verwenden|Verbindung|Entitäten hinzufügen|Wähle und ordne die Karten der Insel. Passe unten ihre Namen und zusätzlichen Messwerte an.|Seiten|Seite erstellen|Seite|Seitentitel|Seite löschen|Vorherige Seite|Nächste Seite|Erstelle benannte Seiten und ordne ihnen Entitäten zu. Wische seitwärts, um Seiten zu wechseln; Scrollen bewegt Zeilen wie in Entdecken.|Verschieben|Duplizieren|Entitätsoptionen|Standardspalten|Eigene Spaltenanzahl|Letzte Zeile ausfüllen|Verbreitert Karten in einer unvollständigen letzten Zeile auf die verfügbare Breite. Gilt nur für diese Seite.|Lichtfarbe wählen|Farbton|Sättigung|Farbe anwenden|Abbrechen|Anwenden sendet eine Farbänderung. Ein ausgeschaltetes Licht wird eingeschaltet.")
        case .fr: return Self("Home Assistant|Contrôlez vos entités Home Assistant depuis la Dynamic Island.|Créez un jeton de longue durée dans votre profil Home Assistant. Il est conservé dans le trousseau de ce Mac. Laissez vide pour garder le jeton enregistré.|URL du serveur|Jeton d’accès|Connecter / Tester|Oublier la connexion|Rechercher des entités|Entités visibles|Choisissez les entités à afficher dans les réglages Home Assistant.|Configurer Home Assistant|Connexion…|Connecté|Hors ligne · les états peuvent être périmés|Saisissez l’adresse HTTP ou HTTPS du serveur sans le chemin du tableau de bord.|Vérifiez votre jeton d’accès Home Assistant.|Connexion impossible. Vérifiez le serveur et votre réseau ou VPN.|Home Assistant a refusé l’action.|Le résultat est incertain. Les états seront actualisés sans répéter l’action.|Impossible d’accéder au jeton dans le trousseau.|Cette entité ou action est indisponible.|Ouvrir le tableau de bord|Allumé|Éteint|Exécuter|Luminosité|Position|Ouvrir|Fermer|Arrêter|Mode|Température|Minimum|Maximum|Monter|Descendre|Chauffage|Refroidissement|Chauffage / Refroidissement|Automatique|Déshumidification|Ventilation seule|Inconnu|Indisponible|Entités par ligne|Nom personnalisé|Détails|On|Off|Lancer|Mesures supplémentaires|Premier capteur|Second capteur|Aucun|Les mesures sont actualisées en direct lorsque Home Assistant signale un changement. Choisissez les capteurs de chaque carte ; leur fréquence de mesure dépend de Home Assistant.|Renommer le capteur|Utiliser le nom original|Connexion|Ajouter des entités|Choisissez et organisez les cartes de l’île. Personnalisez leurs noms et mesures supplémentaires ci-dessous.|Pages|Créer une page|Page|Titre de la page|Supprimer la page|Page précédente|Page suivante|Créez des pages nommées et attribuez-leur des entités. Balayez latéralement pour changer de page ; le défilement déplace les lignes comme dans Explorer.|Déplacer|Dupliquer|Options de l’entité|Colonnes par défaut|Nombre de colonnes personnalisé|Remplir la dernière ligne|Élargit les cartes d’une dernière ligne incomplète sur toute la largeur disponible. S’applique uniquement à cette page.|Choisir la couleur de la lumière|Teinte|Saturation|Appliquer la couleur|Annuler|Appliquer envoie un seul changement de couleur. Une lumière éteinte s’allume.")
        case .it: return Self("Home Assistant|Controlla le entità di Home Assistant dalla Dynamic Island.|Crea un token di lunga durata nel profilo Home Assistant. Viene salvato nel Portachiavi di questo Mac. Lascia vuoto per mantenere il token salvato.|URL del server|Token di accesso|Connetti / Verifica|Dimentica connessione|Cerca entità|Entità visibili|Scegli le entità da mostrare nelle impostazioni di Home Assistant.|Configura Home Assistant|Connessione…|Connesso|Offline · gli stati potrebbero essere obsoleti|Inserisci l’indirizzo HTTP o HTTPS del server senza il percorso del dashboard.|Controlla il token di accesso di Home Assistant.|Impossibile connettersi. Controlla il server e la rete o VPN.|Home Assistant ha rifiutato l’azione.|Il risultato è incerto. Gli stati verranno aggiornati senza ripetere l’azione.|Impossibile accedere al token nel Portachiavi.|Questa entità o azione non è disponibile.|Apri dashboard|Acceso|Spento|Esegui|Luminosità|Posizione|Apri|Chiudi|Ferma|Modalità|Temperatura|Minimo|Massimo|Sposta su|Sposta giù|Riscaldamento|Raffreddamento|Riscaldamento / Raffreddamento|Automatico|Deumidificazione|Solo ventola|Sconosciuto|Non disponibile|Entità per riga|Nome personalizzato|Dettagli|On|Off|Avvia|Letture aggiuntive|Primo sensore|Secondo sensore|Nessuno|Le letture si aggiornano in tempo reale quando Home Assistant segnala cambiamenti. Scegli i sensori per ogni scheda; la frequenza di lettura dipende da Home Assistant.|Rinomina sensore|Usa nome originale|Connessione|Aggiungi entità|Scegli e ordina le schede dell’isola. Personalizza i nomi e le letture aggiuntive qui sotto.|Pagine|Crea pagina|Pagina|Titolo della pagina|Elimina pagina|Pagina precedente|Pagina successiva|Crea pagine con titolo e assegna le entità. Scorri lateralmente per cambiare pagina; lo scorrimento verticale sposta le righe come in Esplora.|Sposta|Duplica|Opzioni dell’entità|Colonne predefinite|Numero di colonne personalizzato|Riempi l’ultima riga|Allarga le schede di un’ultima riga incompleta per occupare tutta la larghezza. Si applica solo a questa pagina.|Scegli il colore della luce|Tonalità|Saturazione|Applica colore|Annulla|Applica invia una sola modifica del colore. Se la luce è spenta, si accende.")
        case .ja: return Self("Home Assistant|Dynamic IslandからHome Assistantのエンティティを操作します。|Home Assistantのプロフィールで長期アクセストークンを作成してください。このMacのキーチェーンに保存されます。空欄にすると保存済みのトークンを使用します。|サーバーURL|アクセストークン|接続 / テスト|接続を削除|エンティティを検索|表示するエンティティ|Home Assistant設定で表示するエンティティを選択してください。|Home Assistantを設定|接続中…|接続済み|オフライン・状態が古い可能性があります|ダッシュボードのパスを含まないサーバーのHTTPまたはHTTPSアドレスを入力してください。|Home Assistantのアクセストークンを確認してください。|接続できません。サーバーとネットワークまたはVPNを確認してください。|Home Assistantが操作を拒否しました。|結果は不明です。状態を更新します。操作は再実行しません。|キーチェーンのトークンにアクセスできません。|このエンティティまたは操作は利用できません。|ダッシュボードを開く|オン|オフ|実行|明るさ|位置|開く|閉じる|停止|モード|温度|最小|最大|上へ移動|下へ移動|暖房|冷房|暖房 / 冷房|自動|除湿|送風のみ|不明|利用不可|行ごとのエンティティ数|カスタム名|詳細|オン|オフ|実行|追加の測定値|1つ目のセンサー|2つ目のセンサー|なし|Home Assistant が変更を通知すると測定値がリアルタイムで更新されます。各カードのセンサーを選択してください。デバイスの報告頻度は Home Assistant が管理します。|センサー名を変更|元の名前を使用|接続|エンティティを追加|アイランドに表示するカードを選択して並べ替えます。以下で名前と追加の測定値を設定できます。|ページ|ページを作成|ページ|ページのタイトル|ページを削除|前のページ|次のページ|名前付きのページを作成してエンティティを割り当てます。横にスワイプしてページを切り替え、縦スクロールでExploreと同じように行を移動します。|移動|複製|エンティティのオプション|既定の列数|列数をカスタマイズ|最後の行を広げる|最後の行が埋まっていない場合、カードを利用可能な幅いっぱいに広げます。このページのみに適用されます。|ライトの色を選択|色相|彩度|色を適用|キャンセル|適用すると色の変更を一度だけ送信します。消灯中のライトは点灯します。")
        case .ko: return Self("Home Assistant|Dynamic Island에서 Home Assistant 엔티티를 제어합니다.|Home Assistant 프로필에서 장기 액세스 토큰을 만드세요. 이 Mac의 키체인에 저장됩니다. 저장된 토큰을 유지하려면 비워 두세요.|서버 URL|액세스 토큰|연결 / 테스트|연결 삭제|엔티티 검색|표시할 엔티티|Home Assistant 설정에서 표시할 엔티티를 선택하세요.|Home Assistant 설정|연결 중…|연결됨|오프라인 · 상태가 오래되었을 수 있습니다|대시보드 경로 없이 서버의 HTTP 또는 HTTPS 주소를 입력하세요.|Home Assistant 액세스 토큰을 확인하세요.|연결할 수 없습니다. 서버와 네트워크 또는 VPN을 확인하세요.|Home Assistant가 작업을 거부했습니다.|결과가 불확실합니다. 작업을 반복하지 않고 상태를 새로 고칩니다.|키체인의 토큰에 접근할 수 없습니다.|이 엔티티 또는 작업을 사용할 수 없습니다.|대시보드 열기|켜짐|꺼짐|실행|밝기|위치|열기|닫기|중지|모드|온도|최소|최대|위로 이동|아래로 이동|난방|냉방|난방 / 냉방|자동|제습|팬만|알 수 없음|사용 불가|행당 엔티티 수|사용자 지정 이름|세부 정보|켜짐|꺼짐|실행|추가 측정값|첫 번째 센서|두 번째 센서|없음|Home Assistant가 변경 사항을 알리면 측정값이 실시간으로 업데이트됩니다. 카드마다 센서를 선택하세요. 기기의 보고 주기는 Home Assistant에서 관리합니다.|센서 이름 변경|원래 이름 사용|연결|엔티티 추가|아일랜드에 표시할 카드를 선택하고 정렬하세요. 아래에서 이름과 추가 측정값을 설정할 수 있습니다.|페이지|페이지 만들기|페이지|페이지 제목|페이지 삭제|이전 페이지|다음 페이지|이름이 있는 페이지를 만들고 엔티티를 지정하세요. 옆으로 쓸어 페이지를 바꾸고, 세로 스크롤로 Explore처럼 행을 이동하세요.|이동|복제|엔티티 옵션|기본 열 수|사용자 지정 열 수|마지막 행 채우기|마지막 행이 불완전하면 카드를 사용 가능한 너비 전체로 넓힙니다. 이 페이지에만 적용됩니다.|조명 색상 선택|색조|채도|색상 적용|취소|적용하면 색상 변경을 한 번 전송합니다. 조명이 꺼져 있으면 켜집니다.")
        case .uk: return Self("Home Assistant|Керуйте сутностями Home Assistant із Dynamic Island.|Створіть довготривалий токен у профілі Home Assistant. Він зберігається у В’язці ключів цього Mac. Залиште поле порожнім, щоб зберегти поточний токен.|URL сервера|Токен доступу|Під’єднати / Перевірити|Забути підключення|Пошук сутностей|Видимі сутності|Виберіть сутності для показу в налаштуваннях Home Assistant.|Налаштувати Home Assistant|Підключення…|Підключено|Немає зв’язку · стани можуть застаріти|Введіть HTTP- або HTTPS-адресу сервера без шляху до панелі.|Перевірте токен доступу Home Assistant.|Не вдалося підключитися. Перевірте сервер і мережу або VPN.|Home Assistant відхилив дію.|Результат невідомий. Стани оновляться без повторення дії.|Немає доступу до токена у В’язці ключів.|Сутність або дія недоступні.|Відкрити панель|Увімкнено|Вимкнено|Запустити|Яскравість|Положення|Відкрити|Закрити|Зупинити|Режим|Температура|Мінімум|Максимум|Вище|Нижче|Обігрів|Охолодження|Обігрів / Охолодження|Автоматично|Осушення|Лише вентилятор|Невідомо|Недоступно|Сутностей у рядку|Власна назва|Докладніше|Увімк.|Вимк.|Пуск|Додаткові показники|Перший датчик|Другий датчик|Немає|Показники оновлюються наживо, коли Home Assistant повідомляє про зміни. Виберіть датчики для кожної картки; частотою вимірювань пристрою керує Home Assistant.|Перейменувати датчик|Використати початкову назву|Підключення|Додати сутності|Виберіть і впорядкуйте картки острівця. Налаштуйте їхні назви та додаткові показники нижче.|Сторінки|Створити сторінку|Сторінка|Назва сторінки|Видалити сторінку|Попередня сторінка|Наступна сторінка|Створіть іменовані сторінки та призначте їм сутності. Гортайте вбік для зміни сторінок; прокручування переміщує рядки як в огляді.|Перемістити|Дублювати|Параметри сутності|Стовпці за замовчуванням|Власна кількість стовпців|Заповнити останній рядок|Розширює картки неповного останнього рядка на всю доступну ширину. Лише для цієї сторінки.|Вибрати колір світла|Тон|Насиченість|Застосувати колір|Скасувати|Застосування надсилає одну зміну кольору. Вимкнена лампа ввімкнеться.")
        case .zhHans: return Self("Home Assistant|从Dynamic Island控制Home Assistant实体。|在Home Assistant个人资料中创建长期访问令牌。令牌保存在此Mac的钥匙串中。留空以保留已保存的令牌。|服务器URL|访问令牌|连接 / 测试|忘记连接|搜索实体|显示的实体|在Home Assistant设置中选择要显示的实体。|配置Home Assistant|正在连接…|已连接|离线 · 状态可能已过时|输入服务器的HTTP或HTTPS地址，不含仪表盘路径。|请检查Home Assistant访问令牌。|无法连接。请检查服务器和网络或VPN。|Home Assistant拒绝了操作。|结果不确定。将刷新状态，不会重复操作。|无法访问钥匙串中的令牌。|此实体或操作不可用。|打开仪表盘|开启|关闭|运行|亮度|位置|打开|关闭|停止|模式|温度|最低|最高|上移|下移|制热|制冷|制热 / 制冷|自动|除湿|仅送风|未知|不可用|每行实体数|自定义名称|详情|开|关|运行|附加读数|第一个传感器|第二个传感器|无|Home Assistant 报告变化时，读数会实时更新。请选择每张卡片的传感器；设备的报告频率由 Home Assistant 管理。|重命名传感器|使用原始名称|连接|添加实体|选择并排列岛上显示的卡片。在下方自定义名称和附加读数。|页面|创建页面|页面|页面标题|删除页面|上一页|下一页|创建命名页面并分配实体。在岛上左右滑动切换页面；垂直滚动像探索页面一样移动整行。|移动|复制|实体选项|默认列数|自定义列数|填满最后一行|最后一行未填满时，将卡片加宽至占满可用宽度。仅适用于此页面。|选择灯光颜色|色相|饱和度|应用颜色|取消|应用会发送一次颜色更改。若灯已关闭，将会开启。")
        case .zhTW: return Self("Home Assistant|從Dynamic Island控制Home Assistant實體。|在Home Assistant個人資料中建立長期存取權杖。權杖儲存在此Mac的鑰匙圈中。留空以保留已儲存的權杖。|伺服器URL|存取權杖|連線 / 測試|忘記連線|搜尋實體|顯示的實體|在Home Assistant設定中選擇要顯示的實體。|設定Home Assistant|連線中…|已連線|離線 · 狀態可能已過時|輸入伺服器的HTTP或HTTPS位址，不含儀表板路徑。|請檢查Home Assistant存取權杖。|無法連線。請檢查伺服器和網路或VPN。|Home Assistant拒絕了操作。|結果不確定。將更新狀態，不會重複操作。|無法存取鑰匙圈中的權杖。|此實體或操作無法使用。|開啟儀表板|開啟|關閉|執行|亮度|位置|開啟|關閉|停止|模式|溫度|最低|最高|上移|下移|暖氣|冷氣|暖氣 / 冷氣|自動|除濕|僅送風|未知|無法使用|每列實體數|自訂名稱|詳細資訊|開|關|執行|額外讀數|第一個感測器|第二個感測器|無|Home Assistant 回報變化時，讀數會即時更新。請選擇每張卡片的感測器；裝置的回報頻率由 Home Assistant 管理。|重新命名感測器|使用原始名稱|連線|新增實體|選擇並排列島上顯示的卡片。在下方自訂名稱和額外讀數。|頁面|建立頁面|頁面|頁面標題|刪除頁面|上一頁|下一頁|建立命名頁面並分配實體。在島上左右滑動切換頁面；垂直捲動像探索頁面一樣移動整列。|移動|複製|實體選項|預設欄數|自訂欄數|填滿最後一列|最後一列未填滿時，將卡片加寬至填滿可用寬度。僅適用於此頁面。|選擇燈光顏色|色相|飽和度|套用顏色|取消|套用會傳送一次顏色變更。若燈已關閉，將會開啟。")
        case .zhHK: return Self("Home Assistant|從Dynamic Island控制Home Assistant實體。|在Home Assistant個人資料中建立長期存取權杖。權杖儲存在此Mac的鑰匙圈中。留空以保留已儲存的權杖。|伺服器URL|存取權杖|連線 / 測試|忘記連線|搜尋實體|顯示的實體|在Home Assistant設定中選擇要顯示的實體。|設定Home Assistant|連線中…|已連線|離線 · 狀態可能已過時|輸入伺服器的HTTP或HTTPS網址，不含儀表板路徑。|請檢查Home Assistant存取權杖。|無法連線。請檢查伺服器和網絡或VPN。|Home Assistant拒絕了操作。|結果不確定。將更新狀態，不會重複操作。|無法存取鑰匙圈中的權杖。|此實體或操作無法使用。|開啟儀表板|開啟|關閉|執行|亮度|位置|開啟|關閉|停止|模式|溫度|最低|最高|上移|下移|暖氣|冷氣|暖氣 / 冷氣|自動|除濕|僅送風|未知|無法使用|每行實體數|自訂名稱|詳細資料|開|關|執行|額外讀數|第一個感應器|第二個感應器|無|Home Assistant 回報變化時，讀數會即時更新。請選擇每張卡片的感應器；裝置的回報頻率由 Home Assistant 管理。|重新命名感應器|使用原本名稱|連線|新增實體|選擇並排列島上顯示的卡片。在下方自訂名稱和額外讀數。|頁面|建立頁面|頁面|頁面標題|刪除頁面|上一頁|下一頁|建立命名頁面並分配實體。在島上左右滑動切換頁面；垂直捲動像探索頁面一樣移動整列。|移動|複製|實體選項|預設欄數|自訂欄數|填滿最後一列|最後一列未填滿時，將卡片加寬至填滿可用寬度。僅適用於此頁面。|選擇燈光顏色|色相|飽和度|套用顏色|取消|套用會傳送一次顏色變更。若燈已關閉，將會開啟。")
        }
    }
}
