// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Strings for the input sounds and the click highlight. Sound names stay in
/// English everywhere, the way instrument and switch names do.
struct InputFeedbackStrings {
    // Input sounds
    let soundsTitle: String
    let soundsCaption: String
    let soundsEnable: String
    let soundsPrivacy: String
    let presetsSection: String
    let presetsCaption: String
    let presetStandard: String
    let presetRecording: String
    let presetQuiet: String
    let presetPlayful: String
    let presetSubtle: String
    let clicksSection: String
    let clicksToggle: String
    let soundLabel: String
    let volumeLabel: String
    let previewButton: String
    let familyDesk: String
    let familyStudio: String
    let familyToybox: String
    let familyTingle: String
    let familyFidget: String
    let familyAnalog: String
    let familyArena: String
    let familySpooky: String
    let familyCustom: String
    let keyboardSection: String
    let keyboardToggle: String
    let keyboardCaption: String
    let modifierKeysToggle: String
    let typingComboToggle: String
    let typingComboCaption: String
    let matchKeyboardButton: String
    let scrollSection: String
    let scrollToggle: String
    let scrollStyleLabel: String
    let extrasSection: String
    let doubleClickToggle: String
    let longPressToggle: String
    let dragToggle: String
    let stereoToggle: String
    let quietSection: String
    let quietMicrophoneToggle: String
    let quietMicrophoneCaption: String
    let quietAppsLabel: String
    let quietAppsCaption: String
    let addAppButton: String
    let removeButton: String
    let noApps: String
    let customSection: String
    let customCaption: String
    let customPress: String
    let customRelease: String
    let customScroll: String
    let chooseFileButton: String
    let importFailed: String
    let notRunningCaption: String
    // Click highlight
    let highlightTitle: String
    let highlightCaption: String
    let rippleSection: String
    let rippleToggle: String
    let styleLabel: String
    let styleRing: String
    let styleDoubleRing: String
    let styleGlow: String
    let styleDot: String
    let sizeLabel: String
    let colorLabel: String
    let onlyWhileRecording: String
    let onlyWhileRecordingCaption: String
    let spotlightSection: String
    let spotlightToggle: String
    let spotlightCaption: String
    let darknessLabel: String
    let sampleButton: String

    func presetName(_ preset: InputFeedbackPreset) -> String {
        switch preset {
        case .standard: return presetStandard
        case .recording: return presetRecording
        case .quiet: return presetQuiet
        case .playful: return presetPlayful
        case .subtle: return presetSubtle
        }
    }

    func familyName(_ family: InputSoundFamily) -> String {
        switch family {
        case .desk: return familyDesk
        case .studio: return familyStudio
        case .toybox: return familyToybox
        case .tingle: return familyTingle
        case .fidget: return familyFidget
        case .analog: return familyAnalog
        case .arena: return familyArena
        case .spooky: return familySpooky
        }
    }

    func customSlotName(_ slot: InputSoundCustomSlot) -> String {
        switch slot {
        case .press: return customPress
        case .release: return customRelease
        case .scroll: return customScroll
        }
    }

    func styleName(_ style: ClickRippleStyle) -> String {
        switch style {
        case .ring: return styleRing
        case .doubleRing: return styleDoubleRing
        case .glow: return styleGlow
        case .dot: return styleDot
        }
    }
}

extension FeatureStrings {
    static func inputFeedback(_ language: AppLanguage) -> InputFeedbackStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension InputFeedbackStrings {
    static let enUS = InputFeedbackStrings(
        soundsTitle: "Click & Key Sounds",
        soundsCaption: "Plays a sound for every click, key press and scroll notch in every app.",
        soundsEnable: "Play input sounds",
        soundsPrivacy: "Only the kind of key is used, never which key. Nothing is recorded, stored or sent, and keys stay silent in password fields.",
        presetsSection: "Presets",
        presetsCaption: "Sets the sounds and the click highlight in one tap.",
        presetStandard: "Default",
        presetRecording: "Recording",
        presetQuiet: "Quiet",
        presetPlayful: "Playful",
        presetSubtle: "Subtle",
        clicksSection: "Clicks",
        clicksToggle: "Click sounds",
        soundLabel: "Sound",
        volumeLabel: "Volume",
        previewButton: "Preview",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Your recordings",
        keyboardSection: "Keyboard",
        keyboardToggle: "Key sounds",
        keyboardCaption: "Space, Return and Delete each sound a little different from letter keys.",
        modifierKeysToggle: "Modifier keys",
        typingComboToggle: "Typing combos",
        typingComboCaption: "A fast, steady rhythm earns a chime that rises one note at a time.",
        matchKeyboardButton: "Match clicks and scrolling to the keyboard",
        scrollSection: "Scrolling",
        scrollToggle: "Scroll ticks",
        scrollStyleLabel: "Style",
        extrasSection: "Extras",
        doubleClickToggle: "Double-click sound",
        longPressToggle: "Long-press sound",
        dragToggle: "Drag and drop sounds",
        stereoToggle: "Stereo follows the pointer",
        quietSection: "Quiet",
        quietMicrophoneToggle: "Quiet while an app uses the microphone",
        quietMicrophoneCaption: "Only checks whether the microphone is in use. It is never opened.",
        quietAppsLabel: "Quiet in these apps",
        quietAppsCaption: "Sounds stay off while one of these apps is in front.",
        addAppButton: "Add App…",
        removeButton: "Remove",
        noApps: "No apps",
        customSection: "Your recordings",
        customCaption: "Use your own press, release and scroll sounds. Files stay on this Mac.",
        customPress: "Press",
        customRelease: "Release",
        customScroll: "Scroll",
        chooseFileButton: "Choose…",
        importFailed: "That file could not be read as audio.",
        notRunningCaption: "Input sounds need Accessibility to hear clicks and keys.",
        highlightTitle: "Click Highlight",
        highlightCaption: "Draws a ripple under clicks and can dim the screen around the pointer, so recordings show where you click.",
        rippleSection: "Ripple",
        rippleToggle: "Show a ripple on clicks",
        styleLabel: "Style",
        styleRing: "Ring",
        styleDoubleRing: "Double ring",
        styleGlow: "Glow",
        styleDot: "Dot",
        sizeLabel: "Size",
        colorLabel: "Color",
        onlyWhileRecording: "Only while recording",
        onlyWhileRecordingCaption: "Follows the screen recorder in this app.",
        spotlightSection: "Spotlight",
        spotlightToggle: "Dim the screen around the pointer",
        spotlightCaption: "Everything except a soft circle around the pointer is dimmed.",
        darknessLabel: "Darkness",
        sampleButton: "Show Sample"
    )

    // TRANSLATIONS-BEGIN
    static let ptBR = InputFeedbackStrings(
        soundsTitle: "Sons de Cliques e Teclas",
        soundsCaption: "Toca um som a cada clique, tecla pressionada e passo da rolagem em qualquer app.",
        soundsEnable: "Tocar sons de entrada",
        soundsPrivacy: "Só o tipo de tecla é usado, nunca qual tecla. Nada é gravado, armazenado ou enviado, e as teclas ficam em silêncio em campos de senha.",
        presetsSection: "Predefinições",
        presetsCaption: "Ajusta os sons e o destaque de cliques com um toque.",
        presetStandard: "Padrão",
        presetRecording: "Gravação",
        presetQuiet: "Silencioso",
        presetPlayful: "Divertido",
        presetSubtle: "Sutil",
        clicksSection: "Cliques",
        clicksToggle: "Sons de clique",
        soundLabel: "Som",
        volumeLabel: "Volume",
        previewButton: "Pré-visualizar",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Suas gravações",
        keyboardSection: "Teclado",
        keyboardToggle: "Sons de teclas",
        keyboardCaption: "Espaço, Return e Delete soam um pouco diferentes das teclas de letras.",
        modifierKeysToggle: "Teclas modificadoras",
        typingComboToggle: "Combos de digitação",
        typingComboCaption: "Um ritmo rápido e constante rende um toque que sobe uma nota por vez.",
        matchKeyboardButton: "Combinar cliques e rolagem com o teclado",
        scrollSection: "Rolagem",
        scrollToggle: "Tiques de rolagem",
        scrollStyleLabel: "Estilo",
        extrasSection: "Extras",
        doubleClickToggle: "Som de clique duplo",
        longPressToggle: "Som de pressionar e segurar",
        dragToggle: "Sons de arrastar e soltar",
        stereoToggle: "Estéreo acompanha o ponteiro",
        quietSection: "Silêncio",
        quietMicrophoneToggle: "Silenciar enquanto um app usa o microfone",
        quietMicrophoneCaption: "Só verifica se o microfone está em uso. Ele nunca é aberto.",
        quietAppsLabel: "Silenciar nestes apps",
        quietAppsCaption: "Os sons ficam desligados enquanto um destes apps estiver em primeiro plano.",
        addAppButton: "Adicionar App…",
        removeButton: "Remover",
        noApps: "Nenhum app",
        customSection: "Suas gravações",
        customCaption: "Use seus próprios sons de pressionar, soltar e rolar. Os arquivos ficam neste Mac.",
        customPress: "Pressionar",
        customRelease: "Soltar",
        customScroll: "Rolar",
        chooseFileButton: "Escolher…",
        importFailed: "Não foi possível ler esse arquivo como áudio.",
        notRunningCaption: "Os sons de entrada precisam de Acessibilidade para ouvir cliques e teclas.",
        highlightTitle: "Destaque de Cliques",
        highlightCaption: "Desenha uma onda sob os cliques e pode escurecer a tela ao redor do ponteiro, para que as gravações mostrem onde você clica.",
        rippleSection: "Onda",
        rippleToggle: "Mostrar uma onda nos cliques",
        styleLabel: "Estilo",
        styleRing: "Anel",
        styleDoubleRing: "Anel duplo",
        styleGlow: "Brilho",
        styleDot: "Ponto",
        sizeLabel: "Tamanho",
        colorLabel: "Cor",
        onlyWhileRecording: "Somente durante a gravação",
        onlyWhileRecordingCaption: "Acompanha o gravador de tela neste app.",
        spotlightSection: "Foco",
        spotlightToggle: "Escurecer a tela ao redor do ponteiro",
        spotlightCaption: "Tudo, exceto um círculo suave ao redor do ponteiro, fica escurecido.",
        darknessLabel: "Escuridão",
        sampleButton: "Mostrar Exemplo"
    )

    static let tr = InputFeedbackStrings(
        soundsTitle: "Tıklama ve Tuş Sesleri",
        soundsCaption: "Her uygulamada her tıklama, tuşa basma ve kaydırma adımı için bir ses çalar.",
        soundsEnable: "Giriş seslerini çal",
        soundsPrivacy: "Yalnızca tuşun türü kullanılır, hangi tuş olduğu asla. Hiçbir şey kaydedilmez, saklanmaz veya gönderilmez; parola alanlarında tuşlar sessiz kalır.",
        presetsSection: "Ön Ayarlar",
        presetsCaption: "Sesleri ve tıklama vurgusunu tek dokunuşla ayarlar.",
        presetStandard: "Varsayılan",
        presetRecording: "Kayıt",
        presetQuiet: "Sessiz",
        presetPlayful: "Eğlenceli",
        presetSubtle: "Hafif",
        clicksSection: "Tıklamalar",
        clicksToggle: "Tıklama sesleri",
        soundLabel: "Ses",
        volumeLabel: "Ses düzeyi",
        previewButton: "Önizle",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Kayıtlarınız",
        keyboardSection: "Klavye",
        keyboardToggle: "Tuş sesleri",
        keyboardCaption: "Boşluk, Return ve Delete harf tuşlarından biraz farklı ses çıkarır.",
        modifierKeysToggle: "Değiştirici tuşlar",
        typingComboToggle: "Yazma kombinasyonları",
        typingComboCaption: "Hızlı ve düzenli bir tempo, her seferinde bir nota yükselen bir çınlama kazandırır.",
        matchKeyboardButton: "Tıklamaları ve kaydırmayı klavyeyle eşleştir",
        scrollSection: "Kaydırma",
        scrollToggle: "Kaydırma tıkları",
        scrollStyleLabel: "Stil",
        extrasSection: "Ekstralar",
        doubleClickToggle: "Çift tıklama sesi",
        longPressToggle: "Uzun basma sesi",
        dragToggle: "Sürükle ve bırak sesleri",
        stereoToggle: "Stereo işaretçiyi izler",
        quietSection: "Sessizlik",
        quietMicrophoneToggle: "Bir uygulama mikrofonu kullanırken sessiz kal",
        quietMicrophoneCaption: "Yalnızca mikrofonun kullanımda olup olmadığını denetler. Mikrofon asla açılmaz.",
        quietAppsLabel: "Bu uygulamalarda sessiz kal",
        quietAppsCaption: "Bu uygulamalardan biri öndeyken sesler kapalı kalır.",
        addAppButton: "Uygulama Ekle…",
        removeButton: "Kaldır",
        noApps: "Uygulama yok",
        customSection: "Kayıtlarınız",
        customCaption: "Kendi basma, bırakma ve kaydırma seslerinizi kullanın. Dosyalar bu Mac’te kalır.",
        customPress: "Basma",
        customRelease: "Bırakma",
        customScroll: "Kaydırma",
        chooseFileButton: "Seç…",
        importFailed: "Bu dosya ses olarak okunamadı.",
        notRunningCaption: "Giriş sesleri, tıklamaları ve tuşları duymak için Erişilebilirlik iznine ihtiyaç duyar.",
        highlightTitle: "Tıklama Vurgusu",
        highlightCaption: "Tıklamaların altına bir dalga çizer ve işaretçinin çevresindeki ekranı karartabilir; böylece kayıtlar nereye tıkladığınızı gösterir.",
        rippleSection: "Dalga",
        rippleToggle: "Tıklamalarda dalga göster",
        styleLabel: "Stil",
        styleRing: "Halka",
        styleDoubleRing: "Çift halka",
        styleGlow: "Parıltı",
        styleDot: "Nokta",
        sizeLabel: "Boyut",
        colorLabel: "Renk",
        onlyWhileRecording: "Yalnızca kayıt sırasında",
        onlyWhileRecordingCaption: "Bu uygulamadaki ekran kaydını izler.",
        spotlightSection: "Spot Işığı",
        spotlightToggle: "İşaretçinin çevresindeki ekranı karart",
        spotlightCaption: "İşaretçinin çevresindeki yumuşak bir daire dışında her şey karartılır.",
        darknessLabel: "Karanlık",
        sampleButton: "Örnek Göster"
    )

    static let ru = InputFeedbackStrings(
        soundsTitle: "Звуки кликов и клавиш",
        soundsCaption: "Воспроизводит звук при каждом клике, нажатии клавиши и шаге прокрутки в любом приложении.",
        soundsEnable: "Воспроизводить звуки ввода",
        soundsPrivacy: "Используется только тип клавиши, но не сама клавиша. Ничего не записывается, не сохраняется и не отправляется, а в полях пароля клавиши молчат.",
        presetsSection: "Наборы",
        presetsCaption: "Настраивает звуки и подсветку кликов одним касанием.",
        presetStandard: "По умолчанию",
        presetRecording: "Запись",
        presetQuiet: "Тихий",
        presetPlayful: "Игривый",
        presetSubtle: "Деликатный",
        clicksSection: "Клики",
        clicksToggle: "Звуки кликов",
        soundLabel: "Звук",
        volumeLabel: "Громкость",
        previewButton: "Прослушать",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Ваши записи",
        keyboardSection: "Клавиатура",
        keyboardToggle: "Звуки клавиш",
        keyboardCaption: "Пробел, Return и Delete звучат немного иначе, чем буквенные клавиши.",
        modifierKeysToggle: "Клавиши-модификаторы",
        typingComboToggle: "Комбо при наборе",
        typingComboCaption: "Быстрый и ровный ритм вознаграждается перезвоном, который поднимается на одну ноту.",
        matchKeyboardButton: "Подобрать клики и прокрутку под клавиатуру",
        scrollSection: "Прокрутка",
        scrollToggle: "Щелчки прокрутки",
        scrollStyleLabel: "Стиль",
        extrasSection: "Дополнительно",
        doubleClickToggle: "Звук двойного клика",
        longPressToggle: "Звук долгого нажатия",
        dragToggle: "Звуки перетаскивания",
        stereoToggle: "Стерео следует за указателем",
        quietSection: "Тишина",
        quietMicrophoneToggle: "Молчать, пока приложение использует микрофон",
        quietMicrophoneCaption: "Проверяется только, используется ли микрофон. Он никогда не включается.",
        quietAppsLabel: "Молчать в этих приложениях",
        quietAppsCaption: "Звуки не воспроизводятся, пока одно из этих приложений на переднем плане.",
        addAppButton: "Добавить приложение…",
        removeButton: "Удалить",
        noApps: "Нет приложений",
        customSection: "Ваши записи",
        customCaption: "Используйте собственные звуки нажатия, отпускания и прокрутки. Файлы остаются на этом Mac.",
        customPress: "Нажатие",
        customRelease: "Отпускание",
        customScroll: "Прокрутка",
        chooseFileButton: "Выбрать…",
        importFailed: "Не удалось прочитать этот файл как аудио.",
        notRunningCaption: "Для звуков ввода нужен доступ к разделу «Универсальный доступ», чтобы слышать клики и клавиши.",
        highlightTitle: "Подсветка кликов",
        highlightCaption: "Рисует волну под кликами и может затемнять экран вокруг указателя, чтобы на записях было видно, куда вы кликаете.",
        rippleSection: "Волна",
        rippleToggle: "Показывать волну при кликах",
        styleLabel: "Стиль",
        styleRing: "Кольцо",
        styleDoubleRing: "Двойное кольцо",
        styleGlow: "Свечение",
        styleDot: "Точка",
        sizeLabel: "Размер",
        colorLabel: "Цвет",
        onlyWhileRecording: "Только во время записи",
        onlyWhileRecordingCaption: "Следует за записью экрана в этом приложении.",
        spotlightSection: "Прожектор",
        spotlightToggle: "Затемнять экран вокруг указателя",
        spotlightCaption: "Всё, кроме мягкого круга вокруг указателя, затемняется.",
        darknessLabel: "Затемнение",
        sampleButton: "Показать пример"
    )

    static let es = InputFeedbackStrings(
        soundsTitle: "Sonidos de clics y teclas",
        soundsCaption: "Reproduce un sonido con cada clic, pulsación de tecla y paso de desplazamiento en cualquier app.",
        soundsEnable: "Reproducir sonidos de entrada",
        soundsPrivacy: "Solo se usa el tipo de tecla, nunca cuál es. No se graba, almacena ni envía nada, y las teclas permanecen en silencio en los campos de contraseña.",
        presetsSection: "Ajustes predefinidos",
        presetsCaption: "Configura los sonidos y el resaltado de clics con un toque.",
        presetStandard: "Predeterminado",
        presetRecording: "Grabación",
        presetQuiet: "Silencioso",
        presetPlayful: "Divertido",
        presetSubtle: "Sutil",
        clicksSection: "Clics",
        clicksToggle: "Sonidos de clic",
        soundLabel: "Sonido",
        volumeLabel: "Volumen",
        previewButton: "Previsualizar",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Tus grabaciones",
        keyboardSection: "Teclado",
        keyboardToggle: "Sonidos de teclas",
        keyboardCaption: "Espacio, Return y Delete suenan un poco distinto a las teclas de letras.",
        modifierKeysToggle: "Teclas modificadoras",
        typingComboToggle: "Combos al escribir",
        typingComboCaption: "Un ritmo rápido y constante se premia con un campanilleo que sube una nota cada vez.",
        matchKeyboardButton: "Ajustar clics y desplazamiento al teclado",
        scrollSection: "Desplazamiento",
        scrollToggle: "Chasquidos de desplazamiento",
        scrollStyleLabel: "Estilo",
        extrasSection: "Extras",
        doubleClickToggle: "Sonido de doble clic",
        longPressToggle: "Sonido de pulsación larga",
        dragToggle: "Sonidos de arrastrar y soltar",
        stereoToggle: "El estéreo sigue al puntero",
        quietSection: "Silencio",
        quietMicrophoneToggle: "Silenciar mientras una app usa el micrófono",
        quietMicrophoneCaption: "Solo comprueba si el micrófono está en uso. Nunca se abre.",
        quietAppsLabel: "Silenciar en estas apps",
        quietAppsCaption: "Los sonidos se desactivan mientras una de estas apps esté en primer plano.",
        addAppButton: "Añadir app…",
        removeButton: "Quitar",
        noApps: "Ninguna app",
        customSection: "Tus grabaciones",
        customCaption: "Usa tus propios sonidos de pulsar, soltar y desplazar. Los archivos permanecen en este Mac.",
        customPress: "Pulsar",
        customRelease: "Soltar",
        customScroll: "Desplazar",
        chooseFileButton: "Elegir…",
        importFailed: "No se pudo leer ese archivo como audio.",
        notRunningCaption: "Los sonidos de entrada necesitan Accesibilidad para oír los clics y las teclas.",
        highlightTitle: "Resaltado de clics",
        highlightCaption: "Dibuja una onda bajo los clics y puede oscurecer la pantalla alrededor del puntero, para que las grabaciones muestren dónde haces clic.",
        rippleSection: "Onda",
        rippleToggle: "Mostrar una onda al hacer clic",
        styleLabel: "Estilo",
        styleRing: "Anillo",
        styleDoubleRing: "Anillo doble",
        styleGlow: "Resplandor",
        styleDot: "Punto",
        sizeLabel: "Tamaño",
        colorLabel: "Color",
        onlyWhileRecording: "Solo al grabar",
        onlyWhileRecordingCaption: "Sigue al grabador de pantalla de esta app.",
        spotlightSection: "Foco",
        spotlightToggle: "Oscurecer la pantalla alrededor del puntero",
        spotlightCaption: "Todo se oscurece, salvo un círculo suave alrededor del puntero.",
        darknessLabel: "Oscuridad",
        sampleButton: "Mostrar ejemplo"
    )

    static let sk = InputFeedbackStrings(
        soundsTitle: "Zvuky kliknutí a klávesov",
        soundsCaption: "Prehráva zvuk pri každom kliknutí, stlačení klávesu a kroku posúvania v každej aplikácii.",
        soundsEnable: "Prehrávať zvuky vstupu",
        soundsPrivacy: "Používa sa iba typ klávesu, nikdy nie to, ktorý kláves to je. Nič sa nenahráva, neukladá ani neodosiela a klávesy v poliach pre heslá zostávajú tiché.",
        presetsSection: "Predvoľby",
        presetsCaption: "Nastaví zvuky a zvýraznenie kliknutí jedným ťuknutím.",
        presetStandard: "Predvolené",
        presetRecording: "Nahrávanie",
        presetQuiet: "Tiché",
        presetPlayful: "Hravé",
        presetSubtle: "Jemné",
        clicksSection: "Kliknutia",
        clicksToggle: "Zvuky kliknutí",
        soundLabel: "Zvuk",
        volumeLabel: "Hlasitosť",
        previewButton: "Ukážka",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Vaše nahrávky",
        keyboardSection: "Klávesnica",
        keyboardToggle: "Zvuky klávesov",
        keyboardCaption: "Medzerník, Return a Delete znejú trochu inak ako klávesy s písmenami.",
        modifierKeysToggle: "Modifikačné klávesy",
        typingComboToggle: "Kombá pri písaní",
        typingComboCaption: "Rýchly a rovnomerný rytmus odmení zvonenie, ktoré stúpa o jeden tón.",
        matchKeyboardButton: "Prispôsobiť kliknutia a posúvanie klávesnici",
        scrollSection: "Posúvanie",
        scrollToggle: "Cvaknutia posúvania",
        scrollStyleLabel: "Štýl",
        extrasSection: "Doplnky",
        doubleClickToggle: "Zvuk dvojitého kliknutia",
        longPressToggle: "Zvuk dlhého stlačenia",
        dragToggle: "Zvuky presúvania",
        stereoToggle: "Stereo sleduje ukazovateľ",
        quietSection: "Ticho",
        quietMicrophoneToggle: "Mlčať, kým aplikácia používa mikrofón",
        quietMicrophoneCaption: "Len zisťuje, či sa mikrofón používa. Nikdy sa neotvára.",
        quietAppsLabel: "Mlčať v týchto aplikáciách",
        quietAppsCaption: "Zvuky sú vypnuté, kým je jedna z týchto aplikácií v popredí.",
        addAppButton: "Pridať aplikáciu…",
        removeButton: "Odstrániť",
        noApps: "Žiadne aplikácie",
        customSection: "Vaše nahrávky",
        customCaption: "Použite vlastné zvuky stlačenia, uvoľnenia a posúvania. Súbory zostávajú v tomto Macu.",
        customPress: "Stlačenie",
        customRelease: "Uvoľnenie",
        customScroll: "Posúvanie",
        chooseFileButton: "Vybrať…",
        importFailed: "Tento súbor sa nepodarilo prečítať ako zvuk.",
        notRunningCaption: "Zvuky vstupu potrebujú Prístupnosť, aby počuli kliknutia a klávesy.",
        highlightTitle: "Zvýraznenie kliknutí",
        highlightCaption: "Vykresľuje vlnu pod kliknutiami a dokáže stmaviť obrazovku okolo ukazovateľa, aby nahrávky ukazovali, kam klikáte.",
        rippleSection: "Vlna",
        rippleToggle: "Zobrazovať vlnu pri kliknutiach",
        styleLabel: "Štýl",
        styleRing: "Kruh",
        styleDoubleRing: "Dvojitý kruh",
        styleGlow: "Žiara",
        styleDot: "Bodka",
        sizeLabel: "Veľkosť",
        colorLabel: "Farba",
        onlyWhileRecording: "Iba počas nahrávania",
        onlyWhileRecordingCaption: "Sleduje nahrávanie obrazovky v tejto aplikácii.",
        spotlightSection: "Reflektor",
        spotlightToggle: "Stmaviť obrazovku okolo ukazovateľa",
        spotlightCaption: "Všetko okrem jemného kruhu okolo ukazovateľa sa stmaví.",
        darknessLabel: "Tmavosť",
        sampleButton: "Zobraziť ukážku"
    )

    static let de = InputFeedbackStrings(
        soundsTitle: "Klick- und Tastentöne",
        soundsCaption: "Spielt für jeden Klick, Tastendruck und Scroll-Schritt in jeder App einen Ton ab.",
        soundsEnable: "Eingabetöne abspielen",
        soundsPrivacy: "Es wird nur die Art der Taste verwendet, nie welche Taste. Nichts wird aufgezeichnet, gespeichert oder gesendet, und in Passwortfeldern bleiben Tasten stumm.",
        presetsSection: "Voreinstellungen",
        presetsCaption: "Stellt Töne und Klick-Hervorhebung mit einem Tipp ein.",
        presetStandard: "Standard",
        presetRecording: "Aufnahme",
        presetQuiet: "Leise",
        presetPlayful: "Verspielt",
        presetSubtle: "Dezent",
        clicksSection: "Klicks",
        clicksToggle: "Klicktöne",
        soundLabel: "Ton",
        volumeLabel: "Lautstärke",
        previewButton: "Vorhören",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Eigene Aufnahmen",
        keyboardSection: "Tastatur",
        keyboardToggle: "Tastentöne",
        keyboardCaption: "Leertaste, Return und Delete klingen etwas anders als Buchstabentasten.",
        modifierKeysToggle: "Sondertasten",
        typingComboToggle: "Tipp-Kombos",
        typingComboCaption: "Ein schneller, gleichmäßiger Rhythmus wird mit einem Klingeln belohnt, das Note für Note steigt.",
        matchKeyboardButton: "Klicks und Scrollen an die Tastatur anpassen",
        scrollSection: "Scrollen",
        scrollToggle: "Scroll-Ticks",
        scrollStyleLabel: "Stil",
        extrasSection: "Extras",
        doubleClickToggle: "Doppelklickton",
        longPressToggle: "Ton für langes Drücken",
        dragToggle: "Ziehen-und-Ablegen-Töne",
        stereoToggle: "Stereo folgt dem Zeiger",
        quietSection: "Ruhe",
        quietMicrophoneToggle: "Leise, während eine App das Mikrofon verwendet",
        quietMicrophoneCaption: "Prüft nur, ob das Mikrofon verwendet wird. Es wird nie geöffnet.",
        quietAppsLabel: "Leise in diesen Apps",
        quietAppsCaption: "Solange eine dieser Apps im Vordergrund ist, bleiben die Töne aus.",
        addAppButton: "App hinzufügen …",
        removeButton: "Entfernen",
        noApps: "Keine Apps",
        customSection: "Eigene Aufnahmen",
        customCaption: "Verwende eigene Töne für Drücken, Loslassen und Scrollen. Die Dateien bleiben auf diesem Mac.",
        customPress: "Drücken",
        customRelease: "Loslassen",
        customScroll: "Scrollen",
        chooseFileButton: "Auswählen …",
        importFailed: "Diese Datei konnte nicht als Audio gelesen werden.",
        notRunningCaption: "Eingabetöne benötigen Bedienungshilfen, um Klicks und Tasten zu hören.",
        highlightTitle: "Klick-Hervorhebung",
        highlightCaption: "Zeichnet eine Welle unter Klicks und kann den Bildschirm um den Zeiger abdunkeln, damit Aufnahmen zeigen, wo du klickst.",
        rippleSection: "Welle",
        rippleToggle: "Welle bei Klicks anzeigen",
        styleLabel: "Stil",
        styleRing: "Ring",
        styleDoubleRing: "Doppelring",
        styleGlow: "Leuchten",
        styleDot: "Punkt",
        sizeLabel: "Größe",
        colorLabel: "Farbe",
        onlyWhileRecording: "Nur während der Aufnahme",
        onlyWhileRecordingCaption: "Folgt der Bildschirmaufnahme in dieser App.",
        spotlightSection: "Spotlight",
        spotlightToggle: "Bildschirm um den Zeiger abdunkeln",
        spotlightCaption: "Alles außer einem weichen Kreis um den Zeiger wird abgedunkelt.",
        darknessLabel: "Abdunklung",
        sampleButton: "Beispiel zeigen"
    )

    static let fr = InputFeedbackStrings(
        soundsTitle: "Sons des clics et des touches",
        soundsCaption: "Joue un son à chaque clic, appui sur une touche et cran de défilement dans toutes les apps.",
        soundsEnable: "Jouer les sons de saisie",
        soundsPrivacy: "Seul le type de touche est utilisé, jamais la touche elle-même. Rien n’est enregistré, stocké ni envoyé, et les touches restent silencieuses dans les champs de mot de passe.",
        presetsSection: "Préréglages",
        presetsCaption: "Règle les sons et la mise en évidence des clics en un geste.",
        presetStandard: "Par défaut",
        presetRecording: "Enregistrement",
        presetQuiet: "Discret",
        presetPlayful: "Ludique",
        presetSubtle: "Subtil",
        clicksSection: "Clics",
        clicksToggle: "Sons de clic",
        soundLabel: "Son",
        volumeLabel: "Volume",
        previewButton: "Aperçu",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Vos enregistrements",
        keyboardSection: "Clavier",
        keyboardToggle: "Sons des touches",
        keyboardCaption: "Espace, Retour et Suppr. sonnent un peu différemment des touches de lettres.",
        modifierKeysToggle: "Touches de modification",
        typingComboToggle: "Combos de frappe",
        typingComboCaption: "Un rythme rapide et régulier est récompensé par un carillon qui monte d’une note à la fois.",
        matchKeyboardButton: "Accorder les clics et le défilement au clavier",
        scrollSection: "Défilement",
        scrollToggle: "Crans de défilement",
        scrollStyleLabel: "Style",
        extrasSection: "Extras",
        doubleClickToggle: "Son du double-clic",
        longPressToggle: "Son de l’appui prolongé",
        dragToggle: "Sons du glisser-déposer",
        stereoToggle: "La stéréo suit le pointeur",
        quietSection: "Silence",
        quietMicrophoneToggle: "Silence quand une app utilise le micro",
        quietMicrophoneCaption: "Vérifie seulement si le micro est utilisé. Il n’est jamais ouvert.",
        quietAppsLabel: "Silence dans ces apps",
        quietAppsCaption: "Les sons restent coupés tant qu’une de ces apps est au premier plan.",
        addAppButton: "Ajouter une app…",
        removeButton: "Retirer",
        noApps: "Aucune app",
        customSection: "Vos enregistrements",
        customCaption: "Utilisez vos propres sons d’appui, de relâchement et de défilement. Les fichiers restent sur ce Mac.",
        customPress: "Appui",
        customRelease: "Relâchement",
        customScroll: "Défilement",
        chooseFileButton: "Choisir…",
        importFailed: "Ce fichier n’a pas pu être lu comme audio.",
        notRunningCaption: "Les sons de saisie ont besoin d’Accessibilité pour entendre les clics et les touches.",
        highlightTitle: "Mise en évidence des clics",
        highlightCaption: "Dessine une onde sous les clics et peut assombrir l’écran autour du pointeur, pour que les enregistrements montrent où vous cliquez.",
        rippleSection: "Onde",
        rippleToggle: "Afficher une onde lors des clics",
        styleLabel: "Style",
        styleRing: "Anneau",
        styleDoubleRing: "Double anneau",
        styleGlow: "Halo",
        styleDot: "Point",
        sizeLabel: "Taille",
        colorLabel: "Couleur",
        onlyWhileRecording: "Uniquement pendant l’enregistrement",
        onlyWhileRecordingCaption: "Suit l’enregistreur d’écran de cette app.",
        spotlightSection: "Projecteur",
        spotlightToggle: "Assombrir l’écran autour du pointeur",
        spotlightCaption: "Tout est assombri, sauf un cercle doux autour du pointeur.",
        darknessLabel: "Obscurité",
        sampleButton: "Afficher un exemple"
    )

    static let it = InputFeedbackStrings(
        soundsTitle: "Suoni di clic e tasti",
        soundsCaption: "Riproduce un suono a ogni clic, pressione di un tasto e scatto di scorrimento in ogni app.",
        soundsEnable: "Riproduci i suoni di input",
        soundsPrivacy: "Viene usato solo il tipo di tasto, mai quale tasto. Nulla viene registrato, memorizzato o inviato, e i tasti restano silenziosi nei campi password.",
        presetsSection: "Preset",
        presetsCaption: "Imposta i suoni e l’evidenziazione dei clic con un tocco.",
        presetStandard: "Predefinito",
        presetRecording: "Registrazione",
        presetQuiet: "Silenzioso",
        presetPlayful: "Giocoso",
        presetSubtle: "Discreto",
        clicksSection: "Clic",
        clicksToggle: "Suoni dei clic",
        soundLabel: "Suono",
        volumeLabel: "Volume",
        previewButton: "Anteprima",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Le tue registrazioni",
        keyboardSection: "Tastiera",
        keyboardToggle: "Suoni dei tasti",
        keyboardCaption: "Spazio, Invio e Elimina suonano un po’ diversi dai tasti delle lettere.",
        modifierKeysToggle: "Tasti modificatori",
        typingComboToggle: "Combo di digitazione",
        typingComboCaption: "Un ritmo veloce e costante è premiato con un tintinnio che sale di una nota alla volta.",
        matchKeyboardButton: "Adatta clic e scorrimento alla tastiera",
        scrollSection: "Scorrimento",
        scrollToggle: "Scatti di scorrimento",
        scrollStyleLabel: "Stile",
        extrasSection: "Extra",
        doubleClickToggle: "Suono del doppio clic",
        longPressToggle: "Suono della pressione prolungata",
        dragToggle: "Suoni di trascinamento",
        stereoToggle: "Lo stereo segue il puntatore",
        quietSection: "Silenzio",
        quietMicrophoneToggle: "Silenzio mentre un’app usa il microfono",
        quietMicrophoneCaption: "Controlla solo se il microfono è in uso. Non viene mai aperto.",
        quietAppsLabel: "Silenzio in queste app",
        quietAppsCaption: "I suoni restano disattivati mentre una di queste app è in primo piano.",
        addAppButton: "Aggiungi app…",
        removeButton: "Rimuovi",
        noApps: "Nessuna app",
        customSection: "Le tue registrazioni",
        customCaption: "Usa i tuoi suoni di pressione, rilascio e scorrimento. I file restano su questo Mac.",
        customPress: "Pressione",
        customRelease: "Rilascio",
        customScroll: "Scorrimento",
        chooseFileButton: "Scegli…",
        importFailed: "Impossibile leggere il file come audio.",
        notRunningCaption: "I suoni di input richiedono Accessibilità per sentire clic e tasti.",
        highlightTitle: "Evidenziazione dei clic",
        highlightCaption: "Disegna un’onda sotto i clic e può oscurare lo schermo attorno al puntatore, così le registrazioni mostrano dove fai clic.",
        rippleSection: "Onda",
        rippleToggle: "Mostra un’onda ai clic",
        styleLabel: "Stile",
        styleRing: "Anello",
        styleDoubleRing: "Doppio anello",
        styleGlow: "Alone",
        styleDot: "Punto",
        sizeLabel: "Dimensione",
        colorLabel: "Colore",
        onlyWhileRecording: "Solo durante la registrazione",
        onlyWhileRecordingCaption: "Segue la registrazione dello schermo in questa app.",
        spotlightSection: "Riflettore",
        spotlightToggle: "Oscura lo schermo attorno al puntatore",
        spotlightCaption: "Tutto, tranne un cerchio morbido attorno al puntatore, viene oscurato.",
        darknessLabel: "Oscurità",
        sampleButton: "Mostra esempio"
    )

    static let ja = InputFeedbackStrings(
        soundsTitle: "クリック音とキー音",
        soundsCaption: "すべてのAppで、クリック、キー入力、スクロールの刻みごとに音を鳴らします。",
        soundsEnable: "入力音を鳴らす",
        soundsPrivacy: "使用するのはキーの種類のみで、どのキーかは分かりません。何も記録、保存、送信されず、パスワード欄ではキー音は鳴りません。",
        presetsSection: "プリセット",
        presetsCaption: "サウンドとクリックハイライトをワンタップで設定します。",
        presetStandard: "デフォルト",
        presetRecording: "収録",
        presetQuiet: "静か",
        presetPlayful: "にぎやか",
        presetSubtle: "控えめ",
        clicksSection: "クリック",
        clicksToggle: "クリック音",
        soundLabel: "サウンド",
        volumeLabel: "音量",
        previewButton: "プレビュー",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "自分の録音",
        keyboardSection: "キーボード",
        keyboardToggle: "キー音",
        keyboardCaption: "スペース、Return、Deleteは文字キーと少し違う音になります。",
        modifierKeysToggle: "修飾キー",
        typingComboToggle: "タイピングコンボ",
        typingComboCaption: "速く安定したリズムで入力すると、1音ずつ上がるチャイムが鳴ります。",
        matchKeyboardButton: "クリックとスクロールをキーボードに合わせる",
        scrollSection: "スクロール",
        scrollToggle: "スクロール音",
        scrollStyleLabel: "スタイル",
        extrasSection: "その他",
        doubleClickToggle: "ダブルクリック音",
        longPressToggle: "長押し音",
        dragToggle: "ドラッグ&ドロップ音",
        stereoToggle: "ステレオでポインタを追従",
        quietSection: "消音",
        quietMicrophoneToggle: "Appがマイクを使用中は消音",
        quietMicrophoneCaption: "マイクが使用中かどうかを確認するだけで、マイクが開かれることはありません。",
        quietAppsLabel: "これらのAppでは消音",
        quietAppsCaption: "これらのアプリが最前面にある間はサウンドを鳴らしません。",
        addAppButton: "Appを追加…",
        removeButton: "削除",
        noApps: "Appなし",
        customSection: "自分の録音",
        customCaption: "押す、離す、スクロールの音に自分の音声を使えます。ファイルはこのMacに保存されます。",
        customPress: "押す",
        customRelease: "離す",
        customScroll: "スクロール",
        chooseFileButton: "選択…",
        importFailed: "このファイルをオーディオとして読み込めませんでした。",
        notRunningCaption: "入力音でクリックやキーを検出するには、アクセシビリティの許可が必要です。",
        highlightTitle: "クリックハイライト",
        highlightCaption: "クリックの下に波紋を描き、ポインタの周囲の画面を暗くできます。収録でクリック位置が分かります。",
        rippleSection: "波紋",
        rippleToggle: "クリック時に波紋を表示",
        styleLabel: "スタイル",
        styleRing: "リング",
        styleDoubleRing: "二重リング",
        styleGlow: "グロー",
        styleDot: "ドット",
        sizeLabel: "サイズ",
        colorLabel: "色",
        onlyWhileRecording: "収録中のみ",
        onlyWhileRecordingCaption: "このAppの画面収録に連動します。",
        spotlightSection: "スポットライト",
        spotlightToggle: "ポインタの周囲の画面を暗くする",
        spotlightCaption: "ポインタの周囲のやわらかい円以外が暗くなります。",
        darknessLabel: "暗さ",
        sampleButton: "サンプルを表示"
    )

    static let ko = InputFeedbackStrings(
        soundsTitle: "클릭 및 키 사운드",
        soundsCaption: "모든 앱에서 클릭, 키 입력, 스크롤 단계마다 소리를 재생합니다.",
        soundsEnable: "입력 사운드 재생",
        soundsPrivacy: "키의 종류만 사용하며 어떤 키인지는 알 수 없습니다. 아무것도 기록, 저장 또는 전송되지 않으며 암호 입력란에서는 키 소리가 나지 않습니다.",
        presetsSection: "프리셋",
        presetsCaption: "사운드와 클릭 강조 표시를 한 번에 설정합니다.",
        presetStandard: "기본",
        presetRecording: "녹화",
        presetQuiet: "조용히",
        presetPlayful: "경쾌하게",
        presetSubtle: "은은하게",
        clicksSection: "클릭",
        clicksToggle: "클릭 사운드",
        soundLabel: "사운드",
        volumeLabel: "볼륨",
        previewButton: "미리 듣기",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "내 녹음",
        keyboardSection: "키보드",
        keyboardToggle: "키 사운드",
        keyboardCaption: "Space, Return, Delete는 문자 키와 조금 다른 소리가 납니다.",
        modifierKeysToggle: "보조 키",
        typingComboToggle: "타이핑 콤보",
        typingComboCaption: "빠르고 꾸준한 리듬으로 입력하면 한 음씩 올라가는 차임이 울립니다.",
        matchKeyboardButton: "클릭과 스크롤을 키보드에 맞추기",
        scrollSection: "스크롤",
        scrollToggle: "스크롤 틱",
        scrollStyleLabel: "스타일",
        extrasSection: "추가 기능",
        doubleClickToggle: "더블 클릭 사운드",
        longPressToggle: "길게 누르기 사운드",
        dragToggle: "드래그 앤 드롭 사운드",
        stereoToggle: "스테레오가 포인터를 따라감",
        quietSection: "무음",
        quietMicrophoneToggle: "앱이 마이크를 사용하는 동안 무음",
        quietMicrophoneCaption: "마이크가 사용 중인지만 확인하며 마이크를 열지는 않습니다.",
        quietAppsLabel: "다음 앱에서 무음",
        quietAppsCaption: "이 앱 중 하나가 앞에 있는 동안에는 소리가 나지 않습니다.",
        addAppButton: "앱 추가…",
        removeButton: "제거",
        noApps: "앱 없음",
        customSection: "내 녹음",
        customCaption: "누르기, 떼기, 스크롤 소리를 직접 사용하세요. 파일은 이 Mac에만 보관됩니다.",
        customPress: "누르기",
        customRelease: "떼기",
        customScroll: "스크롤",
        chooseFileButton: "선택…",
        importFailed: "이 파일을 오디오로 읽을 수 없습니다.",
        notRunningCaption: "입력 사운드가 클릭과 키를 감지하려면 손쉬운 사용 권한이 필요합니다.",
        highlightTitle: "클릭 강조 표시",
        highlightCaption: "클릭 아래에 물결을 그리고 포인터 주변의 화면을 어둡게 할 수 있어, 녹화에서 클릭한 위치가 보입니다.",
        rippleSection: "물결",
        rippleToggle: "클릭 시 물결 표시",
        styleLabel: "스타일",
        styleRing: "링",
        styleDoubleRing: "이중 링",
        styleGlow: "글로우",
        styleDot: "점",
        sizeLabel: "크기",
        colorLabel: "색상",
        onlyWhileRecording: "녹화 중에만",
        onlyWhileRecordingCaption: "이 앱의 화면 녹화를 따라갑니다.",
        spotlightSection: "스포트라이트",
        spotlightToggle: "포인터 주변 화면 어둡게 하기",
        spotlightCaption: "포인터 주변의 부드러운 원을 제외한 나머지가 어두워집니다.",
        darknessLabel: "어둡기",
        sampleButton: "샘플 보기"
    )

    static let zhHans = InputFeedbackStrings(
        soundsTitle: "点击与按键音效",
        soundsCaption: "在所有 App 中，每次点击、按键和滚动刻度都会播放声音。",
        soundsEnable: "播放输入音效",
        soundsPrivacy: "仅使用按键的类型，绝不会知道具体是哪个键。不会记录、存储或发送任何内容，且在密码栏中按键保持静音。",
        presetsSection: "预设",
        presetsCaption: "一键设定音效和点击高亮。",
        presetStandard: "默认",
        presetRecording: "录制",
        presetQuiet: "安静",
        presetPlayful: "活泼",
        presetSubtle: "轻柔",
        clicksSection: "点击",
        clicksToggle: "点击音效",
        soundLabel: "音效",
        volumeLabel: "音量",
        previewButton: "试听",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "我的录音",
        keyboardSection: "键盘",
        keyboardToggle: "按键音效",
        keyboardCaption: "空格、Return 和 Delete 的声音与字母键略有不同。",
        modifierKeysToggle: "修饰键",
        typingComboToggle: "打字连击",
        typingComboCaption: "节奏快速且稳定时，会奏出逐音升高的清脆铃声。",
        matchKeyboardButton: "使点击和滚动与键盘一致",
        scrollSection: "滚动",
        scrollToggle: "滚动刻度音",
        scrollStyleLabel: "样式",
        extrasSection: "其他",
        doubleClickToggle: "双击音效",
        longPressToggle: "长按音效",
        dragToggle: "拖放音效",
        stereoToggle: "立体声跟随指针",
        quietSection: "静音",
        quietMicrophoneToggle: "App 使用麦克风时静音",
        quietMicrophoneCaption: "仅检查麦克风是否正在使用，绝不会打开麦克风。",
        quietAppsLabel: "在这些 App 中静音",
        quietAppsCaption: "这些 App 位于最前面时不播放声音。",
        addAppButton: "添加 App…",
        removeButton: "移除",
        noApps: "无 App",
        customSection: "我的录音",
        customCaption: "使用你自己的按下、松开和滚动音效。文件保留在这台 Mac 上。",
        customPress: "按下",
        customRelease: "松开",
        customScroll: "滚动",
        chooseFileButton: "选取…",
        importFailed: "无法将该文件作为音频读取。",
        notRunningCaption: "输入音效需要“辅助功能”权限才能听到点击和按键。",
        highlightTitle: "点击高亮",
        highlightCaption: "在点击处绘制涟漪，并可将指针周围的屏幕调暗，让录屏显示你点击的位置。",
        rippleSection: "涟漪",
        rippleToggle: "点击时显示涟漪",
        styleLabel: "样式",
        styleRing: "圆环",
        styleDoubleRing: "双圆环",
        styleGlow: "光晕",
        styleDot: "圆点",
        sizeLabel: "大小",
        colorLabel: "颜色",
        onlyWhileRecording: "仅在录制时",
        onlyWhileRecordingCaption: "跟随此 App 中的屏幕录制。",
        spotlightSection: "聚光灯",
        spotlightToggle: "调暗指针周围的屏幕",
        spotlightCaption: "除指针周围的柔和圆形区域外，其余部分都会调暗。",
        darknessLabel: "暗度",
        sampleButton: "显示示例"
    )

    static let zhTW = InputFeedbackStrings(
        soundsTitle: "點按與按鍵音效",
        soundsCaption: "在所有 App 中，每次點按、按鍵和捲動刻度都會播放聲音。",
        soundsEnable: "播放輸入音效",
        soundsPrivacy: "僅使用按鍵的類型，絕不會知道是哪個按鍵。不會記錄、儲存或傳送任何內容，且在密碼欄位中按鍵保持靜音。",
        presetsSection: "預設",
        presetsCaption: "一鍵設定音效與點按強調。",
        presetStandard: "預設值",
        presetRecording: "錄製",
        presetQuiet: "安靜",
        presetPlayful: "活潑",
        presetSubtle: "輕柔",
        clicksSection: "點按",
        clicksToggle: "點按音效",
        soundLabel: "音效",
        volumeLabel: "音量",
        previewButton: "試聽",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "我的錄音",
        keyboardSection: "鍵盤",
        keyboardToggle: "按鍵音效",
        keyboardCaption: "空白鍵、Return 和 Delete 的聲音與字母鍵略有不同。",
        modifierKeysToggle: "修飾鍵",
        typingComboToggle: "打字連擊",
        typingComboCaption: "節奏快速且穩定時，會響起逐音升高的清脆鈴聲。",
        matchKeyboardButton: "讓點按和捲動與鍵盤一致",
        scrollSection: "捲動",
        scrollToggle: "捲動刻度音",
        scrollStyleLabel: "樣式",
        extrasSection: "其他",
        doubleClickToggle: "點按兩下音效",
        longPressToggle: "長按音效",
        dragToggle: "拖放音效",
        stereoToggle: "立體聲跟隨指標",
        quietSection: "靜音",
        quietMicrophoneToggle: "App 使用麥克風時靜音",
        quietMicrophoneCaption: "僅檢查麥克風是否正在使用，絕不會開啟麥克風。",
        quietAppsLabel: "在這些 App 中靜音",
        quietAppsCaption: "這些 App 位於最前方時不會播放聲音。",
        addAppButton: "加入 App…",
        removeButton: "移除",
        noApps: "沒有 App",
        customSection: "我的錄音",
        customCaption: "使用你自己的按下、放開和捲動音效。檔案會保留在這部 Mac 上。",
        customPress: "按下",
        customRelease: "放開",
        customScroll: "捲動",
        chooseFileButton: "選擇…",
        importFailed: "無法將該檔案作為音訊讀取。",
        notRunningCaption: "輸入音效需要「輔助使用」權限才能聽到點按和按鍵。",
        highlightTitle: "點按強調",
        highlightCaption: "在點按處繪製漣漪，並可將指標周圍的螢幕調暗，讓螢幕錄影顯示你點按的位置。",
        rippleSection: "漣漪",
        rippleToggle: "點按時顯示漣漪",
        styleLabel: "樣式",
        styleRing: "圓環",
        styleDoubleRing: "雙圓環",
        styleGlow: "光暈",
        styleDot: "圓點",
        sizeLabel: "大小",
        colorLabel: "顏色",
        onlyWhileRecording: "僅在錄製時",
        onlyWhileRecordingCaption: "跟隨此 App 中的螢幕錄影。",
        spotlightSection: "聚光燈",
        spotlightToggle: "調暗指標周圍的螢幕",
        spotlightCaption: "除指標周圍的柔和圓形區域外，其餘部分都會調暗。",
        darknessLabel: "暗度",
        sampleButton: "顯示範例"
    )

    static let zhHK = InputFeedbackStrings(
        soundsTitle: "點按與按鍵音效",
        soundsCaption: "在所有 App 中，每次點按、按鍵和捲動刻度都會播放聲音。",
        soundsEnable: "播放輸入音效",
        soundsPrivacy: "只會使用按鍵的類型，絕不會知道是哪個按鍵。不會記錄、儲存或傳送任何內容，而且在密碼欄位中按鍵保持靜音。",
        presetsSection: "預設",
        presetsCaption: "一鍵設定音效與點按強調。",
        presetStandard: "預設值",
        presetRecording: "錄製",
        presetQuiet: "安靜",
        presetPlayful: "活潑",
        presetSubtle: "輕柔",
        clicksSection: "點按",
        clicksToggle: "點按音效",
        soundLabel: "音效",
        volumeLabel: "音量",
        previewButton: "試聽",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "我的錄音",
        keyboardSection: "鍵盤",
        keyboardToggle: "按鍵音效",
        keyboardCaption: "空白鍵、Return 和 Delete 的聲音與字母鍵略有不同。",
        modifierKeysToggle: "修飾鍵",
        typingComboToggle: "打字連擊",
        typingComboCaption: "節奏快速而穩定時，會響起逐音升高的清脆鈴聲。",
        matchKeyboardButton: "讓點按和捲動與鍵盤一致",
        scrollSection: "捲動",
        scrollToggle: "捲動刻度音",
        scrollStyleLabel: "樣式",
        extrasSection: "其他",
        doubleClickToggle: "按兩下音效",
        longPressToggle: "長按音效",
        dragToggle: "拖放音效",
        stereoToggle: "立體聲跟隨指標",
        quietSection: "靜音",
        quietMicrophoneToggle: "App 使用咪高峰時靜音",
        quietMicrophoneCaption: "只會檢查咪高峰是否正在使用，絕不會開啟咪高峰。",
        quietAppsLabel: "在這些 App 中靜音",
        quietAppsCaption: "這些 App 位於最前方時不會播放聲音。",
        addAppButton: "加入 App…",
        removeButton: "移除",
        noApps: "沒有 App",
        customSection: "我的錄音",
        customCaption: "使用你自己的按下、放開和捲動音效。檔案會保留在這部 Mac 上。",
        customPress: "按下",
        customRelease: "放開",
        customScroll: "捲動",
        chooseFileButton: "選擇…",
        importFailed: "無法將該檔案作為音訊讀取。",
        notRunningCaption: "輸入音效需要「輔助使用」權限才能聽到點按和按鍵。",
        highlightTitle: "點按強調",
        highlightCaption: "在點按處繪製漣漪，並可將指標周圍的螢幕調暗，讓螢幕錄影顯示你點按的位置。",
        rippleSection: "漣漪",
        rippleToggle: "點按時顯示漣漪",
        styleLabel: "樣式",
        styleRing: "圓環",
        styleDoubleRing: "雙圓環",
        styleGlow: "光暈",
        styleDot: "圓點",
        sizeLabel: "大小",
        colorLabel: "顏色",
        onlyWhileRecording: "只在錄製時",
        onlyWhileRecordingCaption: "跟隨此 App 中的螢幕錄影。",
        spotlightSection: "聚光燈",
        spotlightToggle: "調暗指標周圍的螢幕",
        spotlightCaption: "除指標周圍的柔和圓形區域外，其餘部分都會調暗。",
        darknessLabel: "暗度",
        sampleButton: "顯示範例"
    )

    static let uk = InputFeedbackStrings(
        soundsTitle: "Звуки кліків і клавіш",
        soundsCaption: "Відтворює звук під час кожного кліку, натискання клавіші та кроку прокручування в будь-якій програмі.",
        soundsEnable: "Відтворювати звуки введення",
        soundsPrivacy: "Використовується лише тип клавіші, а не сама клавіша. Нічого не записується, не зберігається і не надсилається, а в полях пароля клавіші мовчать.",
        presetsSection: "Набори",
        presetsCaption: "Налаштовує звуки та підсвічування кліків одним дотиком.",
        presetStandard: "За умовчанням",
        presetRecording: "Запис",
        presetQuiet: "Тихий",
        presetPlayful: "Грайливий",
        presetSubtle: "Делікатний",
        clicksSection: "Кліки",
        clicksToggle: "Звуки кліків",
        soundLabel: "Звук",
        volumeLabel: "Гучність",
        previewButton: "Прослухати",
        familyDesk: "Desk",
        familyStudio: "Studio",
        familyToybox: "Toybox",
        familyTingle: "Tingle",
        familyFidget: "Fidget",
        familyAnalog: "Analog",
        familyArena: "Arena",
        familySpooky: "Spooky",
        familyCustom: "Ваші записи",
        keyboardSection: "Клавіатура",
        keyboardToggle: "Звуки клавіш",
        keyboardCaption: "Пробіл, Return і Delete звучать трохи інакше, ніж літерні клавіші.",
        modifierKeysToggle: "Клавіші-модифікатори",
        typingComboToggle: "Комбо під час набору",
        typingComboCaption: "Швидкий і рівний ритм винагороджується передзвоном, що підіймається на одну ноту.",
        matchKeyboardButton: "Підігнати кліки та прокручування під клавіатуру",
        scrollSection: "Прокручування",
        scrollToggle: "Клацання прокручування",
        scrollStyleLabel: "Стиль",
        extrasSection: "Додатково",
        doubleClickToggle: "Звук подвійного кліку",
        longPressToggle: "Звук довгого натискання",
        dragToggle: "Звуки перетягування",
        stereoToggle: "Стерео слідує за вказівником",
        quietSection: "Тиша",
        quietMicrophoneToggle: "Мовчати, поки програма використовує мікрофон",
        quietMicrophoneCaption: "Лише перевіряє, чи використовується мікрофон. Він ніколи не вмикається.",
        quietAppsLabel: "Мовчати в цих програмах",
        quietAppsCaption: "Звуки не відтворюються, поки одна з цих програм на передньому плані.",
        addAppButton: "Додати програму…",
        removeButton: "Вилучити",
        noApps: "Немає програм",
        customSection: "Ваші записи",
        customCaption: "Використовуйте власні звуки натискання, відпускання та прокручування. Файли залишаються на цьому Mac.",
        customPress: "Натискання",
        customRelease: "Відпускання",
        customScroll: "Прокручування",
        chooseFileButton: "Вибрати…",
        importFailed: "Не вдалося прочитати цей файл як аудіо.",
        notRunningCaption: "Для звуків введення потрібен доступ до розділу «Універсальний доступ», щоб чути кліки та клавіші.",
        highlightTitle: "Підсвічування кліків",
        highlightCaption: "Малює хвилю під кліками та може затемнювати екран навколо вказівника, щоб на записах було видно, куди ви клікаєте.",
        rippleSection: "Хвиля",
        rippleToggle: "Показувати хвилю під час кліків",
        styleLabel: "Стиль",
        styleRing: "Кільце",
        styleDoubleRing: "Подвійне кільце",
        styleGlow: "Сяйво",
        styleDot: "Крапка",
        sizeLabel: "Розмір",
        colorLabel: "Колір",
        onlyWhileRecording: "Лише під час запису",
        onlyWhileRecordingCaption: "Слідує за записом екрана в цій програмі.",
        spotlightSection: "Прожектор",
        spotlightToggle: "Затемнювати екран навколо вказівника",
        spotlightCaption: "Усе, крім м’якого кола навколо вказівника, затемнюється.",
        darknessLabel: "Затемнення",
        sampleButton: "Показати приклад"
    )
    // TRANSLATIONS-END
}
