// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

enum KeyboardRemapStrings {
    private static let languages: [AppLanguage] = [.enUS, .ptBR, .tr, .ru, .es, .sk, .de, .fr, .it, .ja, .ko, .uk, .zhHans, .zhTW, .zhHK]
    private static let table: [String: [String]] = [
        "pageTitle": "Keyboard Remaps|Remapeamento do teclado|Klavye yeniden eşleme|Переназначение клавиш|Reasignación de teclado|Premapovanie klávesnice|Tastaturbelegung|Remappage du clavier|Rimappatura tastiera|キーの割り当て|키보드 재매핑|Перепризначення клавіш|键盘重映射|鍵盤重新對應|鍵盤重新對應".components(separatedBy: "|"),
        "enable": "Enable keyboard remaps|Ativar remapeamento do teclado|Klavye yeniden eşlemeyi etkinleştir|Включить переназначение клавиш|Activar reasignación de teclado|Zapnúť premapovanie klávesnice|Tastaturbelegung aktivieren|Activer le remappage du clavier|Abilita rimappatura tastiera|キーの割り当てを有効にする|키보드 재매핑 활성화|Увімкнути перепризначення клавіш|启用键盘重映射|啟用鍵盤重新對應|啟用鍵盤重新對應".components(separatedBy: "|"),
        "active": "Active now|Ativo agora|Şu anda etkin|Сейчас активно|Activo ahora|Teraz aktívne|Jetzt aktiv|Actif|Attivo ora|動作中|현재 활성화됨|Зараз активно|当前已启用|目前已啟用|目前已啟用".components(separatedBy: "|"),
        "preview": "Current setup preview|Prévia da configuração atual|Geçerli ayar önizlemesi|Предпросмотр текущих настроек|Vista previa de la configuración|Náhľad aktuálneho nastavenia|Vorschau der aktuellen Belegung|Aperçu de la configuration|Anteprima configurazione attuale|現在の設定プレビュー|현재 설정 미리보기|Попередній перегляд налаштувань|当前设置预览|目前設定預覽|目前設定預覽".components(separatedBy: "|"),
        "nextLanguage": "Next input language|Próximo idioma de entrada|Sonraki giriş dili|Следующий язык ввода|Siguiente idioma de entrada|Ďalší jazyk vstupu|Nächste Eingabesprache|Langue de saisie suivante|Lingua di input successiva|次の入力言語|다음 입력 언어|Наступна мова введення|下一个输入语言|下一個輸入語言|下一個輸入語言".components(separatedBy: "|"),
        "toggleCaps": "Toggle Caps Lock|Alternar Caps Lock|Caps Lock değiştir|Переключить Caps Lock|Alternar Caps Lock|Prepnúť Caps Lock|Caps Lock umschalten|Basculer Caps Lock|Attiva/disattiva Caps Lock|Caps Lockを切り替え|Caps Lock 전환|Перемкнути Caps Lock|切换大写锁定|切換大寫鎖定|切換大寫鎖定".components(separatedBy: "|"),
        "doNothing": "Do nothing|Não fazer nada|Hiçbir şey yapma|Ничего не делать|No hacer nada|Nerobiť nič|Keine Aktion|Ne rien faire|Nessuna azione|何もしない|아무 동작 안 함|Нічого не робити|不执行操作|不執行動作|不執行動作".components(separatedBy: "|"),
        "restored": "Mappings are restored when the feature stops or Vorssaint quits.|O mapeamento original é restaurado quando o recurso para ou o Vorssaint sai.|Özellik durduğunda veya Vorssaint kapandığında özgün eşlemeler geri yüklenir.|Исходные назначения восстанавливаются при остановке функции или выходе из Vorssaint.|Se restaura la asignación original cuando se detiene la función o se cierra Vorssaint.|Pôvodné mapovanie sa obnoví po zastavení funkcie alebo ukončení Vorssaint.|Die ursprüngliche Belegung wird wiederhergestellt, wenn die Funktion stoppt oder Vorssaint beendet wird.|Le mappage original est rétabli à l’arrêt de la fonction ou de Vorssaint.|La mappatura originale viene ripristinata quando la funzione si ferma o Vorssaint esce.|機能の停止時やVorssaintの終了時に元の割り当てに戻ります。|기능이 중지되거나 Vorssaint가 종료되면 원래 매핑이 복원됩니다.|Початкові призначення відновлюються після зупинки функції або виходу з Vorssaint.|功能停止或 Vorssaint 退出时会恢复原始映射。|功能停止或 Vorssaint 結束時會還原原始對應。|功能停止或 Vorssaint 結束時會還原原始對應。".components(separatedBy: "|"),
        "inactive": "Preview only — enable keyboard remaps to apply.|Somente prévia — ative o remapeamento para aplicar.|Yalnızca önizleme — uygulamak için klavye eşlemelerini etkinleştirin.|Только предпросмотр — включите переназначение для применения.|Solo vista previa — activa la reasignación para aplicar.|Iba náhľad — zapnite premapovanie na použitie.|Nur Vorschau — zum Anwenden Tastaturbelegung aktivieren.|Aperçu uniquement — activez le remappage pour appliquer.|Solo anteprima — abilita la rimappatura per applicare.|プレビューのみです。適用するにはキーの割り当てを有効にしてください。|미리보기입니다. 적용하려면 키보드 재매핑을 켜세요.|Лише попередній перегляд — увімкніть перепризначення для застосування.|仅预览 — 启用键盘重映射后生效。|僅預覽 — 啟用鍵盤重新對應後生效。|僅預覽 — 啟用鍵盤重新對應後生效。".components(separatedBy: "|"),
        "hubDescription": "Remap keys and shortcuts to keys, shortcuts, or app actions.|Remapeie teclas e atalhos para teclas, atalhos ou ações de apps.|Tuşları ve kısayolları tuşlara, kısayollara veya uygulama eylemlerine eşleyin.|Переназначайте клавиши и сочетания на другие клавиши, сочетания или действия.|Reasigna teclas y atajos a teclas, atajos o acciones de apps.|Premapujte klávesy a skratky na klávesy, skratky alebo akcie aplikácií.|Tasten und Kurzbefehle auf Tasten, Kurzbefehle oder App-Aktionen umlegen.|Remappez touches et raccourcis vers des touches, raccourcis ou actions d’apps.|Rimappa tasti e scorciatoie su tasti, scorciatoie o azioni delle app.|キーやショートカットに別のキー、ショートカット、アプリの動作を割り当てます。|키와 단축키를 다른 키, 단축키 또는 앱 동작으로 매핑합니다.|Перепризначайте клавіші та сполучення на інші клавіші, сполучення або дії.|将按键和快捷键映射为按键、快捷键或应用操作。|將按鍵與快速鍵對應為按鍵、快速鍵或 App 動作。|將按鍵與快捷鍵對應為按鍵、快捷鍵或 App 動作。".components(separatedBy: "|"),
        "permissionStatus": "Allow Accessibility to activate keyboard remaps.|Permita Acessibilidade para ativar o remapeamento.|Klavye eşlemeleri için Erişilebilirlik izni verin.|Разрешите Универсальный доступ для переназначения клавиш.|Permite Accesibilidad para activar la reasignación.|Povoľte Prístupnosť na aktiváciu premapovania.|Bedienungshilfen erlauben, um die Belegung zu aktivieren.|Autorisez l’accessibilité pour activer le remappage.|Consenti Accessibilità per attivare la rimappatura.|キーの割り当てにはアクセシビリティを許可してください。|키보드 재매핑을 위해 손쉬운 사용을 허용하세요.|Дозвольте Доступність для перепризначення клавіш.|允许辅助功能以启用键盘重映射。|允許輔助使用以啟用鍵盤重新對應。|允許輔助使用以啟用鍵盤重新對應。".components(separatedBy: "|"),
        "superkeyStatus": "Paused while Super Key is enabled. Turn it off to use this preset.|Pausado enquanto Super Key está ativo. Desative-o para usar este preset.|Super Key etkinken duraklatıldı. Bu ön ayar için onu kapatın.|Приостановлено, пока включён Super Key. Отключите его для этого набора.|En pausa mientras Super Key está activo. Desactívalo para usar este ajuste.|Pozastavené, kým je zapnutý Super Key. Vypnite ho na použitie tohto nastavenia.|Pausiert, solange Super Key aktiviert ist. Für diese Voreinstellung deaktivieren.|En pause tant que Super Key est actif. Désactivez-le pour utiliser ce préréglage.|In pausa mentre Super Key è attivo. Disattivalo per usare questa configurazione.|Super Keyが有効な間は停止します。このプリセットを使うには無効にしてください。|Super Key가 켜져 있어 일시 중지되었습니다. 이 프리셋을 쓰려면 끄세요.|Призупинено, поки ввімкнено Super Key. Вимкніть його для цього набору.|Super Key 启用期间暂停。停用它以使用此预设。|Super Key 啟用期間暫停。停用它以使用此預設。|Super Key 啟用期間暫停。停用它以使用此預設。".components(separatedBy: "|"),
        "tapStatus": "macOS refused the keyboard event tap. Check Accessibility permission.|O macOS recusou a captura do teclado. Verifique a permissão de Acessibilidade.|macOS klavye olay erişimini reddetti. Erişilebilirlik iznini kontrol edin.|macOS отказала в перехвате клавиатуры. Проверьте Универсальный доступ.|macOS rechazó la captura del teclado. Comprueba el permiso de Accesibilidad.|macOS odmietol zachytávanie klávesnice. Skontrolujte povolenie Prístupnosti.|macOS hat den Tastaturzugriff abgelehnt. Berechtigung für Bedienungshilfen prüfen.|macOS a refusé la capture clavier. Vérifiez l’autorisation d’accessibilité.|macOS ha rifiutato la cattura della tastiera. Controlla il permesso Accessibilità.|macOSがキーイベントの取得を拒否しました。アクセシビリティの許可を確認してください。|macOS가 키보드 이벤트 접근을 거부했습니다. 손쉬운 사용 권한을 확인하세요.|macOS відмовила в перехопленні клавіатури. Перевірте дозвіл Доступності.|macOS 拒绝了键盘事件访问。请检查辅助功能权限。|macOS 拒絕鍵盤事件存取。請檢查輔助使用權限。|macOS 拒絕鍵盤事件存取。請檢查輔助使用權限。".components(separatedBy: "|"),
        "modifierConflict": "macOS modifier remaps overlap these rules. Restore overlapping keys in Keyboard → Keyboard Shortcuts → Modifier Keys, then retry.|Os remapeamentos do macOS sobrepõem estas regras. Restaure as teclas em Teclado → Atalhos de teclado → Teclas modificadoras e tente novamente.|macOS değiştirici eşlemeleri bu kurallarla çakışıyor. Klavye → Klavye Kestirmeleri → Değiştirici Tuşlar bölümünde çakışan tuşları geri yükleyip yeniden deneyin.|Правила пересекаются с настройками macOS. Восстановите клавиши в Клавиатура → Сочетания клавиш → Клавиши модификации и повторите.|Las reasignaciones de macOS coinciden con estas reglas. Restaura las teclas en Teclado → Funciones rápidas → Teclas de modificación y reintenta.|Premapovania macOS sa prekrývajú s pravidlami. Obnovte klávesy v Klávesnica → Klávesové skratky → Modifikačné klávesy a skúste znova.|macOS-Belegungen überschneiden sich mit diesen Regeln. Betroffene Tasten unter Tastatur → Tastaturkurzbefehle → Sondertasten zurücksetzen und erneut versuchen.|Les remappages macOS chevauchent ces règles. Rétablissez les touches dans Clavier → Raccourcis clavier → Touches de modification, puis réessayez.|Le rimappature macOS si sovrappongono alle regole. Ripristina i tasti in Tastiera → Abbreviazioni da tastiera → Tasti modificatori, poi riprova.|macOSの修飾キー設定が競合しています。キーボード → キーボードショートカット → 修飾キーで該当キーを戻し、再試行してください。|macOS 보조 키 설정이 규칙과 겹칩니다. 키보드 → 키보드 단축키 → 보조 키에서 해당 키를 복원한 후 다시 시도하세요.|Правила перетинаються з налаштуваннями macOS. Відновіть клавіші в Клавіатура → Клавіатурні скорочення → Клавіші-модифікатори та повторіть.|macOS 修饰键映射与规则冲突。请在键盘 → 键盘快捷键 → 修饰键中恢复相关按键，然后重试。|macOS 修飾鍵對應與規則衝突。請在鍵盤 → 鍵盤快速鍵 → 修飾鍵中還原相關按鍵，然後重試。|macOS 修飾鍵對應與規則衝突。請在鍵盤 → 鍵盤快捷鍵 → 修飾鍵中還原相關按鍵，然後重試。".components(separatedBy: "|"),
        "keyboardSettings": "Open Keyboard settings|Abrir ajustes de teclado|Klavye ayarlarını aç|Открыть настройки клавиатуры|Abrir ajustes de teclado|Otvoriť nastavenia klávesnice|Tastatureinstellungen öffnen|Ouvrir les réglages du clavier|Apri impostazioni tastiera|キーボード設定を開く|키보드 설정 열기|Відкрити параметри клавіатури|打开键盘设置|開啟鍵盤設定|開啟鍵盤設定".components(separatedBy: "|"),
        "retry": "Retry|Tentar novamente|Yeniden dene|Повторить|Reintentar|Skúsiť znova|Erneut versuchen|Réessayer|Riprova|再試行|다시 시도|Повторити|重试|重試|重試".components(separatedBy: "|"),
        "conflictStatus": "Conflicting keyboard mapping. Disable overlapping Karabiner or macOS modifier remaps.|Mapeamento em conflito. Desative remapeamentos sobrepostos do Karabiner ou macOS.|Klavye eşlemesi çakışıyor. Karabiner veya macOS’te çakışan eşlemeleri kapatın.|Конфликт назначений клавиш. Отключите пересекающиеся правила Karabiner или macOS.|Conflicto de asignación. Desactiva reasignaciones coincidentes de Karabiner o macOS.|Konflikt mapovania. Vypnite prekrývajúce sa premapovania Karabiner alebo macOS.|Konflikt bei der Belegung. Überlappende Karabiner- oder macOS-Belegungen deaktivieren.|Conflit de mappage. Désactivez les remappages Karabiner ou macOS correspondants.|Conflitto di mappatura. Disattiva le rimappature sovrapposte di Karabiner o macOS.|キーの割り当てが競合しています。KarabinerやmacOSの重複する設定を無効にしてください。|키보드 매핑이 충돌합니다. 겹치는 Karabiner 또는 macOS 매핑을 끄세요.|Конфлікт призначень клавіш. Вимкніть відповідні правила Karabiner або macOS.|键盘映射冲突。请停用重叠的 Karabiner 或 macOS 修饰键重映射。|鍵盤對應衝突。請停用重疊的 Karabiner 或 macOS 修飾鍵重新對應。|鍵盤對應衝突。請停用重疊的 Karabiner 或 macOS 修飾鍵重新對應。".components(separatedBy: "|"),
        "recoveryStatus": "Could not start keyboard mapping recovery.|Não foi possível iniciar a recuperação do mapeamento.|Klavye eşleme kurtarması başlatılamadı.|Не удалось запустить восстановление назначений клавиш.|No se pudo iniciar la recuperación de asignación.|Nepodarilo sa spustiť obnovu mapovania klávesnice.|Wiederherstellung der Tastaturbelegung konnte nicht gestartet werden.|Impossible de lancer la restauration du mappage clavier.|Impossibile avviare il ripristino della mappatura.|キー割り当ての復旧処理を開始できませんでした。|키보드 매핑 복구를 시작할 수 없습니다.|Не вдалося запустити відновлення призначень клавіш.|无法启动键盘映射恢复。|無法啟動鍵盤對應復原。|無法啟動鍵盤對應復原。".components(separatedBy: "|"),
        "writeStatus": "macOS did not confirm the mapping. Try disabling other key remappers.|O macOS não confirmou o mapeamento. Tente desativar outros remapeadores.|macOS eşlemeyi doğrulamadı. Diğer tuş eşleyicilerini kapatmayı deneyin.|macOS не подтвердила назначения. Попробуйте отключить другие программы переназначения.|macOS no confirmó la asignación. Prueba a desactivar otros reasignadores.|macOS nepotvrdil mapovanie. Skúste vypnúť iné nástroje na premapovanie.|macOS hat die Belegung nicht bestätigt. Andere Belegungsprogramme deaktivieren.|macOS n’a pas confirmé le mappage. Essayez de désactiver les autres outils de remappage.|macOS non ha confermato la mappatura. Prova a disattivare altri strumenti di rimappatura.|macOSが割り当てを確認できませんでした。他のキー割り当てツールを無効にしてください。|macOS가 매핑을 확인하지 못했습니다. 다른 키 재매핑 도구를 꺼보세요.|macOS не підтвердила призначення. Спробуйте вимкнути інші програми перепризначення.|macOS 未确认映射。请尝试停用其他键盘重映射工具。|macOS 未確認對應。請嘗試停用其他鍵盤重新對應工具。|macOS 未確認對應。請嘗試停用其他鍵盤重新對應工具。".components(separatedBy: "|"),
        "clearStatus": "Could not restore the mapping. Quit other remappers and turn this feature off again to retry.|Não foi possível restaurar o mapeamento. Feche outros remapeadores e desative este recurso novamente.|Eşleme geri yüklenemedi. Diğer eşleyicileri kapatın ve bu özelliği tekrar kapatın.|Не удалось восстановить назначения. Закройте другие программы переназначения и снова выключите эту функцию.|No se pudo restaurar la asignación. Cierra otros reasignadores y desactiva esta función otra vez.|Nepodarilo sa obnoviť mapovanie. Ukončite iné nástroje a znova vypnite túto funkciu.|Belegung konnte nicht wiederhergestellt werden. Andere Belegungsprogramme beenden und diese Funktion erneut ausschalten.|Impossible de rétablir le mappage. Fermez les autres outils puis désactivez à nouveau cette fonction.|Impossibile ripristinare la mappatura. Chiudi gli altri strumenti e disattiva di nuovo questa funzione.|割り当てを元に戻せませんでした。他の割り当てツールを終了し、この機能をもう一度オフにしてください。|매핑을 복원할 수 없습니다. 다른 재매핑 도구를 종료하고 이 기능을 다시 꺼보세요.|Не вдалося відновити призначення. Закрийте інші програми та знову вимкніть цю функцію.|无法恢复映射。请退出其他重映射工具并再次关闭此功能重试。|無法還原對應。請結束其他重新對應工具並再次關閉此功能重試。|無法還原對應。請結束其他重新對應工具並再次關閉此功能重試。".components(separatedBy: "|"),
        "genericNote": "Choose your own keys and actions. New setups start empty.|Escolha suas teclas e ações. Novas configurações começam vazias.|Tuşlarınızı ve eylemlerinizi seçin. Yeni ayarlar boş başlar.|Выберите свои клавиши и действия. Новые настройки пусты.|Elige tus teclas y acciones. Las nuevas configuraciones empiezan vacías.|Vyberte si klávesy a akcie. Nové nastavenia sú prázdne.|Wähle eigene Tasten und Aktionen. Neue Konfigurationen starten leer.|Choisissez vos touches et actions. Les nouvelles configurations sont vides.|Scegli tasti e azioni. Le nuove configurazioni sono vuote.|キーと動作を自由に選べます。初期設定にはルールがありません。|키와 동작을 선택하세요. 새 설정은 비어 있습니다.|Виберіть свої клавіші та дії. Нові налаштування порожні.|自行选择按键和操作。新配置默认为空。|自行選擇按鍵與動作。新設定預設為空。|自行選擇按鍵與動作。新設定預設為空。".components(separatedBy: "|"),
        "keyRules": "Key rules|Regras de teclas|Tuş kuralları|Правила клавиш|Reglas de teclas|Pravidlá klávesov|Tastenregeln|Règles de touches|Regole dei tasti|キーのルール|키 규칙|Правила клавіш|按键规则|按鍵規則|按鍵規則".components(separatedBy: "|"),
        "keyRulesNote": "Map a physical key to another key, a shortcut, or an action.|Mapeie uma tecla física para outra tecla, atalho ou ação.|Fiziksel tuşu başka bir tuşa, kısayola veya eyleme eşleyin.|Назначьте физической клавише другую клавишу, сочетание или действие.|Asigna una tecla física a otra tecla, atajo o acción.|Priraďte fyzickej klávese inú klávesu, skratku alebo akciu.|Eine physische Taste einer anderen Taste, einem Kurzbefehl oder einer Aktion zuordnen.|Associez une touche physique à une autre touche, un raccourci ou une action.|Associa un tasto fisico a un altro tasto, una scorciatoia o un’azione.|物理キーに別のキー、ショートカット、動作を割り当てます。|물리 키를 다른 키, 단축키 또는 동작에 매핑합니다.|Призначте фізичній клавіші іншу клавішу, сполучення або дію.|将物理按键映射为其他按键、快捷键或操作。|將實體按鍵對應為其他按鍵、快速鍵或動作。|將實體按鍵對應為其他按鍵、快捷鍵或動作。".components(separatedBy: "|"),
        "shortcutRules": "Shortcut rules|Regras de atalhos|Kısayol kuralları|Правила сочетаний|Reglas de atajos|Pravidlá skratiek|Kurzbefehlregeln|Règles de raccourcis|Regole delle scorciatoie|ショートカットのルール|단축키 규칙|Правила сполучень|快捷键规则|快速鍵規則|快捷鍵規則".components(separatedBy: "|"),
        "shortcutRulesNote": "Modifiers must match exactly. Shortcut rules run after key remaps.|Os modificadores devem corresponder exatamente. Os atalhos são aplicados após o remapeamento de teclas.|Değiştiriciler tam eşleşmelidir. Kısayol kuralları tuş eşlemelerinden sonra uygulanır.|Модификаторы должны совпадать точно. Сочетания применяются после переназначения клавиш.|Los modificadores deben coincidir exactamente. Los atajos se aplican después de reasignar teclas.|Modifikátory sa musia presne zhodovať. Skratky sa uplatnia po premapovaní klávesov.|Modifikatortasten müssen genau übereinstimmen. Kurzbefehle greifen nach der Tastenbelegung.|Les modificateurs doivent correspondre exactement. Les raccourcis s’appliquent après le remappage des touches.|I modificatori devono corrispondere esattamente. Le scorciatoie si applicano dopo la rimappatura dei tasti.|修飾キーは完全一致で判定します。ショートカットのルールはキーの割り当て後に適用されます。|보조 키가 정확히 일치해야 합니다. 단축키 규칙은 키 재매핑 후 적용됩니다.|Модифікатори мають точно збігатися. Сполучення застосовуються після перепризначення клавіш.|修饰键必须完全匹配。快捷键规则在按键重映射后生效。|修飾鍵必須完全相符。快速鍵規則在按鍵重新對應後生效。|修飾鍵必須完全相符。快捷鍵規則在按鍵重新對應後生效。".components(separatedBy: "|"),
        "addKeyRule": "Add key rule|Adicionar regra de tecla|Tuş kuralı ekle|Добавить правило клавиши|Añadir regla de tecla|Pridať pravidlo klávesu|Tastenregel hinzufügen|Ajouter une règle de touche|Aggiungi regola tasto|キーのルールを追加|키 규칙 추가|Додати правило клавіші|添加按键规则|新增按鍵規則|新增按鍵規則".components(separatedBy: "|"),
        "addShortcutRule": "Add shortcut rule|Adicionar regra de atalho|Kısayol kuralı ekle|Добавить правило сочетания|Añadir regla de atajo|Pridať pravidlo skratky|Kurzbefehlregel hinzufügen|Ajouter une règle de raccourci|Aggiungi regola scorciatoia|ショートカットのルールを追加|단축키 규칙 추가|Додати правило сполучення|添加快捷键规则|新增快速鍵規則|新增快捷鍵規則".components(separatedBy: "|"),
        "edit": "Edit|Editar|Düzenle|Изменить|Editar|Upraviť|Bearbeiten|Modifier|Modifica|編集|편집|Змінити|编辑|編輯|編輯".components(separatedBy: "|"),
        "removeRule": "Remove rule|Remover regra|Kuralı kaldır|Удалить правило|Eliminar regla|Odstrániť pravidlo|Regel entfernen|Supprimer la règle|Rimuovi regola|ルールを削除|규칙 삭제|Видалити правило|删除规则|移除規則|移除規則".components(separatedBy: "|"),
        "clearRules": "Clear all rules|Limpar todas as regras|Tüm kuralları temizle|Удалить все правила|Eliminar todas las reglas|Odstrániť všetky pravidlá|Alle Regeln entfernen|Supprimer toutes les règles|Rimuovi tutte le regole|すべてのルールを削除|모든 규칙 삭제|Видалити всі правила|清除所有规则|清除所有規則|清除所有規則".components(separatedBy: "|"),
        "emptyRules": "No active rules. Add a rule or use the suggested setup.|Nenhuma regra ativa. Adicione uma regra ou use a sugestão.|Etkin kural yok. Kural ekleyin veya önerilen ayarı kullanın.|Нет активных правил. Добавьте правило или используйте предложенный набор.|No hay reglas activas. Añade una regla o usa la configuración sugerida.|Žiadne aktívne pravidlá. Pridajte pravidlo alebo použite návrh.|Keine aktiven Regeln. Regel hinzufügen oder Vorschlag verwenden.|Aucune règle active. Ajoutez une règle ou utilisez la suggestion.|Nessuna regola attiva. Aggiungi una regola o usa il suggerimento.|有効なルールはありません。ルールを追加するか、提案された設定を使用してください。|활성 규칙이 없습니다. 규칙을 추가하거나 추천 설정을 사용하세요.|Немає активних правил. Додайте правило або скористайтеся запропонованим набором.|没有启用的规则。请添加规则或使用建议配置。|沒有啟用的規則。請新增規則或使用建議設定。|沒有啟用的規則。請新增規則或使用建議設定。".components(separatedBy: "|"),
        "suggestion": "Suggested remaps|Remapeamentos sugeridos|Önerilen eşlemeler|Предлагаемые переназначения|Reasignaciones sugeridas|Navrhované premapovania|Vorgeschlagene Belegungen|Remappages suggérés|Rimappature suggerite|おすすめの割り当て|추천 키 매핑|Пропоновані перепризначення|建议的映射|建議的對應|建議的對應".components(separatedBy: "|"),
        "suggestionNote": "Choose an optional example for your workflow. Preview its rules before adding them.|Escolha um exemplo opcional para seu fluxo de trabalho. Confira as regras antes de adicionar.|İş akışınız için isteğe bağlı bir örnek seçin. Eklemeden önce kuralları inceleyin.|Выберите пример для своей работы. Просмотрите правила перед добавлением.|Elige un ejemplo opcional para tu trabajo. Revisa sus reglas antes de añadirlas.|Vyberte si príklad pre svoju prácu. Pred pridaním si pozrite pravidlá.|Ein optionales Beispiel für Ihren Arbeitsablauf wählen. Regeln vor dem Hinzufügen ansehen.|Choisissez un exemple adapté à votre usage. Vérifiez ses règles avant de les ajouter.|Scegli un esempio per il tuo lavoro. Controlla le regole prima di aggiungerle.|用途に合う例を選び、追加前にルールを確認してください。|작업 방식에 맞는 예시를 선택하고 추가하기 전에 규칙을 확인하세요.|Виберіть приклад для своєї роботи. Перегляньте правила перед додаванням.|选择适合工作方式的可选示例，添加前预览规则。|選擇適合工作方式的選用範例，新增前預覽規則。|選擇適合工作方式的可選範例，新增前預覽規則。".components(separatedBy: "|"),
        "viewSuggestion": "Preview|Prévia|Önizleme|Просмотр|Vista previa|Náhľad|Vorschau|Aperçu|Anteprima|プレビュー|미리 보기|Перегляд|预览|預覽|預覽".components(separatedBy: "|"),
        "addSuggestion": "Add suggested rules|Adicionar regras sugeridas|Önerilen kuralları ekle|Добавить предложенные правила|Añadir reglas sugeridas|Pridať navrhované pravidlá|Vorgeschlagene Regeln hinzufügen|Ajouter les règles suggérées|Aggiungi regole suggerite|提案されたルールを追加|추천 규칙 추가|Додати запропоновані правила|添加建议规则|新增建議規則|新增建議規則".components(separatedBy: "|"),
        "suggestionMerge": "Only missing rules are added. Your existing mappings and disabled choices are kept.|Apenas regras ausentes são adicionadas. Suas regras existentes e opções desativadas são mantidas.|Yalnızca eksik kurallar eklenir. Mevcut eşlemeler ve kapalı seçimler korunur.|Добавляются только отсутствующие правила. Ваши назначения и отключённые правила сохраняются.|Solo se añaden reglas que faltan. Se conservan tus asignaciones y opciones desactivadas.|Pridajú sa iba chýbajúce pravidlá. Existujúce mapovania a vypnuté voľby sa zachovajú.|Nur fehlende Regeln werden ergänzt. Bestehende Belegungen und deaktivierte Optionen bleiben erhalten.|Seules les règles manquantes sont ajoutées. Vos règles existantes et choix désactivés sont conservés.|Si aggiungono solo le regole mancanti. Mappature esistenti e scelte disattivate vengono mantenute.|不足しているルールのみ追加します。既存の割り当てや無効にした設定は保持されます。|없는 규칙만 추가합니다. 기존 매핑과 비활성화한 선택은 유지됩니다.|Додаються лише відсутні правила. Ваші призначення та вимкнені правила зберігаються.|仅添加缺失的规则。现有映射和已禁用的选择将保留。|僅新增缺少的規則。現有對應與已停用的選擇將保留。|僅新增缺少的規則。現有對應與已停用的選擇將保留。".components(separatedBy: "|"),
        "from": "From|De|Kaynak|Откуда|Desde|Z|Von|De|Da|変更元|원본|Звідки|原按键|原按鍵|原按鍵".components(separatedBy: "|"),
        "to": "To|Para|Hedef|Куда|A|Na|Zu|Vers|A|変更先|대상|Куди|目标|目標|目標".components(separatedBy: "|"),
        "key": "Key|Tecla|Tuş|Клавиша|Tecla|Kláves|Taste|Touche|Tasto|キー|키|Клавіша|按键|按鍵|按鍵".components(separatedBy: "|"),
        "shortcut": "Shortcut|Atalho|Kısayol|Сочетание|Atajo|Skratka|Kurzbefehl|Raccourci|Scorciatoia|ショートカット|단축키|Сполучення|快捷键|快速鍵|快捷鍵".components(separatedBy: "|"),
        "ruleEnabled": "Rule enabled|Regra ativada|Kural etkin|Правило включено|Regla activada|Pravidlo zapnuté|Regel aktiviert|Règle activée|Regola abilitata|ルールを有効にする|규칙 활성화|Правило ввімкнено|启用规则|啟用規則|啟用規則".components(separatedBy: "|"),
        "openApp": "Open application|Abrir aplicativo|Uygulama aç|Открыть приложение|Abrir aplicación|Otvoriť aplikáciu|App öffnen|Ouvrir une application|Apri applicazione|アプリを開く|앱 열기|Відкрити програму|打开应用|開啟 App|開啟 App".components(separatedBy: "|"),
        "chooseApp": "Choose application…|Escolher aplicativo…|Uygulama seç…|Выбрать приложение…|Elegir aplicación…|Vybrať aplikáciu…|App auswählen…|Choisir une application…|Scegli applicazione…|アプリを選択…|앱 선택…|Вибрати програму…|选择应用…|選擇 App…|選擇 App…".components(separatedBy: "|"),
        "cancel": "Cancel|Cancelar|İptal|Отмена|Cancelar|Zrušiť|Abbrechen|Annuler|Annulla|キャンセル|취소|Скасувати|取消|取消|取消".components(separatedBy: "|"),
        "save": "Save|Salvar|Kaydet|Сохранить|Guardar|Uložiť|Sichern|Enregistrer|Salva|保存|저장|Зберегти|保存|儲存|儲存".components(separatedBy: "|"),
        "compatibility": "Compatibility|Compatibilidade|Uyumluluk|Совместимость|Compatibilidad|Kompatibilita|Kompatibilität|Compatibilité|Compatibilità|互換性|호환성|Сумісність|兼容性|相容性|兼容性".components(separatedBy: "|"),
        "genericHardware": "Requires Accessibility. Some keyboards handle Fn in firmware. Super Key pauses remaps. Action keys reserve F13–F20, except F18.|Requer Acessibilidade. Alguns teclados tratam Fn no firmware. Super Key pausa o remapeamento. Ações reservam F13–F20, exceto F18.|Erişilebilirlik gerekir. Bazı klavyelerde Fn donanımda işlenir. Super Key eşlemeleri duraklatır. Eylemler F18 hariç F13–F20 kullanır.|Требуется Универсальный доступ. Некоторые клавиатуры обрабатывают Fn в прошивке. Super Key приостанавливает правила. Действия резервируют F13–F20, кроме F18.|Requiere Accesibilidad. Algunos teclados gestionan Fn internamente. Super Key pausa la reasignación. Las acciones reservan F13–F20, excepto F18.|Vyžaduje Prístupnosť. Niektoré klávesnice spracúvajú Fn vo firmvéri. Super Key pozastaví mapovania. Akcie vyhradia F13–F20 okrem F18.|Bedienungshilfen erforderlich. Manche Tastaturen verarbeiten Fn intern. Super Key pausiert die Belegung. Aktionen reservieren F13–F20 außer F18.|Nécessite l’accessibilité. Certains claviers gèrent Fn en interne. Super Key suspend le remappage. Les actions réservent F13–F20, sauf F18.|Richiede Accessibilità. Alcune tastiere gestiscono Fn nel firmware. Super Key sospende le rimappature. Le azioni riservano F13–F20, tranne F18.|アクセシビリティが必要です。Fnを内部処理するキーボードもあります。Super Key有効時は停止します。動作キーにはF18を除くF13〜F20を使用します。|손쉬운 사용 권한이 필요합니다. 일부 키보드는 Fn을 내부에서 처리합니다. Super Key는 재매핑을 중지합니다. 동작 키는 F18을 제외한 F13–F20을 사용합니다.|Потрібна Доступність. Деякі клавіатури обробляють Fn у прошивці. Super Key призупиняє правила. Дії резервують F13–F20, крім F18.|需要辅助功能权限。部分键盘在固件中处理 Fn。Super Key 会暂停重映射。操作按键占用 F13–F20，F18 除外。|需要輔助使用權限。部分鍵盤在韌體中處理 Fn。Super Key 會暫停重新對應。動作按鍵保留 F13–F20，F18 除外。|需要輔助使用權限。部分鍵盤在韌體中處理 Fn。Super Key 會暫停重新對應。動作按鍵保留 F13–F20，F18 除外。".components(separatedBy: "|"),
        "genericActions": "Key actions apply to a key pressed alone. Add shortcut rules for modifiers. Output shortcuts bypass Quit Protection.|Ações de tecla se aplicam à tecla sozinha. Adicione atalhos para modificadores. Atalhos de saída ignoram a Proteção de saída.|Tuş eylemleri tek başına basılınca uygulanır. Değiştiriciler için kısayol ekleyin. Çıkış kısayolları çıkış korumasını atlar.|Действия клавиши работают без модификаторов. Для модификаторов добавьте сочетания. Выходные сочетания обходят защиту от выхода.|Las acciones de tecla se aplican sin modificadores. Añade reglas para modificadores. Los atajos de salida omiten la protección.|Akcie klávesov platia pri samostatnom stlačení. Pre modifikátory pridajte skratky. Výstupné skratky obchádzajú ochranu ukončenia.|Tastenaktionen gelten ohne Modifikatortasten. Für Kombinationen Kurzbefehle hinzufügen. Ausgabekurzbefehle umgehen den Beendigungsschutz.|Les actions de touches s’appliquent sans modificateur. Ajoutez des raccourcis pour les combinaisons. Les sorties contournent la protection de fermeture.|Le azioni dei tasti si applicano senza modificatori. Aggiungi scorciatoie per le combinazioni. Le uscite ignorano la protezione uscita.|キーの動作は単独で押した場合に適用されます。修飾キーとの組み合わせには別のルールを追加します。出力ショートカットは終了保護を通過します。|키 동작은 단독으로 누를 때 적용됩니다. 보조 키 조합은 단축키 규칙을 추가하세요. 출력 단축키는 종료 보호를 건너뜁니다.|Дії клавіш працюють без модифікаторів. Для модифікаторів додайте сполучення. Вихідні сполучення обходять захист від виходу.|按键操作适用于单独按键。修饰键组合请添加快捷键规则。输出快捷键会绕过退出保护。|按鍵動作適用於單獨按鍵。修飾鍵組合請新增快速鍵規則。輸出快速鍵會略過結束保護。|按鍵動作適用於單獨按鍵。修飾鍵組合請新增快捷鍵規則。輸出快捷鍵會略過結束保護。".components(separatedBy: "|"),
        "layoutNote": "Follows the input layout:|Segue o layout de entrada:|Giriş düzenini izler:|Следует раскладке ввода:|Sigue la distribución de entrada:|Sleduje rozloženie vstupu:|Folgt dem Eingabelayout:|Suit la disposition de saisie :|Segue il layout di input:|入力配列に従います：|입력 레이아웃 사용:|Відповідає розкладці введення:|跟随输入布局：|依照輸入配置：|依照輸入配置：".components(separatedBy: "|"),
        "duplicateRule": "Two active rules use the same source. Disable or edit one.|Duas regras ativas usam a mesma origem. Desative ou edite uma.|İki etkin kural aynı kaynağı kullanıyor. Birini kapatın veya düzenleyin.|Два активных правила имеют один источник. Отключите или измените одно.|Dos reglas activas usan el mismo origen. Desactiva o edita una.|Dve aktívne pravidlá používajú rovnaký zdroj. Jedno vypnite alebo upravte.|Zwei aktive Regeln verwenden dieselbe Quelle. Eine deaktivieren oder bearbeiten.|Deux règles actives utilisent la même source. Désactivez ou modifiez l’une d’elles.|Due regole attive usano la stessa origine. Disattivane o modificane una.|同じ変更元に有効なルールが複数あります。一方を無効にするか編集してください。|활성 규칙 두 개가 같은 원본을 사용합니다. 하나를 끄거나 편집하세요.|Два активні правила мають одне джерело. Вимкніть або змініть одне.|两个启用的规则使用相同来源。请停用或编辑其中一个。|兩個啟用的規則使用相同來源。請停用或編輯其中一個。|兩個啟用的規則使用相同來源。請停用或編輯其中一個。".components(separatedBy: "|"),
        "invalidRule": "Choose a valid source and target. They must differ; app actions need an application.|Escolha origem e destino válidos e diferentes. Ações de app precisam de um aplicativo.|Geçerli ve farklı kaynak ve hedef seçin. Uygulama eylemleri için uygulama seçin.|Выберите разные допустимые источник и цель. Для открытия приложения выберите его.|Elige un origen y destino válidos y distintos. Para abrir una app debes elegirla.|Vyberte platný a odlišný zdroj a cieľ. Akcia aplikácie potrebuje aplikáciu.|Gültige, unterschiedliche Quelle und Ziel wählen. App-Aktionen benötigen eine App.|Choisissez une source et une cible valides et différentes. Une action d’app nécessite une application.|Scegli origine e destinazione valide e diverse. Le azioni app richiedono un’applicazione.|有効で異なる変更元と変更先を選んでください。アプリの動作にはアプリの選択が必要です。|유효하고 서로 다른 원본과 대상을 선택하세요. 앱 동작에는 앱 선택이 필요합니다.|Виберіть різні допустимі джерело та ціль. Для відкриття програми виберіть її.|请选择有效且不同的来源与目标。应用操作需要选择应用。|請選擇有效且不同的來源與目標。App 動作需要選擇 App。|請選擇有效且不同的來源與目標。App 動作需要選擇 App。".components(separatedBy: "|"),
        "tooManyActions": "At most seven physical keys can trigger actions. Shortcut-only actions have no such limit.|Até sete teclas físicas podem acionar ações. Ações apenas de atalho não têm esse limite.|En fazla yedi fiziksel tuş eylem tetikleyebilir. Yalnızca kısayol eylemlerinde bu sınır yoktur.|Действия можно назначить максимум семи физическим клавишам. Для сочетаний такого ограничения нет.|Hasta siete teclas físicas pueden activar acciones. Las acciones de atajos no tienen ese límite.|Akcie môže spúšťať najviac sedem fyzických klávesov. Akcie skratiek tento limit nemajú.|Höchstens sieben physische Tasten können Aktionen auslösen. Reine Kurzbefehle haben dieses Limit nicht.|Au plus sept touches physiques peuvent déclencher des actions. Les actions de raccourcis n’ont pas cette limite.|Al massimo sette tasti fisici possono attivare azioni. Le azioni di scorciatoie non hanno questo limite.|動作を割り当てられる物理キーは最大7つです。ショートカットだけの動作にはこの制限はありません。|동작을 실행하는 물리 키는 최대 7개입니다. 단축키 전용 동작에는 이 제한이 없습니다.|Дії можна призначити максимум семи фізичним клавішам. Для сполучень такого обмеження немає.|最多可将七个物理按键设为操作触发键。仅快捷键操作不受此限制。|最多可將七個實體按鍵設為動作觸發鍵。僅快速鍵動作不受此限制。|最多可將七個實體按鍵設為動作觸發鍵。僅快捷鍵動作不受此限制。".components(separatedBy: "|"),
        "reservedKey": "An action trigger key is also used by another rule. Choose another key.|Uma tecla reservada para ações é usada por outra regra. Escolha outra tecla.|Eylem tetikleme tuşu başka kuralda kullanılıyor. Başka tuş seçin.|Служебная клавиша действия используется другим правилом. Выберите другую клавишу.|Una tecla reservada para acciones también se usa en otra regla. Elige otra tecla.|Kláves akcie používa aj iné pravidlo. Vyberte inú klávesu.|Eine Aktionstaste wird auch von einer anderen Regel verwendet. Andere Taste wählen.|Une touche réservée aux actions est utilisée par une autre règle. Choisissez une autre touche.|Un tasto riservato alle azioni è usato da un’altra regola. Scegli un altro tasto.|動作用の内部キーが他のルールでも使われています。別のキーを選んでください。|동작 트리거 키가 다른 규칙에서도 사용됩니다. 다른 키를 선택하세요.|Службова клавіша дії використовується іншим правилом. Виберіть іншу клавішу.|操作触发键也被其他规则使用。请选择其他按键。|動作觸發鍵也被其他規則使用。請選擇其他按鍵。|動作觸發鍵也被其他規則使用。請選擇其他按鍵。".components(separatedBy: "|"),
        "sourceRemapped": "Caps Lock is mapped to another key. Use that resulting key in shortcut rules.|Caps Lock está mapeado para outra tecla. Use a tecla resultante nos atalhos.|Caps Lock başka tuşa eşlendi. Kısayollarda sonuç tuşunu kullanın.|Caps Lock назначена другая клавиша. Используйте её в сочетаниях.|Caps Lock se reasigna a otra tecla. Usa la tecla resultante en los atajos.|Caps Lock je premapovaný na inú klávesu. V skratkách použite výslednú klávesu.|Caps Lock ist einer anderen Taste zugeordnet. Diese Taste in Kurzbefehlen verwenden.|Caps Lock est associé à une autre touche. Utilisez cette touche dans les raccourcis.|Caps Lock è associato a un altro tasto. Usa quel tasto nelle scorciatoie.|Caps Lockが別のキーに割り当てられています。ショートカットには変更後のキーを使用してください。|Caps Lock이 다른 키로 매핑되었습니다. 단축키 규칙에는 변경된 키를 사용하세요.|Caps Lock призначена інша клавіша. Використовуйте її в сполученнях.|Caps Lock 已映射为其他按键。快捷键规则请使用映射后的按键。|Caps Lock 已對應為其他按鍵。快速鍵規則請使用對應後的按鍵。|Caps Lock 已對應為其他按鍵。快捷鍵規則請使用對應後的按鍵。".components(separatedBy: "|"),
        "missingApp": "The application for this rule is not installed.|O aplicativo desta regra não está instalado.|Bu kuralın uygulaması yüklü değil.|Приложение для этого правила не установлено.|La aplicación de esta regla no está instalada.|Aplikácia pre toto pravidlo nie je nainštalovaná.|Die App für diese Regel ist nicht installiert.|L’application de cette règle n’est pas installée.|L’applicazione per questa regola non è installata.|このルールのアプリはインストールされていません。|이 규칙의 앱이 설치되어 있지 않습니다.|Програма для цього правила не встановлена.|此规则的应用尚未安装。|此規則的 App 尚未安裝。|此規則的 App 尚未安裝。".components(separatedBy: "|"),
        "left": "Left|Esquerdo|Sol|Левый|Izquierdo|Ľavý|Links|Gauche|Sinistro|左|왼쪽|Лівий|左|左|左".components(separatedBy: "|"),
        "right": "Right|Direito|Sağ|Правый|Derecho|Pravý|Rechts|Droit|Destro|右|오른쪽|Правий|右|右|右".components(separatedBy: "|"),
        "preset_capsEscape": "Caps Lock → Escape|Caps Lock → Escape|Caps Lock → Escape|Caps Lock → Escape|Bloq Mayús → Escape|Caps Lock → Escape|Caps Lock → Escape|Verr. maj. → Échap|Bloc Maiusc → Escape|Caps Lock → Escape|Caps Lock → Escape|Caps Lock → Escape|Caps Lock → Escape|Caps Lock → Escape|Caps Lock → Escape".components(separatedBy: "|"),
        "preset_capsEscape_note": "Escape within reach for Vim and editors. Replaces normal Caps Lock.|Escape ao alcance para Vim e editores. Substitui o Caps Lock normal.|Vim ve editörler için Escape daha yakında. Normal Caps Lock işlevini değiştirir.|Escape ближе для Vim и редакторов. Заменяет обычный Caps Lock.|Escape al alcance para Vim y editores. Sustituye Bloq Mayús.|Escape na dosah pre Vim a editory. Nahradí bežný Caps Lock.|Escape für Vim und Editoren leichter erreichen. Ersetzt normales Caps Lock.|Échap à portée pour Vim et les éditeurs. Remplace Verr. maj.|Escape a portata di mano per Vim e gli editor. Sostituisce Bloc Maiusc.|Vimやエディタ用のEscapeを押しやすくします。通常のCaps Lockを置き換えます。|Vim과 편집기에서 Escape를 쉽게 누릅니다. 일반 Caps Lock을 대체합니다.|Escape ближче для Vim і редакторів. Замінює звичайний Caps Lock.|方便在 Vim 和编辑器中按 Escape，替代普通 Caps Lock。|方便在 Vim 和編輯器中按 Escape，取代一般 Caps Lock。|方便在 Vim 和編輯器中按 Escape，取代一般 Caps Lock。".components(separatedBy: "|"),
        "preset_capsControl": "Caps Lock → Control|Caps Lock → Control|Caps Lock → Control|Caps Lock → Control|Bloq Mayús → Control|Caps Lock → Control|Caps Lock → Control|Verr. maj. → Contrôle|Bloc Maiusc → Control|Caps Lock → Control|Caps Lock → Control|Caps Lock → Control|Caps Lock → Control|Caps Lock → Control|Caps Lock → Control".components(separatedBy: "|"),
        "preset_capsControl_note": "Control on the home row for terminal shortcuts. Replaces normal Caps Lock.|Control na fileira central para atalhos do terminal. Substitui o Caps Lock normal.|Terminal kısayolları için Control ana sırada. Normal Caps Lock işlevini değiştirir.|Control на основном ряду для терминала. Заменяет обычный Caps Lock.|Control en la fila central para atajos de terminal. Sustituye Bloq Mayús.|Control v základnom rade pre terminálové skratky. Nahradí bežný Caps Lock.|Control in der Grundreihe für Terminal-Kurzbefehle. Ersetzt normales Caps Lock.|Contrôle sur la rangée centrale pour le terminal. Remplace Verr. maj.|Control sulla riga centrale per il terminale. Sostituisce Bloc Maiusc.|ターミナル用のControlをホームポジションに配置します。通常のCaps Lockを置き換えます。|터미널 단축키를 위한 Control을 기본 행에 둡니다. 일반 Caps Lock을 대체합니다.|Control на основному ряду для термінала. Замінює звичайний Caps Lock.|将 Control 放在主键位行，方便终端快捷键，替代普通 Caps Lock。|將 Control 放在主鍵位列，方便終端快速鍵，取代一般 Caps Lock。|將 Control 放在主鍵位列，方便終端快捷鍵，取代一般 Caps Lock。".components(separatedBy: "|"),
        "preset_lineNavigation": "PC-style Home / End|Home / End como no PC|PC tarzı Home / End|Home / End как на ПК|Inicio / Fin como en PC|Home / End ako na PC|Home / End wie am PC|Début / Fin comme sur PC|Home / End come su PC|PC式のHome / End|PC 방식 Home / End|Home / End як на ПК|PC 风格 Home / End|PC 風格 Home / End|PC 風格 Home / End".components(separatedBy: "|"),
        "preset_lineNavigation_note": "Home/End move to line boundaries; Shift selects. App support varies.|Home/End vão ao início/fim da linha; Shift seleciona. O suporte varia por app.|Home/End satır başına/sonuna gider; Shift seçer. Uygulama desteği değişir.|Home/End перемещают к границам строки; Shift выделяет. Зависит от приложения.|Inicio/Fin van a los extremos de la línea; Mayús selecciona. Depende de la app.|Home/End presunú na okraje riadku; Shift vyberá. Podpora závisí od aplikácie.|Home/End springen an Zeilengrenzen; Shift wählt aus. App-Unterstützung variiert.|Début/Fin vont aux limites de ligne ; Maj sélectionne. Selon l’app.|Home/End vanno ai limiti della riga; Maiusc seleziona. Il supporto varia per app.|Home/Endで行頭・行末へ移動、Shiftで選択します。アプリにより異なります。|Home/End로 줄 시작과 끝으로 이동하고 Shift로 선택합니다. 앱에 따라 다릅니다.|Home/End переходять до меж рядка; Shift виділяє. Залежить від програми.|Home/End 移至行首或行尾，Shift 可选择文本。支持情况因应用而异。|Home/End 移至行首或行尾，Shift 可選取文字。支援情況因 App 而異。|Home/End 移至行首或行尾，Shift 可選取文字。支援情況因 App 而異。".components(separatedBy: "|"),
        "preset_fnLanguages": "Fn and languages|Fn e idiomas|Fn ve diller|Fn и языки|Fn e idiomas|Fn a jazyky|Fn und Sprachen|Fn et langues|Fn e lingue|Fnと言語|Fn과 입력 언어|Fn і мови|Fn 与输入语言|Fn 與輸入語言|Fn 與輸入語言".components(separatedBy: "|"),
        "preset_fnLanguages_note": "Fn becomes Command; Caps Lock switches languages. Shift+Caps Lock keeps capitals.|Fn vira Command; Caps Lock troca idiomas. Shift+Caps Lock mantém maiúsculas.|Fn Command olur; Caps Lock dil değiştirir. Shift+Caps Lock büyük harfleri korur.|Fn становится Command; Caps Lock переключает язык. Shift+Caps Lock сохраняет прописные буквы.|Fn pasa a Comando; Bloq Mayús cambia idiomas. Mayús+Bloq Mayús conserva las mayúsculas.|Fn sa zmení na Command; Caps Lock prepína jazyky. Shift+Caps Lock zachová veľké písmená.|Fn wird Command; Caps Lock wechselt Sprachen. Shift+Caps Lock behält Großbuchstaben.|Fn devient Commande ; Verr. maj. change de langue. Maj+Verr. maj. conserve les majuscules.|Fn diventa Comando; Bloc Maiusc cambia lingua. Maiusc+Bloc Maiusc mantiene le maiuscole.|FnをCommandにし、Caps Lockで言語を切り替えます。Shift+Caps Lockで大文字機能を使えます。|Fn을 Command로 바꾸고 Caps Lock으로 언어를 전환합니다. Shift+Caps Lock으로 대문자 기능을 유지합니다.|Fn стає Command; Caps Lock перемикає мови. Shift+Caps Lock зберігає великі літери.|Fn 变为 Command，Caps Lock 切换语言，Shift+Caps Lock 保留大写功能。|Fn 變為 Command，Caps Lock 切換語言，Shift+Caps Lock 保留大寫功能。|Fn 變為 Command，Caps Lock 切換語言，Shift+Caps Lock 保留大寫功能。".components(separatedBy: "|"),
        "commandKey": "Command|Command|Command|Command|Comando|Command|Command|Commande|Comando|Command|Command|Command|Command|Command|Command".components(separatedBy: "|"),
        "controlKey": "Control|Control|Control|Control|Control|Control|Control|Contrôle|Control|Control|Control|Control|Control|Control|Control".components(separatedBy: "|"),
        "optionKey": "Option|Option|Option|Option|Opción|Option|Option|Option|Opzione|Option|Option|Option|Option|Option|Option".components(separatedBy: "|"),
        "shiftKey": "Shift|Shift|Shift|Shift|Mayús|Shift|Shift|Maj|Maiusc|Shift|Shift|Shift|Shift|Shift|Shift".components(separatedBy: "|"),
        "homeKey": "Home|Home|Home|Home|Inicio|Home|Home|Début|Home|Home|Home|Home|Home|Home|Home".components(separatedBy: "|"),
        "endKey": "End|End|End|End|Fin|End|End|Fin|End|End|End|End|End|End|End".components(separatedBy: "|"),
        "leftArrowKey": "Left Arrow|Seta esquerda|Sol ok|Стрелка влево|Flecha izquierda|Šípka doľava|Pfeil links|Flèche gauche|Freccia sinistra|左矢印|왼쪽 화살표|Стрілка ліворуч|左箭头|向左鍵|左方向鍵".components(separatedBy: "|"),
        "rightArrowKey": "Right Arrow|Seta direita|Sağ ok|Стрелка вправо|Flecha derecha|Šípka doprava|Pfeil rechts|Flèche droite|Freccia destra|右矢印|오른쪽 화살표|Стрілка праворуч|右箭头|向右鍵|右方向鍵".components(separatedBy: "|"),
        "preset_saferQuit": "Safer quitting|Encerramento mais seguro|Daha güvenli çıkış|Безопасный выход|Salida más segura|Bezpečnejšie ukončenie|Sicherer beenden|Quitter plus sûrement|Uscita più sicura|誤終了を防ぐ|안전한 앱 종료|Безпечний вихід|更安全地退出|更安全地結束|更安全地退出".components(separatedBy: "|"),
        "preset_saferQuit_note": "Command+Q does nothing; Option+Q quits. Prevent accidental quitting near Command+Tab. Replaces the character normally typed by Option+Q.|Command+Q não faz nada; Option+Q encerra. Evita sair por engano perto de Command+Tab. Substitui o caractere de Option+Q.|Command+Q etkisizdir; Option+Q çıkar. Command+Tab yakınındaki yanlış çıkışları önler. Option+Q karakterini değiştirir.|Command+Q ничего не делает; Option+Q завершает приложение. Защищает от ошибок рядом с Command+Tab. Заменяет символ Option+Q.|Comando+Q no hace nada; Opción+Q sale. Evita salidas accidentales cerca de Comando+Tab. Sustituye el carácter de Opción+Q.|Command+Q nič neurobí; Option+Q ukončí aplikáciu. Zabráni omylom pri Command+Tab. Nahradí znak Option+Q.|Command+Q tut nichts; Option+Q beendet. Verhindert versehentliches Beenden nahe Command+Tab. Ersetzt das Zeichen von Option+Q.|Commande+Q ne fait rien ; Option+Q quitte. Évite les erreurs près de Commande+Tab. Remplace le caractère d’Option+Q.|Comando+Q non fa nulla; Opzione+Q esce. Evita uscite accidentali vicino a Comando+Tab. Sostituisce il carattere di Opzione+Q.|Command+Qを無効にし、Option+Qで終了します。Command+Tab付近の誤操作を防ぎます。Option+Qの文字入力を置き換えます。|Command+Q는 무시하고 Option+Q로 종료합니다. Command+Tab 근처의 실수를 방지합니다. Option+Q 문자 입력을 대체합니다.|Command+Q нічого не робить; Option+Q завершує програму. Захищає від помилок біля Command+Tab. Замінює символ Option+Q.|Command+Q 不执行操作，Option+Q 退出，避免在 Command+Tab 附近误退出。会替代 Option+Q 通常输入的字符。|Command+Q 不執行操作，Option+Q 結束，避免在 Command+Tab 附近誤結束。會取代 Option+Q 原本輸入的字元。|Command+Q 不執行操作，Option+Q 退出，避免在 Command+Tab 附近誤退出。會取代 Option+Q 原本輸入的字元。".components(separatedBy: "|"),
        "quitApp": "Quit app|Encerrar app|Uygulamadan çık|Завершить приложение|Salir de la app|Ukončiť aplikáciu|App beenden|Quitter l’app|Esci dall’app|アプリを終了|앱 종료|Завершити програму|退出应用|結束 App|退出 App".components(separatedBy: "|"),
    ]

    static func text(_ key: String, language: AppLanguage = L10n.shared.language) -> String {
        guard let values = table[key], let index = languages.firstIndex(of: language),
              values.indices.contains(index) else { return key }
        return values[index]
    }

    static func isComplete(for language: AppLanguage) -> Bool {
        guard let index = languages.firstIndex(of: language) else { return false }
        return table.values.allSatisfy { $0.count == languages.count && !$0[index].isEmpty }
    }
}
