// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchSpotifyStrings {
    /// The Features hub name.
    let feature: String
    let account: String
    let accountHint: String
    let connected: String
    let connecting: String
    let connectFailed: String
    let connect: String
    let disconnect: String
    let getStarted: String
    let step1: String
    let openDeveloper: String
    let step2: String
    let copyRedirect: String
    let copied: String
    let step3: String
    let clientIDPlaceholder: String
    let invalidClientID: String
    let premiumNote: String
    let like: String
    let unlike: String
    let likeFailed: String
    /// Shown in the browser tab once sign-in hands control back.
    let signedIn: String
}

extension FeatureStrings {
    static func notchSpotify(_ language: AppLanguage) -> NotchSpotifyStrings {
        switch language {
        case .enUS: return NotchSpotifyStrings(
            feature: "Spotify likes",
            account: "Spotify",
            accountHint: "Like or unlike the playing song from the music page.",
            connected: "Connected to Spotify",
            connecting: "Finish signing in in your browser…",
            connectFailed: "Could not connect. Check the Client ID and the redirect URI, then try again.",
            connect: "Connect Spotify",
            disconnect: "Disconnect",
            getStarted: "Set up in three steps",
            step1: "Create an app on Spotify for Developers and choose Web API.",
            openDeveloper: "Open Spotify for Developers",
            step2: "Add this redirect URI to the app.",
            copyRedirect: "Copy redirect URI",
            copied: "Copied",
            step3: "Paste the app’s Client ID.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "A Client ID has 32 letters and numbers.",
            premiumNote: "The app’s owner needs Spotify Premium. Sign-in details stay on this Mac.",
            like: "Add to Liked Songs",
            unlike: "Remove from Liked Songs",
            likeFailed: "Could not update Liked Songs.",
            signedIn: "Signed in. You can close this tab and return to Vorssaint.")
        case .ptBR: return NotchSpotifyStrings(
            feature: "Curtidas do Spotify",
            account: "Spotify",
            accountHint: "Curta ou descurta a música tocando na página de música.",
            connected: "Conectado ao Spotify",
            connecting: "Conclua o login no navegador…",
            connectFailed: "Não foi possível conectar. Verifique o Client ID e a URI de redirecionamento e tente de novo.",
            connect: "Conectar Spotify",
            disconnect: "Desconectar",
            getStarted: "Configure em três passos",
            step1: "Crie um app no Spotify for Developers e escolha Web API.",
            openDeveloper: "Abrir Spotify for Developers",
            step2: "Adicione esta URI de redirecionamento ao app.",
            copyRedirect: "Copiar URI de redirecionamento",
            copied: "Copiado",
            step3: "Cole o Client ID do app.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Um Client ID tem 32 letras e números.",
            premiumNote: "O dono do app precisa do Spotify Premium. Os dados de login ficam neste Mac.",
            like: "Adicionar às Músicas Curtidas",
            unlike: "Remover das Músicas Curtidas",
            likeFailed: "Não foi possível atualizar as Músicas Curtidas.",
            signedIn: "Login concluído. Você pode fechar esta aba e voltar ao Vorssaint.")
        case .tr: return NotchSpotifyStrings(
            feature: "Spotify beğenileri",
            account: "Spotify",
            accountHint: "Çalan şarkıyı müzik sayfasından beğenin veya beğenmekten vazgeçin.",
            connected: "Spotify’a bağlandı",
            connecting: "Girişi tarayıcıda tamamlayın…",
            connectFailed: "Bağlanılamadı. Client ID’yi ve yönlendirme URI’sini kontrol edip yeniden deneyin.",
            connect: "Spotify’ı bağla",
            disconnect: "Bağlantıyı kes",
            getStarted: "Üç adımda kurun",
            step1: "Spotify for Developers’ta bir uygulama oluşturun ve Web API’yi seçin.",
            openDeveloper: "Spotify for Developers’ı aç",
            step2: "Bu yönlendirme URI’sini uygulamaya ekleyin.",
            copyRedirect: "Yönlendirme URI’sini kopyala",
            copied: "Kopyalandı",
            step3: "Uygulamanın Client ID’sini yapıştırın.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID 32 harf ve rakamdan oluşur.",
            premiumNote: "Uygulama sahibinin Spotify Premium’u olmalıdır. Giriş bilgileri bu Mac’te kalır.",
            like: "Beğenilen Şarkılara ekle",
            unlike: "Beğenilen Şarkılardan kaldır",
            likeFailed: "Beğenilen Şarkılar güncellenemedi.",
            signedIn: "Giriş yapıldı. Bu sekmeyi kapatıp Vorssaint’e dönebilirsiniz.")
        case .ru: return NotchSpotifyStrings(
            feature: "Лайки Spotify",
            account: "Spotify",
            accountHint: "Добавляйте играющую песню в «Любимые треки» или убирайте её прямо со страницы музыки.",
            connected: "Spotify подключён",
            connecting: "Завершите вход в браузере…",
            connectFailed: "Не удалось подключиться. Проверьте Client ID и URI перенаправления и попробуйте снова.",
            connect: "Подключить Spotify",
            disconnect: "Отключить",
            getStarted: "Настройка в три шага",
            step1: "Создайте приложение в Spotify for Developers и выберите Web API.",
            openDeveloper: "Открыть Spotify for Developers",
            step2: "Добавьте в приложение этот URI перенаправления.",
            copyRedirect: "Скопировать URI перенаправления",
            copied: "Скопировано",
            step3: "Вставьте Client ID приложения.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID состоит из 32 букв и цифр.",
            premiumNote: "Владельцу приложения нужен Spotify Premium. Данные входа хранятся только на этом Mac.",
            like: "Добавить в «Любимые треки»",
            unlike: "Убрать из «Любимых треков»",
            likeFailed: "Не удалось обновить «Любимые треки».",
            signedIn: "Вход выполнен. Можно закрыть эту вкладку и вернуться в Vorssaint.")
        case .es: return NotchSpotifyStrings(
            feature: "Me gusta de Spotify",
            account: "Spotify",
            accountHint: "Da o quita «me gusta» a la canción que suena desde la página de música.",
            connected: "Conectado a Spotify",
            connecting: "Termina de iniciar sesión en el navegador…",
            connectFailed: "No se pudo conectar. Revisa el Client ID y la URI de redirección e inténtalo de nuevo.",
            connect: "Conectar Spotify",
            disconnect: "Desconectar",
            getStarted: "Configúralo en tres pasos",
            step1: "Crea una app en Spotify for Developers y elige Web API.",
            openDeveloper: "Abrir Spotify for Developers",
            step2: "Añade esta URI de redirección a la app.",
            copyRedirect: "Copiar URI de redirección",
            copied: "Copiado",
            step3: "Pega el Client ID de la app.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Un Client ID tiene 32 letras y números.",
            premiumNote: "El propietario de la app necesita Spotify Premium. Los datos de inicio de sesión se quedan en este Mac.",
            like: "Añadir a Canciones que te gustan",
            unlike: "Quitar de Canciones que te gustan",
            likeFailed: "No se pudo actualizar Canciones que te gustan.",
            signedIn: "Sesión iniciada. Puedes cerrar esta pestaña y volver a Vorssaint.")
        case .sk: return NotchSpotifyStrings(
            feature: "Obľúbené v Spotify",
            account: "Spotify",
            accountHint: "Označte alebo zrušte obľúbenie hrajúcej skladby priamo zo stránky hudby.",
            connected: "Pripojené k Spotify",
            connecting: "Dokončite prihlásenie v prehliadači…",
            connectFailed: "Nepodarilo sa pripojiť. Skontrolujte Client ID a URI presmerovania a skúste to znova.",
            connect: "Pripojiť Spotify",
            disconnect: "Odpojiť",
            getStarted: "Nastavenie v troch krokoch",
            step1: "Vytvorte aplikáciu v Spotify for Developers a vyberte Web API.",
            openDeveloper: "Otvoriť Spotify for Developers",
            step2: "Pridajte do aplikácie toto URI presmerovania.",
            copyRedirect: "Kopírovať URI presmerovania",
            copied: "Skopírované",
            step3: "Vložte Client ID aplikácie.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID má 32 písmen a číslic.",
            premiumNote: "Vlastník aplikácie potrebuje Spotify Premium. Prihlasovacie údaje zostávajú v tomto Macu.",
            like: "Pridať do Obľúbených skladieb",
            unlike: "Odstrániť z Obľúbených skladieb",
            likeFailed: "Obľúbené skladby sa nepodarilo aktualizovať.",
            signedIn: "Prihlásenie prebehlo. Túto kartu môžete zavrieť a vrátiť sa do Vorssaint.")
        case .de: return NotchSpotifyStrings(
            feature: "Spotify-Likes",
            account: "Spotify",
            accountHint: "Füge den laufenden Song auf der Musikseite zu Lieblingssongs hinzu oder entferne ihn.",
            connected: "Mit Spotify verbunden",
            connecting: "Schließe die Anmeldung im Browser ab …",
            connectFailed: "Verbindung fehlgeschlagen. Prüfe Client ID und Weiterleitungs-URI und versuche es erneut.",
            connect: "Spotify verbinden",
            disconnect: "Trennen",
            getStarted: "In drei Schritten einrichten",
            step1: "Erstelle eine App bei Spotify for Developers und wähle Web API.",
            openDeveloper: "Spotify for Developers öffnen",
            step2: "Füge der App diese Weiterleitungs-URI hinzu.",
            copyRedirect: "Weiterleitungs-URI kopieren",
            copied: "Kopiert",
            step3: "Füge die Client ID der App ein.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Eine Client ID hat 32 Buchstaben und Ziffern.",
            premiumNote: "Der App-Besitzer braucht Spotify Premium. Anmeldedaten bleiben auf diesem Mac.",
            like: "Zu Lieblingssongs hinzufügen",
            unlike: "Aus Lieblingssongs entfernen",
            likeFailed: "Lieblingssongs konnten nicht aktualisiert werden.",
            signedIn: "Angemeldet. Du kannst diesen Tab schließen und zu Vorssaint zurückkehren.")
        case .fr: return NotchSpotifyStrings(
            feature: "J’aime Spotify",
            account: "Spotify",
            accountHint: "Likez ou retirez le morceau en cours depuis la page musique.",
            connected: "Connecté à Spotify",
            connecting: "Terminez la connexion dans votre navigateur…",
            connectFailed: "Connexion impossible. Vérifiez le Client ID et l’URI de redirection, puis réessayez.",
            connect: "Connecter Spotify",
            disconnect: "Déconnecter",
            getStarted: "Configuration en trois étapes",
            step1: "Créez une app sur Spotify for Developers et choisissez Web API.",
            openDeveloper: "Ouvrir Spotify for Developers",
            step2: "Ajoutez cette URI de redirection à l’app.",
            copyRedirect: "Copier l’URI de redirection",
            copied: "Copié",
            step3: "Collez le Client ID de l’app.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Un Client ID compte 32 lettres et chiffres.",
            premiumNote: "Le propriétaire de l’app doit avoir Spotify Premium. Les informations de connexion restent sur ce Mac.",
            like: "Ajouter aux Titres likés",
            unlike: "Retirer des Titres likés",
            likeFailed: "Impossible de mettre à jour les Titres likés.",
            signedIn: "Connexion réussie. Vous pouvez fermer cet onglet et revenir à Vorssaint.")
        case .it: return NotchSpotifyStrings(
            feature: "Mi piace di Spotify",
            account: "Spotify",
            accountHint: "Aggiungi o togli il brano in riproduzione dai preferiti dalla pagina musica.",
            connected: "Collegato a Spotify",
            connecting: "Completa l’accesso nel browser…",
            connectFailed: "Impossibile collegarsi. Controlla il Client ID e l’URI di reindirizzamento, poi riprova.",
            connect: "Collega Spotify",
            disconnect: "Scollega",
            getStarted: "Configura in tre passaggi",
            step1: "Crea un’app su Spotify for Developers e scegli Web API.",
            openDeveloper: "Apri Spotify for Developers",
            step2: "Aggiungi questo URI di reindirizzamento all’app.",
            copyRedirect: "Copia URI di reindirizzamento",
            copied: "Copiato",
            step3: "Incolla il Client ID dell’app.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Un Client ID ha 32 lettere e numeri.",
            premiumNote: "Il proprietario dell’app deve avere Spotify Premium. I dati di accesso restano su questo Mac.",
            like: "Aggiungi ai Brani che ti piacciono",
            unlike: "Rimuovi dai Brani che ti piacciono",
            likeFailed: "Impossibile aggiornare i Brani che ti piacciono.",
            signedIn: "Accesso eseguito. Puoi chiudere questa scheda e tornare a Vorssaint.")
        case .ja: return NotchSpotifyStrings(
            feature: "Spotify のお気に入り",
            account: "Spotify",
            accountHint: "ミュージックページから再生中の曲をお気に入りに追加・削除できます。",
            connected: "Spotify に接続済み",
            connecting: "ブラウザでサインインを完了してください…",
            connectFailed: "接続できませんでした。Client ID とリダイレクト URI を確認して、もう一度お試しください。",
            connect: "Spotify に接続",
            disconnect: "接続解除",
            getStarted: "3 ステップで設定",
            step1: "Spotify for Developers でアプリを作成し、Web API を選びます。",
            openDeveloper: "Spotify for Developers を開く",
            step2: "このリダイレクト URI をアプリに追加します。",
            copyRedirect: "リダイレクト URI をコピー",
            copied: "コピーしました",
            step3: "アプリの Client ID を貼り付けます。",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID は 32 文字の英数字です。",
            premiumNote: "アプリの所有者には Spotify Premium が必要です。サインイン情報はこの Mac に保存されます。",
            like: "お気に入りの曲に追加",
            unlike: "お気に入りの曲から削除",
            likeFailed: "お気に入りの曲を更新できませんでした。",
            signedIn: "サインインしました。このタブを閉じて Vorssaint に戻ってください。")
        case .ko: return NotchSpotifyStrings(
            feature: "Spotify 좋아요",
            account: "Spotify",
            accountHint: "음악 페이지에서 재생 중인 노래를 좋아요 표시하거나 취소합니다.",
            connected: "Spotify에 연결됨",
            connecting: "브라우저에서 로그인을 완료하세요…",
            connectFailed: "연결할 수 없습니다. Client ID와 리디렉션 URI를 확인한 후 다시 시도하세요.",
            connect: "Spotify 연결",
            disconnect: "연결 해제",
            getStarted: "세 단계로 설정",
            step1: "Spotify for Developers에서 앱을 만들고 Web API를 선택하세요.",
            openDeveloper: "Spotify for Developers 열기",
            step2: "이 리디렉션 URI를 앱에 추가하세요.",
            copyRedirect: "리디렉션 URI 복사",
            copied: "복사됨",
            step3: "앱의 Client ID를 붙여 넣으세요.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID는 32자의 영문자와 숫자입니다.",
            premiumNote: "앱 소유자는 Spotify Premium이 필요합니다. 로그인 정보는 이 Mac에 보관됩니다.",
            like: "좋아요 표시한 곡에 추가",
            unlike: "좋아요 표시한 곡에서 제거",
            likeFailed: "좋아요 표시한 곡을 업데이트할 수 없습니다.",
            signedIn: "로그인되었습니다. 이 탭을 닫고 Vorssaint로 돌아가세요.")
        case .uk: return NotchSpotifyStrings(
            feature: "Вподобання Spotify",
            account: "Spotify",
            accountHint: "Додавайте пісню, що грає, до «Улюблених треків» або прибирайте її просто зі сторінки музики.",
            connected: "Spotify підключено",
            connecting: "Завершіть вхід у браузері…",
            connectFailed: "Не вдалося підключитися. Перевірте Client ID і URI переспрямування та спробуйте ще раз.",
            connect: "Підключити Spotify",
            disconnect: "Відключити",
            getStarted: "Налаштування у три кроки",
            step1: "Створіть застосунок у Spotify for Developers і виберіть Web API.",
            openDeveloper: "Відкрити Spotify for Developers",
            step2: "Додайте до застосунку цей URI переспрямування.",
            copyRedirect: "Скопіювати URI переспрямування",
            copied: "Скопійовано",
            step3: "Вставте Client ID застосунку.",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID складається з 32 літер і цифр.",
            premiumNote: "Власнику застосунку потрібен Spotify Premium. Дані входу зберігаються лише на цьому Mac.",
            like: "Додати до «Улюблених треків»",
            unlike: "Прибрати з «Улюблених треків»",
            likeFailed: "Не вдалося оновити «Улюблені треки».",
            signedIn: "Вхід виконано. Можна закрити цю вкладку й повернутися до Vorssaint.")
        case .zhHans: return NotchSpotifyStrings(
            feature: "Spotify 点赞",
            account: "Spotify",
            accountHint: "在音乐页将正在播放的歌曲点赞或取消点赞。",
            connected: "已连接 Spotify",
            connecting: "请在浏览器中完成登录…",
            connectFailed: "无法连接。请检查 Client ID 和重定向 URI，然后重试。",
            connect: "连接 Spotify",
            disconnect: "断开连接",
            getStarted: "三步完成设置",
            step1: "在 Spotify for Developers 创建应用，并选择 Web API。",
            openDeveloper: "打开 Spotify for Developers",
            step2: "将此重定向 URI 添加到应用。",
            copyRedirect: "拷贝重定向 URI",
            copied: "已拷贝",
            step3: "粘贴应用的 Client ID。",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID 由 32 个字母和数字组成。",
            premiumNote: "应用所有者需要 Spotify Premium。登录信息保存在这台 Mac 上。",
            like: "加入已点赞的歌曲",
            unlike: "从已点赞的歌曲中移除",
            likeFailed: "无法更新已点赞的歌曲。",
            signedIn: "已登录。你可以关闭此标签页并返回 Vorssaint。")
        case .zhTW: return NotchSpotifyStrings(
            feature: "Spotify 按讚",
            account: "Spotify",
            accountHint: "在音樂頁為正在播放的歌曲按讚或取消按讚。",
            connected: "已連接 Spotify",
            connecting: "請在瀏覽器中完成登入…",
            connectFailed: "無法連接。請檢查 Client ID 和重新導向 URI，然後再試一次。",
            connect: "連接 Spotify",
            disconnect: "中斷連接",
            getStarted: "三個步驟完成設定",
            step1: "在 Spotify for Developers 建立 App，並選擇 Web API。",
            openDeveloper: "打開 Spotify for Developers",
            step2: "將此重新導向 URI 加入 App。",
            copyRedirect: "拷貝重新導向 URI",
            copied: "已拷貝",
            step3: "貼上 App 的 Client ID。",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID 由 32 個字母和數字組成。",
            premiumNote: "App 擁有者需要 Spotify Premium。登入資料保存在這部 Mac 上。",
            like: "加入已按讚的歌曲",
            unlike: "從已按讚的歌曲中移除",
            likeFailed: "無法更新已按讚的歌曲。",
            signedIn: "已登入。你可以關閉此分頁並返回 Vorssaint。")
        case .zhHK: return NotchSpotifyStrings(
            feature: "Spotify 讚好",
            account: "Spotify",
            accountHint: "在音樂頁為正在播放的歌曲讚好或取消讚好。",
            connected: "已連接 Spotify",
            connecting: "請在瀏覽器中完成登入…",
            connectFailed: "無法連接。請檢查 Client ID 和重新導向 URI，然後再試一次。",
            connect: "連接 Spotify",
            disconnect: "中斷連接",
            getStarted: "三個步驟完成設定",
            step1: "在 Spotify for Developers 建立 App，並選擇 Web API。",
            openDeveloper: "打開 Spotify for Developers",
            step2: "將此重新導向 URI 加入 App。",
            copyRedirect: "複製重新導向 URI",
            copied: "已複製",
            step3: "貼上 App 的 Client ID。",
            clientIDPlaceholder: "Client ID",
            invalidClientID: "Client ID 由 32 個字母和數字組成。",
            premiumNote: "App 擁有者需要 Spotify Premium。登入資料保存在這部 Mac 上。",
            like: "加入已讚好的歌曲",
            unlike: "從已讚好的歌曲中移除",
            likeFailed: "無法更新已讚好的歌曲。",
            signedIn: "已登入。你可以關閉此分頁並返回 Vorssaint。")
        }
    }
}
