// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchWatchStrings {
    let title: String
    let description: String
    let setupHint: String
    let choose: String
    let chooseAgain: String
    let purpose: String
    let stop: String
    let watchAgain: String
    let permissionHint: String
    let allowAccess: String
    let tellMe: String
    let changes: String
    let settles: String
    let contains: String
    let reaches: String
    let settlesHint: String
    let textPlaceholder: String
    let numberPlaceholder: String
    let noText: String
    let inIsland: String
    let automatic: String
    let hidden: String
    let changedNotice: String
    let settledNotice: String
    let showsFormat: String
    let reachedFormat: String
    let closedNotice: String
    let sinceFormat: String
    let sound: String

    func condition(_ condition: NotchWatchCondition) -> String {
        switch condition {
        case .changes: return changes
        case .settles: return settles
        case .contains: return contains
        case .reaches: return reaches
        }
    }

    func outcome(_ outcome: NotchWatchOutcome) -> String {
        switch outcome {
        case .changed: return changedNotice
        case .settled: return settledNotice
        case .shows(let text): return String(format: showsFormat, text)
        case .reached(let text): return String(format: reachedFormat, text)
        case .closed: return closedNotice
        }
    }

    func since(_ time: String) -> String { String(format: sinceFormat, time) }
}

extension FeatureStrings {
    static func notchWatch(_ language: AppLanguage) -> NotchWatchStrings {
        switch language {
        case .enUS: return NotchWatchStrings(
            title: "Watch",
            description: "Turn any part of any window into a live activity in the Dynamic Island, with an alert when it changes, finishes or shows what you are waiting for.",
            setupHint: "Choose any part of a window, like a progress bar, a build status or a score. The island reads it for you and tells you when it changes.",
            choose: "Choose Area",
            chooseAgain: "Choose Another Area",
            purpose: "Choose what to watch",
            stop: "Stop Watching",
            watchAgain: "Watch Again",
            permissionHint: "Watch reads the area you choose on your Mac, so it needs Screen Recording. Nothing leaves your Mac.",
            allowAccess: "Allow Screen Recording",
            tellMe: "Tell me",
            changes: "When it changes",
            settles: "When it stops changing",
            contains: "When it shows",
            reaches: "When the number reaches",
            settlesHint: "After it changes, it must stay still for 30 seconds.",
            textPlaceholder: "Text, like Done",
            numberPlaceholder: "Number, like 100",
            noText: "No text",
            inIsland: "Show in the island",
            automatic: "Automatic",
            hidden: "The window is hidden. Watching continues when it returns.",
            changedNotice: "It changed",
            settledNotice: "It stopped changing",
            showsFormat: "It shows %@",
            reachedFormat: "It reached %@",
            closedNotice: "The window closed",
            sinceFormat: "Watching since %@",
            sound: "Play a sound")
        case .ptBR: return NotchWatchStrings(
            title: "Observar",
            description: "Transforme qualquer parte de qualquer janela em uma atividade ao vivo no Dynamic Island, com aviso quando mudar, terminar ou mostrar o que você espera.",
            setupHint: "Escolha qualquer parte de uma janela, como uma barra de progresso, o status de um build ou um placar. A ilha lê para você e avisa quando mudar.",
            choose: "Escolher área",
            chooseAgain: "Escolher outra área",
            purpose: "Escolha o que observar",
            stop: "Parar de observar",
            watchAgain: "Observar de novo",
            permissionHint: "Observar lê a área escolhida no próprio Mac, por isso precisa de Gravação de Tela. Nada sai do seu Mac.",
            allowAccess: "Permitir Gravação de Tela",
            tellMe: "Avisar",
            changes: "Quando mudar",
            settles: "Quando parar de mudar",
            contains: "Quando mostrar",
            reaches: "Quando o número chegar a",
            settlesHint: "Depois de mudar, precisa ficar parado por 30 segundos.",
            textPlaceholder: "Texto, como Concluído",
            numberPlaceholder: "Número, como 100",
            noText: "Sem texto",
            inIsland: "Mostrar na ilha",
            automatic: "Automático",
            hidden: "A janela está oculta. A observação continua quando ela voltar.",
            changedNotice: "Mudou",
            settledNotice: "Parou de mudar",
            showsFormat: "Mostra %@",
            reachedFormat: "Chegou a %@",
            closedNotice: "A janela fechou",
            sinceFormat: "Observando desde %@",
            sound: "Tocar um som")
        case .es: return NotchWatchStrings(
            title: "Observar",
            description: "Convierte cualquier parte de cualquier ventana en una actividad en directo en el Dynamic Island, con un aviso cuando cambie, termine o muestre lo que esperas.",
            setupHint: "Elige cualquier parte de una ventana, como una barra de progreso, el estado de una compilación o un marcador. La isla la lee por ti y te avisa cuando cambia.",
            choose: "Elegir área",
            chooseAgain: "Elegir otra área",
            purpose: "Elige qué observar",
            stop: "Dejar de observar",
            watchAgain: "Observar de nuevo",
            permissionHint: "Observar lee el área elegida en tu Mac, por eso necesita Grabación de pantalla. Nada sale de tu Mac.",
            allowAccess: "Permitir Grabación de pantalla",
            tellMe: "Avisar",
            changes: "Cuando cambie",
            settles: "Cuando deje de cambiar",
            contains: "Cuando muestre",
            reaches: "Cuando el número llegue a",
            settlesHint: "Después de cambiar, debe quedarse quieta 30 segundos.",
            textPlaceholder: "Texto, como Listo",
            numberPlaceholder: "Número, como 100",
            noText: "Sin texto",
            inIsland: "Mostrar en la isla",
            automatic: "Automático",
            hidden: "La ventana está oculta. La observación sigue cuando vuelva.",
            changedNotice: "Ha cambiado",
            settledNotice: "Ha dejado de cambiar",
            showsFormat: "Muestra %@",
            reachedFormat: "Ha llegado a %@",
            closedNotice: "La ventana se cerró",
            sinceFormat: "Observando desde las %@",
            sound: "Reproducir un sonido")
        case .sk: return NotchWatchStrings(
            title: "Sledovať",
            description: "Premeňte ľubovoľnú časť ľubovoľného okna na živú aktivitu v Dynamic Island s upozornením, keď sa zmení, skončí alebo ukáže, na čo čakáte.",
            setupHint: "Vyberte ľubovoľnú časť okna, napríklad priebeh, stav zostavy alebo skóre. Ostrov ju za vás číta a upozorní vás, keď sa zmení.",
            choose: "Vybrať oblasť",
            chooseAgain: "Vybrať inú oblasť",
            purpose: "Vyberte, čo sledovať",
            stop: "Prestať sledovať",
            watchAgain: "Sledovať znova",
            permissionHint: "Sledovanie číta vybranú oblasť priamo v Macu, preto potrebuje Nahrávanie obrazovky. Nič neopustí váš Mac.",
            allowAccess: "Povoliť Nahrávanie obrazovky",
            tellMe: "Upozorniť",
            changes: "Keď sa zmení",
            settles: "Keď sa prestane meniť",
            contains: "Keď ukáže",
            reaches: "Keď číslo dosiahne",
            settlesHint: "Po zmene musí zostať 30 sekúnd bez pohybu.",
            textPlaceholder: "Text, napríklad Hotovo",
            numberPlaceholder: "Číslo, napríklad 100",
            noText: "Bez textu",
            inIsland: "Zobraziť na ostrove",
            automatic: "Automaticky",
            hidden: "Okno je skryté. Sledovanie pokračuje, keď sa vráti.",
            changedNotice: "Zmenilo sa",
            settledNotice: "Prestalo sa meniť",
            showsFormat: "Ukazuje %@",
            reachedFormat: "Dosiahlo %@",
            closedNotice: "Okno sa zatvorilo",
            sinceFormat: "Sleduje sa od %@",
            sound: "Prehrať zvuk")
        case .de: return NotchWatchStrings(
            title: "Beobachten",
            description: "Mach jeden Teil eines beliebigen Fensters zu einer Live-Aktivität im Dynamic Island, mit Hinweis, wenn er sich ändert, fertig ist oder zeigt, worauf du wartest.",
            setupHint: "Wähle einen Teil eines Fensters, etwa einen Fortschrittsbalken, den Status eines Builds oder einen Spielstand. Die Insel liest ihn für dich und meldet sich, wenn er sich ändert.",
            choose: "Bereich wählen",
            chooseAgain: "Anderen Bereich wählen",
            purpose: "Wähle, was beobachtet wird",
            stop: "Beobachten beenden",
            watchAgain: "Erneut beobachten",
            permissionHint: "Beobachten liest den gewählten Bereich direkt auf dem Mac und braucht dafür die Bildschirmaufnahme. Nichts verlässt deinen Mac.",
            allowAccess: "Bildschirmaufnahme erlauben",
            tellMe: "Melden",
            changes: "Wenn er sich ändert",
            settles: "Wenn er sich nicht mehr ändert",
            contains: "Wenn er zeigt",
            reaches: "Wenn die Zahl erreicht",
            settlesHint: "Nach einer Änderung muss er 30 Sekunden lang still bleiben.",
            textPlaceholder: "Text, etwa Fertig",
            numberPlaceholder: "Zahl, etwa 100",
            noText: "Kein Text",
            inIsland: "Auf der Insel zeigen",
            automatic: "Automatisch",
            hidden: "Das Fenster ist ausgeblendet. Das Beobachten geht weiter, sobald es zurück ist.",
            changedNotice: "Hat sich geändert",
            settledNotice: "Ändert sich nicht mehr",
            showsFormat: "Zeigt %@",
            reachedFormat: "Hat %@ erreicht",
            closedNotice: "Das Fenster wurde geschlossen",
            sinceFormat: "Beobachtet seit %@",
            sound: "Ton abspielen")
        case .fr: return NotchWatchStrings(
            title: "Surveiller",
            description: "Transformez n’importe quelle partie d’une fenêtre en activité en direct dans le Dynamic Island, avec une alerte quand elle change, se termine ou affiche ce que vous attendez.",
            setupHint: "Choisissez une partie d’une fenêtre, comme une barre de progression, l’état d’une compilation ou un score. L’île la lit pour vous et vous prévient quand elle change.",
            choose: "Choisir une zone",
            chooseAgain: "Choisir une autre zone",
            purpose: "Choisissez quoi surveiller",
            stop: "Arrêter la surveillance",
            watchAgain: "Surveiller à nouveau",
            permissionHint: "Surveiller lit la zone choisie sur votre Mac, il lui faut donc l’Enregistrement de l’écran. Rien ne quitte votre Mac.",
            allowAccess: "Autoriser l’Enregistrement de l’écran",
            tellMe: "Prévenir",
            changes: "Quand elle change",
            settles: "Quand elle ne change plus",
            contains: "Quand elle affiche",
            reaches: "Quand le nombre atteint",
            settlesHint: "Après un changement, elle doit rester immobile 30 secondes.",
            textPlaceholder: "Texte, comme Terminé",
            numberPlaceholder: "Nombre, comme 100",
            noText: "Aucun texte",
            inIsland: "Afficher dans l’île",
            automatic: "Automatique",
            hidden: "La fenêtre est masquée. La surveillance reprend à son retour.",
            changedNotice: "Elle a changé",
            settledNotice: "Elle ne change plus",
            showsFormat: "Elle affiche %@",
            reachedFormat: "Elle a atteint %@",
            closedNotice: "La fenêtre s’est fermée",
            sinceFormat: "Surveillée depuis %@",
            sound: "Jouer un son")
        case .it: return NotchWatchStrings(
            title: "Osserva",
            description: "Trasforma qualsiasi parte di qualsiasi finestra in un’attività dal vivo nel Dynamic Island, con un avviso quando cambia, finisce o mostra ciò che aspetti.",
            setupHint: "Scegli una parte di una finestra, come una barra di avanzamento, lo stato di una build o un punteggio. L’isola la legge per te e ti avvisa quando cambia.",
            choose: "Scegli area",
            chooseAgain: "Scegli un’altra area",
            purpose: "Scegli cosa osservare",
            stop: "Smetti di osservare",
            watchAgain: "Osserva di nuovo",
            permissionHint: "Osserva legge l’area scelta direttamente sul Mac, quindi serve la Registrazione schermo. Nulla lascia il tuo Mac.",
            allowAccess: "Consenti Registrazione schermo",
            tellMe: "Avvisa",
            changes: "Quando cambia",
            settles: "Quando smette di cambiare",
            contains: "Quando mostra",
            reaches: "Quando il numero arriva a",
            settlesHint: "Dopo un cambiamento, deve restare ferma per 30 secondi.",
            textPlaceholder: "Testo, come Fatto",
            numberPlaceholder: "Numero, come 100",
            noText: "Nessun testo",
            inIsland: "Mostra nell’isola",
            automatic: "Automatico",
            hidden: "La finestra è nascosta. L’osservazione riprende quando ritorna.",
            changedNotice: "È cambiata",
            settledNotice: "Ha smesso di cambiare",
            showsFormat: "Mostra %@",
            reachedFormat: "È arrivata a %@",
            closedNotice: "La finestra si è chiusa",
            sinceFormat: "Osservata dalle %@",
            sound: "Riproduci un suono")
        case .ru: return NotchWatchStrings(
            title: "Наблюдение",
            description: "Превратите любую часть любого окна в живую активность в Dynamic Island с оповещением, когда она изменится, завершится или покажет то, чего вы ждёте.",
            setupHint: "Выберите любую часть окна, например индикатор выполнения, статус сборки или счёт. Остров прочитает её за вас и сообщит, когда она изменится.",
            choose: "Выбрать область",
            chooseAgain: "Выбрать другую область",
            purpose: "Выберите, за чем наблюдать",
            stop: "Остановить",
            watchAgain: "Наблюдать снова",
            permissionHint: "Наблюдение читает выбранную область прямо на Mac, поэтому нужна Запись экрана. Ничего не покидает ваш Mac.",
            allowAccess: "Разрешить Запись экрана",
            tellMe: "Сообщить",
            changes: "Когда изменится",
            settles: "Когда перестанет меняться",
            contains: "Когда покажет",
            reaches: "Когда число дойдёт до",
            settlesHint: "После изменения она должна оставаться неподвижной 30 секунд.",
            textPlaceholder: "Текст, например Готово",
            numberPlaceholder: "Число, например 100",
            noText: "Нет текста",
            inIsland: "Показывать на острове",
            automatic: "Автоматически",
            hidden: "Окно скрыто. Наблюдение продолжится, когда оно вернётся.",
            changedNotice: "Изменилось",
            settledNotice: "Перестало меняться",
            showsFormat: "Показывает %@",
            reachedFormat: "Дошло до %@",
            closedNotice: "Окно закрылось",
            sinceFormat: "Наблюдение с %@",
            sound: "Воспроизвести звук")
        case .tr: return NotchWatchStrings(
            title: "İzle",
            description: "Herhangi bir pencerenin herhangi bir bölümünü Dynamic Island’da canlı bir etkinliğe dönüştürün. Değiştiğinde, bittiğinde ya da beklediğinizi gösterdiğinde haber verir.",
            setupHint: "Bir pencerenin herhangi bir bölümünü seçin, örneğin bir ilerleme çubuğu, bir derlemenin durumu ya da bir skor. Ada onu sizin için okur ve değiştiğinde haber verir.",
            choose: "Alan Seç",
            chooseAgain: "Başka Alan Seç",
            purpose: "Neyin izleneceğini seçin",
            stop: "İzlemeyi Durdur",
            watchAgain: "Yeniden İzle",
            permissionHint: "İzle, seçtiğiniz alanı Mac’inizde okur, bu yüzden Ekran Kaydı gerekir. Hiçbir şey Mac’inizden çıkmaz.",
            allowAccess: "Ekran Kaydına İzin Ver",
            tellMe: "Haber ver",
            changes: "Değiştiğinde",
            settles: "Değişmeyi bıraktığında",
            contains: "Şunu gösterdiğinde",
            reaches: "Sayı şuna ulaştığında",
            settlesHint: "Değiştikten sonra 30 saniye boyunca sabit kalmalıdır.",
            textPlaceholder: "Metin, örneğin Bitti",
            numberPlaceholder: "Sayı, örneğin 100",
            noText: "Metin yok",
            inIsland: "Adada göster",
            automatic: "Otomatik",
            hidden: "Pencere gizli. Geri geldiğinde izleme devam eder.",
            changedNotice: "Değişti",
            settledNotice: "Değişmeyi bıraktı",
            showsFormat: "Gösteriyor: %@",
            reachedFormat: "Ulaştı: %@",
            closedNotice: "Pencere kapandı",
            sinceFormat: "İzleniyor, başlangıç: %@",
            sound: "Ses çal")
        case .ja: return NotchWatchStrings(
            title: "ウォッチ",
            description: "どのウインドウのどの部分でも Dynamic Island のライブアクティビティにして、変化したとき、終わったとき、待っている内容が表示されたときに知らせます。",
            setupHint: "進行状況バー、ビルドの状態、スコアなど、ウインドウの好きな部分を選んでください。アイランドが代わりに読み取り、変化したら知らせます。",
            choose: "範囲を選択",
            chooseAgain: "別の範囲を選択",
            purpose: "ウォッチする範囲を選択",
            stop: "ウォッチを停止",
            watchAgain: "もう一度ウォッチ",
            permissionHint: "ウォッチは選んだ範囲を Mac 上で読み取るため、画面収録が必要です。データが Mac の外に出ることはありません。",
            allowAccess: "画面収録を許可",
            tellMe: "通知",
            changes: "変化したとき",
            settles: "変化が止まったとき",
            contains: "次を表示したとき",
            reaches: "数値が次に達したとき",
            settlesHint: "変化したあと 30 秒間止まっている必要があります。",
            textPlaceholder: "テキスト、例: 完了",
            numberPlaceholder: "数値、例: 100",
            noText: "テキストなし",
            inIsland: "アイランドに表示",
            automatic: "自動",
            hidden: "ウインドウが隠れています。戻るとウォッチを続けます。",
            changedNotice: "変化しました",
            settledNotice: "変化が止まりました",
            showsFormat: "%@ と表示されました",
            reachedFormat: "%@ に達しました",
            closedNotice: "ウインドウが閉じました",
            sinceFormat: "%@ からウォッチ中",
            sound: "サウンドを再生")
        case .ko: return NotchWatchStrings(
            title: "지켜보기",
            description: "어떤 윈도우의 어떤 부분이든 Dynamic Island의 실시간 현황으로 만들고, 바뀌거나 끝나거나 기다리던 내용이 나타나면 알려 줍니다.",
            setupHint: "진행 막대, 빌드 상태, 점수처럼 윈도우의 원하는 부분을 선택하세요. 아일랜드가 대신 읽고 바뀌면 알려 줍니다.",
            choose: "영역 선택",
            chooseAgain: "다른 영역 선택",
            purpose: "지켜볼 영역 선택",
            stop: "지켜보기 중단",
            watchAgain: "다시 지켜보기",
            permissionHint: "지켜보기는 선택한 영역을 Mac에서 직접 읽기 때문에 화면 기록 권한이 필요합니다. 아무것도 Mac 밖으로 나가지 않습니다.",
            allowAccess: "화면 기록 허용",
            tellMe: "알림",
            changes: "바뀌면",
            settles: "더 이상 바뀌지 않으면",
            contains: "다음이 보이면",
            reaches: "숫자가 다음에 도달하면",
            settlesHint: "바뀐 뒤 30초 동안 그대로 있어야 합니다.",
            textPlaceholder: "텍스트, 예: 완료",
            numberPlaceholder: "숫자, 예: 100",
            noText: "텍스트 없음",
            inIsland: "아일랜드에 표시",
            automatic: "자동",
            hidden: "윈도우가 가려져 있습니다. 다시 나타나면 계속 지켜봅니다.",
            changedNotice: "바뀌었습니다",
            settledNotice: "더 이상 바뀌지 않습니다",
            showsFormat: "%@ 표시됨",
            reachedFormat: "%@에 도달함",
            closedNotice: "윈도우가 닫혔습니다",
            sinceFormat: "%@부터 지켜보는 중",
            sound: "사운드 재생")
        case .uk: return NotchWatchStrings(
            title: "Спостереження",
            description: "Перетворіть будь-яку частину будь-якого вікна на живу активність у Dynamic Island зі сповіщенням, коли вона зміниться, завершиться або покаже те, на що ви чекаєте.",
            setupHint: "Виберіть будь-яку частину вікна, наприклад індикатор поступу, стан збірки чи рахунок. Острів прочитає її за вас і повідомить, коли вона зміниться.",
            choose: "Вибрати область",
            chooseAgain: "Вибрати іншу область",
            purpose: "Виберіть, за чим спостерігати",
            stop: "Зупинити",
            watchAgain: "Спостерігати знову",
            permissionHint: "Спостереження читає вибрану область просто на Mac, тому потрібен Запис екрана. Ніщо не залишає ваш Mac.",
            allowAccess: "Дозволити Запис екрана",
            tellMe: "Повідомити",
            changes: "Коли зміниться",
            settles: "Коли перестане змінюватися",
            contains: "Коли покаже",
            reaches: "Коли число досягне",
            settlesHint: "Після зміни вона має лишатися нерухомою 30 секунд.",
            textPlaceholder: "Текст, наприклад Готово",
            numberPlaceholder: "Число, наприклад 100",
            noText: "Немає тексту",
            inIsland: "Показувати на острові",
            automatic: "Автоматично",
            hidden: "Вікно приховане. Спостереження продовжиться, коли воно повернеться.",
            changedNotice: "Змінилося",
            settledNotice: "Перестало змінюватися",
            showsFormat: "Показує %@",
            reachedFormat: "Досягло %@",
            closedNotice: "Вікно закрилося",
            sinceFormat: "Спостереження з %@",
            sound: "Відтворити звук")
        case .zhHans: return NotchWatchStrings(
            title: "观察",
            description: "把任意窗口的任意部分变成Dynamic Island中的实时活动，在它变化、完成或出现你等待的内容时提醒你。",
            setupHint: "选择窗口的任意部分，比如进度条、构建状态或比分。岛会替你读取，并在它变化时提醒你。",
            choose: "选择区域",
            chooseAgain: "选择其他区域",
            purpose: "选择要观察的内容",
            stop: "停止观察",
            watchAgain: "再次观察",
            permissionHint: "观察会在 Mac 上读取所选区域，因此需要屏幕录制权限。任何内容都不会离开你的 Mac。",
            allowAccess: "允许屏幕录制",
            tellMe: "提醒",
            changes: "变化时",
            settles: "停止变化时",
            contains: "显示以下内容时",
            reaches: "数字达到以下值时",
            settlesHint: "变化之后需要保持 30 秒不动。",
            textPlaceholder: "文本，例如 完成",
            numberPlaceholder: "数字，例如 100",
            noText: "无文本",
            inIsland: "在岛上显示",
            automatic: "自动",
            hidden: "窗口已隐藏。它回来后会继续观察。",
            changedNotice: "已变化",
            settledNotice: "已停止变化",
            showsFormat: "显示 %@",
            reachedFormat: "已达到 %@",
            closedNotice: "窗口已关闭",
            sinceFormat: "自 %@ 起观察",
            sound: "播放声音")
        case .zhTW: return NotchWatchStrings(
            title: "觀察",
            description: "把任何視窗的任何部分變成Dynamic Island中的即時動態，在它變化、完成或出現你等待的內容時提醒你。",
            setupHint: "選擇視窗的任何部分，例如進度列、建置狀態或比數。島會替你讀取，並在它變化時提醒你。",
            choose: "選擇區域",
            chooseAgain: "選擇其他區域",
            purpose: "選擇要觀察的內容",
            stop: "停止觀察",
            watchAgain: "再次觀察",
            permissionHint: "觀察會在 Mac 上讀取所選區域，因此需要螢幕錄製權限。任何內容都不會離開你的 Mac。",
            allowAccess: "允許螢幕錄製",
            tellMe: "提醒",
            changes: "變化時",
            settles: "停止變化時",
            contains: "顯示以下內容時",
            reaches: "數字達到以下數值時",
            settlesHint: "變化之後需要維持 30 秒不動。",
            textPlaceholder: "文字，例如 完成",
            numberPlaceholder: "數字，例如 100",
            noText: "沒有文字",
            inIsland: "在島上顯示",
            automatic: "自動",
            hidden: "視窗已隱藏。它回來後會繼續觀察。",
            changedNotice: "已變化",
            settledNotice: "已停止變化",
            showsFormat: "顯示 %@",
            reachedFormat: "已達到 %@",
            closedNotice: "視窗已關閉",
            sinceFormat: "自 %@ 起觀察",
            sound: "播放聲音")
        case .zhHK: return NotchWatchStrings(
            title: "觀察",
            description: "把任何視窗的任何部分變成Dynamic Island中的即時動態，在它變化、完成或出現你等待的內容時提醒你。",
            setupHint: "選擇視窗的任何部分，例如進度列、建置狀態或比數。島會替你讀取，並在它變化時提醒你。",
            choose: "選擇區域",
            chooseAgain: "選擇其他區域",
            purpose: "選擇要觀察的內容",
            stop: "停止觀察",
            watchAgain: "再次觀察",
            permissionHint: "觀察會在 Mac 上讀取所選區域，因此需要螢幕錄影權限。任何內容都不會離開你的 Mac。",
            allowAccess: "允許螢幕錄影",
            tellMe: "提醒",
            changes: "變化時",
            settles: "停止變化時",
            contains: "顯示以下內容時",
            reaches: "數字達到以下數值時",
            settlesHint: "變化之後需要維持 30 秒不動。",
            textPlaceholder: "文字，例如 完成",
            numberPlaceholder: "數字，例如 100",
            noText: "沒有文字",
            inIsland: "在島上顯示",
            automatic: "自動",
            hidden: "視窗已隱藏。它回來後會繼續觀察。",
            changedNotice: "已變化",
            settledNotice: "已停止變化",
            showsFormat: "顯示 %@",
            reachedFormat: "已達到 %@",
            closedNotice: "視窗已關閉",
            sinceFormat: "自 %@ 起觀察",
            sound: "播放聲音")
        }
    }
}
