// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchCalendarStrings {
    let title: String
    let description: String
    let permission: String
    let allow: String
    let denied: String
    let settings: String
    let empty: String
    let next: String
    let ongoing: String
    let allDay: String
    let untitled: String
    let openCalendar: String
    let week: String
    let today: String
    let requestFailed: String
    let previousMonth: String
    let nextMonth: String
    let previousWeek: String
    let nextWeek: String
    /// The month grid, offered from the week strip of a short island.
    let month: String
    let emptyDay: String
    let hasEvents: String
    let countdown: String
    let countdownHint: String
    /// How long before a start the countdown appears, chosen events included.
    let countdownLead: String
    /// An event's menu in the island, to count down to that event alone.
    let addCountdown: String
    let removeCountdown: String
    /// Counts the event under way down to its end.
    let timeLeft: String
    let timeLeftHint: String
    /// Heads the per-calendar checkboxes in Settings.
    let calendars: String
    /// Before the time of a later event beside the closed island's clock: "then 2:15".
    let then: String
    /// Heads the countdowns on the Calendar page when two or more start at once.
    let together: String
    /// Joins an event's video call from the island.
    let join: String
    /// In the Join button's menu: copies the call's link.
    let copyLink: String
    /// In the Join button's menu: opens the call's page instead of its app.
    let openInBrowser: String
    /// Lets a calendar heads-up open the island over a full-screen app.
    let announceInFullscreen: String
    let announceInFullscreenHint: String
}

extension FeatureStrings {
    static func notchCalendar(_ language: AppLanguage) -> NotchCalendarStrings {
        switch language {
        case .enUS: return NotchCalendarStrings(
            title: "Calendar",
            description: "Browse the month and your upcoming appointments in the Dynamic Island.",
            permission: "Read your calendars to show upcoming appointments. Events stay on this Mac.",
            allow: "Allow Calendar Access",
            denied: "Allow calendar access in System Settings to see your appointments.",
            settings: "Open System Settings",
            empty: "No upcoming appointments",
            next: "Up next",
            ongoing: "Happening now",
            allDay: "All day",
            untitled: "Untitled event",
            openCalendar: "Open Calendar",
            week: "Next 7 days",
            today: "Today",
            requestFailed: "Could not request calendar access. Please try again.",
            previousMonth: "Previous month",
            nextMonth: "Next month",
            previousWeek: "Previous week",
            nextWeek: "Next week",
            month: "Month",
            emptyDay: "No appointments on this day",
            hasEvents: "Has appointments",
            countdown: "Event countdown",
            countdownHint: "Show every timed event in the closed island before it starts. To count down to only some, turn this off and right-click them on the island’s Calendar page. Titles may appear in screen captures.",
            countdownLead: "Time before event",
            addCountdown: "Add Countdown",
            removeCountdown: "Remove Countdown",
            timeLeft: "Time left in current event",
            timeLeftHint: "Show a timed event in progress in the closed island during the hour before it ends. Its title may appear in screen captures.",
            calendars: "Calendars shown",
            then: "then",
            together: "Starting at the same time",
            join: "Join",
            copyLink: "Copy Link",
            openInBrowser: "Open in Browser",
            announceInFullscreen: "Announce in full screen",
            announceInFullscreenHint: "Show calendar heads-ups even over a full-screen app. Otherwise they wait until you leave full screen.")
        case .ptBR: return NotchCalendarStrings(
            title: "Calendário",
            description: "Veja o mês e seus próximos compromissos no Dynamic Island.",
            permission: "Leia seus calendários para mostrar os próximos compromissos. Os eventos ficam neste Mac.",
            allow: "Permitir acesso ao calendário",
            denied: "Permita o acesso ao calendário nos Ajustes do Sistema para ver seus compromissos.",
            settings: "Abrir Ajustes do Sistema",
            empty: "Nenhum compromisso por enquanto",
            next: "Próximo compromisso",
            ongoing: "Acontecendo agora",
            allDay: "Dia inteiro",
            untitled: "Evento sem título",
            openCalendar: "Abrir calendário",
            week: "Próximos 7 dias",
            today: "Hoje",
            requestFailed: "Não foi possível pedir acesso ao calendário. Tente novamente.",
            previousMonth: "Mês anterior",
            nextMonth: "Próximo mês",
            previousWeek: "Semana anterior",
            nextWeek: "Próxima semana",
            month: "Mês",
            emptyDay: "Nenhum compromisso neste dia",
            hasEvents: "Tem compromissos",
            countdown: "Contagem para o próximo evento",
            countdownHint: "Mostra cada evento com horário no notch antes do início. Para contar só alguns, desligue esta opção e clique com o botão direito neles na página Calendário do notch. Os títulos podem aparecer em capturas de tela.",
            countdownLead: "Tempo antes do evento",
            addCountdown: "Adicionar contagem regressiva",
            removeCountdown: "Remover contagem regressiva",
            timeLeft: "Tempo restante do evento atual",
            timeLeftHint: "Mostra o evento com horário em andamento no notch durante a última hora antes de terminar. O título pode aparecer em capturas de tela.",
            calendars: "Calendários exibidos",
            then: "depois",
            together: "Começam ao mesmo tempo",
            join: "Entrar",
            copyLink: "Copiar link",
            openInBrowser: "Abrir no navegador",
            announceInFullscreen: "Avisar em tela cheia",
            announceInFullscreenHint: "Mostra os avisos do calendário mesmo sobre um app em tela cheia. Caso contrário, eles esperam você sair da tela cheia.")
        case .es: return NotchCalendarStrings(
            title: "Calendario",
            description: "Consulta el mes y tus próximas citas en el Dynamic Island.",
            permission: "Lee tus calendarios para mostrar las próximas citas. Los eventos se quedan en este Mac.",
            allow: "Permitir acceso al calendario",
            denied: "Permite el acceso al calendario en Ajustes del Sistema para ver tus citas.",
            settings: "Abrir Ajustes del Sistema",
            empty: "No hay próximas citas",
            next: "A continuación",
            ongoing: "En curso",
            allDay: "Todo el día",
            untitled: "Evento sin título",
            openCalendar: "Abrir Calendario",
            week: "Próximos 7 días",
            today: "Hoy",
            requestFailed: "No se pudo solicitar acceso al calendario. Inténtalo de nuevo.",
            previousMonth: "Mes anterior",
            nextMonth: "Mes siguiente",
            previousWeek: "Semana anterior",
            nextWeek: "Semana siguiente",
            month: "Mes",
            emptyDay: "No hay citas este día",
            hasEvents: "Tiene citas",
            countdown: "Cuenta atrás para el próximo evento",
            countdownHint: "Muestra cada evento con hora en el notch antes de que empiece. Para contar solo algunos, desactiva esta opción y haz clic derecho en ellos en la página Calendario del notch. Los títulos pueden aparecer en capturas de pantalla.",
            countdownLead: "Tiempo antes del evento",
            addCountdown: "Añadir cuenta atrás",
            removeCountdown: "Quitar cuenta atrás",
            timeLeft: "Tiempo restante del evento actual",
            timeLeftHint: "Muestra el evento con hora en curso en el notch durante la última hora antes de que termine. El título puede aparecer en capturas de pantalla.",
            calendars: "Calendarios mostrados",
            then: "luego",
            together: "Empiezan a la vez",
            join: "Unirse",
            copyLink: "Copiar enlace",
            openInBrowser: "Abrir en el navegador",
            announceInFullscreen: "Avisar en pantalla completa",
            announceInFullscreenHint: "Muestra los avisos del calendario incluso sobre una app en pantalla completa. Si no, esperan a que salgas de la pantalla completa.")
        case .sk: return NotchCalendarStrings(
            title: "Kalendár",
            description: "Prezerajte mesiac a nadchádzajúce stretnutia v Dynamic Island.",
            permission: "Číta vaše kalendáre, aby zobrazil nadchádzajúce stretnutia. Udalosti zostávajú na tomto Macu.",
            allow: "Povoliť prístup ku kalendáru",
            denied: "Ak chcete vidieť svoje stretnutia, povoľte prístup ku kalendáru v Systémových nastaveniach.",
            settings: "Otvoriť Systémové nastavenia",
            empty: "Žiadne nadchádzajúce stretnutia",
            next: "Nasleduje",
            ongoing: "Prebieha teraz",
            allDay: "Celý deň",
            untitled: "Udalosť bez názvu",
            openCalendar: "Otvoriť Kalendár",
            week: "Nasledujúcich 7 dní",
            today: "Dnes",
            requestFailed: "Nepodarilo sa požiadať o prístup ku kalendáru. Skúste to znova.",
            previousMonth: "Predchádzajúci mesiac",
            nextMonth: "Nasledujúci mesiac",
            previousWeek: "Predchádzajúci týždeň",
            nextWeek: "Nasledujúci týždeň",
            month: "Mesiac",
            emptyDay: "V tento deň nemáte žiadne stretnutia",
            hasEvents: "Má stretnutia",
            countdown: "Odpočítavanie do udalosti",
            countdownHint: "Zobrazí každú udalosť s časom v zatvorenom výreze pred jej začiatkom. Ak chcete odpočítavať len niektoré, vypnite túto voľbu a kliknite na ne pravým tlačidlom na stránke Kalendár vo výreze. Názvy sa môžu zobraziť na snímkach obrazovky.",
            countdownLead: "Čas pred udalosťou",
            addCountdown: "Pridať odpočítavanie",
            removeCountdown: "Odstrániť odpočítavanie",
            timeLeft: "Zostávajúci čas aktuálnej udalosti",
            timeLeftHint: "Zobrazí prebiehajúcu udalosť s časom v zatvorenom výreze počas hodiny pred jej koncom. Názov sa môže zobraziť na snímkach obrazovky.",
            calendars: "Zobrazené kalendáre",
            then: "potom",
            together: "Začínajú naraz",
            join: "Pripojiť sa",
            copyLink: "Kopírovať odkaz",
            openInBrowser: "Otvoriť v prehliadači",
            announceInFullscreen: "Oznamovať na celej obrazovke",
            announceInFullscreenHint: "Zobrazí upozornenia kalendára aj nad aplikáciou na celej obrazovke. Inak počkajú, kým celú obrazovku opustíte.")
        case .de: return NotchCalendarStrings(
            title: "Kalender",
            description: "Den Monat und deine nächsten Termine im Dynamic Island ansehen.",
            permission: "Liest deine Kalender, um kommende Termine anzuzeigen. Die Ereignisse bleiben auf diesem Mac.",
            allow: "Kalenderzugriff erlauben",
            denied: "Erlaube den Kalenderzugriff in den Systemeinstellungen, um deine Termine zu sehen.",
            settings: "Systemeinstellungen öffnen",
            empty: "Keine anstehenden Termine",
            next: "Nächster Termin",
            ongoing: "Findet gerade statt",
            allDay: "Ganztägig",
            untitled: "Ereignis ohne Titel",
            openCalendar: "Kalender öffnen",
            week: "Nächste 7 Tage",
            today: "Heute",
            requestFailed: "Der Kalenderzugriff konnte nicht angefordert werden. Versuche es erneut.",
            previousMonth: "Vorheriger Monat",
            nextMonth: "Nächster Monat",
            previousWeek: "Vorherige Woche",
            nextWeek: "Nächste Woche",
            month: "Monat",
            emptyDay: "Keine Termine an diesem Tag",
            hasEvents: "Termine vorhanden",
            countdown: "Countdown zum nächsten Termin",
            countdownHint: "Zeigt jeden Termin mit Uhrzeit vor Beginn in der geschlossenen Insel. Um nur einige herunterzuzählen, diese Option ausschalten und die Termine auf der Kalenderseite der Insel rechtsklicken. Titel können in Bildschirmaufnahmen erscheinen.",
            countdownLead: "Zeit vor dem Termin",
            addCountdown: "Countdown hinzufügen",
            removeCountdown: "Countdown entfernen",
            timeLeft: "Restzeit des aktuellen Termins",
            timeLeftHint: "Zeigt einen laufenden Termin mit Uhrzeit in der geschlossenen Insel in der Stunde vor seinem Ende. Der Titel kann in Bildschirmaufnahmen erscheinen.",
            calendars: "Angezeigte Kalender",
            then: "dann",
            together: "Beginnen gleichzeitig",
            join: "Beitreten",
            copyLink: "Link kopieren",
            openInBrowser: "Im Browser öffnen",
            announceInFullscreen: "Im Vollbild ankündigen",
            announceInFullscreenHint: "Zeigt Kalenderhinweise auch über einer Vollbild-App. Sonst warten sie, bis du das Vollbild verlässt.")
        case .fr: return NotchCalendarStrings(
            title: "Calendrier",
            description: "Consultez le mois et vos prochains rendez-vous dans le Dynamic Island.",
            permission: "Lit vos calendriers pour afficher les prochains rendez-vous. Les événements restent sur ce Mac.",
            allow: "Autoriser l’accès au calendrier",
            denied: "Autorisez l’accès au calendrier dans les Réglages Système pour voir vos rendez-vous.",
            settings: "Ouvrir les Réglages Système",
            empty: "Aucun rendez-vous à venir",
            next: "À venir",
            ongoing: "En cours",
            allDay: "Toute la journée",
            untitled: "Événement sans titre",
            openCalendar: "Ouvrir Calendrier",
            week: "7 prochains jours",
            today: "Aujourd’hui",
            requestFailed: "Impossible de demander l’accès au calendrier. Réessayez.",
            previousMonth: "Mois précédent",
            nextMonth: "Mois suivant",
            previousWeek: "Semaine précédente",
            nextWeek: "Semaine suivante",
            month: "Mois",
            emptyDay: "Aucun rendez-vous ce jour-là",
            hasEvents: "Rendez-vous prévus",
            countdown: "Compte à rebours du prochain événement",
            countdownHint: "Affiche chaque événement avec une heure dans l’encoche avant son début. Pour n’en décompter que certains, désactivez cette option et faites un clic droit sur eux dans la page Calendrier de l’encoche. Les titres peuvent apparaître dans les captures d’écran.",
            countdownLead: "Délai avant l’événement",
            addCountdown: "Ajouter un compte à rebours",
            removeCountdown: "Retirer le compte à rebours",
            timeLeft: "Temps restant de l’événement en cours",
            timeLeftHint: "Affiche l’événement en cours avec une heure dans l’encoche pendant l’heure qui précède sa fin. Son titre peut apparaître dans les captures d’écran.",
            calendars: "Calendriers affichés",
            then: "puis",
            together: "Commencent en même temps",
            join: "Rejoindre",
            copyLink: "Copier le lien",
            openInBrowser: "Ouvrir dans le navigateur",
            announceInFullscreen: "Annoncer en plein écran",
            announceInFullscreenHint: "Affiche les alertes du calendrier même au-dessus d’une app en plein écran. Sinon, elles attendent que vous quittiez le plein écran.")
        case .it: return NotchCalendarStrings(
            title: "Calendario",
            description: "Consulta il mese e i prossimi appuntamenti nel Dynamic Island.",
            permission: "Legge i calendari per mostrare i prossimi appuntamenti. Gli eventi restano su questo Mac.",
            allow: "Consenti accesso al calendario",
            denied: "Consenti l’accesso al calendario in Impostazioni di Sistema per vedere gli appuntamenti.",
            settings: "Apri Impostazioni di Sistema",
            empty: "Nessun appuntamento in programma",
            next: "Prossimo appuntamento",
            ongoing: "In corso",
            allDay: "Tutto il giorno",
            untitled: "Evento senza titolo",
            openCalendar: "Apri Calendario",
            week: "Prossimi 7 giorni",
            today: "Oggi",
            requestFailed: "Impossibile richiedere l’accesso al calendario. Riprova.",
            previousMonth: "Mese precedente",
            nextMonth: "Mese successivo",
            previousWeek: "Settimana precedente",
            nextWeek: "Settimana successiva",
            month: "Mese",
            emptyDay: "Nessun appuntamento in questo giorno",
            hasEvents: "Appuntamenti presenti",
            countdown: "Conto alla rovescia per il prossimo evento",
            countdownHint: "Mostra ogni evento con un orario nell’isola chiusa prima che inizi. Per contarne solo alcuni, disattiva questa opzione e fai clic destro su di essi nella pagina Calendario dell’isola. I titoli possono apparire nelle acquisizioni dello schermo.",
            countdownLead: "Tempo prima dell’evento",
            addCountdown: "Aggiungi conto alla rovescia",
            removeCountdown: "Rimuovi conto alla rovescia",
            timeLeft: "Tempo rimanente dell’evento in corso",
            timeLeftHint: "Mostra l’evento in corso con un orario nell’isola chiusa durante l’ultima ora prima della fine. Il titolo può apparire nelle acquisizioni dello schermo.",
            calendars: "Calendari mostrati",
            then: "poi",
            together: "Iniziano insieme",
            join: "Partecipa",
            copyLink: "Copia link",
            openInBrowser: "Apri nel browser",
            announceInFullscreen: "Avvisa a schermo intero",
            announceInFullscreenHint: "Mostra gli avvisi del calendario anche sopra un’app a schermo intero. Altrimenti attendono che esci dallo schermo intero.")
        case .ru: return NotchCalendarStrings(
            title: "Календарь",
            description: "Просматривайте месяц и ближайшие встречи в вырезе экрана.",
            permission: "Чтение календарей для показа предстоящих встреч. События остаются на этом Mac.",
            allow: "Разрешить доступ к календарю",
            denied: "Разрешите доступ к календарю в Системных настройках, чтобы видеть встречи.",
            settings: "Открыть Системные настройки",
            empty: "Предстоящих встреч нет",
            next: "Следующая встреча",
            ongoing: "Сейчас",
            allDay: "Весь день",
            untitled: "Событие без названия",
            openCalendar: "Открыть Календарь",
            week: "Ближайшие 7 дней",
            today: "Сегодня",
            requestFailed: "Не удалось запросить доступ к календарю. Повторите попытку.",
            previousMonth: "Предыдущий месяц",
            nextMonth: "Следующий месяц",
            previousWeek: "Предыдущая неделя",
            nextWeek: "Следующая неделя",
            month: "Месяц",
            emptyDay: "В этот день встреч нет",
            hasEvents: "Есть встречи",
            countdown: "Отсчёт до следующего события",
            countdownHint: "Показывает каждое событие со временем перед его началом. Чтобы отсчитывать только некоторые, выключите этот параметр и щёлкните их правой кнопкой на странице «Календарь» в вырезе экрана. Названия могут попасть на снимки экрана.",
            countdownLead: "Время до события",
            addCountdown: "Добавить отсчёт",
            removeCountdown: "Убрать отсчёт",
            timeLeft: "Оставшееся время текущего события",
            timeLeftHint: "Показывает текущее событие со временем за час до его окончания. Название может попасть на снимки экрана.",
            calendars: "Показываемые календари",
            then: "затем",
            together: "Начинаются одновременно",
            join: "Подключиться",
            copyLink: "Скопировать ссылку",
            openInBrowser: "Открыть в браузере",
            announceInFullscreen: "Оповещать в полноэкранном режиме",
            announceInFullscreenHint: "Показывает напоминания календаря даже поверх полноэкранного приложения. Иначе они ждут выхода из полноэкранного режима.")
        case .tr: return NotchCalendarStrings(
            title: "Takvim",
            description: "Ayı ve yaklaşan randevularınızı çentikte görüntüleyin.",
            permission: "Yaklaşan randevuları göstermek için takvimlerinizi okur. Etkinlikler bu Mac’te kalır.",
            allow: "Takvim Erişimine İzin Ver",
            denied: "Randevularınızı görmek için Sistem Ayarları’nda takvim erişimine izin verin.",
            settings: "Sistem Ayarları’nı Aç",
            empty: "Yaklaşan randevu yok",
            next: "Sıradaki",
            ongoing: "Şu anda",
            allDay: "Tüm gün",
            untitled: "Başlıksız etkinlik",
            openCalendar: "Takvimi Aç",
            week: "Önümüzdeki 7 gün",
            today: "Bugün",
            requestFailed: "Takvim erişimi istenemedi. Tekrar deneyin.",
            previousMonth: "Önceki ay",
            nextMonth: "Sonraki ay",
            previousWeek: "Önceki hafta",
            nextWeek: "Sonraki hafta",
            month: "Ay",
            emptyDay: "Bu gün için randevu yok",
            hasEvents: "Randevu var",
            countdown: "Sonraki etkinliğe geri sayım",
            countdownHint: "Saatli her etkinliği başlamadan önce çentikte gösterir. Yalnızca bazılarına geri sayım için bunu kapat ve çentiğin Takvim sayfasında onlara sağ tıkla. Başlıklar ekran görüntülerinde görünebilir.",
            countdownLead: "Etkinlikten önceki süre",
            addCountdown: "Geri sayım ekle",
            removeCountdown: "Geri sayımı kaldır",
            timeLeft: "Geçerli etkinlikte kalan süre",
            timeLeftHint: "Devam eden saatli etkinliği bitmeden önceki bir saat boyunca çentikte gösterir. Başlığı ekran görüntülerinde görünebilir.",
            calendars: "Gösterilen takvimler",
            then: "sonra",
            together: "Aynı anda başlıyor",
            join: "Katıl",
            copyLink: "Bağlantıyı kopyala",
            openInBrowser: "Tarayıcıda aç",
            announceInFullscreen: "Tam ekranda duyur",
            announceInFullscreenHint: "Takvim uyarılarını tam ekran bir uygulamanın üzerinde bile gösterir. Aksi halde tam ekrandan çıkmanı beklerler.")
        case .ja: return NotchCalendarStrings(
            title: "カレンダー",
            description: "Dynamic Islandで月のカレンダーと今後の予定を確認できます。",
            permission: "カレンダーを読み取り、今後の予定を表示します。予定の情報はこのMacに保持されます。",
            allow: "カレンダーへのアクセスを許可",
            denied: "予定を表示するには、システム設定でカレンダーへのアクセスを許可してください。",
            settings: "システム設定を開く",
            empty: "今後の予定はありません",
            next: "次の予定",
            ongoing: "進行中",
            allDay: "終日",
            untitled: "名称未設定の予定",
            openCalendar: "カレンダーを開く",
            week: "今後7日間",
            today: "今日",
            requestFailed: "カレンダーへのアクセスを要求できませんでした。もう一度お試しください。",
            previousMonth: "前の月",
            nextMonth: "次の月",
            previousWeek: "前の週",
            nextWeek: "次の週",
            month: "月",
            emptyDay: "この日の予定はありません",
            hasEvents: "予定あり",
            countdown: "次の予定までのカウントダウン",
            countdownHint: "時刻があるすべての予定を、開始前から閉じたノッチに表示します。一部の予定だけにするには、この設定をオフにして、ノッチのカレンダーページで予定を右クリックします。タイトルが画面収録やスクリーンショットに映る場合があります。",
            countdownLead: "開始前の表示時間",
            addCountdown: "カウントダウンを追加",
            removeCountdown: "カウントダウンを削除",
            timeLeft: "進行中の予定の残り時間",
            timeLeftHint: "終了1時間前から、時刻がある進行中の予定を閉じたノッチに表示します。タイトルが画面収録やスクリーンショットに映る場合があります。",
            calendars: "表示するカレンダー",
            then: "次",
            together: "同時に開始",
            join: "参加",
            copyLink: "リンクをコピー",
            openInBrowser: "ブラウザで開く",
            announceInFullscreen: "フルスクリーンでも通知",
            announceInFullscreenHint: "フルスクリーンのアプリの上でもカレンダーのお知らせを表示します。オフの場合はフルスクリーンを終了するまで待ちます。")
        case .ko: return NotchCalendarStrings(
            title: "캘린더",
            description: "Dynamic Island에서 월별 달력과 다가오는 일정을 확인하세요.",
            permission: "다가오는 일정을 표시하기 위해 캘린더를 읽습니다. 일정은 이 Mac에만 보관됩니다.",
            allow: "캘린더 접근 허용",
            denied: "일정을 보려면 시스템 설정에서 캘린더 접근을 허용하세요.",
            settings: "시스템 설정 열기",
            empty: "예정된 일정 없음",
            next: "다음 일정",
            ongoing: "진행 중",
            allDay: "하루 종일",
            untitled: "제목 없는 일정",
            openCalendar: "캘린더 열기",
            week: "앞으로 7일",
            today: "오늘",
            requestFailed: "캘린더 접근을 요청할 수 없습니다. 다시 시도하세요.",
            previousMonth: "이전 달",
            nextMonth: "다음 달",
            previousWeek: "이전 주",
            nextWeek: "다음 주",
            month: "월",
            emptyDay: "이 날의 일정 없음",
            hasEvents: "일정 있음",
            countdown: "다음 일정 카운트다운",
            countdownHint: "시간이 지정된 모든 일정을 시작 전부터 닫힌 노치에 표시합니다. 일부 일정만 카운트다운하려면 이 옵션을 끄고 노치의 캘린더 페이지에서 해당 일정을 보조 클릭하세요. 제목이 화면 캡처에 나타날 수 있습니다.",
            countdownLead: "일정 전 표시 시간",
            addCountdown: "카운트다운 추가",
            removeCountdown: "카운트다운 제거",
            timeLeft: "진행 중인 일정의 남은 시간",
            timeLeftHint: "종료 1시간 전부터 시간이 지정된 진행 중인 일정을 닫힌 노치에 표시합니다. 제목이 화면 캡처에 나타날 수 있습니다.",
            calendars: "표시할 캘린더",
            then: "다음",
            together: "동시에 시작",
            join: "참가",
            copyLink: "링크 복사",
            openInBrowser: "브라우저에서 열기",
            announceInFullscreen: "전체 화면에서도 알림",
            announceInFullscreenHint: "전체 화면 앱 위에서도 캘린더 알림을 표시합니다. 끄면 전체 화면을 나갈 때까지 기다립니다.")
        case .zhHans: return NotchCalendarStrings(
            title: "日历",
            description: "在Dynamic Island中浏览月历和即将开始的日程。",
            permission: "读取日历以显示即将开始的日程。日程信息仅保留在此 Mac 上。",
            allow: "允许访问日历",
            denied: "请在系统设置中允许访问日历，以查看日程。",
            settings: "打开系统设置",
            empty: "暂无即将开始的日程",
            next: "下一个日程",
            ongoing: "正在进行",
            allDay: "全天",
            untitled: "无标题日程",
            openCalendar: "打开日历",
            week: "未来 7 天",
            today: "今天",
            requestFailed: "无法请求日历访问权限，请重试。",
            previousMonth: "上个月",
            nextMonth: "下个月",
            previousWeek: "上一周",
            nextWeek: "下一周",
            month: "月",
            emptyDay: "当天没有日程",
            hasEvents: "有日程",
            countdown: "下个日程倒计时",
            countdownHint: "在开始前，于收起的刘海区域显示每个定时日程。若只想为部分日程倒计时，请关闭此选项，然后在刘海区域的日历页面中右键点按这些日程。标题可能出现在屏幕截图中。",
            countdownLead: "提前显示时间",
            addCountdown: "添加倒计时",
            removeCountdown: "移除倒计时",
            timeLeft: "当前日程剩余时间",
            timeLeftHint: "在结束前一小时，于收起的刘海区域显示正在进行的定时日程。标题可能出现在屏幕截图中。",
            calendars: "显示的日历",
            then: "接着",
            together: "同时开始",
            join: "加入",
            copyLink: "拷贝链接",
            openInBrowser: "在浏览器中打开",
            announceInFullscreen: "全屏时也提醒",
            announceInFullscreenHint: "即使在全屏 App 上方也显示日历提醒。否则会等你退出全屏。")
        case .zhTW: return NotchCalendarStrings(
            title: "行事曆",
            description: "在Dynamic Island中瀏覽月曆與即將到來的行程。",
            permission: "讀取行事曆以顯示即將到來的行程。行程資訊僅保留在這部 Mac 上。",
            allow: "允許取用行事曆",
            denied: "請在系統設定中允許取用行事曆，以查看行程。",
            settings: "打開系統設定",
            empty: "沒有即將到來的行程",
            next: "下一個行程",
            ongoing: "進行中",
            allDay: "整天",
            untitled: "未命名行程",
            openCalendar: "打開行事曆",
            week: "未來 7 天",
            today: "今天",
            requestFailed: "無法要求行事曆取用權限，請再試一次。",
            previousMonth: "上個月",
            nextMonth: "下個月",
            previousWeek: "上一週",
            nextWeek: "下一週",
            month: "月",
            emptyDay: "當天沒有行程",
            hasEvents: "有行程",
            countdown: "下一個行程倒數",
            countdownHint: "在開始前，於收合的動態島顯示每個有時間的行程。若只要為部分行程倒數，請關閉此選項，並在動態島的行事曆頁面對這些行程按右鍵。標題可能出現在螢幕截圖中。",
            countdownLead: "提前顯示時間",
            addCountdown: "加入倒數",
            removeCountdown: "移除倒數",
            timeLeft: "目前行程剩餘時間",
            timeLeftHint: "在結束前一小時，於收合的動態島顯示進行中且有時間的行程。標題可能出現在螢幕截圖中。",
            calendars: "顯示的行事曆",
            then: "接著",
            together: "同時開始",
            join: "加入",
            copyLink: "拷貝連結",
            openInBrowser: "在瀏覽器中打開",
            announceInFullscreen: "全螢幕時也提醒",
            announceInFullscreenHint: "即使在全螢幕 App 上方也顯示行事曆提醒。否則會等你離開全螢幕。")
        case .zhHK: return NotchCalendarStrings(
            title: "日曆",
            description: "在Dynamic Island中瀏覽月曆及即將到來的行程。",
            permission: "讀取日曆以顯示即將到來的行程。行程資料只保留在此 Mac 上。",
            allow: "允許取用日曆",
            denied: "請在系統設定中允許取用日曆，以查看行程。",
            settings: "開啟系統設定",
            empty: "沒有即將到來的行程",
            next: "下一個行程",
            ongoing: "進行中",
            allDay: "全天",
            untitled: "未命名行程",
            openCalendar: "開啟日曆",
            week: "未來 7 天",
            today: "今天",
            requestFailed: "無法要求日曆取用權限，請重試。",
            previousMonth: "上個月",
            nextMonth: "下個月",
            previousWeek: "上一週",
            nextWeek: "下一週",
            month: "月",
            emptyDay: "當天沒有行程",
            hasEvents: "有行程",
            countdown: "下一個行程倒數",
            countdownHint: "在開始前，於收合的動態島顯示每個有時間的行程。若只要為部分行程倒數，請關閉此選項，並在動態島的日曆頁面對這些行程按右鍵。標題可能出現在螢幕截圖中。",
            countdownLead: "提前顯示時間",
            addCountdown: "加入倒數",
            removeCountdown: "移除倒數",
            timeLeft: "目前行程剩餘時間",
            timeLeftHint: "在結束前一小時，於收合的動態島顯示進行中且有時間的行程。標題可能出現在螢幕截圖中。",
            calendars: "顯示的日曆",
            then: "接著",
            together: "同時開始",
            join: "加入",
            copyLink: "複製連結",
            openInBrowser: "在瀏覽器中開啟",
            announceInFullscreen: "全螢幕時也提醒",
            announceInFullscreenHint: "即使在全螢幕 App 上方也顯示日曆提醒。否則會等你離開全螢幕。")
        case .uk: return NotchCalendarStrings(
            title: "Календар",
            description: "Переглядайте місяць та майбутні події у Dynamic Island.",
            permission: "Читає ваші календарі, щоб показувати майбутні події. Події залишаються на цьому Mac.",
            allow: "Дозволити доступ до календаря",
            denied: "Дозвольте доступ до календаря в Системних параметрах, щоб бачити свої події.",
            settings: "Відкрити Системні параметри",
            empty: "Немає майбутніх подій",
            next: "Далі",
            ongoing: "Зараз триває",
            allDay: "Увесь день",
            untitled: "Подія без назви",
            openCalendar: "Відкрити Календар",
            week: "Наступні 7 днів",
            today: "Сьогодні",
            requestFailed: "Не вдалося запросити доступ до календаря. Спробуйте ще раз.",
            previousMonth: "Попередній місяць",
            nextMonth: "Наступний місяць",
            previousWeek: "Попередній тиждень",
            nextWeek: "Наступний тиждень",
            month: "Місяць",
            emptyDay: "Цього дня немає подій",
            hasEvents: "Є події",
            countdown: "Відлік до наступної події",
            countdownHint: "Показує кожну подію з визначеним часом перед її початком. Щоб відлічувати лише деякі, вимкніть цей параметр і клацніть їх правою кнопкою на сторінці «Календар» у Dynamic Island. Назви можуть потрапити на знімки екрана.",
            countdownLead: "Час до події",
            addCountdown: "Додати відлік",
            removeCountdown: "Прибрати відлік",
            timeLeft: "Залишок часу поточної події",
            timeLeftHint: "Показує поточну подію з визначеним часом за годину до її завершення. Назва може потрапити на знімки екрана.",
            calendars: "Календарі для показу",
            then: "потім",
            together: "Починаються одночасно",
            join: "Приєднатися",
            copyLink: "Скопіювати посилання",
            openInBrowser: "Відкрити в браузері",
            announceInFullscreen: "Сповіщати в повноекранному режимі",
            announceInFullscreenHint: "Показує нагадування календаря навіть поверх повноекранної програми. Інакше вони чекають, доки ви вийдете з повноекранного режиму.")
        }
    }
}
