// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct NotchMusicExtrasStrings {
    let lyrics: String
    let lyricsDescription: String
    let enableLyrics: String
    let online: String
    let onlineHint: String
    let importLyrics: String
    let importHint: String
    let loading: String
    let unavailable: String
    let failed: String
    let retry: String
    let instrumental: String
    let waiting: String
    let noPosition: String
    let offset: String
    let earlier: String
    let later: String
    let reset: String
    let actionFailed: String
    let playbackFailed: String
    let allowPlayback: String
    let automationPermission: String
    let automationExplanation: String
    let queue: String
    let queueDescription: String
    let enableQueue: String
    let queueUnavailable: String
    let queueEmpty: String
    let playNow: String
    let refresh: String
    let openPlayer: String
    let liveEqualizer: String
    /// One line for the features hub, where the hint below would not fit.
    let liveEqualizerDescription: String
    let liveEqualizerHint: String
    let liveEqualizerUnavailable: String
}

extension FeatureStrings {
    static func notchMusicExtras(_ language: AppLanguage) -> NotchMusicExtrasStrings {
        switch language {
        case .enUS: return NotchMusicExtrasStrings(
            lyrics: "Lyrics",
            lyricsDescription: "Follow the lyrics of the current song in the Dynamic Island.",
            enableLyrics: "Show lyrics",
            online: "Find lyrics online",
            onlineHint: "While lyrics are open, send the song title, artist, album and duration to lrclib.net. Imported lyrics stay on this Mac.",
            importLyrics: "Import lyrics…",
            importHint: "Choose timed lyrics for the current recording. They are kept only while this song is open.",
            loading: "Loading lyrics…",
            unavailable: "No matching lyrics for this recording.",
            failed: "Could not load the lyrics.",
            retry: "Try again",
            instrumental: "Instrumental",
            waiting: "Waiting for the first verse",
            noPosition: "The player does not share its position.",
            offset: "Timing",
            earlier: "Earlier",
            later: "Later",
            reset: "Reset",
            actionFailed: "The player did not switch to this song.",
            playbackFailed: "Could not change playback.",
            allowPlayback: "Allow playback control",
            automationPermission: "Playback automation",
            automationExplanation: "Some music apps require permission for their playback controls. Authorize the selected player from Dynamic Island; access is granted separately for each app.",
            queue: "Up next",
            queueDescription: "See the actual upcoming songs shared by your player.",
            enableQueue: "Show upcoming songs",
            queueUnavailable: "This player does not share its upcoming songs.",
            queueEmpty: "No upcoming songs",
            playNow: "Play now",
            refresh: "Refresh",
            openPlayer: "Open player",
            liveEqualizer: "Bars follow the music",
            liveEqualizerDescription: "Move the Dynamic Island bars with the sound your player makes.",
            liveEqualizerHint: "Listens to the player’s own audio output to move the bars. macOS asks once to allow system audio recording. Nothing is stored or sent. Without it, the bars keep their usual motion.",
            liveEqualizerUnavailable: "Needs macOS 14.4 or later.")
        case .ptBR: return NotchMusicExtrasStrings(
            lyrics: "Letra",
            lyricsDescription: "Acompanhe a letra da música atual no Dynamic Island.",
            enableLyrics: "Mostrar letra",
            online: "Buscar letras on-line",
            onlineHint: "Enquanto a letra estiver aberta, envie título, artista, álbum e duração da música para lrclib.net. Letras importadas ficam neste Mac.",
            importLyrics: "Importar letra…",
            importHint: "Escolha a letra sincronizada desta gravação. Ela fica guardada apenas enquanto esta música estiver aberta.",
            loading: "Carregando letra…",
            unavailable: "Nenhuma letra correspondente a esta gravação.",
            failed: "Não foi possível carregar a letra.",
            retry: "Tentar novamente",
            instrumental: "Instrumental",
            waiting: "Aguardando o primeiro verso",
            noPosition: "O reprodutor não informa a posição da música.",
            offset: "Sincronização",
            earlier: "Adiantar",
            later: "Atrasar",
            reset: "Redefinir",
            actionFailed: "O reprodutor não mudou para esta música.",
            playbackFailed: "Não foi possível alterar a reprodução.",
            allowPlayback: "Permitir controle da reprodução",
            automationPermission: "Automação da reprodução",
            automationExplanation: "Alguns reprodutores precisam de permissão para seus controles. Autorize o reprodutor escolhido na Dynamic Island; o acesso é concedido separadamente para cada app.",
            queue: "A seguir",
            queueDescription: "Veja as próximas músicas informadas pelo reprodutor.",
            enableQueue: "Mostrar próximas músicas",
            queueUnavailable: "Este reprodutor não informa as próximas músicas.",
            queueEmpty: "Nenhuma música a seguir",
            playNow: "Reproduzir agora",
            refresh: "Atualizar",
            openPlayer: "Abrir reprodutor",
            liveEqualizer: "Barras seguem a música",
            liveEqualizerDescription: "Mova as barras do Dynamic Island com o som do seu reprodutor.",
            liveEqualizerHint: "Ouve a saída de áudio do próprio reprodutor para mover as barras. O macOS pede uma vez permissão para gravar o áudio do sistema. Nada é guardado nem enviado. Sem ela, as barras mantêm o movimento habitual.",
            liveEqualizerUnavailable: "Requer macOS 14.4 ou posterior.")
        case .es: return NotchMusicExtrasStrings(
            lyrics: "Letra",
            lyricsDescription: "Sigue la letra de la canción actual en el Dynamic Island.",
            enableLyrics: "Mostrar letra",
            online: "Buscar letras en línea",
            onlineHint: "Mientras la letra esté abierta, envía el título, artista, álbum y duración a lrclib.net. Las letras importadas se quedan en este Mac.",
            importLyrics: "Importar letra…",
            importHint: "Elige la letra sincronizada de esta grabación. Solo se conserva mientras esta canción esté abierta.",
            loading: "Cargando letra…",
            unavailable: "No hay letra que coincida con esta grabación.",
            failed: "No se pudo cargar la letra.",
            retry: "Reintentar",
            instrumental: "Instrumental",
            waiting: "Esperando el primer verso",
            noPosition: "El reproductor no comparte la posición.",
            offset: "Sincronización",
            earlier: "Adelantar",
            later: "Retrasar",
            reset: "Restablecer",
            actionFailed: "El reproductor no cambió a esta canción.",
            playbackFailed: "No se pudo cambiar la reproducción.",
            allowPlayback: "Permitir controlar la reproducción",
            automationPermission: "Automatización de reproducción",
            automationExplanation: "Algunos reproductores necesitan permiso para sus controles. Autoriza el reproductor elegido desde Dynamic Island; el acceso se concede por separado para cada app.",
            queue: "A continuación",
            queueDescription: "Ve las próximas canciones que comparte el reproductor.",
            enableQueue: "Mostrar próximas canciones",
            queueUnavailable: "Este reproductor no comparte las próximas canciones.",
            queueEmpty: "No hay próximas canciones",
            playNow: "Reproducir ahora",
            refresh: "Actualizar",
            openPlayer: "Abrir reproductor",
            liveEqualizer: "Las barras siguen la música",
            liveEqualizerDescription: "Mueve las barras del Dynamic Island con el sonido del reproductor.",
            liveEqualizerHint: "Escucha la salida de audio del propio reproductor para mover las barras. macOS pide una vez permiso para grabar el audio del sistema. No se guarda ni se envía nada. Sin él, las barras mantienen su movimiento habitual.",
            liveEqualizerUnavailable: "Necesita macOS 14.4 o posterior.")
        case .de: return NotchMusicExtrasStrings(
            lyrics: "Liedtext",
            lyricsDescription: "Verfolge den Text des aktuellen Songs im Dynamic Island.",
            enableLyrics: "Liedtext anzeigen",
            online: "Liedtexte online suchen",
            onlineHint: "Bei geöffnetem Liedtext werden Titel, Interpret, Album und Dauer an lrclib.net gesendet. Importierte Texte bleiben auf diesem Mac.",
            importLyrics: "Liedtext importieren…",
            importHint: "Wähle einen synchronisierten Text für diese Aufnahme. Er bleibt nur gespeichert, solange dieser Song geöffnet ist.",
            loading: "Liedtext wird geladen…",
            unavailable: "Kein passender Text für diese Aufnahme.",
            failed: "Der Liedtext konnte nicht geladen werden.",
            retry: "Erneut versuchen",
            instrumental: "Instrumental",
            waiting: "Warten auf die erste Strophe",
            noPosition: "Der Player teilt seine Wiedergabeposition nicht.",
            offset: "Synchronisierung",
            earlier: "Früher",
            later: "Später",
            reset: "Zurücksetzen",
            actionFailed: "Der Player hat nicht zu diesem Song gewechselt.",
            playbackFailed: "Wiedergabe konnte nicht geändert werden.",
            allowPlayback: "Wiedergabesteuerung erlauben",
            automationPermission: "Wiedergabeautomation",
            automationExplanation: "Einige Musik-Apps benötigen eine Erlaubnis für die Steuerung. Erlaube den ausgewählten Player in Dynamic Island; der Zugriff wird für jede App einzeln erteilt.",
            queue: "Als Nächstes",
            queueDescription: "Sieh die nächsten Songs, die dein Player bereitstellt.",
            enableQueue: "Nächste Songs anzeigen",
            queueUnavailable: "Dieser Player stellt seine nächsten Songs nicht bereit.",
            queueEmpty: "Keine nächsten Songs",
            playNow: "Jetzt abspielen",
            refresh: "Aktualisieren",
            openPlayer: "Player öffnen",
            liveEqualizer: "Balken folgen der Musik",
            liveEqualizerDescription: "Bewege die Balken im Dynamic Island mit dem Klang deines Players.",
            liveEqualizerHint: "Hört die Audioausgabe des Players ab, um die Balken zu bewegen. macOS fragt einmal nach der Erlaubnis, Systemaudio aufzunehmen. Nichts wird gespeichert oder gesendet. Ohne sie behalten die Balken ihre gewohnte Bewegung.",
            liveEqualizerUnavailable: "Benötigt macOS 14.4 oder neuer.")
        case .fr: return NotchMusicExtrasStrings(
            lyrics: "Paroles",
            lyricsDescription: "Suivez les paroles du morceau en cours dans le Dynamic Island.",
            enableLyrics: "Afficher les paroles",
            online: "Chercher les paroles en ligne",
            onlineHint: "Lorsque les paroles sont ouvertes, le titre, l’artiste, l’album et la durée sont envoyés à lrclib.net. Les paroles importées restent sur ce Mac.",
            importLyrics: "Importer des paroles…",
            importHint: "Choisissez les paroles synchronisées de cet enregistrement. Elles restent disponibles uniquement tant que ce morceau est ouvert.",
            loading: "Chargement des paroles…",
            unavailable: "Aucune parole correspondante pour cet enregistrement.",
            failed: "Impossible de charger les paroles.",
            retry: "Réessayer",
            instrumental: "Instrumental",
            waiting: "En attente du premier couplet",
            noPosition: "Le lecteur ne partage pas la position de lecture.",
            offset: "Synchronisation",
            earlier: "Avancer",
            later: "Retarder",
            reset: "Réinitialiser",
            actionFailed: "Le lecteur n’a pas lancé ce morceau.",
            playbackFailed: "Impossible de modifier la lecture.",
            allowPlayback: "Autoriser le contrôle de la lecture",
            automationPermission: "Automatisation de la lecture",
            automationExplanation: "Certains lecteurs demandent une autorisation pour leurs commandes. Autorisez le lecteur choisi dans Dynamic Island ; chaque app reçoit une autorisation distincte.",
            queue: "À suivre",
            queueDescription: "Consultez les prochains morceaux partagés par votre lecteur.",
            enableQueue: "Afficher les prochains morceaux",
            queueUnavailable: "Ce lecteur ne partage pas ses prochains morceaux.",
            queueEmpty: "Aucun morceau à suivre",
            playNow: "Lire maintenant",
            refresh: "Actualiser",
            openPlayer: "Ouvrir le lecteur",
            liveEqualizer: "Les barres suivent la musique",
            liveEqualizerDescription: "Animez les barres du Dynamic Island avec le son de votre lecteur.",
            liveEqualizerHint: "Écoute la sortie audio du lecteur pour animer les barres. macOS demande une fois l’autorisation d’enregistrer l’audio du système. Rien n’est conservé ni envoyé. Sans elle, les barres gardent leur mouvement habituel.",
            liveEqualizerUnavailable: "Nécessite macOS 14.4 ou ultérieur.")
        case .it: return NotchMusicExtrasStrings(
            lyrics: "Testo",
            lyricsDescription: "Segui il testo del brano attuale nel Dynamic Island.",
            enableLyrics: "Mostra testo",
            online: "Cerca testi online",
            onlineHint: "Quando il testo è aperto, titolo, artista, album e durata vengono inviati a lrclib.net. I testi importati restano su questo Mac.",
            importLyrics: "Importa testo…",
            importHint: "Scegli il testo sincronizzato di questa registrazione. Viene conservato solo mentre questo brano è aperto.",
            loading: "Caricamento del testo…",
            unavailable: "Nessun testo corrispondente a questa registrazione.",
            failed: "Impossibile caricare il testo.",
            retry: "Riprova",
            instrumental: "Strumentale",
            waiting: "In attesa della prima strofa",
            noPosition: "Il lettore non condivide la posizione di riproduzione.",
            offset: "Sincronizzazione",
            earlier: "Anticipa",
            later: "Ritarda",
            reset: "Ripristina",
            actionFailed: "Il lettore non è passato a questo brano.",
            playbackFailed: "Impossibile modificare la riproduzione.",
            allowPlayback: "Consenti il controllo della riproduzione",
            automationPermission: "Automazione della riproduzione",
            automationExplanation: "Alcuni lettori richiedono il permesso per i controlli. Autorizza il lettore scelto da Dynamic Island; l’accesso viene concesso separatamente per ogni app.",
            queue: "In coda",
            queueDescription: "Vedi i prossimi brani condivisi dal lettore.",
            enableQueue: "Mostra prossimi brani",
            queueUnavailable: "Questo lettore non condivide i prossimi brani.",
            queueEmpty: "Nessun brano in coda",
            playNow: "Riproduci ora",
            refresh: "Aggiorna",
            openPlayer: "Apri lettore",
            liveEqualizer: "Le barre seguono la musica",
            liveEqualizerDescription: "Muovi le barre nel Dynamic Island con il suono del lettore.",
            liveEqualizerHint: "Ascolta l’uscita audio del lettore per muovere le barre. macOS chiede una volta il permesso di registrare l’audio di sistema. Nulla viene salvato o inviato. Senza, le barre mantengono il movimento abituale.",
            liveEqualizerUnavailable: "Richiede macOS 14.4 o successivo.")
        case .ru: return NotchMusicExtrasStrings(
            lyrics: "Текст песни",
            lyricsDescription: "Следите за текстом текущей песни в вырезе.",
            enableLyrics: "Показывать текст",
            online: "Искать тексты в интернете",
            onlineHint: "Пока текст открыт, название песни, исполнитель, альбом и длительность отправляются на lrclib.net. Импортированные тексты остаются на этом Mac.",
            importLyrics: "Импортировать текст…",
            importHint: "Выберите синхронизированный текст этой записи. Он хранится только пока эта песня открыта.",
            loading: "Загрузка текста…",
            unavailable: "Для этой записи не найден подходящий текст.",
            failed: "Не удалось загрузить текст.",
            retry: "Повторить",
            instrumental: "Инструментальная композиция",
            waiting: "Ожидание первого куплета",
            noPosition: "Плеер не сообщает позицию воспроизведения.",
            offset: "Синхронизация",
            earlier: "Раньше",
            later: "Позже",
            reset: "Сбросить",
            actionFailed: "Плеер не переключился на эту песню.",
            playbackFailed: "Не удалось изменить воспроизведение.",
            allowPlayback: "Разрешить управление воспроизведением",
            automationPermission: "Автоматизация воспроизведения",
            automationExplanation: "Некоторым плеерам нужно разрешение для управления. Разрешите управление выбранным плеером в Dynamic Island; доступ предоставляется отдельно каждому приложению.",
            queue: "Далее",
            queueDescription: "Просматривайте следующие песни, переданные плеером.",
            enableQueue: "Показывать следующие песни",
            queueUnavailable: "Этот плеер не сообщает следующие песни.",
            queueEmpty: "Следующих песен нет",
            playNow: "Воспроизвести сейчас",
            refresh: "Обновить",
            openPlayer: "Открыть плеер",
            liveEqualizer: "Полоски следуют музыке",
            liveEqualizerDescription: "Двигайте полоски в вырезе звуком самого плеера.",
            liveEqualizerHint: "Слушает вывод звука самого плеера, чтобы двигать полоски. macOS один раз попросит разрешение на запись системного звука. Ничего не сохраняется и не отправляется. Без него полоски двигаются как обычно.",
            liveEqualizerUnavailable: "Требуется macOS 14.4 или новее.")
        case .tr: return NotchMusicExtrasStrings(
            lyrics: "Şarkı sözleri",
            lyricsDescription: "Çalan şarkının sözlerini çentikte takip edin.",
            enableLyrics: "Şarkı sözlerini göster",
            online: "Sözleri çevrimiçi bul",
            onlineHint: "Sözler açıkken şarkı adı, sanatçı, albüm ve süre lrclib.net adresine gönderilir. İçe aktarılan sözler bu Mac’te kalır.",
            importLyrics: "Şarkı sözü içe aktar…",
            importHint: "Bu kaydın zamanlanmış sözlerini seçin. Yalnızca bu şarkı açıkken saklanırlar.",
            loading: "Şarkı sözleri yükleniyor…",
            unavailable: "Bu kayda uygun şarkı sözü yok.",
            failed: "Şarkı sözleri yüklenemedi.",
            retry: "Yeniden dene",
            instrumental: "Enstrümantal",
            waiting: "İlk dize bekleniyor",
            noPosition: "Oynatıcı çalma konumunu paylaşmıyor.",
            offset: "Zamanlama",
            earlier: "Öne al",
            later: "Geciktir",
            reset: "Sıfırla",
            actionFailed: "Oynatıcı bu şarkıya geçmedi.",
            playbackFailed: "Oynatma değiştirilemedi.",
            allowPlayback: "Oynatma denetimine izin ver",
            automationPermission: "Oynatma otomasyonu",
            automationExplanation: "Bazı müzik uygulamaları denetimler için izin ister. Seçilen oynatıcıya Dynamic Island’dan izin verin; erişim her uygulama için ayrı verilir.",
            queue: "Sıradaki",
            queueDescription: "Oynatıcının paylaştığı sıradaki şarkıları görün.",
            enableQueue: "Sıradaki şarkıları göster",
            queueUnavailable: "Bu oynatıcı sıradaki şarkıları paylaşmıyor.",
            queueEmpty: "Sırada şarkı yok",
            playNow: "Şimdi çal",
            refresh: "Yenile",
            openPlayer: "Oynatıcıyı aç",
            liveEqualizer: "Çubuklar müziği izler",
            liveEqualizerDescription: "Çentikteki çubukları oynatıcının sesiyle hareket ettirin.",
            liveEqualizerHint: "Çubukları hareket ettirmek için oynatıcının kendi ses çıkışını dinler. macOS sistem sesini kaydetme iznini bir kez sorar. Hiçbir şey saklanmaz veya gönderilmez. İzin verilmezse çubuklar her zamanki hareketini sürdürür.",
            liveEqualizerUnavailable: "macOS 14.4 veya üstü gerekir.")
        case .ja: return NotchMusicExtrasStrings(
            lyrics: "歌詞",
            lyricsDescription: "再生中の曲の歌詞をDynamic Islandに表示します。",
            enableLyrics: "歌詞を表示",
            online: "オンラインで歌詞を検索",
            onlineHint: "歌詞を開いている間、曲名、アーティスト、アルバム、再生時間を lrclib.net に送信します。読み込んだ歌詞はこのMacに保持されます。",
            importLyrics: "歌詞を読み込む…",
            importHint: "この音源に合った同期歌詞を選択してください。この曲を開いている間だけ保持されます。",
            loading: "歌詞を読み込み中…",
            unavailable: "この音源に一致する歌詞がありません。",
            failed: "歌詞を読み込めませんでした。",
            retry: "再試行",
            instrumental: "インストゥルメンタル",
            waiting: "歌い出しを待っています",
            noPosition: "プレーヤーが再生位置を共有していません。",
            offset: "タイミング",
            earlier: "早める",
            later: "遅らせる",
            reset: "リセット",
            actionFailed: "プレーヤーがこの曲に切り替わりませんでした。",
            playbackFailed: "再生を変更できませんでした。",
            allowPlayback: "再生の操作を許可",
            automationPermission: "再生のオートメーション",
            automationExplanation: "一部の音楽アプリでは操作の許可が必要です。Dynamic Islandで選択したプレーヤーを許可してください。アクセスはアプリごとに付与されます。",
            queue: "次に再生",
            queueDescription: "プレーヤーが共有する次の曲を表示します。",
            enableQueue: "次の曲を表示",
            queueUnavailable: "このプレーヤーは次の曲を共有していません。",
            queueEmpty: "次の曲はありません",
            playNow: "今すぐ再生",
            refresh: "更新",
            openPlayer: "プレーヤーを開く",
            liveEqualizer: "バーが音楽に合わせて動く",
            liveEqualizerDescription: "Dynamic Islandのバーをプレーヤーの音に合わせて動かします。",
            liveEqualizerHint: "プレーヤー自身の音声出力を聞き取ってバーを動かします。macOS はシステム音声の録音許可を一度だけ求めます。何も保存や送信はされません。許可がない場合、バーは通常の動きのままです。",
            liveEqualizerUnavailable: "macOS 14.4 以降が必要です。")
        case .ko: return NotchMusicExtrasStrings(
            lyrics: "가사",
            lyricsDescription: "현재 곡의 가사를 Dynamic Island에서 확인합니다.",
            enableLyrics: "가사 표시",
            online: "온라인에서 가사 찾기",
            onlineHint: "가사가 열려 있는 동안 곡 제목, 아티스트, 앨범 및 재생 시간을 lrclib.net으로 보냅니다. 가져온 가사는 이 Mac에만 유지됩니다.",
            importLyrics: "가사 가져오기…",
            importHint: "이 녹음에 맞는 시간 정보가 있는 가사를 선택하세요. 이 곡이 열려 있는 동안만 유지됩니다.",
            loading: "가사 불러오는 중…",
            unavailable: "이 녹음과 일치하는 가사가 없습니다.",
            failed: "가사를 불러올 수 없습니다.",
            retry: "다시 시도",
            instrumental: "연주곡",
            waiting: "첫 소절을 기다리는 중",
            noPosition: "플레이어가 재생 위치를 공유하지 않습니다.",
            offset: "동기화",
            earlier: "앞당기기",
            later: "늦추기",
            reset: "재설정",
            actionFailed: "플레이어가 이 곡으로 전환하지 않았습니다.",
            playbackFailed: "재생을 변경할 수 없습니다.",
            allowPlayback: "재생 제어 허용",
            automationPermission: "재생 자동화",
            automationExplanation: "일부 음악 앱은 제어 권한이 필요합니다. Dynamic Island에서 선택한 플레이어를 허용하세요. 접근 권한은 앱마다 별도로 부여됩니다.",
            queue: "다음 곡",
            queueDescription: "플레이어가 공유하는 다음 곡을 확인합니다.",
            enableQueue: "다음 곡 표시",
            queueUnavailable: "이 플레이어는 다음 곡을 공유하지 않습니다.",
            queueEmpty: "다음 곡이 없습니다",
            playNow: "지금 재생",
            refresh: "새로 고침",
            openPlayer: "플레이어 열기",
            liveEqualizer: "막대가 음악을 따라 움직임",
            liveEqualizerDescription: "Dynamic Island의 막대를 플레이어의 소리에 맞춰 움직입니다.",
            liveEqualizerHint: "플레이어의 오디오 출력을 듣고 막대를 움직입니다. macOS가 시스템 오디오 녹음 권한을 한 번 요청합니다. 아무것도 저장하거나 전송하지 않습니다. 권한이 없으면 막대는 평소처럼 움직입니다.",
            liveEqualizerUnavailable: "macOS 14.4 이상이 필요합니다.")
        case .zhHans: return NotchMusicExtrasStrings(
            lyrics: "歌词",
            lyricsDescription: "在Dynamic Island中跟随当前歌曲的歌词。",
            enableLyrics: "显示歌词",
            online: "在线查找歌词",
            onlineHint: "歌词打开时，会将歌曲标题、艺人、专辑和时长发送至 lrclib.net。导入的歌词保留在此 Mac 上。",
            importLyrics: "导入歌词…",
            importHint: "选择与当前录音匹配的同步歌词。仅在此歌曲打开期间保留。",
            loading: "正在载入歌词…",
            unavailable: "没有与此录音匹配的歌词。",
            failed: "无法载入歌词。",
            retry: "重试",
            instrumental: "纯音乐",
            waiting: "等待第一句歌词",
            noPosition: "播放器未共享播放位置。",
            offset: "同步",
            earlier: "提前",
            later: "延后",
            reset: "重置",
            actionFailed: "播放器未切换到这首歌曲。",
            playbackFailed: "无法更改播放状态。",
            allowPlayback: "允许控制播放",
            automationPermission: "播放自动化",
            automationExplanation: "部分音乐应用需要授权才能控制播放。请在 Dynamic Island 中授权所选播放器；每个应用需单独授权。",
            queue: "接下来",
            queueDescription: "查看播放器共享的后续歌曲。",
            enableQueue: "显示后续歌曲",
            queueUnavailable: "此播放器未共享后续歌曲。",
            queueEmpty: "没有后续歌曲",
            playNow: "立即播放",
            refresh: "刷新",
            openPlayer: "打开播放器",
            liveEqualizer: "音柱跟随音乐",
            liveEqualizerDescription: "让Dynamic Island的音柱随播放器的声音起伏。",
            liveEqualizerHint: "监听播放器自身的音频输出来驱动音柱。macOS 会请求一次系统音频录制权限。不会保存或发送任何内容。未授权时音柱保持原有动画。",
            liveEqualizerUnavailable: "需要 macOS 14.4 或更高版本。")
        case .zhTW: return NotchMusicExtrasStrings(
            lyrics: "歌詞",
            lyricsDescription: "在Dynamic Island中跟隨目前歌曲的歌詞。",
            enableLyrics: "顯示歌詞",
            online: "線上尋找歌詞",
            onlineHint: "歌詞開啟時，會將歌曲名稱、演出者、專輯和長度傳送至 lrclib.net。匯入的歌詞保留在此 Mac 上。",
            importLyrics: "匯入歌詞…",
            importHint: "選擇與目前錄音相符的同步歌詞。僅在這首歌曲開啟期間保留。",
            loading: "正在載入歌詞…",
            unavailable: "沒有與此錄音相符的歌詞。",
            failed: "無法載入歌詞。",
            retry: "重試",
            instrumental: "純音樂",
            waiting: "等待第一句歌詞",
            noPosition: "播放器未分享播放位置。",
            offset: "同步",
            earlier: "提前",
            later: "延後",
            reset: "重設",
            actionFailed: "播放器未切換至這首歌曲。",
            playbackFailed: "無法更改播放狀態。",
            allowPlayback: "允許控制播放",
            automationPermission: "播放自動化",
            automationExplanation: "部分音樂 App 需要授權才能控制播放。請在 Dynamic Island 中授權所選播放器；每個 App 皆需個別授權。",
            queue: "接著播放",
            queueDescription: "查看播放器分享的後續歌曲。",
            enableQueue: "顯示後續歌曲",
            queueUnavailable: "此播放器未分享後續歌曲。",
            queueEmpty: "沒有後續歌曲",
            playNow: "立即播放",
            refresh: "重新整理",
            openPlayer: "開啟播放器",
            liveEqualizer: "音柱跟隨音樂",
            liveEqualizerDescription: "讓Dynamic Island的音柱隨播放器的聲音起伏。",
            liveEqualizerHint: "監聽播放器本身的音訊輸出來驅動音柱。macOS 會請求一次系統音訊錄製權限。不會儲存或傳送任何內容。未授權時音柱保持原有動畫。",
            liveEqualizerUnavailable: "需要 macOS 14.4 或更新版本。")
        case .zhHK: return NotchMusicExtrasStrings(
            lyrics: "歌詞",
            lyricsDescription: "在Dynamic Island中跟隨目前歌曲的歌詞。",
            enableLyrics: "顯示歌詞",
            online: "網上尋找歌詞",
            onlineHint: "歌詞開啟時，會將歌曲名稱、演出者、專輯和長度傳送至 lrclib.net。匯入的歌詞保留在此 Mac 上。",
            importLyrics: "匯入歌詞…",
            importHint: "選擇與目前錄音相符的同步歌詞。僅在這首歌曲開啟期間保留。",
            loading: "正在載入歌詞…",
            unavailable: "沒有與此錄音相符的歌詞。",
            failed: "無法載入歌詞。",
            retry: "再試",
            instrumental: "純音樂",
            waiting: "等待第一句歌詞",
            noPosition: "播放器未分享播放位置。",
            offset: "同步",
            earlier: "提前",
            later: "延後",
            reset: "重設",
            actionFailed: "播放器未切換至這首歌曲。",
            playbackFailed: "無法更改播放狀態。",
            allowPlayback: "允許控制播放",
            automationPermission: "播放自動化",
            automationExplanation: "部分音樂 App 需要授權才能控制播放。請在 Dynamic Island 中授權所選播放器；每個 App 都需要獨立授權。",
            queue: "接著播放",
            queueDescription: "查看播放器分享的後續歌曲。",
            enableQueue: "顯示後續歌曲",
            queueUnavailable: "此播放器未分享後續歌曲。",
            queueEmpty: "沒有後續歌曲",
            playNow: "立即播放",
            refresh: "重新整理",
            openPlayer: "開啟播放器",
            liveEqualizer: "音柱跟隨音樂",
            liveEqualizerDescription: "讓Dynamic Island的音柱隨播放器的聲音起伏。",
            liveEqualizerHint: "監聽播放器本身的音訊輸出來驅動音柱。macOS 會請求一次系統音訊錄製權限。不會儲存或傳送任何內容。未授權時音柱保持原有動畫。",
            liveEqualizerUnavailable: "需要 macOS 14.4 或更新版本。")
        case .uk: return NotchMusicExtrasStrings(
            lyrics: "Текст пісні",
            lyricsDescription: "Слідкуйте за текстом поточної пісні у Dynamic Island.",
            enableLyrics: "Показувати текст пісні",
            online: "Шукати тексти онлайн",
            onlineHint: "Поки текст відкрито, програма надсилає назву пісні, виконавця, альбом та тривалість на lrclib.net. Імпортовані тексти залишаються на цьому Mac.",
            importLyrics: "Імпортувати текст…",
            importHint: "Виберіть синхронізований текст для поточного запису. Він зберігається, лише поки відкрита ця пісня.",
            loading: "Завантаження тексту…",
            unavailable: "Немає тексту, що відповідає цьому запису.",
            failed: "Не вдалося завантажити текст.",
            retry: "Спробувати знову",
            instrumental: "Інструментальна",
            waiting: "Очікування на перший куплет",
            noPosition: "Програвач не повідомляє свою позицію.",
            offset: "Синхронізація",
            earlier: "Раніше",
            later: "Пізніше",
            reset: "Скинути",
            actionFailed: "Програвач не перейшов до цієї пісні.",
            playbackFailed: "Не вдалося змінити відтворення.",
            allowPlayback: "Дозволити керування відтворенням",
            automationPermission: "Автоматизація відтворення",
            automationExplanation: "Деякі музичні програми потребують дозволу на керування відтворенням. Авторизуйте вибраний програвач у Dynamic Island; доступ надається окремо для кожної програми.",
            queue: "Далі за чергою",
            queueDescription: "Переглядайте наступні пісні, якими ділиться ваш програвач.",
            enableQueue: "Показувати наступні пісні",
            queueUnavailable: "Цей програвач не повідомляє наступні пісні.",
            queueEmpty: "Немає наступних пісень",
            playNow: "Відтворити зараз",
            refresh: "Оновити",
            openPlayer: "Відкрити програвач",
            liveEqualizer: "Смужки слідують за музикою",
            liveEqualizerDescription: "Рухайте смужки Dynamic Island разом зі звуком, який видає програвач.",
            liveEqualizerHint: "Слухає власний аудіовихід програвача, щоб рухати смужками. macOS один раз запитає дозвіл на запис системного звуку. Нічого не зберігається та не надсилається. Без дозволу смужки рухаються як завжди.",
            liveEqualizerUnavailable: "Потрібен macOS 14.4 або новіше.")
        }
    }
}
