// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

struct QuitProtectionStrings {
    let name: String
    let description: String
    let intro: String
    let enabled: String
    let enabledCaption: String
    let mode: String
    let hold: String
    let doublePress: String
    let extraModifier: String
    let holdDuration: String
    let doublePressInterval: String
    let modifier: String
    let appScope: String
    let allApps: String
    let selectedOnly: String
    let allExceptSelected: String
    let exceptions: String
    let noExceptions: String
    let addApp: String
    let feedback: String
    let accessibilityCaption: String
    let holdQuitHUDFormat: String
    let holdCloseHUDFormat: String
    let doubleQuitHUDFormat: String
    let doubleCloseHUDFormat: String
    let extraQuitHUDFormat: String
    let extraCloseHUDFormat: String
    let cancelHint: String
    let releaseHint: String
    let shiftKey: String
    let optionKey: String
    let controlKey: String
    let lockShortcutCaption: String
    let lockShortcutOwnedByQuit: String
    let holdLockHUDFormat: String
    let doubleLockHUDFormat: String
    let touchIDTitle: String
    let touchIDEnabled: String
    let touchIDEnabledCaption: String
    let touchIDIgnore: String
    let touchIDHoldUnavailable: String
    let touchIDHoldHUD: String
    let releaseCancelHint: String

    func holdHUDFormat(for shortcut: QuitProtectionShortcut) -> String {
        shortcut == .quit ? holdQuitHUDFormat : holdCloseHUDFormat
    }

    func doubleHUDFormat(for shortcut: QuitProtectionShortcut) -> String {
        shortcut == .quit ? doubleQuitHUDFormat : doubleCloseHUDFormat
    }

    func extraHUDFormat(for shortcut: QuitProtectionShortcut) -> String {
        shortcut == .quit ? extraQuitHUDFormat : extraCloseHUDFormat
    }

    static func make(_ language: AppLanguage) -> QuitProtectionStrings {
        FeatureStrings.quitProtection(language)
    }
}

extension FeatureStrings {
    static func quitProtection(_ language: AppLanguage) -> QuitProtectionStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .sk: return .sk
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        case .uk: return .uk
        }
    }
}

extension QuitProtectionStrings {
    static let enUS = QuitProtectionStrings(
        name: "Quit & close protection",
        description: "Protects ⌘Q and ⌘W from accidental presses",
        intro: "Configure each shortcut independently. The original action passes only after the selected confirmation.",
        enabled: "Protect this shortcut",
        enabledCaption: "Other Command shortcuts continue to work normally.",
        mode: "Confirmation mode",
        hold: "Hold to confirm",
        doublePress: "Double press",
        extraModifier: "Require extra modifier",
        holdDuration: "Hold duration",
        doublePressInterval: "Double press interval",
        modifier: "Extra modifier",
        appScope: "Applications",
        allApps: "All applications",
        selectedOnly: "Selected applications only",
        allExceptSelected: "All except selected applications",
        exceptions: "Exceptions",
        noExceptions: "No applications selected",
        addApp: "Add application…",
        feedback: "Show visual feedback",
        accessibilityCaption: "Protection uses Accessibility to observe only the shortcuts and the button it protects.",
        holdQuitHUDFormat: "Hold %@ to quit",
        holdCloseHUDFormat: "Hold %@ to close",
        doubleQuitHUDFormat: "Press %@ again to quit",
        doubleCloseHUDFormat: "Press %@ again to close",
        extraQuitHUDFormat: "Use %@ to quit",
        extraCloseHUDFormat: "Use %@ to close",
        cancelHint: "Esc cancels",
        releaseHint: "Release to confirm",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "Holds back the ⌃⌘Q screen lock until confirmed. While this is on, Vorssaint handles the shortcut and gives it back to macOS when it is turned off or the app quits.",
        lockShortcutOwnedByQuit: "⌘Q protection uses Control as its extra key, so ⌃⌘Q confirms a quit there and this guard stays off.",
        holdLockHUDFormat: "Hold %@ to lock",
        doubleLockHUDFormat: "Press %@ again to lock",
        touchIDTitle: "Touch ID / Power button",
        touchIDEnabled: "Protect this button",
        touchIDEnabledCaption: "A quick tap no longer locks the Mac. The lock shortcut and the Lock Screen menu item still work.",
        touchIDIgnore: "Never lock with the button",
        touchIDHoldUnavailable: "This Mac does not report when the button is released, so only the never lock option works.",
        touchIDHoldHUD: "Keep holding to lock",
        releaseCancelHint: "Release to cancel"
    )

    static let ptBR = QuitProtectionStrings(
        name: "Proteção de encerramento",
        description: "Protege ⌘Q e ⌘W contra toques acidentais",
        intro: "Configure cada atalho separadamente. A ação original só passa depois da confirmação escolhida.",
        enabled: "Proteger este atalho",
        enabledCaption: "Outros atalhos com Command continuam funcionando normalmente.",
        mode: "Modo de confirmação",
        hold: "Segurar para confirmar",
        doublePress: "Pressionar duas vezes",
        extraModifier: "Exigir modificador extra",
        holdDuration: "Tempo pressionado",
        doublePressInterval: "Intervalo entre pressões",
        modifier: "Modificador extra",
        appScope: "Aplicativos",
        allApps: "Todos os aplicativos",
        selectedOnly: "Somente aplicativos selecionados",
        allExceptSelected: "Todos, exceto os selecionados",
        exceptions: "Exceções",
        noExceptions: "Nenhum aplicativo selecionado",
        addApp: "Adicionar aplicativo…",
        feedback: "Mostrar feedback visual",
        accessibilityCaption: "A proteção usa Acessibilidade para observar apenas os atalhos e o botão que protege.",
        holdQuitHUDFormat: "Segure %@ para encerrar",
        holdCloseHUDFormat: "Segure %@ para fechar",
        doubleQuitHUDFormat: "Pressione %@ novamente para encerrar",
        doubleCloseHUDFormat: "Pressione %@ novamente para fechar",
        extraQuitHUDFormat: "Use %@ para encerrar",
        extraCloseHUDFormat: "Use %@ para fechar",
        cancelHint: "Esc cancela",
        releaseHint: "Solte para confirmar",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "Segura o bloqueio de tela ⌃⌘Q até a confirmação. Enquanto estiver ativo, o Vorssaint trata o atalho e o devolve ao macOS quando a proteção é desligada ou o app é encerrado.",
        lockShortcutOwnedByQuit: "A proteção de ⌘Q usa Control como tecla extra, então ⌃⌘Q confirma o encerramento ali e esta proteção fica desligada.",
        holdLockHUDFormat: "Segure %@ para bloquear",
        doubleLockHUDFormat: "Pressione %@ novamente para bloquear",
        touchIDTitle: "Botão Touch ID / liga/desliga",
        touchIDEnabled: "Proteger este botão",
        touchIDEnabledCaption: "Um toque rápido não bloqueia mais o Mac. O atalho de bloqueio e o item Bloquear Tela continuam funcionando.",
        touchIDIgnore: "Nunca bloquear com o botão",
        touchIDHoldUnavailable: "Este Mac não informa quando o botão é solto, então só a opção de nunca bloquear funciona.",
        touchIDHoldHUD: "Continue segurando para bloquear",
        releaseCancelHint: "Solte para cancelar"
    )

    static let es = QuitProtectionStrings(
        name: "Protección de cierre",
        description: "Protege ⌘Q y ⌘W contra pulsaciones accidentales",
        intro: "Configura cada atajo de forma independiente. La acción original solo se ejecuta tras la confirmación elegida.",
        enabled: "Proteger este atajo",
        enabledCaption: "Otros atajos con Command siguen funcionando con normalidad.",
        mode: "Modo de confirmación",
        hold: "Mantener para confirmar",
        doublePress: "Pulsar dos veces",
        extraModifier: "Requerir modificador adicional",
        holdDuration: "Tiempo de pulsación",
        doublePressInterval: "Intervalo entre pulsaciones",
        modifier: "Modificador adicional",
        appScope: "Aplicaciones",
        allApps: "Todas las aplicaciones",
        selectedOnly: "Solo aplicaciones seleccionadas",
        allExceptSelected: "Todas excepto las seleccionadas",
        exceptions: "Excepciones",
        noExceptions: "Ninguna aplicación seleccionada",
        addApp: "Añadir aplicación…",
        feedback: "Mostrar respuesta visual",
        accessibilityCaption: "La protección utiliza Accesibilidad para supervisar solo los atajos y el botón que protege.",
        holdQuitHUDFormat: "Mantén %@ para salir",
        holdCloseHUDFormat: "Mantén %@ para cerrar",
        doubleQuitHUDFormat: "Pulsa %@ de nuevo para salir",
        doubleCloseHUDFormat: "Pulsa %@ de nuevo para cerrar",
        extraQuitHUDFormat: "Usa %@ para salir",
        extraCloseHUDFormat: "Usa %@ para cerrar",
        cancelHint: "Esc cancela",
        releaseHint: "Suelta para confirmar",
        shiftKey: "Mayúsculas",
        optionKey: "Opción",
        controlKey: "Control",
        lockShortcutCaption: "Retiene el bloqueo de pantalla ⌃⌘Q hasta que se confirme. Mientras esté activo, Vorssaint gestiona el atajo y se lo devuelve a macOS al desactivarlo o al cerrar la app.",
        lockShortcutOwnedByQuit: "La protección de ⌘Q usa Control como tecla adicional, así que ⌃⌘Q confirma la salida allí y esta protección queda desactivada.",
        holdLockHUDFormat: "Mantén %@ para bloquear",
        doubleLockHUDFormat: "Pulsa %@ de nuevo para bloquear",
        touchIDTitle: "Botón Touch ID / encendido",
        touchIDEnabled: "Proteger este botón",
        touchIDEnabledCaption: "Un toque rápido ya no bloquea el Mac. El atajo de bloqueo y la opción Bloquear pantalla siguen funcionando.",
        touchIDIgnore: "No bloquear nunca con el botón",
        touchIDHoldUnavailable: "Este Mac no indica cuándo se suelta el botón, así que solo funciona la opción de no bloquear nunca.",
        touchIDHoldHUD: "Sigue manteniendo para bloquear",
        releaseCancelHint: "Suelta para cancelar"
    )

    static let sk = QuitProtectionStrings(
        name: "Ochrana pred ukončením a zatvorením",
        description: "Chráni ⌘Q a ⌘W pred náhodným stlačením",
        intro: "Nastavte každú skratku samostatne. Pôvodná akcia sa vykoná až po zvolenom potvrdení.",
        enabled: "Chrániť túto skratku",
        enabledCaption: "Ostatné skratky s Command fungujú bez zmeny.",
        mode: "Režim potvrdenia",
        hold: "Podržať na potvrdenie",
        doublePress: "Dvojité stlačenie",
        extraModifier: "Vyžadovať ďalší modifikátor",
        holdDuration: "Doba podržania",
        doublePressInterval: "Interval medzi stlačeniami",
        modifier: "Ďalší modifikátor",
        appScope: "Aplikácie",
        allApps: "Všetky aplikácie",
        selectedOnly: "Iba vybrané aplikácie",
        allExceptSelected: "Všetky okrem vybraných aplikácií",
        exceptions: "Výnimky",
        noExceptions: "Nie sú vybrané žiadne aplikácie",
        addApp: "Pridať aplikáciu…",
        feedback: "Zobraziť vizuálnu spätnú väzbu",
        accessibilityCaption: "Ochrana používa Prístupnosť na sledovanie iba chránených skratiek a tlačidla.",
        holdQuitHUDFormat: "Podržte %@ na ukončenie",
        holdCloseHUDFormat: "Podržte %@ na zatvorenie",
        doubleQuitHUDFormat: "Stlačte %@ znova na ukončenie",
        doubleCloseHUDFormat: "Stlačte %@ znova na zatvorenie",
        extraQuitHUDFormat: "Použite %@ na ukončenie",
        extraCloseHUDFormat: "Použite %@ na zatvorenie",
        cancelHint: "Esc zruší",
        releaseHint: "Uvoľnením potvrdíte",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "Zadrží zámku obrazovky ⌃⌘Q, kým ju nepotvrdíte. Kým je zapnutá, skratku spracúva Vorssaint a vráti ju macOS po vypnutí alebo ukončení aplikácie.",
        lockShortcutOwnedByQuit: "Ochrana ⌘Q používa Control ako ďalší kláves, preto ⌃⌘Q potvrdzuje ukončenie tam a táto ochrana zostáva vypnutá.",
        holdLockHUDFormat: "Podržte %@ na zamknutie",
        doubleLockHUDFormat: "Stlačte %@ znova na zamknutie",
        touchIDTitle: "Tlačidlo Touch ID / napájanie",
        touchIDEnabled: "Chrániť toto tlačidlo",
        touchIDEnabledCaption: "Rýchly dotyk už Mac nezamkne. Skratka zámku a položka Zamknúť obrazovku fungujú ďalej.",
        touchIDIgnore: "Nikdy nezamykať tlačidlom",
        touchIDHoldUnavailable: "Tento Mac nehlási, kedy sa tlačidlo pustí, preto funguje iba možnosť nikdy nezamykať.",
        touchIDHoldHUD: "Držte ďalej na zamknutie",
        releaseCancelHint: "Pustite na zrušenie"
    )

    static let de = QuitProtectionStrings(
        name: "Beenden- & Schließen-Schutz",
        description: "Schützt ⌘Q und ⌘W vor versehentlichem Drücken",
        intro: "Konfigurieren Sie jeden Kurzbefehl unabhängig. Die ursprüngliche Aktion wird erst nach der Bestätigung ausgeführt.",
        enabled: "Diesen Kurzbefehl schützen",
        enabledCaption: "Andere Befehle mit der Command-Taste funktionieren weiterhin normal.",
        mode: "Bestätigungsmodus",
        hold: "Halten zum Bestätigen",
        doublePress: "Zweimal drücken",
        extraModifier: "Zusätzliche Sondertaste erfordern",
        holdDuration: "Haltedauer",
        doublePressInterval: "Intervall zwischen Betätigungen",
        modifier: "Zusätzliche Sondertaste",
        appScope: "Programme",
        allApps: "Alle Programme",
        selectedOnly: "Nur ausgewählte Programme",
        allExceptSelected: "Alle außer ausgewählten Programmen",
        exceptions: "Ausnahmen",
        noExceptions: "Keine Programme ausgewählt",
        addApp: "Programm hinzufügen…",
        feedback: "Visuelles Feedback anzeigen",
        accessibilityCaption: "Der Schutz nutzt Bedienungshilfen, um nur die geschützten Kurzbefehle und die Taste zu überwachen.",
        holdQuitHUDFormat: "%@ halten zum Beenden",
        holdCloseHUDFormat: "%@ halten zum Schließen",
        doubleQuitHUDFormat: "%@ erneut drücken zum Beenden",
        doubleCloseHUDFormat: "%@ erneut drücken zum Schließen",
        extraQuitHUDFormat: "%@ verwenden zum Beenden",
        extraCloseHUDFormat: "%@ verwenden zum Schließen",
        cancelHint: "Esc bricht ab",
        releaseHint: "Loslassen zum Bestätigen",
        shiftKey: "Umschalttaste",
        optionKey: "Wahltaste",
        controlKey: "Control",
        lockShortcutCaption: "Hält die Bildschirmsperre ⌃⌘Q zurück, bis sie bestätigt ist. Solange der Schutz aktiv ist, verarbeitet Vorssaint den Kurzbefehl und gibt ihn an macOS zurück, wenn er ausgeschaltet oder die App beendet wird.",
        lockShortcutOwnedByQuit: "Der ⌘Q-Schutz nutzt Control als zusätzliche Taste, daher bestätigt ⌃⌘Q dort das Beenden und dieser Schutz bleibt aus.",
        holdLockHUDFormat: "%@ halten zum Sperren",
        doubleLockHUDFormat: "%@ erneut drücken zum Sperren",
        touchIDTitle: "Touch-ID-/Ein-Aus-Taste",
        touchIDEnabled: "Diese Taste schützen",
        touchIDEnabledCaption: "Ein kurzes Antippen sperrt den Mac nicht mehr. Der Sperr-Kurzbefehl und der Menüeintrag Bildschirm sperren funktionieren weiter.",
        touchIDIgnore: "Nie mit der Taste sperren",
        touchIDHoldUnavailable: "Dieser Mac meldet nicht, wann die Taste losgelassen wird, daher funktioniert nur die Option „Nie sperren“.",
        touchIDHoldHUD: "Weiter halten zum Sperren",
        releaseCancelHint: "Loslassen zum Abbrechen"
    )

    static let fr = QuitProtectionStrings(
        name: "Protection fermeture et quitter",
        description: "Protège ⌘Q et ⌘W contre les frappes accidentelles",
        intro: "Configurez chaque raccourci indépendamment. L’action originale ne passe qu’après la confirmation choisie.",
        enabled: "Protéger ce raccourci",
        enabledCaption: "Les autres raccourcis avec Command continuent de fonctionner normalement.",
        mode: "Mode de confirmation",
        hold: "Maintenir pour confirmer",
        doublePress: "Appuyer deux fois",
        extraModifier: "Exiger une touche de modification",
        holdDuration: "Durée de maintien",
        doublePressInterval: "Intervalle entre les frappes",
        modifier: "Touche de modification",
        appScope: "Applications",
        allApps: "Toutes les applications",
        selectedOnly: "Applications sélectionnées uniquement",
        allExceptSelected: "Toutes sauf les applications sélectionnées",
        exceptions: "Exceptions",
        noExceptions: "Aucune application sélectionnée",
        addApp: "Ajouter une application…",
        feedback: "Afficher le retour visuel",
        accessibilityCaption: "La protection utilise Accessibilité pour observer uniquement les raccourcis et le bouton qu’elle protège.",
        holdQuitHUDFormat: "Maintenez %@ pour quitter",
        holdCloseHUDFormat: "Maintenez %@ pour fermer",
        doubleQuitHUDFormat: "Appuyez à nouveau sur %@ pour quitter",
        doubleCloseHUDFormat: "Appuyez à nouveau sur %@ pour fermer",
        extraQuitHUDFormat: "Utilisez %@ pour quitter",
        extraCloseHUDFormat: "Utilisez %@ pour fermer",
        cancelHint: "Échap pour annuler",
        releaseHint: "Relâchez pour confirmer",
        shiftKey: "Maj",
        optionKey: "Option",
        controlKey: "Contrôle",
        lockShortcutCaption: "Retient le verrouillage d’écran ⌃⌘Q jusqu’à confirmation. Tant que la protection est active, Vorssaint gère le raccourci et le rend à macOS quand elle est désactivée ou que l’app se ferme.",
        lockShortcutOwnedByQuit: "La protection de ⌘Q utilise Contrôle comme touche supplémentaire, donc ⌃⌘Q y confirme la fermeture et cette protection reste désactivée.",
        holdLockHUDFormat: "Maintenez %@ pour verrouiller",
        doubleLockHUDFormat: "Appuyez à nouveau sur %@ pour verrouiller",
        touchIDTitle: "Bouton Touch ID / alimentation",
        touchIDEnabled: "Protéger ce bouton",
        touchIDEnabledCaption: "Un appui rapide ne verrouille plus le Mac. Le raccourci de verrouillage et l’élément Verrouiller l’écran continuent de fonctionner.",
        touchIDIgnore: "Ne jamais verrouiller avec le bouton",
        touchIDHoldUnavailable: "Ce Mac n’indique pas quand le bouton est relâché ; seule l’option de ne jamais verrouiller fonctionne.",
        touchIDHoldHUD: "Continuez à maintenir pour verrouiller",
        releaseCancelHint: "Relâchez pour annuler"
    )

    static let it = QuitProtectionStrings(
        name: "Protezione chiusura e uscita",
        description: "Protegge ⌘Q e ⌘W da pressioni accidentali",
        intro: "Configura ogni abbreviazione in modo indipendente. L’azione originale viene eseguita solo dopo la conferma.",
        enabled: "Proteggi questa abbreviazione",
        enabledCaption: "Le altre abbreviazioni con Command continuano a funzionare normalmente.",
        mode: "Modalità di conferma",
        hold: "Tieni premuto per confermare",
        doublePress: "Premi due volte",
        extraModifier: "Richiedi modificatore aggiuntivo",
        holdDuration: "Durata della pressione",
        doublePressInterval: "Intervallo tra le pressioni",
        modifier: "Modificatore aggiuntivo",
        appScope: "Applicazioni",
        allApps: "Tutte le applicazioni",
        selectedOnly: "Solo applicazioni selezionate",
        allExceptSelected: "Tutte tranne quelle selezionate",
        exceptions: "Eccezioni",
        noExceptions: "Nessuna applicazione selezionata",
        addApp: "Aggiungi applicazione…",
        feedback: "Mostra feedback visivo",
        accessibilityCaption: "La protezione usa Accessibilità per osservare solo le abbreviazioni e il pulsante che protegge.",
        holdQuitHUDFormat: "Tieni premuto %@ per uscire",
        holdCloseHUDFormat: "Tieni premuto %@ per chiudere",
        doubleQuitHUDFormat: "Premi di nuovo %@ per uscire",
        doubleCloseHUDFormat: "Premi di nuovo %@ per chiudere",
        extraQuitHUDFormat: "Usa %@ per uscire",
        extraCloseHUDFormat: "Usa %@ per chiudere",
        cancelHint: "Esc annulla",
        releaseHint: "Rilascia per confermare",
        shiftKey: "Maiuscole",
        optionKey: "Opzione",
        controlKey: "Controllo",
        lockShortcutCaption: "Trattiene il blocco schermo ⌃⌘Q finché non viene confermato. Finché è attivo, l’abbreviazione la gestisce Vorssaint, che la restituisce a macOS quando il controllo viene spento o l’app si chiude.",
        lockShortcutOwnedByQuit: "La protezione di ⌘Q usa Controllo come tasto aggiuntivo, quindi ⌃⌘Q conferma l’uscita e questa protezione resta spenta.",
        holdLockHUDFormat: "Tieni premuto %@ per bloccare",
        doubleLockHUDFormat: "Premi di nuovo %@ per bloccare",
        touchIDTitle: "Pulsante Touch ID / accensione",
        touchIDEnabled: "Proteggi questo pulsante",
        touchIDEnabledCaption: "Un tocco veloce non blocca più il Mac. L’abbreviazione di blocco e la voce Blocca schermo continuano a funzionare.",
        touchIDIgnore: "Non bloccare mai con il pulsante",
        touchIDHoldUnavailable: "Questo Mac non segnala quando il pulsante viene rilasciato, quindi funziona solo l’opzione di non bloccare mai.",
        touchIDHoldHUD: "Continua a tenere premuto per bloccare",
        releaseCancelHint: "Rilascia per annullare"
    )

    static let tr = QuitProtectionStrings(
        name: "Kapatma ve çıkış koruması",
        description: "⌘Q ve ⌘W kısayollarını yanlışlıkla basılmaya karşı korur",
        intro: "Her kısayolu bağımsız yapılandırın. Asıl eylem yalnızca seçilen onaydan sonra iletilir.",
        enabled: "Bu kısayolu koru",
        enabledCaption: "Diğer Command kısayolları normal şekilde çalışmaya devam eder.",
        mode: "Onay modu",
        hold: "Onaylamak için basılı tutun",
        doublePress: "İki kez basın",
        extraModifier: "Ek niteleyici tuş iste",
        holdDuration: "Basılı tutma süresi",
        doublePressInterval: "Basma aralığı",
        modifier: "Ek niteleyici",
        appScope: "Uygulamalar",
        allApps: "Tüm uygulamalar",
        selectedOnly: "Yalnızca seçilen uygulamalar",
        allExceptSelected: "Seçilenler dışındaki tümü",
        exceptions: "İstisnalar",
        noExceptions: "Hiçbir uygulama seçilmedi",
        addApp: "Uygulama ekle…",
        feedback: "Görsel geri bildirim göster",
        accessibilityCaption: "Koruma, Erişilebilirlik’i yalnızca koruduğu kısayolları ve düğmeyi izlemek için kullanır.",
        holdQuitHUDFormat: "Çıkmak için %@ basılı tutun",
        holdCloseHUDFormat: "Kapatmak için %@ basılı tutun",
        doubleQuitHUDFormat: "Çıkmak için tekrar %@ basın",
        doubleCloseHUDFormat: "Kapatmak için tekrar %@ basın",
        extraQuitHUDFormat: "Çıkmak için %@ kullanın",
        extraCloseHUDFormat: "Kapatmak için %@ kullanın",
        cancelHint: "Esc iptal eder",
        releaseHint: "Onaylamak için bırakın",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "⌃⌘Q ekran kilidini onaylanana kadar tutar. Bu açıkken kısayolu Vorssaint yönetir ve kapatıldığında ya da uygulamadan çıkıldığında macOS’a geri verir.",
        lockShortcutOwnedByQuit: "⌘Q koruması ek tuş olarak Control kullanıyor, bu yüzden ⌃⌘Q orada çıkışı onaylar ve bu koruma kapalı kalır.",
        holdLockHUDFormat: "Kilitlemek için %@ basılı tutun",
        doubleLockHUDFormat: "Kilitlemek için tekrar %@ basın",
        touchIDTitle: "Touch ID / Güç düğmesi",
        touchIDEnabled: "Bu düğmeyi koru",
        touchIDEnabledCaption: "Hızlı bir dokunuş artık Mac’i kilitlemez. Kilit kısayolu ve Ekranı Kilitle öğesi çalışmaya devam eder.",
        touchIDIgnore: "Düğmeyle asla kilitleme",
        touchIDHoldUnavailable: "Bu Mac düğmenin ne zaman bırakıldığını bildirmiyor; yalnızca asla kilitleme seçeneği çalışır.",
        touchIDHoldHUD: "Kilitlemek için basılı tutmaya devam edin",
        releaseCancelHint: "İptal için bırakın"
    )

    static let ru = QuitProtectionStrings(
        name: "Защита от закрытия",
        description: "Защищает ⌘Q и ⌘W от случайного нажатия",
        intro: "Настройте каждое сочетание отдельно. Исходное действие выполняется только после подтверждения.",
        enabled: "Защитить это сочетание",
        enabledCaption: "Остальные сочетания с Command продолжают работать как обычно.",
        mode: "Режим подтверждения",
        hold: "Удержание для подтверждения",
        doublePress: "Двойное нажатие",
        extraModifier: "Требовать доп. клавишу",
        holdDuration: "Время удержания",
        doublePressInterval: "Интервал между нажатиями",
        modifier: "Дополнительная клавиша",
        appScope: "Приложения",
        allApps: "Все приложения",
        selectedOnly: "Только выбранные приложения",
        allExceptSelected: "Все, кроме выбранных",
        exceptions: "Исключения",
        noExceptions: "Приложения не выбраны",
        addApp: "Добавить приложение…",
        feedback: "Показывать подсказку",
        accessibilityCaption: "Защита использует Универсальный доступ только для отслеживания защищаемых сочетаний и кнопки.",
        holdQuitHUDFormat: "Удерживайте %@ для выхода",
        holdCloseHUDFormat: "Удерживайте %@ для закрытия",
        doubleQuitHUDFormat: "Нажмите %@ ещё раз для выхода",
        doubleCloseHUDFormat: "Нажмите %@ ещё раз для закрытия",
        extraQuitHUDFormat: "Используйте %@ для выхода",
        extraCloseHUDFormat: "Используйте %@ для закрытия",
        cancelHint: "Esc отменяет",
        releaseHint: "Отпустите для подтверждения",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "Удерживает блокировку экрана ⌃⌘Q до подтверждения. Пока защита включена, сочетанием управляет Vorssaint и возвращает его macOS, когда защита выключена или приложение закрыто.",
        lockShortcutOwnedByQuit: "Защита ⌘Q использует Control как доп. клавишу, поэтому ⌃⌘Q там подтверждает выход, а эта защита остаётся выключенной.",
        holdLockHUDFormat: "Удерживайте %@ для блокировки",
        doubleLockHUDFormat: "Нажмите %@ ещё раз для блокировки",
        touchIDTitle: "Кнопка Touch ID / питания",
        touchIDEnabled: "Защитить эту кнопку",
        touchIDEnabledCaption: "Короткое касание больше не блокирует Mac. Сочетание блокировки и пункт «Заблокировать экран» продолжают работать.",
        touchIDIgnore: "Никогда не блокировать кнопкой",
        touchIDHoldUnavailable: "Этот Mac не сообщает, когда кнопка отпущена, поэтому работает только вариант «никогда не блокировать».",
        touchIDHoldHUD: "Продолжайте удерживать для блокировки",
        releaseCancelHint: "Отпустите для отмены"
    )

    static let ja = QuitProtectionStrings(
        name: "終了・閉じるの誤操作防止",
        description: "⌘Q と ⌘W の誤入力を防止します",
        intro: "ショートカットごとに個別に設定できます。確認操作を行ってから元の操作が実行されます。",
        enabled: "このショートカットを保護",
        enabledCaption: "その他の Command ショートカットは通常どおり動作します。",
        mode: "確認モード",
        hold: "長押しで確認",
        doublePress: "2回押して確認",
        extraModifier: "追加の修飾キーを要求",
        holdDuration: "長押し時間",
        doublePressInterval: "連続入力の間隔",
        modifier: "追加の修飾キー",
        appScope: "対象アプリケーション",
        allApps: "すべてのアプリケーション",
        selectedOnly: "選択したアプリケーションのみ",
        allExceptSelected: "選択したアプリケーション以外すべて",
        exceptions: "例外リスト",
        noExceptions: "アプリケーションが選択されていません",
        addApp: "アプリケーションを追加…",
        feedback: "視覚的フィードバックを表示",
        accessibilityCaption: "この機能はアクセシビリティを使用して、保護対象のショートカットとボタンのみをグローバルに監視します。",
        holdQuitHUDFormat: "終了するには %@ を長押し",
        holdCloseHUDFormat: "閉じるには %@ を長押し",
        doubleQuitHUDFormat: "終了するにはもう一度 %@ を入力",
        doubleCloseHUDFormat: "閉じるにはもう一度 %@ を入力",
        extraQuitHUDFormat: "終了するには %@ を使用",
        extraCloseHUDFormat: "閉じるには %@ を使用",
        cancelHint: "Esc でキャンセル",
        releaseHint: "離して確認",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "⌃⌘Q による画面のロックを、確認が取れるまで保留します。オンの間は Vorssaint がこのショートカットを処理し、オフにするかアプリを終了すると macOS に戻します。",
        lockShortcutOwnedByQuit: "⌘Q の保護が追加の修飾キーに Control を使っているため、⌃⌘Q は終了の確認になり、この保護はオフのままです。",
        holdLockHUDFormat: "ロックするには %@ を長押し",
        doubleLockHUDFormat: "ロックするにはもう一度 %@ を入力",
        touchIDTitle: "Touch ID / 電源ボタン",
        touchIDEnabled: "このボタンを保護",
        touchIDEnabledCaption: "軽く触れただけでは Mac がロックされなくなります。ロックのショートカットと「画面をロック」項目は引き続き使えます。",
        touchIDIgnore: "ボタンでは常にロックしない",
        touchIDHoldUnavailable: "この Mac はボタンが離された時点を通知しないため、「常にロックしない」のみ使えます。",
        touchIDHoldHUD: "ロックするには長押しを続けてください",
        releaseCancelHint: "離すとキャンセル"
    )

    static let ko = QuitProtectionStrings(
        name: "종료 및 닫기 보호",
        description: "⌘Q 및 ⌘W의 실수 입력을 방지합니다",
        intro: "각 단축키를 개별적으로 설정합니다. 선택한 확인 동작을 완료해야 원래 동작이 실행됩니다.",
        enabled: "이 단축키 보호",
        enabledCaption: "다른 Command 단축키는 정상적으로 작동합니다.",
        mode: "확인 방식",
        hold: "길게 눌러 확인",
        doublePress: "두 번 눌러 확인",
        extraModifier: "추가 보조 키 필요",
        holdDuration: "길게 누르는 시간",
        doublePressInterval: "입력 간격",
        modifier: "추가 보조 키",
        appScope: "응용 프로그램",
        allApps: "모든 응용 프로그램",
        selectedOnly: "선택한 응용 프로그램만",
        allExceptSelected: "선택한 응용 프로그램 제외 전체",
        exceptions: "예외 목록",
        noExceptions: "선택된 응용 프로그램 없음",
        addApp: "응용 프로그램 추가…",
        feedback: "시각적 피드백 표시",
        accessibilityCaption: "이 기능은 손쉬운 사용을 사용하여 보호하는 단축키와 버튼만 전역적으로 감지합니다.",
        holdQuitHUDFormat: "종료하려면 %@ 길게 누르기",
        holdCloseHUDFormat: "닫으려면 %@ 길게 누르기",
        doubleQuitHUDFormat: "종료하려면 %@ 다시 누르기",
        doubleCloseHUDFormat: "닫으려면 %@ 다시 누르기",
        extraQuitHUDFormat: "종료하려면 %@ 사용",
        extraCloseHUDFormat: "닫으려면 %@ 사용",
        cancelHint: "Esc 취소",
        releaseHint: "손을 떼어 확인",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "⌃⌘Q 화면 잠금을 확인될 때까지 보류합니다. 켜져 있는 동안 Vorssaint가 단축키를 처리하며, 끄거나 앱을 종료하면 macOS에 돌려줍니다.",
        lockShortcutOwnedByQuit: "⌘Q 보호가 추가 보조 키로 Control을 사용하므로 ⌃⌘Q는 종료 확인에 쓰이고 이 보호는 꺼진 상태로 유지됩니다.",
        holdLockHUDFormat: "잠그려면 %@ 길게 누르기",
        doubleLockHUDFormat: "잠그려면 %@ 다시 누르기",
        touchIDTitle: "Touch ID / 전원 버튼",
        touchIDEnabled: "이 버튼 보호",
        touchIDEnabledCaption: "짧게 눌러도 더 이상 Mac이 잠기지 않습니다. 잠금 단축키와 화면 잠금 항목은 계속 작동합니다.",
        touchIDIgnore: "버튼으로 잠그지 않기",
        touchIDHoldUnavailable: "이 Mac은 버튼을 뗀 시점을 알려 주지 않으므로 ‘잠그지 않기’ 옵션만 작동합니다.",
        touchIDHoldHUD: "잠그려면 계속 누르세요",
        releaseCancelHint: "떼면 취소"
    )

    static let zhHans = QuitProtectionStrings(
        name: "退出与关闭保护",
        description: "防止误按 ⌘Q 和 ⌘W",
        intro: "可单独配置每个快捷键。仅在完成选定的确认操作后才执行原操作。",
        enabled: "保护此快捷键",
        enabledCaption: "其他 Command 快捷键仍可正常使用。",
        mode: "确认模式",
        hold: "按住以确认",
        doublePress: "连按两次",
        extraModifier: "需要额外修饰键",
        holdDuration: "按住时长",
        doublePressInterval: "连按间隔",
        modifier: "额外修饰键",
        appScope: "应用程序",
        allApps: "所有应用程序",
        selectedOnly: "仅所选应用程序",
        allExceptSelected: "除所选外的所有应用程序",
        exceptions: "例外列表",
        noExceptions: "未选择任何应用程序",
        addApp: "添加应用程序…",
        feedback: "显示视觉反馈",
        accessibilityCaption: "该保护功能使用辅助功能仅全局监听其保护的快捷键和按钮。",
        holdQuitHUDFormat: "按住 %@ 以退出",
        holdCloseHUDFormat: "按住 %@ 以关闭",
        doubleQuitHUDFormat: "再次按 %@ 以退出",
        doubleCloseHUDFormat: "再次按 %@ 以关闭",
        extraQuitHUDFormat: "使用 %@ 以退出",
        extraCloseHUDFormat: "使用 %@ 以关闭",
        cancelHint: "Esc 取消",
        releaseHint: "松开以确认",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "在确认之前暂缓 ⌃⌘Q 锁定屏幕。开启期间由 Vorssaint 处理该快捷键，关闭或退出 App 时交还给 macOS。",
        lockShortcutOwnedByQuit: "⌘Q 保护使用 Control 作为额外修饰键，因此 ⌃⌘Q 用于确认退出，此保护保持关闭。",
        holdLockHUDFormat: "按住 %@ 以锁定",
        doubleLockHUDFormat: "再次按 %@ 以锁定",
        touchIDTitle: "Touch ID / 电源按钮",
        touchIDEnabled: "保护此按钮",
        touchIDEnabledCaption: "轻点一下不再锁定 Mac。锁定快捷键和“锁定屏幕”菜单项仍然可用。",
        touchIDIgnore: "永不通过按钮锁定",
        touchIDHoldUnavailable: "此 Mac 不报告按钮何时松开，因此只有“永不锁定”选项可用。",
        touchIDHoldHUD: "继续按住以锁定",
        releaseCancelHint: "松开以取消"
    )

    static let zhTW = QuitProtectionStrings(
        name: "結束與關閉保護",
        description: "防止誤按 ⌘Q 和 ⌘W",
        intro: "可單獨設定每個快速鍵。僅在完成選定的確認動作後才執行原動作。",
        enabled: "保護此快速鍵",
        enabledCaption: "其他 Command 快速鍵仍可正常使用。",
        mode: "確認模式",
        hold: "按住以確認",
        doublePress: "連按兩次",
        extraModifier: "需要額外變更鍵",
        holdDuration: "按住時間",
        doublePressInterval: "連按間隔",
        modifier: "額外變更鍵",
        appScope: "應用程式",
        allApps: "所有應用程式",
        selectedOnly: "僅所選應用程式",
        allExceptSelected: "除所選外的所有應用程式",
        exceptions: "例外清單",
        noExceptions: "未選取任何應用程式",
        addApp: "加入應用程式…",
        feedback: "顯示視覺回饋",
        accessibilityCaption: "該保護功能使用輔助使用僅全域監聽其保護的快速鍵和按鈕。",
        holdQuitHUDFormat: "按住 %@ 以結束",
        holdCloseHUDFormat: "按住 %@ 以關閉",
        doubleQuitHUDFormat: "再次按 %@ 以結束",
        doubleCloseHUDFormat: "再次按 %@ 以關閉",
        extraQuitHUDFormat: "使用 %@ 以結束",
        extraCloseHUDFormat: "使用 %@ 以關閉",
        cancelHint: "Esc 取消",
        releaseHint: "放開以確認",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "在確認之前暫緩 ⌃⌘Q 鎖定螢幕。開啟期間由 Vorssaint 處理該快速鍵，關閉或結束 App 時交還給 macOS。",
        lockShortcutOwnedByQuit: "⌘Q 保護使用 Control 作為額外變更鍵，因此 ⌃⌘Q 用於確認結束，此保護維持關閉。",
        holdLockHUDFormat: "按住 %@ 以鎖定",
        doubleLockHUDFormat: "再次按 %@ 以鎖定",
        touchIDTitle: "Touch ID / 電源按鈕",
        touchIDEnabled: "保護此按鈕",
        touchIDEnabledCaption: "輕點一下不再鎖定 Mac。鎖定快速鍵和「鎖定螢幕」選單項目仍然可用。",
        touchIDIgnore: "永不透過按鈕鎖定",
        touchIDHoldUnavailable: "此 Mac 不會回報按鈕何時放開，因此只有「永不鎖定」選項可用。",
        touchIDHoldHUD: "繼續按住以鎖定",
        releaseCancelHint: "放開以取消"
    )

    static let zhHK = QuitProtectionStrings(
        name: "結束與關閉保護",
        description: "防止誤按 ⌘Q 和 ⌘W",
        intro: "可單獨設定每個快捷鍵。僅在完成選定的確認動作後才執行原動作。",
        enabled: "保護此快捷鍵",
        enabledCaption: "其他 Command 快捷鍵仍可正常使用。",
        mode: "確認模式",
        hold: "按住以確認",
        doublePress: "連按兩次",
        extraModifier: "需要額外修飾鍵",
        holdDuration: "按住時間",
        doublePressInterval: "連按間隔",
        modifier: "額外修飾鍵",
        appScope: "應用程式",
        allApps: "所有應用程式",
        selectedOnly: "僅所選應用程式",
        allExceptSelected: "除所選外的所有應用程式",
        exceptions: "例外清單",
        noExceptions: "未選取任何應用程式",
        addApp: "加入應用程式…",
        feedback: "顯示視覺回饋",
        accessibilityCaption: "該保護功能使用輔助使用僅全域監聽其保護的快捷鍵和按鈕。",
        holdQuitHUDFormat: "按住 %@ 以結束",
        holdCloseHUDFormat: "按住 %@ 以關閉",
        doubleQuitHUDFormat: "再次按 %@ 以結束",
        doubleCloseHUDFormat: "再次按 %@ 以關閉",
        extraQuitHUDFormat: "使用 %@ 以結束",
        extraCloseHUDFormat: "使用 %@ 以關閉",
        cancelHint: "Esc 取消",
        releaseHint: "放開以確認",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "在確認之前暫緩 ⌃⌘Q 鎖定螢幕。開啟期間由 Vorssaint 處理該快捷鍵，關閉或結束 App 時交還給 macOS。",
        lockShortcutOwnedByQuit: "⌘Q 保護使用 Control 作為額外修飾鍵，因此 ⌃⌘Q 用於確認結束，此保護維持關閉。",
        holdLockHUDFormat: "按住 %@ 以鎖定",
        doubleLockHUDFormat: "再次按 %@ 以鎖定",
        touchIDTitle: "Touch ID / 電源按鈕",
        touchIDEnabled: "保護此按鈕",
        touchIDEnabledCaption: "輕點一下不再鎖定 Mac。鎖定快捷鍵和「鎖定螢幕」選單項目仍然可用。",
        touchIDIgnore: "永不透過按鈕鎖定",
        touchIDHoldUnavailable: "此 Mac 不會回報按鈕何時放開，因此只有「永不鎖定」選項可用。",
        touchIDHoldHUD: "繼續按住以鎖定",
        releaseCancelHint: "放開以取消"
    )

    static let uk = QuitProtectionStrings(
        name: "Захист від виходу та закриття",
        description: "Захищає ⌘Q та ⌘W від випадкових натискань",
        intro: "Налаштуйте кожне клавіатурне скорочення окремо. Початкова дія виконується лише після вибраного підтвердження.",
        enabled: "Захищати це клавіатурне скорочення",
        enabledCaption: "Інші клавіатурні скорочення з Command продовжують працювати як зазвичай.",
        mode: "Режим підтвердження",
        hold: "Утримувати для підтвердження",
        doublePress: "Натиснути двічі",
        extraModifier: "Вимагати додаткову клавішу-модифікатор",
        holdDuration: "Тривалість утримання",
        doublePressInterval: "Інтервал подвійного натискання",
        modifier: "Додаткова клавіша-модифікатор",
        appScope: "Програми",
        allApps: "Усі програми",
        selectedOnly: "Лише вибрані програми",
        allExceptSelected: "Усі, крім вибраних програм",
        exceptions: "Винятки",
        noExceptions: "Не вибрано жодної програми",
        addApp: "Додати програму…",
        feedback: "Показувати візуальний відгук",
        accessibilityCaption: "Для захисту використовується дозвіл «Доступність», щоб глобально відстежувати лише захищені скорочення та кнопку.",
        holdQuitHUDFormat: "Утримуйте %@, щоб завершити програму",
        holdCloseHUDFormat: "Утримуйте %@, щоб закрити вікно",
        doubleQuitHUDFormat: "Натисніть %@ ще раз, щоб завершити програму",
        doubleCloseHUDFormat: "Натисніть %@ ще раз, щоб закрити вікно",
        extraQuitHUDFormat: "Використайте %@, щоб завершити програму",
        extraCloseHUDFormat: "Використайте %@, щоб закрити вікно",
        cancelHint: "Esc скасовує",
        releaseHint: "Відпустіть для підтвердження",
        shiftKey: "Shift",
        optionKey: "Option",
        controlKey: "Control",
        lockShortcutCaption: "Утримує блокування екрана ⌃⌘Q до підтвердження. Поки захист увімкнено, скорочення обробляє Vorssaint і повертає його macOS, коли захист вимкнено або застосунок закрито.",
        lockShortcutOwnedByQuit: "Захист ⌘Q використовує Control як додаткову клавішу, тож ⌃⌘Q там підтверджує вихід, а цей захист лишається вимкненим.",
        holdLockHUDFormat: "Утримуйте %@, щоб заблокувати",
        doubleLockHUDFormat: "Натисніть %@ ще раз, щоб заблокувати",
        touchIDTitle: "Кнопка Touch ID / живлення",
        touchIDEnabled: "Захищати цю кнопку",
        touchIDEnabledCaption: "Короткий дотик більше не блокує Mac. Скорочення блокування та пункт «Заблокувати екран» і далі працюють.",
        touchIDIgnore: "Ніколи не блокувати кнопкою",
        touchIDHoldUnavailable: "Цей Mac не повідомляє, коли кнопку відпущено, тому працює лише варіант «ніколи не блокувати».",
        touchIDHoldHUD: "Продовжуйте утримувати, щоб заблокувати",
        releaseCancelHint: "Відпустіть, щоб скасувати"
    )
}
