// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

enum ScratchpadLibraryLabel: Int, CaseIterable {
    case inbox, all, pinned, trash, folders, newFolder, renameFolder, deleteFolder, move
    case pin, unpin, temporary, source, sidebar, search, delete, restore, emptyTrash
    case deleteForever, permanentMessage, importNotes, backup, restoreBackup, exportFolder
    case replaceMessage, folderMessage, liveEditing, failed
    case duplicate, checklistTools, uncheckAll, removeCompleted
}

struct ScratchpadLibraryStrings {
    let language: AppLanguage
    subscript(_ label: ScratchpadLibraryLabel) -> String { Self.translations[language]![label.rawValue] }

    private static let translations: [AppLanguage: [String]] = [
        .enUS: ["Inbox", "All notes", "Pinned", "Trash", "Folders", "New folder", "Rename folder", "Delete folder", "Move to folder", "Pin note", "Unpin note", "Temporary note", "Markdown source", "Browse notes", "Search notes", "Move to Trash", "Restore", "Empty Trash", "Delete permanently", "Permanently delete these notes? This cannot be undone.", "Import notes", "Back up Scratchpad", "Restore Scratchpad backup", "Export folder as Markdown", "Replace your notes with this backup? A recovery copy of your current notes will be saved first.", "The notes in this folder will move to Inbox.", "Live Markdown", "The operation could not be completed. Your existing notes were preserved.", "Duplicate note", "Checklist", "Uncheck all", "Remove completed items"],
        .ptBR: ["Entrada", "Todas as notas", "Fixadas", "Lixeira", "Pastas", "Nova pasta", "Renomear pasta", "Excluir pasta", "Mover para pasta", "Fixar nota", "Desafixar nota", "Nota temporária", "Código Markdown", "Explorar notas", "Buscar notas", "Mover para Lixeira", "Restaurar", "Esvaziar Lixeira", "Excluir permanentemente", "Excluir estas notas permanentemente? Não é possível desfazer.", "Importar notas", "Fazer backup do Rascunho", "Restaurar backup do Rascunho", "Exportar pasta como Markdown", "Substituir as notas por este backup? Uma cópia das notas atuais será salva primeiro.", "As notas desta pasta serão movidas para Entrada.", "Markdown ao vivo", "Não foi possível concluir. As notas existentes foram preservadas.", "Duplicar nota", "Lista de tarefas", "Desmarcar tudo", "Remover itens concluídos"],
        .tr: ["Gelen kutusu", "Tüm notlar", "Sabitlenenler", "Çöp Kutusu", "Klasörler", "Yeni klasör", "Klasörü yeniden adlandır", "Klasörü sil", "Klasöre taşı", "Notu sabitle", "Sabitlemeyi kaldır", "Geçici not", "Markdown kaynağı", "Notlara göz at", "Notlarda ara", "Çöp Kutusuna taşı", "Geri yükle", "Çöp Kutusunu boşalt", "Kalıcı olarak sil", "Bu notlar kalıcı olarak silinsin mi? Geri alınamaz.", "Notları içe aktar", "Notları yedekle", "Not yedeğini geri yükle", "Klasörü Markdown olarak dışa aktar", "Notlar bu yedekle değiştirilsin mi? Önce mevcut notların kopyası kaydedilecek.", "Bu klasördeki notlar Gelen kutusuna taşınacak.", "Canlı Markdown", "İşlem tamamlanamadı. Mevcut notlar korundu.", "Notu çoğalt", "Kontrol listesi", "Tüm işaretleri kaldır", "Tamamlanan öğeleri kaldır"],
        .ru: ["Входящие", "Все заметки", "Закреплённые", "Корзина", "Папки", "Новая папка", "Переименовать папку", "Удалить папку", "Переместить в папку", "Закрепить заметку", "Открепить заметку", "Временная заметка", "Исходный Markdown", "Обзор заметок", "Поиск заметок", "В Корзину", "Восстановить", "Очистить Корзину", "Удалить навсегда", "Удалить эти заметки навсегда? Это нельзя отменить.", "Импорт заметок", "Создать резервную копию", "Восстановить резервную копию", "Экспорт папки в Markdown", "Заменить заметки этой копией? Сначала будет сохранена копия текущих заметок.", "Заметки этой папки будут перемещены во Входящие.", "Живой Markdown", "Не удалось завершить операцию. Заметки сохранены.", "Дублировать заметку", "Список задач", "Снять все отметки", "Убрать выполненные пункты"],
        .es: ["Entrada", "Todas las notas", "Fijadas", "Papelera", "Carpetas", "Nueva carpeta", "Renombrar carpeta", "Eliminar carpeta", "Mover a carpeta", "Fijar nota", "Desfijar nota", "Nota temporal", "Fuente Markdown", "Explorar notas", "Buscar notas", "Mover a Papelera", "Restaurar", "Vaciar Papelera", "Eliminar definitivamente", "¿Eliminar estas notas definitivamente? No se puede deshacer.", "Importar notas", "Crear copia de Scratchpad", "Restaurar copia de Scratchpad", "Exportar carpeta como Markdown", "¿Reemplazar las notas con esta copia? Primero se guardará una copia de las notas actuales.", "Las notas de esta carpeta se moverán a Entrada.", "Markdown en vivo", "No se pudo completar la operación. Se conservaron las notas existentes.", "Duplicar nota", "Lista de tareas", "Desmarcar todo", "Quitar elementos completados"],
        .sk: ["Doručené", "Všetky poznámky", "Pripnuté", "Kôš", "Priečinky", "Nový priečinok", "Premenovať priečinok", "Odstrániť priečinok", "Presunúť do priečinka", "Pripnúť poznámku", "Odopnúť poznámku", "Dočasná poznámka", "Zdroj Markdown", "Prehliadať poznámky", "Hľadať poznámky", "Presunúť do Koša", "Obnoviť", "Vyprázdniť Kôš", "Natrvalo odstrániť", "Natrvalo odstrániť tieto poznámky? Toto sa nedá vrátiť.", "Importovať poznámky", "Zálohovať poznámky", "Obnoviť zálohu", "Exportovať priečinok ako Markdown", "Nahradiť poznámky touto zálohou? Najprv sa uloží kópia aktuálnych poznámok.", "Poznámky z priečinka sa presunú do Doručených.", "Živý Markdown", "Operáciu sa nepodarilo dokončiť. Poznámky zostali zachované.", "Duplikovať poznámku", "Kontrolný zoznam", "Zrušiť všetky začiarknutia", "Odstrániť dokončené položky"],
        .de: ["Eingang", "Alle Notizen", "Angeheftet", "Papierkorb", "Ordner", "Neuer Ordner", "Ordner umbenennen", "Ordner löschen", "In Ordner verschieben", "Notiz anheften", "Notiz lösen", "Temporäre Notiz", "Markdown-Quelltext", "Notizen durchsuchen", "Notizen suchen", "In Papierkorb verschieben", "Wiederherstellen", "Papierkorb leeren", "Endgültig löschen", "Diese Notizen endgültig löschen? Dies kann nicht rückgängig gemacht werden.", "Notizen importieren", "Scratchpad sichern", "Scratchpad-Sicherung wiederherstellen", "Ordner als Markdown exportieren", "Notizen durch diese Sicherung ersetzen? Zuerst wird eine Kopie der aktuellen Notizen gespeichert.", "Die Notizen dieses Ordners werden in den Eingang verschoben.", "Live-Markdown", "Der Vorgang konnte nicht abgeschlossen werden. Bestehende Notizen wurden erhalten.", "Notiz duplizieren", "Checkliste", "Alle abwählen", "Erledigte Einträge entfernen"],
        .fr: ["Boîte de réception", "Toutes les notes", "Épinglées", "Corbeille", "Dossiers", "Nouveau dossier", "Renommer le dossier", "Supprimer le dossier", "Déplacer vers un dossier", "Épingler la note", "Désépingler la note", "Note temporaire", "Source Markdown", "Parcourir les notes", "Rechercher des notes", "Mettre à la Corbeille", "Restaurer", "Vider la Corbeille", "Supprimer définitivement", "Supprimer définitivement ces notes ? Cette action est irréversible.", "Importer des notes", "Sauvegarder Scratchpad", "Restaurer une sauvegarde", "Exporter le dossier en Markdown", "Remplacer les notes par cette sauvegarde ? Une copie des notes actuelles sera enregistrée d’abord.", "Les notes de ce dossier seront déplacées dans la boîte de réception.", "Markdown en direct", "L’opération a échoué. Les notes existantes ont été conservées.", "Dupliquer la note", "Liste de tâches", "Tout décocher", "Retirer les éléments terminés"],
        .it: ["Posta in arrivo", "Tutte le note", "Fissate", "Cestino", "Cartelle", "Nuova cartella", "Rinomina cartella", "Elimina cartella", "Sposta nella cartella", "Fissa nota", "Rimuovi fissaggio", "Nota temporanea", "Sorgente Markdown", "Sfoglia note", "Cerca note", "Sposta nel Cestino", "Ripristina", "Svuota Cestino", "Elimina definitivamente", "Eliminare queste note definitivamente? Non è possibile annullare.", "Importa note", "Esegui backup di Scratchpad", "Ripristina backup", "Esporta cartella come Markdown", "Sostituire le note con questo backup? Prima verrà salvata una copia delle note attuali.", "Le note di questa cartella verranno spostate nella Posta in arrivo.", "Markdown dal vivo", "Impossibile completare l’operazione. Le note esistenti sono state conservate.", "Duplica nota", "Lista di controllo", "Deseleziona tutto", "Rimuovi elementi completati"],
        .ja: ["受信箱", "すべてのノート", "ピン留め", "ゴミ箱", "フォルダ", "新規フォルダ", "フォルダ名を変更", "フォルダを削除", "フォルダに移動", "ノートをピン留め", "ピン留めを解除", "一時ノート", "Markdownソース", "ノートを参照", "ノートを検索", "ゴミ箱に移動", "復元", "ゴミ箱を空にする", "完全に削除", "これらのノートを完全に削除しますか？元に戻せません。", "ノートを読み込む", "Scratchpadをバックアップ", "バックアップを復元", "フォルダをMarkdownで書き出す", "このバックアップでノートを置き換えますか？現在のノートのコピーを先に保存します。", "このフォルダのノートは受信箱に移動します。", "ライブMarkdown", "操作を完了できませんでした。既存のノートは保持されました。", "ノートを複製", "チェックリスト", "すべてのチェックを外す", "完了した項目を除く"],
        .ko: ["받은 편지함", "모든 노트", "고정됨", "휴지통", "폴더", "새 폴더", "폴더 이름 변경", "폴더 삭제", "폴더로 이동", "노트 고정", "고정 해제", "임시 노트", "Markdown 소스", "노트 둘러보기", "노트 검색", "휴지통으로 이동", "복원", "휴지통 비우기", "영구 삭제", "이 노트를 영구 삭제하시겠습니까? 되돌릴 수 없습니다.", "노트 가져오기", "Scratchpad 백업", "백업 복원", "폴더를 Markdown으로 내보내기", "이 백업으로 노트를 교체하시겠습니까? 먼저 현재 노트 사본을 저장합니다.", "이 폴더의 노트는 받은 편지함으로 이동합니다.", "실시간 Markdown", "작업을 완료하지 못했습니다. 기존 노트는 보존되었습니다.", "노트 복제", "체크리스트", "모두 체크 해제", "완료한 항목 제거"],
        .zhHans: ["收件箱", "所有笔记", "已置顶", "废纸篓", "文件夹", "新建文件夹", "重命名文件夹", "删除文件夹", "移到文件夹", "置顶笔记", "取消置顶", "临时笔记", "Markdown 源码", "浏览笔记", "搜索笔记", "移到废纸篓", "恢复", "清空废纸篓", "永久删除", "永久删除这些笔记？此操作无法撤销。", "导入笔记", "备份 Scratchpad", "恢复备份", "将文件夹导出为 Markdown", "用此备份替换笔记？将先保存当前笔记的副本。", "此文件夹中的笔记将移到收件箱。", "实时 Markdown", "无法完成操作。现有笔记已保留。", "复制笔记", "清单", "全部取消勾选", "移除已完成项目"],
        .zhTW: ["收件匣", "所有筆記", "已釘選", "垃圾桶", "資料夾", "新增資料夾", "重新命名資料夾", "刪除資料夾", "移至資料夾", "釘選筆記", "取消釘選", "暫存筆記", "Markdown 原始碼", "瀏覽筆記", "搜尋筆記", "移至垃圾桶", "還原", "清空垃圾桶", "永久刪除", "永久刪除這些筆記？此操作無法復原。", "匯入筆記", "備份 Scratchpad", "還原備份", "將資料夾匯出為 Markdown", "以此備份取代筆記？將先儲存目前筆記的副本。", "此資料夾中的筆記將移至收件匣。", "即時 Markdown", "無法完成操作。現有筆記已保留。", "複製筆記", "檢查清單", "全部取消勾選", "移除已完成項目"],
        .zhHK: ["收件匣", "所有筆記", "已置頂", "垃圾桶", "資料夾", "新增資料夾", "重新命名資料夾", "刪除資料夾", "移至資料夾", "置頂筆記", "取消置頂", "暫存筆記", "Markdown 原始碼", "瀏覽筆記", "搜尋筆記", "移至垃圾桶", "還原", "清空垃圾桶", "永久刪除", "永久刪除這些筆記？此操作無法復原。", "匯入筆記", "備份 Scratchpad", "還原備份", "將資料夾匯出為 Markdown", "以此備份取代筆記？會先儲存目前筆記的副本。", "此資料夾中的筆記會移至收件匣。", "即時 Markdown", "無法完成操作。現有筆記已保留。", "複製筆記", "檢查清單", "全部取消勾選", "移除已完成項目"],
        .uk: ["Вхідні", "Усі нотатки", "Закріплені", "Кошик", "Папки", "Нова папка", "Перейменувати папку", "Видалити папку", "Перемістити до папки", "Закріпити нотатку", "Відкріпити нотатку", "Тимчасова нотатка", "Джерело Markdown", "Переглянути нотатки", "Пошук нотаток", "Перемістити до Кошика", "Відновити", "Очистити Кошик", "Видалити назавжди", "Видалити ці нотатки назавжди? Це неможливо скасувати.", "Імпортувати нотатки", "Створити резервну копію", "Відновити резервну копію", "Експортувати папку в Markdown", "Замінити нотатки цією копією? Спочатку буде збережено копію поточних нотаток.", "Нотатки з цієї папки буде переміщено до Вхідних.", "Живий Markdown", "Не вдалося завершити операцію. Наявні нотатки збережено.", "Дублювати нотатку", "Список завдань", "Зняти всі позначки", "Прибрати виконані пункти"]
    ]
}
