// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

/// Localized strings for the screenshot tool.
struct ScreenshotFeatureStrings {
    let pageTitle: String
    let hubDescription: String
    let captureButton: String
    let panelCaption: String
    let fileNamePrefix: String
    let hintDrag: String
    let hintClick: String
    let hintFullScreen: String
    let hintCancel: String
    let hintRepeat: String
    let freezeToggle: String
    let freezeCaption: String
    let folderLabel: String
    let folderChoose: String
    let subfolderLabel: String
    let subfolderCaption: String
    let fileNamePatternLabel: String
    let fileNamePatternCaption: String
    let fileNumberStartLabel: String
    let fileNumberResetButton: String
    let fileNumberNextFormat: String
    let delayLabel: String
    let delayOff: String
    let delaySecondsFormat: String
    let pointerToggle: String
    let downscaleToggle: String
    let downscaleCaption: String
    let editorTitle: String
    let toolShortcutsTitle: String
    let toolShortcutsToggle: String
    let toolShortcutsCaption: String
    let toolSelect: String
    let toolArrow: String
    let toolLine: String
    let toolRect: String
    let toolEllipse: String
    let toolFreehand: String
    let toolHighlight: String
    let toolText: String
    let toolSticker: String
    let toolCounter: String
    let toolPixelate: String
    let toolRedact: String
    let toolCrop: String
    let textPlaceholder: String
    let cropApply: String
    let cancel: String
    let colorLabel: String
    let strokeLabel: String
    let shadowLabel: String
    let backdropLabel: String
    let backdropNone: String
    let editButton: String
    let copyButton: String
    let saveButton: String
    let saveAsButton: String
    let pinButton: String
    let copyTextButton: String
    let discardTitle: String
    let discardMessage: String
    let discardConfirm: String
    let copiedHUD: String
    let savedHUDFormat: String
    let savedAndCopiedHUDFormat: String
    let defaultActionLabel: String
    let defaultActionCaption: String
    let defaultActionNone: String
    let defaultActionSaveAndCopy: String
    let captureFailed: String
    let pinOpacity: String
    let pinClickThrough: String
    let pinCloseAll: String
    let backdropPaddingLabel: String
    let backdropWallpaperLabel: String
    let backdropImageButton: String
    let backdropSolidLabel: String
    let backdropGradientLabel: String
    let backdropCornersLabel: String
    let backdropSavePreset: String
    let backdropDeletePreset: String
    let backdropCustomLabel: String
    let openEditorToggle: String
    let openEditorCaption: String
    let autoCopyToggle: String
    let autoCopyCaption: String
    let hintLoupe: String
    let lastRegionToggle: String
}

extension FeatureStrings {
    static func screenshot(_ language: AppLanguage) -> ScreenshotFeatureStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension ScreenshotFeatureStrings {
    static let enUS = ScreenshotFeatureStrings(
        pageTitle: "Screenshot",
        hubDescription: "Captures an area, window or screen and annotates it",
        captureButton: "Capture now",
        panelCaption: "Capture an area, window or the whole screen",
        fileNamePrefix: "Screenshot",
        hintDrag: "Drag to select an area",
        hintClick: "Click a window to capture it",
        hintFullScreen: "Return captures the whole screen",
        hintCancel: "Esc cancels",
        hintRepeat: "R repeats the last area",
        freezeToggle: "Freeze the screen while selecting",
        freezeCaption: "The picture stops while you choose the area, so nothing moves away or changes during the selection.",
        folderLabel: "Save to",
        folderChoose: "Choose…",
        subfolderLabel: "Subfolder pattern",
        subfolderCaption: "Optional. Creates dated subfolders inside the folder above using %y, %year, %mo, %month, %d, %h, %mi and %s, for example %y-%mo for 24-03.",
        fileNamePatternLabel: "File name",
        fileNamePatternCaption: "Optional. Overrides the default name using the same %y, %year, %mo, %month, %d, %h, %mi and %s tokens, plus %# for an auto-incrementing number (%## pads to 2 digits, %### to 3, and so on).",
        fileNumberStartLabel: "Starts at",
        fileNumberResetButton: "Reset",
        fileNumberNextFormat: "Next: %d",
        delayLabel: "Delay",
        delayOff: "Off",
        delaySecondsFormat: "%d s",
        pointerToggle: "Include the pointer",
        downscaleToggle: "Save at 1x size",
        downscaleCaption: "Retina captures are saved at half their pixel size, which makes smaller files.",
        editorTitle: "Screenshot",
        toolShortcutsTitle: "Editor tools",
        toolShortcutsToggle: "Use number shortcuts",
        toolShortcutsCaption: "Use the arrows or choose a number. The first nine tools use 1 to 9. The others have no shortcut.",
        toolSelect: "Select",
        toolArrow: "Arrow",
        toolLine: "Line",
        toolRect: "Rectangle",
        toolEllipse: "Ellipse",
        toolFreehand: "Pen",
        toolHighlight: "Highlighter",
        toolText: "Text",
        toolSticker: "Sticker",
        toolCounter: "Number",
        toolPixelate: "Pixelate",
        toolRedact: "Solid block",
        toolCrop: "Crop",
        textPlaceholder: "Text",
        cropApply: "Crop",
        cancel: "Cancel",
        colorLabel: "Color",
        strokeLabel: "Thickness",
        shadowLabel: "Shadows",
        backdropLabel: "Background",
        backdropNone: "None",
        editButton: "Edit",
        copyButton: "Copy",
        saveButton: "Save",
        saveAsButton: "Save As…",
        pinButton: "Pin to screen",
        copyTextButton: "Copy text",
        discardTitle: "Discard this screenshot?",
        discardMessage: "It was not copied or saved yet.",
        discardConfirm: "Discard",
        copiedHUD: "Screenshot copied",
        savedHUDFormat: "Saved to %@",
        savedAndCopiedHUDFormat: "Saved to %@ and copied",
        defaultActionLabel: "Default action",
        defaultActionCaption: "Runs automatically right after capture. The confirmation still appears, so you can Edit or discard afterward.",
        defaultActionNone: "Ask each time",
        defaultActionSaveAndCopy: "Save & Copy",
        captureFailed: "The screen could not be captured",
        pinOpacity: "Opacity",
        pinClickThrough: "Ignore clicks",
        pinCloseAll: "Close all pins",
        backdropPaddingLabel: "Margin",
        backdropWallpaperLabel: "Wallpaper",
        backdropImageButton: "Image…",
        backdropSolidLabel: "Solid",
        backdropGradientLabel: "Gradient",
        backdropCornersLabel: "Corners",
        backdropSavePreset: "Save background",
        backdropDeletePreset: "Remove",
        backdropCustomLabel: "Custom",
        openEditorToggle: "Open the editor right after capturing",
        openEditorCaption: "The capture skips the floating preview and opens ready to annotate.",
        autoCopyToggle: "Copy to the clipboard automatically",
        autoCopyCaption: "Every capture goes to the clipboard as soon as it is taken, ready to paste. Saving a file stays a separate choice.",
        hintLoupe: "Z toggles the loupe",
        lastRegionToggle: "Show the last capture outline"
    )

    static let ptBR = ScreenshotFeatureStrings(
        pageTitle: "Captura de tela",
        hubDescription: "Captura uma área, janela ou tela e permite anotar",
        captureButton: "Capturar agora",
        panelCaption: "Capture uma área, uma janela ou a tela inteira",
        fileNamePrefix: "Captura de Tela",
        hintDrag: "Arraste para selecionar uma área",
        hintClick: "Clique numa janela para capturá-la",
        hintFullScreen: "Return captura a tela inteira",
        hintCancel: "Esc cancela",
        hintRepeat: "R repete a última área",
        freezeToggle: "Congelar a tela durante a seleção",
        freezeCaption: "A imagem para enquanto você escolhe a área, então nada se move nem muda durante a seleção.",
        folderLabel: "Salvar em",
        folderChoose: "Escolher…",
        subfolderLabel: "Padrão de subpasta",
        subfolderCaption: "Opcional. Cria subpastas com data dentro da pasta acima usando %y, %year, %mo, %month, %d, %h, %mi e %s, por exemplo %y-%mo para 24-03.",
        fileNamePatternLabel: "Nome do arquivo",
        fileNamePatternCaption: "Opcional. Substitui o nome padrão usando os mesmos tokens %y, %year, %mo, %month, %d, %h, %mi e %s, além de %# para um número que aumenta automaticamente (%## preenche com 2 dígitos, %### com 3, e assim por diante).",
        fileNumberStartLabel: "Começa em",
        fileNumberResetButton: "Redefinir",
        fileNumberNextFormat: "Próximo: %d",
        delayLabel: "Atraso",
        delayOff: "Desativado",
        delaySecondsFormat: "%d s",
        pointerToggle: "Incluir o ponteiro",
        downscaleToggle: "Salvar em tamanho 1x",
        downscaleCaption: "Capturas Retina são salvas com metade dos pixels, o que gera arquivos menores.",
        editorTitle: "Captura de tela",
        toolShortcutsTitle: "Ferramentas do editor",
        toolShortcutsToggle: "Usar atalhos numéricos",
        toolShortcutsCaption: "Use as setas ou escolha um número. As nove primeiras ferramentas usam 1 a 9. As demais ficam sem atalho.",
        toolSelect: "Selecionar",
        toolArrow: "Seta",
        toolLine: "Linha",
        toolRect: "Retângulo",
        toolEllipse: "Elipse",
        toolFreehand: "Caneta",
        toolHighlight: "Marca-texto",
        toolText: "Texto",
        toolSticker: "Adesivo",
        toolCounter: "Número",
        toolPixelate: "Pixelizar",
        toolRedact: "Bloco sólido",
        toolCrop: "Recortar",
        textPlaceholder: "Texto",
        cropApply: "Recortar",
        cancel: "Cancelar",
        colorLabel: "Cor",
        strokeLabel: "Espessura",
        shadowLabel: "Sombras",
        backdropLabel: "Fundo",
        backdropNone: "Nenhum",
        editButton: "Editar",
        copyButton: "Copiar",
        saveButton: "Salvar",
        saveAsButton: "Salvar Como…",
        pinButton: "Fixar na tela",
        copyTextButton: "Copiar texto",
        discardTitle: "Descartar esta captura?",
        discardMessage: "Ela ainda não foi copiada nem salva.",
        discardConfirm: "Descartar",
        copiedHUD: "Captura copiada",
        savedHUDFormat: "Salva em %@",
        savedAndCopiedHUDFormat: "Salva em %@ e copiada",
        defaultActionLabel: "Ação padrão",
        defaultActionCaption: "É executada automaticamente logo após a captura. A confirmação ainda aparece, então você pode Editar ou descartar depois.",
        defaultActionNone: "Perguntar sempre",
        defaultActionSaveAndCopy: "Salvar e Copiar",
        captureFailed: "Não foi possível capturar a tela",
        pinOpacity: "Opacidade",
        pinClickThrough: "Ignorar cliques",
        pinCloseAll: "Fechar todas as fixadas",
        backdropPaddingLabel: "Margem",
        backdropWallpaperLabel: "Papel de parede",
        backdropImageButton: "Imagem…",
        backdropSolidLabel: "Sólida",
        backdropGradientLabel: "Gradiente",
        backdropCornersLabel: "Cantos",
        backdropSavePreset: "Salvar fundo",
        backdropDeletePreset: "Remover",
        backdropCustomLabel: "Personalizado",
        openEditorToggle: "Abrir o editor logo após capturar",
        openEditorCaption: "A captura pula a pré-visualização flutuante e já abre pronta para anotar.",
        autoCopyToggle: "Copiar para a área de transferência automaticamente",
        autoCopyCaption: "Toda captura vai para a área de transferência assim que é feita, pronta para colar. Salvar um arquivo continua sendo uma escolha à parte.",
        hintLoupe: "Z alterna a lupa",
        lastRegionToggle: "Mostrar o contorno da última captura"
    )

    static let tr = ScreenshotFeatureStrings(
        pageTitle: "Ekran görüntüsü",
        hubDescription: "Bir alanı, pencereyi veya ekranı yakalar ve işaretlemenizi sağlar",
        captureButton: "Şimdi yakala",
        panelCaption: "Bir alanı, bir pencereyi veya tüm ekranı yakalayın",
        fileNamePrefix: "Ekran Görüntüsü",
        hintDrag: "Bir alan seçmek için sürükleyin",
        hintClick: "Yakalamak için bir pencereye tıklayın",
        hintFullScreen: "Return tüm ekranı yakalar",
        hintCancel: "Esc iptal eder",
        hintRepeat: "R son alanı yineler",
        freezeToggle: "Seçim sırasında ekranı dondur",
        freezeCaption: "Alanı seçerken görüntü durur, böylece seçim sırasında hiçbir şey hareket etmez veya değişmez.",
        folderLabel: "Kayıt yeri",
        folderChoose: "Seç…",
        subfolderLabel: "Alt klasör deseni",
        subfolderCaption: "İsteğe bağlı. Yukarıdaki klasörün içinde %y, %year, %mo, %month, %d, %h, %mi ve %s kullanarak tarihli alt klasörler oluşturur, örneğin %y-%mo için 24-03.",
        fileNamePatternLabel: "Dosya adı",
        fileNamePatternCaption: "İsteğe bağlı. Varsayılan adı %y, %year, %mo, %month, %d, %h, %mi ve %s ile aynı belirteçleri, ayrıca otomatik artan bir sayı için %# kullanarak geçersiz kılar (%## 2 basamağa, %### 3 basamağa tamamlar).",
        fileNumberStartLabel: "Başlangıç",
        fileNumberResetButton: "Sıfırla",
        fileNumberNextFormat: "Sıradaki: %d",
        delayLabel: "Gecikme",
        delayOff: "Kapalı",
        delaySecondsFormat: "%d sn",
        pointerToggle: "İmleci dahil et",
        downscaleToggle: "1x boyutunda kaydet",
        downscaleCaption: "Retina yakalamalar piksel boyutunun yarısıyla kaydedilir, bu da daha küçük dosyalar üretir.",
        editorTitle: "Ekran görüntüsü",
        toolShortcutsTitle: "Düzenleyici araçları",
        toolShortcutsToggle: "Sayı kısayollarını kullan",
        toolShortcutsCaption: "Okları kullanın veya bir sayı seçin. İlk dokuz araç 1 ile 9'u kullanır. Diğerlerinin kısayolu yoktur.",
        toolSelect: "Seç",
        toolArrow: "Ok",
        toolLine: "Çizgi",
        toolRect: "Dikdörtgen",
        toolEllipse: "Elips",
        toolFreehand: "Kalem",
        toolHighlight: "Fosforlu kalem",
        toolText: "Metin",
        toolSticker: "Çıkartma",
        toolCounter: "Numara",
        toolPixelate: "Pikselleştir",
        toolRedact: "Düz blok",
        toolCrop: "Kırp",
        textPlaceholder: "Metin",
        cropApply: "Kırp",
        cancel: "Vazgeç",
        colorLabel: "Renk",
        strokeLabel: "Kalınlık",
        shadowLabel: "Gölgeler",
        backdropLabel: "Arka plan",
        backdropNone: "Yok",
        editButton: "Düzenle",
        copyButton: "Kopyala",
        saveButton: "Kaydet",
        saveAsButton: "Farklı Kaydet…",
        pinButton: "Ekrana sabitle",
        copyTextButton: "Metni kopyala",
        discardTitle: "Bu ekran görüntüsü silinsin mi?",
        discardMessage: "Henüz kopyalanmadı veya kaydedilmedi.",
        discardConfirm: "Sil",
        copiedHUD: "Ekran görüntüsü kopyalandı",
        savedHUDFormat: "Şuraya kaydedildi: %@",
        savedAndCopiedHUDFormat: "Şuraya kaydedildi ve kopyalandı: %@",
        defaultActionLabel: "Varsayılan eylem",
        defaultActionCaption: "Yakalamadan hemen sonra otomatik olarak çalışır. Onay yine de görünür, böylece sonrasında Düzenle veya sil seçeneklerini kullanabilirsiniz.",
        defaultActionNone: "Her seferinde sor",
        defaultActionSaveAndCopy: "Kaydet ve Kopyala",
        captureFailed: "Ekran yakalanamadı",
        pinOpacity: "Opaklık",
        pinClickThrough: "Tıklamaları yoksay",
        pinCloseAll: "Tüm sabitlenenleri kapat",
        backdropPaddingLabel: "Kenar payı",
        backdropWallpaperLabel: "Duvar kağıdı",
        backdropImageButton: "Görsel…",
        backdropSolidLabel: "Düz",
        backdropGradientLabel: "Degrade",
        backdropCornersLabel: "Köşeler",
        backdropSavePreset: "Arka planı kaydet",
        backdropDeletePreset: "Kaldır",
        backdropCustomLabel: "Özel",
        openEditorToggle: "Yakaladıktan hemen sonra düzenleyiciyi aç",
        openEditorCaption: "Yakalama, yüzen önizlemeyi atlar ve işaretlemeye hazır şekilde açılır.",
        autoCopyToggle: "Otomatik olarak panoya kopyala",
        autoCopyCaption: "Her yakalama alınır alınmaz panoya gider ve yapıştırmaya hazır olur. Dosya olarak kaydetmek ayrı bir seçim olarak kalır.",
        hintLoupe: "Z büyüteci açar/kapatır",
        lastRegionToggle: "Son yakalamanın çerçevesini göster"
    )

    static let ru = ScreenshotFeatureStrings(
        pageTitle: "Снимок экрана",
        hubDescription: "Снимает область, окно или экран и позволяет делать пометки",
        captureButton: "Снять сейчас",
        panelCaption: "Снимите область, окно или весь экран",
        fileNamePrefix: "Снимок экрана",
        hintDrag: "Потяните, чтобы выделить область",
        hintClick: "Нажмите на окно, чтобы снять его",
        hintFullScreen: "Return снимает весь экран",
        hintCancel: "Esc отменяет",
        hintRepeat: "R повторяет последнюю область",
        freezeToggle: "Замораживать экран при выделении",
        freezeCaption: "Изображение останавливается, пока вы выбираете область, поэтому во время выделения ничего не двигается и не меняется.",
        folderLabel: "Сохранять в",
        folderChoose: "Выбрать…",
        subfolderLabel: "Шаблон подпапки",
        subfolderCaption: "Необязательно. Создаёт подпапки с датой внутри указанной папки, используя %y, %year, %mo, %month, %d, %h, %mi и %s, например %y-%mo даёт 24-03.",
        fileNamePatternLabel: "Имя файла",
        fileNamePatternCaption: "Необязательно. Переопределяет имя по умолчанию с помощью тех же токенов %y, %year, %mo, %month, %d, %h, %mi и %s, а также %# для автоматически увеличивающегося номера (%## дополняет до 2 цифр, %### до 3 и так далее).",
        fileNumberStartLabel: "Начинается с",
        fileNumberResetButton: "Сбросить",
        fileNumberNextFormat: "Следующий: %d",
        delayLabel: "Задержка",
        delayOff: "Выкл.",
        delaySecondsFormat: "%d с",
        pointerToggle: "Включать указатель",
        downscaleToggle: "Сохранять в размере 1x",
        downscaleCaption: "Снимки Retina сохраняются с половиной пикселей, что даёт файлы меньшего размера.",
        editorTitle: "Снимок экрана",
        toolShortcutsTitle: "Инструменты редактора",
        toolShortcutsToggle: "Использовать цифровые сочетания",
        toolShortcutsCaption: "Используйте стрелки или выберите цифру. Первые девять инструментов используют цифры от 1 до 9. У остальных нет сочетания.",
        toolSelect: "Выбор",
        toolArrow: "Стрелка",
        toolLine: "Линия",
        toolRect: "Прямоугольник",
        toolEllipse: "Эллипс",
        toolFreehand: "Перо",
        toolHighlight: "Маркер",
        toolText: "Текст",
        toolSticker: "Стикер",
        toolCounter: "Номер",
        toolPixelate: "Пикселизация",
        toolRedact: "Плашка",
        toolCrop: "Обрезать",
        textPlaceholder: "Текст",
        cropApply: "Обрезать",
        cancel: "Отменить",
        colorLabel: "Цвет",
        strokeLabel: "Толщина",
        shadowLabel: "Тени",
        backdropLabel: "Фон",
        backdropNone: "Нет",
        editButton: "Изменить",
        copyButton: "Скопировать",
        saveButton: "Сохранить",
        saveAsButton: "Сохранить как…",
        pinButton: "Закрепить на экране",
        copyTextButton: "Скопировать текст",
        discardTitle: "Удалить этот снимок?",
        discardMessage: "Он ещё не скопирован и не сохранён.",
        discardConfirm: "Удалить",
        copiedHUD: "Снимок скопирован",
        savedHUDFormat: "Сохранено в %@",
        savedAndCopiedHUDFormat: "Сохранено в %@ и скопировано",
        defaultActionLabel: "Действие по умолчанию",
        defaultActionCaption: "Выполняется автоматически сразу после захвата. Подтверждение всё равно появляется, так что потом можно изменить или удалить снимок.",
        defaultActionNone: "Спрашивать каждый раз",
        defaultActionSaveAndCopy: "Сохранить и скопировать",
        captureFailed: "Не удалось снять экран",
        pinOpacity: "Непрозрачность",
        pinClickThrough: "Игнорировать нажатия",
        pinCloseAll: "Закрыть все закреплённые",
        backdropPaddingLabel: "Поля",
        backdropWallpaperLabel: "Обои",
        backdropImageButton: "Изображение…",
        backdropSolidLabel: "Сплошной",
        backdropGradientLabel: "Градиент",
        backdropCornersLabel: "Углы",
        backdropSavePreset: "Сохранить фон",
        backdropDeletePreset: "Удалить",
        backdropCustomLabel: "Свой",
        openEditorToggle: "Открывать редактор сразу после снимка",
        openEditorCaption: "Снимок пропускает плавающее окно предпросмотра и сразу открывается готовым к пометкам.",
        autoCopyToggle: "Автоматически копировать в буфер обмена",
        autoCopyCaption: "Каждый снимок попадает в буфер обмена сразу после съёмки и готов к вставке. Сохранение файла остаётся отдельным выбором.",
        hintLoupe: "Z включает лупу",
        lastRegionToggle: "Показывать контур последней области"
    )

    static let es = ScreenshotFeatureStrings(
        pageTitle: "Captura de pantalla",
        hubDescription: "Captura un área, ventana o pantalla y permite anotarla",
        captureButton: "Capturar ahora",
        panelCaption: "Captura un área, una ventana o toda la pantalla",
        fileNamePrefix: "Captura de pantalla",
        hintDrag: "Arrastra para seleccionar un área",
        hintClick: "Haz clic en una ventana para capturarla",
        hintFullScreen: "Return captura toda la pantalla",
        hintCancel: "Esc cancela",
        hintRepeat: "R repite la última área",
        freezeToggle: "Congelar la pantalla durante la selección",
        freezeCaption: "La imagen se detiene mientras eliges el área, así nada se mueve ni cambia durante la selección.",
        folderLabel: "Guardar en",
        folderChoose: "Elegir…",
        subfolderLabel: "Patrón de subcarpeta",
        subfolderCaption: "Opcional. Crea subcarpetas con fecha dentro de la carpeta anterior usando %y, %year, %mo, %month, %d, %h, %mi y %s, por ejemplo %y-%mo para 24-03.",
        fileNamePatternLabel: "Nombre de archivo",
        fileNamePatternCaption: "Opcional. Reemplaza el nombre predeterminado usando los mismos tokens %y, %year, %mo, %month, %d, %h, %mi y %s, además de %# para un número que se incrementa automáticamente (%## lo rellena a 2 dígitos, %### a 3, y así sucesivamente).",
        fileNumberStartLabel: "Empieza en",
        fileNumberResetButton: "Restablecer",
        fileNumberNextFormat: "Siguiente: %d",
        delayLabel: "Retraso",
        delayOff: "Desactivado",
        delaySecondsFormat: "%d s",
        pointerToggle: "Incluir el puntero",
        downscaleToggle: "Guardar en tamaño 1x",
        downscaleCaption: "Las capturas Retina se guardan con la mitad de píxeles, lo que genera archivos más pequeños.",
        editorTitle: "Captura de pantalla",
        toolShortcutsTitle: "Herramientas del editor",
        toolShortcutsToggle: "Usar atajos numéricos",
        toolShortcutsCaption: "Usa las flechas o elige un número. Las primeras nueve herramientas usan del 1 al 9. Las demás no tienen atajo.",
        toolSelect: "Seleccionar",
        toolArrow: "Flecha",
        toolLine: "Línea",
        toolRect: "Rectángulo",
        toolEllipse: "Elipse",
        toolFreehand: "Lápiz",
        toolHighlight: "Marcador",
        toolText: "Texto",
        toolSticker: "Adhesivo",
        toolCounter: "Número",
        toolPixelate: "Pixelar",
        toolRedact: "Bloque sólido",
        toolCrop: "Recortar",
        textPlaceholder: "Texto",
        cropApply: "Recortar",
        cancel: "Cancelar",
        colorLabel: "Color",
        strokeLabel: "Grosor",
        shadowLabel: "Sombras",
        backdropLabel: "Fondo",
        backdropNone: "Ninguno",
        editButton: "Editar",
        copyButton: "Copiar",
        saveButton: "Guardar",
        saveAsButton: "Guardar como…",
        pinButton: "Fijar en pantalla",
        copyTextButton: "Copiar texto",
        discardTitle: "¿Descartar esta captura?",
        discardMessage: "Todavía no se copió ni se guardó.",
        discardConfirm: "Descartar",
        copiedHUD: "Captura copiada",
        savedHUDFormat: "Guardada en %@",
        savedAndCopiedHUDFormat: "Guardada en %@ y copiada",
        defaultActionLabel: "Acción predeterminada",
        defaultActionCaption: "Se ejecuta automáticamente justo después de la captura. La confirmación sigue apareciendo, así que puedes Editar o descartar después.",
        defaultActionNone: "Preguntar cada vez",
        defaultActionSaveAndCopy: "Guardar y copiar",
        captureFailed: "No se pudo capturar la pantalla",
        pinOpacity: "Opacidad",
        pinClickThrough: "Ignorar clics",
        pinCloseAll: "Cerrar todas las fijadas",
        backdropPaddingLabel: "Margen",
        backdropWallpaperLabel: "Fondo de pantalla",
        backdropImageButton: "Imagen…",
        backdropSolidLabel: "Sólido",
        backdropGradientLabel: "Degradado",
        backdropCornersLabel: "Esquinas",
        backdropSavePreset: "Guardar fondo",
        backdropDeletePreset: "Eliminar",
        backdropCustomLabel: "Personalizado",
        openEditorToggle: "Abrir el editor justo después de capturar",
        openEditorCaption: "La captura omite la previsualización flotante y se abre lista para anotar.",
        autoCopyToggle: "Copiar al portapapeles automáticamente",
        autoCopyCaption: "Cada captura va al portapapeles en cuanto se toma, lista para pegar. Guardar un archivo sigue siendo una elección aparte.",
        hintLoupe: "Z activa la lupa",
        lastRegionToggle: "Mostrar sombra de la última captura"
    )

    static let de = ScreenshotFeatureStrings(
        pageTitle: "Bildschirmfoto",
        hubDescription: "Nimmt einen Bereich, ein Fenster oder den Bildschirm auf und erlaubt Anmerkungen",
        captureButton: "Jetzt aufnehmen",
        panelCaption: "Einen Bereich, ein Fenster oder den ganzen Bildschirm aufnehmen",
        fileNamePrefix: "Bildschirmfoto",
        hintDrag: "Ziehen, um einen Bereich auszuwählen",
        hintClick: "Auf ein Fenster klicken, um es aufzunehmen",
        hintFullScreen: "Return nimmt den ganzen Bildschirm auf",
        hintCancel: "Esc bricht ab",
        hintRepeat: "R wiederholt den letzten Bereich",
        freezeToggle: "Bildschirm während der Auswahl einfrieren",
        freezeCaption: "Das Bild bleibt stehen, während du den Bereich wählst. So bewegt oder ändert sich nichts während der Auswahl.",
        folderLabel: "Sichern unter",
        folderChoose: "Auswählen…",
        subfolderLabel: "Unterordnermuster",
        subfolderCaption: "Optional. Erstellt datierte Unterordner im obigen Ordner mit %y, %year, %mo, %month, %d, %h, %mi und %s, zum Beispiel %y-%mo für 24-03.",
        fileNamePatternLabel: "Dateiname",
        fileNamePatternCaption: "Optional. Überschreibt den Standardnamen mit denselben Tokens %y, %year, %mo, %month, %d, %h, %mi und %s sowie %# für eine automatisch fortlaufende Nummer (%## füllt auf 2 Stellen auf, %### auf 3 usw.).",
        fileNumberStartLabel: "Beginnt bei",
        fileNumberResetButton: "Zurücksetzen",
        fileNumberNextFormat: "Nächste: %d",
        delayLabel: "Verzögerung",
        delayOff: "Aus",
        delaySecondsFormat: "%d s",
        pointerToggle: "Zeiger einbeziehen",
        downscaleToggle: "In 1x-Größe sichern",
        downscaleCaption: "Retina-Aufnahmen werden mit halber Pixelgröße gesichert, was kleinere Dateien ergibt.",
        editorTitle: "Bildschirmfoto",
        toolShortcutsTitle: "Editorwerkzeuge",
        toolShortcutsToggle: "Zifferntasten verwenden",
        toolShortcutsCaption: "Mit den Pfeilen verschieben oder eine Ziffer wählen. Die ersten neun Werkzeuge verwenden 1 bis 9. Die übrigen haben keinen Kurzbefehl.",
        toolSelect: "Auswählen",
        toolArrow: "Pfeil",
        toolLine: "Linie",
        toolRect: "Rechteck",
        toolEllipse: "Ellipse",
        toolFreehand: "Stift",
        toolHighlight: "Marker",
        toolText: "Text",
        toolSticker: "Sticker",
        toolCounter: "Nummer",
        toolPixelate: "Verpixeln",
        toolRedact: "Farbblock",
        toolCrop: "Zuschneiden",
        textPlaceholder: "Text",
        cropApply: "Zuschneiden",
        cancel: "Abbrechen",
        colorLabel: "Farbe",
        strokeLabel: "Stärke",
        shadowLabel: "Schatten",
        backdropLabel: "Hintergrund",
        backdropNone: "Ohne",
        editButton: "Bearbeiten",
        copyButton: "Kopieren",
        saveButton: "Sichern",
        saveAsButton: "Sichern unter…",
        pinButton: "Am Bildschirm anheften",
        copyTextButton: "Text kopieren",
        discardTitle: "Dieses Bildschirmfoto verwerfen?",
        discardMessage: "Es wurde noch nicht kopiert oder gesichert.",
        discardConfirm: "Verwerfen",
        copiedHUD: "Bildschirmfoto kopiert",
        savedHUDFormat: "Gesichert unter %@",
        savedAndCopiedHUDFormat: "Gesichert unter %@ und kopiert",
        defaultActionLabel: "Standardaktion",
        defaultActionCaption: "Wird direkt nach der Aufnahme automatisch ausgeführt. Die Bestätigung erscheint trotzdem, sodass du danach noch bearbeiten oder verwerfen kannst.",
        defaultActionNone: "Jedes Mal fragen",
        defaultActionSaveAndCopy: "Sichern & Kopieren",
        captureFailed: "Der Bildschirm konnte nicht aufgenommen werden",
        pinOpacity: "Deckkraft",
        pinClickThrough: "Klicks ignorieren",
        pinCloseAll: "Alle angehefteten schließen",
        backdropPaddingLabel: "Rand",
        backdropWallpaperLabel: "Hintergrundbild",
        backdropImageButton: "Bild…",
        backdropSolidLabel: "Einfarbig",
        backdropGradientLabel: "Verlauf",
        backdropCornersLabel: "Ecken",
        backdropSavePreset: "Hintergrund sichern",
        backdropDeletePreset: "Entfernen",
        backdropCustomLabel: "Eigene",
        openEditorToggle: "Editor direkt nach der Aufnahme öffnen",
        openEditorCaption: "Die Aufnahme überspringt die schwebende Vorschau und öffnet sich bereit für Anmerkungen.",
        autoCopyToggle: "Automatisch in die Zwischenablage kopieren",
        autoCopyCaption: "Jede Aufnahme landet sofort in der Zwischenablage, bereit zum Einfügen. Das Speichern als Datei bleibt eine eigene Entscheidung.",
        hintLoupe: "Z schaltet die Lupe um",
        lastRegionToggle: "Umriss der letzten Aufnahme anzeigen"
    )

    static let fr = ScreenshotFeatureStrings(
        pageTitle: "Capture d'écran",
        hubDescription: "Capture une zone, une fenêtre ou l'écran et permet de l'annoter",
        captureButton: "Capturer maintenant",
        panelCaption: "Capturez une zone, une fenêtre ou tout l'écran",
        fileNamePrefix: "Capture d'écran",
        hintDrag: "Faites glisser pour sélectionner une zone",
        hintClick: "Cliquez sur une fenêtre pour la capturer",
        hintFullScreen: "Return capture tout l'écran",
        hintCancel: "Esc annule",
        hintRepeat: "R répète la dernière zone",
        freezeToggle: "Figer l'écran pendant la sélection",
        freezeCaption: "L'image s'arrête pendant que vous choisissez la zone, donc rien ne bouge ni ne change pendant la sélection.",
        folderLabel: "Enregistrer dans",
        folderChoose: "Choisir…",
        subfolderLabel: "Motif de sous-dossier",
        subfolderCaption: "Facultatif. Crée des sous-dossiers datés dans le dossier ci-dessus avec %y, %year, %mo, %month, %d, %h, %mi et %s, par exemple %y-%mo pour 24-03.",
        fileNamePatternLabel: "Nom du fichier",
        fileNamePatternCaption: "Facultatif. Remplace le nom par défaut avec les mêmes jetons %y, %year, %mo, %month, %d, %h, %mi et %s, plus %# pour un numéro qui s'incrémente automatiquement (%## le remplit sur 2 chiffres, %### sur 3, etc.).",
        fileNumberStartLabel: "Commence à",
        fileNumberResetButton: "Réinitialiser",
        fileNumberNextFormat: "Suivant : %d",
        delayLabel: "Délai",
        delayOff: "Désactivé",
        delaySecondsFormat: "%d s",
        pointerToggle: "Inclure le pointeur",
        downscaleToggle: "Enregistrer en taille 1x",
        downscaleCaption: "Les captures Retina sont enregistrées avec moitié moins de pixels, ce qui donne des fichiers plus petits.",
        editorTitle: "Capture d'écran",
        toolShortcutsTitle: "Outils de l’éditeur",
        toolShortcutsToggle: "Utiliser les raccourcis numériques",
        toolShortcutsCaption: "Utilisez les flèches ou choisissez un numéro. Les neuf premiers outils utilisent 1 à 9. Les autres n’ont pas de raccourci.",
        toolSelect: "Sélectionner",
        toolArrow: "Flèche",
        toolLine: "Ligne",
        toolRect: "Rectangle",
        toolEllipse: "Ellipse",
        toolFreehand: "Crayon",
        toolHighlight: "Surligneur",
        toolText: "Texte",
        toolSticker: "Autocollant",
        toolCounter: "Numéro",
        toolPixelate: "Pixelliser",
        toolRedact: "Bloc plein",
        toolCrop: "Rogner",
        textPlaceholder: "Texte",
        cropApply: "Rogner",
        cancel: "Annuler",
        colorLabel: "Couleur",
        strokeLabel: "Épaisseur",
        shadowLabel: "Ombres",
        backdropLabel: "Arrière-plan",
        backdropNone: "Aucun",
        editButton: "Modifier",
        copyButton: "Copier",
        saveButton: "Enregistrer",
        saveAsButton: "Enregistrer sous…",
        pinButton: "Épingler à l'écran",
        copyTextButton: "Copier le texte",
        discardTitle: "Abandonner cette capture ?",
        discardMessage: "Elle n'a pas encore été copiée ni enregistrée.",
        discardConfirm: "Abandonner",
        copiedHUD: "Capture copiée",
        savedHUDFormat: "Enregistrée dans %@",
        savedAndCopiedHUDFormat: "Enregistrée dans %@ et copiée",
        defaultActionLabel: "Action par défaut",
        defaultActionCaption: "S'exécute automatiquement juste après la capture. La confirmation s'affiche quand même, ce qui permet ensuite de modifier ou de supprimer.",
        defaultActionNone: "Demander à chaque fois",
        defaultActionSaveAndCopy: "Enregistrer et copier",
        captureFailed: "Impossible de capturer l'écran",
        pinOpacity: "Opacité",
        pinClickThrough: "Ignorer les clics",
        pinCloseAll: "Fermer toutes les épingles",
        backdropPaddingLabel: "Marge",
        backdropWallpaperLabel: "Fond d'écran",
        backdropImageButton: "Image…",
        backdropSolidLabel: "Unie",
        backdropGradientLabel: "Dégradé",
        backdropCornersLabel: "Coins",
        backdropSavePreset: "Enregistrer le fond",
        backdropDeletePreset: "Supprimer",
        backdropCustomLabel: "Personnalisé",
        openEditorToggle: "Ouvrir l'éditeur juste après la capture",
        openEditorCaption: "La capture ignore l'aperçu flottant et s'ouvre prête à être annotée.",
        autoCopyToggle: "Copier automatiquement dans le presse-papiers",
        autoCopyCaption: "Chaque capture va dans le presse-papiers dès qu'elle est prise, prête à être collée. Enregistrer un fichier reste un choix distinct.",
        hintLoupe: "Z active la loupe",
        lastRegionToggle: "Afficher le contour de la dernière capture"
    )

    static let it = ScreenshotFeatureStrings(
        pageTitle: "Istantanea schermo",
        hubDescription: "Cattura un'area, una finestra o lo schermo e permette di annotarla",
        captureButton: "Cattura ora",
        panelCaption: "Cattura un'area, una finestra o l'intero schermo",
        fileNamePrefix: "Istantanea",
        hintDrag: "Trascina per selezionare un'area",
        hintClick: "Fai clic su una finestra per catturarla",
        hintFullScreen: "Return cattura l'intero schermo",
        hintCancel: "Esc annulla",
        hintRepeat: "R ripete l'ultima area",
        freezeToggle: "Congela lo schermo durante la selezione",
        freezeCaption: "L'immagine si ferma mentre scegli l'area, quindi niente si muove o cambia durante la selezione.",
        folderLabel: "Salva in",
        folderChoose: "Scegli…",
        subfolderLabel: "Modello sottocartella",
        subfolderCaption: "Facoltativo. Crea sottocartelle datate nella cartella sopra usando %y, %year, %mo, %month, %d, %h, %mi e %s, ad esempio %y-%mo per 24-03.",
        fileNamePatternLabel: "Nome file",
        fileNamePatternCaption: "Facoltativo. Sostituisce il nome predefinito usando gli stessi token %y, %year, %mo, %month, %d, %h, %mi e %s, più %# per un numero che si incrementa automaticamente (%## lo riempie a 2 cifre, %### a 3, e così via).",
        fileNumberStartLabel: "Inizia da",
        fileNumberResetButton: "Reimposta",
        fileNumberNextFormat: "Prossimo: %d",
        delayLabel: "Ritardo",
        delayOff: "Disattivato",
        delaySecondsFormat: "%d s",
        pointerToggle: "Includi il puntatore",
        downscaleToggle: "Salva in dimensione 1x",
        downscaleCaption: "Le catture Retina vengono salvate con metà dei pixel, producendo file più piccoli.",
        editorTitle: "Istantanea schermo",
        toolShortcutsTitle: "Strumenti dell’editor",
        toolShortcutsToggle: "Usa le scorciatoie numeriche",
        toolShortcutsCaption: "Usa le frecce o scegli un numero. I primi nove strumenti usano i tasti da 1 a 9. Gli altri non hanno una scorciatoia.",
        toolSelect: "Seleziona",
        toolArrow: "Freccia",
        toolLine: "Linea",
        toolRect: "Rettangolo",
        toolEllipse: "Ellisse",
        toolFreehand: "Penna",
        toolHighlight: "Evidenziatore",
        toolText: "Testo",
        toolSticker: "Adesivo",
        toolCounter: "Numero",
        toolPixelate: "Pixella",
        toolRedact: "Blocco pieno",
        toolCrop: "Ritaglia",
        textPlaceholder: "Testo",
        cropApply: "Ritaglia",
        cancel: "Annulla",
        colorLabel: "Colore",
        strokeLabel: "Spessore",
        shadowLabel: "Ombre",
        backdropLabel: "Sfondo",
        backdropNone: "Nessuno",
        editButton: "Modifica",
        copyButton: "Copia",
        saveButton: "Salva",
        saveAsButton: "Salva come…",
        pinButton: "Fissa sullo schermo",
        copyTextButton: "Copia testo",
        discardTitle: "Eliminare questa istantanea?",
        discardMessage: "Non è stata ancora copiata né salvata.",
        discardConfirm: "Elimina",
        copiedHUD: "Istantanea copiata",
        savedHUDFormat: "Salvata in %@",
        savedAndCopiedHUDFormat: "Salvata in %@ e copiata",
        defaultActionLabel: "Azione predefinita",
        defaultActionCaption: "Viene eseguita automaticamente subito dopo la cattura. La conferma appare comunque, così puoi Modificare o eliminare in seguito.",
        defaultActionNone: "Chiedi ogni volta",
        defaultActionSaveAndCopy: "Salva e copia",
        captureFailed: "Impossibile catturare lo schermo",
        pinOpacity: "Opacità",
        pinClickThrough: "Ignora i clic",
        pinCloseAll: "Chiudi tutte le fissate",
        backdropPaddingLabel: "Margine",
        backdropWallpaperLabel: "Sfondo scrivania",
        backdropImageButton: "Immagine…",
        backdropSolidLabel: "Tinta unita",
        backdropGradientLabel: "Gradiente",
        backdropCornersLabel: "Angoli",
        backdropSavePreset: "Salva sfondo",
        backdropDeletePreset: "Rimuovi",
        backdropCustomLabel: "Personalizzato",
        openEditorToggle: "Apri l'editor subito dopo la cattura",
        openEditorCaption: "La cattura salta l'anteprima flottante e si apre pronta per le annotazioni.",
        autoCopyToggle: "Copia automaticamente negli appunti",
        autoCopyCaption: "Ogni cattura va negli appunti appena viene fatta, pronta da incollare. Salvare un file resta una scelta a parte.",
        hintLoupe: "Z attiva la lente",
        lastRegionToggle: "Mostra il contorno dell'ultima cattura"
    )

    static let ja = ScreenshotFeatureStrings(
        pageTitle: "スクリーンショット",
        hubDescription: "範囲やウインドウ、画面全体を撮影して注釈を付けられます",
        captureButton: "今すぐ撮影",
        panelCaption: "範囲、ウインドウ、画面全体を撮影します",
        fileNamePrefix: "スクリーンショット",
        hintDrag: "ドラッグで範囲を選択",
        hintClick: "ウインドウをクリックで撮影",
        hintFullScreen: "Returnで画面全体を撮影",
        hintCancel: "Escでキャンセル",
        hintRepeat: "Rで前回の範囲を再撮影",
        freezeToggle: "選択中は画面を静止させる",
        freezeCaption: "範囲を選んでいる間は画像が止まるため、選択中に何も動いたり変わったりしません。",
        folderLabel: "保存先",
        folderChoose: "選択…",
        subfolderLabel: "サブフォルダのパターン",
        subfolderCaption: "省略可。上のフォルダ内に %y、%year、%mo、%month、%d、%h、%mi、%s を使って日付付きのサブフォルダを作成します。例: %y-%mo で 24-03。",
        fileNamePatternLabel: "ファイル名",
        fileNamePatternCaption: "省略可。%y、%year、%mo、%month、%d、%h、%mi、%s と同じトークンに加え、自動的に増える番号として %# を使ってデフォルトの名前を上書きします（%## は2桁、%### は3桁に揃えます）。",
        fileNumberStartLabel: "開始番号",
        fileNumberResetButton: "リセット",
        fileNumberNextFormat: "次の番号: %d",
        delayLabel: "タイマー",
        delayOff: "オフ",
        delaySecondsFormat: "%d 秒",
        pointerToggle: "ポインタを含める",
        downscaleToggle: "1xサイズで保存",
        downscaleCaption: "Retinaの撮影はピクセル数を半分にして保存され、ファイルが小さくなります。",
        editorTitle: "スクリーンショット",
        toolShortcutsTitle: "エディタのツール",
        toolShortcutsToggle: "数字キーのショートカットを使う",
        toolShortcutsCaption: "矢印を使うか数字を選びます。最初の9個は1から9を使い、それ以降にはショートカットがありません。",
        toolSelect: "選択",
        toolArrow: "矢印",
        toolLine: "直線",
        toolRect: "長方形",
        toolEllipse: "楕円",
        toolFreehand: "ペン",
        toolHighlight: "ハイライト",
        toolText: "テキスト",
        toolSticker: "ステッカー",
        toolCounter: "番号",
        toolPixelate: "モザイク",
        toolRedact: "塗りつぶし",
        toolCrop: "トリミング",
        textPlaceholder: "テキスト",
        cropApply: "トリミング",
        cancel: "キャンセル",
        colorLabel: "カラー",
        strokeLabel: "太さ",
        shadowLabel: "影",
        backdropLabel: "背景",
        backdropNone: "なし",
        editButton: "編集",
        copyButton: "コピー",
        saveButton: "保存",
        saveAsButton: "別名で保存…",
        pinButton: "画面にピン留め",
        copyTextButton: "テキストをコピー",
        discardTitle: "このスクリーンショットを破棄しますか?",
        discardMessage: "まだコピーも保存もされていません。",
        discardConfirm: "破棄",
        copiedHUD: "スクリーンショットをコピーしました",
        savedHUDFormat: "%@ に保存しました",
        savedAndCopiedHUDFormat: "%@ に保存してコピーしました",
        defaultActionLabel: "既定のアクション",
        defaultActionCaption: "キャプチャ直後に自動的に実行されます。確認表示はそのまま出るので、後から編集または破棄できます。",
        defaultActionNone: "毎回確認する",
        defaultActionSaveAndCopy: "保存してコピー",
        captureFailed: "画面を撮影できませんでした",
        pinOpacity: "不透明度",
        pinClickThrough: "クリックを無視",
        pinCloseAll: "すべてのピンを閉じる",
        backdropPaddingLabel: "余白",
        backdropWallpaperLabel: "壁紙",
        backdropImageButton: "画像…",
        backdropSolidLabel: "単色",
        backdropGradientLabel: "グラデーション",
        backdropCornersLabel: "角丸",
        backdropSavePreset: "背景を保存",
        backdropDeletePreset: "削除",
        backdropCustomLabel: "カスタム",
        openEditorToggle: "撮影後すぐにエディタを開く",
        openEditorCaption: "撮影はフローティングプレビューを飛ばして、すぐに注釈を付けられる状態で開きます。",
        autoCopyToggle: "自動的にクリップボードへコピー",
        autoCopyCaption: "撮影した瞬間にクリップボードへ入り、すぐに貼り付けられます。ファイルとして保存するかどうかは別の選択のままです。",
        hintLoupe: "Zでルーペを切り替え",
        lastRegionToggle: "最後のキャプチャ範囲を表示"
    )

    static let ko = ScreenshotFeatureStrings(
        pageTitle: "스크린샷",
        hubDescription: "영역, 윈도우 또는 화면을 캡처하고 주석을 남길 수 있습니다",
        captureButton: "지금 캡처",
        panelCaption: "영역, 윈도우 또는 전체 화면을 캡처합니다",
        fileNamePrefix: "스크린샷",
        hintDrag: "드래그하여 영역 선택",
        hintClick: "윈도우를 클릭하면 캡처됩니다",
        hintFullScreen: "Return 키로 전체 화면 캡처",
        hintCancel: "Esc 키로 취소",
        hintRepeat: "R 키로 마지막 영역 반복",
        freezeToggle: "선택하는 동안 화면 정지",
        freezeCaption: "영역을 고르는 동안 화면이 멈추므로 선택 중에 아무것도 움직이거나 바뀌지 않습니다.",
        folderLabel: "저장 위치",
        folderChoose: "선택…",
        subfolderLabel: "하위 폴더 패턴",
        subfolderCaption: "선택 사항입니다. 위 폴더 안에 %y, %year, %mo, %month, %d, %h, %mi, %s를 사용해 날짜별 하위 폴더를 만듭니다. 예: %y-%mo는 24-03이 됩니다.",
        fileNamePatternLabel: "파일 이름",
        fileNamePatternCaption: "선택 사항입니다. %y, %year, %mo, %month, %d, %h, %mi, %s와 같은 토큰과, 자동으로 증가하는 번호를 위한 %#를 사용해 기본 이름을 대체합니다 (%##는 2자리, %###는 3자리로 채웁니다).",
        fileNumberStartLabel: "시작 번호",
        fileNumberResetButton: "재설정",
        fileNumberNextFormat: "다음 번호: %d",
        delayLabel: "타이머",
        delayOff: "끔",
        delaySecondsFormat: "%d초",
        pointerToggle: "포인터 포함",
        downscaleToggle: "1x 크기로 저장",
        downscaleCaption: "Retina 캡처는 픽셀 수를 절반으로 줄여 저장되어 파일이 작아집니다.",
        editorTitle: "스크린샷",
        toolShortcutsTitle: "편집 도구",
        toolShortcutsToggle: "숫자 단축키 사용",
        toolShortcutsCaption: "화살표를 사용하거나 숫자를 선택합니다. 처음 9개 도구는 1부터 9를 사용하고 나머지는 단축키가 없습니다.",
        toolSelect: "선택",
        toolArrow: "화살표",
        toolLine: "직선",
        toolRect: "사각형",
        toolEllipse: "타원",
        toolFreehand: "펜",
        toolHighlight: "형광펜",
        toolText: "텍스트",
        toolSticker: "스티커",
        toolCounter: "번호",
        toolPixelate: "픽셀화",
        toolRedact: "단색 블록",
        toolCrop: "자르기",
        textPlaceholder: "텍스트",
        cropApply: "자르기",
        cancel: "취소",
        colorLabel: "색상",
        strokeLabel: "두께",
        shadowLabel: "그림자",
        backdropLabel: "배경",
        backdropNone: "없음",
        editButton: "편집",
        copyButton: "복사",
        saveButton: "저장",
        saveAsButton: "다른 이름으로 저장…",
        pinButton: "화면에 고정",
        copyTextButton: "텍스트 복사",
        discardTitle: "이 스크린샷을 버리시겠습니까?",
        discardMessage: "아직 복사되거나 저장되지 않았습니다.",
        discardConfirm: "버리기",
        copiedHUD: "스크린샷이 복사되었습니다",
        savedHUDFormat: "%@에 저장되었습니다",
        savedAndCopiedHUDFormat: "%@에 저장하고 복사했습니다",
        defaultActionLabel: "기본 동작",
        defaultActionCaption: "캡처 직후 자동으로 실행됩니다. 확인 화면은 그대로 표시되므로 이후에 편집하거나 삭제할 수 있습니다.",
        defaultActionNone: "매번 물어보기",
        defaultActionSaveAndCopy: "저장 후 복사",
        captureFailed: "화면을 캡처할 수 없습니다",
        pinOpacity: "불투명도",
        pinClickThrough: "클릭 무시",
        pinCloseAll: "고정된 항목 모두 닫기",
        backdropPaddingLabel: "여백",
        backdropWallpaperLabel: "배경 화면",
        backdropImageButton: "이미지…",
        backdropSolidLabel: "단색",
        backdropGradientLabel: "그라데이션",
        backdropCornersLabel: "모서리",
        backdropSavePreset: "배경 저장",
        backdropDeletePreset: "제거",
        backdropCustomLabel: "사용자화",
        openEditorToggle: "캡처 후 바로 편집기 열기",
        openEditorCaption: "캡처가 떠 있는 미리보기를 건너뛰고 바로 주석을 남길 수 있는 상태로 열립니다.",
        autoCopyToggle: "자동으로 클립보드에 복사",
        autoCopyCaption: "캡처하는 즉시 클립보드에 담겨 바로 붙여넣을 수 있습니다. 파일로 저장하는 것은 여전히 별도의 선택입니다.",
        hintLoupe: "Z 키로 확대경 전환",
        lastRegionToggle: "마지막 캡처 영역 표시"
    )

    static let zhHans = ScreenshotFeatureStrings(
        pageTitle: "截屏",
        hubDescription: "截取区域、窗口或整个屏幕并添加标注",
        captureButton: "立即截取",
        panelCaption: "截取区域、窗口或整个屏幕",
        fileNamePrefix: "截屏",
        hintDrag: "拖动以选择区域",
        hintClick: "点按窗口即可截取",
        hintFullScreen: "按 Return 截取整个屏幕",
        hintCancel: "按 Esc 取消",
        hintRepeat: "按 R 重复上次区域",
        freezeToggle: "选择时冻结屏幕",
        freezeCaption: "选择区域时画面会静止，因此选择过程中不会有任何移动或变化。",
        folderLabel: "存储位置",
        folderChoose: "选择…",
        subfolderLabel: "子文件夹格式",
        subfolderCaption: "可选。使用 %y、%year、%mo、%month、%d、%h、%mi 和 %s 在上方文件夹内创建按日期命名的子文件夹，例如 %y-%mo 表示 24-03。",
        fileNamePatternLabel: "文件名",
        fileNamePatternCaption: "可选。使用与 %y、%year、%mo、%month、%d、%h、%mi 和 %s 相同的标记来覆盖默认名称，另外可用 %# 表示自动递增的编号（%## 补齐为 2 位，%### 为 3 位，以此类推）。",
        fileNumberStartLabel: "起始编号",
        fileNumberResetButton: "重置",
        fileNumberNextFormat: "下一个：%d",
        delayLabel: "延迟",
        delayOff: "关闭",
        delaySecondsFormat: "%d 秒",
        pointerToggle: "包含指针",
        downscaleToggle: "以 1x 大小存储",
        downscaleCaption: "Retina 截屏将以一半像素存储，文件更小。",
        editorTitle: "截屏",
        toolShortcutsTitle: "编辑工具",
        toolShortcutsToggle: "使用数字快捷键",
        toolShortcutsCaption: "使用箭头或选择数字。前九个工具使用 1 到 9，其余工具没有快捷键。",
        toolSelect: "选择",
        toolArrow: "箭头",
        toolLine: "直线",
        toolRect: "矩形",
        toolEllipse: "椭圆",
        toolFreehand: "画笔",
        toolHighlight: "荧光笔",
        toolText: "文本",
        toolSticker: "贴纸",
        toolCounter: "编号",
        toolPixelate: "像素化",
        toolRedact: "色块",
        toolCrop: "裁剪",
        textPlaceholder: "文本",
        cropApply: "裁剪",
        cancel: "取消",
        colorLabel: "颜色",
        strokeLabel: "粗细",
        shadowLabel: "阴影",
        backdropLabel: "背景",
        backdropNone: "无",
        editButton: "编辑",
        copyButton: "拷贝",
        saveButton: "存储",
        saveAsButton: "存储为…",
        pinButton: "钉在屏幕上",
        copyTextButton: "拷贝文本",
        discardTitle: "要丢弃这张截屏吗?",
        discardMessage: "它还没有被拷贝或存储。",
        discardConfirm: "丢弃",
        copiedHUD: "截屏已拷贝",
        savedHUDFormat: "已存储到 %@",
        savedAndCopiedHUDFormat: "已存储到 %@ 并已拷贝",
        defaultActionLabel: "默认操作",
        defaultActionCaption: "会在截屏后自动执行。确认提示仍会显示，之后仍可编辑或丢弃。",
        defaultActionNone: "每次都询问",
        defaultActionSaveAndCopy: "存储并拷贝",
        captureFailed: "无法截取屏幕",
        pinOpacity: "不透明度",
        pinClickThrough: "忽略点按",
        pinCloseAll: "关闭所有钉住的截屏",
        backdropPaddingLabel: "边距",
        backdropWallpaperLabel: "壁纸",
        backdropImageButton: "图片…",
        backdropSolidLabel: "纯色",
        backdropGradientLabel: "渐变",
        backdropCornersLabel: "圆角",
        backdropSavePreset: "保存背景",
        backdropDeletePreset: "移除",
        backdropCustomLabel: "自定义",
        openEditorToggle: "截取后立即打开编辑器",
        openEditorCaption: "截屏会跳过浮动预览，直接打开即可开始标注。",
        autoCopyToggle: "自动复制到剪贴板",
        autoCopyCaption: "每次截屏后会立即进入剪贴板，随时可以粘贴。是否保存为文件仍是单独的选择。",
        hintLoupe: "按 Z 切换放大镜",
        lastRegionToggle: "显示上次截图区域轮廓"
    )

    static let zhTW = ScreenshotFeatureStrings(
        pageTitle: "截圖",
        hubDescription: "擷取區域、視窗或整個螢幕並加上標註",
        captureButton: "立即擷取",
        panelCaption: "擷取區域、視窗或整個螢幕",
        fileNamePrefix: "截圖",
        hintDrag: "拖移以選取區域",
        hintClick: "按一下視窗即可擷取",
        hintFullScreen: "按 Return 擷取整個螢幕",
        hintCancel: "按 Esc 取消",
        hintRepeat: "按 R 重複上次區域",
        freezeToggle: "選取時凍結螢幕",
        freezeCaption: "選取區域時畫面會靜止，因此選取過程中不會有任何移動或變化。",
        folderLabel: "儲存位置",
        folderChoose: "選擇…",
        subfolderLabel: "子資料夾格式",
        subfolderCaption: "選填。使用 %y、%year、%mo、%month、%d、%h、%mi 和 %s 在上方資料夾內建立含日期的子資料夾，例如 %y-%mo 代表 24-03。",
        fileNamePatternLabel: "檔案名稱",
        fileNamePatternCaption: "選填。使用與 %y、%year、%mo、%month、%d、%h、%mi 和 %s 相同的標記來覆蓋預設名稱，另外可用 %# 表示自動遞增的編號（%## 補齊為 2 位，%### 為 3 位，以此類推）。",
        fileNumberStartLabel: "起始編號",
        fileNumberResetButton: "重設",
        fileNumberNextFormat: "下一個：%d",
        delayLabel: "延遲",
        delayOff: "關閉",
        delaySecondsFormat: "%d 秒",
        pointerToggle: "包含指標",
        downscaleToggle: "以 1x 大小儲存",
        downscaleCaption: "Retina 截圖會以一半像素儲存，檔案更小。",
        editorTitle: "截圖",
        toolShortcutsTitle: "編輯工具",
        toolShortcutsToggle: "使用數字快速鍵",
        toolShortcutsCaption: "使用箭頭或選擇數字。前九個工具使用 1 到 9，其餘工具沒有快速鍵。",
        toolSelect: "選取",
        toolArrow: "箭頭",
        toolLine: "直線",
        toolRect: "矩形",
        toolEllipse: "橢圓",
        toolFreehand: "畫筆",
        toolHighlight: "螢光筆",
        toolText: "文字",
        toolSticker: "貼圖",
        toolCounter: "編號",
        toolPixelate: "像素化",
        toolRedact: "色塊",
        toolCrop: "裁切",
        textPlaceholder: "文字",
        cropApply: "裁切",
        cancel: "取消",
        colorLabel: "顏色",
        strokeLabel: "粗細",
        shadowLabel: "陰影",
        backdropLabel: "背景",
        backdropNone: "無",
        editButton: "編輯",
        copyButton: "拷貝",
        saveButton: "儲存",
        saveAsButton: "另存為…",
        pinButton: "釘選在螢幕上",
        copyTextButton: "拷貝文字",
        discardTitle: "要捨棄這張截圖嗎?",
        discardMessage: "它還沒有被拷貝或儲存。",
        discardConfirm: "捨棄",
        copiedHUD: "截圖已拷貝",
        savedHUDFormat: "已儲存到 %@",
        savedAndCopiedHUDFormat: "已儲存到 %@ 並已拷貝",
        defaultActionLabel: "預設動作",
        defaultActionCaption: "會在擷取後自動執行。確認提示仍會顯示，之後仍可編輯或捨棄。",
        defaultActionNone: "每次都詢問",
        defaultActionSaveAndCopy: "儲存並拷貝",
        captureFailed: "無法擷取螢幕",
        pinOpacity: "不透明度",
        pinClickThrough: "忽略點按",
        pinCloseAll: "關閉所有釘選的截圖",
        backdropPaddingLabel: "邊距",
        backdropWallpaperLabel: "桌布",
        backdropImageButton: "圖片…",
        backdropSolidLabel: "純色",
        backdropGradientLabel: "漸層",
        backdropCornersLabel: "圓角",
        backdropSavePreset: "儲存背景",
        backdropDeletePreset: "移除",
        backdropCustomLabel: "自訂",
        openEditorToggle: "擷取後立即開啟編輯器",
        openEditorCaption: "截圖會略過浮動預覽，直接開啟即可開始標註。",
        autoCopyToggle: "自動拷貝到剪貼板",
        autoCopyCaption: "每次截圖後會立即進入剪貼板，隨時可以貼上。是否儲存為檔案仍是獨立的選擇。",
        hintLoupe: "按 Z 切換放大鏡",
        lastRegionToggle: "顯示上次截圖區域輪廓"
    )

    static let zhHK = ScreenshotFeatureStrings(
        pageTitle: "截圖",
        hubDescription: "擷取範圍、視窗或整個螢幕並加上標註",
        captureButton: "立即擷取",
        panelCaption: "擷取範圍、視窗或整個螢幕",
        fileNamePrefix: "截圖",
        hintDrag: "拖移以選取範圍",
        hintClick: "按一下視窗即可擷取",
        hintFullScreen: "按 Return 擷取整個螢幕",
        hintCancel: "按 Esc 取消",
        hintRepeat: "按 R 重複上次範圍",
        freezeToggle: "選取時凍結螢幕",
        freezeCaption: "選取範圍時畫面會靜止，因此選取過程中不會有任何移動或變化。",
        folderLabel: "儲存位置",
        folderChoose: "選擇…",
        subfolderLabel: "子資料夾格式",
        subfolderCaption: "選填。使用 %y、%year、%mo、%month、%d、%h、%mi 和 %s 喺上面資料夾入面建立帶日期嘅子資料夾，例如 %y-%mo 即係 24-03。",
        fileNamePatternLabel: "檔案名稱",
        fileNamePatternCaption: "選填。使用同一組 %y、%year、%mo、%month、%d、%h、%mi 同 %s 標記嚟覆蓋預設名稱，另外可以用 %# 表示自動遞增嘅編號（%## 補齊做 2 位，%### 做 3 位，如此類推）。",
        fileNumberStartLabel: "起始編號",
        fileNumberResetButton: "重設",
        fileNumberNextFormat: "下一個：%d",
        delayLabel: "延遲",
        delayOff: "關閉",
        delaySecondsFormat: "%d 秒",
        pointerToggle: "包含指標",
        downscaleToggle: "以 1x 大小儲存",
        downscaleCaption: "Retina 截圖會以一半像素儲存，檔案更小。",
        editorTitle: "截圖",
        toolShortcutsTitle: "編輯工具",
        toolShortcutsToggle: "使用數字快速鍵",
        toolShortcutsCaption: "使用箭嘴或選擇數字。前九個工具使用 1 到 9，其餘工具沒有快速鍵。",
        toolSelect: "選取",
        toolArrow: "箭嘴",
        toolLine: "直線",
        toolRect: "矩形",
        toolEllipse: "橢圓",
        toolFreehand: "畫筆",
        toolHighlight: "螢光筆",
        toolText: "文字",
        toolSticker: "貼圖",
        toolCounter: "編號",
        toolPixelate: "像素化",
        toolRedact: "色塊",
        toolCrop: "裁切",
        textPlaceholder: "文字",
        cropApply: "裁切",
        cancel: "取消",
        colorLabel: "顏色",
        strokeLabel: "粗幼",
        shadowLabel: "陰影",
        backdropLabel: "背景",
        backdropNone: "無",
        editButton: "編輯",
        copyButton: "拷貝",
        saveButton: "儲存",
        saveAsButton: "另存為…",
        pinButton: "釘選在螢幕上",
        copyTextButton: "拷貝文字",
        discardTitle: "要捨棄這張截圖嗎?",
        discardMessage: "它還未被拷貝或儲存。",
        discardConfirm: "捨棄",
        copiedHUD: "截圖已拷貝",
        savedHUDFormat: "已儲存到 %@",
        savedAndCopiedHUDFormat: "已儲存到 %@ 並已拷貝",
        defaultActionLabel: "預設動作",
        defaultActionCaption: "會喺擷取之後自動執行。確認提示仍然會顯示，之後你仲可以編輯或捨棄。",
        defaultActionNone: "每次都問",
        defaultActionSaveAndCopy: "儲存並拷貝",
        captureFailed: "無法擷取螢幕",
        pinOpacity: "不透明度",
        pinClickThrough: "忽略點按",
        pinCloseAll: "關閉所有釘選的截圖",
        backdropPaddingLabel: "邊距",
        backdropWallpaperLabel: "桌布",
        backdropImageButton: "圖片…",
        backdropSolidLabel: "純色",
        backdropGradientLabel: "漸變",
        backdropCornersLabel: "圓角",
        backdropSavePreset: "儲存背景",
        backdropDeletePreset: "移除",
        backdropCustomLabel: "自訂",
        openEditorToggle: "擷取後立即開啟編輯器",
        openEditorCaption: "截圖會略過浮動預覽，直接開啟即可開始標註。",
        autoCopyToggle: "自動拷貝到剪貼板",
        autoCopyCaption: "每次截圖後會立即進入剪貼板，隨時可以貼上。是否儲存為檔案仍是獨立的選擇。",
        hintLoupe: "按 Z 切換放大鏡",
        lastRegionToggle: "顯示上次截圖區域輪廓"
    )
}
