// SPDX-License-Identifier: GPL-3.0-or-later
// Author: naveenkrdy
// Copyright (C) 2026 Vorssaint

import Foundation

struct SelectionActionsStrings {
    let pageTitle: String
    let hubDescription: String
    let enableToggleTitle: String
    let enableToggleCaption: String
    let displayStyleLabel: String
    let displayStyleIcon: String
    let displayStyleWord: String
    let maxVisibleLabel: String
    let maxVisibleCaption: String
    let permissionTitle: String
    let permissionBody: String
    let permissionButton: String
    let actionsSectionTitle: String
    let actionsSectionCaption: String
    let excludedSectionTitle: String
    let excludedAppsTitle: String
    let excludedAppsCaption: String
    let excludedAppsAddButton: String
    let excludedAppsRemoveButton: String
    let excludedDomainsTitle: String
    let excludedDomainsCaption: String
    let excludedDomainsPlaceholder: String
    let excludedDomainsAddButton: String
    let excludedDomainsRemoveButton: String

    let copyTitle: String
    let cutTitle: String
    let pasteTitle: String
    let deleteTitle: String
    let pastePlainTitle: String
    let uppercaseTitle: String
    let lowercaseTitle: String
    let capitalizeTitle: String
    let removeSpacesTitle: String
    let underscoreTitle: String
    let joinLinesTitle: String
    let commaListTitle: String
    let sortTitle: String
    let reverseTitle: String
    let randomTitle: String
    let quotesTitle: String
    let bracketsTitle: String
    let urlEncodeTitle: String
    let urlDecodeTitle: String
    let base64EncodeTitle: String
    let base64DecodeTitle: String
    let calculateTitle: String
    let addToScratchpadTitle: String

    let copyDescription: String
    let cutDescription: String
    let pasteDescription: String
    let deleteDescription: String
    let pastePlainDescription: String
    let uppercaseDescription: String
    let lowercaseDescription: String
    let capitalizeDescription: String
    let removeSpacesDescription: String
    let underscoreDescription: String
    let joinLinesDescription: String
    let commaListDescription: String
    let sortDescription: String
    let reverseDescription: String
    let randomDescription: String
    let quotesDescription: String
    let bracketsDescription: String
    let urlEncodeDescription: String
    let urlDecodeDescription: String
    let base64EncodeDescription: String
    let base64DecodeDescription: String
    let calculateDescription: String
    let addToScratchpadDescription: String

    func title(for action: SelectionAction) -> String {
        switch action {
        case .copy: return copyTitle
        case .cut: return cutTitle
        case .paste: return pasteTitle
        case .delete: return deleteTitle
        case .pastePlain: return pastePlainTitle
        case .uppercase: return uppercaseTitle
        case .lowercase: return lowercaseTitle
        case .capitalize: return capitalizeTitle
        case .removeSpaces: return removeSpacesTitle
        case .underscore: return underscoreTitle
        case .joinLines: return joinLinesTitle
        case .commaList: return commaListTitle
        case .sort: return sortTitle
        case .reverse: return reverseTitle
        case .random: return randomTitle
        case .quotes: return quotesTitle
        case .brackets: return bracketsTitle
        case .urlEncode: return urlEncodeTitle
        case .urlDecode: return urlDecodeTitle
        case .base64Encode: return base64EncodeTitle
        case .base64Decode: return base64DecodeTitle
        case .calculate: return calculateTitle
        case .addToScratchpad: return addToScratchpadTitle
        }
    }

    func description(for action: SelectionAction) -> String {
        switch action {
        case .copy: return copyDescription
        case .cut: return cutDescription
        case .paste: return pasteDescription
        case .delete: return deleteDescription
        case .pastePlain: return pastePlainDescription
        case .uppercase: return uppercaseDescription
        case .lowercase: return lowercaseDescription
        case .capitalize: return capitalizeDescription
        case .removeSpaces: return removeSpacesDescription
        case .underscore: return underscoreDescription
        case .joinLines: return joinLinesDescription
        case .commaList: return commaListDescription
        case .sort: return sortDescription
        case .reverse: return reverseDescription
        case .random: return randomDescription
        case .quotes: return quotesDescription
        case .brackets: return bracketsDescription
        case .urlEncode: return urlEncodeDescription
        case .urlDecode: return urlDecodeDescription
        case .base64Encode: return base64EncodeDescription
        case .base64Decode: return base64DecodeDescription
        case .calculate: return calculateDescription
        case .addToScratchpad: return addToScratchpadDescription
        }
    }
}

extension FeatureStrings {
    static func selectionActions(_ language: AppLanguage) -> SelectionActionsStrings {
        switch language {
        case .enUS: return .enUS
        case .ptBR: return .ptBR
        case .tr: return .tr
        case .ru: return .ru
        case .es: return .es
        case .de: return .de
        case .fr: return .fr
        case .it: return .it
        case .ja: return .ja
        case .ko: return .ko
        case .zhHans: return .zhHans
        case .zhTW: return .zhTW
        case .zhHK: return .zhHK
        }
    }
}

extension SelectionActionsStrings {
    static let enUS = SelectionActionsStrings(
        pageTitle: "Selection Actions",
        hubDescription: "Quick actions on any text you select",
        enableToggleTitle: "Enable Selection Actions",
        enableToggleCaption: "Shows a small toolbar next to text you select in any app",
        displayStyleLabel: "Show actions as",
        displayStyleIcon: "Icons",
        displayStyleWord: "Words",
        maxVisibleLabel: "Show at most",
        maxVisibleCaption: "The rest collapse under a ▾ in the bar",
        permissionTitle: "Accessibility Access Needed",
        permissionBody: "Selection Actions reads what you select and can replace it, which requires Accessibility access.",
        permissionButton: "Grant Access",
        actionsSectionTitle: "Actions",
        actionsSectionCaption: "Drag to reorder. Only actions that make sense for the current selection appear in the bar.",
        excludedSectionTitle: "Excluded",
        excludedAppsTitle: "Apps",
        excludedAppsCaption: "Selection Actions never appears in these apps.",
        excludedAppsAddButton: "Add App…",
        excludedAppsRemoveButton: "Remove",
        excludedDomainsTitle: "Websites",
        excludedDomainsCaption: "One website per line. Works in Safari, Chrome, Edge, Brave and Firefox — other browsers may not report the page address.",
        excludedDomainsPlaceholder: "example.com",
        excludedDomainsAddButton: "Add",
        excludedDomainsRemoveButton: "Remove",
        copyTitle: "Copy",
        cutTitle: "Cut",
        pasteTitle: "Paste",
        deleteTitle: "Delete",
        pastePlainTitle: "Paste as Plain Text",
        uppercaseTitle: "UPPERCASE",
        lowercaseTitle: "lowercase",
        capitalizeTitle: "Capitalize",
        removeSpacesTitle: "Remove Spaces",
        underscoreTitle: "Underscore",
        joinLinesTitle: "Join Lines",
        commaListTitle: "Comma List",
        sortTitle: "Sort",
        reverseTitle: "Reverse",
        randomTitle: "Random",
        quotesTitle: "Quotes",
        bracketsTitle: "Brackets",
        urlEncodeTitle: "URL Encode",
        urlDecodeTitle: "URL Decode",
        base64EncodeTitle: "Base64 Encode",
        base64DecodeTitle: "Base64 Decode",
        calculateTitle: "Calculate",
        addToScratchpadTitle: "Add to Scratchpad",
        copyDescription: "Copies the selection to the clipboard.",
        cutDescription: "Copies the selection, then removes it.",
        pasteDescription: "Replaces the selection with what's on the clipboard.",
        deleteDescription: "Removes the selection without copying it.",
        pastePlainDescription: "Same, but strips fonts, colors and links first.",
        uppercaseDescription: "Converts the selection to uppercase.",
        lowercaseDescription: "Converts the selection to lowercase.",
        capitalizeDescription: "Capitalizes each word in the selection.",
        removeSpacesDescription: "Removes every space in the selection.",
        underscoreDescription: "Replaces spaces with underscores.",
        joinLinesDescription: "Joins multiple lines into one.",
        commaListDescription: "Joins lines or words into a comma-separated list.",
        sortDescription: "Sorts lines, words, or letters alphabetically.",
        reverseDescription: "Reverses the order of lines, words, or letters.",
        randomDescription: "Shuffles lines, words, or letters.",
        quotesDescription: "Wraps the selection in quotation marks.",
        bracketsDescription: "Wraps the selection in parentheses.",
        urlEncodeDescription: "Percent-encodes the selection for a URL.",
        urlDecodeDescription: "Removes percent-encoding from the selection.",
        base64EncodeDescription: "Encodes the selection as Base64.",
        base64DecodeDescription: "Decodes the selection from Base64.",
        calculateDescription: "Evaluates the selection as a math expression.",
        addToScratchpadDescription: "Adds the selection to the Scratchpad."
    )

    static let ptBR = SelectionActionsStrings(
        pageTitle: "Ações de Seleção",
        hubDescription: "Ações rápidas sobre qualquer texto selecionado",
        enableToggleTitle: "Ativar Ações de Seleção",
        enableToggleCaption: "Mostra uma pequena barra ao lado do texto selecionado em qualquer app",
        displayStyleLabel: "Mostrar ações como",
        displayStyleIcon: "Ícones",
        displayStyleWord: "Palavras",
        maxVisibleLabel: "Mostrar no máximo",
        maxVisibleCaption: "O restante fica dentro de um ▾ na barra",
        permissionTitle: "Acesso de Acessibilidade Necessário",
        permissionBody: "Ações de Seleção lê o texto selecionado e pode substituí-lo, o que exige acesso de Acessibilidade.",
        permissionButton: "Conceder Acesso",
        actionsSectionTitle: "Ações",
        actionsSectionCaption: "Arraste para reordenar. Só aparecem na barra as ações que fazem sentido para a seleção atual.",
        excludedSectionTitle: "Excluídos",
        excludedAppsTitle: "Apps",
        excludedAppsCaption: "Ações de Seleção nunca aparece nestes apps.",
        excludedAppsAddButton: "Adicionar App…",
        excludedAppsRemoveButton: "Remover",
        excludedDomainsTitle: "Sites",
        excludedDomainsCaption: "Um site por linha. Funciona no Safari, Chrome, Edge, Brave e Firefox — outros navegadores podem não informar o endereço da página.",
        excludedDomainsPlaceholder: "exemplo.com",
        excludedDomainsAddButton: "Adicionar",
        excludedDomainsRemoveButton: "Remover",
        copyTitle: "Copiar",
        cutTitle: "Recortar",
        pasteTitle: "Colar",
        deleteTitle: "Excluir",
        pastePlainTitle: "Colar como Texto Simples",
        uppercaseTitle: "MAIÚSCULAS",
        lowercaseTitle: "minúsculas",
        capitalizeTitle: "Capitalizar",
        removeSpacesTitle: "Remover Espaços",
        underscoreTitle: "Sublinhado",
        joinLinesTitle: "Unir Linhas",
        commaListTitle: "Lista com Vírgulas",
        sortTitle: "Ordenar",
        reverseTitle: "Inverter",
        randomTitle: "Aleatório",
        quotesTitle: "Aspas",
        bracketsTitle: "Parênteses",
        urlEncodeTitle: "Codificar URL",
        urlDecodeTitle: "Decodificar URL",
        base64EncodeTitle: "Codificar Base64",
        base64DecodeTitle: "Decodificar Base64",
        calculateTitle: "Calcular",
        addToScratchpadTitle: "Adicionar ao Bloco de Notas",
        copyDescription: "Copia a seleção para a área de transferência.",
        cutDescription: "Copia a seleção e a remove em seguida.",
        pasteDescription: "Substitui a seleção pelo conteúdo da área de transferência.",
        deleteDescription: "Remove a seleção sem copiá-la.",
        pastePlainDescription: "O mesmo, mas removendo fontes, cores e links antes.",
        uppercaseDescription: "Converte a seleção para maiúsculas.",
        lowercaseDescription: "Converte a seleção para minúsculas.",
        capitalizeDescription: "Coloca em maiúscula a inicial de cada palavra da seleção.",
        removeSpacesDescription: "Remove todos os espaços da seleção.",
        underscoreDescription: "Substitui espaços por sublinhados.",
        joinLinesDescription: "Une várias linhas em uma só.",
        commaListDescription: "Une linhas ou palavras em uma lista separada por vírgulas.",
        sortDescription: "Ordena linhas, palavras ou letras alfabeticamente.",
        reverseDescription: "Inverte a ordem de linhas, palavras ou letras.",
        randomDescription: "Embaralha linhas, palavras ou letras.",
        quotesDescription: "Coloca a seleção entre aspas.",
        bracketsDescription: "Coloca a seleção entre parênteses.",
        urlEncodeDescription: "Codifica a seleção em percent-encoding para uma URL.",
        urlDecodeDescription: "Remove a codificação percent-encoding da seleção.",
        base64EncodeDescription: "Codifica a seleção em Base64.",
        base64DecodeDescription: "Decodifica a seleção de Base64.",
        calculateDescription: "Avalia a seleção como uma expressão matemática.",
        addToScratchpadDescription: "Adiciona a seleção ao Bloco de Notas."
    )

    static let tr = SelectionActionsStrings(
        pageTitle: "Seçim Eylemleri",
        hubDescription: "Seçtiğiniz herhangi bir metin üzerinde hızlı eylemler",
        enableToggleTitle: "Seçim Eylemlerini Etkinleştir",
        enableToggleCaption: "Herhangi bir uygulamada seçtiğiniz metnin yanında küçük bir araç çubuğu gösterir",
        displayStyleLabel: "Eylemleri şu şekilde göster",
        displayStyleIcon: "Simgeler",
        displayStyleWord: "Kelimeler",
        maxVisibleLabel: "En fazla şunu göster",
        maxVisibleCaption: "Kalanlar çubukta bir ▾ altında toplanır",
        permissionTitle: "Erişilebilirlik İzni Gerekli",
        permissionBody: "Seçim Eylemleri, seçtiğiniz metni okur ve değiştirebilir; bu da Erişilebilirlik izni gerektirir.",
        permissionButton: "İzin Ver",
        actionsSectionTitle: "Eylemler",
        actionsSectionCaption: "Yeniden sıralamak için sürükleyin. Çubukta yalnızca geçerli seçim için anlamlı olan eylemler görünür.",
        excludedSectionTitle: "Hariç Tutulanlar",
        excludedAppsTitle: "Uygulamalar",
        excludedAppsCaption: "Seçim Eylemleri bu uygulamalarda hiç görünmez.",
        excludedAppsAddButton: "Uygulama Ekle…",
        excludedAppsRemoveButton: "Kaldır",
        excludedDomainsTitle: "Web Siteleri",
        excludedDomainsCaption: "Satır başına bir web sitesi. Safari, Chrome, Edge, Brave ve Firefox'ta çalışır — diğer tarayıcılar sayfa adresini bildirmeyebilir.",
        excludedDomainsPlaceholder: "ornek.com",
        excludedDomainsAddButton: "Ekle",
        excludedDomainsRemoveButton: "Kaldır",
        copyTitle: "Kopyala",
        cutTitle: "Kes",
        pasteTitle: "Yapıştır",
        deleteTitle: "Sil",
        pastePlainTitle: "Düz Metin Olarak Yapıştır",
        uppercaseTitle: "BÜYÜK HARF",
        lowercaseTitle: "küçük harf",
        capitalizeTitle: "Baş Harfleri Büyüt",
        removeSpacesTitle: "Boşlukları Kaldır",
        underscoreTitle: "Alt Çizgi",
        joinLinesTitle: "Satırları Birleştir",
        commaListTitle: "Virgüllü Liste",
        sortTitle: "Sırala",
        reverseTitle: "Ters Çevir",
        randomTitle: "Rastgele",
        quotesTitle: "Tırnak İşareti",
        bracketsTitle: "Parantez",
        urlEncodeTitle: "URL Kodla",
        urlDecodeTitle: "URL Kodunu Çöz",
        base64EncodeTitle: "Base64 Kodla",
        base64DecodeTitle: "Base64 Kodunu Çöz",
        calculateTitle: "Hesapla",
        addToScratchpadTitle: "Not Defterine Ekle",
        copyDescription: "Seçimi panoya kopyalar.",
        cutDescription: "Seçimi kopyalar, sonra kaldırır.",
        pasteDescription: "Seçimi panodaki içerikle değiştirir.",
        deleteDescription: "Seçimi kopyalamadan kaldırır.",
        pastePlainDescription: "Aynısı, ancak önce yazı tiplerini, renkleri ve bağlantıları kaldırır.",
        uppercaseDescription: "Seçimi büyük harfe çevirir.",
        lowercaseDescription: "Seçimi küçük harfe çevirir.",
        capitalizeDescription: "Seçimdeki her kelimenin baş harfini büyütür.",
        removeSpacesDescription: "Seçimdeki tüm boşlukları kaldırır.",
        underscoreDescription: "Boşlukları alt çizgiyle değiştirir.",
        joinLinesDescription: "Birden fazla satırı tek satırda birleştirir.",
        commaListDescription: "Satırları veya kelimeleri virgülle ayrılmış bir listede birleştirir.",
        sortDescription: "Satırları, kelimeleri veya harfleri alfabetik sıralar.",
        reverseDescription: "Satırların, kelimelerin veya harflerin sırasını ters çevirir.",
        randomDescription: "Satırları, kelimeleri veya harfleri karıştırır.",
        quotesDescription: "Seçimi tırnak işareti içine alır.",
        bracketsDescription: "Seçimi parantez içine alır.",
        urlEncodeDescription: "Seçimi bir URL için yüzde kodlamasıyla kodlar.",
        urlDecodeDescription: "Seçimden yüzde kodlamasını kaldırır.",
        base64EncodeDescription: "Seçimi Base64 olarak kodlar.",
        base64DecodeDescription: "Seçimi Base64'ten çözer.",
        calculateDescription: "Seçimi bir matematik ifadesi olarak hesaplar.",
        addToScratchpadDescription: "Seçimi Not Defterine ekler."
    )

    static let ru = SelectionActionsStrings(
        pageTitle: "Действия с выделением",
        hubDescription: "Быстрые действия с любым выделенным текстом",
        enableToggleTitle: "Включить действия с выделением",
        enableToggleCaption: "Показывает небольшую панель рядом с выделенным текстом в любом приложении",
        displayStyleLabel: "Показывать действия как",
        displayStyleIcon: "Значки",
        displayStyleWord: "Слова",
        maxVisibleLabel: "Показывать не более",
        maxVisibleCaption: "Остальные скрываются под ▾ на панели",
        permissionTitle: "Требуется доступ Универсального доступа",
        permissionBody: "«Действия с выделением» считывает выделенный текст и может заменить его, для чего требуется доступ Универсального доступа.",
        permissionButton: "Предоставить доступ",
        actionsSectionTitle: "Действия",
        actionsSectionCaption: "Перетащите, чтобы изменить порядок. На панели показываются только действия, подходящие для текущего выделения.",
        excludedSectionTitle: "Исключения",
        excludedAppsTitle: "Приложения",
        excludedAppsCaption: "«Действия с выделением» никогда не появляются в этих приложениях.",
        excludedAppsAddButton: "Добавить приложение…",
        excludedAppsRemoveButton: "Удалить",
        excludedDomainsTitle: "Сайты",
        excludedDomainsCaption: "По одному сайту на строку. Работает в Safari, Chrome, Edge, Brave и Firefox — другие браузеры могут не сообщать адрес страницы.",
        excludedDomainsPlaceholder: "example.com",
        excludedDomainsAddButton: "Добавить",
        excludedDomainsRemoveButton: "Удалить",
        copyTitle: "Копировать",
        cutTitle: "Вырезать",
        pasteTitle: "Вставить",
        deleteTitle: "Удалить",
        pastePlainTitle: "Вставить как обычный текст",
        uppercaseTitle: "ВЕРХНИЙ РЕГИСТР",
        lowercaseTitle: "нижний регистр",
        capitalizeTitle: "Заглавные буквы",
        removeSpacesTitle: "Удалить пробелы",
        underscoreTitle: "Подчёркивание",
        joinLinesTitle: "Объединить строки",
        commaListTitle: "Список через запятую",
        sortTitle: "Сортировать",
        reverseTitle: "Развернуть",
        randomTitle: "Случайно",
        quotesTitle: "Кавычки",
        bracketsTitle: "Скобки",
        urlEncodeTitle: "URL-кодирование",
        urlDecodeTitle: "URL-декодирование",
        base64EncodeTitle: "Кодировать Base64",
        base64DecodeTitle: "Декодировать Base64",
        calculateTitle: "Вычислить",
        addToScratchpadTitle: "Добавить в Блокнот",
        copyDescription: "Копирует выделение в буфер обмена.",
        cutDescription: "Копирует выделение, затем удаляет его.",
        pasteDescription: "Заменяет выделение содержимым буфера обмена.",
        deleteDescription: "Удаляет выделение без копирования.",
        pastePlainDescription: "То же самое, но сначала убирает шрифты, цвета и ссылки.",
        uppercaseDescription: "Переводит выделение в верхний регистр.",
        lowercaseDescription: "Переводит выделение в нижний регистр.",
        capitalizeDescription: "Делает заглавной первую букву каждого слова в выделении.",
        removeSpacesDescription: "Удаляет все пробелы в выделении.",
        underscoreDescription: "Заменяет пробелы символами подчёркивания.",
        joinLinesDescription: "Объединяет несколько строк в одну.",
        commaListDescription: "Объединяет строки или слова в список через запятую.",
        sortDescription: "Сортирует строки, слова или буквы по алфавиту.",
        reverseDescription: "Меняет порядок строк, слов или букв на обратный.",
        randomDescription: "Перемешивает строки, слова или буквы.",
        quotesDescription: "Заключает выделение в кавычки.",
        bracketsDescription: "Заключает выделение в скобки.",
        urlEncodeDescription: "Кодирует выделение для URL (percent-encoding).",
        urlDecodeDescription: "Убирает percent-encoding из выделения.",
        base64EncodeDescription: "Кодирует выделение в Base64.",
        base64DecodeDescription: "Декодирует выделение из Base64.",
        calculateDescription: "Вычисляет выделение как математическое выражение.",
        addToScratchpadDescription: "Добавляет выделение в Блокнот."
    )

    static let es = SelectionActionsStrings(
        pageTitle: "Acciones de Selección",
        hubDescription: "Acciones rápidas sobre cualquier texto seleccionado",
        enableToggleTitle: "Activar Acciones de Selección",
        enableToggleCaption: "Muestra una pequeña barra junto al texto que selecciones en cualquier app",
        displayStyleLabel: "Mostrar acciones como",
        displayStyleIcon: "Iconos",
        displayStyleWord: "Palabras",
        maxVisibleLabel: "Mostrar como máximo",
        maxVisibleCaption: "El resto queda dentro de un ▾ en la barra",
        permissionTitle: "Se necesita acceso de Accesibilidad",
        permissionBody: "Acciones de Selección lee el texto seleccionado y puede reemplazarlo, lo que requiere acceso de Accesibilidad.",
        permissionButton: "Conceder Acceso",
        actionsSectionTitle: "Acciones",
        actionsSectionCaption: "Arrastra para reordenar. Solo las acciones que tienen sentido para la selección actual aparecen en la barra.",
        excludedSectionTitle: "Excluidos",
        excludedAppsTitle: "Apps",
        excludedAppsCaption: "Acciones de Selección nunca aparece en estas apps.",
        excludedAppsAddButton: "Añadir App…",
        excludedAppsRemoveButton: "Eliminar",
        excludedDomainsTitle: "Sitios Web",
        excludedDomainsCaption: "Un sitio web por línea. Funciona en Safari, Chrome, Edge, Brave y Firefox; otros navegadores podrían no indicar la dirección de la página.",
        excludedDomainsPlaceholder: "ejemplo.com",
        excludedDomainsAddButton: "Añadir",
        excludedDomainsRemoveButton: "Eliminar",
        copyTitle: "Copiar",
        cutTitle: "Cortar",
        pasteTitle: "Pegar",
        deleteTitle: "Eliminar",
        pastePlainTitle: "Pegar como Texto Sin Formato",
        uppercaseTitle: "MAYÚSCULAS",
        lowercaseTitle: "minúsculas",
        capitalizeTitle: "Capitalizar",
        removeSpacesTitle: "Quitar Espacios",
        underscoreTitle: "Guion Bajo",
        joinLinesTitle: "Unir Líneas",
        commaListTitle: "Lista con Comas",
        sortTitle: "Ordenar",
        reverseTitle: "Invertir",
        randomTitle: "Aleatorio",
        quotesTitle: "Comillas",
        bracketsTitle: "Paréntesis",
        urlEncodeTitle: "Codificar URL",
        urlDecodeTitle: "Decodificar URL",
        base64EncodeTitle: "Codificar Base64",
        base64DecodeTitle: "Decodificar Base64",
        calculateTitle: "Calcular",
        addToScratchpadTitle: "Añadir al Bloc de Notas",
        copyDescription: "Copia la selección al portapapeles.",
        cutDescription: "Copia la selección y luego la elimina.",
        pasteDescription: "Reemplaza la selección con el contenido del portapapeles.",
        deleteDescription: "Elimina la selección sin copiarla.",
        pastePlainDescription: "Lo mismo, pero eliminando antes fuentes, colores y enlaces.",
        uppercaseDescription: "Convierte la selección a mayúsculas.",
        lowercaseDescription: "Convierte la selección a minúsculas.",
        capitalizeDescription: "Pone en mayúscula la inicial de cada palabra de la selección.",
        removeSpacesDescription: "Elimina todos los espacios de la selección.",
        underscoreDescription: "Reemplaza los espacios por guiones bajos.",
        joinLinesDescription: "Une varias líneas en una sola.",
        commaListDescription: "Une líneas o palabras en una lista separada por comas.",
        sortDescription: "Ordena líneas, palabras o letras alfabéticamente.",
        reverseDescription: "Invierte el orden de líneas, palabras o letras.",
        randomDescription: "Mezcla líneas, palabras o letras.",
        quotesDescription: "Envuelve la selección entre comillas.",
        bracketsDescription: "Envuelve la selección entre paréntesis.",
        urlEncodeDescription: "Codifica la selección con percent-encoding para una URL.",
        urlDecodeDescription: "Quita el percent-encoding de la selección.",
        base64EncodeDescription: "Codifica la selección en Base64.",
        base64DecodeDescription: "Decodifica la selección desde Base64.",
        calculateDescription: "Evalúa la selección como una expresión matemática.",
        addToScratchpadDescription: "Añade la selección al Bloc de Notas."
    )

    static let de = SelectionActionsStrings(
        pageTitle: "Auswahlaktionen",
        hubDescription: "Schnelle Aktionen für jeden ausgewählten Text",
        enableToggleTitle: "Auswahlaktionen aktivieren",
        enableToggleCaption: "Zeigt eine kleine Leiste neben Text, den du in einer beliebigen App auswählst",
        displayStyleLabel: "Aktionen anzeigen als",
        displayStyleIcon: "Symbole",
        displayStyleWord: "Wörter",
        maxVisibleLabel: "Höchstens anzeigen",
        maxVisibleCaption: "Der Rest wird in der Leiste unter einem ▾ zusammengefasst",
        permissionTitle: "Bedienungshilfen-Zugriff erforderlich",
        permissionBody: "Auswahlaktionen liest den ausgewählten Text und kann ihn ersetzen, wofür Zugriff auf die Bedienungshilfen nötig ist.",
        permissionButton: "Zugriff gewähren",
        actionsSectionTitle: "Aktionen",
        actionsSectionCaption: "Zum Umsortieren ziehen. In der Leiste erscheinen nur Aktionen, die zur aktuellen Auswahl passen.",
        excludedSectionTitle: "Ausgeschlossen",
        excludedAppsTitle: "Apps",
        excludedAppsCaption: "Auswahlaktionen erscheint in diesen Apps nie.",
        excludedAppsAddButton: "App hinzufügen…",
        excludedAppsRemoveButton: "Entfernen",
        excludedDomainsTitle: "Websites",
        excludedDomainsCaption: "Eine Website pro Zeile. Funktioniert in Safari, Chrome, Edge, Brave und Firefox — andere Browser melden die Seitenadresse möglicherweise nicht.",
        excludedDomainsPlaceholder: "beispiel.de",
        excludedDomainsAddButton: "Hinzufügen",
        excludedDomainsRemoveButton: "Entfernen",
        copyTitle: "Kopieren",
        cutTitle: "Ausschneiden",
        pasteTitle: "Einfügen",
        deleteTitle: "Löschen",
        pastePlainTitle: "Als reinen Text einfügen",
        uppercaseTitle: "GROSSBUCHSTABEN",
        lowercaseTitle: "kleinbuchstaben",
        capitalizeTitle: "Großschreiben",
        removeSpacesTitle: "Leerzeichen entfernen",
        underscoreTitle: "Unterstrich",
        joinLinesTitle: "Zeilen zusammenführen",
        commaListTitle: "Kommaliste",
        sortTitle: "Sortieren",
        reverseTitle: "Umkehren",
        randomTitle: "Zufällig",
        quotesTitle: "Anführungszeichen",
        bracketsTitle: "Klammern",
        urlEncodeTitle: "URL kodieren",
        urlDecodeTitle: "URL dekodieren",
        base64EncodeTitle: "Base64 kodieren",
        base64DecodeTitle: "Base64 dekodieren",
        calculateTitle: "Berechnen",
        addToScratchpadTitle: "Zum Notizblock hinzufügen",
        copyDescription: "Kopiert die Auswahl in die Zwischenablage.",
        cutDescription: "Kopiert die Auswahl und entfernt sie dann.",
        pasteDescription: "Ersetzt die Auswahl durch den Inhalt der Zwischenablage.",
        deleteDescription: "Entfernt die Auswahl, ohne sie zu kopieren.",
        pastePlainDescription: "Dasselbe, entfernt aber zuerst Schriften, Farben und Links.",
        uppercaseDescription: "Wandelt die Auswahl in Großbuchstaben um.",
        lowercaseDescription: "Wandelt die Auswahl in Kleinbuchstaben um.",
        capitalizeDescription: "Schreibt jedes Wort der Auswahl groß.",
        removeSpacesDescription: "Entfernt alle Leerzeichen in der Auswahl.",
        underscoreDescription: "Ersetzt Leerzeichen durch Unterstriche.",
        joinLinesDescription: "Führt mehrere Zeilen zu einer zusammen.",
        commaListDescription: "Fügt Zeilen oder Wörter zu einer kommagetrennten Liste zusammen.",
        sortDescription: "Sortiert Zeilen, Wörter oder Buchstaben alphabetisch.",
        reverseDescription: "Kehrt die Reihenfolge von Zeilen, Wörtern oder Buchstaben um.",
        randomDescription: "Mischt Zeilen, Wörter oder Buchstaben.",
        quotesDescription: "Setzt die Auswahl in Anführungszeichen.",
        bracketsDescription: "Setzt die Auswahl in Klammern.",
        urlEncodeDescription: "Kodiert die Auswahl per Prozent-Kodierung für eine URL.",
        urlDecodeDescription: "Entfernt die Prozent-Kodierung aus der Auswahl.",
        base64EncodeDescription: "Kodiert die Auswahl als Base64.",
        base64DecodeDescription: "Dekodiert die Auswahl aus Base64.",
        calculateDescription: "Wertet die Auswahl als mathematischen Ausdruck aus.",
        addToScratchpadDescription: "Fügt die Auswahl dem Notizblock hinzu."
    )

    static let fr = SelectionActionsStrings(
        pageTitle: "Actions de sélection",
        hubDescription: "Actions rapides sur tout texte sélectionné",
        enableToggleTitle: "Activer les actions de sélection",
        enableToggleCaption: "Affiche une petite barre à côté du texte sélectionné dans n'importe quelle app",
        displayStyleLabel: "Afficher les actions en",
        displayStyleIcon: "Icônes",
        displayStyleWord: "Mots",
        maxVisibleLabel: "Afficher au maximum",
        maxVisibleCaption: "Le reste se replie sous un ▾ dans la barre",
        permissionTitle: "Accès Accessibilité requis",
        permissionBody: "Actions de sélection lit le texte sélectionné et peut le remplacer, ce qui nécessite l'accès Accessibilité.",
        permissionButton: "Autoriser l'accès",
        actionsSectionTitle: "Actions",
        actionsSectionCaption: "Faites glisser pour réorganiser. Seules les actions pertinentes pour la sélection actuelle apparaissent dans la barre.",
        excludedSectionTitle: "Exclusions",
        excludedAppsTitle: "Apps",
        excludedAppsCaption: "Actions de sélection n'apparaît jamais dans ces apps.",
        excludedAppsAddButton: "Ajouter une app…",
        excludedAppsRemoveButton: "Supprimer",
        excludedDomainsTitle: "Sites web",
        excludedDomainsCaption: "Un site par ligne. Fonctionne dans Safari, Chrome, Edge, Brave et Firefox — les autres navigateurs peuvent ne pas signaler l'adresse de la page.",
        excludedDomainsPlaceholder: "exemple.com",
        excludedDomainsAddButton: "Ajouter",
        excludedDomainsRemoveButton: "Supprimer",
        copyTitle: "Copier",
        cutTitle: "Couper",
        pasteTitle: "Coller",
        deleteTitle: "Supprimer",
        pastePlainTitle: "Coller sans mise en forme",
        uppercaseTitle: "MAJUSCULES",
        lowercaseTitle: "minuscules",
        capitalizeTitle: "Mettre en majuscules",
        removeSpacesTitle: "Supprimer les espaces",
        underscoreTitle: "Tiret bas",
        joinLinesTitle: "Joindre les lignes",
        commaListTitle: "Liste avec virgules",
        sortTitle: "Trier",
        reverseTitle: "Inverser",
        randomTitle: "Aléatoire",
        quotesTitle: "Guillemets",
        bracketsTitle: "Parenthèses",
        urlEncodeTitle: "Encoder l'URL",
        urlDecodeTitle: "Décoder l'URL",
        base64EncodeTitle: "Encoder en Base64",
        base64DecodeTitle: "Décoder le Base64",
        calculateTitle: "Calculer",
        addToScratchpadTitle: "Ajouter au Bloc-notes",
        copyDescription: "Copie la sélection dans le presse-papiers.",
        cutDescription: "Copie la sélection, puis la supprime.",
        pasteDescription: "Remplace la sélection par le contenu du presse-papiers.",
        deleteDescription: "Supprime la sélection sans la copier.",
        pastePlainDescription: "Pareil, mais retire d'abord les polices, couleurs et liens.",
        uppercaseDescription: "Convertit la sélection en majuscules.",
        lowercaseDescription: "Convertit la sélection en minuscules.",
        capitalizeDescription: "Met en majuscule l'initiale de chaque mot de la sélection.",
        removeSpacesDescription: "Supprime tous les espaces de la sélection.",
        underscoreDescription: "Remplace les espaces par des tirets bas.",
        joinLinesDescription: "Réunit plusieurs lignes en une seule.",
        commaListDescription: "Réunit des lignes ou des mots en une liste séparée par des virgules.",
        sortDescription: "Trie les lignes, mots ou lettres par ordre alphabétique.",
        reverseDescription: "Inverse l'ordre des lignes, mots ou lettres.",
        randomDescription: "Mélange les lignes, mots ou lettres.",
        quotesDescription: "Encadre la sélection de guillemets.",
        bracketsDescription: "Encadre la sélection de parenthèses.",
        urlEncodeDescription: "Encode la sélection en percent-encoding pour une URL.",
        urlDecodeDescription: "Retire le percent-encoding de la sélection.",
        base64EncodeDescription: "Encode la sélection en Base64.",
        base64DecodeDescription: "Décode la sélection depuis Base64.",
        calculateDescription: "Évalue la sélection comme une expression mathématique.",
        addToScratchpadDescription: "Ajoute la sélection au Bloc-notes."
    )

    static let it = SelectionActionsStrings(
        pageTitle: "Azioni di selezione",
        hubDescription: "Azioni rapide su qualsiasi testo selezionato",
        enableToggleTitle: "Attiva Azioni di selezione",
        enableToggleCaption: "Mostra una piccola barra accanto al testo selezionato in qualsiasi app",
        displayStyleLabel: "Mostra le azioni come",
        displayStyleIcon: "Icone",
        displayStyleWord: "Parole",
        maxVisibleLabel: "Mostra al massimo",
        maxVisibleCaption: "Il resto si raccoglie sotto un ▾ nella barra",
        permissionTitle: "Accesso Accessibilità richiesto",
        permissionBody: "Azioni di selezione legge il testo selezionato e può sostituirlo, il che richiede l'accesso Accessibilità.",
        permissionButton: "Concedi accesso",
        actionsSectionTitle: "Azioni",
        actionsSectionCaption: "Trascina per riordinare. Nella barra compaiono solo le azioni pertinenti alla selezione attuale.",
        excludedSectionTitle: "Esclusi",
        excludedAppsTitle: "App",
        excludedAppsCaption: "Azioni di selezione non appare mai in queste app.",
        excludedAppsAddButton: "Aggiungi App…",
        excludedAppsRemoveButton: "Rimuovi",
        excludedDomainsTitle: "Siti Web",
        excludedDomainsCaption: "Un sito per riga. Funziona in Safari, Chrome, Edge, Brave e Firefox — altri browser potrebbero non segnalare l'indirizzo della pagina.",
        excludedDomainsPlaceholder: "esempio.com",
        excludedDomainsAddButton: "Aggiungi",
        excludedDomainsRemoveButton: "Rimuovi",
        copyTitle: "Copia",
        cutTitle: "Taglia",
        pasteTitle: "Incolla",
        deleteTitle: "Elimina",
        pastePlainTitle: "Incolla come Testo Semplice",
        uppercaseTitle: "MAIUSCOLO",
        lowercaseTitle: "minuscolo",
        capitalizeTitle: "Iniziali Maiuscole",
        removeSpacesTitle: "Rimuovi Spazi",
        underscoreTitle: "Trattino Basso",
        joinLinesTitle: "Unisci Righe",
        commaListTitle: "Elenco con Virgole",
        sortTitle: "Ordina",
        reverseTitle: "Inverti",
        randomTitle: "Casuale",
        quotesTitle: "Virgolette",
        bracketsTitle: "Parentesi",
        urlEncodeTitle: "Codifica URL",
        urlDecodeTitle: "Decodifica URL",
        base64EncodeTitle: "Codifica Base64",
        base64DecodeTitle: "Decodifica Base64",
        calculateTitle: "Calcola",
        addToScratchpadTitle: "Aggiungi al Blocco Note",
        copyDescription: "Copia la selezione negli appunti.",
        cutDescription: "Copia la selezione, poi la rimuove.",
        pasteDescription: "Sostituisce la selezione con il contenuto degli appunti.",
        deleteDescription: "Rimuove la selezione senza copiarla.",
        pastePlainDescription: "Lo stesso, ma rimuove prima font, colori e link.",
        uppercaseDescription: "Converte la selezione in maiuscolo.",
        lowercaseDescription: "Converte la selezione in minuscolo.",
        capitalizeDescription: "Rende maiuscola l'iniziale di ogni parola della selezione.",
        removeSpacesDescription: "Rimuove tutti gli spazi dalla selezione.",
        underscoreDescription: "Sostituisce gli spazi con trattini bassi.",
        joinLinesDescription: "Unisce più righe in una sola.",
        commaListDescription: "Unisce righe o parole in un elenco separato da virgole.",
        sortDescription: "Ordina righe, parole o lettere in ordine alfabetico.",
        reverseDescription: "Inverte l'ordine di righe, parole o lettere.",
        randomDescription: "Mescola righe, parole o lettere.",
        quotesDescription: "Racchiude la selezione tra virgolette.",
        bracketsDescription: "Racchiude la selezione tra parentesi.",
        urlEncodeDescription: "Codifica la selezione con percent-encoding per un URL.",
        urlDecodeDescription: "Rimuove il percent-encoding dalla selezione.",
        base64EncodeDescription: "Codifica la selezione in Base64.",
        base64DecodeDescription: "Decodifica la selezione da Base64.",
        calculateDescription: "Valuta la selezione come espressione matematica.",
        addToScratchpadDescription: "Aggiunge la selezione al Blocco Note."
    )

    static let ja = SelectionActionsStrings(
        pageTitle: "選択アクション",
        hubDescription: "選択したテキストに対するクイックアクション",
        enableToggleTitle: "選択アクションを有効にする",
        enableToggleCaption: "どのアプリでもテキストを選択すると、近くに小さなツールバーを表示します",
        displayStyleLabel: "アクションの表示形式",
        displayStyleIcon: "アイコン",
        displayStyleWord: "文字",
        maxVisibleLabel: "表示する最大数",
        maxVisibleCaption: "残りはバー内の▾にまとめられます",
        permissionTitle: "アクセシビリティのアクセスが必要です",
        permissionBody: "選択アクションは選択したテキストを読み取り、置き換えることがあるため、アクセシビリティへのアクセスが必要です。",
        permissionButton: "アクセスを許可",
        actionsSectionTitle: "アクション",
        actionsSectionCaption: "ドラッグして並べ替えられます。現在の選択に該当するアクションのみバーに表示されます。",
        excludedSectionTitle: "除外",
        excludedAppsTitle: "App",
        excludedAppsCaption: "選択アクションはこれらのAppでは表示されません。",
        excludedAppsAddButton: "Appを追加…",
        excludedAppsRemoveButton: "削除",
        excludedDomainsTitle: "Webサイト",
        excludedDomainsCaption: "1行に1サイト。Safari、Chrome、Edge、Brave、Firefoxで動作します — 他のブラウザではページのアドレスを取得できない場合があります。",
        excludedDomainsPlaceholder: "example.com",
        excludedDomainsAddButton: "追加",
        excludedDomainsRemoveButton: "削除",
        copyTitle: "コピー",
        cutTitle: "カット",
        pasteTitle: "ペースト",
        deleteTitle: "削除",
        pastePlainTitle: "プレーンテキストとしてペースト",
        uppercaseTitle: "大文字",
        lowercaseTitle: "小文字",
        capitalizeTitle: "先頭を大文字に",
        removeSpacesTitle: "余分な空白を削除",
        underscoreTitle: "アンダースコア",
        joinLinesTitle: "行を結合",
        commaListTitle: "カンマ区切りリスト",
        sortTitle: "並べ替え",
        reverseTitle: "反転",
        randomTitle: "ランダム",
        quotesTitle: "引用符",
        bracketsTitle: "括弧",
        urlEncodeTitle: "URLエンコード",
        urlDecodeTitle: "URLデコード",
        base64EncodeTitle: "Base64エンコード",
        base64DecodeTitle: "Base64デコード",
        calculateTitle: "計算",
        addToScratchpadTitle: "メモ帳に追加",
        copyDescription: "選択範囲をクリップボードにコピーします。",
        cutDescription: "選択範囲をコピーしてから削除します。",
        pasteDescription: "選択範囲をクリップボードの内容で置き換えます。",
        deleteDescription: "選択範囲をコピーせずに削除します。",
        pastePlainDescription: "同様の動作ですが、先にフォント・色・リンクを取り除きます。",
        uppercaseDescription: "選択範囲を大文字に変換します。",
        lowercaseDescription: "選択範囲を小文字に変換します。",
        capitalizeDescription: "選択範囲の各単語の先頭を大文字にします。",
        removeSpacesDescription: "選択範囲のすべての空白を削除します。",
        underscoreDescription: "空白をアンダースコアに置き換えます。",
        joinLinesDescription: "複数行を1行に結合します。",
        commaListDescription: "行または単語をカンマ区切りのリストに結合します。",
        sortDescription: "行・単語・文字をアルファベット順に並べ替えます。",
        reverseDescription: "行・単語・文字の順序を反転します。",
        randomDescription: "行・単語・文字をシャッフルします。",
        quotesDescription: "選択範囲を引用符で囲みます。",
        bracketsDescription: "選択範囲を括弧で囲みます。",
        urlEncodeDescription: "選択範囲をURL用にパーセントエンコードします。",
        urlDecodeDescription: "選択範囲のパーセントエンコードを解除します。",
        base64EncodeDescription: "選択範囲をBase64にエンコードします。",
        base64DecodeDescription: "選択範囲をBase64からデコードします。",
        calculateDescription: "選択範囲を数式として計算します。",
        addToScratchpadDescription: "選択範囲をメモ帳に追加します。"
    )

    static let ko = SelectionActionsStrings(
        pageTitle: "선택 항목 작업",
        hubDescription: "선택한 텍스트에 대한 빠른 작업",
        enableToggleTitle: "선택 항목 작업 사용",
        enableToggleCaption: "어떤 앱에서든 텍스트를 선택하면 작은 도구 모음을 표시합니다",
        displayStyleLabel: "작업 표시 방식",
        displayStyleIcon: "아이콘",
        displayStyleWord: "단어",
        maxVisibleLabel: "최대 표시 개수",
        maxVisibleCaption: "나머지는 도구 모음의 ▾ 안에 모입니다",
        permissionTitle: "손쉬운 사용 접근 권한 필요",
        permissionBody: "선택 항목 작업은 선택한 텍스트를 읽고 바꿀 수 있으며, 이를 위해 손쉬운 사용 접근 권한이 필요합니다.",
        permissionButton: "접근 허용",
        actionsSectionTitle: "작업",
        actionsSectionCaption: "드래그하여 순서를 바꿀 수 있습니다. 현재 선택 항목에 해당하는 작업만 도구 모음에 표시됩니다.",
        excludedSectionTitle: "제외",
        excludedAppsTitle: "앱",
        excludedAppsCaption: "선택 항목 작업은 이 앱들에서 나타나지 않습니다.",
        excludedAppsAddButton: "앱 추가…",
        excludedAppsRemoveButton: "제거",
        excludedDomainsTitle: "웹사이트",
        excludedDomainsCaption: "한 줄에 하나씩 입력하세요. Safari, Chrome, Edge, Brave, Firefox에서 작동하며, 다른 브라우저는 페이지 주소를 알려주지 않을 수 있습니다.",
        excludedDomainsPlaceholder: "example.com",
        excludedDomainsAddButton: "추가",
        excludedDomainsRemoveButton: "제거",
        copyTitle: "복사",
        cutTitle: "잘라내기",
        pasteTitle: "붙여넣기",
        deleteTitle: "삭제",
        pastePlainTitle: "일반 텍스트로 붙여넣기",
        uppercaseTitle: "대문자",
        lowercaseTitle: "소문자",
        capitalizeTitle: "첫 글자 대문자",
        removeSpacesTitle: "공백 제거",
        underscoreTitle: "밑줄",
        joinLinesTitle: "줄 합치기",
        commaListTitle: "쉼표 목록",
        sortTitle: "정렬",
        reverseTitle: "반전",
        randomTitle: "무작위",
        quotesTitle: "따옴표",
        bracketsTitle: "괄호",
        urlEncodeTitle: "URL 인코딩",
        urlDecodeTitle: "URL 디코딩",
        base64EncodeTitle: "Base64 인코딩",
        base64DecodeTitle: "Base64 디코딩",
        calculateTitle: "계산",
        addToScratchpadTitle: "메모장에 추가",
        copyDescription: "선택 항목을 클립보드에 복사합니다.",
        cutDescription: "선택 항목을 복사한 후 제거합니다.",
        pasteDescription: "선택 항목을 클립보드 내용으로 바꿉니다.",
        deleteDescription: "선택 항목을 복사하지 않고 제거합니다.",
        pastePlainDescription: "동일하지만 글꼴, 색상, 링크를 먼저 제거합니다.",
        uppercaseDescription: "선택 항목을 대문자로 변환합니다.",
        lowercaseDescription: "선택 항목을 소문자로 변환합니다.",
        capitalizeDescription: "선택 항목의 각 단어 첫 글자를 대문자로 만듭니다.",
        removeSpacesDescription: "선택 항목의 모든 공백을 제거합니다.",
        underscoreDescription: "공백을 밑줄로 바꿉니다.",
        joinLinesDescription: "여러 줄을 한 줄로 합칩니다.",
        commaListDescription: "줄 또는 단어를 쉼표로 구분된 목록으로 합칩니다.",
        sortDescription: "줄, 단어 또는 글자를 알파벳순으로 정렬합니다.",
        reverseDescription: "줄, 단어 또는 글자의 순서를 반전합니다.",
        randomDescription: "줄, 단어 또는 글자를 무작위로 섞습니다.",
        quotesDescription: "선택 항목을 따옴표로 감쌉니다.",
        bracketsDescription: "선택 항목을 괄호로 감쌉니다.",
        urlEncodeDescription: "URL용으로 선택 항목을 퍼센트 인코딩합니다.",
        urlDecodeDescription: "선택 항목의 퍼센트 인코딩을 제거합니다.",
        base64EncodeDescription: "선택 항목을 Base64로 인코딩합니다.",
        base64DecodeDescription: "선택 항목을 Base64에서 디코딩합니다.",
        calculateDescription: "선택 항목을 수식으로 계산합니다.",
        addToScratchpadDescription: "선택 항목을 메모장에 추가합니다."
    )

    static let zhHans = SelectionActionsStrings(
        pageTitle: "选择操作",
        hubDescription: "对任意选中文本执行快捷操作",
        enableToggleTitle: "启用选择操作",
        enableToggleCaption: "在任意应用中选中文本时，在旁边显示一个小工具栏",
        displayStyleLabel: "操作显示方式",
        displayStyleIcon: "图标",
        displayStyleWord: "文字",
        maxVisibleLabel: "最多显示",
        maxVisibleCaption: "其余操作会收进工具栏中的 ▾",
        permissionTitle: "需要辅助功能权限",
        permissionBody: "选择操作会读取所选文本并可能替换它，这需要辅助功能权限。",
        permissionButton: "授予权限",
        actionsSectionTitle: "操作",
        actionsSectionCaption: "拖动即可重新排序。工具栏中只显示适用于当前选中内容的操作。",
        excludedSectionTitle: "排除项",
        excludedAppsTitle: "应用",
        excludedAppsCaption: "选择操作永远不会在这些应用中出现。",
        excludedAppsAddButton: "添加应用…",
        excludedAppsRemoveButton: "移除",
        excludedDomainsTitle: "网站",
        excludedDomainsCaption: "每行一个网站。适用于 Safari、Chrome、Edge、Brave 和 Firefox — 其他浏览器可能无法报告网页地址。",
        excludedDomainsPlaceholder: "example.com",
        excludedDomainsAddButton: "添加",
        excludedDomainsRemoveButton: "移除",
        copyTitle: "拷贝",
        cutTitle: "剪切",
        pasteTitle: "粘贴",
        deleteTitle: "删除",
        pastePlainTitle: "粘贴为纯文本",
        uppercaseTitle: "大写",
        lowercaseTitle: "小写",
        capitalizeTitle: "首字母大写",
        removeSpacesTitle: "移除多余空格",
        underscoreTitle: "下划线",
        joinLinesTitle: "合并行",
        commaListTitle: "逗号列表",
        sortTitle: "排序",
        reverseTitle: "反转",
        randomTitle: "随机",
        quotesTitle: "引号",
        bracketsTitle: "括号",
        urlEncodeTitle: "URL 编码",
        urlDecodeTitle: "URL 解码",
        base64EncodeTitle: "Base64 编码",
        base64DecodeTitle: "Base64 解码",
        calculateTitle: "计算",
        addToScratchpadTitle: "添加到便签",
        copyDescription: "将所选内容复制到剪贴板。",
        cutDescription: "先复制所选内容，再将其移除。",
        pasteDescription: "用剪贴板内容替换所选内容。",
        deleteDescription: "移除所选内容但不复制。",
        pastePlainDescription: "效果相同，但会先去除字体、颜色和链接。",
        uppercaseDescription: "将所选内容转换为大写。",
        lowercaseDescription: "将所选内容转换为小写。",
        capitalizeDescription: "将所选内容中每个单词的首字母大写。",
        removeSpacesDescription: "移除所选内容中的所有空格。",
        underscoreDescription: "用下划线替换空格。",
        joinLinesDescription: "将多行合并为一行。",
        commaListDescription: "将各行或各词合并为逗号分隔的列表。",
        sortDescription: "按字母顺序对行、词或字母排序。",
        reverseDescription: "反转行、词或字母的顺序。",
        randomDescription: "打乱行、词或字母的顺序。",
        quotesDescription: "用引号将所选内容括起来。",
        bracketsDescription: "用括号将所选内容括起来。",
        urlEncodeDescription: "为 URL 对所选内容进行百分号编码。",
        urlDecodeDescription: "移除所选内容中的百分号编码。",
        base64EncodeDescription: "将所选内容编码为 Base64。",
        base64DecodeDescription: "将所选内容从 Base64 解码。",
        calculateDescription: "将所选内容作为数学表达式计算。",
        addToScratchpadDescription: "将所选内容添加到便签。"
    )

    static let zhTW = SelectionActionsStrings(
        pageTitle: "選取操作",
        hubDescription: "對任意選取的文字執行快速操作",
        enableToggleTitle: "啟用選取操作",
        enableToggleCaption: "在任何 App 中選取文字時，於旁邊顯示一個小工具列",
        displayStyleLabel: "操作顯示方式",
        displayStyleIcon: "圖示",
        displayStyleWord: "文字",
        maxVisibleLabel: "最多顯示",
        maxVisibleCaption: "其餘操作會收進工具列中的 ▾",
        permissionTitle: "需要輔助使用權限",
        permissionBody: "選取操作會讀取所選文字並可能取代它，這需要輔助使用權限。",
        permissionButton: "授予權限",
        actionsSectionTitle: "操作",
        actionsSectionCaption: "拖曳即可重新排序。工具列中只會顯示適用於目前選取內容的操作。",
        excludedSectionTitle: "排除項目",
        excludedAppsTitle: "App",
        excludedAppsCaption: "選取操作永遠不會在這些 App 中出現。",
        excludedAppsAddButton: "新增 App…",
        excludedAppsRemoveButton: "移除",
        excludedDomainsTitle: "網站",
        excludedDomainsCaption: "每行一個網站。適用於 Safari、Chrome、Edge、Brave 和 Firefox — 其他瀏覽器可能無法回報網頁位址。",
        excludedDomainsPlaceholder: "example.com",
        excludedDomainsAddButton: "新增",
        excludedDomainsRemoveButton: "移除",
        copyTitle: "拷貝",
        cutTitle: "剪下",
        pasteTitle: "貼上",
        deleteTitle: "刪除",
        pastePlainTitle: "貼上為純文字",
        uppercaseTitle: "大寫",
        lowercaseTitle: "小寫",
        capitalizeTitle: "首字母大寫",
        removeSpacesTitle: "移除多餘空格",
        underscoreTitle: "底線",
        joinLinesTitle: "合併行",
        commaListTitle: "逗號清單",
        sortTitle: "排序",
        reverseTitle: "反轉",
        randomTitle: "隨機",
        quotesTitle: "引號",
        bracketsTitle: "括號",
        urlEncodeTitle: "URL 編碼",
        urlDecodeTitle: "URL 解碼",
        base64EncodeTitle: "Base64 編碼",
        base64DecodeTitle: "Base64 解碼",
        calculateTitle: "計算",
        addToScratchpadTitle: "新增到便箋",
        copyDescription: "將所選內容複製到剪貼簿。",
        cutDescription: "先複製所選內容，再將其移除。",
        pasteDescription: "用剪貼簿內容取代所選內容。",
        deleteDescription: "移除所選內容但不複製。",
        pastePlainDescription: "效果相同，但會先移除字型、顏色和連結。",
        uppercaseDescription: "將所選內容轉換為大寫。",
        lowercaseDescription: "將所選內容轉換為小寫。",
        capitalizeDescription: "將所選內容中每個單字的首字母大寫。",
        removeSpacesDescription: "移除所選內容中的所有空格。",
        underscoreDescription: "用底線取代空格。",
        joinLinesDescription: "將多行合併為一行。",
        commaListDescription: "將各行或各詞合併為以逗號分隔的清單。",
        sortDescription: "依字母順序將行、詞或字母排序。",
        reverseDescription: "反轉行、詞或字母的順序。",
        randomDescription: "打亂行、詞或字母的順序。",
        quotesDescription: "用引號將所選內容括起來。",
        bracketsDescription: "用括號將所選內容括起來。",
        urlEncodeDescription: "為 URL 對所選內容進行百分比編碼。",
        urlDecodeDescription: "移除所選內容中的百分比編碼。",
        base64EncodeDescription: "將所選內容編碼為 Base64。",
        base64DecodeDescription: "將所選內容從 Base64 解碼。",
        calculateDescription: "將所選內容作為數學運算式計算。",
        addToScratchpadDescription: "將所選內容新增到便箋。"
    )

    static let zhHK = SelectionActionsStrings(
        pageTitle: "選取操作",
        hubDescription: "對任意選取的文字執行快速操作",
        enableToggleTitle: "啟用選取操作",
        enableToggleCaption: "在任何 App 中選取文字時，於旁邊顯示一個小工具列",
        displayStyleLabel: "操作顯示方式",
        displayStyleIcon: "圖示",
        displayStyleWord: "文字",
        maxVisibleLabel: "最多顯示",
        maxVisibleCaption: "其餘操作會收進工具列中的 ▾",
        permissionTitle: "需要輔助使用權限",
        permissionBody: "選取操作會讀取所選文字並可能取代它，這需要輔助使用權限。",
        permissionButton: "授予權限",
        actionsSectionTitle: "操作",
        actionsSectionCaption: "拖曳即可重新排序。工具列中只會顯示適用於目前選取內容的操作。",
        excludedSectionTitle: "排除項目",
        excludedAppsTitle: "App",
        excludedAppsCaption: "選取操作永遠不會在這些 App 中出現。",
        excludedAppsAddButton: "新增 App…",
        excludedAppsRemoveButton: "移除",
        excludedDomainsTitle: "網站",
        excludedDomainsCaption: "每行一個網站。適用於 Safari、Chrome、Edge、Brave 和 Firefox — 其他瀏覽器可能無法回報網頁位址。",
        excludedDomainsPlaceholder: "example.com",
        excludedDomainsAddButton: "新增",
        excludedDomainsRemoveButton: "移除",
        copyTitle: "拷貝",
        cutTitle: "剪下",
        pasteTitle: "貼上",
        deleteTitle: "刪除",
        pastePlainTitle: "貼上為純文字",
        uppercaseTitle: "大寫",
        lowercaseTitle: "小寫",
        capitalizeTitle: "首字母大寫",
        removeSpacesTitle: "移除多餘空格",
        underscoreTitle: "底線",
        joinLinesTitle: "合併行",
        commaListTitle: "逗號清單",
        sortTitle: "排序",
        reverseTitle: "反轉",
        randomTitle: "隨機",
        quotesTitle: "引號",
        bracketsTitle: "括號",
        urlEncodeTitle: "URL 編碼",
        urlDecodeTitle: "URL 解碼",
        base64EncodeTitle: "Base64 編碼",
        base64DecodeTitle: "Base64 解碼",
        calculateTitle: "計算",
        addToScratchpadTitle: "新增到便箋",
        copyDescription: "將所選內容複製到剪貼簿。",
        cutDescription: "先複製所選內容，再將其移除。",
        pasteDescription: "用剪貼簿內容取代所選內容。",
        deleteDescription: "移除所選內容但不複製。",
        pastePlainDescription: "效果相同，但會先移除字型、顏色和連結。",
        uppercaseDescription: "將所選內容轉換為大寫。",
        lowercaseDescription: "將所選內容轉換為小寫。",
        capitalizeDescription: "將所選內容中每個單字的首字母大寫。",
        removeSpacesDescription: "移除所選內容中的所有空格。",
        underscoreDescription: "用底線取代空格。",
        joinLinesDescription: "將多行合併為一行。",
        commaListDescription: "將各行或各詞合併為以逗號分隔的清單。",
        sortDescription: "依字母順序將行、詞或字母排序。",
        reverseDescription: "反轉行、詞或字母的順序。",
        randomDescription: "打亂行、詞或字母的順序。",
        quotesDescription: "用引號將所選內容括起來。",
        bracketsDescription: "用括號將所選內容括起來。",
        urlEncodeDescription: "為 URL 對所選內容進行百分比編碼。",
        urlDecodeDescription: "移除所選內容中的百分比編碼。",
        base64EncodeDescription: "將所選內容編碼為 Base64。",
        base64DecodeDescription: "將所選內容從 Base64 解碼。",
        calculateDescription: "將所選內容作為數學運算式計算。",
        addToScratchpadDescription: "將所選內容新增到便箋。"
    )
}
