// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Українська.
extension FeatureHubStrings {
    static let uk = FeatureHubStrings(
        pageTitle: "Функції",
        intro: "Встановлюйте лише те, чим користуєтесь. Усе видалене зникає з усієї програми та перестає завантажуватися.",
        tabFeatures: "Функції",
        tabPermissions: "Дозволи",
        activeCountFormat: "Встановлено %1$d з %2$d функцій",
        monitorAllOffNote: "Коли все вимкнено, Монітор зникає з панелі та рядка меню.",
        titleDockClick: "Клацання по Dock",
        titleMouseNavigation: "Бокові кнопки",
        titleMusicBlock: "Блокувальник програми Музика",
        groupWindowsDock: "Вікна та Dock",
        groupMouseKeyboard: "Миша та клавіатура",
        groupClipboardFiles: "Буфер обміну та файли",
        groupSound: "Звук",
        groupEnergyDisplay: "Живлення та дисплей",
        groupTools: "Інструменти",
        groupMonitor: "Системний монітор",
        permissionsIntro: "Що робить кожен дозвіл та які функції його використовують. Інший доступ запитується лише при використанні.",
        usedByFormat: "Використовується: %@",
        usedByNone: "Зараз ніщо з увімкненого не використовує цей дозвіл.",
        unusedBanner: "Ви надали цей дозвіл, але ніщо з увімкненого його не потребує. За бажанням відкличте його в Системних налаштуваннях.",
        statusGranted: "Надано",
        statusMissing: "Не надано",
        statusUnknown: "Програма не може це перевірити",
        requestButton: "Запитати",
        openSystemSettings: "Відкрити Системні налаштування",
        permAccessibility: "Універсальний доступ",
        permScreenRecording: "Запис екрана",
        permFullDisk: "Повний доступ до диска",
        permFilesAndFolders: "Файли та папки",
        permNotifications: "Сповіщення",
        permAutomationFinder: "Автоматизація Finder",
        permAutomationTerminal: "Автоматизація Термінала",
        permAudioCapture: "Звук програм",
        explainAccessibility: "Дозволяє функціям реагувати на клацання та клавіші та переміщати вікна.",
        explainScreenRecording: "Дозволяє функціям показувати мініатюри вікон та читати текст на екрані.",
        explainFullDisk: "Дозволяє очищувачу та деінсталятору знаходити залишки файлів всюди.",
        explainFilesAndFolders: "Дозволяє очищенню завантажень WhatsApp та експериментальному органайзеру перевіряти папку «Завантаження».",
        explainNotifications: "Дозволяє програмі сповіщати вас про увімкнені оповіщення.",
        explainAutomationFinder: "Дозволяє програмі просити Finder переміщати файли за вас.",
        explainAutomationTerminal: "Дозволяє командам Homebrew відкриватися в Терміналі.",
        explainAudioCapture: "Дозволяє мікшеру налаштовувати гучність кожної програми.",
        descSwitcher: "Перемикайте програми та вікна з прев'ю",
        descDockPreview: "Прев'ю вікон при наведенні на Dock",
        descDockClick: "Клац по значку Dock згортає або перемикає вікна",
        descWindowMaximizer: "Зелена кнопка розгортає замість повного екрана",
        descWindowLayout: "Розставляйте вікна поєднаннями клавіш або прилипанням до країв, потім коригуйте перетягуванням",
        descAutoQuit: "Закривати програми, коли закривається їхнє останнє вікно",
        descScrollInverter: "Інвертувати напрямок колеса миші",
        descSmoothScroll: "Плавна анімована прокрутка миші",
        descMouseNavigation: "Бокові кнопки миші йдуть назад та вперед",
        descMiddleClick: "Клац трьома пальцями працює як середній клац",
        descKeyboardDebounce: "Ігнорувати випадкові подвійні натискання клавіш",
        descClipboardHistory: "Зберігати локальну історію скопійованого",
        descPastePlain: "Вставляти текст без форматування",
        descFinderCutPaste: "Вирізати та вставляти файли у Finder",
        descShelf: "Кидайте файли на рядок меню, щоб зберегти їх",
        descURLCleaner: "Скопійовані посилання втрачають трекери",
        descMixer: "Повзунок гучності для кожної програми",
        descSoundOutputSwitcher: "Перемикати виходи звуку поєднанням клавіш",
        descMicMute: "Вимкнути мікрофон звідки завгодно",
        descMusicBlock: "Не давати програмі Музика запускатися самій",
        descKeepAwake: "Не давати Mac засинати на вимогу",
        descExtraBrightness: "Додаткова яскравість на XDR-дисплеях",
        descQuickLauncher: "Плаваюча панель з вашими улюбленими інструментами",
        descColorPicker: "Візьміть будь-який колір на екрані",
        descScreenOCR: "Копіюйте текст або QR-коди з чого завгодно на екрані",
        descCleaningMode: "Блокувати клавіатуру та екран для чищення",
        descMediaTools: "Стискайте відео, зображення та GIF",
        descCleaner: "Очищайте кеш та сміттєві файли",
        descUninstaller: "Видаляйте програми та їхні залишки",
        descHomebrew: "Тримайте пакети Homebrew в актуальному стані",
        descMonitorCPU: "Використання та температура процесора",
        descMonitorGPU: "Використання та температура графіки",
        descMonitorMemory: "Використання та тиск пам'яті",
        descMonitorNetwork: "Швидкість та використання мережі",
        descMonitorDisk: "Місце та активність диска",
        descMonitorPower: "Акумулятор, живлення та заряджання",
        installButton: "Встановити",
        uninstallButton: "Видалити",
        footerNote: "Видалення нічого не стирає: функція просто зникає з програми та перестає завантажуватися. Встановіть її знову, і все повернеться як було.",
        restartNote: "Функції, видалені в цій сесії, залишаються в пам'яті до перезапуску програми. Перезапустіть, щоб вивантажити їх зараз.",
        restartButton: "Перезапустити зараз",
        installAllButton: "Встановити все",
        uninstallAllButton: "Видалити все",
        presetsTitle: "Почніть з набору",
        presetsCaption: "Одне клацання налаштовує програму під ваш стиль роботи. Решта залишається доступною одним клацанням.",
        presetEssentialName: "Основне",
        presetEssentialDesc: "Мікшер гучності, системний монітор та режим без сну.",
        presetWindowsName: "Вікна",
        presetWindowsDesc: "Перемикач програм, розкладка вікон та функції Dock.",
        presetBatteryName: "Акумулятор та тиша",
        presetBatteryDesc: "Компактний монітор з акумулятором, пам'яттю та процесором. Нічого не відстежує введення.",
        presetApplyButton: "Застосувати",
        presetConfirmFormat: "Встановити набір %1$@ та видалити решту? Нічого не стирається, усе повертається одним клацанням.",
        presetConfirmApply: "Застосувати набір",
        presetConfirmCancel: "Скасувати",
        energyIdle: "Нічого в стані спокою",
        energyMouse: "Слухає мишу",
        energyPointer: "Слухає введення вказівника",
        energyKeyboard: "Слухає клавіатуру",
        energyInputs: "Слухає мишу та клавіатуру",
        energyPeriodic: "Перевіряє з інтервалом",
        energyHelp: "Що функція тримає активним, поки вона ввімкнена. Видалені функції не завантажують нічого.",
        explainAppManagement: "Дозволяє оновленням замінювати або видаляти програми, встановлені через менеджер пакетів.",
        onboardingSelectedPermissionsTitle: "Дозволи для вашого вибору",
        onboardingNoSelectedPermissions: "Вам не потрібно надавати жодних дозволів для завершення налаштування.",
        onboardingOtherPermissionsTitle: "Інші дозволи",
        onboardingOtherPermissionsCaption: "Необов'язково. Надайте їх зараз або пізніше, коли функція їх потребуватиме."
    )
}
