// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

extension SettingsCategoryStrings {
    static let uk = SettingsCategoryStrings(
        essentials: "Основне",
        windowsControls: "Керування вікнами",
        files: "Файли",
        utilities: "Утиліти",
        app: "Програма",
        appManagement: "Керування програмами"
    )
}

extension ClipboardFeatureStrings {
    static let uk = ClipboardFeatureStrings(
        title: "Буфер обміну",
        enable: "Зберігати історію буфера обміну",
        caption: "Зберігає скопійований текст, щоб ви могли використати його пізніше. Все залишається локальним і може бути очищене будь-коли.",
        localNote: "Все залишається на цьому Mac. Дуже великі елементи ігноруються.",
        skipSensitive: "Пропускати текст, схожий на конфіденційний",
        skipSensitiveCaption: "Уникає збереження коротких рядків без пробілів, схожих на паролі, токени або ключі.",
        limit: "Ліміт",
        limitUnlimited: "Без обмежень",
        showInPanel: "Показати в панелі",
        shortcut: "Клавіатурне скорочення історії",
        shortcutCaption: "Відкриває швидке вікно з пошуком, закріпленими елементами та клавіатурними скороченнями ⌘1–⌘9 для вставки в попередню програму.",
        shortcutHint: "Натисніть на рядок, щоб вставити його в попередню програму. ⌘-клац вибирає кілька; ⌘C копіює без вставки.",
        clickRowShortcut: "Натисніть рядок",
        commandClickShortcut: "⌘ Клац",
        pinned: "Закріплено",
        recent: "Недавнє",
        pin: "Закріпити",
        unpin: "Відкріпити",
        clearRecent: "Очистити недавні",
        clearAll: "Очистити незакріплене",
        empty: "Немає збереженого тексту",
        disabled: "Увімкніть історію, щоб почати зберігати скопійований текст.",
        search: "Шукати скопійований текст",
        copy: "Скопіювати",
        copied: "Скопійовано",
        delete: "Видалити елемент",
        selectMultiple: "Додати до стопки",
        unselectMultiple: "Видалити зі стопки",
        selectShortcutAction: "Вибрати",
        pasteSelectedFormat: "Вставити %d",
        copySelectedFormat: "Скопіювати %d",
        clearSelection: "Очистити вибір",
        moveUp: "Вгору",
        moveDown: "Вниз",
        noResults: "Немає результатів",
        newestFirst: "Спочатку нові",
        active: "Збереження нового тексту",
        includeImagesFiles: "Також зберігати скопійовані зображення та файли",
        includeImagesFilesCaption: "Зображення потрапляють в історію, а файли запам'ятовуються як посилання на їхнє розташування. Закріплюйте та вставляйте їх як будь-який текстовий елемент.",
        imageEntryLabel: "Зображення",
        fileCountFormat: "%d файлів",
        pasteImageAsFile: "Вставляти скопійовані зображення як файли",
        pasteImageAsFileCaption: "Коли активний Finder, ⌘V зберігає скопійоване зображення як PNG у поточній папці.",
        previewLabel: "Попередній перегляд",
        edit: "Редагувати",
        cancel: "Скасувати",
        save: "Зберегти",
        autoClearEnable: "Автоочищення буфера з затримкою",
        autoClearSecondsSuffix: "секунд",
        autoClearOnSleep: "Очищати буфер при засинанні комп'ютера",
        autoClearOnDisplaySleep: "Очищати буфер при засинанні дисплея",
        autoClearOnScreenLock: "Очищати буфер при блокуванні екрана",
        autoClearCaption: "Очищає лише системний буфер обміну. Збережені елементи залишаються в історії.",
        deleteSelectedFormat: "Видалити %d"
    )
}

extension WindowLayoutFeatureStrings {
    static let uk = WindowLayoutFeatureStrings(
        title: "Розкладка вікон",
        caption: "Розставляйте вікна у розділи екрана або переміщуйте та змінюйте їхній розмір трекпадом або мишею.",
        showInPanel: "Показати в панелі",
        gestureSection: "Перетягування вікна",
        gestureEnable: "Переміщення та зміна розміру перетягуванням",
        gestureCaption: "На трекпаді або миші утримуйте показані клавіші-модифікатори та перетягуйте в будь-якому місці всередині вікна.",
        gestureModifiers: "Клавіші для переміщення",
        gestureMove: "Перетягніть для переміщення",
        gestureResize: "Додайте Shift та перетягуйте для зміни розміру",
        gestureResizeHint: "Стартова точка обирає найближчий край або кут. На миші перетягування правою кнопкою також змінює розмір.",
        gestureRaiseWindow: "Винести перетягуване вікно на передній план",
        shortcuts: "Клавіатурні скорочення",
        shortcutsCaption: "Використовуйте глобальні поєднання для розташування активного вікна без відкриття панелі.",
        permissionCaption: "Використовує Універсальний доступ лише для переміщення та зміни розміру вікон.",
        noWindow: "Активне вікно не знайдено.",
        missingPermission: "Надайте Універсальний доступ для переміщення вікон.",
        failed: "Не вдалося перемістити це вікно.",
        done: "Вікно розташоване.",
        restored: "Вікно відновлено.",
        noRestore: "Немає попередньої розкладки для відновлення.",
        target: "Активне вікно",
        halves: "Половини",
        thirds: "Третини",
        sixths: "Шостини",
        corners: "Кути",
        other: "Дії",
        leftHalf: "Ліворуч",
        rightHalf: "Праворуч",
        topHalf: "Вгорі",
        bottomHalf: "Внизу",
        leftThird: "Ліва 1/3",
        centerThird: "Центральна 1/3",
        rightThird: "Права 1/3",
        leftTwoThirds: "Ліва 2/3",
        rightTwoThirds: "Права 2/3",
        topLeftSixth: "Вгорі ліворуч 1/6",
        topCenterSixth: "Вгорі по центру 1/6",
        topRightSixth: "Вгорі праворуч 1/6",
        bottomLeftSixth: "Внизу ліворуч 1/6",
        bottomCenterSixth: "Внизу по центру 1/6",
        bottomRightSixth: "Внизу праворуч 1/6",
        topLeft: "Вгорі ліворуч",
        topRight: "Вгорі праворуч",
        bottomLeft: "Внизу ліворуч",
        bottomRight: "Внизу праворуч",
        maximize: "Розгорнути",
        center: "Центр",
        nextDisplay: "Наступний дисплей",
        restore: "Відновити",
        fullScreen: "На весь екран",
        previousDisplay: "Попередній дисплей",
        edgeSnapEnable: "Прилипати вікнами до країв екрана",
        edgeSnapCaption: "Увімкніть це, потім перетягніть рядок заголовка вікна до будь-якого краю або кута екрана та відпустіть.",
        edgeSnapSystemConflict: "macOS використовує ті самі краї. Вимкніть мозаїку вікон у розділі «Робочий стіл і Dock», щоб Vorssaint міг керувати ними.",
        edgeSnapOpenSystemSettings: "Відкрити «Робочий стіл і Dock»",
        edgeSnapWaitingForSystem: "Увімкнено в Vorssaint. Почне працювати, щойно мозаїку macOS буде вимкнено.",
        marginMaximize: "Розгорнути з полем",
        gapsSection: "Проміжки",
        gapsCaption: "Проміжок між прилиплими вікнами та між вікнами та краєм екрана.",
        windowGap: "Проміжок між вікнами",
        screenGap: "Проміжок екрана",
        gapNone: "Немає",
        gapTiny: "Крихітний",
        gapSmall: "Малий",
        gapMedium: "Середній",
        gapLarge: "Великий",
        gapExtraLarge: "Дуже великий"
    )
}

extension MonitorAlertFeatureStrings {
    static let uk = MonitorAlertFeatureStrings(
        section: "Сповіщення",
        caption: "Сповіщення спрацьовують, коли досягаються вибрані межі. Сповіщення про використання й температуру CPU ігнорують сплески коротші за 12 секунд. Налаштування повтору обмежує лише повтори того самого сповіщення.",
        notificationsDenied: "Сповіщення Vorssaint вимкнено в Системних налаштуваннях, тому вони не можуть з'являтися.",
        cpu: "Високий CPU",
        cpuTemperature: "Висока температура CPU",
        memory: "Критичний тиск пам'яті",
        disk: "Мало місця на диску",
        battery: "Низький заряд акумулятора",
        cpuThreshold: "CPU вище",
        cpuTemperatureThreshold: "Температура вище",
        diskThreshold: "Вільного місця менше",
        batteryThreshold: "Заряд акумулятора нижче",
        cooldown: "Повторити те саме сповіщення через",
        cooldown2: "2 хвилини",
        cooldown5: "5 хвилин",
        cooldown15: "15 хвилин",
        cooldown30: "30 хвилин",
        cooldown60: "1 година",
        cpuTitle: "Високий CPU",
        cpuBodyFormat: "CPU тримався вище %d%% кілька секунд.",
        cpuTemperatureTitle: "Гарячий CPU",
        cpuTemperatureBodyFormat: "CPU досяг %d °C.",
        memoryTitle: "Критична пам'ять",
        memoryBody: "Тиск пам'яті досяг критичного рівня.",
        diskTitle: "Мало місця на диску",
        diskBodyFormat: "На %@ залишилося менше %d%%.",
        batteryTitle: "Низький заряд акумулятора",
        batteryBodyFormat: "Заряд акумулятора становить %d%%.",
        batteryTemperature: "Висока температура акумулятора",
        batteryTemperatureThreshold: "Температура вище",
        batteryTemperatureTitle: "Гарячий акумулятор",
        batteryTemperatureBodyFormat: "Акумулятор нагрівся до %d °C."
    )
}

extension MixerFeatureStrings {
    static let uk = MixerFeatureStrings(
        hideInactiveApps: "Приховувати неактивні програми"
    )
}

extension CommandBarFeatureStrings {
    static let uk = CommandBarFeatureStrings(
        pageTitle: "Панель команд",
        hubDescription: "Поле введення, щоб знайти та виконати всі функції програми",
        panelCaption: "Введіть, щоб знайти та виконати будь-яку функцію",
        settingsCaption: "Одне клавіатурне скорочення відкриває поле введення на поточному екрані. Введіть кілька літер, натисніть Return, і готово. Введене не зберігається.",
        openButton: "Відкрити панель команд зараз",
        searchPlaceholder: "Введіть, що хочете зробити",
        suggestionsLabel: "Пропозиції",
        noResultsTitle: "Цю назву не знайдено.",
        noResultsAction: "Переглянути пропозиції",
        argumentRangeFormat: "%d до %d",
        argumentHint: "Return застосувати · Esc повернутися",
        confirmHint: "Return підтвердити · Esc скасувати",
        kindApp: "Програма",
        kindClipboard: "Вставити з історії",
        kindSnippet: "Вставити сніпет",
        soundOutputSubtitle: "Перемкнути звуковий пристрій виведення",
        soundOutputCurrent: "Поточний пристрій виведення",
        volumeTitle: "Гучність",
        brightnessTitle: "Яскравість екрана",
        keepAwakeForFormat: "Не давати заснути %@",
        needsSetupFormat: "Увімкніть %@ у налаштуваннях",
        needsPermissionHint: "Потрібен дозвіл · натисніть Return для запиту",
        actionCheckAppUpdates: "Перевірити оновлення програм",
        actionCleanURL: "Очистити скопійоване посилання",
        actionOpenSettings: "Відкрити налаштування",
        answerBatteryLabel: "Акумулятор",
        answerBatteryCharging: "Заряджається",
        answerBatteryPlugged: "Підключено до живлення",
        answerMemoryLabel: "Пам'ять",
        answerMemoryFormat: "Використано %@ / %@",
        answerStorageLabel: "Сховище",
        answerStorageFormat: "Доступно %@ / %@",
        copyHint: "Return скопіювати",
        kindWindow: "Вікно",
        quitFormat: "Завершити %@",
        quitConfirmFormat: "Завершити %@?",
        kindMenu: "Команди меню",
        actionsTitle: "Дії",
        actionsHint: "Дії",
        actionPin: "Закріпити вгорі",
        actionUnpin: "Відкріпити",
        actionName: "Дати власну назву",
        actionRename: "Змінити назву, на яку відгукується",
        actionHide: "Ніколи не показувати це",
        actionForget: "Забути, як часто я це використовую",
        aliasPlaceholder: "Назва, яку ви йому даєте",
        aliasTakenFormat: "%@ вже використовує цю назву",
        sourcesTitle: "Вміст пошуку панелі команд",
        sourcesCaption: "Приховуйте те, що не хочете бачити. Ваші власні дії завжди залишаються.",
        sourceActions: "Дії Vorssaint",
        sourceApps: "Програми",
        sourceMenus: "Команди меню найпереднішої програми",
        sourceWindows: "Відкриті вікна",
        sourceQuitApps: "Завершити програму",
        sourceSettingsPages: "Сторінки налаштувань",
        sourceSnippets: "Сніпети",
        sourceClipboard: "Історія буфера обміну",
        sourceEmoji: "Емодзі",
        sourceFolders: "Папки",
        sourceAnswers: "Відповіді про цей Mac",
        sourceCalculator: "Обчислення та конвертація",
        namedTitle: "Ваші назви",
        namedEmpty: "Ще немає назв. Відкрийте панель команд, виберіть рядок і натисніть клавішу дії.",
        pinnedTitle: "Закріплено",
        pinnedEmpty: "Ще нічого не закріплено.",
        hiddenTitle: "Ніколи не показувати",
        hiddenEmpty: "Жодний елемент не приховано.",
        forgetAllButton: "Забути, що я використовую найчастіше",
        tryTheseLabel: "Спробувати",
        stillLooking: "Пошук триває…",
        removeButton: "Видалити",
        confirmButton: "Підтвердити",
        soundMute: "Без звуку",
        soundUnmute: "Відновити звук",
        stateOn: "Ввімкнено",
        powerSleep: "Сон",
        powerRestart: "Перезавантажити",
        powerRestartConfirm: "Перезавантажити?",
        powerShutDown: "Вимкнути",
        powerShutDownConfirm: "Вимкнути Mac?",
        powerLogOut: "Вийти",
        powerLogOutConfirm: "Вийти?",
        wifiOn: "Увімкнути Wi-Fi",
        wifiOff: "Вимкнути Wi-Fi",
        kindEmoji: "Емодзі",
        kindFolder: "Папка",
        answerDateLabel: "Сьогодні",
        answerTimeLabel: "Поточний час",
        kindAnswer: "Відповідь",
        kindSelection: "Виділення",
        selectedTitle: "Вибрано",
        selectionCopy: "Копіювати",
        selectionSearch: "Для пошуку",
        selectionUpper: "Усе великими літерами",
        selectionLower: "Усе малими літерами",
        selectionTitleCase: "Великі перші літери",
        selectionShelf: "Покласти на полицю",
        selectionCount: "Статистика",
        selectionCountFormat: "%d слів, %d символів",
        sourceSelection: "Вибраний вміст",
        kindLink: "Швидка дія",
        linkSearchHint: "Після назви введіть що шукати",
        linksTitle: "Ваші швидкі дії",
        linksEmpty: "Поки порожньо. Додайте сайт, папку, пошук або скрипт, що використовуєте щодня.",
        linkDestinationLabel: "Куди йти",
        linkKindLink: "Сайт або посилання",
        linkKindPlace: "Папка або файл",
        linkPlaceholdersHint: "Додайте один, він автоматично заповниться при відкритті",
        placeholderQuery: "Те, що ви ввели",
        placeholderClipboard: "Те, що ви скопіювали",
        placeholderSelection: "Вибраний вміст",
        placeholderDate: "Сьогодні",
        privacyNote: "Все виконується на цьому Mac: без облікового запису, без хмари, нічого не передається назовні.",
        actionShortcut: "Встановити клавіатурне скорочення",
        actionShortcutChange: "Змінити клавіатурне скорочення",
        actionShortcutRemove: "Прибрати клавіатурне скорочення",
        shortcutCaptureHint: "Натисніть бажану клавішу · Delete очищає · Esc повертає",
        rowShortcutsTitle: "Елементи із власними клавіатурними скороченнями",
        rowShortcutsEmpty: "Ще немає елементів із клавіатурними скороченнями. Відкрийте будь-який елемент, щоб задати клавіатурне скорочення.",
        turnOnFormat: "Увімкнути %@",
        turnOffFormat: "Вимкнути %@",
        everythingTitle: "Усе, що вона може",
        categoryAll: "Усе",
        restartAppFormat: "Перезапустити %@",
        forceQuitAppFormat: "Примусово завершити %@…",
        forceQuitAppConfirmFormat: "Примусово завершити %@? Незбережені зміни будуть втрачені.",
        uninstallAppFormat: "Видалити %@…",
        openInBrowser: "Відкрити в браузері",
        linkKindScript: "Скрипт",
        scriptHint: "Виберіть виконуваний файл. Введіть назву, потім вміст для надсилання. Результати з'являться тут, щойно ви припините введення.",
        scriptRunsWithoutArgument: "Виконувати й при введенні лише назви",
        scriptRunFailed: "Не вдалося виконати цей файл",
        scriptSearchHint: "Після назви введіть вміст для надсилання",
        scriptBareSearchHint: "Можна виконати одразу або ввести вміст для надсилання",
        linkAddButton: "Додати швидку дію",
        positionCaption: "Перетягніть логотип ліворуч від поля введення, щоб розмістити панель команд у будь-якому місці екрана; двічі клацніть логотип, щоб повернути її до центру.",
        resetPositionButton: "Відцентрувати панель команд",
        shortcutToggle: "Глобальне клавіатурне скорочення панелі команд",
        dragHint: "Перетягніть для переміщення · двічі клацніть, щоб відцентрувати",
        actionRevealInFinder: "Показати у Finder",
        sourceMacSettings: "Панелі Системних налаштувань",
        sourceFiles: "Файли",
        filesTitle: "Пошук у файлах",
        filesCaption: "Виберіть папку для пошуку; під час введення файли знаходитимуться за назвою. Без індексування та дозволів: використовується власний пошук Mac, показується лише те, що ви бачите у Finder.",
        filesEmpty: "Ще немає папок, тому файли не шукаються.",
        filesAddFolder: "Додати папку",
        filesIgnoreCaption: "Назви, які ніколи не показуються: повна назва папки або файлу, або розширення, як *.log.",
        filesIgnorePlaceholder: "Назва папки або файлу",
        filesIgnoreAdd: "Додати",
        compactModeToggle: "Компактний режим",
        compactModeCaption: "Панель відкривається без пропозицій. Результати з’являються під час введення."
    )
}
