// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Polish catalog.
extension Strings {
    static let pl = Strings(
        statusIdleTooltip: "Vorssaint: normalne usypianie",
        statusActiveUntil: "Vorssaint: nie usypiaj do",
        statusActiveIndefinite: "Vorssaint: usypianie wyłączone",
        menuEnableAwake: "Włącz tryb „Nie usypiaj”",
        menuDisableAwake: "Wyłącz tryb „Nie usypiaj”",
        menuActivateFor: "Włącz na…",
        menuSettings: "Ustawienia…",
        menuAbout: "O Vorssaint",
        menuQuit: "Zakończ Vorssaint",
        menuHide: "Ukryj Vorssaint",
        menuHideOthers: "Ukryj pozostałe",
        menuShowAll: "Pokaż wszystkie",
        menuEdit: "Edytuj",
        menuUndo: "Cofnij",
        menuRedo: "Ponów",
        actionClear: "Wyczyść",
        actionRemove: "Usuń",
        actionBack: "Wstecz",
        actionSearch: "Szukaj",
        actionMute: "Wycisz",
        actionUnmute: "Wyłącz wyciszenie",
        actionPlay: "Odtwórz",
        actionPause: "Wstrzymaj",
        menuCut: "Wytnij",
        menuCopy: "Kopiuj",
        menuPaste: "Wklej",
        menuSelectAll: "Zaznacz wszystko",
        menuWindow: "Okno",
        menuMinimize: "Minimalizuj",
        menuZoom: "Powiększ",
        menuClose: "Zamknij",

        minutes15: "15 minut",
        minutes30: "30 minut",
        hour1: "1 godzina",
        hours2: "2 godziny",
        hours4: "4 godziny",
        hours8: "8 godzin",
        indefinitely: "Bez ograniczeń",
        indefinite: "Bez ograniczeń",

        panelSettings: "Ustawienia",
        panelQuit: "Zakończ",
        panelHotkeyHint: "Przełącz skrótem",

        keepAwakeTitle: "Nie usypiaj",
        keepAwakeEndsIn: "Koniec za",
        keepAwakeUntilDisabled: "Aktywne do wyłączenia",
        keepAwakeNormalRules: "Mac korzysta ze standardowych ustawień oszczędzania energii",
        keepAwakeUntilLabel: "Do",
        keepAwakeUntilStart: "Rozpocznij",
        keepAwakeOptions: "Opcje",
        keepAwakeMouseJiggle: "Przesuń nieznacznie wskaźnik",
        keepAwakeMouseJiggleCaption: "Podczas sesji przesuwa nieco wskaźnik w wybranym odstępie czasu.",
        keepAwakeMouseJiggleInterval: "Interwał",
        keepAwakeActiveIconLabel: "Aktywna ikona",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Kawa",
        keepAwakeActiveIconEye: "Oko",
        keepAwakeActiveIconMoon: "Księżyc",
        keepAwakeActiveIconLight: "Żarówka",
        keepAwakeIconTintLabel: "Kolor aktywnej ikony",
        keepAwakeIconTintOrange: "Pomarańczowy",
        keepAwakeIconTintGreen: "Zielony",
        keepAwakeIconTintBlue: "Niebieski",
        keepAwakeIconTintPurple: "Fioletowy",
        keepAwakeIconTintPink: "Różowy",
        keepAwakeIconTintNone: "Brak koloru",
        durationLabel: "Czas trwania",
        clamshellTitle: "Kontynuuj pracę z zamkniętą pokrywą",
        clamshellOnCaption: "Usypianie całkowicie wyłączone. Pamiętaj o zasilaniu",
        clamshellNeedsSession: "Działa, gdy tryb „Nie usypiaj” jest aktywny",
        clamshellReady: "Gotowy. Przełącza bez hasła",
        clamshellNeedsPassword: "Raz poprosi o hasło administratora",

        systemSection: "System",
        temperatures: "Temperatury",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Bateria",
        usageSection: "Użycie sprzętu",
        memorySection: "Pamięć",
        memoryPressure: "Obciążenie",
        memorySwapUsed: "Używana pamięć wymiany",
        memoryCompressed: "Skompresowana",
        memoryCachedFiles: "Pliki w pamięci podręcznej",
        pressureNormal: "Normalne",
        pressureWarning: "Podwyższone",
        pressureCritical: "Krytyczne",
        monitorUnavailable: "Czujniki niedostępne na tym komputerze Mac",
        energyAppsTitle: "Aplikacje zużywające znaczną ilość energii",
        energyAppsIdle: "Brak znaczącego zużycia energii",

        notifySessionEndedTitle: "Sesja zakończona",
        notifySessionEndedBody: "Czas minął. Komputer Mac znów będzie normalnie spać.",
        notifyBatteryTitle: "Vorssaint wyłączone",
        notifyBatteryBody: "Niski poziom baterii. Przywrócono normalne usypianie, aby oszczędzać energię.",
        adminPromptClamshellOn: "Vorssaint potrzebuje Twojego hasła, aby Mac mógł działać przy zamkniętej pokrywie.",
        adminPromptClamshellOff: "Vorssaint potrzebuje Twojego hasła, aby przywrócić normalny tryb uśpienia komputera Mac.",
        adminPromptRecover: "Vorssaint zakończył działanie przy wyłączonym usypianiu Maca. Wprowadź hasło, aby przywrócić normalne usypianie.",
        adminPromptUpdate: "Aby zainstalować aktualizację, Vorssaint potrzebuje Twojego hasła.",
        adminPromptSudoersInstall: "Vorssaint utworzy ograniczoną regułę (wyłącznie pmset disablesleep), aby przełączać tryb zamkniętej pokrywy bez pytania o hasło. Hasło jest potrzebne tylko teraz.",
        adminPromptSudoersRemove: "Vorssaint usunie regułę umożliwiającą korzystanie z trybu zamkniętej pokrywy bez hasła.",

        settingsTitle: "Ustawienia Vorssaint",
        tabGeneral: "Ogólne",
        tabEnergy: "Energia",
        tabMouse: "Mysz i gładzik",
        tabSwitcher: "Przełącznik",
        tabAdvanced: "Zaawansowane",
        tabAbout: "O aplikacji",
        tabReleaseNotes: "Co nowego",
        releaseNotesOnUpdateToggle: "Pokaż, co nowego po aktualizacji",
        minimalWindowPreviews: "Minimalne podglądy",
        minimalWindowPreviewsCaption: "Ukryj tytuły, przyciski i detale dekoracyjne w podglądzie Docka i przełącznika. Wybór pozostaje widoczny.",
        previewSizeLabel: "Rozmiar podglądu",
        previewSizeNormal: "Normalne",
        previewSizeLarge: "Duży",
        previewSizeXLarge: "Bardzo duży",
        settingsGroupFeatures: "Funkcje",
        advancedResetSection: "Uprawnienia",
        advancedResetDescription: "Usuwa wszystkie uprawnienia przyznane Vorssaint (dostępność, nagrywanie ekranu, pełny dostęp do dysku i inne), element logowania i regułę zamkniętej pokrywy. Przydatne do rozpoczęcia od nowa lub przed odinstalowaniem. Aplikacja pozostaje zainstalowana.",
        advancedClearButton: "Wyczyść wszystkie uprawnienia",
        advancedCleared: "Uprawnienia wyczyszczone.",
        advancedClearFailed: "Nie można usunąć niektórych uprawnień lub reguły zamkniętej pokrywy. Spróbuj ponownie i zezwól na żądanie hasła, jeśli się pojawi.",
        advancedClearConfirmTitle: "Wyczyścić wszystkie uprawnienia?",
        advancedClearConfirmBody: "Funkcje wymagające uprawnień przestaną działać, dopóki nie przyznasz ich ponownie. Twoje ustawienia zostaną zachowane.",
        advancedUninstallSection: "Odinstaluj",
        advancedUninstallDescription: "Wykonuje wszystkie powyższe czynności, następnie usuwa preferencje i przenosi Vorssaint do Kosza, nie pozostawiając nic. Aplikacja kończy działanie po zakończeniu. Możesz zainstalować ponownie w dowolnym momencie.",
        advancedUninstallButton: "Odinstaluj całkowicie Vorssaint",
        advancedUninstallConfirmTitle: "Odinstalować Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint wyczyści swoje uprawnienia, usunie preferencje i przeniesie się do Kosza, a następnie wyjdzie. Nie można tego cofnąć w aplikacji, ale plik pozostaje w Koszu, dopóki go nie opróżnisz.",
        advancedUninstallFailedTitle: "Odinstalowywanie zatrzymane",
        advancedUninstallFailedBody: "Vorssaint nie mógł przywrócić zmienionych ustawień systemowych: uśpienia, prędkości wentylatora, przyspieszenia myszy lub kolejności przestrzeni. Nic nie zostało usunięte. Spróbuj ponownie i zezwól na żądanie hasła, jeśli się pojawi.",

        launchAtLogin: "Uruchom przy logowaniu",
        languageLabel: "Język",
        menuBarSection: "Pasek menu",
        showCountdown: "Pokaż pozostały czas obok ikony",
        globalHotkeySection: "Globalny skrót",
        hotkeyToggle: "Włącz skrót trybu „Nie usypiaj”",
        hotkeyCaption: "Działa w dowolnej aplikacji, bez dodatkowych uprawnień.",

        sessionSection: "Sesja",
        defaultDurationLabel: "Domyślny czas trwania",
        keepAwakeAutoStart: "Włącz „Nie usypiaj” po uruchomieniu Vorssaint",
        keepAwakeAutoStartCaption: "Rozpoczyna sesję z domyślnym czasem trwania.",
        batteryProtectionSection: "Ochrona baterii",
        batteryDisableBelow: "Wyłącz, gdy poziom naładowania baterii spadnie poniżej",
        batteryNever: "Nigdy",
        batteryProtectionCaption: "Chroni zapomnianą sesję przed wyczerpaniem baterii MacBooka.",
        clamshellSection: "Zamknięta pokrywa",
        configuring: "Konfiguruję…",
        sudoersFailed: "Nie można włączyć trybu zamkniętej pokrywy. Spróbuj ponownie.",
        clamshellExplanation: "Opcja „Kontynuuj pracę z zamkniętą pokrywą” całkowicie wyłącza usypianie, gdy tryb „Nie usypiaj” jest aktywny. Normalne usypianie zostaje automatycznie przywrócone po zakończeniu sesji lub aplikacji. Zalecane jest podłączenie zasilania.",
        dimScreenOnLidCloseTitle: "Przyciemnij wyświetlacz do zera",
        dimScreenOnLidCloseCaption: "Przyciemnia wyświetlacz po zamknięciu pokrywy i przywraca jasność po jej otwarciu.",

        scrollSection: "Przewijanie",
        invertMouseScroll: "Odwróć przewijanie myszy",
        invertMouseScrollCaption: "Odwraca kierunek kółka myszy.",
        scrollTrackpadNote: "Gładzik pozostaje nienaruszony: zapewnia naturalne przewijanie w systemie macOS.",
        scrollActiveNow: "Odwracam teraz przewijanie myszą",
        mouseNavigationActiveNow: "Przyciski boczne są teraz aktywne",
        smoothScrollName: "Płynne przewijanie",
        smoothScrollCaption: "Zamienia każdy ruch kółka myszy w krótki, delikatny ruch. Nie ma to wpływu na gładzik.",
        smoothScrollStepLabel: "Szybkość przewijania",
        mouseNavigationSection: "Nawigacja",
        mouseNavigationEnable: "Użyj przycisków bocznych, aby przejść do tyłu i do przodu",
        mouseNavigationCaption: "Zamienia przyciski Wstecz i Dalej myszy w polecenia nawigacji w Finder, przeglądarkach i kompatybilnych aplikacjach.",
        middleClickSection: "Środkowe kliknięcie gładzika",
        middleClickEnable: "Kliknięcie trzema palcami działa jak środkowy przycisk myszy",
        middleClickEnableCaption: "Naciśnięcie gładzika trzema palcami działa jak kliknięcie kółkiem myszy: otwieranie łączy w nowej karcie, zamykanie kart i wykonywanie wszystkich innych czynności, które wykonuje środkowy przycisk.",
        middleClickDragConflict: "Przeciąganie trzema palcami w systemie macOS jest włączone i wykorzystuje trzy palce, więc kliknij czterema palcami, aby kliknąć środkowym przyciskiem. Aby użyć trzech, wyłącz przeciąganie trzema palcami w Ustawieniach systemu w obszarze Dostępność, Sterowanie wskaźnikiem i Opcje gładzika.",
        middleClickNoTrackpad: "Nie można odczytać dotknięć gładzika. Podłącz obsługiwany gładzik.",
        middleClickTapPicker: "Lekkie dotknięcie również klika",
        middleClickTapOff: "Wyłączone",
        middleClickTapThreeFingers: "3 palce",
        middleClickTapFourFingers: "4 palce",
        middleClickTapCaption: "Lekkie dotknięcie taką liczbą palców, bez naciskania, powoduje również uruchomienie środkowego kliknięcia. Ślizganie nigdy się nie liczy. Jeśli stuknięcie trzema palcami w systemie macOS jest przypisane do funkcji Look Up, wyłącz ją, aby oba nie uruchomiły się jednocześnie.",
        quickToolsTab: "Szybki panel",
        quickToolShortcutToggle: "Globalny skrót",
        ocrName: "Skopiuj tekst z ekranu",
        ocrCaption: "Wybierz obszar ekranu, a rozpoznany tekst zostanie skopiowany i gotowy do wklejenia.",
        ocrCopied: "Tekst skopiowany",
        ocrNoText: "Nie znaleziono tekstu",
        colorPickerName: "Próbnik kolorów",
        colorPickerCaption: "Chwyć kolor dowolnego piksela na ekranie i skopiuj go w swoim ulubionym formacie.",
        colorPickerFormatLabel: "Skopiowany format",
        colorPickerBareHexToggle: "Kopiuj bez przedrostka #",
        colorPickerPickNow: "Wybierz kolor",
        micMuteName: "Wyciszenie mikrofonu",
        micUnmuteName: "Wyłącz wyciszenie mikrofonu",
        micMuteCaption: "Odcina mikrofon komputera Mac jednym kliknięciem lub skrótem w każdej aplikacji.",
        micMutedHUD: "Mikrofon wyciszony",
        micUnmutedHUD: "Mikrofon włączony",
        micMutePartialHUD: "Niektórych mikrofonów nie udało się wyciszyć",
        micUnmutePartialHUD: "Niektóre mikrofony są nadal wyciszone",
        micMuteMenuBarToggle: "Pokaż na pasku menu, gdy jest wyciszony",
        micMuteMenuBarCaption: "Gdy ta funkcja wycisza mikrofon, obok ikony aplikacji na pasku menu pojawia się czerwony przekreślony mikrofon.",
        pastePlainName: "Wklej jako zwykły tekst",
        pastePlainCaption: "Wkleja skopiowany tekst bez kolorów, czcionek i formatowania. Oryginał pozostaje w schowku.",
        launcherName: "Szybki panel",
        launcherCaption: "Pływający panel z Twoimi ulubionymi narzędziami, przywoływany skrótem z dowolnego miejsca.",
        launcherOpenNow: "Otwórz szybki panel",
        launcherEditHint: "Użyj przycisku dostosowywania, aby wybierać, ukrywać i przestawiać narzędzia.",
        launcherEmptyState: "Wszystkie narzędzia są ukryte. Dodaj je ponownie przyciskiem dostosowywania.",
        launcherAddSection: "Dodaj ponownie",
        launcherKeysHint: "Strzałki nawigują, Enter otwiera, 1 do 9 otwiera bezpośrednio",

        switcherSection: "Przełącznik okien",
        switcherEnable: "Użyj przełącznika Vorssaint",
        switcherEnableCaption: "Przełączaj się między aplikacjami i oknami, w tym oknami zminimalizowanymi i wieloma oknami z tej samej aplikacji.",
        switcherUsageHint: "Przytrzymaj skrót, aby nawigować; zwolnij, aby aktywować okno. Shift lub ← wraca; W zamyka okno; Q zamyka aplikację; Esc anuluje.",
        switcherNoWindows: "Żadnych otwartych okien",
        switcherIconRowMode: "Pokaż %@ z dużymi ikonami",
        switcherIconRowModeCaption: "Pokazuje jedną ikonę na aplikację, a nad nią znajduje się podgląd okna tej aplikacji.",
        switcherSimpleModeCaption: "Pokazuje ikony aplikacji i tytuły okien, bez podglądów i przechwytywania ekranu przez przełącznik.",
        switcherShortcutHintApps: "Aplikacje",
        switcherShortcutHintWindows: "Okna",
        switcherWindowShortcutCaption: "Otwiera przełącznik okien aplikacji znajdującej się na pierwszym planie. Gdy przełącznik jest otwarty, powoduje przeskakiwanie między oknami wybranej aplikacji.",
        switcherTakeOverSystemShortcuts: "Zamień macOS ⌘Tab i ⌘`",
        switcherTakeOverSystemShortcutsCaption: "Wyłącza odpowiednie skróty macOS do przełączania aplikacji i okien tylko wtedy, gdy przełącznik Vorssaint jest aktywny. Wszystkie uruchomione aplikacje pozostają dostępne.",
        switcherAppearanceDelay: "Opóźnienie pojawienia się",
        switcherAppearanceDelayCaption: "Jak długo skrót musi być przytrzymany, zanim pojawi się przełącznik.",
        switcherInstantSelection: "Natychmiastowy wybór",
        switcherInstantSelectionCaption: "Natychmiast przenosi wyróżnienie i pozycję przewijania podczas przeglądania aplikacji i okien.",
        switcherMergeTabs: "Pokaż jeden wpis na aplikację",
        switcherMergeTabsCaption: "Zwija wszystkie okna aplikacji do jednego wpisu w przełączniku, zamiast jednego wpisu w każdym oknie.",
        switcherWindowlessApps: "Aplikacje bez otwartego okna",
        switcherWindowlessAppsCaption: "Wybiera, które uruchomione aplikacje bez okna mają być wyświetlane w przełączniku.",
        switcherWindowlessAppsOff: "Nie pokazuj",
        switcherWindowlessAppsFinder: "Tylko Finder",
        switcherWindowlessAppsAll: "Wszystkie aplikacje",
        switcherNoOpenWindow: "Brak otwartego okna",
        switcherOtherDesktop: "Inny pulpit",
        dockPreviewName: "Podgląd Docka",
        dockPreviewEnable: "Podgląd okien z Docka",
        dockPreviewEnableCaption: "Najedź kursorem na otwartą aplikację w Docku, aby zobaczyć jej okna, a następnie kliknij tę, którą chcesz.",
        dockPreviewCurrentSpaceOnlyCaption: "Gdy opcja jest wyłączona, wyświetla okna ze wszystkich biurek. Wybranie okna na innym biurku przeniesie Cię do niego.",
        dockPreviewBackgroundOpacity: "Tło panelu",
        dockPreviewBackgroundOpacityCaption: "Zmniejsz go, aby zobaczyć więcej tego, co znajduje się za panelem.",
        dockPreviewBackgroundOpacityGlassCaption: "Liquid Glass jest włączone, więc przezroczystość panelu ustawia się w Ustawieniach systemowych > Wygląd.",
        dockPreviewOpenDelay: "Opóźnienie otwarcia",
        dockPreviewOpenDelayCaption: "Jak długo wskaźnik musi spoczywać na ikonie, zanim otworzy się jej panel.",
        dockPreviewQuitAppOnClose: "Zakończ aplikację za pomocą przycisku ×",
        dockPreviewQuitAppOnCloseCaption: "W Dock Preview × zamyka całą aplikację, zamiast zamykać tylko to okno.",
        dockPreviewKeepDockVisible: "Zachowaj widoczność Docka (eksperymentalnie)",
        dockPreviewKeepDockVisibleCaption: "Wstrzymuje automatyczne ukrywanie, gdy podgląd jest otwarty i przywraca je po wyjściu. Może zmieniać rozmiar okien. Jeśli działanie aplikacji zostanie przerwane, otwórz ją ponownie, aby przywrócić Dock.",
        dockPreviewOrderByCreation: "Sortuj okna według czasu utworzenia",
        dockPreviewOrderByCreationCaption: "Pokaż najpierw starsze okna, a nie te, z których korzystałeś ostatnio.",
        dockClickMinimize: "Kliknij ikonę Docku, aby zminimalizować",
        dockClickMinimizeCaption: "Okna aktywnej aplikacji minimalizują się po kliknięciu jej ikony w Docku. Kliknij ponownie, aby je przywrócić.",
        dockClickCycleWindows: "Kliknij ikonę Docku, aby przełączać okna",
        dockClickCycleWindowsCaption: "Klikaj ikonę aktywnej aplikacji w Docku, aby przełączać jej okna, podobnie jak za pomocą ⌘`.",
        dockPreviewActiveNow: "Aktywny w Docku",
        dockPreviewDockUnavailable: "Nie można odczytać elementów Docka.",
        dockPreviewAutohideBeta: "Beta. Możesz napotkać pewne błędy.",
        dockPreviewOpenWindow: "Otwórz okno",
        dockPreviewCloseWindow: "Zamknij okno",
        dockPreviewMinimizeWindow: "Minimalizuj okno",
        dockPreviewRestoreWindow: "Przywróć okno",
        dockPreviewPinPanel: "Przypnij podgląd",
        dockPreviewUnpinPanel: "Odepnij podgląd",
        dockPreviewPinned: "Przypięte",
        dockPreviewClosePanel: "Zamknij podgląd",
        dockPreviewPreviousWindow: "Poprzednie okno",
        dockPreviewNextWindow: "Następne okno",

        cutPasteName: "Wytnij i wklej",
        cutPasteEnable: "Wycinaj i wklejaj pliki w Finderze",
        cutPasteEnableCaption: "Użyj ⌘X, aby wyciąć, oraz ⌘V, aby przenieść pliki i foldery w Finderze.",
        cutPasteShowHUD: "Pokaż pływający panel",
        cutPasteShowHUDCaption: "Wyświetl pływający wskaźnik z wyciętymi plikami, gdy Finder jest aktywny.",
        cutPasteHowTitle: "Jak używać",
        cutPasteStep1: "Zaznacz elementy w Finderze i naciśnij ⌘X, aby je wyciąć.",
        cutPasteStep2: "Otwórz folder docelowy i naciśnij ⌘V, aby je tam przenieść.",
        cutPasteTextNote: "W polach tekstowych (np. przy zmianie nazwy) ⌘X i ⌘V działają normalnie.",
        cutPasteActiveNow: "Gotowe do wycinania w Finderze",
        cutPasteAutomationNote: "Przy pierwszym użyciu macOS prosi o zgodę na sterowanie Finderem.",
        cutReadyTitle: "Wytnij",
        cutReadyHint: "w folderze docelowym, aby przenieść",
        cutCancel: "Anuluj wycinanie",
        cutDoneTitle: "Przeniesiono!",
        cutMovedSingular: "Przeniesiono 1 element",
        cutMovedPluralFormat: "Przeniesiono: %d",
        cutSomeFailed: "Niektórych elementów nie udało się przenieść",
        cutMovingTitle: "Przenoszenie…",
        cutMovingCountFormat: "%d z %d",

        autoQuitName: "Zakończ przy zamykaniu",
        autoQuitEnable: "Zakończ aplikację po zamknięciu jej ostatniego okna",
        autoQuitEnableCaption: "Zamknięcie ostatniego okna aplikacji również powoduje jej zamknięcie.",
        autoQuitActiveNow: "Aktywny teraz",
        autoQuitHowTitle: "Jak to działa",
        autoQuitStep1: "Zamknij ostatnie okno aplikacji (⌘W lub czerwony przycisk).",
        autoQuitStep2: "Aplikacja kończy działanie. Okna dialogowe „Zapisać zmiany?” nadal są wyświetlane.",
        autoQuitPredictableNote: "Aplikacje, które normalnie działają bez okna, nigdy nie są zamykane.",
        autoQuitOngoingWorkNote: "Niektóre aplikacje zamykają ostatnie okno podczas kontynuowania pracy, np. rejestrator ekranu po rozpoczęciu przechwytywania. Te również są zamykane, chyba że znajdują się na liście wyjątków.",
        autoQuitExceptionsTitle: "Wyjątki",
        autoQuitExceptionsCaption: "Aplikacje na tej liście pozostają otwarte nawet bez okien.",
        autoQuitExceptionsEmpty: "Żadnych wyjątków",
        autoQuitAddApp: "Dodaj aplikację…",

        uninstallerName: "Deinstalator",
        uninstallerEnableCaption: "Usuwa aplikację wraz z pamięciami podręcznymi, preferencjami, dziennikami i resztkami, które pozostawia.",
        uninstallerStep1: "Przeciągnij aplikację do Ustawień lub wybierz ją z listy.",
        uninstallerStep2: "Sprawdź znalezione pliki i ilość zajmowanego miejsca.",
        uninstallerStep3: "Przenieś, co chcesz, do Kosza. Nic nie jest usuwane trwale.",
        uninstallerMenuItem: "Odinstaluj aplikację…",
        uninstallerDropTitle: "Przeciągnij tutaj aplikację",
        uninstallerDropSubtitle: "lub wybierz aplikację do przeskanowania",
        uninstallerChoose: "Wybierz aplikację…",
        uninstallerPickerTitle: "Wybierz aplikację",
        uninstallerPickerSearch: "Wyszukaj aplikacje",
        uninstallerPickerEmpty: "Nie znaleziono aplikacji",
        uninstallerEmptyNote: "Bez Twojego potwierdzenia nic nie zostanie usunięte.",
        uninstallerFDANote: "Przyznaj pełny dostęp do dysku, aby uzyskać dokładniejsze skanowanie.",
        uninstallerFDAGrant: "Przyznaj dostęp…",
        uninstallerFDAHint: "Włącz Vorssaint na liście. Jeśli go tam nie ma, kliknij + i wybierz Vorssaint z Aplikacji. Dostęp zostanie przyznany dopiero po ponownym otwarciu aplikacji.",
        uninstallerFDARelaunch: "Uruchom ponownie teraz",
        uninstallerScanning: "Skanuję pliki…",
        uninstallerRemoving: "Przenoszenie do Kosza…",
        uninstallerFoundTitle: "znaleziono",
        uninstallerSelectedFormat: "Wybrano %d z %d",
        uninstallerRemove: "Przenieś do Kosza",
        uninstallerCancel: "Anuluj",
        uninstallerConfirmationExpired: "To potwierdzenie jest już nieaktualne. Przejrzyj bieżące pozycje i potwierdź ponownie.",
        uninstallerDoneTitle: "Zrobione!",
        uninstallerFreedFormat: "Usunięto %@",
        uninstallerSomeFailed: "Niektórych elementów nie udało się przenieść do Kosza.",
        uninstallerFailedNeedsFDA: "Dane aplikacji w trybie piaskownicy można przenosić tylko przy pełnym dostępie do dysku. Hasło administratora nie zastępuje tego.",
        uninstallerFailedMoreFormat: "i %d więcej",
        uninstallerAnother: "Odinstaluj kolejną",
        uninstallerCatApp: "Aplikacja",
        uninstallerCatSupport: "Dane aplikacji",
        uninstallerCatCaches: "Pamięć podręczna",
        uninstallerCatPreferences: "Preferencje",
        uninstallerCatContainers: "Kontenery",
        uninstallerCatLogs: "Dzienniki",
        uninstallerCatState: "Stan zapisany",
        uninstallerCatOther: "Pozostałe",
        uninstallerCommandBarBrowseTitle: "Odinstaluj aplikację",
        uninstallerCommandBarToggle: "Pokaż na pasku poleceń",
        uninstallerCommandBarCaption: "Wybierz i odinstaluj aplikacje na pasku poleceń.",
        uninstallerCommandBarFinderTitle: "Odinstaluj aplikację wybraną w Finder",
        uninstallerSelectionUnavailable: "Wybierz aplikację, którą można usunąć w Finder, lub wybierz inną z listy.",

        urlCleanerName: "Wyczyść adres URL",
        urlCleanerEnable: "Wyczyść adresy URL podczas ich kopiowania",
        urlCleanerEnableCaption: "Usuwa parametry śledzenia z linku w momencie dotarcia do schowka.",
        urlCleanerActiveNow: "Aktywny teraz",
        urlCleanerManualTitle: "Wyczyść teraz",
        urlCleanerInputPlaceholder: "Wklej adres URL",
        urlCleanerOutputPlaceholder: "Tutaj pojawi się czysty adres URL",
        urlCleanerCleanButton: "Wyczyść",
        urlCleanerPasteButton: "Wklej",
        urlCleanerCopyButton: "Kopiuj",
        urlCleanerClearButton: "Wyczyść pole",
        urlCleanerNoURL: "Wklej prawidłowy adres URL.",
        urlCleanerNoChange: "Nic do czyszczenia.",
        urlCleanerCleaned: "Adres URL został wyczyszczony.",
        urlCleanerCopied: "Skopiowano.",
        urlCleanerLocalNote: "Działa lokalnie, bez połączenia z siecią.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Wyszukuj, instaluj i usuwaj formuły oraz pakiety cask.",
        homebrewMissingTitle: "Nie znaleziono Homebrew",
        homebrewMissingBody: "Vorssaint może otworzyć Terminal za pomocą oficjalnego instalatora Homebrew. Terminal pokaże kroki i w razie potrzeby poprosi o podanie hasła.",
        homebrewInstallHomebrew: "Zainstaluj Homebrew",
        homebrewInstallHomebrewCaption: "Kiedy Terminal zakończy działanie, wróć tutaj i kliknij Odśwież.",
        homebrewInstallHomebrewOpened: "Instalator otwarty w terminalu.",
        homebrewShellSetupTitle: "Zakończ konfigurację terminala",
        homebrewShellSetupBody: "Homebrew jest zainstalowany, ale Terminal może jeszcze nie znajdować polecenia brew. Vorssaint może otworzyć Terminal z poleceniem konfiguracji.",
        homebrewShellSetupButton: "Skonfiguruj Terminal",
        homebrewShellSetupOpened: "Polecenie otwarte w terminalu. Następnie wróć tutaj i kliknij Odśwież.",
        homebrewRefresh: "Odśwież",
        homebrewCheckPackages: "Sprawdź pakiety",
        homebrewTrustTitle: "Źródło tap nie jest jeszcze zaufane",
        homebrewTrustCaption: "Homebrew prosi o potwierdzenie przed użyciem zewnętrznych źródeł tap. Zaufaj %@, aby kontynuować.",
        homebrewTrustButton: "Zaufaj i kontynuuj",
        homebrewSearchPlaceholder: "Wyszukaj pakiety",
        homebrewKeyboardHint: "Spacja lub Return zamyka panel macOS. Użyj przycisku wyszukiwania.",
        homebrewSearchButton: "Szukaj",
        homebrewSearchResults: "Wyniki",
        homebrewInstalled: "Zainstalowany",
        homebrewAll: "Wszystko",
        homebrewFormulas: "Formuły",
        homebrewCasks: "Pakiety cask",
        homebrewNoPackages: "Nie znaleziono pakietów",
        homebrewDependencies: "Zależności",
        homebrewGroupDependencies: "Grupuj zależności",
        homebrewOrphans: "Już nie potrzebne",
        homebrewOrphansNote: "Zainstalowane jako zależności, ale żaden zainstalowany pakiet już ich nie potrzebuje.",
        homebrewDependencyUpdatesFormat: "Aktualizacje zależności: %d",
        homebrewNoSelection: "Wybierz zainstalowany pakiet lub wyszukaj nowy.",
        homebrewDetailsTitle: "Szczegóły pakietu",
        homebrewInstall: "Zainstaluj",
        homebrewUninstall: "Odinstaluj",
        homebrewUpgrade: "Zaktualizuj",
        homebrewUpgradeAll: "Zaktualizuj wszystko",
        homebrewUpdateHomebrew: "Zaktualizuj Homebrew",
        homebrewAllPackages: "pakiety",
        homebrewOpenTerminal: "Otwórz Terminal",
        homebrewCancelOperation: "Anuluj",
        homebrewClearLog: "Wyczyść dziennik",
        homebrewLogTitle: "Dziennik",
        homebrewVersion: "Wersja",
        homebrewDescription: "Typ",
        homebrewHomepage: "Otwórz stronę internetową",
        homebrewPopularity: "Popularność",
        homebrewPopularityFormat: "%@ instalacji w ciągu %@ dni",
        homebrewInstalledBadge: "Zainstalowany",
        homebrewNotInstalledBadge: "Nie zainstalowano",
        homebrewUpdates: "Aktualizacje",
        homebrewUpdateAvailableBadge: "Dostępna aktualizacja",
        homebrewLatestVersion: "Najnowsza wersja",
        homebrewConfirmInstallTitle: "Zainstalować z Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew pobierze i zainstaluje %@. Można także zainstalować zależności.",
        homebrewConfirmUninstallTitle: "Odinstalować za pomocą Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew odinstaluje %@. Pliki konfiguracyjne mogą pozostać w systemie.",
        homebrewConfirmUpgradeTitle: "Zaktualizować za pomocą Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew pobierze i zastosuje najnowszą wersję %@. Zależności mogą również zostać zaktualizowane.",
        homebrewConfirmUpgradeAllTitle: "Zaktualizować wszystko za pomocą Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew pobierze i zastosuje najnowsze wersje pakietów z dostępnymi aktualizacjami. Zależności mogą również zostać zaktualizowane.",
        homebrewConfirmUpdateHomebrewTitle: "Zaktualizować Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew pobierze najnowsze informacje, a następnie ponownie załaduje Twoje pakiety.",
        homebrewTerminalFallback: "Ta operacja wymaga, aby Terminal zapytał o hasło administratora. Vorssaint nie przechwytuje haseł.",
        homebrewLoading: "Ładowanie…",
        homebrewSearchEmpty: "Brak wyników",
        homebrewOperationInstallFormat: "Instalowanie %@",
        homebrewOperationUninstallFormat: "Odinstalowanie %@",
        homebrewOperationUpgradeFormat: "Aktualizacja %@",
        homebrewOperationUpgradeAll: "Aktualizowanie pakietów",
        homebrewOperationUpdateHomebrew: "Aktualizacja Homebrew",
        homebrewOperationInstalledFormat: "Zainstalowano %@.",
        homebrewOperationUninstalledFormat: "Odinstalowano %@.",
        homebrewOperationUpgradedFormat: "%@ zaktualizowano.",
        homebrewOperationUpgradedAll: "Pakiety zaktualizowane.",
        homebrewOperationUpdatedHomebrew: "Homebrew zaktualizowano.",
        homebrewOperationFailedFormat: "Nie można dokończyć %@.",
        homebrewOperationCancelled: "Operacja anulowana.",
        homebrewOperationPreparing: "Przygotowanie…",
        homebrewOperationDownloading: "Pobieram pliki…",
        homebrewOperationInstalling: "Instaluję pliki…",
        homebrewOperationUninstalling: "Usuwanie plików…",
        homebrewOperationUpgrading: "Aktualizuję pliki…",
        homebrewOperationFinalizing: "Kończenie…",
        homebrewOperationRefreshing: "Odświeżanie listy…",
        homebrewOperationTerminal: "Kontynuuj w Terminalu.",
        homebrewOperationElapsedFormat: "Czas: %@",
        homebrewOperationShowDetails: "Pokaż szczegóły",
        homebrewOperationHideDetails: "Ukryj szczegóły",
        homebrewOperationTechnicalLog: "Szczegóły techniczne",
        homebrewOperationProgressUnknown: "Homebrew nie zgłosił jeszcze wartości procentowej.",

        mediaName: "Multimedia",
        mediaEnableCaption: "Kompresuj filmy, konwertuj i przetwarzaj obrazy, twórz pliki GIF i wyodrębniaj tekst lokalnie.",
        mediaLocalNote: "Działa lokalnie, bez połączenia z siecią.",
        mediaToolVideo: "Wideo",
        mediaToolGIF: "GIF-y",
        mediaToolImage: "Obraz",
        mediaToolText: "Tekst",
        mediaSelectFile: "Wybierz plik",
        mediaDropHint: "Upuść plik tutaj lub kliknij, aby go wybrać.",
        mediaOutput: "Wyjście",
        mediaOutputAutomatic: "Automatycznie",
        mediaChooseOutput: "Miejsce docelowe",
        mediaStartVideo: "Kompresuj wideo",
        mediaStartGIF: "Utwórz GIF",
        mediaStartImage: "Przetwórz obraz",
        mediaStartConvertPDF: "Konwertuj do formatu PDF",
        mediaStartText: "Wyodrębnij tekst",
        mediaCancel: "Anuluj",
        mediaStartTime: "Rozpocznij",
        mediaEndTime: "Koniec",
        mediaQuality: "Kompresja",
        mediaCompressionLow: "Niski",
        mediaCompressionMedium: "Średni",
        mediaCompressionHigh: "Wysoki",
        mediaCompressionLowDescription: "Wysoka jakość, duży rozmiar pliku",
        mediaCompressionMediumDescription: "Zrównoważona jakość i rozmiar pliku",
        mediaCompressionHighDescription: "Niska jakość, mały rozmiar pliku",
        mediaMaxSize: "Rozmiar",
        mediaSizingResolution: "Rozdzielczość",
        mediaSizingFileSize: "Rozmiar pliku",
        mediaTargetSize: "Rozmiar docelowy",
        mediaTargetSizeHint: "Rozdzielczość dostosowuje się, aby pozostać poniżej limitu.",
        mediaErrorTargetTooSmall: "Rozmiar docelowy jest za mały dla tego klipu. Przytnij lub podnieś limit.",
        mediaMegabytesSuffix: "MB",
        mediaWidth: "Szerokość",
        mediaFPS: "FPS",
        mediaKeepAudio: "Zachowaj dźwięk",
        mediaCodec: "Kodek",
        mediaFormat: "Format",
        mediaStripMetadata: "Usuń metadane",
        mediaLoopGIF: "Zapętl GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Dokładny",
        mediaOCRFast: "Szybko",
        mediaLanguageCorrection: "Korekta językowa",
        mediaTextOutputNote: "Wyodrębniony tekst można skopiować i zapisać w formacie TXT.",
        mediaRunning: "Przetwarzanie",
        mediaCompleted: "Gotowe",
        mediaCancelled: "Anulowano.",
        mediaOpenInFinder: "Pokaż w Finderze",
        mediaCopyText: "Skopiuj tekst",
        mediaRunAgain: "Uruchom ponownie",
        mediaEmptyText: "Nie znaleziono tekstu.",
        mediaResultSavedFormat: "Zapisano jako %@",
        mediaResultSizeFormat: "%@ → %@",
        mediaResultGrewCaption: "Przekonwertowany plik okazał się większy niż oryginał.",
        mediaErrorNoFile: "Najpierw wybierz plik.",
        mediaErrorNoVideo: "Ten plik nie zawiera ścieżki wideo.",
        mediaErrorSameOutput: "Wybierz miejsce docelowe inne niż oryginalny plik.",
        mediaErrorUnsupported: "Format nieobsługiwany przez macOS.",

        shelfName: "Półka",
        shelfEnable: "Tymczasowy obszar do przeciągania plików",
        shelfEnableCaption: "Pływające miejsce do gromadzenia plików, obrazów i tekstu, a następnie przeciągania ich w dowolne miejsce później.",
        shelfHowTitle: "Jak używać",
        shelfStep1: "Otwórz półkę skrótem klawiszowym lub potrząsając myszą podczas przeciągania.",
        shelfStep2: "Upuść na półkę pliki, obrazy, linki lub tekst, aby je przechować.",
        shelfStep3: "Przeciągnij każdy element z powrotem do dowolnej aplikacji, kiedy go potrzebujesz.",
        shelfShakeToggle: "Otwórz, potrząsając myszką podczas przeciągania",
        shelfShakeCaption: "Szybko potrząśnij wskaźnikiem, trzymając przedmiot, aby przywołać go w pobliżu kursora.",
        shelfDropZoneToggle: "Zachowaj przeciągnięte pliki na pasku menu",
        shelfDropZoneCaption: "Podczas przeciągania pliku półka pojawia się pod ikoną paska menu. Upuszczone elementy pozostają w niej. Możesz ją zwinąć i otworzyć kliknięciem. Pusta półka znika.",
        shelfDropZoneCaptionTopCenter: "Podczas przeciągania pliku półka pojawia się jako plakietka u góry ekranu. Przechowuje upuszczone elementy i otwiera się kliknięciem. Pusta plakietka znika.",
        shelfDropZoneLabel: "Upuść tutaj",
        shelfDockPlacement: "Pozycja",
        shelfDockMenuBar: "Pod ikoną paska menu",
        shelfDockTopCenter: "Górna środkowa część ekranu",
        shelfDockIslandNote: "Po włączeniu Dynamic Island półka jest zawsze u góry, pośrodku ekranu.",
        shelfCollapse: "Zwiń",
        shelfBehaviorTitle: "Po użyciu",
        shelfCloseAfterDrop: "Zamknij po przejściu do innej aplikacji",
        shelfCloseAfterDropCaption: "Zamyka półkę, gdy aplikacja docelowa przyjmie elementy. Przypięcie w panelu utrzymuje ją otwartą.",
        shelfRemoveAfterDrop: "Usuń przedmioty po upuszczeniu",
        shelfRemoveAfterDropCaption: "Pozycje zaakceptowane przez inną aplikację opuszczają półkę. Wyłącz tę opcję, aby zachować tam kopię. Przypięte elementy zawsze pozostają.",
        shelfExclusionsTitle: "Automatyczne wyjątki",
        shelfExclusionsEmpty: "Nie dodano żadnych aplikacji.",
        shelfExclusionsCaption: "Potrząsanie myszą i strefa upuszczania pod paskiem menu nie działają dla przeciągania rozpoczętego w tych aplikacjach. Skrót i opcja „Otwórz teraz” nadal działają.",
        shelfPin: "Zachowaj otwarte",
        shelfUnpin: "Pozwól na zamknięcie po użyciu",
        extraBrightnessName: "Dodatkowa jasność",
        extraBrightnessCaption: "Wykorzystuje zapas HDR wyświetlacza, aby przekroczyć maksymalną jasność. Zużywa więcej baterii, a komputer Mac może się nagrzewać.",
        extraBrightnessLevelLabel: "Intensywność",
        extraBrightnessUnsupported: "Dostępne tylko na wyświetlaczach XDR, takich jak te w 14 i 16-calowym MacBooku Pro.",
        shelfHotkeyLabel: "Skrót",
        shelfOpenNow: "Otwórz teraz",
        shelfNoPermission: "Nie wymaga żadnych uprawnień.",
        shelfMenuItem: "Otwórz półkę",
        shelfTitle: "Półka",
        shelfEmpty: "Przeciągnij elementy tutaj",
        shelfClearAll: "Wyczyść wszystko",
        shelfRemoveSelected: "Usuń wybrane",
        shelfSelectedFormat: "Wybrano %d",
        shelfHint: "Kliknij, aby wybrać. Przeciągnij, aby użyć, lub kliknij prawym przyciskiem myszy, aby uzyskać więcej akcji.",
        shelfItemImage: "Obraz",
        shelfTooltipItemsFormat: "%d elementów",
        shelfTooltipItemsFew: "%d elementy",
        shelfTooltipImageSingular: "%d obraz",
        shelfTooltipImageFew: "%d obrazy",
        shelfTooltipImagePlural: "%d obrazów",
        shelfTooltipFileSingular: "%d plik",
        shelfTooltipFileFew: "%d pliki",
        shelfTooltipFilePlural: "%d plików",
        shelfTooltipNoteSingular: "%d notatka",
        shelfTooltipNoteFew: "%d notatki",
        shelfTooltipNotePlural: "%d notatek",
        shelfTooltipLinkSingular: "%d link",
        shelfTooltipLinkFew: "%d linki",
        shelfTooltipLinkPlural: "%d linków",
        shelfActionOpen: "Otwórz",
        shelfActionOpenWith: "Otwórz za pomocą",
        shelfActionShare: "Udostępnij",
        shelfActionPin: "Przypnij",
        shelfActionUnpin: "Odepnij",

        breakdownMeasuring: "Pomiar…",

        mixerSection: "Mikser głośności",
        mixerEmpty: "Tutaj pojawiają się aplikacje korzystające z dźwięku",
        mixerUnavailable: "Dostępne w systemie macOS 14.4 i nowszych wersjach",
        mixerPermissionBody: "Aby regulować głośność poszczególnych aplikacji, zezwól na nagrywanie ekranu i dźwięku systemowego w Ustawieniach systemowych. Dźwięk nie jest nagrywany.",
        mixerResetTooltip: "Zresetuj do 100%",
        mixerOutputDefault: "Domyślne",
        mixerOutputCurrent: "aktualny",
        mixerOutputUnavailable: "Wyjście niedostępne",
        mixerOutputFallback: "Używanie ustawień domyślnych do czasu powrotu tego urządzenia.",
        mixerBypassedCaption: "Ta aplikacja zarządza własnym dźwiękiem.",
        mixerOutputTooltip: "Wybierz wyjście",
        mixerAirPlayChooseSpeaker: "Wybierz głośnik AirPlay…",
        mixerSystemOutputTitle: "Wyjście",
        mixerSystemOutputNoDevices: "Nie znaleziono wyjść",
        mixerSystemOutputTooltip: "Wybierz wyjście systemowe",
        mixerSystemOutputErrorFormat: "Nie można przełączyć: %@",
        mixerLowerOnHeadphonesDisconnect: "Zmniejsz głośność po odłączeniu słuchawek",
        mixerLowerOnHeadphonesDisconnectCaption: "Zmienia głośność wyjścia audio po odłączeniu słuchawek przewodowych lub Bluetooth.",
        mixerHeadphonesDisconnectVolume: "Głośność po rozłączeniu",
        preciseVolumeRollerEnable: "Użyj mniejszych stopni głośności",
        preciseVolumeRollerCaption: "Zamienia pokrętła i klawisze głośności w mniejsze stopnie głośności systemu.",
        preciseVolumeRollerTapFailed: "Nie można nasłuchiwać klawiszy głośności.",
        soundOutputSwitcherTitle: "Przełącznik wyjścia audio",
        soundOutputSwitcherEnable: "Przełącz wyjścia za pomocą skrótu",
        soundOutputSwitcherCaption: "Wybierz wyjścia i za pomocą skrótu przejdź do kolejnego dostępnego.",
        soundOutputSwitcherDevices: "Wyjścia w cyklu",
        soundOutputSwitcherNoAvailableSelection: "Wybierz co najmniej jedno dostępne wyjście.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Nie znaleziono mikrofonów",
        mixerInputUnavailable: "Mikrofon niedostępny",
        mixerInputFallback: "Używanie ustawień domyślnych do czasu przywrócenia tego mikrofonu.",
        mixerInputTooltip: "Wybierz mikrofon",
        mixerInputErrorFormat: "Nie można przełączyć: %@",
        mixerVisibleApps: "Aplikacje na liście",
        mixerAllShown: "Wszystko",
        mixerHiddenCountLabel: "Ukryty",
        mixerHideFromList: "Ukryj na liście",
        audioPrioritySection: "Priorytet dźwięku",
        audioPriorityOutputEnable: "Automatycznie przełączaj na wyjście o najwyższym priorytecie",
        audioPriorityInputEnable: "Automatycznie przełączaj na mikrofon o najwyższym priorytecie",
        audioPriorityOutputList: "Priorytet wyjścia audio",
        audioPriorityInputList: "Priorytet mikrofonu",
        audioPriorityMoveUp: "Przesuń w górę",
        audioPriorityMoveDown: "Przesuń w dół",
        audioPriorityUnavailable: "Niedostępne",
        audioPriorityCurrent: "Aktualny",
        audioPriorityCaption: "Urządzenia wybierane są w kolejności priorytetów. Po podłączeniu urządzenia o wyższym priorytecie staje się ono aktywne. Kiedy aktywny się rozłączy, następny dostępny przejmuje kontrolę.",

        updatesSection: "Aktualizacje",
        autoCheckToggle: "Automatycznie sprawdzaj dostępność aktualizacji",
        includeBetaUpdatesToggle: "Otrzymuj aktualizacje wersji beta",
        includeBetaUpdatesCaption: "Wersje beta zawierają funkcje w fazie rozwoju i mogą zawierać błędy lub niekompletne działanie.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Sprawdź teraz",
        updateChecking: "Sprawdzanie…",
        updateUpToDate: "Korzystasz z najnowszej wersji.",
        updateAvailablePrefix: "Dostępna aktualizacja:",
        updateInstallButton: "Pobierz i zainstaluj",
        updateDownloading: "Pobieram aktualizację…",
        updateInstalling: "Instaluję i uruchamiam ponownie…",
        updateFailedPrefix: "Nie udało się sprawdzić:",
        updateLastChecked: "Ostatnio sprawdzane:",
        updateNotifyTitle: "Aktualizacja Vorssaint",
        updateInstallFailedBody: "Aktualizacja została pobrana, ale nie można jej zastosować. Pobierz najnowszą wersję ze strony wydań GitHub i przeciągnij aplikację na bieżącą.",
        updateNeedsApplicationsTitle: "Przenieś Vorssaint do aplikacji",
        updateNeedsApplicationsBody: "Aplikacja działa z miejsca, którego nie można zaktualizować, na przykład z obrazu dysku lub tymczasowej lokalizacji systemu. Przeciągnij Vorssaint do folderu Aplikacje, otwórz go stamtąd i spróbuj ponownie.",
        menuCheckUpdates: "Sprawdź aktualizacje…",

        permissionRequired: "Wymagane uprawnienie",
        permissionAccessibility: "Dostępność",
        permissionScreenRecording: "Nagrywanie ekranu",
        permissionGranted: "Przyznano",
        permissionMissing: "Nie przyznano",
        permissionOpenSettings: "Otwórz Ustawienia systemowe…",
        permissionRequest: "Przyznaj dostęp",
        permissionRestartNote: "po udzieleniu zgody macOS może poprosić o ponowne otwarcie aplikacji.",
        secureInputTitle: "Bezpieczne wprowadzanie jest włączone",
        secureInputHeldFormat: "%@ korzysta z bezpiecznego wprowadzania, więc Vorssaint nie może wpisywać tekstu. Zamknij pole hasła lub tę aplikację, aby je zwolnić.",
        secureInputUnattributed: "Żadna uruchomiona aplikacja nie zgłasza używania tej funkcji. Wyloguj się i zaloguj ponownie, aby ją wyłączyć.",
        secureInputUnidentified: "Nie można ustalić, która aplikacja korzysta z bezpiecznego wprowadzania. Vorssaint nie może wpisywać tekstu.",
        secureInputRevealFormat: "Pokaż %@",

        aboutDescription: "Centrum narzędziowe dla Twojego komputera Mac.\nEnergia, monitor systemu, przewijanie i przełącznik okien bezpośrednio na pasku menu.",
        versionPrefix: "Wersja",
        reviewIntro: "Wprowadzenie do przeglądu",
        reviewHighlights: "Przejrzyj najważniejsze informacje",
        viewOnGitHub: "Zobacz na GitHubie",

        obContinue: "Kontynuuj",
        obBack: "Wstecz",
        obSkipStep: "Pomiń ten krok",
        obStart: "Otwórz Vorssaint",
        obStepWelcomeTitle: "Witamy w Vorssaint",
        obStepWelcomeBody: "Dyskretne narzędzie na pasku menu, dzięki któremu codzienny system MacOS staje się bardziej praktyczny.",
        obWelcomeBullet1Title: "Energia pod kontrolą",
        obWelcomeBullet1Body: "Trzymaj Maca w stanie czuwania tak długo, jak chcesz, nawet przy zamkniętej pokrywie.",
        obWelcomeBullet2Title: "Przejrzysty widok systemu",
        obWelcomeBullet2Body: "Temperatury CPU, GPU i baterii, użycie sprzętu oraz obciążenie pamięci w czasie rzeczywistym.",
        obWelcomeBullet3Title: "Mysz i okna, tak jak chcesz",
        obWelcomeBullet3Body: "Odwrócone przewijanie myszą i przełącznik okien z miniaturami.",
        obLanguageLabel: "Język",
        obStepAccessibilityTitle: "Dostępność",
        obStepAccessibilityBody: "Potrzebne do odwrócenia przewijania myszy i aby przełącznik okien reagował na klawiaturę.",
        obAccessibilityWhy: "Aplikacja obserwuje tylko kółko myszy i skrót przełącznika. Nic nie jest nigdzie nagrywane ani wysyłane.",
        obStepRecordingTitle: "Nagrywanie ekranu",
        obStepRecordingBody: "Pozwala przełącznikowi wyświetlać prawdziwe miniatury okien zamiast samych ikon.",
        obRecordingWhy: "Miniatury są generowane na bieżąco, pozostają w pamięci i nigdy nie opuszczają komputera Mac. Bez tego przełącznik nadal działa z ikonami.",
        obStepMonitorTitle: "Monitor systemu",
        obStepMonitorBody: "Panel pokazuje temperatury CPU, GPU i baterii, użycie sprzętu oraz obciążenie pamięci.",
        obMonitorNoPermission: "Nie potrzeba pozwolenia. Czujniki odczytywane są bezpośrednio z systemu.",
        obStepOptionalTitle: "Opcjonalne funkcje",
        obStepOptionalBody: "Włącz to, czego chcesz teraz używać. Wszystko można później zmienić w Ustawieniach.",
        obStepStatusTitle: "Kontrola",
        obStepStatusBody: "Upewnij się, że wszystko jest gotowe na żądane funkcje.",
        obStatusRecheck: "Sprawdź ponownie",
        obStepDoneTitle: "Wszystko gotowe!",
        obStepDoneBody: "Vorssaint już opiekuje się Twoim komputerem Mac.",
        obDoneHint: "Poszukaj czarnej dziury na pasku menu w prawym górnym rogu ekranu.",
        obWhatsNewTitle: "Co nowego w tej wersji",
        obWhatsNewFallback: "Ta aktualizacja zawiera najnowsze poprawki i ulepszenia.",
        obLanguageUpdateTitle: "Teraz w Twoim języku",
        obLanguageUpdateBody: "Vorssaint mówi teraz w kilku językach. Wybierz ten, którego chcesz użyć; możesz to zmienić w dowolnym momencie w Ustawieniach.",
        obPurposeTitle: "Co cię tu sprowadziło?",
        obPurposeBody: "Wybierz gotową konfigurację lub wybierz dokładnie to, czego chcesz użyć.",
        obPurposeSkip: "Możesz później dodać lub usunąć funkcje w Ustawieniach.",

        tabMonitor: "Monitor",
        monitorMenuBarSection: "Na pasku menu",
        monitorMenuBarCaption: "Wybierz, co pojawi się obok ikony na pasku menu.",
        monitorCombineTemperatures: "Połącz użycie i temperaturę",
        monitorCombineTemperaturesCaption: "Gdy włączone jest użycie i temperatura dla tego samego elementu, pokaż je w jednym bloku.",
        monitorSeparateMenuBarMetrics: "Oddziel metryki na osobne elementy",
        monitorSeparateMenuBarMetricsCaption: "Rozdziela aktywne bloki na pasku menu. Przy włączonym łączeniu użycie i temperatura pozostają razem.",
        monitorNetworkUploadFirst: "Wysyłanie nad pobieraniem",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Pamięć",
        monitorShowNetwork: "Sieć",
        monitorShowPowerLabel: "Moc",
        monitorIntervalLabel: "Aktualizuj co",
        monitorInterval1: "1 sekunda",
        monitorInterval2: "2 sekundy",
        monitorInterval5: "5 sekund",
        monitorPanelSection: "W panelu",
        panelNavigationMode: "Nawiguj po panelu według sekcji",
        panelNavigationCaption: "Wyświetla jedną sekcję na raz. Wybierz opcję Lista, aby zobaczyć wszystko w jednym ciągłym przewijaniu.",
        panelFooterSections: "Sekcje",
        panelFooterList: "Lista",
        betaBadge: "BETA",
        betaFeatureWarning: "Beta. Możesz napotkać pewne błędy.",

        networkSection: "Sieć",
        networkIPAddresses: "Adresy IP",
        networkLocalIP: "Lokalny adres IPv4",
        networkDownload: "Pobieranie",
        networkUpload: "Wysyłanie",
        networkThisSession: "Ta sesja",
        networkMeasuring: "Pomiar…",
        networkApps: "Aplikacje korzystające z sieci",
        networkAppsIdle: "Żadne aplikacje nie korzystają teraz z sieci",

        diskSection: "Dyski",
        diskUsed: "zajęte",
        diskFree: "wolne",
        diskMenuBarStyleLabel: "Wyświetlanie danych dysku",
        diskMenuBarUsedPercentage: "Procent zajętego miejsca",
        diskMenuBarAvailableSpace: "Dostępne miejsce",
        diskMenuBarUsedSpace: "Zajęte miejsce",
        diskAvailable: "dostępne",
        diskPurgeable: "możliwe do oczyszczenia",
        diskInternal: "Wewnętrzny",
        diskExternal: "Zewnętrzny",
        diskSelect: "Wybierz dysk",
        diskRead: "Odczyt",
        diskWrite: "Zapis",
        diskSMARTStatus: "Status",
        diskSMARTUnavailable: "SMART niedostępny dla tego dysku",
        diskTotalRead: "Łącznie odczytano",
        diskTotalWritten: "Łącznie zapisano",
        diskTemperature: "Temperatura",
        diskHealth: "Kondycja",
        diskPowerCycles: "Cykle zasilania",
        diskPowerOnHours: "Godziny pracy",
        diskUnsafeShutdowns: "Niebezpieczne wyłączenia",
        diskMediaErrors: "Błędy nośnika",
        diskEject: "Wysuń",
        diskEjectAll: "Wysuń wszystko",
        diskEjecting: "Wysuwanie…",
        diskReadyToRemove: "Gotowe do odłączenia",
        diskEjectFailed: "Nie można wysunąć",
        diskProtectionCaption: "Wysuń przed odłączeniem.",
        diskNoExternal: "Brak dysku zewnętrznego gotowego do wysunięcia.",
        diskOpenInFinder: "Otwórz",
        diskStorageSettings: "Pamięć masowa",
        diskNoDisks: "Nie znaleziono zamontowanych dysków.",

        powerSection: "Zasilanie",
        powerSystem: "System",
        powerAdapter: "Zasilacz",
        powerBattery: "Bateria",
        powerCharging: "Ładowanie",
        powerOnBattery: "Na baterii",
        powerPluggedIn: "Podłączony",
        powerUnavailable: "Wskaźniki mocy niedostępne na tym komputerze Mac",
        powerAdapterMaxFormat: "%@ maks",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Temperatura procesora",
        monitorShowGPUTemperature: "Temperatura GPU",
        monitorShowBatteryTemperature: "Temperatura akumulatora",
        monitorShowPeripheralBattery: "Baterie akcesoriów",
        peripheralBatteryNoDevices: "Nie znaleziono żadnych urządzeń",
        monitorGraphsSection: "Wykresy",

        updateBannerTitle: "Dostępna aktualizacja",
        updateBannerAction: "Zaktualizuj",
        obStepMenuBarTitle: "Metryki na pasku menu",
        obStepMenuBarBody: "Wybierz, co ma być wyświetlane obok ikony. Powyższy podgląd jest aktualizowany na bieżąco.",
        obStepMenuBarNote: "Nowość: Bloki sieci i zasilania oraz wykresy w panelu. Dostosuj wszystko później w Ustawieniach > Monitor.",
        monitorMenuBarPresetLabel: "Styl",
        menuBarPresetReadable: "Czytelny",
        menuBarPresetDense: "Gęsty",
        menuBarSpacingLabel: "Odstępy na pasku menu",
        menuBarSpacingStandard: "Standard",
        menuBarSpacingCompact: "Kompaktowy",
        menuBarHideIconToggle: "Ukryj ikonę aplikacji, gdy wyświetlane są dane",
        menuBarHideIconCaption: "Ikona powraca sama, gdy metryki opuszczą pasek i gdy jest coś do zasygnalizowania (gotowość aktualizacji, włączona funkcja „Nie śpij” lub wyciszony mikrofon).",
        monitorLabelStyleLabel: "Etykiety",
        menuBarLabelStyleCompact: "Kompaktowy",
        menuBarLabelStyleClassic: "Klasyczny",
        monitorMemoryStyleLabel: "Pokaż pamięć jako",
        monitorMemoryPressureDot: "Wskaźnik obciążenia",
        memoryStyleDot: "Kropka",
        memoryStylePercent: "%",
        memoryStyleBoth: "Obydwa",
        systemUptime: "Czas pracy:",
        batteryCharge: "Poziom naładowania",
        powerHealth: "Kondycja baterii",
        powerCycles: "Cykle",
        speedTestRun: "Test prędkości",
        speedTestAgain: "Przetestuj ponownie",
        speedTestLatency: "Opóźnienie",
        speedTestTesting: "Testowanie…",
        speedTestFailed: "Test nie powiódł się",

        monitorShowInPanel: "Pokaż w panelu",
        disclosureExpanded: "Rozszerzony",
        disclosureCollapsed: "Zwinięty",
        panelHideItem: "Ukryj w panelu",
        panelShowItem: "Pokaż w panelu",
        panelHiddenItem: "Ukryty",
        monitorItemUptime: "Czas pracy",
        monitorItemNetSpeed: "Prędkość na żywo",
        monitorItemNetTotals: "Sumy sesji",
        monitorItemNetTest: "Test prędkości",
        monitorItemDiskUsage: "Użycie dysku",
        monitorItemDiskActivity: "Aktywność na żywo",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Ochrona zewnętrzna",
        monitorItemDiskTools: "Narzędzia",
        monitorPanelConfigHint: "Otwórz blok, aby wybrać, co będzie pokazywał.",
        monitorOrderHint: "Przeciągnij, aby zmienić kolejność sekcji panelu i użyj oka, aby pokazać lub ukryć każdą z nich.",
        obStepPanelTitle: "Co jest w panelu",
        obStepPanelBody: "Otwórz każdy blok i wybierz dokładnie to, co wyświetli się po kliknięciu ikony.",
        obStepPanelNavigationTitle: "Panel oparty na sekcjach",
        obStepPanelNavigationBody: "Panel może teraz wyświetlać jedną sekcję na raz. Możesz przełączać się między sekcjami i listą w Ustawieniach.",

        cleaningMenuItem: "Tryb czyszczenia",
        utilitiesSection: "Narzędzia",
        quickControlsSection: "Sterowanie",
        panelCategoryWindows: "Okna",
        panelCategoryInput: "Mysz i klawiatura",
        panelCategoryFiles: "Pliki",
        windowMaximizeName: "Maksymalizuj okna",
        windowMaximizeCaption: "Zielony przycisk maksymalizuje okno bez tworzenia nowego biurka Spaces.",
        windowMaximizeActiveNow: "Aktywne obejście zielonego przycisku",
        windowMaximizeNeedsAccessibility: "Wymaga uprawnień Dostępności.",
        keyDebounceName: "Filtrowanie powtórzeń",
        keyDebounceEnable: "Filtruj powtarzające się naciśnięcia klawiszy",
        keyDebounceCaption: "Filtruje bardzo szybko powtarzające się naciśnięcia klawiszy.",
        keyDebounceActiveNow: "Filtr aktywny",
        keyDebounceGlobalWindow: "Globalny przedział czasu",
        keyDebouncePerKeySection: "Poszczególne klawisze",
        keyDebouncePerKeyCaption: "Ustawienia poszczególnych klawiszy zastępują globalny przedział czasu. Ustaw 0 ms, aby wyłączyć filtrowanie danego klawisza.",
        keyDebounceKeyLabel: "Klawisz",
        keyDebounceWindowLabel: "Przedział czasu",
        keyDebounceAddKey: "Dodaj klawisz",
        keyDebounceNoOverrides: "Nie skonfigurowano żadnych konkretnych klawiszy.",
        keyDebounceRemoveKey: "Usuń klawisz",
        cleaningPanelCaption: "Blokuje klawiaturę, umożliwiając bezpieczne czyszczenie.",
        cleaningOverlayTitle: "Klawiatura zablokowana do czyszczenia",
        cleaningOverlaySubtitle: "Naciśnij klawisz Escape 5 razy, aby odblokować",
        cleaningOverlayUnlock: "Odblokuj",
        cleaningOverlayMouseHint: "Twoja mysz i gładzik nadal działają",
        cleaningKeepScreenVisibleToggle: "Zachowaj widoczność ekranu",
        cleaningKeepScreenVisibleCaption: "Wyświetla dyskretny wskaźnik w rogu ekranu, zamiast zaciemniać zawartość.",
        cleaningStartNow: "Zablokuj teraz klawiaturę",
        cleaningNeedsAxTitle: "Wymagane uprawnienia Dostępności",
        cleaningNeedsAxBody: "Aby bezpiecznie zablokować klawiaturę, Vorssaint potrzebuje uprawnień Dostępność. Przyznaj to w Ustawieniach systemu i spróbuj ponownie.",

        tabSupport: "Wsparcie",
        shortcutsPageCaption: "Edytuj każdy globalny skrót funkcji zainstalowanych na tym Macu. Nieaktywne skróty pozostają zapisane, ale nie działają.",
        shortcutsPageTitle: "Skróty klawiszowe",
        settingsSearchPlaceholder: "Szukaj w ustawieniach",
        donateHeading: "Pomóż Vorssaint dalej się rozwijać",
        donateMessage: "Vorssaint jest darmowy, niezależny i zbudowany w moim wolnym czasie. Jeśli chcesz wspomóc finansowo, Kup mi kawę bezpośrednio pomaga mi w dalszym rozwoju.",
        donateButton: "Wesprzyj w Buy Me a Coffee",
        donateThanks: "Dziękuję, że tu jesteś. 🖤",
        supportIntroTitle: "Pomóż Vorssaint dalej się rozwijać",
        supportIntroMessage: "Jeśli chcesz wesprzeć finansowo rozwój, Kup Mi Kawę to jedyne miejsce, w którym możesz to zrobić.",
        supportIntroStarButton: "Dodaj gwiazdkę Vorssaint na GitHubie",
        supportIntroStarMessage: "Nigdy nie oczekuje się wsparcia finansowego. Gwiazda na GitHubie pomaga większej liczbie osób odkryć Vorssaint i ma realny wpływ na jego rozwój.",
        supportIntroCoffeeButton: "Wesprzyj w Buy Me a Coffee",
        supportIntroLaterButton: "Nie teraz",
        supportIntroDoneButton: "Gotowe",
        discordIntroTitle: "Społeczność Discord Vorssaint dopiero się rozkręca",
        discordIntroMessage: "Społeczność Vorssaint jest nowa i wciąż jest tworzona. Dołącz wcześniej, aby poznać innych użytkowników i pomóc w stworzeniu przyjaznej przestrzeni wokół aplikacji.",
        discordIntroJoinButton: "Dołącz do społeczności Discorda",
        communityIntroTitle: "Zobacz to przed wszystkimi innymi",
        communityIntroMessage: "Osoby, które już śledziły mnie na X, zobaczyły kilka zmian w tej aktualizacji wcześniej niż ktokolwiek inny. Publikuję zapowiedzi tego, co nadchodzi i pokazuję, jak to działa, więc znasz już podstawy przed wypuszczeniem aktualizacji. Śledź dalej i zobacz, co będzie dalej!",
        communityIntroFollowButton: "Obserwuj @vorssaint na X",
        homebrewOfficialIntroTitle: "Teraz w oficjalnym katalogu Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint można teraz zainstalować bezpośrednio z oficjalnego katalogu Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nowa instalacja",
        homebrewOfficialIntroMigrationTitle: "Używasz starego źródła tap?",
        homebrewOfficialIntroMigrationMessage: "Usuń stare źródło tap jednorazowo. Aplikacja i ustawienia pozostają zachowane.",
        homebrewOfficialIntroCopyButton: "Kopiuj polecenie",
        updateShowcaseTitle: "Co nowego w wersji 3.1.4",
        updateShowcaseMessage: "Rzuć okiem na główne ulepszenia wprowadzone w tej aktualizacji.",
        updateShowcaseUnavailable: "Nie można teraz załadować filmu. Nadal możesz kontynuować.",
        updateShowcaseRestart: "Uruchom ponownie",
        showMenuBarIcon: "Pokaż ikonę paska menu",
        menuBarIconStillHiddenTitle: "Ikona jest nadal ukryta",
        menuBarIconStillHiddenBody: "Ikona została odbudowana, jednak macOS nie dał jej widocznego miejsca. Na pasku menu prawdopodobnie brakuje miejsca: usuń niektóre ikony paska menu (lub zamknij aplikacje z długimi menu) i spróbuj ponownie.",
        menuBarIconManagerHintFormat: "%@ jest otwarty i może przechowywać ikonę w ukrytej sekcji. Poszukaj tam Vorssaint lub ustaw %@ tak, aby zawsze pokazywał Vorssaint.",
        menuBarIconDisallowedBody: "macOS usuwa Vorssaint z paska menu. Otwórz Ustawienia systemu > Pasek menu, znajdź Vorssaint na liście aplikacji i włącz opcję „Zezwalaj na pasku menu”. Ikona pojawia się natychmiast po włączeniu przełącznika.",
        shortcutRecording: "Naciśnij nowy skrót",
        shortcutReset: "Resetuj",
        shortcutNone: "Brak",
        shortcutClear: "Usuń skrót",
        shortcutInvalid: "Użyj przynajmniej Control, Option lub Command z klawiszem.",
        shortcutPressKeys: "Wciśnij klawisze",
        shortcutEscapeHint: "Esc anuluje.",
        shortcutDeleteHint: "Delete usuwa skrót.",
        shortcutNotCaptured: "Nie zarejestrowano skrótu. macOS lub inna aplikacja już korzysta z tej kombinacji. Spróbuj innej.",
        shortcutConflictFormat: "Ten skrót jest już używany przez %@.",
        shortcutTakeOverOffer: "macOS używa %@ jako jednego ze swoich własnych skrótów.",
        shortcutTakeOverAction: "Przejmij kontrolę, podczas gdy Vorssaint działa",
        shortcutTakeOverCaption: "macOS odzyskuje skrót, gdy Vorssaint nie działa lub dana funkcja jest wyłączona.",
        shortcutTakeOverDismiss: "Nie przejmuj skrótu",
        shortcutUnavailable: "macOS odrzucił ten skrót. Wybierz inny.",
        shelfShortcutToggle: "Skrót do półki",
        switcherUsageHintFormat: "Przytrzymaj %@, aby nawigować; zwolnij, aby aktywować okno. Shift lub ← wraca; W zamyka okno; Q zamyka aplikację; Esc anuluje.",
        musicBlockSection: "Klawisze multimedialne",
        musicBlockTitle: "Zatrzymaj odtwarzanie muzyki przed samodzielnym otwarciem",
        musicBlockCaption: "Blokuje otwieranie aplikacji muzycznej po wykryciu klucza multimedialnego. Wymaga dostępu do ułatwień dostępu. Polecenia słuchawek bez wykrytego klawisza pozostają w spokoju.",
        musicBlockUnavailable: "Ta ochrona jest obecnie niedostępna. Wyłącz i włącz, aby spróbować ponownie.",
        musicBlockReplacementLabel: "Zamiast tego otwórz",
        musicBlockReplacementNone: "Brak",
        musicBlockReplacementBlocked: "Muzyka i iTunes to aplikacje blokowane, więc zamiast tego nie można ich otworzyć. Wybierz inną aplikację.",
        musicBlockChooseApp: "Wybierz aplikację…",
        musicBlockPlayReplacement: "Zagraj po otwarciu zamiennika",
        cleanerName: "Odkurzacz",
        cleanerIntroTitle: "Wyczyść swojego Maca",
        cleanerIntroCaption: "Skanuje w poszukiwaniu pozostałości po odinstalowanych aplikacjach, pamięciach podręcznych, dziennikach i Koszu. Najpierw przeglądasz wszystko, a usunięte elementy trafiają do Kosza.",
        cleanerScan: "Skanuj",
        cleanerScanning: "Skanowanie…",
        cleanerCleaning: "Czyszczenie…",
        cleanerCatLeftovers: "Pozostałości po odinstalowanych aplikacjach",
        cleanerCatLoginItems: "Osierocone elementy startowe",
        cleanerCatCaches: "Pamięć podręczna",
        cleanerCatLogs: "Dzienniki",
        cleanerCatDeveloper: "Pozostałości narzędzi deweloperskich",
        cleanerCatTrash: "Kosz",
        cleanerLeftoversNote: "Znalezione w drodze analizy i pozostawione bez sprawdzenia. Sprawdź ścieżkę przed zaznaczeniem.",
        cleanerLoginItemsNote: "Wpis w obszarze Elementy logowania znika po ponownym uruchomieniu komputera Mac.",
        cleanerTrashNote: "Opróżnianie Kosza jest trwałe.",
        cleanerCatDeviceBackups: "Kopie zapasowe iPhone'a",
        cleanerDeviceBackupsCaption: "Stare kopie zapasowe iPhone’ów i iPadów zajmują dużo miejsca, które macOS zalicza do kategorii „Inne”. Usuń tylko te, których już nie potrzebujesz. Nowa kopia powstanie po ponownym podłączeniu urządzenia.",
        cleanerCatScreenshots: "Zapomniane zrzuty ekranu",
        cleanerScreenshotsCaptionFormat: "Zrzuty ekranu nieotwierane od %d dni, które nadal mają nazwę i lokalizację nadaną przez macOS. Zrzuty przeniesione lub ze zmienioną nazwą nigdy nie trafiają na tę listę.",
        cleanerScreenshotsSettingCaption: "Skan zawiera listę zrzutów ekranu, których nie otwierałeś przez tak długi czas, bez zaznaczenia, wraz z ich całkowitym rozmiarem.",
        cleanerScreenshotsAfterFormat: "Po %d dniach",
        cleanerNothingFound: "Nic do czyszczenia. Twój Mac jest uporządkowany.",
        cleanerClean: "Wyczyść",
        cleanerDoneNote: "Elementy trafiły do ​​Kosza i można je stamtąd odzyskać.",
        cleanerAgain: "Zeskanuj ponownie",
        cleanerRevealInFinder: "Pokaż w Finderze",
        cleanerPanelCaption: "Pozostałości aplikacji, pamięci podręczne i dzienniki",
        cleanerSafeSection: "Bezpieczne sprzątanie",
        cleanerOptionalSection: "Opcjonalnie, najpierw przejrzyj",
        cleanerCatOtherCaches: "Inne pamięci podręczne",
        cleanerCachesCaption: "Pliki tymczasowe, które aplikacje samodzielnie odtwarzają.",
        cleanerLogsCaption: "Stare logi diagnostyczne.",
        cleanerDeveloperCaption: "Pozostałości po kompilacji Xcode i symulatorze.",
        cleanerLoginItemsCaption: "Wpisy startowe pozostawione przez aplikacje, które już nie istnieją.",
        cleanerLeftoversCaption: "Pliki pozostawione przez odinstalowane aplikacje.",
        cleanerOtherCachesCaption: "Bezpieczny do usunięcia, nic się nie psuje. Aplikacje mogą raz otworzyć się wolniej, a pobrana zawartość, na przykład muzyka offline, zostanie pobrana ponownie.",
        cleanerCleanSizeFormat: "Wyczyść %@",
        cleanerScheduleTitle: "Automatyczne czyszczenie",
        cleanerScheduleOff: "Wyłączone",
        cleanerScheduleDaily: "Codziennie",
        cleanerScheduleWeekly: "Co tydzień",
        cleanerScheduleCaption: "Czyści samodzielnie tylko bezpieczną część w wybranym czasie i wysyła wszystko do Kosza.",
        cleanerScheduleLastFormat: "Ostatnie automatyczne czyszczenie uwolniło %@.",
        cleanerAutoNotificationFormat: "Zwolniono %@, przenosząc elementy do Kosza.",
        cleanerScheduleNextFormat: "Następne czyszczenie %@.",
        cleanerScheduleRanFormat: "Ostatnie automatyczne czyszczenie %@.",
        cleanerScheduleNotifyToggle: "Powiadom po zakończeniu",
        cleanerNotifDenied: "Powiadomienia Vorssaint są wyłączone w systemie.",
        cleanerNotifOpenSettings: "Otwórz ustawienia powiadomień…",
        launchAtLoginNeedsApplications: "Aplikacja działa z miejsca, którego nie można otworzyć przy logowaniu. Przeciągnij Vorssaint do folderu Aplikacje, otwórz go stamtąd i włącz ponownie.",
        launchAtLoginNeedsApproval: "Element logowania został zarejestrowany, ale system macOS nadal potrzebuje Twojej zgody. W Ustawieniach systemu zezwól Vorssaint na otwieranie się przy logowaniu i działanie w tle.",
        ocrRemoveLineBreaksToggle: "Usuń podziały wierszy",
        ocrRemoveLineBreaksCaption: "Usuwa podziały wierszy, dzięki czemu skopiowany tekst jest wklejany jako jeden akapit.",
        ocrQRToggle: "Czytaj kody QR",
        ocrQRCaption: "Jeśli obszar ma kod QR, jego zawartość zostanie wyświetlona do skopiowania lub otwarcia.",
        ocrQRCopied: "Skopiowano kod QR",
        qrResultTitle: "Kod QR",
        qrResultCopy: "Kopiuj",
        qrResultOpen: "Otwórz link",
        highlightsTitle: "Nowość w tej aktualizacji",
        highlightsTitleClipboardRedesign: "Przeprojektowany schowek",
        highlightsTitleWindowLayout: "Układ okien",
        highlightsTitleQuitProtection: "Ochrona przed zakończeniem i zamknięciem",
        highlightsTitleRecorderBlur: "Rozmycie prywatności podczas nagrywania",
        highlightsCaptionDockPreview: "Podgląd w Docku działa teraz z włączonym powiększeniem w Docku",
        highlightsCaptionScreenshot: "Narzędzie do zrzutów ekranu zyskało lupę pikselową i odczyt kodu QR",
        highlightsCaptionSnippetLibrary: "Menu fragmentów z możliwością przeszukiwania umożliwia wpisanie dowolnego fragmentu bezpośrednio przy kursorze",
        highlightsCaptionCapturePalette: "Jeden skrót otwiera teraz pływającą paletę dla zrzutów ekranu, nagrań, tekstu i kolorów ekranu z pobliskimi elementami sterującymi.",
        highlightsCaptionClipboardRedesign: "Historia schowka otwiera się teraz jako kompaktowa paleta z uporządkowanymi wierszami i podglądem na żądanie umożliwiającym odczytanie lub edycję całego elementu.",
        highlightsCaptionWindowLayout: "Ustaw okna za pomocą pierścienia kierunkowego za pomocą skrótu i ​​wskaźnika lub przeciągnij do krawędzi ekranu, aby przyciągać je z niestandardowymi odstępami.",
        highlightsCaptionQuitProtection: "Unikaj zamykania aplikacji lub przypadkowego zamykania okien za pomocą przytrzymania, dwukrotnego naciśnięcia lub dodatkowego modyfikatora, który można dostosować do każdej aplikacji.",
        highlightsCaptionRecorderBlur: "Ukryj prywatne dane, hasła i wrażliwe obszary w dowolnym miejscu nagranego wideo przed udostępnieniem lub wyeksportowaniem.",
        highlightsConfigure: "Skonfiguruj",
        highlightsTry: "Spróbuj",
        highlightsSeeAll: "Zobacz wszystkie zmiany",
        switcherCurrentSpaceOnly: "Pokaż tylko bieżący pulpit",
        switcherCurrentSpaceOnlyCaption: "Wyświetla listę tylko okien z pulpitu, na którym się znajdujesz. Wybranie okna nigdy nie przenosi Cię na inny pulpit.",
        shelfFileMissing: "Plik już nie istnieje",
        previewSizeSmall: "Mały",
        mixerSoundEffectsOutputTitle: "Dźwięki systemowe",
        mixerSoundEffectsOutputTooltip: "Wybierz, gdzie mają być odtwarzane alerty i efekty dźwiękowe",
        monitorOpenActivityMonitor: "Otwórz Monitor aktywności",
        dockClickHide: "Kliknij ikonę Docka, aby ukryć aplikację",
        dockClickHideCaption: "Aktywna aplikacja ukrywa się po kliknięciu jej ikony w Docku. Kliknij ponownie, aby go przywrócić.",
        monitorMemoryMetricLabel: "Sposób pomiaru pamięci",
        memoryMetricUsed: "Używana pamięć",
        memoryMetricApp: "Pamięć aplikacji",
        keepAwakeRightClickToggle: "Kliknięcie prawym przyciskiem ikony paska menu przełącza „Nie usypiaj”",
        keepAwakeRightClickToggleCaption: "Zastępuje menu kontekstowe wyświetlane prawym przyciskiem myszy.",
        urlCleanerRulesTitle: "Reguły czyszczenia",
        urlCleanerRulesCaption: "Witryna dołącza te parametry do własnych łączy udostępnianych, aby śledzić, skąd pochodzi łącze. Włączone, nazwa jest usuwana podczas czyszczenia łącza; wyłączony, pozostaje. Dodane nazwy można usunąć.",
        urlCleanerRulesCoverageCaption: "Lista obejmuje różne ścieżki udostępniania witryny (strona internetowa, aplikacja, pokój na żywo), dlatego jest długa; prawdziwe łącze zwykle przenosi tylko dwa do czterech z nich.",
        urlCleanerRulesAllSites: "Wszystkie witryny",
        urlCleanerRulesCountSingular: "1 parametr",
        urlCleanerRulesCountPluralFormat: "Parametry: %d",
        urlCleanerRulesAddSite: "Dodaj witrynę",
        urlCleanerRulesParameterPlaceholder: "Nazwa parametru",
        urlCleanerRulesMatchCaption: "Wpisz nazwę po lewej stronie znaku =, na przykład utm_source. Nazwa, która pasuje, usuwa ten jeden parametr z łącza, a resztę pozostawia bez zmian.",
        urlCleanerRulesAddButton: "Dodaj",
        urlCleanerRulesRemoveButton: "Usuń nazwę",
        urlCleanerRulesRemoveSiteButton: "Wyłącz wszystkie reguły dla tej witryny",
        urlCleanerRemovedFormat: "Usunięto %@",
        switcherSearchPin: "Przypnij wyszukiwanie klawiszem S",
        switcherSearchPinCaption: "S rozpoczyna wyszukiwanie i przypina przełącznik do otwarcia, więc wpisanie nie powoduje już wyświetlania znaków specjalnych, gdy skrót używa ⌥, a wyszukiwanie rozpoczynające się od Q lub W nie powoduje już zamykania okna ani omyłkowego zamykania aplikacji.",
        invertVerticalScroll: "Odwróć przewijanie w pionie",
        invertHorizontalScroll: "Odwróć przewijanie w poziomie",
        scrollHorizontalName: "Przewiń w bok, przytrzymując klawisz",
        scrollHorizontalModifierLabel: "Klawisz modyfikujący",
        scrollHorizontalCommandKey: "Command",
        scrollHorizontalCaption: "Przytrzymaj tylko wybrany modyfikator, aby przewijać pionowe kółko myszy w poziomie. Pozostałe kombinacje klawiszy pozostają niezmienione.",
        switcherShowShortcutHints: "Pokaż wskazówki dotyczące skrótów",
        switcherShowShortcutHintsCaption: "Pokazuje skróty do aplikacji i okien pod ikonami.",
        uninstallerHomebrewPackageFormat: "%@ zostanie również usunięty z Homebrew.",
        shelfEdgeToggle: "Otwórz w pobliżu krawędzi ekranu",
        shelfEdgeCaption: "Przeciągnij plik w kierunku krawędzi ekranu, aby zajrzeć do półki. Upuść go tam lub pociągnij, a cofnie się.",
        focusFollowsMouseName: "Aktywuj okno pod wskaźnikiem",
        focusFollowsMouseCaption: "Aktywuje okno pod wskaźnikiem.",
        focusFollowsMouseDelay: "Opóźnienie po najechaniu",
        focusFollowsMouseRaise: "Przenieś okno na pierwszy plan",
        focusFollowsMouseWaitForStop: "Poczekaj, aż wskaźnik się zatrzyma",
        switcherMinimizedPlacementLabel: "Zminimalizowane okna",
        switcherTreatHiddenAppsLikeMinimized: "Traktuj ukryte aplikacje jak zminimalizowane okna",
        switcherMinimizedPlacementNormal: "Standardowa kolejność",
        switcherMinimizedPlacementEnd: "Umieść na końcu",
        switcherMinimizedPlacementHidden: "Ukryj",
        switcherShowFullscreenWindows: "Pokaż okna pełnoekranowe",
        switcherScreenPlacementLabel: "Wyświetl na",
        switcherScreenPlacementPointer: "Ekran ze wskaźnikiem",
        switcherScreenPlacementMenuBar: "Ekran z paskiem menu",
        switcherScreenPlacementActiveWindow: "Ekran z aktywnym oknem",
        switcherScreenPlacementCaption: "Na którym wyświetlaczu otwiera się przełącznik, gdy podłączonych jest więcej niż jeden.",
        switcherCurrentDisplayOnly: "Pokaż tylko bieżący ekran",
        switcherCurrentDisplayOnlyCaption: "Wyświetla tylko okna na wyświetlaczu pod wskaźnikiem. Jeśli ten wyświetlacz nie ma okien, przełącznik nie otworzy się.",
        smoothScrollResponseLabel: "Reakcja",
        smoothScrollCoastLabel: "Bezwładność",
        mouseAccelerationName: "Wyłącz przyspieszenie myszy",
        mouseAccelerationCaption: "Usuwa przyspieszenie wskaźnika dla podłączonych myszy. Twoje poprzednie ustawienie zostanie przywrócone, gdy zostanie wyłączone lub Vorssaint zakończy działanie.",
        linearScrollName: "Przewijanie liniowe",
        linearScrollCaption: "Każde nacięcie kółka myszy przewija się na tę samą odległość, niezależnie od tego, jak szybko się obraca. Nie ma to wpływu na gładzik.",
        linearScrollLinesLabel: "Linie na krok",
        shelfClearOnClose: "Wyczyść po zamknięciu",
        shelfClearOnCloseCaption: "Opróżnia półkę dopiero po kliknięciu przycisku zamykania. Automatyczne ukrywanie i zwijanie pozwala zachować elementy.",
        shelfShortcutFinderSelection: "Dodaj zaznaczenie z Findera skrótem",
        shelfShortcutFinderSelectionCaption: "Mając Finder na pierwszym planie, skrót otwiera półkę z wybranymi plikami, które już się na niej znajdują. Gdy nic nie jest zaznaczone, otwiera się jak zwykle.",
        spacesOrderName: "Zachowaj stałą kolejność biurek Spaces",
        spacesOrderCaption: "Wyłącza automatyczne zmienianie kolejności biurek Spaces według ostatniego użycia. Biurka pozostają w ustalonej kolejności. Po wyłączeniu funkcji wraca poprzednie ustawienie. Zastosowanie zmiany może wymagać jednorazowego ponownego uruchomienia Docka."
    )
}
