// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// ภาษาไทย — โครงสร้างและคำแปลส่วนติดต่อผู้ใช้
extension Strings {
    static let th = Strings(
        statusIdleTooltip: "Vorssaint: สลีปตามปกติ",
        statusActiveUntil: "Vorssaint: ตื่นอยู่จนถึง",
        statusActiveIndefinite: "Vorssaint: ตื่นอยู่ตลอดเวลาจนกว่าจะปิด",
        menuEnableAwake: "เปิดการคงสถานะตื่น",
        menuDisableAwake: "ปิดการคงสถานะตื่น",
        menuActivateFor: "เปิดใช้งานเป็นเวลา…",
        menuSettings: "การตั้งค่า…",
        menuAbout: "เกี่ยวกับ Vorssaint",
        menuQuit: "ออกจาก Vorssaint",
        menuHide: "ซ่อน Vorssaint",
        menuHideOthers: "ซ่อนอื่นๆ",
        menuShowAll: "แสดงทั้งหมด",
        menuEdit: "แก้ไข",
        menuUndo: "เลิกทำ",
        menuRedo: "ทำซ้ำ",
        actionClear: "ล้าง",
        actionRemove: "เอาออก",
        actionBack: "ย้อนกลับ",
        actionSearch: "ค้นหา",
        actionMute: "ปิดเสียง",
        actionUnmute: "เปิดเสียง",
        actionPlay: "เล่น",
        actionPause: "หยุดชั่วคราว",
        menuCut: "ตัด",
        menuCopy: "คัดลอก",
        menuPaste: "วาง",
        menuSelectAll: "เลือกทั้งหมด",
        menuWindow: "หน้าต่าง",
        menuMinimize: "ย่อ",
        menuZoom: "ซูม",
        menuClose: "ปิด",
        minutes15: "15 นาที",
        minutes30: "30 นาที",
        hour1: "1 ชั่วโมง",
        hours2: "2 ชั่วโมง",
        hours4: "4 ชั่วโมง",
        hours8: "8 ชั่วโมง",
        indefinitely: "ไม่จำกัดเวลา",
        indefinite: "ไม่มีกำหนด",
        panelSettings: "การตั้งค่า",
        panelQuit: "ออกจากแอป",
        panelHotkeyHint: "สลับการทำงานด้วยปุ่มลัด",
        keepAwakeTitle: "คงสถานะตื่น",
        keepAwakeEndsIn: "จะสิ้นสุดในอีก",
        keepAwakeUntilDisabled: "ทำงานจนกว่าคุณจะปิด",
        keepAwakeNormalRules: "Mac ปฏิบัติตามการตั้งค่าพลังงานปกติ",
        keepAwakeUntilLabel: "จนถึงเวลา",
        keepAwakeUntilStart: "เริ่ม",
        keepAwakeOptions: "ตัวเลือก",
        keepAwakeMouseJiggle: "ขยับตัวชี้เมาส์เล็กน้อย",
        keepAwakeMouseJiggleCaption: "ขยับตัวชี้เมาส์เล็กน้อยตามช่วงเวลาที่กำหนดเพื่อป้องกันการสลีป",
        keepAwakeMouseJiggleInterval: "ช่วงเวลา",
        keepAwakeActiveIconLabel: "ไอคอนขณะทำงาน",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "กาแฟ",
        keepAwakeActiveIconEye: "ดวงตา",
        keepAwakeActiveIconMoon: "ดวงจันทร์",
        keepAwakeActiveIconLight: "หลอดไฟ",
        keepAwakeIconTintLabel: "สีไอคอนขณะทำงาน",
        keepAwakeIconTintOrange: "สีส้ม",
        keepAwakeIconTintGreen: "สีเขียว",
        keepAwakeIconTintBlue: "สีฟ้า",
        keepAwakeIconTintPurple: "สีม่วง",
        keepAwakeIconTintPink: "สีชมพู",
        keepAwakeIconTintNone: "ไม่มีสี",
        durationLabel: "ระยะเวลา",
        clamshellTitle: "ทำงานต่อเมื่อพับฝาจอ (Clamshell)",
        clamshellOnCaption: "ปิดการสลีปโดยสมบูรณ์ โปรดระวังเรื่องการใช้พลังงานแบตเตอรี่",
        clamshellNeedsSession: "ทำงานทุกครั้งที่เปิดโหมดคงสถานะตื่น",
        clamshellReady: "พร้อมใช้งาน สลับเปิด/ปิดได้โดยไม่ต้องใส่รหัสผ่าน",
        clamshellNeedsPassword: "จะถามรหัสผ่านผู้ดูแลระบบเพียงครั้งเดียว",
        systemSection: "ระบบ",
        temperatures: "อุณหภูมิ",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "แบตเตอรี่",
        usageSection: "การใช้งานฮาร์ดแวร์",
        memorySection: "หน่วยความจำ",
        memoryPressure: "แรงดันหน่วยความจำ",
        memorySwapUsed: "สว็อปที่ใช้",
        memoryCompressed: "บีบอัดแล้ว",
        memoryCachedFiles: "ไฟล์แคช",
        pressureNormal: "ปกติ",
        pressureWarning: "เตือน",
        pressureCritical: "วิกฤต",
        monitorUnavailable: "ไม่พบเซ็นเซอร์บน Mac เครื่องนี้",
        energyAppsTitle: "แอปที่ใช้พลังงานสูง",
        energyAppsIdle: "ไม่มีแอปที่ใช้พลังงานสูงอย่างมีนัยสำคัญ",
        notifySessionEndedTitle: "สิ้นสุดเซสชันคงสถานะตื่น",
        notifySessionEndedBody: "หมดเวลาแล้ว Mac จะกลับเข้าสู่โหมดสลีปตามปกติ",
        notifyBatteryTitle: "Vorssaint ปิดการทำงาน",
        notifyBatteryBody: "แบตเตอรี่เหลือน้อย กลับสู่โหมดสลีปตามปกติเพื่อประหยัดพลังงาน",
        adminPromptClamshellOn: "Vorssaint ต้องใช้รหัสผ่านของคุณเพื่อให้ Mac ทำงานต่อได้แม้พับฝาจอลง",
        adminPromptClamshellOff: "Vorssaint ต้องใช้รหัสผ่านของคุณเพื่อคืนค่าการสลีปตามปกติของ Mac",
        adminPromptRecover: "Vorssaint ถูกปิดขณะที่โหมดสลีปของ Mac ยังปิดอยู่ กรุณาใส่รหัสผ่านเพื่อคืนค่าการสลีปตามปกติ",
        adminPromptUpdate: "Vorssaint ต้องใช้รหัสผ่านของคุณเพื่อติดตั้งการอัปเดต",
        adminPromptSudoersInstall: "Vorssaint จะสร้างกฎแบบจำกัด (เฉพาะคำสั่ง pmset disable sleep) เพื่อให้สามารถสลับโหมดพับฝาได้โดยไม่ต้องถามรหัสผ่านซ้ำอีก นี่เป็นครั้งเดียวที่ต้องใส่รหัสผ่าน",
        adminPromptSudoersRemove: "Vorssaint จะลบกฎโหมดพับฝาที่ไม่ต้องใส่รหัสผ่านออก",
        settingsTitle: "การตั้งค่า Vorssaint",
        tabGeneral: "ทั่วไป",
        tabEnergy: "พลังงาน",
        tabMouse: "เมาส์และแทร็กแพด",
        tabSwitcher: "ตัวสลับแอป",
        tabAdvanced: "ขั้นสูง",
        tabAbout: "เกี่ยวกับ",
        tabReleaseNotes: "มีอะไรใหม่",
        releaseNotesOnUpdateToggle: "แสดงสิ่งที่มีใหม่หลังจากการอัปเดต",
        minimalWindowPreviews: "ภาพตัวอย่างแบบมินิมอล",
        minimalWindowPreviewsCaption: "ซ่อนชื่อหน้าต่าง ปุ่ม และรายละเอียดตกแต่งในตัวอย่าง Dock และตัวสลับแอป เพื่อความเรียบง่าย",
        previewSizeLabel: "ขนาดตัวอย่าง",
        previewSizeNormal: "ปกติ",
        previewSizeLarge: "ใหญ่",
        previewSizeXLarge: "ใหญ่พิเศษ",
        settingsGroupFeatures: "ฟีเจอร์",
        advancedResetSection: "สิทธิ์การเข้าถึง",
        advancedResetDescription: "ล้างสิทธิ์ทั้งหมดที่เคยมอบให้ Vorssaint (การช่วยการเข้าถึง, การบันทึกหน้าจอ, การเข้าถึงดิสก์เต็มรูปแบบ ฯลฯ) รวมถึงรายการเข้าสู่ระบบและกฎโหมดพับฝา เหมาะสำหรับเริ่มต้นใหม่ก่อนถอนการติดตั้ง โดยแอปจะยังไม่ถูกลบ",
        advancedClearButton: "ล้างสิทธิ์ทั้งหมด",
        advancedCleared: "ล้างสิทธิ์เรียบร้อยแล้ว",
        advancedClearFailed: "ไม่สามารถล้างสิทธิ์บางรายการหรือกฎโหมดพับฝาได้ กรุณาลองใหม่อีกครั้งและอนุญาตเมื่อมีหน้าต่างถามรหัสผ่าน",
        advancedClearConfirmTitle: "ต้องการล้างสิทธิ์ทั้งหมดหรือไม่?",
        advancedClearConfirmBody: "ฟีเจอร์ที่ต้องใช้สิทธิ์จะหยุดทำงานจนกว่าคุณจะอนุญาตใหม่อีกครั้ง การตั้งค่าของคุณจะยังคงอยู่",
        advancedUninstallSection: "ถอนการติดตั้ง",
        advancedUninstallDescription: "ล้างสิทธิ์ทั้งหมด ลบการตั้งค่า และย้าย Vorssaint ไปยังถังขยะอย่างสมบูรณ์โดยไม่ทิ้งไฟล์ตกค้างไว้ เมื่อเสร็จแล้วแอปจะปิดตัวลง คุณสามารถติดตั้งใหม่ได้ตลอดเวลา",
        advancedUninstallButton: "ถอนการติดตั้ง Vorssaint โดยสมบูรณ์",
        advancedUninstallConfirmTitle: "ถอนการติดตั้ง Vorssaint หรือไม่?",
        advancedUninstallConfirmBody: "Vorssaint จะล้างสิทธิ์ ลบไฟล์การตั้งค่า และย้ายตัวแอปไปที่ถังขยะจากนั้นจะปิดตัวลง ไฟล์จะยังอยู่ในถังขยะจนกว่าคุณจะสั่งล้างถังขยะ",
        advancedUninstallFailedTitle: "การถอนการติดตั้งหยุดชะงัก",
        advancedUninstallFailedBody: "Vorssaint ไม่สามารถคืนค่าการตั้งค่าระบบบางอย่างได้ เช่น การสลีป ความเร็วพัดลม หรือการเร่งความเร็วเมาส์ จึงยังไม่มีการลบไฟล์ใดๆ กรุณาลองใหม่อีกครั้ง",
        launchAtLogin: "เปิดเมื่อเข้าสู่ระบบ",
        languageLabel: "ภาษา",
        menuBarSection: "แถบเมนู",
        showCountdown: "แสดงเวลานับถอยหลังข้างไอคอน",
        globalHotkeySection: "ปุ่มลัดส่วนกลาง (Global Shortcut)",
        hotkeyToggle: "เปิดใช้งานปุ่มลัดสำหรับ “คงสถานะตื่น”",
        hotkeyCaption: "ใช้งานได้จากทุกแอป ไม่ต้องใช้สิทธิ์พิเศษ",
        sessionSection: "เซสชันคงสถานะตื่น",
        defaultDurationLabel: "ระยะเวลาเริ่มต้น",
        keepAwakeAutoStart: "เปิดการคงสถานะตื่นทันทีเมื่อเปิด Vorssaint",
        keepAwakeAutoStartCaption: "เริ่มเซสชันด้วยระยะเวลาเริ่มต้นโดยอัตโนมัติ",
        batteryProtectionSection: "การป้องกันแบตเตอรี่",
        batteryDisableBelow: "ปิดการทำงานอัตโนมัติเมื่อแบตเตอรี่ต่ำกว่า",
        batteryNever: "ไม่เลย",
        batteryProtectionCaption: "ป้องกันไม่ให้การลืมปิดเซสชันทำให้แบตเตอรี่ MacBook หมด",
        clamshellSection: "โหมดพับฝา (Clamshell)",
        configuring: "กำลังกำหนดค่า…",
        sudoersFailed: "ไม่สามารถเปิดโหมดพับฝาได้ กรุณาลองใหม่อีกครั้ง",
        clamshellExplanation: "“ทำงานต่อเมื่อพับฝาจอ” จะปิดโหมดสลีปอย่างสมบูรณ์ในขณะที่เปิดการคงสถานะตื่นอยู่ และจะคืนค่าเดิมอัตโนมัติเมื่อสิ้นสุดเซสชันหรือออกจากแอป แนะนำให้ใช้ขณะเสียบสายชาร์จ",
        dimScreenOnLidCloseTitle: "หรี่ความสว่างหน้าจอจนสุด",
        dimScreenOnLidCloseCaption: "หรี่ความสว่างหน้าจอเมื่อปิดฝาลง และคืนค่าความสว่างเมื่อเปิดฝาขึ้นมา",
        scrollSection: "การเลื่อน",
        invertMouseScroll: "สลับทิศทางการเลื่อนเมาส์",
        invertMouseScrollCaption: "กลับทิศทางของล้อเลื่อนเมาส์",
        scrollTrackpadNote: "แทร็กแพดจะไม่ได้รับผลกระทบ เพื่อรักษาการเลื่อนที่เป็นธรรมชาติของ macOS",
        scrollActiveNow: "กำลังสลับทิศทางการเลื่อนเมาส์อยู่ในขณะนี้",
        mouseNavigationActiveNow: "ปุ่มด้านข้างของเมาส์กำลังทำงานอยู่",
        smoothScrollName: "การเลื่อนอย่างนุ่มนวล (Smooth Scroll)",
        smoothScrollCaption: "แปลงการหมุนล้อเมาส์แต่ละคลิกให้เป็นการเลื่อนที่นุ่มนวลเป็นธรรมชาติ แทร็กแพดจะไม่ได้รับผลกระทบ",
        smoothScrollStepLabel: "ความเร็วขั้น",
        mouseNavigationSection: "การนำทางด้วยเมาส์",
        mouseNavigationEnable: "ใช้ปุ่มด้านข้างสำหรับย้อนกลับและไปข้างหน้า",
        mouseNavigationCaption: "เปลี่ยนปุ่มด้านข้างของเมาส์ให้เป็นคำสั่งย้อนกลับ/ไปข้างหน้าใน Finder, เว็บบราวเซอร์ และแอปที่รองรับ",
        middleClickSection: "คลิกปุ่มกลาง (Middle Click)",
        middleClickEnable: "คลิกสามนิ้วบนแทร็กแพดเพื่อคลิกปุ่มกลาง",
        middleClickEnableCaption: "แตะกดแทร็กแพดด้วยสามนิ้วเพื่อทำหน้าที่เหมือนคลิกล้อเมาส์: เปิดลิงก์ในแท็บใหม่ ปิดแท็บ และคำสั่งอื่นๆ",
        middleClickDragConflict: "คำสั่งลากด้วยสามนิ้วของ macOS เปิดอยู่และใช้ท่าทางเดียวกัน ปิดได้ที่ การตั้งค่าระบบ > การช่วยการเข้าถึง > การควบคุมตัวชี้ > ตัวเลือกแทร็กแพด",
        middleClickTapPicker: "แตะเบาๆ เพื่อคลิกปุ่มกลาง",
        middleClickTapOff: "ปิด",
        middleClickTapThreeFingers: "3 นิ้ว",
        middleClickTapFourFingers: "4 นิ้ว",
        middleClickTapCaption: "แตะเบาๆ ด้วยจำนวนนิ้วที่กำหนดโดยไม่ต้องกดลงไป เพื่อคลิกปุ่มกลาง",
        quickToolsTab: "แผงเครื่องมือด่วน",
        quickToolShortcutToggle: "เปิดใช้งานปุ่มลัดสากล",
        ocrName: "คัดลอกข้อความจากหน้าจอ (OCR)",
        ocrCaption: "ลากเลือกพื้นที่บนหน้าจอเพื่อตรวจหาและคัดลอกข้อความพร้อมนำไปวางได้ทันที",
        ocrCopied: "คัดลอกข้อความแล้ว",
        ocrNoText: "ไม่พบข้อความในพื้นที่ที่เลือก",
        colorPickerName: "เครื่องมือดูดสี (Color Picker)",
        colorPickerCaption: "จิ้มดูดสีจากพิกเซลบนหน้าจอและคัดลอกรหัสสีในรูปแบบที่คุณต้องการ",
        colorPickerFormatLabel: "รูปแบบรหัสสี",
        colorPickerBareHexToggle: "คัดลอกโดยไม่มีเครื่องหมาย # นำหน้า",
        colorPickerPickNow: "ดูดสีเดี๋ยวนี้",
        micMuteName: "ปิดเสียงไมโครโฟน",
        micUnmuteName: "เปิดเสียงไมโครโฟน",
        micMuteCaption: "ตัดเสียงไมโครโฟนของ Mac ได้อย่างรวดเร็วด้วยการคลิกหรือปุ่มลัดจากทุกแอป",
        micMutedHUD: "ปิดเสียงไมโครโฟนแล้ว",
        micUnmutedHUD: "เปิดเสียงไมโครโฟนแล้ว",
        micMutePartialHUD: "ไม่สามารถปิดเสียงไมโครโฟนบางตัวได้",
        micUnmutePartialHUD: "ไมโครโฟนบางตัวยังคงปิดเสียงอยู่",
        micMuteMenuBarToggle: "แสดงบนแถบเมนูขณะปิดเสียง",
        micMuteMenuBarCaption: "แสดงไอคอนไมโครโฟนพร้อมกากบาทสีแดงบนแถบเมนูเมื่อไมโครโฟนถูกปิดเสียง",
        pastePlainName: "วางเป็นข้อความธรรมดา (Paste as Plain Text)",
        pastePlainCaption: "วางข้อความที่คัดลอกโดยตัดสี แบบอักษร หรือการจัดรูปแบบออกทั้งหมด",
        launcherName: "แผงเครื่องมือด่วน",
        launcherCaption: "แผงลอยรวบรวมเครื่องมือโปรดของคุณ เรียกใช้งานด้วยปุ่มลัดได้จากทุกที่",
        launcherOpenNow: "เปิดแผงเครื่องมือด่วน",
        launcherEditHint: "คลิกปุ่มปรับแต่งเพื่อเลือก ซ่อน หรือลากจัดลำดับเครื่องมือ",
        launcherEmptyState: "เครื่องมือทั้งหมดถูกซ่อนอยู่ คลิกปุ่มปรับแต่งเพื่อเลือกแสดงอีกครั้ง",
        launcherAddSection: "เพิ่มกลับเข้ามา",
        launcherKeysHint: "ใช้ปุ่มลูกศรเพื่อเลือก, Enter เพื่อเปิด, หรือกดเลข 1 ถึง 9 เพื่อเปิดทันที",
        switcherSection: "ตัวสลับแอป (App Switcher)",
        switcherEnable: "เปิดใช้ตัวสลับแอป Vorssaint",
        switcherEnableCaption: "สลับระหว่างแอปและหน้าต่าง รวมถึงหน้าต่างที่ย่อไว้และหน้าต่างหลายบานจากแอปเดียวกัน",
        switcherUsageHint: "กดปุ่มลัดค้างไว้เพื่อเลื่อนดู ปล่อยเพื่อเลือกหน้าต่าง; Shift หรือ ← เพื่อถอยหลัง; W เพื่อปิดหน้าต่าง; Q เพื่อออกจากแอป; Esc เพื่อยกเลิก",
        switcherNoWindows: "ไม่มีหน้าต่างที่เปิดอยู่",
        switcherIconRowMode: "แสดง %@ พร้อมไอคอนขนาดใหญ่",
        switcherIconRowModeCaption: "แสดงไอคอนเดี่ยวต่อหนึ่งแอปพร้อมภาพตัวอย่างหน้าต่างของแอปนั้นด้านบน",
        switcherSimpleModeCaption: "แสดงเฉพาะไอคอนแอปและชื่อหน้าต่างโดยไม่ต้องแสดงภาพตัวอย่าง",
        switcherShortcutHintApps: "แอป",
        switcherShortcutHintWindows: "หน้าต่าง",
        switcherWindowShortcutCaption: "เปิดตัวสลับเฉพาะหน้าต่างของแอปที่อยู่ด้านหน้าสุด",
        switcherTakeOverSystemShortcuts: "แทนที่ปุ่มลัดระบบ ⌘Tab และ ⌘`",
        switcherTakeOverSystemShortcutsCaption: "แทนที่ปุ่มลัดสลับแอปและหน้าต่างของ macOS เฉพาะในขณะที่ตัวสลับของ Vorssaint กำลังทำงาน",
        switcherAppearanceDelay: "ความล่าช้าในการแสดงผล",
        switcherAppearanceDelayCaption: "ระยะเวลาที่ต้องกดปุ่มลัดค้างไว้ก่อนที่หน้าต่างตัวสลับจะปรากฏขึ้น",
        switcherInstantSelection: "เลือกทันที",
        switcherInstantSelectionCaption: "เลื่อนตำแหน่งไฮไลต์และเปลี่ยนหน้าต่างทันทีเมื่อคุณเลื่อนดูแอป",
        switcherMergeTabs: "รวมหน้าต่างของแอปเป็นรายการเดียว",
        switcherMergeTabsCaption: "รวมหน้าต่างทั้งหมดของแอปเดียวกันให้แสดงเป็นรายการเดียวในตัวสลับ",
        switcherWindowlessApps: "แอปที่ไม่มีหน้าต่างเปิดอยู่",
        switcherWindowlessAppsCaption: "เลือกแสดงแอปที่กำลังทำงานอยู่แต่ไม่มีหน้าต่างเปิดไว้ในตัวสลับแอป",
        switcherWindowlessAppsOff: "ไม่แสดง",
        switcherWindowlessAppsFinder: "เฉพาะ Finder เท่านั้น",
        switcherWindowlessAppsAll: "แอปทั้งหมด",
        switcherNoOpenWindow: "ไม่มีหน้าต่างเปิดอยู่",
        switcherOtherDesktop: "เดสก์ท็อปอื่น",
        dockPreviewName: "ตัวอย่าง Dock (Dock Preview)",
        dockPreviewEnable: "ดูภาพตัวอย่างหน้าต่างจาก Dock",
        dockPreviewEnableCaption: "ชี้เมาส์เหนือแอปบน Dock เพื่อดูภาพตัวอย่างหน้าต่างของแอปนั้น แล้วคลิกหน้าต่างที่ต้องการเปิด",
        dockPreviewCurrentSpaceOnlyCaption: "แสดงเฉพาะหน้าต่างบนเดสก์ท็อปปัจจุบันสำหรับ Dock Preview",
        dockPreviewBackgroundOpacity: "ความทึบของพื้นหลังแผง",
        dockPreviewBackgroundOpacityCaption: "ปรับลดลงเพื่อมองเห็นเนื้อหาด้านหลังแผงตัวอย่างได้มากขึ้น",
        dockPreviewOpenDelay: "ความล่าช้าในการเปิดตัวอย่าง",
        dockPreviewOpenDelayCaption: "ระยะเวลาที่ตัวชี้เมาส์ต้องวางค้างบนไอคอน Dock ก่อนที่แผงตัวอย่างจะเปิดขึ้น",
        dockPreviewQuitAppOnClose: "ออกจากแอปด้วยปุ่ม ×",
        dockPreviewQuitAppOnCloseCaption: "ในตัวอย่าง Dock การคลิกปุ่ม × จะเป็นการออกจากแอปนั้นทั้งหมดแทนที่จะปิดเพียงหน้าต่างเดียว",
        dockPreviewKeepDockVisible: "เปิด Dock ค้างไว้เสมอขณะดูตัวอย่าง (ทดลอง)",
        dockPreviewKeepDockVisibleCaption: "หยุดการซ่อน Dock อัตโนมัติชั่วคราวขณะแสดงตัวอย่าง และคืนค่าเดิมเมื่อเลื่อนเมาส์ออก",
        dockPreviewOrderByCreation: "เรียงลำดับหน้าต่างตามเวลาที่สร้าง",
        dockPreviewOrderByCreationCaption: "แสดงหน้าต่างที่สร้างก่อนขึ้นก่อน แทนที่จะเรียงตามหน้าต่างที่ใช้งานล่าสุด",
        dockClickMinimize: "คลิกไอคอน Dock เพื่อย่อหน้าต่าง",
        dockClickMinimizeCaption: "หน้าต่างของแอปที่กำลังใช้งานอยู่จะถูกย่อลงเมื่อคุณคลิกที่ไอคอน Dock และคลิกอีกครั้งเพื่อนำกลับมา",
        dockClickCycleWindows: "คลิกไอคอน Dock เพื่อสลับวนหน้าต่าง",
        dockClickCycleWindowsCaption: "คลิกไอคอน Dock ของแอปที่กำลังใช้งานเพื่อสลับวนไปมาระหว่างหน้าต่างของแอปนั้น เหมือนการกด ⌘`",
        dockPreviewActiveNow: "เปิดใช้งานใน Dock แล้ว",
        dockPreviewDockUnavailable: "ไม่สามารถอ่านรายการใน Dock ได้",
        dockPreviewAutohideBeta: "ฟีเจอร์เบต้า อาจพบข้อบกพร่องบางประการได้",
        dockPreviewOpenWindow: "เปิดหน้าต่าง",
        dockPreviewCloseWindow: "ปิดหน้าต่าง",
        dockPreviewMinimizeWindow: "ย่อหน้าต่าง",
        dockPreviewRestoreWindow: "คืนค่าหน้าต่าง",
        dockPreviewPinPanel: "ปักหมุดแผงตัวอย่าง",
        dockPreviewUnpinPanel: "เลิกปักหมุดแผงตัวอย่าง",
        dockPreviewPinned: "ปักหมุดแล้ว",
        dockPreviewClosePanel: "ปิดแผงตัวอย่าง",
        dockPreviewPreviousWindow: "หน้าต่างก่อนหน้า",
        dockPreviewNextWindow: "หน้าต่างถัดไป",
        cutPasteName: "ตัดและวาง (Cut & Paste)",
        cutPasteEnable: "ตัดและวางไฟล์ใน Finder",
        cutPasteEnableCaption: "กด ⌘X เพื่อตัด และกด ⌘V เพื่อย้ายไฟล์และโฟลเดอร์ใน Finder",
        cutPasteShowHUD: "แสดงแถบแจ้งเตือนลอย",
        cutPasteShowHUDCaption: "แสดงแถบสถานะลอยพร้อมชื่อไฟล์ที่ตัดในขณะที่ Finder กำลังทำงาน",
        cutPasteHowTitle: "วิธีใช้งาน",
        cutPasteStep1: "เลือกไฟล์ใน Finder แล้วกด ⌘X เพื่อตัด",
        cutPasteStep2: "เปิดโฟลเดอร์ปลายทางแล้วกด ⌘V เพื่อย้ายไฟล์มาที่นี่",
        cutPasteTextNote: "ในช่องป้อนข้อความ (เช่น ขณะเปลี่ยนชื่อไฟล์) ⌘X และ ⌘V จะยังคงทำงานตัดและวางข้อความตามปกติ",
        cutPasteActiveNow: "พร้อมใช้งานคำสั่งตัดใน Finder",
        cutPasteAutomationNote: "macOS จะขออนุญาตควบคุม Finder ในครั้งแรกที่ใช้งาน",
        cutReadyTitle: "ตัดแล้ว",
        cutReadyHint: "กด ⌘V ในโฟลเดอร์ปลายทางเพื่อย้าย",
        cutCancel: "ยกเลิกการตัด",
        cutDoneTitle: "ย้ายเรียบร้อยแล้ว!",
        cutMovedSingular: "ย้ายแล้ว 1 รายการ",
        cutMovedPluralFormat: "ย้าย %d รายการแล้ว",
        cutSomeFailed: "ไม่สามารถย้ายบางรายการได้",
        cutMovingTitle: "กำลังย้าย…",
        cutMovingCountFormat: "%d จาก %d",
        autoQuitName: "ออกจากแอปเมื่อปิดหน้าต่าง (Auto Quit)",
        autoQuitEnable: "ออกจากแอปอัตโนมัติเมื่อปิดหน้าต่างสุดท้าย",
        autoQuitEnableCaption: "การปิดหน้าต่างสุดท้ายของแอปจะเป็นการออกจากแอปนั้นด้วย",
        autoQuitActiveNow: "เปิดใช้งานอยู่ในขณะนี้",
        autoQuitHowTitle: "หลักการทำงาน",
        autoQuitStep1: "ปิดหน้าต่างสุดท้ายของแอป (กด ⌘W หรือคลิกปุ่มสีแดง)",
        autoQuitStep2: "แอปจะปิดตัวลงอัตโนมัติ โดยกล่องถาม “ต้องการบันทึกการเปลี่ยนแปลงหรือไม่?” จะยังคงแสดงตามปกติ",
        autoQuitPredictableNote: "แอปที่ทำงานเบื้องหลังโดยไม่มีหน้าต่างเป็นปกติจะไม่มีวันถูกปิด",
        autoQuitOngoingWorkNote: "บางแอปจะซ่อนหน้าต่างสุดท้ายขณะทำงานต่อเนื่อง เช่น ตัวบันทึกหน้าจอเมื่อเริ่มอัดวิดีโอ แอปเหล่านี้จะถูกออกจากแอปด้วยเช่นกัน ยกเว้นจะถูกเพิ่มไว้ในรายการข้อยกเว้น",
        autoQuitExceptionsTitle: "รายการข้อยกเว้น",
        autoQuitExceptionsCaption: "แอปในรายการนี้จะยังคงเปิดทำงานต่อไปแม้ไม่มีหน้าต่างเปิดอยู่",
        autoQuitExceptionsEmpty: "ไม่มีรายการข้อยกเว้น",
        autoQuitAddApp: "เพิ่มแอป…",
        uninstallerName: "โปรแกรมถอนการติดตั้งแอป (App Uninstaller)",
        uninstallerEnableCaption: "ลบแอปพร้อมกับไฟล์แคช การตั้งค่า บันทึกระบบ และไฟล์ตกค้างทั้งหมด",
        uninstallerStep1: "ลากแอปมาวางในการตั้งค่า หรือเลือกแอปจากรายการ",
        uninstallerStep2: "ตรวจสอบไฟล์ที่ตรวจพบและพื้นที่ที่ถูกใช้งาน",
        uninstallerStep3: "ย้ายไฟล์ทั้งหมดที่ต้องการลงถังขยะ โดยจะยังไม่ถูกลบถาวรในทันที",
        uninstallerMenuItem: "ถอนการติดตั้งแอป…",
        uninstallerDropTitle: "ลากแอปมาวางที่นี่",
        uninstallerDropSubtitle: "หรือคลิกเลือกแอปที่ต้องการสแกน",
        uninstallerChoose: "เลือกแอป…",
        uninstallerPickerTitle: "เลือกแอปพลิเคชัน",
        uninstallerPickerSearch: "ค้นหาแอป",
        uninstallerPickerEmpty: "ไม่พบแอป",
        uninstallerEmptyNote: "จะไม่มีการลบไฟล์ใดๆ จนกว่าคุณจะกดยืนยัน",
        uninstallerFDANote: "อนุญาตสิทธิ์การเข้าถึงดิสก์เต็มรูปแบบ (Full Disk Access) เพื่อการสแกนที่ละเอียดยิ่งขึ้น",
        uninstallerFDAGrant: "มอบสิทธิ์การเข้าถึง…",
        uninstallerFDAHint: "เปิด Vorssaint ในรายการ หากไม่มีอยู่ ให้คลิก + และเลือก Vorssaint จากโฟลเดอร์ Applications การตั้งค่าจะมีผลหลังจากเปิดแอปใหม่อีกครั้ง",
        uninstallerFDARelaunch: "เปิดแอปใหม่อีกครั้ง",
        uninstallerScanning: "กำลังสแกนไฟล์…",
        uninstallerRemoving: "กำลังย้ายไปที่ถังขยะ…",
        uninstallerFoundTitle: "พบไฟล์ที่เกี่ยวข้อง",
        uninstallerSelectedFormat: "เลือก %1$d จาก %2$d รายการ",
        uninstallerRemove: "ย้ายไปที่ถังขยะ",
        uninstallerCancel: "ยกเลิก",
        uninstallerConfirmationExpired: "การยืนยันนี้หมดอายุแล้ว กรุณาตรวจสอบรายการใหม่อีกครั้งและกดยืนยัน",
        uninstallerDoneTitle: "เสร็จสิ้น!",
        uninstallerFreedFormat: "คืนพื้นที่ได้ %@",
        uninstallerSomeFailed: "บางรายการไม่สามารถย้ายลงถังขยะได้",
        uninstallerFailedNeedsFDA: "ข้อมูลของแอปใน Sandbox สามารถลบได้เมื่อมีสิทธิ์การเข้าถึงดิสก์เต็มรูปแบบเท่านั้น รหัสผ่านผู้ดูแลระบบไม่สามารถใช้แทนได้",
        uninstallerFailedMoreFormat: "และอีก %d รายการ",
        uninstallerAnother: "ถอนการติดตั้งแอปอื่น",
        uninstallerCatApp: "แอปพลิเคชัน",
        uninstallerCatSupport: "ข้อมูลสนับสนุน (Application Support)",
        uninstallerCatCaches: "แคช (Caches)",
        uninstallerCatPreferences: "ไฟล์การตั้งค่า (Preferences)",
        uninstallerCatContainers: "คอนเทนเนอร์ (Containers)",
        uninstallerCatLogs: "บันทึกการทำงาน (Logs)",
        uninstallerCatState: "สถานะที่บันทึกไว้ (Saved Application State)",
        uninstallerCatOther: "ไฟล์อื่นๆ",
        uninstallerCommandBarBrowseTitle: "ถอนการติดตั้งแอปพลิเคชัน",
        uninstallerCommandBarToggle: "แสดงในแถบคำสั่ง",
        uninstallerCommandBarCaption: "ค้นหาและสั่งถอนการติดตั้งแอปผ่านแถบคำสั่งได้ทันที",
        uninstallerCommandBarFinderTitle: "ถอนการติดตั้งแอปที่เลือกใน Finder",
        uninstallerSelectionUnavailable: "เลือกแอปที่ต้องการลบใน Finder หรือเลือกจากรายการ",
        urlCleanerName: "ล้าง URL (URL Cleaner)",
        urlCleanerEnable: "ล้างพารามิเตอร์ติดตามออกจาก URL อัตโนมัติ",
        urlCleanerEnableCaption: "ลบพารามิเตอร์ติดตาม (Tracking Parameters) ออกจากลิงก์ทันทีที่คุณคัดลอกลงคลิปบอร์ด",
        urlCleanerActiveNow: "เปิดใช้งานอยู่ในขณะนี้",
        urlCleanerManualTitle: "ล้าง URL ด้วยตนเอง",
        urlCleanerInputPlaceholder: "วาง URL ที่ต้องการล้างที่นี่",
        urlCleanerOutputPlaceholder: "URL ที่สะอาดปราศจากการติดตามจะแสดงที่นี่",
        urlCleanerCleanButton: "ล้าง URL",
        urlCleanerPasteButton: "วาง",
        urlCleanerCopyButton: "คัดลอก",
        urlCleanerClearButton: "ล้างช่องข้อมูล",
        urlCleanerNoURL: "กรุณาวาง URL ที่ถูกต้อง",
        urlCleanerNoChange: "URL นี้สะอาดแล้ว ไม่จำเป็นต้องล้าง",
        urlCleanerCleaned: "ล้าง URL เรียบร้อยแล้ว",
        urlCleanerCopied: "คัดลอกเรียบร้อยแล้ว",
        urlCleanerLocalNote: "ประมวลผลในเครื่อง ไม่มีการส่งข้อมูลผ่านเครือข่าย",
        homebrewName: "Homebrew",
        homebrewEnableCaption: "ค้นหา ติดตั้ง และจัดการ Formulas และ Casks",
        homebrewMissingTitle: "ไม่พบ Homebrew ในระบบ",
        homebrewMissingBody: "Vorssaint สามารถเปิด Terminal เพื่อรันตัวติดตั้ง Homebrew อย่างเป็นทางการให้คุณได้ Terminal จะแสดงขั้นตอนและขอรหัสผ่านหากจำเป็น",
        homebrewInstallHomebrew: "ติดตั้ง Homebrew",
        homebrewInstallHomebrewCaption: "เมื่อ Terminal ทำงานเสร็จสิ้น ให้กลับมาที่นี่แล้วคลิก “รีเฟรช”",
        homebrewInstallHomebrewOpened: "เปิดตัวติดตั้งใน Terminal แล้ว",
        homebrewShellSetupTitle: "ตั้งค่าสภาพแวดล้อม Terminal ให้เสร็จสิ้น",
        homebrewShellSetupBody: "ติดตั้ง Homebrew แล้ว แต่ Terminal อาจยังมองไม่เห็นคำสั่ง brew, Vorssaint สามารถเปิดคำสั่งตั้งค่าใน Terminal ให้ได้",
        homebrewShellSetupButton: "ตั้งค่า Terminal",
        homebrewShellSetupOpened: "เปิดคำสั่งตั้งค่าใน Terminal แล้ว จากนั้นให้กลับมาที่นี่แล้วคลิก “รีเฟรช”",
        homebrewRefresh: "รีเฟรช",
        homebrewCheckPackages: "ตรวจสอบแพ็กเกจ",
        homebrewTrustTitle: "ยังไม่ได้เชื่อถือ Tap นี้",
        homebrewTrustCaption: "Homebrew จะขอคำยืนยันจากคุณก่อนใช้งาน Tap ของบุคคลภายนอก เชื่อถือ %@ เพื่อดำเนินการต่อ",
        homebrewTrustButton: "เชื่อถือและดำเนินการต่อ",
        homebrewSearchPlaceholder: "ค้นหาแพ็กเกจ…",
        homebrewKeyboardHint: "กด Space หรือ Return เพื่อปิดแผง หรือใช้ปุ่มค้นหา",
        homebrewSearchButton: "ค้นหา",
        homebrewSearchResults: "ผลการค้นหา",
        homebrewInstalled: "ติดตั้งแล้ว",
        homebrewAll: "ทั้งหมด",
        homebrewFormulas: "Formulas",
        homebrewCasks: "Casks",
        homebrewNoPackages: "ไม่พบแพ็กเกจ",
        homebrewDependencies: "แพ็กเกจที่ต้องใช้ร่วมกัน (Dependencies)",
        homebrewGroupDependencies: "จัดกลุ่มตาม Dependencies",
        homebrewNoSelection: "เลือกแพ็กเกจที่ติดตั้งแล้วหรือค้นหาแพ็กเกจใหม่",
        homebrewDetailsTitle: "รายละเอียดแพ็กเกจ",
        homebrewInstall: "ติดตั้ง",
        homebrewUninstall: "ถอนการติดตั้ง",
        homebrewUpgrade: "อัปเกรด",
        homebrewUpgradeAll: "อัปเกรดทั้งหมด",
        homebrewUpdateHomebrew: "อัปเดต Homebrew",
        homebrewAllPackages: "แพ็กเกจทั้งหมด",
        homebrewOpenTerminal: "เปิดใน Terminal",
        homebrewCancelOperation: "ยกเลิก",
        homebrewClearLog: "ล้างบันทึก",
        homebrewLogTitle: "บันทึกการทำงาน",
        homebrewVersion: "เวอร์ชัน",
        homebrewDescription: "คำอธิบาย",
        homebrewHomepage: "เปิดเว็บไซต์หลัก",
        homebrewPopularity: "ความนิยม",
        homebrewPopularityFormat: "ติดตั้ง %1$@ ครั้ง ใน %2$@ วันที่ผ่านมา",
        homebrewInstalledBadge: "ติดตั้งแล้ว",
        homebrewNotInstalledBadge: "ยังไม่ได้ติดตั้ง",
        homebrewUpdates: "รายการอัปเดต",
        homebrewUpdateAvailableBadge: "มีอัปเดตใหม่",
        homebrewLatestVersion: "เวอร์ชันล่าสุด",
        homebrewConfirmInstallTitle: "ติดตั้งด้วย Homebrew หรือไม่?",
        homebrewConfirmInstallBodyFormat: "Homebrew จะดาวน์โหลดและติดตั้ง %@ การดำเนินการนี้อาจติดตั้งส่วนประกอบที่จำเป็นด้วย",
        homebrewConfirmUninstallTitle: "ถอนการติดตั้งด้วย Homebrew หรือไม่?",
        homebrewConfirmUninstallBodyFormat: "Homebrew จะถอนการติดตั้ง %@ ไฟล์การกำหนดค่าอาจยังคงอยู่ในระบบ",
        homebrewConfirmUpgradeTitle: "อัปเกรดด้วย Homebrew หรือไม่?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew จะดาวน์โหลดและอัปเกรด %@ เป็นเวอร์ชันล่าสุด",
        homebrewConfirmUpgradeAllTitle: "อัปเกรดแพ็กเกจทั้งหมดด้วย Homebrew หรือไม่?",
        homebrewConfirmUpgradeAllBody: "Homebrew จะดาวน์โหลดและอัปเดตแพ็กเกจทั้งหมดที่มีเวอร์ชันใหม่ แพ็กเกจที่ต้องใช้ร่วมกันอาจได้รับการอัปเดตด้วยเช่นกัน",
        homebrewConfirmUpdateHomebrewTitle: "อัปเดตฐานข้อมูล Homebrew หรือไม่?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew จะดึงข้อมูลแพ็กเกจล่าสุดและโหลดรายการของคุณใหม่",
        homebrewTerminalFallback: "การดำเนินการนี้ต้องใช้ Terminal เพื่อถามรหัสผ่านผู้ดูแลระบบ Vorssaint จะไม่บันทึกรหัสผ่านของคุณ",
        homebrewLoading: "กำลังโหลด…",
        homebrewSearchEmpty: "ไม่พบผลลัพธ์",
        homebrewOperationInstallFormat: "กำลังติดตั้ง %@",
        homebrewOperationUninstallFormat: "กำลังถอนการติดตั้ง %@",
        homebrewOperationUpgradeFormat: "กำลังอัปเกรด %@",
        homebrewOperationUpgradeAll: "กำลังอัปเกรดแพ็กเกจทั้งหมด",
        homebrewOperationUpdateHomebrew: "กำลังอัปเดต Homebrew",
        homebrewOperationInstalledFormat: "ติดตั้ง %@ สำเร็จแล้ว",
        homebrewOperationUninstalledFormat: "ถอนการติดตั้ง %@ สำเร็จแล้ว",
        homebrewOperationUpgradedFormat: "อัปเกรด %@ สำเร็จแล้ว",
        homebrewOperationUpgradedAll: "อัปเกรดแพ็กเกจทั้งหมดเรียบร้อยแล้ว",
        homebrewOperationUpdatedHomebrew: "อัปเดต Homebrew เรียบร้อยแล้ว",
        homebrewOperationFailedFormat: "การดำเนินการกับ %@ ล้มเหลว",
        homebrewOperationCancelled: "การดำเนินการถูกยกเลิก",
        homebrewOperationPreparing: "กำลังเตรียมการ…",
        homebrewOperationDownloading: "กำลังดาวน์โหลด…",
        homebrewOperationInstalling: "กำลังติดตั้ง…",
        homebrewOperationUninstalling: "กำลังถอนการติดตั้ง…",
        homebrewOperationUpgrading: "กำลังอัปเกรด…",
        homebrewOperationFinalizing: "กำลังเสร็จสิ้น…",
        homebrewOperationRefreshing: "กำลังรีเฟรช…",
        homebrewOperationTerminal: "ดำเนินการต่อใน Terminal",
        homebrewOperationElapsedFormat: "เสร็จสิ้นใน %@",
        homebrewOperationShowDetails: "แสดงรายละเอียด",
        homebrewOperationHideDetails: "ซ่อนรายละเอียด",
        homebrewOperationTechnicalLog: "บันทึกทางเทคนิค",
        homebrewOperationProgressUnknown: "Homebrew ยังไม่รายงานความคืบหน้า",
        mediaName: "จัดการสื่อ (Media Tools)",
        mediaEnableCaption: "บีบอัดวิดีโอ แปลงไฟล์ภาพ สร้างภาพ GIF และแยกข้อความจากภาพภายในเครื่องของคุณ",
        mediaLocalNote: "ประมวลผลในเครื่อง ไม่มีการส่งข้อมูลผ่านเครือข่าย",
        mediaToolVideo: "วิดีโอ",
        mediaToolGIF: "GIF",
        mediaToolImage: "รูปภาพ",
        mediaToolText: "ข้อความ",
        mediaSelectFile: "เลือกไฟล์",
        mediaDropHint: "ลากไฟล์มาวางที่นี่ หรือคลิกเพื่อเลือกไฟล์",
        mediaOutput: "ผลลัพธ์",
        mediaOutputAutomatic: "อัตโนมัติ",
        mediaChooseOutput: "เลือกโฟลเดอร์ปลายทาง…",
        mediaStartVideo: "เริ่มบีบอัดวิดีโอ",
        mediaStartGIF: "สร้างภาพ GIF",
        mediaStartImage: "ประมวลผลรูปภาพ",
        mediaStartConvertPDF: "แปลงเป็น PDF",
        mediaStartText: "แยกข้อความจากภาพ",
        mediaCancel: "ยกเลิก",
        mediaStartTime: "เวลาเริ่มต้น",
        mediaEndTime: "เวลาสิ้นสุด",
        mediaQuality: "คุณภาพการบีบอัด",
        mediaCompressionLow: "ต่ำ (ไฟล์ใหญ่)",
        mediaCompressionMedium: "ปานกลาง",
        mediaCompressionHigh: "สูง (ไฟล์เล็ก)",
        mediaCompressionLowDescription: "คุณภาพสูงมาก ขนาดไฟล์ใหญ่",
        mediaCompressionMediumDescription: "คุณภาพและขนาดไฟล์สมดุลกัน",
        mediaCompressionHighDescription: "คุณภาพปานกลาง ขนาดไฟล์เล็กที่สุด",
        mediaMaxSize: "ขนาดสูงสุด",
        mediaSizingResolution: "ความละเอียดภาพ",
        mediaSizingFileSize: "ขนาดไฟล์",
        mediaTargetSize: "ขนาดเป้าหมาย",
        mediaTargetSizeHint: "ความละเอียดจะถูกปรับให้อยู่ภายในขีดจำกัดที่กำหนด",
        mediaErrorTargetTooSmall: "ขนาดเป้าหมายเล็กเกินไปสำหรับคลิปนี้ กรุณาตัดความยาวหรือเพิ่มขีดจำกัด",
        mediaMegabytesSuffix: "MB",
        mediaWidth: "ความกว้าง",
        mediaFPS: "เฟรมต่อวินาที (FPS)",
        mediaKeepAudio: "เก็บเสียงไว้",
        mediaCodec: "ตัวแปลงสัญญาณ (Codec)",
        mediaFormat: "รูปแบบไฟล์",
        mediaStripMetadata: "ลบข้อมูลเมทาดาทา (Metadata)",
        mediaLoopGIF: "เล่นวนซ้ำภาพ GIF",
        mediaOCRMode: "โหมดตรวจจับข้อความ (OCR)",
        mediaOCRAccurate: "แม่นยำสูง",
        mediaOCRFast: "รวดเร็ว",
        mediaLanguageCorrection: "การแก้ไขภาษาอัตโนมัติ",
        mediaTextOutputNote: "ข้อความที่แยกออกมาสามารถคัดลอกหรือบันทึกเป็นไฟล์ .txt ได้",
        mediaRunning: "กำลังประมวลผล…",
        mediaCompleted: "เสร็จสิ้นเรียบร้อยแล้ว",
        mediaCancelled: "ยกเลิกแล้ว",
        mediaOpenInFinder: "แสดงใน Finder",
        mediaCopyText: "คัดลอกข้อความ",
        mediaRunAgain: "ประมวลผลอีกครั้ง",
        mediaEmptyText: "ไม่พบข้อความ",
        mediaResultSavedFormat: "บันทึกไปยัง %@",
        mediaResultSizeFormat: "%@ ลดเหลือ %@",
        mediaResultGrewCaption: "ไฟล์ที่แปลงออกมามีขนาดใหญ่กว่าเดิม",
        mediaErrorNoFile: "กรุณาเลือกไฟล์ก่อน",
        mediaErrorNoVideo: "ไฟล์นี้ไม่มีแทร็กวิดีโอ",
        mediaErrorSameOutput: "กรุณาเลือกโฟลเดอร์ปลายทางที่ต่างจากไฟล์ต้นฉบับ",
        mediaErrorUnsupported: "รูปแบบไฟล์นี้ไม่ได้รับการสนับสนุนโดย macOS",
        shelfName: "ชั้นวางพักไฟล์ (Shelf)",
        shelfEnable: "พื้นที่พักไฟล์ชั่วคราวขณะลากวาง",
        shelfEnableCaption: "แผงลอยสำหรับรวบรวมไฟล์ รูปภาพ ลิงก์ และข้อความ แล้วนำไปลากวางที่อื่นได้สะดวก",
        shelfHowTitle: "วิธีใช้งาน",
        shelfStep1: "เปิดโดยกดปุ่มลัด หรือเขย่าเมาส์ไปมาขณะกำลังลากไฟล์",
        shelfStep2: "วางไฟล์ รูปภาพ ลิงก์ หรือข้อความลงบนชั้นวางเพื่อพักไว้",
        shelfStep3: "ลากรายการออกจากชั้นวางไปวางในแอปที่ต้องการเมื่อพร้อม",
        shelfShakeToggle: "เปิดชั้นวางโดยการเขย่าเมาส์ขณะลาก",
        shelfShakeCaption: "เขย่าตัวชี้เมาส์ไปมาอย่างรวดเร็วขณะกำลังกดค้างลากไอเท็ม เพื่อเรียกชั้นวางขึ้นมาใกล้เคอร์เซอร์",
        shelfDropZoneToggle: "แสดงจุดทิ้งไฟล์บนแถบเมนู",
        shelfDropZoneCaption: "ขณะลากไฟล์ จุดทิ้งไฟล์จะปรากฏขึ้นใต้ไอคอนแถบเมนู เมื่อวางไฟล์ลงไปจะถูกเก็บไว้ที่นั่น",
        shelfDropZoneCaptionTopCenter: "ขณะลากไฟล์ ชั้นวางจะปรากฏเป็นแถบลอยอยู่ตรงกลางด้านบนของหน้าจอ",
        shelfDropZoneLabel: "วางไฟล์ที่นี่",
        shelfDockPlacement: "ตำแหน่งการแสดงผล",
        shelfDockMenuBar: "ใต้ไอคอนแถบเมนู",
        shelfDockTopCenter: "ตรงกลางด้านบนของหน้าจอ",
        shelfDockIslandNote: "หากมี Dynamic Island แถบจะแสดงตรงกลางด้านบนเสมอ",
        shelfCollapse: "ยุบแผง",
        shelfBehaviorTitle: "พฤติกรรมหลังการใช้งาน",
        shelfCloseAfterDrop: "ปิดแผงอัตโนมัติเมื่อลากไฟล์ไปแอปอื่นแล้ว",
        shelfCloseAfterDropCaption: "ปิดชั้นวางอัตโนมัติเมื่อปลายทางรับไฟล์เรียบร้อยแล้ว การปักหมุดจะช่วยให้แผงเปิดค้างไว้",
        shelfRemoveAfterDrop: "ลบรายการออกจากชั้นวางหลังจากนำไปวาง",
        shelfRemoveAfterDropCaption: "นำรายการออกจากชั้นวางเมื่อนำไปวางในแอปอื่นแล้ว ปิดตัวเลือกนี้หากต้องการเก็บสำเนาไว้บนชั้นวาง",
        shelfExclusionsTitle: "แอปที่ยกเว้นการทำงานอัตโนมัติ",
        shelfExclusionsEmpty: "ยังไม่มีแอปที่ยกเว้น",
        shelfExclusionsCaption: "การเขย่าเมาส์และจุดทิ้งไฟล์บนแถบเมนูจะไม่ทำงานสำหรับการลากที่เริ่มจากแอปเหล่านี้",
        shelfPin: "ปักหมุดเปิดค้างไว้",
        shelfUnpin: "อนุญาตให้ปิดหลังใช้งาน",
        extraBrightnessName: "ความสว่างพิเศษ (Extra Brightness)",
        extraBrightnessCaption: "ใช้ขีดจำกัดความสว่าง HDR ของหน้าจอเพื่อเพิ่มความสว่างเกินระดับสูงสุดปกติ (จะใช้พลังงานแบตเตอรี่มากขึ้นและ Mac อาจอุ่นขึ้น)",
        extraBrightnessLevelLabel: "ระดับความสว่าง",
        extraBrightnessUnsupported: "รองรับเฉพาะจอแสดงผล XDR เช่น บน MacBook Pro รุ่น 14 และ 16 นิ้ว",
        shelfHotkeyLabel: "ปุ่มลัด",
        shelfOpenNow: "เปิดชั้นวางเดี๋ยวนี้",
        shelfNoPermission: "ไม่ต้องใช้สิทธิ์พิเศษ",
        shelfMenuItem: "เปิดชั้นวาง…",
        shelfTitle: "ชั้นวางพักไฟล์",
        shelfEmpty: "ลากรายการมาวางพักไว้ที่นี่",
        shelfClearAll: "ล้างทั้งหมด",
        shelfRemoveSelected: "ลบรายการที่เลือก",
        shelfSelectedFormat: "เลือก %d รายการ",
        shelfHint: "คลิกเพื่อเลือก, ลากออกเพื่อใช้งาน หรือคลิกขวาเพื่อดูคำสั่งเพิ่มเติม",
        shelfItemImage: "รูปภาพ",
        shelfTooltipItemsFormat: "%d รายการ",
        shelfTooltipItemsFew: "%d รายการ",
        shelfTooltipImageSingular: "%d รูปภาพ",
        shelfTooltipImageFew: "%d รูปภาพ",
        shelfTooltipImagePlural: "%d รูปภาพ",
        shelfTooltipFileSingular: "%d ไฟล์",
        shelfTooltipFileFew: "%d ไฟล์",
        shelfTooltipFilePlural: "%d ไฟล์",
        shelfTooltipNoteSingular: "%d โน้ต",
        shelfTooltipNoteFew: "%d โน้ต",
        shelfTooltipNotePlural: "%d โน้ต",
        shelfTooltipLinkSingular: "%d ลิงก์",
        shelfTooltipLinkFew: "%d ลิงก์",
        shelfTooltipLinkPlural: "%d ลิงก์",
        shelfActionOpen: "เปิด",
        shelfActionOpenWith: "เปิดด้วย…",
        shelfActionShare: "แชร์…",
        shelfActionPin: "ปักหมุด",
        shelfActionUnpin: "เลิกปักหมุด",
        breakdownMeasuring: "กำลังวัด…",
        mixerSection: "มิกเซอร์ควบคุมระดับเสียง (Volume Mixer)",
        mixerEmpty: "แอปที่กำลังเล่นเสียงจะแสดงที่นี่",
        mixerUnavailable: "ใช้งานได้บน macOS 14.4 หรือใหม่กว่า",
        mixerPermissionBody: "หากต้องการปรับระดับเสียงแยกแต่ละแอป กรุณาอนุญาตสิทธิ์ “การบันทึกเสียงหน้าจอและระบบ” ในการตั้งค่าระบบ โดยเสียงของคุณจะไม่ถูกบันทึก",
        mixerResetTooltip: "รีเซ็ตเป็น 100%",
        mixerOutputDefault: "ค่าเริ่มต้น",
        mixerOutputCurrent: "ปัจจุบัน",
        mixerOutputUnavailable: "อุปกรณ์ส่งออกเสียงไม่พร้อมใช้งาน",
        mixerOutputFallback: "ใช้อุปกรณ์เริ่มต้นจนกว่าอุปกรณ์นี้จะเชื่อมต่อกลับมา",
        mixerBypassedCaption: "แอปนี้ควบคุมระดับเสียงด้วยตนเอง",
        mixerOutputTooltip: "เลือกอุปกรณ์ส่งออกเสียง",
        mixerSystemOutputTitle: "อุปกรณ์ส่งออกเสียง",
        mixerSystemOutputNoDevices: "ไม่พบอุปกรณ์ส่งออกเสียง",
        mixerSystemOutputTooltip: "เลือกอุปกรณ์ส่งออกเสียงของระบบ",
        mixerSystemOutputErrorFormat: "ไม่สามารถสลับได้: %@",
        mixerLowerOnHeadphonesDisconnect: "ลดระดับเสียงลงอัตโนมัติเมื่อถอดหูฟัง",
        mixerLowerOnHeadphonesDisconnectCaption: "ปรับลดระดับเสียงของลำโพงลงเมื่อหูฟังแบบมีสายหรือบลูทูธถูกตัดการเชื่อมต่อ เพื่อป้องกันเสียงดังรบกวน",
        mixerHeadphonesDisconnectVolume: "ระดับเสียงหลังถอดหูฟัง",
        preciseVolumeRollerEnable: "ปรับระดับเสียงทีละนิดอย่างละเอียด",
        preciseVolumeRollerCaption: "เปลี่ยนการหมุนล้อปรับเสียงและปุ่มปรับเสียงให้ปรับทีละขั้นย่อยอย่างละเอียด",
        preciseVolumeRollerTapFailed: "ไม่สามารถดักจับการกดปุ่มปรับระดับเสียงได้",
        soundOutputSwitcherTitle: "ตัวสลับอุปกรณ์เสียง (Sound Output Switcher)",
        soundOutputSwitcherEnable: "สลับอุปกรณ์เสียงด้วยปุ่มลัด",
        soundOutputSwitcherCaption: "เลือกอุปกรณ์เสียงที่ต้องการและใช้ปุ่มลัดเพื่อสลับวนไปยังอุปกรณ์ถัดไปได้อย่างรวดเร็ว",
        soundOutputSwitcherDevices: "อุปกรณ์ที่อยู่ในรอบการสลับ",
        soundOutputSwitcherNoAvailableSelection: "กรุณาเลือกอุปกรณ์ส่งออกเสียงอย่างน้อยหนึ่งรายการ",
        mixerInputTitle: "ไมโครโฟน",
        mixerInputNoDevices: "ไม่พบไมโครโฟน",
        mixerInputUnavailable: "ไมโครโฟนไม่พร้อมใช้งาน",
        mixerInputFallback: "ใช้ไมโครโฟนเริ่มต้นจนกว่าอุปกรณ์นี้จะเชื่อมต่อกลับมา",
        mixerInputTooltip: "เลือกไมโครโฟน",
        mixerInputErrorFormat: "ข้อผิดพลาดอินพุตของมิกเซอร์: %@",
        mixerVisibleApps: "แอปที่แสดงในรายการ",
        mixerAllShown: "แสดงทั้งหมด",
        mixerHiddenCountLabel: "ซ่อนอยู่",
        mixerHideFromList: "ซ่อนออกจากรายการ",
        audioPrioritySection: "ลำดับความสำคัญของอุปกรณ์เสียง",
        audioPriorityOutputEnable: "สลับไปยังอุปกรณ์ส่งออกเสียงที่มีลำดับความสำคัญสูงสุดอัตโนมัติ",
        audioPriorityInputEnable: "สลับไปยังไมโครโฟนที่มีลำดับความสำคัญสูงสุดอัตโนมัติ",
        audioPriorityOutputList: "ลำดับอุปกรณ์ส่งออกเสียง",
        audioPriorityInputList: "ลำดับไมโครโฟน",
        audioPriorityMoveUp: "เลื่อนขึ้น",
        audioPriorityMoveDown: "เลื่อนลง",
        audioPriorityUnavailable: "ไม่พร้อมใช้งาน",
        audioPriorityCurrent: "ปัจจุบัน",
        audioPriorityCaption: "อุปกรณ์จะถูกเลือกตามลำดับความสำคัญ เมื่อเชื่อมต่ออุปกรณ์ที่มีลำดับสูงกว่า ระบบจะสลับไปใช้ทันที และเมื่อถอดออก ระบบจะสลับไปใช้อันถัดไป",
        updatesSection: "การอัปเดต",
        autoCheckToggle: "ตรวจสอบการอัปเดตโดยอัตโนมัติ",
        includeBetaUpdatesToggle: "รับการอัปเดตเวอร์ชันเบต้า",
        includeBetaUpdatesCaption: "เวอร์ชันเบต้าอาจมีฟีเจอร์ใหม่ที่กำลังพัฒนา แต่อาจมีข้อผิดพลาดได้",
        betaBadgeLabel: "เบต้า",
        checkNowButton: "ตรวจสอบทันที",
        updateChecking: "กำลังตรวจสอบ…",
        updateUpToDate: "คุณกำลังใช้เวอร์ชันล่าสุดแล้ว",
        updateAvailablePrefix: "มีเวอร์ชันใหม่อัปเดต:",
        updateInstallButton: "ดาวน์โหลดและติดตั้ง",
        updateDownloading: "กำลังดาวน์โหลดอัปเดต…",
        updateInstalling: "กำลังติดตั้งและเริ่มแอปใหม่…",
        updateFailedPrefix: "ไม่สามารถตรวจสอบได้:",
        updateLastChecked: "ตรวจสอบล่าสุดเมื่อ:",
        updateNotifyTitle: "อัปเดต Vorssaint",
        updateInstallFailedBody: "ดาวน์โหลดอัปเดตเรียบร้อยแล้วแต่ไม่สามารถติดตั้งได้ กรุณาดาวน์โหลดเวอร์ชันล่าสุดจากหน้า GitHub Releases โดยตรง",
        updateNeedsApplicationsTitle: "กรุณาย้าย Vorssaint ไปไว้ในโฟลเดอร์ Applications",
        updateNeedsApplicationsBody: "แอปกำลังทำงานจากดิสก์อิมเมจหรือโฟลเดอร์ชั่วคราว กรุณาย้าย Vorssaint ไปไว้ในโฟลเดอร์ Applications แล้วเปิดใหม่อีกครั้ง",
        menuCheckUpdates: "ตรวจสอบการอัปเดต…",
        permissionRequired: "ต้องได้รับสิทธิ์การเข้าถึง",
        permissionAccessibility: "การช่วยการเข้าถึง (Accessibility)",
        permissionScreenRecording: "การบันทึกหน้าจอ (Screen Recording)",
        permissionGranted: "ได้รับสิทธิ์แล้ว",
        permissionMissing: "ยังไม่ได้รับสิทธิ์",
        permissionOpenSettings: "เปิดการตั้งค่าระบบ…",
        permissionRequest: "อนุญาตสิทธิ์การเข้าถึง",
        permissionRestartNote: "macOS อาจขอให้เปิดแอปใหม่อีกครั้งหลังจากอนุญาตสิทธิ์",
        secureInputTitle: "Secure Input กำลังทำงาน",
        secureInputHeldFormat: "%@ กำลังใช้งาน Secure Input",
        secureInputUnattributed: "ไม่สามารถระบุแอปที่เปิดใช้งาน Secure Input",
        secureInputUnidentified: "แอปที่ไม่รู้จักกำลังเปิดใช้งาน Secure Input",
        secureInputRevealFormat: "แสดง %@ ใน Finder",
        aboutDescription: "ศูนย์รวมเครื่องมือยูทิลิตี้สำหรับ Mac ของคุณ\nจัดการพลังงาน การตรวจสอบระบบ การเลื่อนเมาส์ และตัวสลับหน้าต่างบนแถบเมนูโดยตรง",
        versionPrefix: "เวอร์ชัน",
        reviewIntro: "ดูคำแนะนำการใช้งาน",
        reviewHighlights: "ดูไฮไลต์ฟีเจอร์เด่น",
        viewOnGitHub: "ดูโปรเจกต์บน GitHub",
        obContinue: "ดำเนินการต่อ",
        obBack: "ย้อนกลับ",
        obSkipStep: "ข้ามขั้นตอนนี้",
        obStart: "เริ่มใช้งาน Vorssaint",
        obStepWelcomeTitle: "ยินดีต้อนรับสู่ Vorssaint",
        obStepWelcomeBody: "ยูทิลิตี้บนแถบเมนูที่ช่วยเพิ่มประสิทธิภาพการใช้งาน macOS ประจำวันของคุณ",
        obWelcomeBullet1Title: "ควบคุมพลังงานได้ดั่งใจ",
        obWelcomeBullet1Body: "คงสถานะตื่นให้ Mac ของคุณได้นานเท่าที่ต้องการ แม้ขณะพับฝาจอลง",
        obWelcomeBullet2Title: "มองเห็นสถานะระบบอย่างชัดเจน",
        obWelcomeBullet2Body: "ตรวจสอบอุณหภูมิ CPU, GPU, แบตเตอรี่ การใช้งานฮาร์ดแวร์ และแรงดันหน่วยความจำแบบเรียลไทม์",
        obWelcomeBullet3Title: "เมาส์และหน้าต่าง ในแบบของคุณ",
        obWelcomeBullet3Body: "สลับทิศทางการเลื่อนเมาส์ เลื่อนอย่างนุ่มนวล และสลับหน้าต่างพร้อมภาพตัวอย่าง",
        obLanguageLabel: "ภาษา",
        obStepAccessibilityTitle: "สิทธิ์การช่วยการเข้าถึง",
        obStepAccessibilityBody: "จำเป็นสำหรับการสลับการเลื่อนเมาส์ และเพื่อให้ตัวสลับหน้าต่างตอบสนองต่อแป้นพิมพ์ลัด",
        obAccessibilityWhy: "แอปตรวจจับเฉพาะการหมุนล้อเมาส์และปุ่มลัดตัวสลับหน้าต่างเท่านั้น ไม่มีการบันทึกหรือส่งข้อมูลใดๆ ออกไปภายนอก",
        obStepRecordingTitle: "สิทธิ์การบันทึกหน้าจอ",
        obStepRecordingBody: "จำเป็นสำหรับการสร้างภาพตัวอย่างหน้าต่างจริงในตัวสลับแอป",
        obRecordingWhy: "ภาพตัวอย่างจะถูกสร้างและเก็บไว้ในหน่วยความจำชั่วคราวเท่านั้น หากไม่อนุญาต ตัวสลับจะแสดงผลเป็นไอคอนแทน",
        obStepMonitorTitle: "การตรวจสอบระบบ",
        obStepMonitorBody: "แผงควบคุมแสดงอุณหภูมิ CPU, GPU, แบตเตอรี่ รวมถึงการใช้งานทรัพยากรระบบ",
        obMonitorNoPermission: "ไม่ต้องใช้สิทธิ์พิเศษ เซ็นเซอร์จะถูกอ่านค่าจากระบบโดยตรง",
        obStepOptionalTitle: "ฟีเจอร์เสริม",
        obStepOptionalBody: "เลือกเปิดใช้งานฟีเจอร์ที่คุณต้องการใช้งานตอนนี้ โดยสามารถปรับแต่งเพิ่มเติมได้ในภายหลัง",
        obStepStatusTitle: "ตรวจสอบความพร้อม",
        obStepStatusBody: "ตรวจสอบให้แน่ใจว่าระบบพร้อมสำหรับฟีเจอร์ที่คุณต้องการใช้งาน",
        obStatusRecheck: "ตรวจสอบอีกครั้ง",
        obStepDoneTitle: "พร้อมใช้งานแล้ว!",
        obStepDoneBody: "Vorssaint พร้อมดูแล Mac ของคุณแล้ว",
        obDoneHint: "มองหาไอคอน Vorssaint บนแถบเมนูที่มุมขวาบนของหน้าจอ",
        obWhatsNewTitle: "มีอะไรใหม่ในเวอร์ชันนี้",
        obWhatsNewFallback: "การอัปเดตนี้มาพร้อมกับการปรับปรุงประสิทธิภาพและแก้ไขข้อผิดพลาดล่าสุด",
        obLanguageUpdateTitle: "พร้อมใช้งานในภาษาของคุณแล้ว",
        obLanguageUpdateBody: "Vorssaint รองรับหลายภาษาแล้วตอนนี้ คุณสามารถเปลี่ยนภาษาได้ตลอดเวลาในการตั้งค่า",
        obPurposeTitle: "คุณต้องการใช้งานเพื่อจุดประสงค์ใด?",
        obPurposeBody: "เลือกชุดการตั้งค่าที่เตรียมไว้ หรือปรับแต่งตามความต้องการของคุณ",
        obPurposeSkip: "คุณสามารถเปิดหรือปิดฟีเจอร์ต่างๆ ได้ในภายหลังที่หน้าการตั้งค่า",
        tabMonitor: "มอนิเตอร์ระบบ (Monitor)",
        monitorMenuBarSection: "การแสดงผลบนแถบเมนู",
        monitorMenuBarCaption: "เลือกข้อมูลที่ต้องการแสดงถัดจากไอคอนบนแถบเมนู",
        monitorCombineTemperatures: "รวมการใช้งานและอุณหภูมิ",
        monitorCombineTemperaturesCaption: "แสดงการใช้งานและอุณหภูมิของรายการเดียวกันรวมกันเป็นบล็อกเดียว",
        monitorSeparateMenuBarMetrics: "แยกข้อมูลแต่ละตัวออกเป็นรายการของตัวเอง",
        monitorSeparateMenuBarMetricsCaption: "แยกการแสดงผลบนแถบเมนูเป็นบล็อกอิสระ",
        monitorNetworkUploadFirst: "แสดงความเร็วอัปโหลดอยู่ด้านบนดาวน์โหลด",
        monitorShowCPU: "CPU",
        monitorShowMemory: "หน่วยความจำ",
        monitorShowNetwork: "เครือข่าย",
        monitorShowPowerLabel: "พลังงาน",
        monitorIntervalLabel: "อัปเดตทุกๆ",
        monitorInterval1: "1 วินาที",
        monitorInterval2: "2 วินาที",
        monitorInterval5: "5 วินาที",
        monitorPanelSection: "การแสดงผลในแผงควบคุม",
        panelNavigationMode: "การนำทางในแผงควบคุมตามหมวดหมู่",
        panelNavigationCaption: "แสดงทีละส่วน หรือเลือกเป็นรายการเพื่อดูข้อมูลทั้งหมดในคราวเดียว",
        panelFooterSections: "หมวดหมู่",
        panelFooterList: "รายการทั้งหมด",
        betaBadge: "เบต้า",
        betaFeatureWarning: "ฟีเจอร์เบต้า อาจพบข้อผิดพลาดบางประการได้",
        networkSection: "เครือข่าย",
        networkIPAddresses: "ที่อยู่ IP",
        networkLocalIP: "IPv4 ในเครื่อง",
        networkDownload: "ดาวน์โหลด",
        networkUpload: "อัปโหลด",
        networkThisSession: "เซสชันนี้",
        networkMeasuring: "กำลังวัดความเร็ว…",
        networkApps: "แอปที่ใช้เครือข่าย",
        networkAppsIdle: "ไม่มีแอปที่ใช้งานเครือข่ายในขณะนี้",
        diskSection: "ดิสก์",
        diskUsed: "ใช้แล้ว",
        diskFree: "ว่าง",
        diskMenuBarStyleLabel: "รูปแบบแถบเมนูดิสก์",
        diskMenuBarUsedPercentage: "เปอร์เซ็นต์ที่ใช้",
        diskMenuBarAvailableSpace: "พื้นที่ว่าง",
        diskMenuBarUsedSpace: "พื้นที่ที่ใช้",
        diskAvailable: "ว่าง",
        diskPurgeable: "ล้างข้อมูลได้ (Purgeable)",
        diskInternal: "ดิสก์ภายใน",
        diskExternal: "ดิสก์ภายนอก",
        diskSelect: "เลือกดิสก์",
        diskRead: "อ่าน",
        diskWrite: "เขียน",
        diskSMARTStatus: "สถานะ S.M.A.R.T.",
        diskSMARTUnavailable: "ดิสก์นี้ไม่รองรับ S.M.A.R.T.",
        diskTotalRead: "อ่านข้อมูลรวม",
        diskTotalWritten: "เขียนข้อมูลรวม",
        diskTemperature: "อุณหภูมิดิสก์",
        diskHealth: "สุขภาพดิสก์",
        diskPowerCycles: "รอบการเปิดใช้งาน (Power Cycles)",
        diskPowerOnHours: "ชั่วโมงการเปิดใช้งาน",
        diskUnsafeShutdowns: "การปิดเครื่องอย่างไม่ปลอดภัย",
        diskMediaErrors: "ข้อผิดพลาดของมีเดีย",
        diskEject: "ดีดออก",
        diskEjectAll: "ดีดออกทั้งหมด",
        diskEjecting: "กำลังดีดออก…",
        diskReadyToRemove: "พร้อมถอดอุปกรณ์ออกได้อย่างปลอดภัย",
        diskEjectFailed: "ไม่สามารถดีดออกได้",
        diskProtectionCaption: "ดีดออกก่อนถอดสายเชื่อมต่อเสมอ",
        diskNoExternal: "ไม่มีดิสก์ภายนอกที่เชื่อมต่ออยู่",
        diskOpenInFinder: "เปิดใน Finder",
        diskStorageSettings: "การตั้งค่าพื้นที่จัดเก็บข้อมูล",
        diskNoDisks: "ไม่พบดิสก์ที่ต่อเชื่อม",
        powerSection: "พลังงาน",
        powerSystem: "ระบบ",
        powerAdapter: "อะแดปเตอร์แปลงไฟ",
        powerBattery: "แบตเตอรี่",
        powerCharging: "กำลังชาร์จ",
        powerOnBattery: "ใช้พลังงานจากแบตเตอรี่",
        powerPluggedIn: "เสียบปลั๊กไฟแล้ว",
        powerUnavailable: "ไม่พบเซ็นเซอร์วัดพลังงานบน Mac เครื่องนี้",
        powerAdapterMaxFormat: "อะแดปเตอร์แปลงไฟสูงสุด %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "อุณหภูมิ CPU",
        monitorShowGPUTemperature: "อุณหภูมิ GPU",
        monitorShowBatteryTemperature: "อุณหภูมิแบตเตอรี่",
        monitorShowPeripheralBattery: "แบตเตอรี่อุปกรณ์เสริม",
        peripheralBatteryNoDevices: "ไม่พบอุปกรณ์เสริมที่เชื่อมต่อ",
        monitorGraphsSection: "กราฟแสดงผล",
        monitorGraphsCaption: "เลือกข้อมูลที่ต้องการแสดงเป็นกราฟย้อนหลัง",
        updateBannerTitle: "มีอัปเดตใหม่พร้อมใช้งาน",
        updateBannerAction: "อัปเดตเดี๋ยวนี้",
        obStepMenuBarTitle: "ข้อมูลบนแถบเมนู",
        obStepMenuBarBody: "เลือกข้อมูลที่ต้องการแสดงถัดจากไอคอน ภาพตัวอย่างด้านบนจะอัปเดตทันที",
        obStepMenuBarNote: "ใหม่: ข้อมูลเครือข่าย พลังงาน และกราฟแสดงผล ปรับแต่งได้ที่ การตั้งค่า > มอนิเตอร์",
        monitorMenuBarPresetLabel: "รูปแบบการแสดงผล",
        menuBarPresetReadable: "อ่านง่าย",
        menuBarPresetDense: "กะทัดรัดหนาแน่น",
        menuBarSpacingLabel: "ระยะห่างบนแถบเมนู",
        menuBarSpacingStandard: "มาตรฐาน",
        menuBarSpacingCompact: "กะทัดรัด",
        menuBarHideIconToggle: "ซ่อนไอคอนแอปขณะแสดงข้อมูลบนแถบเมนู",
        menuBarHideIconCaption: "ไอคอนจะแสดงขึ้นมาอัตโนมัติเมื่อมีการแจ้งเตือน (เช่น มีอัปเดตใหม่หรือไมโครโฟนปิดเสียงอยู่)",
        monitorLabelStyleLabel: "สไตล์ป้ายข้อความ",
        menuBarLabelStyleCompact: "กะทัดรัด",
        menuBarLabelStyleClassic: "คลาสสิก",
        monitorMemoryStyleLabel: "รูปแบบการแสดงผลหน่วยความจำ",
        monitorMemoryPressureDot: "จุดแสดงระดับแรงดันหน่วยความจำ",
        memoryStyleDot: "จุด",
        memoryStylePercent: "เปอร์เซ็นต์ (%)",
        memoryStyleBoth: "ทั้งสองอย่าง",
        systemUptime: "เปิดเครื่องมาแล้ว",
        batteryCharge: "ระดับแบตเตอรี่",
        powerHealth: "สุขภาพแบตเตอรี่",
        powerCycles: "รอบการชาร์จ (Cycles)",
        speedTestRun: "ทดสอบความเร็ว",
        speedTestAgain: "ทดสอบอีกครั้ง",
        speedTestLatency: "ค่าความหน่วง (Latency)",
        speedTestTesting: "กำลังทดสอบ…",
        speedTestFailed: "การทดสอบความเร็วล้มเหลว",
        monitorShowInPanel: "แสดงในแผงควบคุม",
        disclosureExpanded: "ขยาย",
        disclosureCollapsed: "ยุบ",
        panelHideItem: "ซ่อนจากแผงควบคุม",
        panelShowItem: "แสดงในแผงควบคุม",
        panelHiddenItem: "ซ่อนอยู่",
        monitorItemUptime: "เวลาเปิดเครื่อง (Uptime)",
        monitorItemNetSpeed: "ความเร็วเครือข่ายสด",
        monitorItemNetTotals: "ปริมาณข้อมูลรวมในเซสชัน",
        monitorItemNetTest: "ทดสอบความเร็วเครือข่าย",
        monitorItemDiskUsage: "การใช้งานพื้นที่ดิสก์",
        monitorItemDiskActivity: "กิจกรรมการอ่าน/เขียนดิสก์",
        monitorItemDiskSMART: "สถานะ S.M.A.R.T.",
        monitorItemDiskProtection: "การป้องกันดิสก์ภายนอก",
        monitorItemDiskTools: "เครื่องมือดิสก์",
        monitorPanelConfigHint: "คลิกเปิดแต่ละบล็อกเพื่อเลือกข้อมูลที่ต้องการแสดง",
        monitorOrderHint: "ลากเพื่อจัดลำดับหมวดหมู่ในแผงควบคุม และคลิกไอคอนรูปดวงตาเพื่อซ่อนหรือแสดง",
        obStepPanelTitle: "สิ่งที่อยู่ในแผงควบคุม",
        obStepPanelBody: "เปิดแต่ละบล็อกเพื่อเลือกข้อมูลที่จะแสดงเมื่อคุณคลิกที่ไอคอนบนแถบเมนู",
        obStepPanelNavigationTitle: "แผงควบคุมตามหมวดหมู่",
        obStepPanelNavigationBody: "สามารถแสดงผลทีละหมวดหมู่ได้ โดยสลับไปมาระหว่างหมวดหมู่หรือรายการทั้งหมดได้ในการตั้งค่า",
        cleaningMenuItem: "โหมดทำความสะอาดแป้นพิมพ์…",
        utilitiesSection: "ยูทิลิตี้",
        quickControlsSection: "การควบคุมด่วน",
        panelCategoryWindows: "หน้าต่าง",
        panelCategoryInput: "เมาส์และแป้นพิมพ์",
        panelCategoryFiles: "ไฟล์",
        windowMaximizeName: "ขยายหน้าต่างเต็มจอแบบไม่มี Space (Maximize)",
        windowMaximizeCaption: "คลิกปุ่มสีเขียวเพื่อขยายหน้าต่างจนเต็มหน้าจอโดยไม่ต้องสร้าง Space ใหม่แบบ macOS ปกติ",
        windowMaximizeActiveNow: "เปิดใช้งานการแทนที่ปุ่มสีเขียวแล้ว",
        windowMaximizeNeedsAccessibility: "ต้องใช้สิทธิ์การช่วยการเข้าถึงในการทำงาน",
        keyDebounceName: "ป้องกันการกดแป้นพิมพ์ซ้ำ (Key Debounce)",
        keyDebounceEnable: "กรองการกดแป้นพิมพ์ซ้ำโดยไม่ได้ตั้งใจ",
        keyDebounceCaption: "กรองการกดแป้นพิมพ์ซ้ำที่เกิดขึ้นเร็วผิดปกติ (เช่น ปัญหาคีย์บอร์ดเบิ้ล)",
        keyDebounceActiveNow: "ตัวกรองกำลังทำงานอยู่",
        keyDebounceGlobalWindow: "ช่วงเวลากลาง (Global Window)",
        keyDebouncePerKeySection: "แป้นพิมพ์ที่กำหนดค่าเฉพาะ",
        keyDebouncePerKeyCaption: "ค่าเฉพาะแต่ละแป้นจะแทนที่ช่วงเวลากลาง ใส่ค่า 0 ms เพื่อหยุดการกรองแป้นนั้น",
        keyDebounceKeyLabel: "แป้นพิมพ์",
        keyDebounceWindowLabel: "ช่วงเวลา (มิลลิวินาที)",
        keyDebounceAddKey: "เพิ่มแป้นพิมพ์",
        keyDebounceNoOverrides: "ยังไม่มีการกำหนดค่าแป้นพิมพ์เฉพาะ",
        keyDebounceRemoveKey: "ลบแป้นพิมพ์",
        cleaningPanelCaption: "ล็อกแป้นพิมพ์ชั่วคราวเพื่อให้คุณเช็ดทำความสะอาดได้อย่างปลอดภัย",
        cleaningOverlayTitle: "ล็อกแป้นพิมพ์เพื่อทำความสะอาดแล้ว",
        cleaningOverlaySubtitle: "กดปุ่ม Escape 5 ครั้งเพื่อปลดล็อก",
        cleaningOverlayUnlock: "ปลดล็อก",
        cleaningOverlayMouseHint: "เมาส์และแทร็กแพดยังคงใช้งานได้ตามปกติ",
        cleaningKeepScreenVisibleToggle: "แสดงหน้าจอตามปกติขณะล็อก",
        cleaningKeepScreenVisibleCaption: "แสดงข้อความแจ้งเตือนที่มุมหน้าจอแทนการทำให้หน้าจอมืดลง",
        cleaningStartNow: "ล็อกแป้นพิมพ์เดี๋ยวนี้",
        cleaningNeedsAxTitle: "ต้องใช้สิทธิ์การช่วยการเข้าถึง",
        cleaningNeedsAxBody: "เพื่อล็อกแป้นพิมพ์อย่างปลอดภัย Vorssaint ต้องได้รับสิทธิ์การช่วยการเข้าถึง กรุณาอนุญาตในการตั้งค่าระบบ",
        tabSupport: "สนับสนุน",
        shortcutsPageCaption: "ปรับแต่งปุ่มลัดส่วนกลางของทุกฟีเจอร์ใน Mac เครื่องนี้ ปุ่มลัดที่ปิดใช้งานจะยังคงถูกบันทึกไว้",
        shortcutsPageTitle: "แป้นพิมพ์ลัด",
        settingsSearchPlaceholder: "ค้นหาการตั้งค่า…",
        donateHeading: "ร่วมสนับสนุนการพัฒนา Vorssaint",
        donateMessage: "Vorssaint เป็นโปรเจกต์โอเพนซอร์สอิสระที่สร้างขึ้นในเวลาว่าง หากคุณชื่นชอบและต้องการร่วมสนับสนุน การเลี้ยงกาแฟผ่าน Buy Me a Coffee จะช่วยสนับสนุนการพัฒนาฟีเจอร์ใหม่ๆ ได้โดยตรง",
        donateButton: "เลี้ยงกาแฟผ่าน Buy Me a Coffee",
        donateThanks: "ขอบคุณมากสำหรับการสนับสนุน 🖤",
        supportIntroTitle: "ร่วมสนับสนุนการพัฒนา Vorssaint",
        supportIntroMessage: "หากคุณต้องการร่วมสนับสนุนการพัฒนา Buy Me a Coffee คือช่องทางอย่างเป็นทางการ",
        supportIntroStarButton: "ให้ Star Vorssaint บน GitHub",
        supportIntroStarMessage: "ให้ดาวบน GitHub เพื่อสนับสนุนโครงการ",
        supportIntroCoffeeButton: "Buy Me a Coffee",
        supportIntroLaterButton: "ไว้คราวหลัง",
        supportIntroDoneButton: "เสร็จสิ้น",
        discordIntroTitle: "ชุมชน Vorssaint บน Discord",
        discordIntroMessage: "ชุมชน Vorssaint กำลังสร้างขึ้นเพื่อพูดคุย แนะนำฟีเจอร์ และแจ้งปัญหา เข้าร่วมกับเราได้บน Discord",
        discordIntroJoinButton: "เข้าร่วม Discord",
        communityIntroTitle: "ติดตามการอัปเดตก่อนใคร",
        communityIntroMessage: "ติดตามข่าวสารและพรีวิวฟีเจอร์ใหม่บน X",
        communityIntroFollowButton: "ติดตาม @vorssaint บน X",
        homebrewOfficialIntroTitle: "พร้อมให้ติดตั้งแล้วในแค็ตตาล็อก Homebrew ทางการ",
        homebrewOfficialIntroMessage: "คุณสามารถติดตั้ง Vorssaint ได้โดยตรงผ่านคำสั่งของ Homebrew อย่างเป็นทางการ",
        homebrewOfficialIntroInstallLabel: "ติดตั้งใหม่",
        homebrewOfficialIntroMigrationTitle: "ใช้ Tap เวอร์ชันเก่าอยู่ใช่ไหม?",
        homebrewOfficialIntroMigrationMessage: "สั่ง Untap เพียงครั้งเดียว แอปและการตั้งค่าของคุณจะยังคงอยู่เหมือนเดิม",
        homebrewOfficialIntroCopyButton: "คัดลอกคำสั่ง",
        updateShowcaseTitle: "มีอะไรใหม่ในเวอร์ชัน 3.1.4",
        updateShowcaseMessage: "ดูสรุปฟีเจอร์และการปรับปรุงหลักๆ ในการอัปเดตนี้",
        updateShowcaseUnavailable: "ไม่สามารถโหลดวิดีโอได้ในขณะนี้ คุณยังคงสามารถใช้งานต่อได้",
        updateShowcaseRestart: "เริ่มแอปใหม่",
        showMenuBarIcon: "แสดงไอคอนบนแถบเมนู",
        menuBarIconStillHiddenTitle: "ไอคอนยังคงถูกซ่อนอยู่",
        menuBarIconStillHiddenBody: "ไอคอนถูกเปิดแล้ว แต่แถบเมนูอาจมีพื้นที่ไม่เพียงพอ: ลองซ่อนไอคอนอื่นบางส่วน หรือปิดแอปที่มีเมนูยาว",
        menuBarIconManagerHintFormat: "%@ กำลังทำงานและอาจซ่อนไอคอนไว้ในส่วนที่พับอยู่ ตรวจสอบที่นั่นหรือตั้งค่าให้ %@ แสดง Vorssaint เสมอ",
        menuBarIconDisallowedBody: "macOS กำลังบล็อก Vorssaint จากแถบเมนู ไปที่ การตั้งค่าระบบ > ศูนย์ควบคุม ค้นหา Vorssaint และเปิด “แสดงในแถบเมนู”",
        shortcutRecording: "กดปุ่มลัดที่ต้องการ…",
        shortcutReset: "รีเซ็ต",
        shortcutNone: "ไม่มี",
        shortcutClear: "ลบปุ่มลัด",
        shortcutInvalid: "ต้องมีปุ่ม Control, Option หรือ Command ร่วมด้วยอย่างน้อยหนึ่งปุ่ม",
        shortcutPressKeys: "กดปุ่มลัด",
        shortcutEscapeHint: "กด Esc เพื่อยกเลิก",
        shortcutDeleteHint: "กด Delete เพื่อล้าง",
        shortcutNotCaptured: "ไม่สามารถบันทึกได้ ชุดปุ่มนี้ถูกใช้งานโดยระบบหรือแอปอื่นอยู่แล้ว กรุณาลองชุดปุ่มอื่น",
        shortcutConflictFormat: "ปุ่มลัดนี้ถูกใช้งานโดย %@ แล้ว",
        shortcutTakeOverOffer: "macOS กำลังใช้ %@ สำหรับปุ่มลัดระบบ",
        shortcutTakeOverAction: "แทนที่ปุ่มลัดขณะที่ Vorssaint กำลังทำงาน",
        shortcutTakeOverCaption: "macOS จะสามารถใช้ปุ่มลัดนี้ได้ตามเดิมเมื่อปิด Vorssaint หรือปิดฟีเจอร์นี้",
        shortcutTakeOverDismiss: "ไม่แทนที่",
        shortcutUnavailable: "macOS ไม่อนุญาตให้ใช้ปุ่มลัดนี้ กรุณาเลือกชุดปุ่มอื่น",
        shelfShortcutToggle: "ปุ่มลัดเปิดชั้นวางพักไฟล์",
        switcherUsageHintFormat: "กด %@ ค้างไว้เพื่อเลื่อนดู; ปล่อยเพื่อเลือกหน้าต่าง; Shift หรือ ← เพื่อถอยหลัง; W เพื่อปิดหน้าต่าง; Q เพื่อออกจากแอป; Esc เพื่อยกเลิก",
        musicBlockSection: "ปุ่มควบคุมสื่อ (Media Keys)",
        musicBlockTitle: "ป้องกันไม่ให้แอป Music เปิดขึ้นมาเอง",
        musicBlockCaption: "บล็อกไม่ให้แอป Apple Music เด้งเปิดขึ้นมาเมื่อกดปุ่มเล่นเพลง ต้องใช้สิทธิ์การช่วยการเข้าถึง",
        musicBlockUnavailable: "การป้องกันนี้ไม่พร้อมใช้งานในขณะนี้ กรุณาปิดแล้วเปิดใหม่อีกครั้ง",
        musicBlockReplacementLabel: "เปิดแอปนี้แทน",
        musicBlockReplacementNone: "ไม่เปิดแอปใดๆ",
        musicBlockReplacementBlocked: "Music และ iTunes ถูกบล็อกไว้ ไม่สามารถเลือกเปิดแทนได้ กรุณาเลือกแอปอื่น",
        musicBlockChooseApp: "เลือกแอป…",
        musicBlockPlayReplacement: "สั่งเล่นเพลงทันทีหลังจากเปิดแอปที่เลือก",
        cleanerName: "ล้างไฟล์ขยะ (System Cleaner)",
        cleanerIntroTitle: "ทำความสะอาด Mac ของคุณ",
        cleanerIntroCaption: "สแกนหาไฟล์ตกค้างจากแอปที่ถอนการติดตั้งแล้ว แคช บันทึกระบบ และถังขยะ คุณสามารถตรวจสอบไฟล์ทั้งหมดก่อนลบ และรายการที่ลบจะถูกส่งไปที่ถังขยะ",
        cleanerScan: "เริ่มสแกน",
        cleanerScanning: "กำลังสแกน…",
        cleanerCleaning: "กำลังทำความสะอาด…",
        cleanerCatLeftovers: "ไฟล์ตกค้างจากแอปที่ถอนการติดตั้งแล้ว",
        cleanerCatLoginItems: "รายการเปิดเครื่องที่ไม่มีตัวแอปแล้ว",
        cleanerCatCaches: "ไฟล์แคชของแอป",
        cleanerCatLogs: "บันทึกการทำงานของระบบ (Logs)",
        cleanerCatDeveloper: "ไฟล์ชั่วคราวของนักพัฒนา (Xcode)",
        cleanerCatTrash: "ถังขยะ (Trash)",
        cleanerLeftoversNote: "ตรวจพบจากการวิเคราะห์และยังไม่ได้เลือก กรุณาตรวจสอบตำแหน่งไฟล์ก่อนติ๊กเลือก",
        cleanerLoginItemsNote: "รายการภายใต้รายการเปิดเครื่องจะหายไปหลังจากเริ่มการทำงานของ Mac ใหม่",
        cleanerTrashNote: "การล้างถังขยะจะมีผลถาวร",
        cleanerCatDeviceBackups: "ไฟล์สำรองข้อมูล iPhone/iPad",
        cleanerDeviceBackupsCaption: "ไฟล์สำรองข้อมูลของ iPhone และ iPad เก่าที่กินพื้นที่จัดเก็บข้อมูล ลบเฉพาะไฟล์ที่คุณไม่ต้องการแล้ว การสำรองข้อมูลใหม่จะเกิดขึ้นเมื่อเสียบอุปกรณ์อีกครั้ง",
        cleanerCatScreenshots: "ภาพถ่ายหน้าจอที่ลืมไปแล้ว",
        cleanerScreenshotsCaptionFormat: "ภาพถ่ายหน้าจอที่คุณไม่ได้เปิดดูมานานกว่า %d วันและยังใช้ชื่อตามที่ macOS ตั้งให้",
        cleanerScreenshotsSettingCaption: "การสแกนจะแสดงภาพถ่ายหน้าจอที่คุณไม่ได้เปิดดูมานานตามจำนวนวันที่กำหนด",
        cleanerScreenshotsAfterFormat: "หลังจาก %d วัน",
        cleanerNothingFound: "ไม่พบไฟล์ขยะ Mac ของคุณสะอาดและเป็นระเบียบเรียบร้อยดี",
        cleanerClean: "ล้างไฟล์ขยะ",
        cleanerDoneNote: "รายการทั้งหมดจะถูกย้ายไปที่ถังขยะและสามารถกู้คืนได้จากที่นั่น",
        cleanerAgain: "สแกนอีกครั้ง",
        cleanerRevealInFinder: "แสดงใน Finder",
        cleanerPanelCaption: "ไฟล์ตกค้าง แคช และบันทึกระบบ",
        cleanerSafeSection: "รายการที่ปลอดภัยในการล้าง",
        cleanerOptionalSection: "รายการเสริม (ควรตรวจสอบก่อนลบ)",
        cleanerCatOtherCaches: "แคชอื่นๆ",
        cleanerCachesCaption: "ไฟล์ชั่วคราวที่แอปจะสร้างขึ้นใหม่ได้เองอัตโนมัติ",
        cleanerLogsCaption: "บันทึกการวินิจฉัยระบบเก่า",
        cleanerDeveloperCaption: "ไฟล์ที่เหลือจากการคอมไพล์และการจำลองใน Xcode",
        cleanerLoginItemsCaption: "รายการเปิดเครื่องที่หลงเหลือจากแอปที่ถูกลบไปแล้ว",
        cleanerLeftoversCaption: "ไฟล์ที่แอปที่คุณถอนการติดตั้งทิ้งไว้ในระบบ",
        cleanerOtherCachesCaption: "ปลอดภัยในการลบ ไม่ทำให้ระบบเสียหาย แต่อาจทำให้แอปเปิดช้าลงเล็กน้อยในครั้งแรก",
        cleanerCleanSizeFormat: "ล้างไฟล์แล้ว %@",
        cleanerScheduleTitle: "กำหนดการล้างข้อมูลอัตโนมัติ",
        cleanerScheduleOff: "ปิด",
        cleanerScheduleDaily: "ทุกวัน",
        cleanerScheduleWeekly: "ทุกสัปดาห์",
        cleanerScheduleCaption: "ทำความสะอาดเฉพาะส่วนที่ปลอดภัยโดยอัตโนมัติตามเวลาที่เลือก และส่งไฟล์ไปที่ถังขยะ",
        cleanerScheduleLastFormat: "การล้างข้อมูลอัตโนมัติครั้งล่าสุดคืนพื้นที่ได้ %@",
        cleanerAutoNotificationFormat: "คืนพื้นที่ %@ และส่งไปยังถังขยะแล้ว",
        cleanerScheduleNextFormat: "การล้างข้อมูลครั้งต่อไป: %@",
        cleanerScheduleRanFormat: "การล้างข้อมูลอัตโนมัติครั้งล่าสุด: %@",
        cleanerScheduleNotifyToggle: "แจ้งเตือนเมื่อล้างข้อมูลเสร็จสิ้น",
        cleanerNotifDenied: "การแจ้งเตือนของ Vorssaint ถูกปิดไว้ในการตั้งค่าระบบ",
        cleanerNotifOpenSettings: "เปิดการตั้งค่าการแจ้งเตือน…",
        launchAtLoginNeedsApplications: "แอปกำลังทำงานจากตำแหน่งที่ไม่สามารถเปิดเมื่อเข้าสู่ระบบได้ กรุณาย้าย Vorssaint ไปที่โฟลเดอร์ Applications แล้วเปิดใหม่อีกครั้ง",
        launchAtLoginNeedsApproval: "รายการเข้าสู่ระบบได้รับการลงทะเบียนแล้วแต่ถูกปิดไว้ในการตั้งค่าระบบ ไปที่ การตั้งค่าระบบ > ทั่วไป > รายการเข้าสู่ระบบ และเปิดสวิตช์ Vorssaint",
        ocrRemoveLineBreaksToggle: "ตัดการขึ้นบรรทัดใหม่",
        ocrRemoveLineBreaksCaption: "ลบตัวแบ่งบรรทัดออก เพื่อให้ข้อความที่คัดลอกมากลายเป็นย่อหน้าเดียวกันอย่างต่อเนื่อง",
        ocrQRToggle: "ตรวจจับและอ่าน QR Code",
        ocrQRCaption: "หากพื้นที่ที่เลือกมี QR Code ข้อมูลจะปรากฏขึ้นเพื่อให้คัดลอกหรือเปิดลิงก์ได้ทันที",
        ocrQRCopied: "คัดลอกข้อมูล QR Code แล้ว",
        qrResultTitle: "ผลการอ่าน QR Code",
        qrResultCopy: "คัดลอก",
        qrResultOpen: "เปิดลิงก์",
        highlightsTitle: "มีอะไรใหม่ในการอัปเดตนี้",
        highlightsTitleClipboardRedesign: "ประวัติคลิปบอร์ดดีไซน์ใหม่",
        highlightsTitleWindowLayout: "การจัดเค้าโครงหน้าต่าง (Window Layout)",
        highlightsTitleQuitProtection: "การป้องกันการออกจากแอปและปิดหน้าต่าง",
        highlightsTitleRecorderBlur: "การเบลอข้อมูลส่วนบุคคลในตัวบันทึกหน้าจอ",
        highlightsCaptionDockPreview: "ตัวอย่าง Dock รองรับการทำงานร่วมกับการขยายไอคอนของ Dock แล้ว",
        highlightsCaptionScreenshot: "เครื่องมือถ่ายภาพหน้าจอเพิ่มแว่นขยายระดับพิกเซลและการอ่าน QR Code",
        highlightsCaptionSnippetLibrary: "เมนูคลังข้อความสั้นที่ค้นหาได้ พิมพ์ข้อความที่เคอร์เซอร์ได้ทันที",
        highlightsCaptionCapturePalette: "ปุ่มลัดเดียวเปิดแผงลอยสำหรับถ่ายภาพหน้าจอ บันทึกวิดีโอ ดึงข้อความ และดูดสี",
        highlightsCaptionClipboardRedesign: "ประวัติคลิปบอร์ดแบบกะทัดรัด แถวข้อมูลสะอาดตา พร้อมดูตัวอย่างและแก้ไขได้ทันที",
        highlightsCaptionWindowLayout: "จัดตำแหน่งหน้าต่างด้วยวงล้อทิศทาง หรือลากไปที่ขอบหน้าจอเพื่อจัดชิดขอบพร้อมช่องว่างที่กำหนดเอง",
        highlightsCaptionQuitProtection: "ป้องกันการเผลอกดออกจากแอปหรือปิดหน้าต่างโดยไม่ตั้งใจ ด้วยการกดค้างหรือกดสองครั้ง",
        highlightsCaptionRecorderBlur: "ซ่อนข้อมูลส่วนตัว รหัสผ่าน และส่วนที่ละเอียดอ่อนในวิดีโอที่บันทึกก่อนแชร์หรือส่งออก",
        highlightsConfigure: "ตั้งค่า",
        highlightsTry: "ลองใช้งาน",
        highlightsSeeAll: "ดูการเปลี่ยนแปลงทั้งหมด",
        switcherCurrentSpaceOnly: "แสดงเฉพาะเดสก์ท็อปปัจจุบัน",
        switcherCurrentSpaceOnlyCaption: "แสดงเฉพาะหน้าต่างบนเดสก์ท็อปปัจจุบัน",
        shelfFileMissing: "ไฟล์ไม่มีอยู่อีกต่อไป",
        previewSizeSmall: "เล็ก",
        mixerSoundEffectsOutputTitle: "เสียงเอฟเฟกต์ระบบ",
        mixerSoundEffectsOutputTooltip: "ส่งเสียงแจ้งเตือนและเอฟเฟกต์ไปยังอุปกรณ์นี้",
        monitorOpenActivityMonitor: "เปิดตัวตรวจสอบกิจกรรม (Activity Monitor)",
        dockClickHide: "คลิกไอคอน Dock เพื่อซ่อนแอป",
        dockClickHideCaption: "แอปที่กำลังใช้งานอยู่จะถูกซ่อนเมื่อคุณคลิกที่ไอคอน Dock และคลิกอีกครั้งเพื่อนำกลับมา",
        monitorMemoryMetricLabel: "หน่วยวัดหน่วยความจำ",
        memoryMetricUsed: "หน่วยความจำที่ใช้",
        memoryMetricApp: "หน่วยความจำของแอป",
        keepAwakeRightClickToggle: "คลิกขวาเพื่อสลับเปิด/ปิด",
        keepAwakeRightClickToggleCaption: "คลิกขวาที่ไอคอนแถบเมนูเพื่อเปิดหรือปิดการคงสถานะตื่นทันที",
        urlCleanerRulesTitle: "กฎการล้าง URL",
        urlCleanerRulesCaption: "เว็บไซต์จะแนบพารามิเตอร์เหล่านี้เข้ากับลิงก์แชร์เพื่อติดตามแหล่งที่มา เมื่อเปิดใช้งาน พารามิเตอร์เหล่านี้จะถูกลบออกเมื่อคัดลอกลิงก์",
        urlCleanerRulesCoverageCaption: "รายการนี้ครอบคลุมเส้นทางการแชร์ที่หลากหลายของแต่ละเว็บไซต์ ซึ่งทำให้ลิงก์ที่แชร์สะอาดและปลอดภัยยิ่งขึ้น",
        urlCleanerRulesAllSites: "ทุกเว็บไซต์",
        urlCleanerRulesCountSingular: "1 พารามิเตอร์",
        urlCleanerRulesCountPluralFormat: "%d พารามิเตอร์",
        urlCleanerRulesAddSite: "เพิ่มเว็บไซต์",
        urlCleanerRulesParameterPlaceholder: "ชื่อพารามิเตอร์",
        urlCleanerRulesMatchCaption: "ระบุชื่อพารามิเตอร์ทางซ้ายของเครื่องหมาย = เช่น utm_source ซึ่งจะถูกลบออกจากลิงก์",
        urlCleanerRulesAddButton: "เพิ่ม",
        urlCleanerRulesRemoveButton: "ลบพารามิเตอร์",
        urlCleanerRulesRemoveSiteButton: "ลบกฎทั้งหมดของเว็บไซต์นี้",
        urlCleanerRemovedFormat: "ลบ %@ แล้ว",
        switcherSearchPin: "ปักหมุดค้นหาด้วยปุ่ม S",
        switcherSearchPinCaption: "กด S เพื่อเริ่มค้นหาและปักหมุดตัวสลับแอป ช่วยป้องกันไม่ให้การพิมพ์ค้นหาไปสั่งปิดหน้าต่างหรือออกจากแอปโดยไม่ได้ตั้งใจ",
        invertVerticalScroll: "สลับการเลื่อนแนวตั้ง",
        invertHorizontalScroll: "สลับการเลื่อนแนวนอน",
        scrollHorizontalName: "เลื่อนแนวนอนขณะกดปุ่มพิเศษค้างไว้",
        scrollHorizontalModifierLabel: "ปุ่มพิเศษ (Modifier Key)",
        scrollHorizontalCommandKey: "Command (⌘)",
        scrollHorizontalCaption: "กดปุ่มพิเศษที่เลือกค้างไว้เพื่อเปลี่ยนการหมุนล้อเมาส์แนวตั้งให้เลื่อนในแนวนอน",
        switcherShowShortcutHints: "แสดงคำแนะนำปุ่มลัด",
        switcherShowShortcutHintsCaption: "แสดงปุ่มลัดของแอปและหน้าต่างด้านล่างไอคอน",
        uninstallerHomebrewPackageFormat: "%@ จะถูกถอนการติดตั้งออกจาก Homebrew ด้วย",
        shelfEdgeToggle: "เปิดเมื่อลากเข้าใกล้ขอบหน้าจอ",
        shelfEdgeCaption: "ลากไฟล์ไปชิดขอบหน้าจอเพื่อเรียกชั้นวางพักไฟล์ออกมา",
        focusFollowsMouseName: "โฟกัสหน้าต่างตามตัวชี้เมาส์",
        focusFollowsMouseCaption: "สลับโฟกัสและนำหน้าต่างใต้ตัวชี้เมาส์ขึ้นมาด้านหน้าอัตโนมัติหลังจากวางเมาส์ค้างไว้ครู่หนึ่ง",
        focusFollowsMouseDelay: "ความล่าช้าในการวางเมาส์",
        switcherMinimizedPlacementLabel: "ตำแหน่งหน้าต่างที่ย่อไว้",
        switcherTreatHiddenAppsLikeMinimized: "จัดการแอปที่ซ่อนอยู่เหมือนกับหน้าต่างที่ย่อไว้",
        switcherMinimizedPlacementNormal: "เรียงตามลำดับปกติ",
        switcherMinimizedPlacementEnd: "วางไว้ท้ายสุด",
        switcherMinimizedPlacementHidden: "ซ่อน",
        switcherShowFullscreenWindows: "แสดงหน้าต่างแบบเต็มหน้าจอ",
        switcherScreenPlacementLabel: "แสดงบนหน้าจอ",
        switcherScreenPlacementPointer: "หน้าจอที่มีตัวชี้เมาส์อยู่",
        switcherScreenPlacementMenuBar: "หน้าจอหลักที่มีแถบเมนู",
        switcherScreenPlacementActiveWindow: "หน้าจอที่มีหน้าต่างใช้งานอยู่",
        switcherScreenPlacementCaption: "เลือกจอแสดงผลที่ตัวสลับแอปจะเปิดขึ้นเมื่อเชื่อมต่อหลายหน้าจอ",
        switcherCurrentDisplayOnly: "แสดงเฉพาะหน้าจอที่ใช้งานอยู่",
        switcherCurrentDisplayOnlyCaption: "แสดงเฉพาะหน้าต่างบนจอแสดงผลที่ตัวชี้เมาส์อยู่",
        smoothScrollResponseLabel: "การตอบสนอง",
        smoothScrollCoastLabel: "การเคลื่อนที่ต่อเนื่อง",
        mouseAccelerationName: "ปิดการเร่งความเร็วของเมาส์ (Mouse Acceleration)",
        mouseAccelerationCaption: "ปิดการเร่งความเร็วของตัวชี้เมาส์เพื่อให้การเคลื่อนที่เป็นเส้นตรงและแม่นยำยิ่งขึ้น การตั้งค่าเดิมจะกลับมาเมื่อปิดตัวเลือกนี้หรือปิดแอป",
        shelfClearOnClose: "ล้างรายการเมื่อปิด",
        shelfClearOnCloseCaption: "ล้างไฟล์ทั้งหมดบนชั้นวางพักไฟล์เมื่อปิดแผง"
    )
}
