// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

extension Strings {
    static let he = Strings(
        statusIdleTooltip: "Vorssaint: שינה רגילה",
        statusActiveUntil: "Vorssaint: ער עד",
        statusActiveIndefinite: "Vorssaint: ער ללא הגבלה",
        menuEnableAwake: "הפעל שמירה על ערנות",
        menuDisableAwake: "כבה שמירה על ערנות",
        menuActivateFor: "הפעל למשך…",
        menuSettings: "הגדרות…",
        menuAbout: "אודות Vorssaint",
        menuQuit: "צא מ-Vorssaint",
        menuHide: "הסתר את Vorssaint",
        menuHideOthers: "הסתר אחרים",
        menuShowAll: "הצג הכל",
        menuEdit: "עריכה",
        menuUndo: "בטל",
        menuRedo: "בצע שוב",
        menuCut: "גזור",
        menuCopy: "העתק",
        menuPaste: "הדבק",
        menuSelectAll: "בחר הכל",
        menuWindow: "חלון",
        menuMinimize: "מזער",
        menuZoom: "זום",
        menuClose: "סגור",

        minutes15: "15 דקות",
        minutes30: "30 דקות",
        hour1: "שעה אחת",
        hours2: "שעתיים",
        hours4: "4 שעות",
        hours8: "8 שעות",
        indefinitely: "ללא הגבלה",
        indefinite: "ללא הגבלה",

        panelSettings: "הגדרות",
        panelQuit: "צא",
        panelHotkeyHint: "קיצור מחליף",

        keepAwakeTitle: "שמור ערנות",
        keepAwakeEndsIn: "מסתיים בעוד",
        keepAwakeUntilDisabled: "פעיל עד שתכבה אותו",
        keepAwakeNormalRules: "ה-Mac פועל לפי כללי האנרגיה הרגילים",
        keepAwakeOptions: "אפשרויות",
        keepAwakeMouseJiggle: "הזז מעט את הסמן",
        keepAwakeMouseJiggleCaption: "במהלך סשן, מזיז מעט את הסמן במרווח הנבחר.",
        keepAwakeMouseJiggleInterval: "מרווח",
        keepAwakeActiveIconLabel: "סמל פעיל",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "קפה",
        keepAwakeActiveIconEye: "עין",
        keepAwakeActiveIconMoon: "ירח",
        keepAwakeActiveIconLight: "נורה",
        keepAwakeIconTintLabel: "צבע סמל פעיל",
        keepAwakeIconTintOrange: "כתום",
        keepAwakeIconTintGreen: "ירוק",
        keepAwakeIconTintBlue: "כחול",
        keepAwakeIconTintPurple: "סגול",
        keepAwakeIconTintPink: "ורוד",
        keepAwakeIconTintNone: "ללא צבע",
        durationLabel: "משך",
        clamshellTitle: "המשך עם מכסה סגור",
        clamshellOnCaption: "שינה מנוטרלת לחלוטין. שים לב לצריכת החשמל",
        clamshellNeedsSession: "מופעל בכל פעם ש'שמור ערנות' פעיל",
        clamshellReady: "מוכן. עובד ללא סיסמה",
        clamshellNeedsPassword: "יבקש סיסמת מנהל פעם אחת",

        systemSection: "מערכת",
        temperatures: "טמפרטורות",
        cpuLabel: "מעבד",
        gpuLabel: "מעבד גרפי",
        batteryLabel: "סוללה",
        usageSection: "שימוש בחומרה",
        memorySection: "זיכרון",
        memoryPressure: "לחץ",
        memorySwapUsed: "Swap בשימוש",
        memoryCompressed: "דחוס",
        memoryCachedFiles: "קבצים במטמון",
        pressureNormal: "תקין",
        pressureWarning: "אזהרה",
        pressureCritical: "קריטי",
        monitorUnavailable: "חיישנים לא זמינים ב-Mac זה",
        energyAppsTitle: "אפליקציות צורכות אנרגיה רבה",
        energyAppsIdle: "אין שימוש משמעותי באנרגיה",

        notifySessionEndedTitle: "הסשן הסתיים",
        notifySessionEndedBody: "הזמן נגמר. ה-Mac יחזור לישון כרגיל.",
        notifyBatteryTitle: "Vorssaint כבוי",
        notifyBatteryBody: "סוללה חלשה. שינה רגילה הוחזרה להגנה על המטען.",
        adminPromptClamshellOn: "Vorssaint צריך את הסיסמה שלך כדי להשאיר את ה-Mac פעיל עם מכסה סגור.",
        adminPromptClamshellOff: "Vorssaint צריך את הסיסמה שלך כדי להחזיר את השינה הרגילה של ה-Mac.",
        adminPromptRecover: "Vorssaint נסגר בזמן שהשינה של ה-Mac הייתה מנוטרלת. הזן את הסיסמה להחזרת שינה רגילה.",
        adminPromptUpdate: "Vorssaint צריך את הסיסמה שלך כדי להתקין את העדכון.",
        adminPromptSudoersInstall: "Vorssaint יצור כלל מוגבל (pmset disablesleep בלבד) להפעלת מצב מכסה סגור ללא בקשת סיסמה. זו הפעם היחידה שהסיסמה תידרש.",
        adminPromptSudoersRemove: "Vorssaint יסיר את הכלל למכסה סגור ללא סיסמה.",

        settingsTitle: "הגדרות Vorssaint",
        tabGeneral: "כללי",
        tabEnergy: "אנרגיה",
        tabMouse: "עכבר וטראקפד",
        tabSwitcher: "מחליף",
        tabAdvanced: "מתקדם",
        tabAbout: "אודות",
        tabReleaseNotes: "מה חדש",
        releaseNotesOnUpdateToggle: "הצג מה חדש לאחר עדכון",
        previewSizeLabel: "גודל תצוגה מקדימה",
        previewSizeNormal: "רגיל",
        previewSizeLarge: "גדול",
        previewSizeXLarge: "גדול מאוד",
        settingsGroupFeatures: "תכונות",
        advancedResetSection: "הרשאות",
        advancedResetDescription: "מסיר כל הרשאה שנתת ל-Vorssaint (נגישות, הקלטת מסך, גישה מלאה לדיסק ואחרות), את פריט ההתחלה ואת כלל המכסה הסגור. שימושי להתחלה מחדש או לפני הסרה. האפליקציה נשארת מותקנת.",
        advancedClearButton: "נקה את כל ההרשאות",
        advancedCleared: "הרשאות נוקו.",
        advancedClearConfirmTitle: "לנקות את כל ההרשאות?",
        advancedClearConfirmBody: "תכונות שדורשות הרשאות יפסיקו לעבוד עד שתעניק אותן שוב. ההגדרות שלך נשמרות.",
        advancedUninstallSection: "הסרה",
        advancedUninstallDescription: "עושה את כל הנ״ל, ואז מסיר את ההעדפות ומעביר את Vorssaint לאשפה, בלי להשאיר דבר. האפליקציה נסגרת בסיום. ניתן להתקין מחדש בכל עת.",
        advancedUninstallButton: "הסר את Vorssaint לחלוטין",
        advancedUninstallConfirmTitle: "להסיר את Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint ינקה את ההרשאות שלו, יסיר את ההעדפות ויעבור לאשפה, ואז ייסגר. זה לא ניתן לביטול מהאפליקציה, אבל הוא נשאר באשפה עד שתרוקן אותה.",

        launchAtLogin: "הפעל בהתחברות",
        languageLabel: "שפה",
        menuBarSection: "שורת התפריטים",
        showCountdown: "הצג זמן נותר ליד הסמל",
        globalHotkeySection: "קיצור גלובלי",
        hotkeyToggle: "הפעל קיצור ל'שמור ערנות'",
        hotkeyCaption: "עובד בכל אפליקציה, בלי הרשאות נוספות.",

        sessionSection: "סשן",
        defaultDurationLabel: "משך ברירת מחדל",
        keepAwakeAutoStart: "שמור ערנות כש-Vorssaint נפתח",
        keepAwakeAutoStartCaption: "מתחיל סשן עם משך ברירת המחדל.",
        batteryProtectionSection: "הגנת סוללה",
        batteryDisableBelow: "כבה כשהסוללה יורדת מתחת ל",
        batteryNever: "לעולם לא",
        batteryProtectionCaption: "מונע מסשן שנשכח לרוקן את סוללת ה-MacBook.",
        clamshellSection: "מכסה סגור",
        configuring: "מגדיר…",
        sudoersFailed: "לא ניתן להפעיל מצב מכסה סגור. נסה שוב.",
        clamshellExplanation: "'המשך עם מכסה סגור' מנטרל לחלוטין את השינה בזמן ש'שמור ערנות' פעיל ומבוטל אוטומטית כשהסשן מסתיים או האפליקציה נסגרת. מומלץ להשתמש בחיבור לחשמל.",

        scrollSection: "גלילה",
        invertMouseScroll: "הפוך גלילת עכבר",
        invertMouseScrollCaption: "הופך את כיוון גלגל העכבר.",
        scrollTrackpadNote: "הטראקפד לא משתנה: שומר על הגלילה הטבעית של macOS.",
        scrollActiveNow: "הופך גלילת עכבר עכשיו",
        mouseNavigationActiveNow: "כפתורים צדדיים פעילים עכשיו",
        smoothScrollName: "גלילה חלקה",
        smoothScrollCaption: "הופך כל צעד של גלגל העכבר לגלישה קצרה ועדינה. הטראקפד לא מושפע.",
        smoothScrollStepLabel: "מרחק לכל צעד",
        mouseNavigationSection: "ניווט",
        mouseNavigationEnable: "השתמש בכפתורים צדדיים לאחור וקדימה",
        mouseNavigationCaption: "הופך את כפתורי האחור והקדימה של העכבר לפקודות ניווט ב-Finder, דפדפנים ואפליקציות תואמות.",
        middleClickSection: "לחיצה אמצעית",
        middleClickEnable: "לחיצה בשלוש אצבעות פועלת כלחיצה אמצעית",
        middleClickEnableCaption: "לחיצה על הטראקפד עם שלוש אצבעות עובדת כמו לחיצה על גלגל העכבר: פותחת קישורים בלשונית חדשה, סוגרת לשוניות וכל מה שהכפתור האמצעי עושה.",
        middleClickDragConflict: "גרירה בשלוש אצבעות של macOS מופעלת ומשתמשת באותה מחווה. כבה אותה בהגדרות המערכת תחת נגישות, בקרת סמן, אפשרויות טראקפד, והלחיצה האמצעית תעבוד.",
        middleClickTapPicker: "הקשה קלה גם לוחצת",
        middleClickTapOff: "כבוי",
        middleClickTapThreeFingers: "3 אצבעות",
        middleClickTapFourFingers: "4 אצבעות",
        middleClickTapCaption: "הקשה קלה עם מספר זה של אצבעות, בלי ללחוץ, גם מפעילה את הלחיצה האמצעית. החלקה לעולם לא נחשבת. אם הקשה בשלוש אצבעות של macOS מוקצת לחיפוש, כבה אותה כדי ששניהם לא יופעלו יחד.",
        quickToolsTab: "פאנל מהיר",
        quickToolShortcutToggle: "קיצור גלובלי",
        ocrName: "העתק טקסט מהמסך",
        ocrCaption: "בחר אזור במסך והטקסט המזוהה מועתק, מוכן להדבקה.",
        ocrCopied: "טקסט הועתק",
        ocrNoText: "לא נמצא טקסט",
        colorPickerName: "בוחר צבע",
        colorPickerCaption: "לכוד את הצבע של כל פיקסל במסך והעתק אותו בפורמט המועדף עליך.",
        colorPickerFormatLabel: "פורמט מועתק",
        colorPickerBareHexToggle: "העתק ללא הקידומת #",
        colorPickerPickNow: "בחר צבע",
        micMuteName: "השתק מיקרופון",
        micUnmuteName: "הפעל מיקרופון מחדש",
        micMuteCaption: "חותך את המיקרופון של ה-Mac בלחיצה או קיצור, בכל אפליקציה.",
        micMutedHUD: "מיקרופון מושתק",
        micUnmutedHUD: "מיקרופון הופעל מחדש",
        micMuteMenuBarToggle: "הצג בשורת התפריטים בזמן השתקה",
        micMuteMenuBarCaption: "מיקרופון מושתק באדום מופיע ליד סמל האפליקציה בשורת התפריטים.",
        pastePlainName: "הדבק כטקסט רגיל",
        pastePlainCaption: "מדביק את מה שהעתקת בלי צבעים, גופנים או עיצוב. המקור נשאר בלוח ההעתקה.",
        launcherName: "פאנל מהיר",
        launcherCaption: "פאנל צף עם הכלים האהובים עליך, הנקרא בקיצור מכל מקום.",
        launcherOpenNow: "פתח פאנל מהיר",
        launcherEditHint: "השתמש בכפתור הכיוונון לבחירה, הסתרה וגרירה של הכלים.",
        launcherEmptyState: "כל הכלים מוסתרים. השתמש בכפתור הכיוונון להחזרתם.",
        launcherAddSection: "הוסף בחזרה",
        launcherKeysHint: "חיצים לניווט, Enter פותח, 1 עד 9 פותחים ישירות",

        switcherSection: "מחליף אפליקציות",
        switcherEnable: "השתמש במחליף של Vorssaint",
        switcherEnableCaption: "עבור בין אפליקציות וחלונות, כולל חלונות ממוזערים ומספר חלונות מאותה אפליקציה.",
        switcherUsageHint: "החזק את הקיצור לניווט; שחרר להפעלת החלון. Shift או ← חוזרים אחורה; W סוגר את החלון; Q סוגר את האפליקציה; Esc מבטל.",
        switcherNoWindows: "אין חלונות פתוחים",
        switcherIconRowMode: "הצג %@ עם סמלים גדולים",
        switcherIconRowModeCaption: "מציג סמל אחד לכל אפליקציה עם תצוגות מקדימות של החלונות שלה מעליו.",
        switcherSimpleMode: "מחליף אפליקציות פשוט",
        switcherSimpleModeCaption: "מציג סמלי אפליקציות וכותרות חלונות, בלי תצוגות מקדימות או לכידת מסך על ידי המחליף.",
        switcherShortcutHintApps: "אפליקציות",
        switcherShortcutHintWindows: "חלונות",
        switcherWindowShortcutCaption: "פותח מחליף לחלונות של האפליקציה הקדמית. כשמחליף האפליקציות פתוח, קופץ בין חלונות האפליקציה הנבחרת.",
        switcherAppearanceDelay: "השהיית הופעה",
        switcherAppearanceDelayCaption: "כמה זמן הקיצור צריך להיות לחוץ לפני שהמחליף מופיע.",
        switcherMergeTabs: "הצג ערך אחד לכל אפליקציה",
        switcherMergeTabsCaption: "מכווץ את כל חלונות האפליקציה לערך אחד במחליף, במקום ערך אחד לכל חלון.",
        switcherWindowlessApps: "אפליקציות ללא חלון פתוח",
        switcherWindowlessAppsCaption: "בוחר אילו אפליקציות פועלות ללא חלון בכלל מופיעות במחליף.",
        switcherWindowlessAppsOff: "אל תציג",
        switcherWindowlessAppsFinder: "רק Finder",
        switcherWindowlessAppsAll: "כל האפליקציות",
        switcherNoOpenWindow: "אין חלון פתוח",
        switcherOtherDesktop: "שולחן עבודה אחר",
        dockPreviewName: "תצוגה מקדימה ב-Dock",
        dockPreviewEnable: "תצוגה מקדימה של חלונות ב-Dock",
        dockPreviewEnableCaption: "עבור עם העכבר על אפליקציה פתוחה ב-Dock לראות את החלונות שלה ולחץ על זה שתרצה לפתוח.",
        dockPreviewBackgroundOpacity: "רקע הפאנל",
        dockPreviewBackgroundOpacityCaption: "הפחת לראות יותר ממה שמאחורי הפאנל.",
        dockPreviewOpenDelay: "השהיית פתיחה",
        dockPreviewOpenDelayCaption: "כמה זמן הסמן צריך להיות מעל סמל לפני שהפאנל נפתח.",
        dockPreviewQuitAppOnClose: "סגור אפליקציה עם כפתור ×",
        dockPreviewQuitAppOnCloseCaption: "בתצוגה מקדימה ב-Dock, × סוגר את כל האפליקציה במקום רק את החלון הזה.",
        dockClickMinimize: "לחיצה ב-Dock ממזערת",
        dockClickMinimizeCaption: "חלונות האפליקציה הפעילה ממוזערים בלחיצה על הסמל שלהם ב-Dock. לחץ שוב להחזרתם.",
        dockClickCycleWindows: "לחיצה ב-Dock מחליפה חלונות",
        dockClickCycleWindowsCaption: "לחץ על סמל ה-Dock של האפליקציה הפעילה למעבר בין החלונות שלה, כמו ⌘`.",
        dockPreviewActiveNow: "פעיל ב-Dock",
        dockPreviewDockUnavailable: "לא ניתן לקרוא את פריטי ה-Dock.",
        dockPreviewAutohideBeta: "בטא. ייתכנו כמה באגים.",
        dockPreviewOpenWindow: "פתח חלון",
        dockPreviewCloseWindow: "סגור חלון",
        dockPreviewMinimizeWindow: "מזער חלון",
        dockPreviewRestoreWindow: "שחזר חלון",
        dockPreviewPinPanel: "הצמד תצוגה",
        dockPreviewUnpinPanel: "בטל הצמדה",
        dockPreviewPinned: "מוצמד",
        dockPreviewClosePanel: "סגור תצוגה",
        dockPreviewPreviousWindow: "חלון קודם",
        dockPreviewNextWindow: "חלון הבא",

        cutPasteName: "גזור והדבק",
        cutPasteEnable: "גזור והדבק קבצים ב-Finder",
        cutPasteEnableCaption: "השתמש ב-⌘X לגזירה ו-⌘V להעברת קבצים ותיקיות ב-Finder.",
        cutPasteShowHUD: "הצג פאנל צף",
        cutPasteShowHUDCaption: "מציג אינדיקטור צף עם הקבצים הגזורים בזמן שה-Finder פעיל.",
        cutPasteHowTitle: "איך להשתמש",
        cutPasteStep1: "בחר פריטים ב-Finder ולחץ ⌘X לגזירתם.",
        cutPasteStep2: "פתח את תיקיית היעד ולחץ ⌘V להעברתם לשם.",
        cutPasteTextNote: "בשדות טקסט (כמו בשינוי שם), ⌘X ו-⌘V ממשיכים לעבוד כרגיל.",
        cutPasteActiveNow: "מוכן לגזירה ב-Finder",
        cutPasteAutomationNote: "בפעם הראשונה, macOS יבקש הרשאה לשלוט ב-Finder.",
        cutReadyTitle: "גזור",
        cutReadyHint: "בתיקיית היעד להעברה",
        cutCancel: "בטל גזירה",
        cutDoneTitle: "הועבר!",
        cutMovedSingular: "פריט אחד הועבר",
        cutMovedPluralFormat: "%d פריטים הועברו",
        cutSomeFailed: "חלק מהפריטים לא ניתן היה להעביר",
        cutMovingTitle: "מעביר…",
        cutMovingCountFormat: "%d מתוך %d",

        autoQuitName: "צא בסגירה",
        autoQuitEnable: "צא מאפליקציה בסגירת החלון האחרון",
        autoQuitEnableCaption: "סגירת החלון האחרון של אפליקציה גם סוגרת אותה.",
        autoQuitActiveNow: "פעיל עכשיו",
        autoQuitHowTitle: "איך זה עובד",
        autoQuitStep1: "סגור את החלון האחרון של אפליקציה (⌘W או הכפתור האדום).",
        autoQuitStep2: "האפליקציה נסגרת מעצמה. דיאלוגים של 'לשמור?' ממשיכים להופיע.",
        autoQuitPredictableNote: "אפליקציות שעובדות בדרך כלל בלי חלון לעולם לא נסגרות.",
        autoQuitExceptionsTitle: "חריגים",
        autoQuitExceptionsCaption: "אפליקציות ברשימה זו נשארות פתוחות גם ללא חלונות.",
        autoQuitExceptionsEmpty: "אין חריגים",
        autoQuitAddApp: "הוסף אפליקציה…",

        uninstallerName: "מסיר התקנה",
        uninstallerEnableCaption: "מסיר אפליקציה יחד עם מטמונים, העדפות, יומנים ושאריות שהשאירה מאחור.",
        uninstallerStep1: "גרור אפליקציה להגדרות או בחר אחת מהרשימה.",
        uninstallerStep2: "סקור את הקבצים שנמצאו וכמה מקום הם תופסים.",
        uninstallerStep3: "העבר לאשפה מה שתרצה. שום דבר לא נמחק לצמיתות.",
        uninstallerMenuItem: "הסר התקנה של אפליקציה…",
        uninstallerDropTitle: "גרור אפליקציה לכאן",
        uninstallerDropSubtitle: "או בחר אחת לניתוח",
        uninstallerChoose: "בחר אפליקציה…",
        uninstallerPickerTitle: "בחר אפליקציה",
        uninstallerPickerSearch: "חפש אפליקציות",
        uninstallerPickerEmpty: "לא נמצאו אפליקציות",
        uninstallerEmptyNote: "שום דבר לא מוסר ללא אישורך.",
        uninstallerFDANote: "הענק גישה מלאה לדיסק לניתוח מקיף יותר.",
        uninstallerFDAGrant: "הענק גישה…",
        uninstallerFDAHint: "הפעל את Vorssaint ברשימה. אם הוא לא מופיע, לחץ על + ובחר את Vorssaint באפליקציות. הגישה חלה רק לאחר פתיחה מחדש של האפליקציה.",
        uninstallerFDARelaunch: "פתח מחדש עכשיו",
        uninstallerScanning: "מנתח קבצים…",
        uninstallerRemoving: "מעביר לאשפה…",
        uninstallerFoundTitle: "נמצאו",
        uninstallerSelectedFormat: "%d מתוך %d נבחרו",
        uninstallerRemove: "העבר לאשפה",
        uninstallerCancel: "בטל",
        uninstallerDoneTitle: "מוכן!",
        uninstallerFreedFormat: "%@ שוחררו",
        uninstallerSomeFailed: "חלק מהפריטים לא ניתן היה להעביר לאשפה.",
        uninstallerFailedNeedsFDA: "נתונים של אפליקציות באזור מוגן ניתנים להעברה רק עם גישה מלאה לדיסק. סיסמת מנהל לא מחליפה הרשאה זו.",
        uninstallerFailedMoreFormat: "ו-%d נוספים",
        uninstallerAnother: "הסר התקנה של אחרת",
        uninstallerCatApp: "אפליקציה",
        uninstallerCatSupport: "תמיכה",
        uninstallerCatCaches: "מטמונים",
        uninstallerCatPreferences: "העדפות",
        uninstallerCatContainers: "מיכלים",
        uninstallerCatLogs: "יומנים",
        uninstallerCatState: "מצב שמור",
        uninstallerCatOther: "אחרים",

        urlCleanerName: "נקה URL",
        urlCleanerEnable: "נקה URL בהעתקה",
        urlCleanerEnableCaption: "מסיר פרמטרי מעקב מקישור ברגע שהוא מגיע ללוח ההעתקה.",
        urlCleanerActiveNow: "פעיל עכשיו",
        urlCleanerManualTitle: "נקה עכשיו",
        urlCleanerInputPlaceholder: "הדבק URL",
        urlCleanerOutputPlaceholder: "ה-URL הנקי מופיע כאן",
        urlCleanerCleanButton: "נקה",
        urlCleanerPasteButton: "הדבק",
        urlCleanerCopyButton: "העתק",
        urlCleanerClearButton: "נקה שדה",
        urlCleanerNoURL: "הדבק URL תקין.",
        urlCleanerNoChange: "אין מה לנקות.",
        urlCleanerCleaned: "URL נוקה.",
        urlCleanerCopied: "הועתק.",
        urlCleanerLocalNote: "מקומי. בלי רשת.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "חפש, התקן והסר נוסחאות וחביונות.",
        homebrewMissingTitle: "Homebrew לא נמצא",
        homebrewMissingBody: "Vorssaint יכול לפתוח טרמינל עם מתקין Homebrew הרשמי. הטרמינל מציג את השלבים ומבקש את הסיסמה שלך אם צריך.",
        homebrewInstallHomebrew: "התקן Homebrew",
        homebrewInstallHomebrewCaption: "כשתסיים בטרמינל, חזור לכאן ולחץ רענן.",
        homebrewInstallHomebrewOpened: "מתקין נפתח בטרמינל.",
        homebrewShellSetupTitle: "סיום הגדרת טרמינל",
        homebrewShellSetupBody: "Homebrew מותקן, אבל הטרמינל עדיין עלול לא למצוא את פקודת brew. Vorssaint יכול לפתוח טרמינל עם פקודת ההגדרה.",
        homebrewShellSetupButton: "הגדר טרמינל",
        homebrewShellSetupOpened: "פקודה נפתחה בטרמינל. אחר כך חזור לכאן ולחץ רענן.",
        homebrewRefresh: "רענן",
        homebrewCheckPackages: "בדוק חבילות",
        homebrewTrustTitle: "Tap עדיין לא מהימן",
        homebrewTrustCaption: "Homebrew עכשיו מבקש את אישורך לפני שימוש ב-taps של צד שלישי. תן אמון ב-%@ להמשך.",
        homebrewTrustButton: "תן אמון והמשך",
        homebrewSearchPlaceholder: "חפש חבילות",
        homebrewKeyboardHint: "רווח או Enter סוגרים את הפאנל של macOS. השתמש בכפתור החיפוש.",
        homebrewSearchButton: "חפש",
        homebrewSearchResults: "תוצאות",
        homebrewInstalled: "מותקנים",
        homebrewAll: "הכל",
        homebrewFormulas: "נוסחאות",
        homebrewCasks: "חביונות",
        homebrewNoPackages: "לא נמצאו חבילות",
        homebrewNoSelection: "בחר חבילה מותקנת או חפש חדשה.",
        homebrewDetailsTitle: "פרטי חבילה",
        homebrewInstall: "התקן",
        homebrewUninstall: "הסר",
        homebrewUpgrade: "שדרג",
        homebrewUpgradeAll: "שדרג הכל",
        homebrewUpdateHomebrew: "עדכן Homebrew",
        homebrewAllPackages: "חבילות",
        homebrewOpenTerminal: "פתח טרמינל",
        homebrewCancelOperation: "בטל",
        homebrewClearLog: "נקה יומן",
        homebrewLogTitle: "יומן",
        homebrewVersion: "גרסה",
        homebrewDescription: "סוג",
        homebrewHomepage: "פתח אתר",
        homebrewPopularity: "פופולריות",
        homebrewPopularityFormat: "%@ התקנות ב-%@ ימים",
        homebrewInstalledBadge: "מותקן",
        homebrewNotInstalledBadge: "לא מותקן",
        homebrewUpdates: "עדכונים",
        homebrewUpdateAvailableBadge: "עדכון זמין",
        homebrewLatestVersion: "הכי חדש",
        homebrewConfirmInstallTitle: "להתקין עם Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew יוריד ויתקין את %@. ייתכן ויתקין גם תלויות.",
        homebrewConfirmUninstallTitle: "להסיר עם Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew יסיר את %@. קבצי תצורה עלולים להישאר במערכת.",
        homebrewConfirmUpgradeTitle: "לשדרג עם Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew יוריד ויחיל את הגרסה האחרונה של %@. ייתכן וישדרג גם תלויות.",
        homebrewConfirmUpgradeAllTitle: "לשדרג הכל עם Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew יוריד ויחיל את הגרסאות האחרונות של החבילות עם עדכונים זמינים. ייתכן וישדרג גם תלויות.",
        homebrewConfirmUpdateHomebrewTitle: "לעדכן את Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew יחפש את המידע העדכני ביותר ואז יטען מחדש את החבילות שלך.",
        homebrewTerminalFallback: "פעולה זו צריכה טרמינל כדי לבקש סיסמת מנהל. Vorssaint לא לוכד סיסמאות.",
        homebrewLoading: "טוען…",
        homebrewSearchEmpty: "אין תוצאות",
        homebrewOperationInstallFormat: "מתקין את %@",
        homebrewOperationUninstallFormat: "מסיר את %@",
        homebrewOperationUpgradeFormat: "משדרג את %@",
        homebrewOperationUpgradeAll: "משדרג חבילות",
        homebrewOperationUpdateHomebrew: "מעדכן את Homebrew",
        homebrewOperationInstalledFormat: "%@ הותקן.",
        homebrewOperationUninstalledFormat: "%@ הוסר.",
        homebrewOperationUpgradedFormat: "%@ שודרג.",
        homebrewOperationUpgradedAll: "חבילות שודרגו.",
        homebrewOperationUpdatedHomebrew: "Homebrew עודכן.",
        homebrewOperationFailedFormat: "לא ניתן להשלים את %@.",
        homebrewOperationCancelled: "פעולה בוטלה.",
        homebrewOperationPreparing: "מכין...",
        homebrewOperationDownloading: "מוריד קבצים...",
        homebrewOperationInstalling: "מתקין קבצים...",
        homebrewOperationUninstalling: "מסיר קבצים...",
        homebrewOperationUpgrading: "משדרג קבצים...",
        homebrewOperationFinalizing: "מסיים...",
        homebrewOperationRefreshing: "מרענן רשימה...",
        homebrewOperationTerminal: "המשך בטרמינל.",
        homebrewOperationElapsedFormat: "%@ חלפו",
        homebrewOperationShowDetails: "הצג פרטים",
        homebrewOperationHideDetails: "הסתר פרטים",
        homebrewOperationTechnicalLog: "פרטים טכניים",
        homebrewOperationProgressUnknown: "Homebrew עדיין לא דיווח אחוז.",

        mediaName: "מדיה",
        mediaEnableCaption: "דחוס סרטונים, המר ועבד תמונות, צור GIFs וחלץ טקסט מקומית.",
        mediaLocalNote: "מקומי. בלי רשת.",
        mediaToolVideo: "סרטון",
        mediaToolGIF: "GIF",
        mediaToolImage: "תמונה",
        mediaToolText: "טקסט",
        mediaSelectFile: "בחר קובץ",
        mediaDropHint: "גרור קובץ לכאן או לחץ לבחירה.",
        mediaOutput: "פלט",
        mediaOutputAutomatic: "אוטומטי",
        mediaChooseOutput: "יעד",
        mediaStartVideo: "דחוס סרטון",
        mediaStartGIF: "צור GIF",
        mediaStartImage: "עבד תמונה",
        mediaStartConvertPDF: "המר ל-PDF",
        mediaStartText: "חלץ טקסט",
        mediaCancel: "בטל",
        mediaStartTime: "התחלה",
        mediaEndTime: "סיום",
        mediaQuality: "דחיסה",
        mediaCompressionLow: "נמוכה",
        mediaCompressionMedium: "בינונית",
        mediaCompressionHigh: "גבוהה",
        mediaMaxSize: "גודל",
        mediaSizingResolution: "רזולוציה",
        mediaSizingFileSize: "גודל קובץ",
        mediaTargetSize: "גודל יעד",
        mediaTargetSizeHint: "הרזולוציה מותאמת להישאר מתחת למגבלה.",
        mediaErrorTargetTooSmall: "גודל יעד קטן מדי לקטע זה. קצר אותו או הגדל את המגבלה.",
        mediaMegabytesSuffix: " מ\"ב",
        mediaWidth: "רוחב",
        mediaFPS: "FPS",
        mediaKeepAudio: "שמור אודיו",
        mediaCodec: "מקודד",
        mediaFormat: "פורמט",
        mediaStripMetadata: "הסר מטא-נתונים",
        mediaLoopGIF: "חזור על GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "מדויק",
        mediaOCRFast: "מהיר",
        mediaLanguageCorrection: "תיקון שפה",
        mediaTextOutputNote: "הטקסט שחולץ ניתן להעתקה ושמירה כ-TXT.",
        mediaRunning: "מעבד",
        mediaCompleted: "הושלם",
        mediaCancelled: "בוטל.",
        mediaOpenInFinder: "הצג",
        mediaCopyText: "העתק טקסט",
        mediaRunAgain: "הרץ שוב",
        mediaEmptyText: "לא נמצא טקסט.",
        mediaResultSavedFormat: "נשמר כ-%@",
        mediaResultSizeFormat: "%@ ל-%@",
        mediaResultGrewCaption: "הקובץ המומר גדול יותר מהמקורי.",
        mediaErrorNoFile: "בחר קובץ קודם.",
        mediaErrorNoVideo: "קובץ זה אינו מכיל רצועת וידאו.",
        mediaErrorSameOutput: "בחר יעד שונה מהקובץ המקורי.",
        mediaErrorUnsupported: "פורמט לא נתמך על ידי macOS.",

        shelfName: "מדף",
        shelfEnable: "אזור זמני לגרירת קבצים",
        shelfEnableCaption: "מרחב צף לאיסוף קבצים, תמונות וטקסט, ואז לגרירתם לכל מקום.",
        shelfHowTitle: "איך להשתמש",
        shelfStep1: "פתח עם הקיצור או על ידי ניעור העכבר בזמן גרירה.",
        shelfStep2: "שחרר עליו קבצים, תמונות, קישורים או טקסט לשמירה.",
        shelfStep3: "גרור כל פריט בחזרה לכל אפליקציה כשתצטרך.",
        shelfShakeToggle: "פתח על ידי ניעור העכבר בזמן גרירה",
        shelfShakeCaption: "נער את הסמן במהירות בזמן שאתה מחזיק פריט כדי לקרוא לאזור ליד הסמן.",
        shelfDropZoneToggle: "שמור קבצים בשורת התפריטים בזמן גרירה",
        shelfDropZoneCaption: "בזמן גרירת קובץ, האזור מופיע מתחת לסמל בשורת התפריטים. מה שתשחרר נשמר שם, בכפתור שאתה מכווץ ופותח בלחיצה ושנעלם כשהאזור ריק.",
        shelfDropZoneLabel: "שחרר כאן",
        shelfCollapse: "כווץ",
        shelfBehaviorTitle: "אחרי השימוש",
        shelfCloseAfterDrop: "סגור אחרי שחרור באפליקציה אחרת",
        shelfCloseAfterDropCaption: "סוגר את האזור כשהיעד מקבל את הפריטים. הסיכה בפאנל שומרת אותו פתוח.",
        shelfRemoveAfterDrop: "הסר פריטים אחרי שחרור",
        shelfRemoveAfterDropCaption: "פריטים שהתקבלו על ידי אפליקציה אחרת יוצאים מהאזור. כבה כדי לשמור עותק בו.",
        shelfExclusionsTitle: "חריגים אוטומטיים",
        shelfExclusionsEmpty: "אין אפליקציות שנוספו.",
        shelfExclusionsCaption: "ניעור ואזור שורת התפריטים לא נפתחים בזמן גרירות שהתחילו באפליקציות אלו. הקיצור ופתח עכשיו ממשיכים לעבוד.",
        shelfPin: "שמור פתוח",
        shelfUnpin: "אפשר לסגור לאחר השימוש",
        extraBrightnessName: "בהירות נוספת",
        extraBrightnessCaption: "משתמש בעתודת ה-HDR של המסך כדי לעבור את הבהירות המקסימלית. צורך יותר סוללה וה-Mac עלול להתחמם.",
        extraBrightnessLevelLabel: "עוצמה",
        extraBrightnessUnsupported: "זמין רק במסכי XDR, כמו אלו של MacBook Pro 14 ו-16 אינץ'.",
        shelfHotkeyLabel: "קיצור",
        shelfOpenNow: "פתח עכשיו",
        shelfNoPermission: "לא דורש שום הרשאה.",
        shelfMenuItem: "פתח אזור זמני",
        shelfTitle: "אזור זמני",
        shelfEmpty: "גרור פריטים לכאן",
        shelfClearAll: "נקה הכל",
        shelfRemoveSelected: "הסר נבחרים",
        shelfSelectedFormat: "%d נבחרו",
        shelfHint: "לחץ לבחירה. גרור לשימוש או לחץ לחיצה ימנית לפעולות נוספות.",
        shelfItemImage: "תמונה",
        shelfTooltipItemsFormat: "%d פריטים",
        shelfTooltipImageSingular: "%d תמונה",
        shelfTooltipImagePlural: "%d תמונות",
        shelfTooltipFileSingular: "%d קובץ",
        shelfTooltipFilePlural: "%d קבצים",
        shelfTooltipNoteSingular: "%d הערה",
        shelfTooltipNotePlural: "%d הערות",
        shelfTooltipLinkSingular: "%d קישור",
        shelfTooltipLinkPlural: "%d קישורים",
        shelfActionOpen: "פתח",
        shelfActionOpenWith: "פתח עם",
        shelfActionAirDrop: "שתף דרך AirDrop",

        breakdownMeasuring: "מודד…",

        mixerSection: "מיקסר עוצמה",
        mixerEmpty: "אפליקציות שמשתמשות באודיו מופיעות כאן",
        mixerUnavailable: "זמין מ-macOS 14.4",
        mixerPermissionBody: "כדי להתאים עוצמה לפי אפליקציה, אשר 'הקלטת מסך ואודיו מערכת' בהגדרות המערכת. האודיו לעולם לא מוקלט.",
        mixerResetTooltip: "חזור ל-100%",
        mixerOutputDefault: "ברירת מחדל",
        mixerOutputCurrent: "נוכחי",
        mixerOutputUnavailable: "פלט לא זמין",
        mixerOutputFallback: "משתמש בברירת המחדל עד שהתקן זה יחזור.",
        mixerBypassedCaption: "אפליקציה זו שולטת באודיו של עצמה.",
        mixerOutputTooltip: "בחר פלט",
        mixerSystemOutputTitle: "פלט",
        mixerSystemOutputNoDevices: "לא נמצאו פלטים",
        mixerSystemOutputTooltip: "בחר פלט מערכת",
        mixerSystemOutputErrorFormat: "לא ניתן להחליף: %@",
        mixerLowerOnHeadphonesDisconnect: "הנמך עוצמה בניתוק אוזניות",
        mixerLowerOnHeadphonesDisconnectCaption: "מתאים את הפלט כשאוזניות עם חוט או Bluetooth מתנתקות.",
        mixerHeadphonesDisconnectVolume: "עוצמה בניתוק",
        preciseVolumeRollerEnable: "עוצמה מדויקת יותר בבקרה",
        preciseVolumeRollerCaption: "הופך גלגלות ומקשי עוצמה לצעדים קטנים יותר.",
        preciseVolumeRollerTapFailed: "לא ניתן להאזין למקשי העוצמה.",
        soundOutputSwitcherTitle: "מחליף פלט",
        soundOutputSwitcherEnable: "החלף פלטים בקיצור",
        soundOutputSwitcherCaption: "בחר את הפלטים והשתמש בקיצור למעבר לזמין הבא.",
        soundOutputSwitcherDevices: "פלטים במחזור",
        soundOutputSwitcherNoAvailableSelection: "בחר לפחות פלט זמין אחד.",
        mixerInputTitle: "מיקרופון",
        mixerInputNoDevices: "לא נמצא מיקרופון",
        mixerInputUnavailable: "מיקרופון לא זמין",
        mixerInputFallback: "משתמש בברירת המחדל עד שמיקרופון זה יחזור.",
        mixerInputTooltip: "בחר מיקרופון",
        mixerInputErrorFormat: "לא ניתן להחליף: %@",
        mixerVisibleApps: "אפליקציות ברשימה",
        mixerAllShown: "הכל",
        mixerHiddenCountLabel: "מוסתרים",
        mixerHideFromList: "הסתר מהרשימה",

        updatesSection: "עדכונים",
        autoCheckToggle: "חפש עדכונים אוטומטית",
        includeBetaUpdatesToggle: "קבל עדכוני בטא",
        includeBetaUpdatesCaption: "גרסאות בטא כוללות תכונות בפיתוח ועלולות להציג חוסר יציבות או התנהגויות לא שלמות.",
        betaBadgeLabel: "בטא",
        checkNowButton: "חפש עכשיו",
        updateChecking: "מחפש…",
        updateUpToDate: "אתה בגרסה העדכנית ביותר.",
        updateAvailablePrefix: "עדכון זמין:",
        updateInstallButton: "הורד והתקן",
        updateDownloading: "מוריד עדכון…",
        updateInstalling: "מתקין ומפעיל מחדש…",
        updateFailedPrefix: "לא ניתן לבדוק:",
        updateLastChecked: "בדיקה אחרונה:",
        updateNotifyTitle: "עדכון Vorssaint",
        updateInstallFailedBody: "העדכון הורד, אבל לא ניתן להחיל אותו. הורד את הגרסה האחרונה מדף ה-releases ב-GitHub וגרור את האפליקציה מעל הנוכחית.",
        updateNeedsApplicationsTitle: "העבר את Vorssaint לאפליקציות",
        updateNeedsApplicationsBody: "האפליקציה רצה ממקום שלא ניתן לעדכן ממנו, כמו תמונת הדיסק או אזור זמני במערכת. גרור את Vorssaint לתיקיית האפליקציות, פתח משם ונסה שוב.",
        menuCheckUpdates: "חפש עדכונים…",

        permissionRequired: "נדרשת הרשאה",
        permissionAccessibility: "נגישות",
        permissionScreenRecording: "הקלטת מסך",
        permissionGranted: "ניתנה",
        permissionMissing: "לא ניתנה",
        permissionOpenSettings: "פתח הגדרות מערכת…",
        permissionRequest: "הענק גישה",
        permissionRestartNote: "macOS עלול לבקש לפתוח מחדש את האפליקציה לאחר ההענקה.",

        aboutDescription: "מרכז כלים ל-Mac שלך.\nאנרגיה, מוניטור מערכת, גלילה ומחליף חלונות, ישירות בשורת התפריטים.",
        versionPrefix: "גרסה",
        reviewIntro: "סקור מבוא",
        reviewHighlights: "סקור חדשות",
        viewOnGitHub: "צפה ב-GitHub",

        obContinue: "המשך",
        obBack: "חזור",
        obSkipStep: "דלג על שלב זה",
        obStart: "פתח את Vorssaint",
        obStepWelcomeTitle: "ברוך הבא ל-Vorssaint",
        obStepWelcomeBody: "כלי שימושי דיסקרטי בשורת התפריטים שהופך את macOS לנוח יותר ביומיום.",
        obWelcomeBullet1Title: "אנרגיה בשליטה",
        obWelcomeBullet1Body: "השאר את ה-Mac ער ככל שתרצה, אפילו עם מכסה סגור.",
        obWelcomeBullet2Title: "תמונת מצב ברורה של המערכת",
        obWelcomeBullet2Body: "טמפרטורות, שימוש במעבד ומעבד גרפי ולחץ זיכרון בזמן אמת.",
        obWelcomeBullet3Title: "עכבר וחלונות בסגנון שלך",
        obWelcomeBullet3Body: "גלילה הפוכה בעכבר ומחליף חלונות עם תמונות ממוזערות.",
        obLanguageLabel: "שפה",
        obStepAccessibilityTitle: "נגישות",
        obStepAccessibilityBody: "נדרשת להיפוך גלילת העכבר ולכך שמחליף החלונות יגיב למקלדת.",
        obAccessibilityWhy: "האפליקציה רק מאזינה לגלגל העכבר ולקיצור המחליף. שום דבר לא מוקלט או נשלח לשום מקום.",
        obStepRecordingTitle: "הקלטת מסך",
        obStepRecordingBody: "מאפשרת להציג תמונות ממוזערות אמיתיות של החלונות במחליף, במקום רק סמלים.",
        obRecordingWhy: "התמונות הממוזערות נוצרות במקום, נשארות רק בזיכרון ולעולם לא עוזבות את ה-Mac שלך. בלעדיה, המחליף עובד עם סמלים.",
        obStepMonitorTitle: "מוניטור מערכת",
        obStepMonitorBody: "הפאנל מציג טמפרטורות של מעבד, מעבד גרפי וסוללה, שימוש בחומרה ולחץ זיכרון.",
        obMonitorNoPermission: "לא צריך הרשאה. החיישנים נקראים ישירות מהמערכת.",
        obStepOptionalTitle: "תכונות אופציונליות",
        obStepOptionalBody: "הפעל עכשיו מה שתרצה להשתמש בו. הכל ניתן לשינוי אחר כך בהגדרות.",
        obStepStatusTitle: "בדיקה",
        obStepStatusBody: "בדוק אם הכל מוכן לתכונות שתרצה להשתמש בהן.",
        obStatusRecheck: "בדוק שוב",
        obStepDoneTitle: "הכל מוכן!",
        obStepDoneBody: "Vorssaint כבר דואג ל-Mac שלך.",
        obDoneHint: "חפש את החור השחור בשורת התפריטים, בפינה הימנית העליונה של המסך.",
        obWhatsNewTitle: "חדש בגרסה זו",
        obWhatsNewFallback: "עדכון זה כולל את התיקונים והשיפורים האחרונים.",
        obLanguageUpdateTitle: "עכשיו בשפה שלך",
        obLanguageUpdateBody: "Vorssaint עכשיו מדבר מספר שפות. בחר את מה שאתה מעדיף להשתמש בו; אפשר לשנות בכל עת בהגדרות.",
        obPurposeTitle: "מה הביא אותך לכאן?",
        obPurposeBody: "בחר תצורה מוכנה או סמן בדיוק מה שתרצה להשתמש בו.",
        obPurposeSkip: "אתה יכול להוסיף או להסיר תכונות אחר כך בהגדרות.",

        tabMonitor: "מוניטור",
        monitorMenuBarSection: "בשורת התפריטים",
        monitorMenuBarCaption: "בחר מה מופיע ליד הסמל בשורת התפריטים.",
        monitorCombineTemperatures: "שלב שימוש וטמפרטורה",
        monitorCombineTemperaturesCaption: "כששימוש וטמפרטורה של אותו פריט פעילים, מציג הכל בבלוק אחד.",
        monitorSeparateMenuBarMetrics: "הפרד מדדים לפריטים משלהם",
        monitorSeparateMenuBarMetricsCaption: "מפריד את הבלוקים הפעילים בשורת התפריטים ושומר שימוש וטמפרטורה יחד כששילוב פעיל.",
        monitorNetworkUploadFirst: "העלאה לפני הורדה",
        monitorShowCPU: "מעבד",
        monitorShowMemory: "זיכרון",
        monitorShowNetwork: "רשת",
        monitorShowPowerLabel: "אנרגיה",
        monitorIntervalLabel: "עדכן כל",
        monitorInterval1: "שנייה אחת",
        monitorInterval2: "שתי שניות",
        monitorInterval5: "חמש שניות",
        monitorPanelSection: "בפאנל",
        panelNavigationMode: "נווט לפי סעיפים בפאנל",
        panelNavigationCaption: "מציג סעיף אחד בכל פעם. בחר רשימה לראות הכל בגלילה רציפה.",
        panelFooterSections: "סעיפים",
        panelFooterList: "רשימה",
        betaBadge: "בטא",
        betaFeatureWarning: "בטא. ייתכנו כמה באגים.",

        networkSection: "רשת",
        networkDownload: "הורדה",
        networkUpload: "העלאה",
        networkThisSession: "בסשן זה",
        networkMeasuring: "מודד…",
        networkApps: "אפליקציות משתמשות ברשת",
        networkAppsIdle: "אין אפליקציות משתמשות ברשת עכשיו",

        diskSection: "דיסקים",
        diskUsed: "בשימוש",
        diskFree: "פנוי",
        diskAvailable: "זמין",
        diskPurgeable: "ניתן לפינוי",
        diskInternal: "פנימי",
        diskExternal: "חיצוני",
        diskSelect: "בחר דיסק",
        diskRead: "קריאה",
        diskWrite: "כתיבה",
        diskSMARTStatus: "סטטוס",
        diskSMARTUnavailable: "SMART לא זמין לדיסק זה",
        diskTotalRead: "נקרא סה\"כ",
        diskTotalWritten: "נכתב סה\"כ",
        diskTemperature: "טמפרטורה",
        diskHealth: "בריאות",
        diskPowerCycles: "מחזורים",
        diskPowerOnHours: "שעות פעיל",
        diskUnsafeShutdowns: "כיבויים לא בטוחים",
        diskMediaErrors: "שגיאות מדיה",
        diskEject: "הוצא",
        diskEjectAll: "הוצא הכל",
        diskEjecting: "מוציא…",
        diskReadyToRemove: "מוכן להסרה",
        diskEjectFailed: "לא ניתן להוציא",
        diskProtectionCaption: "הוצא לפני ניתוק.",
        diskNoExternal: "אין דיסקים חיצוניים מוכנים להוצאה.",
        diskOpenInFinder: "פתח",
        diskStorageSettings: "אחסון",
        diskNoDisks: "לא נמצאו דיסקים מחוברים.",

        powerSection: "אנרגיה",
        powerSystem: "מערכת",
        powerAdapter: "מתאם",
        powerBattery: "סוללה",
        powerCharging: "טוען",
        powerOnBattery: "על סוללה",
        powerPluggedIn: "מחובר לחשמל",
        powerUnavailable: "מדדי אנרגיה לא זמינים ב-Mac זה",
        powerAdapterMaxFormat: "%@ מקס.",
        monitorShowGPU: "מעבד גרפי",
        monitorShowCPUTemperature: "טמפרטורת מעבד",
        monitorShowGPUTemperature: "טמפרטורת מעבד גרפי",
        monitorShowBatteryTemperature: "טמפרטורת סוללה",
        monitorShowPeripheralBattery: "סוללת התקנים",
        peripheralBatteryNoDevices: "לא נמצאו התקנים",
        monitorGraphsSection: "גרפים",
        monitorGraphsCaption: "בחר אילו מדדים יציגו גרף לאורך זמן.",

        updateBannerTitle: "עדכון זמין",
        updateBannerAction: "עדכן",
        obStepMenuBarTitle: "מדדים בשורת התפריטים",
        obStepMenuBarBody: "בחר מה להציג ליד הסמל. התצוגה המקדימה למעלה משתנה בזמן אמת.",
        obStepMenuBarNote: "חדש: בלוקי רשת ואנרגיה וגרפים בפאנל. התאם הכל אחר כך בהגדרות › מוניטור.",
        monitorMenuBarPresetLabel: "סגנון",
        menuBarPresetReadable: "קריא",
        menuBarPresetDense: "צפוף",
        menuBarSpacingLabel: "רווח בשורה",
        menuBarSpacingStandard: "רגיל",
        menuBarSpacingCompact: "קומפקטי",
        menuBarHideIconToggle: "הסתר את סמל האפליקציה כשיש מדדים",
        menuBarHideIconCaption: "הסמל חוזר מעצמו כשהמדדים יוצאים מהשורה וכשיש משהו להודיע (עדכון מוכן או מיקרופון מושתק).",
        monitorLabelStyleLabel: "תוויות",
        menuBarLabelStyleCompact: "קומפקטיות",
        menuBarLabelStyleClassic: "קלאסיות",
        monitorMemoryStyleLabel: "הצג זיכרון כ",
        monitorMemoryPressureDot: "נקודת לחץ",
        memoryStyleDot: "נקודה",
        memoryStylePercent: "%",
        memoryStyleBoth: "שניהם",
        systemUptime: "פעיל מזה",
        batteryCharge: "מטען",
        powerHealth: "בריאות סוללה",
        powerCycles: "מחזורים",
        speedTestRun: "בדוק מהירות",
        speedTestAgain: "בדוק שוב",
        speedTestLatency: "השהיה",
        speedTestTesting: "בודק…",
        speedTestFailed: "כשל בבדיקה",

        monitorShowInPanel: "הצג בפאנל",
        disclosureExpanded: "מורחב",
        disclosureCollapsed: "מכווץ",
        panelHideItem: "הסתר מהפאנל",
        panelShowItem: "הצג בפאנל",
        panelHiddenItem: "מוסתר",
        monitorItemUptime: "זמן פעיל",
        monitorItemNetSpeed: "מהירות בזמן אמת",
        monitorItemNetTotals: "סה\"כ בסשן",
        monitorItemNetTest: "בדיקת מהירות",
        monitorItemDiskUsage: "שימוש בדיסק",
        monitorItemDiskActivity: "פעילות בזמן אמת",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "הגנה חיצונית",
        monitorItemDiskTools: "כלים",
        monitorPanelConfigHint: "פתח בלוק לבחירה מה הוא מציג.",
        monitorOrderSection: "סדר סעיפים",
        monitorOrderHint: "גרור לסידור מחדש של סעיפי הפאנל והשתמש בעין להצגה או הסתרה של כל אחד.",
        obStepPanelTitle: "מה מופיע בפאנל",
        obStepPanelBody: "פתח כל בלוק ובחר בדיוק מה להציג כשאתה לוחץ על הסמל.",
        obStepPanelNavigationTitle: "פאנל לפי סעיפים",
        obStepPanelNavigationBody: "הפאנל עכשיו יכול להציג סעיף אחד בכל פעם. אתה יכול לעבור בין סעיפים לרשימה בהגדרות.",

        cleaningMenuItem: "מצב ניקוי",
        utilitiesSection: "כלי עזר",
        quickControlsSection: "בקרים",
        panelCategoryWindows: "חלונות",
        panelCategoryInput: "עכבר ומקלדת",
        panelCategoryFiles: "קבצים",
        windowMaximizeName: "הגדל חלונות",
        windowMaximizeCaption: "הכפתור הירוק מגדיל בלי ליצור מרחב נוסף.",
        windowMaximizeActiveNow: "פעיל בכפתור הירוק",
        windowMaximizeNeedsAccessibility: "דורש נגישות לפעולה.",
        keyDebounceName: "דה-באונס",
        keyDebounceEnable: "סנן מקשים כפולים",
        keyDebounceCaption: "מסנן הקשות כפולות מהירות מדי.",
        keyDebounceActiveNow: "מסנן פעיל",
        keyDebounceGlobalWindow: "חלון גלובלי",
        keyDebouncePerKeySection: "מקשים ספציפיים",
        keyDebouncePerKeyCaption: "ערכים לפי מקש מחליפים את החלון הגלובלי. השתמש ב-0 מ\"ש לא לסנן מקש מסוים.",
        keyDebounceKeyLabel: "מקש",
        keyDebounceWindowLabel: "חלון",
        keyDebounceAddKey: "הוסף מקש",
        keyDebounceNoOverrides: "אין מקשים ספציפיים מוגדרים.",
        keyDebounceRemoveKey: "הסר מקש",
        cleaningPanelCaption: "נועל את המקלדת לניקוי בטוח.",
        cleaningOverlayTitle: "מקלדת נעולה לניקוי",
        cleaningOverlaySubtitle: "לחץ Esc 5 פעמים לפתיחה",
        cleaningOverlayUnlock: "פתח",
        cleaningOverlayMouseHint: "העכבר והטראקפד ממשיכים לעבוד",
        cleaningKeepScreenVisibleToggle: "להשאיר את המסך גלוי",
        cleaningKeepScreenVisibleCaption: "מציג חיווי דיסקרטי בפינת המסך במקום להחשיך את התוכן.",
        cleaningStartNow: "לנעול את המקלדת עכשיו",
        cleaningNeedsAxTitle: "דורש נגישות",
        cleaningNeedsAxBody: "כדי לנעול את המקלדת בבטחה, Vorssaint צריך הרשאת נגישות. הענק בהגדרות המערכת ונסה שוב.",

        tabSupport: "תמיכה",
        shortcutsPageCaption: "ערוך כאן את כל הקיצורים הגלובליים של התכונות המותקנות ב-Mac זה. הלא פעילים נשמרים, אבל לא עובדים.",
        shortcutsPageTitle: "קיצורי מקלדת",
        settingsSearchPlaceholder: "חפש הגדרות",
        donateHeading: "עזור ל-Vorssaint להמשיך לגדול",
        donateMessage: "Vorssaint הוא חינמי, עצמאי ומפותח בזמני הפנוי. אם תרצה לתרום כלכלית, Buy Me a Coffee עוזר ישירות לקדם את הפיתוח.",
        donateButton: "תמוך ב-Buy Me a Coffee",
        donateThanks: "תודה שאתה כאן. 🖤",
        supportIntroTitle: "עזור ל-Vorssaint להמשיך לגדול",
        supportIntroMessage: "אם תרצה לתמוך כלכלית בפיתוח, Buy Me a Coffee הוא המקום היחיד לעשות זאת.",
        supportIntroStarButton: "תן כוכב ב-GitHub",
        supportIntroStarMessage: "תמיכה כלכלית לעולם לא צפויה. כוכב ב-GitHub עוזר ליותר אנשים למצוא את Vorssaint ועושה הבדל עצום בפיתוח.",
        supportIntroCoffeeButton: "תמוך ב-Buy Me a Coffee",
        supportIntroLaterButton: "לא עכשיו",
        supportIntroDoneButton: "סיום",
        discordIntroTitle: "קהילת Vorssaint ב-Discord מתחילה",
        discordIntroMessage: "הקהילה של Vorssaint היא חדשה ועדיין בפיתוח. הצטרף מההתחלה כדי להכיר משתמשים אחרים ולעזור לבנות מרחב מסביר פנים סביב האפליקציה.",
        discordIntroBenefitHelp: "שאל שאלות ושתף זרימות עבודה",
        discordIntroBenefitFeedback: "דווח על באגים, בקש שיפורים ועזור להחליט מה בא אחר כך",
        discordIntroBenefitPreviews: "עקוב אחר הפיתוח, תצוגות מקדימות וחדשות גרסאות",
        discordIntroJoinButton: "הצטרף לקהילה ב-Discord",
        communityIntroTitle: "בוא לראות לפני כולם",
        communityIntroMessage: "מי שכבר עקב אחריי ב-X ראה כמה חדשות בעדכון זה לפני כולם. שם אני מפרסם תצוגות מקדימות של מה שבא אחר כך ומראה איך זה עובד, כדי שכבר תדע את הבסיס לפני שהעדכון יוצא. עקוב שם וראה מה בא!",
        communityIntroFollowButton: "עקוב אחר @vorssaint ב-X",
        homebrewOfficialIntroTitle: "עכשיו בקטלוג הרשמי של Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint עכשיו ניתן להתקנה ישירות מהקטלוג הרשמי של Homebrew.",
        homebrewOfficialIntroInstallLabel: "התקנה חדשה",
        homebrewOfficialIntroMigrationTitle: "השתמשת ב-tap הישן?",
        homebrewOfficialIntroMigrationMessage: "הסר את ה-tap פעם אחת. האפליקציה וההגדרות שלך נשארות במקום.",
        homebrewOfficialIntroCopyButton: "העתק פקודה",
        updateShowcaseTitle: "חדש ב-3.1.4",
        updateShowcaseMessage: "צפה בתצוגה מקדימה מהירה של השיפורים העיקריים בעדכון זה.",
        updateShowcaseUnavailable: "לא ניתן לטעון את הסרטון עכשיו. אתה עדיין יכול להמשיך.",
        updateShowcaseRestart: "חזור להתחלה",
        showMenuBarIcon: "הצג סמל בשורת התפריטים",
        showMenuBarIconCaption: "אם סמל Vorssaint נעלם (macOS יכול להסתיר סמלים כששורת התפריטים מתמלאת, נפוץ ב-Mac עם חריץ), פתח מחדש את Vorssaint מתיקיית האפליקציות או דרך Spotlight: זה יוצר מחדש את הסמל ו, אם הוא עדיין מוסתר, פותח חלון זה. הכפתור למעלה עושה אותו הדבר כשאתה כבר יכול להגיע לכאן. לשמור פחות סמלים בשורה, או פחות מדדים ב-Vorssaint, מפחית משמעותית את הסיכוי.",
        menuBarIconStillHiddenTitle: "הסמל עדיין מוסתר",
        menuBarIconStillHiddenBody: "הסמל נוצר מחדש, אבל macOS לא נתן לו מקום נראה. שורת התפריטים כנראה מלאה: הסר כמה סמלים מהשורה (או סגור אפליקציות עם תפריטים ארוכים) ונסה שוב.",
        menuBarIconManagerHintFormat: "ה-%@ פתוח ועשוי לשמור על הסמל בסעיף המוסתר שלו. חפש את Vorssaint שם, או הגדר את ה-%@ תמיד להציג את Vorssaint.",
        shortcutRecording: "לחץ את הקיצור החדש",
        shortcutReset: "אפס",
        shortcutNone: "ללא",
        shortcutClear: "הסר קיצור",
        shortcutInvalid: "השתמש לפחות ב-Control, Option או Command יחד עם מקש.",
        shortcutPressKeys: "לחץ",
        shortcutEscapeHint: "Esc מבטל.",
        shortcutDeleteHint: "Delete מסיר.",
        shortcutNotCaptured: "שום דבר לא נלכד. macOS או אפליקציה אחרת כבר משתמשים בשילוב זה. נסה אחר.",
        shortcutConflictFormat: "קיצור זה כבר בשימוש על ידי %@.",
        shortcutUnavailable: "macOS סירב לקיצור זה. בחר אחר.",
        shelfShortcutToggle: "קיצור אזור זמני",
        switcherUsageHintFormat: "החזק %@ לניווט; שחרר להפעלת החלון. Shift או ← חוזרים אחורה; W סוגר את החלון; Q סוגר את האפליקציה; Esc מבטל.",
        musicBlockSection: "מקשי מדיה",
        musicBlockTitle: "מנע מ-Music להיפתח מעצמו",
        musicBlockCaption: "אפליקציית Music מפסיקה להיפתח בלחיצה על מקשי המדיה. אתה עדיין יכול לפתוח אותה כשתרצה.",
        musicBlockReplacementLabel: "פתח במקום",
        musicBlockReplacementNone: "ללא",
        musicBlockChooseApp: "בחר אפליקציה…",
        cleanerName: "ניקוי",
        cleanerIntroTitle: "נקה את הזבל ב-Mac",
        cleanerIntroCaption: "מחפש שאריות של אפליקציות שהוסרו, מטמונים, יומנים ואת האשפה. אתה סוקר הכל לפני והפריטים שהוסרו עוברים לאשפה.",
        cleanerScan: "סרוק",
        cleanerScanning: "סורק…",
        cleanerCleaning: "מנקה…",
        cleanerCatLeftovers: "שאריות אפליקציות שהוסרו",
        cleanerCatLoginItems: "פריטי התחלה יתומים",
        cleanerCatCaches: "מטמונים",
        cleanerCatLogs: "יומנים",
        cleanerCatDeveloper: "זבל פיתוח",
        cleanerCatTrash: "אשפה",
        cleanerLeftoversNote: "נמצאו על ידי ניתוח ומתחילים לא מסומנים. בדוק את הנתיב לפני סימון.",
        cleanerLoginItemsNote: "הכניסה בפריטי התחלה נעלמת לאחר הפעלה מחדש של ה-Mac.",
        cleanerTrashNote: "ריקון האשפה הוא קבוע.",
        cleanerCatDeviceBackups: "גיבויי iPhone",
        cleanerDeviceBackupsCaption: "גיבויים ישנים של iPhone ו-iPad תופסים חלק ניכר ממה ש-macOS קורא לו אחרים. הסר רק את אלה שאתה לא צריך יותר; גיבוי חדש נעשה כשהמכשיר יחובר שוב.",
        cleanerNothingFound: "אין מה לנקות. ה-Mac שלך מסודר.",
        cleanerClean: "נקה",
        cleanerDoneNote: "הפריטים עברו לאשפה וניתן לשחזר משם.",
        cleanerAgain: "סרוק שוב",
        cleanerRevealInFinder: "הצג ב-Finder",
        cleanerPanelCaption: "שאריות אפליקציות, מטמונים ויומנים",
        cleanerSafeSection: "ניקוי בטוח",
        cleanerOptionalSection: "אופציונלי, בדוק לפני",
        cleanerCatOtherCaches: "מטמונים אחרים",
        cleanerCachesCaption: "קבצים זמניים שהאפליקציות יוצרות מחדש בעצמן.",
        cleanerLogsCaption: "יומני אבחון ישנים.",
        cleanerDeveloperCaption: "שאריות של הידור ומדמים של Xcode.",
        cleanerLoginItemsCaption: "כניסות התחלה שנשארו על ידי אפליקציות שכבר לא קיימות.",
        cleanerLeftoversCaption: "קבצים שנשארו על ידי אפליקציות שהסרת.",
        cleanerOtherCachesCaption: "בטוח למחוק, שום דבר לא נשבר. אפליקציות עלולות להיפתח לאט יותר בפעם הראשונה ותוכן שהורד, כמו מוזיקה לא מקוונת, יורד שוב.",
        cleanerCleanSizeFormat: "נקה %@",
        cleanerScheduleTitle: "ניקוי אוטומטי",
        cleanerScheduleOff: "מכובה",
        cleanerScheduleDaily: "יומי",
        cleanerScheduleWeekly: "שבועי",
        cleanerScheduleCaption: "מנקה בעצמו רק את החלק הבטוח בזמן הנבחר ושולח הכל לאשפה.",
        cleanerScheduleLastFormat: "הניקוי האוטומטי האחרון שחרר %@.",
        cleanerAutoNotificationFormat: "%@ שוחררו ונשלחו לאשפה.",
        cleanerScheduleNextFormat: "ניקוי הבא %@.",
        cleanerScheduleRanFormat: "ניקוי אוטומטי אחרון %@.",
        cleanerScheduleNotifyToggle: "הודע כשמסתיים",
        cleanerNotifDenied: "ההתראות של Vorssaint מכובות במערכת.",
        cleanerNotifOpenSettings: "פתח הגדרות התראות…",
        launchAtLoginNeedsApplications: "האפליקציה רצה ממקום שלא מאפשר פתיחה בהתחברות. גרור את Vorssaint לתיקיית האפליקציות, פתח משם והפעל שוב.",
        launchAtLoginNeedsApproval: "פריט ההתחברות רשום, אבל עדיין כבוי בהגדרות המערכת. פתח הגדרות מערכת › כללי › פריטי התחלה והרחבות והפעל את Vorssaint תחת 'פתח בהתחברות'.",
        ocrRemoveLineBreaksToggle: "הסר מעברי שורה",
        ocrRemoveLineBreaksCaption: "מסיר את מעברי השורה כדי שהטקסט שהועתק יודבק כפסקה אחת.",
        ocrQRToggle: "קרא קודי QR",
        ocrQRCaption: "אם האזור מכיל קוד QR, התוכן שלו מופיע להעתקה או פתיחה.",
        ocrQRCopied: "קוד QR הועתק",
        qrResultTitle: "קוד QR",
        qrResultCopy: "העתק",
        qrResultOpen: "פתח קישור",
        highlightsTitle: "חדש בגרסה זו",
        highlightsTitleClipboardRedesign: "מראה חדש של לוח ההעתקה",
        highlightsCaptionDockPreview: "התצוגה המקדימה ב-Dock עובדת עכשיו עם הגדלת ה-Dock מופעלת",
        highlightsCaptionScreenshot: "צילום המסך קיבל זכוכית מגדלת פיקסלים וקריאת קודי QR",
        highlightsCaptionSnippetLibrary: "תפריט קטעים עם חיפוש מקליד כל קטע ישירות בסמן",
        highlightsCaptionCapturePalette: "קיצור יחיד עכשיו פותח פלטה צפה לצילומים, הקלטות, טקסט במסך וצבעים עם הגדרות בסביבה.",
        highlightsCaptionClipboardRedesign: "ההיסטוריה עכשיו נפתחת כפלטה קומפקטית, עם קווים נקיים ותצוגה מקדימה לפי דרישה לקריאה או עריכה של הפריט המלא.",
        highlightsConfigure: "הגדר",
        highlightsTry: "נסה",
        highlightsSeeAll: "ראה את כל השינויים",
        switcherCurrentSpaceOnly: "הצג רק את שולחן העבודה הנוכחי",
        switcherCurrentSpaceOnlyCaption: "מציג במחליף רק את החלונות של שולחן העבודה שאתה בו. בחירת חלון לעולם לא מעבירה אותך לשולחן עבודה אחר.",
        shelfFileMissing: "הקובץ כבר לא קיים",
        previewSizeSmall: "קטן",
        mixerSoundEffectsOutputTitle: "צלילי מערכת",
        mixerSoundEffectsOutputTooltip: "בחר איפה התראות ואפקטים צליליים מתנגנים",
        monitorOpenActivityMonitor: "פתח את צג הפעילות",
        dockClickHide: "לחיצה ב-Dock מסתירה את האפליקציה",
        dockClickHideCaption: "האפליקציה הפעילה מוסתרת בלחיצה על הסמל שלה ב-Dock. לחץ שוב להחזרתה.",
        monitorMemoryMetricLabel: "מדוד זיכרון כ",
        memoryMetricUsed: "זיכרון בשימוש",
        memoryMetricApp: "זיכרון אפליקציות",
        keepAwakeRightClickToggle: "לחיצה ימנית על סמל שורת התפריטים מחליפה 'שמור ערנות'",
        keepAwakeRightClickToggleCaption: "מחליף את תפריט ההקשר של הלחיצה הימנית.",
        urlCleanerRulesTitle: "כללי ניקוי",
        urlCleanerRulesCaption: "אתר מצרף פרמטרים אלה לקישורי השיתוף שלו כדי לעקוב מאיפה הקישור הגיע. כשמופעל, השם מוסר בניקוי קישור; כשכבוי, הוא נשאר. שמות שתוסיף ניתנים להחרגה.",
        urlCleanerRulesCoverageCaption: "הרשימה מכסה את נתיבי השיתוף השונים של אתר — הדף, האפליקציה, חדר חי — ולכן היא ארוכה; קישור אמיתי בדרך כלל נושא רק שניים עד ארבעה מהם.",
        urlCleanerRulesAllSites: "כל האתרים",
        urlCleanerRulesCountSingular: "פרמטר אחד",
        urlCleanerRulesCountPluralFormat: "%d פרמטרים",
        urlCleanerRulesAddSite: "הוסף אתר",
        urlCleanerRulesParameterPlaceholder: "שם הפרמטר",
        urlCleanerRulesMatchCaption: "כתוב את השם משמאל ל- = , כמו utm_source. שם שמתאים מסיר את הפרמטר הזה מהקישור ומשאיר את השאר כמו שהוא.",
        urlCleanerRulesAddButton: "הוסף",
        urlCleanerRulesRemoveButton: "מחק שם",
        urlCleanerRulesRemoveSiteButton: "כבה את כל הכללים של אתר זה",
        urlCleanerRemovedFormat: "הוסרו %@",
        switcherSearchPin: "הצמד חיפוש עם S",
        switcherSearchPinCaption: "S מתחיל חיפוש ומצמיד את המחליף הפתוח, כך שהקלדה לא מייצרת תווים מיוחדים כשהקיצור משתמש ב-⌥, וחיפוש שמתחיל ב-Q או W לא סוגר את החלון או את האפליקציה בטעות.",
        invertVerticalScroll: "הפוך גלילה אנכית",
        invertHorizontalScroll: "הפוך גלילה אופקית",
        switcherShowShortcutHints: "הצג רמזי קיצורים",
        switcherShowShortcutHintsCaption: "מציג את קיצורי האפליקציות והחלונות מתחת לסמלים.",
        uninstallerHomebrewPackageFormat: "%@ גם יוסר מ-Homebrew.",
        shelfEdgeToggle: "פתח קרוב לקצה המסך",
        shelfEdgeCaption: "בזמן גרירת קובץ קרוב לקצה המסך, האזור מציץ פנימה. שחרר שם, או משוך בחזרה והוא נסוג.",
        focusFollowsMouseName: "מיקוד במעבר עכבר",
        focusFollowsMouseCaption: "מעביר למיקוד ומביא לחזית את החלון תחת הסמן לאחר הפסקה קצרה.",
        focusFollowsMouseDelay: "השהיה במעבר עכבר",
        switcherMinimizedPlacementLabel: "חלונות ממוזערים",
        switcherMinimizedPlacementNormal: "סדר רגיל",
        switcherMinimizedPlacementEnd: "שים בסוף",
        switcherMinimizedPlacementHidden: "הסתר",
        switcherShowFullscreenWindows: "הצג חלונות במסך מלא",
        switcherScreenPlacementLabel: "הצג ב",
        switcherScreenPlacementPointer: "מסך עם הסמן",
        switcherScreenPlacementMenuBar: "מסך עם שורת התפריטים",
        switcherScreenPlacementActiveWindow: "מסך עם החלון הפעיל",
        switcherScreenPlacementCaption: "באיזה מסך המחליף נפתח כשיש יותר מאחד מחובר.",
        smoothScrollResponseLabel: "תגובה",
        mouseAccelerationName: "לבטל האצת עכבר",
        mouseAccelerationCaption: "מסיר את האצת הסמן לעכברים המחוברים. ההגדרה הקודמת חוזרת כשמכבים את האפשרות הזו או יוצאים מ-Vorssaint."
    )
}
