// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Nederlands — translated and hand-checked, not machine output.
extension Strings {
    static let nl = Strings(
        statusIdleTooltip: "Vorssaint: normale sluimerstand",
        statusActiveUntil: "Vorssaint: wakker tot",
        statusActiveIndefinite: "Vorssaint: continu wakker",
        menuEnableAwake: "Wakker houden inschakelen",
        menuDisableAwake: "Wakker houden uitschakelen",
        menuActivateFor: "Activeren voor…",
        menuSettings: "Instellingen…",
        menuAbout: "Over Vorssaint",
        menuQuit: "Vorssaint afsluiten",
        menuHide: "Vorssaint verbergen",
        menuHideOthers: "Overige verbergen",
        menuShowAll: "Alles tonen",
        menuEdit: "Bewerken",
        menuUndo: "Ongedaan maken",
        menuRedo: "Opnieuw uitvoeren",
        menuCut: "Knippen",
        menuCopy: "Kopiëren",
        menuPaste: "Plakken",
        menuSelectAll: "Alles selecteren",
        menuWindow: "Venster",
        menuMinimize: "Minimaliseren",
        menuZoom: "Zoomen",
        menuClose: "Sluiten",

        minutes15: "15 minuten",
        minutes30: "30 minuten",
        hour1: "1 uur",
        hours2: "2 uur",
        hours4: "4 uur",
        hours8: "8 uur",
        indefinitely: "Continu",
        indefinite: "Onbeperkt",

        panelSettings: "Instellingen",
        panelQuit: "Afsluiten",
        panelHotkeyHint: "Sneltoets schakelt",

        keepAwakeTitle: "Wakker houden",
        keepAwakeEndsIn: "Eindigt over",
        keepAwakeUntilDisabled: "Actief tot je het uitschakelt",
        keepAwakeNormalRules: "De Mac volgt zijn normale energieregels",
        keepAwakeOptions: "Opties",
        keepAwakeMouseJiggle: "Wijzer licht bewegen",
        keepAwakeMouseJiggleCaption: "Beweegt de wijzer tijdens een sessie een klein beetje, op het gekozen interval.",
        keepAwakeMouseJiggleInterval: "Interval",
        keepAwakeActiveIconLabel: "Actief symbool",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Koffie",
        keepAwakeActiveIconEye: "Oog",
        keepAwakeActiveIconMoon: "Maan",
        keepAwakeActiveIconLight: "Gloeilamp",
        keepAwakeIconTintLabel: "Kleur van actief symbool",
        keepAwakeIconTintOrange: "Oranje",
        keepAwakeIconTintGreen: "Groen",
        keepAwakeIconTintBlue: "Blauw",
        keepAwakeIconTintPurple: "Paars",
        keepAwakeIconTintPink: "Roze",
        keepAwakeIconTintNone: "Geen kleur",
        durationLabel: "Duur",
        clamshellTitle: "Doorwerken met gesloten deksel",
        clamshellOnCaption: "Sluimerstand volledig uitgeschakeld. Let op je batterij",
        clamshellNeedsSession: "Wordt toegepast zodra “Wakker houden” actief is",
        clamshellReady: "Klaar. Schakelt zonder wachtwoord",
        clamshellNeedsPassword: "Vraagt eenmalig om het beheerderswachtwoord",

        systemSection: "Systeem",
        temperatures: "Temperaturen",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Batterij",
        usageSection: "Hardwaregebruik",
        memorySection: "Geheugen",
        memoryPressure: "Druk",
        memorySwapUsed: "Swap gebruikt",
        memoryCompressed: "Gecomprimeerd",
        memoryCachedFiles: "Bestanden in cache",
        pressureNormal: "Normaal",
        pressureWarning: "Verhoogd",
        pressureCritical: "Kritiek",
        monitorUnavailable: "Sensoren niet beschikbaar op deze Mac",
        energyAppsTitle: "Apps met hoog energieverbruik",
        energyAppsIdle: "Geen hoog energieverbruik",

        notifySessionEndedTitle: "Sessie beëindigd",
        notifySessionEndedBody: "De tijd is om. De Mac gaat weer normaal in sluimerstand.",
        notifyBatteryTitle: "Vorssaint uitgeschakeld",
        notifyBatteryBody: "Batterij bijna leeg. De normale sluimerstand is hersteld om de lading te beschermen.",
        adminPromptClamshellOn: "Vorssaint heeft je wachtwoord nodig om door te werken met gesloten deksel.",
        adminPromptClamshellOff: "Vorssaint heeft je wachtwoord nodig om de normale sluimerstand van de Mac te herstellen.",
        adminPromptRecover: "Vorssaint is afgesloten terwijl de sluimerstand van de Mac was uitgeschakeld. Voer het wachtwoord in om de normale sluimerstand te herstellen.",
        adminPromptUpdate: "Vorssaint heeft je wachtwoord nodig om de update te installeren.",
        adminPromptSudoersInstall: "Vorssaint maakt een beperkte regel aan (alleen pmset disablesleep) om de modus voor gesloten deksel te schakelen zonder wachtwoord. Dit is de enige keer dat het wachtwoord nodig is.",
        adminPromptSudoersRemove: "Vorssaint verwijdert de wachtwoordvrije regel voor gesloten deksel.",

        settingsTitle: "Vorssaint-instellingen",
        tabGeneral: "Algemeen",
        tabEnergy: "Energie",
        tabMouse: "Muis & trackpad",
        tabSwitcher: "Omschakelaar",
        tabAdvanced: "Geavanceerd",
        tabAbout: "Over",
        tabReleaseNotes: "Nieuw",
        releaseNotesOnUpdateToggle: "Toon nieuwigheden na een update",
        previewSizeLabel: "Voorvertoningsgrootte",
        previewSizeNormal: "Normaal",
        previewSizeLarge: "Groot",
        previewSizeXLarge: "Extra groot",
        settingsGroupFeatures: "Functies",
        advancedResetSection: "Toestemmingen",
        advancedResetDescription: "Verwijdert alle toestemmingen die je aan Vorssaint hebt gegeven (Toegankelijkheid, Schermopname, Volledige schijftoegang en meer), het aanmeldobject en de regel voor gesloten deksel. Handig voor een frisse start of vóór het deïnstalleren. De app blijft geïnstalleerd.",
        advancedClearButton: "Alle toestemmingen wissen",
        advancedCleared: "Toestemmingen gewist.",
        advancedClearConfirmTitle: "Alle toestemmingen wissen?",
        advancedClearConfirmBody: "Functies die toestemmingen nodig hebben, werken niet meer totdat je ze opnieuw verleent. Je instellingen blijven behouden.",
        advancedUninstallSection: "Deïnstalleren",
        advancedUninstallDescription: "Doet al het bovenstaande, verwijdert daarna de voorkeuren en verplaatst Vorssaint naar de Prullenmand, zonder iets achter te laten. De app sluit af zodra dit klaar is. Je kunt op elk moment opnieuw installeren.",
        advancedUninstallButton: "Vorssaint volledig deïnstalleren",
        advancedUninstallConfirmTitle: "Vorssaint deïnstalleren?",
        advancedUninstallConfirmBody: "Vorssaint wist zijn toestemmingen, verwijdert zijn voorkeuren en verplaatst zichzelf naar de Prullenmand, en sluit dan af. Dit kan niet ongedaan worden gemaakt vanuit de app, maar het blijft in de Prullenmand tot je die leegt.",
        advancedUninstallFailedTitle: "Deïnstalleren gestopt",
        advancedUninstallFailedBody: "Vorssaint kon een gewijzigde systeeminstelling niet herstellen: sluimerstand, ventilatorsnelheid of muisversnelling. Er is niets verwijderd. Probeer het opnieuw en sta het wachtwoordverzoek toe als dat verschijnt.",

        launchAtLogin: "Openen bij aanmelden",
        languageLabel: "Taal",
        menuBarSection: "Menubalk",
        showCountdown: "Toon resterende tijd naast het symbool",
        globalHotkeySection: "Globale sneltoets",
        hotkeyToggle: "Sneltoets voor “Wakker houden” inschakelen",
        hotkeyCaption: "Werkt in elke app, geen extra toestemmingen nodig.",

        sessionSection: "Sessie",
        defaultDurationLabel: "Standaardduur",
        keepAwakeAutoStart: "Wakker houden zodra Vorssaint opent",
        keepAwakeAutoStartCaption: "Start een sessie met de standaardduur.",
        batteryProtectionSection: "Batterijbescherming",
        batteryDisableBelow: "Uitschakelen als batterij onder",
        batteryNever: "Nooit",
        batteryProtectionCaption: "Voorkomt dat een vergeten sessie de batterij van de MacBook leegtrekt.",
        clamshellSection: "Gesloten deksel",
        configuring: "Wordt geconfigureerd…",
        sudoersFailed: "Kon de modus voor gesloten deksel niet inschakelen. Probeer het opnieuw.",
        clamshellExplanation: "“Doorwerken met gesloten deksel” schakelt de sluimerstand volledig uit zolang “Wakker houden” actief is, en wordt automatisch teruggezet zodra de sessie eindigt of de app afsluit. Gebruik dit bij voorkeur met de stekker in het stopcontact.",

        scrollSection: "Scrollen",
        invertMouseScroll: "Muisscrollen omkeren",
        invertMouseScrollCaption: "Keert de richting van het muiswiel om.",
        scrollTrackpadNote: "Het trackpad blijft ongewijzigd: het behoudt het natuurlijke scrollen van macOS.",
        scrollActiveNow: "Muisscrollen wordt nu omgekeerd",
        mouseNavigationActiveNow: "Zijknoppen nu actief",
        smoothScrollName: "Vloeiend scrollen",
        smoothScrollCaption: "Verandert elke stap van het muiswiel in een korte, zachte glijbeweging. Het trackpad blijft ongewijzigd.",
        smoothScrollStepLabel: "Scrollsnelheid",
        mouseNavigationSection: "Navigatie",
        mouseNavigationEnable: "Zijknoppen gebruiken voor Terug en Vooruit",
        mouseNavigationCaption: "Verandert de Terug- en Vooruit-knoppen van de muis in navigatieopdrachten in Finder, browsers en compatibele apps.",
        middleClickSection: "Middelste klik",
        middleClickEnable: "Klik met drie vingers werkt als middelste klik",
        middleClickEnableCaption: "Het trackpad met drie vingers indrukken werkt als een klik op het muiswiel: links openen in een nieuw tabblad, tabbladen sluiten en al het andere wat de middelste knop doet.",
        middleClickDragConflict: "Slepen met drie vingers van macOS staat aan en gebruikt hetzelfde gebaar. Schakel dit uit in Systeeminstellingen onder Toegankelijkheid, Wijzerbediening, Trackpad-opties, zodat de middelste klik werkt.",
        middleClickTapPicker: "Een lichte tik klikt ook",
        middleClickTapOff: "Uit",
        middleClickTapThreeFingers: "3 vingers",
        middleClickTapFourFingers: "4 vingers",
        middleClickTapCaption: "Een lichte tik met dat aantal vingers, zonder te drukken, activeert ook de middelste klik. Vegen telt nooit mee. Als de macOS-tik met drie vingers is toegewezen aan Opzoeken, schakel dat dan uit zodat beide niet tegelijk afgaan.",
        quickToolsTab: "Snelpaneel",
        quickToolShortcutToggle: "Globale sneltoets",
        ocrName: "Tekst van scherm kopiëren",
        ocrCaption: "Selecteer een deel van het scherm en de herkende tekst wordt gekopieerd, klaar om te plakken.",
        ocrCopied: "Tekst gekopieerd",
        ocrNoText: "Geen tekst gevonden",
        colorPickerName: "Kleurenpipet",
        colorPickerCaption: "Grijp de kleur van elke pixel op het scherm en kopieer die in je favoriete formaat.",
        colorPickerFormatLabel: "Gekopieerd formaat",
        colorPickerBareHexToggle: "Kopiëren zonder het #-voorvoegsel",
        colorPickerPickNow: "Kleur kiezen",
        micMuteName: "Microfoon dempen",
        micUnmuteName: "Microfoon weer aanzetten",
        micMuteCaption: "Schakelt de microfoon van de Mac uit met een klik of sneltoets, in elke app.",
        micMutedHUD: "Microfoon gedempt",
        micUnmutedHUD: "Microfoon weer aan",
        micMuteMenuBarToggle: "Tonen in de menubalk zolang gedempt",
        micMuteMenuBarCaption: "Een rode doorgestreepte microfoon verschijnt naast het symbool van de app in de menubalk.",
        pastePlainName: "Als platte tekst plakken",
        pastePlainCaption: "Plakt wat je hebt gekopieerd zonder kleuren, lettertypen of opmaak. Het origineel blijft op het klembord staan.",
        launcherName: "Snelpaneel",
        launcherCaption: "Een zwevend paneel met je favoriete hulpprogramma's, overal op te roepen met een sneltoets.",
        launcherOpenNow: "Snelpaneel openen",
        launcherEditHint: "Gebruik de instellen-knop om hulpprogramma's te kiezen, te verbergen en te verslepen.",
        launcherEmptyState: "Alle hulpprogramma's zijn verborgen. Gebruik de instellen-knop om ze terug te zetten.",
        launcherAddSection: "Terugzetten",
        launcherKeysHint: "Pijltjes navigeren, Enter opent, 1 tot 9 openen direct",

        switcherSection: "App-omschakelaar",
        switcherEnable: "Vorssaint-omschakelaar gebruiken",
        switcherEnableCaption: "Schakel tussen apps en vensters, inclusief geminimaliseerde vensters en meerdere vensters van dezelfde app.",
        switcherUsageHint: "Houd de sneltoets ingedrukt om te navigeren; laat los om het venster te activeren. Shift of ← gaat terug; W sluit het venster; Q sluit de app af; Esc annuleert.",
        switcherNoWindows: "Geen geopende vensters",
        switcherIconRowMode: "Toon %@ met grote symbolen",
        switcherIconRowModeCaption: "Toont één symbool per app met de venstervoorvertoningen van die app erboven.",
        switcherSimpleMode: "Eenvoudige app-omschakelaar",
        switcherSimpleModeCaption: "Toont app-symbolen en venstertitels, zonder voorvertoningen of schermopname door de omschakelaar.",
        switcherShortcutHintApps: "Apps",
        switcherShortcutHintWindows: "Vensters",
        switcherWindowShortcutCaption: "Opent een omschakelaar voor de vensters van de voorste app. Terwijl de app-omschakelaar open is, springt dit tussen de vensters van de geselecteerde app.",
        switcherTakeOverSystemShortcuts: "macOS ⌘Tab en ⌘` vervangen",
        switcherTakeOverSystemShortcutsCaption: "Schakelt de bijbehorende macOS-app- en venstersneltoetsen alleen uit terwijl de omschakelaar van Vorssaint actief is. Alle actieve apps blijven bereikbaar.",
        switcherAppearanceDelay: "Verschijningsvertraging",
        switcherAppearanceDelayCaption: "Hoe lang de sneltoets ingedrukt moet blijven voordat de omschakelaar verschijnt.",
        switcherMergeTabs: "Toon één item per app",
        switcherMergeTabsCaption: "Voegt alle vensters van een app samen tot één item in de omschakelaar, in plaats van één item per venster.",
        switcherWindowlessApps: "Apps zonder geopend venster",
        switcherWindowlessAppsCaption: "Bepaalt welke actieve apps zonder enig venster in de omschakelaar verschijnen.",
        switcherWindowlessAppsOff: "Niet tonen",
        switcherWindowlessAppsFinder: "Alleen Finder",
        switcherWindowlessAppsAll: "Alle apps",
        switcherNoOpenWindow: "Geen geopend venster",
        switcherOtherDesktop: "Ander bureaublad",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Vensters voorvertonen vanuit het Dock",
        dockPreviewEnableCaption: "Beweeg over een geopende app in het Dock om de vensters te zien, en klik dan op het gewenste venster.",
        dockPreviewBackgroundOpacity: "Achtergrond van paneel",
        dockPreviewBackgroundOpacityCaption: "Verlaag dit om meer te zien van wat achter het paneel zit.",
        dockPreviewOpenDelay: "Openingsvertraging",
        dockPreviewOpenDelayCaption: "Hoe lang de wijzer op een symbool moet blijven staan voordat het paneel opent.",
        dockPreviewQuitAppOnClose: "App afsluiten met de ×-knop",
        dockPreviewQuitAppOnCloseCaption: "In Dock Preview sluit × de hele app af in plaats van alleen dat venster te sluiten.",
        dockClickMinimize: "Klik op Dock-symbool om te minimaliseren",
        dockClickMinimizeCaption: "De vensters van de actieve app minimaliseren wanneer je op het Dock-symbool klikt. Klik nogmaals om ze terug te halen.",
        dockClickCycleWindows: "Klik op Dock-symbool om tussen vensters te wisselen",
        dockClickCycleWindowsCaption: "Klik op het Dock-symbool van een actieve app om door zijn vensters te bladeren, zoals ⌘`.",
        dockPreviewActiveNow: "Actief in het Dock",
        dockPreviewDockUnavailable: "Kon Dock-items niet lezen.",
        dockPreviewAutohideBeta: "Bèta. Er kunnen nog fouten optreden.",
        dockPreviewOpenWindow: "Venster openen",
        dockPreviewCloseWindow: "Venster sluiten",
        dockPreviewMinimizeWindow: "Venster minimaliseren",
        dockPreviewRestoreWindow: "Venster herstellen",
        dockPreviewPinPanel: "Voorvertoning vastzetten",
        dockPreviewUnpinPanel: "Voorvertoning losmaken",
        dockPreviewPinned: "Vastgezet",
        dockPreviewClosePanel: "Voorvertoning sluiten",
        dockPreviewPreviousWindow: "Vorige venster",
        dockPreviewNextWindow: "Volgende venster",

        cutPasteName: "Knippen & plakken",
        cutPasteEnable: "Bestanden knippen & plakken in Finder",
        cutPasteEnableCaption: "Gebruik ⌘X om te knippen en ⌘V om bestanden en mappen te verplaatsen in Finder.",
        cutPasteShowHUD: "Zwevend paneel tonen",
        cutPasteShowHUDCaption: "Toont een zwevende indicator met de geknipte bestanden zolang Finder actief is.",
        cutPasteHowTitle: "Zo werkt het",
        cutPasteStep1: "Selecteer items in Finder en druk op ⌘X om ze te knippen.",
        cutPasteStep2: "Open de doelmap en druk op ⌘V om ze daarheen te verplaatsen.",
        cutPasteTextNote: "In tekstvelden (bijvoorbeeld bij het hernoemen) blijven ⌘X en ⌘V gewoon werken.",
        cutPasteActiveNow: "Klaar om te knippen in Finder",
        cutPasteAutomationNote: "De eerste keer vraagt macOS om toestemming om Finder te besturen.",
        cutReadyTitle: "Geknipt",
        cutReadyHint: "in de doelmap om te verplaatsen",
        cutCancel: "Knippen annuleren",
        cutDoneTitle: "Verplaatst!",
        cutMovedSingular: "1 item verplaatst",
        cutMovedPluralFormat: "%d items verplaatst",
        cutSomeFailed: "Sommige items konden niet worden verplaatst",
        cutMovingTitle: "Wordt verplaatst…",
        cutMovingCountFormat: "%d van %d",

        autoQuitName: "Afsluiten bij sluiten",
        autoQuitEnable: "App afsluiten wanneer het laatste venster sluit",
        autoQuitEnableCaption: "Het sluiten van het laatste venster van een app sluit ook de app af.",
        autoQuitActiveNow: "Nu actief",
        autoQuitHowTitle: "Zo werkt het",
        autoQuitStep1: "Sluit het laatste venster van een app (⌘W of de rode knop).",
        autoQuitStep2: "De app sluit zichzelf af. Dialoogvensters zoals “Wijzigingen bewaren?” verschijnen nog steeds.",
        autoQuitPredictableNote: "Apps die normaal zonder venster draaien, worden nooit afgesloten.",
        autoQuitExceptionsTitle: "Uitzonderingen",
        autoQuitExceptionsCaption: "Apps op deze lijst blijven open, ook zonder vensters.",
        autoQuitExceptionsEmpty: "Geen uitzonderingen",
        autoQuitAddApp: "App toevoegen…",

        uninstallerName: "Deïnstallatieprogramma",
        uninstallerEnableCaption: "Verwijdert een app samen met de caches, voorkeuren, logbestanden en resten die hij achterlaat.",
        uninstallerStep1: "Sleep een app naar Instellingen, of kies er een uit de lijst.",
        uninstallerStep2: "Bekijk de gevonden bestanden en hoeveel ruimte ze innemen.",
        uninstallerStep3: "Verplaats wat je wilt naar de Prullenmand. Er wordt niets definitief verwijderd.",
        uninstallerMenuItem: "Een app deïnstalleren…",
        uninstallerDropTitle: "Sleep een app hierheen",
        uninstallerDropSubtitle: "of kies er een om te scannen",
        uninstallerChoose: "App kiezen…",
        uninstallerPickerTitle: "App kiezen",
        uninstallerPickerSearch: "Apps zoeken",
        uninstallerPickerEmpty: "Geen apps gevonden",
        uninstallerEmptyNote: "Er wordt niets verwijderd zonder jouw bevestiging.",
        uninstallerFDANote: "Geef volledige schijftoegang voor een grondigere scan.",
        uninstallerFDAGrant: "Toegang verlenen…",
        uninstallerFDAHint: "Schakel Vorssaint in de lijst in. Staat het er niet bij, klik dan op + en kies Vorssaint uit Programma's. De toegang geldt pas nadat je de app opnieuw opent.",
        uninstallerFDARelaunch: "Nu herstarten",
        uninstallerScanning: "Bestanden worden gescand…",
        uninstallerRemoving: "Wordt naar de Prullenmand verplaatst…",
        uninstallerFoundTitle: "gevonden",
        uninstallerSelectedFormat: "%d van %d geselecteerd",
        uninstallerRemove: "Naar Prullenmand verplaatsen",
        uninstallerCancel: "Annuleren",
        uninstallerDoneTitle: "Klaar!",
        uninstallerFreedFormat: "%@ vrijgemaakt",
        uninstallerSomeFailed: "Sommige items konden niet naar de Prullenmand worden verplaatst.",
        uninstallerFailedNeedsFDA: "Data van apps in de sandbox kan alleen worden verplaatst met volledige schijftoegang. Het beheerderswachtwoord vervangt dit niet.",
        uninstallerFailedMoreFormat: "en nog %d",
        uninstallerAnother: "Nog een deïnstalleren",
        uninstallerCatApp: "Programma",
        uninstallerCatSupport: "Ondersteuning",
        uninstallerCatCaches: "Caches",
        uninstallerCatPreferences: "Voorkeuren",
        uninstallerCatContainers: "Containers",
        uninstallerCatLogs: "Logbestanden",
        uninstallerCatState: "Opgeslagen status",
        uninstallerCatOther: "Overig",

        urlCleanerName: "URL opschonen",
        urlCleanerEnable: "URL's opschonen tijdens het kopiëren",
        urlCleanerEnableCaption: "Verwijdert trackingparameters uit een link zodra die op het klembord terechtkomt.",
        urlCleanerActiveNow: "Nu actief",
        urlCleanerManualTitle: "Nu opschonen",
        urlCleanerInputPlaceholder: "Plak een URL",
        urlCleanerOutputPlaceholder: "De opgeschoonde URL verschijnt hier",
        urlCleanerCleanButton: "Opschonen",
        urlCleanerPasteButton: "Plakken",
        urlCleanerCopyButton: "Kopiëren",
        urlCleanerClearButton: "Veld leegmaken",
        urlCleanerNoURL: "Plak een geldige URL.",
        urlCleanerNoChange: "Niets om op te schonen.",
        urlCleanerCleaned: "URL opgeschoond.",
        urlCleanerCopied: "Gekopieerd.",
        urlCleanerLocalNote: "Lokaal. Geen netwerk.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Zoek, installeer en verwijder formules en casks.",
        homebrewMissingTitle: "Homebrew niet gevonden",
        homebrewMissingBody: "Vorssaint kan Terminal openen met het officiële Homebrew-installatieprogramma. Terminal toont de stappen en vraagt indien nodig om je wachtwoord.",
        homebrewInstallHomebrew: "Homebrew installeren",
        homebrewInstallHomebrewCaption: "Kom hier terug zodra Terminal klaar is en klik op Vernieuwen.",
        homebrewInstallHomebrewOpened: "Installatieprogramma geopend in Terminal.",
        homebrewShellSetupTitle: "Terminal-configuratie afronden",
        homebrewShellSetupBody: "Homebrew is geïnstalleerd, maar Terminal vindt het commando brew mogelijk nog niet. Vorssaint kan Terminal openen met het configuratiecommando.",
        homebrewShellSetupButton: "Terminal configureren",
        homebrewShellSetupOpened: "Commando geopend in Terminal. Kom daarna hier terug en klik op Vernieuwen.",
        homebrewRefresh: "Vernieuwen",
        homebrewCheckPackages: "Pakketten controleren",
        homebrewTrustTitle: "Tap nog niet vertrouwd",
        homebrewTrustCaption: "Homebrew vraagt nu om je bevestiging voordat het taps van derden gebruikt. Vertrouw %@ om door te gaan.",
        homebrewTrustButton: "Vertrouwen en doorgaan",
        homebrewSearchPlaceholder: "Pakketten zoeken",
        homebrewKeyboardHint: "Spatiebalk of Enter sluit het macOS-paneel. Gebruik de zoekknop.",
        homebrewSearchButton: "Zoeken",
        homebrewSearchResults: "Resultaten",
        homebrewInstalled: "Geïnstalleerd",
        homebrewAll: "Alle",
        homebrewFormulas: "Formules",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Geen pakketten gevonden",
        homebrewNoSelection: "Selecteer een geïnstalleerd pakket of zoek naar een nieuw pakket.",
        homebrewDetailsTitle: "Pakketdetails",
        homebrewInstall: "Installeren",
        homebrewUninstall: "Deïnstalleren",
        homebrewUpgrade: "Bijwerken",
        homebrewUpgradeAll: "Alles bijwerken",
        homebrewUpdateHomebrew: "Homebrew bijwerken",
        homebrewAllPackages: "pakketten",
        homebrewOpenTerminal: "Terminal openen",
        homebrewCancelOperation: "Annuleren",
        homebrewClearLog: "Logboek wissen",
        homebrewLogTitle: "Logboek",
        homebrewVersion: "Versie",
        homebrewDescription: "Type",
        homebrewHomepage: "Website openen",
        homebrewPopularity: "Populariteit",
        homebrewPopularityFormat: "%@ installaties in %@ dagen",
        homebrewInstalledBadge: "Geïnstalleerd",
        homebrewNotInstalledBadge: "Niet geïnstalleerd",
        homebrewUpdates: "Updates",
        homebrewUpdateAvailableBadge: "Update beschikbaar",
        homebrewLatestVersion: "Nieuwste",
        homebrewConfirmInstallTitle: "Installeren met Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew downloadt en installeert %@. Afhankelijkheden kunnen ook worden geïnstalleerd.",
        homebrewConfirmUninstallTitle: "Deïnstalleren met Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew deïnstalleert %@. Configuratiebestanden kunnen op het systeem achterblijven.",
        homebrewConfirmUpgradeTitle: "Bijwerken met Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew downloadt en past de nieuwste versie van %@ toe. Afhankelijkheden kunnen ook worden bijgewerkt.",
        homebrewConfirmUpgradeAllTitle: "Alles bijwerken met Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew downloadt en past de nieuwste versies toe voor pakketten met beschikbare updates. Afhankelijkheden kunnen ook worden bijgewerkt.",
        homebrewConfirmUpdateHomebrewTitle: "Homebrew bijwerken?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew haalt de nieuwste informatie op en laadt daarna je pakketten opnieuw.",
        homebrewTerminalFallback: "Deze actie heeft Terminal nodig om naar het beheerderswachtwoord te vragen. Vorssaint registreert nooit wachtwoorden.",
        homebrewLoading: "Wordt geladen…",
        homebrewSearchEmpty: "Geen resultaten",
        homebrewOperationInstallFormat: "%@ wordt geïnstalleerd",
        homebrewOperationUninstallFormat: "%@ wordt gedeïnstalleerd",
        homebrewOperationUpgradeFormat: "%@ wordt bijgewerkt",
        homebrewOperationUpgradeAll: "Pakketten worden bijgewerkt",
        homebrewOperationUpdateHomebrew: "Homebrew wordt bijgewerkt",
        homebrewOperationInstalledFormat: "%@ geïnstalleerd.",
        homebrewOperationUninstalledFormat: "%@ gedeïnstalleerd.",
        homebrewOperationUpgradedFormat: "%@ bijgewerkt.",
        homebrewOperationUpgradedAll: "Pakketten bijgewerkt.",
        homebrewOperationUpdatedHomebrew: "Homebrew bijgewerkt.",
        homebrewOperationFailedFormat: "%@ kon niet worden voltooid.",
        homebrewOperationCancelled: "Actie geannuleerd.",
        homebrewOperationPreparing: "Wordt voorbereid...",
        homebrewOperationDownloading: "Bestanden worden gedownload...",
        homebrewOperationInstalling: "Bestanden worden geïnstalleerd...",
        homebrewOperationUninstalling: "Bestanden worden verwijderd...",
        homebrewOperationUpgrading: "Bestanden worden bijgewerkt...",
        homebrewOperationFinalizing: "Wordt afgerond...",
        homebrewOperationRefreshing: "Lijst wordt vernieuwd...",
        homebrewOperationTerminal: "Ga verder in Terminal.",
        homebrewOperationElapsedFormat: "%@ verstreken",
        homebrewOperationShowDetails: "Details tonen",
        homebrewOperationHideDetails: "Details verbergen",
        homebrewOperationTechnicalLog: "Technische details",
        homebrewOperationProgressUnknown: "Homebrew heeft nog geen percentage doorgegeven.",

        mediaName: "Media",
        mediaEnableCaption: "Comprimeer video's, converteer en bewerk afbeeldingen, maak GIF's en haal lokaal tekst uit beelden.",
        mediaLocalNote: "Lokaal. Geen netwerk.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Afbeelding",
        mediaToolText: "Tekst",
        mediaSelectFile: "Bestand kiezen",
        mediaDropHint: "Zet een bestand hier neer of klik om er een te kiezen.",
        mediaOutput: "Uitvoer",
        mediaOutputAutomatic: "Automatisch",
        mediaChooseOutput: "Bestemming",
        mediaStartVideo: "Video comprimeren",
        mediaStartGIF: "GIF maken",
        mediaStartImage: "Afbeelding bewerken",
        mediaStartConvertPDF: "Omzetten naar PDF",
        mediaStartText: "Tekst uithalen",
        mediaCancel: "Annuleren",
        mediaStartTime: "Start",
        mediaEndTime: "Einde",
        mediaQuality: "Compressie",
        mediaCompressionLow: "Laag",
        mediaCompressionMedium: "Gemiddeld",
        mediaCompressionHigh: "Hoog",
        mediaMaxSize: "Grootte",
        mediaSizingResolution: "Resolutie",
        mediaSizingFileSize: "Bestandsgrootte",
        mediaTargetSize: "Doelgrootte",
        mediaTargetSizeHint: "De resolutie past zich aan om onder de limiet te blijven.",
        mediaErrorTargetTooSmall: "Doelgrootte te klein voor dit fragment. Kort het in of verhoog de limiet.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Breedte",
        mediaFPS: "FPS",
        mediaKeepAudio: "Audio behouden",
        mediaCodec: "Codec",
        mediaFormat: "Formaat",
        mediaStripMetadata: "Metadata verwijderen",
        mediaLoopGIF: "GIF herhalen",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Nauwkeurig",
        mediaOCRFast: "Snel",
        mediaLanguageCorrection: "Taalcorrectie",
        mediaTextOutputNote: "Uitgehaalde tekst kan worden gekopieerd en opgeslagen als TXT.",
        mediaRunning: "Wordt verwerkt",
        mediaCompleted: "Klaar",
        mediaCancelled: "Geannuleerd.",
        mediaOpenInFinder: "Tonen",
        mediaCopyText: "Tekst kopiëren",
        mediaRunAgain: "Opnieuw uitvoeren",
        mediaEmptyText: "Geen tekst gevonden.",
        mediaResultSavedFormat: "Opgeslagen als %@",
        mediaResultSizeFormat: "%@ naar %@",
        mediaResultGrewCaption: "Het geconverteerde bestand is groter dan het origineel.",
        mediaErrorNoFile: "Kies eerst een bestand.",
        mediaErrorNoVideo: "Dit bestand heeft geen videospoor.",
        mediaErrorSameOutput: "Kies een bestemming die verschilt van het originele bestand.",
        mediaErrorUnsupported: "Formaat wordt niet ondersteund door macOS.",

        shelfName: "Shelf",
        shelfEnable: "Tijdelijke plek om bestanden naartoe te slepen",
        shelfEnableCaption: "Een zwevende plek om bestanden, afbeeldingen en tekst te verzamelen en ze later overal naartoe te slepen.",
        shelfHowTitle: "Zo werkt het",
        shelfStep1: "Open het met de sneltoets, of door de muis te schudden tijdens het slepen.",
        shelfStep2: "Zet bestanden, afbeeldingen, links of tekst erop neer om ze vast te houden.",
        shelfStep3: "Sleep elk item weer naar een willekeurige app wanneer je het nodig hebt.",
        shelfShakeToggle: "Openen door de muis te schudden tijdens het slepen",
        shelfShakeCaption: "Schud de wijzer snel terwijl je een item vasthoudt om het bij de cursor te laten verschijnen.",
        shelfDropZoneToggle: "Gesleepte bestanden bewaren in de menubalk",
        shelfDropZoneCaption: "Terwijl je een bestand sleept, verschijnt de Shelf onder het menubalksymbool. Wat je erop neerzet, blijft daar bewaard, in een knop die je met een klik in- en uitklapt en die verdwijnt zodra de Shelf leeg is.",
        shelfDropZoneLabel: "Hier neerzetten",
        shelfCollapse: "Inklappen",
        shelfBehaviorTitle: "Na gebruik",
        shelfCloseAfterDrop: "Sluiten na neerzetten in een andere app",
        shelfCloseAfterDropCaption: "Sluit de Shelf zodra de bestemming de items accepteert. De speld in het paneel houdt hem open.",
        shelfRemoveAfterDrop: "Items verwijderen na neerzetten",
        shelfRemoveAfterDropCaption: "Items die door een andere app worden geaccepteerd, verlaten de Shelf. Schakel dit uit om er een kopie te bewaren.",
        shelfExclusionsTitle: "Automatische uitzonderingen",
        shelfExclusionsEmpty: "Geen apps toegevoegd.",
        shelfExclusionsCaption: "Schudden en de menubalk-dropzone blijven uit voor sleepacties die in deze apps beginnen. De sneltoets en Nu openen werken nog steeds.",
        shelfPin: "Openhouden",
        shelfUnpin: "Sluiten na gebruik toestaan",
        extraBrightnessName: "Extra helderheid",
        extraBrightnessCaption: "Gebruikt de HDR-marge van het beeldscherm om verder te gaan dan de maximale helderheid. Verbruikt meer batterij en de Mac kan warm worden.",
        extraBrightnessLevelLabel: "Intensiteit",
        extraBrightnessUnsupported: "Alleen beschikbaar op XDR-beeldschermen, zoals die van de 14- en 16-inch MacBook Pro.",
        shelfHotkeyLabel: "Sneltoets",
        shelfOpenNow: "Nu openen",
        shelfNoPermission: "Vereist geen toestemmingen.",
        shelfMenuItem: "Shelf openen",
        shelfTitle: "Shelf",
        shelfEmpty: "Sleep items hierheen",
        shelfClearAll: "Alles wissen",
        shelfRemoveSelected: "Selectie verwijderen",
        shelfSelectedFormat: "%d geselecteerd",
        shelfHint: "Klik om te selecteren. Sleep eruit om te gebruiken of rechtsklik voor meer acties.",
        shelfItemImage: "Afbeelding",
        shelfTooltipItemsFormat: "%d items",
        shelfTooltipImageSingular: "%d afbeelding",
        shelfTooltipImagePlural: "%d afbeeldingen",
        shelfTooltipFileSingular: "%d bestand",
        shelfTooltipFilePlural: "%d bestanden",
        shelfTooltipNoteSingular: "%d notitie",
        shelfTooltipNotePlural: "%d notities",
        shelfTooltipLinkSingular: "%d link",
        shelfTooltipLinkPlural: "%d links",
        shelfActionOpen: "Openen",
        shelfActionOpenWith: "Openen met",
        shelfActionAirDrop: "Delen via AirDrop",

        breakdownMeasuring: "Wordt gemeten…",

        mixerSection: "Volumemixer",
        mixerEmpty: "Apps die audio gebruiken, verschijnen hier",
        mixerUnavailable: "Beschikbaar vanaf macOS 14.4",
        mixerPermissionBody: "Om het volume per app aan te passen, sta “Scherm- en systeemaudio-opname” toe in Systeeminstellingen. Audio wordt nooit opgenomen.",
        mixerResetTooltip: "Terugzetten naar 100%",
        mixerOutputDefault: "Standaard",
        mixerOutputCurrent: "huidig",
        mixerOutputUnavailable: "Uitvoer niet beschikbaar",
        mixerOutputFallback: "Standaard wordt gebruikt totdat dit apparaat terugkeert.",
        mixerBypassedCaption: "Deze app beheert zijn eigen audio.",
        mixerOutputTooltip: "Uitvoer kiezen",
        mixerSystemOutputTitle: "Uitvoer",
        mixerSystemOutputNoDevices: "Geen uitvoerapparaten gevonden",
        mixerSystemOutputTooltip: "Systeemuitvoer kiezen",
        mixerSystemOutputErrorFormat: "Kon niet wisselen: %@",
        mixerLowerOnHeadphonesDisconnect: "Volume verlagen wanneer koptelefoon wordt losgekoppeld",
        mixerLowerOnHeadphonesDisconnectCaption: "Past de uitvoer aan wanneer een bekabelde of Bluetooth-koptelefoon wordt losgekoppeld.",
        mixerHeadphonesDisconnectVolume: "Volume na loskoppelen",
        preciseVolumeRollerEnable: "Fijnere volumestappen gebruiken",
        preciseVolumeRollerCaption: "Verandert volumewieltjes en -toetsen in kleinere systeemvolumestappen.",
        preciseVolumeRollerTapFailed: "Kon niet luisteren naar volumetoetsen.",
        soundOutputSwitcherTitle: "Uitvoeromschakelaar",
        soundOutputSwitcherEnable: "Uitvoer wisselen met sneltoets",
        soundOutputSwitcherCaption: "Kies uitvoerapparaten en gebruik de sneltoets om naar de volgende beschikbare te gaan.",
        soundOutputSwitcherDevices: "Uitvoer in wisselvolgorde",
        soundOutputSwitcherNoAvailableSelection: "Selecteer minstens één beschikbare uitvoer.",
        mixerInputTitle: "Microfoon",
        mixerInputNoDevices: "Geen microfoons gevonden",
        mixerInputUnavailable: "Microfoon niet beschikbaar",
        mixerInputFallback: "Standaard wordt gebruikt totdat deze microfoon terugkeert.",
        mixerInputTooltip: "Microfoon kiezen",
        mixerInputErrorFormat: "Kon niet wisselen: %@",
        mixerVisibleApps: "Apps in de lijst",
        mixerAllShown: "Alle",
        mixerHiddenCountLabel: "Verborgen",
        mixerHideFromList: "Verbergen uit de lijst",

        updatesSection: "Updates",
        autoCheckToggle: "Automatisch zoeken naar updates",
        includeBetaUpdatesToggle: "Bèta-updates ontvangen",
        includeBetaUpdatesCaption: "Bètaversies bevatten functies die nog in ontwikkeling zijn en kunnen fouten of onvolledig gedrag bevatten.",
        betaBadgeLabel: "Bèta",
        checkNowButton: "Nu zoeken",
        updateChecking: "Wordt gezocht…",
        updateUpToDate: "Je gebruikt de nieuwste versie.",
        updateAvailablePrefix: "Update beschikbaar:",
        updateInstallButton: "Downloaden en installeren",
        updateDownloading: "Update wordt gedownload…",
        updateInstalling: "Wordt geïnstalleerd en herstart…",
        updateFailedPrefix: "Zoeken mislukt:",
        updateLastChecked: "Laatst gezocht:",
        updateNotifyTitle: "Vorssaint-update",
        updateInstallFailedBody: "De update is gedownload, maar kon niet worden toegepast. Download de nieuwste versie van de GitHub-releasepagina en sleep de app over de huidige versie heen.",
        updateNeedsApplicationsTitle: "Verplaats Vorssaint naar Programma's",
        updateNeedsApplicationsBody: "De app draait vanaf een plek die niet kan worden bijgewerkt, zoals het schijfkopiebestand of een tijdelijke systeemlocatie. Sleep Vorssaint naar de map Programma's, open het vandaar en probeer het opnieuw.",
        menuCheckUpdates: "Naar updates zoeken…",

        permissionRequired: "Toestemming vereist",
        permissionAccessibility: "Toegankelijkheid",
        permissionScreenRecording: "Schermopname",
        permissionGranted: "Verleend",
        permissionMissing: "Niet verleend",
        permissionOpenSettings: "Systeeminstellingen openen…",
        permissionRequest: "Toegang verlenen",
        permissionRestartNote: "macOS kan na het verlenen vragen om de app opnieuw te openen.",

        aboutDescription: "Een hulpmiddelencentrale voor je Mac.\nEnergie, systeemmonitor, scrollen en een vensteromschakelaar, direct in de menubalk.",
        versionPrefix: "Versie",
        reviewIntro: "Introductie opnieuw bekijken",
        reviewHighlights: "Hoogtepunten bekijken",
        viewOnGitHub: "Bekijken op GitHub",

        obContinue: "Doorgaan",
        obBack: "Terug",
        obSkipStep: "Deze stap overslaan",
        obStart: "Vorssaint openen",
        obStepWelcomeTitle: "Welkom bij Vorssaint",
        obStepWelcomeBody: "Een discrete menubalk-app die macOS in het dagelijks gebruik praktischer maakt.",
        obWelcomeBullet1Title: "Energie onder controle",
        obWelcomeBullet1Body: "Houd de Mac zo lang wakker als je wilt, zelfs met gesloten deksel.",
        obWelcomeBullet2Title: "Helder overzicht van je systeem",
        obWelcomeBullet2Body: "CPU-, GPU- en batterijtemperaturen, hardwaregebruik en geheugendruk in real time.",
        obWelcomeBullet3Title: "Muis en vensters, zoals jij het wilt",
        obWelcomeBullet3Body: "Omgekeerd muisscrollen en een vensteromschakelaar met miniaturen.",
        obLanguageLabel: "Taal",
        obStepAccessibilityTitle: "Toegankelijkheid",
        obStepAccessibilityBody: "Nodig om muisscrollen om te keren en om de vensteromschakelaar te laten reageren op het toetsenbord.",
        obAccessibilityWhy: "De app houdt alleen het muiswiel en de sneltoets van de omschakelaar in de gaten. Er wordt niets opgenomen of ergens naartoe gestuurd.",
        obStepRecordingTitle: "Schermopname",
        obStepRecordingBody: "Laat de omschakelaar echte vensterminiaturen tonen in plaats van alleen symbolen.",
        obRecordingWhy: "Miniaturen worden ter plekke gegenereerd, blijven in het geheugen en verlaten je Mac nooit. Zonder deze toestemming werkt de omschakelaar nog steeds met symbolen.",
        obStepMonitorTitle: "Systeemmonitor",
        obStepMonitorBody: "Het paneel toont CPU-, GPU- en batterijtemperaturen, hardwaregebruik en geheugendruk.",
        obMonitorNoPermission: "Geen toestemming nodig. Sensoren worden rechtstreeks uit het systeem gelezen.",
        obStepOptionalTitle: "Optionele functies",
        obStepOptionalBody: "Schakel in wat je nu wilt gebruiken. Alles kan later worden aangepast in Instellingen.",
        obStepStatusTitle: "Controle",
        obStepStatusBody: "Zorg dat alles klaarstaat voor de functies die je wilt gebruiken.",
        obStatusRecheck: "Opnieuw controleren",
        obStepDoneTitle: "Helemaal klaar!",
        obStepDoneBody: "Vorssaint zorgt al voor je Mac.",
        obDoneHint: "Kijk naar het zwarte gat in de menubalk, rechtsboven in het scherm.",
        obWhatsNewTitle: "Nieuw in deze versie",
        obWhatsNewFallback: "Deze update bevat de nieuwste correcties en verbeteringen.",
        obLanguageUpdateTitle: "Nu in jouw taal",
        obLanguageUpdateBody: "Vorssaint spreekt nu meerdere talen. Kies de taal die je wilt gebruiken; je kunt dit altijd wijzigen in Instellingen.",
        obPurposeTitle: "Wat brengt je hier?",
        obPurposeBody: "Kies een kant-en-klare instelling of selecteer precies wat je wilt gebruiken.",
        obPurposeSkip: "Je kunt functies later toevoegen of verwijderen in Instellingen.",

        tabMonitor: "Monitor",
        monitorMenuBarSection: "In de menubalk",
        monitorMenuBarCaption: "Kies wat naast het symbool in de menubalk verschijnt.",
        monitorCombineTemperatures: "Gebruik en temperatuur combineren",
        monitorCombineTemperaturesCaption: "Als gebruik en temperatuur voor hetzelfde onderdeel zijn ingeschakeld, toon ze dan in één blok.",
        monitorSeparateMenuBarMetrics: "Meetwaarden scheiden in eigen items",
        monitorSeparateMenuBarMetricsCaption: "Scheidt actieve blokken in de menubalk en houdt gebruik en temperatuur samen wanneer combineren aanstaat.",
        monitorNetworkUploadFirst: "Upload boven download",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Geheugen",
        monitorShowNetwork: "Netwerk",
        monitorShowPowerLabel: "Energie",
        monitorIntervalLabel: "Bijwerken elke",
        monitorInterval1: "1 seconde",
        monitorInterval2: "2 seconden",
        monitorInterval5: "5 seconden",
        monitorPanelSection: "In het paneel",
        panelNavigationMode: "Paneel navigeren per sectie",
        panelNavigationCaption: "Toont telkens één sectie. Kies Lijst om alles in één doorlopende scroll te zien.",
        panelFooterSections: "Secties",
        panelFooterList: "Lijst",
        betaBadge: "BÈTA",
        betaFeatureWarning: "Bèta. Er kunnen nog fouten optreden.",

        networkSection: "Netwerk",
        networkDownload: "Download",
        networkUpload: "Upload",
        networkThisSession: "Deze sessie",
        networkMeasuring: "Wordt gemeten…",
        networkApps: "Apps met netwerkverkeer",
        networkAppsIdle: "Geen app gebruikt nu het netwerk",

        diskSection: "Schijven",
        diskUsed: "gebruikt",
        diskFree: "vrij",
        diskAvailable: "beschikbaar",
        diskPurgeable: "wisbaar",
        diskInternal: "Intern",
        diskExternal: "Extern",
        diskSelect: "Schijf selecteren",
        diskRead: "Lezen",
        diskWrite: "Schrijven",
        diskSMARTStatus: "Status",
        diskSMARTUnavailable: "SMART niet beschikbaar voor deze schijf",
        diskTotalRead: "Totaal gelezen",
        diskTotalWritten: "Totaal geschreven",
        diskTemperature: "Temperatuur",
        diskHealth: "Gezondheid",
        diskPowerCycles: "Inschakelcycli",
        diskPowerOnHours: "Bedrijfsuren",
        diskUnsafeShutdowns: "Onveilige afsluitingen",
        diskMediaErrors: "Mediafouten",
        diskEject: "Uitwerpen",
        diskEjectAll: "Alles uitwerpen",
        diskEjecting: "Wordt uitgeworpen…",
        diskReadyToRemove: "Klaar om te verwijderen",
        diskEjectFailed: "Uitwerpen mislukt",
        diskProtectionCaption: "Werp uit voordat je loskoppelt.",
        diskNoExternal: "Geen externe schijf klaar om uit te werpen.",
        diskOpenInFinder: "Openen",
        diskStorageSettings: "Opslag",
        diskNoDisks: "Geen aangekoppelde schijven gevonden.",

        powerSection: "Energie",
        powerSystem: "Systeem",
        powerAdapter: "Netvoeding",
        powerBattery: "Batterij",
        powerCharging: "Wordt opgeladen",
        powerOnBattery: "Op batterij",
        powerPluggedIn: "Aangesloten op stroom",
        powerUnavailable: "Energiegegevens niet beschikbaar op deze Mac",
        powerAdapterMaxFormat: "max. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "CPU-temperatuur",
        monitorShowGPUTemperature: "GPU-temperatuur",
        monitorShowBatteryTemperature: "Batterijtemperatuur",
        monitorShowPeripheralBattery: "Batterij randapparaat",
        peripheralBatteryNoDevices: "Geen apparaten gevonden",
        monitorGraphsSection: "Grafieken",
        monitorGraphsCaption: "Kies welke meetwaarden een grafiek over tijd tonen.",

        updateBannerTitle: "Update beschikbaar",
        updateBannerAction: "Bijwerken",
        obStepMenuBarTitle: "Meetwaarden in de menubalk",
        obStepMenuBarBody: "Kies wat naast het symbool wordt getoond. De voorvertoning hierboven werkt live bij.",
        obStepMenuBarNote: "Nieuw: blokken voor netwerk en energie, en grafieken in het paneel. Stel dit later verder af bij Instellingen › Monitor.",
        monitorMenuBarPresetLabel: "Stijl",
        menuBarPresetReadable: "Leesbaar",
        menuBarPresetDense: "Beknopt",
        menuBarSpacingLabel: "Ruimte in menubalk",
        menuBarSpacingStandard: "Standaard",
        menuBarSpacingCompact: "Compact",
        menuBarHideIconToggle: "App-symbool verbergen zolang meetwaarden worden getoond",
        menuBarHideIconCaption: "Het symbool keert vanzelf terug wanneer de meetwaarden de balk verlaten en wanneer er iets te melden is (een update klaar of de microfoon gedempt).",
        monitorLabelStyleLabel: "Labels",
        menuBarLabelStyleCompact: "Compact",
        menuBarLabelStyleClassic: "Klassiek",
        monitorMemoryStyleLabel: "Geheugen tonen als",
        monitorMemoryPressureDot: "Drukpunt",
        memoryStyleDot: "Punt",
        memoryStylePercent: "%",
        memoryStyleBoth: "Beide",
        systemUptime: "Actief sinds",
        batteryCharge: "Lading",
        powerHealth: "Batterijstatus",
        powerCycles: "Cycli",
        speedTestRun: "Snelheidstest",
        speedTestAgain: "Opnieuw testen",
        speedTestLatency: "Latentie",
        speedTestTesting: "Wordt getest…",
        speedTestFailed: "Test mislukt",

        monitorShowInPanel: "Tonen in paneel",
        disclosureExpanded: "Uitgeklapt",
        disclosureCollapsed: "Ingeklapt",
        panelHideItem: "Verbergen in paneel",
        panelShowItem: "Tonen in paneel",
        panelHiddenItem: "Verborgen",
        monitorItemUptime: "Bedrijfstijd",
        monitorItemNetSpeed: "Live snelheid",
        monitorItemNetTotals: "Sessietotalen",
        monitorItemNetTest: "Snelheidstest",
        monitorItemDiskUsage: "Schijfgebruik",
        monitorItemDiskActivity: "Live activiteit",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Externe bescherming",
        monitorItemDiskTools: "Hulpprogramma's",
        monitorPanelConfigHint: "Open een blok om te kiezen wat het toont.",
        monitorOrderSection: "Volgorde van secties",
        monitorOrderHint: "Sleep om de panelsecties opnieuw te ordenen en gebruik het oog om elke sectie te tonen of verbergen.",
        obStepPanelTitle: "Wat er in het paneel staat",
        obStepPanelBody: "Open elk blok en kies precies wat wordt getoond wanneer je op het symbool klikt.",
        obStepPanelNavigationTitle: "Paneel op basis van secties",
        obStepPanelNavigationBody: "Het paneel kan nu telkens één sectie tonen. Je kunt wisselen tussen Secties en Lijst in Instellingen.",

        cleaningMenuItem: "Reinigingsmodus",
        utilitiesSection: "Hulpprogramma's",
        quickControlsSection: "Bediening",
        panelCategoryWindows: "Vensters",
        panelCategoryInput: "Muis en toetsenbord",
        panelCategoryFiles: "Bestanden",
        windowMaximizeName: "Vensters maximaliseren",
        windowMaximizeCaption: "De groene knop maximaliseert zonder een nieuwe Space te maken.",
        windowMaximizeActiveNow: "Groene-knop-override actief",
        windowMaximizeNeedsAccessibility: "Heeft Toegankelijkheid nodig om te werken.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Dubbele toetsen filteren",
        keyDebounceCaption: "Filtert zeer snelle dubbele toetsaanslagen.",
        keyDebounceActiveNow: "Filter actief",
        keyDebounceGlobalWindow: "Globaal venster",
        keyDebouncePerKeySection: "Specifieke toetsen",
        keyDebouncePerKeyCaption: "Waarden per toets overschrijven het globale venster. Gebruik 0 ms om een toets niet te filteren.",
        keyDebounceKeyLabel: "Toets",
        keyDebounceWindowLabel: "Venster",
        keyDebounceAddKey: "Toets toevoegen",
        keyDebounceNoOverrides: "Geen specifieke toetsen ingesteld.",
        keyDebounceRemoveKey: "Toets verwijderen",
        cleaningPanelCaption: "Vergrendelt het toetsenbord zodat je veilig kunt schoonmaken.",
        cleaningOverlayTitle: "Toetsenbord vergrendeld om schoon te maken",
        cleaningOverlaySubtitle: "Druk 5 keer op Esc om te ontgrendelen",
        cleaningOverlayUnlock: "Ontgrendelen",
        cleaningOverlayMouseHint: "Je muis en trackpad blijven werken",
        cleaningKeepScreenVisibleToggle: "Scherm zichtbaar houden",
        cleaningKeepScreenVisibleCaption: "Toont een discrete indicator in de hoek van het scherm in plaats van de inhoud te verduisteren.",
        cleaningStartNow: "Toetsenbord nu vergrendelen",
        cleaningNeedsAxTitle: "Toegankelijkheid vereist",
        cleaningNeedsAxBody: "Om het toetsenbord veilig te vergrendelen, heeft Vorssaint toestemming voor Toegankelijkheid nodig. Verleen deze in Systeeminstellingen en probeer het opnieuw.",

        tabSupport: "Ondersteunen",
        shortcutsPageCaption: "Bewerk hier alle globale sneltoetsen van de functies die op deze Mac zijn geïnstalleerd. Inactieve sneltoetsen blijven bewaard, maar worden niet uitgevoerd.",
        shortcutsPageTitle: "Toetsenbordsneltoetsen",
        settingsSearchPlaceholder: "Instellingen doorzoeken",
        donateHeading: "Help Vorssaint verder groeien",
        donateMessage: "Vorssaint is gratis, onafhankelijk en gebouwd in mijn vrije tijd. Als je financieel wilt bijdragen, helpt Buy Me a Coffee me rechtstreeks om de ontwikkeling voort te zetten.",
        donateButton: "Steunen via Buy Me a Coffee",
        donateThanks: "Bedankt dat je hier bent. 🖤",
        supportIntroTitle: "Help Vorssaint verder groeien",
        supportIntroMessage: "Als je de ontwikkeling financieel wilt steunen, is Buy Me a Coffee de enige plek daarvoor.",
        supportIntroStarButton: "Geef Vorssaint een ster op GitHub",
        supportIntroStarMessage: "Financiële steun wordt nooit verwacht. Een ster op GitHub helpt meer mensen Vorssaint te ontdekken en maakt echt verschil voor de ontwikkeling.",
        supportIntroCoffeeButton: "Steunen via Buy Me a Coffee",
        supportIntroLaterButton: "Niet nu",
        supportIntroDoneButton: "Gereed",
        discordIntroTitle: "De Vorssaint Discord-community staat nog maar aan het begin",
        discordIntroMessage: "De Vorssaint-community is nieuw en wordt nog opgebouwd. Doe vroeg mee om andere gebruikers te ontmoeten en mee te bouwen aan een gastvrije plek rond de app.",
        discordIntroBenefitHelp: "Krijg hulp en deel workflows",
        discordIntroBenefitFeedback: "Meld fouten, vraag om verbeteringen en help bepalen wat er hierna komt",
        discordIntroBenefitPreviews: "Bekijk werk in uitvoering, vroege previews en nieuws over releases",
        discordIntroJoinButton: "Word lid van de Discord-community",
        communityIntroTitle: "Zie het als eerste",
        communityIntroMessage: "Mensen die me al volgden op X zagen verschillende wijzigingen in deze update eerder dan wie dan ook. Ik post previews van wat eraan komt en laat zien hoe het werkt, zodat je de basis al kent voordat de update uitkomt. Volg mee en zie wat er hierna komt!",
        communityIntroFollowButton: "Volg @vorssaint op X",
        homebrewOfficialIntroTitle: "Nu in de officiële Homebrew-catalogus",
        homebrewOfficialIntroMessage: "Vorssaint kan nu rechtstreeks vanuit de officiële Homebrew-catalogus worden geïnstalleerd.",
        homebrewOfficialIntroInstallLabel: "Nieuwe installatie",
        homebrewOfficialIntroMigrationTitle: "Gebruikte je de oude tap?",
        homebrewOfficialIntroMigrationMessage: "Verwijder de tap eenmalig. De app en je instellingen blijven behouden.",
        homebrewOfficialIntroCopyButton: "Commando kopiëren",
        updateShowcaseTitle: "Nieuw in 3.1.4",
        updateShowcaseMessage: "Werp een korte blik op de belangrijkste verbeteringen in deze update.",
        updateShowcaseUnavailable: "De video kon nu niet worden geladen. Je kunt gewoon doorgaan.",
        updateShowcaseRestart: "Opnieuw beginnen",
        showMenuBarIcon: "Menubalksymbool tonen",
        showMenuBarIconCaption: "Als het symbool van Vorssaint verdwijnt (macOS kan menubalksymbolen verbergen als de balk vol raakt, vaak bij Macs met een notch), open Vorssaint dan opnieuw via Programma's of Spotlight: dat herbouwt het symbool en opent, als het nog steeds verborgen is, dit venster. De knop hierboven doet hetzelfde als je hier al kunt komen. Minder menubalksymbolen, of minder Vorssaint-meetwaarden, maakt dit veel minder waarschijnlijk.",
        menuBarIconStillHiddenTitle: "Het symbool is nog steeds verborgen",
        menuBarIconStillHiddenBody: "Het symbool is herbouwd, maar macOS heeft er geen zichtbare plek voor gegeven. De menubalk zit waarschijnlijk vol: verwijder een aantal menubalksymbolen (of sluit apps met lange menu's) en probeer het opnieuw.",
        menuBarIconManagerHintFormat: "%@ is open en houdt het symbool mogelijk in zijn verborgen sectie. Zoek Vorssaint daar, of stel %@ zo in dat Vorssaint altijd wordt getoond.",
        shortcutRecording: "Druk de nieuwe sneltoets in",
        shortcutReset: "Terugzetten",
        shortcutNone: "Geen",
        shortcutClear: "Sneltoets verwijderen",
        shortcutInvalid: "Gebruik minstens Control, Option of Command met een toets.",
        shortcutPressKeys: "Druk toetsen in",
        shortcutEscapeHint: "Esc annuleert.",
        shortcutDeleteHint: "Delete wist.",
        shortcutNotCaptured: "Er is niets vastgelegd. macOS of een andere app gebruikt die combinatie al. Probeer een andere.",
        shortcutConflictFormat: "Deze sneltoets wordt al gebruikt door %@.",
        shortcutUnavailable: "macOS heeft deze sneltoets geweigerd. Kies een andere.",
        shelfShortcutToggle: "Sneltoets voor Shelf",
        switcherUsageHintFormat: "Houd %@ ingedrukt om te navigeren; laat los om het venster te activeren. Shift of ← gaat terug; W sluit het venster; Q sluit de app af; Esc annuleert.",
        musicBlockSection: "Mediatoetsen",
        musicBlockTitle: "Muziek niet vanzelf laten openen",
        musicBlockCaption: "De Muziek-app opent niet meer wanneer je op de mediatoetsen drukt. Je kunt hem nog steeds zelf openen.",
        musicBlockReplacementLabel: "In plaats daarvan openen",
        musicBlockReplacementNone: "Geen",
        musicBlockChooseApp: "App kiezen…",
        cleanerName: "Opschoner",
        cleanerIntroTitle: "Ruim je Mac op",
        cleanerIntroCaption: "Zoekt naar resten van gedeïnstalleerde apps, caches, logbestanden en de Prullenmand. Je bekijkt alles eerst zelf en verwijderde items gaan naar de Prullenmand.",
        cleanerScan: "Scannen",
        cleanerScanning: "Wordt gescand…",
        cleanerCleaning: "Wordt opgeruimd…",
        cleanerCatLeftovers: "Resten van gedeïnstalleerde apps",
        cleanerCatLoginItems: "Verweesde opstartitems",
        cleanerCatCaches: "Caches",
        cleanerCatLogs: "Logbestanden",
        cleanerCatDeveloper: "Ontwikkelaarsrommel",
        cleanerCatTrash: "Prullenmand",
        cleanerLeftoversNote: "Gevonden door analyse en niet aangevinkt. Controleer het pad voordat je aanvinkt.",
        cleanerLoginItemsNote: "Het item onder Aanmelditems verdwijnt na het herstarten van de Mac.",
        cleanerTrashNote: "De Prullenmand legen is definitief.",
        cleanerCatDeviceBackups: "iPhone-back-ups",
        cleanerDeviceBackupsCaption: "Oude iPhone- en iPad-back-ups nemen een groot deel in van de opslag die macOS Overig noemt. Verwijder alleen de back-ups die je niet meer nodig hebt; een nieuwe wordt gemaakt zodra je het apparaat weer aansluit.",
        cleanerNothingFound: "Niets om op te ruimen. Je Mac is netjes.",
        cleanerClean: "Opruimen",
        cleanerDoneNote: "Items zijn naar de Prullenmand verplaatst en kunnen daar worden teruggehaald.",
        cleanerAgain: "Opnieuw scannen",
        cleanerRevealInFinder: "Tonen in Finder",
        cleanerPanelCaption: "App-resten, caches en logbestanden",
        cleanerSafeSection: "Veilig opruimen",
        cleanerOptionalSection: "Optioneel, eerst bekijken",
        cleanerCatOtherCaches: "Overige caches",
        cleanerCachesCaption: "Tijdelijke bestanden die apps zelf opnieuw aanmaken.",
        cleanerLogsCaption: "Oude diagnostische logbestanden.",
        cleanerDeveloperCaption: "Bouw- en simulatorresten van Xcode.",
        cleanerLoginItemsCaption: "Opstartitems achtergelaten door apps die niet meer bestaan.",
        cleanerLeftoversCaption: "Bestanden achtergelaten door apps die je hebt gedeïnstalleerd.",
        cleanerOtherCachesCaption: "Veilig om te verwijderen, er gaat niets stuk. Apps kunnen één keer trager opstarten en gedownloade inhoud, zoals offline muziek, wordt opnieuw gedownload.",
        cleanerCleanSizeFormat: "%@ opruimen",
        cleanerScheduleTitle: "Automatisch opruimen",
        cleanerScheduleOff: "Uit",
        cleanerScheduleDaily: "Dagelijks",
        cleanerScheduleWeekly: "Wekelijks",
        cleanerScheduleCaption: "Ruimt vanzelf alleen het veilige deel op, op het gekozen tijdstip, en stuurt alles naar de Prullenmand.",
        cleanerScheduleLastFormat: "De laatste automatische opruiming maakte %@ vrij.",
        cleanerAutoNotificationFormat: "%@ vrijgemaakt en naar de Prullenmand gestuurd.",
        cleanerScheduleNextFormat: "Volgende opruiming %@.",
        cleanerScheduleRanFormat: "Laatste automatische opruiming %@.",
        cleanerScheduleNotifyToggle: "Melden wanneer klaar",
        cleanerNotifDenied: "Meldingen van Vorssaint staan uit in het systeem.",
        cleanerNotifOpenSettings: "Meldingsinstellingen openen…",
        launchAtLoginNeedsApplications: "De app draait vanaf een plek die niet bij aanmelden kan openen. Sleep Vorssaint naar de map Programma's, open het vandaar en schakel dit weer in.",
        launchAtLoginNeedsApproval: "Het aanmeldobject is geregistreerd, maar staat nog uit in Systeeminstellingen. Open Systeeminstellingen › Algemeen › Aanmelditems en extensies en schakel Vorssaint in onder Openen bij aanmelden.",
        ocrRemoveLineBreaksToggle: "Regeleinden verwijderen",
        ocrRemoveLineBreaksCaption: "Verwijdert regeleinden zodat gekopieerde tekst als één alinea wordt geplakt.",
        ocrQRToggle: "QR-codes lezen",
        ocrQRCaption: "Als het gebied een QR-code bevat, wordt de inhoud getoond om te kopiëren of te openen.",
        ocrQRCopied: "QR-code gekopieerd",
        qrResultTitle: "QR-code",
        qrResultCopy: "Kopiëren",
        qrResultOpen: "Link openen",
        highlightsTitle: "Nieuw in deze update",
        highlightsTitleClipboardRedesign: "Vernieuwd klembord",
        highlightsCaptionDockPreview: "Dock Preview werkt nu ook met Dock-vergroting ingeschakeld",
        highlightsCaptionScreenshot: "Het schermafbeelding-hulpmiddel heeft nu een pixelloep en QR-code-herkenning",
        highlightsCaptionSnippetLibrary: "Een doorzoekbaar fragmentenmenu typt elk fragment direct bij je cursor",
        highlightsCaptionCapturePalette: "Eén sneltoets opent nu een zwevend palet voor schermafbeeldingen, opnames, schermtekst en kleuren, met bediening dichtbij.",
        highlightsCaptionClipboardRedesign: "De klembordgeschiedenis opent nu als een compact palet met overzichtelijke rijen en een voorvertoning op aanvraag om het volledige item te lezen of te bewerken.",
        highlightsConfigure: "Instellen",
        highlightsTry: "Proberen",
        highlightsSeeAll: "Alle wijzigingen bekijken",
        switcherCurrentSpaceOnly: "Alleen huidig bureaublad tonen",
        switcherCurrentSpaceOnlyCaption: "Toont alleen vensters van het bureaublad waar je op bent. Het kiezen van een venster brengt je nooit naar een ander bureaublad.",
        shelfFileMissing: "Het bestand bestaat niet meer",
        previewSizeSmall: "Klein",
        mixerSoundEffectsOutputTitle: "Systeemgeluiden",
        mixerSoundEffectsOutputTooltip: "Kies waar waarschuwingen en geluidseffecten worden afgespeeld",
        monitorOpenActivityMonitor: "Activiteitenmonitor openen",
        dockClickHide: "Klik op Dock-symbool om de app te verbergen",
        dockClickHideCaption: "De actieve app wordt verborgen wanneer je op het Dock-symbool klikt. Klik nogmaals om hem terug te halen.",
        monitorMemoryMetricLabel: "Geheugen meten als",
        memoryMetricUsed: "Gebruikt geheugen",
        memoryMetricApp: "App-geheugen",
        keepAwakeRightClickToggle: "Rechtsklik op het menubalksymbool om Wakker houden te schakelen",
        keepAwakeRightClickToggleCaption: "Vervangt het contextmenu bij rechtsklikken.",
        urlCleanerRulesTitle: "Opschoonregels",
        urlCleanerRulesCaption: "Een website voegt deze parameters toe aan zijn eigen deellinks om te volgen waar de link vandaan kwam. Ingeschakeld wordt een naam verwijderd bij het opschonen van een link; uitgeschakeld blijft die staan. Namen die je zelf toevoegt, kun je verwijderen.",
        urlCleanerRulesCoverageCaption: "De lijst dekt de verschillende deelmethoden van een website — de webpagina, de app, een liveruimte — daarom is hij lang; een echte link bevat meestal maar twee tot vier daarvan.",
        urlCleanerRulesAllSites: "Alle websites",
        urlCleanerRulesCountSingular: "1 parameter",
        urlCleanerRulesCountPluralFormat: "%d parameters",
        urlCleanerRulesAddSite: "Website toevoegen",
        urlCleanerRulesParameterPlaceholder: "Parameternaam",
        urlCleanerRulesMatchCaption: "Zet de naam links van het =-teken, zoals utm_source. Een overeenkomende naam haalt precies die ene parameter uit de link en laat de rest ongewijzigd.",
        urlCleanerRulesAddButton: "Toevoegen",
        urlCleanerRulesRemoveButton: "Naam verwijderen",
        urlCleanerRulesRemoveSiteButton: "Alle regels voor deze website uitschakelen",
        urlCleanerRemovedFormat: "Verwijderd %@",
        switcherSearchPin: "Zoeken vastzetten met S",
        switcherSearchPinCaption: "S start een zoekopdracht en zet de omschakelaar vast open, zodat typen geen speciale tekens meer oplevert wanneer je sneltoets ⌥ gebruikt, en een zoekopdracht die met Q of W begint niet meer per ongeluk het venster sluit of de app afsluit.",
        invertVerticalScroll: "Verticaal scrollen omkeren",
        invertHorizontalScroll: "Horizontaal scrollen omkeren",
        switcherShowShortcutHints: "Sneltoetshints tonen",
        switcherShowShortcutHintsCaption: "Toont de app- en venstersneltoetsen onder de symbolen.",
        uninstallerHomebrewPackageFormat: "%@ wordt ook uit Homebrew verwijderd.",
        shelfEdgeToggle: "Openen bij een schermrand",
        shelfEdgeCaption: "Sleep een bestand richting de schermrand om de Shelf even te laten gluren. Zet het daar neer, of trek terug en de Shelf verdwijnt weer.",
        focusFollowsMouseName: "Focus volgt muis",
        focusFollowsMouseCaption: "Geeft focus aan en brengt het venster onder de wijzer naar voren na een korte pauze.",
        focusFollowsMouseDelay: "Zweefvertraging",
        switcherMinimizedPlacementLabel: "Geminimaliseerde vensters",
        switcherMinimizedPlacementNormal: "Normale volgorde",
        switcherMinimizedPlacementEnd: "Achteraan plaatsen",
        switcherMinimizedPlacementHidden: "Verbergen",
        switcherShowFullscreenWindows: "Volledige-schermvensters tonen",
        switcherScreenPlacementLabel: "Tonen op",
        switcherScreenPlacementPointer: "Scherm met de wijzer",
        switcherScreenPlacementMenuBar: "Scherm met de menubalk",
        switcherScreenPlacementActiveWindow: "Scherm met het actieve venster",
        switcherScreenPlacementCaption: "Op welk beeldscherm de omschakelaar opent wanneer er meer dan één is aangesloten.",
        smoothScrollResponseLabel: "Reactie",
        mouseAccelerationName: "Muisversnelling uitschakelen",
        mouseAccelerationCaption: "Verwijdert wijzerversnelling voor aangesloten muizen. Je vorige instelling keert terug zodra dit wordt uitgeschakeld of Vorssaint afsluit."
    )
}
