// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Українська — повний переклад інтерфейсу.
extension Strings {
    static let uk = Strings(
        statusIdleTooltip: "Vorssaint: Mac може засинати",
        statusActiveUntil: "Vorssaint: Mac не засинатиме до",
        statusActiveIndefinite: "Vorssaint: Mac не засинатиме, доки не вимкнете",
        menuEnableAwake: "Увімкнути режим без сну",
        menuDisableAwake: "Вимкнути режим без сну",
        menuActivateFor: "Увімкнути на…",
        menuSettings: "Налаштування…",
        menuAbout: "Про Vorssaint",
        menuQuit: "Вийти з Vorssaint",
        menuHide: "Сховати Vorssaint",
        menuHideOthers: "Сховати інші",
        menuShowAll: "Показати всі",
        menuEdit: "Редагування",
        menuUndo: "Скасувати",
        menuRedo: "Повторити",
        menuCut: "Вирізати",
        menuCopy: "Скопіювати",
        menuPaste: "Вставити",
        menuSelectAll: "Вибрати все",
        menuWindow: "Вікно",
        menuMinimize: "Згорнути",
        menuZoom: "Змінити масштаб",
        menuClose: "Закрити",
        minutes15: "15 хвилин",
        minutes30: "30 хвилин",
        hour1: "1 година",
        hours2: "2 години",
        hours4: "4 години",
        hours8: "8 годин",
        indefinitely: "Доки не вимкнете",
        indefinite: "Доки не вимкнете",
        panelSettings: "Налаштування",
        panelQuit: "Вийти",
        panelHotkeyHint: "Клавіатурне скорочення перемикає",
        keepAwakeTitle: "Не давати Mac заснути",
        keepAwakeEndsIn: "Завершиться через",
        keepAwakeUntilDisabled: "Активно, поки ви не вимкнете",
        keepAwakeNormalRules: "Mac працює зі звичайними налаштуваннями енергозбереження",
        keepAwakeOptions: "Параметри",
        keepAwakeMouseJiggle: "Злегка рухати вказівник",
        keepAwakeMouseJiggleCaption: "Під час сеансу злегка рухає вказівник із вибраною періодичністю.",
        keepAwakeMouseJiggleInterval: "Інтервал",
        keepAwakeActiveIconLabel: "Активний значок",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Кава",
        keepAwakeActiveIconEye: "Око",
        keepAwakeActiveIconMoon: "Місяць",
        keepAwakeActiveIconLight: "Лампочка",
        keepAwakeIconTintLabel: "Колір активного значка",
        keepAwakeIconTintOrange: "Помаранчевий",
        keepAwakeIconTintGreen: "Зелений",
        keepAwakeIconTintBlue: "Синій",
        keepAwakeIconTintPurple: "Фіолетовий",
        keepAwakeIconTintPink: "Рожевий",
        keepAwakeIconTintNone: "Без кольору",
        durationLabel: "Тривалість",
        clamshellTitle: "Не присипляти Mac із закритою кришкою",
        clamshellOnCaption: "Режим сну повністю вимкнено. Стежте за зарядом акумулятора",
        clamshellNeedsSession: "Застосовується, коли активний режим «Не давати заснути»",
        clamshellReady: "Готово. Перемикається без пароля",
        clamshellNeedsPassword: "Один раз попросить пароль адміністратора",
        systemSection: "Система",
        temperatures: "Температури",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Акумулятор",
        usageSection: "Навантаження",
        memorySection: "Пам'ять",
        memoryPressure: "Тиск",
        memorySwapUsed: "Підкачка",
        memoryCompressed: "Стиснута",
        memoryCachedFiles: "Кешовані файли",
        pressureNormal: "Норма",
        pressureWarning: "Обережно",
        pressureCritical: "Критично",
        monitorUnavailable: "Датчики недоступні на цьому Mac",
        energyAppsTitle: "Програми зі значним енергоспоживанням",
        energyAppsIdle: "Зараз немає значного енергоспоживання",
        notifySessionEndedTitle: "Сеанс завершено",
        notifySessionEndedBody: "Час вийшов. Mac знову засинатиме як зазвичай.",
        notifyBatteryTitle: "Vorssaint вимкнено",
        notifyBatteryBody: "Низький заряд. Звичайний сон відновлено, щоб зберегти заряд акумулятора.",
        adminPromptClamshellOn: "Vorssaint потрібен ваш пароль, щоб Mac продовжував працювати з закритою кришкою.",
        adminPromptClamshellOff: "Vorssaint потрібен ваш пароль, щоб відновити звичайний режим сну Mac.",
        adminPromptRecover: "Vorssaint завершився, поки сон Mac був вимкнений. Введіть пароль, щоб відновити звичайний режим сну.",
        adminPromptUpdate: "Vorssaint потрібен ваш пароль, щоб встановити оновлення.",
        adminPromptSudoersInstall: "Vorssaint створить обмежене правило (лише pmset disablesleep), щоб перемикати режим закритої кришки без запиту пароля. Пароль потрібен лише цього разу.",
        adminPromptSudoersRemove: "Vorssaint видалить правило закритої кришки без пароля.",
        settingsTitle: "Налаштування Vorssaint",
        tabGeneral: "Загальне",
        tabEnergy: "Живлення",
        tabMouse: "Миша та трекпад",
        tabSwitcher: "Перемикач",
        tabAdvanced: "Додатково",
        tabAbout: "Про програму",
        tabReleaseNotes: "Що нового",
        releaseNotesOnUpdateToggle: "Показувати зміни після оновлення",
        previewSizeLabel: "Розмір мініатюр",
        previewSizeNormal: "Норма",
        previewSizeLarge: "Великий",
        previewSizeXLarge: "Дуже великий",
        settingsGroupFeatures: "Функції",
        advancedResetSection: "Дозволи",
        advancedResetDescription: "Видаляє всі дозволи, які ви надали Vorssaint (Універсальний доступ, Запис екрана, Повний доступ до диска та інші), елемент входу і правило закритої кришки. Корисно для початку з чистого аркуша або перед видаленням. Програма залишається встановленою.",
        advancedClearButton: "Скинути всі дозволи",
        advancedCleared: "Дозволи скинуто.",
        advancedClearConfirmTitle: "Скинути всі дозволи?",
        advancedClearConfirmBody: "Функції, яким потрібні дозволи, перестануть працювати, поки ви не надасте їх знову. Налаштування зберігаються.",
        advancedUninstallSection: "Видалити",
        advancedUninstallDescription: "Робить усе вищезазначене, потім видаляє налаштування та переміщує Vorssaint у Кошик без слідів. Після завершення програма завершить роботу. Встановити знову можна будь-коли.",
        advancedUninstallButton: "Видалити Vorssaint повністю",
        advancedUninstallConfirmTitle: "Видалити Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint очистить дозволи, видалить налаштування та переміститься у Кошик, після чого закриється. Це не можна скасувати з програми, але файл залишиться в Кошику, поки ви його не очистите.",
        launchAtLogin: "Запускати при вході",
        languageLabel: "Мова",
        menuBarSection: "Рядок меню",
        showCountdown: "Показувати час, що залишився, біля значка",
        globalHotkeySection: "Глобальне поєднання",
        hotkeyToggle: "Увімкнути гарячу клавішу для «Не давати заснути»",
        hotkeyCaption: "Працює в будь-якій програмі без додаткових дозволів.",
        sessionSection: "Сеанс",
        defaultDurationLabel: "Тривалість за замовчуванням",
        keepAwakeAutoStart: "Не давати заснути при запуску Vorssaint",
        keepAwakeAutoStartCaption: "Запускає сеанс із тривалістю за замовчуванням.",
        batteryProtectionSection: "Захист акумулятора",
        batteryDisableBelow: "Вимикати, коли заряд впаде нижче",
        batteryNever: "Ніколи",
        batteryProtectionCaption: "Не дає забутому сеансу розрядити акумулятор MacBook.",
        clamshellSection: "Закрита кришка",
        configuring: "Налаштування…",
        sudoersFailed: "Не вдалося ввімкнути режим закритої кришки. Спробуйте ще раз.",
        clamshellExplanation: "«Не присипляти Mac із закритою кришкою» повністю вимикає сон, поки активний режим «Не давати заснути», і автоматично повертає звичайну поведінку, коли сеанс завершується або програма закривається. Краще використовувати при підключеному живленні.",
        scrollSection: "Прокрутка",
        invertMouseScroll: "Інвертувати прокрутку миші",
        invertMouseScrollCaption: "Змінює напрямок колеса миші на протилежний.",
        scrollTrackpadNote: "Трекпад не змінюється: природна прокрутка macOS лишається як є.",
        scrollActiveNow: "Прокрутку миші зараз інвертовано",
        mouseNavigationActiveNow: "Бокові кнопки зараз активні",
        smoothScrollName: "Плавна прокрутка",
        smoothScrollCaption: "Перетворює кожен клац колеса миші на коротке плавне ковзання. Трекпад не змінюється.",
        smoothScrollStepLabel: "Швидкість прокрутки",
        mouseNavigationSection: "Навігація",
        mouseNavigationEnable: "Використовувати бокові кнопки для Назад і Вперед",
        mouseNavigationCaption: "Перетворює кнопки миші «Назад» і «Вперед» на команди навігації у Finder, браузерах та сумісних програмах.",
        middleClickSection: "Середня кнопка",
        middleClickEnable: "Клац трьома пальцями як середня кнопка",
        middleClickEnableCaption: "Натискання трекпада трьома пальцями працює як клац колесом миші: відкриває посилання в новій вкладці, закриває вкладки та все інше, що вміє середня кнопка.",
        middleClickDragConflict: "Перетягування трьома пальцями в macOS увімкнене і використовує цей самий жест. Вимкніть його в Системних налаштуваннях у розділі Універсальний доступ, Керування вказівником, Параметри трекпада, і клац середньою кнопкою запрацює.",
        middleClickTapPicker: "Легкий торк також клацає",
        middleClickTapOff: "Вимкнено",
        middleClickTapThreeFingers: "3 пальці",
        middleClickTapFourFingers: "4 пальці",
        middleClickTapCaption: "Легкий торк такою кількістю пальців, без натискання, також викликає клац середньою кнопкою. Ковзання не враховуються. Якщо торк трьома пальцями в macOS призначено на «Пошук», вимкніть його, щоб обидва не спрацьовували разом.",
        quickToolsTab: "Швидка панель",
        quickToolShortcutToggle: "Глобальне поєднання",
        ocrName: "Скопіювати текст з екрана",
        ocrCaption: "Виділіть область екрана, і розпізнаний текст буде скопійовано, готовий до вставки.",
        ocrCopied: "Текст скопійовано",
        ocrNoText: "Текст не знайдено",
        colorPickerName: "Піпетка кольору",
        colorPickerCaption: "Візьміть колір будь-якого пікселя на екрані та скопіюйте його в обраному форматі.",
        colorPickerFormatLabel: "Формат копіювання",
        colorPickerBareHexToggle: "Копіювати без префікса #",
        colorPickerPickNow: "Взяти колір",
        micMuteName: "Вимкнути мікрофон",
        micUnmuteName: "Увімкнути мікрофон",
        micMuteCaption: "Вимикає мікрофон Mac одним клацом або поєднанням клавіш у всіх програмах.",
        micMutedHUD: "Мікрофон вимкнено",
        micUnmutedHUD: "Мікрофон знову ввімкнено",
        micMuteMenuBarToggle: "Показувати в рядку меню, поки вимкнено",
        micMuteMenuBarCaption: "Біля значка програми в рядку меню з'являється червоний перекреслений мікрофон.",
        pastePlainName: "Вставити як звичайний текст",
        pastePlainCaption: "Вставляє скопійоване без кольорів, шрифтів та форматування. Оригінал залишається в буфері обміну.",
        launcherName: "Швидка панель",
        launcherCaption: "Плаваюча панель з улюбленими інструментами, викликається поєднанням клавіш звідки завгодно.",
        launcherOpenNow: "Відкрити швидку панель",
        launcherEditHint: "Кнопка налаштування дозволяє вибирати, ховати та перетягувати інструменти.",
        launcherEmptyState: "Усі інструменти приховані. Поверніть їх кнопкою налаштування.",
        launcherAddSection: "Повернути",
        launcherKeysHint: "Стрілки для навігації, Enter відкриває, 1–9 відкривають одразу",
        switcherSection: "Перемикач програм",
        switcherEnable: "Використовувати перемикач Vorssaint",
        switcherEnableCaption: "Перемикає програми та вікна, включно зі згорнутими та кількома вікнами однієї програми.",
        switcherUsageHint: "Утримуйте клавіатурне скорочення для навігації; відпустіть, щоб активувати вікно. Shift або ← повертає назад; W закриває вікно; Q завершує програму; Esc скасовує.",
        switcherNoWindows: "Немає відкритих вікон",
        switcherIconRowMode: "Показувати %@ з великими значками",
        switcherIconRowModeCaption: "Показує по одному значку на програму, а зверху мініатюри її вікон.",
        switcherSimpleMode: "Простий перемикач програм",
        switcherSimpleModeCaption: "Показує значки програм та заголовки вікон без мініатюр та захоплення екрана перемикачем.",
        switcherShortcutHintApps: "Програми",
        switcherShortcutHintWindows: "Вікна",
        switcherWindowShortcutCaption: "Відкриває перемикач вікон програми на передньому плані. Поки відкритий перемикач програм, переходитиме між вікнами обраної програми.",
        switcherAppearanceDelay: "Затримка появи",
        switcherAppearanceDelayCaption: "Як довго потрібно утримувати клавіатурне скорочення, перш ніж з'явиться перемикач.",
        switcherMergeTabs: "Показувати один запис на програму",
        switcherMergeTabsCaption: "Зводить усі вікна програми в один запис у перемикачі замість окремого запису на кожне вікно.",
        switcherWindowlessApps: "Програми без відкритих вікон",
        switcherWindowlessAppsCaption: "Вибирає, які запущені програми без жодного вікна з'являються в перемикачі.",
        switcherWindowlessAppsOff: "Не показувати",
        switcherWindowlessAppsFinder: "Лише Finder",
        switcherWindowlessAppsAll: "Усі програми",
        switcherNoOpenWindow: "Без відкритих вікон",
        switcherOtherDesktop: "Інший робочий стіл",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Показувати вікна з Dock",
        dockPreviewEnableCaption: "Наведіть вказівник на відкриту програму в Dock, щоб побачити її вікна, потім натисніть потрібне.",
        dockPreviewBackgroundOpacity: "Фон панелі",
        dockPreviewBackgroundOpacityCaption: "Зменште, щоб бачити більше того, що знаходиться за панеллю.",
        dockPreviewOpenDelay: "Затримка відкриття",
        dockPreviewOpenDelayCaption: "Скільки вказівник має залишатися на значку, перш ніж відкриється панель.",
        dockPreviewQuitAppOnClose: "Завершувати програму кнопкою ×",
        dockPreviewQuitAppOnCloseCaption: "У Dock Preview кнопка × завершує всю програму, а не закриває лише це вікно.",
        dockClickMinimize: "Згортати клацом по Dock",
        dockClickMinimizeCaption: "Вікна активної програми згортаються при клаці по її значку в Dock. Клацніть ще раз, щоб повернути їх.",
        dockClickCycleWindows: "Клацом по Dock перемикати вікна",
        dockClickCycleWindowsCaption: "Клац по значку активної програми в Dock перемикає між її вікнами, як ⌘`.",
        dockPreviewActiveNow: "Активно в Dock",
        dockPreviewDockUnavailable: "Не вдалося прочитати елементи Dock.",
        dockPreviewAutohideBeta: "Бета. Можливі помилки.",
        dockPreviewOpenWindow: "Відкрити вікно",
        dockPreviewCloseWindow: "Закрити вікно",
        dockPreviewMinimizeWindow: "Згорнути вікно",
        dockPreviewRestoreWindow: "Відновити вікно",
        dockPreviewPinPanel: "Закріпити мініатюру",
        dockPreviewUnpinPanel: "Відкріпити мініатюру",
        dockPreviewPinned: "Закріплено",
        dockPreviewClosePanel: "Закрити мініатюру",
        dockPreviewPreviousWindow: "Попереднє вікно",
        dockPreviewNextWindow: "Наступне вікно",
        cutPasteName: "Вирізати та вставити",
        cutPasteEnable: "Вирізати та вставляти файли у Finder",
        cutPasteEnableCaption: "Використовуйте ⌘X для вирізання та ⌘V для переміщення файлів і папок у Finder.",
        cutPasteShowHUD: "Показувати плаваючу панель",
        cutPasteShowHUDCaption: "Показує плаваючий індикатор з вирізаними файлами, поки активний Finder.",
        cutPasteHowTitle: "Як використовувати",
        cutPasteStep1: "Виділіть елементи у Finder і натисніть ⌘X, щоб вирізати їх.",
        cutPasteStep2: "Відкрийте папку призначення та натисніть ⌘V, щоб перемістити їх туди.",
        cutPasteTextNote: "У текстових полях (наприклад, при перейменуванні) ⌘X та ⌘V продовжують працювати як зазвичай.",
        cutPasteActiveNow: "Готово до вирізання у Finder",
        cutPasteAutomationNote: "При першому використанні macOS попросить дозвіл на керування Finder.",
        cutReadyTitle: "Вирізати",
        cutReadyHint: "у папці призначення для переміщення",
        cutCancel: "Скасувати вирізання",
        cutDoneTitle: "Переміщено!",
        cutMovedSingular: "Переміщено 1 елемент",
        cutMovedPluralFormat: "Переміщено елементів: %d",
        cutSomeFailed: "Деякі елементи не вдалося перемістити",
        cutMovingTitle: "Переміщення…",
        cutMovingCountFormat: "%d з %d",
        autoQuitName: "Закривати разом із вікном",
        autoQuitEnable: "Закривати програму, коли закривається її останнє вікно",
        autoQuitEnableCaption: "Закриття останнього вікна програми також завершує її.",
        autoQuitActiveNow: "Зараз активно",
        autoQuitHowTitle: "Як це працює",
        autoQuitStep1: "Закрийте останнє вікно програми (⌘W або червоною кнопкою).",
        autoQuitStep2: "Програма завершиться сама. Діалоги «Зберегти зміни?» продовжують з'являтися.",
        autoQuitPredictableNote: "Програми, які зазвичай працюють без вікна, ніколи не закриваються автоматично.",
        autoQuitExceptionsTitle: "Виключення",
        autoQuitExceptionsCaption: "Програми в цьому списку залишаються відкритими навіть без вікон.",
        autoQuitExceptionsEmpty: "Без винятків",
        autoQuitAddApp: "Додати програму…",
        uninstallerName: "Деінсталятор",
        uninstallerEnableCaption: "Видаляє програму разом з її кешем, налаштуваннями, журналами та іншими залишками.",
        uninstallerStep1: "Перетягніть програму в Налаштування або виберіть зі списку.",
        uninstallerStep2: "Перегляньте знайдені файли та скільки місця вони займають.",
        uninstallerStep3: "Перемістіть у Кошик те, що хочете видалити. Нічого не видаляється безповоротно.",
        uninstallerMenuItem: "Видалити програму…",
        uninstallerDropTitle: "Перетягніть сюди програму",
        uninstallerDropSubtitle: "або виберіть одну для сканування",
        uninstallerChoose: "Вибрати програму…",
        uninstallerPickerTitle: "Виберіть програму",
        uninstallerPickerSearch: "Шукати програми",
        uninstallerPickerEmpty: "Програми не знайдені",
        uninstallerEmptyNote: "Нічого не видаляється без вашого підтвердження.",
        uninstallerFDANote: "Надайте повний доступ до диска для глибшого сканування.",
        uninstallerFDAGrant: "Надати доступ…",
        uninstallerFDAHint: "Увімкніть Vorssaint у списку. Якщо його там немає, натисніть + і виберіть Vorssaint з папки «Програми». Доступ набуде чинності лише після повторного відкриття програми.",
        uninstallerFDARelaunch: "Перезапустити зараз",
        uninstallerScanning: "Сканування файлів…",
        uninstallerRemoving: "Переміщення в Кошик…",
        uninstallerFoundTitle: "знайдено",
        uninstallerSelectedFormat: "Вибрано %d з %d",
        uninstallerRemove: "Перемістити в Кошик",
        uninstallerCancel: "Скасувати",
        uninstallerDoneTitle: "Готово!",
        uninstallerFreedFormat: "Звільнено %@",
        uninstallerSomeFailed: "Деякі елементи не вдалося перемістити в Кошик.",
        uninstallerFailedNeedsFDA: "Дані програм у пісочниці можна перемістити лише з повним доступом до диска. Пароль адміністратора його не замінює.",
        uninstallerFailedMoreFormat: "і ще %d",
        uninstallerAnother: "Видалити іншу",
        uninstallerCatApp: "Програма",
        uninstallerCatSupport: "Підтримка",
        uninstallerCatCaches: "Кеші",
        uninstallerCatPreferences: "Налаштування",
        uninstallerCatContainers: "Контейнери",
        uninstallerCatLogs: "Журнали",
        uninstallerCatState: "Збережений стан",
        uninstallerCatOther: "Інше",
        urlCleanerName: "Очищення URL",
        urlCleanerEnable: "Очищати URL при копіюванні",
        urlCleanerEnableCaption: "Видаляє параметри відстеження з посилання в момент потрапляння в буфер обміну.",
        urlCleanerActiveNow: "Зараз активно",
        urlCleanerManualTitle: "Очистити зараз",
        urlCleanerInputPlaceholder: "Вставте URL",
        urlCleanerOutputPlaceholder: "Тут з'явиться очищений URL",
        urlCleanerCleanButton: "Очистити",
        urlCleanerPasteButton: "Вставити",
        urlCleanerCopyButton: "Скопіювати",
        urlCleanerClearButton: "Очистити поле",
        urlCleanerNoURL: "Вставте дійсну URL-адресу.",
        urlCleanerNoChange: "Нема чого очищати.",
        urlCleanerCleaned: "URL очищено.",
        urlCleanerCopied: "Скопійовано.",
        urlCleanerLocalNote: "Локально. Без мережі.",
        homebrewName: "Homebrew",
        homebrewEnableCaption: "Пошук, встановлення та видалення formulae і casks.",
        homebrewMissingTitle: "Homebrew не знайдено",
        homebrewMissingBody: "Vorssaint може відкрити Термінал з офіційним інсталятором Homebrew. Термінал покаже кроки та за потреби попросить ваш пароль.",
        homebrewInstallHomebrew: "Встановити Homebrew",
        homebrewInstallHomebrewCaption: "Коли Термінал завершить, поверніться сюди та натисніть «Оновити».",
        homebrewInstallHomebrewOpened: "Інсталятор відкрито у Терміналі.",
        homebrewShellSetupTitle: "Завершити налаштування Термінала",
        homebrewShellSetupBody: "Homebrew встановлено, але Термінал може ще не знаходити команду brew. Vorssaint може відкрити Термінал з командою налаштування.",
        homebrewShellSetupButton: "Налаштувати Термінал",
        homebrewShellSetupOpened: "Команду відкрито у Терміналі. Потім поверніться сюди та натисніть «Оновити».",
        homebrewRefresh: "Оновити",
        homebrewCheckPackages: "Перевірити пакети",
        homebrewTrustTitle: "Tap ще не довірений",
        homebrewTrustCaption: "Homebrew тепер просить підтвердження перед використанням сторонніх tap. Довіряйте %@, щоб продовжити.",
        homebrewTrustButton: "Довіряти та продовжити",
        homebrewSearchPlaceholder: "Шукати пакети",
        homebrewKeyboardHint: "Space або Return закриває системну панель macOS. Використовуйте кнопку пошуку.",
        homebrewSearchButton: "Шукати",
        homebrewSearchResults: "Результати",
        homebrewInstalled: "Встановлено",
        homebrewAll: "Усі",
        homebrewFormulas: "Formulae",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Пакети не знайдені",
        homebrewNoSelection: "Виберіть встановлений пакет або знайдіть новий.",
        homebrewDetailsTitle: "Деталі пакета",
        homebrewInstall: "Встановити",
        homebrewUninstall: "Видалити",
        homebrewUpgrade: "Оновити",
        homebrewUpgradeAll: "Оновити все",
        homebrewUpdateHomebrew: "Оновити Homebrew",
        homebrewAllPackages: "пакети",
        homebrewOpenTerminal: "Відкрити Термінал",
        homebrewCancelOperation: "Скасувати",
        homebrewClearLog: "Очистити журнал",
        homebrewLogTitle: "Журнал",
        homebrewVersion: "Версія",
        homebrewDescription: "Тип",
        homebrewHomepage: "Відкрити сайт",
        homebrewPopularity: "Популярність",
        homebrewPopularityFormat: "%@ встановлень за %@ днів",
        homebrewInstalledBadge: "Встановлено",
        homebrewNotInstalledBadge: "Не встановлено",
        homebrewUpdates: "Оновлення",
        homebrewUpdateAvailableBadge: "Доступне оновлення",
        homebrewLatestVersion: "Найновіша",
        homebrewConfirmInstallTitle: "Встановити через Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew завантажить та встановить %@. Залежності також можуть бути встановлені.",
        homebrewConfirmUninstallTitle: "Видалити через Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew видалить %@. Конфігураційні файли можуть залишитися в системі.",
        homebrewConfirmUpgradeTitle: "Оновити через Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew завантажить та застосує останню версію %@. Залежності також можуть бути оновлені.",
        homebrewConfirmUpgradeAllTitle: "Оновити все через Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew завантажить та застосує останні версії пакетів, для яких доступні оновлення. Залежності також можуть бути оновлені.",
        homebrewConfirmUpdateHomebrewTitle: "Оновити Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew отримає свіжу інформацію та перезавантажить ваші пакети.",
        homebrewTerminalFallback: "Ця операція потребує Термінала для запиту пароля адміністратора. Vorssaint не перехоплює паролі.",
        homebrewLoading: "Завантаження…",
        homebrewSearchEmpty: "Немає результатів",
        homebrewOperationInstallFormat: "Встановлення %@",
        homebrewOperationUninstallFormat: "Видалення %@",
        homebrewOperationUpgradeFormat: "Оновлення %@",
        homebrewOperationUpgradeAll: "Оновлення пакетів",
        homebrewOperationUpdateHomebrew: "Оновлення Homebrew",
        homebrewOperationInstalledFormat: "%@ встановлено.",
        homebrewOperationUninstalledFormat: "%@ видалено.",
        homebrewOperationUpgradedFormat: "%@ оновлено.",
        homebrewOperationUpgradedAll: "Пакети оновлено.",
        homebrewOperationUpdatedHomebrew: "Homebrew оновлено.",
        homebrewOperationFailedFormat: "Не вдалося завершити %@.",
        homebrewOperationCancelled: "Операцію скасовано.",
        homebrewOperationPreparing: "Підготовка...",
        homebrewOperationDownloading: "Завантаження файлів...",
        homebrewOperationInstalling: "Встановлення файлів...",
        homebrewOperationUninstalling: "Видалення файлів...",
        homebrewOperationUpgrading: "Оновлення файлів...",
        homebrewOperationFinalizing: "Завершення...",
        homebrewOperationRefreshing: "Оновлення списку...",
        homebrewOperationTerminal: "Продовжте у Терміналі.",
        homebrewOperationElapsedFormat: "Минуло %@",
        homebrewOperationShowDetails: "Показати деталі",
        homebrewOperationHideDetails: "Сховати деталі",
        homebrewOperationTechnicalLog: "Технічні деталі",
        homebrewOperationProgressUnknown: "Homebrew ще не повідомив відсоток виконання.",
        mediaName: "Медіа",
        mediaEnableCaption: "Стискайте відео, конвертуйте та обробляйте зображення, створюйте GIF та видобувайте текст локально.",
        mediaLocalNote: "Локально. Без мережі.",
        mediaToolVideo: "Відео",
        mediaToolGIF: "GIF",
        mediaToolImage: "Зображення",
        mediaToolText: "Текст",
        mediaSelectFile: "Вибрати файл",
        mediaDropHint: "Перетягніть файл сюди або натисніть, щоб вибрати.",
        mediaOutput: "Папка призначення",
        mediaOutputAutomatic: "Автоматично",
        mediaChooseOutput: "Папка призначення",
        mediaStartVideo: "Стиснути відео",
        mediaStartGIF: "Створити GIF",
        mediaStartImage: "Обробити зображення",
        mediaStartConvertPDF: "Конвертувати в PDF",
        mediaStartText: "Видобути текст",
        mediaCancel: "Скасувати",
        mediaStartTime: "Початок",
        mediaEndTime: "Кінець",
        mediaQuality: "Стиснення",
        mediaCompressionLow: "Низьке",
        mediaCompressionMedium: "Середнє",
        mediaCompressionHigh: "Високе",
        mediaMaxSize: "Розмір",
        mediaSizingResolution: "Роздільна здатність",
        mediaSizingFileSize: "Розмір файлу",
        mediaTargetSize: "Цільовий розмір",
        mediaTargetSizeHint: "Роздільна здатність підлаштовується, щоб не перевищити ліміт.",
        mediaErrorTargetTooSmall: "Цільовий розмір замалий для цього кліпу. Обріжте його або збільште ліміт.",
        mediaMegabytesSuffix: " МБ",
        mediaWidth: "Ширина",
        mediaFPS: "FPS",
        mediaKeepAudio: "Зберегти звук",
        mediaCodec: "Кодек",
        mediaFormat: "Формат",
        mediaStripMetadata: "Видалити метадані",
        mediaLoopGIF: "Зациклити GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Точно",
        mediaOCRFast: "Швидко",
        mediaLanguageCorrection: "Мовна корекція",
        mediaTextOutputNote: "Видобутий текст можна скопіювати та зберегти як TXT.",
        mediaRunning: "Обробка",
        mediaCompleted: "Готово",
        mediaCancelled: "Скасовано.",
        mediaOpenInFinder: "Показати",
        mediaCopyText: "Скопіювати текст",
        mediaRunAgain: "Запустити знову",
        mediaEmptyText: "Текст не знайдено.",
        mediaResultSavedFormat: "Збережено як %@",
        mediaResultSizeFormat: "%@ у %@",
        mediaResultGrewCaption: "Конвертований файл вийшов більшим за оригінал.",
        mediaErrorNoFile: "Спочатку виберіть файл.",
        mediaErrorNoVideo: "У цього файлу немає відеодоріжки.",
        mediaErrorSameOutput: "Виберіть папку призначення, відмінну від вихідного файлу.",
        mediaErrorUnsupported: "Формат не підтримується macOS.",
        shelfName: "Полиця",
        shelfEnable: "Тимчасова область для перетягування файлів",
        shelfEnableCaption: "Плаваюче місце, куди можна зібрати файли, зображення та текст, а потім перетягнути їх куди завгодно.",
        shelfHowTitle: "Як використовувати",
        shelfStep1: "Відкрийте її гарячою клавішею або швидко порухавши мишею під час перетягування.",
        shelfStep2: "Кидайте на неї файли, зображення, посилання або текст, щоб тимчасово зберегти.",
        shelfStep3: "Перетягніть кожен елемент назад у будь-яку програму, коли він потрібен.",
        shelfShakeToggle: "Відкривати потряхуванням миші під час перетягування",
        shelfShakeCaption: "Швидко порухайте вказівником, утримуючи об'єкт, щоб викликати полицю біля курсора.",
        shelfDropZoneToggle: "Тримати перетягнуті файли в рядку меню",
        shelfDropZoneCaption: "Поки ви перетягуєте файл, полиця з'являється під значком у рядку меню. Те, що ви відпустите, залишається там, у кнопці, яку можна згорнути та відкрити одним клацом, і яка зникає, коли полиця порожня.",
        shelfDropZoneLabel: "Відпустіть тут",
        shelfCollapse: "Згорнути",
        shelfBehaviorTitle: "Після використання",
        shelfCloseAfterDrop: "Закривати після перенесення в іншу програму",
        shelfCloseAfterDropCaption: "Закриває полицю, коли програма-призначення приймає елементи. Кнопка закріплення на панелі тримає її відкритою.",
        shelfRemoveAfterDrop: "Видаляти елементи після перенесення",
        shelfRemoveAfterDropCaption: "Елементи, прийняті іншою програмою, залишають полицю. Вимкніть, щоб зберегти копію.",
        shelfExclusionsTitle: "Автоматичні винятки",
        shelfExclusionsEmpty: "Програми не додані.",
        shelfExclusionsCaption: "Потрушування та зона в рядку меню не спрацьовують для перетягувань із цих програм. Клавіатурні скорочення та «Відкрити зараз» продовжують працювати.",
        shelfPin: "Тримати відкритою",
        shelfUnpin: "Дозволити закриття після використання",
        extraBrightnessName: "Додаткова яскравість",
        extraBrightnessCaption: "Використовує запас HDR дисплея, щоб перевищити максимальну яскравість. Споживає більше заряду акумулятора, і Mac може нагріватися.",
        extraBrightnessLevelLabel: "Інтенсивність",
        extraBrightnessUnsupported: "Доступно лише на XDR-дисплеях, наприклад у MacBook Pro 14 та 16 дюймів.",
        shelfHotkeyLabel: "Клавіатурне скорочення",
        shelfOpenNow: "Відкрити зараз",
        shelfNoPermission: "Дозволів не потрібно.",
        shelfMenuItem: "Відкрити полицю",
        shelfTitle: "Полиця",
        shelfEmpty: "Перетягніть елементи сюди",
        shelfClearAll: "Очистити все",
        shelfRemoveSelected: "Видалити вибране",
        shelfSelectedFormat: "Вибрано: %d",
        shelfHint: "Клацніть для вибору. Перетягніть для використання або клацніть правою для інших дій.",
        shelfItemImage: "Зображення",
        shelfTooltipItemsFormat: "%d елементів",
        shelfTooltipImageSingular: "%d зображення",
        shelfTooltipImagePlural: "%d зображень",
        shelfTooltipFileSingular: "%d файл",
        shelfTooltipFilePlural: "%d файлів",
        shelfTooltipNoteSingular: "%d нотатка",
        shelfTooltipNotePlural: "%d нотаток",
        shelfTooltipLinkSingular: "%d посилання",
        shelfTooltipLinkPlural: "%d посилань",
        shelfActionOpen: "Відкрити",
        shelfActionOpenWith: "Відкрити з допомогою",
        shelfActionAirDrop: "Поділитися через AirDrop",
        breakdownMeasuring: "Вимірювання…",
        mixerSection: "Мікшер гучності",
        mixerEmpty: "Програми, що відтворюють звук, з'являться тут",
        mixerUnavailable: "Доступно в macOS 14.4 та новіших",
        mixerPermissionBody: "Для регулювання гучності окремих програм дозвольте «Запис екрана та системного звуку» у Системних налаштуваннях. Звук ніколи не записується.",
        mixerResetTooltip: "Скинути на 100%",
        mixerOutputDefault: "За замовчуванням",
        mixerOutputCurrent: "поточний",
        mixerOutputUnavailable: "Пристрій виведення недоступний",
        mixerOutputFallback: "Використовується вихід за замовчуванням, поки цей пристрій не повернеться.",
        mixerBypassedCaption: "Ця програма сама керує своїм звуком.",
        mixerOutputTooltip: "Вибрати пристрій виведення",
        mixerSystemOutputTitle: "Пристрій виведення",
        mixerSystemOutputNoDevices: "Пристроїв виведення не знайдено",
        mixerSystemOutputTooltip: "Вибрати системний пристрій виведення",
        mixerSystemOutputErrorFormat: "Не вдалося перемкнути: %@",
        mixerLowerOnHeadphonesDisconnect: "Знижувати гучність при від'єднанні навушників",
        mixerLowerOnHeadphonesDisconnectCaption: "Змінює гучність виходу при від'єднанні дротових або Bluetooth-навушників.",
        mixerHeadphonesDisconnectVolume: "Гучність після від'єднання",
        preciseVolumeRollerEnable: "Використовувати точніші кроки гучності",
        preciseVolumeRollerCaption: "Перетворює колесики та клавіші гучності на менші системні кроки.",
        preciseVolumeRollerTapFailed: "Не вдалося відстежувати клавіші гучності.",
        soundOutputSwitcherTitle: "Перемикач виходу",
        soundOutputSwitcherEnable: "Перемикати виходи гарячою клавішею",
        soundOutputSwitcherCaption: "Виберіть виходи та використовуйте клавіатурне скорочення, щоб перейти до наступного доступного.",
        soundOutputSwitcherDevices: "Пристрої в циклі перемикання",
        soundOutputSwitcherNoAvailableSelection: "Виберіть хоча б один доступний пристрій виведення.",
        mixerInputTitle: "Мікрофон",
        mixerInputNoDevices: "Мікрофони не знайдені",
        mixerInputUnavailable: "Мікрофон недоступний",
        mixerInputFallback: "Використовується значення за замовчуванням, поки цей мікрофон не повернеться.",
        mixerInputTooltip: "Вибрати мікрофон",
        mixerInputErrorFormat: "Не вдалося перемкнути: %@",
        mixerVisibleApps: "Програми в списку",
        mixerAllShown: "Усі",
        mixerHiddenCountLabel: "Приховано",
        mixerHideFromList: "Сховати зі списку",
        updatesSection: "Оновлення",
        autoCheckToggle: "Перевіряти оновлення автоматично",
        includeBetaUpdatesToggle: "Отримувати бета-версії",
        includeBetaUpdatesCaption: "Бета-версії містять функції в розробці та можуть містити помилки або незавершену поведінку.",
        betaBadgeLabel: "Бета",
        checkNowButton: "Перевірити зараз",
        updateChecking: "Перевірка…",
        updateUpToDate: "У вас остання версія.",
        updateAvailablePrefix: "Доступне оновлення:",
        updateInstallButton: "Завантажити та встановити",
        updateDownloading: "Завантаження оновлення…",
        updateInstalling: "Встановлення та перезапуск…",
        updateFailedPrefix: "Не вдалося перевірити:",
        updateLastChecked: "Найновіша перевірка:",
        updateNotifyTitle: "Оновлення Vorssaint",
        updateInstallFailedBody: "Оновлення завантажено, але застосувати не вдалося. Завантажте останню версію зі сторінки релізів на GitHub та перетягніть програму поверх поточної.",
        updateNeedsApplicationsTitle: "Перемістіть Vorssaint у папку «Програми»",
        updateNeedsApplicationsBody: "Програму запущено з місця, яке не можна оновити, наприклад з образу диска або тимчасового системного розташування. Перетягніть Vorssaint у папку «Програми», відкрийте його звідти та спробуйте знову.",
        menuCheckUpdates: "Перевірити оновлення…",
        permissionRequired: "Потрібен дозвіл",
        permissionAccessibility: "Універсальний доступ",
        permissionScreenRecording: "Запис екрана",
        permissionGranted: "Надано",
        permissionMissing: "Не надано",
        permissionOpenSettings: "Відкрити Системні налаштування…",
        permissionRequest: "Надати доступ",
        permissionRestartNote: "macOS може попросити закрити й знову відкрити програму після надання дозволу.",
        aboutDescription: "Набір корисних інструментів для вашого Mac.\nЖивлення, системний монітор, прокрутка та перемикач вікон прямо в рядку меню.",
        versionPrefix: "Версія",
        reviewIntro: "Показати вступ знову",
        reviewHighlights: "Показати огляд новинок знову",
        viewOnGitHub: "Відкрити на GitHub",
        obContinue: "Далі",
        obBack: "Назад",
        obSkipStep: "Пропустити крок",
        obStart: "Відкрити Vorssaint",
        obStepWelcomeTitle: "Вітаємо у Vorssaint",
        obStepWelcomeBody: "Непомітна утиліта в рядку меню, яка робить повсякденну роботу в macOS зручнішою.",
        obWelcomeBullet1Title: "Живлення під контролем",
        obWelcomeBullet1Body: "Не давайте Mac заснути стільки, скільки потрібно, навіть із закритою кришкою.",
        obWelcomeBullet2Title: "Зрозуміла картина системи",
        obWelcomeBullet2Body: "Температури CPU, GPU та акумулятора, навантаження обладнання і тиск пам'яті в реальному часі.",
        obWelcomeBullet3Title: "Миша та вікна по-вашому",
        obWelcomeBullet3Body: "Інвертована прокрутка миші та перемикач вікон з мініатюрами.",
        obLanguageLabel: "Мова",
        obStepAccessibilityTitle: "Універсальний доступ",
        obStepAccessibilityBody: "Потрібен для інвертування прокрутки миші та роботи перемикача вікон з клавіатури.",
        obAccessibilityWhy: "Програма стежить лише за колесом миші та поєднанням клавіш перемикача. Нічого не записується та нікуди не надсилається.",
        obStepRecordingTitle: "Запис екрана",
        obStepRecordingBody: "Дозволяє перемикачу показувати справжні мініатюри вікон замість одних значків.",
        obRecordingWhy: "Мініатюри створюються на льоту, залишаються в пам'яті та ніколи не залишають ваш Mac. Без цього перемикач усе одно працює, але лише зі значками.",
        obStepMonitorTitle: "Системний монітор",
        obStepMonitorBody: "Панель показує температури CPU, GPU та акумулятора, навантаження обладнання і тиск пам'яті.",
        obMonitorNoPermission: "Дозволи не потрібні. Датчики зчитуються безпосередньо з системи.",
        obStepOptionalTitle: "Необов'язкові функції",
        obStepOptionalBody: "Увімкніть те, чим хочете користуватися зараз. Усе можна змінити пізніше в Налаштуваннях.",
        obStepStatusTitle: "Перевірка",
        obStepStatusBody: "Переконайтеся, що все готово для потрібних вам функцій.",
        obStatusRecheck: "Перевірити знову",
        obStepDoneTitle: "Усе готово!",
        obStepDoneBody: "Vorssaint вже дбає про ваш Mac.",
        obDoneHint: "Шукайте чорну діру в рядку меню, у правому верхньому куті екрана.",
        obWhatsNewTitle: "Що нового в цій версії",
        obWhatsNewFallback: "В це оновлення ввійшли останні виправлення та вдосконалення.",
        obLanguageUpdateTitle: "Тепер вашою мовою",
        obLanguageUpdateBody: "Vorssaint тепер говорить кількома мовами. Виберіть ту, яку хочете використовувати; змінити її можна будь-коли в Налаштуваннях.",
        obPurposeTitle: "Що привело вас сюди?",
        obPurposeBody: "Виберіть готове налаштування або саме ті функції, якими хочете користуватися.",
        obPurposeSkip: "Функції можна додати або прибрати пізніше в Налаштуваннях.",
        tabMonitor: "Монітор",
        monitorMenuBarSection: "У рядку меню",
        monitorMenuBarCaption: "Виберіть, що показувати біля значка в рядку меню.",
        monitorCombineTemperatures: "Об'єднувати навантаження та температуру",
        monitorCombineTemperaturesCaption: "Коли увімкнені і навантаження, і температура одного елемента, показувати їх одним блоком.",
        monitorSeparateMenuBarMetrics: "Виводити метрики окремими елементами",
        monitorSeparateMenuBarMetricsCaption: "Розділяє активні блоки в рядку меню та зберігає навантаження і температуру разом, якщо увімкнене об'єднання.",
        monitorNetworkUploadFirst: "Показувати віддачу над завантаженням",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Пам'ять",
        monitorShowNetwork: "Мережа",
        monitorShowPowerLabel: "Живлення",
        monitorIntervalLabel: "Оновлювати кожні",
        monitorInterval1: "1 секунду",
        monitorInterval2: "2 секунди",
        monitorInterval5: "5 секунд",
        monitorPanelSection: "У панелі",
        panelNavigationMode: "Навігація панелі за секціями",
        panelNavigationCaption: "Показує по одному розділу за раз. Виберіть «Список», щоб переглядати все безперервною прокруткою.",
        panelFooterSections: "Секції",
        panelFooterList: "Список",
        betaBadge: "БЕТА",
        betaFeatureWarning: "Бета. Можливі помилки.",
        networkSection: "Мережа",
        networkDownload: "Завантаження",
        networkUpload: "Віддача",
        networkThisSession: "Цей сеанс",
        networkMeasuring: "Вимірювання…",
        networkApps: "Програми, що використовують мережу",
        networkAppsIdle: "Зараз немає програм, що використовують мережу",
        diskSection: "Диски",
        diskUsed: "зайнято",
        diskFree: "вільно",
        diskAvailable: "доступно",
        diskPurgeable: "очищуваний",
        diskInternal: "Внутрішній",
        diskExternal: "Зовнішній",
        diskSelect: "Вибрати диск",
        diskRead: "Читання",
        diskWrite: "Запис",
        diskSMARTStatus: "Статус",
        diskSMARTUnavailable: "SMART недоступний для цього диска",
        diskTotalRead: "Всього прочитано",
        diskTotalWritten: "Всього записано",
        diskTemperature: "Температура",
        diskHealth: "Стан",
        diskPowerCycles: "Цикли живлення",
        diskPowerOnHours: "Години роботи",
        diskUnsafeShutdowns: "Небезпечні вимкнення",
        diskMediaErrors: "Помилки носія",
        diskEject: "Вийняти",
        diskEjectAll: "Вийняти все",
        diskEjecting: "Виймання…",
        diskReadyToRemove: "Можна відключати",
        diskEjectFailed: "Не вдалося вийняти",
        diskProtectionCaption: "Виймайте перед від'єднанням.",
        diskNoExternal: "Немає зовнішніх дисків, готових до виймання.",
        diskOpenInFinder: "Відкрити",
        diskStorageSettings: "Сховище",
        diskNoDisks: "Змонтовані диски не знайдені.",
        powerSection: "Живлення",
        powerSystem: "Система",
        powerAdapter: "Адаптер",
        powerBattery: "Акумулятор",
        powerCharging: "Заряджається",
        powerOnBattery: "Від акумулятора",
        powerPluggedIn: "Підключено до живлення",
        powerUnavailable: "Метрики живлення недоступні на цьому Mac",
        powerAdapterMaxFormat: "макс. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Температура CPU",
        monitorShowGPUTemperature: "Температура GPU",
        monitorShowBatteryTemperature: "Температура акумулятора",
        monitorShowPeripheralBattery: "Акумулятор аксесуарів",
        peripheralBatteryNoDevices: "Пристрої не знайдені",
        monitorGraphsSection: "Графіки",
        monitorGraphsCaption: "Виберіть, для яких метрик показувати графік у часі.",
        updateBannerTitle: "Доступне оновлення",
        updateBannerAction: "Оновити",
        obStepMenuBarTitle: "Метрики в рядку меню",
        obStepMenuBarBody: "Виберіть, що показувати біля значка. Прев'ю вище оновлюється наживо.",
        obStepMenuBarNote: "Нове: блоки Мережа та Живлення, а також графіки в панелі. Усе це можна докладно налаштувати пізніше в Налаштування › Монітор.",
        monitorMenuBarPresetLabel: "Стиль",
        menuBarPresetReadable: "Читабельний",
        menuBarPresetDense: "Щільний",
        menuBarSpacingLabel: "Інтервал у рядку меню",
        menuBarSpacingStandard: "Стандартний",
        menuBarSpacingCompact: "Компактний",
        menuBarHideIconToggle: "Ховати значок програми, поки показані метрики",
        menuBarHideIconCaption: "Значок повертається сам, коли метрики зникають із рядка меню, а також коли є що повідомити (готове оновлення або вимкнено мікрофон).",
        monitorLabelStyleLabel: "Підписи",
        menuBarLabelStyleCompact: "Компактні",
        menuBarLabelStyleClassic: "Класичні",
        monitorMemoryStyleLabel: "Показувати пам'ять як",
        monitorMemoryPressureDot: "Точка тиску",
        memoryStyleDot: "Точка",
        memoryStylePercent: "%",
        memoryStyleBoth: "Обидва",
        systemUptime: "Працює",
        batteryCharge: "Заряд",
        powerHealth: "Стан акумулятора",
        powerCycles: "Цикли",
        speedTestRun: "Тест швидкості",
        speedTestAgain: "Перевірити знову",
        speedTestLatency: "Затримка",
        speedTestTesting: "Перевірка…",
        speedTestFailed: "Тест не вдався",
        monitorShowInPanel: "Показати в панелі",
        disclosureExpanded: "Розгорнуто",
        disclosureCollapsed: "Згорнуто",
        panelHideItem: "Сховати з панелі",
        panelShowItem: "Показати в панелі",
        panelHiddenItem: "Приховано",
        monitorItemUptime: "Час роботи",
        monitorItemNetSpeed: "Поточна швидкість",
        monitorItemNetTotals: "Підсумки сеансу",
        monitorItemNetTest: "Тест швидкості",
        monitorItemDiskUsage: "Використання диска",
        monitorItemDiskActivity: "Поточна активність",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Захист зовнішніх дисків",
        monitorItemDiskTools: "Інструменти",
        monitorPanelConfigHint: "Відкрийте блок, щоб вибрати, що він показує.",
        monitorOrderSection: "Порядок розділів",
        monitorOrderHint: "Перетягуйте, щоб змінювати порядок розділів панелі, та використовуйте око, щоб показувати або ховати кожен із них.",
        obStepPanelTitle: "Що показувати на панелі",
        obStepPanelBody: "Відкрийте кожен блок і виберіть, що саме показуватиметься при натисканні на значок.",
        obStepPanelNavigationTitle: "Панель за секціями",
        obStepPanelNavigationBody: "Тепер панель може показувати по одному розділу за раз. Перемикатися між «Секціями» та «Списком» можна в Налаштуваннях.",
        cleaningMenuItem: "Режим очищення",
        utilitiesSection: "Утиліти",
        quickControlsSection: "Керування",
        panelCategoryWindows: "Вікна",
        panelCategoryInput: "Миша та клавіатура",
        panelCategoryFiles: "Файли",
        windowMaximizeName: "Розгортати вікна",
        windowMaximizeCaption: "Зелена кнопка розгортає вікно, не створюючи новий Space.",
        windowMaximizeActiveNow: "Перевизначення зеленої кнопки активне",
        windowMaximizeNeedsAccessibility: "Для роботи потрібен Універсальний доступ.",
        keyDebounceName: "Фільтр повторів",
        keyDebounceEnable: "Фільтрувати повторні натискання",
        keyDebounceCaption: "Фільтрує дуже швидкі повторні натискання клавіш.",
        keyDebounceActiveNow: "Фільтр активний",
        keyDebounceGlobalWindow: "Глобальне вікно",
        keyDebouncePerKeySection: "Окремі клавіші",
        keyDebouncePerKeyCaption: "Значення для окремих клавіш мають пріоритет над глобальним вікном. Використовуйте 0 мс, щоб не фільтрувати конкретну клавішу.",
        keyDebounceKeyLabel: "Клавіша",
        keyDebounceWindowLabel: "Вікно",
        keyDebounceAddKey: "Додати клавішу",
        keyDebounceNoOverrides: "Окремі клавіші не налаштовані.",
        keyDebounceRemoveKey: "Видалити клавішу",
        cleaningPanelCaption: "Блокує клавіатуру, щоб можна було безпечно почистити її.",
        cleaningOverlayTitle: "Клавіатуру заблоковано для чищення",
        cleaningOverlaySubtitle: "Натисніть Esc 5 разів, щоб розблокувати",
        cleaningOverlayUnlock: "Розблокувати",
        cleaningOverlayMouseHint: "Миша та трекпад продовжують працювати",
        cleaningKeepScreenVisibleToggle: "Залишати екран видимим",
        cleaningKeepScreenVisibleCaption: "Показує компактний індикатор у куті екрана замість затемнення вмісту.",
        cleaningStartNow: "Заблокувати клавіатуру зараз",
        cleaningNeedsAxTitle: "Потрібен Універсальний доступ",
        cleaningNeedsAxBody: "Для безпечного блокування клавіатури Vorssaint потрібен доступ до Універсального доступу. Надайте його в Системних налаштуваннях та спробуйте знову.",
        tabSupport: "Підтримка",
        shortcutsPageCaption: "Редагуйте всі глобальні клавіатурні скорочення функцій, встановлених на цьому Mac. Неактивні поєднання зберігаються, але не спрацьовують.",
        shortcutsPageTitle: "Клавіатурні скорочення",
        settingsSearchPlaceholder: "Пошук у налаштуваннях",
        donateHeading: "Допоможіть Vorssaint розвиватися",
        donateMessage: "Vorssaint безкоштовний, незалежний і створюється у вільний час. Якщо ви хочете допомогти фінансово, Buy Me a Coffee безпосередньо підтримує подальшу розробку.",
        donateButton: "Підтримати через Buy Me a Coffee",
        donateThanks: "Дякуємо, що ви тут. 🖤",
        supportIntroTitle: "Допоможіть Vorssaint розвиватися",
        supportIntroMessage: "Якщо ви хочете фінансово підтримати розробку, зробити це можна лише через Buy Me a Coffee.",
        supportIntroStarButton: "Поставити Vorssaint зірку на GitHub",
        supportIntroStarMessage: "Фінансова підтримка зовсім не обов'язкова. Зірка на GitHub допомагає більшій кількості людей знайти Vorssaint і справді впливає на його розвиток.",
        supportIntroCoffeeButton: "Підтримати через Buy Me a Coffee",
        supportIntroLaterButton: "Не зараз",
        supportIntroDoneButton: "Готово",
        discordIntroTitle: "Спільнота Vorssaint у Discord тільки починає рости",
        discordIntroMessage: "Спільнота Vorssaint нова і все ще формується. Приєднуйтесь зараз, знайомтеся з іншими користувачами та допоможіть створити привітний простір навколо програми.",
        discordIntroBenefitHelp: "Отримуйте допомогу та діліться робочими процесами",
        discordIntroBenefitFeedback: "Повідомляйте про помилки, пропонуйте вдосконалення та впливайте на подальші плани",
        discordIntroBenefitPreviews: "Стежте за розробкою, ранніми прев'ю та новинами випусків",
        discordIntroJoinButton: "Приєднатися до спільноти в Discord",
        communityIntroTitle: "Дивіться все раніше за всіх",
        communityIntroMessage: "Ті, хто вже стежив за мною у X, побачили багато змін цього оновлення раніше за всіх. Я публікую прев'ю майбутніх новинок та показую, як вони працюють, щоб ви знали основи ще до виходу оновлення. Підписуйтеся та дізнайтеся, що буде далі!",
        communityIntroFollowButton: "Підписатися на @vorssaint у X",
        homebrewOfficialIntroTitle: "Тепер в офіційному каталозі Homebrew",
        homebrewOfficialIntroMessage: "Тепер Vorssaint можна встановити безпосередньо з офіційного каталогу Homebrew.",
        homebrewOfficialIntroInstallLabel: "Нове встановлення",
        homebrewOfficialIntroMigrationTitle: "Користувалися старим tap?",
        homebrewOfficialIntroMigrationMessage: "Видаліть tap один раз. Програма та ваші налаштування залишаться на місці.",
        homebrewOfficialIntroCopyButton: "Копіювати команду",
        updateShowcaseTitle: "Що нового в 3.1.4",
        updateShowcaseMessage: "Швидко погляньте на головні вдосконалення цього оновлення.",
        updateShowcaseUnavailable: "Зараз не вдалося завантажити відео. Ви все одно можете продовжити.",
        updateShowcaseRestart: "Почати заново",
        showMenuBarIcon: "Показувати значок у рядку меню",
        showMenuBarIconCaption: "Якщо значок Vorssaint зникне (macOS може ховати значки рядка меню, коли в ньому не вистачає місця, що часто буває на Mac з вирізом), відкрийте Vorssaint знову з папки «Програми» або через Spotlight: це створить значок заново і, якщо він все ще прихований, відкриє це вікно. Кнопка вище робить те саме, коли ви вже можете сюди потрапити. Чим менше значків у рядку меню або метрик Vorssaint, тим нижчий шанс, що це станеться.",
        menuBarIconStillHiddenTitle: "Значок все ще прихований",
        menuBarIconStillHiddenBody: "Значок було створено наново, але macOS не виділила йому видимого місця. Найімовірніше, у рядку меню не вистачає місця: приберіть кілька значків (або закрийте програми з довгими меню) та спробуйте знову.",
        menuBarIconManagerHintFormat: "%@ запущений і, можливо, тримає значок у своєму прихованому розділі. Пошукайте Vorssaint там або налаштуйте %@ завжди показувати Vorssaint.",
        shortcutRecording: "Натисніть нове клавіатурне скорочення",
        shortcutReset: "Скинути",
        shortcutNone: "Немає",
        shortcutClear: "Прибрати клавіатурне скорочення",
        shortcutInvalid: "Використовуйте хоча б Control, Option або Command разом із клавішею.",
        shortcutPressKeys: "Натисніть",
        shortcutEscapeHint: "Esc скасовує.",
        shortcutDeleteHint: "Delete прибирає.",
        shortcutNotCaptured: "Нічого не записано. Це поєднання вже зайняте macOS або іншою програмою. Спробуйте інше.",
        shortcutConflictFormat: "Це поєднання вже використовується %@.",
        shortcutUnavailable: "macOS відхилила це клавіатурне скорочення. Виберіть інше.",
        shelfShortcutToggle: "Клавіатурне скорочення полиці",
        switcherUsageHintFormat: "Утримуйте %@ для навігації; відпустіть, щоб активувати вікно. Shift або ← повертає назад; W закриває вікно; Q завершує програму; Esc скасовує.",
        musicBlockSection: "Медіаклавіші",
        musicBlockTitle: "Не давати Музиці відкриватися самій",
        musicBlockCaption: "Програма Музика більше не відкривається при натисканні медіаклавіш. Ви все ще можете відкрити її самі.",
        musicBlockReplacementLabel: "Відкривати замість",
        musicBlockReplacementNone: "Немає",
        musicBlockChooseApp: "Вибрати програму…",
        cleanerName: "Очищення",
        cleanerIntroTitle: "Очистіть Mac від сміття",
        cleanerIntroCaption: "Шукає залишки видалених програм, кеші, журнали та Кошик. Усе перевіряється заздалегідь, а видалене потрапляє в Кошик.",
        cleanerScan: "Перевірити",
        cleanerScanning: "Перевірка…",
        cleanerCleaning: "Очищення…",
        cleanerCatLeftovers: "Залишки видалених програм",
        cleanerCatLoginItems: "Осиротілі елементи входу",
        cleanerCatCaches: "Кеші",
        cleanerCatLogs: "Журнали",
        cleanerCatDeveloper: "Сміття розробника",
        cleanerCatTrash: "Кошик",
        cleanerLeftoversNote: "Знайдено аналізом і не відмічено. Перевірте шлях, перш ніж відмічати.",
        cleanerLoginItemsNote: "Запис у Елементах входу зникає після перезавантаження Mac.",
        cleanerTrashNote: "Очищення Кошика незворотне.",
        cleanerCatDeviceBackups: "Резервні копії iPhone",
        cleanerDeviceBackupsCaption: "Старі копії iPhone та iPad займають велику частину сховища, яку macOS називає «Інше». Видаляйте лише ті, що більше не потрібні; нова копія створюється при наступному підключенні пристрою.",
        cleanerNothingFound: "Нема чого очищати. Ваш Mac у порядку.",
        cleanerClean: "Очистити",
        cleanerDoneNote: "Елементи переміщено в Кошик, звідки їх можна відновити.",
        cleanerAgain: "Перевірити знову",
        cleanerRevealInFinder: "Показати у Finder",
        cleanerPanelCaption: "Залишки програм, кеші та журнали",
        cleanerSafeSection: "Безпечне очищення",
        cleanerOptionalSection: "За бажанням, спочатку перевірте",
        cleanerCatOtherCaches: "Інші кеші",
        cleanerCachesCaption: "Тимчасові файли, які програми створюють наново самі.",
        cleanerLogsCaption: "Старі журнали діагностики.",
        cleanerDeveloperCaption: "Залишки збірок та симуляторів Xcode.",
        cleanerLoginItemsCaption: "Елементи входу програм, яких більше не існує.",
        cleanerLeftoversCaption: "Файли, що залишилися від видалених програм.",
        cleanerOtherCachesCaption: "Видаляти безпечно, нічого не зламається. Програми можуть відкритися повільніше один раз, а завантажене, наприклад офлайн-музика, скачається знову.",
        cleanerCleanSizeFormat: "Очистити %@",
        cleanerScheduleTitle: "Автоматичне очищення",
        cleanerScheduleOff: "Вимкнено",
        cleanerScheduleDaily: "Щодня",
        cleanerScheduleWeekly: "Щотижня",
        cleanerScheduleCaption: "В обраний час сама очищає лише безпечну частину та надсилає все в Кошик.",
        cleanerScheduleLastFormat: "Останнє автоматичне очищення звільнило %@.",
        cleanerAutoNotificationFormat: "%@ звільнено та надіслано в Кошик.",
        cleanerScheduleNextFormat: "Наступне очищення %@.",
        cleanerScheduleRanFormat: "Останнє автоматичне очищення %@.",
        cleanerScheduleNotifyToggle: "Сповіщати після завершення",
        cleanerNotifDenied: "Сповіщення Vorssaint вимкнено в системі.",
        cleanerNotifOpenSettings: "Відкрити налаштування сповіщень…",
        launchAtLoginNeedsApplications: "Програму запущено з місця, з якого не можна відкриватися при вході. Перетягніть Vorssaint у папку «Програми», відкрийте його звідти та увімкніть параметр знову.",
        launchAtLoginNeedsApproval: "Елемент входу зареєстровано, але в Системних налаштуваннях він вимкнений. Відкрийте «Системні налаштування › Загальні › Елементи входу та розширення» та увімкніть Vorssaint у розділі «Відкривати при вході».",
        ocrRemoveLineBreaksToggle: "Прибирати перенесення рядків",
        ocrRemoveLineBreaksCaption: "Видаляє перенесення рядків, щоб скопійований текст вставлявся одним абзацом.",
        ocrQRToggle: "Читати QR-коди",
        ocrQRCaption: "Якщо в області є QR-код, його вміст можна скопіювати або відкрити.",
        ocrQRCopied: "QR-код скопійовано",
        qrResultTitle: "QR-код",
        qrResultCopy: "Скопіювати",
        qrResultOpen: "Відкрити посилання",
        highlightsTitle: "Нове в цьому оновленні",
        highlightsTitleClipboardRedesign: "Оновлений буфер обміну",
        highlightsCaptionDockPreview: "Dock Preview тепер працює з увімкненим збільшенням Dock",
        highlightsCaptionScreenshot: "Інструмент знімків екрана отримав піксельну лупу та читання QR-кодів",
        highlightsCaptionSnippetLibrary: "Меню сніпетів із пошуком друкує будь-який сніпет прямо біля курсора",
        highlightsCaptionCapturePalette: "Одне клавіатурне скорочення тепер відкриває плаваючу палітру для знімків, записів, тексту на екрані та кольорів зі зручним доступом до налаштувань.",
        highlightsCaptionClipboardRedesign: "Історія тепер відкривається як компактна палітра з акуратними рядками та попереднім переглядом за запитом для читання або редагування елемента.",
        highlightsConfigure: "Налаштувати",
        highlightsTry: "Спробувати",
        highlightsSeeAll: "Усі зміни",
        switcherCurrentSpaceOnly: "Показувати лише поточний робочий стіл",
        switcherCurrentSpaceOnlyCaption: "У перемикачі видно лише вікна робочого стола, на якому ви знаходитеся. Вибір вікна ніколи не переносить вас на інший робочий стіл.",
        shelfFileMissing: "Файл більше не існує",
        previewSizeSmall: "Малий",
        mixerSoundEffectsOutputTitle: "Системні звуки",
        mixerSoundEffectsOutputTooltip: "Вибрати пристрій для сповіщень та звукових ефектів",
        monitorOpenActivityMonitor: "Відкрити Моніторинг системи",
        dockClickHide: "Ховати програму клацом по Dock",
        dockClickHideCaption: "Активна програма ховається при клаці по її значку в Dock. Натисніть ще раз, щоб повернути її.",
        monitorMemoryMetricLabel: "Як вимірювати пам'ять",
        memoryMetricUsed: "Зайнято пам'яті",
        memoryMetricApp: "Пам'ять програм",
        keepAwakeRightClickToggle: "Клацніть правою кнопкою значок у рядку меню, щоб увімкнути або вимкнути «Не давати заснути»",
        keepAwakeRightClickToggleCaption: "Замінює контекстне меню правої кнопки миші.",
        urlCleanerRulesTitle: "Правила очищення",
        urlCleanerRulesCaption: "Сайт додає ці параметри у власні посилання для поширення, щоб відстежити, звідки прийшло посилання. З прапорцем назва видаляється при очищенні посилання, без прапорця залишається. Додані вами назви можна видалити.",
        urlCleanerRulesCoverageCaption: "Список охоплює різні способи поділитися на одному сайті: сторінку, програму та ефір, тому він довгий; у справжньому посиланні зазвичай лише два-чотири з них.",
        urlCleanerRulesAllSites: "Усі сайти",
        urlCleanerRulesCountSingular: "1 параметр",
        urlCleanerRulesCountPluralFormat: "Параметрів: %d",
        urlCleanerRulesAddSite: "Додати сайт",
        urlCleanerRulesParameterPlaceholder: "Назва параметра",
        urlCleanerRulesMatchCaption: "Впишіть назву ліворуч від = , наприклад utm_source. Назва, що збіглася, прибирає з посилання лише цей параметр, решта залишається як була.",
        urlCleanerRulesAddButton: "Додати",
        urlCleanerRulesRemoveButton: "Видалити назву",
        urlCleanerRulesRemoveSiteButton: "Вимкнути всі правила цього сайту",
        urlCleanerRemovedFormat: "Видалено: %@",
        switcherSearchPin: "Закріпити пошук клавішею S",
        switcherSearchPinCaption: "S запускає пошук і закріплює перемикач відкритим. Введення більше не дає спеціальні символи, якщо поєднання використовує ⌥, а пошук, що починається з Q або W, більше не закриває вікно та не завершує програму помилково.",
        invertVerticalScroll: "Інвертувати вертикальну прокрутку",
        invertHorizontalScroll: "Інвертувати горизонтальну прокрутку",
        switcherShowShortcutHints: "Показувати підказки поєднань клавіш",
        switcherShowShortcutHintsCaption: "Показує клавіатурні скорочення для програм та вікон під значками.",
        uninstallerHomebrewPackageFormat: "%@ також буде видалено з Homebrew.",
        shelfEdgeToggle: "Відкривати біля краю екрана",
        shelfEdgeCaption: "Перетягніть файл до краю екрана, щоб полиця виглянула. Відпустіть його там, або потягніть назад, і полиця прибереться.",
        focusFollowsMouseName: "Фокус за вказівником",
        focusFollowsMouseCaption: "Фокусує та піднімає вікно під вказівником після короткої паузи.",
        focusFollowsMouseDelay: "Затримка наведення",
        switcherMinimizedPlacementLabel: "Згорнуті вікна",
        switcherMinimizedPlacementNormal: "Звичайний порядок",
        switcherMinimizedPlacementEnd: "У кінець списку",
        switcherMinimizedPlacementHidden: "Сховати",
        switcherShowFullscreenWindows: "Показувати повноекранні вікна",
        switcherScreenPlacementLabel: "Показувати на",
        switcherScreenPlacementPointer: "Екран із вказівником",
        switcherScreenPlacementMenuBar: "Екран із рядком меню",
        switcherScreenPlacementActiveWindow: "Екран із активним вікном",
        switcherScreenPlacementCaption: "На якому екрані відкривається перемикач, коли підключено кілька екранів.",
        smoothScrollResponseLabel: "Відгук",
        mouseAccelerationName: "Вимкнути прискорення миші",
        mouseAccelerationCaption: "Вимикає прискорення вказівника для підключених мишей. Попереднє налаштування повернеться після вимкнення функції або виходу з Vorssaint."
    )
}
