// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// العربية — translated and hand-checked, not machine output.
extension Strings {
    static let ar = Strings(
        statusIdleTooltip: "Vorssaint: سكون عادي",
        statusActiveUntil: "Vorssaint: مستيقظ حتى",
        statusActiveIndefinite: "Vorssaint: مستيقظ بلا مدة محددة",
        menuEnableAwake: "تفعيل الإبقاء مستيقظًا",
        menuDisableAwake: "إيقاف الإبقاء مستيقظًا",
        menuActivateFor: "التفعيل لمدة…",
        menuSettings: "الإعدادات…",
        menuAbout: "حول Vorssaint",
        menuQuit: "إنهاء Vorssaint",
        menuHide: "إخفاء Vorssaint",
        menuHideOthers: "إخفاء الآخرين",
        menuShowAll: "إظهار الكل",
        menuEdit: "تحرير",
        menuUndo: "تراجع",
        menuRedo: "إعادة",
        menuCut: "قص",
        menuCopy: "نسخ",
        menuPaste: "لصق",
        menuSelectAll: "تحديد الكل",
        menuWindow: "نافذة",
        menuMinimize: "تصغير",
        menuZoom: "تكبير/تصغير",
        menuClose: "إغلاق",

        minutes15: "15 دقيقة",
        minutes30: "30 دقيقة",
        hour1: "ساعة واحدة",
        hours2: "ساعتان",
        hours4: "4 ساعات",
        hours8: "8 ساعات",
        indefinitely: "بلا مدة محددة",
        indefinite: "غير محدد",

        panelSettings: "الإعدادات",
        panelQuit: "إنهاء",
        panelHotkeyHint: "الاختصار يبدّل الحالة",

        keepAwakeTitle: "الإبقاء مستيقظًا",
        keepAwakeEndsIn: "ينتهي بعد",
        keepAwakeUntilDisabled: "نشط حتى توقفه",
        keepAwakeNormalRules: "يتبع الـ Mac قواعد الطاقة المعتادة",
        keepAwakeOptions: "الخيارات",
        keepAwakeMouseJiggle: "تحريك المؤشر قليلًا",
        keepAwakeMouseJiggleCaption: "يحرّك المؤشر قليلًا أثناء الجلسة على الفترة المحددة.",
        keepAwakeMouseJiggleInterval: "الفترة",
        keepAwakeActiveIconLabel: "الأيقونة النشطة",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "قهوة",
        keepAwakeActiveIconEye: "عين",
        keepAwakeActiveIconMoon: "قمر",
        keepAwakeActiveIconLight: "مصباح",
        keepAwakeIconTintLabel: "لون الأيقونة النشطة",
        keepAwakeIconTintOrange: "برتقالي",
        keepAwakeIconTintGreen: "أخضر",
        keepAwakeIconTintBlue: "أزرق",
        keepAwakeIconTintPurple: "بنفسجي",
        keepAwakeIconTintPink: "وردي",
        keepAwakeIconTintNone: "بلا لون",
        durationLabel: "المدة",
        clamshellTitle: "المتابعة والغطاء مغلق",
        clamshellOnCaption: "السكون معطّل تمامًا. انتبه للطاقة",
        clamshellNeedsSession: "يُطبَّق كلما كان «الإبقاء مستيقظًا» نشطًا",
        clamshellReady: "جاهز. يبدّل الحالة بدون كلمة سر",
        clamshellNeedsPassword: "سيطلب كلمة سر المسؤول مرة واحدة",

        systemSection: "النظام",
        temperatures: "درجات الحرارة",
        cpuLabel: "المعالج",
        gpuLabel: "بطاقة الرسوم",
        batteryLabel: "البطارية",
        usageSection: "استخدام العتاد",
        memorySection: "الذاكرة",
        memoryPressure: "الضغط",
        memorySwapUsed: "التبديل المستخدم",
        memoryCompressed: "المضغوطة",
        memoryCachedFiles: "الملفات المخزنة مؤقتًا",
        pressureNormal: "عادي",
        pressureWarning: "تنبيه",
        pressureCritical: "حرج",
        monitorUnavailable: "المستشعرات غير متاحة على هذا الـ Mac",
        energyAppsTitle: "التطبيقات ذات استهلاك الطاقة الكبير",
        energyAppsIdle: "لا يوجد استهلاك كبير للطاقة",

        notifySessionEndedTitle: "انتهت الجلسة",
        notifySessionEndedBody: "انتهى الوقت. سيعود الـ Mac إلى السكون المعتاد.",
        notifyBatteryTitle: "تم إيقاف Vorssaint",
        notifyBatteryBody: "البطارية منخفضة. أُعيد السكون المعتاد للحفاظ على الشحن.",
        adminPromptClamshellOn: "يحتاج Vorssaint إلى كلمة السر لإبقاء الـ Mac يعمل والغطاء مغلق.",
        adminPromptClamshellOff: "يحتاج Vorssaint إلى كلمة السر لاستعادة السكون المعتاد للـ Mac.",
        adminPromptRecover: "أُنهي Vorssaint بينما كان سكون الـ Mac معطّلًا. أدخل كلمة السر لاستعادة السكون المعتاد.",
        adminPromptUpdate: "يحتاج Vorssaint إلى كلمة السر لتثبيت التحديث.",
        adminPromptSudoersInstall: "سينشئ Vorssaint قاعدة محدودة (‏pmset disablesleep فقط) لتبديل وضع الغطاء المغلق دون طلب كلمة سر. وهذه هي المرة الوحيدة التي تُطلب فيها كلمة السر.",
        adminPromptSudoersRemove: "سيزيل Vorssaint قاعدة الغطاء المغلق التي لا تتطلب كلمة سر.",

        settingsTitle: "إعدادات Vorssaint",
        tabGeneral: "عام",
        tabEnergy: "الطاقة",
        tabMouse: "الماوس ولوحة التتبع",
        tabSwitcher: "المبدّل",
        tabAdvanced: "متقدم",
        tabAbout: "حول",
        tabReleaseNotes: "الجديد",
        releaseNotesOnUpdateToggle: "إظهار الجديد بعد التحديث",
        previewSizeLabel: "حجم المعاينة",
        previewSizeNormal: "عادي",
        previewSizeLarge: "كبير",
        previewSizeXLarge: "كبير جدًا",
        settingsGroupFeatures: "المزايا",
        advancedResetSection: "الأذونات",
        advancedResetDescription: "يزيل كل إذن منحته لـ Vorssaint (إمكانية الوصول، وتسجيل الشاشة، والوصول الكامل للقرص وغيرها)، وعنصر تسجيل الدخول، وقاعدة الغطاء المغلق. مفيد للبدء من جديد أو قبل إلغاء التثبيت. ويبقى التطبيق مثبتًا.",
        advancedClearButton: "مسح كل الأذونات",
        advancedCleared: "تم مسح الأذونات.",
        advancedClearConfirmTitle: "مسح كل الأذونات؟",
        advancedClearConfirmBody: "ستتوقف المزايا التي تحتاج إلى أذونات عن العمل حتى تمنحها مجددًا. وتبقى إعداداتك محفوظة.",
        advancedUninstallSection: "إلغاء التثبيت",
        advancedUninstallDescription: "ينفّذ كل ما سبق، ثم يزيل التفضيلات وينقل Vorssaint إلى المهملات دون أن يترك شيئًا. ويُنهى التطبيق عند الانتهاء. ويمكنك إعادة التثبيت في أي وقت.",
        advancedUninstallButton: "إلغاء تثبيت Vorssaint بالكامل",
        advancedUninstallConfirmTitle: "إلغاء تثبيت Vorssaint؟",
        advancedUninstallConfirmBody: "سيمسح Vorssaint أذوناته ويزيل تفضيلاته وينتقل إلى المهملات ثم يُنهى. ولا يمكن التراجع عن ذلك من داخل التطبيق، لكنه يبقى في المهملات حتى تفرغها.",

        launchAtLogin: "التشغيل عند تسجيل الدخول",
        languageLabel: "اللغة",
        menuBarSection: "شريط القائمة",
        showCountdown: "إظهار الوقت المتبقي بجانب الأيقونة",
        globalHotkeySection: "الاختصار العام",
        hotkeyToggle: "تفعيل اختصار «الإبقاء مستيقظًا»",
        hotkeyCaption: "يعمل في أي تطبيق دون أذونات إضافية.",

        sessionSection: "الجلسة",
        defaultDurationLabel: "المدة الافتراضية",
        keepAwakeAutoStart: "الإبقاء مستيقظًا عند فتح Vorssaint",
        keepAwakeAutoStartCaption: "يبدأ جلسة بالمدة الافتراضية.",
        batteryProtectionSection: "حماية البطارية",
        batteryDisableBelow: "الإيقاف عند انخفاض البطارية دون",
        batteryNever: "أبدًا",
        batteryProtectionCaption: "يمنع جلسة منسية من استنزاف بطارية الـ MacBook.",
        clamshellSection: "الغطاء المغلق",
        configuring: "جارٍ الإعداد…",
        sudoersFailed: "تعذّر تفعيل وضع الغطاء المغلق. حاول مجددًا.",
        clamshellExplanation: "يعطّل خيار «المتابعة والغطاء مغلق» السكون تمامًا أثناء نشاط «الإبقاء مستيقظًا»، ويُعاد تلقائيًا عند انتهاء الجلسة أو إنهاء التطبيق. ويُفضَّل استخدامه أثناء التوصيل بالطاقة.",

        scrollSection: "التمرير",
        invertMouseScroll: "عكس تمرير الماوس",
        invertMouseScrollCaption: "يعكس اتجاه عجلة الماوس.",
        scrollTrackpadNote: "لا تتأثر لوحة التتبع: فهي تحتفظ بالتمرير الطبيعي في macOS.",
        scrollActiveNow: "يعكس تمرير الماوس الآن",
        mouseNavigationActiveNow: "الأزرار الجانبية نشطة الآن",
        smoothScrollName: "التمرير السلس",
        smoothScrollCaption: "يحوّل كل خطوة من عجلة الماوس إلى انزلاق قصير وهادئ. ولا تتأثر لوحة التتبع.",
        smoothScrollStepLabel: "المسافة لكل خطوة",
        mouseNavigationSection: "التنقل",
        mouseNavigationEnable: "استخدام الأزرار الجانبية للرجوع والتقدم",
        mouseNavigationCaption: "يحوّل زري الرجوع والتقدم في الماوس إلى أوامر تنقل في Finder والمتصفحات والتطبيقات المتوافقة.",
        middleClickSection: "النقرة الوسطى",
        middleClickEnable: "النقر بثلاثة أصابع يعمل كنقرة وسطى",
        middleClickEnableCaption: "الضغط على لوحة التتبع بثلاثة أصابع يعمل كالنقر بعجلة الماوس: فتح الروابط في علامة تبويب جديدة، وإغلاق علامات التبويب، وكل ما يفعله الزر الأوسط.",
        middleClickDragConflict: "السحب بثلاثة أصابع في macOS مفعّل ويستخدم الإيماءة نفسها. أوقفه من إعدادات النظام ضمن إمكانية الوصول ثم التحكم بالمؤشر ثم خيارات لوحة التتبع، فتعمل النقرة الوسطى.",
        middleClickTapPicker: "النقرة الخفيفة تنقر أيضًا",
        middleClickTapOff: "متوقفة",
        middleClickTapThreeFingers: "3 أصابع",
        middleClickTapFourFingers: "4 أصابع",
        middleClickTapCaption: "النقرة الخفيفة بهذا العدد من الأصابع، دون ضغط، تطلق النقرة الوسطى أيضًا. أما الانزلاق فلا يُحتسب أبدًا. وإذا كانت نقرة الأصابع الثلاثة في macOS معيّنة لـ «البحث»، فأوقفها كي لا يعملا معًا.",
        quickToolsTab: "اللوحة السريعة",
        quickToolShortcutToggle: "اختصار عام",
        ocrName: "نسخ النص من الشاشة",
        ocrCaption: "حدد منطقة من الشاشة فيُنسخ النص المتعرَّف عليه جاهزًا للصق.",
        ocrCopied: "تم نسخ النص",
        ocrNoText: "لم يتم العثور على نص",
        colorPickerName: "منتقي الألوان",
        colorPickerCaption: "التقط لون أي بكسل على الشاشة وانسخه بالصيغة المفضلة لديك.",
        colorPickerFormatLabel: "الصيغة المنسوخة",
        colorPickerBareHexToggle: "النسخ بدون البادئة #",
        colorPickerPickNow: "التقاط لون",
        micMuteName: "كتم الميكروفون",
        micUnmuteName: "إلغاء كتم الميكروفون",
        micMuteCaption: "يقطع ميكروفون الـ Mac بنقرة أو باختصار في كل التطبيقات.",
        micMutedHUD: "تم كتم الميكروفون",
        micUnmutedHUD: "عاد الميكروفون للعمل",
        micMuteMenuBarToggle: "الإظهار في شريط القائمة أثناء الكتم",
        micMuteMenuBarCaption: "يظهر ميكروفون أحمر مشطوب بجوار أيقونة التطبيق في شريط القائمة.",
        pastePlainName: "اللصق كنص عادي",
        pastePlainCaption: "يلصق ما نسخته بلا ألوان أو خطوط أو تنسيق. ويبقى الأصل في الحافظة.",
        launcherName: "اللوحة السريعة",
        launcherCaption: "لوحة عائمة بأدواتك المفضلة، تُستدعى باختصار من أي مكان.",
        launcherOpenNow: "فتح اللوحة السريعة",
        launcherEditHint: "استخدم زر الضبط لاختيار الأدوات وإخفائها وسحبها.",
        launcherEmptyState: "كل الأدوات مخفية. استخدم زر الضبط لإعادتها.",
        launcherAddSection: "إعادة الإضافة",
        launcherKeysHint: "الأسهم للتنقل، وEnter للفتح، ومن 1 إلى 9 للفتح المباشر",

        switcherSection: "مبدّل التطبيقات",
        switcherEnable: "استخدام مبدّل Vorssaint",
        switcherEnableCaption: "بدّل بين التطبيقات والنوافذ، بما فيها النوافذ المصغّرة وعدة نوافذ من التطبيق نفسه.",
        switcherUsageHint: "استمر بالضغط على الاختصار للتنقل؛ وأفلته لتفعيل النافذة. وShift أو ← للرجوع؛ وW لإغلاق النافذة؛ وQ لإنهاء التطبيق؛ وEsc للإلغاء.",
        switcherNoWindows: "لا توجد نوافذ مفتوحة",
        switcherIconRowMode: "إظهار %@ بأيقونات كبيرة",
        switcherIconRowModeCaption: "يعرض أيقونة واحدة لكل تطبيق مع معاينات نوافذه فوقها.",
        switcherSimpleMode: "مبدّل تطبيقات بسيط",
        switcherSimpleModeCaption: "يعرض أيقونات التطبيقات وعناوين النوافذ، بلا معاينات ودون التقاط للشاشة من المبدّل.",
        switcherShortcutHintApps: "التطبيقات",
        switcherShortcutHintWindows: "النوافذ",
        switcherWindowShortcutCaption: "يفتح مبدّلًا لنوافذ التطبيق في المقدمة. وأثناء فتح مبدّل التطبيقات، ينتقل بين نوافذ التطبيق المحدد.",
        switcherAppearanceDelay: "تأخير الظهور",
        switcherAppearanceDelayCaption: "المدة التي يجب الاستمرار بالضغط على الاختصار خلالها قبل ظهور المبدّل.",
        switcherMergeTabs: "إظهار مدخل واحد لكل تطبيق",
        switcherMergeTabsCaption: "يجمع كل نوافذ التطبيق في مدخل واحد داخل المبدّل بدلًا من مدخل لكل نافذة.",
        switcherWindowlessApps: "التطبيقات بلا نوافذ مفتوحة",
        switcherWindowlessAppsCaption: "يحدد أي التطبيقات العاملة بلا أي نافذة تظهر في المبدّل.",
        switcherWindowlessAppsOff: "عدم الإظهار",
        switcherWindowlessAppsFinder: "Finder فقط",
        switcherWindowlessAppsAll: "كل التطبيقات",
        switcherNoOpenWindow: "لا توجد نافذة مفتوحة",
        switcherOtherDesktop: "سطح مكتب آخر",
        dockPreviewName: "معاينة الـ Dock",
        dockPreviewEnable: "معاينة النوافذ من الـ Dock",
        dockPreviewEnableCaption: "مرّر المؤشر فوق تطبيق مفتوح في الـ Dock لرؤية نوافذه، ثم انقر النافذة التي تريدها.",
        dockPreviewBackgroundOpacity: "خلفية اللوحة",
        dockPreviewBackgroundOpacityCaption: "اخفضها لترى المزيد مما خلف اللوحة.",
        dockPreviewOpenDelay: "تأخير الفتح",
        dockPreviewOpenDelayCaption: "المدة التي يجب أن يستقر فيها المؤشر على الأيقونة قبل فتح لوحتها.",
        dockPreviewQuitAppOnClose: "إنهاء التطبيق بزر ×",
        dockPreviewQuitAppOnCloseCaption: "في معاينة الـ Dock، ينهي × التطبيق بأكمله بدلًا من إغلاق تلك النافذة وحدها.",
        dockClickMinimize: "النقر على أيقونة الـ Dock للتصغير",
        dockClickMinimizeCaption: "تُصغَّر نوافذ التطبيق النشط عند نقر أيقونته في الـ Dock. وانقر مجددًا لإعادتها.",
        dockClickCycleWindows: "النقر على أيقونة الـ Dock للتنقل بين النوافذ",
        dockClickCycleWindowsCaption: "انقر أيقونة تطبيق نشط في الـ Dock للتنقل بين نوافذه، مثل ⌘`.",
        dockPreviewActiveNow: "نشطة في الـ Dock",
        dockPreviewDockUnavailable: "تعذّرت قراءة عناصر الـ Dock.",
        dockPreviewAutohideBeta: "نسخة تجريبية. قد تصادف بعض العلل.",
        dockPreviewOpenWindow: "فتح النافذة",
        dockPreviewCloseWindow: "إغلاق النافذة",
        dockPreviewMinimizeWindow: "تصغير النافذة",
        dockPreviewRestoreWindow: "استعادة النافذة",
        dockPreviewPinPanel: "تثبيت المعاينة",
        dockPreviewUnpinPanel: "إلغاء تثبيت المعاينة",
        dockPreviewPinned: "مثبّتة",
        dockPreviewClosePanel: "إغلاق المعاينة",
        dockPreviewPreviousWindow: "النافذة السابقة",
        dockPreviewNextWindow: "النافذة التالية",

        cutPasteName: "القص واللصق",
        cutPasteEnable: "قص الملفات ولصقها في Finder",
        cutPasteEnableCaption: "استخدم ⌘X للقص و⌘V لنقل الملفات والمجلدات في Finder.",
        cutPasteShowHUD: "إظهار لوحة عائمة",
        cutPasteShowHUDCaption: "يعرض مؤشرًا عائمًا بالملفات المقصوصة أثناء نشاط Finder.",
        cutPasteHowTitle: "طريقة الاستخدام",
        cutPasteStep1: "حدد عناصر في Finder واضغط ⌘X لقصها.",
        cutPasteStep2: "افتح مجلد الوجهة واضغط ⌘V لنقلها إليه.",
        cutPasteTextNote: "في حقول النص (كإعادة التسمية)، يواصل ⌘X و⌘V عملهما المعتاد.",
        cutPasteActiveNow: "جاهز للقص في Finder",
        cutPasteAutomationNote: "في المرة الأولى، يطلب macOS إذنًا للتحكم في Finder.",
        cutReadyTitle: "مقصوص",
        cutReadyHint: "في مجلد الوجهة للنقل",
        cutCancel: "إلغاء القص",
        cutDoneTitle: "تم النقل!",
        cutMovedSingular: "تم نقل عنصر واحد",
        cutMovedPluralFormat: "تم نقل %d عنصر",
        cutSomeFailed: "تعذّر نقل بعض العناصر",
        cutMovingTitle: "جارٍ النقل…",
        cutMovingCountFormat: "%d من %d",

        autoQuitName: "الإنهاء عند الإغلاق",
        autoQuitEnable: "إنهاء التطبيق عند إغلاق آخر نافذة له",
        autoQuitEnableCaption: "إغلاق آخر نافذة للتطبيق يُنهيه أيضًا.",
        autoQuitActiveNow: "نشط الآن",
        autoQuitHowTitle: "طريقة العمل",
        autoQuitStep1: "أغلِق آخر نافذة للتطبيق (‏⌘W أو الزر الأحمر).",
        autoQuitStep2: "يُنهى التطبيق من تلقاء نفسه. وتظل مربعات «حفظ التغييرات؟» تظهر.",
        autoQuitPredictableNote: "التطبيقات التي تعمل عادةً بلا نافذة لا تُنهى أبدًا.",
        autoQuitExceptionsTitle: "الاستثناءات",
        autoQuitExceptionsCaption: "تبقى التطبيقات في هذه القائمة مفتوحة حتى بلا نوافذ.",
        autoQuitExceptionsEmpty: "لا توجد استثناءات",
        autoQuitAddApp: "إضافة تطبيق…",

        uninstallerName: "أداة إلغاء التثبيت",
        uninstallerEnableCaption: "تزيل التطبيق مع ما يخلّفه من ذاكرات تخزين مؤقت وتفضيلات وسجلات وبقايا.",
        uninstallerStep1: "اسحب تطبيقًا إلى الإعدادات، أو اختر واحدًا من القائمة.",
        uninstallerStep2: "راجِع الملفات التي عُثر عليها والمساحة التي تشغلها.",
        uninstallerStep3: "انقل ما تريد إلى المهملات. ولا يُحذف شيء نهائيًا.",
        uninstallerMenuItem: "إلغاء تثبيت تطبيق…",
        uninstallerDropTitle: "اسحب تطبيقًا إلى هنا",
        uninstallerDropSubtitle: "أو اختر واحدًا لفحصه",
        uninstallerChoose: "اختيار تطبيق…",
        uninstallerPickerTitle: "اختيار تطبيق",
        uninstallerPickerSearch: "البحث في التطبيقات",
        uninstallerPickerEmpty: "لم يتم العثور على تطبيقات",
        uninstallerEmptyNote: "لا يُزال شيء دون تأكيدك.",
        uninstallerFDANote: "امنح الوصول الكامل للقرص للحصول على فحص أدق.",
        uninstallerFDAGrant: "منح الوصول…",
        uninstallerFDAHint: "فعّل Vorssaint في القائمة. وإن لم يكن موجودًا، فانقر + واختر Vorssaint من «التطبيقات». ولا يسري الوصول إلا بعد إعادة فتح التطبيق.",
        uninstallerFDARelaunch: "إعادة التشغيل الآن",
        uninstallerScanning: "جارٍ فحص الملفات…",
        uninstallerRemoving: "جارٍ النقل إلى المهملات…",
        uninstallerFoundTitle: "تم العثور عليها",
        uninstallerSelectedFormat: "%d محدد من %d",
        uninstallerRemove: "النقل إلى المهملات",
        uninstallerCancel: "إلغاء",
        uninstallerDoneTitle: "تم!",
        uninstallerFreedFormat: "تم استرجاع %@",
        uninstallerSomeFailed: "تعذّر نقل بعض العناصر إلى المهملات.",
        uninstallerFailedNeedsFDA: "لا يمكن نقل بيانات التطبيقات المعزولة إلا بالوصول الكامل للقرص. ولا تغني كلمة سر المسؤول عنه.",
        uninstallerFailedMoreFormat: "و%d غيرها",
        uninstallerAnother: "إلغاء تثبيت تطبيق آخر",
        uninstallerCatApp: "التطبيق",
        uninstallerCatSupport: "ملفات الدعم",
        uninstallerCatCaches: "ذاكرات التخزين المؤقت",
        uninstallerCatPreferences: "التفضيلات",
        uninstallerCatContainers: "الحاويات",
        uninstallerCatLogs: "السجلات",
        uninstallerCatState: "الحالة المحفوظة",
        uninstallerCatOther: "أخرى",

        urlCleanerName: "تنظيف الروابط",
        urlCleanerEnable: "تنظيف الروابط أثناء نسخها",
        urlCleanerEnableCaption: "يزيل معاملات التتبع من الرابط لحظة وصوله إلى الحافظة.",
        urlCleanerActiveNow: "نشط الآن",
        urlCleanerManualTitle: "التنظيف الآن",
        urlCleanerInputPlaceholder: "الصق رابطًا",
        urlCleanerOutputPlaceholder: "يظهر الرابط النظيف هنا",
        urlCleanerCleanButton: "تنظيف",
        urlCleanerPasteButton: "لصق",
        urlCleanerCopyButton: "نسخ",
        urlCleanerClearButton: "مسح الحقل",
        urlCleanerNoURL: "الصق رابطًا صالحًا.",
        urlCleanerNoChange: "لا شيء لتنظيفه.",
        urlCleanerCleaned: "تم تنظيف الرابط.",
        urlCleanerCopied: "تم النسخ.",
        urlCleanerLocalNote: "محلي. بلا شبكة.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "ابحث عن الصيغ والحزم وثبّتها وأزِلها.",
        homebrewMissingTitle: "لم يتم العثور على Homebrew",
        homebrewMissingBody: "يستطيع Vorssaint فتح Terminal بمثبّت Homebrew الرسمي. ويعرض Terminal الخطوات ويطلب كلمة السر عند الحاجة.",
        homebrewInstallHomebrew: "تثبيت Homebrew",
        homebrewInstallHomebrewCaption: "عند انتهاء Terminal، عُد إلى هنا وانقر «تحديث».",
        homebrewInstallHomebrewOpened: "فُتح المثبّت في Terminal.",
        homebrewShellSetupTitle: "إكمال إعداد Terminal",
        homebrewShellSetupBody: "تم تثبيت Homebrew، لكن قد لا يجد Terminal أمر brew بعد. ويستطيع Vorssaint فتح Terminal بأمر الإعداد.",
        homebrewShellSetupButton: "إعداد Terminal",
        homebrewShellSetupOpened: "فُتح الأمر في Terminal. ثم عُد إلى هنا وانقر «تحديث».",
        homebrewRefresh: "تحديث",
        homebrewCheckPackages: "التحقق من الحزم",
        homebrewTrustTitle: "المصدر غير موثوق بعد",
        homebrewTrustCaption: "يطلب Homebrew الآن تأكيدك قبل استخدام مصادر خارجية. وثّق %@ للمتابعة.",
        homebrewTrustButton: "التوثيق والمتابعة",
        homebrewSearchPlaceholder: "البحث في الحزم",
        homebrewKeyboardHint: "المسافة أو Return يغلق لوحة macOS. استخدم زر البحث.",
        homebrewSearchButton: "بحث",
        homebrewSearchResults: "النتائج",
        homebrewInstalled: "المثبّتة",
        homebrewAll: "الكل",
        homebrewFormulas: "الصيغ",
        homebrewCasks: "الحزم",
        homebrewNoPackages: "لم يتم العثور على حزم",
        homebrewNoSelection: "اختر حزمة مثبّتة أو ابحث عن حزمة جديدة.",
        homebrewDetailsTitle: "تفاصيل الحزمة",
        homebrewInstall: "تثبيت",
        homebrewUninstall: "إلغاء التثبيت",
        homebrewUpgrade: "تحديث",
        homebrewUpgradeAll: "تحديث الكل",
        homebrewUpdateHomebrew: "تحديث Homebrew",
        homebrewAllPackages: "حزمة",
        homebrewOpenTerminal: "فتح Terminal",
        homebrewCancelOperation: "إلغاء",
        homebrewClearLog: "مسح السجل",
        homebrewLogTitle: "السجل",
        homebrewVersion: "الإصدار",
        homebrewDescription: "النوع",
        homebrewHomepage: "فتح الموقع",
        homebrewPopularity: "الشعبية",
        homebrewPopularityFormat: "%@ عملية تثبيت خلال %@ يوم",
        homebrewInstalledBadge: "مثبّتة",
        homebrewNotInstalledBadge: "غير مثبّتة",
        homebrewUpdates: "التحديثات",
        homebrewUpdateAvailableBadge: "يتوفر تحديث",
        homebrewLatestVersion: "الأحدث",
        homebrewConfirmInstallTitle: "التثبيت عبر Homebrew؟",
        homebrewConfirmInstallBodyFormat: "سينزّل Homebrew %@ ويثبّته. وقد تُثبَّت التبعيات أيضًا.",
        homebrewConfirmUninstallTitle: "إلغاء التثبيت عبر Homebrew؟",
        homebrewConfirmUninstallBodyFormat: "سيلغي Homebrew تثبيت %@. وقد تبقى ملفات الإعداد في النظام.",
        homebrewConfirmUpgradeTitle: "التحديث عبر Homebrew؟",
        homebrewConfirmUpgradeBodyFormat: "سينزّل Homebrew أحدث إصدار من %@ ويطبّقه. وقد تُحدَّث التبعيات أيضًا.",
        homebrewConfirmUpgradeAllTitle: "تحديث الكل عبر Homebrew؟",
        homebrewConfirmUpgradeAllBody: "سينزّل Homebrew أحدث الإصدارات للحزم التي تتوفر لها تحديثات ويطبّقها. وقد تُحدَّث التبعيات أيضًا.",
        homebrewConfirmUpdateHomebrewTitle: "تحديث Homebrew؟",
        homebrewConfirmUpdateHomebrewBody: "سيجلب Homebrew أحدث المعلومات ثم يعيد تحميل حزمك.",
        homebrewTerminalFallback: "تحتاج هذه العملية إلى Terminal لطلب كلمة سر المسؤول. ولا يلتقط Vorssaint كلمات السر.",
        homebrewLoading: "جارٍ التحميل…",
        homebrewSearchEmpty: "لا توجد نتائج",
        homebrewOperationInstallFormat: "جارٍ تثبيت %@",
        homebrewOperationUninstallFormat: "جارٍ إلغاء تثبيت %@",
        homebrewOperationUpgradeFormat: "جارٍ تحديث %@",
        homebrewOperationUpgradeAll: "جارٍ تحديث الحزم",
        homebrewOperationUpdateHomebrew: "جارٍ تحديث Homebrew",
        homebrewOperationInstalledFormat: "تم تثبيت %@.",
        homebrewOperationUninstalledFormat: "تم إلغاء تثبيت %@.",
        homebrewOperationUpgradedFormat: "تم تحديث %@.",
        homebrewOperationUpgradedAll: "تم تحديث الحزم.",
        homebrewOperationUpdatedHomebrew: "تم تحديث Homebrew.",
        homebrewOperationFailedFormat: "تعذّر إكمال %@.",
        homebrewOperationCancelled: "تم إلغاء العملية.",
        homebrewOperationPreparing: "جارٍ التحضير...",
        homebrewOperationDownloading: "جارٍ تنزيل الملفات...",
        homebrewOperationInstalling: "جارٍ تثبيت الملفات...",
        homebrewOperationUninstalling: "جارٍ إزالة الملفات...",
        homebrewOperationUpgrading: "جارٍ تحديث الملفات...",
        homebrewOperationFinalizing: "جارٍ الإنهاء...",
        homebrewOperationRefreshing: "جارٍ تحديث القائمة...",
        homebrewOperationTerminal: "تابِع في Terminal.",
        homebrewOperationElapsedFormat: "مضى %@",
        homebrewOperationShowDetails: "إظهار التفاصيل",
        homebrewOperationHideDetails: "إخفاء التفاصيل",
        homebrewOperationTechnicalLog: "التفاصيل التقنية",
        homebrewOperationProgressUnknown: "لم يبلّغ Homebrew عن نسبة مئوية بعد.",

        mediaName: "الوسائط",
        mediaEnableCaption: "اضغط الفيديوهات، وحوّل الصور وعالجها، وأنشئ ملفات GIF، واستخرج النصوص محليًا.",
        mediaLocalNote: "محلي. بلا شبكة.",
        mediaToolVideo: "فيديو",
        mediaToolGIF: "GIF",
        mediaToolImage: "صورة",
        mediaToolText: "نص",
        mediaSelectFile: "اختيار ملف",
        mediaDropHint: "أفلِت ملفًا هنا أو انقر لاختيار واحد.",
        mediaOutput: "الناتج",
        mediaOutputAutomatic: "تلقائي",
        mediaChooseOutput: "الوجهة",
        mediaStartVideo: "ضغط الفيديو",
        mediaStartGIF: "إنشاء GIF",
        mediaStartImage: "معالجة الصورة",
        mediaStartConvertPDF: "التحويل إلى PDF",
        mediaStartText: "استخراج النص",
        mediaCancel: "إلغاء",
        mediaStartTime: "البداية",
        mediaEndTime: "النهاية",
        mediaQuality: "الضغط",
        mediaCompressionLow: "منخفض",
        mediaCompressionMedium: "متوسط",
        mediaCompressionHigh: "مرتفع",
        mediaMaxSize: "الحجم",
        mediaSizingResolution: "الدقة",
        mediaSizingFileSize: "حجم الملف",
        mediaTargetSize: "الحجم المستهدف",
        mediaTargetSizeHint: "تتكيف الدقة للبقاء دون الحد.",
        mediaErrorTargetTooSmall: "الحجم المستهدف أصغر من أن يناسب هذا المقطع. اقتصّه أو ارفع الحد.",
        mediaMegabytesSuffix: " ميغابايت",
        mediaWidth: "العرض",
        mediaFPS: "إطار/ث",
        mediaKeepAudio: "الاحتفاظ بالصوت",
        mediaCodec: "المرمّز",
        mediaFormat: "الصيغة",
        mediaStripMetadata: "إزالة البيانات الوصفية",
        mediaLoopGIF: "تكرار GIF",
        mediaOCRMode: "التعرف على النص",
        mediaOCRAccurate: "دقيق",
        mediaOCRFast: "سريع",
        mediaLanguageCorrection: "تصحيح لغوي",
        mediaTextOutputNote: "يمكن نسخ النص المستخرج وحفظه كملف TXT.",
        mediaRunning: "جارٍ المعالجة",
        mediaCompleted: "تم",
        mediaCancelled: "تم الإلغاء.",
        mediaOpenInFinder: "الإظهار",
        mediaCopyText: "نسخ النص",
        mediaRunAgain: "التشغيل مجددًا",
        mediaEmptyText: "لم يتم العثور على نص.",
        mediaResultSavedFormat: "تم الحفظ باسم %@",
        mediaResultSizeFormat: "من %@ إلى %@",
        mediaResultGrewCaption: "جاء الملف المحوَّل أكبر من الأصل.",
        mediaErrorNoFile: "اختر ملفًا أولًا.",
        mediaErrorNoVideo: "لا يحتوي هذا الملف على مسار فيديو.",
        mediaErrorSameOutput: "اختر وجهة مختلفة عن الملف الأصلي.",
        mediaErrorUnsupported: "الصيغة غير مدعومة في macOS.",

        shelfName: "الرف",
        shelfEnable: "منطقة مؤقتة لسحب الملفات",
        shelfEnableCaption: "موضع عائم لجمع الملفات والصور والنصوص، ثم سحبها إلى أي مكان لاحقًا.",
        shelfHowTitle: "طريقة الاستخدام",
        shelfStep1: "افتحه بالاختصار، أو بهزّ الماوس أثناء السحب.",
        shelfStep2: "أفلِت عليه الملفات أو الصور أو الروابط أو النصوص للاحتفاظ بها.",
        shelfStep3: "اسحب كل عنصر منه إلى أي تطبيق عند الحاجة.",
        shelfShakeToggle: "الفتح بهزّ الماوس أثناء السحب",
        shelfShakeCaption: "هزّ المؤشر بسرعة أثناء إمساكك بعنصر لاستدعائه قرب المؤشر.",
        shelfDropZoneToggle: "إبقاء الملفات المسحوبة في شريط القائمة",
        shelfDropZoneCaption: "أثناء سحبك لملف، يظهر الرف أسفل أيقونة شريط القائمة. ويُحفظ ما تفلته هناك مباشرةً، في زر يمكنك تصغيره وفتحه بنقرة، ويختفي متى فرغ الرف.",
        shelfDropZoneLabel: "أفلِت هنا",
        shelfCollapse: "طي",
        shelfBehaviorTitle: "بعد الاستخدام",
        shelfCloseAfterDrop: "الإغلاق بعد الإفلات في تطبيق آخر",
        shelfCloseAfterDropCaption: "يغلق الرف عندما تقبل الوجهة العناصر. والتثبيت في اللوحة يُبقيه مفتوحًا.",
        shelfRemoveAfterDrop: "إزالة العناصر بعد الإفلات",
        shelfRemoveAfterDropCaption: "تغادر الرفَّ العناصرُ التي قبلها تطبيق آخر. أوقف هذا للاحتفاظ بنسخة فيه.",
        shelfExclusionsTitle: "الاستثناءات التلقائية",
        shelfExclusionsEmpty: "لم تُضف أي تطبيقات.",
        shelfExclusionsCaption: "تبقى الهزّة ومنطقة الإفلات في شريط القائمة متوقفتين لعمليات السحب التي تبدأ في هذه التطبيقات. ويظل الاختصار و«الفتح الآن» يعملان.",
        shelfPin: "الإبقاء مفتوحًا",
        shelfUnpin: "السماح بالإغلاق بعد الاستخدام",
        extraBrightnessName: "سطوع إضافي",
        extraBrightnessCaption: "يستخدم مجال HDR في الشاشة لتجاوز أقصى سطوع. ويستهلك بطارية أكثر وقد يسخن الـ Mac.",
        extraBrightnessLevelLabel: "الشدة",
        extraBrightnessUnsupported: "متاح على شاشات XDR فقط، مثل شاشات MacBook Pro مقاس 14 و16 بوصة.",
        shelfHotkeyLabel: "الاختصار",
        shelfOpenNow: "الفتح الآن",
        shelfNoPermission: "لا يتطلب أي أذونات.",
        shelfMenuItem: "فتح الرف",
        shelfTitle: "الرف",
        shelfEmpty: "اسحب العناصر إلى هنا",
        shelfClearAll: "مسح الكل",
        shelfRemoveSelected: "إزالة المحدد",
        shelfSelectedFormat: "%d محدد",
        shelfHint: "انقر للتحديد. واسحب للخارج للاستخدام أو انقر بالزر الأيمن لمزيد من الإجراءات.",
        shelfItemImage: "صورة",
        shelfTooltipItemsFormat: "%d عنصر",
        shelfTooltipImageSingular: "%d صورة",
        shelfTooltipImagePlural: "%d صورة",
        shelfTooltipFileSingular: "%d ملف",
        shelfTooltipFilePlural: "%d ملف",
        shelfTooltipNoteSingular: "%d ملاحظة",
        shelfTooltipNotePlural: "%d ملاحظة",
        shelfTooltipLinkSingular: "%d رابط",
        shelfTooltipLinkPlural: "%d رابط",
        shelfActionOpen: "فتح",
        shelfActionOpenWith: "فتح باستخدام",
        shelfActionAirDrop: "المشاركة عبر AirDrop",

        breakdownMeasuring: "جارٍ القياس…",

        mixerSection: "خالط الصوت",
        mixerEmpty: "تظهر هنا التطبيقات التي تستخدم الصوت",
        mixerUnavailable: "متاح على macOS 14.4 وأحدث",
        mixerPermissionBody: "لضبط مستوى الصوت لكل تطبيق، اسمح بـ «تسجيل الشاشة وصوت النظام» في إعدادات النظام. ولا يُسجَّل الصوت أبدًا.",
        mixerResetTooltip: "إعادة التعيين إلى 100%",
        mixerOutputDefault: "افتراضي",
        mixerOutputCurrent: "الحالي",
        mixerOutputUnavailable: "المخرج غير متاح",
        mixerOutputFallback: "يُستخدم الافتراضي حتى يعود هذا الجهاز.",
        mixerBypassedCaption: "يدير هذا التطبيق صوته بنفسه.",
        mixerOutputTooltip: "اختيار المخرج",
        mixerSystemOutputTitle: "المخرج",
        mixerSystemOutputNoDevices: "لم يتم العثور على مخارج",
        mixerSystemOutputTooltip: "اختيار مخرج النظام",
        mixerSystemOutputErrorFormat: "تعذّر التبديل: %@",
        mixerLowerOnHeadphonesDisconnect: "خفض الصوت عند فصل السماعات",
        mixerLowerOnHeadphonesDisconnectCaption: "يضبط المخرج عند فصل السماعات السلكية أو البلوتوث.",
        mixerHeadphonesDisconnectVolume: "مستوى الصوت بعد الفصل",
        preciseVolumeRollerEnable: "استخدام خطوات أدق للصوت",
        preciseVolumeRollerCaption: "يحوّل عجلات الصوت ومفاتيحه إلى خطوات أصغر في مستوى صوت النظام.",
        preciseVolumeRollerTapFailed: "تعذّر مراقبة مفاتيح الصوت.",
        soundOutputSwitcherTitle: "مبدّل المخارج",
        soundOutputSwitcherEnable: "تبديل المخارج بالاختصار",
        soundOutputSwitcherCaption: "اختر المخارج واستخدم الاختصار للانتقال إلى المخرج المتاح التالي.",
        soundOutputSwitcherDevices: "المخارج المشمولة بالتنقل",
        soundOutputSwitcherNoAvailableSelection: "اختر مخرجًا متاحًا واحدًا على الأقل.",
        mixerInputTitle: "الميكروفون",
        mixerInputNoDevices: "لم يتم العثور على ميكروفونات",
        mixerInputUnavailable: "الميكروفون غير متاح",
        mixerInputFallback: "يُستخدم الافتراضي حتى يعود هذا الميكروفون.",
        mixerInputTooltip: "اختيار الميكروفون",
        mixerInputErrorFormat: "تعذّر التبديل: %@",
        mixerVisibleApps: "التطبيقات في القائمة",
        mixerAllShown: "الكل",
        mixerHiddenCountLabel: "مخفية",
        mixerHideFromList: "الإخفاء من القائمة",

        updatesSection: "التحديثات",
        autoCheckToggle: "التحقق من التحديثات تلقائيًا",
        includeBetaUpdatesToggle: "تلقّي التحديثات التجريبية",
        includeBetaUpdatesCaption: "تتضمن الإصدارات التجريبية مزايا قيد التطوير وقد تحتوي على علل أو سلوك غير مكتمل.",
        betaBadgeLabel: "تجريبي",
        checkNowButton: "التحقق الآن",
        updateChecking: "جارٍ التحقق…",
        updateUpToDate: "أنت على أحدث إصدار.",
        updateAvailablePrefix: "يتوفر تحديث:",
        updateInstallButton: "التنزيل والتثبيت",
        updateDownloading: "جارٍ تنزيل التحديث…",
        updateInstalling: "جارٍ التثبيت وإعادة التشغيل…",
        updateFailedPrefix: "تعذّر التحقق:",
        updateLastChecked: "آخر تحقق:",
        updateNotifyTitle: "تحديث Vorssaint",
        updateInstallFailedBody: "نُزّل التحديث لكن تعذّر تطبيقه. نزّل أحدث إصدار من صفحة إصدارات GitHub واسحب التطبيق فوق النسخة الحالية.",
        updateNeedsApplicationsTitle: "انقل Vorssaint إلى «التطبيقات»",
        updateNeedsApplicationsBody: "يعمل التطبيق من موضع لا يمكن تحديثه، مثل صورة القرص أو موقع نظام مؤقت. اسحب Vorssaint إلى مجلد «التطبيقات» وافتحه من هناك ثم حاول مجددًا.",
        menuCheckUpdates: "التحقق من التحديثات…",

        permissionRequired: "الإذن مطلوب",
        permissionAccessibility: "إمكانية الوصول",
        permissionScreenRecording: "تسجيل الشاشة",
        permissionGranted: "ممنوح",
        permissionMissing: "غير ممنوح",
        permissionOpenSettings: "فتح إعدادات النظام…",
        permissionRequest: "منح الوصول",
        permissionRestartNote: "قد يطلب macOS إعادة فتح التطبيق بعد المنح.",

        aboutDescription: "مركز أدوات للـ Mac.\nالطاقة، ومراقبة النظام، والتمرير، ومبدّل النوافذ، في شريط القائمة مباشرةً.",
        versionPrefix: "الإصدار",
        reviewIntro: "مراجعة المقدمة",
        reviewHighlights: "مراجعة أبرز الجديد",
        viewOnGitHub: "العرض على GitHub",

        obContinue: "متابعة",
        obBack: "رجوع",
        obSkipStep: "تخطي هذه الخطوة",
        obStart: "فتح Vorssaint",
        obStepWelcomeTitle: "مرحبًا بك في Vorssaint",
        obStepWelcomeBody: "أداة هادئة في شريط القائمة تجعل استخدام macOS اليومي أكثر عملية.",
        obWelcomeBullet1Title: "الطاقة تحت السيطرة",
        obWelcomeBullet1Body: "أبقِ الـ Mac مستيقظًا للمدة التي تريدها، حتى والغطاء مغلق.",
        obWelcomeBullet2Title: "رؤية واضحة للنظام",
        obWelcomeBullet2Body: "حرارة المعالج وبطاقة الرسوم والبطارية، واستخدام العتاد، وضغط الذاكرة، لحظة بلحظة.",
        obWelcomeBullet3Title: "الماوس والنوافذ على طريقتك",
        obWelcomeBullet3Body: "تمرير معكوس للماوس ومبدّل نوافذ بمصغّرات.",
        obLanguageLabel: "اللغة",
        obStepAccessibilityTitle: "إمكانية الوصول",
        obStepAccessibilityBody: "مطلوبة لعكس تمرير الماوس ولاستجابة مبدّل النوافذ للوحة المفاتيح.",
        obAccessibilityWhy: "يراقب التطبيق عجلة الماوس واختصار المبدّل فقط. ولا يُسجَّل شيء ولا يُرسل إلى أي مكان.",
        obStepRecordingTitle: "تسجيل الشاشة",
        obStepRecordingBody: "يتيح للمبدّل عرض مصغّرات حقيقية للنوافذ بدلًا من الأيقونات وحدها.",
        obRecordingWhy: "تُنشأ المصغّرات لحظيًا وتبقى في الذاكرة ولا تغادر الـ Mac أبدًا. وبدونها يظل المبدّل يعمل بالأيقونات.",
        obStepMonitorTitle: "مراقبة النظام",
        obStepMonitorBody: "تعرض اللوحة حرارة المعالج وبطاقة الرسوم والبطارية، واستخدام العتاد، وضغط الذاكرة.",
        obMonitorNoPermission: "لا حاجة إلى إذن. تُقرأ المستشعرات من النظام مباشرةً.",
        obStepOptionalTitle: "مزايا اختيارية",
        obStepOptionalBody: "فعّل ما تريد استخدامه الآن. ويمكن تغيير كل شيء لاحقًا من الإعدادات.",
        obStepStatusTitle: "الفحص",
        obStepStatusBody: "تأكّد من جاهزية كل شيء للمزايا التي تريدها.",
        obStatusRecheck: "التحقق مجددًا",
        obStepDoneTitle: "كل شيء جاهز!",
        obStepDoneBody: "أصبح Vorssaint يعتني بالـ Mac الخاص بك.",
        obDoneHint: "ابحث عن الثقب الأسود في شريط القائمة، أعلى يمين الشاشة.",
        obWhatsNewTitle: "الجديد في هذا الإصدار",
        obWhatsNewFallback: "يتضمن هذا التحديث أحدث الإصلاحات والتحسينات.",
        obLanguageUpdateTitle: "الآن بلغتك",
        obLanguageUpdateBody: "أصبح Vorssaint يتحدث عدة لغات. اختر اللغة التي تريد استخدامها؛ ويمكنك تغييرها في أي وقت من الإعدادات.",
        obPurposeTitle: "ما الذي جاء بك إلى هنا؟",
        obPurposeBody: "اختر إعدادًا جاهزًا أو حدد بالضبط ما تريد استخدامه.",
        obPurposeSkip: "يمكنك إضافة المزايا أو إزالتها لاحقًا من الإعدادات.",

        tabMonitor: "المراقبة",
        monitorMenuBarSection: "في شريط القائمة",
        monitorMenuBarCaption: "اختر ما يظهر بجوار الأيقونة في شريط القائمة.",
        monitorCombineTemperatures: "دمج الاستخدام والحرارة",
        monitorCombineTemperaturesCaption: "عند تفعيل الاستخدام والحرارة للعنصر نفسه، يُعرضان في كتلة واحدة.",
        monitorSeparateMenuBarMetrics: "فصل المقاييس في عناصر مستقلة",
        monitorSeparateMenuBarMetricsCaption: "يفصل الكتل النشطة في شريط القائمة ويُبقي الاستخدام والحرارة معًا عند تفعيل الدمج.",
        monitorNetworkUploadFirst: "الرفع فوق التنزيل",
        monitorShowCPU: "المعالج",
        monitorShowMemory: "الذاكرة",
        monitorShowNetwork: "الشبكة",
        monitorShowPowerLabel: "الطاقة",
        monitorIntervalLabel: "التحديث كل",
        monitorInterval1: "ثانية واحدة",
        monitorInterval2: "ثانيتان",
        monitorInterval5: "5 ثوانٍ",
        monitorPanelSection: "في اللوحة",
        panelNavigationMode: "التنقل في اللوحة بالأقسام",
        panelNavigationCaption: "يعرض قسمًا واحدًا في كل مرة. اختر «قائمة» لرؤية كل شيء في تمرير متصل.",
        panelFooterSections: "أقسام",
        panelFooterList: "قائمة",
        betaBadge: "تجريبي",
        betaFeatureWarning: "نسخة تجريبية. قد تصادف بعض العلل.",

        networkSection: "الشبكة",
        networkDownload: "التنزيل",
        networkUpload: "الرفع",
        networkThisSession: "هذه الجلسة",
        networkMeasuring: "جارٍ القياس…",
        networkApps: "التطبيقات التي تستخدم الشبكة",
        networkAppsIdle: "لا توجد تطبيقات تستخدم الشبكة الآن",

        diskSection: "الأقراص",
        diskUsed: "مستخدمة",
        diskFree: "حرة",
        diskAvailable: "متاحة",
        diskPurgeable: "قابلة للتفريغ",
        diskInternal: "داخلي",
        diskExternal: "خارجي",
        diskSelect: "اختيار قرص",
        diskRead: "قراءة",
        diskWrite: "كتابة",
        diskSMARTStatus: "الحالة",
        diskSMARTUnavailable: "بيانات SMART غير متاحة لهذا القرص",
        diskTotalRead: "إجمالي القراءة",
        diskTotalWritten: "إجمالي الكتابة",
        diskTemperature: "درجة الحرارة",
        diskHealth: "السلامة",
        diskPowerCycles: "دورات التشغيل",
        diskPowerOnHours: "ساعات التشغيل",
        diskUnsafeShutdowns: "الإيقافات غير الآمنة",
        diskMediaErrors: "أخطاء الوسائط",
        diskEject: "إخراج",
        diskEjectAll: "إخراج الكل",
        diskEjecting: "جارٍ الإخراج…",
        diskReadyToRemove: "جاهز للفصل",
        diskEjectFailed: "تعذّر الإخراج",
        diskProtectionCaption: "أخرِج القرص قبل فصله.",
        diskNoExternal: "لا يوجد قرص خارجي جاهز للإخراج.",
        diskOpenInFinder: "فتح",
        diskStorageSettings: "التخزين",
        diskNoDisks: "لم يتم العثور على أقراص موصولة.",

        powerSection: "الطاقة",
        powerSystem: "النظام",
        powerAdapter: "المحوّل",
        powerBattery: "البطارية",
        powerCharging: "قيد الشحن",
        powerOnBattery: "على البطارية",
        powerPluggedIn: "موصول بالطاقة",
        powerUnavailable: "مقاييس الطاقة غير متاحة على هذا الـ Mac",
        powerAdapterMaxFormat: "%@ كحد أقصى",
        monitorShowGPU: "بطاقة الرسوم",
        monitorShowCPUTemperature: "حرارة المعالج",
        monitorShowGPUTemperature: "حرارة بطاقة الرسوم",
        monitorShowBatteryTemperature: "حرارة البطارية",
        monitorShowPeripheralBattery: "بطارية الملحقات",
        peripheralBatteryNoDevices: "لم يتم العثور على أجهزة",
        monitorGraphsSection: "الرسوم البيانية",
        monitorGraphsCaption: "اختر المقاييس التي تُعرض في رسم بياني عبر الزمن.",

        updateBannerTitle: "يتوفر تحديث",
        updateBannerAction: "تحديث",
        obStepMenuBarTitle: "المقاييس في شريط القائمة",
        obStepMenuBarBody: "اختر ما يظهر بجوار الأيقونة. وتتحدث المعاينة أعلاه مباشرةً.",
        obStepMenuBarNote: "جديد: كتل الشبكة والطاقة والرسوم البيانية في اللوحة. اضبط كل ذلك لاحقًا في الإعدادات › المراقبة.",
        monitorMenuBarPresetLabel: "النمط",
        menuBarPresetReadable: "واضح",
        menuBarPresetDense: "مكثف",
        menuBarSpacingLabel: "تباعد شريط القائمة",
        menuBarSpacingStandard: "قياسي",
        menuBarSpacingCompact: "مضغوط",
        menuBarHideIconToggle: "إخفاء أيقونة التطبيق أثناء عرض المقاييس",
        menuBarHideIconCaption: "تعود الأيقونة تلقائيًا عندما تغادر المقاييس الشريط وعندما يكون هناك ما يستدعي التنبيه (تحديث جاهز أو ميكروفون مكتوم).",
        monitorLabelStyleLabel: "التسميات",
        menuBarLabelStyleCompact: "مضغوطة",
        menuBarLabelStyleClassic: "كلاسيكية",
        monitorMemoryStyleLabel: "عرض الذاكرة كـ",
        monitorMemoryPressureDot: "نقطة الضغط",
        memoryStyleDot: "نقطة",
        memoryStylePercent: "%",
        memoryStyleBoth: "كلاهما",
        systemUptime: "يعمل منذ",
        batteryCharge: "الشحن",
        powerHealth: "سلامة البطارية",
        powerCycles: "الدورات",
        speedTestRun: "اختبار السرعة",
        speedTestAgain: "إعادة الاختبار",
        speedTestLatency: "زمن الاستجابة",
        speedTestTesting: "جارٍ الاختبار…",
        speedTestFailed: "فشل الاختبار",

        monitorShowInPanel: "الإظهار في اللوحة",
        disclosureExpanded: "موسّع",
        disclosureCollapsed: "مطوي",
        panelHideItem: "الإخفاء من اللوحة",
        panelShowItem: "الإظهار في اللوحة",
        panelHiddenItem: "مخفي",
        monitorItemUptime: "مدة التشغيل",
        monitorItemNetSpeed: "السرعة الحالية",
        monitorItemNetTotals: "إجماليات الجلسة",
        monitorItemNetTest: "اختبار السرعة",
        monitorItemDiskUsage: "استخدام القرص",
        monitorItemDiskActivity: "النشاط الحالي",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "حماية الأقراص الخارجية",
        monitorItemDiskTools: "الأدوات",
        monitorPanelConfigHint: "افتح كتلة لاختيار ما تعرضه.",
        monitorOrderSection: "ترتيب الأقسام",
        monitorOrderHint: "اسحب لإعادة ترتيب أقسام اللوحة واستخدم العين لإظهار كل قسم أو إخفائه.",
        obStepPanelTitle: "ما في اللوحة",
        obStepPanelBody: "افتح كل كتلة واختر بالضبط ما يظهر عند نقر الأيقونة.",
        obStepPanelNavigationTitle: "لوحة بالأقسام",
        obStepPanelNavigationBody: "أصبح بإمكان اللوحة عرض قسم واحد في كل مرة. ويمكنك التبديل بين «أقسام» و«قائمة» من الإعدادات.",

        cleaningMenuItem: "وضع التنظيف",
        utilitiesSection: "الأدوات",
        quickControlsSection: "عناصر التحكم",
        panelCategoryWindows: "النوافذ",
        panelCategoryInput: "الماوس ولوحة المفاتيح",
        panelCategoryFiles: "الملفات",
        windowMaximizeName: "تكبير النوافذ",
        windowMaximizeCaption: "الزر الأخضر يكبّر دون إنشاء مساحة جديدة.",
        windowMaximizeActiveNow: "تجاوز الزر الأخضر نشط",
        windowMaximizeNeedsAccessibility: "يحتاج إلى إمكانية الوصول ليعمل.",
        keyDebounceName: "تصفية التكرار",
        keyDebounceEnable: "تصفية المفاتيح المكررة",
        keyDebounceCaption: "يصفّي ضغطات المفاتيح المكررة السريعة جدًا.",
        keyDebounceActiveNow: "التصفية نشطة",
        keyDebounceGlobalWindow: "النافذة الزمنية العامة",
        keyDebouncePerKeySection: "مفاتيح محددة",
        keyDebouncePerKeyCaption: "تتجاوز قيم المفاتيح الفردية النافذة العامة. استخدم 0 مللي ثانية لإيقاف تصفية مفتاح.",
        keyDebounceKeyLabel: "المفتاح",
        keyDebounceWindowLabel: "النافذة الزمنية",
        keyDebounceAddKey: "إضافة مفتاح",
        keyDebounceNoOverrides: "لم تُضبط أي مفاتيح محددة.",
        keyDebounceRemoveKey: "إزالة المفتاح",
        cleaningPanelCaption: "يقفل لوحة المفاتيح لتنظّفها بأمان.",
        cleaningOverlayTitle: "لوحة المفاتيح مقفلة للتنظيف",
        cleaningOverlaySubtitle: "اضغط Escape 5 مرات لإلغاء القفل",
        cleaningOverlayUnlock: "إلغاء القفل",
        cleaningOverlayMouseHint: "الماوس ولوحة التتبع لا يزالان يعملان",
        cleaningNeedsAxTitle: "إمكانية الوصول مطلوبة",
        cleaningNeedsAxBody: "لقفل لوحة المفاتيح بأمان، يحتاج Vorssaint إلى إذن إمكانية الوصول. امنحه من إعدادات النظام وحاول مجددًا.",

        tabSupport: "الدعم",
        shortcutsPageCaption: "حرّر كل اختصار عام من المزايا المثبتة على هذا الـ Mac. وتبقى الاختصارات غير المفعّلة محفوظة لكنها لا تعمل.",
        shortcutsPageTitle: "اختصارات لوحة المفاتيح",
        settingsSearchPlaceholder: "البحث في الإعدادات",
        donateHeading: "ساعِد Vorssaint على الاستمرار في النمو",
        donateMessage: "Vorssaint مجاني ومستقل وأبنيه في وقت فراغي. وإذا أردت المساهمة ماليًا، فإن Buy Me a Coffee يساعدني مباشرةً على مواصلة التطوير.",
        donateButton: "الدعم عبر Buy Me a Coffee",
        donateThanks: "شكرًا لوجودك هنا. 🖤",
        supportIntroTitle: "ساعِد Vorssaint على الاستمرار في النمو",
        supportIntroMessage: "إذا أردت دعم التطوير ماليًا، فإن Buy Me a Coffee هو المكان الوحيد لذلك.",
        supportIntroStarButton: "ضع نجمة لـ Vorssaint على GitHub",
        supportIntroStarMessage: "الدعم المالي ليس متوقعًا أبدًا. أما نجمة على GitHub فتساعد المزيد من الناس على اكتشاف Vorssaint وتُحدث فرقًا حقيقيًا في تطويره.",
        supportIntroCoffeeButton: "الدعم عبر Buy Me a Coffee",
        supportIntroLaterButton: "ليس الآن",
        supportIntroDoneButton: "تم",
        discordIntroTitle: "مجتمع Vorssaint على Discord في بدايته",
        discordIntroMessage: "مجتمع Vorssaint جديد ولا يزال قيد البناء. انضم مبكرًا لتتعرف على مستخدمين آخرين وتساعد في بناء مساحة مرحّبة حول التطبيق.",
        discordIntroBenefitHelp: "احصل على المساعدة وشارِك طرق عملك",
        discordIntroBenefitFeedback: "أبلِغ عن العلل واطلب التحسينات وشارِك في تحديد ما هو قادم",
        discordIntroBenefitPreviews: "اطّلع على العمل الجاري والمعاينات المبكرة وأخبار الإصدارات",
        discordIntroJoinButton: "الانضمام إلى مجتمع Discord",
        communityIntroTitle: "شاهِده قبل الجميع",
        communityIntroMessage: "رأى من يتابعونني على X عدة تغييرات في هذا التحديث قبل غيرهم. أنشر معاينات لما هو قادم وأشرح طريقة عمله، لتعرف الأساسيات قبل صدور التحديث. تابِعني لترى ما هو قادم!",
        communityIntroFollowButton: "متابعة ‎@vorssaint على X",
        homebrewOfficialIntroTitle: "الآن في فهرس Homebrew الرسمي",
        homebrewOfficialIntroMessage: "أصبح بالإمكان تثبيت Vorssaint مباشرةً من فهرس Homebrew الرسمي.",
        homebrewOfficialIntroInstallLabel: "تثبيت جديد",
        homebrewOfficialIntroMigrationTitle: "هل استخدمت المصدر القديم؟",
        homebrewOfficialIntroMigrationMessage: "أزِل المصدر مرة واحدة. ويبقى التطبيق وإعداداتك في مكانها.",
        homebrewOfficialIntroCopyButton: "نسخ الأمر",
        updateShowcaseTitle: "الجديد في 3.1.4",
        updateShowcaseMessage: "ألقِ نظرة سريعة على أبرز التحسينات في هذا التحديث.",
        updateShowcaseUnavailable: "تعذّر تحميل الفيديو في الوقت الحالي. ولا يزال بإمكانك المتابعة.",
        updateShowcaseRestart: "إعادة التشغيل",
        showMenuBarIcon: "إظهار أيقونة شريط القائمة",
        showMenuBarIconCaption: "إذا اختفت أيقونة Vorssaint (فقد يخفي macOS أيقونات شريط القائمة عند نفاد المساحة، وهو أمر شائع على أجهزة Mac ذات النتوء)، فأعِد فتح Vorssaint من «التطبيقات» أو Spotlight: فذلك يعيد بناء الأيقونة، وإن بقيت مخفية فتح هذه النافذة. والزر أعلاه يفعل الشيء نفسه متى استطعت الوصول إلى هنا. وإبقاء عدد أقل من أيقونات شريط القائمة، أو عدد أقل من مقاييس Vorssaint، يقلل احتمال حدوث ذلك كثيرًا.",
        menuBarIconStillHiddenTitle: "لا تزال الأيقونة مخفية",
        menuBarIconStillHiddenBody: "أُعيد بناء الأيقونة، لكن macOS لم يمنحها موضعًا ظاهرًا. والأرجح أن شريط القائمة نفدت مساحته: أزِل بعض أيقونات شريط القائمة (أو أغلِق تطبيقات ذات قوائم طويلة) وحاول مجددًا.",
        menuBarIconManagerHintFormat: "%@ مفتوح وقد يُبقي الأيقونة في قسمه المخفي. ابحث عن Vorssaint هناك، أو اضبط %@ لإظهار Vorssaint دائمًا.",
        shortcutRecording: "اضغط الاختصار الجديد",
        shortcutReset: "إعادة تعيين",
        shortcutNone: "بلا",
        shortcutClear: "إزالة الاختصار",
        shortcutInvalid: "استخدم Control أو Option أو Command على الأقل مع مفتاح.",
        shortcutPressKeys: "اضغط المفاتيح",
        shortcutEscapeHint: "Escape للإلغاء.",
        shortcutDeleteHint: "Delete للمسح.",
        shortcutNotCaptured: "لم يُلتقط شيء. فـ macOS أو تطبيق آخر يستخدم هذه المجموعة أصلًا. جرّب مجموعة أخرى.",
        shortcutConflictFormat: "هذا الاختصار مستخدم من قِبل %@.",
        shortcutUnavailable: "رفض macOS هذا الاختصار. اختر اختصارًا آخر.",
        shelfShortcutToggle: "اختصار الرف",
        switcherUsageHintFormat: "استمر بالضغط على %@ للتنقل؛ وأفلته لتفعيل النافذة. وShift أو ← للرجوع؛ وW لإغلاق النافذة؛ وQ لإنهاء التطبيق؛ وEsc للإلغاء.",
        musicBlockSection: "مفاتيح الوسائط",
        musicBlockTitle: "منع Music من الفتح تلقائيًا",
        musicBlockCaption: "لم يعد تطبيق Music يُفتح عند ضغط مفاتيح الوسائط. ولا يزال بإمكانك فتحه بنفسك.",
        musicBlockReplacementLabel: "الفتح بدلًا منه",
        musicBlockReplacementNone: "بلا",
        musicBlockChooseApp: "اختيار تطبيق…",
        cleanerName: "المنظّف",
        cleanerIntroTitle: "نظّف الـ Mac الخاص بك",
        cleanerIntroCaption: "يفحص بقايا التطبيقات الملغى تثبيتها وذاكرات التخزين المؤقت والسجلات والمهملات. تراجع كل شيء أولًا وتنتقل العناصر المزالة إلى المهملات.",
        cleanerScan: "فحص",
        cleanerScanning: "جارٍ الفحص…",
        cleanerCleaning: "جارٍ التنظيف…",
        cleanerCatLeftovers: "بقايا التطبيقات الملغى تثبيتها",
        cleanerCatLoginItems: "عناصر بدء تشغيل يتيمة",
        cleanerCatCaches: "ذاكرات التخزين المؤقت",
        cleanerCatLogs: "السجلات",
        cleanerCatDeveloper: "مخلفات التطوير",
        cleanerCatTrash: "المهملات",
        cleanerLeftoversNote: "عُثر عليها بالتحليل وتُركت بلا تحديد. تحقق من المسار قبل التحديد.",
        cleanerLoginItemsNote: "يختفي المدخل من «عناصر تسجيل الدخول» بعد إعادة تشغيل الـ Mac.",
        cleanerTrashNote: "إفراغ المهملات إجراء نهائي.",
        cleanerCatDeviceBackups: "نسخ iPhone الاحتياطية",
        cleanerDeviceBackupsCaption: "تشغل نسخ iPhone وiPad الاحتياطية القديمة حصة كبيرة من المساحة التي يسميها macOS «أخرى». أزِل ما لم تعد بحاجة إليه فقط؛ وستُنشأ نسخة جديدة عند توصيل الجهاز مرة أخرى.",
        cleanerNothingFound: "لا شيء لتنظيفه. الـ Mac الخاص بك مرتب.",
        cleanerClean: "تنظيف",
        cleanerDoneNote: "انتقلت العناصر إلى المهملات ويمكن استعادتها من هناك.",
        cleanerAgain: "إعادة الفحص",
        cleanerRevealInFinder: "الإظهار في Finder",
        cleanerPanelCaption: "بقايا التطبيقات وذاكرات التخزين المؤقت والسجلات",
        cleanerSafeSection: "تنظيف آمن",
        cleanerOptionalSection: "اختياري، راجِعه أولًا",
        cleanerCatOtherCaches: "ذاكرات تخزين مؤقت أخرى",
        cleanerCachesCaption: "ملفات مؤقتة تعيد التطبيقات بناءها بنفسها.",
        cleanerLogsCaption: "سجلات تشخيصية قديمة.",
        cleanerDeveloperCaption: "بقايا بناء Xcode والمحاكيات.",
        cleanerLoginItemsCaption: "مدخلات بدء تشغيل خلّفتها تطبيقات لم تعد موجودة.",
        cleanerLeftoversCaption: "ملفات خلّفتها تطبيقات ألغيت تثبيتها.",
        cleanerOtherCachesCaption: "إزالتها آمنة ولا تعطّل شيئًا. وقد تُفتح التطبيقات ببطء مرة واحدة ويُعاد تنزيل المحتوى المنزَّل مثل الموسيقى دون اتصال.",
        cleanerCleanSizeFormat: "تنظيف %@",
        cleanerScheduleTitle: "التنظيف التلقائي",
        cleanerScheduleOff: "متوقف",
        cleanerScheduleDaily: "يوميًا",
        cleanerScheduleWeekly: "أسبوعيًا",
        cleanerScheduleCaption: "ينظّف الجزء الآمن فقط تلقائيًا في الوقت المحدد وينقل كل شيء إلى المهملات.",
        cleanerScheduleLastFormat: "حرّر آخر تنظيف تلقائي %@.",
        cleanerAutoNotificationFormat: "تم تحرير %@ ونقله إلى المهملات.",
        cleanerScheduleNextFormat: "التنظيف التالي %@.",
        cleanerScheduleRanFormat: "آخر تنظيف تلقائي %@.",
        cleanerScheduleNotifyToggle: "الإشعار عند الانتهاء",
        cleanerNotifDenied: "إشعارات Vorssaint متوقفة في النظام.",
        cleanerNotifOpenSettings: "فتح إعدادات الإشعارات…",
        launchAtLoginNeedsApplications: "يعمل التطبيق من موضع لا يمكن فتحه عند تسجيل الدخول. اسحب Vorssaint إلى مجلد «التطبيقات» وافتحه من هناك ثم فعّل هذا مجددًا.",
        launchAtLoginNeedsApproval: "عنصر تسجيل الدخول مسجَّل لكنه لا يزال متوقفًا في إعدادات النظام. افتح إعدادات النظام › عام › عناصر تسجيل الدخول والامتدادات وفعّل Vorssaint ضمن «الفتح عند تسجيل الدخول».",
        ocrRemoveLineBreaksToggle: "إزالة فواصل الأسطر",
        ocrRemoveLineBreaksCaption: "يزيل فواصل الأسطر ليُلصق النص المنسوخ كفقرة واحدة.",
        ocrQRToggle: "قراءة رموز QR",
        ocrQRCaption: "إذا احتوت المنطقة على رمز QR، فسيُعرض محتواه لنسخه أو فتحه.",
        ocrQRCopied: "تم نسخ رمز QR",
        qrResultTitle: "رمز QR",
        qrResultCopy: "نسخ",
        qrResultOpen: "فتح الرابط",
        highlightsTitle: "الجديد في هذا التحديث",
        highlightsTitleClipboardRedesign: "حافظة بتصميم جديد",
        highlightsCaptionDockPreview: "أصبحت معاينة الـ Dock تعمل مع تفعيل تكبير الـ Dock",
        highlightsCaptionScreenshot: "اكتسبت أداة لقطة الشاشة عدسة بكسل وقراءة لرموز QR",
        highlightsCaptionSnippetLibrary: "قائمة مقاطع قابلة للبحث تكتب أي مقطع عند موضع المؤشر مباشرةً",
        highlightsCaptionCapturePalette: "أصبح اختصار واحد يفتح لوحة عائمة للقطات الشاشة والتسجيلات ونص الشاشة والألوان مع عناصر تحكم قريبة.",
        highlightsCaptionClipboardRedesign: "أصبح سجل الحافظة يُفتح كلوحة مضغوطة بصفوف مرتبة ومعاينة عند الطلب لقراءة العنصر كاملًا أو تحريره.",
        highlightsConfigure: "الإعداد",
        highlightsTry: "جرّبه",
        highlightsSeeAll: "عرض كل التغييرات",
        switcherCurrentSpaceOnly: "إظهار سطح المكتب الحالي فقط",
        switcherCurrentSpaceOnlyCaption: "يعرض نوافذ سطح المكتب الذي أنت فيه فقط. واختيار نافذة لا ينقلك أبدًا إلى سطح مكتب آخر.",
        shelfFileMissing: "لم يعد الملف موجودًا",
        previewSizeSmall: "صغير",
        mixerSoundEffectsOutputTitle: "أصوات النظام",
        mixerSoundEffectsOutputTooltip: "اختر مكان تشغيل التنبيهات والمؤثرات الصوتية",
        monitorOpenActivityMonitor: "فتح «مراقب النشاط»",
        dockClickHide: "النقر على أيقونة الـ Dock لإخفاء التطبيق",
        dockClickHideCaption: "يُخفى التطبيق النشط عند نقر أيقونته في الـ Dock. وانقر مجددًا لإعادته.",
        monitorMemoryMetricLabel: "قياس الذاكرة كـ",
        memoryMetricUsed: "الذاكرة المستخدمة",
        memoryMetricApp: "ذاكرة التطبيقات",
        keepAwakeRightClickToggle: "النقر بالزر الأيمن على أيقونة شريط القائمة يبدّل «الإبقاء مستيقظًا»",
        keepAwakeRightClickToggleCaption: "يحل محل قائمة السياق التي تظهر بالنقر بالزر الأيمن.",
        urlCleanerRulesTitle: "قواعد التنظيف",
        urlCleanerRulesCaption: "يُلحق الموقع هذه المعاملات بروابط المشاركة الخاصة به لتتبع مصدر الرابط. فإذا كان الاسم مفعّلًا، أُزيل عند تنظيف الرابط؛ وإذا كان متوقفًا، بقي. ويمكن حذف الأسماء التي تضيفها.",
        urlCleanerRulesCoverageCaption: "تغطي القائمة مسارات المشاركة المختلفة للموقع — صفحة الويب، والتطبيق، والغرفة المباشرة — ولهذا فهي طويلة؛ أما الرابط الحقيقي فيحمل عادةً اثنين إلى أربعة منها فقط.",
        urlCleanerRulesAllSites: "كل المواقع",
        urlCleanerRulesCountSingular: "معامل واحد",
        urlCleanerRulesCountPluralFormat: "%d معامل",
        urlCleanerRulesAddSite: "إضافة موقع",
        urlCleanerRulesParameterPlaceholder: "اسم المعامل",
        urlCleanerRulesMatchCaption: "اكتب الاسم الواقع يسار علامة = ، مثل utm_source. والاسم المطابق يزيل ذلك المعامل وحده من الرابط ويترك البقية كما هي.",
        urlCleanerRulesAddButton: "إضافة",
        urlCleanerRulesRemoveButton: "حذف الاسم",
        urlCleanerRulesRemoveSiteButton: "إيقاف كل قواعد هذا الموقع",
        urlCleanerRemovedFormat: "تمت إزالة %@",
        switcherSearchPin: "تثبيت البحث بمفتاح S",
        switcherSearchPinCaption: "يبدأ S بحثًا ويثبّت المبدّل مفتوحًا، فلا تعود الكتابة تنتج رموزًا خاصة عندما يستخدم اختصارك ⌥، ولا يعود البحث الذي يبدأ بـ Q أو W يغلق النافذة أو يُنهي التطبيق بالخطأ.",
        invertVerticalScroll: "عكس التمرير الرأسي",
        invertHorizontalScroll: "عكس التمرير الأفقي",
        switcherShowShortcutHints: "إظهار تلميحات الاختصارات",
        switcherShowShortcutHintsCaption: "يعرض اختصارات التطبيقات والنوافذ أسفل الأيقونات.",
        uninstallerHomebrewPackageFormat: "سيُزال %@ من Homebrew أيضًا.",
        shelfEdgeToggle: "الفتح قرب حافة الشاشة",
        shelfEdgeCaption: "اسحب ملفًا نحو حافة الشاشة ليطل الرف. أفلِته هناك، أو تراجَع فينسحب.",
        focusFollowsMouseName: "التركيز يتبع الماوس",
        focusFollowsMouseCaption: "يركّز على النافذة تحت المؤشر ويرفعها بعد توقف قصير.",
        focusFollowsMouseDelay: "تأخير التمرير",
        switcherMinimizedPlacementLabel: "النوافذ المصغّرة",
        switcherMinimizedPlacementNormal: "الترتيب العادي",
        switcherMinimizedPlacementEnd: "الوضع في النهاية",
        switcherMinimizedPlacementHidden: "إخفاء",
        switcherShowFullscreenWindows: "إظهار نوافذ ملء الشاشة",
        switcherScreenPlacementLabel: "الإظهار على",
        switcherScreenPlacementPointer: "الشاشة التي عليها المؤشر",
        switcherScreenPlacementMenuBar: "الشاشة التي عليها شريط القائمة",
        switcherScreenPlacementActiveWindow: "الشاشة التي عليها النافذة النشطة",
        switcherScreenPlacementCaption: "الشاشة التي يُفتح عليها المبدّل عند توصيل أكثر من شاشة."
    )
}
