// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Ελληνικά — Greek localization.
extension Strings {
    static let el = Strings(
        statusIdleTooltip: "Vorssaint: κανονική λειτουργία ύπνου",
        statusActiveUntil: "Vorssaint: ενεργό έως",
        statusActiveIndefinite: "Vorssaint: ενεργό επ’ αόριστον",
        menuEnableAwake: "Ενεργοποίηση αποτροπής ύπνου",
        menuDisableAwake: "Απενεργοποίηση αποτροπής ύπνου",
        menuActivateFor: "Ενεργοποίηση για…",
        menuSettings: "Ρυθμίσεις…",
        menuAbout: "Πληροφορίες για το Vorssaint",
        menuQuit: "Τερματισμός Vorssaint",
        menuHide: "Απόκρυψη Vorssaint",
        menuHideOthers: "Απόκρυψη άλλων",
        menuShowAll: "Εμφάνιση όλων",
        menuEdit: "Επεξεργασία",
        menuUndo: "Αναίρεση",
        menuRedo: "Επανάληψη",
        actionClear: "Εκκαθάριση",
        actionRemove: "Αφαίρεση",
        actionBack: "Πίσω",
        actionSearch: "Αναζήτηση",
        actionMute: "Σίγαση",
        actionUnmute: "Κατάργηση σίγασης",
        actionPlay: "Αναπαραγωγή",
        actionPause: "Παύση",
        menuCut: "Αποκοπή",
        menuCopy: "Αντιγραφή",
        menuPaste: "Επικόλληση",
        menuSelectAll: "Επιλογή όλων",
        menuWindow: "Παράθυρο",
        menuMinimize: "Ελαχιστοποίηση",
        menuZoom: "Μεγέθυνση",
        menuClose: "Κλείσιμο",

        minutes15: "15 λεπτά",
        minutes30: "30 λεπτά",
        hour1: "1 ώρα",
        hours2: "2 ώρες",
        hours4: "4 ώρες",
        hours8: "8 ώρες",
        indefinitely: "Επ’ αόριστον",
        indefinite: "Αόριστη διάρκεια",

        panelSettings: "Ρυθμίσεις",
        panelQuit: "Τερματισμός",
        panelHotkeyHint: "Εναλλαγή με συντόμευση",

        keepAwakeTitle: "Αποτροπή ύπνου",
        keepAwakeEndsIn: "Λήγει σε",
        keepAwakeUntilDisabled: "Ενεργό μέχρι να το απενεργοποιήσετε",
        keepAwakeNormalRules: "Το Mac ακολουθεί τις κανονικές ρυθμίσεις ενέργειας",
        keepAwakeUntilLabel: "Έως",
        keepAwakeUntilStart: "Έναρξη",
        keepAwakeOptions: "Επιλογές",
        keepAwakeMouseJiggle: "Ελαφρά μετακίνηση του δείκτη",
        keepAwakeMouseJiggleCaption: "Κατά τη διάρκεια μιας συνεδρίας, μετακινεί ελαφρά τον δείκτη στο επιλεγμένο χρονικό διάστημα.",
        keepAwakeMouseJiggleInterval: "Διάστημα",
        keepAwakeActiveIconLabel: "Ενεργό εικονίδιο",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Καφές",
        keepAwakeActiveIconEye: "Μάτι",
        keepAwakeActiveIconMoon: "Φεγγάρι",
        keepAwakeActiveIconLight: "Λαμπτήρας",
        keepAwakeIconTintLabel: "Χρώμα ενεργού εικονιδίου",
        keepAwakeIconTintOrange: "Πορτοκαλί",
        keepAwakeIconTintGreen: "Πράσινο",
        keepAwakeIconTintBlue: "Μπλε",
        keepAwakeIconTintPurple: "Μοβ",
        keepAwakeIconTintPink: "Ροζ",
        keepAwakeIconTintNone: "Χωρίς χρώμα",
        durationLabel: "Διάρκεια",
        clamshellTitle: "Συνέχιση λειτουργίας με κλειστό καπάκι",
        clamshellOnCaption: "Ο ύπνος είναι πλήρως απενεργοποιημένος. Προσέξτε την κατανάλωση ενέργειας",
        clamshellNeedsSession: "Εφαρμόζεται όταν είναι ενεργή η “Αποτροπή ύπνου”",
        clamshellReady: "Έτοιμο. Εναλλαγή χωρίς συνθηματικό",
        clamshellNeedsPassword: "Θα ζητηθεί μία φορά το συνθηματικό διαχειριστή",

        systemSection: "Σύστημα",
        temperatures: "Θερμοκρασίες",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Μπαταρία",
        usageSection: "Χρήση υλικού",
        memorySection: "Μνήμη",
        memoryPressure: "Πίεση μνήμης",
        memorySwapUsed: "Χρήση χώρου swap",
        memoryCompressed: "Συμπιεσμένη",
        memoryCachedFiles: "Αρχεία στη μνήμη cache",
        pressureNormal: "Κανονική",
        pressureWarning: "Προειδοποίηση",
        pressureCritical: "Κρίσιμη",
        monitorUnavailable: "Οι αισθητήρες δεν είναι διαθέσιμοι σε αυτό το Mac",
        energyAppsTitle: "Εφαρμογές που χρησιμοποιούν σημαντική ενέργεια",
        energyAppsIdle: "Καμία εφαρμογή δεν χρησιμοποιεί σημαντική ενέργεια",

        notifySessionEndedTitle: "Η συνεδρία έληξε",
        notifySessionEndedBody: "Ο χρόνος έληξε. Το Mac θα επανέλθει στην κανονική λειτουργία ύπνου.",
        notifyBatteryTitle: "Το Vorssaint απενεργοποιήθηκε",
        notifyBatteryBody: "Χαμηλή στάθμη μπαταρίας. Επαναφέρθηκε η κανονική λειτουργία ύπνου για προστασία της φόρτισης.",
        adminPromptClamshellOn: "Το Vorssaint χρειάζεται το συνθηματικό σας για να διατηρήσει το Mac σε λειτουργία με κλειστό καπάκι.",
        adminPromptClamshellOff: "Το Vorssaint χρειάζεται το συνθηματικό σας για να επαναφέρει την κανονική λειτουργία ύπνου του Mac.",
        adminPromptRecover: "Το Vorssaint τερματίστηκε ενώ ο ύπνος του Mac ήταν απενεργοποιημένος. Εισαγάγετε το συνθηματικό για να επαναφέρετε την κανονική λειτουργία ύπνου.",
        adminPromptUpdate: "Το Vorssaint χρειάζεται το συνθηματικό σας για να εγκαταστήσει την ενημέρωση.",
        adminPromptSudoersInstall: "Το Vorssaint θα δημιουργήσει έναν περιορισμένο κανόνα, μόνο για pmset disablesleep, ώστε να ενεργοποιεί ή να απενεργοποιεί τη λειτουργία με κλειστό καπάκι χωρίς να ζητά συνθηματικό. Αυτή είναι η μόνη φορά που απαιτείται το συνθηματικό.",
        adminPromptSudoersRemove: "Το Vorssaint θα αφαιρέσει τον κανόνα χωρίς συνθηματικό για τη λειτουργία με κλειστό καπάκι.",

        settingsTitle: "Ρυθμίσεις Vorssaint",
        tabGeneral: "Γενικά",
        tabEnergy: "Ενέργεια",
        tabMouse: "Ποντίκι και επιφάνεια αφής",
        tabSwitcher: "Εναλλαγή εφαρμογών",
        tabAdvanced: "Προηγμένα",
        tabAbout: "Πληροφορίες",
        tabReleaseNotes: "Τι νέο υπάρχει",
        releaseNotesOnUpdateToggle: "Εμφάνιση των νέων μετά την ενημέρωση",
        minimalWindowPreviews: "Απλοποιημένες προεπισκοπήσεις",
        minimalWindowPreviewsCaption: "Απόκρυψη τίτλων, κουμπιών και διακοσμητικών λεπτομερειών στις προεπισκοπήσεις του Dock και της εναλλαγής εφαρμογών. Η επιλογή παραμένει ορατή.",
        previewSizeLabel: "Μέγεθος προεπισκόπησης",
        previewSizeNormal: "Κανονικό",
        previewSizeLarge: "Μεγάλο",
        previewSizeXLarge: "Πολύ μεγάλο",
        settingsGroupFeatures: "Δυνατότητες",
        advancedResetSection: "Δικαιώματα",
        advancedResetDescription: "Αφαιρεί όλα τα δικαιώματα που έχετε παραχωρήσει στο Vorssaint (Προσβασιμότητα, Εγγραφή οθόνης και ήχου συστήματος, Πλήρης πρόσβαση στον δίσκο και άλλα), το στοιχείο σύνδεσης και τον κανόνα λειτουργίας με κλειστό καπάκι. Χρήσιμο για νέα αρχή ή πριν από την απεγκατάσταση. Η εφαρμογή παραμένει εγκατεστημένη.",
        advancedClearButton: "Αφαίρεση όλων των δικαιωμάτων",
        advancedCleared: "Τα δικαιώματα αφαιρέθηκαν.",
        advancedClearFailed: "Δεν ήταν δυνατή η αφαίρεση ορισμένων δικαιωμάτων ή του κανόνα λειτουργίας με κλειστό καπάκι. Δοκιμάστε ξανά και επιτρέψτε το αίτημα συνθηματικού, αν εμφανιστεί.",
        advancedClearConfirmTitle: "Να αφαιρεθούν όλα τα δικαιώματα;",
        advancedClearConfirmBody: "Οι δυνατότητες που απαιτούν δικαιώματα θα σταματήσουν να λειτουργούν μέχρι να τα παραχωρήσετε ξανά. Οι ρυθμίσεις σας θα διατηρηθούν.",
        advancedUninstallSection: "Απεγκατάσταση",
        advancedUninstallDescription: "Εκτελεί όλα τα παραπάνω και στη συνέχεια αφαιρεί τις προτιμήσεις και μετακινεί το Vorssaint στον Κάδο, χωρίς να αφήνει υπολείμματα. Η εφαρμογή τερματίζεται όταν ολοκληρωθεί η διαδικασία. Μπορείτε να την εγκαταστήσετε ξανά οποιαδήποτε στιγμή.",
        advancedUninstallButton: "Πλήρης απεγκατάσταση του Vorssaint",
        advancedUninstallConfirmTitle: "Να απεγκατασταθεί το Vorssaint;",
        advancedUninstallConfirmBody: "Το Vorssaint θα αφαιρέσει τα δικαιώματά του, θα διαγράψει τις προτιμήσεις του, θα μετακινηθεί στον Κάδο και στη συνέχεια θα τερματιστεί. Αυτό δεν μπορεί να αναιρεθεί από την εφαρμογή, αλλά το Vorssaint θα παραμείνει στον Κάδο μέχρι να τον αδειάσετε.",
        advancedUninstallFailedTitle: "Η απεγκατάσταση διακόπηκε",
        advancedUninstallFailedBody: "Το Vorssaint δεν μπόρεσε να επαναφέρει μια ρύθμιση συστήματος που είχε αλλάξει: ύπνο, ταχύτητα ανεμιστήρα ή επιτάχυνση ποντικιού. Δεν αφαιρέθηκε τίποτα. Δοκιμάστε ξανά και επιτρέψτε το αίτημα συνθηματικού, αν εμφανιστεί.",

        launchAtLogin: "Άνοιγμα κατά τη σύνδεση",
        languageLabel: "Γλώσσα",
        menuBarSection: "Γραμμή μενού",
        showCountdown: "Εμφάνιση υπολειπόμενου χρόνου δίπλα στο εικονίδιο",
        globalHotkeySection: "Καθολική συντόμευση",
        hotkeyToggle: "Ενεργοποίηση συντόμευσης για “Αποτροπή ύπνου”",
        hotkeyCaption: "Λειτουργεί σε οποιαδήποτε εφαρμογή, χωρίς πρόσθετα δικαιώματα.",

        sessionSection: "Συνεδρία",
        defaultDurationLabel: "Προεπιλεγμένη διάρκεια",
        keepAwakeAutoStart: "Αποτροπή ύπνου κατά το άνοιγμα του Vorssaint",
        keepAwakeAutoStartCaption: "Ξεκινά μια συνεδρία με την προεπιλεγμένη διάρκεια.",
        batteryProtectionSection: "Προστασία μπαταρίας",
        batteryDisableBelow: "Απενεργοποίηση όταν η μπαταρία πέσει κάτω από",
        batteryNever: "Ποτέ",
        batteryProtectionCaption: "Αποτρέπει την εξάντληση της μπαταρίας του MacBook από μια ξεχασμένη συνεδρία.",
        clamshellSection: "Κλειστό καπάκι",
        configuring: "Διαμόρφωση…",
        sudoersFailed: "Δεν ήταν δυνατή η ενεργοποίηση της λειτουργίας με κλειστό καπάκι. Δοκιμάστε ξανά.",
        clamshellExplanation: "Η “Συνέχιση λειτουργίας με κλειστό καπάκι” απενεργοποιεί πλήρως τον ύπνο όσο είναι ενεργή η “Αποτροπή ύπνου” και αναιρείται αυτόματα όταν λήξει η συνεδρία ή τερματιστεί η εφαρμογή. Προτιμήστε τη χρήση με το Mac συνδεδεμένο στο ρεύμα.",
        dimScreenOnLidCloseTitle: "Μείωση φωτεινότητας οθόνης στο μηδέν",
        dimScreenOnLidCloseCaption: "Μειώνει τη φωτεινότητα της οθόνης όταν κλείνει το καπάκι και την επαναφέρει όταν ανοίγει.",

        scrollSection: "Κύλιση",
        invertMouseScroll: "Αντιστροφή κύλισης ποντικιού",
        invertMouseScrollCaption: "Αντιστρέφει την κατεύθυνση του τροχού κύλισης του ποντικιού.",
        scrollTrackpadNote: "Η επιφάνεια αφής δεν επηρεάζεται: διατηρεί τη φυσική κύλιση του macOS.",
        scrollActiveNow: "Η κύλιση του ποντικιού είναι ανεστραμμένη αυτήν τη στιγμή",
        mouseNavigationActiveNow: "Τα πλευρικά κουμπιά είναι ενεργά αυτήν τη στιγμή",
        smoothScrollName: "Ομαλή κύλιση",
        smoothScrollCaption: "Μετατρέπει κάθε βήμα του τροχού κύλισης του ποντικιού σε σύντομη, ομαλή κίνηση. Η επιφάνεια αφής δεν επηρεάζεται.",
        smoothScrollStepLabel: "Ταχύτητα κύλισης",
        mouseNavigationSection: "Πλοήγηση",
        mouseNavigationEnable: "Χρήση των πλευρικών κουμπιών για Πίσω και Εμπρός",
        mouseNavigationCaption: "Μετατρέπει τα κουμπιά Πίσω και Εμπρός του ποντικιού σε εντολές πλοήγησης στο Finder, σε προγράμματα περιήγησης και σε συμβατές εφαρμογές.",
        middleClickSection: "Μεσαίο κλικ",
        middleClickEnable: "Κλικ με τρία δάχτυλα ως μεσαίο κλικ",
        middleClickEnableCaption: "Το πάτημα της επιφάνειας αφής με τρία δάχτυλα λειτουργεί όπως το κλικ του τροχού ενός ποντικιού: ανοίγει συνδέσμους σε νέα καρτέλα, κλείνει καρτέλες και εκτελεί ό,τι κάνει το μεσαίο κουμπί.",
        middleClickDragConflict: "Η “Μεταφορά με τρία δάχτυλα” του macOS είναι ενεργοποιημένη και χρησιμοποιεί την ίδια χειρονομία. Απενεργοποιήστε την στις Ρυθμίσεις συστήματος > Προσβασιμότητα > Έλεγχος δείκτη > Επιλογές επιφάνειας αφής, ώστε να λειτουργήσει το μεσαίο κλικ.",
        middleClickNoTrackpad: "Δεν είναι δυνατή η ανάγνωση αγγιγμάτων στην επιφάνεια αφής. Συνδέστε μια υποστηριζόμενη επιφάνεια αφής.",
        middleClickTapPicker: "Το ελαφρύ άγγιγμα κάνει επίσης κλικ",
        middleClickTapOff: "Απενεργοποιημένο",
        middleClickTapThreeFingers: "3 δάχτυλα",
        middleClickTapFourFingers: "4 δάχτυλα",
        middleClickTapCaption: "Ένα ελαφρύ άγγιγμα με τόσα δάχτυλα, χωρίς πάτημα, ενεργοποιεί επίσης το μεσαίο κλικ. Η ολίσθηση δεν ενεργοποιεί ποτέ το κλικ. Αν το άγγιγμα με τρία δάχτυλα του macOS έχει αντιστοιχιστεί στην “Αναζήτηση”, απενεργοποιήστε το ώστε να μην ενεργοποιούνται και τα δύο μαζί.",
        quickToolsTab: "Γρήγορος πίνακας",
        quickToolShortcutToggle: "Καθολική συντόμευση",
        ocrName: "Αντιγραφή κειμένου από την οθόνη",
        ocrCaption: "Επιλέξτε μια περιοχή της οθόνης και το αναγνωρισμένο κείμενο αντιγράφεται, έτοιμο για επικόλληση.",
        ocrCopied: "Το κείμενο αντιγράφηκε",
        ocrNoText: "Δεν βρέθηκε κείμενο",
        colorPickerName: "Επιλογέας χρώματος",
        colorPickerCaption: "Επιλέξτε το χρώμα οποιουδήποτε pixel στην οθόνη και αντιγράψτε το στην προτιμώμενη μορφή σας.",
        colorPickerFormatLabel: "Μορφή αντιγραφής",
        colorPickerBareHexToggle: "Αντιγραφή χωρίς το πρόθεμα #",
        colorPickerPickNow: "Επιλογή χρώματος",
        micMuteName: "Σίγαση μικροφώνου",
        micUnmuteName: "Κατάργηση σίγασης μικροφώνου",
        micMuteCaption: "Θέτει σε σίγαση το μικρόφωνο του Mac με ένα κλικ ή μια συντόμευση, σε όλες τις εφαρμογές.",
        micMutedHUD: "Το μικρόφωνο τέθηκε σε σίγαση",
        micUnmutedHUD: "Η σίγαση του μικροφώνου καταργήθηκε",
        micMutePartialHUD: "Δεν ήταν δυνατή η σίγαση ορισμένων μικροφώνων",
        micUnmutePartialHUD: "Ορισμένα μικρόφωνα παραμένουν σε σίγαση",
        micMuteMenuBarToggle: "Εμφάνιση στη γραμμή μενού κατά τη σίγαση",
        micMuteMenuBarCaption: "Ένα κόκκινο διαγραμμένο εικονίδιο μικροφώνου εμφανίζεται δίπλα στο εικονίδιο της εφαρμογής στη γραμμή μενού.",
        pastePlainName: "Επικόλληση ως απλό κείμενο",
        pastePlainCaption: "Επικολλά ό,τι αντιγράψατε χωρίς χρώματα, γραμματοσειρές ή μορφοποίηση. Το πρωτότυπο παραμένει στο Πρόχειρο.",
        launcherName: "Γρήγορος πίνακας",
        launcherCaption: "Ένας αιωρούμενος πίνακας με τα αγαπημένα σας εργαλεία, που ανοίγει με μια συντόμευση από οπουδήποτε.",
        launcherOpenNow: "Άνοιγμα γρήγορου πίνακα",
        launcherEditHint: "Χρησιμοποιήστε το κουμπί ρυθμίσεων για να επιλέξετε, να αποκρύψετε και να αναδιατάξετε τα εργαλεία.",
        launcherEmptyState: "Όλα τα εργαλεία είναι κρυμμένα. Χρησιμοποιήστε το κουμπί ρυθμίσεων για να τα προσθέσετε ξανά.",
        launcherAddSection: "Επαναπροσθήκη",
        launcherKeysHint: "Τα βέλη μετακινούν την επιλογή, το Enter ανοίγει και τα πλήκτρα 1 έως 9 ανοίγουν απευθείας",

        switcherSection: "Εναλλαγή εφαρμογών",
        switcherEnable: "Χρήση εναλλαγής εφαρμογών του Vorssaint",
        switcherEnableCaption: "Εναλλαγή μεταξύ εφαρμογών και παραθύρων, συμπεριλαμβανομένων ελαχιστοποιημένων παραθύρων και πολλών παραθύρων της ίδιας εφαρμογής.",
        switcherUsageHint: "Κρατήστε πατημένη τη συντόμευση για πλοήγηση και αφήστε την για ενεργοποίηση του παραθύρου. Το Shift ή ← μετακινεί προς τα πίσω, το W κλείνει το παράθυρο, το Q τερματίζει την εφαρμογή και το Esc ακυρώνει.",
        switcherNoWindows: "Δεν υπάρχουν ανοιχτά παράθυρα",
        switcherIconRowMode: "Εμφάνιση %@ με μεγάλα εικονίδια",
        switcherIconRowModeCaption: "Εμφανίζει ένα εικονίδιο ανά εφαρμογή, με τις προεπισκοπήσεις των παραθύρων της από πάνω.",
        switcherSimpleModeCaption: "Εμφανίζει εικονίδια εφαρμογών και τίτλους παραθύρων, χωρίς προεπισκοπήσεις ή καταγραφή οθόνης από την εναλλαγή.",
        switcherShortcutHintApps: "Εφαρμογές",
        switcherShortcutHintWindows: "Παράθυρα",
        switcherWindowShortcutCaption: "Ανοίγει εναλλαγή για τα παράθυρα της εφαρμογής στο προσκήνιο. Όταν είναι ανοιχτή η εναλλαγή “Εφαρμογές”, μετακινείται μεταξύ των παραθύρων της επιλεγμένης εφαρμογής.",
        switcherTakeOverSystemShortcuts: "Αντικατάσταση των ⌘Tab και ⌘` του macOS",
        switcherTakeOverSystemShortcutsCaption: "Απενεργοποιεί τις αντίστοιχες συντομεύσεις εφαρμογών και παραθύρων του macOS μόνο όσο είναι ενεργή η εναλλαγή του Vorssaint. Όλες οι εφαρμογές που εκτελούνται παραμένουν προσβάσιμες.",
        switcherAppearanceDelay: "Καθυστέρηση εμφάνισης",
        switcherAppearanceDelayCaption: "Ο χρόνος που πρέπει να κρατήσετε πατημένη τη συντόμευση πριν εμφανιστεί η εναλλαγή.",
        switcherInstantSelection: "Άμεση επιλογή",
        switcherInstantSelectionCaption: "Μετακινεί αμέσως την επισήμανση και τη θέση κύλισης καθώς περιηγείστε σε εφαρμογές και παράθυρα.",
        switcherMergeTabs: "Μία καταχώριση ανά εφαρμογή",
        switcherMergeTabsCaption: "Συμπτύσσει όλα τα παράθυρα μιας εφαρμογής σε μία καταχώριση στην εναλλαγή, αντί για μία καταχώριση ανά παράθυρο.",
        switcherWindowlessApps: "Εφαρμογές χωρίς ανοιχτό παράθυρο",
        switcherWindowlessAppsCaption: "Επιλέγει ποιες εφαρμογές που εκτελούνται χωρίς κανένα ανοιχτό παράθυρο θα εμφανίζονται στην εναλλαγή.",
        switcherWindowlessAppsOff: "Να μην εμφανίζονται",
        switcherWindowlessAppsFinder: "Μόνο Finder",
        switcherWindowlessAppsAll: "Όλες οι εφαρμογές",
        switcherNoOpenWindow: "Χωρίς ανοιχτό παράθυρο",
        switcherOtherDesktop: "Άλλο γραφείο εργασίας",
        dockPreviewName: "Προεπισκόπηση Dock",
        dockPreviewEnable: "Προεπισκόπηση παραθύρων από το Dock",
        dockPreviewEnableCaption: "Μετακινήστε τον δείκτη πάνω από μια ανοιχτή εφαρμογή στο Dock για να δείτε τα παράθυρά της και μετά κάντε κλικ σε αυτό που θέλετε.",
        dockPreviewCurrentSpaceOnlyCaption: "Όταν είναι απενεργοποιημένο, εμφανίζονται παράθυρα από όλα τα γραφεία εργασίας. Αν επιλέξετε παράθυρο σε άλλο γραφείο εργασίας, μεταφέρεστε σε αυτό.",
        dockPreviewBackgroundOpacity: "Φόντο πίνακα",
        dockPreviewBackgroundOpacityCaption: "Μειώστε το για να βλέπετε περισσότερο από ό,τι βρίσκεται πίσω από τον πίνακα.",
        dockPreviewBackgroundOpacityGlassCaption: "Το Liquid Glass είναι ενεργό, επομένως η διαφάνεια του πίνακα ορίζεται στις Ρυθμίσεις συστήματος > Εμφάνιση.",
        dockPreviewOpenDelay: "Καθυστέρηση ανοίγματος",
        dockPreviewOpenDelayCaption: "Ο χρόνος που πρέπει να παραμείνει ο δείκτης πάνω σε ένα εικονίδιο πριν ανοίξει ο πίνακάς του.",
        dockPreviewQuitAppOnClose: "Τερματισμός εφαρμογής με το κουμπί ×",
        dockPreviewQuitAppOnCloseCaption: "Στην Προεπισκόπηση Dock, το × τερματίζει ολόκληρη την εφαρμογή αντί να κλείνει μόνο αυτό το παράθυρο.",
        dockPreviewKeepDockVisible: "Διατήρηση ορατού Dock (πειραματικό)",
        dockPreviewKeepDockVisibleCaption: "Παύει προσωρινά την αυτόματη απόκρυψη όσο είναι ανοιχτή η προεπισκόπηση και την επαναφέρει όταν απομακρυνθείτε. Ενδέχεται να αλλάξει το μέγεθος παραθύρων. Αν διακοπεί η εφαρμογή, ανοίξτε την ξανά για να επαναφέρετε το Dock.",
        dockPreviewOrderByCreation: "Ταξινόμηση παραθύρων κατά χρόνο δημιουργίας",
        dockPreviewOrderByCreationCaption: "Εμφανίζει πρώτα τα παλαιότερα παράθυρα αντί για εκείνα που χρησιμοποιήσατε πιο πρόσφατα.",
        dockClickMinimize: "Κλικ στο εικονίδιο του Dock για ελαχιστοποίηση",
        dockClickMinimizeCaption: "Τα παράθυρα της ενεργής εφαρμογής ελαχιστοποιούνται όταν κάνετε κλικ στο εικονίδιό της στο Dock. Κάντε ξανά κλικ για να τα επαναφέρετε.",
        dockClickCycleWindows: "Κλικ στο εικονίδιο του Dock για κυκλική εναλλαγή παραθύρων",
        dockClickCycleWindowsCaption: "Κάντε κλικ στο εικονίδιο μιας ενεργής εφαρμογής στο Dock για κυκλική μετακίνηση στα παράθυρά της, όπως με ⌘`.",
        dockPreviewActiveNow: "Ενεργό στο Dock",
        dockPreviewDockUnavailable: "Δεν ήταν δυνατή η ανάγνωση των στοιχείων του Dock.",
        dockPreviewAutohideBeta: "Έκδοση beta. Ενδέχεται να παρουσιαστούν ορισμένα σφάλματα.",
        dockPreviewOpenWindow: "Άνοιγμα παραθύρου",
        dockPreviewCloseWindow: "Κλείσιμο παραθύρου",
        dockPreviewMinimizeWindow: "Ελαχιστοποίηση παραθύρου",
        dockPreviewRestoreWindow: "Επαναφορά παραθύρου",
        dockPreviewPinPanel: "Καρφίτσωμα προεπισκόπησης",
        dockPreviewUnpinPanel: "Κατάργηση καρφιτσώματος προεπισκόπησης",
        dockPreviewPinned: "Καρφιτσωμένη",
        dockPreviewClosePanel: "Κλείσιμο προεπισκόπησης",
        dockPreviewPreviousWindow: "Προηγούμενο παράθυρο",
        dockPreviewNextWindow: "Επόμενο παράθυρο",

        cutPasteName: "Αποκοπή και επικόλληση",
        cutPasteEnable: "Αποκοπή και επικόλληση αρχείων στο Finder",
        cutPasteEnableCaption: "Χρησιμοποιήστε ⌘X για αποκοπή και ⌘V για μετακίνηση αρχείων και φακέλων στο Finder.",
        cutPasteShowHUD: "Εμφάνιση αιωρούμενου πίνακα",
        cutPasteShowHUDCaption: "Εμφανίζει μια αιωρούμενη ένδειξη με τα αρχεία που έχουν αποκοπεί όσο είναι ενεργό το Finder.",
        cutPasteHowTitle: "Τρόπος χρήσης",
        cutPasteStep1: "Επιλέξτε στοιχεία στο Finder και πατήστε ⌘X για αποκοπή.",
        cutPasteStep2: "Ανοίξτε τον φάκελο προορισμού και πατήστε ⌘V για να τα μετακινήσετε εκεί.",
        cutPasteTextNote: "Στα πεδία κειμένου, όπως κατά τη μετονομασία, τα ⌘X και ⌘V εξακολουθούν να λειτουργούν κανονικά.",
        cutPasteActiveNow: "Έτοιμο για αποκοπή στο Finder",
        cutPasteAutomationNote: "Την πρώτη φορά, το macOS ζητά άδεια για τον έλεγχο του Finder.",
        cutReadyTitle: "Αποκοπή",
        cutReadyHint: "στον φάκελο προορισμού για μετακίνηση",
        cutCancel: "Ακύρωση αποκοπής",
        cutDoneTitle: "Η μετακίνηση ολοκληρώθηκε",
        cutMovedSingular: "Μετακινήθηκε 1 στοιχείο",
        cutMovedPluralFormat: "Μετακινήθηκαν %d στοιχεία",
        cutSomeFailed: "Δεν ήταν δυνατή η μετακίνηση ορισμένων στοιχείων",
        cutMovingTitle: "Μετακίνηση…",
        cutMovingCountFormat: "%d από %d",

        autoQuitName: "Τερματισμός κατά το κλείσιμο",
        autoQuitEnable: "Τερματισμός εφαρμογής όταν κλείνει το τελευταίο παράθυρό της",
        autoQuitEnableCaption: "Με το κλείσιμο του τελευταίου παραθύρου μιας εφαρμογής τερματίζεται και η εφαρμογή.",
        autoQuitActiveNow: "Ενεργό τώρα",
        autoQuitHowTitle: "Τρόπος λειτουργίας",
        autoQuitStep1: "Κλείστε το τελευταίο παράθυρο μιας εφαρμογής (⌘W ή το κόκκινο κουμπί).",
        autoQuitStep2: "Η εφαρμογή τερματίζεται αυτόματα. Οι διάλογοι “Αποθήκευση αλλαγών;” εξακολουθούν να εμφανίζονται.",
        autoQuitPredictableNote: "Οι εφαρμογές που κανονικά εκτελούνται χωρίς παράθυρο δεν τερματίζονται ποτέ.",
        autoQuitOngoingWorkNote: "Ορισμένες εφαρμογές κλείνουν το τελευταίο παράθυρό τους ενώ συνεχίζουν να λειτουργούν, όπως μια εφαρμογή εγγραφής οθόνης μετά την έναρξη της εγγραφής. Και αυτές τερματίζονται, εκτός αν βρίσκονται στη λίστα Εξαιρέσεων.",
        autoQuitExceptionsTitle: "Εξαιρέσεις",
        autoQuitExceptionsCaption: "Οι εφαρμογές αυτής της λίστας παραμένουν ανοιχτές ακόμη και χωρίς παράθυρα.",
        autoQuitExceptionsEmpty: "Δεν υπάρχουν εξαιρέσεις",
        autoQuitAddApp: "Προσθήκη εφαρμογής…",

        uninstallerName: "Πρόγραμμα απεγκατάστασης",
        uninstallerEnableCaption: "Αφαιρεί μια εφαρμογή μαζί με τις μνήμες cache, τις προτιμήσεις, τα αρχεία καταγραφής και τα υπολείμματα που αφήνει πίσω.",
        uninstallerStep1: "Σύρετε μια εφαρμογή στις Ρυθμίσεις ή επιλέξτε μία από τη λίστα.",
        uninstallerStep2: "Ελέγξτε τα αρχεία που βρέθηκαν και τον χώρο που καταλαμβάνουν.",
        uninstallerStep3: "Μετακινήστε στον Κάδο όσα θέλετε. Τίποτα δεν διαγράφεται οριστικά.",
        uninstallerMenuItem: "Απεγκατάσταση εφαρμογής…",
        uninstallerDropTitle: "Σύρετε μια εφαρμογή εδώ",
        uninstallerDropSubtitle: "ή επιλέξτε μία για σάρωση",
        uninstallerChoose: "Επιλογή εφαρμογής…",
        uninstallerPickerTitle: "Επιλογή εφαρμογής",
        uninstallerPickerSearch: "Αναζήτηση εφαρμογών",
        uninstallerPickerEmpty: "Δεν βρέθηκαν εφαρμογές",
        uninstallerEmptyNote: "Τίποτα δεν αφαιρείται χωρίς την επιβεβαίωσή σας.",
        uninstallerFDANote: "Παραχωρήστε Πλήρη πρόσβαση στον δίσκο για πιο διεξοδική σάρωση.",
        uninstallerFDAGrant: "Παραχώρηση πρόσβασης…",
        uninstallerFDAHint: "Ενεργοποιήστε το Vorssaint στη λίστα. Αν δεν βρίσκεται εκεί, κάντε κλικ στο + και επιλέξτε το Vorssaint από τις Εφαρμογές. Η πρόσβαση εφαρμόζεται μόνο αφού ανοίξετε ξανά την εφαρμογή.",
        uninstallerFDARelaunch: "Άνοιγμα ξανά τώρα",
        uninstallerScanning: "Σάρωση αρχείων…",
        uninstallerRemoving: "Μετακίνηση στον Κάδο…",
        uninstallerFoundTitle: "βρέθηκαν",
        uninstallerSelectedFormat: "Επιλέχθηκαν %d από %d",
        uninstallerRemove: "Μετακίνηση στον Κάδο",
        uninstallerCancel: "Ακύρωση",
        uninstallerConfirmationExpired: "Αυτή η επιβεβαίωση δεν είναι πλέον έγκυρη. Ελέγξτε τα τρέχοντα στοιχεία και επιβεβαιώστε ξανά.",
        uninstallerDoneTitle: "Ολοκληρώθηκε!",
        uninstallerFreedFormat: "Ανακτήθηκαν %@",
        uninstallerSomeFailed: "Δεν ήταν δυνατή η μετακίνηση ορισμένων στοιχείων στον Κάδο.",
        uninstallerFailedNeedsFDA: "Τα δεδομένα εφαρμογών σε sandbox μπορούν να μετακινηθούν μόνο με Πλήρη πρόσβαση στον δίσκο. Το συνθηματικό διαχειριστή δεν την υποκαθιστά.",
        uninstallerFailedMoreFormat: "και %d ακόμη",
        uninstallerAnother: "Απεγκατάσταση άλλης εφαρμογής",
        uninstallerCatApp: "Εφαρμογή",
        uninstallerCatSupport: "Υποστήριξη",
        uninstallerCatCaches: "Μνήμες cache",
        uninstallerCatPreferences: "Προτιμήσεις",
        uninstallerCatContainers: "Containers",
        uninstallerCatLogs: "Αρχεία καταγραφής",
        uninstallerCatState: "Αποθηκευμένη κατάσταση",
        uninstallerCatOther: "Άλλα",
        uninstallerCommandBarBrowseTitle: "Απεγκατάσταση εφαρμογής",
        uninstallerCommandBarToggle: "Εμφάνιση στη Γραμμή εντολών",
        uninstallerCommandBarCaption: "Επιλογή και απεγκατάσταση εφαρμογών από τη Γραμμή εντολών.",
        uninstallerCommandBarFinderTitle: "Απεγκατάσταση εφαρμογής που έχει επιλεγεί στο Finder",
        uninstallerSelectionUnavailable: "Επιλέξτε στο Finder μια εφαρμογή που μπορεί να αφαιρεθεί ή επιλέξτε κάποια άλλη από τη λίστα.",

        urlCleanerName: "Καθαρισμός URL",
        urlCleanerEnable: "Καθαρισμός URL κατά την αντιγραφή",
        urlCleanerEnableCaption: "Αφαιρεί τις παραμέτρους παρακολούθησης από έναν σύνδεσμο μόλις φτάσει στο Πρόχειρο.",
        urlCleanerActiveNow: "Ενεργό τώρα",
        urlCleanerManualTitle: "Καθαρισμός τώρα",
        urlCleanerInputPlaceholder: "Επικολλήστε ένα URL",
        urlCleanerOutputPlaceholder: "Το καθαρό URL εμφανίζεται εδώ",
        urlCleanerCleanButton: "Καθαρισμός",
        urlCleanerPasteButton: "Επικόλληση",
        urlCleanerCopyButton: "Αντιγραφή",
        urlCleanerClearButton: "Εκκαθάριση πεδίου",
        urlCleanerNoURL: "Επικολλήστε ένα έγκυρο URL.",
        urlCleanerNoChange: "Δεν υπάρχει κάτι για καθαρισμό.",
        urlCleanerCleaned: "Το URL καθαρίστηκε.",
        urlCleanerCopied: "Αντιγράφηκε.",
        urlCleanerLocalNote: "Τοπική επεξεργασία. Χωρίς χρήση δικτύου.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Αναζήτηση, εγκατάσταση και αφαίρεση formulae και casks.",
        homebrewMissingTitle: "Το Homebrew δεν βρέθηκε",
        homebrewMissingBody: "Το Vorssaint μπορεί να ανοίξει το Τερματικό με το επίσημο πρόγραμμα εγκατάστασης του Homebrew. Το Τερματικό εμφανίζει τα βήματα και ζητά το συνθηματικό σας, αν χρειάζεται.",
        homebrewInstallHomebrew: "Εγκατάσταση Homebrew",
        homebrewInstallHomebrewCaption: "Όταν ολοκληρωθεί η διαδικασία στο Τερματικό, επιστρέψτε εδώ και κάντε κλικ στην “Ανανέωση”.",
        homebrewInstallHomebrewOpened: "Το πρόγραμμα εγκατάστασης άνοιξε στο Τερματικό.",
        homebrewShellSetupTitle: "Ολοκλήρωση διαμόρφωσης Τερματικού",
        homebrewShellSetupBody: "Το Homebrew είναι εγκατεστημένο, αλλά το Τερματικό ενδέχεται να μην βρίσκει ακόμη την εντολή brew. Το Vorssaint μπορεί να ανοίξει το Τερματικό με την εντολή διαμόρφωσης.",
        homebrewShellSetupButton: "Διαμόρφωση Τερματικού",
        homebrewShellSetupOpened: "Η εντολή άνοιξε στο Τερματικό. Στη συνέχεια επιστρέψτε εδώ και κάντε κλικ στην “Ανανέωση”.",
        homebrewRefresh: "Ανανέωση",
        homebrewCheckPackages: "Έλεγχος πακέτων",
        homebrewTrustTitle: "Το tap δεν είναι ακόμη αξιόπιστο",
        homebrewTrustCaption: "Το Homebrew ζητά πλέον την επιβεβαίωσή σας πριν χρησιμοποιήσει taps τρίτων. Εγκρίνετε το %@ για να συνεχίσετε.",
        homebrewTrustButton: "Έγκριση και συνέχεια",
        homebrewSearchPlaceholder: "Αναζήτηση πακέτων",
        homebrewKeyboardHint: "Το Space ή Return κλείνει τον πίνακα του macOS. Χρησιμοποιήστε το κουμπί αναζήτησης.",
        homebrewSearchButton: "Αναζήτηση",
        homebrewSearchResults: "Αποτελέσματα",
        homebrewInstalled: "Εγκατεστημένα",
        homebrewAll: "Όλα",
        homebrewFormulas: "Formulae",
        homebrewCasks: "Casks",
        homebrewNoPackages: "Δεν βρέθηκαν πακέτα",
        homebrewDependencies: "Εξαρτήσεις",
        homebrewGroupDependencies: "Ομαδοποίηση εξαρτήσεων",
        homebrewOrphans: "Δεν απαιτούνται πλέον",
        homebrewOrphansNote: "Εγκαταστάθηκαν ως εξαρτήσεις, αλλά κανένα εγκατεστημένο πακέτο δεν τις χρειάζεται πλέον.",
        homebrewNoSelection: "Επιλέξτε ένα εγκατεστημένο πακέτο ή αναζητήστε ένα νέο.",
        homebrewDetailsTitle: "Λεπτομέρειες πακέτου",
        homebrewInstall: "Εγκατάσταση",
        homebrewUninstall: "Απεγκατάσταση",
        homebrewUpgrade: "Ενημέρωση",
        homebrewUpgradeAll: "Ενημέρωση όλων",
        homebrewUpdateHomebrew: "Ενημέρωση Homebrew",
        homebrewAllPackages: "πακέτα",
        homebrewOpenTerminal: "Άνοιγμα Τερματικού",
        homebrewCancelOperation: "Ακύρωση",
        homebrewClearLog: "Εκκαθάριση αρχείου καταγραφής",
        homebrewLogTitle: "Αρχείο καταγραφής",
        homebrewVersion: "Έκδοση",
        homebrewDescription: "Τύπος",
        homebrewHomepage: "Άνοιγμα ιστότοπου",
        homebrewPopularity: "Δημοτικότητα",
        homebrewPopularityFormat: "%@ εγκαταστάσεις σε %@ ημέρες",
        homebrewInstalledBadge: "Εγκατεστημένο",
        homebrewNotInstalledBadge: "Μη εγκατεστημένο",
        homebrewUpdates: "Ενημερώσεις",
        homebrewUpdateAvailableBadge: "Διαθέσιμη ενημέρωση",
        homebrewLatestVersion: "Τελευταία",
        homebrewConfirmInstallTitle: "Εγκατάσταση με το Homebrew;",
        homebrewConfirmInstallBodyFormat: "Το Homebrew θα πραγματοποιήσει λήψη και εγκατάσταση του %@. Ενδέχεται να εγκατασταθούν και εξαρτήσεις.",
        homebrewConfirmUninstallTitle: "Απεγκατάσταση με το Homebrew;",
        homebrewConfirmUninstallBodyFormat: "Το Homebrew θα απεγκαταστήσει το %@. Ενδέχεται να παραμείνουν αρχεία διαμόρφωσης στο σύστημα.",
        homebrewConfirmUpgradeTitle: "Ενημέρωση με το Homebrew;",
        homebrewConfirmUpgradeBodyFormat: "Το Homebrew θα πραγματοποιήσει λήψη και εγκατάσταση της πιο πρόσφατης έκδοσης του %@. Ενδέχεται να ενημερωθούν και εξαρτήσεις.",
        homebrewConfirmUpgradeAllTitle: "Ενημέρωση όλων με το Homebrew;",
        homebrewConfirmUpgradeAllBody: "Το Homebrew θα πραγματοποιήσει λήψη και εγκατάσταση των πιο πρόσφατων εκδόσεων για τα πακέτα με διαθέσιμες ενημερώσεις. Ενδέχεται να ενημερωθούν και εξαρτήσεις.",
        homebrewConfirmUpdateHomebrewTitle: "Ενημέρωση Homebrew;",
        homebrewConfirmUpdateHomebrewBody: "Το Homebrew θα ανακτήσει τις πιο πρόσφατες πληροφορίες και στη συνέχεια θα φορτώσει ξανά τα πακέτα σας.",
        homebrewTerminalFallback: "Αυτή η ενέργεια απαιτεί το Τερματικό για την εισαγωγή του συνθηματικού διαχειριστή. Το Vorssaint δεν καταγράφει συνθηματικά.",
        homebrewLoading: "Φόρτωση…",
        homebrewSearchEmpty: "Δεν υπάρχουν αποτελέσματα",
        homebrewOperationInstallFormat: "Εγκατάσταση %@",
        homebrewOperationUninstallFormat: "Απεγκατάσταση %@",
        homebrewOperationUpgradeFormat: "Ενημέρωση %@",
        homebrewOperationUpgradeAll: "Ενημέρωση πακέτων",
        homebrewOperationUpdateHomebrew: "Ενημέρωση Homebrew",
        homebrewOperationInstalledFormat: "Το %@ εγκαταστάθηκε.",
        homebrewOperationUninstalledFormat: "Το %@ απεγκαταστάθηκε.",
        homebrewOperationUpgradedFormat: "Το %@ ενημερώθηκε.",
        homebrewOperationUpgradedAll: "Τα πακέτα ενημερώθηκαν.",
        homebrewOperationUpdatedHomebrew: "Το Homebrew ενημερώθηκε.",
        homebrewOperationFailedFormat: "Δεν ήταν δυνατή η ολοκλήρωση της ενέργειας %@.",
        homebrewOperationCancelled: "Η ενέργεια ακυρώθηκε.",
        homebrewOperationPreparing: "Προετοιμασία…",
        homebrewOperationDownloading: "Λήψη αρχείων…",
        homebrewOperationInstalling: "Εγκατάσταση αρχείων…",
        homebrewOperationUninstalling: "Αφαίρεση αρχείων…",
        homebrewOperationUpgrading: "Ενημέρωση αρχείων…",
        homebrewOperationFinalizing: "Ολοκλήρωση…",
        homebrewOperationRefreshing: "Ανανέωση λίστας…",
        homebrewOperationTerminal: "Συνέχεια στο Τερματικό.",
        homebrewOperationElapsedFormat: "Χρόνος που πέρασε: %@",
        homebrewOperationShowDetails: "Εμφάνιση λεπτομερειών",
        homebrewOperationHideDetails: "Απόκρυψη λεπτομερειών",
        homebrewOperationTechnicalLog: "Τεχνικές λεπτομέρειες",
        homebrewOperationProgressUnknown: "Το Homebrew δεν έχει αναφέρει ακόμη ποσοστό προόδου.",

        mediaName: "Πολυμέσα",
        mediaEnableCaption: "Συμπίεση βίντεο, μετατροπή και επεξεργασία εικόνων, δημιουργία GIF και εξαγωγή κειμένου τοπικά.",
        mediaLocalNote: "Τοπική επεξεργασία. Χωρίς χρήση δικτύου.",
        mediaToolVideo: "Βίντεο",
        mediaToolGIF: "GIF",
        mediaToolImage: "Εικόνα",
        mediaToolText: "Κείμενο",
        mediaSelectFile: "Επιλογή αρχείου",
        mediaDropHint: "Αποθέστε ένα αρχείο εδώ ή κάντε κλικ για να επιλέξετε ένα.",
        mediaOutput: "Έξοδος",
        mediaOutputAutomatic: "Αυτόματα",
        mediaChooseOutput: "Προορισμός",
        mediaStartVideo: "Συμπίεση βίντεο",
        mediaStartGIF: "Δημιουργία GIF",
        mediaStartImage: "Επεξεργασία εικόνας",
        mediaStartConvertPDF: "Μετατροπή σε PDF",
        mediaStartText: "Εξαγωγή κειμένου",
        mediaCancel: "Ακύρωση",
        mediaStartTime: "Έναρξη",
        mediaEndTime: "Λήξη",
        mediaQuality: "Συμπίεση",
        mediaCompressionLow: "Χαμηλή",
        mediaCompressionMedium: "Μεσαία",
        mediaCompressionHigh: "Υψηλή",
        mediaCompressionLowDescription: "Υψηλή ποιότητα, μεγάλο μέγεθος αρχείου",
        mediaCompressionMediumDescription: "Ισορροπία ποιότητας και μεγέθους αρχείου",
        mediaCompressionHighDescription: "Χαμηλή ποιότητα, μικρό μέγεθος αρχείου",
        mediaMaxSize: "Μέγεθος",
        mediaSizingResolution: "Ανάλυση",
        mediaSizingFileSize: "Μέγεθος αρχείου",
        mediaTargetSize: "Επιθυμητό μέγεθος",
        mediaTargetSizeHint: "Η ανάλυση προσαρμόζεται ώστε το αρχείο να παραμένει κάτω από το όριο.",
        mediaErrorTargetTooSmall: "Το επιθυμητό μέγεθος είναι πολύ μικρό για αυτό το κλιπ. Περικόψτε το ή αυξήστε το όριο.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Πλάτος",
        mediaFPS: "FPS",
        mediaKeepAudio: "Διατήρηση ήχου",
        mediaCodec: "Κωδικοποιητής",
        mediaFormat: "Μορφή",
        mediaStripMetadata: "Αφαίρεση μεταδεδομένων",
        mediaLoopGIF: "Επανάληψη GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Ακριβής",
        mediaOCRFast: "Γρήγορη",
        mediaLanguageCorrection: "Διόρθωση γλώσσας",
        mediaTextOutputNote: "Το εξαγόμενο κείμενο μπορεί να αντιγραφεί και να αποθηκευτεί ως TXT.",
        mediaRunning: "Επεξεργασία",
        mediaCompleted: "Ολοκληρώθηκε",
        mediaCancelled: "Ακυρώθηκε.",
        mediaOpenInFinder: "Εμφάνιση στο Finder",
        mediaCopyText: "Αντιγραφή κειμένου",
        mediaRunAgain: "Εκτέλεση ξανά",
        mediaEmptyText: "Δεν βρέθηκε κείμενο.",
        mediaResultSavedFormat: "Αποθηκεύτηκε ως %@",
        mediaResultSizeFormat: "Από %@ σε %@",
        mediaResultGrewCaption: "Το αρχείο μετά τη μετατροπή είναι μεγαλύτερο από το αρχικό.",
        mediaErrorNoFile: "Επιλέξτε πρώτα ένα αρχείο.",
        mediaErrorNoVideo: "Αυτό το αρχείο δεν περιέχει κομμάτι βίντεο.",
        mediaErrorSameOutput: "Επιλέξτε προορισμό διαφορετικό από το αρχικό αρχείο.",
        mediaErrorUnsupported: "Η μορφή δεν υποστηρίζεται από το macOS.",

        shelfName: "Ράφι",
        shelfEnable: "Προσωρινός χώρος για μεταφορά αρχείων",
        shelfEnableCaption: "Ένας αιωρούμενος χώρος όπου μπορείτε να συγκεντρώνετε αρχεία, εικόνες και κείμενο και να τα σύρετε οπουδήποτε αργότερα.",
        shelfHowTitle: "Τρόπος χρήσης",
        shelfStep1: "Ανοίξτε το με τη συντόμευση ή κουνώντας γρήγορα το ποντίκι κατά τη μεταφορά.",
        shelfStep2: "Αποθέστε αρχεία, εικόνες, συνδέσμους ή κείμενο πάνω του για προσωρινή διατήρηση.",
        shelfStep3: "Σύρετε κάθε στοιχείο από το Ράφι σε οποιαδήποτε εφαρμογή όταν το χρειαστείτε.",
        shelfShakeToggle: "Άνοιγμα με κούνημα του ποντικιού κατά τη μεταφορά",
        shelfShakeCaption: "Κουνήστε γρήγορα τον δείκτη ενώ κρατάτε ένα στοιχείο για να εμφανιστεί το Ράφι κοντά στον δείκτη.",
        shelfDropZoneToggle: "Διατήρηση μεταφερόμενων αρχείων στη γραμμή μενού",
        shelfDropZoneCaption: "Κατά τη μεταφορά ενός αρχείου, το Ράφι εμφανίζεται κάτω από το εικονίδιο της γραμμής μενού. Ό,τι αποθέσετε παραμένει εκεί, σε ένα κουμπί που μπορείτε να συμπτύξετε και να ανοίξετε με ένα κλικ. Το κουμπί εξαφανίζεται όταν αδειάσει το Ράφι.",
        shelfDropZoneCaptionTopCenter: "Κατά τη μεταφορά ενός αρχείου, το Ράφι εμφανίζεται ως σήμα στο επάνω κέντρο της οθόνης. Ό,τι αποθέσετε παραμένει εκεί, σε ένα σήμα που ανοίγει με ένα κλικ και εξαφανίζεται όταν αδειάσει το Ράφι.",
        shelfDropZoneLabel: "Απόθεση εδώ",
        shelfDockPlacement: "Θέση",
        shelfDockMenuBar: "Κάτω από το εικονίδιο της γραμμής μενού",
        shelfDockTopCenter: "Επάνω κέντρο της οθόνης",
        shelfDockIslandNote: "Το Dynamic Island διατηρείται στο επάνω κέντρο όσο είναι ενεργό.",
        shelfCollapse: "Σύμπτυξη",
        shelfBehaviorTitle: "Μετά τη χρήση",
        shelfCloseAfterDrop: "Κλείσιμο μετά την απόθεση σε άλλη εφαρμογή",
        shelfCloseAfterDropCaption: "Κλείνει το Ράφι όταν η εφαρμογή προορισμού αποδεχτεί τα στοιχεία. Το καρφίτσωμα στον πίνακα το διατηρεί ανοιχτό.",
        shelfRemoveAfterDrop: "Αφαίρεση στοιχείων μετά την απόθεση",
        shelfRemoveAfterDropCaption: "Τα στοιχεία που γίνονται αποδεκτά από άλλη εφαρμογή αφαιρούνται από το Ράφι. Απενεργοποιήστε αυτήν την επιλογή για να διατηρείται ένα αντίγραφο. Τα καρφιτσωμένα στοιχεία παραμένουν πάντα.",
        shelfExclusionsTitle: "Αυτόματες εξαιρέσεις",
        shelfExclusionsEmpty: "Δεν έχουν προστεθεί εφαρμογές.",
        shelfExclusionsCaption: "Το κούνημα και η ζώνη απόθεσης στη γραμμή μενού παραμένουν ανενεργά για μεταφορές που ξεκινούν από αυτές τις εφαρμογές. Η συντόμευση και το “Άνοιγμα τώρα” εξακολουθούν να λειτουργούν.",
        shelfPin: "Διατήρηση ανοιχτού",
        shelfUnpin: "Να επιτρέπεται το κλείσιμο μετά τη χρήση",
        extraBrightnessName: "Επιπλέον φωτεινότητα",
        extraBrightnessCaption: "Χρησιμοποιεί το περιθώριο HDR της οθόνης για φωτεινότητα πάνω από τη μέγιστη κανονική τιμή. Καταναλώνει περισσότερη μπαταρία και το Mac ενδέχεται να θερμανθεί.",
        extraBrightnessLevelLabel: "Ένταση",
        extraBrightnessUnsupported: "Διατίθεται μόνο σε οθόνες XDR, όπως αυτές των MacBook Pro 14 και 16 ιντσών.",
        shelfHotkeyLabel: "Συντόμευση",
        shelfOpenNow: "Άνοιγμα τώρα",
        shelfNoPermission: "Δεν απαιτούνται δικαιώματα.",
        shelfMenuItem: "Άνοιγμα Ραφιού",
        shelfTitle: "Ράφι",
        shelfEmpty: "Σύρετε στοιχεία εδώ",
        shelfClearAll: "Εκκαθάριση όλων",
        shelfRemoveSelected: "Αφαίρεση επιλεγμένων",
        shelfSelectedFormat: "%d επιλεγμένα",
        shelfHint: "Κάντε κλικ για επιλογή. Σύρετε προς τα έξω για χρήση ή κάντε δεξί κλικ για περισσότερες ενέργειες.",
        shelfItemImage: "Εικόνα",
        shelfTooltipItemsFormat: "%d στοιχεία",
        shelfTooltipItemsFew: "%d στοιχεία",
        shelfTooltipImageSingular: "%d εικόνα",
        shelfTooltipImageFew: "%d εικόνες",
        shelfTooltipImagePlural: "%d εικόνες",
        shelfTooltipFileSingular: "%d αρχείο",
        shelfTooltipFileFew: "%d αρχεία",
        shelfTooltipFilePlural: "%d αρχεία",
        shelfTooltipNoteSingular: "%d σημείωση",
        shelfTooltipNoteFew: "%d σημειώσεις",
        shelfTooltipNotePlural: "%d σημειώσεις",
        shelfTooltipLinkSingular: "%d σύνδεσμος",
        shelfTooltipLinkFew: "%d σύνδεσμοι",
        shelfTooltipLinkPlural: "%d σύνδεσμοι",
        shelfActionOpen: "Άνοιγμα",
        shelfActionOpenWith: "Άνοιγμα με",
        shelfActionShare: "Κοινή χρήση",
        shelfActionPin: "Καρφίτσωμα",
        shelfActionUnpin: "Κατάργηση καρφιτσώματος",

        breakdownMeasuring: "Μέτρηση…",

        mixerSection: "Μείκτης έντασης ήχου",
        mixerEmpty: "Οι εφαρμογές που χρησιμοποιούν ήχο εμφανίζονται εδώ",
        mixerUnavailable: "Διατίθεται σε macOS 14.4 ή νεότερη έκδοση",
        mixerPermissionBody: "Για ρύθμιση της έντασης ήχου ανά εφαρμογή, επιτρέψτε την “Εγγραφή οθόνης και ήχου συστήματος” στις Ρυθμίσεις συστήματος. Ο ήχος δεν εγγράφεται ποτέ.",
        mixerResetTooltip: "Επαναφορά στο 100%",
        mixerOutputDefault: "Προεπιλογή",
        mixerOutputCurrent: "τρέχουσα",
        mixerOutputUnavailable: "Η έξοδος δεν είναι διαθέσιμη",
        mixerOutputFallback: "Χρήση της προεπιλεγμένης μέχρι να επιστρέψει αυτή η συσκευή.",
        mixerBypassedCaption: "Αυτή η εφαρμογή διαχειρίζεται τον ήχο της η ίδια.",
        mixerOutputTooltip: "Επιλογή εξόδου",
        mixerAirPlayChooseSpeaker: "Επιλογή ηχείου AirPlay…",
        mixerSystemOutputTitle: "Έξοδος",
        mixerSystemOutputNoDevices: "Δεν βρέθηκαν έξοδοι",
        mixerSystemOutputTooltip: "Επιλογή εξόδου συστήματος",
        mixerSystemOutputErrorFormat: "Δεν ήταν δυνατή η αλλαγή: %@",
        mixerLowerOnHeadphonesDisconnect: "Μείωση έντασης όταν αποσυνδέονται τα ακουστικά",
        mixerLowerOnHeadphonesDisconnectCaption: "Ρυθμίζει την ένταση εξόδου όταν αποσυνδέονται ενσύρματα ακουστικά ή ακουστικά Bluetooth.",
        mixerHeadphonesDisconnectVolume: "Ένταση μετά την αποσύνδεση",
        preciseVolumeRollerEnable: "Χρήση μικρότερων βημάτων έντασης",
        preciseVolumeRollerCaption: "Μετατρέπει τους τροχούς και τα πλήκτρα έντασης ήχου σε μικρότερα βήματα έντασης του συστήματος.",
        preciseVolumeRollerTapFailed: "Δεν ήταν δυνατή η ανίχνευση των πλήκτρων έντασης ήχου.",
        soundOutputSwitcherTitle: "Εναλλαγή εξόδου",
        soundOutputSwitcherEnable: "Εναλλαγή εξόδων με συντόμευση",
        soundOutputSwitcherCaption: "Επιλέξτε εξόδους και χρησιμοποιήστε τη συντόμευση για μετάβαση στην επόμενη διαθέσιμη.",
        soundOutputSwitcherDevices: "Έξοδοι στην εναλλαγή",
        soundOutputSwitcherNoAvailableSelection: "Επιλέξτε τουλάχιστον μία διαθέσιμη έξοδο.",
        mixerInputTitle: "Μικρόφωνο",
        mixerInputNoDevices: "Δεν βρέθηκαν μικρόφωνα",
        mixerInputUnavailable: "Το μικρόφωνο δεν είναι διαθέσιμο",
        mixerInputFallback: "Χρήση του προεπιλεγμένου μέχρι να επιστρέψει αυτό το μικρόφωνο.",
        mixerInputTooltip: "Επιλογή μικροφώνου",
        mixerInputErrorFormat: "Δεν ήταν δυνατή η αλλαγή: %@",
        mixerVisibleApps: "Εφαρμογές στη λίστα",
        mixerAllShown: "Όλες",
        mixerHiddenCountLabel: "Κρυμμένες",
        mixerHideFromList: "Απόκρυψη από τη λίστα",
        audioPrioritySection: "Προτεραιότητα ήχου",
        audioPriorityOutputEnable: "Αυτόματη εναλλαγή στην έξοδο υψηλότερης προτεραιότητας",
        audioPriorityInputEnable: "Αυτόματη εναλλαγή στο μικρόφωνο υψηλότερης προτεραιότητας",
        audioPriorityOutputList: "Προτεραιότητα εξόδου",
        audioPriorityInputList: "Προτεραιότητα μικροφώνου",
        audioPriorityMoveUp: "Μετακίνηση επάνω",
        audioPriorityMoveDown: "Μετακίνηση κάτω",
        audioPriorityUnavailable: "Μη διαθέσιμο",
        audioPriorityCurrent: "Τρέχον",
        audioPriorityCaption: "Οι συσκευές επιλέγονται με σειρά προτεραιότητας. Όταν συνδέεται συσκευή υψηλότερης προτεραιότητας, γίνεται ενεργή. Όταν αποσυνδέεται η ενεργή συσκευή, χρησιμοποιείται η επόμενη διαθέσιμη.",

        updatesSection: "Ενημερώσεις",
        autoCheckToggle: "Αυτόματος έλεγχος για ενημερώσεις",
        includeBetaUpdatesToggle: "Λήψη ενημερώσεων beta",
        includeBetaUpdatesCaption: "Οι εκδόσεις beta περιλαμβάνουν δυνατότητες υπό ανάπτυξη και ενδέχεται να περιέχουν σφάλματα ή μη ολοκληρωμένη λειτουργικότητα.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Έλεγχος τώρα",
        updateChecking: "Έλεγχος…",
        updateUpToDate: "Έχετε την πιο πρόσφατη έκδοση.",
        updateAvailablePrefix: "Διαθέσιμη ενημέρωση:",
        updateInstallButton: "Λήψη και εγκατάσταση",
        updateDownloading: "Λήψη ενημέρωσης…",
        updateInstalling: "Εγκατάσταση και επανεκκίνηση…",
        updateFailedPrefix: "Ο έλεγχος απέτυχε:",
        updateLastChecked: "Τελευταίος έλεγχος:",
        updateNotifyTitle: "Ενημέρωση Vorssaint",
        updateInstallFailedBody: "Έγινε λήψη της ενημέρωσης, αλλά δεν ήταν δυνατή η εφαρμογή της. Κάντε λήψη της πιο πρόσφατης έκδοσης από τη σελίδα εκδόσεων στο GitHub και σύρετε την εφαρμογή πάνω από την τρέχουσα.",
        updateNeedsApplicationsTitle: "Μετακίνηση του Vorssaint στις Εφαρμογές",
        updateNeedsApplicationsBody: "Η εφαρμογή εκτελείται από θέση που δεν επιτρέπει ενημέρωση, όπως ένα είδωλο δίσκου ή μια προσωρινή θέση του συστήματος. Σύρετε το Vorssaint στον φάκελο Εφαρμογές, ανοίξτε το από εκεί και δοκιμάστε ξανά.",
        menuCheckUpdates: "Έλεγχος για ενημερώσεις…",

        permissionRequired: "Απαιτείται άδεια",
        permissionAccessibility: "Προσβασιμότητα",
        permissionScreenRecording: "Εγγραφή οθόνης και ήχου συστήματος",
        permissionGranted: "Παραχωρήθηκε",
        permissionMissing: "Δεν παραχωρήθηκε",
        permissionOpenSettings: "Άνοιγμα Ρυθμίσεων συστήματος…",
        permissionRequest: "Παραχώρηση πρόσβασης",
        permissionRestartNote: "Το macOS ενδέχεται να ζητήσει να ανοίξει ξανά η εφαρμογή μετά την παραχώρηση πρόσβασης.",
        secureInputTitle: "Η ασφαλής εισαγωγή είναι ενεργή",
        secureInputHeldFormat: "Η εφαρμογή %@ τη διατηρεί ενεργή, επομένως το Vorssaint δεν μπορεί να πληκτρολογήσει για εσάς. Κλείστε το πεδίο συνθηματικού της ή τερματίστε την εφαρμογή για να απελευθερωθεί.",
        secureInputUnattributed: "Καμία εφαρμογή που εκτελείται δεν φαίνεται να τη διατηρεί ενεργή. Αποσυνδεθείτε και συνδεθείτε ξανά για να την επαναφέρετε.",
        secureInputUnidentified: "Δεν ήταν δυνατή η αναγνώριση της εφαρμογής που τη διατηρεί ενεργή, επομένως το Vorssaint δεν μπορεί να πληκτρολογήσει για εσάς.",
        secureInputRevealFormat: "Εμφάνιση %@",

        aboutDescription: "Ένα κέντρο βοηθητικών εργαλείων για το Mac σας.\nΕνέργεια, παρακολούθηση συστήματος, κύλιση και εναλλαγή παραθύρων, απευθείας από τη γραμμή μενού.",
        versionPrefix: "Έκδοση",
        reviewIntro: "Εισαγωγή παρουσίασης",
        reviewHighlights: "Κύρια σημεία παρουσίασης",
        viewOnGitHub: "Προβολή στο GitHub",

        obContinue: "Συνέχεια",
        obBack: "Πίσω",
        obSkipStep: "Παράλειψη αυτού του βήματος",
        obStart: "Άνοιγμα Vorssaint",
        obStepWelcomeTitle: "Καλώς ορίσατε στο Vorssaint",
        obStepWelcomeBody: "Ένα διακριτικό βοηθητικό εργαλείο στη γραμμή μενού που κάνει την καθημερινή χρήση του macOS πιο πρακτική.",
        obWelcomeBullet1Title: "Έλεγχος ενέργειας",
        obWelcomeBullet1Body: "Διατηρήστε το Mac ενεργό για όσο θέλετε, ακόμη και με κλειστό καπάκι.",
        obWelcomeBullet2Title: "Καθαρή εικόνα του συστήματος",
        obWelcomeBullet2Body: "Θερμοκρασίες CPU, GPU και μπαταρίας, χρήση υλικού και πίεση μνήμης σε πραγματικό χρόνο.",
        obWelcomeBullet3Title: "Ποντίκι και παράθυρα στα μέτρα σας",
        obWelcomeBullet3Body: "Αντεστραμμένη κύλιση ποντικιού και εναλλαγή παραθύρων με μικρογραφίες.",
        obLanguageLabel: "Γλώσσα",
        obStepAccessibilityTitle: "Προσβασιμότητα",
        obStepAccessibilityBody: "Απαιτείται για την αντιστροφή της κύλισης του ποντικιού και για την απόκριση της εναλλαγής παραθύρων στο πληκτρολόγιο.",
        obAccessibilityWhy: "Η εφαρμογή παρακολουθεί μόνο τον τροχό κύλισης του ποντικιού και τη συντόμευση της εναλλαγής. Τίποτα δεν καταγράφεται ή αποστέλλεται οπουδήποτε.",
        obStepRecordingTitle: "Εγγραφή οθόνης και ήχου συστήματος",
        obStepRecordingBody: "Επιτρέπει στην εναλλαγή παραθύρων να εμφανίζει πραγματικές μικρογραφίες παραθύρων αντί μόνο για εικονίδια.",
        obRecordingWhy: "Οι μικρογραφίες δημιουργούνται επιτόπου, παραμένουν στη μνήμη και δεν φεύγουν ποτέ από το Mac σας. Χωρίς αυτήν την άδεια, η εναλλαγή εξακολουθεί να λειτουργεί με εικονίδια.",
        obStepMonitorTitle: "Παρακολούθηση συστήματος",
        obStepMonitorBody: "Ο πίνακας εμφανίζει θερμοκρασίες CPU, GPU και μπαταρίας, χρήση υλικού και πίεση μνήμης.",
        obMonitorNoPermission: "Δεν απαιτείται άδεια. Οι αισθητήρες διαβάζονται απευθείας από το σύστημα.",
        obStepOptionalTitle: "Προαιρετικές δυνατότητες",
        obStepOptionalBody: "Ενεργοποιήστε ό,τι θέλετε να χρησιμοποιήσετε τώρα. Μπορείτε να αλλάξετε τα πάντα αργότερα στις Ρυθμίσεις.",
        obStepStatusTitle: "Έλεγχος",
        obStepStatusBody: "Βεβαιωθείτε ότι όλα είναι έτοιμα για τις δυνατότητες που θέλετε.",
        obStatusRecheck: "Έλεγχος ξανά",
        obStepDoneTitle: "Όλα έτοιμα!",
        obStepDoneBody: "Το Vorssaint φροντίζει ήδη το Mac σας.",
        obDoneHint: "Αναζητήστε τη μαύρη τρύπα στη γραμμή μενού, επάνω δεξιά στην οθόνη.",
        obWhatsNewTitle: "Τι νέο υπάρχει σε αυτήν την έκδοση",
        obWhatsNewFallback: "Αυτή η ενημέρωση περιλαμβάνει τις πιο πρόσφατες διορθώσεις και βελτιώσεις.",
        obLanguageUpdateTitle: "Τώρα και στη γλώσσα σας",
        obLanguageUpdateBody: "Το Vorssaint είναι πλέον διαθέσιμο σε πολλές γλώσσες. Επιλέξτε αυτήν που θέλετε να χρησιμοποιείτε. Μπορείτε να την αλλάξετε οποιαδήποτε στιγμή στις Ρυθμίσεις.",
        obPurposeTitle: "Τι σας έφερε εδώ;",
        obPurposeBody: "Επιλέξτε μια έτοιμη διαμόρφωση ή ακριβώς τις δυνατότητες που θέλετε να χρησιμοποιήσετε.",
        obPurposeSkip: "Μπορείτε να προσθέσετε ή να αφαιρέσετε δυνατότητες αργότερα από τις Ρυθμίσεις.",

        tabMonitor: "Παρακολούθηση",
        monitorMenuBarSection: "Στη γραμμή μενού",
        monitorMenuBarCaption: "Επιλέξτε τι θα εμφανίζεται δίπλα στο εικονίδιο στη γραμμή μενού.",
        monitorCombineTemperatures: "Συνδυασμός χρήσης και θερμοκρασίας",
        monitorCombineTemperaturesCaption: "Όταν είναι ενεργοποιημένες η χρήση και η θερμοκρασία για το ίδιο στοιχείο, εμφανίζονται μαζί σε ένα μπλοκ.",
        monitorSeparateMenuBarMetrics: "Ξεχωριστές μετρήσεις στη γραμμή μενού",
        monitorSeparateMenuBarMetricsCaption: "Διαχωρίζει τα ενεργά μπλοκ στη γραμμή μενού και διατηρεί μαζί τη χρήση και τη θερμοκρασία όταν είναι ενεργός ο συνδυασμός.",
        monitorNetworkUploadFirst: "Αποστολή πάνω από τη λήψη",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Μνήμη",
        monitorShowNetwork: "Δίκτυο",
        monitorShowPowerLabel: "Ισχύς",
        monitorIntervalLabel: "Ενημέρωση κάθε",
        monitorInterval1: "1 δευτερόλεπτο",
        monitorInterval2: "2 δευτερόλεπτα",
        monitorInterval5: "5 δευτερόλεπτα",
        monitorPanelSection: "Στον πίνακα",
        panelNavigationMode: "Πλοήγηση στον πίνακα ανά ενότητα",
        panelNavigationCaption: "Εμφανίζει μία ενότητα κάθε φορά. Επιλέξτε “Λίστα” για να βλέπετε τα πάντα σε μία συνεχή κύλιση.",
        panelFooterSections: "Ενότητες",
        panelFooterList: "Λίστα",
        betaBadge: "BETA",
        betaFeatureWarning: "Έκδοση beta. Ενδέχεται να παρουσιαστούν ορισμένα σφάλματα.",

        networkSection: "Δίκτυο",
        networkIPAddresses: "Διευθύνσεις IP",
        networkLocalIP: "Τοπική IPv4",
        networkDownload: "Λήψη",
        networkUpload: "Αποστολή",
        networkThisSession: "Αυτή η συνεδρία",
        networkMeasuring: "Μέτρηση…",
        networkApps: "Εφαρμογές που χρησιμοποιούν το δίκτυο",
        networkAppsIdle: "Καμία εφαρμογή δεν χρησιμοποιεί το δίκτυο αυτήν τη στιγμή",

        diskSection: "Δίσκοι",
        diskUsed: "σε χρήση",
        diskFree: "ελεύθερα",
        diskMenuBarStyleLabel: "Εμφάνιση δίσκου",
        diskMenuBarUsedPercentage: "Ποσοστό σε χρήση",
        diskMenuBarAvailableSpace: "Διαθέσιμος χώρος",
        diskMenuBarUsedSpace: "Χρησιμοποιημένος χώρος",
        diskAvailable: "διαθέσιμα",
        diskPurgeable: "εκκαθαρίσιμα",
        diskInternal: "Εσωτερικός",
        diskExternal: "Εξωτερικός",
        diskSelect: "Επιλογή δίσκου",
        diskRead: "Ανάγνωση",
        diskWrite: "Εγγραφή",
        diskSMARTStatus: "Κατάσταση",
        diskSMARTUnavailable: "Το SMART δεν είναι διαθέσιμο για αυτόν τον δίσκο",
        diskTotalRead: "Συνολική ανάγνωση",
        diskTotalWritten: "Συνολική εγγραφή",
        diskTemperature: "Θερμοκρασία",
        diskHealth: "Υγεία",
        diskPowerCycles: "Κύκλοι ενεργοποίησης",
        diskPowerOnHours: "Ώρες λειτουργίας",
        diskUnsafeShutdowns: "Μη ασφαλείς τερματισμοί",
        diskMediaErrors: "Σφάλματα μέσου",
        diskEject: "Εξαγωγή",
        diskEjectAll: "Εξαγωγή όλων",
        diskEjecting: "Εξαγωγή…",
        diskReadyToRemove: "Έτοιμος για αφαίρεση",
        diskEjectFailed: "Δεν ήταν δυνατή η εξαγωγή",
        diskProtectionCaption: "Κάντε εξαγωγή πριν από την αποσύνδεση.",
        diskNoExternal: "Δεν υπάρχει εξωτερικός δίσκος έτοιμος για εξαγωγή.",
        diskOpenInFinder: "Άνοιγμα",
        diskStorageSettings: "Χώρος αποθήκευσης",
        diskNoDisks: "Δεν βρέθηκαν προσαρτημένοι δίσκοι.",

        powerSection: "Ισχύς",
        powerSystem: "Σύστημα",
        powerAdapter: "Τροφοδοτικό",
        powerBattery: "Μπαταρία",
        powerCharging: "Φόρτιση",
        powerOnBattery: "Με μπαταρία",
        powerPluggedIn: "Συνδεδεμένο στο ρεύμα",
        powerUnavailable: "Οι μετρήσεις ισχύος δεν είναι διαθέσιμες σε αυτό το Mac",
        powerAdapterMaxFormat: "Μέγιστο %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Θερμοκρασία CPU",
        monitorShowGPUTemperature: "Θερμοκρασία GPU",
        monitorShowBatteryTemperature: "Θερμοκρασία μπαταρίας",
        monitorShowPeripheralBattery: "Μπαταρία περιφερειακών",
        peripheralBatteryNoDevices: "Δεν βρέθηκαν συσκευές",
        monitorGraphsSection: "Γραφήματα",

        updateBannerTitle: "Διαθέσιμη ενημέρωση",
        updateBannerAction: "Ενημέρωση",
        obStepMenuBarTitle: "Μετρήσεις στη γραμμή μενού",
        obStepMenuBarBody: "Επιλέξτε τι θα εμφανίζεται δίπλα στο εικονίδιο. Η παραπάνω προεπισκόπηση ενημερώνεται σε πραγματικό χρόνο.",
        obStepMenuBarNote: "Νέο: μπλοκ Δικτύου και Ισχύος και γραφήματα στον πίνακα. Μπορείτε να τα προσαρμόσετε αργότερα στις Ρυθμίσεις › Παρακολούθηση.",
        monitorMenuBarPresetLabel: "Στιλ",
        menuBarPresetReadable: "Ευανάγνωστο",
        menuBarPresetDense: "Πυκνό",
        menuBarSpacingLabel: "Απόσταση στη γραμμή μενού",
        menuBarSpacingStandard: "Τυπική",
        menuBarSpacingCompact: "Συμπαγής",
        menuBarHideIconToggle: "Απόκρυψη του εικονιδίου εφαρμογής κατά την εμφάνιση μετρήσεων",
        menuBarHideIconCaption: "Το εικονίδιο επανεμφανίζεται αυτόματα όταν δεν υπάρχουν μετρήσεις στη γραμμή ή όταν υπάρχει κάτι που πρέπει να επισημανθεί, όπως διαθέσιμη ενημέρωση ή μικρόφωνο σε σίγαση.",
        monitorLabelStyleLabel: "Ετικέτες",
        menuBarLabelStyleCompact: "Συμπαγείς",
        menuBarLabelStyleClassic: "Κλασικές",
        monitorMemoryStyleLabel: "Εμφάνιση μνήμης ως",
        monitorMemoryPressureDot: "Κουκκίδα πίεσης",
        memoryStyleDot: "Κουκκίδα",
        memoryStylePercent: "%",
        memoryStyleBoth: "Και τα δύο",
        systemUptime: "Χρόνος λειτουργίας",
        batteryCharge: "Φόρτιση",
        powerHealth: "Υγεία μπαταρίας",
        powerCycles: "Κύκλοι φόρτισης",
        speedTestRun: "Δοκιμή ταχύτητας",
        speedTestAgain: "Δοκιμή ξανά",
        speedTestLatency: "Καθυστέρηση",
        speedTestTesting: "Δοκιμή…",
        speedTestFailed: "Η δοκιμή απέτυχε",

        monitorShowInPanel: "Εμφάνιση στον πίνακα",
        disclosureExpanded: "Αναπτυγμένο",
        disclosureCollapsed: "Συμπτυγμένο",
        panelHideItem: "Απόκρυψη από τον πίνακα",
        panelShowItem: "Εμφάνιση στον πίνακα",
        panelHiddenItem: "Κρυφό",
        monitorItemUptime: "Χρόνος λειτουργίας",
        monitorItemNetSpeed: "Τρέχουσα ταχύτητα",
        monitorItemNetTotals: "Σύνολα συνεδρίας",
        monitorItemNetTest: "Δοκιμή ταχύτητας",
        monitorItemDiskUsage: "Χρήση δίσκου",
        monitorItemDiskActivity: "Τρέχουσα δραστηριότητα",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Προστασία εξωτερικών δίσκων",
        monitorItemDiskTools: "Εργαλεία",
        monitorPanelConfigHint: "Ανοίξτε μια ενότητα για να επιλέξετε τι θα εμφανίζει.",
        monitorOrderHint: "Σύρετε για να αλλάξετε τη σειρά των ενοτήτων του πίνακα και χρησιμοποιήστε το μάτι για εμφάνιση ή απόκρυψη καθεμιάς.",
        obStepPanelTitle: "Τι υπάρχει στον πίνακα",
        obStepPanelBody: "Ανοίξτε κάθε ενότητα και επιλέξτε ακριβώς τι θα εμφανίζεται όταν κάνετε κλικ στο εικονίδιο.",
        obStepPanelNavigationTitle: "Πίνακας ανά ενότητα",
        obStepPanelNavigationBody: "Ο πίνακας μπορεί πλέον να εμφανίζει μία ενότητα κάθε φορά. Μπορείτε να εναλλάσσεστε μεταξύ “Ενότητες” και “Λίστα” στις Ρυθμίσεις.",

        cleaningMenuItem: "Λειτουργία καθαρισμού",
        utilitiesSection: "Βοηθήματα",
        quickControlsSection: "Στοιχεία ελέγχου",
        panelCategoryWindows: "Παράθυρα",
        panelCategoryInput: "Ποντίκι και πληκτρολόγιο",
        panelCategoryFiles: "Αρχεία",
        windowMaximizeName: "Μεγιστοποίηση παραθύρων",
        windowMaximizeCaption: "Το πράσινο κουμπί μεγιστοποιεί το παράθυρο χωρίς να δημιουργεί νέο γραφείο εργασίας.",
        windowMaximizeActiveNow: "Η παράκαμψη του πράσινου κουμπιού είναι ενεργή",
        windowMaximizeNeedsAccessibility: "Απαιτείται πρόσβαση στην Προσβασιμότητα.",
        keyDebounceName: "Φίλτρο διπλών πατημάτων",
        keyDebounceEnable: "Φιλτράρισμα διπλών πατημάτων πλήκτρων",
        keyDebounceCaption: "Φιλτράρει πολύ γρήγορα επαναλαμβανόμενα πατήματα πλήκτρων.",
        keyDebounceActiveNow: "Το φίλτρο είναι ενεργό",
        keyDebounceGlobalWindow: "Γενικό διάστημα",
        keyDebouncePerKeySection: "Συγκεκριμένα πλήκτρα",
        keyDebouncePerKeyCaption: "Οι τιμές ανά πλήκτρο υπερισχύουν του γενικού διαστήματος. Χρησιμοποιήστε 0 ms για να μη φιλτράρεται ένα πλήκτρο.",
        keyDebounceKeyLabel: "Πλήκτρο",
        keyDebounceWindowLabel: "Διάστημα",
        keyDebounceAddKey: "Προσθήκη πλήκτρου",
        keyDebounceNoOverrides: "Δεν έχουν διαμορφωθεί συγκεκριμένα πλήκτρα.",
        keyDebounceRemoveKey: "Αφαίρεση πλήκτρου",
        cleaningPanelCaption: "Κλειδώνει το πληκτρολόγιο για ασφαλή καθαρισμό.",
        cleaningOverlayTitle: "Το πληκτρολόγιο κλειδώθηκε για καθαρισμό",
        cleaningOverlaySubtitle: "Πατήστε το Escape 5 φορές για ξεκλείδωμα",
        cleaningOverlayUnlock: "Ξεκλείδωμα",
        cleaningOverlayMouseHint: "Το ποντίκι και η επιφάνεια αφής εξακολουθούν να λειτουργούν",
        cleaningKeepScreenVisibleToggle: "Διατήρηση ορατής οθόνης",
        cleaningKeepScreenVisibleCaption: "Εμφανίζει μια διακριτική ένδειξη στη γωνία της οθόνης αντί να μαυρίζει το περιεχόμενο.",
        cleaningStartNow: "Κλείδωμα πληκτρολογίου τώρα",
        cleaningNeedsAxTitle: "Απαιτείται Προσβασιμότητα",
        cleaningNeedsAxBody: "Για ασφαλές κλείδωμα του πληκτρολογίου, το Vorssaint χρειάζεται πρόσβαση στην Προσβασιμότητα. Παραχωρήστε την στις Ρυθμίσεις συστήματος και δοκιμάστε ξανά.",

        tabSupport: "Υποστήριξη",
        shortcutsPageCaption: "Επεξεργαστείτε όλες τις καθολικές συντομεύσεις των δυνατοτήτων που είναι εγκατεστημένες σε αυτό το Mac. Οι ανενεργές συντομεύσεις παραμένουν αποθηκευμένες αλλά δεν εκτελούνται.",
        shortcutsPageTitle: "Συντομεύσεις πληκτρολογίου",
        settingsSearchPlaceholder: "Αναζήτηση ρυθμίσεων",
        donateHeading: "Βοηθήστε το Vorssaint να συνεχίσει να αναπτύσσεται",
        donateMessage: "Το Vorssaint είναι δωρεάν, ανεξάρτητο και αναπτύσσεται στον ελεύθερο χρόνο μου. Αν θέλετε να συνεισφέρετε οικονομικά, το Buy Me a Coffee με βοηθά άμεσα να συνεχίσω την ανάπτυξή του.",
        donateButton: "Υποστήριξη μέσω Buy Me a Coffee",
        donateThanks: "Σας ευχαριστώ που είστε εδώ. 🖤",
        supportIntroTitle: "Βοηθήστε το Vorssaint να συνεχίσει να αναπτύσσεται",
        supportIntroMessage: "Αν θέλετε να υποστηρίξετε οικονομικά την ανάπτυξη, το Buy Me a Coffee είναι ο μοναδικός τρόπος.",
        supportIntroStarButton: "Προσθήκη αστεριού στο Vorssaint στο GitHub",
        supportIntroStarMessage: "Η οικονομική υποστήριξη δεν είναι ποτέ αναμενόμενη. Ένα αστέρι στο GitHub βοηθά περισσότερους ανθρώπους να ανακαλύψουν το Vorssaint και κάνει πραγματική διαφορά στην ανάπτυξή του.",
        supportIntroCoffeeButton: "Υποστήριξη μέσω Buy Me a Coffee",
        supportIntroLaterButton: "Όχι τώρα",
        supportIntroDoneButton: "Τέλος",
        discordIntroTitle: "Η κοινότητα Vorssaint στο Discord μόλις ξεκινά",
        discordIntroMessage: "Η κοινότητα του Vorssaint είναι νέα και ακόμη δημιουργείται. Μπείτε από νωρίς για να γνωρίσετε άλλους χρήστες και να βοηθήσετε στη δημιουργία ενός φιλόξενου χώρου γύρω από την εφαρμογή.",
        discordIntroJoinButton: "Συμμετοχή στην κοινότητα Discord",
        communityIntroTitle: "Δείτε το πριν από όλους τους άλλους",
        communityIntroMessage: "Όσοι με ακολουθούσαν ήδη στο X είδαν αρκετές αλλαγές αυτής της ενημέρωσης πριν από όλους τους άλλους. Δημοσιεύω προεπισκοπήσεις όσων έρχονται και δείχνω πώς λειτουργούν, ώστε να γνωρίζετε ήδη τα βασικά πριν κυκλοφορήσει η ενημέρωση. Ακολουθήστε με για να δείτε τι έρχεται στη συνέχεια!",
        communityIntroFollowButton: "Ακολουθήστε το @vorssaint στο X",
        homebrewOfficialIntroTitle: "Τώρα στον επίσημο κατάλογο Homebrew",
        homebrewOfficialIntroMessage: "Το Vorssaint μπορεί πλέον να εγκατασταθεί απευθείας από τον επίσημο κατάλογο Homebrew.",
        homebrewOfficialIntroInstallLabel: "Νέα εγκατάσταση",
        homebrewOfficialIntroMigrationTitle: "Χρησιμοποιούσατε το παλιό tap;",
        homebrewOfficialIntroMigrationMessage: "Αφαιρέστε το tap μία φορά. Η εφαρμογή και οι ρυθμίσεις σας παραμένουν στη θέση τους.",
        homebrewOfficialIntroCopyButton: "Αντιγραφή εντολής",
        updateShowcaseTitle: "Τι νέο υπάρχει στην έκδοση 3.1.4",
        updateShowcaseMessage: "Δείτε γρήγορα τις σημαντικότερες βελτιώσεις αυτής της ενημέρωσης.",
        updateShowcaseUnavailable: "Δεν ήταν δυνατή η φόρτωση του βίντεο αυτήν τη στιγμή. Μπορείτε να συνεχίσετε κανονικά.",
        updateShowcaseRestart: "Επανεκκίνηση",
        showMenuBarIcon: "Εμφάνιση εικονιδίου στη γραμμή μενού",
        menuBarIconStillHiddenTitle: "Το εικονίδιο παραμένει κρυμμένο",
        menuBarIconStillHiddenBody: "Το εικονίδιο δημιουργήθηκε ξανά, αλλά το macOS δεν του έδωσε ορατή θέση. Πιθανότατα δεν υπάρχει αρκετός χώρος στη γραμμή μενού. Αφαιρέστε μερικά εικονίδια της γραμμής μενού ή κλείστε εφαρμογές με μεγάλα μενού και δοκιμάστε ξανά.",
        menuBarIconManagerHintFormat: "Το %@ είναι ανοιχτό και ενδέχεται να διατηρεί το εικονίδιο στην κρυφή ενότητά του. Αναζητήστε εκεί το Vorssaint ή ρυθμίστε το %@ ώστε να εμφανίζει πάντα το Vorssaint.",
        menuBarIconDisallowedBody: "Το macOS δεν επιτρέπει στο Vorssaint να εμφανίζεται στη γραμμή μενού. Ανοίξτε τις Ρυθμίσεις συστήματος > Γραμμή μενού, βρείτε το Vorssaint στη λίστα εφαρμογών και ενεργοποιήστε το “Να επιτρέπεται στη γραμμή μενού”. Το εικονίδιο θα εμφανιστεί μόλις ενεργοποιηθεί ο διακόπτης.",
        shortcutRecording: "Πατήστε τη νέα συντόμευση",
        shortcutReset: "Επαναφορά",
        shortcutNone: "Καμία",
        shortcutClear: "Αφαίρεση συντόμευσης",
        shortcutInvalid: "Χρησιμοποιήστε τουλάχιστον το Control, Option ή Command μαζί με ένα πλήκτρο.",
        shortcutPressKeys: "Πατήστε πλήκτρα",
        shortcutEscapeHint: "Το Escape ακυρώνει.",
        shortcutDeleteHint: "Το Delete διαγράφει.",
        shortcutNotCaptured: "Δεν καταγράφηκε συντόμευση. Το macOS ή κάποια άλλη εφαρμογή χρησιμοποιεί ήδη αυτόν τον συνδυασμό. Δοκιμάστε έναν άλλο.",
        shortcutConflictFormat: "Αυτή η συντόμευση χρησιμοποιείται ήδη από το %@.",
        shortcutTakeOverOffer: "Το macOS χρησιμοποιεί το %@ για μία από τις δικές του συντομεύσεις.",
        shortcutTakeOverAction: "Χρήση από το Vorssaint όσο εκτελείται",
        shortcutTakeOverCaption: "Το macOS ανακτά το πλήκτρο όταν το Vorssaint δεν εκτελείται ή όταν αυτή η δυνατότητα είναι απενεργοποιημένη.",
        shortcutTakeOverDismiss: "Να μη χρησιμοποιηθεί",
        shortcutUnavailable: "Το macOS απέρριψε αυτήν τη συντόμευση. Επιλέξτε μια άλλη.",
        shelfShortcutToggle: "Συντόμευση Ραφιού",
        switcherUsageHintFormat: "Κρατήστε πατημένο το %@ για πλοήγηση και αφήστε το για ενεργοποίηση του παραθύρου. Το Shift ή ← μετακινεί προς τα πίσω, το W κλείνει το παράθυρο, το Q τερματίζει την εφαρμογή και το Esc ακυρώνει.",
        musicBlockSection: "Πλήκτρα πολυμέσων",
        musicBlockTitle: "Αποτροπή αυτόματου ανοίγματος της Μουσικής",
        musicBlockCaption: "Εμποδίζει το άνοιγμα της εφαρμογής Μουσική μετά την ανίχνευση πλήκτρου πολυμέσων. Απαιτεί πρόσβαση στην Προσβασιμότητα. Οι εντολές ακουστικών χωρίς ανιχνευμένο πάτημα πλήκτρου δεν επηρεάζονται.",
        musicBlockUnavailable: "Αυτή η προστασία δεν είναι διαθέσιμη αυτήν τη στιγμή. Απενεργοποιήστε την και ενεργοποιήστε την ξανά για νέα προσπάθεια.",
        musicBlockReplacementLabel: "Άνοιγμα αντί για",
        musicBlockReplacementNone: "Καμία",
        musicBlockReplacementBlocked: "Η Μουσική και το iTunes είναι οι εφαρμογές που αποκλείονται, επομένως δεν μπορούν να ανοίγουν ως αντικατάσταση. Επιλέξτε άλλη εφαρμογή.",
        musicBlockChooseApp: "Επιλογή εφαρμογής…",
        musicBlockPlayReplacement: "Αναπαραγωγή μετά το άνοιγμα της εφαρμογής αντικατάστασης",
        cleanerName: "Καθαρισμός",
        cleanerIntroTitle: "Καθαρίστε το Mac σας",
        cleanerIntroCaption: "Σαρώνει για υπολείμματα απεγκατεστημένων εφαρμογών, μνήμες cache, αρχεία καταγραφής και περιεχόμενα του Κάδου. Ελέγχετε πρώτα τα πάντα και τα στοιχεία που αφαιρούνται μεταφέρονται στον Κάδο.",
        cleanerScan: "Σάρωση",
        cleanerScanning: "Σάρωση…",
        cleanerCleaning: "Καθαρισμός…",
        cleanerCatLeftovers: "Υπολείμματα απεγκατεστημένων εφαρμογών",
        cleanerCatLoginItems: "Ορφανά στοιχεία σύνδεσης",
        cleanerCatCaches: "Μνήμες cache",
        cleanerCatLogs: "Αρχεία καταγραφής",
        cleanerCatDeveloper: "Άχρηστα αρχεία προγραμματιστή",
        cleanerCatTrash: "Κάδος",
        cleanerLeftoversNote: "Εντοπίζονται μέσω ανάλυσης και παραμένουν αποεπιλεγμένα. Ελέγξτε τη διαδρομή πριν τα επιλέξετε.",
        cleanerLoginItemsNote: "Η καταχώριση στα Στοιχεία σύνδεσης εξαφανίζεται μετά την επανεκκίνηση του Mac.",
        cleanerTrashNote: "Το άδειασμα του Κάδου είναι οριστικό.",
        cleanerCatDeviceBackups: "Εφεδρικά αντίγραφα iPhone",
        cleanerDeviceBackupsCaption: "Τα παλιά εφεδρικά αντίγραφα iPhone και iPad μπορούν να καταλαμβάνουν μεγάλο μέρος του χώρου αποθήκευσης που το macOS εμφανίζει ως “Άλλο”. Αφαιρέστε μόνο όσα δεν χρειάζεστε πλέον. Θα δημιουργηθεί νέο εφεδρικό αντίγραφο όταν συνδέσετε ξανά τη συσκευή.",
        cleanerCatScreenshots: "Ξεχασμένα στιγμιότυπα οθόνης",
        cleanerScreenshotsCaptionFormat: "Στιγμιότυπα οθόνης που δεν έχετε ανοίξει εδώ και %d ημέρες και εξακολουθούν να έχουν το όνομα και τον φάκελο που τους έδωσε το macOS. Όσα έχετε μετονομάσει ή μετακινήσει δεν εμφανίζονται εδώ.",
        cleanerScreenshotsSettingCaption: "Η σάρωση εμφανίζει, αποεπιλεγμένα, τα στιγμιότυπα οθόνης που δεν έχετε ανοίξει για αυτό το χρονικό διάστημα, μαζί με το συνολικό τους μέγεθος.",
        cleanerScreenshotsAfterFormat: "Μετά από %d ημέρες",
        cleanerNothingFound: "Δεν υπάρχει τίποτα για καθαρισμό. Το Mac σας είναι τακτοποιημένο.",
        cleanerClean: "Καθαρισμός",
        cleanerDoneNote: "Τα στοιχεία μεταφέρθηκαν στον Κάδο και μπορούν να ανακτηθούν από εκεί.",
        cleanerAgain: "Νέα σάρωση",
        cleanerRevealInFinder: "Εμφάνιση στο Finder",
        cleanerPanelCaption: "Υπολείμματα εφαρμογών, μνήμες cache και αρχεία καταγραφής",
        cleanerSafeSection: "Ασφαλής καθαρισμός",
        cleanerOptionalSection: "Προαιρετικά, ελέγξτε πρώτα",
        cleanerCatOtherCaches: "Άλλες μνήμες cache",
        cleanerCachesCaption: "Προσωρινά αρχεία που οι εφαρμογές δημιουργούν ξανά αυτόματα.",
        cleanerLogsCaption: "Παλιά διαγνωστικά αρχεία καταγραφής.",
        cleanerDeveloperCaption: "Υπολείμματα build του Xcode και προσομοιωτών.",
        cleanerLoginItemsCaption: "Στοιχεία εκκίνησης που άφησαν εφαρμογές που δεν υπάρχουν πλέον.",
        cleanerLeftoversCaption: "Αρχεία που άφησαν πίσω τους εφαρμογές που απεγκαταστήσατε.",
        cleanerOtherCachesCaption: "Μπορούν να αφαιρεθούν με ασφάλεια χωρίς να επηρεαστεί η λειτουργία των εφαρμογών. Ορισμένες εφαρμογές ενδέχεται να ανοίξουν πιο αργά μία φορά και περιεχόμενο που είχε ληφθεί, όπως μουσική για χρήση εκτός σύνδεσης, θα ληφθεί ξανά.",
        cleanerCleanSizeFormat: "Καθαρισμός %@",
        cleanerScheduleTitle: "Αυτόματος καθαρισμός",
        cleanerScheduleOff: "Απενεργοποιημένος",
        cleanerScheduleDaily: "Καθημερινά",
        cleanerScheduleWeekly: "Εβδομαδιαία",
        cleanerScheduleCaption: "Καθαρίζει αυτόματα μόνο τα ασφαλή στοιχεία την επιλεγμένη ώρα και τα μεταφέρει στον Κάδο.",
        cleanerScheduleLastFormat: "Ο τελευταίος αυτόματος καθαρισμός ελευθέρωσε %@.",
        cleanerAutoNotificationFormat: "Ελευθερώθηκαν %@ και μεταφέρθηκαν στον Κάδο.",
        cleanerScheduleNextFormat: "Επόμενος καθαρισμός: %@.",
        cleanerScheduleRanFormat: "Τελευταίος αυτόματος καθαρισμός: %@.",
        cleanerScheduleNotifyToggle: "Γνωστοποίηση μετά την ολοκλήρωση",
        cleanerNotifDenied: "Οι γνωστοποιήσεις του Vorssaint είναι απενεργοποιημένες στο σύστημα.",
        cleanerNotifOpenSettings: "Άνοιγμα ρυθμίσεων Γνωστοποιήσεων…",
        launchAtLoginNeedsApplications: "Η εφαρμογή εκτελείται από θέση από την οποία δεν μπορεί να ανοίγει κατά τη σύνδεση. Σύρετε το Vorssaint στον φάκελο Εφαρμογές, ανοίξτε το από εκεί και ενεργοποιήστε ξανά αυτήν την επιλογή.",
        launchAtLoginNeedsApproval: "Το στοιχείο σύνδεσης έχει καταχωριστεί αλλά παραμένει απενεργοποιημένο στις Ρυθμίσεις συστήματος. Ανοίξτε Ρυθμίσεις συστήματος › Γενικά › Στοιχεία σύνδεσης και επεκτάσεις και ενεργοποιήστε το Vorssaint στην ενότητα “Άνοιγμα κατά τη σύνδεση”.",
        ocrRemoveLineBreaksToggle: "Αφαίρεση αλλαγών γραμμής",
        ocrRemoveLineBreaksCaption: "Αφαιρεί τις αλλαγές γραμμής ώστε το αντιγραμμένο κείμενο να επικολλάται ως μία παράγραφος.",
        ocrQRToggle: "Ανάγνωση κωδικών QR",
        ocrQRCaption: "Αν η περιοχή περιέχει κωδικό QR, εμφανίζεται το περιεχόμενό του για αντιγραφή ή άνοιγμα.",
        ocrQRCopied: "Ο κωδικός QR αντιγράφηκε",
        qrResultTitle: "Κωδικός QR",
        qrResultCopy: "Αντιγραφή",
        qrResultOpen: "Άνοιγμα συνδέσμου",
        highlightsTitle: "Νέο σε αυτήν την ενημέρωση",
        highlightsTitleClipboardRedesign: "Νέος σχεδιασμός Προχείρου",
        highlightsTitleWindowLayout: "Διάταξη παραθύρων",
        highlightsTitleQuitProtection: "Προστασία από τερματισμό και κλείσιμο",
        highlightsTitleRecorderBlur: "Θόλωση απορρήτου στις εγγραφές",
        highlightsCaptionDockPreview: "Η Προεπισκόπηση Dock λειτουργεί πλέον και όταν είναι ενεργή η μεγέθυνση του Dock",
        highlightsCaptionScreenshot: "Το εργαλείο στιγμιότυπων οθόνης απέκτησε μεγεθυντικό φακό pixel και ανάγνωση κωδικών QR",
        highlightsCaptionSnippetLibrary: "Ένα μενού αποσπασμάτων με αναζήτηση πληκτρολογεί οποιοδήποτε απόσπασμα απευθείας στη θέση του δείκτη",
        highlightsCaptionCapturePalette: "Μία συντόμευση ανοίγει πλέον μια αιωρούμενη παλέτα για στιγμιότυπα οθόνης, εγγραφές, κείμενο οθόνης και χρώματα, με τα σχετικά στοιχεία ελέγχου δίπλα τους.",
        highlightsCaptionClipboardRedesign: "Το ιστορικό προχείρου ανοίγει πλέον ως συμπαγής παλέτα με καθαρές γραμμές και προεπισκόπηση κατ’ απαίτηση για ανάγνωση ή επεξεργασία ολόκληρου του στοιχείου.",
        highlightsCaptionWindowLayout: "Τοποθετήστε παράθυρα με το κυκλικό χειριστήριο κατεύθυνσης χρησιμοποιώντας συντόμευση και δείκτη ή σύρετέ τα στις άκρες της οθόνης για αυτόματη τοποθέτηση με προσαρμοσμένα κενά.",
        highlightsCaptionQuitProtection: "Αποφύγετε τον κατά λάθος τερματισμό εφαρμογών ή το κλείσιμο παραθύρων με παρατεταμένο πάτημα, διπλό πάτημα ή ένα πρόσθετο πλήκτρο τροποποίησης, με ξεχωριστή προσαρμογή για κάθε εφαρμογή.",
        highlightsCaptionRecorderBlur: "Αποκρύψτε προσωπικές πληροφορίες, συνθηματικά και ευαίσθητες περιοχές σε οποιοδήποτε σημείο του εγγεγραμμένου βίντεο πριν από την κοινή χρήση ή την εξαγωγή.",
        highlightsConfigure: "Διαμόρφωση",
        highlightsTry: "Δοκιμή",
        highlightsSeeAll: "Εμφάνιση όλων των αλλαγών",
        switcherCurrentSpaceOnly: "Εμφάνιση μόνο του τρέχοντος γραφείου εργασίας",
        switcherCurrentSpaceOnlyCaption: "Εμφανίζει μόνο τα παράθυρα του γραφείου εργασίας στο οποίο βρίσκεστε. Η επιλογή παραθύρου δεν σας μεταφέρει ποτέ σε άλλο γραφείο εργασίας.",
        shelfFileMissing: "Το αρχείο δεν υπάρχει πλέον",
        previewSizeSmall: "Μικρό",
        mixerSoundEffectsOutputTitle: "Ήχοι συστήματος",
        mixerSoundEffectsOutputTooltip: "Επιλέξτε πού θα αναπαράγονται οι ειδοποιήσεις και τα ηχητικά εφέ",
        monitorOpenActivityMonitor: "Άνοιγμα Παρακολούθησης δραστηριότητας",
        dockClickHide: "Κλικ στο εικονίδιο του Dock για απόκρυψη εφαρμογής",
        dockClickHideCaption: "Η ενεργή εφαρμογή αποκρύπτεται όταν κάνετε κλικ στο εικονίδιό της στο Dock. Κάντε ξανά κλικ για να την εμφανίσετε.",
        monitorMemoryMetricLabel: "Μέτρηση μνήμης ως",
        memoryMetricUsed: "Μνήμη σε χρήση",
        memoryMetricApp: "Μνήμη εφαρμογών",
        keepAwakeRightClickToggle: "Δεξί κλικ στο εικονίδιο της γραμμής μενού για εναλλαγή της Αποτροπής ύπνου",
        keepAwakeRightClickToggleCaption: "Αντικαθιστά το μενού συντόμευσης του δεξιού κλικ.",
        urlCleanerRulesTitle: "Κανόνες καθαρισμού",
        urlCleanerRulesCaption: "Ένας ιστότοπος προσθέτει αυτές τις παραμέτρους στους συνδέσμους κοινής χρήσης για να παρακολουθεί από πού προήλθε ο σύνδεσμος. Όταν ένας κανόνας είναι ενεργός, η αντίστοιχη παράμετρος αφαιρείται κατά τον καθαρισμό του συνδέσμου. Όταν είναι ανενεργός, παραμένει. Τα ονόματα που προσθέτετε μπορούν να διαγραφούν.",
        urlCleanerRulesCoverageCaption: "Η λίστα καλύπτει τις διαφορετικές διαδρομές κοινής χρήσης ενός ιστότοπου, όπως την ιστοσελίδα, την εφαρμογή ή έναν ζωντανό χώρο. Γι’ αυτό είναι μεγάλη· ένας πραγματικός σύνδεσμος συνήθως περιέχει μόνο δύο έως τέσσερις από αυτές τις παραμέτρους.",
        urlCleanerRulesAllSites: "Όλοι οι ιστότοποι",
        urlCleanerRulesCountSingular: "1 παράμετρος",
        urlCleanerRulesCountPluralFormat: "%d παράμετροι",
        urlCleanerRulesAddSite: "Προσθήκη ιστότοπου",
        urlCleanerRulesParameterPlaceholder: "Όνομα παραμέτρου",
        urlCleanerRulesMatchCaption: "Γράψτε το όνομα που βρίσκεται αριστερά από το =, όπως utm_source. Αν το όνομα ταιριάζει, αφαιρείται μόνο αυτή η παράμετρος από τον σύνδεσμο και όλα τα υπόλοιπα παραμένουν όπως ήταν.",
        urlCleanerRulesAddButton: "Προσθήκη",
        urlCleanerRulesRemoveButton: "Διαγραφή ονόματος",
        urlCleanerRulesRemoveSiteButton: "Απενεργοποίηση όλων των κανόνων για αυτόν τον ιστότοπο",
        urlCleanerRemovedFormat: "Αφαιρέθηκαν %@",
        switcherSearchPin: "Καρφίτσωμα αναζήτησης με S",
        switcherSearchPinCaption: "Το S ξεκινά αναζήτηση και διατηρεί ανοιχτή την εναλλαγή, ώστε η πληκτρολόγηση να μην παράγει πλέον ειδικούς χαρακτήρες όταν η συντόμευσή σας χρησιμοποιεί ⌥ και μια αναζήτηση που ξεκινά με Q ή W να μην κλείνει κατά λάθος το παράθυρο ή την εφαρμογή.",
        invertVerticalScroll: "Αντιστροφή κατακόρυφης κύλισης",
        invertHorizontalScroll: "Αντιστροφή οριζόντιας κύλισης",
        scrollHorizontalName: "Οριζόντια κύλιση με παρατεταμένο πάτημα πλήκτρου",
        scrollHorizontalModifierLabel: "Πλήκτρο τροποποίησης",
        scrollHorizontalCommandKey: "Command",
        scrollHorizontalCaption: "Κρατήστε πατημένο μόνο το επιλεγμένο πλήκτρο τροποποίησης για να χρησιμοποιήσετε τον κατακόρυφο τροχό του ποντικιού για οριζόντια κύλιση. Οι άλλοι συνδυασμοί πλήκτρων δεν επηρεάζονται.",
        switcherShowShortcutHints: "Εμφάνιση υποδείξεων συντομεύσεων",
        switcherShowShortcutHintsCaption: "Εμφανίζει τις συντομεύσεις εφαρμογών και παραθύρων κάτω από τα εικονίδια.",
        uninstallerHomebrewPackageFormat: "Το %@ θα αφαιρεθεί επίσης από το Homebrew.",
        shelfEdgeToggle: "Άνοιγμα κοντά σε άκρο της οθόνης",
        shelfEdgeCaption: "Σύρετε ένα αρχείο προς το άκρο της οθόνης για να εμφανιστεί το Ράφι. Αποθέστε το εκεί ή απομακρύνετέ το από το άκρο για να κρυφτεί ξανά.",
        focusFollowsMouseName: "Η εστίαση ακολουθεί το ποντίκι",
        focusFollowsMouseCaption: "Εστιάζει και φέρνει στο προσκήνιο το παράθυρο κάτω από τον δείκτη μετά από μια σύντομη καθυστέρηση.",
        focusFollowsMouseDelay: "Καθυστέρηση κατάδειξης",
        focusFollowsMouseRaise: "Μεταφορά παραθύρου στο προσκήνιο",
        focusFollowsMouseWaitForStop: "Αναμονή μέχρι να σταματήσει ο δείκτης",
        switcherMinimizedPlacementLabel: "Ελαχιστοποιημένα παράθυρα",
        switcherTreatHiddenAppsLikeMinimized: "Αντιμετώπιση κρυμμένων εφαρμογών ως ελαχιστοποιημένων παραθύρων",
        switcherMinimizedPlacementNormal: "Κανονική σειρά",
        switcherMinimizedPlacementEnd: "Τοποθέτηση στο τέλος",
        switcherMinimizedPlacementHidden: "Απόκρυψη",
        switcherShowFullscreenWindows: "Εμφάνιση παραθύρων πλήρους οθόνης",
        switcherScreenPlacementLabel: "Εμφάνιση σε",
        switcherScreenPlacementPointer: "Οθόνη με τον δείκτη",
        switcherScreenPlacementMenuBar: "Οθόνη με τη γραμμή μενού",
        switcherScreenPlacementActiveWindow: "Οθόνη με το ενεργό παράθυρο",
        switcherScreenPlacementCaption: "Επιλέγει σε ποια οθόνη ανοίγει η εναλλαγή όταν είναι συνδεδεμένες περισσότερες από μία.",
        switcherCurrentDisplayOnly: "Εμφάνιση μόνο της τρέχουσας οθόνης",
        switcherCurrentDisplayOnlyCaption: "Εμφανίζει μόνο τα παράθυρα της οθόνης στην οποία βρίσκεται ο δείκτης. Αν αυτή η οθόνη δεν έχει παράθυρα, η εναλλαγή δεν ανοίγει.",
        smoothScrollResponseLabel: "Απόκριση",
        smoothScrollCoastLabel: "Αδράνεια",
        mouseAccelerationName: "Απενεργοποίηση επιτάχυνσης ποντικιού",
        mouseAccelerationCaption: "Αφαιρεί την επιτάχυνση του δείκτη για τα συνδεδεμένα ποντίκια. Η προηγούμενη ρύθμισή σας επανέρχεται όταν απενεργοποιηθεί αυτή η δυνατότητα ή τερματιστεί το Vorssaint.",
        linearScrollName: "Γραμμική κύλιση",
        linearScrollCaption: "Κάθε βήμα του τροχού του ποντικιού πραγματοποιεί κύλιση κατά την ίδια απόσταση, ανεξάρτητα από το πόσο γρήγορα περιστρέφεται. Η επιφάνεια αφής δεν επηρεάζεται.",
        linearScrollLinesLabel: "Γραμμές ανά βήμα",
        shelfClearOnClose: "Εκκαθάριση κατά το κλείσιμο",
        shelfClearOnCloseCaption: "Αδειάζει το Ράφι μόνο όταν κάνετε κλικ στο κουμπί κλεισίματός του. Η αυτόματη απόκρυψη και η σύμπτυξη διατηρούν τα στοιχεία.",
        shelfShortcutFinderSelection: "Προσθήκη της επιλογής Finder με τη συντόμευση",
        shelfShortcutFinderSelectionCaption: "Με το Finder στο προσκήνιο, η συντόμευση ανοίγει το Ράφι με τα επιλεγμένα αρχεία ήδη μέσα σε αυτό. Αν δεν έχει επιλεγεί τίποτα, ανοίγει κανονικά.",
        spacesOrderName: "Διατήρηση των γραφείων εργασίας σε σταθερή σειρά",
        spacesOrderCaption: "Αποτρέπει το macOS από το να αναδιατάσσει τα γραφεία εργασίας με βάση την πιο πρόσφατη χρήση, ώστε να παραμένουν στη σειρά που ορίσατε. Η προηγούμενη ρύθμιση επανέρχεται όταν απενεργοποιήσετε αυτή την επιλογή. Το Dock μπορεί να επανεκκινηθεί μία φορά για να εφαρμοστεί η αλλαγή.",
    )
}
