// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Tiếng Việt — translated and hand-checked, not machine output.
extension Strings {
    static let vi = Strings(
        statusIdleTooltip: "Vorssaint: ngủ bình thường",
        statusActiveUntil: "Vorssaint: thức đến",
        statusActiveIndefinite: "Vorssaint: thức vô thời hạn",
        menuEnableAwake: "Bật giữ máy thức",
        menuDisableAwake: "Tắt giữ máy thức",
        menuActivateFor: "Kích hoạt trong…",
        menuSettings: "Cài đặt…",
        menuAbout: "Giới thiệu Vorssaint",
        menuQuit: "Thoát Vorssaint",
        menuHide: "Ẩn Vorssaint",
        menuHideOthers: "Ẩn ứng dụng khác",
        menuShowAll: "Hiện tất cả",
        menuEdit: "Chỉnh sửa",
        menuUndo: "Hoàn tác",
        menuRedo: "Làm lại",
        actionClear: "Xóa",
        actionRemove: "Xóa",
        actionBack: "Quay lại",
        actionSearch: "Tìm kiếm",
        actionMute: "Tắt tiếng",
        actionUnmute: "Bật tiếng",
        actionPlay: "Phát",
        actionPause: "Tạm dừng",
        menuCut: "Cắt",
        menuCopy: "Sao chép",
        menuPaste: "Dán",
        menuSelectAll: "Chọn tất cả",
        menuWindow: "Cửa sổ",
        menuMinimize: "Thu nhỏ",
        menuZoom: "Phóng to",
        menuClose: "Đóng",

        minutes15: "15 phút",
        minutes30: "30 phút",
        hour1: "1 giờ",
        hours2: "2 giờ",
        hours4: "4 giờ",
        hours8: "8 giờ",
        indefinitely: "Vô thời hạn",
        indefinite: "Vô thời hạn",

        panelSettings: "Cài đặt",
        panelQuit: "Thoát",
        panelHotkeyHint: "Phím tắt để bật/tắt",

        keepAwakeTitle: "Giữ máy thức",
        keepAwakeEndsIn: "Kết thúc sau",
        keepAwakeUntilDisabled: "Hoạt động đến khi được tắt",
        keepAwakeNormalRules: "Mac tuân theo quy tắc năng lượng thông thường",
        keepAwakeOptions: "Tùy chọn",
        keepAwakeMouseJiggle: "Di chuyển con trỏ nhẹ",
        keepAwakeMouseJiggleCaption:
            "Trong một phiên, con trỏ được di chuyển nhẹ theo khoảng thời gian đã chọn.",
        keepAwakeMouseJiggleInterval: "Khoảng thời gian",
        keepAwakeActiveIconLabel: "Biểu tượng khi hoạt động",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Cà phê",
        keepAwakeActiveIconEye: "Mắt",
        keepAwakeActiveIconMoon: "Mặt trăng",
        keepAwakeActiveIconLight: "Bóng đèn",
        keepAwakeIconTintLabel: "Màu biểu tượng khi hoạt động",
        keepAwakeIconTintOrange: "Cam",
        keepAwakeIconTintGreen: "Xanh lá",
        keepAwakeIconTintBlue: "Xanh dương",
        keepAwakeIconTintPurple: "Tím",
        keepAwakeIconTintPink: "Hồng",
        keepAwakeIconTintNone: "Không màu",
        durationLabel: "Thời lượng",
        clamshellTitle: "Tiếp tục hoạt động khi gập màn hình",
        clamshellOnCaption: "Đã tắt hoàn toàn chế độ ngủ. Lưu ý mức pin",
        clamshellNeedsSession: "Áp dụng bất cứ khi nào “Giữ máy thức” đang hoạt động",
        clamshellReady: "Sẵn sàng. Bật/tắt không cần mật khẩu",
        clamshellNeedsPassword: "Sẽ hỏi mật khẩu quản trị viên một lần",

        systemSection: "Hệ thống",
        temperatures: "Nhiệt độ",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Pin",
        usageSection: "Mức sử dụng phần cứng",
        memorySection: "Bộ nhớ",
        memoryPressure: "Áp lực bộ nhớ",
        memorySwapUsed: "Bộ nhớ hoán đổi đã dùng",
        memoryCompressed: "Đã nén",
        memoryCachedFiles: "Tệp trong bộ đệm",
        pressureNormal: "Bình thường",
        pressureWarning: "Cần lưu ý",
        pressureCritical: "Nghiêm trọng",
        monitorUnavailable: "Không có cảm biến trên Mac này",
        energyAppsTitle: "Ứng dụng tiêu tốn nhiều năng lượng",
        energyAppsIdle: "Không có ứng dụng nào tiêu tốn nhiều năng lượng",

        notifySessionEndedTitle: "Phiên đã kết thúc",
        notifySessionEndedBody: "Đã hết thời gian. Mac sẽ ngủ bình thường trở lại.",
        notifyBatteryTitle: "Vorssaint đã tắt",
        notifyBatteryBody: "Pin yếu. Chế độ ngủ bình thường đã được khôi phục để bảo vệ pin.",
        adminPromptClamshellOn:
            "Vorssaint cần mật khẩu quản trị viên để tiếp tục hoạt động khi gập màn hình.",
        adminPromptClamshellOff:
            "Vorssaint cần mật khẩu quản trị viên để khôi phục chế độ ngủ bình thường của Mac.",
        adminPromptRecover:
            "Vorssaint đã thoát trong khi chế độ ngủ của Mac đang bị tắt. Nhập mật khẩu để khôi phục chế độ ngủ bình thường.",
        adminPromptUpdate: "Vorssaint cần mật khẩu quản trị viên để cài đặt bản cập nhật.",
        adminPromptSudoersInstall:
            "Vorssaint sẽ tạo một quy tắc giới hạn (chỉ pmset disablesleep) để bật/tắt chế độ gập màn hình mà không cần mật khẩu. Đây là lần duy nhất cần đến mật khẩu.",
        adminPromptSudoersRemove: "Vorssaint sẽ xóa quy tắc gập màn hình không cần mật khẩu.",

        settingsTitle: "Cài đặt Vorssaint",
        tabGeneral: "Chung",
        tabEnergy: "Năng lượng",
        tabMouse: "Chuột & Trackpad",
        tabSwitcher: "Bộ chuyển đổi",
        tabAdvanced: "Nâng cao",
        tabAbout: "Giới thiệu",
        tabReleaseNotes: "Có gì mới",
        releaseNotesOnUpdateToggle: "Hiện thông tin cập nhật sau khi cập nhật",
        minimalWindowPreviews: "Xem trước tối giản",
        minimalWindowPreviewsCaption:
            "Ẩn tiêu đề, nút và chi tiết trang trí trong hình xem trước ở Dock và bộ chuyển đổi. Mục đang chọn vẫn hiện rõ.",
        previewSizeLabel: "Kích thước xem trước",
        previewSizeNormal: "Bình thường",
        previewSizeLarge: "Lớn",
        previewSizeXLarge: "Rất lớn",
        settingsGroupFeatures: "Tính năng",
        advancedResetSection: "Quyền truy cập",
        advancedResetDescription:
            "Xóa mọi quyền đã cấp cho Vorssaint (Trợ năng, Ghi màn hình, Toàn quyền truy cập ổ đĩa và các quyền khác), mục khởi động cùng hệ thống và quy tắc gập màn hình. Hữu ích khi muốn bắt đầu lại từ đầu hoặc trước khi gỡ cài đặt. Ứng dụng vẫn được giữ nguyên.",
        advancedClearButton: "Xóa mọi quyền truy cập",
        advancedCleared: "Đã xóa quyền truy cập.",
        advancedClearConfirmTitle: "Xóa mọi quyền truy cập?",
        advancedClearConfirmBody:
            "Các tính năng cần quyền truy cập sẽ ngừng hoạt động cho đến khi được cấp quyền lại. Cài đặt vẫn được giữ nguyên.",
        advancedUninstallSection: "Gỡ cài đặt",
        advancedUninstallDescription:
            "Thực hiện tất cả các bước trên, sau đó xóa tùy chọn cài đặt và chuyển Vorssaint vào Thùng rác, không để lại gì. Ứng dụng sẽ thoát khi hoàn tất. Có thể cài đặt lại bất cứ lúc nào.",
        advancedUninstallButton: "Gỡ cài đặt Vorssaint hoàn toàn",
        advancedUninstallConfirmTitle: "Gỡ cài đặt Vorssaint?",
        advancedUninstallConfirmBody:
            "Vorssaint sẽ xóa quyền truy cập, xóa tùy chọn cài đặt và chuyển vào Thùng rác, sau đó thoát. Việc này không thể hoàn tác từ ứng dụng, nhưng vẫn nằm trong Thùng rác cho đến khi được dọn sạch.",
        advancedUninstallFailedTitle: "Đã dừng gỡ cài đặt",
        advancedUninstallFailedBody:
            "Vorssaint không thể khôi phục một cài đặt hệ thống đã thay đổi: chế độ ngủ, tốc độ quạt hoặc gia tốc chuột. Không có gì bị xóa. Hãy thử lại và cho phép yêu cầu mật khẩu nếu nó xuất hiện.",

        launchAtLogin: "Khởi chạy khi đăng nhập",
        languageLabel: "Ngôn ngữ",
        menuBarSection: "Thanh menu",
        showCountdown: "Hiện thời gian còn lại cạnh biểu tượng",
        globalHotkeySection: "Phím tắt toàn cục",
        hotkeyToggle: "Bật phím tắt cho “Giữ máy thức”",
        hotkeyCaption: "Hoạt động trong mọi ứng dụng, không cần thêm quyền truy cập.",

        sessionSection: "Phiên",
        defaultDurationLabel: "Thời lượng mặc định",
        keepAwakeAutoStart: "Giữ máy thức khi mở Vorssaint",
        keepAwakeAutoStartCaption: "Bắt đầu một phiên với thời lượng mặc định.",
        batteryProtectionSection: "Bảo vệ pin",
        batteryDisableBelow: "Tắt khi pin xuống dưới",
        batteryNever: "Không bao giờ",
        batteryProtectionCaption: "Tránh để một phiên bị quên làm cạn pin MacBook.",
        clamshellSection: "Gập màn hình",
        configuring: "Đang cấu hình…",
        sudoersFailed: "Không thể bật chế độ gập màn hình. Hãy thử lại.",
        clamshellExplanation:
            "“Tiếp tục hoạt động khi gập màn hình” tắt hoàn toàn chế độ ngủ trong khi “Giữ máy thức” đang hoạt động, và tự động khôi phục khi phiên kết thúc hoặc ứng dụng thoát. Nên dùng khi đang cắm sạc.",

        scrollSection: "Cuộn",
        invertMouseScroll: "Đảo chiều cuộn chuột",
        invertMouseScrollCaption: "Đảo ngược hướng cuộn của con lăn chuột.",
        scrollTrackpadNote: "Trackpad không bị ảnh hưởng: vẫn giữ hướng cuộn tự nhiên của macOS.",
        scrollActiveNow: "Đang đảo chiều cuộn chuột",
        mouseNavigationActiveNow: "Nút bên hông đang hoạt động",
        smoothScrollName: "Cuộn mượt",
        smoothScrollCaption:
            "Biến mỗi nấc cuộn của con lăn chuột thành một chuyển động trượt ngắn, mượt mà. Trackpad không bị ảnh hưởng.",
        smoothScrollStepLabel: "Khoảng cách mỗi nấc",
        mouseNavigationSection: "Điều hướng",
        mouseNavigationEnable: "Dùng nút bên hông để Lùi và Tiến",
        mouseNavigationCaption:
            "Biến các nút Lùi và Tiến của chuột thành lệnh điều hướng trong Finder, trình duyệt và các ứng dụng tương thích.",
        middleClickSection: "Nhấp giữa",
        middleClickEnable: "Chạm ba ngón hoạt động như nhấp giữa",
        middleClickEnableCaption:
            "Nhấn trackpad bằng ba ngón tay hoạt động như nhấp con lăn chuột: mở liên kết trong thẻ mới, đóng thẻ và mọi thao tác khác của nút giữa.",
        middleClickDragConflict:
            "Thao tác kéo ba ngón của macOS đang bật và dùng chung cử chỉ này. Hãy tắt trong Cài đặt Hệ thống, mục Trợ năng, Điều khiển con trỏ, Tùy chọn Trackpad, để nhấp giữa hoạt động được.",
        middleClickTapPicker: "Chạm nhẹ cũng tính là nhấp",
        middleClickTapOff: "Tắt",
        middleClickTapThreeFingers: "3 ngón",
        middleClickTapFourFingers: "4 ngón",
        middleClickTapCaption:
            "Một cái chạm nhẹ bằng đúng số ngón đó, không cần nhấn xuống, cũng kích hoạt nhấp giữa. Trượt tay không bao giờ được tính. Nếu thao tác chạm ba ngón của macOS đang gán cho Tra cứu, hãy tắt nó để hai thao tác không kích hoạt cùng lúc.",
        quickToolsTab: "Bảng nhanh",
        quickToolShortcutToggle: "Phím tắt toàn cục",
        ocrName: "Sao chép văn bản từ màn hình",
        ocrCaption:
            "Chọn một vùng trên màn hình, văn bản nhận dạng được sẽ được sao chép, sẵn sàng để dán.",
        ocrCopied: "Đã sao chép văn bản",
        ocrNoText: "Không tìm thấy văn bản",
        colorPickerName: "Công cụ chọn màu",
        colorPickerCaption:
            "Lấy màu của bất kỳ điểm ảnh nào trên màn hình và sao chép theo định dạng ưa thích.",
        colorPickerFormatLabel: "Định dạng khi sao chép",
        colorPickerBareHexToggle: "Sao chép không kèm tiền tố #",
        colorPickerPickNow: "Chọn màu",
        micMuteName: "Tắt tiếng micrô",
        micUnmuteName: "Bật tiếng micrô",
        micMuteCaption:
            "Tắt micrô của Mac bằng một cú nhấp hoặc phím tắt, áp dụng cho mọi ứng dụng.",
        micMutedHUD: "Đã tắt tiếng micrô",
        micUnmutedHUD: "Đã bật tiếng micrô trở lại",
        micMuteMenuBarToggle: "Hiện trên thanh menu khi đang tắt tiếng",
        micMuteMenuBarCaption:
            "Một biểu tượng micrô gạch chéo đỏ xuất hiện cạnh biểu tượng ứng dụng trên thanh menu.",
        pastePlainName: "Dán dưới dạng văn bản thuần",
        pastePlainCaption:
            "Dán nội dung đã sao chép mà không giữ màu sắc, phông chữ hay định dạng. Bản gốc vẫn còn trong bộ nhớ tạm.",
        launcherName: "Bảng nhanh",
        launcherCaption: "Một bảng nổi chứa các công cụ ưa thích, mở bằng phím tắt từ bất cứ đâu.",
        launcherOpenNow: "Mở bảng nhanh",
        launcherEditHint: "Dùng nút tinh chỉnh để chọn, ẩn và kéo sắp xếp lại các công cụ.",
        launcherEmptyState: "Mọi công cụ đều đang bị ẩn. Dùng nút tinh chỉnh để thêm lại.",
        launcherAddSection: "Thêm lại",
        launcherKeysHint: "Mũi tên để di chuyển, Enter để mở, 1 đến 9 để mở trực tiếp",

        switcherSection: "Bộ chuyển đổi ứng dụng",
        switcherEnable: "Dùng bộ chuyển đổi của Vorssaint",
        switcherEnableCaption:
            "Chuyển đổi giữa các ứng dụng và cửa sổ, kể cả cửa sổ đã thu nhỏ và nhiều cửa sổ của cùng một ứng dụng.",
        switcherUsageHint:
            "Giữ phím tắt để di chuyển; thả ra để kích hoạt cửa sổ. Shift hoặc ← để quay lại; W đóng cửa sổ; Q thoát ứng dụng; Esc hủy.",
        switcherNoWindows: "Không có cửa sổ đang mở",
        switcherIconRowMode: "Hiện %@ với biểu tượng lớn",
        switcherIconRowModeCaption:
            "Hiện một biểu tượng cho mỗi ứng dụng, kèm hình xem trước các cửa sổ của ứng dụng đó ở phía trên.",
        switcherSimpleMode: "Bộ chuyển đổi ứng dụng đơn giản",
        switcherSimpleModeCaption:
            "Hiện biểu tượng ứng dụng và tiêu đề cửa sổ, không có hình xem trước hay chụp màn hình từ bộ chuyển đổi.",
        switcherShortcutHintApps: "Ứng dụng",
        switcherShortcutHintWindows: "Cửa sổ",
        switcherWindowShortcutCaption:
            "Mở bộ chuyển đổi cho các cửa sổ của ứng dụng đang ở phía trước. Khi bộ chuyển đổi ứng dụng đang mở, chuyển giữa các cửa sổ của ứng dụng đang chọn.",
        switcherTakeOverSystemShortcuts: "Thay thế ⌘Tab và ⌘` của macOS",
        switcherTakeOverSystemShortcutsCaption:
            "Chỉ tắt các phím tắt ứng dụng và cửa sổ tương ứng của macOS trong khi bộ chuyển đổi của Vorssaint đang hoạt động. Mọi ứng dụng đang chạy vẫn có thể truy cập được.",
        switcherAppearanceDelay: "Độ trễ khi xuất hiện",
        switcherAppearanceDelayCaption: "Thời gian cần giữ phím tắt trước khi bộ chuyển đổi xuất hiện.",
        switcherMergeTabs: "Hiện một mục cho mỗi ứng dụng",
        switcherMergeTabsCaption:
            "Gộp toàn bộ cửa sổ của một ứng dụng thành một mục duy nhất trong bộ chuyển đổi, thay vì mỗi cửa sổ một mục.",
        switcherWindowlessApps: "Ứng dụng không có cửa sổ mở",
        switcherWindowlessAppsCaption:
            "Chọn những ứng dụng đang chạy nhưng không có cửa sổ nào sẽ hiện trong bộ chuyển đổi.",
        switcherWindowlessAppsOff: "Không hiện",
        switcherWindowlessAppsFinder: "Chỉ Finder",
        switcherWindowlessAppsAll: "Mọi ứng dụng",
        switcherNoOpenWindow: "Không có cửa sổ mở",
        switcherOtherDesktop: "Desktop khác",
        dockPreviewName: "Dock Preview",
        dockPreviewEnable: "Xem trước cửa sổ từ Dock",
        dockPreviewEnableCaption:
            "Di chuột qua một ứng dụng đang mở trên Dock để xem các cửa sổ của nó, sau đó nhấp vào cửa sổ muốn mở.",
        dockPreviewCurrentSpaceOnlyCaption:
            "Khi tắt, sẽ hiện cửa sổ từ mọi desktop. Chọn cửa sổ ở desktop khác sẽ chuyển bạn tới đó.",
        dockPreviewBackgroundOpacity: "Nền của bảng",
        dockPreviewBackgroundOpacityCaption: "Giảm xuống để thấy rõ hơn những gì phía sau bảng.",
        dockPreviewOpenDelay: "Độ trễ khi mở",
        dockPreviewOpenDelayCaption:
            "Thời gian con trỏ cần dừng trên một biểu tượng trước khi bảng của nó mở ra.",
        dockPreviewQuitAppOnClose: "Thoát ứng dụng bằng nút ×",
        dockPreviewQuitAppOnCloseCaption:
            "Trong Dock Preview, × sẽ thoát toàn bộ ứng dụng thay vì chỉ đóng cửa sổ đó.",
        dockClickMinimize: "Nhấp biểu tượng Dock để thu nhỏ",
        dockClickMinimizeCaption:
            "Các cửa sổ của ứng dụng đang hoạt động sẽ thu nhỏ khi nhấp vào biểu tượng Dock của nó. Nhấp lại để hiện lại.",
        dockClickCycleWindows: "Nhấp biểu tượng Dock để chuyển qua các cửa sổ",
        dockClickCycleWindowsCaption:
            "Nhấp biểu tượng Dock của ứng dụng đang hoạt động để xoay vòng qua các cửa sổ của nó, giống như ⌘`.",
        dockPreviewActiveNow: "Đang hoạt động trên Dock",
        dockPreviewDockUnavailable: "Không thể đọc các mục trên Dock.",
        dockPreviewAutohideBeta: "Bản beta. Có thể gặp một vài lỗi.",
        dockPreviewOpenWindow: "Mở cửa sổ",
        dockPreviewCloseWindow: "Đóng cửa sổ",
        dockPreviewMinimizeWindow: "Thu nhỏ cửa sổ",
        dockPreviewRestoreWindow: "Khôi phục cửa sổ",
        dockPreviewPinPanel: "Ghim bảng xem trước",
        dockPreviewUnpinPanel: "Bỏ ghim bảng xem trước",
        dockPreviewPinned: "Đã ghim",
        dockPreviewClosePanel: "Đóng bảng xem trước",
        dockPreviewPreviousWindow: "Cửa sổ trước",
        dockPreviewNextWindow: "Cửa sổ tiếp theo",

        cutPasteName: "Cắt & dán",
        cutPasteEnable: "Cắt & dán tệp trong Finder",
        cutPasteEnableCaption: "Dùng ⌘X để cắt và ⌘V để di chuyển tệp và thư mục trong Finder.",
        cutPasteShowHUD: "Hiện bảng nổi",
        cutPasteShowHUDCaption:
            "Hiện một bảng nổi hiển thị các tệp đã cắt trong khi Finder đang hoạt động.",
        cutPasteHowTitle: "Cách sử dụng",
        cutPasteStep1: "Chọn các mục trong Finder và nhấn ⌘X để cắt.",
        cutPasteStep2: "Mở thư mục đích và nhấn ⌘V để di chuyển chúng vào đó.",
        cutPasteTextNote:
            "Trong các ô văn bản (như khi đổi tên), ⌘X và ⌘V vẫn hoạt động như bình thường.",
        cutPasteActiveNow: "Sẵn sàng cắt trong Finder",
        cutPasteAutomationNote: "Lần đầu sử dụng, macOS sẽ hỏi quyền điều khiển Finder.",
        cutReadyTitle: "Đã cắt",
        cutReadyHint: "vào thư mục đích để di chuyển",
        cutCancel: "Hủy cắt",
        cutDoneTitle: "Đã di chuyển!",
        cutMovedSingular: "Đã di chuyển 1 mục",
        cutMovedPluralFormat: "Đã di chuyển %d mục",
        cutSomeFailed: "Một số mục không thể di chuyển được",
        cutMovingTitle: "Đang di chuyển…",
        cutMovingCountFormat: "%d trên %d",

        autoQuitName: "Thoát khi đóng cửa sổ",
        autoQuitEnable: "Thoát ứng dụng khi đóng cửa sổ cuối cùng",
        autoQuitEnableCaption:
            "Đóng cửa sổ cuối cùng của một ứng dụng cũng sẽ khiến ứng dụng đó thoát.",
        autoQuitActiveNow: "Đang hoạt động",
        autoQuitHowTitle: "Cách hoạt động",
        autoQuitStep1: "Đóng cửa sổ cuối cùng của một ứng dụng (⌘W hoặc nút đỏ).",
        autoQuitStep2:
            "Ứng dụng sẽ tự thoát. Hộp thoại “Lưu thay đổi?” vẫn xuất hiện như bình thường.",
        autoQuitPredictableNote:
            "Các ứng dụng thường chạy không cần cửa sổ sẽ không bao giờ bị thoát.",
        autoQuitExceptionsTitle: "Ngoại lệ",
        autoQuitExceptionsCaption:
            "Các ứng dụng trong danh sách này vẫn mở kể cả khi không có cửa sổ nào.",
        autoQuitExceptionsEmpty: "Không có ngoại lệ",
        autoQuitAddApp: "Thêm ứng dụng…",

        uninstallerName: "Bộ gỡ cài đặt",
        uninstallerEnableCaption:
            "Gỡ bỏ một ứng dụng cùng với bộ nhớ đệm, tùy chọn cài đặt, nhật ký và các tệp còn sót lại mà nó để lại.",
        uninstallerStep1: "Kéo một ứng dụng vào Cài đặt, hoặc chọn một ứng dụng từ danh sách.",
        uninstallerStep2: "Xem lại các tệp được tìm thấy và dung lượng chúng chiếm.",
        uninstallerStep3: "Chuyển những gì muốn xóa vào Thùng rác. Không có gì bị xóa vĩnh viễn.",
        uninstallerMenuItem: "Gỡ cài đặt một ứng dụng…",
        uninstallerDropTitle: "Kéo một ứng dụng vào đây",
        uninstallerDropSubtitle: "hoặc chọn một ứng dụng để quét",
        uninstallerChoose: "Chọn ứng dụng…",
        uninstallerPickerTitle: "Chọn ứng dụng",
        uninstallerPickerSearch: "Tìm ứng dụng",
        uninstallerPickerEmpty: "Không tìm thấy ứng dụng nào",
        uninstallerEmptyNote: "Không có gì bị xóa nếu chưa xác nhận.",
        uninstallerFDANote: "Cấp Toàn quyền truy cập ổ đĩa để quét kỹ hơn.",
        uninstallerFDAGrant: "Cấp quyền truy cập…",
        uninstallerFDAHint:
            "Bật Vorssaint trong danh sách. Nếu không có, nhấp + và chọn Vorssaint trong Ứng dụng. Quyền truy cập chỉ có hiệu lực sau khi mở lại ứng dụng.",
        uninstallerFDARelaunch: "Mở lại ngay",
        uninstallerScanning: "Đang quét tệp…",
        uninstallerRemoving: "Đang chuyển vào Thùng rác…",
        uninstallerFoundTitle: "đã tìm thấy",
        uninstallerSelectedFormat: "Đã chọn %d trên %d",
        uninstallerRemove: "Chuyển vào Thùng rác",
        uninstallerCancel: "Hủy",
        uninstallerDoneTitle: "Xong!",
        uninstallerFreedFormat: "Đã giải phóng %@",
        uninstallerSomeFailed: "Một số mục không thể chuyển vào Thùng rác.",
        uninstallerFailedNeedsFDA:
            "Dữ liệu ứng dụng chạy trong sandbox chỉ có thể di chuyển khi có Toàn quyền truy cập ổ đĩa. Mật khẩu quản trị viên không thay thế được quyền này.",
        uninstallerFailedMoreFormat: "và %d mục nữa",
        uninstallerAnother: "Gỡ cài đặt ứng dụng khác",
        uninstallerCatApp: "Ứng dụng",
        uninstallerCatSupport: "Hỗ trợ",
        uninstallerCatCaches: "Bộ nhớ đệm",
        uninstallerCatPreferences: "Tùy chọn cài đặt",
        uninstallerCatContainers: "Container",
        uninstallerCatLogs: "Nhật ký",
        uninstallerCatState: "Trạng thái đã lưu",
        uninstallerCatOther: "Khác",

        urlCleanerName: "Làm sạch URL",
        urlCleanerEnable: "Làm sạch URL đã sao chép",
        urlCleanerEnableCaption: "Loại bỏ tham số theo dõi khỏi các liên kết đã sao chép.",
        urlCleanerActiveNow: "Đang hoạt động",
        urlCleanerManualTitle: "Làm sạch ngay",
        urlCleanerInputPlaceholder: "Dán một URL",
        urlCleanerOutputPlaceholder: "URL đã làm sạch sẽ hiện ở đây",
        urlCleanerCleanButton: "Làm sạch",
        urlCleanerPasteButton: "Dán",
        urlCleanerCopyButton: "Sao chép",
        urlCleanerClearButton: "Xóa ô nhập",
        urlCleanerNoURL: "Hãy dán một URL hợp lệ.",
        urlCleanerNoChange: "Không có gì để làm sạch.",
        urlCleanerCleaned: "Đã làm sạch URL.",
        urlCleanerCopied: "Đã sao chép.",
        urlCleanerLocalNote: "Cục bộ. Không dùng mạng.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Tìm kiếm, cài đặt và gỡ bỏ formula và cask.",
        homebrewMissingTitle: "Không tìm thấy Homebrew",
        homebrewMissingBody:
            "Vorssaint có thể mở Terminal với trình cài đặt Homebrew chính thức. Terminal sẽ hiện các bước và hỏi mật khẩu nếu cần.",
        homebrewInstallHomebrew: "Cài đặt Homebrew",
        homebrewInstallHomebrewCaption: "Khi Terminal hoàn tất, quay lại đây và nhấp Làm mới.",
        homebrewInstallHomebrewOpened: "Đã mở trình cài đặt trong Terminal.",
        homebrewShellSetupTitle: "Hoàn tất thiết lập Terminal",
        homebrewShellSetupBody:
            "Homebrew đã được cài đặt, nhưng Terminal có thể chưa nhận ra lệnh brew. Vorssaint có thể mở Terminal với lệnh thiết lập.",
        homebrewShellSetupButton: "Thiết lập Terminal",
        homebrewShellSetupOpened: "Đã mở lệnh trong Terminal. Sau đó quay lại đây và nhấp Làm mới.",
        homebrewRefresh: "Làm mới",
        homebrewCheckPackages: "Kiểm tra gói",
        homebrewTrustTitle: "Tap chưa được tin cậy",
        homebrewTrustCaption:
            "Homebrew hiện yêu cầu xác nhận trước khi dùng tap của bên thứ ba. Hãy tin cậy %@ để tiếp tục.",
        homebrewTrustButton: "Tin cậy và tiếp tục",
        homebrewSearchPlaceholder: "Tìm gói",
        homebrewKeyboardHint: "Space hoặc Return sẽ đóng bảng của macOS. Hãy dùng nút tìm kiếm.",
        homebrewSearchButton: "Tìm kiếm",
        homebrewSearchResults: "Kết quả",
        homebrewInstalled: "Đã cài đặt",
        homebrewAll: "Tất cả",
        homebrewFormulas: "Formula",
        homebrewCasks: "Cask",
        homebrewNoPackages: "Không tìm thấy gói nào",
        homebrewNoSelection: "Chọn một gói đã cài đặt hoặc tìm một gói mới.",
        homebrewDetailsTitle: "Chi tiết gói",
        homebrewInstall: "Cài đặt",
        homebrewUninstall: "Gỡ cài đặt",
        homebrewUpgrade: "Cập nhật",
        homebrewUpgradeAll: "Cập nhật tất cả",
        homebrewUpdateHomebrew: "Cập nhật Homebrew",
        homebrewAllPackages: "gói",
        homebrewOpenTerminal: "Mở Terminal",
        homebrewCancelOperation: "Hủy",
        homebrewClearLog: "Xóa nhật ký",
        homebrewLogTitle: "Nhật ký",
        homebrewVersion: "Phiên bản",
        homebrewDescription: "Loại",
        homebrewHomepage: "Mở trang web",
        homebrewPopularity: "Mức phổ biến",
        homebrewPopularityFormat: "%@ lượt cài đặt trong %@ ngày",
        homebrewInstalledBadge: "Đã cài đặt",
        homebrewNotInstalledBadge: "Chưa cài đặt",
        homebrewUpdates: "Cập nhật",
        homebrewUpdateAvailableBadge: "Có bản cập nhật",
        homebrewLatestVersion: "Mới nhất",
        homebrewConfirmInstallTitle: "Cài đặt bằng Homebrew?",
        homebrewConfirmInstallBodyFormat:
            "Homebrew sẽ tải về và cài đặt %@. Các gói phụ thuộc cũng có thể được cài đặt.",
        homebrewConfirmUninstallTitle: "Gỡ cài đặt bằng Homebrew?",
        homebrewConfirmUninstallBodyFormat:
            "Homebrew sẽ gỡ cài đặt %@. Các tệp cấu hình có thể vẫn còn trên hệ thống.",
        homebrewConfirmUpgradeTitle: "Cập nhật bằng Homebrew?",
        homebrewConfirmUpgradeBodyFormat:
            "Homebrew sẽ tải về và áp dụng phiên bản mới nhất của %@. Các gói phụ thuộc cũng có thể được cập nhật.",
        homebrewConfirmUpgradeAllTitle: "Cập nhật tất cả bằng Homebrew?",
        homebrewConfirmUpgradeAllBody:
            "Homebrew sẽ tải về và áp dụng phiên bản mới nhất cho các gói có bản cập nhật. Các gói phụ thuộc cũng có thể được cập nhật.",
        homebrewConfirmUpdateHomebrewTitle: "Cập nhật Homebrew?",
        homebrewConfirmUpdateHomebrewBody:
            "Homebrew sẽ lấy thông tin mới nhất rồi tải lại các gói.",
        homebrewTerminalFallback:
            "Thao tác này cần Terminal để hỏi mật khẩu quản trị viên. Vorssaint không thu thập mật khẩu.",
        homebrewLoading: "Đang tải…",
        homebrewSearchEmpty: "Không có kết quả",
        homebrewOperationInstallFormat: "Đang cài đặt %@",
        homebrewOperationUninstallFormat: "Đang gỡ cài đặt %@",
        homebrewOperationUpgradeFormat: "Đang cập nhật %@",
        homebrewOperationUpgradeAll: "Đang cập nhật các gói",
        homebrewOperationUpdateHomebrew: "Đang cập nhật Homebrew",
        homebrewOperationInstalledFormat: "Đã cài đặt %@.",
        homebrewOperationUninstalledFormat: "Đã gỡ cài đặt %@.",
        homebrewOperationUpgradedFormat: "Đã cập nhật %@.",
        homebrewOperationUpgradedAll: "Đã cập nhật các gói.",
        homebrewOperationUpdatedHomebrew: "Đã cập nhật Homebrew.",
        homebrewOperationFailedFormat: "Không thể hoàn tất %@.",
        homebrewOperationCancelled: "Đã hủy thao tác.",
        homebrewOperationPreparing: "Đang chuẩn bị…",
        homebrewOperationDownloading: "Đang tải tệp…",
        homebrewOperationInstalling: "Đang cài đặt tệp…",
        homebrewOperationUninstalling: "Đang xóa tệp…",
        homebrewOperationUpgrading: "Đang cập nhật tệp…",
        homebrewOperationFinalizing: "Đang hoàn tất…",
        homebrewOperationRefreshing: "Đang làm mới danh sách…",
        homebrewOperationTerminal: "Tiếp tục trong Terminal.",
        homebrewOperationElapsedFormat: "Đã trôi qua %@",
        homebrewOperationShowDetails: "Hiện chi tiết",
        homebrewOperationHideDetails: "Ẩn chi tiết",
        homebrewOperationTechnicalLog: "Chi tiết kỹ thuật",
        homebrewOperationProgressUnknown: "Homebrew chưa báo cáo tỷ lệ phần trăm.",

        mediaName: "Media",
        mediaEnableCaption:
            "Nén video, chuyển đổi và xử lý ảnh, tạo GIF và trích xuất văn bản ngay trên máy.",
        mediaLocalNote: "Cục bộ. Không dùng mạng.",
        mediaToolVideo: "Video",
        mediaToolGIF: "GIF",
        mediaToolImage: "Ảnh",
        mediaToolText: "Văn bản",
        mediaSelectFile: "Chọn tệp",
        mediaDropHint: "Kéo một tệp vào đây hoặc nhấp để chọn.",
        mediaOutput: "Đầu ra",
        mediaOutputAutomatic: "Tự động",
        mediaChooseOutput: "Đích lưu",
        mediaStartVideo: "Nén video",
        mediaStartGIF: "Tạo GIF",
        mediaStartImage: "Xử lý ảnh",
        mediaStartConvertPDF: "Chuyển sang PDF",
        mediaStartText: "Trích xuất văn bản",
        mediaCancel: "Hủy",
        mediaStartTime: "Bắt đầu",
        mediaEndTime: "Kết thúc",
        mediaQuality: "Mức nén",
        mediaCompressionLow: "Thấp",
        mediaCompressionMedium: "Trung bình",
        mediaCompressionHigh: "Cao",
        mediaMaxSize: "Kích thước",
        mediaSizingResolution: "Độ phân giải",
        mediaSizingFileSize: "Dung lượng tệp",
        mediaTargetSize: "Dung lượng mục tiêu",
        mediaTargetSizeHint: "Độ phân giải sẽ tự điều chỉnh để giữ dung lượng dưới giới hạn này.",
        mediaErrorTargetTooSmall: "Dung lượng mục tiêu quá nhỏ cho đoạn này. Hãy cắt bớt hoặc tăng giới hạn.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Chiều rộng",
        mediaFPS: "FPS",
        mediaKeepAudio: "Giữ âm thanh",
        mediaCodec: "Codec",
        mediaFormat: "Định dạng",
        mediaStripMetadata: "Xóa metadata",
        mediaLoopGIF: "Lặp GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Chính xác",
        mediaOCRFast: "Nhanh",
        mediaLanguageCorrection: "Sửa lỗi ngôn ngữ",
        mediaTextOutputNote: "Văn bản trích xuất có thể được sao chép và lưu dưới dạng TXT.",
        mediaRunning: "Đang xử lý",
        mediaCompleted: "Hoàn tất",
        mediaCancelled: "Đã hủy.",
        mediaOpenInFinder: "Hiện",
        mediaCopyText: "Sao chép văn bản",
        mediaRunAgain: "Chạy lại",
        mediaEmptyText: "Không tìm thấy văn bản.",
        mediaResultSavedFormat: "Đã lưu thành %@",
        mediaResultSizeFormat: "%@ thành %@",
        mediaResultGrewCaption: "Tệp sau khi chuyển đổi có dung lượng lớn hơn bản gốc.",
        mediaErrorNoFile: "Hãy chọn một tệp trước.",
        mediaErrorNoVideo: "Tệp này không có track video.",
        mediaErrorSameOutput: "Hãy chọn đích lưu khác với tệp gốc.",
        mediaErrorUnsupported: "Định dạng không được macOS hỗ trợ.",

        shelfName: "Kệ tạm",
        shelfEnable: "Khu vực tạm để kéo tệp",
        shelfEnableCaption:
            "Một không gian nổi để gom tệp, ảnh và văn bản, rồi kéo chúng đi bất cứ đâu sau đó.",
        shelfHowTitle: "Cách sử dụng",
        shelfStep1: "Mở bằng phím tắt, hoặc lắc chuột trong khi đang kéo.",
        shelfStep2: "Thả tệp, ảnh, liên kết hoặc văn bản vào đó để giữ lại.",
        shelfStep3: "Kéo từng mục ra ứng dụng bất kỳ khi cần dùng.",
        shelfShakeToggle: "Mở bằng cách lắc chuột khi đang kéo",
        shelfShakeCaption:
            "Lắc con trỏ nhanh trong khi đang giữ một mục để gọi kệ tạm đến gần con trỏ.",
        shelfDropZoneToggle: "Giữ tệp đang kéo trên thanh menu",
        shelfDropZoneCaption:
            "Trong khi kéo một tệp, kệ tạm sẽ xuất hiện bên dưới biểu tượng trên thanh menu. Những gì được thả vào sẽ nằm ngay đó, trong một nút có thể thu nhỏ và mở bằng một cú nhấp, và sẽ biến mất khi kệ tạm trống.",
        shelfDropZoneLabel: "Thả vào đây",
        shelfCollapse: "Thu gọn",
        shelfBehaviorTitle: "Sau khi sử dụng",
        shelfCloseAfterDrop: "Đóng sau khi thả vào ứng dụng khác",
        shelfCloseAfterDropCaption:
            "Đóng kệ tạm khi đích đến chấp nhận các mục. Ghim trên bảng sẽ giữ nó luôn mở.",
        shelfRemoveAfterDrop: "Xóa mục sau khi thả",
        shelfRemoveAfterDropCaption:
            "Các mục được ứng dụng khác chấp nhận sẽ rời khỏi kệ tạm. Tắt tùy chọn này để giữ lại một bản sao.",
        shelfExclusionsTitle: "Ngoại lệ tự động",
        shelfExclusionsEmpty: "Chưa thêm ứng dụng nào.",
        shelfExclusionsCaption:
            "Thao tác lắc và vùng thả trên thanh menu sẽ bị tắt với các lượt kéo bắt đầu từ những ứng dụng này. Phím tắt và Mở ngay vẫn hoạt động bình thường.",
        shelfPin: "Giữ luôn mở",
        shelfUnpin: "Cho phép đóng sau khi dùng",
        extraBrightnessName: "Độ sáng bổ sung",
        extraBrightnessCaption:
            "Dùng dư địa HDR của màn hình để vượt qua độ sáng tối đa. Tốn nhiều pin hơn và Mac có thể nóng lên.",
        extraBrightnessLevelLabel: "Cường độ",
        extraBrightnessUnsupported:
            "Chỉ khả dụng trên màn hình XDR, như trên MacBook Pro 14 và 16 inch.",
        shelfHotkeyLabel: "Phím tắt",
        shelfOpenNow: "Mở ngay",
        shelfNoPermission: "Không yêu cầu quyền truy cập nào.",
        shelfMenuItem: "Mở kệ tạm",
        shelfTitle: "Kệ tạm",
        shelfEmpty: "Kéo các mục vào đây",
        shelfClearAll: "Xóa tất cả",
        shelfRemoveSelected: "Xóa mục đã chọn",
        shelfSelectedFormat: "Đã chọn %d",
        shelfHint: "Nhấp để chọn. Kéo ra để sử dụng, hoặc nhấp chuột phải để xem thêm thao tác.",
        shelfItemImage: "Ảnh",
        shelfTooltipItemsFormat: "%d mục",
        shelfTooltipItemsFew: "%d mục",
        shelfTooltipImageSingular: "%d ảnh",
        shelfTooltipImageFew: "%d ảnh",
        shelfTooltipImagePlural: "%d ảnh",
        shelfTooltipFileSingular: "%d tệp",
        shelfTooltipFileFew: "%d tệp",
        shelfTooltipFilePlural: "%d tệp",
        shelfTooltipNoteSingular: "%d ghi chú",
        shelfTooltipNoteFew: "%d ghi chú",
        shelfTooltipNotePlural: "%d ghi chú",
        shelfTooltipLinkSingular: "%d liên kết",
        shelfTooltipLinkFew: "%d liên kết",
        shelfTooltipLinkPlural: "%d liên kết",
        shelfActionOpen: "Mở",
        shelfActionOpenWith: "Mở bằng",
        shelfActionShare: "Chia sẻ",

        breakdownMeasuring: "Đang đo…",

        mixerSection: "Bộ trộn âm lượng",
        mixerEmpty: "Các ứng dụng đang dùng âm thanh sẽ hiện ở đây",
        mixerUnavailable: "Khả dụng từ macOS 14.4 trở lên",
        mixerPermissionBody:
            "Để chỉnh âm lượng riêng cho từng ứng dụng, hãy cho phép “Ghi màn hình và âm thanh hệ thống” trong Cài đặt Hệ thống. Âm thanh không bao giờ bị ghi lại.",
        mixerResetTooltip: "Đặt lại về 100%",
        mixerOutputDefault: "Mặc định",
        mixerOutputCurrent: "hiện tại",
        mixerOutputUnavailable: "Không có đầu ra",
        mixerOutputFallback: "Đang dùng thiết bị mặc định cho đến khi thiết bị này quay lại.",
        mixerBypassedCaption: "Ứng dụng này tự quản lý âm thanh của riêng nó.",
        mixerOutputTooltip: "Chọn đầu ra",
        mixerSystemOutputTitle: "Đầu ra",
        mixerSystemOutputNoDevices: "Không tìm thấy đầu ra nào",
        mixerSystemOutputTooltip: "Chọn đầu ra hệ thống",
        mixerSystemOutputErrorFormat: "Không thể chuyển: %@",
        mixerLowerOnHeadphonesDisconnect: "Giảm âm lượng khi ngắt kết nối tai nghe",
        mixerLowerOnHeadphonesDisconnectCaption:
            "Điều chỉnh đầu ra khi tai nghe có dây hoặc Bluetooth ngắt kết nối.",
        mixerHeadphonesDisconnectVolume: "Âm lượng sau khi ngắt kết nối",
        preciseVolumeRollerEnable: "Dùng bước âm lượng nhỏ hơn",
        preciseVolumeRollerCaption:
            "Biến con lăn và phím âm lượng thành các bước âm lượng hệ thống nhỏ hơn.",
        preciseVolumeRollerTapFailed: "Không thể theo dõi phím âm lượng.",
        soundOutputSwitcherTitle: "Bộ chuyển đổi đầu ra",
        soundOutputSwitcherEnable: "Chuyển đầu ra bằng phím tắt",
        soundOutputSwitcherCaption:
            "Chọn các đầu ra và dùng phím tắt để chuyển sang đầu ra khả dụng tiếp theo.",
        soundOutputSwitcherDevices: "Đầu ra trong vòng chuyển",
        soundOutputSwitcherNoAvailableSelection: "Hãy chọn ít nhất một đầu ra khả dụng.",
        mixerInputTitle: "Micrô",
        mixerInputNoDevices: "Không tìm thấy micrô nào",
        mixerInputUnavailable: "Không có micrô",
        mixerInputFallback: "Đang dùng micrô mặc định cho đến khi micrô này quay lại.",
        mixerInputTooltip: "Chọn micrô",
        mixerInputErrorFormat: "Không thể chuyển: %@",
        mixerVisibleApps: "Ứng dụng trong danh sách",
        mixerAllShown: "Tất cả",
        mixerHiddenCountLabel: "Đã ẩn",
        mixerHideFromList: "Ẩn khỏi danh sách",

        updatesSection: "Cập nhật",
        autoCheckToggle: "Tự động kiểm tra bản cập nhật",
        includeBetaUpdatesToggle: "Nhận bản cập nhật beta",
        includeBetaUpdatesCaption:
            "Các phiên bản beta chứa tính năng đang phát triển và có thể có lỗi hoặc chưa hoàn thiện.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Kiểm tra ngay",
        updateChecking: "Đang kiểm tra…",
        updateUpToDate: "Đang dùng phiên bản mới nhất.",
        updateAvailablePrefix: "Có bản cập nhật:",
        updateInstallButton: "Tải về và cài đặt",
        updateDownloading: "Đang tải bản cập nhật…",
        updateInstalling: "Đang cài đặt và khởi động lại…",
        updateFailedPrefix: "Không thể kiểm tra:",
        updateLastChecked: "Lần kiểm tra gần nhất:",
        updateNotifyTitle: "Cập nhật Vorssaint",
        updateInstallFailedBody:
            "Bản cập nhật đã được tải về nhưng không thể áp dụng. Hãy tải phiên bản mới nhất từ trang releases trên GitHub và kéo ứng dụng đè lên bản hiện tại.",
        updateNeedsApplicationsTitle: "Chuyển Vorssaint vào Ứng dụng",
        updateNeedsApplicationsBody:
            "Ứng dụng đang chạy từ một vị trí không thể cập nhật được, chẳng hạn như disk image hoặc một vị trí tạm của hệ thống. Hãy kéo Vorssaint vào thư mục Ứng dụng, mở từ đó rồi thử lại.",
        menuCheckUpdates: "Kiểm tra bản cập nhật…",

        permissionRequired: "Cần cấp quyền",
        permissionAccessibility: "Trợ năng",
        permissionScreenRecording: "Ghi màn hình",
        permissionGranted: "Đã cấp",
        permissionMissing: "Chưa cấp",
        permissionOpenSettings: "Mở Cài đặt Hệ thống…",
        permissionRequest: "Cấp quyền truy cập",
        permissionRestartNote: "macOS có thể yêu cầu mở lại ứng dụng sau khi cấp quyền.",

        aboutDescription:
            "Trung tâm tiện ích cho Mac.\nNăng lượng, theo dõi hệ thống, cuộn chuột và bộ chuyển đổi cửa sổ, ngay trên thanh menu.",
        versionPrefix: "Phiên bản",
        reviewIntro: "Xem lại phần giới thiệu",
        reviewHighlights: "Xem lại điểm nổi bật",
        viewOnGitHub: "Xem trên GitHub",

        obContinue: "Tiếp tục",
        obBack: "Quay lại",
        obSkipStep: "Bỏ qua bước này",
        obStart: "Mở Vorssaint",
        obStepWelcomeTitle: "Chào mừng đến với Vorssaint",
        obStepWelcomeBody:
            "Một tiện ích kín đáo trên thanh menu giúp macOS trở nên thực tế hơn mỗi ngày.",
        obWelcomeBullet1Title: "Kiểm soát năng lượng",
        obWelcomeBullet1Body: "Giữ Mac thức bao lâu tùy ý, kể cả khi gập màn hình.",
        obWelcomeBullet2Title: "Cái nhìn rõ ràng về hệ thống",
        obWelcomeBullet2Body:
            "Nhiệt độ CPU, GPU và pin, mức sử dụng phần cứng và áp lực bộ nhớ theo thời gian thực.",
        obWelcomeBullet3Title: "Chuột và cửa sổ theo cách riêng",
        obWelcomeBullet3Body: "Đảo chiều cuộn chuột và bộ chuyển đổi cửa sổ có hình thu nhỏ.",
        obLanguageLabel: "Ngôn ngữ",
        obStepAccessibilityTitle: "Trợ năng",
        obStepAccessibilityBody:
            "Cần thiết để đảo chiều cuộn chuột và để bộ chuyển đổi cửa sổ phản hồi bàn phím.",
        obAccessibilityWhy:
            "Ứng dụng chỉ theo dõi con lăn chuột và phím tắt của bộ chuyển đổi. Không có gì được ghi lại hay gửi đi bất cứ đâu.",
        obStepRecordingTitle: "Ghi màn hình",
        obStepRecordingBody:
            "Cho phép bộ chuyển đổi hiện hình thu nhỏ thực của cửa sổ thay vì chỉ biểu tượng.",
        obRecordingWhy:
            "Hình thu nhỏ được tạo ngay tức thì, chỉ lưu trong bộ nhớ và không bao giờ rời khỏi Mac. Nếu không có quyền này, bộ chuyển đổi vẫn hoạt động với biểu tượng.",
        obStepMonitorTitle: "Theo dõi hệ thống",
        obStepMonitorBody:
            "Bảng điều khiển hiện nhiệt độ CPU, GPU và pin, mức sử dụng phần cứng và áp lực bộ nhớ.",
        obMonitorNoPermission: "Không cần quyền truy cập. Cảm biến được đọc trực tiếp từ hệ thống.",
        obStepOptionalTitle: "Tính năng tùy chọn",
        obStepOptionalBody:
            "Bật những tính năng muốn dùng ngay. Mọi thứ đều có thể thay đổi sau trong Cài đặt.",
        obStepStatusTitle: "Kiểm tra",
        obStepStatusBody: "Đảm bảo mọi thứ đã sẵn sàng cho các tính năng muốn dùng.",
        obStatusRecheck: "Kiểm tra lại",
        obStepDoneTitle: "Đã sẵn sàng!",
        obStepDoneBody: "Vorssaint đã bắt đầu chăm sóc cho Mac.",
        obDoneHint: "Tìm biểu tượng lỗ đen trên thanh menu, ở góc trên bên phải màn hình.",
        obWhatsNewTitle: "Có gì mới trong phiên bản này",
        obWhatsNewFallback: "Bản cập nhật này bao gồm các bản sửa lỗi và cải tiến mới nhất.",
        obLanguageUpdateTitle: "Giờ đã có ngôn ngữ này",
        obLanguageUpdateBody:
            "Vorssaint giờ đã hỗ trợ nhiều ngôn ngữ. Hãy chọn ngôn ngữ muốn dùng; có thể đổi lại bất cứ lúc nào trong Cài đặt.",
        obPurposeTitle: "Mục đích chính khi dùng Vorssaint là gì?",
        obPurposeBody: "Chọn một cấu hình có sẵn, hoặc chọn chính xác những gì muốn dùng.",
        obPurposeSkip: "Có thể thêm hoặc bớt tính năng sau trong Cài đặt.",

        tabMonitor: "Theo dõi",
        monitorMenuBarSection: "Trên thanh menu",
        monitorMenuBarCaption: "Chọn nội dung hiện cạnh biểu tượng trên thanh menu.",
        monitorCombineTemperatures: "Gộp mức sử dụng và nhiệt độ",
        monitorCombineTemperaturesCaption:
            "Khi mức sử dụng và nhiệt độ của cùng một mục đều được bật, hiện chúng trong một khối.",
        monitorSeparateMenuBarMetrics: "Tách chỉ số thành từng mục riêng",
        monitorSeparateMenuBarMetricsCaption:
            "Tách các khối đang bật trên thanh menu và giữ mức sử dụng cùng nhiệt độ chung nhau khi gộp đang bật.",
        monitorNetworkUploadFirst: "Tải lên phía trên tải xuống",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Bộ nhớ",
        monitorShowNetwork: "Mạng",
        monitorShowPowerLabel: "Năng lượng",
        monitorIntervalLabel: "Cập nhật mỗi",
        monitorInterval1: "1 giây",
        monitorInterval2: "2 giây",
        monitorInterval5: "5 giây",
        monitorPanelSection: "Trên bảng điều khiển",
        panelNavigationMode: "Di chuyển bảng theo từng phần",
        panelNavigationCaption:
            "Hiện một phần tại một thời điểm. Chọn Danh sách để xem tất cả trong một lượt cuộn liên tục.",
        panelFooterSections: "Phần",
        panelFooterList: "Danh sách",
        betaBadge: "BETA",
        betaFeatureWarning: "Bản beta. Có thể gặp một vài lỗi.",

        networkSection: "Mạng",
        networkDownload: "Tải xuống",
        networkUpload: "Tải lên",
        networkThisSession: "Trong phiên này",
        networkMeasuring: "Đang đo…",
        networkApps: "Ứng dụng đang dùng mạng",
        networkAppsIdle: "Không có ứng dụng nào đang dùng mạng",

        diskSection: "Ổ đĩa",
        diskUsed: "đã dùng",
        diskFree: "còn trống",
        diskAvailable: "khả dụng",
        diskPurgeable: "có thể xóa",
        diskInternal: "Ổ trong",
        diskExternal: "Ổ ngoài",
        diskSelect: "Chọn ổ đĩa",
        diskRead: "Đọc",
        diskWrite: "Ghi",
        diskSMARTStatus: "Trạng thái",
        diskSMARTUnavailable: "Không có SMART cho ổ đĩa này",
        diskTotalRead: "Tổng đã đọc",
        diskTotalWritten: "Tổng đã ghi",
        diskTemperature: "Nhiệt độ",
        diskHealth: "Tình trạng",
        diskPowerCycles: "Số chu kỳ bật nguồn",
        diskPowerOnHours: "Số giờ hoạt động",
        diskUnsafeShutdowns: "Số lần tắt không an toàn",
        diskMediaErrors: "Lỗi vật lý",
        diskEject: "Ngắt kết nối",
        diskEjectAll: "Ngắt kết nối tất cả",
        diskEjecting: "Đang ngắt kết nối…",
        diskReadyToRemove: "Sẵn sàng để rút ra",
        diskEjectFailed: "Không thể ngắt kết nối",
        diskProtectionCaption: "Hãy ngắt kết nối trước khi rút ra.",
        diskNoExternal: "Không có ổ đĩa ngoài nào sẵn sàng để ngắt kết nối.",
        diskOpenInFinder: "Mở",
        diskStorageSettings: "Bộ nhớ",
        diskNoDisks: "Không tìm thấy ổ đĩa nào đã gắn kết.",

        powerSection: "Nguồn điện",
        powerSystem: "Hệ thống",
        powerAdapter: "Bộ sạc",
        powerBattery: "Pin",
        powerCharging: "Đang sạc",
        powerOnBattery: "Đang dùng pin",
        powerPluggedIn: "Đang cắm sạc",
        powerUnavailable: "Không có chỉ số nguồn điện trên Mac này",
        powerAdapterMaxFormat: "Tối đa %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Nhiệt độ CPU",
        monitorShowGPUTemperature: "Nhiệt độ GPU",
        monitorShowBatteryTemperature: "Nhiệt độ pin",
        monitorShowPeripheralBattery: "Pin thiết bị ngoại vi",
        peripheralBatteryNoDevices: "Không tìm thấy thiết bị nào",
        monitorGraphsSection: "Biểu đồ",
        monitorGraphsCaption: "Chọn những chỉ số nào hiện biểu đồ theo thời gian.",

        updateBannerTitle: "Có bản cập nhật",
        updateBannerAction: "Cập nhật",
        obStepMenuBarTitle: "Chỉ số trên thanh menu",
        obStepMenuBarBody:
            "Chọn nội dung hiện cạnh biểu tượng. Phần xem trước ở trên sẽ cập nhật trực tiếp.",
        obStepMenuBarNote:
            "Mới: khối Mạng và Năng lượng cùng biểu đồ trên bảng điều khiển. Có thể tinh chỉnh mọi thứ sau trong Cài đặt › Theo dõi.",
        monitorMenuBarPresetLabel: "Kiểu",
        menuBarPresetReadable: "Dễ đọc",
        menuBarPresetDense: "Dày đặc",
        menuBarSpacingLabel: "Khoảng cách trên thanh menu",
        menuBarSpacingStandard: "Tiêu chuẩn",
        menuBarSpacingCompact: "Gọn",
        menuBarHideIconToggle: "Ẩn biểu tượng ứng dụng khi đang hiện chỉ số",
        menuBarHideIconCaption:
            "Biểu tượng tự động hiện lại khi các chỉ số rời khỏi thanh menu và khi có điều gì cần thông báo (bản cập nhật đã sẵn sàng hoặc micrô đang tắt tiếng).",
        monitorLabelStyleLabel: "Nhãn",
        menuBarLabelStyleCompact: "Gọn",
        menuBarLabelStyleClassic: "Cổ điển",
        monitorMemoryStyleLabel: "Hiện bộ nhớ dưới dạng",
        monitorMemoryPressureDot: "Chấm áp lực",
        memoryStyleDot: "Chấm",
        memoryStylePercent: "%",
        memoryStyleBoth: "Cả hai",
        systemUptime: "Hoạt động được",
        batteryCharge: "Mức pin",
        powerHealth: "Tình trạng pin",
        powerCycles: "Số chu kỳ",
        speedTestRun: "Kiểm tra tốc độ",
        speedTestAgain: "Kiểm tra lại",
        speedTestLatency: "Độ trễ",
        speedTestTesting: "Đang kiểm tra…",
        speedTestFailed: "Kiểm tra thất bại",

        monitorShowInPanel: "Hiện trên bảng điều khiển",
        disclosureExpanded: "Đã mở rộng",
        disclosureCollapsed: "Đã thu gọn",
        panelHideItem: "Ẩn khỏi bảng điều khiển",
        panelShowItem: "Hiện trên bảng điều khiển",
        panelHiddenItem: "Đã ẩn",
        monitorItemUptime: "Thời gian hoạt động",
        monitorItemNetSpeed: "Tốc độ trực tiếp",
        monitorItemNetTotals: "Tổng trong phiên",
        monitorItemNetTest: "Kiểm tra tốc độ",
        monitorItemDiskUsage: "Dung lượng ổ đĩa",
        monitorItemDiskActivity: "Hoạt động trực tiếp",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Bảo vệ ổ ngoài",
        monitorItemDiskTools: "Công cụ",
        monitorPanelConfigHint: "Mở một khối để chọn nội dung hiển thị.",
        monitorOrderSection: "Thứ tự các phần",
        monitorOrderHint:
            "Kéo để sắp xếp lại thứ tự các phần trên bảng điều khiển, và dùng biểu tượng mắt để hiện hoặc ẩn từng phần.",
        obStepPanelTitle: "Nội dung trên bảng điều khiển",
        obStepPanelBody:
            "Mở từng khối và chọn chính xác nội dung hiển thị khi nhấp vào biểu tượng.",
        obStepPanelNavigationTitle: "Bảng điều khiển theo từng phần",
        obStepPanelNavigationBody:
            "Bảng điều khiển giờ có thể hiện từng phần một. Có thể chuyển giữa Phần và Danh sách trong Cài đặt.",

        cleaningMenuItem: "Chế độ Vệ sinh",
        utilitiesSection: "Tiện ích",
        quickControlsSection: "Điều khiển",
        panelCategoryWindows: "Cửa sổ",
        panelCategoryInput: "Chuột và bàn phím",
        panelCategoryFiles: "Tệp",
        windowMaximizeName: "Phóng to cửa sổ",
        windowMaximizeCaption: "Nút xanh lá sẽ phóng to mà không tạo Space mới.",
        windowMaximizeActiveNow: "Ghi đè nút xanh lá đang hoạt động",
        windowMaximizeNeedsAccessibility: "Cần quyền Trợ năng để hoạt động.",
        keyDebounceName: "Debounce",
        keyDebounceEnable: "Lọc phím nhấn trùng lặp",
        keyDebounceCaption: "Lọc các lần nhấn phím trùng lặp diễn ra quá nhanh.",
        keyDebounceActiveNow: "Bộ lọc đang hoạt động",
        keyDebounceGlobalWindow: "Cửa sổ thời gian chung",
        keyDebouncePerKeySection: "Phím cụ thể",
        keyDebouncePerKeyCaption:
            "Giá trị riêng cho từng phím sẽ ghi đè cửa sổ thời gian chung. Dùng 0 ms để ngừng lọc một phím.",
        keyDebounceKeyLabel: "Phím",
        keyDebounceWindowLabel: "Cửa sổ thời gian",
        keyDebounceAddKey: "Thêm phím",
        keyDebounceNoOverrides: "Chưa cấu hình phím cụ thể nào.",
        keyDebounceRemoveKey: "Xóa phím",
        cleaningPanelCaption: "Khóa bàn phím để vệ sinh an toàn.",
        cleaningOverlayTitle: "Bàn phím đã khóa để vệ sinh",
        cleaningOverlaySubtitle: "Nhấn Escape 5 lần để mở khóa",
        cleaningOverlayUnlock: "Mở khóa",
        cleaningOverlayMouseHint: "Chuột và trackpad vẫn hoạt động bình thường",
        cleaningKeepScreenVisibleToggle: "Giữ màn hình hiển thị",
        cleaningKeepScreenVisibleCaption:
            "Hiện một chỉ báo kín đáo ở góc màn hình thay vì làm tối toàn bộ nội dung.",
        cleaningStartNow: "Khóa bàn phím ngay",
        cleaningNeedsAxTitle: "Cần quyền Trợ năng",
        cleaningNeedsAxBody:
            "Để khóa bàn phím an toàn, Vorssaint cần quyền Trợ năng. Hãy cấp quyền trong Cài đặt Hệ thống rồi thử lại.",

        tabSupport: "Ủng hộ",
        shortcutsPageCaption:
            "Chỉnh sửa mọi phím tắt toàn cục của các tính năng đã cài đặt trên Mac này. Phím tắt không hoạt động vẫn được lưu nhưng sẽ không chạy.",
        shortcutsPageTitle: "Phím tắt",
        settingsSearchPlaceholder: "Tìm trong cài đặt",
        donateHeading: "Giúp Vorssaint tiếp tục phát triển",
        donateMessage:
            "Vorssaint là ứng dụng miễn phí, độc lập và được phát triển trong thời gian rảnh. Nếu muốn đóng góp tài chính, Buy Me a Coffee sẽ trực tiếp giúp duy trì quá trình phát triển.",
        donateButton: "Ủng hộ qua Buy Me a Coffee",
        donateThanks: "Cảm ơn vì đã đồng hành. 🖤",
        supportIntroTitle: "Giúp Vorssaint tiếp tục phát triển",
        supportIntroMessage:
            "Nếu muốn ủng hộ tài chính cho quá trình phát triển, Buy Me a Coffee là nơi duy nhất để làm điều đó.",
        supportIntroStarButton: "Gắn sao cho Vorssaint trên GitHub",
        supportIntroStarMessage:
            "Không bao giờ kỳ vọng vào sự ủng hộ tài chính. Một ngôi sao trên GitHub giúp nhiều người biết đến Vorssaint hơn và tạo ra khác biệt thực sự cho quá trình phát triển.",
        supportIntroCoffeeButton: "Ủng hộ qua Buy Me a Coffee",
        supportIntroLaterButton: "Để sau",
        supportIntroDoneButton: "Xong",
        discordIntroTitle: "Cộng đồng Vorssaint trên Discord vừa mới bắt đầu",
        discordIntroMessage:
            "Cộng đồng Vorssaint còn mới và đang được xây dựng. Hãy tham gia sớm để gặp gỡ những người dùng khác và cùng góp phần tạo nên một không gian thân thiện quanh ứng dụng.",
        discordIntroJoinButton: "Tham gia cộng đồng Discord",
        communityIntroTitle: "Xem trước mọi người",
        communityIntroMessage:
            "Những người đã theo dõi tôi trên X đã thấy trước nhiều thay đổi trong bản cập nhật này. Tôi đăng trước những tính năng sắp ra mắt và cách chúng hoạt động, để mọi người đã nắm được điều cơ bản trước khi bản cập nhật phát hành. Hãy theo dõi để xem điều gì sắp tới!",
        communityIntroFollowButton: "Theo dõi @vorssaint trên X",
        homebrewOfficialIntroTitle: "Hiện đã có trong danh mục Homebrew chính thức",
        homebrewOfficialIntroMessage:
            "Giờ đây có thể cài đặt Vorssaint trực tiếp từ danh mục Homebrew chính thức.",
        homebrewOfficialIntroInstallLabel: "Cài đặt mới",
        homebrewOfficialIntroMigrationTitle: "Đã dùng tap cũ?",
        homebrewOfficialIntroMigrationMessage:
            "Xóa tap cũ một lần. Ứng dụng và cài đặt vẫn được giữ nguyên.",
        homebrewOfficialIntroCopyButton: "Sao chép lệnh",
        updateShowcaseTitle: "Có gì mới trong 3.1.4",
        updateShowcaseMessage: "Xem nhanh những cải tiến chính trong bản cập nhật này.",
        updateShowcaseUnavailable: "Video hiện không thể tải. Vẫn có thể tiếp tục.",
        updateShowcaseRestart: "Xem lại từ đầu",
        showMenuBarIcon: "Hiện biểu tượng trên thanh menu",
        showMenuBarIconCaption:
            "Nếu biểu tượng Vorssaint biến mất (macOS có thể ẩn biểu tượng trên thanh menu khi thanh này hết chỗ, thường gặp trên các Mac có notch), hãy mở lại Vorssaint từ Ứng dụng hoặc Spotlight: thao tác đó sẽ dựng lại biểu tượng và, nếu vẫn bị ẩn, sẽ mở cửa sổ này. Nút phía trên cũng làm điều tương tự khi đã có thể truy cập đến đây. Giữ ít biểu tượng hơn trên thanh menu, hoặc ít chỉ số Vorssaint hơn, sẽ giúp giảm đáng kể khả năng này xảy ra.",
        menuBarIconStillHiddenTitle: "Biểu tượng vẫn đang bị ẩn",
        menuBarIconStillHiddenBody:
            "Biểu tượng đã được dựng lại, nhưng macOS chưa cấp cho nó một vị trí hiển thị. Thanh menu có thể đã hết chỗ: hãy bớt vài biểu tượng trên thanh menu (hoặc đóng các ứng dụng có menu dài) rồi thử lại.",
        menuBarIconManagerHintFormat:
            "%@ đang mở và có thể đang giữ biểu tượng trong phần ẩn của nó. Hãy tìm Vorssaint ở đó, hoặc đặt %@ luôn hiện Vorssaint.",
        shortcutRecording: "Nhấn phím tắt mới",
        shortcutReset: "Đặt lại",
        shortcutNone: "Không có",
        shortcutClear: "Xóa phím tắt",
        shortcutInvalid:
            "Hãy dùng ít nhất một trong các phím Control, Option hoặc Command kèm một phím khác.",
        shortcutPressKeys: "Nhấn các phím",
        shortcutEscapeHint: "Escape để hủy.",
        shortcutDeleteHint: "Delete để xóa.",
        shortcutNotCaptured:
            "Không ghi nhận được gì. macOS hoặc một ứng dụng khác đã dùng tổ hợp phím này. Hãy thử tổ hợp khác.",
        shortcutConflictFormat: "Phím tắt này đã được %@ sử dụng.",
        shortcutUnavailable: "macOS đã từ chối phím tắt này. Hãy chọn phím tắt khác.",
        shelfShortcutToggle: "Phím tắt kệ tạm",
        switcherUsageHintFormat:
            "Giữ %@ để di chuyển; thả ra để kích hoạt cửa sổ. Shift hoặc ← để quay lại; W đóng cửa sổ; Q thoát ứng dụng; Esc hủy.",
        musicBlockSection: "Phím media",
        musicBlockTitle: "Ngăn Music tự mở",
        musicBlockCaption:
            "Ứng dụng Music sẽ không còn tự mở khi nhấn phím media. Vẫn có thể mở thủ công bất cứ lúc nào.",
        musicBlockReplacementLabel: "Mở ứng dụng khác thay thế",
        musicBlockReplacementNone: "Không có",
        musicBlockChooseApp: "Chọn ứng dụng…",
        cleanerName: "Dọn dẹp",
        cleanerIntroTitle: "Dọn dẹp Mac",
        cleanerIntroCaption:
            "Quét các tệp còn sót của ứng dụng đã gỡ cài đặt, bộ nhớ đệm, nhật ký và Thùng rác. Mọi thứ được xem lại trước, và các mục đã xóa sẽ chuyển vào Thùng rác.",
        cleanerScan: "Quét",
        cleanerScanning: "Đang quét…",
        cleanerCleaning: "Đang dọn dẹp…",
        cleanerCatLeftovers: "Tệp còn sót của ứng dụng đã gỡ cài đặt",
        cleanerCatLoginItems: "Mục khởi động không còn liên kết",
        cleanerCatCaches: "Bộ nhớ đệm",
        cleanerCatLogs: "Nhật ký",
        cleanerCatDeveloper: "Tệp rác của nhà phát triển",
        cleanerCatTrash: "Thùng rác",
        cleanerLeftoversNote:
            "Được tìm thấy qua phân tích và chưa được chọn sẵn. Hãy kiểm tra đường dẫn trước khi chọn.",
        cleanerLoginItemsNote: "Mục trong Mục khởi động sẽ biến mất sau khi khởi động lại Mac.",
        cleanerTrashNote: "Dọn sạch Thùng rác là hành động không thể hoàn tác.",
        cleanerCatDeviceBackups: "Bản sao lưu iPhone",
        cleanerDeviceBackupsCaption:
            "Các bản sao lưu iPhone và iPad cũ chiếm một phần lớn dung lượng mà macOS gọi là Khác. Chỉ nên xóa những bản không còn cần thiết; một bản sao lưu mới sẽ được tạo khi kết nối lại thiết bị.",
        cleanerNothingFound: "Không có gì để dọn dẹp. Mac đang gọn gàng.",
        cleanerClean: "Dọn dẹp",
        cleanerDoneNote: "Các mục đã chuyển vào Thùng rác và có thể khôi phục từ đó.",
        cleanerAgain: "Quét lại",
        cleanerRevealInFinder: "Hiện trong Finder",
        cleanerPanelCaption: "Tệp còn sót của ứng dụng, bộ nhớ đệm và nhật ký",
        cleanerSafeSection: "Dọn dẹp an toàn",
        cleanerOptionalSection: "Tùy chọn, nên xem lại trước",
        cleanerCatOtherCaches: "Bộ nhớ đệm khác",
        cleanerCachesCaption: "Tệp tạm mà ứng dụng tự tạo lại được.",
        cleanerLogsCaption: "Nhật ký chẩn đoán cũ.",
        cleanerDeveloperCaption: "Tệp còn sót từ việc build Xcode và trình giả lập.",
        cleanerLoginItemsCaption: "Mục khởi động do các ứng dụng không còn tồn tại để lại.",
        cleanerLeftoversCaption: "Tệp còn sót lại từ các ứng dụng đã gỡ cài đặt.",
        cleanerOtherCachesCaption:
            "An toàn để xóa, không ảnh hưởng gì. Ứng dụng có thể mở chậm hơn một lần và nội dung đã tải, như nhạc ngoại tuyến, sẽ được tải lại.",
        cleanerCleanSizeFormat: "Dọn dẹp %@",
        cleanerScheduleTitle: "Dọn dẹp tự động",
        cleanerScheduleOff: "Tắt",
        cleanerScheduleDaily: "Hằng ngày",
        cleanerScheduleWeekly: "Hằng tuần",
        cleanerScheduleCaption:
            "Chỉ tự động dọn phần an toàn vào thời điểm đã chọn và chuyển mọi thứ vào Thùng rác.",
        cleanerScheduleLastFormat: "Lần dọn dẹp tự động gần nhất đã giải phóng %@.",
        cleanerAutoNotificationFormat: "Đã giải phóng %@ và chuyển vào Thùng rác.",
        cleanerScheduleNextFormat: "Lần dọn dẹp tiếp theo %@.",
        cleanerScheduleRanFormat: "Lần dọn dẹp tự động gần nhất %@.",
        cleanerScheduleNotifyToggle: "Thông báo khi hoàn tất",
        cleanerNotifDenied: "Thông báo của Vorssaint đang bị tắt trong hệ thống.",
        cleanerNotifOpenSettings: "Mở Cài đặt Thông báo…",
        launchAtLoginNeedsApplications:
            "Ứng dụng đang chạy từ một vị trí không thể mở khi đăng nhập. Hãy kéo Vorssaint vào thư mục Ứng dụng, mở từ đó rồi bật lại tùy chọn này.",
        launchAtLoginNeedsApproval:
            "Mục khởi động đã được đăng ký, nhưng vẫn đang tắt trong Cài đặt Hệ thống. Mở Cài đặt Hệ thống › Chung › Mục khởi động và Tiện ích mở rộng, rồi bật Vorssaint trong mục Mở khi đăng nhập.",
        ocrRemoveLineBreaksToggle: "Xóa ngắt dòng",
        ocrRemoveLineBreaksCaption:
            "Xóa các dấu ngắt dòng để văn bản đã sao chép dán thành một đoạn duy nhất.",
        ocrQRToggle: "Đọc mã QR",
        ocrQRCaption: "Nếu vùng chọn có mã QR, nội dung của nó sẽ hiện ra để sao chép hoặc mở.",
        ocrQRCopied: "Đã sao chép mã QR",
        qrResultTitle: "Mã QR",
        qrResultCopy: "Sao chép",
        qrResultOpen: "Mở liên kết",
        highlightsTitle: "Mới trong bản cập nhật này",
        highlightsTitleClipboardRedesign: "Bộ nhớ tạm được thiết kế lại",
        highlightsTitleWindowLayout: "Bố cục cửa sổ",
        highlightsTitleQuitProtection: "Bảo vệ khi thoát & đóng",
        highlightsTitleRecorderBlur: "Làm mờ riêng tư khi ghi hình",
        highlightsCaptionDockPreview:
            "Dock Preview giờ hoạt động được cả khi bật hiệu ứng phóng to Dock",
        highlightsCaptionScreenshot:
            "Công cụ chụp màn hình có thêm kính lúp điểm ảnh và khả năng đọc mã QR",
        highlightsCaptionSnippetLibrary:
            "Menu snippet có tìm kiếm sẽ gõ bất kỳ đoạn snippet nào ngay tại vị trí con trỏ",
        highlightsCaptionCapturePalette:
            "Một phím tắt duy nhất giờ mở ra một bảng nổi cho chụp màn hình, ghi hình, văn bản trên màn hình và màu sắc, cùng các tùy chỉnh gần đó.",
        highlightsCaptionClipboardRedesign:
            "Lịch sử bộ nhớ tạm giờ mở ra dưới dạng một bảng gọn nhẹ với các dòng rõ ràng và một bản xem trước theo yêu cầu để đọc hoặc chỉnh sửa toàn bộ mục.",
        highlightsCaptionWindowLayout:
            "Định vị cửa sổ bằng vòng định hướng qua phím tắt và con trỏ, hoặc kéo đến cạnh màn hình để ghim với khoảng cách tùy chỉnh.",
        highlightsCaptionQuitProtection:
            "Tránh thoát ứng dụng hoặc đóng cửa sổ ngoài ý muốn bằng cách giữ, nhấn đúp hoặc thêm phím bổ trợ, tùy chỉnh riêng cho từng ứng dụng.",
        highlightsCaptionRecorderBlur:
            "Ẩn thông tin cá nhân, mật khẩu và khu vực nhạy cảm ở bất kỳ đâu trong video đã ghi trước khi chia sẻ hoặc xuất.",
        highlightsConfigure: "Thiết lập",
        highlightsTry: "Dùng thử",
        highlightsSeeAll: "Xem tất cả thay đổi",
        switcherCurrentSpaceOnly: "Chỉ hiện desktop hiện tại",
        switcherCurrentSpaceOnlyCaption:
            "Chỉ liệt kê các cửa sổ thuộc desktop đang dùng. Chọn một cửa sổ sẽ không bao giờ chuyển sang desktop khác.",
        shelfFileMissing: "Tệp này không còn tồn tại",
        previewSizeSmall: "Nhỏ",
        mixerSoundEffectsOutputTitle: "Âm thanh hệ thống",
        mixerSoundEffectsOutputTooltip: "Chọn nơi phát cảnh báo và hiệu ứng âm thanh",
        monitorOpenActivityMonitor: "Mở Theo dõi Hoạt động",
        dockClickHide: "Nhấp biểu tượng Dock để ẩn ứng dụng",
        dockClickHideCaption:
            "Ứng dụng đang hoạt động sẽ ẩn khi nhấp vào biểu tượng Dock của nó. Nhấp lại để hiện lại.",
        monitorMemoryMetricLabel: "Đo bộ nhớ theo",
        memoryMetricUsed: "Bộ nhớ đã dùng",
        memoryMetricApp: "Bộ nhớ ứng dụng",
        keepAwakeRightClickToggle:
            "Nhấp chuột phải vào biểu tượng trên thanh menu để bật/tắt Giữ máy thức",
        keepAwakeRightClickToggleCaption: "Thay thế menu ngữ cảnh khi nhấp chuột phải.",
        urlCleanerRulesTitle: "Quy tắc làm sạch",
        urlCleanerRulesCaption:
            "Một trang web gắn các tham số này vào liên kết chia sẻ của riêng nó để theo dõi nguồn gốc liên kết. Khi bật, tên đó sẽ bị xóa lúc làm sạch liên kết; khi tắt, nó vẫn được giữ lại. Các tên tự thêm có thể xóa được.",
        urlCleanerRulesCoverageCaption:
            "Danh sách bao gồm các đường dẫn chia sẻ khác nhau của một trang (trang web, ứng dụng, phòng trực tiếp), nên khá dài; một liên kết thực tế thường chỉ mang theo hai đến bốn tham số trong số đó.",
        urlCleanerRulesAllSites: "Tất cả trang web",
        urlCleanerRulesCountSingular: "1 tham số",
        urlCleanerRulesCountPluralFormat: "%d tham số",
        urlCleanerRulesAddSite: "Thêm trang web",
        urlCleanerRulesParameterPlaceholder: "Tên tham số",
        urlCleanerRulesMatchCaption:
            "Nhập tên ở bên trái dấu =, ví dụ utm_source. Tên trùng khớp sẽ loại bỏ đúng tham số đó khỏi liên kết và giữ nguyên phần còn lại.",
        urlCleanerRulesAddButton: "Thêm",
        urlCleanerRulesRemoveButton: "Xóa tên",
        urlCleanerRulesRemoveSiteButton: "Tắt tất cả quy tắc của trang web này",
        urlCleanerRemovedFormat: "Đã xóa %@",
        switcherSearchPin: "Ghim tìm kiếm với S",
        switcherSearchPinCaption:
            "S bắt đầu một lượt tìm kiếm và ghim bộ chuyển đổi luôn mở, nên việc gõ chữ sẽ không còn tạo ra ký tự đặc biệt khi phím tắt dùng ⌥, và một lượt tìm kiếm bắt đầu bằng Q hoặc W sẽ không còn vô tình đóng cửa sổ hay thoát ứng dụng.",
        invertVerticalScroll: "Đảo chiều cuộn dọc",
        invertHorizontalScroll: "Đảo chiều cuộn ngang",
        switcherShowShortcutHints: "Hiện gợi ý phím tắt",
        switcherShowShortcutHintsCaption:
            "Hiện phím tắt của ứng dụng và cửa sổ bên dưới các biểu tượng.",
        uninstallerHomebrewPackageFormat: "%@ cũng sẽ được xóa khỏi Homebrew.",
        shelfEdgeToggle: "Mở gần cạnh màn hình",
        shelfEdgeCaption:
            "Kéo một tệp về phía cạnh màn hình để hé mở kệ tạm. Thả vào đó, hoặc kéo ngược lại để nó thu vào.",
        focusFollowsMouseName: "Tiêu điểm theo chuột",
        focusFollowsMouseCaption:
            "Đưa cửa sổ dưới con trỏ lên phía trước sau một khoảng dừng ngắn.",
        focusFollowsMouseDelay: "Độ trễ khi di chuột qua",
        switcherMinimizedPlacementLabel: "Cửa sổ đã thu nhỏ",
        switcherMinimizedPlacementNormal: "Thứ tự bình thường",
        switcherMinimizedPlacementEnd: "Đặt ở cuối",
        switcherMinimizedPlacementHidden: "Ẩn",
        switcherShowFullscreenWindows: "Hiện cửa sổ toàn màn hình",
        switcherScreenPlacementLabel: "Hiện trên",
        switcherScreenPlacementPointer: "Màn hình có con trỏ",
        switcherScreenPlacementMenuBar: "Màn hình có thanh menu",
        switcherScreenPlacementActiveWindow: "Màn hình có cửa sổ đang hoạt động",
        switcherScreenPlacementCaption:
            "Bộ chuyển đổi mở trên màn hình nào khi có nhiều hơn một màn hình được kết nối.",
        switcherCurrentDisplayOnly: "Chỉ hiện màn hình hiện tại",
        switcherCurrentDisplayOnlyCaption:
            "Chỉ liệt kê các cửa sổ trên màn hình có con trỏ. Nếu màn hình đó không có cửa sổ nào, bộ chuyển đổi sẽ không mở.",
        smoothScrollResponseLabel: "Phản hồi",
        mouseAccelerationName: "Tắt gia tốc chuột",
        mouseAccelerationCaption:
            "Loại bỏ gia tốc con trỏ cho các chuột đang kết nối. Cài đặt trước đó sẽ được khôi phục khi tắt tùy chọn này hoặc khi Vorssaint thoát.",
        shelfClearOnClose: "Xóa khi đóng",
        shelfClearOnCloseCaption:
            "Chỉ làm trống kệ tạm khi nhấp vào nút đóng của nó. Ẩn tự động và thu gọn vẫn giữ lại các mục."
    )
}
