// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Vorssaint

import Foundation

// Polski — translated and hand-checked, not machine output.
extension Strings {
    static let pl = Strings(
        statusIdleTooltip: "Vorssaint: normalny tryb uśpienia",
        statusActiveUntil: "Vorssaint: nie usypia do",
        statusActiveIndefinite: "Vorssaint: nie usypia (na stałe)",
        menuEnableAwake: "Włącz zapobieganie usypianiu",
        menuDisableAwake: "Wyłącz zapobieganie usypianiu",
        menuActivateFor: "Aktywuj na…",
        menuSettings: "Ustawienia…",
        menuAbout: "O programie Vorssaint",
        menuQuit: "Zakończ Vorssaint",
        menuHide: "Ukryj Vorssaint",
        menuHideOthers: "Ukryj pozostałe",
        menuShowAll: "Pokaż wszystkie",
        menuEdit: "Edycja",
        menuUndo: "Cofnij",
        menuRedo: "Przywróć",
        actionClear: "Wyczyść",
        actionRemove: "Usuń",
        actionBack: "Wstecz",
        actionSearch: "Szukaj",
        actionMute: "Wycisz",
        actionUnmute: "Wyłącz wyciszenie",
        actionPlay: "Odtwarzaj",
        actionPause: "Wstrzymaj",
        menuCut: "Wytnij",
        menuCopy: "Kopiuj",
        menuPaste: "Wklej",
        menuSelectAll: "Zaznacz wszystko",
        menuWindow: "Okno",
        menuMinimize: "Minimalizuj",
        menuZoom: "Zoom",
        menuClose: "Zamknij",

        minutes15: "15 minut",
        minutes30: "30 minut",
        hour1: "1 godzina",
        hours2: "2 godziny",
        hours4: "4 godziny",
        hours8: "8 godzin",
        indefinitely: "Na stałe",
        indefinite: "Czas nieokreślony",

        panelSettings: "Ustawienia",
        panelQuit: "Zakończ",
        panelHotkeyHint: "Skrót przełącza",

        keepAwakeTitle: "Zapobieganie usypianiu",
        keepAwakeEndsIn: "Koniec za",
        keepAwakeUntilDisabled: "Aktywne do momentu wyłączenia",
        keepAwakeNormalRules: "Mac stosuje standardowe zasady oszczędzania energii",
        keepAwakeUntilLabel: "Do",
        keepAwakeUntilStart: "Uruchom",
        keepAwakeOptions: "Opcje",
        keepAwakeMouseJiggle: "Delikatnie poruszaj wskaźnikiem",
        keepAwakeMouseJiggleCaption: "Podczas sesji delikatnie porusza wskaźnikiem w wybranym odstępie czasu.",
        keepAwakeMouseJiggleInterval: "Odstęp czasu",
        keepAwakeActiveIconLabel: "Ikona aktywności",
        keepAwakeActiveIconVorssaint: "Vorssaint",
        keepAwakeActiveIconCoffee: "Kawa",
        keepAwakeActiveIconEye: "Oko",
        keepAwakeActiveIconMoon: "Księżyc",
        keepAwakeActiveIconLight: "Żarówka",
        keepAwakeIconTintLabel: "Kolor aktywnej ikony",
        keepAwakeIconTintOrange: "Pomarańczowy",
        keepAwakeIconTintGreen: "Zielony",
        keepAwakeIconTintBlue: "Niebieski",
        keepAwakeIconTintPurple: "Fioletowy",
        keepAwakeIconTintPink: "Różowy",
        keepAwakeIconTintNone: "Bez koloru",
        durationLabel: "Czas trwania",
        clamshellTitle: "Działaj przy zamkniętej pokrywie",
        clamshellOnCaption: "Usypianie całkowicie wyłączone. Zwracaj uwagę na zasilanie",
        clamshellNeedsSession: "Stosowane zawsze, gdy aktywne jest „Zapobieganie usypianiu”",
        clamshellReady: "Gotowe. Przełączanie nie wymaga hasła",
        clamshellNeedsPassword: "Jednorazowo poprosi o hasło administratora",

        systemSection: "System",
        temperatures: "Temperatury",
        cpuLabel: "CPU",
        gpuLabel: "GPU",
        batteryLabel: "Bateria",
        usageSection: "Użycie sprzętu",
        memorySection: "Pamięć",
        memoryPressure: "Obciążenie",
        memorySwapUsed: "Użyta pamięć wymiany",
        memoryCompressed: "Skompresowana",
        memoryCachedFiles: "Pliki w pamięci podręcznej",
        pressureNormal: "W normie",
        pressureWarning: "Podwyższone",
        pressureCritical: "Krytyczne",
        monitorUnavailable: "Czujniki niedostępne na tym Macu",
        energyAppsTitle: "Aplikacje zużywające dużo energii",
        energyAppsIdle: "Brak znacznego zużycia energii",

        notifySessionEndedTitle: "Sesja zakończona",
        notifySessionEndedBody: "Czas minął. Mac powróci do standardowego trybu uśpienia.",
        notifyBatteryTitle: "Vorssaint wyłączony",
        notifyBatteryBody: "Niski poziom baterii. Przywrócono standardowe usypianie w celu oszczędzania energii.",
        adminPromptClamshellOn: "Vorssaint wymaga Twojego hasła, aby umożliwić działanie Maca przy zamkniętej pokrywie.",
        adminPromptClamshellOff: "Vorssaint wymaga Twojego hasła, aby przywrócić standardowe usypianie Maca.",
        adminPromptRecover: "Program Vorssaint został zamknięty, gdy usypianie Maca było wyłączone. Wprowadź hasło, aby przywrócić standardowe usypianie.",
        adminPromptUpdate: "Vorssaint wymaga Twojego hasła, aby zainstalować uaktualnienie.",
        adminPromptSudoersInstall: "Vorssaint utworzy regułę o ograniczonych uprawnieniach (tylko pmset disablesleep), aby przełączać tryb zamkniętej pokrywy bez pytania o hasło. To jedyny raz, kiedy hasło jest wymagane.",
        adminPromptSudoersRemove: "Vorssaint usunie regułę trybu zamkniętej pokrywy bez hasła.",

        settingsTitle: "Ustawienia Vorssaint",
        tabGeneral: "Ogólne",
        tabEnergy: "Energia",
        tabMouse: "Mysz i gładzik",
        tabSwitcher: "Przełącznik",
        tabAdvanced: "Zaawansowane",
        tabAbout: "O programie",
        tabReleaseNotes: "Nowości",
        releaseNotesOnUpdateToggle: "Pokazuj nowości po uaktualnieniu",
        minimalWindowPreviews: "Minimalistyczne podglądy",
        minimalWindowPreviewsCaption: "Ukrywa tytuły, przyciski i elementy ozdobne w podglądach Docka i przełącznika. Zaznaczenie pozostaje widoczne.",
        previewSizeLabel: "Wielkość podglądu",
        previewSizeNormal: "Standardowa",
        previewSizeLarge: "Duża",
        previewSizeXLarge: "Bardzo duża",
        settingsGroupFeatures: "Funkcje",
        advancedResetSection: "Uprawnienia",
        advancedResetDescription: "Usuwa wszystkie uprawnienia przyznane programowi Vorssaint (Dostępność, Nagrywanie ekranu, Pełny dostęp do dysku i inne), element logowania oraz regułę zamkniętej pokrywy. Przydatne do rozpoczęcia od nowa lub przed odinstalowaniem. Aplikacja pozostanie zainstalowana.",
        advancedClearButton: "Wyczyść wszystkie uprawnienia",
        advancedCleared: "Uprawnienia zostały wyczyszczone.",
        advancedClearFailed: "Nie udało się usunąć niektórych uprawnień lub reguły zamkniętej pokrywy. Spróbuj ponownie i potwierdź prośbę o hasło, jeśli się pojawi.",
        advancedClearConfirmTitle: "Wyczyścić wszystkie uprawnienia?",
        advancedClearConfirmBody: "Funkcje wymagające uprawnień przestaną działać do momentu ich ponownego przyznania. Twoje ustawienia zostaną zachowane.",
        advancedUninstallSection: "Odinstaluj",
        advancedUninstallDescription: "Wykonuje wszystkie powyższe czynności, a następnie usuwa preferencje i przenosi Vorssaint do Kosza, nie pozostawiając żadnych pozostałości. Po zakończeniu program kończy działanie. Możesz go zainstalować ponownie w dowolnym momencie.",
        advancedUninstallButton: "Odinstaluj całkowicie Vorssaint",
        advancedUninstallConfirmTitle: "Odinstalować Vorssaint?",
        advancedUninstallConfirmBody: "Vorssaint wyczyści swoje uprawnienia, usunie preferencje, zostanie przeniesiony do Kosza i zakończy działanie. Tej operacji nie można cofnąć z poziomu aplikacji, ale program pozostanie w Koszu do momentu jego opróżnienia.",
        advancedUninstallFailedTitle: "Odinstalowywanie przerwane",
        advancedUninstallFailedBody: "Vorssaint nie mógł przywrócić zmienionego ustawienia systemowego: usypiania, prędkości wentylatorów lub przyspieszenia myszy. Nic nie zostało usunięte. Spróbuj ponownie i potwierdź prośbę o hasło, jeśli się pojawi.",

        launchAtLogin: "Otwieraj podczas logowania",
        languageLabel: "Język",
        menuBarSection: "Pasek menu",
        showCountdown: "Pokazuj pozostały czas obok ikony",
        globalHotkeySection: "Skrót globalny",
        hotkeyToggle: "Włącz skrót dla „Zapobieganie usypianiu”",
        hotkeyCaption: "Działa w każdej aplikacji, bez dodatkowych uprawnień.",

        sessionSection: "Sesja",
        defaultDurationLabel: "Domyślny czas trwania",
        keepAwakeAutoStart: "Zapobiegaj usypianiu po otwarciu Vorssaint",
        keepAwakeAutoStartCaption: "Rozpoczyna sesję o domyślnym czasie trwania.",
        batteryProtectionSection: "Ochrona baterii",
        batteryDisableBelow: "Wyłącz, gdy poziom baterii spadnie poniżej",
        batteryNever: "Nigdy",
        batteryProtectionCaption: "Zapobiega rozładowaniu baterii MacBooka przez zapomnianą sesję.",
        clamshellSection: "Zamknięta pokrywa",
        configuring: "Konfigurowanie…",
        sudoersFailed: "Nie udało się włączyć trybu zamkniętej pokrywy. Spróbuj ponownie.",
        clamshellExplanation: "Funkcja „Działaj przy zamkniętej pokrywie” całkowicie wyłącza usypianie, gdy aktywne jest „Zapobieganie usypianiu”, i jest automatycznie wyłączana po zakończeniu sesji lub zamknięciu aplikacji. Zaleca się używanie jej przy podłączonym zasilaczu.",
        dimScreenOnLidCloseTitle: "Całkowicie ściemnij ekran",
        dimScreenOnLidCloseCaption: "Ściemnia ekran po zamknięciu pokrywy i przywraca jasność po jej otwarciu.",

        scrollSection: "Przewijanie",
        invertMouseScroll: "Odwróć przewijanie myszą",
        invertMouseScrollCaption: "Odwraca kierunek kółka myszy.",
        scrollTrackpadNote: "Nie dotyczy gładzika: zachowuje on naturalne przewijanie macOS.",
        scrollActiveNow: "Odwracanie przewijania myszą jest teraz aktywne",
        mouseNavigationActiveNow: "Przyciski boczne są teraz aktywne",
        smoothScrollName: "Płynne przewijanie",
        smoothScrollCaption: "Zmienia każdy skok kółka myszy w krótki, płynny ruch. Nie ma wpływu na gładzik.",
        smoothScrollStepLabel: "Szybkość przewijania",
        mouseNavigationSection: "Nawigacja",
        mouseNavigationEnable: "Używaj przycisków bocznych jako Wstecz i Dalej",
        mouseNavigationCaption: "Zmienia przyciski Wstecz i Dalej myszy w polecenia nawigacji w Finderze, przeglądarkach i zgodnych aplikacjach.",
        middleClickSection: "Środkowe kliknięcie",
        middleClickEnable: "Kliknięcie trzema palcami działa jak środkowe kliknięcie",
        middleClickEnableCaption: "Naciśnięcie gładzika trzema palcami działa jak kliknięcie kółkiem myszy: otwiera łącza na nowej karcie, zamyka karty i wykonuje wszystkie inne funkcje środkowego przycisku.",
        middleClickDragConflict: "Przeciąganie trzema palcami w macOS jest włączone i używa tego samego gestu. Wyłącz je w Ustawieniach systemowych w sekcji Dostępność > Sterowanie wskaźnikiem > Opcje gładzika, a środkowe kliknięcie zacznie działać.",
        middleClickTapPicker: "Lekkie stuknięcie również klika",
        middleClickTapOff: "Wyłączone",
        middleClickTapThreeFingers: "3 palce",
        middleClickTapFourFingers: "4 palce",
        middleClickTapCaption: "Lekkie stuknięcie taką liczbą palców bez naciskania również wywołuje środkowe kliknięcie. Przesunięcie nigdy się nie liczy. Jeśli stuknięcie trzema palcami w macOS jest przypisane do funkcji Sprawdź, wyłącz je, aby obie akcje nie uruchamiały się jednocześnie.",
        quickToolsTab: "Szybki panel",
        quickToolShortcutToggle: "Skrót globalny",
        ocrName: "Kopiuj tekst z ekranu",
        ocrCaption: "Zaznacz obszar ekranu, a rozpoznany tekst zostanie skopiowany, gotowy do wklejenia.",
        ocrCopied: "Skopiowano tekst",
        ocrNoText: "Nie znaleziono tekstu",
        colorPickerName: "Próbnik kolorów",
        colorPickerCaption: "Pobierz kolor dowolnego piksela na ekranie i skopiuj go w ulubionym formacie.",
        colorPickerFormatLabel: "Kopiowany format",
        colorPickerBareHexToggle: "Kopiuj bez prefiksu #",
        colorPickerPickNow: "Wybierz kolor",
        micMuteName: "Wycisz mikrofon",
        micUnmuteName: "Wyłącz wyciszenie mikrofonu",
        micMuteCaption: "Wycisza mikrofon Maca jednym kliknięciem lub skrótem we wszystkich aplikacjach.",
        micMutedHUD: "Mikrofon wyciszony",
        micUnmutedHUD: "Mikrofon włączony",
        micMutePartialHUD: "Nie udało się wyciszyć niektórych mikrofonów",
        micUnmutePartialHUD: "Niektóre mikrofony są nadal wyciszone",
        micMuteMenuBarToggle: "Pokazuj na pasku menu po wyciszeniu",
        micMuteMenuBarCaption: "Obok ikony aplikacji na pasku menu pojawi się czerwony, przekreślony mikrofon.",
        pastePlainName: "Wklej jako zwykły tekst",
        pastePlainCaption: "Wkleja skopiowaną zawartość bez kolorów, czcionek i formatowania. Oryginał pozostaje w schowku.",
        launcherName: "Szybki panel",
        launcherCaption: "Pływający panel z ulubionymi narzędziami, wywoływany skrótem z dowolnego miejsca.",
        launcherOpenNow: "Otwórz szybki panel",
        launcherEditHint: "Użyj przycisku dostosowywania, aby wybierać, ukrywać i przestawiać narzędzia.",
        launcherEmptyState: "Wszystkie narzędzia są ukryte. Użyj przycisku dostosowywania, aby dodać je z powrotem.",
        launcherAddSection: "Dodaj z powrotem",
        launcherKeysHint: "Strzałki nawigują, Enter otwiera, 1–9 otwierają bezpośrednio",
        switcherSection: "Przełącznik aplikacji",
        switcherEnable: "Używaj przełącznika Vorssaint",
        switcherEnableCaption: "Przełączaj się między aplikacjami i oknami, w tym zminimalizowanymi oknami oraz wieloma oknami tej samej aplikacji.",
        switcherUsageHint: "Przytrzymaj skrót, aby nawigować; puść, aby aktywować okno. Shift lub ← cofa; W zamyka okno; Q zamyka aplikację; Esc anuluje.",
        switcherNoWindows: "Brak otwartych okien",
        switcherIconRowMode: "Pokaż %@ z dużymi ikonami",
        switcherIconRowModeCaption: "Wyświetla jedną ikonę dla każdej aplikacji z podglądami jej okien powyżej.",
        switcherSimpleModeCaption: "Wyświetla ikony aplikacji i tytuły okien, bez podglądów i bez rejestrowania ekranu przez przełącznik.",
        switcherShortcutHintApps: "Aplikacje",
        switcherShortcutHintWindows: "Okna",
        switcherWindowShortcutCaption: "Otwiera przełącznik okien dla aplikacji na pierwszym planie. Gdy przełącznik aplikacji jest otwarty, przełącza między oknami zaznaczonej aplikacji.",
        switcherTakeOverSystemShortcuts: "Zastąp ⌘Tab i ⌘` w macOS",
        switcherTakeOverSystemShortcutsCaption: "Wyłącza odpowiednie skróty macOS dla aplikacji i okien tylko wtedy, gdy przełącznik Vorssaint jest aktywny. Wszystkie uruchomione aplikacje pozostają dostępne.",
        switcherAppearanceDelay: "Opóźnienie pojawienia się",
        switcherAppearanceDelayCaption: "Jak długo należy przytrzymać skrót, zanim pojawi się przełącznik.",
        switcherInstantSelection: "Natychmiastowy wybór",
        switcherInstantSelectionCaption: "Natychmiast przesuwa podświetlenie i przewija listę podczas przeglądania aplikacji i okien.",
        switcherMergeTabs: "Pokazuj jedną pozycję dla każdej aplikacji",
        switcherMergeTabsCaption: "Zwija wszystkie okna aplikacji do jednej pozycji w przełączniku zamiast jednej pozycji dla każdego okna.",
        switcherWindowlessApps: "Aplikacje bez otwartych okien",
        switcherWindowlessAppsCaption: "Określa, które uruchomione aplikacje bez żadnego okna mają być widoczne w przełączniku.",
        switcherWindowlessAppsOff: "Nie pokazuj",
        switcherWindowlessAppsFinder: "Tylko Finder",
        switcherWindowlessAppsAll: "Wszystkie aplikacje",
        switcherNoOpenWindow: "Brak otwartego okna",
        switcherOtherDesktop: "Inne biurko",
        dockPreviewName: "Podgląd Docka",
        dockPreviewEnable: "Podgląd okien z Docka",
        dockPreviewEnableCaption: "Najedź wskaźnikiem na otwartą aplikację w Docku, aby zobaczyć jej okna, a następnie kliknij wybrane.",
        dockPreviewCurrentSpaceOnlyCaption: "Gdy ta funkcja jest wyłączona, pokazywane są okna ze wszystkich biurek. Wybranie okna na innym biurku przenosi do niego.",
        dockPreviewBackgroundOpacity: "Tło panelu",
        dockPreviewBackgroundOpacityCaption: "Zmniejsz tę wartość, aby widzieć więcej tego, co znajduje się za panelem.",
        dockPreviewBackgroundOpacityGlassCaption: "Efekt Liquid Glass jest włączony, dlatego przezroczystość panelu ustawia się w: Ustawienia systemowe > Wygląd.",
        dockPreviewOpenDelay: "Opóźnienie otwarcia",
        dockPreviewOpenDelayCaption: "Jak długo wskaźnik musi pozostać na ikonie, zanim otworzy się jej panel.",
        dockPreviewQuitAppOnClose: "Zakończ aplikację przyciskiem ×",
        dockPreviewQuitAppOnCloseCaption: "W Podglądzie Docka przycisk × kończy działanie całej aplikacji zamiast zamykać tylko to okno.",
        dockPreviewKeepDockVisible: "Pozostawiaj Dock widoczny (eksperymentalne)",
        dockPreviewKeepDockVisibleCaption: "Wstrzymuje automatyczne ukrywanie, gdy podgląd jest otwarty, i przywraca je po jego opuszczeniu. Może zmienić rozmiar okien. Jeśli działanie aplikacji zostanie przerwane, otwórz ją ponownie, aby przywrócić Dock.",
        dockPreviewOrderByCreation: "Porządkuj okna według czasu utworzenia",
        dockPreviewOrderByCreationCaption: "Pokazuje najpierw starsze okna zamiast ostatnio używanych.",
        dockClickMinimize: "Kliknij ikonę w Docku, aby zminimalizować",
        dockClickMinimizeCaption: "Okna aktywnej aplikacji minimalizują się po kliknięciu jej ikony w Docku. Kliknij ponownie, aby je przywrócić.",
        dockClickCycleWindows: "Kliknij ikonę w Docku, aby przełączać okna",
        dockClickCycleWindowsCaption: "Kliknij ikonę aktywnej aplikacji w Docku, aby przełączać jej okna – podobnie jak za pomocą ⌘`.",
        dockPreviewActiveNow: "Aktywne w Docku",
        dockPreviewDockUnavailable: "Nie udało się odczytać elementów Docka.",
        dockPreviewAutohideBeta: "Wersja beta. Mogą wystąpić błędy.",
        dockPreviewOpenWindow: "Otwórz okno",
        dockPreviewCloseWindow: "Zamknij okno",
        dockPreviewMinimizeWindow: "Minimalizuj okno",
        dockPreviewRestoreWindow: "Przywróć okno",
        dockPreviewPinPanel: "Przypnij podgląd",
        dockPreviewUnpinPanel: "Odepnij podgląd",
        dockPreviewPinned: "Przypięte",
        dockPreviewClosePanel: "Zamknij podgląd",
        dockPreviewPreviousWindow: "Poprzednie okno",
        dockPreviewNextWindow: "Następne okno",

        cutPasteName: "Wytnij i wklej",
        cutPasteEnable: "Wytnij i wklej pliki w Finderze",
        cutPasteEnableCaption: "Użyj ⌘X, aby wyciąć, oraz ⌘V, aby przenieść pliki i foldery w Finderze.",
        cutPasteShowHUD: "Pokaż pływający panel",
        cutPasteShowHUDCaption: "Wyświetla pływający wskaźnik z wyciętymi plikami, gdy Finder jest aktywny.",
        cutPasteHowTitle: "Jak używać",
        cutPasteStep1: "Zaznacz rzeczy w Finderze i naciśnij ⌘X, aby je wyciąć.",
        cutPasteStep2: "Otwórz folder docelowy i naciśnij ⌘V, aby je tam przenieść.",
        cutPasteTextNote: "W polach tekstowych (np. podczas zmiany nazwy) skróty ⌘X i ⌘V działają jak zwykle.",
        cutPasteActiveNow: "Gotowe do wycinania w Finderze",
        cutPasteAutomationNote: "Za pierwszym razem system macOS poprosi o zgodę na sterowanie Finderem.",
        cutReadyTitle: "Wycięto",
        cutReadyHint: "w folderze docelowym, aby przenieść",
        cutCancel: "Anuluj wycinanie",
        cutDoneTitle: "Przeniesiono!",
        cutMovedSingular: "Przeniesiono 1 rzecz",
        cutMovedPluralFormat: "Przeniesiono %d rzeczy",
        cutSomeFailed: "Niektórych rzeczy nie udało się przenieść",
        cutMovingTitle: "Przenoszenie…",
        cutMovingCountFormat: "%d z %d",

        autoQuitName: "Zakończ po zamknięciu",
        autoQuitEnable: "Zakończ program po zamknięciu jego ostatniego okna",
        autoQuitEnableCaption: "Zamknięcie ostatniego okna programu powoduje również jego zakończenie.",
        autoQuitActiveNow: "Teraz aktywne",
        autoQuitHowTitle: "Jak to działa",
        autoQuitStep1: "Zamknij ostatnie okno programu (⌘W lub czerwony przycisk).",
        autoQuitStep2: "Program zakończy się automatycznie. Komunikaty „Zapisać zmiany?” będą nadal wyświetlane.",
        autoQuitPredictableNote: "Programy, które zwykle działają bez okna, nigdy nie są kończone.",
        autoQuitOngoingWorkNote: "Niektóre programy zamykają ostatnie okno, ale nadal działają, np. rejestrator ekranu po rozpoczęciu nagrywania. One również zostaną zakończone, chyba że znajdują się na liście wyjątków.",
        autoQuitExceptionsTitle: "Wyjątki",
        autoQuitExceptionsCaption: "Programy z tej listy pozostaną otwarte nawet bez okien.",
        autoQuitExceptionsEmpty: "Brak wyjątków",
        autoQuitAddApp: "Dodaj program…",

        uninstallerName: "Deinstalator",
        uninstallerEnableCaption: "Usuwa program wraz z pamięcią podręczną, preferencjami, dziennikami i pozostałościami, które po sobie zostawia.",
        uninstallerStep1: "Przeciągnij program do Ustawień lub wybierz go z listy.",
        uninstallerStep2: "Przejrzyj znalezione pliki i sprawdź, ile miejsca zajmują.",
        uninstallerStep3: "Przenieś do Kosza to, co chcesz. Nic nie jest usuwane trwale.",
        uninstallerMenuItem: "Odinstaluj program…",
        uninstallerDropTitle: "Przeciągnij program tutaj",
        uninstallerDropSubtitle: "lub wybierz program do przeskanowania",
        uninstallerChoose: "Wybierz program…",
        uninstallerPickerTitle: "Wybierz program",
        uninstallerPickerSearch: "Szukaj programów",
        uninstallerPickerEmpty: "Nie znaleziono programów",
        uninstallerEmptyNote: "Nic nie zostanie usunięte bez Twojego potwierdzenia.",
        uninstallerFDANote: "Przyznaj pełny dostęp do dysku, aby przeprowadzić dokładniejsze skanowanie.",
        uninstallerFDAGrant: "Przyznaj dostęp…",
        uninstallerFDAHint: "Włącz Vorssaint na liście. Jeśli go tam nie ma, kliknij przycisk + i wybierz program Vorssaint z folderu Aplikacje. Dostęp zacznie obowiązywać po ponownym otwarciu programu.",
        uninstallerFDARelaunch: "Uruchom ponownie teraz",
        uninstallerScanning: "Skanowanie plików…",
        uninstallerRemoving: "Przenoszenie do Kosza…",
        uninstallerFoundTitle: "znaleziono",
        uninstallerSelectedFormat: "Zaznaczono %d z %d",
        uninstallerRemove: "Przenieś do Kosza",
        uninstallerCancel: "Anuluj",
        uninstallerConfirmationExpired: "To potwierdzenie straciło ważność. Przejrzyj bieżące rzeczy i potwierdź ponownie.",
        uninstallerDoneTitle: "Gotowe!",
        uninstallerFreedFormat: "Zwolniono %@",
        uninstallerSomeFailed: "Niektórych rzeczy nie udało się przenieść do Kosza.",
        uninstallerFailedNeedsFDA: "Dane programów w piaskownicy można przenieść tylko przy pełnym dostępie do dysku. Hasło administratora go nie zastępuje.",
        uninstallerFailedMoreFormat: "i jeszcze %d",
        uninstallerAnother: "Odinstaluj kolejny",
        uninstallerCatApp: "Program",
        uninstallerCatSupport: "Pliki wsparcia",
        uninstallerCatCaches: "Pamięć podręczna",
        uninstallerCatPreferences: "Preferencje",
        uninstallerCatContainers: "Kontenery",
        uninstallerCatLogs: "Dzienniki",
        uninstallerCatState: "Zapisany stan",
        uninstallerCatOther: "Inne",
        uninstallerCommandBarBrowseTitle: "Odinstaluj program",
        uninstallerCommandBarToggle: "Pokaż w pasku poleceń",
        uninstallerCommandBarCaption: "Wybieraj i odinstalowuj programy w pasku poleceń.",
        uninstallerCommandBarFinderTitle: "Odinstaluj program zaznaczony w Finderze",
        uninstallerSelectionUnavailable: "Zaznacz w Finderze program, który można usunąć, lub wybierz inny z listy.",

        urlCleanerName: "Czyszczenie URL",
        urlCleanerEnable: "Oczyszczaj adresy URL podczas kopiowania",
        urlCleanerEnableCaption: "Usuwa parametry śledzące z łącza w momencie skopiowania go do schowka.",
        urlCleanerActiveNow: "Teraz aktywne",
        urlCleanerManualTitle: "Oczyść teraz",
        urlCleanerInputPlaceholder: "Wklej adres URL",
        urlCleanerOutputPlaceholder: "Tutaj pojawi się oczyszczony adres URL",
        urlCleanerCleanButton: "Oczyść",
        urlCleanerPasteButton: "Wklej",
        urlCleanerCopyButton: "Kopiuj",
        urlCleanerClearButton: "Wyczyść pole",
        urlCleanerNoURL: "Wklej prawidłowy adres URL.",
        urlCleanerNoChange: "Brak elementów do oczyszczenia.",
        urlCleanerCleaned: "Adres URL został oczyszczony.",
        urlCleanerCopied: "Skopiowano.",
        urlCleanerLocalNote: "Lokalnie. Bez połączenia z siecią.",

        homebrewName: "Homebrew",
        homebrewEnableCaption: "Wyszukuj, instaluj i usuwaj formuły oraz caski.",
        homebrewMissingTitle: "Nie znaleziono Homebrew",
        homebrewMissingBody: "Vorssaint może otworzyć Terminal z oficjalnym instalatorem Homebrew. Terminal wyświetli poszczególne kroki i w razie potrzeby poprosi o hasło.",
        homebrewInstallHomebrew: "Zainstaluj Homebrew",
        homebrewInstallHomebrewCaption: "Gdy Terminal zakończy działanie, wróć tutaj i kliknij Odśwież.",
        homebrewInstallHomebrewOpened: "Instalator został otwarty w Terminalu.",
        homebrewShellSetupTitle: "Dokończ konfigurację Terminala",
        homebrewShellSetupBody: "Homebrew jest zainstalowany, ale Terminal może jeszcze nie odnajdywać polecenia brew. Vorssaint może otworzyć Terminal z poleceniem konfiguracyjnym.",
        homebrewShellSetupButton: "Skonfiguruj Terminal",
        homebrewShellSetupOpened: "Polecenie zostało otwarte w Terminalu. Następnie wróć tutaj i kliknij Odśwież.",
        homebrewRefresh: "Odśwież",
        homebrewCheckPackages: "Sprawdź pakiety",
        homebrewTrustTitle: "Tap nie jest jeszcze zaufany",
        homebrewTrustCaption: "Homebrew prosi teraz o potwierdzenie przed użyciem tapów innych firm. Aby kontynuować, zaufaj %@.",
        homebrewTrustButton: "Zaufaj i kontynuuj",
        homebrewSearchPlaceholder: "Szukaj pakietów",
        homebrewKeyboardHint: "Spacja lub Return zamyka panel macOS. Użyj przycisku wyszukiwania.",
        homebrewSearchButton: "Szukaj",
        homebrewSearchResults: "Wyniki",
        homebrewInstalled: "Zainstalowane",
        homebrewAll: "Wszystko",
        homebrewFormulas: "Formuły",
        homebrewCasks: "Caski",
        homebrewNoPackages: "Nie znaleziono pakietów",
        homebrewDependencies: "Zależności",
        homebrewGroupDependencies: "Grupuj zależności",
        homebrewNoSelection: "Zaznacz zainstalowany pakiet lub wyszukaj nowy.",
        homebrewDetailsTitle: "Szczegóły pakietu",
        homebrewInstall: "Zainstaluj",
        homebrewUninstall: "Odinstaluj",
        homebrewUpgrade: "Uaktualnij",
        homebrewUpgradeAll: "Uaktualnij wszystko",
        homebrewUpdateHomebrew: "Uaktualnij Homebrew",
        homebrewAllPackages: "pakiety",
        homebrewOpenTerminal: "Otwórz Terminal",
        homebrewCancelOperation: "Anuluj",
        homebrewClearLog: "Wyczyść dziennik",
        homebrewLogTitle: "Dziennik",
        homebrewVersion: "Wersja",
        homebrewDescription: "Typ",
        homebrewHomepage: "Otwórz witrynę",
        homebrewPopularity: "Popularność",
        homebrewPopularityFormat: "Instalacje: %1$@ w ciągu %2$@ dni",
        homebrewInstalledBadge: "Zainstalowane",
        homebrewNotInstalledBadge: "Niezainstalowane",
        homebrewUpdates: "Uaktualnienia",
        homebrewUpdateAvailableBadge: "Dostępne uaktualnienie",
        homebrewLatestVersion: "Najnowsza",
        homebrewConfirmInstallTitle: "Zainstalować przez Homebrew?",
        homebrewConfirmInstallBodyFormat: "Homebrew pobierze i zainstaluje %@. Mogą zostać zainstalowane również zależności.",
        homebrewConfirmUninstallTitle: "Odinstalować przez Homebrew?",
        homebrewConfirmUninstallBodyFormat: "Homebrew odinstaluje %@. Pliki konfiguracyjne mogą pozostać w systemie.",
        homebrewConfirmUpgradeTitle: "Uaktualnić przez Homebrew?",
        homebrewConfirmUpgradeBodyFormat: "Homebrew pobierze i zastosuje najnowszą wersję %@. Zależności również mogą zostać uaktualnione.",
        homebrewConfirmUpgradeAllTitle: "Uaktualnić wszystko przez Homebrew?",
        homebrewConfirmUpgradeAllBody: "Homebrew pobierze i zastosuje najnowsze wersje pakietów, dla których dostępne są uaktualnienia. Zależności również mogą zostać uaktualnione.",
        homebrewConfirmUpdateHomebrewTitle: "Uaktualnić Homebrew?",
        homebrewConfirmUpdateHomebrewBody: "Homebrew pobierze najnowsze informacje, a następnie ponownie wczyta pakiety.",
        homebrewTerminalFallback: "Ta operacja wymaga Terminala, aby poprosić o hasło administratora. Vorssaint nie przechwytuje haseł.",
        homebrewLoading: "Wczytywanie…",
        homebrewSearchEmpty: "Brak wyników",
        homebrewOperationInstallFormat: "Instalowanie %@",
        homebrewOperationUninstallFormat: "Odinstalowywanie %@",
        homebrewOperationUpgradeFormat: "Uaktualnianie %@",
        homebrewOperationUpgradeAll: "Uaktualnianie pakietów",
        homebrewOperationUpdateHomebrew: "Uaktualnianie Homebrew",
        homebrewOperationInstalledFormat: "Zainstalowano %@.",
        homebrewOperationUninstalledFormat: "Odinstalowano %@.",
        homebrewOperationUpgradedFormat: "Uaktualniono %@.",
        homebrewOperationUpgradedAll: "Pakiety zostały uaktualnione.",
        homebrewOperationUpdatedHomebrew: "Homebrew został uaktualniony.",
        homebrewOperationFailedFormat: "Nie udało się ukończyć operacji dla %@.",
        homebrewOperationCancelled: "Operacja została anulowana.",
        homebrewOperationPreparing: "Przygotowywanie…",
        homebrewOperationDownloading: "Pobieranie plików…",
        homebrewOperationInstalling: "Instalowanie plików…",
        homebrewOperationUninstalling: "Usuwanie plików…",
        homebrewOperationUpgrading: "Uaktualnianie plików…",
        homebrewOperationFinalizing: "Kończenie…",
        homebrewOperationRefreshing: "Odświeżanie listy…",
        homebrewOperationTerminal: "Kontynuuj w Terminalu.",
        homebrewOperationElapsedFormat: "upłynęło %@",
        homebrewOperationShowDetails: "Pokaż szczegóły",
        homebrewOperationHideDetails: "Ukryj szczegóły",
        homebrewOperationTechnicalLog: "Szczegóły techniczne",
        homebrewOperationProgressUnknown: "Homebrew nie zgłosił jeszcze postępu procentowego.",

        mediaName: "Multimedia",
        mediaEnableCaption: "Kompresuj wideo, konwertuj i przetwarzaj obrazy, twórz pliki GIF oraz wyodrębniaj tekst lokalnie.",
        mediaLocalNote: "Lokalnie. Bez połączenia z siecią.",
        mediaToolVideo: "Wideo",
        mediaToolGIF: "GIF",
        mediaToolImage: "Obraz",
        mediaToolText: "Tekst",
        mediaSelectFile: "Wybierz plik",
        mediaDropHint: "Upuść plik tutaj lub kliknij, aby go wybrać.",
        mediaOutput: "Katalog wyjściowy",
        mediaOutputAutomatic: "Automatycznie",
        mediaChooseOutput: "Miejsce docelowe",
        mediaStartVideo: "Kompresuj wideo",
        mediaStartGIF: "Utwórz GIF",
        mediaStartImage: "Przetwórz obraz",
        mediaStartConvertPDF: "Konwertuj do PDF",
        mediaStartText: "Wyodrębnij tekst",
        mediaCancel: "Anuluj",
        mediaStartTime: "Początek",
        mediaEndTime: "Koniec",
        mediaQuality: "Kompresja",
        mediaCompressionLow: "Niska",
        mediaCompressionMedium: "Średnia",
        mediaCompressionHigh: "Wysoka",
        mediaCompressionLowDescription: "Wysoka jakość, duży rozmiar pliku",
        mediaCompressionMediumDescription: "Zrównoważona jakość i rozmiar pliku",
        mediaCompressionHighDescription: "Niska jakość, mały rozmiar pliku",
        mediaMaxSize: "Rozmiar",
        mediaSizingResolution: "Rozdzielczość",
        mediaSizingFileSize: "Rozmiar pliku",
        mediaTargetSize: "Rozmiar docelowy",
        mediaTargetSizeHint: "Rozdzielczość zostanie dostosowana, aby nie przekroczyć limitu.",
        mediaErrorTargetTooSmall: "Docelowy rozmiar jest zbyt mały dla tego klipu. Skróć go lub zwiększ limit.",
        mediaMegabytesSuffix: " MB",
        mediaWidth: "Szerokość",
        mediaFPS: "kl./s",
        mediaKeepAudio: "Zachowaj dźwięk",
        mediaCodec: "Kodek",
        mediaFormat: "Format",
        mediaStripMetadata: "Usuń metadane",
        mediaLoopGIF: "Zapętlaj GIF",
        mediaOCRMode: "OCR",
        mediaOCRAccurate: "Dokładny",
        mediaOCRFast: "Szybki",
        mediaLanguageCorrection: "Korekta językowa",
        mediaTextOutputNote: "Wyodrębniony tekst można skopiować i zapisać jako plik TXT.",
        mediaRunning: "Przetwarzanie",
        mediaCompleted: "Gotowe",
        mediaCancelled: "Anulowano.",
        mediaOpenInFinder: "Pokaż",
        mediaCopyText: "Kopiuj tekst",
        mediaRunAgain: "Uruchom ponownie",
        mediaEmptyText: "Nie znaleziono tekstu.",
        mediaResultSavedFormat: "Zapisano jako %@",
        mediaResultSizeFormat: "%@ na %@",
        mediaResultGrewCaption: "Przekonwertowany plik jest większy niż oryginał.",
        mediaErrorNoFile: "Najpierw wybierz plik.",
        mediaErrorNoVideo: "Ten plik nie zawiera ścieżki wideo.",
        mediaErrorSameOutput: "Wybierz miejsce docelowe inne niż plik źródłowy.",
        mediaErrorUnsupported: "Format nieobsługiwany przez system macOS.",

        shelfName: "Półka",
        shelfEnable: "Tymczasowy obszar do przeciągania plików",
        shelfEnableCaption: "Pływający obszar do gromadzenia plików, obrazów i tekstu, które możesz później przeciągnąć w dowolne miejsce.",
        shelfHowTitle: "Jak używać",
        shelfStep1: "Otwórz ją skrótem klawiszowym lub potrząsając myszą podczas przeciągania.",
        shelfStep2: "Upuść na nią pliki, obrazy, łącza lub tekst, aby je przechować.",
        shelfStep3: "Przeciągnij dowolny element do wybranego programu, gdy będzie Ci potrzebny.",
        shelfShakeToggle: "Otwieraj przez potrząśnięcie myszą podczas przeciągania",
        shelfShakeCaption: "Szybko potrząśnij wskaźnikiem podczas przeciągania elementu, aby wyświetlić półkę obok kursora.",
        shelfDropZoneToggle: "Przechowuj przeciągane pliki na pasku menu",
        shelfDropZoneCaption: "Podczas przeciągania pliku półka pojawia się pod ikoną na pasku menu. Wszystko, co upuścisz, pozostaje w przycisku, który możesz zwinąć lub otworzyć kliknięciem, a który znika, gdy półka jest pusta.",
        shelfDropZoneCaptionTopCenter: "Podczas przeciągania pliku półka pojawia się jako plakietka u góry na środku ekranu. Wszystko, co upuścisz, pozostaje w plakietce, którą otwierasz kliknięciem, a która znika, gdy półka jest pusta.",
        shelfDropZoneLabel: "Upuść tutaj",
        shelfDockPlacement: "Położenie",
        shelfDockMenuBar: "Pod ikoną na pasku menu",
        shelfDockTopCenter: "U góry na środku ekranu",
        shelfDockIslandNote: "Gdy funkcja Dynamic Island jest włączona, zajmuje górną środkową część ekranu.",
        shelfCollapse: "Zwiń",
        shelfBehaviorTitle: "Po użyciu",
        shelfCloseAfterDrop: "Zamknij po upuszczeniu w innym programie",
        shelfCloseAfterDropCaption: "Zamyka półkę, gdy program docelowy przyjmie elementy. Przypięcie w panelu pozostawia ją otwartą.",
        shelfRemoveAfterDrop: "Usuń elementy po upuszczeniu",
        shelfRemoveAfterDropCaption: "Elementy przyjęte przez inny program znikają z półki. Wyłącz tę opcję, aby zachować kopię na półce. Przypięte elementy zawsze pozostają.",
        shelfExclusionsTitle: "Automatyczne wyjątki",
        shelfExclusionsEmpty: "Brak dodanych aplikacji.",
        shelfExclusionsCaption: "Potrząsanie i strefa upuszczania na pasku menu pozostają wyłączone przy przeciąganiu rozpoczętym w tych aplikacjach. Skrót oraz przycisk „Otwórz teraz” nadal działają.",
        shelfPin: "Pozostaw otwarte",
        shelfUnpin: "Zezwalaj na zamykanie po użyciu",
        extraBrightnessName: "Dodatkowa jasność",
        extraBrightnessCaption: "Wykorzystuje zapas jasności HDR wyświetlacza, aby przekroczyć maksymalną jasność. Zużywa więcej energii z baterii, a Mac może się nagrzewać.",
        extraBrightnessLevelLabel: "Intensywność",
        extraBrightnessUnsupported: "Dostępne tylko na wyświetlaczach XDR, takich jak w 14- i 16-calowych MacBookach Pro.",
        shelfHotkeyLabel: "Skrót",
        shelfOpenNow: "Otwórz teraz",
        shelfNoPermission: "Nie wymaga uprawnień.",
        shelfMenuItem: "Otwórz półkę",
        shelfTitle: "Półka",
        shelfEmpty: "Przeciągnij elementy tutaj",
        shelfClearAll: "Wyczyść wszystko",
        shelfRemoveSelected: "Usuń zaznaczone",
        shelfSelectedFormat: "Zaznaczono: %d",
        shelfHint: "Kliknij, aby zaznaczyć. Przeciągnij na zewnątrz, aby użyć, lub kliknij prawym przyciskiem myszy, aby wyświetlić więcej czynności.",
        shelfItemImage: "Obraz",
        shelfTooltipItemsFormat: "%d elementów",
        shelfTooltipItemsFew: "%d elementy",
        shelfTooltipImageSingular: "%d obraz",
        shelfTooltipImageFew: "%d obrazy",
        shelfTooltipImagePlural: "%d obrazów",
        shelfTooltipFileSingular: "%d plik",
        shelfTooltipFileFew: "%d pliki",
        shelfTooltipFilePlural: "%d plików",
        shelfTooltipNoteSingular: "%d notatka",
        shelfTooltipNoteFew: "%d notatki",
        shelfTooltipNotePlural: "%d notatek",
        shelfTooltipLinkSingular: "%d łącze",
        shelfTooltipLinkFew: "%d łącza",
        shelfTooltipLinkPlural: "%d łączy",
        shelfActionOpen: "Otwórz",
        shelfActionOpenWith: "Otwórz w programie",
        shelfActionShare: "Udostępnij",
        shelfActionPin: "Przypnij",
        shelfActionUnpin: "Odepnij",

        breakdownMeasuring: "Mierzenie…",

        mixerSection: "Mikser głośności",
        mixerEmpty: "Aplikacje korzystające z dźwięku pojawią się tutaj",
        mixerUnavailable: "Dostępne w systemie macOS 14.4 i nowszych",
        mixerPermissionBody: "Aby regulować głośność poszczególnych aplikacji, zezwól na „Nagrywanie ekranu i dźwięku systemowego” w Ustawieniach systemowych. Dźwięk nigdy nie jest nagrywany.",
        mixerResetTooltip: "Przywróć 100%",
        mixerOutputDefault: "Domyślne",
        mixerOutputCurrent: "bieżące",
        mixerOutputUnavailable: "Wyjście niedostępne",
        mixerOutputFallback: "Używanie urządzenia domyślnego do czasu powrotu tego urządzenia.",
        mixerBypassedCaption: "Ta aplikacja zarządza dźwiękiem samodzielnie.",
        mixerOutputTooltip: "Wybierz wyjście",
        mixerSystemOutputTitle: "Wyjście",
        mixerSystemOutputNoDevices: "Nie znaleziono wyjść",
        mixerSystemOutputTooltip: "Wybierz wyjście systemowe",
        mixerSystemOutputErrorFormat: "Nie udało się przełączyć: %@",
        mixerLowerOnHeadphonesDisconnect: "Zmniejsz głośność po odłączeniu słuchawek",
        mixerLowerOnHeadphonesDisconnectCaption: "Dostosowuje poziom wyjściowy po odłączeniu słuchawek przewodowych lub Bluetooth.",
        mixerHeadphonesDisconnectVolume: "Głośność po odłączeniu",
        preciseVolumeRollerEnable: "Używaj mniejszych kroków głośności",
        preciseVolumeRollerCaption: "Dzieli regulację pokrętłami i klawiszami na mniejsze stopnie głośności systemowej.",
        preciseVolumeRollerTapFailed: "Nie udało się nasłuchiwać klawiszy głośności.",
        soundOutputSwitcherTitle: "Przełącznik wyjść",
        soundOutputSwitcherEnable: "Przełączaj wyjścia za pomocą skrótu",
        soundOutputSwitcherCaption: "Wybierz wyjścia i użyj skrótu, aby przejść do kolejnego dostępnego.",
        soundOutputSwitcherDevices: "Wyjścia w cyklu",
        soundOutputSwitcherNoAvailableSelection: "Wybierz co najmniej jedno dostępne wyjście.",
        mixerInputTitle: "Mikrofon",
        mixerInputNoDevices: "Nie znaleziono mikrofonów",
        mixerInputUnavailable: "Mikrofon niedostępny",
        mixerInputFallback: "Używanie mikrofonu domyślnego do czasu powrotu tego mikrofonu.",
        mixerInputTooltip: "Wybierz mikrofon",
        mixerInputErrorFormat: "Nie udało się przełączyć: %@",
        mixerVisibleApps: "Aplikacje na liście",
        mixerAllShown: "Wszystkie",
        mixerHiddenCountLabel: "Ukryte",
        mixerHideFromList: "Ukryj na liście",
        audioPrioritySection: "Priorytet urządzeń audio",
        audioPriorityOutputEnable: "Automatycznie przełączaj na wyjście o najwyższym priorytecie",
        audioPriorityInputEnable: "Automatycznie przełączaj na mikrofon o najwyższym priorytecie",
        audioPriorityOutputList: "Priorytet wyjść",
        audioPriorityInputList: "Priorytet mikrofonów",
        audioPriorityMoveUp: "Przenieś w górę",
        audioPriorityMoveDown: "Przenieś w dół",
        audioPriorityUnavailable: "Niedostępne",
        audioPriorityCurrent: "Bieżące",
        audioPriorityCaption: "Urządzenia są wybierane według priorytetu. Po podłączeniu urządzenia o wyższym priorytecie staje się ono aktywne. Gdy aktywne urządzenie zostanie odłączone, zastępuje je kolejne dostępne.",

        updatesSection: "Uaktualnienia",
        autoCheckToggle: "Sprawdzaj uaktualnienia automatycznie",
        includeBetaUpdatesToggle: "Otrzymuj uaktualnienia beta",
        includeBetaUpdatesCaption: "Wersje beta zawierają rozwijane funkcje i mogą powodować błędy lub działać niestabilnie.",
        betaBadgeLabel: "Beta",
        checkNowButton: "Sprawdź teraz",
        updateChecking: "Sprawdzam…",
        updateUpToDate: "Masz najnowszą wersję.",
        updateAvailablePrefix: "Dostępne uaktualnienie:",
        updateInstallButton: "Pobierz i zainstaluj",
        updateDownloading: "Pobieranie uaktualnienia…",
        updateInstalling: "Instalowanie i ponowne uruchamianie…",
        updateFailedPrefix: "Nie udało się sprawdzić:",
        updateLastChecked: "Ostatnio sprawdzono:",
        updateNotifyTitle: "Uaktualnienie Vorssaint",
        updateInstallFailedBody: "Uaktualnienie zostało pobrane, ale nie udało się go zainstalować. Pobierz najnowszą wersję ze strony wydań w serwisie GitHub i przeciągnij aplikację na bieżącą.",
        updateNeedsApplicationsTitle: "Przenieś Vorssaint do folderu Aplikacje",
        updateNeedsApplicationsBody: "Aplikacja została uruchomiona z miejsca, którego nie można uaktualnić, takiego jak obraz dysku lub tymczasowa lokalizacja systemowa. Przeciągnij Vorssaint do folderu Aplikacje, otwórz ją stamtąd i spróbuj ponownie.",
        menuCheckUpdates: "Sprawdź uaktualnienia…",

        permissionRequired: "Wymagane uprawnienie",
        permissionAccessibility: "Dostępność",
        permissionScreenRecording: "Nagrywanie ekranu",
        permissionGranted: "Przyznano",
        permissionMissing: "Nie przyznano",
        permissionOpenSettings: "Otwórz Ustawienia systemowe…",
        permissionRequest: "Przyznaj dostęp",
        permissionRestartNote: "System macOS może poprosić o ponowne otwarcie aplikacji po przyznaniu uprawnień.",
        secureInputTitle: "Bezpieczne wprowadzanie jest włączone",
        secureInputHeldFormat: "%@ blokuje bezpieczne wprowadzanie, przez co Vorssaint nie może wpisywać tekstu za Ciebie. Opuść pole hasła lub zamknij tę aplikację, aby je zwolnić.",
        secureInputUnattributed: "Żadna uruchomiona aplikacja nie zgłasza jego użycia. Wyloguj się i zaloguj ponownie, aby je wyczyścić.",
        secureInputUnidentified: "Nie udało się zidentyfikować aplikacji blokującej bezpieczne wprowadzanie, więc Vorssaint nie może pisać za Ciebie.",
        secureInputRevealFormat: "Pokaż %@",

        aboutDescription: "Centrum narzędziowe dla Twojego Maca.\nZasilanie, monitor systemu, przewijanie i przełącznik okien bezpośrednio na pasku menu.",
        versionPrefix: "Wersja",
        reviewIntro: "Zobacz wprowadzenie ponownie",
        reviewHighlights: "Zobacz nowości ponownie",
        viewOnGitHub: "Zobacz w serwisie GitHub",

        obContinue: "Dalej",
        obBack: "Wstecz",
        obSkipStep: "Pomiń ten krok",
        obStart: "Otwórz Vorssaint",
        obStepWelcomeTitle: "Witamy w Vorssaint",
        obStepWelcomeBody: "Dyskretne narzędzie na pasku menu, które ułatwia codzienną pracę w systemie macOS.",
        obWelcomeBullet1Title: "Energia pod kontrolą",
        obWelcomeBullet1Body: "Zapobiegaj usypianiu Maca tak długo, jak chcesz – nawet przy zamkniętej pokrywie.",
        obWelcomeBullet2Title: "Pełny wgląd w system",
        obWelcomeBullet2Body: "Temperatury procesora, układu graficznego i baterii, wykorzystanie sprzętu oraz obciążenie pamięci w czasie rzeczywistym.",
        obWelcomeBullet3Title: "Mysz i okna na Twoich zasadach",
        obWelcomeBullet3Body: "Odwrócone przewijanie myszą oraz przełącznik okien z miniaturami.",
        obLanguageLabel: "Język",
        obStepAccessibilityTitle: "Dostępność",
        obStepAccessibilityBody: "Wymagane do odwrócenia kierunku przewijania myszą oraz obsługi przełącznika okien z klawiatury.",
        obAccessibilityWhy: "Aplikacja monitoruje wyłącznie kółko myszy oraz skrót przełącznika. Nic nie jest nagrywane ani nigdzie wysyłane.",
        obStepRecordingTitle: "Nagrywanie ekranu",
        obStepRecordingBody: "Pozwala przełącznikowi wyświetlać rzeczywiste miniatury okien zamiast samych ikon.",
        obRecordingWhy: "Miniatury są generowane na bieżąco, przechowywane w pamięci i nigdy nie opuszczają Twojego Maca. Bez tego uprawnienia przełącznik nadal działa, wyświetlając ikony.",
        obStepMonitorTitle: "Monitor systemu",
        obStepMonitorBody: "Panel wyświetla temperatury procesora, układu graficznego i baterii, wykorzystanie sprzętu oraz obciążenie pamięci.",
        obMonitorNoPermission: "Uprawnienia nie są wymagane. Odczyty czujników pochodzą bezpośrednio z systemu.",
        obStepOptionalTitle: "Funkcje opcjonalne",
        obStepOptionalBody: "Włącz funkcje, których chcesz używać od zaraz. Wszystko możesz zmienić później w Ustawieniach.",
        obStepStatusTitle: "Sprawdzenie gotowości",
        obStepStatusBody: "Upewnij się, że wszystko jest gotowe do obsługi wybranych funkcji.",
        obStatusRecheck: "Sprawdź ponownie",
        obStepDoneTitle: "Wszystko gotowe!",
        obStepDoneBody: "Vorssaint czuwa już nad Twoim Makiem.",
        obDoneHint: "Szukaj ikony czarnej dziury na pasku menu w prawym górnym rogu ekranu.",
        obWhatsNewTitle: "Co nowego w tej wersji",
        obWhatsNewFallback: "To uaktualnienie zawiera najnowsze poprawki i ulepszenia.",
        obLanguageUpdateTitle: "Teraz w Twoim języku",
        obLanguageUpdateBody: "Vorssaint obsługuje teraz wiele języków. Wybierz ten, którego chcesz używać; możesz go zmienić w dowolnym momencie w Ustawieniach.",
        obPurposeTitle: "Co Cię tu sprowadza?",
        obPurposeBody: "Wybierz gotową konfigurację lub wskaż dokładnie to, z czego chcesz korzystać.",
        obPurposeSkip: "Możesz dodać lub usunąć funkcje w dowolnym momencie w Ustawieniach.",

        tabMonitor: "Monitor",
        monitorMenuBarSection: "Na pasku menu",
        monitorMenuBarCaption: "Wybierz, co ma być widoczne obok ikony na pasku menu.",
        monitorCombineTemperatures: "Połącz użycie i temperaturę",
        monitorCombineTemperaturesCaption: "Gdy włączone jest użycie oraz temperatura dla tego samego elementu, wyświetlaj je w jednym bloku.",
        monitorSeparateMenuBarMetrics: "Rozdziel wskaźniki na osobne elementy",
        monitorSeparateMenuBarMetricsCaption: "Rozdziela aktywne bloki na pasku menu, zachowując łączenie użycia i temperatury, gdy ta opcja jest włączona.",
        monitorNetworkUploadFirst: "Wysyłanie nad pobieraniem",
        monitorShowCPU: "CPU",
        monitorShowMemory: "Pamięć",
        monitorShowNetwork: "Sieć",
        monitorShowPowerLabel: "Zasilanie",
        monitorIntervalLabel: "Odświeżaj co",
        monitorInterval1: "1 sekunda",
        monitorInterval2: "2 sekundy",
        monitorInterval5: "5 sekund",
        monitorPanelSection: "W panelu",
        panelNavigationMode: "Nawigacja w panelu według sekcji",
        panelNavigationCaption: "Wyświetla jedną sekcję naraz. Wybierz „Lista”, aby widzieć wszystko na jednej przewijanej karcie.",
        panelFooterSections: "Sekcje",
        panelFooterList: "Lista",
        betaBadge: "BETA",
        betaFeatureWarning: "Wersja beta. Mogą wystąpić błędy.",

        networkSection: "Sieć",
        networkIPAddresses: "Adresy IP",
        networkLocalIP: "Lokalny adres IPv4",
        networkDownload: "Pobieranie",
        networkUpload: "Wysyłanie",
        networkThisSession: "Bieżąca sesja",
        networkMeasuring: "Mierzenie…",
        networkApps: "Aplikacje korzystające z sieci",
        networkAppsIdle: "Żadna aplikacja nie korzysta teraz z sieci",

        diskSection: "Dyski",
        diskUsed: "zajęte",
        diskFree: "wolne",
        diskMenuBarStyleLabel: "Wyświetlanie dysku",
        diskMenuBarUsedPercentage: "Procent zajętego miejsca",
        diskMenuBarAvailableSpace: "Dostępne miejsce",
        diskMenuBarUsedSpace: "Zajęte miejsce",
        diskAvailable: "dostępne",
        diskPurgeable: "do wyczyszczenia",
        diskInternal: "Wewnętrzny",
        diskExternal: "Zewnętrzny",
        diskSelect: "Wybierz dysk",
        diskRead: "Odczyt",
        diskWrite: "Zapis",
        diskSMARTStatus: "Stan",
        diskSMARTUnavailable: "Funkcja S.M.A.R.T. jest niedostępna dla tego dysku",
        diskTotalRead: "Łącznie odczytano",
        diskTotalWritten: "Łącznie zapisano",
        diskTemperature: "Temperatura",
        diskHealth: "Kondycja",
        diskPowerCycles: "Cykle zasilania",
        diskPowerOnHours: "Godziny pracy",
        diskUnsafeShutdowns: "Niebezpieczne wyłączenia",
        diskMediaErrors: "Błędy nośnika",
        diskEject: "Wysuń",
        diskEjectAll: "Wysuń wszystko",
        diskEjecting: "Wysuwanie…",
        diskReadyToRemove: "Można bezpiecznie odłączyć",
        diskEjectFailed: "Nie udało się wysunąć",
        diskProtectionCaption: "Wysuń przed odłączeniem.",
        diskNoExternal: "Brak dysków zewnętrznych do wysunięcia.",
        diskOpenInFinder: "Otwórz",
        diskStorageSettings: "Pamięć masowa",
        diskNoDisks: "Nie znaleziono podłączonych dysków.",

        powerSection: "Zasilanie",
        powerSystem: "System",
        powerAdapter: "Zasilacz",
        powerBattery: "Bateria",
        powerCharging: "Ładowanie",
        powerOnBattery: "Zasilanie z baterii",
        powerPluggedIn: "Podłączony do zasilania",
        powerUnavailable: "Wskaźniki zasilania są niedostępne na tym Macu",
        powerAdapterMaxFormat: "maks. %@",
        monitorShowGPU: "GPU",
        monitorShowCPUTemperature: "Temperatura CPU",
        monitorShowGPUTemperature: "Temperatura GPU",
        monitorShowBatteryTemperature: "Temperatura baterii",
        monitorShowPeripheralBattery: "Bateria akcesoriów",
        peripheralBatteryNoDevices: "Nie znaleziono urządzeń",
        monitorGraphsSection: "Wykresy",
        monitorGraphsCaption: "Wybierz, które wskaźniki mają wyświetlać wykres w czasie.",

        updateBannerTitle: "Dostępne uaktualnienie",
        updateBannerAction: "Uaktualnij",
        obStepMenuBarTitle: "Wskaźniki na pasku menu",
        obStepMenuBarBody: "Wybierz, co ma się wyświetlać obok ikony. Powyższy podgląd aktualizuje się na bieżąco.",
        obStepMenuBarNote: "Nowość: moduły Sieć i Zasilanie oraz wykresy w panelu. Wszystko możesz dopasować później w menu Ustawienia › Monitor.",
        monitorMenuBarPresetLabel: "Styl",
        menuBarPresetReadable: "Czytelny",
        menuBarPresetDense: "Zwarty",
        menuBarSpacingLabel: "Odstępy na pasku menu",
        menuBarSpacingStandard: "Standardowe",
        menuBarSpacingCompact: "Kompaktowe",
        menuBarHideIconToggle: "Ukryj ikonę aplikacji, gdy wyświetlane są wskaźniki",
        menuBarHideIconCaption: "Ikona powróci automatycznie po ukryciu wskaźników z paska lub w przypadku powiadomienia (gotowe uaktualnienie lub wyciszony mikrofon).",
        monitorLabelStyleLabel: "Etykiety",
        menuBarLabelStyleCompact: "Kompaktowe",
        menuBarLabelStyleClassic: "Klasyczne",
        monitorMemoryStyleLabel: "Pokaż pamięć jako",
        monitorMemoryPressureDot: "Kropka obciążenia",
        memoryStyleDot: "Kropka",
        memoryStylePercent: "%",
        memoryStyleBoth: "Oba",
        systemUptime: "Działa od",
        batteryCharge: "Poziom naładowania",
        powerHealth: "Kondycja baterii",
        powerCycles: "cykli",
        speedTestRun: "Test prędkości",
        speedTestAgain: "Testuj ponownie",
        speedTestLatency: "Opóźnienie",
        speedTestTesting: "Testowanie…",
        speedTestFailed: "Test nie powiódł się",

        monitorShowInPanel: "Pokaż w panelu",
        disclosureExpanded: "Rozwinięte",
        disclosureCollapsed: "Zwinięte",
        panelHideItem: "Ukryj w panelu",
        panelShowItem: "Pokaż w panelu",
        panelHiddenItem: "Ukryte",
        monitorItemUptime: "Czas pracy",
        monitorItemNetSpeed: "Bieżąca prędkość",
        monitorItemNetTotals: "Podsumowanie sesji",
        monitorItemNetTest: "Test prędkości",
        monitorItemDiskUsage: "Użycie dysku",
        monitorItemDiskActivity: "Bieżąca aktywność",
        monitorItemDiskSMART: "SMART",
        monitorItemDiskProtection: "Ochrona dysków zewnętrznych",
        monitorItemDiskTools: "Narzędzia",
        monitorPanelConfigHint: "Rozwiń blok, aby wybrać, co ma wyświetlać.",
        monitorOrderHint: "Przeciągnij, aby zmienić kolejność sekcji panelu, i użyj ikony oka, aby pokazać lub ukryć każdą z nich.",
        obStepPanelTitle: "Zawartość panelu",
        obStepPanelBody: "Rozwiń każdy blok i wybierz dokładnie to, co ma się pojawiać po kliknięciu ikony.",
        obStepPanelNavigationTitle: "Panel z podziałem na sekcje",
        obStepPanelNavigationBody: "Panel może teraz wyświetlać jedną sekcję naraz. W Ustawieniach możesz przełączać się między sekcjami a listą.",

        cleaningMenuItem: "Tryb czyszczenia",
        utilitiesSection: "Narzędzia",
        quickControlsSection: "Sterowanie",
        panelCategoryWindows: "Okna",
        panelCategoryInput: "Mysz i klawiatura",
        panelCategoryFiles: "Pliki",
        windowMaximizeName: "Maksymalizuj okna",
        windowMaximizeCaption: "Zielony przycisk maksymalizuje okno bez tworzenia kolejnego biurka.",
        windowMaximizeActiveNow: "Zastępowanie zielonego przycisku jest aktywne",
        windowMaximizeNeedsAccessibility: "Wymaga Dostępności do działania.",
        keyDebounceName: "Eliminacja drgań (debounce)",
        keyDebounceEnable: "Filtruj powtórzone naciśnięcia klawiszy",
        keyDebounceCaption: "Filtruje bardzo szybkie powtórzone naciśnięcia klawiszy.",
        keyDebounceActiveNow: "Filtr jest aktywny",
        keyDebounceGlobalWindow: "Globalne okno czasowe",
        keyDebouncePerKeySection: "Konkretne klawisze",
        keyDebouncePerKeyCaption: "Wartości dla pojedynczych klawiszy zastępują okno globalne. Użyj 0 ms, aby wyłączyć filtrowanie danego klawisza.",
        keyDebounceKeyLabel: "Klawisz",
        keyDebounceWindowLabel: "Okno czasowe",
        keyDebounceAddKey: "Dodaj klawisz",
        keyDebounceNoOverrides: "Brak skonfigurowanych konkretnych klawiszy.",
        keyDebounceRemoveKey: "Usuń klawisz",
        cleaningPanelCaption: "Blokuje klawiaturę, aby umożliwić jej bezpieczne czyszczenie.",
        cleaningOverlayTitle: "Klawiatura zablokowana do czyszczenia",
        cleaningOverlaySubtitle: "Naciśnij Escape 5 razy, aby odblokować",
        cleaningOverlayUnlock: "Odblokuj",
        cleaningOverlayMouseHint: "Mysz i gładzik nadal działają",
        cleaningKeepScreenVisibleToggle: "Pozostaw ekran widoczny",
        cleaningKeepScreenVisibleCaption: "Wyświetla dyskretny wskaźnik w rogu ekranu zamiast wygaszania zawartości.",
        cleaningStartNow: "Zablokuj klawiaturę teraz",
        cleaningNeedsAxTitle: "Wymagana Dostępność",
        cleaningNeedsAxBody: "Aby bezpiecznie zablokować klawiaturę, Vorssaint potrzebuje uprawnienia Dostępność. Przyznaj je w Ustawieniach systemowych i spróbuj ponownie.",

        tabSupport: "Wsparcie",
        shortcutsPageCaption: "Edytuj wszystkie skróty globalne funkcji zainstalowanych na tym Macu. Nieaktywne skróty pozostają zapisane, ale nie działają.",
        shortcutsPageTitle: "Skróty klawiszowe",
        settingsSearchPlaceholder: "Szukaj w Ustawieniach",
        donateHeading: "Pomóż Vorssaint dalej się rozwijać",
        donateMessage: "Vorssaint jest darmowy, niezależny i tworzony w moim wolnym czasie. Jeśli chcesz wesprzeć go finansowo, Buy Me a Coffee bezpośrednio pomaga mi rozwijać projekt.",
        donateButton: "Wesprzyj na Buy Me a Coffee",
        donateThanks: "Dziękuję, że tu jesteś. 🖤",
        supportIntroTitle: "Pomóż Vorssaint dalej się rozwijać",
        supportIntroMessage: "Jeśli chcesz wesprzeć rozwój finansowo, Buy Me a Coffee jest jedynym miejscem, gdzie możesz to zrobić.",
        supportIntroStarButton: "Oznacz Vorssaint gwiazdką na GitHubie",
        supportIntroStarMessage: "Wsparcie finansowe nie jest w żaden sposób oczekiwane. Gwiazdka na GitHubie pomaga innym odkryć Vorssaint i ma realny wpływ na rozwój aplikacji.",
        supportIntroCoffeeButton: "Wesprzyj na Buy Me a Coffee",
        supportIntroLaterButton: "Nie teraz",
        supportIntroDoneButton: "Gotowe",
        discordIntroTitle: "Społeczność Vorssaint na Discordzie dopiero startuje",
        discordIntroMessage: "Społeczność Vorssaint jest nowa i wciąż powstaje. Dołącz wcześniej, aby poznać innych użytkowników i pomóc budować przyjazne miejsce wokół aplikacji.",
        discordIntroJoinButton: "Dołącz do społeczności na Discordzie",
        communityIntroTitle: "Zobacz nowości przed wszystkimi",
        communityIntroMessage: "Osoby obserwujące mnie na X widziały wiele zmian z tej aktualizacji przed wszystkimi. Publikuję tam zapowiedzi tego, co nadchodzi, i pokazuję, jak to działa – dzięki czemu znasz podstawy, zanim aktualizacja zostanie wydana. Zaobserwuj i zobacz, co pojawi się wkrótce!",
        communityIntroFollowButton: "Obserwuj @vorssaint na X",
        homebrewOfficialIntroTitle: "Oficjalny pakiet Homebrew",
        homebrewOfficialIntroMessage: "Vorssaint można teraz zainstalować bezpośrednio z oficjalnego katalogu Homebrew.",
        homebrewOfficialIntroInstallLabel: "Nowa instalacja",
        homebrewOfficialIntroMigrationTitle: "Używasz starego repozytorium (tap)?",
        homebrewOfficialIntroMigrationMessage: "Wystarczy raz usunąć stary tap. Aplikacja i Twoje ustawienia pozostaną nienaruszone.",
        homebrewOfficialIntroCopyButton: "Kopiuj polecenie",
        updateShowcaseTitle: "Co nowego w 3.1.4",
        updateShowcaseMessage: "Zobacz krótkie podsumowanie najważniejszych nowości w tej aktualizacji.",
        updateShowcaseUnavailable: "Wideo nie mogło zostać teraz załadowane. Możesz kontynuować bez niego.",
        updateShowcaseRestart: "Odtwórz od nowa",
        showMenuBarIcon: "Pokaż ikonę na pasku menu",
        menuBarIconStillHiddenTitle: "Ikona jest nadal ukryta",
        menuBarIconStillHiddenBody: "Ikona została odświeżona, ale system macOS nie przydzielił jej widocznego miejsca. Pasek menu jest prawdopodobnie przepełniony: usuń niektóre ikony z paska (lub zamknij programy z długim menu) i spróbuj ponownie.",
        menuBarIconManagerHintFormat: "%@ jest uruchomiony i może ukrywać ikonę w swojej zwiniętej sekcji. Poszukaj tam aplikacji Vorssaint lub ustaw w %@, aby ikona Vorssaint była zawsze widoczna.",
        menuBarIconDisallowedBody: "System macOS blokuje wyświetlanie Vorssaint na pasku menu. Otwórz Ustawienia systemowe › Pasek menu, znajdź Vorssaint na liście aplikacji i włącz „Pozwalaj na pasku menu”. Ikona pojawi się natychmiast po włączeniu.",
        shortcutRecording: "Naciśnij nowy skrót",
        shortcutReset: "Przywróć domyślny",
        shortcutNone: "Brak",
        shortcutClear: "Usuń skrót",
        shortcutInvalid: "Użyj co najmniej jednego klawisza Control, Option lub Command wraz ze znakiem.",
        shortcutPressKeys: "Naciśnij skrót",
        shortcutEscapeHint: "Escape anuluje.",
        shortcutDeleteHint: "Delete usuwa.",
        shortcutNotCaptured: "Nie zarejestrowano skrótu. Ta kombinacja jest już używana przez system macOS lub inną aplikację. Wybierz inną.",
        shortcutConflictFormat: "Ten skrót jest już używany przez %@.",
        shortcutTakeOverOffer: "System macOS używa %@ dla jednego ze swoich skrótów.",
        shortcutTakeOverAction: "Przejmij, gdy Vorssaint jest uruchomiony",
        shortcutTakeOverCaption: "System macOS odzyskuje swój skrót za każdym razem, gdy Vorssaint nie działa lub ta funkcja jest wyłączona.",
        shortcutTakeOverDismiss: "Nie przejmuj",
        shortcutUnavailable: "System macOS odrzucił ten skrót. Wybierz inny.",
        shelfShortcutToggle: "Przełączaj półkę skrótem",
        switcherUsageHintFormat: "Przytrzymaj %@, aby nawigować; puść, aby przejść do okna. Shift lub ← cofa; W zamyka okno; Q zamyka program; Esc anuluje.",
        musicBlockSection: "Klawisze multimedialne",
        musicBlockTitle: "Zablokuj samoczynne otwieranie aplikacji Muzyka",
        musicBlockCaption: "Blokuje otwieranie aplikacji Muzyka po wykryciu klawisza multimedialnego. Wymaga dostępu do Dostępności. Polecenia ze słuchawek bez wykrytego naciśnięcia klawisza pozostają nienaruszone.",
        musicBlockUnavailable: "Ta ochrona jest w tej chwili niedostępna. Wyłącz ją i włącz ponownie, aby spróbować jeszcze raz.",
        musicBlockReplacementLabel: "Otwieraj w zamian",
        musicBlockReplacementNone: "Brak",
        musicBlockReplacementBlocked: "Aplikacje Muzyka i iTunes są blokowane, więc nie mogą być otwierane w zamian. Wybierz inną aplikację.",
        musicBlockChooseApp: "Wybierz aplikację…",
        musicBlockPlayReplacement: "Rozpocznij odtwarzanie po otwarciu aplikacji zamiennej",
        cleanerName: "Narzędzie czyszczenia",
        cleanerIntroTitle: "Wyczyść swojego Maca",
        cleanerIntroCaption: "Skanuje w poszukiwaniu pozostałości po odinstalowanych aplikacjach, pamięci podręcznej, dzienników i zawartości Kosza. Najpierw wszystko sprawdzisz, a usuwane rzeczy trafiają do Kosza.",
        cleanerScan: "Skanuj",
        cleanerScanning: "Skanowanie…",
        cleanerCleaning: "Czyszczenie…",
        cleanerCatLeftovers: "Pozostałości po odinstalowanych aplikacjach",
        cleanerCatLoginItems: "Osierocone elementy logowania",
        cleanerCatCaches: "Pamięć podręczna",
        cleanerCatLogs: "Dzienniki i logi",
        cleanerCatDeveloper: "Pliki tymczasowe dewelopera",
        cleanerCatTrash: "Kosz",
        cleanerLeftoversNote: "Znalezione podczas analizy i domyślnie odznaczone. Sprawdź ścieżkę przed zaznaczeniem.",
        cleanerLoginItemsNote: "Pozycja w sekcji Rzeczy i rozszerzenia otwierane podczas logowania zniknie po ponownym uruchomieniu Maca.",
        cleanerTrashNote: "Opróżnienie Kosza jest nieodwracalne.",
        cleanerCatDeviceBackups: "Kopie zapasowe iPhone’a",
        cleanerDeviceBackupsCaption: "Stare kopie zapasowe iPhone’a i iPada zajmują dużo miejsca, które macOS oznacza jako Inne. Usuń tylko te, których już nie potrzebujesz; nowa kopia zostanie utworzona po ponownym podłączeniu urządzenia.",
        cleanerCatScreenshots: "Zapomniane zrzuty ekranu",
        cleanerScreenshotsCaptionFormat: "Zrzuty ekranu nieotwierane od %d dni, które nadal mają oryginalną nazwę i folder z macOS. Przemianowane lub przeniesione nigdy się tu nie pojawią.",
        cleanerScreenshotsSettingCaption: "Skanowanie wyświetla nieotwierane od tylu dni zrzuty ekranu (domyślnie odznaczone) wraz z ich łącznym rozmiarem.",
        cleanerScreenshotsAfterFormat: "Po %d dniach",
        cleanerNothingFound: "Brak plików do wyczyszczenia. Twój Mac jest uporządkowany.",
        cleanerClean: "Wyczyść",
        cleanerDoneNote: "Elementy zostały przeniesione do Kosza i można je stamtąd odzyskać.",
        cleanerAgain: "Skanuj ponownie",
        cleanerRevealInFinder: "Pokaż w Finderze",
        cleanerPanelCaption: "Pozostałości po aplikacjach, pamięć podręczna i dzienniki",
        cleanerSafeSection: "Bezpieczne czyszczenie",
        cleanerOptionalSection: "Opcjonalne, przejrzyj najpierw",
        cleanerCatOtherCaches: "Inna pamięć podręczna",
        cleanerCachesCaption: "Pliki tymczasowe, które programy odbudowują automatycznie.",
        cleanerLogsCaption: "Stare dzienniki diagnostyczne i raporty błędów.",
        cleanerDeveloperCaption: "Pozostałości po kompilacjach Xcode i symulatorach.",
        cleanerLoginItemsCaption: "Wpisy startowe pozostawione przez programy, które już nie istnieją.",
        cleanerLeftoversCaption: "Pliki pozostawione przez odinstalowane programy.",
        cleanerOtherCachesCaption: "Bezpieczne do usunięcia, nic się nie uszkodzi. Programy mogą otworzyć się raz nieco wolniej, a zawartość offline (np. pobrana muzyka) zostanie pobrana ponownie.",
        cleanerCleanSizeFormat: "Wyczyść %@",
        cleanerScheduleTitle: "Automatyczne czyszczenie",
        cleanerScheduleOff: "Wyłączone",
        cleanerScheduleDaily: "Codziennie",
        cleanerScheduleWeekly: "Co tydzień",
        cleanerScheduleCaption: "Samoczynnie czyści tylko bezpieczną część o wybranej porze i przenosi wszystko do Kosza.",
        cleanerScheduleLastFormat: "Ostatnie automatyczne czyszczenie zwolniło %@.",
        cleanerAutoNotificationFormat: "Zwolniono %@ i przeniesiono do Kosza.",
        cleanerScheduleNextFormat: "Następne czyszczenie: %@.",
        cleanerScheduleRanFormat: "Ostatnie automatyczne czyszczenie: %@.",
        cleanerScheduleNotifyToggle: "Powiadom po zakończeniu",
        cleanerNotifDenied: "Powiadomienia dla Vorssaint są wyłączone w Ustawieniach systemowych.",
        cleanerNotifOpenSettings: "Otwórz Ustawienia powiadomień…",
        launchAtLoginNeedsApplications: "Program jest uruchomiony z miejsca, które nie pozwala na otwieranie podczas logowania. Przeciągnij Vorssaint do folderu Aplikacje, otwórz go stamtąd i włącz tę opcję ponownie.",
        launchAtLoginNeedsApproval: "Rzecz logowania jest zarejestrowana, ale nadal wyłączona w Ustawieniach systemowych. Otwórz Ustawienia systemowe › Ogólne › Rzeczy i rozszerzenia otwierane podczas logowania i włącz Vorssaint w sekcji Otwieraj podczas logowania.",
        ocrRemoveLineBreaksToggle: "Usuwaj podziały wierszy w rozpoznanym tekście",
        ocrRemoveLineBreaksCaption: "Łączy linie w jeden ciągły akapit podczas kopiowania tekstu z ekranu.",
        ocrQRToggle: "Automatycznie wykrywaj kody QR",
        ocrQRCaption: "Jeśli obszar zawiera kod QR, jego treść jest wyświetlana, aby ją skopiować lub otworzyć.",
        ocrQRCopied: "Skopiowano zawartość kodu QR",
        qrResultTitle: "Kod QR",
        qrResultCopy: "Kopiuj",
        qrResultOpen: "Otwórz łącze",
        highlightsTitle: "Najważniejsze nowości",
        highlightsTitleClipboardRedesign: "Nowy wygląd historii schowka",
        highlightsTitleWindowLayout: "Rozmieszczanie okien",
        highlightsTitleQuitProtection: "Ochrona przed przypadkowym zamknięciem",
        highlightsTitleRecorderBlur: "Rozmywanie poufnych danych w nagraniach",
        highlightsCaptionDockPreview: "Podgląd Docka działa teraz przy włączonym powiększeniu Docka",
        highlightsCaptionScreenshot: "Narzędzie zrzutów ekranu zyskało lupę pikselową i natychmiastowe odczytywanie kodów QR.",
        highlightsCaptionSnippetLibrary: "Wyszukiwalne menu fragmentów tekstu wkleja dowolny szablon wprost pod kursorem.",
        highlightsCaptionCapturePalette: "Jeden skrót otwiera teraz pływającą paletę dla zrzutów, nagrań, tekstu z ekranu i próbnika kolorów.",
        highlightsCaptionClipboardRedesign: "Historia schowka otwiera się teraz jako zwięzła paleta z przejrzystymi wierszami i podglądem na żądanie do czytania i edycji.",
        highlightsCaptionWindowLayout: "Rozmieszczaj okna za pomocą pierścienia kierunkowego ze skrótem i wskaźnikiem lub przeciągaj do krawędzi ekranu.",
        highlightsCaptionQuitProtection: "Unikaj przypadkowego zamykania programów lub okien dzięki przytrzymaniu, podwójnemu naciśnięciu lub dodatkowemu klawiszowi.",
        highlightsCaptionRecorderBlur: "Ukrywaj prywatne dane, hasła i poufne fragmenty w dowolnym miejscu nagranego wideo przed udostępnieniem lub eksportem.",
        highlightsConfigure: "Konfiguruj",
        highlightsTry: "Wypróbuj",
        highlightsSeeAll: "Zobacz wszystkie zmiany",
        switcherCurrentSpaceOnly: "Pokazuj tylko bieżące biurko",
        switcherCurrentSpaceOnlyCaption: "Wyświetla tylko okna z biurka, na którym się znajdujesz. Wybór okna nigdy nie przeniesie Cię na inne biurko.",
        shelfFileMissing: "Plik już nie istnieje",
        previewSizeSmall: "Mała",
        mixerSoundEffectsOutputTitle: "Dźwięki systemowe",
        mixerSoundEffectsOutputTooltip: "Wybierz, gdzie mają być odtwarzane alerty i efekty dźwiękowe",
        monitorOpenActivityMonitor: "Otwórz Monitor aktywności",
        dockClickHide: "Kliknij ikonę w Docku, aby ukryć program",
        dockClickHideCaption: "Aktywny program ukrywa się po kliknięciu jego ikony w Docku. Kliknij ponownie, aby go przywrócić.",
        monitorMemoryMetricLabel: "Mierz pamięć jako",
        memoryMetricUsed: "Użyta pamięć",
        memoryMetricApp: "Pamięć programów",
        keepAwakeRightClickToggle: "Kliknij prawym przyciskiem ikonę w pasku menu, aby przełączyć zapobieganie usypianiu",
        keepAwakeRightClickToggleCaption: "Zastępuje menu kontekstowe po kliknięciu prawym przyciskiem myszy.",
        urlCleanerRulesTitle: "Reguły czyszczenia",
        urlCleanerRulesCaption: "Witryny dołączają te parametry do swoich linków, aby śledzić źródło kliknięcia. Gdy parametr jest włączony, zostaje usunięty podczas czyszczenia łącza; gdy wyłączony, pozostaje. Dodane parametry można usunąć.",
        urlCleanerRulesCoverageCaption: "Lista obejmuje różne ścieżki udostępniania witryny (strona www, aplikacja, pokój na żywo), dlatego jest długa; prawdziwy link zawiera zwykle od dwóch do czterech parametrów.",
        urlCleanerRulesAllSites: "Wszystkie witryny",
        urlCleanerRulesCountSingular: "1 parametr",
        urlCleanerRulesCountPluralFormat: "Parametry: %d",
        urlCleanerRulesAddSite: "Dodaj witrynę",
        urlCleanerRulesParameterPlaceholder: "Nazwa parametru",
        urlCleanerRulesMatchCaption: "Wpisz nazwę po lewej stronie znaku = , np. utm_source. Dopasowana reguła usuwa ten jeden parametr z linku, pozostawiając resztę bez zmian.",
        urlCleanerRulesAddButton: "Dodaj",
        urlCleanerRulesRemoveButton: "Usuń nazwę",
        urlCleanerRulesRemoveSiteButton: "Wyłącz wszystkie reguły dla tej witryny",
        urlCleanerRemovedFormat: "Usunięto: %@",
        switcherSearchPin: "Przypinaj wyszukiwanie klawiszem S",
        switcherSearchPinCaption: "Klawisz S rozpoczyna wyszukiwanie i przypina przełącznik w stanie otwartym. Dzięki temu pisanie nie generuje znaków specjalnych, gdy Twój skrót używa ⌥, a wyszukiwanie rozpoczynające się od liter Q lub W nie zamyka przez pomyłkę okna ani programu.",
        invertVerticalScroll: "Odwróć przewijanie pionowe",
        invertHorizontalScroll: "Odwróć przewijanie poziome",
        scrollHorizontalName: "Przewijaj w poziomie z klawiszem modyfikatora",
        scrollHorizontalModifierLabel: "Klawisz modyfikatora",
        scrollHorizontalCommandKey: "Command",
        scrollHorizontalCaption: "Przytrzymaj wybrany klawisz, aby pionowym kółkiem myszy przewijać w poziomie. Inne skróty pozostają bez zmian.",
        switcherShowShortcutHints: "Pokazuj podpowiedzi skrótów",
        switcherShowShortcutHintsCaption: "Wyświetla skróty klawiszowe dla aplikacji i okien pod ich ikonami.",
        uninstallerHomebrewPackageFormat: "%@ zostanie także usunięty z Homebrew.",
        shelfEdgeToggle: "Wysuwaj przy krawędzi ekranu",
        shelfEdgeCaption: "Przeciągnij plik w stronę krawędzi ekranu, aby wysunąć półkę. Upuść go tam lub cofnij kursor, aby schować półkę.",
        focusFollowsMouseName: "Aktywacja pod wskaźnikiem (focus follows mouse)",
        focusFollowsMouseCaption: "Aktywuje i przenosi na wierzch okno pod wskaźnikiem po krótkiej pauzie.",
        focusFollowsMouseDelay: "Opóźnienie aktywacji",
        switcherMinimizedPlacementLabel: "Zminimalizowane okna",
        switcherTreatHiddenAppsLikeMinimized: "Traktuj ukryte aplikacje jak zminimalizowane okna",
        switcherMinimizedPlacementNormal: "Domyślna kolejność",
        switcherMinimizedPlacementEnd: "Umieść na końcu",
        switcherMinimizedPlacementHidden: "Ukryj",
        switcherShowFullscreenWindows: "Pokazuj okna pełnoekranowe",
        switcherScreenPlacementLabel: "Wyświetlaj na",
        switcherScreenPlacementPointer: "Ekranie ze wskaźnikiem",
        switcherScreenPlacementMenuBar: "Ekranie z paskiem menu",
        switcherScreenPlacementActiveWindow: "Ekranie z aktywnym oknem",
        switcherScreenPlacementCaption: "Na którym wyświetlaczu ma się otwierać przełącznik, gdy podłączonych jest kilka ekranów.",
        switcherCurrentDisplayOnly: "Pokazuj tylko bieżący ekran",
        switcherCurrentDisplayOnlyCaption: "Wyświetla tylko okna z ekranu pod wskaźnikiem. Jeśli na tym ekranie nie ma okien, przełącznik się nie otworzy.",
        smoothScrollResponseLabel: "Czas reakcji",
        smoothScrollCoastLabel: "Wybieg",
        mouseAccelerationName: "Wyłącz akcelerację myszy",
        mouseAccelerationCaption: "Usuwa akcelerację wskaźnika dla podłączonych myszy. Poprzednie ustawienie powróci po wyłączeniu tej funkcji lub zamknięciu Vorssaint.",
        linearScrollName: "Liniowe przewijanie",
        linearScrollCaption: "Każdy skok kółka myszy przewija o dokładnie taką samą odległość, bez względu na szybkość obracania. Nie dotyczy gładzika.",
        linearScrollLinesLabel: "Wiersze na krok",
        shelfClearOnClose: "Wyczyść przy zamknięciu",
        shelfClearOnCloseCaption: "Opróżnia półkę tylko po kliknięciu jej przycisku zamknięcia. Automatyczne ukrywanie i zwijanie zachowują elementy.",
        shelfShortcutFinderSelection: "Dodawaj zaznaczenie z Findera skrótem",
        shelfShortcutFinderSelectionCaption: "Gdy Finder jest na pierwszym planie, skrót otwiera półkę z już dodanymi zaznaczonymi plikami. Jeśli nic nie zaznaczono, otwiera się jak zwykle."
    )
}
